### ISSUE TITLE
Hiding menu bar with F10 disables "Ctrl + " shortcuts

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#1002]
When I hide the tools Menu (File, Edit, View etc.) by pressing F10 key (images attached depict transition), I lose the ability of making in-program commands involving keyboard shortcuts.
E.g.: Ctrl+S, Ctrl+Z, Ctrl+E, Ctrl+C will not produce anything
Whereas other system-wide shortcuts (E.g. Alt-tab) still work fine.
App is Xournal 1.0.9 built 20/03, on Elementary 5.0 (Ubuntu 18.04 based)

![Screenshot from 2019-03-21 17 17 04](https://user-images.githubusercontent.com/16632292/54767662-eb6b5600-4bfd-11e9-9fe7-1d92e4b7f4bd.png)
![Screenshot from 2019-03-21 17 22 01](https://user-images.githubusercontent.com/16632292/54767670-f0c8a080-4bfd-11e9-9c4c-edf95f85ea68.png)

**Comment by peetCreative** [comment]
This is probably do to that the shortcuts are bound to the elements in this toolbar.
This issue should be resolved #803

**Comment by LittleHuba** [comment]
This will be solved by #919

**Comment by bhennion** [comment]
Closing as I think it's been resolved.
