### ISSUE TITLE
Prefs setting for AddVertical/Horizontal space

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1005]
@GregDMeyer has requested this in comments to fixed issue #964 
"One more comment--the amount of extra space seems to be smaller now. I'm not sure this is a big deal, but I was using this feature because it's more comfortable for me to write near the top of my display (so that my palm can rest comfortably on the flat lower part). I can't scroll the bottom of the page up to the top of the view any more. (Maybe allowing user adjustment of the amount of extra space would be a good solution)."

**Comment by LittleHuba** [comment]
UI-Elements added via #1024 but not yet functional.
