### ISSUE TITLE
Crash when using middle mouse button and drag out of window

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1007]
When:
  Using the middle mouse button as hand tool ( but not when selecting the hand tool and using left mouse button ).
  Drag the mouse out of the window. Crash

** (xournalpp:25537): WARNING **: XojTypeCheck failed: NULL xournalpp/src/gui/inputdevices/NewGtkInputDevice.cpp:64
*** Program received signal SIGSEGV (Segmentation fault) ***

Tested on Linux Mint.

**Comment by theKlanc** [comment]
Also happening to me when using a stylus button, I'll try to fix it.

**Comment by gad-o** [comment]
I had to activate "gtk workaround" for using my graphic tablet. 
When relase hand tool(both of mouse and tablet) crash with this backtrace

[scrollreleasecrash.log](https://github.com/xournalpp/xournalpp/files/3047657/scrollreleasecrash.log)

**Comment by Epse** [comment]
I get this same issue when mapping hand tool to a pen button. As soon as my cursor leaves the drawing area (e.g. onto the buttons up top, which happens often) the entire app crashes.

**Comment by LittleHuba** [comment]
Could you test this with the new input system #1070? I'm unable to reproduce it on my platform with the old system. Hence I'm unsure whether this persists.

**Comment by JJones780** [comment]
When I enable the new input system the middle mouse button no longer turns into a hand tool so I can't test for the crash.
If I go back to the old input system I can mmb the hand and get the crash.

**Comment by gad-o** [comment]
> Could you test this with the new input system #1070? I'm unable to reproduce it on my platform with the old system. Hence I'm unsure whether this persists.

If i only check _cbNewInputSystem_, i can't get the hand tool.

After also checking _cbNewInputSystemTPCButton_ my problem fixed. I'm not getting the crash with hand tool when go outside of drawing area.

**Comment by gad-o** [comment]
> Now drawing should work with secondary mouse buttons. Please try again only using _cbNewInputSystem_.

Tried with 928b7a6 But without cvNewInputSystemTPCButton checked, secondary mouse buttons not working

**Comment by LittleHuba** [comment]
@gad-o this should be fixed now.

**Comment by JJones780** [comment]
I can now get the hand tool on middle mouse button and no longer get the crash. 
Good job!
