### ISSUE TITLE
text tool does not position cursor precisely

### ISSUE THREAD

**Issue by medovina** [xournalpp/xournalpp#1008]
I'm running Xournal++ on Ubuntu 19.04.

Here is a cursor positioning issue that has existed for years in Xournal, and is also present in Xournal++.  If you enable the text tool and click at a position where you want to type, the resulting text cursor does not appear exactly at the position of the mouse cursor - instead, it is below it.  This makes it difficult to annotate text fields in a PDF document that does not have fillable forms.

To illustrate this, here are some screenshots I captured.  I'm hovering the mouse cursor over a box where I'd like to enter some text:

![before_box](https://user-images.githubusercontent.com/673039/54876434-41afe300-4e10-11e9-9eaf-c2aaff2eddf1.png)

Now I click, and get a text cursor in the wrong position:

![after_box](https://user-images.githubusercontent.com/673039/54876435-4aa0b480-4e10-11e9-9816-c6f89cb4852f.png)

If I now start typing, the text will be positioned too low, below the box.

**Comment by andreasb242** [comment]
We should center the Text to the cursor...

**Comment by medovina** [comment]
Great, thanks for the quick fix - this bug has annoyed me for years!

**Comment by LittleHuba** [comment]
You're welcome! Happened to find this bug as annoying as you did!
