### ISSUE TITLE
pan prioritized over draw when using stylus

### ISSUE THREAD

**Issue by jaswon5791** [xournalpp/xournalpp#1014]
Recently (after a `pacman -Syyu` iirc, so probably something updated) I have been unable to get my stylus to work properly. Dragging the stylus along the screen will trigger the pan action instead of the pen draw action. For example, when only the vertical scroll bar is available, a vertical stroke of the pen will pan the page up/down, but a horizontal stroke will draw a pen stroke. When both scroll bars are visible (eg. zoomed into page), the stylus won't draw at all, just pan, unless it's held really still at first and then dragged. Checking `Input Device > GTK Touch / Scrolling workaround` allows the stylus to draw but this is only because the panning via touch is disabled.

`xinput list`:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ELAN0732:00 04F3:22E1 touch             	id=10	[slave  pointer  (2)]
⎜   ↳ ELAN0732:00 04F3:22E1 stylus            	id=11	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=14	[slave  pointer  (2)]
⎜   ↳ ELAN0732:00 04F3:22E1 eraser            	id=17	[slave  pointer  (2)]
```

`cat /usr/share/X11/xorg.conf.d/70-wacom.conf`:
```
...
# N-Trig Duosense Electromagnetic Digitizer
Section "InputClass"
	Identifier "Wacom N-Trig class"
	# MatchProduct "HID 1b96:0001|N-Trig Pen|N-Trig DuoSense"
	MatchProduct "04F3:22E1|HID 1b96:0001|N-Trig Pen|N-Trig DuoSense"
	MatchDevicePath "/dev/input/event*"
	Driver "wacom"
	Option "Button2" "3"
	Option "Raw Sample" "2"
EndSection
```

`pacman -Q | grep wacom`:
```
libwacom 0.32-1
xf86-input-wacom 0.36.1-1
```

**Comment by LittleHuba** [comment]
Please post the output of the following command:
`xinput list-props "ELAN0732:00 04F3:22E1 stylus"`
I assume your `Wacom Panscroll Threshold` is too low.

**Comment by jaswon5791** [comment]
```
Device 'ELAN0732:00 04F3:22E1 stylus':
	Device Enabled (150):	1
	Coordinate Transformation Matrix (152):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (276):	0
	Device Accel Constant Deceleration (277):	1.000000
	Device Accel Adaptive Deceleration (278):	1.000000
	Device Accel Velocity Scaling (279):	10.000000
	Device Node (273):	"/dev/input/event9"
	Wacom Tablet Area (283):	0, 0, 18360, 10580
	Wacom Rotation (284):	0
	Wacom Pressurecurve (285):	0, 0, 100, 100
	Wacom Serial IDs (286):	8929, 1, 2, 0, 0
	Wacom Serial ID binding (287):	0
	Wacom Pressure Threshold (288):	26
	Wacom Sample and Suppress (289):	2, 2
	Wacom Enable Touch (290):	0
	Wacom Hover Click (305):	1
	Wacom Enable Touch Gesture (291):	0
	Wacom Touch Gesture Parameters (292):	0, 0, 250
	Wacom Tool Type (293):	"STYLUS" (301)
	Wacom Button Actions (294):	"Wacom button action 0" (295), "Wacom button action 1" (296), "Wacom button action 2" (297), "None" (0), "None" (0), "None" (0), "None" (0), "Wacom button action 3" (298)
	Wacom button action 0 (295):	1572865
	Wacom button action 1 (296):	1572867
	Wacom button action 2 (297):	1572867
	Wacom button action 3 (298):	1572872
	Wacom Pressure Recalibration (306):	1
	Wacom Panscroll Threshold (299):	5200
	Device Product ID (274):	1267, 8929
	Wacom Debug Levels (300):	0, 0
```
I did try adjusting the Panscroll Threshold (originally it was 830), but this does not seem to affect my situation. I suppose one thing to note is that when the eraser button is held, the screen doesn't pan.

**Comment by LittleHuba** [comment]
Sorry for the long silence...
Could you provide me with further information?

Please follow the steps mentioned in https://github.com/xournalpp/xournalpp/issues/874#issuecomment-490258165

You may ignore the different drivers and DEs.

**Comment by LittleHuba** [comment]
Due to inactivity I'll close this issue. If the logs are posted we can reactivate it.
