### ISSUE TITLE
option to automatically export to pdf on every save

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1028]
WOW... I've been using xournal for almost a decade now. Every time I've looked at xournalpp, it seemed not quite prime-time ready, but have just built the latest version, and I'm on awe how far it's come. Congrats and thanks to all the developers!

Just a quick idea for an enhancement (something i've updated in my build of xournal). There could be an option where on every save, xournalpp automatically does an export to a pdf file with the same name. 
The use case is actually related to this https://github.com/xournalpp/xournalpp/issues/936 (in a way). 
I often have a pdf of the document I'm writing, open on a another machine (on a big screen). The pdf version of the document is synced (using, say, dropbox). Then on every save the pdf on my big screen gets an update of the latest version within a few seconds. Doing 'export to pdf', 'overwrite file', etc each time is cumbersome. An alternative would be to have a (optional?) separate button in the toolbar that would export-to-pdf the current version of the document - maybe that's a cleaner approach?

**Comment by LittleHuba** [comment]
We can implement that using a plugin. 
@andreasb242 is the API ready for that?

**Comment by andreasb242** [comment]
It should be possible with a new Button which does save and export, I'll have a look at it, but at the moment I have not much free time.

**Comment by LittleHuba** [comment]
The best solution but arguably also the most amount of work would be to introduce a signal channel, plugins can listen to.

**Comment by eliasrg** [comment]
@petergthatsme Until this feature gets implemented, a workaround is to use `entr`, something like `echo file.xoj | entr xournalpp file.xoj -p file.pdf`

**Comment by petergthatsme** [comment]
@eliasrg oh, good call! didn't realize xournalpp can create a pdf from command line (xournal didn't). This will work well - thanks.

**Comment by petergthatsme** [comment]
i'm closing this issue; it is unlikely to get implemented, and besides given that xournalpp can convert xopp to pdf files via the command line, it's not necessary. 
I've been doing that with inotifywait and it's working very well.

**Comment by LecJackS** [comment]
Using @eliasrg and @petergthatsme suggestion, this a simple script that waits for changes inside a folder directory (recursively) and saves a .pdf every time a .xopp is saved (in the same directory, with the same name, but different extension).

It's in my ~/.bashrc as a function, but maybe it's better to run it as a separate script.

```shell
# Auto save PDF for Xournal++
inot (){
    inotifywait -r -m --format '%w%f' -e CLOSE_WRITE ~/Parent-folder/ |
    while read file_path; do
        echo Convertig file to pdf: $f;
        xournalpp ${file_path} -p "${file_path%.*}.pdf";
        echo Saving done.
    done
}
```

Folder structure as example:
```shell
Parent-folder
 |- Theory
    |- Several .xopp files
 
 |- Practicum
    |- Several .xopp files

 |- Lab
    |- Several .xopp files

 |- Exercises
    |- Several .xopp files

```

**Comment by eliasrg** [comment]
To expand on @LecJackS's solution, I'll share the script that I use. If you call it as `convert-xoj-pdf watch A B` where `A` and `B` are directories, it listens for changes to `.xoj` or `.xopp` files in `A`, _including moved or deleted files_, and creates or deletes PDF files in `B` as necessary. You can also call `convert-xoj-pdf convert_all A B` to create any missing or out-of-date PDFs in `B` directly, or `convert-xoj-pdf clean A B` to delete any PDFs in `B` with no `.xoj` or `.xopp` counterpart in `A`.

Warning: This script deletes files! Be very careful. Don't store anything else in `B`, and definitely don't put `B` the same as `A`. While testing this script, I accidentally called it with the wrong arguments `A` and `B` and it started deleting all my PDF files, which I had to restore from backup. 

Nevertheless, it now works perfectly for me. I start it automatically with the following systemd user service `~/.config/systemd/user/convert-xoj-pdf.service`:

```ini
[Unit]
Description=Convert .xoj and .xopp files to pdf
After=multi-user.target

[Service]
Type=simple
ExecStart=%h/bin/convert-xoj-pdf watch %h/nextcloud %h/nextcloud/xoj-pdfs

[Install]
WantedBy=default.target
```

and it mirrors all my notes in `~/nextcloud` into `~/nextcloud/xoj-pdfs`. Here is the script:

```zsh
#!/usr/bin/env zsh

setopt NULL_GLOB

print_usage() {
    name="$(basename "$1")"
    print "Usage:"
    print "$name (watch | convert_all | clean) <source_dir> <output_dir>"
    print "$name --help"
}

new_path() {
    old_path="$1"
    rel_path="$(realpath --canonicalize-missing \
                                 --relative-to="$source_dir" "$old_path")"
    print "$output_dir/$rel_path"
}

pdf_path() {
    xoj_path="$1"
    new_path="$(new_path "$xoj_path")"
    print "${new_path%.(xoj|xopp)}.pdf"
}

fail_path() {
    pdf_path="$1"
    print "$pdf_path.fail"
}

convert() {
    xoj_path="$1"
    pdf_path="$(pdf_path "$xoj_path")"
    new_dirpath="$(dirname "$pdf_path")"
    fail_path="$(fail_path "$pdf_path")"

    print "Converting $xoj_path -> $pdf_path"
    # Create the directory if it does not exist
    mkdir --verbose --parents "$new_dirpath"
    if xournalpp --create-pdf "$pdf_path" "$xoj_path"; then
        # Delete a fail notice if it exists
        rm --force "$fail_path"
    else
        # Create a fail notice
        print >&2 "Conversion failed. Creating $fail_path"
        touch "$fail_path"
    fi
}

delete() {
    del_path="$1"
    del_dirpath="$(dirname "$del_path")"
    fail_path="$(fail_path "$del_path")"

    print "Deleting $del_path"
    rm "$del_path"
    # Delete a fail notice if it exists
    rm --force "$fail_path"
    # Try deleting the directory; only succeeds if it is empty
    rmdir --verbose --parents --ignore-fail-on-non-empty "$del_dirpath"
}

watch() {
    last_time=""
    last_event=""
    last_path=""

    inotifywait --monitor --recursive \
        --event modify --event delete --event move \
        --format "%T %e %w%f" \
        --timefmt "%s" \
        "$source_dir" |
    # This works even if the directory or filename contain spaces
    while read t event file_path
    do
        [[ "$t" == "$last_time"
        && "$event" == "$last_event"
        && "$file_path" == "$last_path"
        ]] && continue

        last_time="$t"
        last_event="$event"
        last_path="$file_path"

        [[ "$file_path" == (*.xoj|*.xopp) ]]; is_xoj=$(( !$? ))
        [[ -d "$file_path" ]]; is_dir=$(( !$? ))

        case "$event" in
        MODIFY | MOVED_TO)
            (( is_xoj )) && sleep 1s && convert "$file_path";;
        DELETE | MOVED_FROM)
            if (( is_xoj )); then
                pdf_path="$(pdf_path "$file_path")"
                [[ -e "$pdf_path" ]] && delete "$pdf_path"
            fi;;
        MOVED_TO,ISDIR)
            convert_all "$file_path"
            ;;
        MOVED_FROM,ISDIR)
            rm -r "$(new_path "$file_path")"
            ;;
        *)
            print >&2 "Unhandled event: $event $file_path";;
        esac
    done
}

convert_all() {
    subdir="$1"

    for xoj_path in "$subdir"/**/*.(xoj|xopp)
    do
        pdf_path="$(pdf_path "$xoj_path")"
        if [[ ! -e "$pdf_path" || "$pdf_path" -ot "$xoj_path" ]]; then
            convert "$xoj_path"
        fi
    done
}

clean() {
    subdir="$1"

    for pdf_path in "$subdir"/**/*.pdf
    do
        rel_path="$(realpath --canonicalize-missing \
                                 --relative-to="$output_dir" "$pdf_path")"
        xoj_path="$source_dir/${rel_path%.pdf}.xoj"
        xopp_path="$source_dir/${rel_path%.pdf}.xopp"
        if [[ ! -e "$xoj_path" && ! -e "$xopp_path" ]]; then
            print "Neither $xoj_path nor $xopp_path exist."
            delete "$pdf_path"
        fi
    done
}


case "$1" in
    --help)
        print_usage "$0";;
    watch|convert_all|clean)
        if (( $# == 3 )); then
            source_dir="$2"
            output_dir="$3"
        else
            print_usage "$0" >&2
            exit 1
        fi
        ;|
    watch)
        watch;;
    convert_all)
        convert_all "$source_dir";;
    clean)
        clean "$output_dir";;
    *)
        print_usage "$0" >&2
        exit 1;;
esac
```

**Comment by AnnaVd** [comment]
> Using @eliasrg and @petergthatsme suggestion, this a simple script that waits for changes inside a folder directory at `\home` (recursively) and saves a .pdf every time a .xopp is saved (in the same sub-directory, with the same name, but different extension).
> 
> It's in my `~/.bashrc` as a function, but maybe it's better to run it as a separate script.
> 
> ```shell
> # Auto save PDF for Xournal++
> inot (){
>     main_dir=~/Parent Folder/
>     # Wait for changes in ANY files inside directory
>     inotifywait -r -m --format '%w%f' -e CLOSE_WRITE "$main_dir" |
>         while read file_path; do
>             # Check file extension
>             if [[ "$file_path" =~ .*\.(xopp|xoj) ]]
>             then
>                 # Convert to pdf (overwrite if already exists)
>                 echo Converting file to pdf: ${file_path};
>                 xournalpp "${file_path}" -p "${file_path%.*}.pdf";
>                 echo Saving done.
>             fi
>         done
> }
> ```
> 
> Folder structure as example:
> 
> ```shell
> \home
>   |- Parent Folder
>     |- Theory
>       |- Several .xopp files
>  
>     |- Practicum
>       |- Several .xopp files
> 
>     |- Lab
>       |- Project 1
>           |- Several .xopp files
>       |- Project 2
>           |- Several .xopp files
> ```

Hey, I am very interested in using this script, but it doesn't seem to work on my machine... Is it using some packages I must install maybe ? (I'm on Ubuntu 20.04 LTS). Thanks a lot !

**Comment by rolandlo** [comment]
> Hey, I am very interested in using this script, but it doesn't seem to work on my machine... Is it using some packages I must install maybe ? (I'm on Ubuntu 20.04 LTS). Thanks a lot !

The script uses `inotifywait`, which you may not have installed. Just `sudo apt install inotify-tools`.

**Comment by AnnaVd** [comment]
> > Hey, I am very interested in using this script, but it doesn't seem to work on my machine... Is it using some packages I must install maybe ? (I'm on Ubuntu 20.04 LTS). Thanks a lot !
> 
> The script uses `inotifywait`, which you may not have installed. Just `sudo apt install inotify-tools`.

Done, but still not working :(
