### ISSUE TITLE
Select language in selfcompiled xournal++

### ISSUE THREAD

**Issue by msambg** [xournalpp/xournalpp#1036]
I compiled xournal++ myself, when I run it, it is english. 
Where can I get language support for german and how do I switch it?

**Comment by LittleHuba** [comment]
Xournal++ will automatically select your system locale. For that to work you need to install it using `sudo make install`.

**Comment by juniortruka** [comment]
Hey, LittleHba. 

What is the text file of the views in xournal ++ in the installation folder?

I want to edit it for my main language, thank you if it info (windows).
