### ISSUE TITLE
Setting the zoom level when hovering the slider and rotating the mouse wheel has no effect

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#1046]
Hi guys,

xournalpp just hit Manjaro stable substituting the old xournal and I like it a lot! All the new features! :heart_eyes:

Just stumbled upon a very minor issue which should affect about nobody, but for the sake of completeness: If I use the mouse wheel to zoom, however not above the sheet but above the zoom slider, the slider moves but the actual zooming doesn't happen for some reason. Dragging the slider with the mouse works as expected though.

Thanks for xournalpp and keep up the good work!

**Comment by peetCreative** [comment]
I can reproduce it.
