### ISSUE TITLE
Display font in use when opening/creating a file

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#1051]
When I open a file, or create a new one, xournal++ remembers and applies the font and size used in the last session, which is perfect for me. 
However, they are not declared in the toolbar button, so that if I want to go and increase or decrease the size of the text by 1 or 2, I need to figure out which size I was using, and scroll among the fonts to confirm again the one I am using. 
Making the toolbar button "memorize" the font and size as well would be very helpful. 
Thank you for your work!!
PS: OS is elementaryOS, based on Ubuntu 18:04

**Comment by peetCreative** [comment]
Prob connected to #1061
