### ISSUE TITLE
Color chooser (pipette) always chooses black

### ISSUE THREAD

**Issue by jclsn** [xournalpp/xournalpp#1065]
When you want to create a new color and use the pipette tool, the resulting color is always black

**Comment by Technius** [comment]
Is this still an issue?

**Comment by coldspark29** [comment]
Yes, just checked it

**Comment by Zikoel** [comment]
I want to investigate the issue but I can't find any `pipette tool` this issue baybe refers to somthing obsolete ?

**Comment by rolandlo** [comment]
@Zikoel In the toolbar, click on the "Custom Color" icon. Click on "+" in the dialog that opens up. 
![colorchooser](https://user-images.githubusercontent.com/40485433/185357065-28d221e8-3a52-4ec4-91c1-b749706e83ae.png)
Then you should see the pipette.
![pipette](https://user-images.githubusercontent.com/40485433/185357128-24029e04-59f5-4655-8ee6-30d5938ba3d5.png)

**Comment by Zikoel** [comment]
Ok I think this can be related to another bug I can't see that icon on my `Linux Mint 20.2 Cinnamon (Cinnamon version 5.0.7)`

![no-pipette](https://user-images.githubusercontent.com/6044789/185423790-3e519369-7dfb-401c-baf9-fb6c276a65fa.png)

**Comment by rolandlo** [comment]
I can't say why (and which) users don't get to see a pipette (color picker). Probably it depends on the desktop environment. It's not something we can change. You would have to head over to ask the Gtk devs about it. The `GtkColorChooser` widget is also exhibited in the gtk-3-demo.

**Comment by rolandlo** [comment]
Related to #2456 and #1565

**Comment by Zikoel** [comment]
Ok, actually cinnamon is not fully supported by gtk3 [GTK issue 5135](https://gitlab.gnome.org/GNOME/gtk/-/issues/5135)

**Comment by bhennion** [comment]
> When you want to create a new color and use the pipette tool, the resulting color is always black

Actually, this also happens when running `gtk3-demo`. This is a GTK3 bug. It seems to have been fixed in GTK4.
There is nothing we can do (besides porting to gtk4, which is slowly happening). Closing as a dependency issue.
