### ISSUE TITLE
Access to modified ( shift, ctrl etc. ) tool options without a keyboard

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1066]
### Access to modified tool options without a keyboard

The GUI uses keyboard modifiers ( shift, Control, alt ) to expand the functionality of various functions  but this is not accessible to tablet-mode users.

This topic came up in PR #1063 and this new issue has been created so that discussion may continue here.

**Comment by JJones780** [comment]
> I agree that it is best to minimize keyboard-only features (I also have a 2 in 1). From a UI standpoint, I'm thinking it might be best to make ellipses and circles two separate tools, and the same for rectangles and squares, and then adding a button "Center Shapes"? Or keep them the same tools and add another button to act as the Shift modifier (not sure about what to name it though).

I like the idea of an on screen button that can be added to the tool bar to let the user press shift, control or alt etc.

**Comment by JJones780** [comment]
How does this sound:
(Note - this would be a feature you turn on in preferences for advanced users).

The direction you _start_ the drag can be used to set properties:  
 Up = square
Down = rectangle
Left = from center
right = from corner

Likewise for the circle tool.

**Comment by JJones780** [comment]
I've put in the code to let the initial direction dictate the type of rectangle or ellipse as per the direction map in my comment above. 
I tried to give some feedback with cursor changes but it's still probably a default off option as it is not very intuitutive as it is now. Once you knowwhat it does it's very handy though.. and tablet friendly.
Give #1063 a try.

**Comment by Rmano** [comment]
I like it... just having the hovering cursor like this: 

![image](https://user-images.githubusercontent.com/6414907/55940124-c5a30100-5c3f-11e9-817c-9e92305d1641.png)

could be a powerful feed-forward also...

**Comment by JJones780** [comment]
The code for the directional modifiers modifier is in BaseStrokeHandler so very easy to use it for any draw handler. See the comments in the commit.

**Comment by JJones780** [comment]
That's an informative cursor.   I'm thinking about teh possibility of putting an icon ( your icon would work great ) at the center point while the direction decision is still being made. So instead of a cursor.. a center icon.
At that point maybe we should be considering popup pie menus ;)  I didn't say that...  unless GTK already supports it ;)

**Comment by LittleHuba** [comment]
Popup pie menus are nothing we may do. They are patented by Apple and we do NOT want to have a law suite with those guys.

**Comment by morrolinux** [comment]
@LittleHuba didn't know that! so what about Krita, are they infranging any patent or is it just something very similar?

**Comment by LittleHuba** [comment]
This is the patent I'm talking about: 
https://patents.google.com/patent/WO2009158549A2/da 

I actually never used Krita so I can't say whether they circumvented the patent by some special design or simply did not take this problem into account.

**Comment by Rmano** [comment]
I checked out PR #1063 and  I see a little problem: very big circles/ellipses appear polygonal when they're drawn starting "up" at least: 

![image](https://user-images.githubusercontent.com/6414907/56022155-61e60a00-5d0b-11e9-98af-78018af119cc.png)

I have not been able to reproduce it in master branch

**Comment by JJones780** [comment]
> I like it... just having the hovering cursor like this:
> 
I started to add in your cursor but I balked at putting together the draw instructions for it... no time tonight.  So instead I just tried text showing the equivalent key modifiers ( i.e. Control and Shift ).  Prefs Big/Highlighted cursor affects size too.
Try it out...with both size cursors. Now in PR #742
If you want to try your hand at a a cairo draw sequence for a cursor I'd be happy to put it in to try...
see https://www.cairographics.org/samples/

**Comment by JJones780** [comment]
Oops.. I had noticed the poor circles but then forgot about it.... thanks for the reminder!

**Comment by JJones780** [comment]
As for the patent - it's not on pie menus but on a specific implementation of showing a pie sub menu.
Pie menus have been around a long time. 
If we wanted to use them it wouldn't be a problem. I'm sure we could find an expired patent that would cover our needs if there was a concern.

**Comment by JJones780** [comment]
@Rmano  re: low segment circle problem - the fix is in.  Thanks for mentioning it and supplying the screenshot!

**Comment by Rmano** [comment]
Checked. It works! 
I am a bit occupied now, I will try to look at the cairo thing... it is not too different from the low-level PGF layer in TeX. Is there some interactive way to check what are you drawing?

**Comment by JJones780** [comment]
The hard part about drawing this icon is finding that tool that will spit out cairo code...  I did a quick search and see some svg to cairo tools but don't have time to investigate now.  The other option is to write out 'c' code to generate a simple rgba block to read into a pixbuf directly. I've done this for some embedded arduino code using a gimp plugin I modified. Probably prefer the svg->cairo route.
We'd probably want a custom icon for each tool and leave something like the current text-based info cursor as the base class default.

**Comment by eliasrg** [comment]
While the idea of initial direction determining attributes is very clever, it feels somewhat arbitrary to me. I suspect it would give a better user experience to just have separate tools for circles and squares in the menu, and then a button to toggle centering. Thoughts?

**Comment by JJones780** [comment]
I got sidetracked and made other improvements instead. Hopefully the crosshairs and text will do for now.

**Comment by JJones780** [comment]
I got sidetracked and made other improvements instead. Hopefully the crosshairs and text will do for now.
I saw a comment about creating separate tools for Rectangle , Square, Circle and Ellipse. I've put code in the constructor of RectangleHandler and CircleHandler to make it easy to do that ( by inverting the default shift and/or control modifiers ).

**Comment by JJones780** [comment]
The experimental "modifier by initial draw direction" is merged in along with the keyboard modifier enhancements from #1063. Give it a try ( off by default - enable in Preferences->DrawingArea ).

**Comment by JJones780** [comment]
@Rmano - go have a look at #1031- another experiment to benefit  keyboard-less stylus users.
I didn't mean to close this issue... but we can open another one to add toolbar icons.
