### ISSUE TITLE
zoom problem

### ISSUE THREAD

**Issue by msambg** [xournalpp/xournalpp#1069]
I compiled xournalpp Version 1.0.11 last week. 
but I have a problem with zoom. 
I can't really zoom out. 
If I zoom [-] the page gets bigger, in a similar way as I press [+]

If I use the slider the page zooms in when I move the slider left, and it also zooms in, when I move the slider right. 

What'S the problem?

**Comment by JJones780** [comment]
You may have presentation mode on. If so a fix is underway.

**Comment by peetCreative** [comment]
#1022 should solve the problem
