### ISSUE TITLE
xournalpp crashed on save but without data loss

### ISSUE THREAD

**Issue by sadid** [xournalpp/xournalpp#107]
I'm using wacom tablet. after doing some drawings and adding a text box to the file when I tried to save the file (previously saved document), it crashed (the send report bug is keep coming after launching xournalpp again). However the document has been udpated and no data is lost.

xournalpp on Archlinux (ver xournalpp-git 1.0.0.170.gc3c7c87-1 from AUR).
## Error Log:

Date: Tue Feb 10 10:37:39 2015

Error: signal 11:
[bt]: (0) xournalpp() [0x611649]
[bt]: (1) /usr/lib/libc.so.6(+0x33540) [0x7f24ce9c1540]
[bt]: (2) /usr/lib/libpixman-1.so.0(+0x62dbe) [0x7f24cb1bfdbe]
[bt]: (3) /usr/lib/libpixman-1.so.0(pixman_region32_union+0x99) [0x7f24cb1c11f9]
[bt]: (4) /usr/lib/libcairo.so.2(cairo_region_union+0x27) [0x7f24d048b907]
[bt]: (5) /usr/lib/libgdk-3.so.0(+0x3bcc8) [0x7f24d16e0cc8]
[bt]: (6) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x7ca) [0x7f24d1c858fa]
[bt]: (7) /usr/lib/libgtk-3.so.0(+0x2674d1) [0x7f24d1bc64d1]
[bt]: (8) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt]: (9) /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt]: (10) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (11) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (12) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt]: (13) /usr/lib/libgtk-3.so.0(+0x229662) [0x7f24d1b88662]
[bt]: (14) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt]: (15) /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt]: (16) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (17) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (18) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt]: (19) /usr/lib/libgtk-3.so.0(+0xfc2ed) [0x7f24d1a5b2ed]
[bt]: (20) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt]: (21) /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt]: (22) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (23) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (24) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt]: (25) /usr/lib/libgtk-3.so.0(+0xfc2ed) [0x7f24d1a5b2ed]
[bt]: (26) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt]: (27) /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt]: (28) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (29) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (30) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt]: (31) /usr/lib/libgtk-3.so.0(+0x33cd53) [0x7f24d1c9bd53]
[bt]: (32) /usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x145) [0x7f24d0a6f255]
[bt]: (33) /usr/lib/libgobject-2.0.so.0(+0x2181b) [0x7f24d0a8081b]
[bt]: (34) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xfd8) [0x7f24d0a89758]
[bt]: (35) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (36) /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt]: (37) /usr/lib/libgtk-3.so.0(+0x33706f) [0x7f24d1c9606f]
[bt]: (38) /usr/lib/libgobject-2.0.so.0(+0x10484) [0x7f24d0a6f484]
[bt]: (39) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (40) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt]: (41) /usr/lib/libgtk-3.so.0(+0x1402cc) [0x7f24d1a9f2cc]
[bt]: (42) /usr/lib/libgobject-2.0.so.0(+0x10484) [0x7f24d0a6f484]
[bt]: (43) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt]: (44) /usr/lib/libgobject-2.0.so.0(g_signal_emit_by_name+0x52a) [0x7f24d0a89f0a]
[bt]: (45) /usr/lib/libgdk-3.so.0(+0x2e9d4) [0x7f24d16d39d4]
[bt]: (46) /usr/lib/libgdk-3.so.0(+0x20ee8) [0x7f24d16c5ee8]
[bt]: (47) /usr/lib/libglib-2.0.so.0(+0x4a3c3) [0x7f24d079b3c3]
[bt]: (48) /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x15d) [0x7f24d079a91d]
[bt]: (49) /usr/lib/libglib-2.0.so.0(+0x49cf8) [0x7f24d079acf8]
[bt]: (50) /usr/lib/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7f24d079b022]
[bt]: (51) /usr/lib/libgtk-3.so.0(gtk_main+0x85) [0x7f24d1b4b1a5]
[bt]: (52) xournalpp(_ZN11XournalMain3runEiPPc+0x4e9) [0x4d3399]
[bt]: (53) xournalpp(main+0x34) [0x48dbc4]
[bt]: (54) /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f24ce9ae800]
[bt]: (55) xournalpp() [0x48e741]

Try to get a better stracktrace...
[bt] #1 xournalpp() [0x6117e5]
[bt] #2 /usr/lib/libc.so.6(+0x33540) [0x7f24ce9c1540]
[bt] #3 /usr/lib/libpixman-1.so.0(+0x62dbe) [0x7f24cb1bfdbe]
[bt] #4 /usr/lib/libpixman-1.so.0(pixman_region32_union+0x99) [0x7f24cb1c11f9]
[bt] #5 /usr/lib/libcairo.so.2(cairo_region_union+0x27) [0x7f24d048b907]
[bt] #6 /usr/lib/libgdk-3.so.0(+0x3bcc8) [0x7f24d16e0cc8]
[bt] #7 /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x7ca) [0x7f24d1c858fa]
[bt] #8 /usr/lib/libgtk-3.so.0(+0x2674d1) [0x7f24d1bc64d1]
[bt] #9 /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt] #10 /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt] #11 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt] #12 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt] #13 /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt] #14 /usr/lib/libgtk-3.so.0(+0x229662) [0x7f24d1b88662]
[bt] #15 /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt] #16 /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt] #17 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt] #18 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt] #19 /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt] #20 /usr/lib/libgtk-3.so.0(+0xfc2ed) [0x7f24d1a5b2ed]
[bt] #21 /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt] #22 /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt] #23 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt] #24 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt] #25 /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]
[bt] #26 /usr/lib/libgtk-3.so.0(+0xfc2ed) [0x7f24d1a5b2ed]
[bt] #27 /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x83) [0x7f24d0a72233]
[bt] #28 /usr/lib/libgobject-2.0.so.0(+0x103d2) [0x7f24d0a6f3d2]
[bt] #29 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x8e7) [0x7f24d0a89067]
[bt] #30 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f24d0a899bf]
[bt] #31 /usr/lib/libgtk-3.so.0(gtk_widget_size_allocate_with_baseline+0x427) [0x7f24d1c85557]

**Comment by wbrenna** [comment]
Thanks for the details. I have noticed crashes in GTK3 on some machines when running threaded. Launching in unthreaded mode "./xournalpp --no-threads" might help. If this was in unthreaded mode or if you get a save crash in unthreaded mode let me know - otherwise this is on the fix list for when threading gets a much needed overhaul.

**Comment by andreasb242** [comment]
A lot changed with GTK3 in this case, close because of the age

(I fixed some memory errors)
