### ISSUE TITLE
Crash at startup with:  basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by deragon** [xournalpp/xournalpp#1071]
Version 1.0.6-0~201904121319~ubuntu18.04.1 (latest available) crashes on startup, on Ubuntu 18.04 LTS fully updated as of 2019-04-13:

    $ xournalpp
    terminate called after throwing an instance of 'std::logic_error'
      what():  basic_string::_M_construct null not valid

    ** (xournalpp:28957): WARNING **: 08:48:25.805: [Crash Handler] Crashed with signal 6

    ** (xournalpp:28957): WARNING **: 08:48:25.805: [Crash Handler] Wrote crash log to: /home/hans/.xournalpp/errorlogs/errorlog.20190413-084825.log
    $

Attached, the stacktrace.  Obviously, the application is unusable; I have no workaround to get it running.

[errorlog.20190413-084825.log](https://github.com/xournalpp/xournalpp/files/3076189/errorlog.20190413-084825.log)

**Comment by JJones780** [comment]
Thanks for attaching the log file!
It looks like your local file containing information about recent files used across all gtk based apps has been corrupted.  I've merged a fix that will avoid the problem in the future. 
If it's easy for you please test it out.

If you can't test - no problem; just go ahead and  `rm ~/.local/share/recently-used.xbel`  to delete your recent files list and you should be able to run your existing version.

**Comment by deragon** [comment]
I confirm that removing `~/.local/share/recently-used.xbel` fixed the problem.  Thank you.
