### ISSUE TITLE
Touchscreen not recognized in plasma

### ISSUE THREAD

**Issue by voland66** [xournalpp/xournalpp#1073]
I am trying to use xournalpp in Fedora, KDE (plasma 5.14) on Lenovo Yoga X1 3rd generation. xournalpp does not recognize touchscreen and as a result always draws following hand/finger touch. Everything is fine if I log into gnome (both wayland and Xorg). If I go into Preferences/Touchscreen, I see no devices at all in the dropdown box with the list of devices that can be designated as touchscreen. This box contains the list of devices if I run the program in gnome.

**Comment by gzmorell** [comment]
https://phabricator.kde.org/tag/plasma_on_wayland/
https://community.kde.org/Plasma/Wayland_Showstoppers#No_.28wacom.29_Tablet_support

**Comment by voland66** [comment]
I should have been more clear -- I run KDE in Xorg where wacom is supported. Xournal++ can use both touchscreen and stylus -- but it can not distinguish them in kde/plasma, so both stylus and finger are treated as a pen. On the other hand, when I run xournal++ in "Gnome on Xorg" session, it does distinguish between touchscreen and stylus properly.

(For reference -- in KDE on wayland neither touchscreen nor stylus work at all; this is one of the reasons I am running kde on Xorg.)

**Comment by LittleHuba** [comment]
Could you post a screenshot of the Touchscreen tab in settings? Most likely you activated a setting that you shouldn't.

**Comment by voland66** [comment]
I'm attaching the screenshot. The "Device" dropdown box does not have any entries (it lists my devices in gnome on Xorg). Enabling/disabling external hand recognition does not have any effect.

![screenshot](https://user-images.githubusercontent.com/12825594/56912434-1a2de500-6a64-11e9-901c-614b40e4f08f.jpg)

**Comment by LittleHuba** [comment]
This is a bug of the Desktop Environment, as is negotiates between GTK and the input drivers. To be absolutely sure you may build #1070 by hand with the `DEBUG_INPUT` flag enabled. Then start it from the console play around with pen and touchscreen and upload the output of the console here. Do the same with the `DEBUG_INPUT_GDK_PRINT_EVENTS` flag and also upload the output. Then we can take a look what exactly goes wrong.

**Comment by voland66** [comment]
What do I need to do to build xournalpp by hand? I assume I can't just "git clone" to get the source, how do I get the right version to build?

**Comment by Technius** [comment]
Here are the build instructions: https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md

**Comment by voland66** [comment]
Sorry, I was not clear. I know how to build xournalpp once I have the source code. But I was under impression that the version mentioned by @LittleHuba  is not the same as the version I get by doing "git clone http://github.com/xournalpp/xournalpp.git". How do I get the correct version?

**Comment by Technius** [comment]
Ah, you want to build the new input system branch. It should be
```plain
git clone https://github.com/LittleHuba/xournalpp -b fix_input
cd xournalpp
mkdir build && cd build
cmake .. -DDEBUG_INPUT=on
make
```
This should compile a version with the `DEBUG_INPUT` flag (rerun cmake with another flag when you need to).

**Comment by voland66** [comment]
I will paste the debug output below but there is not really much information there. I also noticed that the discussion in the new input thread mentions a checkmark to enable new input in settings. I do not find that checkmark so I am wondering whether I am still building a wrong version? 
(I will rerun this version in gnome to see what the differences in the output are.)

DEBUG_INPUT flag:
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (xournalpp:6182): WARNING **: 11:22:52.416: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!

DEBUG_INPUT_GDK_PRINT_EVENTS flag:
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by voland66** [comment]
The files with the debug information should be attached.

[outputinput.txt](https://github.com/xournalpp/xournalpp/files/3158832/outputinput.txt)
[outputgdk.txt](https://github.com/xournalpp/xournalpp/files/3158833/outputgdk.txt)

**Comment by LittleHuba** [comment]
Seems like you activated both flags at the same time. It is important that you only select one flag, then build, test, upload the output and then repeat the steps for the second flag.

**Comment by voland66** [comment]
Hopefully, the output attached now is the right one:
[output-debug-gdk.txt](https://github.com/xournalpp/xournalpp/files/3168600/output-debug-gdk.txt)
[output-debug-input.txt](https://github.com/xournalpp/xournalpp/files/3168601/output-debug-input.txt)

**Comment by LittleHuba** [comment]
Thanks for the new files! They are the correct ones. As thought, your DE reports your touchscreen as simple mouse, hence the wrong detection. The question which remains is why your dropdown list does not show any devices. I'll have to dig into that part of the code.
As it stands I'll rewrite this part while I add support to assign different devices to input classes (stylus, mouse, touchscreen) as there are other tickets requiring this step as a solution. This should hopefully fix this issue on the way. I'll keep you updated and will request feedback once this is implemented.

**Comment by LittleHuba** [comment]
@voland66 could you please build #1144 manually and check if your issue persists?

**Comment by LittleHuba** [comment]
Use the following commands:
```
git clone https://github.com/LittleHuba/xournalpp -b fix_1073
cd xournalpp
mkdir build && cd build
cmake ..
make
```

**Comment by voland66** [comment]
Still does not work but there is a new message on startup which seems to indicate that you are on the right track. The console output contains the following:
** Message: 14:54:58.331: X11 Touch disabler active for device «Wacom Pen and multitouch sensor Finger»
But the finger still draws. When I open the preferences window in an attempt to specify the touchscreen device, the console output immediately says
** (xournalpp:9800): WARNING **: 15:00:36.114: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!

The first message appears only when I uninstall xorg-x11-drv-wacom and use libinput. The moment I install xorg wacom driver, I do not see the touchscreen disabler message.

**Comment by LittleHuba** [comment]
Unfortunately those two things are not related...
As far as I can see this is actually your DE just not relaying the devices to GDK. But why that is the case is not clear to me as X.org support in KDE is good for everybody else.

Could you check which version of GTK is running on your system? The package manager should know that.

**Comment by voland66** [comment]
I have these two packages installed:
gtk3-3.24.8-1.fc30.x86_64
gtk2-2.24.32-4.fc30.x86_64

**Comment by LittleHuba** [comment]
Could you take a look at #1151 if your devices are showing in the settings panel?

**Comment by voland66** [comment]
Do i still clone fix_1073 version or something else?

**Comment by LittleHuba** [comment]
Here are the updated instructions
```
git clone https://github.com/LittleHuba/xournalpp -b input_dev_classes
cd xournalpp
mkdir build && cd build
cmake ..
make
```

**Comment by LittleHuba** [comment]
Please take a look in the Input System tab!

**Comment by voland66** [comment]
Unfortunately, still "No devices were found..." message in the input system tab. I will try to reinstall wacom xorg driver later today and see if that makes a difference.

**Comment by LittleHuba** [comment]
Hi there could you try this fix? 
https://github.com/mypaint/mypaint/issues/388

I sounds awfully like what you experience...

**Comment by voland66** [comment]
Thank you, "unset GDK_CORE_DEVICE_EVENTS" worked.

**Comment by LittleHuba** [comment]
Nice! So it was your distribution after all.

**Comment by EB2000** [comment]
On fedora, the issue comes from the file /etc/xdg/plasma-workspace/env/gtk3_scrolling.sh, from kde-settings-plasma package. This was introduced to fix a scrolling bug 5 years ago, see https://bugzilla.redhat.com/show_bug.cgi?id=1226465
