### ISSUE TITLE
Can't see the marker

### ISSUE THREAD

**Issue by Frostalin** [xournalpp/xournalpp#1077]
Hello,

I have the problem that I can barely see the cursor while I'm using the pen or the text marker.

Is there an option to increase the cursor? While working on a 13" screen with Full HD I really get into trouble.

Thank you all for your work on the application. ;)

**Comment by JJones780** [comment]
Yes, There are two (!) options in the **Preferences** under the **View** tab:
- Highlight Cursor Position   <- my favourite
- Big Cursor for Pen
