### ISSUE TITLE
gtk3 bugs

### ISSUE THREAD

**Issue by corna** [xournalpp/xournalpp#109]
- When drawing lines very fast, lots of segments are created instead of a smooth line. With event compression disabled, the situation doesn't change. With the glib_new branch the line is smooth
  
  glib_new:
  ![glib_new](https://cloud.githubusercontent.com/assets/6459604/6602055/98f4b982-c819-11e4-8704-a3bfd2ae6f4c.png)
  
  gtk3:
  ![gtk3](https://cloud.githubusercontent.com/assets/6459604/6602056/98f80c5e-c819-11e4-8dbe-5f95ec5701ba.png)
- edit -> preferences often doesn't work, and the preferences menu doesn't show up. I have to close and reopen the application multiple times in order to have it back again

**Comment by dmgerman** [comment]
I did a bit of testing. It does not seem to be the rendering engine. 
I placed a return in DocumentView::drawStroke  before rendering is done and the strokes were not smooth.

--dmg

**Comment by dmgerman** [comment]
It appears that the bottleneck is   gtk_widget_queue_draw_area. I tried to optimized its call in 

bool StrokeHandler::onMotionNotifyEvent(GdkEventMotion* event)

by only doing the last segment:

        Point prevPoint(stroke->getPoint(pointCount - 1));
#define max(a,b) ((a) > (b)? (a):(b))
#define min(a,b) ((a) > (b)? (b):(a))
        double x1 = min(prevPoint.x,currentPoint.x);
        double y1 = min(prevPoint.y, currentPoint.y);
        double x2 = max(prevPoint.x,currentPoint.x);
        double y2 = max(prevPoint.y, currentPoint.y);

        this->redrawable->repaintRect(x1, y1, x2, y2);

but it it didn't seem to make much of a difference. What we really need (and I am not sure how to do it) is to force that every time we use cairo to draw to the screen during the creation of a line, such segment is immediately rendered irrespectively of the event queue (cairo drowing of the segment is done in DocumentView::drawStroke), called from StrokeHandler::onMotionNotifyEvent.

--dmg

**Comment by cass00** [comment]
Have there been any updates on this?
I've made some tests with xournalpp and the dmgerman's "testDrawing" program (dmgerman/testDrawing@24a1df3b) and observed the following on my Surface Pro 3:
-for event compression enabled the pen event frequency (number of events per second) is 60Hz and lines come out segmented
-for event compression disabled the pen event frequency is 125Hz and lines look smooth

Please have a look at cass00/xournalpp@97d601ff160c if you would like to test this. 

So from my point of view, the easiest option is to simply keep event compression disabled.

**Comment by wbrenna** [comment]
I think the original issue, which I replicated at the time, occurred with event compression disabled. At some point I will retest this and if things are fine with event compression disabled, I'm satisfied.

**Comment by oberien** [comment]
I just disabled event compression in `src/gui/XournalWidget.cpp` in `XournalView::setEventCompression` and changed `enable` to `FALSE` when calling [gdk_window_set_event_compression](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-event-compression). For me this solved the issue of edgy strokes and everything looks fine now. So this does seem like being caused by event compression.
Citing from the documentation of `gdk_window_set_event_compression`: "Some types of applications, e.g. paint programs, need to see all motion events and will benefit from turning off event compression." Therefore I created a PR ( #218 ).

@wbrenna Could you please test if that change fixes your issue as well?

**Comment by andreasb242** [comment]
Not reproducable with the new GTK3-Master
