### ISSUE TITLE
Request: Eraser scale with pressure

### ISSUE THREAD

**Issue by WPettersson** [xournalpp/xournalpp#1093]
I have a Thinkpad Yoga S1, with a stylus. When using the pen, everything (including pressure sensitivity) works fine, I can make thin lines or thick ones. I'd like to have a similar option for the eraser, where more pressure means a larger eraser.

**Comment by peetCreative** [comment]
I can imagine that this feature is hard to stear. 
I would rather make the selection of the eraser more transparent by the cursor size and better stearable by a slider.

**Comment by LittleHuba** [comment]
The Yoga S1 still has a wacom pen without a hardware eraser if I'm not mistaken. So you use the tip of the pen and press an additional button to enable the eraser? Just to make sure we are talking about the same thing. If you are using a hardware eraser (other end of the pen) this will not work as the eraser has no pressure sensitivity built in.

I see one big problem with the overall idea. The pressure of the pen changes quite tremendously for small changes in physically pressing the pen against the display. For big size differences of the eraser this is not suitable. We could solve this with one of the following options:
- make the size difference of the eraser very small -> the enhancement has no real benefit
- somehow interpolate the pressure changes and "slow down" the size changes of the eraser (this is still not perfect for short erasing strokes as the interpolation takes some time to get the "correct" value)

If we do not use one of the options above, you will see an eraser that changes sizes very fast and is uncontrollable and thus unusable.

**Comment by WPettersson** [comment]
Yes, it's a wacom pen without a hardware eraser, you use the tip of the pen and an extra button to erase.

I do see what's being said about pressure sensitivity. I did just spend a few minutes seeing how accurate I could be with sensitivity, and I get that we probably don't want an ever-growing eraser at max pressure.

One idea that I had is to maybe set the "max size" of the eraser to be the current eraser size, but allow lower pressures to erase smaller areas. This seems to be something that I can consistently do on my stylus at least, even with the display in "laptop" mode rather than holding it as an actual tablet. We'd still probably want to have only have a few "steps" worth of sizes, so that slight pressure changes don't abruptly change the size of the eraser.

Another alternative is to require a high pressure consistently (say for at least 0.5 seconds) for a change in size, and reset the size to normal every time the pen is lifted completely. That might be starting to get a little complicated, however.

**Comment by LittleHuba** [comment]
> One idea that I had is to maybe set the "max size" of the eraser to be the current eraser size, but allow lower pressures to erase smaller areas. This seems to be something that I can consistently do on my stylus at least, even with the display in "laptop" mode rather than holding it as an actual tablet. We'd still probably want to have only have a few "steps" worth of sizes, so that slight pressure changes don't abruptly change the size of the eraser.

I like this version the most as it seems to be a suitable compromise between usability and wished for feature.

As I'm currently working on input handling anyway, I'll add this to the list of todos.

**Comment by LittleHuba** [comment]
Superceded by #1170 as we can provide pressure curves for each tool quite easily. With this the behaviour is defined by the user and the previous discussion on how to implement this is obsolete.
