### ISSUE TITLE
Moving the latex popup window causes the whole application to move

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1098]
I'm using Solus Linux, but this probably affects all platforms. Moving the "Insert Latex" popup window causes the entire application to move instead of just the popup moving. I would expect only the popup window to move.

![xournal_latex_popup_issue](https://user-images.githubusercontent.com/1066652/56846370-63730e80-6883-11e9-9b77-cb45ac2ba6bb.gif)

It's a minor issue, but it's pretty annoying when the popup covers something that you want to refer to when typing up an equation.

**Comment by Technius** [comment]
This is actually how GTK works, but there's probably a way to work around this.

**Comment by LittleHuba** [comment]
This is actually a global GTK config setting. It's called `Attached Modal Dialogs` or something like that. There is no way to disable this behaviour just in one app.

See https://askubuntu.com/questions/109321/popup-dialogs-attached-to-window-title-and-not-movable-how-to-detach-modal-dial/836137
