### ISSUE TITLE
Respect the XDG base directory specification on Linux

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1101]
The files in `.xournalpp` should be relocated to the appropriate locations specified by the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (e.g. config files go in `~/.config/xournalpp/` and data files go in `~/.local/share/xournalpp`) on Linux.

Reasons:
* It makes it easier to synchronize dotfiles across multiple devices.
* One fewer dotfile in the home directory.
* Makes it easier to find the configuration files for new users (search in the standard location `~/.config/` instead of having to look it up online or run `find / -name '*xournalpp*'`)
* This standard is supported by many Linux programs and tools (e.g. Python, LibreOffice, NeoVim).

**Comment by andreasb242** [comment]
This is correct, this should be cahnged, but the files should be moved on start, so that existing installations are migrated.

**Comment by cbm755** [comment]
Maybe this project is young enough that us users would forgive you for not migrating such files, esp. if you had a prominent notice on the releases page.

**Comment by LittleHuba** [comment]
We could add the moving algorithm for 2 releases and remove it afterwards. That would ensure that the biggest user community would not loose settings and we can remove the complexity afterwards.

**Comment by avidseeker** [comment]
Just as a note, to fully comply with XDG standard:
* `$XDG_CONFIG_HOME/xournalpp/metadata` should be in `$XDG_STATE_HOME/xournalpp/metadata`
* `$XDG_CONFIG_HOME/xournalpp/plugins` should be in `$XDG_DATA_HOME/xournalpp/plugins`
