### ISSUE TITLE
Pasted text appears only after after additional writing, or after unfocusing the textbox

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#1103]
The behaviour I have been noticing in the current Xournal++ version (I have a memory that this did not use to happen 1.5 - 2 months ago), is that if I paste text in a textbox [no matter whether new or containing some text already], the pasted text will not appear immediately, but only if:

- I click outside of the textbox (or anyway unfocus said textbox)

- I write additional text following my Ctrl+V action, so that instantaneously the pasted text will appear

**Comment by edo0** [comment]
> The behaviour I have been noticing in the current Xournal++ version (I have a memory that this did not use to happen 1.5 - 2 months ago), is that if I paste text in a textbox [no matter whether new or containing some text already], the pasted text will not appear immediately, but only if:
> 
> * I click outside of the textbox (or anyway unfocus said textbox)
> * I write additional text following my Ctrl+V action, so that instantaneously the pasted text will appear

**Comment by LittleHuba** [comment]
This sounds like a missing refresh of the view.
