### ISSUE TITLE
Missing dependency for fedora build: gcc-c++

### ISSUE THREAD

**Issue by Scafir** [xournalpp/xournalpp#1116]
gcc-c++ is missing from the dependency list for the fedora build (tested on a fresh install of fedora 30)
I would have loved creating directly a pull request, but my knowledge in git is very limited (I'll try to change that in the future)

**Comment by LittleHuba** [comment]
Thanks for the heads up! 
Git is not that hard to understand. Just look through a few tutorials and try your hand. Learning by doing is the way to go 😉
