### ISSUE TITLE
Text/font size doesn't scale with dpi calibration change in zoom settings.

### ISSUE THREAD

**Issue by CobaltSpace** [xournalpp/xournalpp#1118]
I am on version 1.0.10 on Arch Linux.

**Comment by Technius** [comment]
Does it scale properly when you save the file, restart the program, and load the file?

**Comment by CobaltSpace** [comment]
Yes.

This issue shows up with opening the same file on two different computers with different display dpi calibration.

**Comment by VidalDuval** [comment]
I get a possibly related issue in version 1.0.12 (on Arch Linux as well). I discovered the effect after setting the Display DPI Calibration (Preferences -> Zoom) to 152. Annotated PDFs created previously with Xournal were then showing much bigger text size. When the DPI calibration is set to 100, text size looks the same as it did in Xournal.

**Comment by alfazaz** [comment]
Same problem on uptodate archlinux... It's an annoying bug (when I open a last edited .xopp file with a different dpi calibration, text size is changed -> it's necessary to find the oldest dpi used to keep old texts in right place with right size...).
