### ISSUE TITLE
Crash on Wayland after using Eraser

### ISSUE THREAD

**Issue by jaykijay** [xournalpp/xournalpp#1121]
[xournalpp_CRASH_wayland_gnome.txt](https://github.com/xournalpp/xournalpp/files/3157924/xournalpp_CRASH_wayland_gnome.txt)
[xournalpp_CRASH_wayland_gnome.txt](https://github.com/xournalpp/xournalpp/files/3157926/xournalpp_CRASH_wayland_gnome.txt)

Hi,
xournalpp crashes reproducible only in Wayland and Gnome as DE after using the eraser.
It does not crash right after using it the first time, but after some times using it.
This also happens when using any other Button on Pen.

BTW: Used new input System from @LittleHuba but it also crashes with old System.
BTW2: It does not crash in KDE or Gnome/KDE on xorg with libinput and wacom drivers. Only in Wayland with Gnome.

Attached: Logfiles.
[errorlog.20190508-160830.log](https://github.com/xournalpp/xournalpp/files/3157914/errorlog.20190508-160830.log)
[xournalpp_CRASH_libinput_wayland_gnome_printevents.txt](https://github.com/xournalpp/xournalpp/files/3157915/xournalpp_CRASH_libinput_wayland_gnome_printevents.txt)
[xournalpp_CRASH_wayland_gnome.txt](https://github.com/xournalpp/xournalpp/files/3157927/xournalpp_CRASH_wayland_gnome.txt)

**Comment by LittleHuba** [comment]
This is unfortunately a bug in GTK. Do you have any experience in debugging?

**Comment by l0wl3vel** [comment]
It is not a gtk issue, it is a bug in libinput i reported and it should be fixed in the next feature release: https://gitlab.freedesktop.org/libinput/libinput/issues/259

**Comment by LittleHuba** [comment]
Thanks for the heads up @l0wl3vel
