### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by jenskuespert** [xournalpp/xournalpp#1124]
In Version 1.0.10 the file po/de.po contains a spelling error in line 1581.

It is
#: ../src/util/XojMsgBox.cpp:42
msgid "Replace"
msgstr "Ersetzten"

and should read:
#: ../src/util/XojMsgBox.cpp:42
msgid "Replace"
msgstr "Ersetzen"

Keep up the good work!
-- 
    - Jens -

**Comment by mvdberge** [comment]
Bug is already fixed, could be closed

**Comment by jenskuespert** [comment]
In fact there are other german translations fixed as well.
