### ISSUE TITLE
Automated Windows builds

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1127]
We should automate Windows builds using a service like AppVeyor or Azure Pipelines. Preferably, this should be done before the next release.

**Comment by Technius** [comment]
Superceded by #1176.

**Comment by cbm755** [comment]
Who builds current exe for release?  Is it done (or can it be done) as some sort of cross-compile from GNU/Linux?

**Comment by Technius** [comment]
It's compiled manually by one of the current team members. We use MSYS2 on Windows to build it (see [here](https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md)).

It might be possible to cross-compile, but it's a massive pain to set up and we haven't really looked into it.

**Comment by Technius** [comment]
Automated windows builds were implemented in a few commits before #1252.
