### ISSUE TITLE
Adding 'amssymb'-package to latex template

### ISSUE THREAD

**Issue by Unrealrussian** [xournalpp/xournalpp#1128]
**Is your feature request related to a problem? Please describe.**
When writing in Xournalpp i like to use the latex feature as my handwriting is not always readable but the symbol for real numbers is not available.

**Describe the solution you'd like**
Add the 'amssymb'-package to the latex template

**Additional context**
![image](https://user-images.githubusercontent.com/22859658/57507941-757f9300-7300-11e9-9a85-b48e0348b227.png)

**Comment by Technius** [comment]
`amssymb` occurs often enough to warrant including it in part of #1113. This is a temporary solution though, so I'll be keeping this issue open until I implement a customizable preamble feature.

**Comment by LittleHuba** [comment]
Solved by #1113
