### ISSUE TITLE
Maximizing the window causes scrolling issues

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1132]
**Affects versions :**
 - OS: Linux (Solus Linux), probably affects more versions
 - Version of Xournal++: `master` branch as of ` a5f033e`, as well as v1.0.10

**Describe the bug**
After maximizing the window for the first time, scrolling can break in one of two ways, depending on the situation:
1. Scrolling is completely disabled on the blank document displayed immediately after Xournal++ is opened. Sometimes the same issue occurs when a document with one page is opened
2. Scrolling within the page shown works, but scrolling between pages is disabled. In addition, selecting a page will only scroll within the current page but not change which page is displayed.

**To Reproduce**
Steps to reproduce situation 1:
1. Open Xournal++. There should be a blank document.
2. Maximize the window.
3. Attempt to scroll with the mouse wheel.

Steps to reproduce situation 2:
1. Open Xournal++. Open any document with more than one page.
2. Maximize the window.
3. Attempt to scroll to the next/previous page with the mouse wheel.
4. Attempt to select a different page.

**Expected behavior**
Scrolling should work.

**Screenshots of Problem**
N/A

**Additional context**
N/A

**Comment by JJones780** [comment]
I can replicate this bug in the old input system.
It is not present in the new input system.

**Comment by Technius** [comment]
I can still reproduce situation 1 with the new input system enabled.
