### ISSUE TITLE
Regression: strokes are not saved correctly

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1133]
**Affects versions :**
 - OS: Solus Linux (probably affects more versions)
 - Version of Xournal++: Every version on `master` branch since https://github.com/xournalpp/xournalpp/commit/bea5b61622e7c3484484ca43a520cde8b451034c

**Describe the bug**
There's a regression causing strokes to be saved incorrectly. Note that documents saved with a previous version load with their strokes correct.

**To Reproduce**
1. Open Xournal++, put down a few strokes, and save the document.
2. Load the document that was just saved.

**Expected behavior**
The strokes appear as they were when they were saved.

**Screenshots of Problem**
Before
![issue_before](https://user-images.githubusercontent.com/1066652/57566073-11e77b00-737d-11e9-8da0-7d286af7a700.png)
After
![issue_after](https://user-images.githubusercontent.com/1066652/57566074-13b13e80-737d-11e9-9aad-8d258213c08e.png)

**Additional context**
Error log: [save_issue.log](https://github.com/xournalpp/xournalpp/files/3168706/save_issue.log)

**Comment by Technius** [comment]
If possible, we should add a test suite that can catch this kind of bug in the future.

**Comment by JJones780** [comment]
My bad.. fix is in 1135... merging now.
