### ISSUE TITLE
Missing translation on "Input System"

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1134]
**Affects versions :**
 - OS: Linux Ubuntu 18.04
 - Version of Xournal++: master branch  a5f033ef

**Describe the bug**
Missing/wrong translation on input system: 

**To Reproduce**
Just compile and run.

**Expected behavior**
given that my language is `LANGUAGE=en_GB:en`, I am expecting the string in English.

**Screenshots of Problem**
![2019-05-11_10-58](https://user-images.githubusercontent.com/6414907/57567628-7980e300-73dc-11e9-9998-5e7c5fe4bacf.png)

**Comment by LittleHuba** [comment]
Oops 😅
