### ISSUE TITLE
New input spurious dots and strokes when the tablet has hand pad device active 

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1136]
**Affects versions :**
 - OS: Linux Ubuntu 18.04
 - Version of Xournal++: master 290e7a9c, new input system activated

**Describe the bug**
My tablet is an Intuos CTH480 and it has a physical switch to enable the touchpad behavior. When the switch is off, there is no problem at all, the pen works ok, and there are no spurious dots or strokes. 

When I switch the touchpad on, xournalpp uses the touch events to scroll (great!), but sometime it seems it confuses the touch event with the pen, leading to strokes (rarely) or spurious dots (much more common). 

**To Reproduce**
- Activate the touchpad switch on the tablet.
- Draw something and in the middle, scroll (I normally have the hand resting on the tablet, to scroll I hover the hand and the pen, and I use the fourth finger to scroll). 
- Sometimes a dot appears, or a line is drawn, when I approach back the pen to the tablet without touching it. The `key-mon` indicator *seems* to show a middle-mouse click event in this case...  

**Input Logs**
I have two logs with `DDEBUG_INPUT=ON:
- a log when spurious strokes happened (`debug_input_unwanted_strokes.log`)
- a log when spurious points appeared (`debug_input_unwanted_dot.log`)

and one log with `DEBUG_INPUT_GDK_PRINT_EVENTS=ON` when dots appeared (`debug_input_gdk.log`); I was not able for now to reproduce the unwanted strokes with this debug option. 

Zipped logs: 
[logs.zip](https://github.com/xournalpp/xournalpp/files/3168967/logs.zip)

**Expected behavior**

No spurious strokes or dot should appear. 

**Screenshots of Problem**
Three screencasts related to the three logs: 
1. `debug_input_unwanted_strokes.log`: 
![unwanted_strokes](https://user-images.githubusercontent.com/6414907/57569191-ad1a3800-73f1-11e9-800a-31f2ecd29aa2.gif)

2. `debug_input_unwanted_dot.log`
![unwanted_dot](https://user-images.githubusercontent.com/6414907/57569192-b3a8af80-73f1-11e9-90b7-5d450dc1800c.gif)

3.  `debug_input_gdk.log`
![unwanted_dot_gdk](https://user-images.githubusercontent.com/6414907/57569211-efdc1000-73f1-11e9-8c51-389c90b051df.gif)

**Additional context**

This is low priority, because shutting off the touchpad is easy and fast.

**Comment by Technius** [comment]
It could be a driver/configuration issue, but I'm not sure. I get the dot issue in Krita, too.

**Comment by Rmano** [comment]
Yes, it could be. I almost never use the tablet with other apps ;-), so I am not sure. I agree on the `low  prio` status.

**Comment by LittleHuba** [comment]
There are some events that should not occur (this seems like a driver issue). There is nothing we can do here without delaying all button presses so we can filter out those that should not be there. I'm understandably not happy with this approach.
```
** Message: 13:06:50.817: Event
Event type:	GDK_BUTTON_PRESS
Source device:	GDK_SOURCE_TOUCHPAD
Button:	1

** Message: 13:06:50.817: Event
Event type:	GDK_BUTTON_RELEASE
Source device:	GDK_SOURCE_TOUCHPAD
Button:	1
```

One solution that came to mind was the solution mentioned in #874. But this would disable drawing with your touchpad...
