### ISSUE TITLE
Selection tools: double click to edit

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1137]
**Is your feature request related to a problem? Please describe.**
When I use the select object tool, I often want to move things around and edit them without switching tools. Currently, you have to move them, deselect, switch tool, and then edit.

**Describe the solution you'd like**
Double clicking on selected objects such as Text and LaTeX objects when using a selection tool should cause their corresponding editors to appear.

**Describe alternatives you've considered**
Select object tool could alternatively bring up a context menu that has an `Edit` option when right clicking (current behavior is to copy the object).

**Additional context**
Probably involves changes to input handling.

**Comment by LittleHuba** [comment]
For double clicks we need to catch the event. Currently we only catch single clicks. (but two single clicks are generated before a double click). 
This is a minor change and should not be much work at all.
