### ISSUE TITLE
Coding Conventions

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#114]
The Coding Conventions should be written down, and linked on the README.md file.

If possible, we should search for a tool which supports automatically formatting, so the code of all developer looks the same.

Tabsize, (or space count), if there is a space after the if etc.

Also points like File header should be mentioned.

#ifndef SOMEFILE_H
#define SOMEFILE_H
#endif

Can be replaced by #pragma once
http://en.wikipedia.org/wiki/Pragma_once

**Comment by MarPiRK** [comment]
Formatting standardization is very convenient in NetBeans. I can include exported profile, which I've been using in my branch.
+1 for pragma once, I'll include it in next commit.

**Comment by andreasb242** [comment]
It should also be human readable, as I wrote before in another Issue, I use Eclipse ;-)
And others may don't use an IDE

**Comment by MarPiRK** [comment]
In commit MarPiRK/xournalpp@74c3b1608a2a105ee363fcf6c407f8ebdf38fb01 I've added `#pragma once`.

**Comment by x2b** [comment]
I also added a simple script to normalize the include names, it is here:

https://gist.github.com/x2b/371fde88e447a587750b

Personally I very much dislike includes of the kind `#include "../../view/PdfView.h"`. To get rid of these I added `-I$(top_srcdir)/src \` to `src/Makefile.am` and `src/util/Makefile.am` and ran the script like this:

    for file in `find . -maxdepth 4 -name "*.h" -o -name "*.cpp"`; do ./normalize_includes.py "$file" util/; done

I think adding the includes is pretty standard. The modified includes look much cleaner to me though.

**Comment by MarPiRK** [comment]
You have written on wiki that every if, for, while (even with one line of code) should be embraced with bracket. I think that some small expressions like `if (foo) return;` should be treated as oneliners to improve readability of the code.

**Comment by wbrenna** [comment]
I think the current paradigm is not to use any one-line expressions of that form. Avoiding those is a matter of preference; I think we should keep it as is.

**Comment by andreasb242** [comment]
The link to the wiki: https://github.com/xournalpp/xournalpp/wiki/Coding-conventions

Still not finished.

**Comment by andreasb242** [comment]
The wiki Entry contains now enough information, it will be improved in the future, but I think I close this ticket now.
