### ISSUE TITLE
Autoload .xopp files

### ISSUE THREAD

**Issue by janpath** [xournalpp/xournalpp#1147]
**Affects versions :**
 - Xournal++ 1.0.10

**Describe the bug**
When the “Autoload .pdf.xoj” option is enabled (which should probably be renamed) I would also expect Xournal++ to autoload .xopp files.

**Comment by veecue** [comment]
Will be fixed by #1117
.xopp will not be autoloaded, but .pdf.xopp will and the default file extension for saving a file opened from a PDF will be .pdf.xopp

**Comment by SenaidaHdez** [comment]
Also happens here! It doesn't autoload neither pdf.xoj nor .xopp

**Comment by jonasBoss** [comment]
As #1117 got merged, it is now possible to save *.pdf.xopp files, which will get automatically loaded. Existing files can be renamed "*.pdf.xopp" to enable autoloading for them. 
If the intent is to automatically load *.xopp files as well, this should be a Feature request.

**Comment by Febbe** [comment]
I will close this now, since #1117 fixed the bug and the issue is very old. Please open a new feature request issue.
