### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#115]
There should be a Bash file to execute the Static Code analysis.
For this purpose I know Cppcheck.

Cppcheck is free, but may not the best, but it finds e.g. possible nullpointer access.

I read clang has a good static code analysis, but didn't use it yet.

**Comment by MarPiRK** [comment]
Here you have some cppcheck reports: https://gist.github.com/MarPiRK/df77abd423539fc50c98

**Comment by andreasb242** [comment]
I let "scan-build" over the code, this is the langc Static Code analysis.
In my opinion I saw only one problem, which may result in a memory leak.

Currently I have a linker error on the string_new branch, which I have to look first.

**Comment by wbrenna** [comment]
Probably the same linker error I just had!

**Comment by MarPiRK** [comment]
It would be nice to add Coverity scan support for main repo.
I've done it for my fork: https://scan.coverity.com/projects/marpirk-xournalpp

**Comment by andreasb242** [comment]
I added coverity for the main Project, but the Project is currently not yet aproved
