### ISSUE TITLE
Loading custom plugins

### ISSUE THREAD

**Issue by enricoar** [xournalpp/xournalpp#1155]
Maybe it's already possible, but I didn't find out why. Is it possible to make own  plugins and put them somewhere so they are recognized by xournalpp. At the moment it seems to work only if I put them in the plugin directory of the cloned source. It would be useful if one could put it, e.g. in the  .xournalpp directory.
Thanks

**Comment by Technius** [comment]
This can now be easily accomplished thanks to #1384.

Currently, the plan is to load plugins from *all* of the following paths:
* `$XDG_DATA_HOME/xournalpp/plugins`. This will cover e.g. `~/.local/share/xournalpp/plugins`.
* `$DIR/xournalpp/plugins` where `$DIR` is `a folder from `$XDG_DATA_DIRS`. This will cover e.g. `/usr/share/xournalpp/plugins`.
* `$CONFIG_FOLDER/plugins` where `$CONFIG_FOLDER` is the xournalpp configuration folder, in case the configuration is synced across computers.

**Comment by Febbe** [comment]
I would also add `./plugins` and `../plugins` and `../../plugins`

**Comment by Febbe** [comment]
What shall we do, if there are duplicates?
I propose to add the path to the PluginManager, so both plugins are closeable, but they must be mutually exclusive I think.

**Comment by Technius** [comment]
> I would also add `./plugins` and `../plugins` and `../../plugins`

Do you mean relative to the `xournalpp` binary? If you instead mean relative to the current directory, I would see no reason for why this would be desirable.

> What shall we do, if there are duplicates?

The most straightforward way I can think of is to load only the plugin that comes first in a priority list on the search paths (e.g. load the plugins from the user directories first, then ignore plugins with names similar to the ones already loaded in the following directories).

**Comment by Febbe** [comment]
> Do you mean relative to the `xournalpp` binary? If you instead mean relative to the current directory, I would see no reason for why this would be desirable.

Yes relative to the source, this would make xournalpp relocatable.

> The most straightforward way I can think of is to load only the plugin that comes first in a priority list on the search paths (e.g. load the plugins from the user directories first, then ignore plugins with names similar to the ones already loaded in the following directories).

Interestingly it seems to work very well to load plugins with the same name.
But in the case we only show and load it once, which search order shall we use?
My proposal would be similar to yours: XDG_CONFIG_DIR/xournalpp/plugins > xournalpp<.exe>/../plugin > xournalpp<.exe>/../../plugin > xournalpp<.exe>/../../../plugins >   glade_search_path
