### ISSUE TITLE
Image should be selected by default upon insertion

### ISSUE THREAD

**Issue by bloff** [xournalpp/xournalpp#1158]
When inserting an image in xournal, I used to be able to resize it. However xournalpp doesn't seem to allow for this anymore.

**Comment by JJones780** [comment]
Hi Bruno, Thanks for getting involved with Xournal++ testing.

I am unable to replicate your issue... images resize on the latest build on my machine.
It may be specific to a number of things.
What version of xournal++ are you using? 
What operating system are you using? 
Is this a fresh install of xournal++?
Do you have many custom settings.. would you feel comfortable deleting the settings file ( or move it temporarily then copy it back over it's new replacement after the test ). On Linux the settings file is at ~/.xournalpp/settings.xml

**Comment by niknah** [comment]
Inserting the image doesn't select it.  You have to go to "select object" and then resize it, that was what confused me.

**Comment by Technius** [comment]
This behavior is confusing, so I think we should select the image by default after insertion.

**Comment by bloff** [comment]
Ah, yes, this was exactly the problem. After inserting the image one must first go to Tools -> Select Object and click the image, then one can resize it. Feel free to close this issue unless it should stay open as an enhancement or something.
