### ISSUE TITLE
Running on iOS

### ISSUE THREAD

**Issue by kirk86** [xournalpp/xournalpp#1160]
Is there any possibility to run on tablets iOS, for instance such as ipad?
Thanks!

**Comment by LittleHuba** [comment]
You may port Xournal++ to iOS yourself, but we have enough on our hands with enhancing it and keeping it running on the platforms it is currently available for.
Porting to iOS or Android is a very tedious job as you have to rewrite 90% of the code essentially .

**Comment by TheOneWithTheBraid** [comment]
@kirk86 I started a port. As there does not seems to be a solution coming soon, I started a Xournal++ reader (and maybe later editor too) for mobile platforms including Chrome OS, Android, iOS and web browsers.

https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile

The project is using Flutter and currently only supports opening and parsing the `.xopp` files. Except of the page size and the number of pages in the bottom bar, they can not yet be shown properly. If anyone is interested too in having a mobile port of Xournal++, feel free to contribute.

You can get a online preview here: https://theonewiththebraid.gitlab.io/xournalpp_mobile/#/
