### ISSUE TITLE
Wrong button mapping for Wacom stylus/tablet

### ISSUE THREAD

**Issue by michaelschufi** [xournalpp/xournalpp#1166]
**Affects versions :**
 - OS: Windows 10
 - Version: current master - (793c15ef94c9dbf7735c01fc630c5f6b053e5e29)

**Describe the bug**
The Wacom pen's eraser and other buttons get misinterpreted. E.g.:
Eraser 

**To Reproduce**
(Tested with a Wacom Intuos PT S tablet)
1. In the settings menu set the following settings:
    Stylus -> Button 1 => the select region tool
    Stylus -> Button 2 => the highlighter tool
    Stylus -> Eraser => the eraser tool
1. Write something with the tip of the pen.
1. Try to erase it with the eraser part of the pen.
    _The eraser will not work but write something instead._
1. Try to highlight something, using the lower button (highlighter tool).
    _The page will scroll instead of switching to the highlighter._
    **This can be fixed by a driver setting (see below)**
1. Try to select the written text, using the upper button (region select).
    _Works as intended_

**Input Logs**
I have previously extracted the events and will paste them at the bottom.
The DEBUG_INPUT_GDK_PRINT_EVENTS output is attached:
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3202907/debug_gdk_input.log)

**Expected behavior**
See italics in the _To Reproduce_ section.

**Output of DEBUG_INPUT**
For the _tip_ part of the pen:
```
** Message: 15:29:32.433: Event
Event type:     GDK_ENTER_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:29:32.440: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:29:33.864: Event
Event type:     GDK_BUTTON_PRESS
Source device:  GDK_SOURCE_PEN
Button: 1

** Message: 15:29:33.880: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:29:36.084: Event
Event type:     GDK_BUTTON_RELEASE
Source device:  GDK_SOURCE_PEN
Button: 1

** Message: 15:29:36.104: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:29:41.006: Event
Event type:     GDK_LEAVE_NOTIFY
Source device:  GDK_SOURCE_PEN
```

For the _eraser_ part of the pen:
```
** Message: 15:31:06.324: Event
Event type:     GDK_ENTER_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:31:06.325: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:31:07.432: Event
Event type:     GDK_BUTTON_PRESS
Source device:  GDK_SOURCE_PEN
Button: 1

** Message: 15:31:07.449: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:31:08.927: Event
Event type:     GDK_BUTTON_RELEASE
Source device:  GDK_SOURCE_PEN
Button: 1

** Message: 15:31:08.940: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:31:10.228: Event
Event type:     GDK_LEAVE_NOTIFY
Source device:  GDK_SOURCE_MOUSE
```

When pressing the _upper_ button of the pen:
```
** Message: 15:33:45.244: Event
Event type:     GDK_BUTTON_PRESS
Source device:  GDK_SOURCE_PEN
Button: 2

** Message: 15:33:45.260: Event
Event type:     GDK_MOTION_NOTIFY
Source device:  GDK_SOURCE_PEN

** Message: 15:33:45.395: Event
Event type:     GDK_BUTTON_RELEASE
Source device:  GDK_SOURCE_PEN
Button: 2
```

When pressing the _lower button_ while the tip touches the tablet:
```
** Message: 15:33:42.266: Event
Event type:     GDK_SCROLL
Source device:  GDK_SOURCE_MOUSE
```
**EDIT: This problem can be fixed by changing the button mapping here:**
![grafik](https://user-images.githubusercontent.com/2805598/58804254-b756dd00-8611-11e9-98a5-3339c9ddf83e.png)

**Notes to gtk3-demo**
The gtk3-demo "Touch and Drawing Table" can distinguish between
- "WACOM Tablet Pressure Stylus" for the tip
- "WACOM Tablet Eraser" for the eraser
- "System Aggregated Pointer" for the lower button + dragging

**Comment by LittleHuba** [comment]
The button mapping of your stylus is something we are not able to influence. This is most likely a driver setting. 

Concerning the eraser take a look at #1151

**Comment by LittleHuba** [comment]
> When pressing the _lower button_ while the tip touches the tablet:
> 
> ```
> ** Message: 15:33:42.266: Event
> Event type:     GDK_SCROLL
> Source device:  GDK_SOURCE_MOUSE
> ```

Could you please check if you get any specific button events for this? It might be possible to map the scroll events to motion events but we require button press and button release events or this wont help you.

**Comment by michaelschufi** [comment]
Okay, so I got the problem with the lower button working by assigning it to a mouse function in the driver settings - like middle click or the 4th mouse button (both work, interestingly). 

I haven't had the time to look at #1151 yet. I will post here as soon as I have more information.

**Comment by michaelschufi** [comment]
So, I have found the following issue on the gtk repo:
[Issue 1550 Windows: Wacom Eraser detected as Pen](https://gitlab.gnome.org/GNOME/gtk/issues/1550)
I don't know when this problem is going to be fixed, but it's been 5 months and switching over to a new API seems like a big undertaking.

I also checked out #1151 and I'm not sure if it will help, but since the gtk3-demo recognizes the pen as stylus and can differentiate between pen-tip/eraser I still have hope. As soon as the Windows quirks are implemented in #1151, I can try it again.

**Comment by LittleHuba** [comment]
The windows quirks will follow in another PR, as I'm not sure how to fix this without rewriting GTK. #1151 is big enough already.

**Comment by LittleHuba** [comment]
@michaelschufi could you try this fix?
http://viziblr.com/news/2013/6/23/the-windows-and-wacom-tablet-nightmare-is-over.html

I don't know if it is still there but this might fix all those issues Windows users have.

**Comment by LittleHuba** [comment]
Wacom additionally has a setting to use the WinTab driver. Please activate that if possible.

**Comment by michaelschufi** [comment]
Microsoft has removed the "Flicks" options mentioned in the article. 
![grafik](https://user-images.githubusercontent.com/2805598/58911741-c83e4600-8718-11e9-915f-f03523ab6932.png)
I tried enabling/disabling a lot of other Windows settings but the problem persists.

I also didn't find WinTab "labeled" drivers for my tablet. However, I tried disabling the "new" Windows Ink option in the Wacom settings (to fallback to WinTab drivers, which are apparently included). The change had no effect on the gtk3-demo nor Xournal++ (gtk3-demo still recognizes the eraser).

**Comment by LittleHuba** [comment]
So as far as I got this you still have the problem that there are no devices shown in the settings dialog?
That can only be fixed by GTK devs.

Unfortunately that also means we are unable to help you until that is fixed.

**Comment by LittleHuba** [comment]
And just to make sure: Did you restart after switching to WinTab?

**Comment by michaelschufi** [comment]
> And just to make sure: Did you restart after switching to WinTab?

Yes, I did.

> So as far as I got this you still have the problem that there are no devices shown in the settings dialog?

If you are referring to the new #1151 merge, then yes.

**Comment by LittleHuba** [comment]
New proposal for solution:
We log all devices that were recognized by the input system, which should include also those devices that are not listed by GdkSeat for some reason.
These devices are then added to the list of devices in the settings dialog.

This will allow users to also map these devices to user specified classes.

**Comment by LittleHuba** [comment]
@michaelschufi please try the linked PR #1242 for functionality. I could unfortunately not test whether it works as expected.

**Comment by LittleHuba** [comment]
Please be aware that devices which were previously not listed have to be used once before opening the preferences to be listed.

**Comment by michaelschufi** [comment]
I get "No devices were found.". I tried drawing with the tip of the pen and also switching to the eraser. Can I somehow help you by providing more info?

**Comment by LittleHuba** [comment]
You definitely checked out the new branch and activated the new input system again?

**Comment by michaelschufi** [comment]
I am sure. I also tried: disabling the input system + restart and re-enabling it + restart, as well as disabling Windows Ink in the Wacom drivers.

Btw, I get the following warnings in the mingw64 terminal:

```
$ ./src/xournalpp.exe

** (xournalpp.exe:15012): WARNING **: 23:56:03.645: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(xournalpp.exe:15012): Pango-WARNING **: 23:56:03.720: couldn't load font "C059 Not-Rotated 6.3994140625", falling back to "Sans Not-Rotated 6.3994140625", expect ugly output.

** (xournalpp.exe:15012): WARNING **: 23:56:12.016: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


** (xournalpp.exe:15012): WARNING **: 23:56:12.031: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!

** Message: 23:56:39.751: MemoryLeak: sum 0 objects.
```

**Comment by LittleHuba** [comment]
Should be solved by #1318 please comment if not.

**Comment by Leinadh** [comment]
Heyyy!!!
If you are using a Wacom tablet, disable Windows Ink. That worked for me
![image](https://user-images.githubusercontent.com/34753158/93815753-192ec200-fc1c-11ea-9780-0b301bce3f74.png)

**Comment by ronysaha718** [comment]
> Heyyy!!! If you are using a Wacom tablet, disable Windows Ink. That worked for me ![image](https://user-images.githubusercontent.com/34753158/93815753-192ec200-fc1c-11ea-9780-0b301bce3f74.png)

Thank you! This helped me get things going.
