### ISSUE TITLE
Switching to a selection tool should autoselect any currently editing text object

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1169]
**Is your feature request related to a problem? Please describe.**
When I'm editing a text object and I want to reposition it, I have to switch to the select tool. But then I have to reselect the text object, which is annoying.

**Describe the solution you'd like**
Switching to a selection tool while a text object is being edited should select the text object automatically. 

**Describe alternatives you've considered**
Allow a text object to be repositioned by a drag (would require quite a few changes).

**How to implement**
Edit these lines: https://github.com/xournalpp/xournalpp/blob/dd30d205f753b83b611f7e9120ef2192a5f7b033/src/control/Control.cpp#L632-L649
In each case, check if a text object is being edited. If so, set the selection to that text object.

**Comment by forgottosave** [comment]
I'll have a look at this issue in the next days

**Comment by WillNilges** [comment]
@Technius  Did this get closed in #4315 ?

**Comment by Technius** [comment]
Yes.
