### ISSUE TITLE
String_new branch fills lines into large areas

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#117]
The new branch fills large sections for me. The attached document is the result from drawing a single curved line with the pen. It forms the large bubble. The type of stroke I drew is shown in progress in the upper right.

![xpp-err](https://cloud.githubusercontent.com/assets/759592/7282020/373c1606-e8fb-11e4-9705-3b130e1fac53.png)

**Comment by andreasb242** [comment]
I can confirm this behaviour.
The problem seems to be a much to big line size (Zoom a little, to force a complete repaint)

**Comment by MarPiRK** [comment]
Please check if it still exists with my last commits from MarPiRK/xournalpp.
I accidentally removed one property from Stroke basing on cppcheck report.

**Comment by andreasb242** [comment]
MarPiRK/xournalpp is not building for me, but I added the width attribute again, so it's now working at the xournalpp/string_new branch
