### ISSUE TITLE
Allow hiding tool bars

### ISSUE THREAD

**Issue by dbosk** [xournalpp/xournalpp#1171]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that must screen space is used by the tool bars (icons for saving, changing tools etc.) which I rarely use.

**Describe the solution you'd like**
I'd like to be able to hide the tool bars, possibly choose a subset to hide. For instance, now there are two rows of tools: top one is save, new document, etc.; bottom is for choosing pen, colors etc. I'd like to hide at least one of these and sometimes both. It would also be nice to shrink the bar at the bottom: with page counter, layer background, zoom etc.

**Describe alternatives you've considered**
Using F10 to remove the menu bar and F11 to go full screen brings more space, but not enough.

**Comment by LittleHuba** [comment]
Already implemented. 
Take a look at `View->Toolbars`

**Comment by dbosk** [comment]
I totally missed that one. I looked for something to hide them, so I 
guess I just overlooked this one, but this is truly great! Thanks a lot 
and sorry for the noise!

**Comment by LittleHuba** [comment]
No worries - happy to help 😉
