### ISSUE TITLE
Automated build and release process

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1176]
# The problem

As the project grows in size and complexity, we need to have a more comprehensive and automated build system. We currently make manual releases, which is time consuming and error prone.

* Builds for all platforms should be automated. Currently, we only have Travis building on Linux.
* Every version compiled by whatever CI platform we're using should be uploaded as an "unstable" or "nightly" release. This will be very helpful to people who want to try bleeding edge builds but don't have the technical knowledge to compile their own version.
* Any tag pushed to the repo should draft a release on GitHub; the release should then be approved by a maintainer. This will make it far easier to do a release and standardize the release binaries.
* We need to not just build the executable, but also distro-specific packages such as `.deb` files and `.rpm` files. We should also build a generic AppImage for other distros. Related issues: #1013, #1177
* Once the build is automated, we need a "Release Guide" which describes what changes are required to the source code (such as updating version numbers) to create a new release.

# My personal opinion

Travis supports what we want right now, but it's not exactly in the best hands right now. We should switch to a CI platform such as CircleCI, AppVeyor, Azure Pipelines, or GitLab CI (I prefer GitLab CI). Bleeding edge builds can be hosted on GitHub, but it would be better to host them on the CI platform that we pick (since GitHub can only store one bleeding edge release at a time, while CI platforms generally host all built versions).

In any case, I have some experience setting up CI for projects, so I'm willing to make these proposed changes. I would appreciate any feedback, so let me know what you think!

# Progress

This meta-issue will track progress on the aforementioned goals.
* [x] Azure Pipelines setup #1244 
* [x] AppImage support #944 
* [x] `.deb` packages #1013, #959 
* [x] `.rpm` packages
* [x] Windows builds #1127 
* [x] Mac builds
* [x] flatpak #1177 
* [x] Create draft releases on tag push
* [ ] Artifactory/bintray setup with nightly releases
* [ ] Release guide

**Comment by JJones780** [comment]
Looks like Travis and Azure Pipelines are the only ones offering windows builds?
I also came across a mention of [buildkite.com](https://buildkite.com) on [YCombinator](https://news.ycombinator.com/item?id=18978251);  it does do Windows builds but they cheat a bit... it does the builds on machines we supply ( running agents to communicate with their servers ).

**Comment by LittleHuba** [comment]
There is not really a requirement to host all distributions on one CI platform. It is some overhead to work on multiple but if it enables us to use better platforms that makes it worth.

**Comment by LittleHuba** [comment]
I would actually stick with TravisCI as long as we can. Should it really go downhill with the new owner we can still switch to other platforms. By then there might be some that support Windows builds along with Linux and MacOS.

**Comment by TheAssassin** [comment]
I always recommend to just write a script that builds an AppImage in one go in a separate temporary build directory to make sure everything's clean and is not influenced by custom user options, and all potential optimizations can be run without damaging anything.

I have a ton of example scripts ready, and I plan to later take one of these and adjust it so it works for xournal++ (mainly for my personal needs). If you're interested, I'll send a PR. Then you can just integrate it in your CI workflows however you want. The advantage of such a script is, it doesn't matter what platform you're building on (be it Travis or GitLab CI or whatever else service, maybe even self hosted), all you need to do is write the little bit of script code that installs the dependencies and then calls that script (and maybe uploads it to somewhere afterwards).

**Comment by TheAssassin** [comment]
Also, consider uploading AppImages for every new commit. That way, you and your users can test the new builds easily without having to deal with the hassle of building software themselves. There's [uploadtool](https://github.com/probonopd/uploadtool) which creates a new prerelease for every new commit and uploads binaries built on Travis. Can also be used to upload additional distribution formats.

**Comment by TheAssassin** [comment]
Filed a [PR](#1182) adding an [appimagecraft](https://github.com/TheAssassin/appimagecraft) config file. Using appimagecraft, you can simply build an AppImage without any hassle (all you need is the dependencies installed on your computer, please refer to the README or Wiki or `.travis.yml` or so).

Please [build on the oldest possible system](https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems) (you seem to use Travis, which uses some Ubuntu LTS, which is good already) to get AppImages with maximum compatibility.

**Comment by Technius** [comment]
Windows support on Travis is still in beta, so it might not be easy to set up. The ideal scenario is that it works, but in the case that it doesn't, we'll have to set up another CI platform (which we'll also have to maintain, creating more work...).

For distro-specific packaging on Linux, I've had good experiences with [fpm](https://github.com/jordansissel/fpm). Packging with it is as simple as calling `fpm` with the correct flags in a script. As a bonus, fpm can also package for mac.

We should consider using Artifactory and Bintray to host our release binaries, since they're free (for OSS) and pretty well-supported.

@TheAssassin Thanks for the suggestions, I'll be taking a look at them. AppImages definitely sound like a good idea to me. I'm not too keen on having a dependency that's extremely new, though.

**Comment by TheAssassin** [comment]
We can always replace it by a hardcoded bash script. But I don't think that's necessary, and you won't benefit from future improvements to the tool. Your call.

**Comment by TheAssassin** [comment]
Looks like @LittleHuba implemented auto-releases now. Can we integrate AppImage builds into that? That's just another CI job that produces an artifact.

**Comment by LittleHuba** [comment]
@TheAssassin If you can provide me with a step by step guide on how to generate a AppImage of Xournal++ then I can setup a release pipeline.

**Comment by TheAssassin** [comment]
You need to get appimagecraft, either by downloading the ready-to-use AppImage from https://github.com/TheAssassin/appimagecraft/releases/download/continuous/appimagecraft-x86_64.AppImage, or by installing it via `pip` (it's a Python tool) like `pip install -e git+https://https://github.com/TheAssassin/appimagecraft/#egg=appimagecraft`.

Then call it in the repo root:

```
# AppImage
> ./appimagecraft-x86_64.AppImage build
# virtualenv or otherwise installed with pip
> appimagecraft build
```

An AppImage will be produced in a temporary build dir (can be changed, if you have to) and will in the end be moved into the root of the repo again. The file naming is `Xournal++-*.AppImage`.

I will try to document appimagecraft better tonight, I haven't got to working on it really in the last weeks. But it works fine. I built a fresh AppImage right before posting my last comment to get a newer version.

appimagecraft is not a regular build processor, it generates bash scripts and then runs them. Therefore, if you want to inspect what's going on, use the `genscripts` command, and it'll generate the scripts into a location you specify. You can then look into them.

**Comment by LittleHuba** [comment]
I'll look into that once @Technius has merged his CPack routines into our pipelines.

**Comment by LittleHuba** [comment]
Building on MacOS is fixed as of #1353 but the current CI pipeline uses Brew and is unable to provide an `.app`. We need to add another pipeline following our [build instcrutions for MacOS](https://github.com/xournalpp/xournalpp/blob/mac-ci-builds/mac-setup/README.md) which provides the artifact.

As I do not have any Mac that fits the requirements to build it, this has to be done by somebody else.

**Comment by WillNilges** [comment]
I noticed that there is no issue open for `.rpm` packages. @LittleHuba sorry if this is one of those older issues to not revive, but since I'd like to avoid `flatpak` in favor of `dnf`, I thought I'd ask what the deal is with Fedora support in general. I've been pondering maintaining a .rpm package.

**Comment by Technius** [comment]
> I noticed that there is no issue open for `.rpm` packages. @LittleHuba sorry if this is one of those older issues to not revive, but since I'd like to avoid `flatpak` in favor of `dnf`, I thought I'd ask what the deal is with Fedora support in general. I've been pondering maintaining a .rpm package.

We haven't seen any requests for `.rpm` packages so far, so it has been low priority. We'd be happy to help you if you're willing to work on a PR for `.rpm` configuration, which would mostly consist of modifying `CMakeLists.txt` to have [CPack RPM configuration](https://cmake.org/cmake/help/v3.7/module/CPackRPM.html).

Ideally, we'd also want to set up CI configuration to make sure it compiles and packages correctly. That's either something I or @LittleHuba can add when we get the PR.

**Comment by WillNilges** [comment]
Excellent. I should have some time to look into this in the next few days.

**Comment by WillNilges** [comment]
So I've been chipping away at this and trying a few different things, but I've been having a few problems. I'm going to open an issue for this endeavour. See #1661

**Comment by Technius** [comment]
Closing this issue because we've automated almost everything.
