### ISSUE TITLE
Publish flatpak to Flathub

### ISSUE THREAD

**Issue by alexruetz** [xournalpp/xournalpp#1177]
Since can build a flatpak of xournalpp thanks to #857 i think it would be good from a user perspective to publish that to flathub.

Are there plans for that?

**Comment by BrainBlasted** [comment]
Would there be any issue if I cleaned up the manifest there and submitted a PR on the flathub repo?

**Comment by Technius** [comment]
Feel free, we're still working on getting some other parts of the build system to work before moving on to this.

**Comment by nedrichards** [comment]
We've accepted the app onto flathub. If upstream wants to take charge/be added just let us know github usernames and we'll sort it out.

**Comment by mabachel** [comment]
I cannot find xournalpp / xournal++ on https://www.flathub.org/. Not only the recently published 1.0.14 is missing but any version at all.

**Comment by Technius** [comment]
This should be fixed now.
