### ISSUE TITLE
libzip dependency configured incorrectly in CMakeLists

### ISSUE THREAD

**Issue by moghiseh** [xournalpp/xournalpp#1180]
Compiling on linux has problem with libzip library. `pkgconfig` finds the right version of libzip but it try to links with only library without path of libzip. Therefore trying to find libzip in linking step fails. Here is the fix:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 856b116..77b045c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -88,7 +88,7 @@ add_includes_ldflags ("${ZLIB_LIBRARIES}" "${ZLIB_INCLUDE_DIRS}")
 
 # libzip
 pkg_check_modules (ZIP REQUIRED "libzip >= 1.0.1")
-add_includes_ldflags ("${ZIP_LIBRARIES}" "${ZIP_INCLUDE_DIRS}")
+add_includes_ldflags ("${ZIP_LDFLAGS}" "${ZIP_INCLUDE_DIRS}")
 
 # pthreads
 find_package (Threads REQUIRED)
```

**Comment by LittleHuba** [comment]
Could you please provide some information on the distribution you are using?

**Comment by moghiseh** [comment]
```
Distributor ID: RedHatEnterpriseWorkstation
Description:    Red Hat Enterprise Linux Workstation release 7.6 (Maipo)
Release:        7.6
Codename:       Maipo
```

**Comment by Technius** [comment]
We should be using `target_link_libraries` in `CMakeLists.txt` instead of adding the linker flags.

**Comment by Technius** [comment]
Nevermind, `target_link_libraries` is used in `src/CMakeLists.txt`, so it's just the following two lines in `/CMakeLists.txt` that need to be changed:
https://github.com/xournalpp/xournalpp/blob/57591e77a397efb3883a3b95f7cc7cc10b7dd23a/CMakeLists.txt#L87-L91
