### ISSUE TITLE
Signal 11 Crash when scrolling

### ISSUE THREAD

**Issue by GammaPi** [xournalpp/xournalpp#1185]
When I use stylus to scroll an annotated pdf, xournal++ crashes occasionally.

user@hostname:~$ xournalpp
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Gtk-Message: 21:09:41.083: GtkDialog mapped without a transient parent. This is discouraged.

** (xournalpp:7800): WARNING **: 21:10:00.199: Could not create backup! (The file was created from an older Xournal version)

** (xournalpp:7800): WARNING **: 21:10:55.222: GladeGui::get: Could not find glade Widget: "cbNewInputSystemTPCButton"

(xournalpp:7800): Gtk-CRITICAL **: 21:10:55.222: gtk_toggle_button_set_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

** (xournalpp:7800): WARNING **: 21:12:19.946: [Crash Handler] Crashed with signal 11

** (xournalpp:7800): WARNING **: 21:12:19.947: [Crash Handler] Wrote crash log to:**PATH TO THE FOLLOWING FILE**

** (xournalpp:7800): WARNING **: 21:12:20.198: Trying to emergency save the current open document…

** (xournalpp:7800): WARNING **: 21:12:20.407: Successfully saved document to "**PATH TO THE FOLLOWING FILE**"

**Error log saved:**
Date: Sun May 26 20:47:05 2019
Error: signal 11
[bt]: (0) xournalpp(+0x1a97ad) [0x55d4697777ad]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fc45130bf20]
[bt]: (2) xournalpp(_ZN17NewGtkInputDevice10getXournalEv+0x1) [0x55d469720281]
[bt]: (3) xournalpp(+0x1507f0) [0x55d46971e7f0]
[bt]: (4) xournalpp(+0x1afd9e) [0x55d46977dd9e]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x2c080) [0x7fc454826080]
[bt]: (6) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x155) [0x7fc4535a1285]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650) [0x7fc4535a1650]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7fc4535a1962]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main+0x85) [0x7fc454d1fa25]
[bt]: (10) xournalpp(_ZN11XournalMain3runEiPPc+0x8b5) [0x55d469681205]
[bt]: (11) xournalpp(main+0x30) [0x55d4696597f0]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc4512eeb97]
[bt]: (13) xournalpp(_start+0x2a) [0x55d469659c4a]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1a9bab) [0x55d469777bab]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fc45130bf20]
??:0
[bt] #3 xournalpp(_ZN17NewGtkInputDevice10getXournalEv+0x1) [0x55d469720281]
??:0
[bt] #4 xournalpp(+0x1507f0) [0x55d46971e7f0]
??:0
[bt] #5 xournalpp(+0x1afd9e) [0x55d46977dd9e]
??:0
[bt] #6 /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x2c080) [0x7fc454826080]
??:0
[bt] #7 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x155) [0x7fc4535a1285]
??:0
[bt] #8 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650) [0x7fc4535a1650]
??:0
[bt] #9 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7fc4535a1962]
??:0
[bt] #10 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main+0x85) [0x7fc454d1fa25]
??:0
[bt] #11 xournalpp(_ZN11XournalMain3runEiPPc+0x8b5) [0x55d469681205]
??:0
[bt] #12 xournalpp(main+0x30) [0x55d4696597f0]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc4512eeb97]
??:0
[bt] #14 xournalpp(_start+0x2a) [0x55d469659c4a]
??:0
Date: Tue May 28 11:18:25 2019
Error: signal 11
[bt]: (0) xournalpp(+0x1a97ad) [0x557f18a297ad]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f20fd056f20]
[bt]: (2) xournalpp(_ZN17NewGtkInputDevice10getXournalEv+0x1) [0x557f189d2281]
[bt]: (3) xournalpp(+0x1507f0) [0x557f189d07f0]
[bt]: (4) xournalpp(+0x1afd9e) [0x557f18a2fd9e]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x2c080) [0x7f2100571080]
[bt]: (6) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x155) [0x7f20ff2ec285]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650) [0x7f20ff2ec650]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xc2) [0x7f20ff2ec962]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main+0x85) [0x7f2100a6aa25]
[bt]: (10) xournalpp(_ZN11XournalMain3runEiPPc+0x8b5) [0x557f18933205]
[bt]: (11) xournalpp(main+0x30) [0x557f1890b7f0]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f20fd039b97]
[bt]: (13) xournalpp(_start+0x2a) [0x557f1890bc4a]

**Comment by LittleHuba** [comment]
Please update to the newest release and try the new input system (enable it in the settings).

**Comment by GammaPi** [comment]
> Please update to the newest release and try the new input system (enable it in the settings).

I installed via apt and enabled "new input system" option marked as experiment. I'll try to see if it fixes the issue~

**Comment by GammaPi** [comment]
The problem is gone after I switched to the new input system.

**Comment by GammaPi** [comment]
I think  #1141 is related.
I'm using bamboo ct671 on ubuntu 18.04(desktop is gnome).

**Comment by LittleHuba** [comment]
Good if the new input system resolves that issue, I wont search for the bug in the old one.

#1141 is most likely not related, as the issue persists in the new input system and the stack trace of the crash is completely different.

**Comment by theniwo** [comment]
The hand tool doesn't work with the new input method when the hand tool is mapped to a button on the pen
