### ISSUE TITLE
LaTeX preamble customization

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1188]
**Is your feature request related to a problem? Please describe.**
I want to be able to customize the preamble of the LaTeX template so I can e.g. add additional packages or define custom variables.

**Describe the solution you'd like**
There should be a setting that allows users to customize the preamble. This setting could be global, or preferably, per-document (for example, you may want to define variables specific to the document being worked on).

**Describe alternatives you've considered**
We can implement a more limited subset of the preamble feature, such as packages or custom variable names.

**Additional context**
Per-document settings would first require the addition of a "Document Settings" dialog that can be used to configure options for a particular document.

**Comment by LittleHuba** [comment]
See #1115

**Comment by MichelReims** [comment]
Hello
In xournalpp-1.1.0 + dev-nightly.20200608-windows, there is no possibility to configure a style file for latex in Edit / preferences

**Comment by Technius** [comment]
> Hello
> In xournalpp-1.1.0 + dev-nightly.20200608-windows, there is no possibility to configure a preambule file for latex in Edit / preferences. There is no LaTeX tab

This feature is still under development and will not be available until I have finished testing it (eta: next week).

**Comment by MichelReims** [comment]
Thank you for that clarification.
Have a good day

**Comment by MichelReims** [comment]
and congratulations for the work done on xournal ++
