### ISSUE TITLE
Crash & Leak on Exit if Toolbar Customization Dialog Left Open

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1189]
**Affects versions :**
Reproduced on V1.0.7 as well as latest development version (1.0.11) on Linux.

**Describe the bug**
Segfault on exit after a multitude of errors reported including
```
Type check: id was negative (-24), object is already deleted!?
** (xournalpp:12960): WARNING **: MemoryLeak: 1 objects of type: GladeGui

** (xournalpp:12960): WARNING **: MemoryLeak: 1 objects of type: ToolbarCustomizeDialog

** (xournalpp:12960): WARNING **: MemoryLeak: 11 objects of type: XojColor

** (xournalpp:12960): WARNING **: MemoryLeak: 1 objects of type: CustomizeableColorList


```

**To Reproduce**
1. Run xournal from command line 
2. Open Toolbar customization dialog ( View->Toolbars->Customize )
3. close xournal++ while dialog is still open.

**Expected behavior**
Clean shutdown.

**Additional context**
Try with and without sidebar open.

**Comment by JJones780** [comment]
Hmm.. sometimes I only get the memory leaks and no crash.
Will investigate further.

**Comment by lehmanju** [comment]
@JJones780 Is this still an issue? I remember most of the memory leaks have been fixed ...

**Comment by Technius** [comment]
This doesn't happen on `master` anymore.
