### ISSUE TITLE
For "Highlighter" and "Pen" cursor almost not visible on page

### ISSUE THREAD

**Issue by demiurg337** [xournalpp/xournalpp#1191]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Ubuntu 18.04.2 LTS
 - Version of Xournal++: master, commit 1b69019c98c77dc2d2ba3b4d2c9b947e49402eb4

**Describe the bug**
For "Highlighter" and "Pen" cursor almost not visible on page (has size 1px or less) and hard to see current position of mouse cursor. 

Mouse cursor can be increased?

P. S.
I can to try to fix it (if it is real bug), if you don't mind.

**Comment by LittleHuba** [comment]
Take a look at the preferences "big cursor" and "highlight cursor"
