### ISSUE TITLE
Consider switching default cursor type to large

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1192]
There's been multiple issues concerning the visibility of the cursor (e.g. see #1191 #1077 #974). I believe that this confusion is frequent enough to warrant changing the default cursor size to the big cursor.

**Comment by LittleHuba** [comment]
I'm actually not really of your opinion, as there are a lot of people that do not complain about this but just use Xournal++. We only get to know about the problems and not about all the cases where it goes well.

I would add this to the FAQ. That should be sufficient.

**Comment by JJones780** [comment]
Personally, I would prefer to see the standard operating system cursor as default with preferences to enable the other options ( dot, pen , highlight ).

I would consider this a "paper cut" issue. A new tag is born!

**Comment by Technius** [comment]
So we've got more confusion with the default cursor size: #1201

If we aren't going to change the default cursor size, we should at least provide a "welcome popup" that indicates that the default size can be changed.

**Comment by LittleHuba** [comment]
I added a better fix to #1151 that switches the cursor to GTK_ARROW if you use the mouse. When using the Stylus or Touch it is reset to the small cursor.

**Comment by petergthatsme** [comment]
@LittleHuba

    I merged a change in where we actually use the normal system cursor when moving the mouse and switch to the small cursor if one uses pen or touch. This should actually fix this issue quite nicely.

I personally find the system cursor (arrow) very distracting when I'm trying to write and prefer just the dot that was the default before. Perhaps making this something the user could select, is an option?

**Comment by LittleHuba** [comment]
This is already possible in the new input system. Just map your mouse to the pen input class.

**Comment by petergthatsme** [comment]
@LittleHuba 
ahhh, yes switching to the new input system and selecting "Merge button events..." indeed gets me back to the old behavior. Great - thanks!

**Comment by JJones780** [comment]
On the new input system ( currently a setting in preferences->InputSystem->Enable New Input System ) - If you are writing with a stylus it shouldn't switch back to the system cursor unless you touch the mouse. 
Does this work for you?

**Comment by petergthatsme** [comment]
yup, it's working nicely - thanks!
