### ISSUE TITLE
Crackling noises when playing audio recording

### ISSUE THREAD

**Issue by Faberix** [xournalpp/xournalpp#1193]
When playing recorded audio using Xounal++, the audio is not played as expected (at least on my two linux machines). Xournal++ plays the audio with a lot of crackling noises, making it really painful to listen to it. The audio is recorded correctly; when playing the related audio file with any other program, it might not be the best quality, but there are no crackling noises.
The crackling noises exist in all possible configurations of output device that work at all.
I uploaded a few test files that I created by playing an audio book on another computer and recording it using Xournal++. AudioFile.ogg is the file recorded by Xournal++, AudioFile-played.flac AudioFile.ogg played with my default player and recorded and XournalAudio is the audio output of Xournal++ (recorded with the same microphone).
I also uploaded the output of Xournal++ while playing the test audio (when run from console). It contains three runs:

1. playing and killing Xournal++ while it was playing
2. playing and using the stop button (it crashed, as it was probably mentioned in issue "xournalpp crashes after playing recording)
3. playing, pausing and then stopping using the buttons

For the these tests, I always used pulse for both input and output device.
I also played it with sysdefault as output device, which resulted in a crash after playing a few seconds (the crackling noises where present, too; output is in xournalpp-output-sysdefault.txt)

It appears that there is a memory leak. That might not be related to my issue, though.

[xournalpp-output.txt](https://github.com/xournalpp/xournalpp/files/3243762/xournalpp-output.txt)
[xournalpp-output-sysdefault.txt](https://github.com/xournalpp/xournalpp/files/3243775/xournalpp-output-sysdefault.txt)

[audioFiles.zip](https://github.com/xournalpp/xournalpp/files/3243747/audioFiles.zip)

expected behavior: Xournal++ plays audio as it is stored in the file

OS: Ubuntu and Kubuntu 19.04
Xournal++ version: 1.0.11

Steps to reproduce: record something and play it using xournal++

**Comment by LittleHuba** [comment]
I'm aware of this bug and the easiest way to fix this is reducing the audio gain significantly when recording. I'll have to dig for the actual fix. Could you try #1190 concerning the crashes?

**Comment by LittleHuba** [comment]
And please provide the errorlogs.

**Comment by LittleHuba** [comment]
The fix might only work with new recordings. Other audio players do heavy remodeling of the audio samples to make them hearable again. We cannot do this unfortunately.

**Comment by Faberix** [comment]
I have now uploaded my errorlogs in case you still need them (sorry for the late response...). They don't seem to contain much useful information, though.

[errorlog.20190601-143028.log](https://github.com/xournalpp/xournalpp/files/3263449/errorlog.20190601-143028.log)
[errorlog.20190601-145525.log](https://github.com/xournalpp/xournalpp/files/3263450/errorlog.20190601-145525.log)
[errorlog.20190601-145559.log](https://github.com/xournalpp/xournalpp/files/3263451/errorlog.20190601-145559.log)
[errorlog.20190601-150042.log](https://github.com/xournalpp/xournalpp/files/3263452/errorlog.20190601-150042.log)

**Comment by LittleHuba** [comment]
Could you build #1190 manually and look if the problem persists?
Please test these two cases:
- Playing an old recording
- Doing a new recording and playing it

Look for both cases if the crackling persists and generally if you find another crash.

**Comment by Faberix** [comment]
Playing a new recording works fine with the fix, but the issue still persists while playing an old one.

**Comment by LittleHuba** [comment]
You may try to resample the old recordings with VLC. That might help. Unfortunately we can't do much here as it would go way beyond the scope of Xournal++ to resample audio files.
