### ISSUE TITLE
White pen invisible on white background

### ISSUE THREAD

**Issue by cimm** [xournalpp/xournalpp#1201]
**Affects versions:**
 - OS: Ubuntu 18.04
 - Version of Xournal++: 1.0.11

**Bug**
The pencil is too small, even invisible if the selected color is the same as the background color.

**To Reproduce**
1. Open the Xournal++ application
2. Select the pen tool and select white as pen color
3. Given a white background the pen is completely invisible.

**Expected behavior**
Some visual indication to find the pen/cursor position. It's really hard to position the pen correctly if you can't see where the cursor is. Not sure if it's related but the pen size does not seem to change the very fine to very thick pencil sizes are all 1px in size. The drawn object (arrow, rectangle, circle, etc.) have the correct size.

![screenshot](https://user-images.githubusercontent.com/68112/58827970-9fe51780-8644-11e9-8279-64f4c164d1ee.png)
_Spot the green cursor (on a white background)_

Thanks for the hard work on this great PDF annotating tool!

**Comment by Technius** [comment]
You can change the cursor size to a larger one or highlight the position:
![image](https://user-images.githubusercontent.com/1066652/58828162-ac904e00-85f9-11e9-95b6-c2b408fa113d.png)

**Comment by Technius** [comment]
Also, it might be better if the cursor color was set to the negative color of the pixels it is hovering over rather than set to the selected color. This would avoid problems of having the cursor be the same color as its background, while keeping the cursor visible at all times.

**Comment by cimm** [comment]
The negative color of the pixels it's hovering over would be a better default IMHO, harder to loose the cursor.

Activating the cursor highlight is a good workaround for now, thanks for the quick response!

**Comment by JJones780** [comment]
There is no XOR mode for cursors on most operating systems (!). We could define a cursor that had two colours or we could inspect the colour under the cursor continuously and change the cursor accordingly.
I'd vote for a 4 or bigger pixel cursor and the highlight ( or a re-designed big cursor ) as default.

**Comment by LittleHuba** [comment]
The most common way to do this is to make a border around the cursor in the opposite color. Then it is visible independent from the background. 

I merged a change in where we actually use the normal system cursor when moving the mouse and switch to the small cursor if one uses pen or touch. This should actually fix this issue quite nicely. 

Your opinion?

**Comment by JJones780** [comment]
Yes, I think it works pretty well!  This would be my preference.

I also tried making it change to the pen cursor when the mouse button is down but I'm not sure that adds much.
One thing I noticed is that the big pen and dot show the current colour so some users might prefer it? 
The user might also prefer to see the eraser before applying it? 

Anyone else want to comment?

**Comment by LittleHuba** [comment]
We could invert the border of the cursor to the color of it. That might help...

**Comment by JJones780** [comment]
The cursor no longer changes during editing of object ( i.e. hover over control points ). I tried with the mouse and with stylus. I'll look into it further soon.

**Comment by petergthatsme** [comment]
@LittleHuba 

> I merged a change in where we actually use the normal system cursor when moving the mouse and switch to the small cursor if one uses pen or touch. This should actually fix this issue quite nicely.

I personally find the system cursor (arrow) very distracting when I'm trying to write and prefer just the dot that was the default before. Perhaps making this something the user could select, is an option?

**Comment by JJones780** [comment]
This was fixed in #1222 and #1257.
