### ISSUE TITLE
Dialogs as well as dropdown menus of toolbar icons opening on different monitor while using stylus

### ISSUE THREAD

**Issue by michaelschufi** [xournalpp/xournalpp#1204]
**Affects versions :**
 - OS: Windows 10
 - Xournal++ 1.0.12

**Describe the bug**
The dropdown menu of the toolbar icons (pen/eraser/shape/tool) opens on another monitor while using the stlyus as input. (see screenshot)

**To Reproduce**
1. Start Xournal++
2. Use the stylus to try to change the pen/eraser stroke behaviour.
3. Dropdown menu opens below the toolbar arrow and but is horizontally misaligned.

**Expected behavior**
Dropdown menu opens below the toolbar arrow and is left aligned to the toolbar icon.

**Screenshots of Problem**
![Problem](https://user-images.githubusercontent.com/2805598/58874211-7372df00-86c8-11e9-9c55-f9c39b353ce5.png)

**Additional context**
I have a setup of 3 monitors horizontally aligned like 2,1,3 with #1 being my primary one.

The menu opens always on the monitor to the left:

|Monitor Xournal++ runs in|Monitor menu opens in|
|-|-|
|2|2 (okay, not misaligned!)|
|1|2|
|3|1|

**Comment by michaelschufi** [comment]
Actually, this happens with a lot of other "popups" too, like "Preferences" or "About". But, interestingly, _not_ with File -> Open, File -> Export or "Pick a Font".

**Comment by JJones780** [comment]
Interesting...  I've seen something similar before with another gtk program and os.

I had a quick look over on GTK's list of issues and it is indeed listed: [GTK bug #1477.](https://gitlab.gnome.org/GNOME/gtk/issues/1477)


Thank you for reporting the bug but we will have to wait for the GTK team to fix it.

_p.s. Note that that user reports that everything works fine if the leftmost display is main. That may suffice as a work-around for you?_
