### ISSUE TITLE
Device class settings tab memory leak

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1208]
**Affects versions :**
 - OS: Linux
 - Version of Xournal++: master as of 667eff4

**Describe the bug**
Closing xournalpp after seeing the "Input System" tab in the Preferences window will report a memory leak.
```plain
** (xournalpp:13964): WARNING **: 11:14:55.820: MemoryLeak: 1 objects of type: GladeGui

** (xournalpp:13964): WARNING **: 11:14:55.820: MemoryLeak: 1 objects of type: DeviceClassConfigGui
** Message: 11:14:55.820: MemoryLeak: sum 2 objects.
```

**To Reproduce**
1. Open xournalpp
2. Open the Preferences window
3. Click on the Input System tab
4. Close xournalpp

**Expected behavior**
No memory leak is reported.

**Additional context**
Valgrind reports that the memory is allocated here:
https://github.com/xournalpp/xournalpp/blob/667eff45f1c272fa1be65da53ca52f02ccea655c/src/gui/dialog/DeviceClassConfigGui.cpp#L13
so the memory leak probably isn't within `DeviceClassConfigGui`, but somewhere else.

**Comment by LittleHuba** [comment]
Just fixed a second ago with #1209
