### ISSUE TITLE
Floating toolbox not showing up

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#1210]
**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++ : 1.0.11 compiled from source just now

**Bug description:**
After setting "Floating toolbox" as preferred mouse right action, right-clicking on any Item open up a tiny white rectangular box instead of the toolbox, as if it couldn't load.
No errors are being reported on the shell

![image](https://user-images.githubusercontent.com/20294254/58904132-311cc280-8707-11e9-96dc-1148d1d0a406.png)

**Comment by LittleHuba** [comment]
That is actually only the empty floating toolbox. You need to put tool-buttons into the toolbox or select the toolbar layout.
