### ISSUE TITLE
Pen strokes don't appear in real-time after searching

### ISSUE THREAD

**Issue by veecue** [xournalpp/xournalpp#1217]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++ master

**Describe the bug**
Pen strokes don't appear in real-time after searching

**To Reproduce**
1. Start Xournal
2. Do some pen input
3. Search the document for something
4. Cancel the search
5. Try pen input again. The strokes will only appear after the pen is lifted off the display (the stroke is finished)

**Expected behavior**
Search should not influence pen behaviour at all

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by LittleHuba** [comment]
This problem also exists when the search is still active. Each stroke will be shown when the input finishes.

**Comment by LittleHuba** [comment]
The problem is that searching changes the viewport of the journal. This influences which part of the viewport is redrawn. The region that is redrawn is offset and has the wrong size. Additionally strokes are drawn with the wrong zooming factor.

**Comment by JJones780** [comment]
I've got this solved.. putting together patch now.
