### ISSUE TITLE
Update dependencies to match Ubuntu 16.04 LTS, add C++ GTK bindings

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1218]
## Summary
Since Ubuntu 14.04 LTS is now EOL, we should consider matching dependency versions with Ubuntu 16.04 LTS. We should
* Enable C++14 (supported by the gcc version in Ubuntu 16.04)
* Update `glib` version to `2.48`

To help the development of new code, I also recommend adding the official C++ bindings to GTK:
* `glibmm`
* `gtkmm`

## Timeframe

This should be accomplished by the next major release (i.e. Xournal++ 1.1, when major features such as the new input system, the floating toolbox, and the new file format are no longer experimental).

**Comment by LittleHuba** [comment]
We need to keep other distributions in mind as well. There are some with even further outdated libraries than Ubuntu. 

The new file format will take at least a few more months. I'm currently bogged down with other work. But the other things in your timeframe will work out.

**Comment by Technius** [comment]
Closing since the build config has changed in major ways since this issue was opened.
