### ISSUE TITLE
Draw polygon tool

### ISSUE THREAD

**Issue by alexandredias3d** [xournalpp/xournalpp#1221]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to highlight text with a different polygon than the rectangle tool. To do this, I have to select the line tool and draw the polygon manually without any help of the program to restrict movement like Inkscape and GIMP do. Also, I could not find a way to fill the contents of a "shape" created by the line tool.

**Describe the solution you'd like**
A new drawing tool that works similarly to how the *Draw bezier curves and straight lines (Shift + F6)* tool in Inkscape work could be added to Xournal++. This tool works as follows. The user chooses the first point.  After that, following points are chosen and they form a a line with the previous one. The last selected point closes the polygon.

**Additional context**
Here is a screenshot of this feature in Inkscape.
![A quadrilateral on the left and a triangle on the right](https://user-images.githubusercontent.com/25330126/59149035-aed21e00-89e6-11e9-8e2e-e24cbc6ce027.png)

It is also present on GIMP in the Free Select tool.

**Comment by LittleHuba** [comment]
Sounds like a very useful tool.

Recommendation for implementation:
To stop drawing further points the line is finished when a double click is received.

**Comment by Technius** [comment]
The line drawing part was implemented in #1688. Polygon fill has not been implemented yet.

**Comment by Technius** [comment]
Actually, polygon fill _has_ been implemented (I tested just now), so I'm closing this issue.
