### ISSUE TITLE
Ignore input immediately after ending selection with tap

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1225]
When you have the selection tool selected as one of the buttons and move/resize an object you can only end the selection by drawing a stroke or tapping into the gray area. It would be nice to have a green checkmark (maybe at the right side, opposed to the X), to get out of the selection tool. Else you have to always draw a stroke and then erase it again.

**Comment by luke-skywalker** [comment]
I can end the selection by just tapping outside of the selected area, then I change tool. This way no stroke is drawn, nor needs to be erased.

Yet, I think it's quite a good enhancement! It reminds me of the way [Lecturenotes handles selections](https://lecturenotes.fandom.com/wiki/Getting_started), which is quite intuitive and uses a green checkmark.

**Comment by coldspark29** [comment]
I though of this again. Maybe a check mark just bloats the screen and creates more distractions. We could just stay intuitive:

You can end the selection by tapping outside of the window. The only problem is that you make a stroke then and have to delete the small dot you created. This is really annoying. Maybe the best way is to just deactivate strokes when you tap outside of the selection and then immediately activate it again.

**Comment by LittleHuba** [comment]
> Maybe the best way is to just deactivate strokes when you tap outside of the selection and then immediately activate it again.

This should be quite easy and is default behaviour of other apps as far as I know.

**Comment by coldspark29** [comment]
Yes and for a reason: You have to end selections so often, that it is most convenient to be able to do this by clicking anywhere. If you always have to hit a checkmark it just gets annoying after some time. The X for deleting has its righteous place, but the check mark would be too much.

**Comment by Thomi7** [comment]
It looks like this issue has been resolved in some unmentioned PR (I couldn't find a relating closed PR). 
For me it's working on the latest master. When I select with my pen button and then click outside of the selection with the pen the first stroke is ignored. I think we should close this.

**Comment by Thomi7** [comment]
@LittleHuba May I close this issue?

**Comment by coldspark29** [comment]
I think so. It has been solved lately by just clicking outside of the resize area. I also realized that this needs a click more to continue drawing, but to me it is more intuitive.

**Comment by LittleHuba** [comment]
Yeah this was solved some time ago.
