### ISSUE TITLE
Select object fails after moving to overlap another object

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1227]
**Affects versions :**
 - OS: Linux
 - Version of Xournal++: master as of 3fa954c

**Describe the bug**
Select object sometimes doesn't select the clicked object if it is moved such that it overlaps with another object.

**To Reproduce**
1. Create a text object. 
2. Use Select Object to select the text field and move it around. Try this multiple times and observe that it is selected correctly.
3. Switch to the pen tool and enable Draw Rectangle.
4. Draw a rectangle somewhere away from the text field.
5. Switch to Select Object. Select the text field and move it inside the rectangle, then deselect the text field.
6. Attempt to select the text field. Neither the text field nor the rectangle will be selected.

**Expected behavior**
The text field should be selected.

**Screenshots of Problem**
![peekGHZW2Z](https://user-images.githubusercontent.com/1066652/59213205-2fb92300-8b69-11e9-91a3-5800eace1216.gif)

**Additional context**
The issue is probably somewhere in `PageViewFindObjectHelper.h`.

**Comment by JJones780** [comment]
I've noticed very recently that it's harder to select objects. 
Also... the selection isn't uniformly around the object. Is this due to a recent change or am I just noticing it?

**Comment by Technius** [comment]
If you mean the Select Object tool, I'm not sure. I only realized how finicky it was just recently (I mostly used Select Rectangle, which works fairly well).

**Comment by Technius** [comment]
The cause is that only the first object whose bounding box contains the selection point is checked for selection criteria:

https://github.com/xournalpp/xournalpp/blob/583a317ff1d63b8d65d4019b75fb27801e5c0098/src/gui/PageViewFindObjectHelper.h#L53-L63

I just fixed the issue, but I still have gripes with the selection system that should be addressed in the future (I'll describe them in another ticket when I have time).
