### ISSUE TITLE
Wrong number of page after scrolling

### ISSUE THREAD

**Issue by demiurg337** [xournalpp/xournalpp#1230]
**Affects versions :**
 - OS: Ubuntu 18.04

**Describe the bug**
After I have openned pdf and do scroling by mouse wheel or by scrollbar the page number indicator doesn't change (I mean indicator at left bottom part of screen).

**To Reproduce**
1. Open pdf file.
2. Do scrolling to the next pages by mouse wheel or by scrollbar.

**Comment by Technius** [comment]
Duplicate of #1184.
