### ISSUE TITLE
Canceling open a file after discarding changes causes subsequent saves to create empty files

### ISSUE THREAD

**Issue by triptronics** [xournalpp/xournalpp#1233]
Hello!
First of all, thank you so much for this program! I'm a college student using Ubuntu and Xournal was killing me. This program is a huge help!

I think I have discovered a bug when trying to open a file while working on a current document that has not autosaved since last modification.

I will have a current document open and make changes before autosave has saved the file (since last autosave).
Next, I will try to open a new file, I will get a prompt if I want to discard any changes on the current document, I click discard.
I then close out of the "open a file" dialog box (nautilius on Ubuntu) and never actually open a file.
I'm now still on my original document I made modifications to before autosave (it never closed even though I clicked discard earlier). 
I go to click save and then it brings up a save dialog box and asks for a name to save the file (this shouldn't happen because this isn't a new file! It should simply save).
I proceed to give the file a new name (I don't want it to overwrite my current file incase something went wrong).

Sure enough, something goes wrong with the new file that is saved and it's only about 400 bytes whereas the original file is 5.7 MB. 

I go to open the new file with 400 bytes and it is just a blank Xournal++ screen. Was able to reproduce this multiple times.

Please see if others can reproduce this, thanks!

**Comment by Technius** [comment]
Can confirm that the same problem also occurs with `Annotate PDF`.

The cause is in `Control::close`:
https://github.com/xournalpp/xournalpp/blob/99b7e18206e96c97f877e7e799a76db7b8c44af2/src/control/Control.cpp#L2921-L2932
which is called in the functions that require a file open dialog. `close` is triggered before any actual opening occurs, so cancelling will cause the editor to clear the currently loaded data even when a new file is not selected!

**Comment by Technius** [comment]
Can you test if #1235 fixes the issue? You can follow the instructions [here](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md) to compile it manually, but you need to clone with the command
```git checkout https://github.com/Technius/xournalpp -b issue-1233```.

**Comment by triptronics** [comment]
Hello, sorry for the late response! I just tested and the issue no longer appears! It's all good, you guys are awesome! :D I might have a few more bugs up my sleeve that I have discovered and I will post those as soon as I can so long as no one else beat me to it.
