### ISSUE TITLE
[new input] toggling "Enable Pressure Sensitivity" only works after restart

### ISSUE THREAD

**Issue by cbm755** [xournalpp/xournalpp#1237]
**Affects versions :**
 - Windows
 - 1.0.12

**Describe the bug**
"Enable Pressure Sensitivity" preference seems to need a restart when using the new input system.  I guess the text could note a restart is required, but even better would be if it worked without a restart.

It does seems to work without a restart using the old input system.

**To Reproduce**
1. enable new input system
2. restart
3. draw
4. toggle prssure sensitivity
5. draw: not pressure behaviour unchanged
6. restart
7. draw: pressure behaviour has now changed.

**Expected behavior**
works without restarting, or (less ideally) text indicates a restart is needed.

**Comment by LittleHuba** [comment]
Currently Pressure sensitivity is cached within the input system to save on some querries for each input. As far as I know the old input system does it too or I might have overlooked a call while porting the functionality. I'll fix it.

**Comment by Rmano** [comment]
This is also related to #943. Being able to change it without going into the menus would be really nice (maybe an icon somewhere? or an assignable stylus button?).
Thanks!

**Comment by LittleHuba** [comment]
@Rmano this is a prerequisite for #943 but the fix for that issue should be done separately.
