### ISSUE TITLE
Make use of clang-format

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#1250]
**Is your feature request related to a problem? Please describe.**
Developers tend to use the automatic format functions of their IDE's, those aren't configured the same way other developers configured theirs, and they even differ between your own workstations.

**Describe the solution you'd like**
Instead of letting the developers configure their format function, we should provide a clang-format configuration file, since clang-format is mostly IDE and platform independent. It also is supported by mostly every IDE.   

The provided eclipse configuration file is not sufficient and i think also out of date.

This will reduce merge conflicts due different formatting.
We can also reformat the whole project with one simple one liner over the terminal.

**Comment by LittleHuba** [comment]
Sounds like a very good idea!
Would you mind creating said file?

**Comment by Febbe** [comment]
Yes i can do that, but i also have some concerns and Questions about the current coding convention.

Why we use the \t character, the length depends always on the current editor and the code will look different in different editors if the programmers don't mix \t and \s in one line to ensure, that the spacing is editor independent. I would just use 4 spaces, since we accept a line width of 120 (2 for 80).

I also think that the current coding style eats lines, reducing the readability especially for short if-else statements, short functions and lambdas, i would just remove the additional line break before all {} code blocks and allow to inline those blocks if they are short and one liners.

I also would change the default placing of the const and volatile keyword after the type (or just don't care, but that could be confusing).
Since the only place where a const is allowed to be in front, when it stands in front of a type. In all other cases it must stand behind or will qualify something else or wont work:
E.g. a function void lock() const{ /*lock mutable mutex*/} i well formed, but void const lock(){ /*lock mutable mutex*/} wont compile.

or T getMyT() const{...} is a constant function which returns a copy of T, but T const getMyT(){...} will return a constant T (const T ==  T const) and the function itself cant be used in a const context anymore which would be unintended behaviour.

It also is better to read:
Ex 1: const T *const t;
Ex 2: T const* const t;

Assuming a read direction from left to right:
1) To a const T, a pointer is pointing to, which is const and named t.
2) T which is const, a pointer is pointing to, which is const, named t.

Assuming a read direction from right to left:
1) t is a constant pointer, to the type T which is const.
2) t is a constant pointer, to const T.
  
In both cases the second one is clearer to read.

**Comment by veecue** [comment]
I want to drop my opinion here:
`if` should always use brackets and at least three lines for better readability:

> if (a) {
>      b;
> }

For many short cases, ternary operators can be used instead (e.g. `return a ? b : c;`

Also I find the `const Type way better to be read than `Type const`. Your examples show it very clearly with a read direction from left to right: A constant T vs T which is a constant.

**Comment by Febbe** [comment]
Thanks for the opinion :)

> if should always use brackets 

completely agree with that generally conditionals should use {}, even it's a one liner.
But i am a fan of early exit / break or continue statements. Those really don't need to be split into 3 lines.
With clang-format we can define a threshold, so that only longer statements will be split into 3. E.g.:
```
if(!ptr) {return false;}
if(ptr) {return ptr->short;}
```
And:
```
if(!ptr) {
    return very_long_function_call();
}
if(ptr) {
    return ptr->long_variable_name_here;
}
```

> Also I find the const Type way better to be read than Type const`. Your examples show it very clearly with a read direction from left to right: A constant T vs T which is a constant.

No one will form it to a sentence normally i meant, how i  process the line in mind and wanted to make it more clear by using words my problem is the inconsistent. I hope the following example is better:{const -> T} -> {* -> const} ->...-> {* -> const} -> {function() -> const} instead of 
{T -> const} -> {* -> const} ->...-> {* -> const} -> {function() -> const} or right to left:
{const -> function()} -> {const -> *} ->...-> {const -> *} -> {T -> const} instead of 
{const -> function()} -> {const -> *} ->...-> {const -> *} -> {const -> T}

It is also more confusing to c++ newbies because const T const * does not do what they want if they mean const T* const.
At last it is also nicer for the eyes if we have several unqualified and qualified Types in a row:
```
auto i = int{1};
auto b = false;
auto const k = int{1};
auto const c = true;
auto volatile const& t = T{};
T const* const t = getTPtr();
```

**Comment by veecue** [comment]
Thanks for the additional explanations. Probably my problem with the `const` keyword is that I see it as a keyword (instead of `var`) and not as part of the type.

**Comment by Technius** [comment]
The current check is far too aggressive right now. If a legacy file is not formatted correctly according to `clang-format` but a PR only modifies one line of code, then the checks mark the entire PR as incorrectly formatted.

We can go in and clean up all of the source files at some point, but that's going to trash the commit history and make it difficult to merge existing PRs.

**Comment by LittleHuba** [comment]
The problem is that I can't check which lines have been edited. It was already a pain to get the files which have been edited. But you can sure try your hand. 

The current Vega ooze would actually help us move to formatted code as all PRs would force all modified files to be formatted.

**Comment by Technius** [comment]
As a historical note: I recently merged #1263, which makes the check less aggressive.

**Comment by Technius** [comment]
Looks like current configuration prefers the following brace style:
```c
if (foo) {
  bar();
}
```
which is not consistent with the current style used in the codebase.

**Comment by Febbe** [comment]
It must be set from Linux to ALLMAN or Custom. Or we go with this stile, since u can do a newline after the conditional if you want to separate the statement with his body.

**Comment by JJones780** [comment]
See #1275 for a clang format which matches Xournal++'s standard format.
There may be some fine tuning to do yet.

**Comment by JJones780** [comment]
I'm going to merge the changed clang format as it is much much closer to Xournal++'s historical  standard.  I think it's important to stick to the current style:

-  piecemeal conversion to a new format won't look good at all;
-  converting everything will interfere with our use of git history ( to track down problems etc.);
-  converting the entire git history is do-able but not straightforward and has some uncertainty;
-  the current standard works.

**Comment by JJones780** [comment]
oh, and LittleHuba said 
"If you want to try your hand you can update the format file in the repo."
;)

**Comment by JJones780** [comment]
We can always go forward with a new format after further discussion.

**Comment by JJones780** [comment]
### Play with clang-format
This is of note:  https://zed0.co.uk/clang-format-configurator/
It's a step beyond the ones I've run into thus far as it loads and saves as well as has an editable code preview.

**Comment by Febbe** [comment]
Unfortunately this site is quite buggy it produces clang format files with little errors like 'Yes' instead of true :D . And it clears newer setting from ClangFormat > 6. I also used it to create the first scratch file, but i needed to review it with the official documentaion http://releases.llvm.org/8.0.0/tools/clang/docs/ClangFormatStyleOptions.html . There are also specific examples.

**Comment by Febbe** [comment]
Done
