### ISSUE TITLE
Release stable on 7zip format beyond setup.exe for win 10?

### ISSUE THREAD

**Issue by Caiuzx** [xournalpp/xournalpp#1258]
Can you release xournalpp in 7zip beyond setup.exe for win 10 ?
ps: thanks for fixing the text bug in win 10.
Omar

**Comment by LittleHuba** [comment]
What exactly do you mean with 7zip? The packaged setup or just the packaged binary?

**Comment by Caiuzx** [comment]
> What exactly do you mean with 7zip? The packaged setup or just the packaged binary?

Oh ! i meant the packaged binary :D

**Comment by LittleHuba** [comment]
The setup is now zipped but there is no size-imporvement. I'm adverse to using a different archive format than .zip as this would make us dependent on some third-party software to unpack the setup.

**Comment by Caiuzx** [comment]
> 
> 
> The setup is now zipped but there is no size-imporvement. I'm adverse to using a different archive format than .zip as this would make us dependent on some third-party software to unpack the setup.

thanks a lots !
