### ISSUE TITLE
Stylus does not open popup/dropdown menu (gnome Wayland)

### ISSUE THREAD

**Issue by jonasBoss** [xournalpp/xournalpp#1264]
**Affects versions :**
 - OS: Arch Linux GNOME (Wayland) (Xorg works)
 - xournalpp-git (AUR)

**Describe the bug**
Stylus is unable to open dropdown/popup menus 

**To Reproduce**
1. start Xournalpp on a GNOME (Wayland) system 
2. open any dropdown/popup menu with Stylus
3. the menu does not appear

**Expected behavior**
The menu appears

**Additional context**
The bug is not present with Xorg (plasma and gnome).
Unfortunately I was yet unable to test with a other Wayland based UI.

**Comment by osirmuggler** [comment]
Can confirm. Also running a GNOME session via Wayland.

**Comment by Technius** [comment]
This seems like a GTK bug, since the main menus are handled through Glade.

**Comment by ammen99** [comment]
I think this might be a bug in GNOME-Wayland itself. Opening menus work fine (with the stylus) on other compositors like Rootston and Wayfire (both are wlroots-based)

**Comment by lehmanju** [comment]
Probably related to #1364, how did you use your stylus on rootston/weston? I can't get touch events through as browsing issues on rootston also turned out that touch is not supported yet.

**Comment by ammen99** [comment]
@lehmanju, are you running latest wlroots and rootston? It supports both stylus and touch input. Idk about weston.

**Comment by lehmanju** [comment]
Hmm, just installed latest package version from arch repository. Will try with master later.

**Comment by lehmanju** [comment]
Just rechecked and I indeed ran the latest version 0.6.0. I started rootston from gnome wayland, maybe I have to do this from X.

**Comment by lehmanju** [comment]
Interesting, running rootston and xournalpp natively works. So this is indeed a GNOME compositor issue. Additionally, you get `button_press`/`button_release` events using stylus input. On GNOME you only get `tablet motion` events resulting in the menu not opening. I will close and merge this with #1364 as I already started a GNOME compositor issue there.
