### ISSUE TITLE
how to change GUI language?

### ISSUE THREAD

**Issue by andrewchenshx** [xournalpp/xournalpp#1265]
**Affects versions :**
 - OS: [Windows 7 64bit]
 - Version of Xournal++ [1.0.12]

**Describe the bug**
after launching this app, i found some menus were displayed as English, while some were Chinese.
how can i select a language for displaying the GUI elements.

**Comment by LittleHuba** [comment]
The parts in english are actually just missing translations for your language. Take a look at the Shoutout in the Readme!

To disable the translations you can prepend your call to start xournalpp with `LANG=en_US`.
See [this](https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html) document for more information.

**Comment by LittleHuba** [comment]
Ahh sorry just saw you are on Windows. There it is not as easy as on Linux...
You'll have to take a look at the installation directory. There should somewhere be *.go files with the country codes as filenames. Just delete or rename your translation file. That should make gettext fallback to the english version.

**Comment by andrewchenshx** [comment]
@LittleHuba , the following script works for me.
`
set LANG=en_US
the\path\to\xournalpp.exe
`

**Comment by Annegrim** [comment]
For anyone still searching in 2020:

I didn't find any `*.go` files and also had no idea how to use the script, but deleting the folder `path\to\install\Xournal++\share\locale\<country code>` did the job for me.

Sidenote: There really should be a setting for the locale..

**Comment by banan314** [comment]
I deleted **all** folders in `path\to\install\Xournal++\share\locale` and it worked.

**Comment by juniortruka** [comment]
Hey, How I Can Create a file (pt_br) for xournal ++? 

I searched files with name *.po, but only have file "Makefile.in.in" in folder "po"
