### ISSUE TITLE
can NOT open the help document

### ISSUE THREAD

**Issue by andrewchenshx** [xournalpp/xournalpp#1266]
**Affects versions :**
 - OS: [Windows 7 64bit]
 - Version of Xournal++ [1.0.12]

**Describe the bug**
the help document does NOT open.

**To Reproduce**
1. launch the program
2. click the 'Help(H)' menu
3. click the 'help' menu item

**Expected behavior**
the help document should open

**Screenshots of Problem**
there was an error displaying help. Failed to execute helper program(Invalid argument)

**Additional context**

**Comment by Technius** [comment]
I'm guessing this is because we don't bundle `gvfs` with the windows build: https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window

We might have to submit a package request to Msys2 since `gvfs` isn't in their repositories.

**Comment by LittleHuba** [comment]
Either that or we build it ourselves like all the other libraries that are not available...

**Comment by Technius** [comment]
Actually, we might be able to work around it by calling the `open` command on Windows and leaving the code as-is on Linux.
