### ISSUE TITLE
Things we should do at PR-Freeze

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#1279]
Independent:

- [x] disable automatic generation of translation files for every build and update pipeline to do this for commits to master
- [ ] Enums with PascalCase instead of CAPS_SNAKE_CASE

Do before clang-tidy and clang-format:

- [x] replace NULL with nullptr
- [x] replace TRUE with true
- [x] replace FALSE with false
- [x] replace MAX with std::max
- [x] replace MIN with std::min
- [x] replace ABS with std::abs
- [x] remove XournalType Checks
- [x] flip to cpp11+ Syntax (E.g.: using {} to initialize objects and parameters);
__
- [x] use the cpp 17 standard
~~- Switch all Paths to std::filesystem::path~~
- [ ] try to replace #define 's with cpp17 templates (faster compile times, more clear exception descriptions).

Cleanup:
- [x] use clang-tidy to insert std::move(); wherever it is possible. (performance)
- [ ] use clang-tidy to enforce some good coding conventions.
- [x] discuss ClangFormat changes
- [x] apply .clang-format on all source and header files
- [ ] add the requirement of c++17 and the existence of the <optional> header in libstdc++/libc++ to the manual build instructions

Optional, if possible
~~- Switch all Paths to std::filesystem::path~~

Defered:
- Switch all Paths to std::filesystem::path

**Comment by andreasb242** [comment]
> flip to cpp11+ Syntax
What do you mean with this? It should already be enabled, and used on some places.

**Comment by LittleHuba** [comment]
> > flip to cpp11+ Syntax
> 
> What do you mean with this? It should already be enabled, and used on some places.

I think he means that it is not used everywhere. There is quite a mix of initialization variants in our code. But most are okay just some of those are dubious (e.g. assigning 0 and casting it to the object type)

**Comment by LittleHuba** [comment]
We should consider doing this in the next few weeks as PRs are currently very hard as CLang checks fail nearly every time. leading to bad commit histories.

**Comment by Technius** [comment]
Clang checks are going to fail regardless if a PR submitter isn't careful enough. We should update contributing guidelines:
* Use the `azure_pipelines/format_diff_lines.pl` script, as shown in the automated checks, before making commits.
* Amend and rebase/squash commits that only fix bad formatting; this avoids bad commit histories

**Comment by Febbe** [comment]
I don't know why, but I didn't had a problem with gitformat ever. I just looked, which was the parent of my first commit(after rebase) and used it with git-clang-format. It worked like a charm. The best would be to use the formatting between every commit. But for this eather a special IDE like clion or great discipline would be necessary. That would also prevent bad commit histories,  because the formatting is correct on every commit

**Comment by Febbe** [comment]
This is not necessary after the pr freeze, because format file on safe would be no problem anymore.

**Comment by LittleHuba** [comment]
It goes awry if you edit half of a conditional expression and the first bracket is correctly formatted but the second not. (At least that was one thing I couldn't get right on the first try)

**Comment by Febbe** [comment]
Btw for all Clion users: There is a plug-in named Safe Actions, which can actually apply formatting on save, only on changed lines if VCS is configured. So no manual call to clang format is necessary.

**Comment by LittleHuba** [comment]
One can also just set CLangFormat in the lower bar of the main window as formatting directive. Then CLion will directly format everything correctly while you type.

**Comment by Febbe** [comment]
Btw. @andreasb242 told me that he actually like the brackets in the same line as his corresponding statement more. I think we should take the chance to modernize our coding style. I suggest to supply some wishes we can discuss. 
I 4 example love the Google style with an indent of 4 and a line with of 120.

**Comment by LittleHuba** [comment]
> I 4 example love the Google style with an indent of 4 and a line with of 120.

I second that!

**Comment by JJones780** [comment]
Any baseline Clang format works for me - no modifications - Google is fine.
Line width: 120 chars is minimum. I wouldn't mind more.. or even infinite.

It would be great if we could get all of our formatting and modernization changes in at once.


**Suggestions gathered from my readings thus far:**

All commits under a new username for this specific purpose.. call the user "AutoModernize" or similar.

Reformat and each modernization as separate commits ( order? ):
- Clang-Format: Google;
- Clang-Tidy: modernize-use-override;
- Clang-Tidy: modernize-use-nullptr;
- Clang-Tidy: modernize-use-bool-literals;
- others: modernize-use-auto, modernize-use-emplace etc.. as determined via discussion here.

Plenty of dry runs.. testing, reviewing of changes.


Relevant links:
**MongoDB's experience:** https://engineering.mongodb.com/post/succeeding-with-clangformat-part-1-pitfalls-and-planning/
**Commands:** https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14/

**Comment by JJones780** [comment]
I've written a script that steps through each clang-tidy modernize operation and commits them individually.
This is a dry run.
The script I used is in the last commit.
I've put the results here (https://github.com/JJones780/xournalpp/commits/testModernize) **for us to view and consider which modernizations we wish to include.**
If there is no commit for a modernization then that means there were no changes due to it. 

Here are the modernizations performed and those which made changes are found on my xournalpp fork as linked above:
    modernize-avoid-bind
    modernize-avoid-c-arrays
    modernize-concat-nested-namespaces
    modernize-deprecated-headers
    modernize-deprecated-ios-base-aliases
    modernize-loop-convert
    modernize-make-shared
    modernize-make-unique
    modernize-pass-by-value
    modernize-raw-string-literal
    modernize-redundant-void-arg
    modernize-replace-auto-ptr
    modernize-replace-random-shuffle
    modernize-return-braced-init-list
    modernize-shrink-to-fit
    modernize-unary-static-assert
    modernize-use-auto
    modernize-use-bool-literals
    modernize-use-default-member-init
    modernize-use-emplace
    modernize-use-equals-default
    modernize-use-equals-delete
    modernize-use-nodiscard
    modernize-use-noexcept
    modernize-use-nullptr
    modernize-use-override
    modernize-use-transparent-functors
    modernize-use-uncaught-exceptions
    modernize-use-using

I guess I should try compiling it and test it too ;)  Soon.

**Comment by Febbe** [comment]
Very good thx😄

**Comment by Febbe** [comment]
Another thing, you used modernize-make-shared and -unique, this feature ist only supported since c++14. Shall we switch to it, or go even for c++ 17? The "4 big" compilers (Intel, clang, msvc, g++) and their corresponding stdcpp lib already support c++17 completely.

**Comment by Febbe** [comment]
I would also activate -wall and -wextra in the CXXFLAGS

**Comment by JJones780** [comment]
I think it would be great to go to C++17 and see few reasons not to.  One hiccup... Our Azure Linux builds are using gcc 5.4.0 which only supports up to C++14. It can't be too hard to specify a newer compiler?? 
The Azure Windows build isn't a problem.. gnu 8.2.0.

Yes, the script I wrote asks clang-tidy for all possible flags and filters out and runs ALL of the modernization ones and checks each one separately into git (if changes were actually made ) for us to review.  It will be easy to modify it to run a subset of the modernization updates.

**Comment by LittleHuba** [comment]
Updating gcc in Azure Pipelines shouldn't be a problem we only have to find an apt-repo providing it.

**Comment by Febbe** [comment]
The problem is the support of older distros. I really don't know if the swap to cpp17 will break the build for older distros. But I don't think so. They will just have a bigger expenditure to install the new compilers.

**Comment by veecue** [comment]
I would like to add the following:
 - [ ] Switch all Paths to std::filesystem::path

**Comment by LittleHuba** [comment]
I think we should remove _switch all Paths to std::filesystem::path_ again, as it will not be possible for the forseeable future. AppleClang does not support it in the minimum version we have to provide support for. This might change in a year or so when macOS 10.3 is old enough to drop support without a lot of people complaining.

**Comment by LittleHuba** [comment]
Do we really want to have boost as a dependency though? Especially if we want to distribute the package for MacOS 10.3 from our Pipelines we might get into a problem. Essentially we would need to separate the pipeline again and take care of multiple dependency blobs we need to maintain for the pipelines themselves. I don't really thinks it is worth it. 

Additionally the complete file handling will be outsourced in the new fileformat library in the forseeable future which would make all these changes obsolete anyway.

**Comment by Febbe** [comment]
Mhh I think having boost in the dependency tree is like having the STL as dependency. And we also just need to preserve the precompiled library file for filesystem in the path. Also the most of the boost features are header only and are pushed as it into the STL.

**Comment by LittleHuba** [comment]
You will have to update the MacOS pipeline blob as I have no way of doing so for the forseeable future (at least 5 months). Just as a warning...

The thing is the new library will be in its own project (repository) making these changes obsolete. Additionally we will have to port the current fileformat to the new library or our rendering engine will be very complex in the end. That is why I think that changing things now makes no real sense. We can keep this in mind for the new implementation.

**Comment by Technius** [comment]
Closing since PR freeze is over.
