### ISSUE TITLE
"Export as..." crashes, glade error introduced with latest update

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#1285]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Elementary OS 5.0 Juno (based on Ubuntu 18.04 LTS)
 - Version of Xournal++:   1.0.6-0 ~201906220514 ~ubuntu18.04.1 

**Describe the bug**
"Error loading glade file ..." (please refer to screenshot) when trying to "Export as..."

**To Reproduce**
1. Open a .xopp file
2. Ctrl + E      or     File > Export as...
3. Fill in name and press save

**Expected behavior**
A dialogue allowing you to choose which pages to export as PDF should appear.
In its place, the following error dialogue appears, and once you close the dialogue Xournal++ just closes down

**Screenshots of Problem**
![Screenshot from 2019-06-22 17 00 07](https://user-images.githubusercontent.com/16632292/59965550-ffca3200-950f-11e9-8107-73a8484a2b9c.png)

**Additional context**
The bug started presenting itself with today's release (1.0.6-0 ~201906220514 ~ubuntu18.04.1) - I am sure because I update the software daily using the PPA, and export notes as PDF on a daily basis.

**Comment by Technius** [comment]
Regression introduced by #1283. @JJones780

**Comment by Technius** [comment]
Fix should be to just remove this line:
https://github.com/xournalpp/xournalpp/blob/bd7f66472ba7e9ba5db03265e3cd8142144f9fc0/ui/exportSettings.glade#L315
