### ISSUE TITLE
Laggy zoom in new input system

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1286]
Arch Linux 5.1
Xournal++ 1.0.13

Zooming is laggy. This doesn't occur in the old input system.

1. Turn on the new input system in the preferences
2. Zoom in or out

**Comment by Febbe** [comment]
Can you try the branch refactor_layout_resize, it could be already fixed there, because the relayouting there is handled differently.

**Comment by LittleHuba** [comment]
I assume you are talking about zooming with the zoom gesture? Then if the branch @Febbe mentioned did not fix the issue it is most likely the new input system blocking the zoom gesture for touch inputs...

**Comment by coldspark29** [comment]
I don't have time to try out the branch, but if it is already fixed there great!

**Comment by Febbe** [comment]
Can you tell us how exactly you zoomed?
With gestures, with the middle mouse button, or with the zoombar?

**Comment by coldspark29** [comment]
It was with gestures

**Comment by LittleHuba** [comment]
I'm unable to reproduce this behaviour. There is currently a PR open that reimplements the zooming gesture locally, as the GDK implementation is very buggy on some devices.
Feel free to check out #1460
