### ISSUE TITLE
Klingon translation

### ISSUE THREAD

**Issue by JasMich** [xournalpp/xournalpp#1287]
**Is your feature request related to a problem? Please describe.**
I'm seriously missing a Klingon translation. How/where can I start one?

**Describe the solution you'd like**
I would just start writing a Klingon translation.

**Describe alternatives you've considered**
The alternative would be having no Klingon translation but that makes me sad :-(

**Additional context**
Klingon is a constructed language all over the world.

**Comment by LittleHuba** [comment]
Nice 😁 

Take a look at the readme in the directory `po`. That should help you along nicely.

**Comment by LittleHuba** [comment]
You may try our new Transifex Project for your translation:
https://www.transifex.com/xournalpp/xournalpp

We are currently checking out Transifex for future use. So please provide some feedback.

**Comment by JasMich** [comment]
Well, Transifex doesn't offer any option for Klingon translations.

**Comment by JasMich** [comment]
Should I use `tlhIngan Hol`, `xifan Hol` or unicode characters? https://en.wikipedia.org/wiki/Klingon_scripts

**Comment by LittleHuba** [comment]
Checkout https://crowdin.com/project/xournalpp
We are trying out multiple platforms -  just that you aren't confused 😉

**Comment by LittleHuba** [comment]
> Should I use `tlhIngan Hol`, `xifan Hol` or unicode characters? https://en.wikipedia.org/wiki/Klingon_scripts

This is absolutely up to you

**Comment by muzena** [comment]
@LittleHuba 
https://translations.launchpad.net/xournalpp
So you dicede to use crowdin instead transifex.
why crowdin is better than transifex?
@LittleHuba 
Can you add Croatian language to crowdin?

**Comment by LittleHuba** [comment]
> @LittleHuba
https://translations.launchpad.net/xournalpp

 I'm not quite sure Launchpad is really suited for our project. 
- I'm actually very underwhelmed with their UI and the overall workflow (unfinished translations are hidden by default until you click a button - they should be highlighted for users to SEE)
- Streaming back the updated translations would need to happen with a manually built pipeline or by hand (which other platforms do on their own)

> why crowdin is better than transifex?

Transifex is quite nice but it prevents us from:
- providing context based on images. That is for some reason a pro feature not unlocked for open source software. As we happen to have a lot of strings that only make sense when one has the appropriate context, I think this would be a good feature to have. 
- Crowdsourcing mode - where this mode is definitely the one we should use...

Crowdin does work as good as Transifex and provides all the previously mentioned features. The integration is quite easy and works well. The only things I currently do not like are already mentioned in their list of future milestones. Additionally the UI will get a major overhaul in the comming weeks which will further improve usability. I think we are in good hands there.

> Can you add Croatian language to crowdin?

I'll unlock it ASAP!

**Comment by LittleHuba** [comment]
> Can you add Croatian language to crowdin?

Done!

**Comment by LittleHuba** [comment]
I'll close this ticket as Crowdin provides the requested languages now. Thanks for doing the translations!
