### ISSUE TITLE
Mouse pointer in input area is normal pointer until writing starts

### ISSUE THREAD

**Issue by lschmalen** [xournalpp/xournalpp#1290]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Ubuntu 19.04
 - Version of Xournal++: 1.0.13 Built on Jun. 24

**Describe the bug**
While using Xournal++, the normal mouse pointer is shown even while I'm hovering over the input area. Once I start writing, the mouse pointer changes to either the small dot or the big input pointer (depending on what is selected in the preferences). Once I stop writing, the mouse pointer changes again to the regular system mouse pointer. Unfortunately, this behavior is considered highly annoying by myself and possibly many others. In the base Xournal, this behaviour is not present and the mouse pointer within the input area is a small tiny dot that changes once it is moved to the menu or outside. This is much more natural.

**Expected behavior**
Mouse pointer changes to dot while inside drawing area and back to system pointer outside, even when not drawing.

**Screenshots of Problem**
Please see the attached photos to see what I mean: first photo while hovering, second photo while writing. Input device is either Wacom Bamboo Stylus or Lenovo X1 Yoga integrated pen.

![IMG_3764](https://user-images.githubusercontent.com/49953583/60074895-514b0a80-9724-11e9-925a-d01a220526f4.jpg)
![IMG_3765](https://user-images.githubusercontent.com/49953583/60074899-53ad6480-9724-11e9-9696-26a228dbf1d3.jpg)

**Comment by LittleHuba** [comment]
@JJones780 would you mind taking this? You were the last one modifying the cursor logic and should know your way around best.

**Comment by JJones780** [comment]
Please enable the new input system in 
`Edit->Preferences->InputSystem: Enable new input system(Requires restart)`
Restart and give it a try; let us know if the behaviour there is sufficient.

We hope to have the new input system as default soon!

@lschmalen Thanks for taking the time to write up this issue. We will be making some more changes to the cursors so your input comes at an opportune time.

**Comment by lschmalen** [comment]
> Please enable the new input system in
> `Edit->Preferences->InputSystem: Enable new input system(Requires restart)`
> Restart and give it a try; let us know if the behaviour there is sufficient ( the cursor should stay as a dot after the stylus is used... until the mouse is used again ).
> 
Tried it and indeed the new input system gives the expected behaviour. Thanks for the suggestion @JJones780 . I was initially reluctant to use the new input system due to the warning in the preferences.

**Comment by LittleHuba** [comment]
> Please enable the new input system

Ahh didn't think of that...

The new input system is stable as far as I have seen. There is one issue with Windows I would like to fix before making it default but I have to wait for a testing device before I can triage that.
But anyway you should not find any problems that didn't exist with the old input system. The warning is there as we introduced the new input system at a very early state and it had to go a long way from there.

**Comment by DuendeInexistente** [comment]
Even enabling the new input system, the pointer reverts back to default as soon as I use the mouse instead of the pen.

**Comment by LittleHuba** [comment]
This is expected behaviour. People complained that the cursor is hard to find when using the mouse. If you want the old behaviour back please request the enhancement and we will add an option in the settings.

**Comment by triptronics** [comment]
I agree that there should be a separate setting for this. Personally, I find it annoying for the mouse cursor to come back every time, it flashes and it is indeed annoying. I'm using the new input system and it's working as expected (always a dot). If people prefer the mouse even when using a stylus and they do not find it annoying, then a separate setting should be made. Also, couldn't we just have an option that would allow us to resize the dot that gets displayed? Thanks!

**Comment by JJones780** [comment]
If I understand you correctly, if using the new input system then all is good?
If a stylus-only user wants a different pointer (  big pen and/or highlight aura ) they can currently set that in the preferences.
Resizing the dot or otherwise change the cursor is something we need to do eventually. At the moment it's a custom drawn cursor so is essentially hardcoded ( with the big pen and auro options too ). I would like to allow the user to set any css cursor or define one themselves.

**Comment by elenitzanaki** [comment]
> Please enable the new input system in
> `Edit->Preferences->InputSystem: Enable new input system(Requires restart)`
> Restart and give it a try; let us know if the behaviour there is sufficient ( the cursor should stay as a dot after the stylus is used... until the mouse is used again ).
> 
> We hope to have the new input system as default soon!
> 
> @lschmalen Thanks for taking the time to write up this issue. We will be making some more changes to the cursors so your input comes at an opportune time.

Thank you so very much for the solution... The previous setting was so frustrating!
