### ISSUE TITLE
Remove the PHP build system remains

### ISSUE THREAD

**Issue by x2b** [xournalpp/xournalpp#131]
This does not require any actual programming work, it can be done in 5 minutes... We are using autotools, not PHP, so please remove this: 

https://github.com/xournalpp/xournalpp/tree/master/buildsystem

and any *.php file

**Comment by andreasb242** [comment]
I already removed it in string new...
You are to late ;-)

**Comment by x2b** [comment]
No problem...

**Comment by andreasb242** [comment]
@x2b You don't have a real email address assigned, right?

markpirk create two project pages for Xournal++.
Both should be public, but for slack you have to register.
Slack is something like a chat, trello something like brainstorming.

https://trello.com/b/nhIQOj4f/ideas
https://trello.com/b/n2a9O8lv/todo

https://xournalpp.slack.com/messages/general/details/

We are currently testing if this is a good idea for developer communication, you may also have a look at it (and for sure any body else which would like to develop on Xournal++)

**Comment by wbrenna** [comment]
Since a mailing list was requested, here is one to test out: xournalpp@googlegroups.com

https://groups.google.com/group/xournalpp/subscribe

All of the messages should be archived and public, viewable without login, and joining doesn't require any credentials other than an email address.

**Comment by MarPiRK** [comment]
What about `count.php`? It can be replaced with some more valuable programs, such as `sloccount`.

**Comment by MarPiRK** [comment]
Anyone's there? What about count.php, which is kinda not part of the project?

**Comment by MarPiRK** [comment]
There are no PHP files in `string_new` right now. Can be closed.
