### ISSUE TITLE
Create Help page

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#132]
Create a help page, and link it on the Help menu, currently we are linking to the Evince Help (I copied the open URL as example from Evince...)

I think we should use the Wiki as help page?

**Comment by MarPiRK** [comment]
Yes, but there's not too much on wiki right now :/

**Comment by andreasb242** [comment]
Yes, you may write a manual to the Wiki? :innocent:

**Comment by MarPiRK** [comment]
Hah, good joke ;D
Maybe after CMake and bf::path → Gio, but if anybody would like to do this I prefer not to do this (as you may expect) :)

**Comment by MarPiRK** [comment]
I think that it would be much cleaner on our wiki if we removed outdated pages like `Arch 20131101` or `Debian …`. They were kind of usable, when we were on Autotools, but now after move to CMake it's pointless to keep them here.
For building from source (CMake case) there is [Installing](https://github.com/xournalpp/xournalpp/wiki/Installing) page.

**Comment by andreasb242** [comment]
Close, as this is not really a task which can be solved. The wiki should be updated.
