### ISSUE TITLE
Add Redo shortcut: Ctrl+Shift+Z

### ISSUE THREAD

**Issue by phcerdan** [xournalpp/xournalpp#1323]
**Is your feature request related to a problem? Please describe.**
The action "Redo" is mapped to Ctrl+Y, which is ok, but not standard, nor used by other apps.

**Describe the solution you'd like**
I would like to map Redo to also Ctrl+Shift+Z (Ctrl+Y can be kept as well)

**Describe alternatives you've considered**
This won't be an issue if there would be a way to map actions to any key, chosen by the user. But I can imagine that change would require way more development.

**Additional context**
I am configuring the keys of the tablet, and it is painful to change the redo key for xournal, when most other apps use ctrl+shift+z.

Thanks a lot for xournal, it is great!

**Comment by Technius** [comment]
Related to #919.
