### ISSUE TITLE
Present option to recover unsaved files after crash

### ISSUE THREAD

**Issue by Schroedi** [xournalpp/xournalpp#1324]
**Is your feature request related to a problem? Please describe.**
When xournal crashes, it is not clear how to recover the last autosave. This is especially important if the file last opened was never saved, or there is an autosave that is newer than the last corresponding save.

**Describe the solution you'd like**
I propose to keep a list of open files in a file on disk. When xournal is closed cleanly, this file will be emptied. In the case of a crash, the content lets xournal check for the conditions mentioned above.
I could also try to contribute code to this issue if you think it would be a welcome addition.

**Comment by LittleHuba** [comment]
This should actually be already the case. The should be a dialog shown that asks you if you want to open the autosave file when Xournal++ crashed previously.
Could you please elaborate on the setps to get the crash when there is no dialog shown? Are you using `kill`
