### ISSUE TITLE
Zooming off center

### ISSUE THREAD

**Issue by Nearoo** [xournalpp/xournalpp#1327]
Possibly related / identical to #404.

**Affects versions :**
 - OS: Ubuntu 18.4.2 LTS
 - Version of Xournal++: 1.0.13
 - Hardware: Lenovo Yoga 720

**Description**
Pinch- & Mouse zoom is off center. When zooming, the scaling seems to always originate from or move to the top center of the entire document. Especially when working on a pdf with many pages, this makes zooming unusable, as even zooming a little bit moves many pages.

**Expected Behaviour**
Increase the scale of the document to where I'd intuitively like it to scale, e.g. when I zoom to the bottom right, the bottom right of the document becomes centered.

**Comment by Febbe** [comment]
Please check out, if this is still present in the branch refactor_layout_resize. There are lot of changes related to the zoom and layouting.

**Comment by Nearoo** [comment]
Can do, instructions?

**Comment by Nearoo** [comment]
After reinstalling it from your repo instead of the version on Ubuntu Software, it works. Might have to do with the fact that on Ubuntu Software, it's a snap... anyway, issue resolved.
