### ISSUE TITLE
preferences dialog is too wide for my screen

### ISSUE THREAD

**Issue by cbm755** [xournalpp/xournalpp#1328]
**Affects versions :**
 - OS: Windows, Fedora GNU/Linux]
 - Version of Xournal++ branch `LittleHuba:fix_device_listing_new`, master a37524e2626e269e1c1defbdf5abe3305d29e863

**Describe the bug**
On Windows 10, I have a portrait screen that is 1200 pixels wide.  But I have some big fonts and/or other scaling selected (could check details if needed).  With this setup, the preferences dialog doesn't fit horizontally on the screen (screenshot below).

On my Fedora laptop, I checked the master branch and the minimum size of the preferences dialog is 968 pixels.  But I suspect this depends on OS fontsize preferences etc.

**To Reproduce**
1. select a low res screen (I guess something like 800 pixels wide)
2. open preferences

**Expected behavior**
If the preferences dialog were a bit more compact or was able to shrink a little more then it would fit.  Or the panes would scroll horizontally as they already do vertically.

**Screenshots of Problem**
![pref_dialog_too_wide](https://user-images.githubusercontent.com/818622/60764226-903d6200-a03a-11e9-985e-783ed02d38db.png)

**Comment by sanette** [comment]
I see two potential solutions
1. slightly reorganize the grid of the "Action on Tool Tap" setting, which is the largest element in the Settings.
2. allow horizontal scrolling
I think we can do both, what do you think?

**Comment by sanette** [comment]
by the way, there is a missing GtkScrolledWindow in inputTabBox, I can add it too

**Comment by rolandlo** [comment]
This was fixed in PR #2592
