### ISSUE TITLE
Multi-core compression

### ISSUE THREAD

**Issue by Faberix** [xournalpp/xournalpp#1336]
Saving big files always takes a lot of time, probably primarily because of the compression. This is especially annoying because you cannot write anything during that time.

One solution would be to use multi-core compression. You could achieve that either by programmatically splitting the document in several pieces and then processing each one in a separate thread or by piping the uncompressed file to an external program such as pigz.

Another solution is to use a binary file format. This would drastically reduce the amount of data that has to be compressed and thus reduce the amount of time needed for it (and probably lead to smaller files, too...).
For the binary file format, you could, for example, use a unique ID for each object type in a file; each object would then consist of that ID (2 bytes would be enough for that), some metadata that is stored in a defined location and stroke data, which, in a binary file, needs _not nearly as much_ space as in a text file (a double needs 8 bytes whereas a 14 digit number with a decimal point as a UTF-8 string needs 15 bytes, almost twice as much); besides, directly saving doubles or floats would avoid rounding losses that occur during the conversion.

**Comment by LittleHuba** [comment]
The actual big size might be a result from the current way we store images (Base64) As we change the format anyway this will be no longer a problem. The new format zips all the images with the journal, which should be multicore compression anyway.
