### ISSUE TITLE
When the cursor is in the text field export to pdf doesn't export the field at all

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#1341]
version 1.0.12 on FreeBSD

**Comment by Technius** [comment]
Fix should be to insert `this->clearSelectionEndText();` at the beginning of each of these two functions:

https://github.com/xournalpp/xournalpp/blob/583a317ff1d63b8d65d4019b75fb27801e5c0098/src/control/Control.cpp#L2802-L2811

**Comment by y2kmurali** [comment]
I'm willing to work on this! 

I'm new to the codebase though, is there a function that sets the view to the same as the way it was when the file was first opened? 
That way, any related issues to any objects (not just text boxes) in focus not being saved would also be fixed (assuming that calling said function would trigger the listeners for all objects being deselected), which I think might be a better fix than doing one function for each potentially broken object). One function I think might work would be `initWindow`, but I'm not quite sure if that would have any unintended side effects. Thoughts?

**Comment by LittleHuba** [comment]
Hi @y2kmurali!
Thanks for the offer to take over this issue!

I think a quick and dirty fix is enough. We introduce a new file format and rendering library which will not be able to reuse that part of the code. Thus an elaborate fix is not really worth it.

Your work on other issues would be more then welcome by the way!

**Comment by y2kmurali** [comment]
Understood, not worth investing a lot of time in an elegant fix when everything will be changed shortly. I've submitted a PR (#1577). 

Of course! I use xournal all the time for schoolwork so I'd love to keep contributing as I become more familiar with the codebase. Do we know when the file format/rendering changes will be merged?

**Comment by LittleHuba** [comment]
Thanks for the PR!

I'm currently writing the code-skeleton for the new library and hope to release it in the next two weeks for review. I'll create a new repository under the xournalpp organisation here on GitHub. If you want to be notified about it follow the organisation.

After the review is done we will start with coding the actual algorithms and porting of all parts of the code we can still use. Additionally we will finally write some tests to make maintenance easier. That step will take a few month at least (hopefully) and you are more then welcome to join in.

After that we will have to write one BIG PR that removes 3/4 of the current code-base from Xournal++ and includes the library for all of that. All in all this will take at least half a year to one year until all is done. Our team is quite small for such a big software unfortunately.
