### ISSUE TITLE
Please provide installation instructions for Windows

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#1342]
I don't use WIndows, was going to recommend it to somebody who uses windows.

But I couldn't find instructions how to install on windows. So windows users would likely get confused.

Please add the instructions to readme.

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/xournal-settings.xml

**Comment by LittleHuba** [comment]
We provide nightly releases for Windows which are packed in an Installer. Please take a look at the release page of our GitHub repository.

Manual instructions are already linked in the main [Readme](https://github.com/xournalpp/xournalpp#building) and can be found [here](https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md).
