### ISSUE TITLE
Please add an option for automatically appending empty pages after last page hase been reached

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#1343]
I frequently use Xournalpp not for annotating PDF files which have a fixed number of pages but for just taking notes. Then, when I reach the bottom of the page, I need to click a button to add another empty page to continue writing.

It would be great to have an option to append an empty page automatically when the end of the file (bottom of the last page) is reached. Maybe make it dependent from the context (off if a PDF file is loaded, on if not).

**Comment by Febbe** [comment]
I also thought about that. Some sort of automatically added pages, they appear greyed out or a bit invisible, and become solid as soon as it is used.

**Comment by LittleHuba** [comment]
Sounds like a nice idea!
I still have the endless paper on my todo list but that takes a little bit more work than this solution.

**Comment by Photon89** [comment]
@Febbe : Right, and if the last page is not yet solid, don't add another page automatically when it is reached.

**Comment by Nearoo** [comment]
An endless canvas similar to One Note would be pretty dope in general

**Comment by cbm755** [comment]
>  Maybe make it dependent from the context (on if a PDF file is loaded, off if not).

I would personally find this most useful when *not* annotating PDF files.  (But I also don't mind this behaviour when annotating PDFs).

**Comment by Photon89** [comment]
@cbm755 I'm sorry, that's exactly what I meant to write! :laughing:

**Comment by LittleHuba** [comment]
@Nearoo the problem is this is a lot of work. One question for example is how to handle attached PDFs as they are currently just backgrounds for equally sized pages. Integrating this into the drawing system is taff...

**Comment by sammdu** [comment]
@LittleHuba I agree with the endless canvas idea. It is a very useful option when printing is not the goal and you want to just sketch some ideas down.
Thanks for your hard work and I am looking forward to this in a future release :-)
