### ISSUE TITLE
Use the Windows 8+ Pointer Input (Windows Ink) API

### ISSUE THREAD

**Issue by bepzi** [xournalpp/xournalpp#1346]
**Is your feature request related to a problem? Please describe.**

GTK+ has a bug where some N-trig based pens aren't recognized as being pressure-sensitive styluses and are instead treated like normal mouse input; `gtk-demo3` only sees my stylus as a "System Aggregated Pointer". Xournal++ inherits this bug, so my stylus doesn't work correctly.

**Describe the solution you'd like**

Rather than using GDK events to track the pen, it might be possible to use the [Pointer Input Messages and Notifications API](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/inputmsg/wmpointer-reference) to retrieve information about the stylus (its position, pressure, etc.) and pass that on to Xournal++.

This would only be relevant on Windows 10, and should be an opt-in feature.

For comparison, this is how Krita does it:

![krita_options](https://user-images.githubusercontent.com/17169802/61165728-b014d000-a4e9-11e9-9115-79cafd98b22f.png)

Under the WinTab API, the stylus behavior is defective and the same as in Xournal++. With the Windows 8+ API, the stylus works correctly and the behavior is as expected.

**Describe alternatives you've considered**

The cleanest solution would be to fix whatever's going wrong in GTK+, so that we don't have to implement any extra logic in Xournal++ while also fixing other programs (GIMP, etc.) that rely on GTK+. I personally don't have any experience contributing to a project like GTK+, and it would take me a while to debug what's going on.

On the other hand, we *do* already know that the newer (non-WinTab) API can produce the desired outcome.

**Additional context**

I'm using a Surface Pro 2017 (5th Gen) with Windows 10, and my stylus is an off-brand N-trig based stylus. Everything works as expected with all Windows Ink-enabled applications (Wacom Bamboo Paper, Windows Sketchpad, and Krita with the Win8+ API option enabled.) Xournal++, GIMP, and `gtk3-demo` are the only applications that do not recognize my stylus.

 * Related issues: #659, #1094 (GTK: [#1549](https://gitlab.gnome.org/GNOME/gtk/issues/1549), [#1845](https://gitlab.gnome.org/GNOME/gtk/issues/1845), [#537 ?](https://gitlab.gnome.org/GNOME/gtk/issues/537))

 * Krita worklog related to implementing Windows Ink: https://phabricator.kde.org/T6807

 * Krita's implementation of Windows Ink: https://github.com/KDE/krita/blob/be4ed821832fece6ec8d7c3e7a1da3f5e59e03bb/libs/ui/input/wintab/kis_tablet_support_win8.cpp

**Comment by Technius** [comment]
Does this bug only occur on Windows?

**Comment by LittleHuba** [comment]
This is common for some styluses on Windows. GTK+ still has buggy support for the Ink API and it seems like there is currently no effort to fix that. 

Unfortunately it is not as easy as it sounds, to query the Ink API from GTK+ based apps as Windows only allows for one listener to the event loop and obviously GTK+ registers itself. 
I'll look into possible fixes but this will take some time and might never be possible. 

@bepzi you should file a bug report over at the gitlab repository of GTK+ so they see there are people missing this support and that they should put some effort into fixing this.

**Comment by bepzi** [comment]
@Technius I'll have to double check. I assumed so, but I guess I don't know for certain.

@LittleHuba That's unfortunate to hear; I'll file a bug report and hopefully something will come of it eventually. Fixing GTK+ was the better solution anyways.

**Comment by LittleHuba** [comment]
@bepzi are you experienced in programming with C/C++?

**Comment by bepzi** [comment]
@LittleHuba Yes, though not really on Windows. I was able to call some of the Windows Ink API functions in my own fork of Xournal++, though like you said that won't be enough if I can't register a listener on the event loop. I may try to investigate the GTK+ issue when I have some time.

**Comment by LittleHuba** [comment]
Well the input system of Xournal++ is prepared to handle different input systems of OSs with the newly introduced abstraction layer.
We might consider patching GTK to let us handle input events ourselves. But I'm not sure how good that would work as we would still want to relay all the events to the normal UI elements and only handle the drawing events.

**Comment by bepzi** [comment]
Just an update: this issue is already filed in the GTK+ repository as [#262](https://gitlab.gnome.org/GNOME/gtk/issues/262)

I was able to get pressure sensitivity to work for my specific tablet! Starting with the Surface Pro 2017 (5th Gen) Microsoft stopped shipping the WinTab drivers with the device, but I just installed them from the [Surface Pro 4 Drivers](https://www.microsoft.com/en-us/download/details.aspx?id=49498) page and they worked as expected. I now have consistent writing and pressure sensitivity in Xournal++. Obviously this is not supported by Microsoft; for anyone else who wants to try this, YMMV.

**Comment by chengyuhui** [comment]
I am on a Yoga 260 tablet, can confirm that WinTab drivers help (it is not installed by Windows Update, had to look on manufacturer's website).

However, touch gestures(i.e. pinch zooming) seems broken.

**Comment by LittleHuba** [comment]
> Just an update: this issue is already filed in the GTK+ repository as #262

This is a really old issue... We have a solution that might fix this in the long run. But we have to first make GTK+ give us access to the system events so we can parse them on our own. As this is a really huge task this will take some time. So for now the WinTab driver has to suffice.

**Comment by LittleHuba** [comment]
> However, touch gestures(i.e. pinch zooming) seems broken.
This will be fixed by #1460

**Comment by Gansgar** [comment]
I would like to help you with this problem. it's quite frustrating that there's no good pdf annotator out there for windows.

**Comment by Gansgar** [comment]
I'm unsure about the structure of the project, but wouldn't it be possible to build your own Event Loop, that merges the GTK+ events with the Windows Pen API?

**Comment by LittleHuba** [comment]
Cool @Gansgar !
Here are some pointers for the necessary steps. Our internal event-handling code is actually well-prepared for this scenario! Your work will be mostly around parsing the events.

What you will need to do:
1. Register another event loop with Glib, which gets the events from Windows
2. Map the events to the current Event-API of our input system (InputEvent class)
3. Filter for events that occur within the bounds of the drawing view (and event sequences that start in the view and leave it)
4. Forward these events to our input-system (InputContext class)

Doesn't sound very complex but you'll work on that one for some time... Happy coding!
If you run in any problems feel free to contact us here or on Gitter (link in the readme)

**Comment by Gansgar** [comment]
Thanks a lot ^^

I'm happy to help. I use a Surface Pro for study and it annoys me that there's no good PDF annotation software out there. Xournal++ is currently the best I've see so far.

**Comment by Gansgar** [comment]
is the GLIB integration needed? Couldn't I trigger a function from `InputEvent` class directly from the Windows Pen API event queue?

**Comment by LittleHuba** [comment]
The thing is that the windows event queue only allows for one listener ->Glib which is required for a lot of components. You might be able to hack your way around that restriction though. I'm not really deep into the workings of Windows so feel free to find your own way.

**Comment by Gansgar** [comment]
oke thanks. I'll see what I can do. I wasn't sure of this restriction has any practical consequences

**Comment by Gansgar** [comment]
Just for history - This is the current state of the input system using my Surface Laptop.
https://www.youtube.com/watch?v=kt8VP5k_bqA

**Comment by Technius** [comment]
There appears to be active work in getting Windows Ink support into GTK: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1563

**Comment by Gansgar** [comment]
That is an interesting development. Does anybody know if it is feasible to compile xournalpp with the latest GTK build that supports it or are there other incompatibilities?

**Comment by LittleHuba** [comment]
That would depend on what they changed. Only one way to find out: try it with a manual build on your system. You'll have to check if the GTK version was already updated in the package or build GTK by hand.

**Comment by Technius** [comment]
Hey everyone, you might be interested in this comment: https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-717523378

**Comment by rolandlo** [comment]
This has been fixed with the release of Xournal++ version 1.1.0-hotfix.1
