### ISSUE TITLE
Hand-drawn signature is pasted at the bottom of the document

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#1350]
I selected it, hit "copy", but the "paste" operation pastes it at the very bottom of the document, and not at the "current", visible location as expected.

**Comment by Technius** [comment]
Related to #877 and #1165.

**Comment by lehmanju** [comment]
@yurivict where do you copy your signature from? did you write it in xournal or is it a graphic from outside the programm? Could you describe your steps to reproduce this? Maybe try #1372 and check whether this fixes it.

**Comment by yurivict** [comment]
> where do you copy your signature from

From another instance of ```xournalpp```. It was hand-drawn there.

**Comment by yurivict** [comment]
> Maybe try #1372 and check whether this fixes it.

1.0.13-nightly.20190722 still has the problem.


> Could you describe your steps to reproduce this?

1. Draw something by hand in one document.
2. Select the drawing and copy it into the clipboard.
3. Open another instance of xournalpp
4. Paste into the middle of the page
5. Observe that it was pasted at the bottom of the page (or maybe it pastes at the exact same location it was in the original).

**Comment by Technius** [comment]
@yurivict Nightly builds don't include PR changes, you'll have to compile #1372 manually. You can do so by cloning the PR repository ([instructions here](https://github.com/xournalpp/xournalpp/wiki/Installing#building-a-pull-request)) and following the build instructions for your platform (e.g. in the readme folder at the repository root)

**Comment by yurivict** [comment]
#1372 improved the behavior, now it pastes exactly at the center of the screen.

IMO, it would be better if it would paste at the cursor location.
