### ISSUE TITLE
Edit existing text

### ISSUE THREAD

**Issue by hellocatfood** [xournalpp/xournalpp#1360]
**Describe the solution you'd like**
I'd like the ability to edit text already within a pdf. This would mean deleting text or replacing it with other text

**Describe alternatives you've considered**
The alternatives include using Inkscape and Libre Office Draw, both of which allow text editing.

**Comment by Technius** [comment]
This would be a great feature to have but this requires non-trivial changes to the rendering/selection system, so we won't be able to get to this for a long while.

**Comment by LittleHuba** [comment]
I think this is actually out of scope for Xournal++ as an annotation software. We have the paradigm of not changing the actual PDF as it would make undo/redo very hard and could corrupt the actual PDF. Additionally PDFs are very hard to edit depending on their quality.

For this reason I'll close this issue but you may bring very good reasons forward why we should change this current paradigm.
