### ISSUE TITLE
Decide which Binary File Format to use

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1362]
Save files in a binary format for efficient size and speed.

I would suggest we look into protocol buffers or other comparable serial data format.
See: https://en.wikipedia.org/wiki/Comparison_of_data-serialization_formats

Some of these facilitate backward compatibility between versions etc.
Some support c++ and/or others.
Managing our own custom format is an option as well but in any case versioning needs to be considered.

**Comment by LittleHuba** [comment]
The only really viable option I see is [protobuf](https://github.com/protocolbuffers/protobuf). We need to think about this before we actually add the new file format (#937)

**Comment by LittleHuba** [comment]
Checking further we should go with: [Cap'n Proto](https://capnproto.org/index.html) which will allow us to implement random access patterns in the future. This would even enable us to include all the data inside the file and remove the need to zip up the attachments.

**Comment by LittleHuba** [comment]
We should decide if we want to keep the zip compression around it and the attachments separate from the annotation file or wrap all attachments into the proto file.

**Comment by LittleHuba** [comment]
Keep zip layer and handle attachments separately? This would mean that we can not open remote files as the zip layer is incompatible with this.

/polls  'Yes' 'No'

**Comment by LittleHuba** [comment]
Keep zip layer and handle attachments separately? This would mean that we can not open remote files as the zip layer is incompatible with this.

/polls 'Yes' 'No'

**Comment by LittleHuba** [comment]
Keep zip layer and handle attachments separately? This would mean that we can not open remote files as the zip layer is incompatible with this.

/polls Yes No

**Comment by andreasb242** [comment]
> Remove zip layer and handle attachments internally? This would mean that we can finally handle remote files which is impossible with the zip layer.

It would be easy possible to support remote files, also with the current implementation. Have a look at the GTK / GLib Documentation:

/**
 * g_file_is_native:
 * @file: input #GFile
 *
 * Checks to see if a file is native to the platform.
 *
 * A native file is one expressed in the platform-native filename format,
 * e.g. "C:\Windows" or "/usr/bin/". This does not mean the file is local,
 * as it might be on a locally mounted remote filesystem.
 *
 * On some systems non-native files may be available using the native
 * filesystem via a userspace filesystem (FUSE), in these cases this call
 * will return %FALSE, but g_file_get_path() will still return a native path.
 *
 * This call does no blocking I/O.
 *
 * Returns: %TRUE if @file is native
 */
gboolean
g_file_is_native (GFile *file)


https://github.com/GNOME/glib/blob/master/gio/gfile.c


So you can convert a GIO Path to the local mounted one, and the local mounted one (FUSE or a real mount, don't matter) can be opened over the Path. So there don't need to be much changed.

So please don't mix remote file support with the binary fileformat.

**Comment by LittleHuba** [comment]
> So please don't mix remote file support with the binary fileformat.

Did not know about that functionality. But that would be a very nice solution for the problem of remote files. So we will handle this separately.

Since the restriction is now gone we should stay with the zip-file system as it makes things like thumbnails, audio-handling, manual extraction of attachments so more easier.

**Comment by umhau** [comment]
As a user, I'm glad to see how this discussion went.  I'm looking forward to being able to use this similarly to onenote.
