### ISSUE TITLE
Opening menu by touch/stylus does not work

### ISSUE THREAD

**Issue by lehmanju** [xournalpp/xournalpp#1364]
**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++: 1.0.12, master

**Describe the bug**
Tapping on a menu will not open the menu, this issue can be categorized into multiple subsections:

- Using **GNOME/Wayland**: The menu does not open when using stylus input and occasionally bugs when using touch input. This is a GNOME/mutter issue as their Wayland compositor does not relay stylus clicking as `button press/release` events. Touch events regularly get canceled (probably by gesture recognition) therefore menus don't open/close correctly. See https://gitlab.gnome.org/GNOME/mutter/issues/711 and https://gitlab.gnome.org/GNOME/mutter/issues/713

- Using **wlroots Wayland compositors**: Menu opens/closes correctly after single touch tap/stylus clicking. 

- Using **X11**: Menu works correctly with stylus but doesn't open on touch tapping. See https://gitlab.gnome.org/GNOME/gtk/issues/945

On all compositors you have to double tap the menu to close it again using touchscreens.

**Expected behavior**
Menu should open after one tap.

**Comment by lehmanju** [comment]
My settings file: https://cloud.devpi.de/s/NHEpZi4yWo3ciao

**Comment by lehmanju** [comment]
Seems to be caused by https://gitlab.gnome.org/GNOME/gtk/issues/945

**Comment by schuhumi** [comment]
I have the same issue on Wayland as well (running natively on wayland, not through xwayland, checked with xeyes not folowing the cursor when in xournalpp window). It works for me after multiple taps, and I suspect the issue is in some way related to the fact, that with an touchscreen in contrast to a mouse pointer you don't get a hover event before the click. Geany for example also has the same problem (seems to use the same menu widget, also runs on wayland natively)

**Comment by lehmanju** [comment]
For some reason it works perfectly on firefox ... I can reproduce the issue on Wayland though.

**Comment by lehmanju** [comment]
Nvm, issue is present on all GTK3 Wayland applications (Firefox ran through XWayland earlier as native Wayland isn't activated by default). Menus in GTK3 get `touch_cancel` events even though it should be `touch_end`.

**Comment by lehmanju** [comment]
This is unbelievable: On `weston` GTK3 runs just fine, although you have to double tap a menu to close it again, on `Gnome Wayland`, however, you get regular `touch_cancel` events because of gesture detection (only on menus though)!? … And on `X11` it doesn't work at all.

**Comment by lehmanju** [comment]
Related to https://gitlab.gnome.org/GNOME/mutter/issues/711

**Comment by lehmanju** [comment]
Gnome fixed this even though it is still a little bit buggy, closing as it is a dependency issue.
