### ISSUE TITLE
SVG for Highlighter

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#137]
I'm getting an error ```Couldn't find pixmap file: tool_highlighter.png```. Probably the old PNG should be put back in unless someone wants to make an SVG for that icon.

**Comment by MarPiRK** [comment]
I think, that we need icon redesign - every icon is in different style. Also there are some standard theme icons, such as document-new, user-bookmark, insert-text, gtk-fullscreen, image, emblem-default and so on, which can be used instead of self made.

**Comment by wbrenna** [comment]
I think this is still present in the most recent pull request - did you find a highlighter in gtk standards?

**Comment by MarPiRK** [comment]
No, it's just my opinion about our current icons. I've told with my sister (she's graphic design  student) and she agreed she may redesign tool icons.

**Comment by andreasb242** [comment]
The icons are now from different sources, some are SVG and self made, some pixel graphics.
I would prefer to have all icons from the same source, and as SVG. But I cannot do it ;-)

**Comment by MarPiRK** [comment]
For now my sister has too much of her own work, so it's not possible to her to make new icons.
I think that for now we should revert old icon.
(I'll do it in a moment)

**Comment by MarPiRK** [comment]
Can be closed
