### ISSUE TITLE
Multiple pointers in GNOME/Wayland

### ISSUE THREAD

**Issue by lehmanju** [xournalpp/xournalpp#1382]
**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++: all

**Describe the bug**
Whenever using GNOME/Wayland and trying to draw sth. with an active pen, xournalpp keeps showing both pointers (last mouse position on the drawing pane and current active stylus position). This results in conflicting behavior between mouse and pen. This does not happen on other wayland compositors (e.g. sway/wlroots).

**To Reproduce**

1. Move mouse into drawing pane
2. Draw sth with pen (mouse stays in drawing pane)
3. Activate eraser (eraser also activates at last mouse position)
4. Both pointers can be moved around independently (as seen in the video)

**Expected behavior**
Disable mouse drawing/erasing abilities while pen is in drawing area. Mouse should probably be switched to hand tool and not be affected by tool switches.

**Screenshots of Problem**
[video](https://cloud.devpi.de/s/4iPm4TJdntLLEgW/download)

**Comment by andreasb242** [comment]
*This issue happens on wayland only*
I also had this some time ago (but I'm not using wayland usually)

**Comment by lehmanju** [comment]
My proposed behavior is:
- stylus enters the drawing area/moves in drawing area -> mouse disappears (*if in drawing area*)
- stylus leaves -> mouse reappears (*if in drawing area*)
- in case leave event for mouse is missing set cursor visible on movement/press events (*if in drawing area*)

It seems quite complicated to have different active tools for different cursors as this would need saving last active tools and switching between tools for different devices. Therefore the simple solution is to have similar behavior to scrolling by single finger touch (*mouse cursor disappears and is shown again on movement*).

**Comment by LittleHuba** [comment]
As mentioned in Gitter Xournal++ is not written to handle multiple inputs of different devices at the same time. Implementation of that is not as easy as just blocking all except one input device. As users will normally not use multiple devices at once this should also not present an issue.

You may use the blocking functionality of the MouseInputHandler and call it when there is some stylus input (This is actually done for the TouchInputHandler already). You will also have to make the cursor temporarily invisible when blocking the input hander. This will take some more work as the cursor system does currently not handle multiple cursors separately.

**Comment by lehmanju** [comment]
Additionally, there seems to be an issue with gtk. https://gitlab.gnome.org/GNOME/gtk/issues/2070

**Comment by lehmanju** [comment]
Fix is available, waiting for merge: https://gitlab.gnome.org/GNOME/gtk/merge_requests/1044

**Comment by lehmanju** [comment]
Another dependency issue: https://gitlab.gnome.org/GNOME/mutter/issues/75

Apparently, it is not intended to have multiple pointers on the screen. As soon that one is resolved xournalpp should work correctly out of the box.

**Comment by LittleHuba** [comment]
Seems like the devs are not really interested in fixing it

> That is expected, as under Wayland tablets are separate from normal mice.

Also the issue is 9 months old...

**Comment by lehmanju** [comment]
Closing, as it doesn't really impact usability and is not within our scope of fixing.
