### ISSUE TITLE
On window resize page scrolling is not working

### ISSUE THREAD

**Issue by lehmanju** [xournalpp/xournalpp#1383]
**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++ master

**Describe the bug**
After starting xournalpp you can barely move the page around by touch and hold scrolling. Horizontal movement does not work at all. After CTRL+Mouse zooming everything works fine.

This happens when resizing the window, specifically from smaller to larger as the page zooms in as well it lands partly outside the viewport.

**To Reproduce**
1. Start xournal++
2. move page around

**Expected behavior**
Render the page centered on startup and be able to scroll without any issues.

**Screenshots of Problem**
![Bildschirmfoto von 2019-07-28 20-20-43](https://user-images.githubusercontent.com/6310133/62011172-2b76b280-b175-11e9-85dc-3e6ed1d1ac37.png)

**Comment by Febbe** [comment]
Is the left alignment also there with the fix in the refactor_layout_resize branch

**Comment by lehmanju** [comment]
Unfortunately, not fixed. As it is only happening on X11 and scrolling is done by GTK this might be a dependency issue?

**Comment by lehmanju** [comment]
**Update**: Happens on X11/Wayland and is related to window resizing. See original description.

**Comment by lehmanju** [comment]
Happens only on fit to window width zoom setting.

**Comment by lehmanju** [comment]
You have to have additional horizontal/vertical space enabled in settings.
