### ISSUE TITLE
Keyboard input not recognized in document search

### ISSUE THREAD

**Issue by raphasu** [xournalpp/xournalpp#1385]
**Affects versions :**
- OS: Linux Mint 19.1 Cinnamon, Cinnamon version 4.0.10
- Hardware: Lenovo X1 Yoga
 - Version of Xournal++ 
   1.0.13
   20190729.1322
   b369cf06-dirty

**Describe the bug**.
No keyboard input is recognized in the document search field. This persists also with an external keyboard plugged in. For other functions of Xournal++ the keyboard works properly, for instance in text fields or when using Ctrl+F. 
On a second system with identical OS and hardware the problem exists as well. 

**To Reproduce**
- Open a blank page or pdf document
- Access the search field via Ctrl + F
- Type any text in the search field

**Comment by Technius** [comment]
Can you clarify what you mean by "document search field"? As far as I'm aware there's only the text search accessed by Ctrl+F (I can't reproduce the issue with text search).

**Comment by raphasu** [comment]
Yes, what I mean is the text search, the one which is accessed by Ctrl+F.

**Comment by lehmanju** [comment]
@raphasu are you sure the input is not recognized? You could be using a gtk theme (especially dark themes) causing problems, i.e. you don't see any input but it in fact it exists, might just not be visible because font and background have the same color.
