### ISSUE TITLE
Toolbar decreases in size if "Customized" 

### ISSUE THREAD

**Issue by fxkrait** [xournalpp/xournalpp#1395]
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
  -- Arch Linux
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]
 -- xournalpp 1.0.12-1
 -- xournalpp-git

**Describe the bug**
 If clicking on the menu item "toolbars"->"customize", the toolbar shrinks in size. This only works if the toolbar is or becomes a custom user defined copy (where the user clicks "Yes" to create a new user-defined toolbar out of the pre-defined toolbar they are wanting to customize).

**To Reproduce**
On a predefined toolbar
1. Load Xournal
2. Load any of the predefined toolbars as the default
3. Restart Xournal (just so it launches with a default toolbar at the start)
4. click on the menu item "toolbars"->"customize", and click "Yes" to make a copy
5. Notice the toolbar size has now shrunk

On a user-defined toolbar
1. Load Xournal (with your user-toolbar)
2. click on the menu item "toolbars"->"customize"
3. Notice the toolbar size has now shrunk

**Expected behavior**
toolbars should remain a consistent size.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

Pre-Defined Toolbar, (Click "YES")
![3](https://user-images.githubusercontent.com/7407672/62431460-9166bb00-b6dc-11e9-8e0b-9da9c9082829.png)

Toolbar has now shrunk in size:
![4](https://user-images.githubusercontent.com/7407672/62431481-afccb680-b6dc-11e9-9219-9e62ef187355.png)

**Additional context**
It would be nice if we could change the scaling for the toolbar size. 
I manually use this "bug" to shrink my custom-toolbar because it appears so large on my device.
It would be nice if I could just set it to the smaller size in the settings.

**Comment by LittleHuba** [comment]
The toolbar will get a major overhaul sometime in the future. Including context-sensitive layouts. I think then would be the right time to also allow for user-specified scaling.

**Comment by JJones780** [comment]
Thanks for reporting this bug.
I've taken out the offending line and you won't be able to reduce the icons sizes using this bug soon... however not long ago I updated Xournal++ to use a css file. You can make changes there to customize the toolbox icon sizes. 
You can try this on Xournal++ released after June13 2019.  ( so a 1.0.13 nightly or 1.0.14+)

The css file on my system is located at:  /usr/local/share/xournalpp/ui/xournalpp.css

```
/*  If you want to change the size of toolbar icons add these to your xournalpp.css:
*   All toolbars:
*/

GtkToolbar GtkButton
{
	padding: 2
}




/* Or for individual toolbars: tbLeft1 tbLeft2 tbTop1 tbTop2 tbBottom1 etc: 
 */

#tbLeft2 GtkButton
{
	padding: 2
}

```

p.s. Also see [GTKInspector]( https://wiki.gnome.org/action/show/Projects/GTK/Inspector ) to investigate other css possibilities.
