### ISSUE TITLE
Highlighter and non-pressure strokes render incorrectly when selected

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1402]
**Affects versions :**
 - OS: Solus Linux
 - Version of Xournal++: `master` @ `a6276cd`, perhaps earlier

**Describe the bug**
Adjacent highlighter and non-pressure strokes do not render correctly when selected/deselected (see attached images).  This behavior does not occur with pressured strokes (e.g. with a drawing tablet).

**To Reproduce**
1. Open a new document.
2. Draw a few highlighter strokes so that their bounding boxes overlap.
3. Select and deselect each of the strokes until you observe the rendering error.
4. Draw a few non-pressure strokes (e.g. with a mouse) and repeat step 3.

**Expected behavior**
The strokes should not exhibit rendering errors.

**Screenshots of Problem**
![xpp_highlight](https://user-images.githubusercontent.com/1066652/62677556-a0ab6a00-b963-11e9-8f2a-cfa3ee818aa8.gif)

**Additional context**
N/A

**Comment by JJones780** [comment]
> 3. Select and deselect each of the strokes until you observe the rendering error.

I didn't get this behaviour at first...  I had to use the arrow selecting tool to get it.
When I used my experimental selection method ( pen tool and `Prefs->DrawingArea->Action on Tool Tap->Trytoselect object first` ) or used the `select rectangle` or `select region` tools it didn't have this problem. 

_Note: It's also mis-calculating the selection boundary ( adding to the width and height but not offsetting properly )._

**Comment by Technius** [comment]
You're right, it looks like only the `Select Object` tool is affected. But the issue still occurs when `Try to select object first` is enabled.

**Comment by Technius** [comment]
I just confirmed that the issue occurs with any object, not just non-highlighter strokes (e.g. try inserting an image and reproducing the bug). The issue does not occur because `Select Rectangle` and `Select Region` force a whole page repaint; `Select Object` only triggers repaint on overlapping objects, but it doesn't seem to be working correctly.

**Comment by LittleHuba** [comment]
The problem is that we check for overlapping objects for the selection area itself but repaint the selection area and the surrounding area for the buttons as well.

**Comment by Technius** [comment]
I cannot reproduce this issue on master branch anymore.
