### ISSUE TITLE
Have text with multiple colors in same text box

### ISSUE THREAD

**Issue by fxkrait** [xournalpp/xournalpp#1406]
**Is your feature request related to a problem? Please describe.**
I'm trying to use xournal for notetaking, and would like to be able to have keywords set to distinct colors from the main text color.

Most of the text I just drag and drop from a PDF ebook in Evince. The current way that I do this is simply to drag and drop (making a text box) with just the keyword, color it, then do the same for the main text, and try to line it up as best I can. However, this is a lot slower than being able to drag and drop the text in its entirety and then changing the color of certain keywords. It is also makes it more difficult to copy the entirety of the text into say an anki card afterword, as now I have to copy and paste multiple snippets of text. 

I believe this is partially related to #1092, in terms of having text with different styles in the same text field. However, that issue talks only about text styles (bold/italic/etc) and not text colors, so I believe this is slightly different. I can remove this if they are too similar, and add a comment to that issue.

**Describe the solution you'd like**
I would like to be able to select the keyword text, and click on the color icons to change it to the given color, while keeping the main text the same.

**Additional context**
Example of what I am doing:
![multipleColors](https://user-images.githubusercontent.com/7407672/62776257-e39e3800-ba5e-11e9-82ed-3d08075cb50c.png)

**Comment by Technius** [comment]
This can be implemented much more easily than #1092 but is definitely limited in scope, so I'll leave this open for now.

**Comment by JJones780** [comment]
See #1430 for an interesting hack that may lead us to a workable solution.

Let's take the discussion to #1092.  I'll let you close this issue and join over there.
Your feedback is appreciated!

**Comment by fxkrait** [comment]
Sounds good.
