### ISSUE TITLE
Please provide updated instructions to build/compile xournalpp

### ISSUE THREAD

**Issue by KeshavA2016** [xournalpp/xournalpp#141]
I am an Arch Linux user interested in maintaining xournalpp-git package in AUR but I am confused as to which git branch to compile from and how to compile it, as the current Arch specific instructions are marked as outdated in the wiki. Can you please guide me to build this? I am a student at a university and xournalpp is absolutely essential for me. Thanks in advance.

**Comment by MarPiRK** [comment]
Everything was told in Slack channel #releases.

**Comment by MarPiRK** [comment]
Can it be closed @KeshavA2015 ? Do you have all needed information?
