### ISSUE TITLE
lcms dependency

### ISSUE THREAD

**Issue by corna** [xournalpp/xournalpp#144]
lcms(1) is not present anymore in the [Debian repos](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=liblcms) as it has been replaced by lcms2.
In the file src/pdf/popplerdirect/poppler-0.24.1/CMakeLists.txt, line 34, we can see that both lcms1 and lcms2 are supported by poppler.
Is it possible to update the lcms requirement in CMakeLists.txt to lcms2 (or require one or the other)?
Also the .travis.yml should be updated as well

**Comment by MarPiRK** [comment]
Yeah, I think changing it to 2nd version shouldn't make any difference.

**Comment by MarPiRK** [comment]
Fixed in MarPiRK/xournalpp@903f789d1b2e1156707f52922ff252ce2b53f6b7. I'll request pull after cleaning up some warnings and when travis-ci/apt-package-whitelist#1341 will be merged (it'll be possible then to convert to container-based Travis build).

**Comment by corna** [comment]
Is there a way to use either lcms or lcms2 in pkg_check_modules?

**Comment by MarPiRK** [comment]
I think that sure, but what for? lcms2 should be available in every recent distro.

**Comment by corna** [comment]
Yes, but why should we drop support for lcms1 when it works perfectly with it?

**Comment by MarPiRK** [comment]
All right, let it be.

**Comment by MarPiRK** [comment]
The best situation would be if poppler CMake build system supported creating static libraries – it'd be just basic ExternalProject not Autotools based one, where to link I need to recheck checked things :confused:.

**Comment by MarPiRK** [comment]
Can be closed

**Comment by corna** [comment]
Great, thanks
