### ISSUE TITLE
making mirror image with resize tool

### ISSUE THREAD

**Issue by ehremington** [xournalpp/xournalpp#1440]
In the old xournal, you could take a selection and by grabbing and dragging one side of the selection box, you could mirror and resize the image. This seems like a minor thing, but I have found myself missing this feature in xournal++ in my physics class. Maybe hard to introduce but it is the only place that I've found to be a regression from the original program.

And while I'm hear let me express my great thanks to everyone working on the project! The addition of a rotation tool to selections was a huge improvement over the original and all of the update going here have been wonderful. So glad this project has taken off!

**Comment by JJones780** [comment]
I can't remember the exact problem, but there might even be a blocking issue to this enhancement. Maybe it wasn't worth doing until rotation was cleaned up?

**Comment by LittleHuba** [comment]
If I remember correctly it was that the file format does not support it. You mentioned transformation matrices as a possible solution.

**Comment by JJones780** [comment]
Yes, I believe there are a few issues which would all be fixed by using ( and storing ) a matrix transform instead of recalculating points and thicknesses.
Off the top of my head I think it included
 - allow the rotation of images ( and other imported objects )
 - editing already rotated objects ( using the handles )
 - editing already scaled objects (using the handles )
 - mirroring objects using scale handles.

**Comment by Technius** [comment]
Related to #918.

**Comment by rolandlo** [comment]
Cloning a selection is already possible. Just right click with your mouse or use pen button 2 (you can remap pen buttons with `xsetwacom` if needed). So I will close this issue.

**Comment by ehremington** [comment]
Wait cloning a section was not what this feature request was about. I would like the a functionality that was present in the original xournal to be present if possible in xournal++. Let me describe again the feature: Upon making a selection, the handle on the side of the selection that allow resizing should also be able to be dragged "through" the unmoving side of the selection to produce a mirror image. This may seems like a minor thing, but in my experience teaching a live physics class with many drawings, I found that I missed it upon moving from xournal to xournal++. I believe that this feature is low priority but is closing this issue the same as a "won't fix"?

**Comment by rolandlo** [comment]
Sorry I misunderstood. I agree, that this would be useful.

**Comment by rolandlo** [comment]
@ehremington Am I assuming correctly that you only need this mirroring feature for strokes? For images, TeXImages and text it would be much harder to implement, I think. Xournal also only mirrors strokes and just moves and scales the other elements.
