### ISSUE TITLE
Drawing a circle by specifying the center and radius

### ISSUE THREAD

**Issue by hatsunearu** [xournalpp/xournalpp#1445]
**Is your feature request related to a problem? Please describe.**
The circle function draws an ellipse by setting major diameter and minor diameter to the x and y displacement of the cursor (i.e. specifying the two "corners" of the ellipse). For some applications (I'm doing stuff with Smith charts) it would be cool if I can click the eventual center of the circle, and the end point of the stroke be the radius of the circle.

**Describe the solution you'd like**
uhhh described above

**Describe alternatives you've considered**
I'm not super good with C++ though I might take a stab at it over the weekend

**Additional context**
nothing really

**Comment by Technius** [comment]
We can keep the ellipse functionality by making the circle mode apply only when holding down e.g. Ctrl or Alt. We could also change which mode is the default (though exactly which is which is up for debate).

**Comment by hatsunearu** [comment]
By pressing Ctrl I get a center-radius mode, but I can't make it a circle and not an ellipse.

I wish you could press another button to make it a circle.

**Comment by JJones780** [comment]
The control and shift keys should work together to do what you want.. if not  then it's a new bug.
In the meantime you can go to prefs and try turning on the  experimental drawingArea->drawdir feature  as in this screenshot:
![image](https://user-images.githubusercontent.com/2329541/64054141-eb736880-cb42-11e9-8440-797d31ad01aa.png)

p.s.  it works in yesterdays code.. I haven't updated today and won't be able to get to any code for at least 6 hours.

**Comment by hatsunearu** [comment]
That is correct. Sorry, I didn't notice. control + shift makes perfect circles and by specifying the center.

**Comment by dadosch** [comment]
Pressing Control Shift is not possible when there is no keyboard available, for example on foldable 2-1 devices. It would be a good idea to have a setting which would flip this behaviour, so that if no ctrl+shift is pressed, the center-circle is drawn...

**Comment by tim-clifford** [comment]
The following patch is all that's needed to flip the behaviour of ctrl and shift to make this the default. When I'm a bit less busy I'll try to make a setting for it and open a PR.

```patch
diff --git a/src/control/tools/CircleHandler.cpp b/src/control/tools/CircleHandler.cpp
index 1e5b0f16..419ed66c 100644
--- a/src/control/tools/CircleHandler.cpp
+++ b/src/control/tools/CircleHandler.cpp
@@ -41,7 +41,7 @@ void CircleHandler::drawShape(Point& c, const PositionInputData& pos) {
             this->modifyModifiersByDrawDir(width, height, true);
         }
 
-        if (this->modShift)  // make circle
+        if (!this->modShift)  // make circle
         {
             int signW = width > 0 ? 1 : -1;
             int signH = height > 0 ? 1 : -1;
@@ -57,7 +57,7 @@ void CircleHandler::drawShape(Point& c, const PositionInputData& pos) {
         double angle = 0;
 
         // set resolution proportional to radius
-        if (!this->modControl) {
+        if (this->modControl) {
             diameterX = width;
             diameterY = height;
             npts = static_cast<int>(std::abs(diameterX * 2.0));
```
