### ISSUE TITLE
Sensitivity is more worse than in xournal

### ISSUE THREAD

**Issue by Raffinade** [xournalpp/xournalpp#1449]
I use a Bamboo Stylus and tested it under xournal und xournal++. The Sensitivity is not as good than in xournal. Sometimes i have to write a letter a few times because my input is not recognized the first time. 

Greets 
Raffinade

**Comment by LittleHuba** [comment]
Have you activated to new input system in the settings?

**Comment by Raffinade** [comment]
Yes i use a bamboo pen and i needed to activate the new input system. But i observed, that if i connect the surface with power, the pen reacts not such sensitiv as i want, so i think its more an influence of the powercable if its connected.

**Comment by LittleHuba** [comment]
Oh that one might be hard to fix... I require the input logs of Xournal++ for this. Please follow these [instructions](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) and create both logs for the following scenarios:

1. power cable is not attached
2. power cable is attached

Please draw exactly four straight lines per scenario that go from each corner to the next corner. Start at the upper right corner and go around clockwise.
Additionally I need to know the following information:
- where your power cable connects to the PC relative to the screen
- what device you actually use and if it is an active pen or a passive pen (does the pen have a battery or some way to charge it or is it only a piece of metal (older pens are most likely of this category))

**Comment by Raffinade** [comment]
I followed the instructions, but there are to many depencies for cmake. So i didnt do that further. 
Sorry

**Comment by LittleHuba** [comment]
Then I will unfortunately be unable to help you. Without these logs tracking the bug and searching for a solution is like looking for the needle in the haystack.
