### ISSUE TITLE
New page has same dimensions as previous page

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1453]
**Is your feature request related to a problem? Please describe.**
If I'm annotating slides (4:3 ratio, 5.04 × 3.78 inch paper size) and I want to add a new, intermediate page, the new page is the default size (for me, letter). This is very jarring if there's a large size mismatch (like here)

**Describe the solution you'd like**
Would prefer if the default was to copy the previous page's size. Don't want to have to modify page size each time I open Xournal++, as I also often work with letter paper size documents. 

**Describe alternatives you've considered**
Manually modify page template each time I open a different document, but this is tedious.

**Comment by andreasb242** [comment]
Just set the Checkbox in the Page template, to copy the last page size.

![grafik](https://user-images.githubusercontent.com/822958/64201834-ea6a7000-ce8f-11e9-852d-2a500bbe7c58.png)

Menu Journal / Page template.
