### ISSUE TITLE
Tool icons rework

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#146]
As it was said in #137 there's need to redesign all icons, so they comply with each other.
It would be the best if we used ready-made icon set, but I don't think that something containing all needed icons exists.
My sister (graphics student) offered her help, but for now she's really busy and cannot do it. If something will change, I'd give a sign.

**Comment by andreasb242** [comment]
Strip it a little down: replace all PNG icons with SVG, so they can be scaled for High DPI Monitors...
This is currently only tool_highlighter.png

**Comment by andreasb242** [comment]
PNG Toolbar icons replaced by an SVG Version
