### ISSUE TITLE
Build for armhf as well

### ISSUE THREAD

**Issue by JulianGro** [xournalpp/xournalpp#1461]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to install xournalpp on Ubuntu Touch (Ubuntu 16.04 armhf based), without compiling it from source, which (at least on my device) takes absolute ages and is a huge pain.

**Describe the solution you'd like**
Adding an armhf build to the PPA would allow to install xournalpp much more easily on such devices.
I would hope that this wouldn't be much of a problem, since there is already arm64 packages being build.

Even if I cannot be sure that xournalpp will actually work on Ubuntu Touch, I would think that there is more than just Ubuntu Touch devices out there that run armhf rather than arm64.

**Comment by LittleHuba** [comment]
We would need to crosscompile this in our Azure pipeline. I have never built an application for Ubuntu Touch nor have I any way of testing if the actual thing works afterwards. You are welcome to open an PR with the necessary steps to crosscompile this on a Ubuntu 16.04 machine formated as a YAML file that Azure Pipelines can understand.
We can help you on the requirements for Xournal++ and how to get around certain difficulties that are generic but we are unable to provide any specific support for Ubuntu Touch.

**Comment by andreasb242** [comment]
Did you try our official PPA?
 sudo add-apt-repository ppa:andreasbutti/xournalpp-master
 sudo apt update
 sudo apt install xournalpp

The ARM was successful.
I don't have an ARM Device to test.

**Comment by jug007** [comment]
@andreasb242 yes I tried that before. Apt said that it couldn't find a package. I am guessing that this is because of Ubuntu Touch being armhf and the package being arm64.

**Comment by andreasb242** [comment]
Ok, then you have probably to build it your own, I don't have more architectures to check on the PPA Build.

By the way, what device do you have?
I paid the first Ubuntu Phone Crowdfounding, even if they get about 22m$ they canceled it, because they missed 1m$ or so, and the money gets refunded...

**Comment by jug007** [comment]
Off Topic:
@andreasb242 I own a BQ M10 HD, which works perfect except of some issues with adb. (but there is an ssh server you can use, so that is not too bad)
Also I guess it is annoying that you cannot get any spare parts for the thing (not from BQ or third parties)
An interesting upcoming device is the [PinePhone](https://www.pine64.org/pinephone/) (I say upcoming, but you can already get the developer version (not prototype)) There is also a PineTab, which is basically the same thing in bigger.
All working devices are here: https://devices.ubuntu-touch.io

**Comment by andreasb242** [comment]
The Processor used in your Tablet is a 64bit, but it may be really have a 32bit OS installed. Not sure.
https://www.mediatek.com/products/tablets/mt8163

It's may not that offtopic as you thought.
I checked the list of supported devices, and the Oneplus One is supported, and there is now an installer which does nearly everything automatically. (ubports-installer)

I have a oneplus one laying around, and flashed ubuntu touch.
I'm currently installing the desktop environment, which is needed to install desktop applications.

I currently don't know, what I need to do to cross compile for Ubuntu Touch, but I already ported Xournal++ to Windows and Mac OS X, which is probably more complicated than compiling for ARM...

**Comment by jug007** [comment]
If you want to use your ubuntu touch device, you will either need to compile a clickable or use a libertine container https://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html

**Comment by andreasb242** [comment]
I'm currently installing the libertine stuff, it does not show the progress, it only shows a spinner... I have to wait ;-)

**Comment by rolandlo** [comment]
There are builds for armhf in the PPA by @archisman-panigrahi, see https://launchpad.net/~apandada1/+archive/ubuntu/xournalpp-stable/+packages. The Debian repository also contains xournalpp builds for armhf.
I'm closing the issue therefore. We can't build for all architectures and OSes on Azure pipeline.
