### ISSUE TITLE
Execinfo can be required on Linux too

### ISSUE THREAD

**Issue by Cogitri** [xournalpp/xournalpp#1462]
**Affects versions :**
 - OS: Alpine Linux Edge. Uses musl libc
 - Version of Xournal++: v1.0.13

**Describe the bug**

Xournalpp just assumes that linux always has execinfo installed, however this is not necessarily the case, only glibc bundles it. You still have to install libexecinfo on musl libc (and possibly other libcs? Not quite sure on that). It'd be nice if xournalpp just checked for the existence of `execinfo.h` instead of guessing. In case execinfo isn't built-into libc on linux it also needs to be linked into the `xournalpp` binary, otherwise it can't find the required symbols:

```
[100%] Linking CXX executable xournalpp
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(CrashHandler.cpp.o): in function `crashHandler(int)':
/home/builder/aports/testing/xournalpp/src/xournalpp-1.0.12/src/util/CrashHandlerUnix.h:70: undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /home/builder/aports/testing/xournalpp/src/xournalpp-1.0.12/src/util/CrashHandlerUnix.h:88: undefined reference to `backtrace_symbols'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(Stacktrace.cpp.o): in function `Stacktrace::printStracktrace(std::ostream&)':
/home/builder/aports/testing/xournalpp/src/xournalpp-1.0.12/src/util/Stacktrace.cpp:82: undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /home/builder/aports/testing/xournalpp/src/xournalpp-1.0.12/src/util/Stacktrace.cpp:83: undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/xournalpp.dir/build.make:593: src/xournalpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:233: src/CMakeFiles/xournalpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Technius** [comment]
You should be able to workaround it in the meantime by using `find_package` and `target_link_libraries` in `src/util/CMakeLists.txt` (PR welcome if it works!). If that doesn't completely fix it, you may also need to modify `xournalpp_LDFLAGS` in `CMakeLists.txt`.

**Comment by Cogitri** [comment]
Ah, since I don't know CMake I just used https://github.com/alpinelinux/aports/blob/974d21238c635d883f543e886633731575c4f06a/testing/xournalpp/link-execinfo.patch for now. Will look into making a proper fix :)
