### ISSUE TITLE
Usage of `mm` libraries

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#147]
As it was discussed some time ago in #111 to make Xournal++ more consistent in terms of language we should move to C++ specific libraries. Gnome related projects have pretty often their `mm` relatives (e.g. glibmm, gtkmm, cairomm, glademm, pangomm).
In general it's not that essential to do it, because when something works you shouldn't touch it :wink:, but there are also some things, which aren't working for unknown reason and moving to `mm` libraries may help in deep review of code and it may simplify some things.

First library which I'm thinking about is `cairomm`. Moving to it shouldn't be that invasive to rest of app and there's no need to immediately move to GTK3, but it would mean rewrite of drawing system, which right now causes some problems (#17, #42, #82).

**Comment by Hoeze** [comment]
Did you see:
https://github.com/Febbe/xournalpp/tree/gtkmm

**Comment by andreasb242** [comment]
Currently I think this change will bring nothing for the user, therefore I close this ticket. There are a lot of other things which makes really sense, e.g. creating ppa etc.
