### ISSUE TITLE
Cannot get french translation

### ISSUE THREAD

**Issue by Pamaceclo** [xournalpp/xournalpp#1470]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Lubuntu 19.04
 - Version of Xournal++ 1.0.13 built on Sept 12,2019

**Describe the bug**
Although basic language of the OS is French, Xournal++ is installed in English. How can I use the French translation ?
**Expected behavior**
To get French localization translation

**Comment by LittleHuba** [comment]
How do you install Xournal++ on your system?

**Comment by Pamaceclo** [comment]
Thank you for your attention,
I'm installing it with the apt command, via the ppa at the url
http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu disco main
Thanks again
Jacques Beckand

Le lun. 16 sept. 2019 à 17:40, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
Could you please provide the output of the following commands typed in your console:
```
locale
localectl
```

**Comment by Pamaceclo** [comment]
Please find the output of those commands below

jacques@jacques-maison:~$ locale
LANG=fr_BE.UTF-8
LANGUAGE=
LC_CTYPE="fr_BE.UTF-8"
LC_NUMERIC=fr_BE.UTF-8
LC_TIME=fr_BE.UTF-8
LC_COLLATE="fr_BE.UTF-8"
LC_MONETARY=fr_BE.UTF-8
LC_MESSAGES="fr_BE.UTF-8"
____________
Diacre Jacques Beckand
Unité Pastorale des Sources Vives
rue Joseph Stallaert 8, 1050 Ixelles
GSM 0476 469426
LC_PAPER=fr_BE.UTF-8
LC_NAME=fr_BE.UTF-8
LC_ADDRESS=fr_BE.UTF-8
LC_TELEPHONE=fr_BE.UTF-8
LC_MEASUREMENT=fr_BE.UTF-8
LC_IDENTIFICATION=fr_BE.UTF-8
LC_ALL=
jacques@jacques-maison:~$ localectl
   System Locale: LANG=fr_BE.UTF-8
       VC Keymap: be-latin1
      X11 Layout: be
       X11 Model: pc105
jacques@jacques-maison:~$


Hope this helps,
Thank you
Jacques

Le jeu. 19 sept. 2019 à 01:53, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
Ahh okay this explains everything. You have the belgium dialect selected for your setup. We currently don't have any translations for this dialect but only ones for traditional French.
Fortunately the tool we are using in the background for translations can handle this kind of scenario. Check out this page for further details: https://wiki.archlinux.org/index.php/Locale#LANGUAGE:_fallback_locales

You would want to set traditional french as fallback locale on your system.
```
localectl set-locale LANGUAGE=fr_FR
```

**Comment by Pamaceclo** [comment]
A big thank you for your answer.
And also all my  wishes for the wonderful job you do for Xournal++
Jacques Beckand


Le jeu. 19 sept. 2019 à 16:46, Ulrich Huber <notifications@github.com> a
écrit :
