### ISSUE TITLE
Pen starts drawing at wrong position

### ISSUE THREAD

**Issue by Cogitri** [xournalpp/xournalpp#1472]
**Affects versions :**
 - OS: Alpine Linux Edge (same with Flatpak), on GNOME 3.34 Wayland
 - Version of Xournal++ : 580ce2c79b8ca3ec35978bb82aa23d024790eb72

**Describe the bug**
The pen's starting point for drawing is incorrect if I use it with my stylus, it works fine with my mouse. The stylus (a HP Tilt Pen) works fine in xournal.

**Screenshots of Problem**
I touch the screen with the stylus in the black circle, but the actual drawing is in the left corner.

![Screenshot from 2019-09-14 15-50-46](https://user-images.githubusercontent.com/8766773/64909089-d3d1dd80-d707-11e9-924c-cf0d071dde0e.png)

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3612759/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3612760/debug_input.log)

**Comment by Cogitri** [comment]
It seems like this is due to Xournal++ assuming that I'm using a 1920x1080 screen, it works fine if I set the resolution to that but it's broken if I set my screen to its native resolution (4k).

**Comment by Cogitri** [comment]
Ah, seems like it's actually on the fact that I use 4K with 200% scaling (because otherwise fonts are too small), which Xournal++ doesn't honour. It works fine if I use 4k with 100% scaling.

**Comment by JJones780** [comment]
I was just going to ask you a question about your setup ( and a nice setup it must be.. 4k laptop touchscreen ! )...  glad you figured this out.

**Comment by JJones780** [comment]
I'm not sure if this will help...but if you want to make the toolbar buttons bigger ( and maybe it can help with other widgets if you're handy with css ) you can try a css mod hack... see my comment here   https://github.com/xournalpp/xournalpp/issues/1395#issuecomment-528289543
Use a value bigger than 2  ;)

**Comment by Cogitri** [comment]
Ah, that's not really the problem, it'd be best if Xournal++ just honours GDK_SCALE, since changing to 1920x1080 isn't nice and working with 4k@100% scale isn't nice either when I try to write on Xournal++ while reading something on the screen too (since fonts get super small)

**Comment by LittleHuba** [comment]
The scale has to be taken into acount here:

https://github.com/xournalpp/xournalpp/blob/9d02801f542b04b60dc1d914e5c0dcc742b3405d/src/gui/inputdevices/AbstractInputHandler.cpp#L95-L96

**Comment by Cogitri** [comment]
Hm, are you sure about that? My debugger doesn't trigger if  I set it to those lines when I draw with my stylus :thinking:

**Comment by Cogitri** [comment]
Ah, it's the new input system, makes sense :)

**Comment by Cogitri** [comment]
Hm, I think AbstractInputHandler.cpp is the wrong place to do this, since this only applies to input with a Pen and not to e.g. Mouse input.

**Comment by LittleHuba** [comment]
The AbstractInputHandler takes care of all input on the drawing area. All input device classes inherit from this class.

**Comment by LittleHuba** [comment]
Especially the method pointed out is the only method translating from global coordinates to page coordinates which are required for drawing.

**Comment by Cogitri** [comment]
Ah, but for everything but a Pen (and a stylus?) the coordinates are already correct, so changing the AbstractInputHandler to return correct results for a Pen will cause it to return wrong results for other input methods.

**Comment by LittleHuba** [comment]
Okay... That does not really make sense but that is GDK for you -_-
Okay then you should override the method in StylusInputHandler and add the scaling there exclusively.

**Comment by PTNobel** [comment]
I'm not a GDK expert at all, but this may not be a Xournalpp issue. Gnome Settings has the same problem where pressing buttons with the stylus creates the click in the wrong spot.

System: Arch Linux with Gnome 3.34 on Wayland.

**Comment by LittleHuba** [comment]
It is definitely not a Xournal++ issue. It is an issue of GDK itself. But the problem is that creating a ticket over at their repository and getting a fix for the issue takes normally between a month and over a year with the high tendency to the latter. So we work nowadays often around the bugs of GDK within our own code. It just makes live easier... In the long run this might be fixed and then we can remove our code again. Not the best solution I know but it is the solution that gives the fastest results for our users.

Feel free to report the bug over at GTK+ though.

**Comment by PTNobel** [comment]
Understood. Looks like there's a bunch of GDK tablet issues with this release:

https://gitlab.gnome.org/GNOME/gtk/issues/2157

If I find time this weekend I'll report it there.

**Comment by PTNobel** [comment]
Understood. Looks like there's a bunch of GDK tablet issues with this release:

https://gitlab.gnome.org/GNOME/gtk/issues/2157

If I find time this weekend I'll report it there.

Also, for anyone else who is looking for a fast fix to this issue in all the apps, my testing suggests X.org isn't effected.

**Comment by LittleHuba** [comment]
This is a GTK+ issue that sounds highly related to this issue:
https://gitlab.gnome.org/GNOME/gtk/issues/734

It's two years old and still not solved by the way :wink:

**Comment by Cogitri** [comment]
> This is a GTK+ issue that sounds highly related to this issue: https://gitlab.gnome.org/GNOME/gtk/issues/734

Hm, not really, since this happens even with a single display. Still, it's unfortunate that there's so little interest in this on GTK upstream's side.

**Comment by Cogitri** [comment]
Also, what I only just now noticed that's kind of weird: The hover position _is_ correct in Xournalpp, just the position of drawing is wrong

**Comment by LittleHuba** [comment]
> Hm, not really, since this happens even with a single display. Still, it's unfortunate that there's so little interest in this on GTK upstream's side.

Which is why I said highly related and not the ticket for the bug :wink: 

> Hm, not really, since this happens even with a single display. Still, it's unfortunate that there's so little interest in this on GTK upstream's side.

Well GTK is a big project and to be true the people using pens for input might be 5% of the whole userbase. Somewhat understandable but still quite awful.

> See https://dist.cogitri.dev/Screencast%20from%2009-21-19%2011%3A50%3A59.webm for a video

Could you make that video with the eraser? I want to see if the cursor of the eraser is where your pen is or if it is also shifted.

Still does not change anything in terms of the solution though...

**Comment by Cogitri** [comment]
> Well GTK is a big project and to be true the people using pens for input might be 5% of the whole userbase. Somewhat understandable but still quite awful.

Yup, everyone just mostly scratches their own itches, that's OSS I guess :)

> Could you make that video with the eraser? I want to see if the cursor of the eraser is where your pen is or if it is also shifted.

The eraser is also shifted :c

**Comment by JJones780** [comment]
I see you are using Wayland.  If this were X I'd point you to   [xinput configuration ](https://wiki.archlinux.org/index.php/Calibrating_Touchscreen).  A quick search and I can't see a Wayland equivalent  :( ?

**Comment by leonm1** [comment]
I'm looking at tackling this for hacktoberfest.

It looks like we can get the scale from this `GtkWidget`: https://github.com/xournalpp/xournalpp/blob/9d02801f542b04b60dc1d914e5c0dcc742b3405d/src/gui/inputdevices/InputContext.h#L49

By using `gtk_widget_get_scale_factor ()`

I believe the best way to implement this is to add a method `gint InputContext::getScale() {}` which would return the the scale of the current window.

Then, I considered overriding the `getInputDataRelativeToCurrentPage` in the `StylusInputHandler` class, but I think it would be more DRY to simply add a block inside a `dynamic_cast<StylusInputHandler>` in `AbstractInputHandler`. This block would scale the coordinates by the scale factor iff the event comes from a stylus.

**Comment by Cogitri** [comment]
Thank you :).

I think it'd be `PenInputHandler` though, at least that's what I use (not sure if styluses are also affected)

**Comment by LittleHuba** [comment]
> Then, I considered overriding the getInputDataRelativeToCurrentPage in the StylusInputHandler class, but I think it would be more DRY to simply add a block inside a dynamic_cast<StylusInputHandler> in AbstractInputHandler. This block would scale the coordinates by the scale factor iff the event comes from a stylus.

Both ways have their advantages and their drawbacks. Whichever you choose will be good in the end. 

We will have to make the fix optional though and add it into the settings dialog, as the problem only exists under certain conditions which seem to not be met by all our users. In the first PR of @Cogitri he mentioned this only being present on Wayland and not on XServer...

**Comment by Cogitri** [comment]
Yup, it only happens on Wayland. What I only now noticed is that clicking the buttons (e.g. colour selection) with the stylus works just fine, seems like the coordinates are only messed up in the drawing pane.

**Comment by Cogitri** [comment]
Uhhhhhh....it seems like this has automatically fixed itself, possibly with the GNOME 3.34.1 upgrade. I'll go see if I can find the package that fixes it.

**Comment by Jus129** [comment]
I am facing the same issue mentioned here, @Cogitri  Can you please help with which version was the issue fixed?
I created another issue at #3546 before finding this.

**Comment by Cogitri** [comment]
I think mutter 3.34.1 fixed it for me back then
