### ISSUE TITLE
Add Travis in main repo

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#148]
Travis integration is working pretty well in my repo MarPiRK/xournalpp. It can be now easily integrated to main xournalpp/xournalpp repo. There should be also added Travis badge in `README.md`.

**Comment by MarPiRK** [comment]
Hey, it's not that hard. A few clicks and it's all. I don't have rights to do this for main repo.

**Comment by wbrenna** [comment]
Sorry - unfamiliar with Travis. Can you give me the steps I'd need to take?

**Comment by MarPiRK** [comment]
Go to https://travis-ci.org/ → Sign in with GitHub
Then you have to authorize Travis to have access to organization (directly on GitHub): Settings → Applications → Travis CI → Organization access → Grant access to `xournalpp` organization.
Now all granted repos should show up in your Travis dashboard (if not, click _Sync_) and turn on xournalpp/xournalpp repo.

Embedding badge in `README.md`: after build, next to the repo name there will appear badge _Build passing_. Click on it and copy Markdown code.

**Comment by wbrenna** [comment]
OK, should rebuild once there is a push. Then I'll put the badge in.

**Comment by MarPiRK** [comment]
Nice

**Comment by MarPiRK** [comment]
PR #150 has been successfully built on Travis :smile:
