### ISSUE TITLE
Display error. When the page is not 100% visible.

### ISSUE THREAD

**Issue by elivanf** [xournalpp/xournalpp#1489]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [Ubuntu Mate 18.04.3 32-bit]
 - Version of Xournal++ [1.0.13]

**Describe the bug**

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**
When the page is not 100% visible, I see only a gray screen, but when I zoom out to see the full page I can see the page. I'm not a developer, but I really like this version of the program and would like to continue using it. Thanks.
My program looked like this after the last update. Since then I've uninstalled and installed the program, and even ubuntu itself.
**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![Captura de tela em 2019-09-21 08-11-04](https://user-images.githubusercontent.com/55623217/65391124-f5e8e280-dd3b-11e9-96ec-3860c893c9cc.png)
![Captura de tela em 2019-09-21 08-11-19](https://user-images.githubusercontent.com/55623217/65391125-f5e8e280-dd3b-11e9-9fed-76298eecbf03.png)
![Captura de tela em 2019-09-22 13-14-42](https://user-images.githubusercontent.com/55623217/65391126-f5e8e280-dd3b-11e9-98d0-e79972a83b2b.png)

**Additional context**

**Comment by Technius** [comment]
I can't reproduce the bug. Did you install Xournal++ from the PPA?

**Comment by LittleHuba** [comment]
Did the version before that work flawlessly? Could you do a downgrade to check that? We reworked the rendering system just a few commits ago to get rid of a bug and this might be a result of that.

**Comment by Febbe** [comment]
Do you really use OS: [Ubuntu Mate 18.04.3 32-bit] not the 64 bit Version? 
Xournalpp is compiled for the 64 bit version. Why you can't use 64 bit Ubuntu 18.04.
I don't really know how you could even start the software without a crash.

**Comment by elivanf** [comment]
I installed it from PPA, following in the footsteps of Github. It worked fine however after an upgrade it stopped working. I will try to migrate to the previous version.

**Comment by elivanf** [comment]
I can't downgrade because I installed it from PPA recently and deleted everything and reinstalled. There is no way to make version 1.0.10 available for me to install.

**Comment by Technius** [comment]
Were you able to resolve the issue?

**Comment by elivanf** [comment]
I saw that the problema was with the 32 bits version. I installed a 64 bits
version.

Em sex, 27 de set de 2019 16:31, Bryan Tan <notifications@github.com>
escreveu:
