### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#149]
When `-Wall` is enabled (`DEBUG_COMPILE=ON`) following warnings appear (I fixed all `-Wsign-compare` warnings in MarPiRK/xournalpp@e916e811f0eb925222431b226a793e003eeda594 already): http://pastebin.com/mHiN4Fss
It would be nice to clean them up. I don't have much time this weekend, so I cannot do it in person.

**Comment by corna** [comment]
Most of those warnings can be safely fixed with a 

     switch(something) {

         [...]

         default:
             return;
     }

I'll work on it

**Comment by andreasb242** [comment]
No progress within 3 years and the master is merged with GTK3, close for now
