### ISSUE TITLE
Why is the user input wrapped inside the variable \preview in Latex in LatexController.cpp

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#1490]
I'm currently working on adding support for markdown through a latex template, but am hitting roadblocks because it seems that all of the user input has to  wrapped inside a variable \preview.

To use markdown inside latex, text has to be formatted like this:
```
\begin{markdown}
text here
\end{markdown}
```
I haven't been able to put the variable \preview inside the markdown environment since it is defined outside of it so the environment doesn't have access to it and just compiles with the text "\preview" instead of the actual value of the var.
```
\begin{markdown}
\preview
\end{markdown}
```
I'd like to know what the purpose of \preview is and if there's ways around it to achieve what I want

**Comment by LittleHuba** [comment]
@technius you are the pro in this area 😉

**Comment by nicolae-stroncea** [comment]
So I assume that's why there's a $x^2$ in the beginning.

I've got some follow-up questions on that:
* what's the relationship between blank formulas and the error checking that is going on? I assume that if there is an error, pdf would  be blank and Poppler wouldn't be able to load it due to size. Is it the same mechanism?
* If they are different things, is setting the layout to a certain height(pheight) used to solve the error checking problem or the blank formulas problem?

**Comment by Technius** [comment]
If there is a blank formula, the error checking code in the template will raise an error, so `pdflatex` will exit with status 1. If `pdflatex` exits with status 1, then we assume that the formula is invalid and display the blank/invalid formula warning message; we do not attempt to load the PDF (in fact, we will delete it afterwards to prevent more errors).

Without the error checking code, `pdflatex` will exit with status 0 and generate a blank PDF when there is a blank formula, thereby crashing Poppler.

Sidenote: the `$x^2$` is purely cosmetic; the default formula could actually be set to anything.

**Comment by Technius** [comment]
For now, I'm closing this issue. Feel free to reopen/reply if you have any additional questions.
