### ISSUE TITLE
Crash on opening files.

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#1491]
**Affects versions :**
 - OS: [Linux Mint 19.2 Cinnamon]
 - Version of Xournal++ [current master]

**Describe the bug**
Pressing the open button crashes the software

**To Reproduce**
compile with clang (in DEBUG Mode), open xournal++ try to open a file

**Expected behavior**
Do not crash.

fixed it already in a local branch, all `std::strings` in `Settings` are returned by value thus they only live after the line if not assigned. There was a .c_str() call on a temporary which is destructed immediately. 
Replaced all returns of a `std::string` by value in `Settings` with a `string const&`.
PR following.

**Comment by Technius** [comment]
Where is this `c_str()` call happening?

**Comment by Febbe** [comment]
Directly in the code, which handles the click on the open button. It's called on a temporary copy of a string owned by settings. There was no need to change that line because the code would be completely correct if the returned value is a const& not a rvalue. And improving only the const correctness of one function would be very odd since this could be the source of many other untracked bug's or mistakes in the future.
