### ISSUE TITLE
Icon for new page and new document are too similar

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1496]
**Affects versions :**
 - OS: Linux, Ubuntu 18.04
 - master

**Describe the bug**
The icon for "insert page" is identical to the icon for "new xournal", which is confusing, and I often click the wrong one (see attached screenshot, note that this is a custom icon layout). 
One possible suggestion is to do what libreoffice does, where the new document icon is the same as the program icon, e.g. writer's new 

**To Reproduce**
n/a

**Expected behavior**.
Two distinct icons to reduce confusion

**Screenshots of Problem**
![gnome-shell-screenshot-7LML8Z](https://user-images.githubusercontent.com/3056063/65482989-93810680-de4f-11e9-9a50-608d6a522864.png)

**Comment by bhennion** [comment]
Fixed via #3154
