### ISSUE TITLE
Xournal++ crashes the entire system whenever I use the eraser tool (occurred in ubuntu 19.04 and 19.10)

### ISSUE THREAD

**Issue by rghoward** [xournalpp/xournalpp#1506]
**Affects versions :**
 - Ubuntu 19.04 and Ubuntu 19.10
 - Version of Xournal++ 1.0.13

**Describe the bug**
Whenever I am using the app and click the eraser tool, the entire system freezes up.  I can't use any type of input on my system and I must hard power down my system.  This has occurred using both my touchpad and my stylus.  It happens every time without fail--usually within a fraction of a second after clicking the button.  Rarely, it will start to work but eventually freeze up the system regardless.

**To Reproduce**
1. Click eraser
2. System immediately freezes

**Expected behavior**
I expect that the eraser would work and I could erase things.

**Additional context**
I'm not sure how to get any kind of data logs that may help.

**Comment by Febbe** [comment]
First of all thank you for your bug report.
I have some question for you.

Did you used the eraser?
How big is the document?
Is the stroke you want to erase long?
Did you self compiled the version of xournalpp?
Which Gtk Version do you use?
Does this happen in an old version of xournalpp on your system?
Can you provide an error log and the console output?
How long have you been waiting?

If you know how to use a debugger and compile c++ code:
can you try to provoke this event and stop xournalpp with the debugger? 

If you can't answer all questions don't hesitate to provide those you know.
Greetings

**Comment by rghoward** [comment]
Hello.

I am unable to use the eraser at all as it immediately locks up the system.

The document is new.  I could click the eraser without anything on the document and it would freeze.

There doesn't need to be a stroke.

I did not self compile.  I use the appstore version.

I believe this is the correct gtk version: 
ii  libgtk-3-0:amd64  3.24.11-1ubuntu1 amd64        GTK graphical user interface library

I do not have an old version to try, could you pinpoint me to how to get one?

I cannot provide an error log.  Unless there is a way to get one after I reboot ubuntu.  

I have waited a few minutes to see if the freezing went away.  Once, my screen went black, but usually the whole screen just sits there.

**Comment by Febbe** [comment]
You can get several releases from here: https://github.com/xournalpp/xournalpp/releases please try out the newest 3 or until one works.
There are to many dependencies missing on my system to test libgtk-3-0:amd64 3.24.11-1ubuntu1.
You can find logfiles either in "~/.xournalpp/errorlogs".

**Comment by rghoward** [comment]
I went ahead and reinstalled ubuntu 19.04 because 19.10 had a separate bug.  However, the bug originated on 19.04 which is why I tried 19.10.

Anyway, the issue seems to be resolved after a clean install of 19.04.  I appreciate your help and will close this issue for now.
