### ISSUE TITLE
Translations fix breaks help

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#151]
I think commit ec25822c63a6b9b5e03ed4687dd9db45fb1e0bd0 breaks the ./xournalpp --help output on my system. Help reads:

```
Application Options:
  --pdf-no-compress        en/LC_MESSAGES/xournalpp.mo
  -p, --create-pdf         gtk20-properties
  -n, --page=N             gtk20-properties
  --display=DISPLAY        X display to use
```

**Comment by MarPiRK** [comment]
I can confirm it:

`Użycie:
  xournalpp [OPCJA…] FILE

Opcje pomocy:
  -h, --help                   Wyświetla opcje pomocy
  --help-all                   Wyświetla wszystkie opcje pomocy
  --help-gtk                   Wyświetla opcje biblioteki GTK+

Opcje programu:
  --pdf-no-compress            Project-Id-Version: xournalpp 1.0.1
Report-Msgid-Bugs-To: 
POT-Creation-Date: 2015-09-30 23:59+0200
PO-Revision-Date: 2015-10-01 00:00+0200
Last-Translator: Marek Pikuła <marek@pikula.co>
Language-Team: Xournal++ team
Language: pl
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Generator: Poedit 1.8.4

  -p, --create-pdf             Nazwa pliku PDF
  -n, --page=N                 0Z�
  --display=EKRAN              Używany ekran X
`

I'll check what's gone wrong.
