### ISSUE TITLE
Indication on how big the pen is

### ISSUE THREAD

**Issue by jug007** [xournalpp/xournalpp#1513]
**Is your feature request related to a problem? Please describe.**
I would like to see how big I am going to draw something before I start drawing it.

**Describe the solution you'd like**
Maybe a ring around the tip of the cursor like in Gimp.
(I would include a screenshot, but my screenshot tool hides the cursor)

**Comment by LittleHuba** [comment]
Know what you mean. We'll look into it.

**Comment by jug007** [comment]
Textmarker is also missing a cursor that shows the selected tool and brush size.

**Comment by idotobi** [comment]
I'd like to take this up. I was any currently getting into that part of the code.

**Comment by idotobi** [comment]
#1945 Should resolve this. I'm happy about any feedback if it also works on your machine.
