### ISSUE TITLE
Requirements Analysis for File Format

### ISSUE THREAD

**Issue by LittleHuba** [xournalpp/xournalpp#1515]
Here is a public place to discuss about the requirements for the new file format.

Following is a list of requirements I have identified so far. Feel free to add further or discuss the validity of any. Implementation of the requirements is not yet important. See this as a wish list.

- support for partial reads (jit)
- continued autosave
- support for both pages and infinity paper
- support for both packed attachments and external attachments
- clear and simple versioning (including backwards compatibility)
- undo/redo preserved over saves (can be switched on or off as it will increase filesize)
- support for external files (OneDrive, Cloud, URL,...)
- clear OO-programming
- compression of attachments

The file format and all code handling it will be outsourced into an own library. We follow common practice with this step and keep a clear separation between handling, modifying and viewing the file.

The discussion will be closed on 09.11.19.

**Comment by andreasb242** [comment]
>support for partial reads (jit)
Which means probably random access, which is usually not possible if the file is compressed. (Huffmann does not allow it, so e.g. with GZip this is not possible, with zip it is possible, because each file is compressed itself, with tar.gz or 7-zip it's therefore not possible).

The Library should be Plattform independent, so e.g. an Android Port will be possible.

**Comment by Febbe** [comment]
zlib or szip should be capable to allow this. The HDF group also used it to compress their random access dataformat

**Comment by andreasb242** [comment]
https://support.hdfgroup.org/doc_resource/SZIP/

SZip is may an option.
zlib is definitive not seekable:
https://stackoverflow.com/questions/14225751/random-access-to-gzipped-files
https://zlib.net/manual.html#Stream

ZLib is always a Stream (yes, you can skip, but for this you decompress everything from the beginning to this position)

**Comment by LittleHuba** [comment]
> Implementation of the requirements is not yet important

As mentioned above this is absolutely independent from the implementation details. With all the requirements listed, I'll then search for viable candidates to cover all aspects.

**Comment by LittleHuba** [comment]
> undo/redo preserved over saves (can be switched on or off as it will increase filesize)

I'm thinking of loosening this to a certain amount of steps (100-200) as otherwise file sizes might explode over time. And no usecases where you actually need to undo 200 steps are coming to mind so far...

**Comment by LittleHuba** [comment]
Multi-User support might be interesting as well. This would make the code quite complex though. Hence I'm not really a fan of this. Your thoughts on this would be very welcome!

**Comment by Febbe** [comment]
Some sort of change management not as complex as undo redo, just log, which person/user changed what in which safe.
Extensibility, without breaking old versions of xournalpp. The new or unknown features should be ignored and the document shall be opened with a warning and read only.

**Comment by LittleHuba** [comment]
> Some sort of change management not as complex as undo redo, just log, which person/user changed what in which safe.

Yeah I thought of something along these terms. You can create two stacks with diffs for elements for undo/redo.

Multi-User compatibility is not secured with this setup though...

**Comment by Febbe** [comment]
Mmh how does this git or other versioning protocols? We could create a fileformat which adds changes successively when multiple clients using one file.

**Comment by JLTastet** [comment]
Hi! First of all, thanks for this amazing program! I will probably have a look at the code once the PR freeze is over and I have a bit more time in my hands.

I used to look for some Xournal-like program with multi-user support some time ago, and just noticed this discussion.

The first question to ask ourselves might be which kind of multi-user support do we want? Simultaneous editing like Google docs? Or something more decentralized, without file locking?
In the latter case, you might want to have a look at [CRDTs](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type), although that would probably be overkill and add a lot of complexity to the file format.
Otherwise, there could be some X++ server for handling writes and resolving conflicts with operational transformation (e.g. if Alice insert a new page while Bob is writing somewhere else). I (maybe naively) think this would put very little constraints on the file format itself, since all writes would be handled by the server.

**Comment by LittleHuba** [comment]
CRDTs would be the perfect solution but I think this is way out of the possibilities of our team. Additionally it would be extremely hard with backwards-compatibility.

> Otherwise, there could be some X++ server

As we will outsource the fileformat handling into a library, that server could be built on top of it. Then we just enforce usage of the server for collaborative work on files.

**Comment by JLTastet** [comment]
TBH, I never really figured out how to use CRDTs for any non-trivial data structures :)

The server seems like a simpler solution, and allows postponing the actual multi-user work until after the file format spec is finished. We might just need to add some metadata to identify who made the changes and when, and maybe a separate undo stack/tree for each user.

**Comment by LittleHuba** [comment]
Yes I'll try to keep this in mind so we have everything ready when the feature is implemented.

With this issue discussed I'll close the analysis phase now and work on the system architecture design.

If you have an additional idea you can still post it here, but I will not promise anything.

**Comment by LittleHuba** [comment]
The final list of requirements is:

- support for partial reads (jit)
- continued autosave
- support for both pages and infinity paper
- support for both packed attachments and external attachments
- clear and simple versioning (including backwards compatibility)
- undo/redo preserved over saves (200 steps) (can be switched on or off)
- support for files on external file systems (OneDrive, Cloud, URL,...)
- clear OO-programming
- compression of attachments
- platform independent
- multi-user support (in terms of preparations for X++ server)

**Comment by LittleHuba** [comment]
For clarification as this could be misunderstood:
- undo/redo preserved over saves (200 steps)
  These steps will still only be available within the current session. Saving  this over multiple sessions would mean we need to identify users globally which would only be possible with an account system at a server of ours. This is not really within the scope of the project, nor what we want to have in terms of privacy for our users.
