### ISSUE TITLE
Can't enter text with "new input system"

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1518]
**Affects versions :**
 - OS: Linux Ubuntu 18.04, X11
 - Version of Xournal++: master

**Describe the bug**
I cannot enter text when I have the new input system enabled. 

**To Reproduce**
1. Open X++, set Prefrences > check box for "new input system" 
2. Close X++, reopen X++. 
3. Try to type text using text tool, nothing happens. 
4. set Prefrences > uncheck box for "new input system" 
2. Close X++, reopen X++. 
3. Try to type text using text tool, text appears as desired.

**Expected behavior**
Text can be entered with new input system.

**Comment by Technius** [comment]
I can't reproduce the issue. Can you attach the program output logs after compiling with `cmake .. -DDEBUG_INPUT=on && cmake --build .`?

**Comment by markwmuller** [comment]
OK, I'm very confused, because now I can't reproduce it either. I'll see if I can figure out what my issue was, and will post if I can turn it on again..

**Comment by markwmuller** [comment]
OK, seems specific to external keyboards. My laptop's builtin keyboard has no issue, but an external keyboard does. 

I'm attaching the logs here. "log_builtin" has keypresses from the laptop's builtin keyboard only; "log_external" keypresses only from the the external keyboard: 
[log_builtin.txt](https://github.com/xournalpp/xournalpp/files/3703194/log_builtin.txt)
[log_external.txt](https://github.com/xournalpp/xournalpp/files/3703195/log_external.txt)

Logs suggest that keypresses are recognized for both keyboards, but no text appears.

Hardware details: Laptop is LenovoYoga X1; external keyboard is a USB HP keyboard. 

Everywhere else, the two keyboards both work fine, e.g. I'm typing this using the external keyboard.

**Comment by LittleHuba** [comment]
For some reason the keyboard is assigned to the `mouse` input class. You can check out the settings if you can change it's device class but I assume it is not possible as keyboards are handled differently.

**Comment by LittleHuba** [comment]
Could you please provide your settings file?

**Comment by markwmuller** [comment]
This is my ~/.xournalpp/settings.xml Note that it's renamed, github doesn't like uploading xml it seems

[settings_renamed.txt](https://github.com/xournalpp/xournalpp/files/3703874/settings_renamed.txt)

**Comment by LittleHuba** [comment]
Could you please remove this part from the settings file and look if the problem persists.

```
<data name="deviceClasses">
    <data name="BM30X mouse">
      <attribute name="deviceClass" type="int" value="1"/>
      <attribute name="deviceSource" type="int" value="0"/>
    </data>
    <data name="HP HP Link-5 Micro Receiver">
      <attribute name="deviceClass" type="int" value="1"/>
      <attribute name="deviceSource" type="int" value="0"/>
    </data>
    <data name="Logitech M705">
      <attribute name="deviceClass" type="int" value="1"/>
      <attribute name="deviceSource" type="int" value="0"/>
    </data>
    <data name="SynPS/2 Synaptics TouchPad">
      <attribute name="deviceClass" type="int" value="1"/>
      <attribute name="deviceSource" type="int" value="6"/>
    </data>
    <data name="TPPS/2 Elan TrackPoint">
      <attribute name="deviceClass" type="int" value="1"/>
      <attribute name="deviceSource" type="int" value="7"/>
    </data>
    <data name="Virtual core XTEST pointer">
      <attribute name="deviceClass" type="int" value="0"/>
      <attribute name="deviceSource" type="int" value="0"/>
    </data>
    <data name="Wacom Pen and multitouch sensor Finger">
      <attribute name="deviceClass" type="int" value="4"/>
      <attribute name="deviceSource" type="int" value="5"/>
    </data>
    <data name="Wacom Pen and multitouch sensor Pen eraser">
      <attribute name="deviceClass" type="int" value="3"/>
      <attribute name="deviceSource" type="int" value="2"/>
    </data>
    <data name="Wacom Pen and multitouch sensor Pen stylus">
      <attribute name="deviceClass" type="int" value="2"/>
      <attribute name="deviceSource" type="int" value="1"/>
    </data>
  </data>
```

**Comment by markwmuller** [comment]
OK, I've removed that block. I had to open X++, close it, and reopen it, but now it seems that the external keyboard works as usual. 

Note that I don't think I ever did anything special in the settings with my input devices, so I'm no sure how the KB got assigned as a mouse.

**Comment by LittleHuba** [comment]
Are you using nightlies by any chance?
I had to fix this in a separate PR back then and this might have broken your settings.

**Comment by markwmuller** [comment]
I'm pulling straight from master, but somewhat irregularly. Thanks for your help! 
I'll close this now, it probably only affects a very small set of people.
