### ISSUE TITLE
Reword "page template" dialogue

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1524]
**Is your feature request related to a problem? Please describe.**
The "Page template" dialogue's settings are confusing. Specifically, there's text for each of the two possible check boxes saying "Use the settings above for the first Page" where the check box says "Copy last page settings". 

How can a setting be used for the first page if it depends on the last? 

Also "settings above" for the second check box -- does this include *all* settings above? (It doesn't, I think, only the last 2).

Finally, the form says "settings will be used when you create a new document", which to me suggests a blank document, rather than annotating a PDF. 

**Describe the solution you'd like**
Suggest to describe what the effect is clearer, e.g.: "Copy current page's size when inserting a new page" and "Copy current page's style (background) when inserting a new page".

Remove "Settings will be used if you create a new document" to "Settings apply on restart" or similar (I'm not sure what is meant by the sentence, but it may be this?)

**Additional context**
I'm not the only one confused, see https://github.com/xournalpp/xournalpp/issues/1517#issuecomment-538848606

ETA: Current dialogue, for reference:
![gnome-shell-screenshot-IN288Z](https://user-images.githubusercontent.com/3056063/66328830-433f8500-e8e2-11e9-90b9-2dfe6a6354ba.png)

**Comment by LittleHuba** [comment]
The whole dialog should be included within the normal settings dialog. We should rework the appearance as well when we do this.
