### ISSUE TITLE
strokes is not smooth on Mac

### ISSUE THREAD

**Issue by FantDing** [xournalpp/xournalpp#1531]
xournalpp version: 1.0.12
macOS version: 10.14.6
__________________________
as you can see as below.
![image](https://user-images.githubusercontent.com/21337200/66617031-d855bd00-ec05-11e9-944e-4fef05aad82b.png)
It can works well on Onenote. 
![image](https://user-images.githubusercontent.com/21337200/66617201-b7419c00-ec06-11e9-866b-2c33b76f9b24.png)
But xouralpp is more attractive to me, I use it on other platforms.

**Comment by LittleHuba** [comment]
Please provide the input logs as described in our Wiki.

**Comment by FantDing** [comment]
when compile the project I met the error
![image](https://user-images.githubusercontent.com/21337200/66633430-639e7500-ec3d-11e9-8ab7-5b21c3332275.png)

**Comment by Febbe** [comment]
What are your steps to compile the project? You need to specify the path to the gtk+ binaries and header files.

**Comment by FantDing** [comment]
@Febbe I follow the steps in wiki "How to provide debug info for input related bugs"

**Comment by LittleHuba** [comment]
You must first follow the steps for manual builds on MacOS. Please check out the instructions linked in the main readme.

**Comment by FantDing** [comment]
@LittleHuba I have exec [those](https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md), should I follow [these](https://github.com/xournalpp/xournalpp/blob/master/mac-setup/README.md)?

**Comment by JJones780** [comment]
Xournal is quite flexible on it's use of input devices:

You may be getting input from two devices. One ( i.e. your mouse ) may be adding jitter to your writing ( stylus? ). 
I was going to suggest going to prefs->inputSystem and disabling the mouse but I tried that and now it crashes whenever I try to draw... changing it back didn't help.  :(   Instead first try unplugging your mouse and see if that's the source of the jitter.   It could also be coming from the touchpad or touchscreen etc... or it's something else entirely.

**Comment by LittleHuba** [comment]
> @LittleHuba I have exec [those](https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md), should I follow [these](https://github.com/xournalpp/xournalpp/blob/master/mac-setup/README.md)?

Yes please follow `these`. Manual build does not work with homebrew. Make sure to use a user on your system that does not have homebrew installed as the build systems break each other.

**Comment by rolandlo** [comment]
The latest nightly build uses Gtk `3.24.35`. The lag is fixed there. Please install the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) or wait for the release of version 1.2.0.
