### ISSUE TITLE
Todo: Remove or change ArrayIterator<T>

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#1532]
The Array Iterator does not work with algorithms of the STL, therefore it is mostly useless. It can also be a source for errors and increases overhead.
Since normal pointers are also Iterators, I would prefer to use pointers with Iterator functions of the STL like std::next, std::prev, std::advance. Or even better replace c-arrays with std::array<T,size_t> or std::vector<T> and use their build in iterators.

Those also enable range based for loops, eg.:
for(auto&& var : container){...}

**Comment by MrMallIronmaker** [comment]
I was looking for a good first issue and saw this. I'm wondering if this issue should this have been closed by PR #1545? Looks like the requested changes were made.

**Comment by LittleHuba** [comment]
> should this have been closed by PR #1545?

Yeah thanks for the heads up! Hope to see your PR fixing another issue soon!
