### ISSUE TITLE
autoload .pdf.xoj fallback when .xoj missing

### ISSUE THREAD

**Issue by motherload** [xournalpp/xournalpp#156]
I have noticed that if you check the option "autoload .pdf.xoj" on Preferences -> Load/Save, xournalpp fails to load the pdf if the .pdf.xoj file is absent if you simply try to open it, either from the command line (xournalpp foo.pdf) or try to open if from the GUI. 

The only way to open a .pdf file in this case is to go in File -> Annotate PDF, which is annoying, since xournalpp can't be called thus by any third-party software as a pdf reader

There should be a fallback implemented to look for the .pdf.xoj, and if it doesn't find it, open the regular .pdf anyway.

**Comment by wbrenna** [comment]
In the gtk2 version I believe this worked properly, but I have just noticed this as a problem as well on the gtk3 branch - you can only open PDFs with Annotate PDF. I agree with you that this needs to be fixed, thanks for reporting!
