### ISSUE TITLE
Selecting objects behind other objects

### ISSUE THREAD

**Issue by jug007** [xournalpp/xournalpp#1564]
**Is your feature request related to a problem? Please describe.**
Selecting something that is behind something else can be difficult or not possible without moving something.

**Describe the solution you'd like**
There should be a way to select something that is behind something.
I would suggest rotating between selections, when there is two or more possible selections.
E.g. you an image on top of you text; So you click twice where the text is to select it.

**Describe alternatives you've considered**
A context menu asking what you want to select, if there is multiple options.

**Related issue**
#810

**Comment by Technius** [comment]
Duplicate of #810.

**Comment by Moini** [comment]
Nah, this isn't a duplicate. While 810 is implemented, I still cannot select things that are behind other things (or even in front of, when selection isn't choosing the object I actually click on).
