### ISSUE TITLE
configure not finding lcms-libs

### ISSUE THREAD

**Issue by tynsh** [xournalpp/xournalpp#157]
I tried compiling xournalpp on Gentoo. After installing lcms, configure from xournalpp still could not find the necessary libs.

```
$ ls /usr/include | grep lcms
lcms2.h
lcms2_plugin.h
```

Changing lcms to lcms2 in line 16223 of configure let xournalpp compile without further problems. Since I dont't know the consequences of changing that in configure I'm not filing a PR :-)

**Comment by wbrenna** [comment]
That's right - I've experienced this behaviour too. It should look for lcms2 and then fallback to lcms but it'll have to be fixed in cmake, I think. Thanks!

**Comment by MarPiRK** [comment]
@tynsh Which branch do you use?

**Comment by tynsh** [comment]
I'm on the master branch, should I try an other?

**Comment by MarPiRK** [comment]
Yes, lcms2 with fallback to lcms (as @wbrenna said) is supported in `development`. It's basing on CMake instead of Autotools.

**Comment by tynsh** [comment]
than I'm closing this. Thanks for the feedback.

**Comment by MarPiRK** [comment]
btw, it'd be nice to make Autotools support lcms2 in `master` @wbrenna

**Comment by poinck** [comment]
This problem is still there; I had to do the changes again in “configure“.
