### ISSUE TITLE
How to enable pen icon for drawing mode?

### ISSUE THREAD

**Issue by tolvanea** [xournalpp/xournalpp#1578]
There has been possibility to have a pen icon for drawing mode, instead of current cursor/dot. However I can't find the possibility to enable it from settings. Has it been removed?

By "pen icon" I mean that cursor changes to pen when pen mode is activated. Similarly to that we have white square in eraser mode.

I prefer pen icon, because it is more natural, and it's easier to see where the cursor is, especially when using wacom pad. 

(Sorry if this is more an question than issue, but I don't know other place to ask.)

**Comment by LittleHuba** [comment]
Go to settings, 6th tab, 2nd group, the first checkbox.

**Comment by tolvanea** [comment]
Thank you, didn't see that!

(I write this following if there are other people who'd like to have always-on pen icon.)

I did one modification to have always-on pen icon.
In source src/gui/XournalppCursor.cpp line 288-305 (master), there's check that if mouse not pressed, then just use regular cursor instead of pen icon. If I comment out this check, and proceed directly to else-branch I get pen icon that is always on. Here's original code for quick reference:
```
else if (type == TOOL_PEN || type == TOOL_HILIGHTER)
{
    if (this->inputDevice == INPUT_DEVICE_MOUSE && !this->mouseDown)  // mouse and not pressed
    {
        setCursor(CRSR_ARROW);
    }
    else
    {
        if (type == TOOL_PEN)
        {
            cursor = getPenCursor();
        }
        else  // must be:  if (type == TOOL_HILIGHTER)
        {
            cursor = getHighlighterCursor();
        }
    }
}
```
