### ISSUE TITLE
Cennot build project

### ISSUE THREAD

**Issue by K0ertis** [xournalpp/xournalpp#158]
Hi! 

When I build this project on the newest Ubuntu distro 15.10 and I get this error:

```
configure.ac:209: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:209: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

May you make a new release? the currently ones are pretty outdated.

Thank you very much!

**Comment by wbrenna** [comment]
Potentially this is due to a missing dependency. I think something GTK related - ```libglib2.0-dev``` or the like. Which branch are you trying to build, in gtk3 or gtk2?

**Comment by K0ertis** [comment]
At first the master tree, and afterwards gtk3 branch

**Comment by andreasb242** [comment]
After 2 Years this is probably solved or not relevant anymore. Close.
