### ISSUE TITLE
Draw line tool broken when snap to grid is disabled

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#1580]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Manjaro Linux
 - Xfce with Compiz as WM
 - gtk3 (version 3.24.12+32+g39e28ab933-1), gtk2 (version 2.24.32-1)
 - Version of Xournal++: 1.0.15

**Describe the bug**
While drawing a straight line, only a short piece of the line next to its origin is visible. After finishing the line, the complete line becomes visible though. However, such lines do not respect the "delete strokes" eraser option. Also, when drawing the line it looks like only certain slopes are possible, that is, snap to grid is not completely disabled.

**To Reproduce**
1. Open Xournal++
2. Activate the "delete strokes" eraser option
3. Deactivate the "Grid Snapping" option 
4. Select the "Draw Line" tool
5. Try to draw a line, observe that it is not fully visible while drawing
6. Try to delete the line, observe that it is not completely deleted when touched by the eraser

**Expected behavior**
The line should be fully visible while drawing and should be completely deletable.

**Screenshots of Problem**
none

**Additional context**
none

**Comment by Fef0** [comment]
Just tried, I confirm your issue

**Comment by Technius** [comment]
This seems be a rendering bug; the missing part of the line is actually placed on the page and can be refreshed by e.g. selecting it or switching to another tool.

**Comment by Technius** [comment]
Actually, it seems like the line data is initially corrupt but "fixes" itself once it's modified or the document is saved:

![xpp_1580](https://user-images.githubusercontent.com/1066652/68257704-03ef7b80-ffe9-11e9-934e-f7e51ea0fafe.gif)

**Comment by tattsan** [comment]
This bug has been seen since 742499a20b99bc1d6d103c7a16376c4a2ef053a8 .

**Comment by Technius** [comment]
Looks like a merge introduced a regression. Before:
https://github.com/xournalpp/xournalpp/commit/742499a20b99bc1d6d103c7a16376c4a2ef053a8#diff-34761b1a8ed64686bc16f0c22332747aR192
After:
https://github.com/xournalpp/xournalpp/commit/742499a20b99bc1d6d103c7a16376c4a2ef053a8#diff-34761b1a8ed64686bc16f0c22332747aL208
I have not checked though.

**Comment by Febbe** [comment]
> Actually, it seems like the line data is initially corrupt but "fixes" itself once it's modified or the document is saved:

The data is correct from the beginning, the drawing of the line (only in progress) is somehow bugged. When a repaint is executed the line is correct again. Looks like there is a copy somewhere, which is not intended.
