### ISSUE TITLE
Freeze after opening a PDF with an outline

### ISSUE THREAD

**Issue by thomasqueirozb** [xournalpp/xournalpp#1582]
**Affects versions :**
 - OS: Arch Linux
 - X11 - i3wm
 - gtk3 version - 1:3.24.12+32+g39e28ab933-1
 - Version of Xournal++ - 1.0.15-1

**Describe the bug**
The software becomes unresponsive and the display freezes. This seems to happen only to specific PDF documents, which have recognized content (each bullet point is listed alongside the page preview)

**To Reproduce**
1. Open the pdf or xopp file
2. Open the file again

**Expected behavior**
Xournal should open the file again

**Comment by LittleHuba** [comment]
Is it possible for you to share the file?

**Comment by thomasqueirozb** [comment]
This pdf sample works just fine to replicate this bug:
https://gahp.net/wp-content/uploads/2017/09/sample.pdf

**Comment by Technius** [comment]
Confirmed that this happens with the sample PDF. No console output is produced.

**Comment by Technius** [comment]
Looks like a deadlock:
```plain
#2  0x000000000052bc3c in Document::lock() (this=this@entry=0x67e530)
    at ../src/model/Document.cpp:59
#3  0x0000000000512e66 in SidebarIndexPage::treeBookmarkSelected(_GtkWidget*, SidebarIndexPage*) (treeview=<optimized out>, sidebar=0xf63a80)
    at ../src/gui/sidebar/indextree/SidebarIndexPage.cpp:156
#4  0x00007ffff717ddd4 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#5  0x00007ffff7191514 in  () at /usr/lib64/libgobject-2.0.so.0
#6  0x00007ffff719a1a7 in g_signal_emit_valist ()
    at /usr/lib64/libgobject-2.0.so.0
#7  0x00007ffff719a82f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#8  0x00007ffff79a5d10 in  () at /usr/lib64/libgtk-3.so.0
#9  0x00007ffff79a8083 in  () at /usr/lib64/libgtk-3.so.0
#10 0x00007ffff717e0f6 in  () at /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff719a1ec in g_signal_emit_valist ()
    at /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff719a82f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff79bc5be in gtk_widget_grab_focus () at /usr/lib64/libgtk-3.so.0
#14 0x0000000000512d7c in SidebarIndexPage::treeBookmarkSelected(_GtkWidget*, SidebarIndexPage*) (treeview=0xf6a3e0, sidebar=0xf63a80)
    at ../src/gui/sidebar/indextree/SidebarIndexPage.cpp:133
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007ffff717dec2 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#16 0x00007ffff7191514 in  () at /usr/lib64/libgobject-2.0.so.0
#17 0x00007ffff719a1a7 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#18 0x00007ffff719a82f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#19 0x00007ffff79a5d10 in  () at /usr/lib64/libgtk-3.so.0
#20 0x00007ffff79a85a7 in gtk_tree_view_set_model () at /usr/lib64/libgtk-3.so.0
#21 0x00000000005126c1 in SidebarIndexPage::documentChanged(DocumentChangeType) (this=0xf63a80, type=<optimized out>) at ../src/gui/sidebar/indextree/SidebarIndexPage.cpp:413
[ rest omitted ... ]
```
Happens because the `SidebarIndexPage::documentChanged` locks the document mutex:
https://github.com/xournalpp/xournalpp/blob/48b5dab807f606e222f191465b38bc6e1df7e2e2/src/gui/sidebar/indextree/SidebarIndexPage.cpp#L411-L413
and the `gtk_tree_view_set_model` then triggers a `cursor-change` event, which then calls `treeBookmarkSelected`, which locks the document again:
https://github.com/xournalpp/xournalpp/blob/48b5dab807f606e222f191465b38bc6e1df7e2e2/src/gui/sidebar/indextree/SidebarIndexPage.cpp#L149-L157
Note that this code will only be run if there is an outline in the PDF.

The same file doesn't have to be reopened. Once a file is loaded, loading _any PDF with an outline_ will trigger the deadlock.
