### ISSUE TITLE
`make install` fails on build/po/cs.gmo

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1596]
**Affects versions :**
 - OS: Linux Ubuntu 18.04 X11
 - Libgtk: 
```bashii  libgtk2.0-dev                                 2.24.32-1ubuntu1                                   amd64        development files for the GTK+ library
ii  libgtk-3-dev:amd64                            3.22.30-1ubuntu4                                   amd64        development files for the GTK+ library
ii  libgtkmm-3.0-dev:amd64                        3.22.2-2                                           amd64        C++ wrappers for GTK+ (development files)
```
 - Version of Xournal++ master c533ab9bc1de77ca52d542491f03e8a4760e0f7d

**Describe the bug**

After a successfully `make`, 

    make install

fails with: 

```bash
CMake Error at po/cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/romano/software/xournalpp/build/po/cs.gmo".
Call Stack (most recent call first):
  cmake_install.cmake:102 (include)


Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1
```

**To Reproduce**

    rm -r build
    git reset --hard 
    git checkout master 
    git pull
    mkdir build 
    cd build 
    cmake ../
    make
    make install

**Expected behavior**

`xournalpp` installs in `/usr/local/...` 

Thanks!!!

**Comment by LittleHuba** [comment]
For now do a `make translations` before building X++.

**Comment by Rmano** [comment]
Yep --- it works. Thank you!

**Comment by LittleHuba** [comment]
We should add a few lines to the cmake file that ensure the target is built as dependency but not refreshed on every build. I'm not quite sure how to do that.

**Comment by Febbe** [comment]
I think you can add the dependency flag and Mark the custom target as "EXCLUDE_FROM_ALL"

**Comment by LittleHuba** [comment]
Second part is already done. I can do the other part next week. If you don't do it before me @Febbe.

**Comment by yurivict** [comment]
xounalpp can't be updated to the latest version because of this problem (breakage on install). You shouldn't have released a new version 2 days ago before this is fixed.

**Comment by Cogitri** [comment]
FWIW Alpine Linux hit this too.
