### ISSUE TITLE
pinch-to-zoom

### ISSUE THREAD

**Issue by cass00** [xournalpp/xournalpp#160]
One feature I'm dearly missing in xournal(pp) is pinch-to-zoom on the touchscreen. As a first step to implement this feature I've forked the gtk3 branch and followed this commit for the evince pdf viewer GNOME/evince@36c7f21f5c0f96cd5. This works fine and can be tested in this commit cass00/xournalpp@33744e262f43b771e35dd9e72ff568dfcfda73bc. However, there some problems with a centred pinch-to-zoom approach (will make a new issue for that)

**Comment by wbrenna** [comment]
Thanks for the work, that is a nice feature to add to the official repository. If you can fix the centering, remove the unneeded comments, and format it in a way consistent with the original file that would be very helpful! Then just issue a pull request.
