### ISSUE TITLE
Can't open the built project in my language

### ISSUE THREAD

**Issue by Maniform** [xournalpp/xournalpp#1604]
Hi everyone,

I'm french and I built the project to try to improve some features. I edited the french translation but when I launched the built project, the language is still in english no matter what I'm doing.

My OS : Ubuntu 18.04.3 LTS

I tried to :
- launch the binaries -> ./xournalpp
- launch with a specific language : LANGUAGE=fr_FR ./xournalpp
- install built deb and launch it
- launch from the built deb with a specific LANGUAGE

I executed "make pot" and "make translations" before and after building the binairies.

Thank you for your help !

**Comment by LittleHuba** [comment]
For translations to be updated and applied you have to provide the install prefix. You can set the install prefix to a directory within your installation directory and then run `make install` and run the program from the directory you specified. That should solve the issue.

**Comment by LittleHuba** [comment]
Check out the Wiki for details on how to provide the prefix

**Comment by Maniform** [comment]
Installing locally works fine, but I would prefer to install properly with the deb package, I don't understand why it doesn't work that way, but if it's too complex it's ok !

**Comment by LittleHuba** [comment]
That is just how gettext works. You can still install the deb-package.

**Comment by Maniform** [comment]
I tried to install from the deb package but it's still in english.

**Comment by Maniform** [comment]
I read all the "Installing" wiki page. The only way I found to have the right localization is to install from source to the $HOME/.local folder. When I build a DEB package, the language is locked on English even if std::locale().name().c_str() return "fr_FR.UTF-8".

And we can't configure the project with a PREFIX and with a package target, cmake returns this error : "Current working directory cannot be established."

**Comment by LittleHuba** [comment]
Did you follow the instructions in the Wiki on how to build the Debian package?

**Comment by Maniform** [comment]
I followed the explanations from the LinuxBuild.md file (there is a ".deb packages" category), not from the wiki, I'll try from the wiki.

**Comment by LittleHuba** [comment]
> I followed the explanations from the LinuxBuild.md file

Sorry that is what I meant.

**Comment by LittleHuba** [comment]
Do you have another version of Xournal++ installed? The packages might collide.

**Comment by Maniform** [comment]
I uninstalled every instance of xournalpp (or xournal++) before this, so yes. I still have xournal installed but it shouldn't be a problem.

For the LinuxBuild.md file, I exactly did these commands :
git clone https://github.com/xournalpp/xournalpp.git
cd xournalpp
mkdir build
cd build
cmake .. -DCPACK_GENERATOR="DEB" ..
make pot
make translations
cmake --build . --target package

Then I installed the deb package generated in build/packages folder and the software is in english instead of french like when I installed it from apt.

**Comment by Maniform** [comment]
I tried to follow the wiki and "make install" command doesn't work.

CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot make directory "/usr/local/share/xournalpp/ui": No such
  file or directory

I've seen this error in other issues.

**Comment by LittleHuba** [comment]
> I tried to follow the wiki and "make install" command doesn't work.

You will have to unset the CMake variables first and then run `make install` as superuser.

After installing the Debian package, please check the directory `/usr/share/locale/de/LC_MESSAGES/` and tell me if there is a file that is named `xournalpp.mo`

**Comment by LittleHuba** [comment]
If you find the file run

`msgunfmt /usr/share/locale/fr/LC_MESSAGES/xournalpp.mo > ./xournalpp.po`

Then open the created file `xournalpp.po` and send me the first block of text with the generation information.

**Comment by Maniform** [comment]
There is no file xournalpp.mo, there's just a xournal.mo.

**Comment by LittleHuba** [comment]
Okay that means that for some reason CMake does not package the translation files...
@Technius you know your way around this part of the build system the best. Any idea why this happens?

**Comment by Technius** [comment]
Regression due to 84290e5. After cloning a fresh copy of xournalpp, `cmake --build . --target translations` fails to run:
```
[1/1] cd /tmp/xournalpp/build/po && ""
FAILED: po/CMakeFiles/translations 
cd /tmp/xournalpp/build/po && ""
/bin/sh: : command not found
ninja: build stopped: subcommand failed.
```
This occurs because `cmake/find/Gettext.cmake` defines the translation target as follows:
https://github.com/xournalpp/xournalpp/blob/c00660b96aba2da2052826cadc0d0951505d60ce/cmake/find/Gettext.cmake#L694-L701

https://github.com/xournalpp/xournalpp/blob/c00660b96aba2da2052826cadc0d0951505d60ce/cmake/find/Gettext.cmake#L546-L550

When `ALL` is not specified in `gettext_create_translations`, the empty string is passed to the target definition, so the "command" for the target is set as the empty string.

**Comment by Technius** [comment]
I just fixed the issue. If the project still doesn't compile, reopen this issue and let me know.

**Comment by Maniform** [comment]
Hi again ! I tried to build and install the deb package to check if the issue is solved but it isn't. I downloaded the newest xournalpp files and built it from the start. The cmake command lines worked fine, I can install and launch xournalpp without any problem but it's still in english. I exactly executed the following command lines : 

git clone https://github.com/xournalpp/xournalpp.git
cd xournalpp
mkdir build
cd build
cmake .. -DCPACK_GENERATOR="DEB" ..
make pot
make translations
cmake --build . --target package

**Comment by Technius** [comment]
The locale files are copied correctly into the `.deb` file (I checked with `dpkg-deb`). Unfortunately, running `LC_ALL=<language> src/xournalpp` does not seem to change the locale regardless if xournalpp is run from the build folder or is installed as a package.

**Comment by Maniform** [comment]
I found a way to solve my problem ! This is what I did :

- git clone https://github.com/xournalpp/xournalpp.git
- cd xournalpp
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr
- make pot
- make translations
- cmake .. -DCPACK_GENERATOR="DEB" ..
- sudo cmake --build . --target package -> don't know why but I have to execute this line with sudoer's rights
- sudo chown -R <username> .
- <installation of the DEB package>

And now xournal++ is in french.
Thank you for your help !

**Comment by LittleHuba** [comment]
Do our packages released on this page still show that error? Then we will have to adapt your commands.

**Comment by Maniform** [comment]
I'm sorry I don't know which released you're talking about...

To be more specific about what I said, I just tryied to invert `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` and `cmake .. -DCPACK_GENERATOR="DEB" ..` so I executed `make pot` and `make translations` between theses commands. And now xournalpp is in english. So the condition to apply the right language in the `DEB` package is to generate the locale after having set `PACK_GENERATOR`.

**Comment by Maniform** [comment]
I'm sorry I don't know which released you're talking about...

I just tryied to invert `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` and `cmake .. -DCPACK_GENERATOR="DEB" ..` so I executed `make pot` and `make translations` between theses commands. And xournalpp is still in French so the condition to apply the right language seems to be the `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` command.

**Comment by LittleHuba** [comment]
I mean the ones here https://github.com/xournalpp/xournalpp/releases
