### ISSUE TITLE
zoom to fit does not work properly with different form factor pages

### ISSUE THREAD

**Issue by JulianGro** [xournalpp/xournalpp#1608]
**Affects versions :**
 - OS: Linux Mint 18.2 (Ubuntu Bionic based)
 - DE: Cinnamon
 - libgtk: 3.22.30
 - Version of Xournal++: from PPA, 1.0.15 build on 19. October 2019

**Describe the bug**
When having zoom to fit selected and switching between pages in different form factors; The zoom is wrong. (Screenshot attached) Example file: [19.11.06_Arbeitsblätter_CV.pdf.xopp.zip](https://github.com/xournalpp/xournalpp/files/3858017/19.11.06_Arbeitsblatter_CV.pdf.xopp.zip)

**To Reproduce**
1. Open file with different form factor pages
2. Select zoom to fit
3. change page

**Expected behavior**
New page should be zoomed to fit

**Screenshots of Problem**
![Bildschirmfoto vom 2019-11-18 10-57-33](https://user-images.githubusercontent.com/11144627/69043097-aac51600-09f2-11ea-9a0f-539f1d4ba412.png)

**Comment by Febbe** [comment]
May be fixed by #2821
