### ISSUE TITLE
Switching between last opened documents does not always update thumbnails

### ISSUE THREAD

**Issue by jug007** [xournalpp/xournalpp#1609]
**Affects versions :**
 -  OS: Linux Mint 18.2 (Ubuntu Bionic based)
 -  DE: Cinnamon
 - libgtk: 3.22.30
 - Version of Xournal++: from PPA, 1.0.15 build on 19. October 2019

**Describe the bug**
When switching between last opened documents the thumnails do not always get updated correctly.

**To Reproduce**
1. load last opened document
2. repeat until thumbnails wrong

**Expected behavior**
Thumbnails should always be reloaded correctly

**Screenshots of Problem**
![Bildschirmfoto vom 2019-11-18 10-56-50](https://user-images.githubusercontent.com/11144627/69049695-bfa8a600-0a00-11ea-98aa-24502b7ce6a3.png)

**Comment by Technius** [comment]
Closed in favor of #1964.
