### ISSUE TITLE
Gnome starts two different instances of Xournalpp

### ISSUE THREAD

**Issue by ysooqe** [xournalpp/xournalpp#1614]
**Affects versions:**
    OS: Linux
    Gnome (X11)
    Version of Xournal++ : 1.1.0+dev (compiled 2019-11-18) and 1.0.16

**Description**
Gnome seems to start two different kinds of "Xournalpp" (see screenshot).
I am using an icon theme called Papyrus.
When I run Xournalpp from the Gnome Launcher (Super-Key) or by clicking a .xopp file from Nautilus, an instance corresponding to the left one on the screenshot is started.
Starting from a terminal, an instance like the one on the right is started.

**Steps to reproduce**
1. Open Xournalpp through the Gnome Launcher.
2. Open Xournalpp from the terminal.

**Expected behaviour**
Both applications are the same "kind" of application.

**Screenshot**
![Screenshot from 2019-11-18 13-38-06](https://user-images.githubusercontent.com/40417462/69068283-c812d800-0a24-11ea-91ce-fcd8d7d2f1de.png)

**Additional files**
I have used `xprop` to get some information about the windows, maybe that can help to determine what is going on. The name of the files is corresponding to the names shown on the screenshot.

[xournal++.txt](https://github.com/xournalpp/xournalpp/files/3859501/xournal%2B%2B.txt)
[xournalpp.txt](https://github.com/xournalpp/xournalpp/files/3859504/xournalpp.txt)

**Comment by LittleHuba** [comment]
See #1612 for the solution as the cause is most likely the same.

**Comment by LittleHuba** [comment]
I do not think this is an issue of Xournal++ but more from the DE or the icon theme. The xprop files are the same except values you would expect to be different. Also everything we can really influence is the WM_Class which is already identical.
I'd recommend you to ask at the IRC of Gnome if anybody knows what could cause this. If you have further information and it is indeed something on our side, please comment and we will fix it ASAP.

Hope the guys over there can help you.

**Comment by ysooqe** [comment]
I would just like to comment on that since I found out something new. Even though the StartupWMClass is properly set on both instances when I check with `xprop`, for some reason the issue disappears if I explicitly add the StartupWMClass to the .desktop file, i.e. `StartupWMClass=xournalpp`, then everything works properly and as expected.
