### ISSUE TITLE
Move the right down corner tool bar to other place

### ISSUE THREAD

**Issue by aliyuchang33** [xournalpp/xournalpp#1615]
**Is your feature request related to a problem? Please describe.**
When using `xournalpp` with pen, my right hand always touch the tool bar accidentally. It then change to other size or jump to another page. Pretty frustrating. 

**Describe the solution you'd like**
Move the toolbar to mid or left.

![2019-11-19_10-32](https://user-images.githubusercontent.com/22322294/69111260-07d6cf80-0ab8-11ea-9a1e-0ce318c48e51.png)

**Comment by Technius** [comment]
You can do this by selecting `View > Toolbars > Customize` in the menu and then dragging the icons in the right corner to the the left side.

**Comment by aliyuchang33** [comment]
Solved, thanks.
