### ISSUE TITLE
Alternative mode for stylus buttons

### ISSUE THREAD

**Issue by TheAssassin** [xournalpp/xournalpp#1619]
I am using a Wacom tablet every second day (in avg) with Xournal++ to take my notes. This works quite well, however I find it annoying how the buttons work.

With most Wacom tablets, you have only a few mm of "air space" above the tablet where the stylus still transmits a position (which is even somewhat precise). As most Wacom styluses have buttons, Xournal++ supports assigning alternative tools to them (e.g., an eraser (my stylus doesn't have one, unfortunately) or the selection tools). This is cool because it saves you from some clicks.

The problem is however that when you switch your tool using those buttons, they're immediately applied (i.e., the eraser erases as soon as the button is clicked). This would be OK for me, but what's a problem is that *I have to keep the stylus in the air* to remain in that tool and use it. For longer selections or larger areas to erase, this is really annoying, as I tend to either leave the "air space" of the tablet, causing a sudden end of functionality (more of an issue for selections) or touch the tablet, causing the old tool (most likely the pencil) to be applied immediately (-> weird lines somewhere you don't want them).

I think this was different in my time using good ol' Xournal. There, you had to press the button to switch the tool, but to use the tool you had to touch the tablet. This makes IMO way more sense than the current system, it's much easier to use and more precise.

Can you please introduce a switch in the configuration or so and implement this behavior? I think even changing the default might be viable, as said, the system I suggest makes a lot more sense in my opinion, as it's easier to use and more precise than the current system. But I'd be very happy with a simple config option I could switch on already.

**Comment by LittleHuba** [comment]
Check out the settings. In the input tab there is an option to merge button and tip events. That will fix it for you.

**Comment by TheAssassin** [comment]
I again went through the settings, but couldn't spot any such option, especially not in the input tab.

![screenshot_2019-11-11-19-19_10-52-28](https://user-images.githubusercontent.com/4503202/69136216-c0057780-0aba-11ea-890c-e3fe4b1bf4f6.png)

Do I have to enable that experimental feature?

**Comment by TheAssassin** [comment]
Never mind, my blindness. I just spotted it as well... Sorry for the additional noise.

**Comment by TheAssassin** [comment]
@LittleHuba I just tested the option, and I have to disagree with closing this issue. It goes in the right direction, however still mixes both "in-air" and "touching" movements. My intention was to get rid of any in-air action, so you can position your stylus without any consequences (especially important for eraser, highlight tool, etc.).

When you press a button, you have to apply a little force. I am sure everyone's gonna shake a bit. So it makes sense to press the button first, then position your stylus and touch the tablet to take any actions.

Furthermore, when using selections, the "old in-air" selection is interrupted and a new one is created once you touch the tablet. A *very* unexpected behavior, as the title of the option "merge" suggests the current tool would just continue to work no matter whether you touch the tablet or not. Is this perhaps related to this? 

```sh
> xsetwacom get 16  TabletPCButton
off
```

Thanks for your help, pointing me to that option already improves my workflow a little bit already.

**Comment by LittleHuba** [comment]
Thing is we can only work with the events we get from the system.
There are two different cases:

Wayland/TabletPCButton=off:
Button press events are sent merged with the tip events (1 if no other button is pressed/2 for first button pressed/3 for second button pressed and so on)

Wacom with TabletPCButton=on:
Auxiliary button press events are sent on their own independent whether the tip touches the surface or not. We get a ButtonPressEvent for button 1 if the tip touches the surface and as soon as a user presses an auxiliary button we get a ButtonPressEvent for button 2

What we do with that mergin option is in essence trying to remember the button presses of the second case which are not from the tip and to apply them as soon as the tip hits the surface. For obvious reasons we can not do this automatically but users have to manually select that option.

What most users want as experience is that the tool is already selected in-air as then the cursor changes and they can position the stylus correctly but the tool actually starts drawing as soon as it touches the surface. Hence exactly how it works for case 1. I don't really see what you want changed there now as no actual action is performed while the pen does not touch the surface. We only change the tool accordingly.

**Comment by TheAssassin** [comment]
@LittleHuba in my small test, there was a rectangle drawn in-air already, when I then touched the tablet a new rectangle was started. The eraser also erased when in-air already. That's the behavior I have seen. You describe a different behavior.

Interesting enough, I just re-tested, and the option didn't seem to work at all any more. I tried enabling and disabling it again a few times, but it didn't make a difference...

**Comment by LittleHuba** [comment]
Okay that should not happen. Please provide me the output of your TabletPcButton property and input logs. 
A simple scenario of you taping the screen once without any button pressed and then a second time with a button pressed should suffice.

**Comment by TheAssassin** [comment]
I already provided the `TabletPcButton` value above, it's `off`.

I am using a laptop whose lid I close to suspend it to RAM, as I'm on my workstation now. This time I plugged in the tablet, opened the lid and opened Xournal. Now, behavior changed once again. This time, I have the rectangle select behavior described before. However, for the lower button (eraser in my config) it's erasing while in the air and switches to rectangular select once I touch the tablet. I saw by coincidence that, *whyever*, the rectangular tool was chosen in the toolbar, that's why it was triggered when I hit the surface. When switching to e.g., a pencil, that pencil is triggered once I hit the surface. That explains my weird behavior described above. The option doesn't seem to work at all...

Not entirely sure how to get that input log. What I can see on stdout is:

```
** (Xournal++-1.0.16-x86_64.AppImage:7803): WARNING **: 00:26:14.344: Input for the same device started twice!

** (Xournal++-1.0.16-x86_64.AppImage:7803): WARNING **: 00:26:16.317: Input for the same device started twice!

** (Xournal++-1.0.16-x86_64.AppImage:7803): WARNING **: 00:26:19.498: Input for the same device started twice!

** (Xournal++-1.0.16-x86_64.AppImage:7803): WARNING **: 00:26:21.680: Input for the same device started twice!

** (Xournal++-1.0.16-x86_64.AppImage:7803): WARNING **: 00:26:23.510: Input for the same device started twice!
```

These messages are generated whenever I hit the tablet surface. When I do, the previously selected tool is activated. (When I leave the surface, the cursor is shown, even if the button is still being pressed).

**Comment by LittleHuba** [comment]
Okay that explains everything. Please activate the new input system in the settings (same page as the other setting) and uncheck the button merging. This will solve the issue.

The olds input system is buggy and no longer supported. It will be removed with the next release.

**Comment by TheAssassin** [comment]
I see. The term "experimental" caused me not to check the box, but I guess it's pretty much done by now. Thanks for your help, it works like a charm!

**Comment by TheAssassin** [comment]
One last question: before activating the option, I had a regular mouse pointer "in air" that helped spot the cursor position in situations where you e.g., paint yellow on a white background. Now there's a the little dot again, like there has been a couple releases ago (1.0.12?). I know I can switch on that "virtual pen" special cursor thing, but is there an option to just show a cursor again?

**Comment by LittleHuba** [comment]
When you use the stylus only a dot is shown as the stylus already shows you the position. When you use the mouse then we show the normal cursor.
If you have a different experience check that the device classes are assigned correctly in the settings.

**Comment by TheAssassin** [comment]
No, that's exactly my experience. My proposal is to allow for displaying a cursor as well when using the tablet. A graphics tablet doesn't show you any position. You're moving your hand on it while tracking some pointer with your eyes on the screen. It's hard to see a yellow (or maybe even white) dot on a white "virtual paper". Hence I liked having that pointer that you have when using a mouse with the tablet.

**Comment by LittleHuba** [comment]
Please open a feature request for this. We do currently not have such a feature.
