### ISSUE TITLE
Windows build instuctions missing tar package

### ISSUE THREAD

**Issue by jug007** [xournalpp/xournalpp#1623]
**Describe the bug**
Windows build instructions are missing the tar package.

**To Reproduce**
1. follow the steps to build on windows
2. PortAudio cannot be build because tar cannot be extracted

**Expected behavior**

**Additional context**
[https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md](https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md)

**Comment by LittleHuba** [comment]
Very interesting as our internal pipeline runs without this package.

I assume you installed tar with:
```bash
$ pacman -S tar
```

**Comment by jug007** [comment]
Yes
