### ISSUE TITLE
Update active page behavior

### ISSUE THREAD

**Issue by jonasBoss** [xournalpp/xournalpp#1631]
**Is your feature request related to a problem? Please describe.**
#1517

**Describe the solution you'd like**
Set active Page to current view if active page is not in view.

**Describe alternatives you've considered**
For #1517 the best solution might be to add the page between the two visible pages

**Comment by LittleHuba** [comment]
In current nightlies active page is updated when scrolling, thus the active page is always in view. Please rephrase or close the ticket.

**Comment by gyps** [comment]
I'm using the current git version (it should be identical to the nightly build, right?).
I just tested creating a 5 page document, go to page 4 insert a page (view jumps to page 1).
In the sidebar the new page is shown as active but the main view (in presentation mode) shows the inactive first page.

**Comment by LittleHuba** [comment]
Yeah there is already another issue that inserting new pages results in scrolling the view to the wrong position most of the time.

I'll close the issue now as it has not been rephrased and is obsolete.
