### ISSUE TITLE
crahes when moving the last page down / first page up through context menu

### ISSUE THREAD

**Issue by ethpi** [xournalpp/xournalpp#1637]
- OS: Kubuntu 18.04 64bit
 - libgtk 3.22.30-1ubuntu4
 - tested with xournalpp 1.0.6-0 201910191646 ubuntu18.04.1 (The menu help / about shows version 1.0.15) and  xournalpp  1.1.0+dev

xournalpp crahes, when moving the last page down

1. Open a new journal
2. Insert a second empty page
3. Move the second (last) page down

Xournalpp crahes, the window vanishes from the screen.

**Comment by Technius** [comment]
Does this only happen when using the context menu, or is there another way to trigger the crash?

**Comment by ethpi** [comment]
Instead of moving the last page down you can move the first page up, if the document contains at least two pages. It seems, that moving a page beyond the valid page range, causes the crash.

I don't know how to move a page without using the context menu of the thumbnails in the sidebar. 

Do you need an error log? Or something like the output of "strace xournalpp"?

By the way: after a few tests I can trigger a crash, by inserting an image in an empty document:
1. Select the icon for an image.
2. Touch the page with the pen to set the position of the picture. Instantly xournalpp crashes.

**Comment by Technius** [comment]
Thanks for the info, the bug should be pretty simple to fix (disable the move down option on the last page / move up option on the first page).

This second crash is unrelated; please post another issue with crash logs and input debugging logs attached.
