### ISSUE TITLE
Adding image crashes Xournal++

### ISSUE THREAD

**Issue by MuTaTeD** [xournalpp/xournalpp#1648]
Version: 1.1.0+dev
OS: Linux (Kbuntu 18.04)
Desktop Environment: KDE
Build: Nov 30 2019, 10:06:11

Xournal++ crashes when I try to add an image in the document using the toolbar button while opening the File Choose dialog box

However I am able to drag and drop the image from the file system onto the document without any problems.

It seems that the crash is caused by the file choose dialog box, however I am able to open the file choose dialog boxes for Open, Save, Save As, Export As etc without any issue

**Comment by LittleHuba** [comment]
Could you provide the errorlog please?

**Comment by MuTaTeD** [comment]
Resolved in #1650 
Seems like a nullptr was de-referenced causing the crash
