### ISSUE TITLE
All pen thickness values in default pen options dropdown

### ISSUE THREAD

**Issue by ltokuno** [xournalpp/xournalpp#1657]
**Is your feature request related to a problem? Please describe.**
The default pen thickness dropdown in Preferences->Defaults only lists the three of the five possible pen thickness values.

**Describe the solution you'd like**
All five pen thickness listed in the thickness dropdown in Preferences->Defaults.

**Describe alternatives you've considered**
Currently if "very fine" or "very thick" is the base pen thickness for a document, then every time pen  thickness is switched, it's necessary to go to through Tools->Pen Options to reset the pen.  This is cumbersome, but works.  
I looked at [#1361 ](https://github.com/xournalpp/xournalpp/issues/1361).  This would be an improvement.  It changes menu lookup into a click (for color) and a slide (for thickness).  This is not as fast as a clicking the default button.  In addition, sliding with a stylus is not as easy as clicking with a stylus.

**Additional context**
No.  On a side note, I think you guys have done a great job bringing new life to an old project.  Thanks!

**Comment by MaheshCodeReader** [comment]
How to increase pen stroke size to whatever I want?
