### ISSUE TITLE
Poor scrolling behavior when selecting/creating/deleting pages

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1658]
**Affects versions :**
 - OS: Solus Linux
 - Display server: X11
 - GTK version: 3.24.12
 - Version of Xournal++: 1.0.16 (maybe), 1.1.0+dev

**Describe the bug**
Scrolling behavior is confusing and unintuitive when selecting, deleting, or creating pages.

**How to reproduce / expected behavior**

| Description | Expected behavior | Status |
| - | - | - |
| 1. When scrolled down a page, right clicking the same page in the sidebar to open the context menu causes the page to scroll to the top | Should not scroll to the top of the page | [Fixed in fork](https://github.com/Technius/xournalpp/tree/pg-preview-scrolling) |
| 2. From a new document, inserting a page, scrolling to the second page, and then inserting another page causes the scroll to move to the top of the first page. | The scroll should remain in the same place (or go to the next page) | See #1517 |
| 3. Deleting the second-to-last page causes the first page to be selected | The page before the second-to-last page should be selected | |

**Screenshots of Problem**
N/A

**Additional context**
I fixed the first bug already in my own fork and will submit a PR when more bugs are fixed.

I will add more bugs to the list as I find them (or as people report them).

**Comment by rickhg12hs** [comment]
From Gitter session:

> rickhg12hs @rickhg12hs Apr 18 00:51
> @Technius Super! I while!
> BTW, when I scroll with a multi-page PDF background, it seems to skip pages. I.e., I'm one the first page, scroll down, and then it jumps to page 3. Is there a setting to avoid that?
> Bryan Tan @Technius Apr 18 00:53
> Are you scrolling with your mouse or with arrow keys/pg up/pg down?
> And are the pages of your PDF the same size?
> rickhg12hs @rickhg12hs Apr 18 00:57
> Yes, pdfinfo says all 4 pages are A4.
> ... arrow keys
> Bryan Tan @Technius Apr 18 00:59
> Can you file an issue? I can't reproduce your problem
> rickhg12hs @rickhg12hs Apr 18 01:00
> pg up/dn works, but sidebar scrolling skips pages
> Bryan Tan @Technius Apr 18 01:00
> Oh, don't file an issue then
> seems like it's another case of #1658
> but feel free to leave a comment on what you're seeing
> and I'll look into it

xournalpp:  Built from GitHub master commit 4d2e2fb475d96da230243b189122d1ca0398a0ea
Summary:  arrow keys up/down and sidebar scrolling skipping pages.
System: Fedora 29, x86_64, Gnome 3.30.2, Xwayland 1.20.4

**Comment by rolandlo** [comment]
I think this has been fixed with PR #2346
