### ISSUE TITLE
Remember last page seen

### ISSUE THREAD

**Issue by Glutanimate** [xournalpp/xournalpp#166]
Hi,

thanks first of all for all of the work put into Xournal++. I've just given it a try and it's a tremendous step forward from Xournal.

One thing I have been missing is an option to remember the last page seen. This is important especially when working with particularly large PDF files. I love that Xournal++ can jump to the next annotation, but when a document is heavily annotated it can still take a while to get to the page you last worked on.

Ideally this should work the same way as the ['Remember last page seen'](https://sourceforge.net/p/xournal/patches/67/) patch for Xournal.

Thanks for giving this feature request a thought.

Cheers
--Glutanimate

**Comment by wbrenna** [comment]
Absolutely, thanks for the suggestion!

**Comment by wbrenna** [comment]
Upon looking at this I'm not sure why it's not working on my system...Metadatamanager calls setInt on pageSelected in XournalView and should save the current page. I suspect there was an update to the scrolling manager that didn't save metadata and that's why the last page seen isn't working.

**Comment by wbrenna** [comment]
I think the bug goes a little deeper. Commenting out the ```getMetdataManager->setInt``` line in ```XournalView.cpp``` fixes the problem where opening from the command line resets the last page to 0. This appears to be an order-of-operations thing. However, it breaks properly updating the last page.

There is also currently a bug on Open - if you use the Open shortcut or toolbar and then cancel, the sidebar freezes up. These two problems might be solvable simultaneously.
