### ISSUE TITLE
Segfault on save/load/select

### ISSUE THREAD

**Issue by chron-isch** [xournalpp/xournalpp#1664]
**Affects versions :**
 - OS: ArchLinux
 - Hardware: MS Surface Go + Pen
 - Wayland/swaywm (sway-git, includes the wlroots patch from #1536)
 - gtk3 - 3.24.13
 - Xournalpp 1.0.16

**Describe the bug**
Xournalpp crashes while trying to save/open/select a file. Every 3rd or 4th time the file select dialog is open I'm actually able to save/select something, but the rest of the time Xournalpp just crashes.

**To Reproduce**
1. Save or open something

**Expected behavior**
Do not segfault.

Xournalpp Log:
[errorlog.20191212-152615.log](https://github.com/xournalpp/xournalpp/files/3956225/errorlog.20191212-152615.log)
GDB Log:
[gdb_bt_on_save.log](https://github.com/xournalpp/xournalpp/files/3956226/gdb_bt_on_save.log)

If you need more info I'd be happy to provide proper backtraces from a debug build.

**Comment by LittleHuba** [comment]
Do you have a GTK icon theme installed? And are you using a flatpak version or do you install via pacman?

**Comment by chron-isch** [comment]
I've tested with the pacman 1.0.16 version as well as a locally build one.

```
# pacman -Q | grep icon                                                   [15:57:31]
adwaita-icon-theme 3.34.3-1
faenza-icon-theme 1.3.1-5
gnome-icon-theme 3.12.0-5
gnome-icon-theme-extras 3.12.0-4
gnome-icon-theme-symbolic 3.12.0-5
gtk-update-icon-cache 1:3.24.13-1
hicolor-icon-theme 0.17-1
```

**Comment by LittleHuba** [comment]
This seems like a GTK bug actually. All backtraces lead to a bug when creating the dialogs for loading/saving. Could you try an older GTK version? In the last few they had various bugs with Wayland. I assume this is another such occurrence.

**Comment by chron-isch** [comment]
You were right, it's not xournalpps error, here's the complete backtraces with debugging enables for xournalpp and gtk3.
[xournalpp_save_crash.log](https://github.com/xournalpp/xournalpp/files/3960721/xournalpp_save_crash.log)

**Comment by chron-isch** [comment]
GTK Issue: https://gitlab.gnome.org/GNOME/gtk/issues/2318

**Comment by chron-isch** [comment]
This fixes the problem: https://github.com/swaywm/wlroots/pull/1775
