### ISSUE TITLE
crash on ubuntu 18.04.03

### ISSUE THREAD

**Issue by giubbe** [xournalpp/xournalpp#1672]
at startup the program crashes. The error message is:

Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme Adwaita (gtk-icon-theme-error-quark, 0)

** (xournalpp:19623): WARNING **: 23:51:22.884: [Crash Handler] Crashed with signal 6

** (xournalpp:19623): WARNING **: 23:51:22.884: [Crash Handler] Wrote crash log to: /home/io/.xournalpp/errorlogs/errorlog.20191215-235122.log
[errorlog.20191215-235122.log](https://github.com/xournalpp/xournalpp/files/3965567/errorlog.20191215-235122.log)

**Comment by Technius** [comment]
Please provide the following information:

* Which version of Xournal++ are you using?
* What version of GTK is installed?
* Are you using X11 or Wayland?
* What icon theme are you using?

Based on the error, it seems like your system is misconfigured or is missing an icon theme package.

**Comment by giubbe** [comment]
the Xournal++ version is 1.1.0+dev
the gtk version is 3.22.30-1ubuntu4
X11
The icon Theme is Adwaita.

with the icon theme "humanity" Xournal++  it works, so it is a wrong Awaita configuration.

**Comment by Technius** [comment]
If you want to still use Adwaita, try the following: https://ubuntuforums.org/showthread.php?t=2392578

We can't do anything on our end to fix this issue, but we can provide an entry in the FAQ.
