### ISSUE TITLE
Touchscreen input troubles in 2-in-1 laptop/tablet

### ISSUE THREAD

**Issue by MrMallIronmaker** [xournalpp/xournalpp#1673]
Hello Xournal++ Community,

Just installed this app on my new Lenovo Yoga 730 in order to take advantage of the new 2-in-1 tablet/touchscreen modes. I'm looking forward to figuring out this bug (perhaps in the code but more likely in my understanding of the settings.)

**Affects versions :**
Ubuntu 18.04.3, GNOME 3.28.2
Xournal++ 1.0.16 and 1.1.0+dev
Log files are from 1.1.0+dev.

**Describe the bug**
I expect touchscreen features of the touchscreen to work right out of the box, or with minor changes in the settings. In particular, using the touchscreen as a drawing input and pinch-to-zoom,.

**To Reproduce**
* Open new document.
* Write using mouse (depressed trackpad) . Blue line is drawn, as expected.
* Write using one finger on touchscreen. Page pans; it should be write like a pen.
* Pinch to zoom using two fingers on touchscreen. Page pans; it should zoom.

**Input Logs**
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ MSFT0001:02 06CB:7F8F Touchpad          	id=10	[slave  pointer  (2)]
⎜   ↳ Wacom HID 5173 Finger touch             	id=12	[slave  pointer  (2)]
⎜   ↳ Wacom HID 5173 Pen stylus               	id=11	[slave  pointer  (2)]
⎜   ↳ Wacom HID 5173 Pen eraser               	id=15	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=13	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3970286/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3970287/debug_input.log)

**Expected behavior**
* With one finger, the page pans instead of writing.
* With two fingers, the page pans instead of zooms.
* I'd like to be able to fix this by fooling around in the Preferences, but I tried a few things and nothing seemed to change the defaults. If it's a simple UI thing, I can submit some changes to the https://github.com/xournalpp/xournalpp/wiki/User-Manual with the fixes that are found.

**Comment by MrMallIronmaker** [comment]
I am able to draw single-pixel dots on the touch screen if I tap or hold a single finger and do not move it. Not sure what this means exactly, but it feels like useful information for someone who knows a lot more about the drawing system.

**Comment by LittleHuba** [comment]
The thing is we either identify the touchscreen as a mouse or as a touchscreen. So you will either be able to write using one finger OR zoom using two fingers currently.
To get either of the options, go into the settings dialog to Input System tab and activate the new input system. Then check the device class assigned to your touchscreen directly beneath. If it is set to touchscreen you will be able to zoom using two fingers, if it is set to mouse or pen you will be able to write but not zoom.

**Comment by LittleHuba** [comment]
If you want to change this behaviour, you will have to introduce a new device class into our codebase and then modify the input handlers to work with this new device class in a mixed mode.

**Comment by MrMallIronmaker** [comment]
Ok, that's helpful. The problem is that neither of those inputs modes produce either expected behavior - I can't get drawing with either pen or touchscreen modes, and I can't get zooming with either pen or touchscreen modes.

So I've changed the touchscreen input type under Edit > Preferences > Input System > Input Devices > Wacom HID 5173 Finger touch (touchscreen) to Pen (screenshot attached). I think this is the state in which I can write but not zoom - but I do neither.

![Screenshot from 2019-12-17 10-20-13](https://user-images.githubusercontent.com/1994318/71014181-229c6400-20b7-11ea-8fdd-85007d498290.png)

I've also switched that same input (Wacom finger touch) to Touchscreen, but I'm getting the same result - a single dot when pressed with one finger, but nothing drawn with one finger moved, and no zoom effect with two fingers.

Note that this doesn't have the panning effect I was able to get earlier - I'm confused as to what is different today. I'm wondering if the problem is somwhere else in the stack.

Perhaps it would be helpful to tell:

* What device is being activated?
* How many touches are discovered?
* What action (scroll, draw, pinch) Xournal++ is trying to do?

Re: device class - I may end up doing that; it may also make more sense to include a custom input device class where you can select each behavior for each kind of gesture (if there are more than these two gestures).

**Comment by LittleHuba** [comment]
Please remove your settings file from the config directory (`/home/.../.config/xournalpp/settings.xml`)

Okay please go into the settings again under tab zoom and check if the zoom gesture is activated. This should fix the experience for the touchscreen class. If not get back to me.

For the pen class please create a input debug log with exactly one line drawn. Use no other devices just the touchscreen.

**Comment by MrMallIronmaker** [comment]
Deleting the settings did activate the zooming - what was the problem there? Is there something I can help with in the code?

I also followed the settings change here (https://github.com/xournalpp/xournalpp/issues/1407) and was able to convert from an ugly pinch-is-like-a-ctrl-scroll to a very nice and smooth iPad-like gesture.

The pen class is here:
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3975055/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3975056/debug_input.log)

There is definitely something different going on - after the one line drawn, the "undo" button appears, and it doesn't when I just move the screen.

**Comment by LittleHuba** [comment]
> Deleting the settings did activate the zooming - what was the problem there? Is there something I can help with in the code?

It was most likely just a conflict in your settings file. We have to rework this at some point, so we can upgrade the settings file easier.

Can you switch to input class mouse and send me the input logs as well?
I might have to create a version with more debug information.

**Comment by MrMallIronmaker** [comment]
Yup! Here's the logs from input class mouse, 1.1.0+dev.

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3980304/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3980307/debug_input.log)

**Comment by LittleHuba** [comment]
I assume the result is the same for both classes?

**Comment by MrMallIronmaker** [comment]
Exactly the same as far as I can tell.

**Comment by LittleHuba** [comment]
@Technius you mentioned being able to replicate the issue on one of your machines. Would you mind looking further into the issue? If you don't have time I can write up a debug version that outputs more information and try my luck from there.

**Comment by frogtux** [comment]
This sounds like an issue I had with my Thinkpad Yoga and it was a driver problem.
The wacom touch driver might not work as expected, so in my case the solution was to use the libinput driver for touch and the wacom driver for the stylus.
You may have both drivers `xserver-xorg-input-libinput` and `xserver-xorg-input-wacom` installed, but the wacom driver overwrites the libinput driver with standard configuration.
The easiest way to test it is uninstalling `xserver-xorg-input-wacom` and restart the X server.
Otherwise you could modify your X server config by copying `40-libinput.conf` and `70-wacom.conf` to `/etc/X11/xorg.conf.d/` (this folder might not exist). If you rename `40-libinput.conf` to `71-libinput.conf` it overwrites the wacom driver (same effect as uninstalling it). So I left the filenames unchanged and I removed all parts with 'touch' in it (see attachment).

I hope it is helpful.

[70-wacom.conf.txt](https://github.com/xournalpp/xournalpp/files/4076513/70-wacom.conf.txt)

**Comment by bhennion** [comment]
A lot has changed in the input system since then. Is this still an issue?

**Comment by MrMallIronmaker** [comment]
@bhennion It's no longer causing problems for me because ended up getting the touchscreen pen a week or two later and avoiding the whole problem. I don't have any interest in reproducing this bug, but if it is something you want to be confident got fixed, I can check for you.

**Comment by bhennion** [comment]
Well, I'd be more comfortable with us checking if the bug still exists, but if it is too much of a hassle, we can simply close this ticket.

**Comment by MrMallIronmaker** [comment]
It seems to me that the "bug" was that the touchscreen wouldn't draw or zoom regardless of whether it's a touchscreen or mouse. That problem seems to be resolved. There was also the feature request of a mode to zoom and pan with two figures, but also draw with a finger, but I no longer have interest in that feature.

With my default Lenovo touchscreen settings: when specifying the touchscreen as a mouse in Xournal++, I'm able to draw, though the line thickness is very thin. In both cases (touchscreen and mouse) a two-finger touch can zoom.

On my Lenovo Yoga, the touchscreen has a setting called "Enable Touch Gesture" that is on by default. In this setting, pinches are transformed in some way that doesn't map one-to-one with finger position. Normally when I use xournal++ I disable this setting through a script. There's probably some way to turn it off permanently, but it hasn't been enough of a problem yet.

After disabling this feature, I'm able to draw when the touchscreen is specified as a mouse, and I can't zoom anymore (which I think is the intended behavior). When the touchscreen is specified as a touchscreen, it pans and zooms as I expect it to.

PS: In case it is helpful for other users, here is the script:
```sh
export DISPLAY=":0"

xhost local:root

TOUCH_GESTURE_PROP=$(xinput list-props 'Wacom HID 5173 Finger touch' | gawk 'match($0, /Enable Touch Gesture \(([0-9]+)\)/, a) {print a[1]}')

xinput set-prop 'Wacom HID 5173 Finger touch' $TOUCH_GESTURE_PROP 0
```

**Comment by bhennion** [comment]
Thanks a lot for checking all that! Closing this ticket then.
