### ISSUE TITLE
Experimental floating toolbox: Pen activates automatically on crossing boundary edges of page.

### ISSUE THREAD

**Issue by ajP89** [xournalpp/xournalpp#1679]
**Affects versions :**
 - OS: Manjaro linux 18.1.4
 -  libgtk : gtk-2.0/2.10.0
 - Version of Xournal++ : 1.0.16

**Describe the bug**
I have set up the experimental toolbox (floating) and it is great. But one issue I have found is that after the toolbox closes, and if I cross the edges of the page (eg from one page to the next, or side edges), I find that the pen starts to write by itself even though it is not touching the surface of the tablet I am using.

**Screenshots of Problem**
1.Opening toolbox and selecting pen tool:
![image](https://user-images.githubusercontent.com/53900896/71168368-8a4fdc00-227c-11ea-9edf-07ee9309a5e4.png)
2.Pen writing by itself:
![image](https://user-images.githubusercontent.com/53900896/71168462-c6833c80-227c-11ea-9ed6-e82fec411f3a.png)

**Comment by nicolae-stroncea** [comment]
I have a similar issue that is not linked to the floating toolbar.

I use a Wacom Stylus with the "merge button events with stylus tip events" setting on. After using a button on the stylus that is mapped to any action (tested with "Select rectangle" and "Hand"), I will experience the same issue of pen activating and writing following my cursor if I cross a page boundary.
