### ISSUE TITLE
"Ok" button in Add/Edit TeX dialog is greyed out

### ISSUE THREAD

**Issue by palmerito0** [xournalpp/xournalpp#1681]
**Affects versions :**
 - OS: Linux (Arch)
 - DE: X11
 - GTK2: 2.24.32-1, GTK3: 1:3.24.13-1
 - Xournal++: 1.0.16-1

**Describe the bug**
No formula is rendered by the Add/Edit TeX dialog, and the OK button is greyed out even when valid TeX code is inputted.

**To Reproduce**
1. Open Add/Edit TeX dialog
2. Enter valid TeX code
3. "Ok" button is greyed out

**Expected behavior**
Ok button should not be greyed out, and the formula should render.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/5355463/71298114-55568e80-233b-11ea-972d-7cb843016b87.png)

**Additional context**
- `pdflatex` is installed and available: 
```
$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
```
- and so is the `standalone` package:
```
$ kpsewhich standalone.sty
/usr/share/texmf-dist/tex/latex/standalone/standalone.sty
```
Running `xournalpp` reports a couple unrelated ALSA errors and also shows the following each time the Add/Edit TeX dialogue is invoked:
```
(xournalpp:2644): Gtk-WARNING **: 15:06:26.798: Error loading theme icon 'gtk-ok' for stock: Icon 'gtk-ok' not present in theme Paper
```

**Comment by Technius** [comment]
This appears to be an issue with your icon theme, since it is missing GTK stock icons. Does the OK button work if you switch to a different icon theme?

**Comment by palmerito0** [comment]
> Does the OK button work if you switch to a different icon theme?

Switched to a couple other icon themes (Adwaita + elementary) and those gave a similar error. Switching to the Arc theme seems to have fixed that specific icon warning (and icons now display correctly), but the OK button is still greyed out:

![image](https://user-images.githubusercontent.com/5355463/71327873-d0967c80-24c2-11ea-8984-ef402172ce83.png)

> check /tmp for a xournalpp-<digits> folder

Found one under `/tmp/xournalpp-<digits>/tex/tex.tex`, these are the contents:
```
\documentclass[crop, border=5pt]{standalone}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{ifthen}
\newlength{\pheight}
\def\preview{\(\displaystyle
x^2
\)}
\begin{document}
\settoheight{\pheight}{\preview} %
\ifthenelse{\pheight=0}
{\GenericError{}{xournalpp: blank formula}{}{}}
\preview
\end{document}
```
Running `pdflatex` on it produces the following:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
---! /home/adrian/.texlive/texmf-var/web2c/pdftex/pdflatex.fmt made by different executable version
(Fatal format file error; I'm stymied)
```

~~"I'm stymied" has to be one of the least helpful error messages I've ever seen~~

**Comment by palmerito0** [comment]
Found the issue: had some residual config files floating in `~/.texlive/` that were messing with `pdflatex`. Removing them with `rm -rf ~/.texlive/` fixed the issue.

Thank you for the suggestion of looking at the temporary `.tex` file @Technius ! Closing the issue now :)

**Comment by Febbe** [comment]
We should add a note in the wiki

**Comment by raffaem** [comment]
I had a similar issue and I had to install `scontents` to make it work.

So, on Fedora 34 Workstation, to have Tex work on Xournal++ you need to run the following command:
```
sudo dnf install texlive-scontents texlive-standalone
```

Thanks for the suggestion of looking to the .tex file!

**Comment by rolandlo** [comment]
> I had a similar issue and I had to install `scontents` to make it work.

There is also the alternative, which is using the `legacy_template.tex` instead of the `default_template.tex` in the LaTeX panel of menu `Edit > Preferences`. On older distros `scontents` cannot be installed.
With the `legacy_template.tex` you would miss some features though (like syntax highlighting via the `listings` package).
