### ISSUE TITLE
Support the 3rd button of Wacom Pen.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#1686]
**Is your feature request related to a problem? Please describe.**
'Wacom Pro Pen 3D' has three side buttons. The 3rd button is the same as button8 of a mouse.
I want to use this button like the other two buttons.

**Comment by rolandlo** [comment]
Any suggestion about what this button should do?

**Comment by tattsan** [comment]
I only want the same configurability as the other buttons. Can I do the same thing via plugins?
Different pens have different button positions. I want to set it up to absorb those differences.

**Comment by rolandlo** [comment]
What do you mean with "different pens"? Do you mean different tools? 
You can use `xsetwacom` to make your 3rd button activate some key combination and (if the tool you wish has no key accelerator in the menubar) use a plugin to activate (and possibly deactivate) the tool you want when this key combination is pressed.
For example (in case you have a Wacom Intuos Pro M) use 

```xsetwacom set "Wacom Intuos Pro M Pen stylus" Button 8 "key ctrl z"```

to make your 3rd pen button press ctrl+z (for undo operation) or replace that shortcut with another one which is defined in your plugin. See the current last post of #919 for a plugin defining some useful shortcuts. Let me know if you need some help.
One thing I don't know yet: Can `xsetwacom` make execute something upon releasing the button on the pen?

**Comment by tattsan** [comment]
'Different pens' means different physical pens.
Physicaly, configurable buttons of wacom pens are the following. Pen3D has no eraser.
```
ProPen3D: 'stylus button2', 'stylus button3', 'stylus button8'.
ProPen2 : 'stylus button2', 'stylus button3', 'eraser button1', 'eraser button2', 'eraser button3'.
```
(I omit 'stylus button1' because its usage is fixed.)

To absorb these differences, It is conceivable to make 'Pen3D button8' equal to 'Pen2 eraser button1'.
But linux wacom driver can't remap 'stylus button' to 'eraser button', or vice versa.
So I thought whether button8 has the same menu in Xournal++ preference settings.

This was what I thought when I posted this issue.

Right now I don't think button8 need it's own menu because it is only ProPen3D which has that button for now,
and we can assign many functionality to the button via plugin. So we may close this issue.

> Can xsetwacom make execute something upon releasing the button on the pen?

I know I can assign 'button release' to 'button press':

```
xsetwacom set "Wacom Cintiq Pro 32 Pen stylus" "Button" "8" "button -2 "
```

But I don't know how to assign something to 'button release'.

**Comment by tattsan** [comment]
I'll use the plugin API, so I close this issue.
