### ISSUE TITLE
From last update(201912241606) I can't edit.

### ISSUE THREAD

**Issue by juan25pz** [xournalpp/xournalpp#1690]
**Affects versions :**
 - OS: Lubuntu 18.04.1
 - libgtk 3.22.30-1ubuntu4
 - Xournal++ 1.0.6-0-201912241606-ubuntu18.04.1
(201912291941 the same problem)

**Describe the bug**
It opens the files but I can't edit, nor existing neither new ones.

**Comment by Febbe** [comment]
Did you checked your preferences or delete them. 
And how does it stand out? 
Did you tried to draw something wit the mouse/pen/finger?
Is the new input system enabled?

**Comment by juan25pz** [comment]
> Did you checked your preferences or delete them.

To discard old preferences conflict I install in another pc (I added the ppa repo and then installed it)
The problem persist in the new version **1.0.6-0-202001062250-ubuntu18.04.1**

> Did you tried to draw something wit the mouse/pen/finger?

I can't edit, no pen, no highlighter, no image, no text, only "Math TEX" is working.

> Is the new input system enabled?

How I do that? is it needed in a "fresh" installation.

In this new version I have noticed that the default blank page only appears in the screen when is smaller than the window, otherwise it disappears.
Can it be republish the older version than 201912241606 in the repo?
Thanks Febbe.

**Comment by juan25pz** [comment]
> Did you checked your preferences or delete them.

To discard old preferences conflict I have installed in another PC
(I added the ppa repo and then installed it)
The problem persist in the new version **1.0.6-0-202001062250-ubuntu18.04.1**

> Did you tried to draw something wit the mouse/pen/finger?

I am using a traditional PC with only mouse/keyboard.
I can't add an element, only "Math TEX" is working.
No pen, no highlighter, no image, no text, neither Select is working.

> Is the new input system enabled?

How I do that? is it needed in a "fresh" installation?

In this new version I have noticed that the default blank page only appears in the screen when is smaller than the window, otherwise it disappears.
Can it be republish the older version than **201912241606** in the repo?
It would be useful to have more than one version (option) available.
Check `apt-cache policy xournalpp` -> Candidate
Thanks **Febbe**.

**Comment by juan25pz** [comment]
Some test of **1.0.6-xxx** in **Ubuntu 18.04 amd64**:
[1.0.6-**20191220-18.04**](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+build/18457655) Similar problem as described above.
[1.0.6-**20190723-18.10**](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+build/17313269) Works in 18.04
I remember my previous working version was that (**20190723**)
but the package is not available for [18.04](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+sourcepub/10362515/+listing-archive-extra)

**Comment by juan25pz** [comment]
Some test of **1.0.6-xxx** in **Ubuntu 18.04 amd64**:
[1.0.6-**20191220-18.04**](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+build/18457655) Similar problem as described above.
[1.0.6-**20190723-18.10**](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+build/17313269) Works in 18.04
I remember my previous working version was **20190723**
but the package is not available for [18.04](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+sourcepub/10362515/+listing-archive-extra)

**Comment by matepak** [comment]
I could reproduce this bug when new input system was enabled. 
When disabled it works fine.
It seems to be related with new input system. 

**Affect version:**
- OS: Ubuntu 20.04
- Xournal ++   1.0.6-0-202002120339~ubuntu20.04.1 installed from ppa.
