### ISSUE TITLE
Zoom fet to screen- no scroll

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#1699]
**Affects versions :**
 - OS:Linux Mint 19.3 Mate
 - Version of Xournal++ 1.1.0+dev

**Describe the bug**
In zoom fet to screen, I cannot use scroll.

**To Reproduce**
https://drive.google.com/file/d/1tcnbeFB051O2Q64ymjZY-u27XeDFkz6G/view?usp=sharing

**Comment by Technius** [comment]
Same cause as #1668.

**Comment by BMicraft** [comment]
I don't think this is quite the same as #1608.

This seems more like #2138 and can probably be closed in favor of that.

**Comment by rolandlo** [comment]
Closed in favor of #2138. Note there is a fix available, PR #2541.
