### ISSUE TITLE
Canvas Blank on Switch Desktop

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#17]
Sometimes upon switching desktop away and back to Xournalpp (Fedora Core 19 addpoppler branch) the canvas is completely blank (the view is just a titlebar with no features) with a stroke-input cursor until some stroke is drawn, upon which a complete refresh takes place.

This might be due to incompatibilities with the newest gtk, perhaps?

**Comment by MarPiRK** [comment]
Is it still there? It is a while since `addpoppler`.

**Comment by wbrenna** [comment]
I suspect it is - I think it's due to the threading problems. Basically it works OK when I run it without threads but there is a large host of problems because threading is currently broken.

**Comment by MarPiRK** [comment]
I can reproduce this problem on my machine (lowering system clock and a little of stress on CPU).

**Comment by wbrenna** [comment]
Good to know - stressing the CPU can bring a wealth of threading bugs. IMO the entire threading needs to be rethought for gtk3.

**Comment by MarPiRK** [comment]
True

**Comment by andreasb242** [comment]
Changed to GTK - close this bug because of age
