### ISSUE TITLE
compliation falis

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1701]
Over the last little while, the compilation has been failing (at least for me) on ubuntu 18.04.
Attaching the longs.
thanks

[CMakeError.log](https://github.com/xournalpp/xournalpp/files/4049711/CMakeError.log)
[CMakeOutput.log](https://github.com/xournalpp/xournalpp/files/4049712/CMakeOutput.log)

**Comment by Febbe** [comment]
A fix is on the way, see https://github.com/xournalpp/xournalpp/issues/1553#issuecomment-573245733 for the reason and how you can fix it.
