### ISSUE TITLE
Redesign large size Xournal++ icon

### ISSUE THREAD

**Issue by luyatshimbalanga** [xournalpp/xournalpp#1705]
**Is your feature request related to a problem? Please describe.**
The current icons used on Xournal++ is set at 48x48 size causing it to not properly display on Gnome Shell.

**Describe the solution you'd like**
Modernize the  Xournal++ icon set at least to 128x128 in SVG format

**Describe alternatives you've considered**
Simply resize the current application icon to 128x128.

**Additional context**
A new Xournal++ logo in addition of refreshed tool icons will improve the appearance of the application while complying to [Gnome Icon and Artwork guideline.](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en)

**Comment by luyatshimbalanga** [comment]
![Screenshot from 2020-01-19 00-32-36](https://user-images.githubusercontent.com/7230131/72677613-3a1e9200-3a53-11ea-95d0-eca397b2dbc3.png)

A preview of the new redesigned Xournal++ icon retaining some elements from the old logo while adhering to Gnome Icon guideline.
Additionally, a icon from the development version is also available.

**Comment by Febbe** [comment]
LGTM

**Comment by Fatih20** [comment]
Cool.

**Comment by Fatih20** [comment]
@luyatshimbalanga So is it going anywhere? Have you made some pull request or what, because I'm looking into doing this as well.

**Comment by luyatshimbalanga** [comment]
![com github xournalpp xournalpp-screenshot](https://user-images.githubusercontent.com/7230131/82125595-d5064f00-975b-11ea-8edb-217a2a8a2ef3.png)
Updated screenshot
