### ISSUE TITLE
Open/Save/Export files only possible from Home/Documents

### ISSUE THREAD

**Issue by sphh** [xournalpp/xournalpp#1711]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Mint 19.3
 - In case of linux, which desktop environment: Cinnamon 4.4.8
 - Which version of libgtk do you use: 3.22.30-1ubuntu4
 - Version of Xournal++: 1.0.16

**Describe the bug**
Whenever I want to open/save a Xournal++ or an PDF file (either using it as background or exporting it), I can only access these folder:

- `Home/Document`
- `Desktop` (but that cannot be selected)
- `Document`

No other folder can be selected.

**To Reproduce**
1. Open Xournal++
2. Select `File > Open` or `File > Save As`, `File > Annotate PDF`, `File > Export as PDF` or `Export As ...` and try to select a directory which is not `Home/Document` or a folder under it.

**Expected behavior**
It should be possible to select any folder on the computer.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/4856462/72689337-998ea780-3b10-11ea-8588-fba0bfafefad.png)
(There are more folders under `Home`, not just `Documents`!)

**Comment by Technius** [comment]
Are you using the Flatpak? If you are, see #1572.

**Comment by sphh** [comment]
Yes, it's installed by the package manager as a Flatpak. (And I missed #1572. Sorry.)

I issued the command given in https://github.com/xournalpp/xournalpp/issues/1572#issuecomment-547224652, but got an `error: Permission denied`. So I issued it as `sudo flatpak ...`. This time I got no error, but saving/opening/... still does not work.

**Comment by Technius** [comment]
Can you try installing `xdg-desktop-portal` and see if it works?

**Comment by sphh** [comment]
Both packages were installed when I encountered the problem:
xdg-desktop-portal 1.0.3-0ubuntu0
xdg-desktop-portal-gtk 1.0.2-0ubuntu1

Do I have to log out and in again after issuing the command from https://github.com/xournalpp/xournalpp/issues/1572#issuecomment-547224652?

**Comment by Technius** [comment]
I just realized that the file chooser portal will not work at all due to external PDFs. Unfortunately, you might have to try the override https://github.com/xournalpp/xournalpp/issues/1572#issuecomment-547198526 and see if it works for you.

**Comment by sphh** [comment]
After calling `sudo flatpak override --filesystem=host com.github.xournalpp.xournalpp` from https://github.com/xournalpp/xournalpp/issues/1572#issuecomment-547198526 I can open files in any location. Thanks.

What are the side effects?

**Comment by Technius** [comment]
Mainly that you can now access any file in any location (defeats the purpose of Flatpak sandboxing), but the downside is probably not worth caring about too much.

**Comment by sphh** [comment]
Thanks for the explanation. I can live with that, because I use the flatpack to install the latest software and not for sandboxing it.

I close this issue, because the underlying cause is tracked in #1572.

**Comment by fedecalosso** [comment]
I just installed Xournal++ on Ubuntu without Flatpack and I have the same problem, even I can't open from other units where I usually save my files.

**Comment by Febbe** [comment]
Can you reopen a new ticket, referring to this but including all the informations required by a bugreport

**Comment by fedecalosso** [comment]
> Can you reopen a new ticket, referring to this but including all the informations required by a bugreport

Yes I can, and I can solve too with an article about similar problem with GIMP on snap: https://www.enmimaquinafunciona.com/pregunta/155805/gimp-210-no-tiene-permiso-para-acceder-a-una-unidad-adicional-mismo-disco-disco-secundario-disco-externo-usb-memoria-etc-por-que-como-resolver-1804?from=redir

**Comment by lguenth** [comment]
Thank you so much @fedecalosso, this solved the issue for me on Ubuntu 20.04. I can now access my external SSD.
