### ISSUE TITLE
Eraser button does not respect changes in writing tool

### ISSUE THREAD

**Issue by y2kmurali** [xournalpp/xournalpp#1712]
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]: Kubuntu 19.04
 - In case of linux, which desktop environment [Wayland, Gnome-Wayland, XWayland, X11]: KDE
 - Which version of libgtk do you use: 3.24.8-1ubuntu1, 2.24.32-3ubuntu1 (not sure which one xournal++ uses)
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]: 1.1.0+dev
    

**Describe the bug**
If you are using a stylus and change the input tool immediately after erasing, the app disregards your manual change and restores the input tool to what it was before erasing began.

**To Reproduce**
1. Select one input tool (e.g. highlighter) and draw something
2. Use the eraser button on a stylus to erase it
3. While still holding the eraser button, change the input tool to something else (e.g. pencil). Alternatively, move the stylus away from the screen so it is no longer detected by the computer and then change the input. I've found both cause the problem consistently. 
4. if you bring the stylus close to the screen (over the writing area), the input automatically switches to the highlighter even though I manually selected the pencil tool.

**Expected behavior**
I expect the app to respect the manual selection instead of overriding it with the input it had cached before the erase button was pressed. I'm guessing there's a simple fix (like checking if the current tool is still an eraser before automatically loading the previous tool) that would fix this.  

**Additional context**
Using a Lenovo Yoga 720 with the Lenovo Active Pen

**Comment by Tall-Lobster** [comment]
#1751 #1670

**Comment by jvwowd** [comment]
#1546

**Comment by Technius** [comment]
Fixed in #2004.
