### ISSUE TITLE
Add option to change background lined ruling/spacing

### ISSUE THREAD

**Issue by y2kmurali** [xournalpp/xournalpp#1713]
**Is your feature request related to a problem? Please describe.**
Some writing applications (i.e. math) require different line spacings than others (i.e. written responses). Xournal currently only has one default line ruling; if I want to change the ruling (e.g. college ruled instead of wide ruled), the only real thing I can do is download a pdf of a college ruled paper and set that as my background, for every document I make.

**Describe the solution you'd like**
I'd like there to be a option under the menu for setting the ruling size manually (i.e. having a menu for ruling width in some unit (font points?)).

**Describe alternatives you've considered**
An alternative might include having a few preset options (wide ruled, college ruled, extra wide ruled, etc.) but that might be extra work for less flexibility for the user.

**Comment by renatobellotti** [comment]
Is there no way to use squared backgrounds instead of lines? I couldn't find the option. For me, this is a deal breaker for not using Xournal++.

**Comment by rolandlo** [comment]
I also think that the ruling size should be made configurable. That's not hard, but requires extending the file format.

@renatobellotti There is the graph background (with or without border). You find it in the menu `journal->page background`

**Comment by Febbe** [comment]
@renatobellotti We already have a preset of default backgrounds, including squared ruling. Those currently have an exact size of 0.5cm(print size)

**Comment by renatobellotti** [comment]
> @renatobellotti We already have a preset of default backgrounds, including squared ruling. Those currently have an exact size of 0.5cm(print size)

Thanks for letting me know!

**Comment by i-zanis** [comment]
Hello, 

Is there a way to reduce the height on the "Ruled" option? 
It enforces letter to become larger.

**Comment by rolandlo** [comment]
@i-zanis It's possible by modifying `pagetemplates.ini`. See https://github.com/xournalpp/xournalpp/issues/2137#issuecomment-799956788
