### ISSUE TITLE
Inserting page while annotating PDF freezes xournalpp

### ISSUE THREAD

**Issue by frogtux** [xournalpp/xournalpp#1717]
**Affects versions :**
 - OS: Debian 10 (buster)
 - X11 with Plasma 5.14.5
 - libgtk 3.19.12
 - Version: 1.1.0+dev

**Describe the bug**
When "Zoom fit to screen" mode or Presentation mode is activated while annotating a PDF and a page with standard background is added, then Xournal++ freezes and terminates after a couple of seconds.

**To Reproduce**
1. Open PDF
2. Activate "Zoom fit to screen" mode or Presentation mode
3. Add new page with standard background (Plain, Graph, Ruled, ...)

**Workaround**
Deactivate "Zoom fit to screen" mode or Presentation mode, insert page and activate previous mode again

**Comment by Febbe** [comment]
I cant reproduce this behaviour on Linux Mint 19.3 Cinnamon (Ubuntu 18.04). So this looks like an dependency or packaging issue.
Which package did you used to install xournalpp?
Can you also try a newer version of libgtk?

**Comment by Technius** [comment]
Appears to be a duplicate of #1660. Are the sizes of your inserted pages and your PDFs different?

**Comment by frogtux** [comment]
I can reproduce #1660, but page sizes doesn't matter for this issue.
To be safe that a external PDF hasn't a slightly different size, I created a PDF from xournalpp with A4 paper size and used this to reproduce the bug.
I use the Ubuntu 18.04 package from Andreas Butti PPA and I tested it with libgtk 3.24.13-1 on Debian testing too.

**Comment by Technius** [comment]
I can't reproduce the bug either. Can you post a gif/video of how you reproduced it?

**Comment by frogtux** [comment]
Here is a short demo gif:

![demo](https://user-images.githubusercontent.com/36341803/73313312-30531680-422b-11ea-8a8c-52f821d460a1.gif)

**Comment by Febbe** [comment]
The Ubuntu binaries are incompatible to Debian binaries you must not use them. Please use the Debian packages provided over our release section.

**Comment by frogtux** [comment]
I switched to the Debian package from Github and the bug doesn't occur anymore.
Interesting that #1660 is fixed too.
Thanks for you help!

**Comment by Technius** [comment]
> I switched to the Debian package from Github and the bug doesn't occur anymore.
> Interesting that #1660 is fixed too.
> Thanks for you help!

Did you use the stable version 1.0.16? AFAIK master branch/nightly has introduced the recent zoom bugs.
