### ISSUE TITLE
Select Object selects the wrong object

### ISSUE THREAD

**Issue by medovina** [xournalpp/xournalpp#1718]
I'm running Xournal++ from on Ubuntu 19.10, installed via the nightly PPA.  I am running it without the new experimental input system.

When I enable the Select Object tool and select on an object, sometimes a nearby object is selected instead.

For example, the screenshot below illustrates part of a form where I am filling in X characters into 
form fields.  I have clicked in the center of the third X from the top of the screen.  I expected that X to be selected, but Xournal has selected the second X instead.  In general, in order to select the X I want I have to click below it, not on it.

![select](https://user-images.githubusercontent.com/673039/73330878-5e078200-4262-11ea-89ba-fb2d1a16968e.png)

**Comment by Technius** [comment]
The selection algorithm currently selects the first matching object ([relevant code](https://github.com/xournalpp/xournalpp/blob/8052bee481f202f3d148ec8337f560e3719dce2f/src/gui/PageViewFindObjectHelper.h#L93-L109)). A simple improvement would be to select the object whose center is closest to the location of the click/tap (of course, there could be better heuristics).
