### ISSUE TITLE
Can't add/edit TeX even if the required package is installed

### ISSUE THREAD

**Issue by tormec** [xournalpp/xournalpp#1719]
**Affects versions :**
 - OS: Xubuntu 18.04.3 LTS (Bionic Beaver)
 - libgtk-3-0 @ 3.22.30-1ubuntu4
 - Xournal++ @ 1.0.16

**Describe the bug**
I can't add/edit TeX content even if the package required `texlive-latex-extra` is installed (see image attached). NormaIy, I write in LaTeX with Texmaker so I'm sure I have all the necessary packages installed.

![bug-add-edit-tex](https://user-images.githubusercontent.com/10964663/73391741-ce50ea80-42d8-11ea-9d6c-4efa166a7d30.png)

Just a side note: the image of that button (Add/Edit Tex) is not very expressive...

**Comment by tattsan** [comment]
The message says "Could not find the LaTeX package 'standalone'."
'standalone' is a package name of LaTeX, and xournalpp uses 'standalone.cls' in it.

**Comment by tormec** [comment]
Yep, but it also says that `standalone` is in `textlive-latex-extra` and, indeed, installing the latter one I've also installed the former one:
/usr/share/texlive/texmf-dist/tex/plain/standalone
/usr/share/texlive/texmf-dist/tex/plain/standalone/standalone.tex

**Comment by tattsan** [comment]
You should confirm whether pdflatex recognize standalone.cls via command line, not on Texmaker. And check what command line Texmaker uses.

**Comment by tormec** [comment]
I talked about Texmaker just to say that I'm sure `standalone is accessible by my Latex installation`. I think it's no longer relevant here...

From command line:
```$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
**standalone
entering extended mode
(/usr/share/texlive/texmf-dist/tex/plain/standalone/standalone.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 10 language(s) loaded.
)
*
```

**Comment by Technius** [comment]
If you run `kpsewhich standalone`, does it output the path of `standalone.tex`?

**Comment by tormec** [comment]
yes, it does
```
$ kpsewhich standalone
/usr/share/texlive/texmf-dist/tex/plain/standalone/standalone.tex
```

**Comment by Technius** [comment]
That's strange. Are you using the Flatpak?

**Comment by tormec** [comment]
No, I'm not using it
```
$ flatpak
Command 'flatpak' not found, but can be installed with:
sudo apt install flatpak
```
As soon as possible I'll try Xournal++ on another machine... maybe I can find which other package is missing.

**Comment by nicegamer7** [comment]
I have a similar problem, but I'm on Windows right now.

It tells me it cannot find kpsewhich in path. But it is, and I do get the correct output when running `kpsewhich standalone` in command prompt.

**Comment by Technius** [comment]
It might be a GTK bug, but I'm not sure. https://gitlab.gnome.org/GNOME/glib/issues/957

The [code that we use for the package checks](https://github.com/xournalpp/xournalpp/blob/9896822e7b73113ee202dce3d13c82192ad7ee07/src/control/LatexController.cpp#L66
) is pretty straightforward, so if there's anything causing them to fail, it has to be in `g_find_program_in_path`.

**Comment by Technius** [comment]
I'm having a hard time reproducing this. I compiled and installed Xournal++ on a Ubuntu 18.04 Docker container and installed the latex dependencies, but it works correctly for me. How did you install Xournal++?

**Comment by tormec** [comment]
From here https://github.com/xournalpp/xournalpp/releases/tag/1.0.16
I downloaded & installed ``xournalpp-1.0.16-Ubuntu-xenial-x86_64.deb``
... but now I realize that I'm on ``Ubuntu-bionic-x86_64`` (as I wrote in the [1st msg](https://github.com/xournalpp/xournalpp/issues/1719#issue-557091166)).
I want to try ``xournalpp-1.0.17-Ubuntu-xenial-x86_64.deb`` and I let you know if something change.

**Comment by tormec** [comment]
Yes!!!! That was my issue

>  but now I realize that I'm on Ubuntu-bionic-x86_64 (as I wrote in the 1st msg).
I want to try xournalpp-1.0.17-Ubuntu-xenial-x86_64.deb and I let you know if something change.

Now it works perfectly!

**Comment by Technius** [comment]
I'm surprised that it actually ran at all when you installed the package for Xenial.

We definitely _do_ need an official package version for 18.04.

**Comment by paolini** [comment]
Same problem here with Ubuntu 18.04.4. I have installed xournal++ with the command 

`sudo snap install xournalpp
`
and standalone is installed:
```
> kpsewhich standalone
/usr/share/texlive/texmf-dist/tex/plain/standalone/standalone.tex

```

**Comment by Technius** [comment]
Can you try the Flatpak or the PPA? I think the snap sandbox is causing problems.

**Comment by Girodu** [comment]
I have the same problem but i'm on Ubuntu 20.04 i installed it via snap, i was looking for uninstall and install it via deb but there isn't a focal fossa one, and there isn't a stable ppa.
what do you recommend me to do?
thank you!

**Comment by LaifsV1** [comment]
Same issue on Ubuntu 18.04.4 LTS. 
I installed Xournal++ 1.0.16 via the Ubuntu Software GUI.
`texlive-latex-extra` is installed and `kpsewhich standalone` finds `standalone.tex`.

**Comment by lizliz** [comment]
I'm having the same issue on Ubuntu 20.04 LTS, get the same error as OP.

I installed Xournal++ 1.0.16 via snapcraft store. 

```
(base) liz@Gandalf:~$ kpsewhich standalone
/usr/share/texlive/texmf-dist/tex/plain/standalone/standalone.tex
```

**Comment by aberetta145** [comment]
same issue as lizliz , ubuntu 20.04.
![image](https://user-images.githubusercontent.com/68437253/87808289-b9055380-c859-11ea-8690-55d84f0f3ed7.png)

**Comment by carloshiga** [comment]
Same issue here. Any solution?

**Comment by OsinenkoP** [comment]
`Ubuntu 20.04`, `xournal 1.0.16`, same issue. Why is it even closed?

**Comment by aberetta145** [comment]
with this version I can finally use latex:
[image: image.png]
Alessandro

Il giorno sab 29 ago 2020 alle ore 14:12 Pavel Osinenko <
notifications@github.com> ha scritto:

**Comment by carloshiga** [comment]
We can't see the image.

**Comment by aberetta145** [comment]
Xournalpp
Version: 1.1.0+dev
with libgtk: 3.24.20


Il giorno lun 14 set 2020 alle ore 01:50 Carlos Higa <
notifications@github.com> ha scritto:

**Comment by busla** [comment]
can this be re-opened?

Using 20.04 and having the same issue as @OsinenkoP

**Comment by busla** [comment]
Fixed this for now, by installing from ppa:apandada1/xournalpp-stable. Lots of improvements!

Thanks for keeping xournalpp rolling!!

Solution found here:
https://tex.stackexchange.com/questions/564936/how-to-make-standalone-package-available-by-my-latex-installation/567649#567649

**Comment by puneetskhurana** [comment]
I had the same issue and here's how I fixed it: 

Uninstalled xournal++ 

Then downloaded the correct package from http://ubuntuhandbook.org/index.php/2019/10/xournal-1-0-5-released-install-ubuntu/

Then, ran the package through gDebi package installer and voila... everything works, including the option to save my files in other folders that were previously not being detected.

The issue was, as far as what I understood, that the package installed through Ubuntu Software Installer was bionic and I am using Ubuntu 20 which is NOT bionic... You need to install the focal package if you are using Ubuntu 20.04 or Ubuntu 20.10 like I. 

Hope this helps!!

**Comment by rolandlo** [comment]
Installation options are generally listed on the work-in-progress [website](https://xournalpp.github.io/installation/). Installing the Snap Package from SnapCraft is discouraged, since it is unofficial, unmaintained and outdated.
If you install the Flatpak, you will not be able to use LaTeX unless you install LaTeX as an extension via `flatpak install flathub org.freedesktop.Sdk.Extension.texlive` according to [this site](https://github.com/flathub/com.github.xournalpp.xournalpp).

**Comment by puigpuig** [comment]
I had the same problem and I followed these steps and worked fine: 
- install the right version for the linux you use. Un my case is Linux Mint 20, that is Focal: https://linuxmint.com/download_all.php
- Install latex standalone by means of: sudo apt-get install texlive-latex-extra 
(see here the instructions.  https://tex.stackexchange.com/questions/270888/installing-latex-standalone-in-ubuntu-for-humans
And it works fine with linux mint 20.1.

**Comment by rolandlo** [comment]
This is an old issue that may need update. In meanwhile we also have a snap package on [snapcraft.io](https://snapcraft.io/xournalpp), which includes TinyTeX, a LaTeX distribution optimized for size containing the essential things.

**Comment by erik55** [comment]
Just wanted to add that on Fedora 35 you have to install two packages for it to work:

    sudo dnf install texlive-{standalone,scontents}

**Comment by GeoMinesDiamonds** [comment]
Compiling from source did it for me.
You can find build instructions in the [home page](https://github.com/xournalpp/xournalpp#building).

If you still run into a problem, you may go to  Edit --> Preferences --> LaTeX --> Test configuration. The output will be in `/tmp/`, where you can find a folder beginning with `xournalpp` and numbers attached after that.

I personally had to install the **varwidth** package by running `sudo tlmgr install varwidth` in a terminal.

**Comment by zak905** [comment]
thanks @erik55, installing the packages you mentionned solved the issue on Fedora 42.
