### ISSUE TITLE
Pixel Slate support

### ISSUE THREAD

**Issue by harpone** [xournalpp/xournalpp#1720]
Oh wow just found out Xournal is still in active development and is looking really great! I remeber using xournal on my Lenovo Tablet with Wacom digitizer like 10 years ago :D

I recently got a Pixel Slate, and found out about the Xournal++ project. I installed the Linux VM just to try Xournal, but unfortunately the Google stylus is not detected...

Any plans to support Pixel Slate and other Pixel devices + the pen?

**Comment by nicegamer7** [comment]
I'd look at #1444. I believe there is significant progress there.

**Comment by harpone** [comment]
Oh cool, I'll check that out thanks!
