### ISSUE TITLE
Cannot find pdflatex in PATH, even though it is in path

### ISSUE THREAD

**Issue by aalok-sathe** [xournalpp/xournalpp#1723]
**Affects versions :**
 - OS: Ubuntu 16.04 MATE 
-  Mate desktop (gdm2, marco compositor)
 - libgtk-3-common/xenial-updates,xenial-updates,now 3.18.9-1ubuntu3.3
 - xournalpp/xenial,now 1.0.6-0\~201910161708\~ubuntu16.04.1

**Describe the bug**
Xournal++ cannot find my pdflatex on PATH even though it is on PATH

**To Reproduce**
1. Open a pdf to annotate using xournalpp
1. Click on the button to input Math TeX
1. Pop-up says: please make sure pdflatex is in your PATH and try again

**Expected behavior**
Able to input TeX using my texlive installation and pdflatex binary that's on PATH

**Comment by Technius** [comment]
Probably related to #1719.

**Comment by Technius** [comment]
If you run xournalpp from console, do you get the same issue? What is the output of `which pdflatex`?

**Comment by ajay-anand** [comment]
I am facing same problem with flatpak version of xournalpp. The PATH has been set in .bashrc as well as in /etc/environment and 'which pdflatex' points to the local folder where latex is installed. Also, it doesn't matter how I launch xournalpp, from console or application icon, in both cases the same message appears. 
Latex installed in:
 ~/.latex/bin/x86_64-linux
OR
/home/user/.latex/bin/x86_64-linux

**Comment by ajay-anand** [comment]
The issue persists even after installing latex natively:
apt install texlive-latex-extra
which pdflatex # /usr/bin/pdflatex
(Using flatpak version of xournalpp 1.0.17 on Ubuntu 18.04)

**Comment by Technius** [comment]
> The issue persists even after installing latex natively:
> apt install texlive-latex-extra
> which pdflatex # /usr/bin/pdflatex
> (Using flatpak version of xournalpp 1.0.17 on Ubuntu 18.04)

For the Flatpak version, you will need to install the texlive extension for Flatpak:
```
flatpak install flathub org.freedesktop.Sdk.Extension.texlive
```

**Comment by ajay-anand** [comment]
> > The issue persists even after installing latex natively:
> > apt install texlive-latex-extra
> > which pdflatex # /usr/bin/pdflatex
> > (Using flatpak version of xournalpp 1.0.17 on Ubuntu 18.04)
> 
> For the Flatpak version, you will need to install the texlive extension for Flatpak:
> 
> ```
> flatpak install flathub org.freedesktop.Sdk.Extension.texlive
> ```

True, thanks.

**Comment by Technius** [comment]
@aalok-sathe Is this still an issue for you?

**Comment by aalok-sathe** [comment]
let me check!

**Comment by aalok-sathe** [comment]
No longer facing this issue! Thanks!

**Comment by sr561** [comment]
I have the same problem, except with a different OS.

OS: macOS 10.14.6
xournalapp version: 1.0.18

When I click on the button to input Math Tex, I get "Could not find pdflatex in PATH. Please install pdflatex and make sure it's in the PATH" although I have pdflatex installed.

**Comment by mePy2** [comment]
Me too (macOS)

**Comment by matthiasunt** [comment]
Having the same issue (macOS 10.15.5, Xournal 1.0.18)

**Comment by renatobellotti** [comment]
Same here on Fedora 32. Following the [comment by @Technius](https://github.com/xournalpp/xournalpp/issues/1723#issuecomment-602080759) solves the problem, so just execute this:

```
flatpak install flathub org.freedesktop.Sdk.Extension.texlive
```

**Comment by mathswami** [comment]
The problem of integrating pdflatex with xournal+ is still there. Any suggestions? Please!

**Comment by renatobellotti** [comment]
I think this is not a problem of xournal++ itself, but of the sandboxing of the Flatpack app. This is why you need to install the texlive extension, as I've written in my previous comment.

**Comment by mathswami** [comment]
> I think this is not a problem of xournal++ itself, but of the sandboxing of the Flatpack app. This is why you need to install the texlive extension, as I've written in my previous comment.

But Flatpack is for integrating various linux platforms. I need it for MacOS. In fact, I can use it inside a VM. Not giving the required result in this case

**Comment by renatobellotti** [comment]
When you open a terminal, can you run `pdflatex`?

**Comment by mathswami** [comment]
Yes, I can

**Comment by mathswami** [comment]
Yes, I can run the pdflatex from the terminal

**Comment by gausscantor** [comment]
for ME (macos 10.14.6) LaTeX in document works, when I start xournal via terminal

> cd /Applications
> open Xournal++.app

**Comment by rolandlo** [comment]
@gausscantor Your solution still works on macos 10.15.7
