### ISSUE TITLE
Change directory for source PDF

### ISSUE THREAD

**Issue by WPettersson** [xournalpp/xournalpp#1725]
**Is your feature request related to a problem? Please describe.**
I often download PDFs to read, and only sometimes want to annotate them and then save the result. By default, downloaded PDFs are saved to /tmp/, and deleted occasionally when cleaning up (i.e., on reboots). If I decide to annotate and keep the result, I can export the resulting annotated PDF to ~/Documents/. However, I cannot save the resulting .xopp file to ~/Documents/, as the .xopp refers to /tmp/ to find the PDF, which will at some point be cleaned up

**Describe the solution you'd like**
I'd like the ability to save "PDF + XOPP" files to a given directory. One option is to have a distinct option for "Change source PDF location", which would update the URL to the PDF, and save the PDF to a new location. Another option would be to save the PDF within the .xopp file as some sort of package.

**Describe alternatives you've considered**
My current workaround is to manually script "move_pdf_to_xopp.sh", which gunzip's the .xopp, extracts the PDF location, copies the PDF to the current directory, updates the unzipped .xopp, then gzips the .xopp back up.

**Comment by Technius** [comment]
A new file format that packages xopp files with all required resources is in the works (#937), but it'll be a few more months (up to a year) before we have an initial implementation out.

**Comment by WPettersson** [comment]
Ooh, I didn't think to look for a new file format, my bad. That will solve my issue, and I'm happy to stick with my workaround for the time being, thanks :)

**Comment by atticus-sullivan** [comment]
> My current workaround is to manually script "move_pdf_to_xopp.sh", which gunzip's the .xopp, extracts the PDF location, copies the PDF to the current directory, updates the unzipped .xopp, then gzips the .xopp back up.

Would you mind sharing the script? ;)

**Comment by WPettersson** [comment]
Sure, it's at https://gist.github.com/WPettersson/325a9e72edf5e9fbe3c6bbe3a699472f

**Comment by atticus-sullivan** [comment]
Thanks


‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rolandlo** [comment]
As I just discovered there is a way in Xournal to move a pdf along with the xoj-file to another folder, without having the link refer to the old file path of the pdf.  Citing from the user guide of Xournal:

> By default, the PDF file used to generate the backgrounds will not be saved with the journal; instead, the journal file will contain a reference to the absolute location of this file. This means that all backgrounds will become unavailable if the PDF file is moved or deleted (although Xournal will let you specify the updated location of the PDF file when opening the journal file). To avoid this, check the option "Attach file to the journal" at the bottom of the dialog box when opening the PDF file. The PDF file will then be saved along with the journal (using a file name of the form *.xoj.bg.pdf). 

This checkbox is still present in Xournal++. It just currently does not have the desired effect, since the (absolute) path is saved even if the "Attach file to the journal" option is checked. This can easily be fixed. I will make a PR.
