### ISSUE TITLE
Trying to build on jessie, missing docs, poppler issues

### ISSUE THREAD

**Issue by axkibe** [xournalpp/xournalpp#173]
Okay, I'm trying to get this build on Debian jessie.

Issue one, after clone, libcms1 is no longer available but libcms2. I get it that the "development" branch ought to be used which fixes this and uses cmake instead of autotools (I can understand pretty well to say goodbye to autotools disaster)

Issue 2. Cmake poppler find fails, since it looks for

```
file (STRINGS "${POPPLER_INCLUDE_DIR}/poppler-config.h" POPPLER_CONFIG_H_CONTENTS REGEX "#define POPPLER_VERSION ")
```

Albeit I installed the poppler-dev packages, I dont have any "poppler-config.h" on my system, I have a "poppler-version.h" in "cpp" tough or "poppler-featuers.h" in "glib" (dunno which xournalpp needs) 
0.26.5 for me

I set that hard by adding

```
set (POPPLER_VERSION "0.26.5")
```

to src/pdf/popplerdirect/workaround/CMakeLists.txt

it fails with

```
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `goo/Makefile.in'
CMakeFiles/poppler.dir/build.make:100: recipe for target 'poppler-prefix/src/poppler-stamp/poppler-configure' failed
make[2]: *** [poppler-prefix/src/poppler-stamp/poppler-configure] Error 1
CMakeFiles/Makefile2:186: recipe for target 'CMakeFiles/poppler.dir/all' failed
make[1]: *** [CMakeFiles/poppler.dir/all] Error 2
```

I guess this works only with specific poppler versions? When yes please document what versions are supported.

BTW I get 

```
Running ./configure --enable-poppler-glib --enable-poppler-cpp --enable-static --disable-poppler-qt4 --disable-poppler-qt5 --disable-utils --enable-zlib ...

configure: WARNING: unrecognized options: --enable-static
```

Which I suppose will turn out as problem as well when you want to bind poppler as static.

**Comment by axkibe** [comment]
PS: As it seems that the 'master' branch is not intended to work on already year old distributions and not being worked anyway, why not move that to "old" and change "development" to "master"?

**Comment by axkibe** [comment]
Ok, thanks for the non-support.

**Comment by wbrenna** [comment]
I missed that issue 2 applies to the development branch. I merged to master so issue 1 and your followup should be fixed.
