### ISSUE TITLE
Add option to make export fit content

### ISSUE THREAD

**Issue by gfauredev** [xournalpp/xournalpp#1739]
**Is your feature request related to a problem? Please describe.**
Is not really a problem but it could save me a lot of time.

**Describe the solution you'd like**
I wish there was an option to make export that contains only the content, without background and useless space that contains nothing.

**Describe alternatives you've considered**
I actually resize files in Gimp but is boring.

**Comment by Alexis-Prel** [comment]
@Shatonly Why not using the `pdfcrop` command for this purpose?

**Comment by bhennion** [comment]
Closing in favour of #4053
