### ISSUE TITLE
Selected strokes are not saved

### ISSUE THREAD

**Issue by Sompom** [xournalpp/xournalpp#174]
Greetings,

There appears to be a problem where a stroke which is selected is not scooped up and saved with the rest of the document; this could be a feature rather than a bug if one declares that anything selected is floating and therefore not really part of the document.

To reproduce:
- Start Xournalpp with a blank document
- Draw a stroke
- Save the document and open it with a different instance of xournal/xournalpp (To make sure saving is working at all!)
- Select the stroke using any of the selection tools, move it somewhat, then save the file (leaving the stroke selected)
- Open the file in a new instance of xournal/xournalpp - I do not see the selected stroke in the file

I tested this with both the gtk3 branch and the master branch (both fresh pulls as of tonight) and the issue is the same in both

Thanks,
Sompom

**Comment by wbrenna** [comment]
Thanks for filing this - this is a good bug to fix, all strokes should be deselected on save.
