### ISSUE TITLE
Building poppler ignores make's jobs flag

### ISSUE THREAD

**Issue by Sompom** [xournalpp/xournalpp#175]
Greetings,

I understand that including poppler in the repository is just a workaround, but there's no reason it shouldn't be a nice workaround! For me, having a jobs flag on poppler reduced the compile time of the entire project from minutes to seconds. One option would be to figure out how to pass a jobs flag from the original makefile. An easier option (a workaround to the workaround, if you like) is to just bolt on a jobs flag and hope nobody notices. I think the attached patch would do the trick.

Thanks,
Sompom

[add_jobs_poppler.patch.txt](https://github.com/xournalpp/xournalpp/files/223158/add_jobs_poppler.patch.txt)

**Comment by MarPiRK** [comment]
I've done it a little bit different way in `development` branch. It's not the best solution, but it seems to work.

**Comment by wbrenna** [comment]
Thanks! In my experience the development branch has solved the poppler issues satisfactorily but this is handy until things get integrated.
