### ISSUE TITLE
Crashes when trying to open Preferences

### ISSUE THREAD

**Issue by NovaViper** [xournalpp/xournalpp#1755]
(Please complete the following information, and then delete this line)

**Affects versions : **
 - OS: Linux, Ubuntu 19.10
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: libgtk-3
 - Version of Xournal++: 1.0.17
 - Installation method: Official Release

**Describe the bug**
Whenever I try to go and open the Preferences of the program via the Preferences tab under Edit, the program immediately crashes

**To Reproduce**
1. Install Xournal++
2. Go to Edit > Preferences
3. The program should crash immediately

**Expected behavior**
Something should open

**Screenshots of Problem**

**Additional context**
I am very, very new to Linux so I'm not sure if there was something I did wrong in installing the package.. I just went and used the deb package that was under the official release

**Comment by Technius** [comment]
Can you try installing from the PPA? Our official distributions only support Ubuntu 16.04.

**Comment by NovaViper** [comment]
I just installed it through the PPA and it works! Thanks for the info

⁣Get BlueMail for Android ​

**Comment by Technius** [comment]
Closing this for now since there's at least one other issue tracking our lack of an 18.04 release.
