### ISSUE TITLE
Xournalapp gets stuck when clicking on "save as" or "export pdf"

### ISSUE THREAD

**Issue by scollovati** [xournalpp/xournalpp#1759]
**Affects versions :**
 - Linux Mint Cinnamon 19.1
 - libgtk2
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
Xournalapp gets stuck when clicking on "save as" or "export pdf". The behaviour happens randomly, but especially when the application has been opened by a long time.

Autosave is disabled since it was creating issues.

**Comment by rolandlo** [comment]
@scollovati Is that still happening with the latest version of Xournal++?

**Comment by scollovati** [comment]
hi @rolandlo,
tested with version `1.0.20` and seems to be solved.

Probably my issue was similar to https://github.com/xournalpp/xournalpp/issues/2062

Thanks for fixing it. This tool is awesome.
