### ISSUE TITLE
Searching for Maintainer for Getting into PPA / Official Repositories

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#176]
We should think about:
- Searching for a Maintainer for Official Debian Repositories
- Create a PPA for Ubuntu / Debian
- Copr for RPM based distributions

Other possibilities?

Other Ideas to make Xournal easier to install? A standard user don't want to compile the application to use it...

**Comment by MarPiRK** [comment]
It's related to #143. It's fairly easy to make packages with CPack.

**Comment by unruhschuh** [comment]
I could create [AppImages](http://appimage.org/) for Xournal++. Which branch should I base it on? The latest release seems a bit old.

**Comment by andreasb242** [comment]
I created a PPA for Ubuntu, I'm currently setting up the build

**Comment by andreasb242** [comment]
I would also know a little bit more how to do the build :-)

What I did until now:
make package creates a package.

But then I found out, that's not how PPAs on Launchpad are working.
You create only a source package, NOT a .dep. The source package will then be compiled.

Thanks to @youduda for getting good tipps and fixing my packaging stuff!
I also created some Debian packaging stuff, but I'll delete it, and use the one from @youduda

**Comment by andreasb242** [comment]
@youduda If you have Time: Help is always welcome ;-)

By the way, I set up a Notebook today, and the xournalpp.desktop is not in the Launcher anymore, so postinst.in has a Bug, which I didn't find yet...

**Comment by andreasb242** [comment]
I installed Ubuntu 18.04 again fresh, and the starter Icon was not in the launcher, but after I cliced on /usr/share/applications/xournalpp.desktop it also was available in the launcher.

So not sure whats the point.

**Comment by andreasb242** [comment]
Ubuntu PPA and OpenSuse Packaging is done. For new Requests please open new Tickets, this was open long enough :-)
