### ISSUE TITLE
[compatibility question] Working with musl?

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [xournalpp/xournalpp#1761]
I would like to know if Xournal++ supports musl C compiler instead of gcc.

**Affects versions :**
 - OS: Void Linux
 - (Linux only) Desktop environment: Gnome-Wayland
 - Version of Xournal++: master
 - Installation method: build from source

**Comment by Technius** [comment]
I believe it does, since @Cogitri has been able to get Xournal++ to work on Alpine Linux. If you get a crash, please see https://github.com/xournalpp/xournalpp/issues/1471#issuecomment-532266214.

**Comment by Cogitri** [comment]
Yup, it works fine with musl libC for me, I use it daily :)
