### ISSUE TITLE
Each instance appears as an iconless entry on GNOME dash and app switcher

### ISSUE THREAD

**Issue by badshah400** [xournalpp/xournalpp#1766]
**Affects versions :**
 - OS: Linux (openSUSE Tumbleweed)
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use: 3.24.14
 - Version of Xournal++: git master at commit 46a4dc8
 - Installation method: Compile from git

**Describe the bug**
Xournalpp registers as a ghost (i.e. iconless) entry on the GNOME dash (application drawer on the left edge of the screen) for each individual instance that is open. This is also true of its appearance on the application switcher (Alt-Tab). The application name is also incorrectly registered on the top bar (just beside Activities) as xournalpp instead of "Xournal++", the app name as registered in the .desktop file.

**To Reproduce**
1. Open multiple instances of xournalpp on GNOME
2. Open the application overview by clicking on "Activities" in the top left corner of the desktop.
3. Try using Alt-Tab to switch between applications.

**Expected behavior**
There should be one entry on both the application switcher and dash registered as "Xournal++" (not as 'xournalpp') with the right icon, no matter the number of instances of the app open (see e.g. how nautilus shows up when it has multiple instances/windows open).

**Screenshots of Problem**
![Screenshot from 2020-03-11 00-14-23](https://user-images.githubusercontent.com/3532467/76367926-e03d9880-632e-11ea-910f-33c30d0308aa.png)
See iconless entries on the dash (left edge of screen), both from xournalpp windows.

![image](https://user-images.githubusercontent.com/3532467/76368175-9a350480-632f-11ea-8fc8-19b7106a1b7c.png)
Ghost entries on application switcher (as opposed to nautilus, which also has 2 instances open)

**Comment by badshah400** [comment]
Similar to issue #1454, I guess, but now with ghost icons.

**Comment by Technius** [comment]
Does this bug still affect you on master? There have been recent changes that may have fixed this bug.

**Comment by badshah400** [comment]
Confirmed fixed by commit 269c1acdcb864e6ca073e1047a1c48f01cf91ffb
