### ISSUE TITLE
Crash while trying to save

### ISSUE THREAD

**Issue by palvaradomoya** [xournalpp/xournalpp#1776]
**Affects versions :**
 - OS: KUbuntu 18.04.04
 - Desktop environment: X11 with KDE/Plasma (544)
 - libgtk 3.22.30 / 2.24.32
 - Version of Xournal++: 1.1.0+dev from master branch, Git commit 46a4dc82
 - Installation method: DEB Package build directly from sources

**Describe the bug**
Xournal++ crashes while trying to save

**To Reproduce**
1. Open xournalpp
2. Draw something, type something
3. Try to save File->Save
4. A file selection dialog is opened.  Nothing can be selected there.  As soon as anything is clicked, the program crashes with:

(xournalpp:27778): Gtk-WARNING **: 18:27:24.974: Theme parsing error: <data>:1:22: Junk at end of value for font-family
Gtk-Message: 18:27:25.068: GtkDialog mapped without a transient parent. This is discouraged.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)

** (xournalpp:27778): WARNING **: 18:27:48.599: [Crash Handler] Crashed with signal 6

** (xournalpp:27778): WARNING **: 18:27:48.599: [Crash Handler] Wrote crash log to: /home/palvarado/.xournalpp/errorlogs/errorlog.20200317-182748.log

** (xournalpp:27778): WARNING **: 18:27:48.757: Trying to emergency save the current open document…

** (xournalpp:27778): WARNING **: 18:27:48.757: Successfully saved document to "/home/palvarado/.xournalpp//emergencysave.xopp"
  

**Expected behavior**
The file should be saved.  (The backup file seems to work though)

**Additional context**
I guess it has something to do with mapping the GTK skin to Qt, but xournalpp shouldn't crash.  The selected skin for GTK 2 and 3 is breeze.

**Comment by Technius** [comment]
Do you have `gnome-icon-theme` installed? This seems similar to #1347.

**Comment by palvaradomoya** [comment]
I don't have the gnome-icon-theme installed.  However, the problem disappeared installing some additional breeze packages.  Since this is the first gtk app that crashed this way, I guess there is nonetheless some uncatched errors around.  I get several compiler warnings about this.  If I get the chance, I try to patch them.

Thanks a lot for the great tool.
