### ISSUE TITLE
Merge development branch to gtk3

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#178]
As I can see currently development is the most active in gtk3 branch. `development` branch has many important fixes and rewrites though, so it would be nice to merge them into `gtk3` and make it after merge `development` branch.

**Comment by wbrenna** [comment]
This would be nice - but it does require some work. A lot of changes were made in gtk3 and merging is not trivial. Ideally those who are working on gtk3 can add past development features to that branch and eventually the two can be brought together without much pain.

**Comment by MarPiRK** [comment]
You have to bear in mind that development is based on old glib_new, which
is gtk2, so it definitely won't be that easy.
24 maj 2016 01:41 "wbrenna" <notifications@github.com> napisał(a):

This would be nice - but it does require some work. A lot of changes were
made in gtk3 and merging is not trivial. Ideally those who are working on
gtk3 can add past development features to that branch and eventually the
two can be brought together without much pain.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/xournalpp/xournalpp/issues/178#issuecomment-221127558>

**Comment by andreasb242** [comment]
Master is now at GTK3, development branch makes anyway no sense - better use fork and pull requests
