### ISSUE TITLE
Debian buster package missing

### ISSUE THREAD

**Issue by meaz** [xournalpp/xournalpp#1787]
Hi,
Just for your information, I've just downloaded the package for debian buster. I had an error with `dpkg -i`: I had to install `libportaudiocpp0` package to make it work.

**Comment by Technius** [comment]
This is expected if you don't have all of the dependencies available: `dpkg -i` will not download any dependencies. Instead, you should use `apt install ./my_package.deb`, which will automatically download any dependencies that the package may require.
