### ISSUE TITLE
Customize toolbar has floating reference bug

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#179]
To reproduce, customize toolbar and move the leftmost separator over by one.

```
(xournalpp:10445): Gtk-WARNING **: A floating object was finalized. This means that someone
called g_object_unref() on an object that had only a floating
reference; the initial floating reference is not owned by anyone
and must be removed with g_object_ref_sink().
Removed tool item from Toolbar toolbarTop1 ID 238
ToolbarData::insertItem(toolbarTop1, SEPARATOR, 4);
Toolbar found: toolbarTop1
return 293
```

**Comment by wbrenna** [comment]
Also, moving the separator seems to be saved with an increment of +1 of where it should actually end up on reopening.

**Comment by ziekke** [comment]
I'd like to add to this that I experienced some crashes when moving things around. I haven't been able to reproduce it when running xournalpp from command line yet, but it occurred when customizing either the "Portrait" toolbar, or the "Left Side" one. I'll try and get more info here.

**Comment by andreasb242** [comment]
I fixed some errors for GTK3 master merge. I found a lot of errors, hopefully these are also gone now
