### ISSUE TITLE
Icon is ugly on Latte Dock and not visible on Cairo-Dock

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1791]
Affects versions :

OS: Manjaro
(Linux only) Desktop environment: X11
Which version of libgtk do you use
gtk3 1:3.24.14+9+g429a6287e0-1
gtk2 2.24.32-2
Version of Xournal++: 1.1.0+dev 46a4dc8
Installation method: AUR

**Describe the bug**

Latte:
![image](https://user-images.githubusercontent.com/19779511/77258960-5a024a00-6c7e-11ea-9dea-10bc684b222b.png)

Cairo:
![image](https://user-images.githubusercontent.com/19779511/77258942-350dd700-6c7e-11ea-9bfb-cf4ec060e27d.png)

**Comment by psifidotos** [comment]
https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

**Comment by coldspark29** [comment]
It is still ugly, but it changes when I manually exchange the icon in /usr/share/applications/com.github.xournalpp.xournalpp.desktop

So seems that the icon itself is buggy!

**Comment by Febbe** [comment]
Can you try to put the SVG - icon into an SVG optimizer. The current icon may be too big or uses a too new standard. For example QT only supports  "svg tiny". Thus KDE is based on QT this may be the case here.

**Comment by coldspark29** [comment]
I don't think this is necessary. A year ago there was no issue, at least in Cairo Dock. Maybe you just revert back to the old icon file?

**Comment by psifidotos** [comment]
https://github.com/xournalpp/xournalpp/blob/master/desktop/com.github.xournalpp.xournalpp.desktop

is that the desktop file you are using in Linux?

**Comment by coldspark29** [comment]
@psifidotos Yes, but I added the StartupWMClass

**Comment by psifidotos** [comment]
> @psifidotos Yes, but I added the StartupWMClass

What it the xprop output?

**Comment by psifidotos** [comment]
What is the xprop output?

**Comment by coldspark29** [comment]
It outputs xournalpp and Xournalpp

**Comment by psifidotos** [comment]
1. These values mean that the StartupWMClass is a necessity to add, otherwise most Linux taskmanagers will struggle to make the association
2. As long as in 1 the desktop file association is made correct then the next question is it might messes svg and png versions. If you remove the png icon version from highcolor theme is it fixed?

**Comment by coldspark29** [comment]
I don’t have xournalpp in my highcolor theme. I already changed the icon to a png I downloaded from Github. Now it looks good in Latte, but not in the application starter.

**Comment by psifidotos** [comment]
isnt the svg installed at the highcolor theme? where is it installed?

**Comment by coldspark29** [comment]
Okay I found it. When I delete it, it is always ugly. By default it gets ugly as soon as you pin it.

**Comment by apandada1** [comment]
The icon was blurred in latte dock in Plasma 5.21.1 (in KDE Neon), and if the icon theme is changed, still the default icon shows up.

The solution was to add the line `StartupWMClass=xournalpp` to the .desktop file (now the icon is not blurred under the default icon theme, and also, it respects modified icon in other icon themes.
Please consider adding this line to the .desktop file in the source code.

Source: https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F
