### ISSUE TITLE
Wacom Wayland support

### ISSUE THREAD

**Issue by Skyfire716** [xournalpp/xournalpp#1793]
I would love to see a Wacom Tablet support under Wayland.

It seems like there is a libinput under Wayland that probably supports Tablets.

https://github.com/linuxwacom/xf86-input-wacom/wiki/Wayland-and-Wacom-devices

**Comment by lehmanju** [comment]
This should already be possible if libinput supports your tablet. Unfortunately, you have to install/configure libinput correctly for your device. We do not provide hardware specific code and rely on libinput/gtk.

**Comment by franglais125** [comment]
@Skyfire716 for what it's worth, I use Xournal++ on Wayland and my Wacom worked just fine out of the box, on Debian Testing.

You could perhaps give it a try with newer package sin your distro.
