### ISSUE TITLE
2nd button on my stylus does not work

### ISSUE THREAD

**Issue by lukyluket** [xournalpp/xournalpp#1796]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Kubuntu 18.04
 - X11
 - Which version of libgtk do you use 3.22.30
 - Version of Xournal++: 1.1.0+dev 
 - Installation method: PPA
**Describe the bug**

My pen has 2 buttons, when I press button 1 I guess it becomes an eraser, and then it has button 2
when I press button 2 nothing happens until the tips touch the screen, then the corresponding tool is selected, but there is no way I can either draw, erase or select, it is as if I was not touching the screen. 

The same setups works on xournal when I have eraser tip selected and button 2 as eraser and button 3 as select region

The xinput command provides this
Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Wacom HID 4841 Pen stylus                 id=13   [slave  pointer  (2)]
⎜   ↳ Wacom HID 4841 Finger touch               id=14   [slave  pointer  (2)]
⎜   ↳ DELL0823:00 044E:120A Touchpad            id=15   [slave  pointer  (2)]
⎜   ↳ Wacom HID 4841 Pen eraser                 id=20   [slave  pointer  (2)]
⎜   ↳ Logitech Optical USB Mouse                id=10   [slave  pointer  (2)]

xsetwacom --get  "Wacom HID 4841 Pen stylus" TabletPCButton
provides on.

Please let me know if you need more information or if you can suggest some settings that make both buttons work, currently only one of them works. 

Thank you for your effort and kind regards

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by lehmanju** [comment]
This is a common problem with libinput or your kernel driver. Unfortunately, you can only try to set the correct device class in settings and configure what your stylus button should do. If it doesn't work then it is an issue outside of out scope.

**Comment by lukyluket** [comment]
thanks lehmanju, just wanted to mention that the issue disappears when unclicking enable new input system in preferences, so I guess is probably an internal bug of the new input system.

Thanks
Luca

**Comment by lehmanju** [comment]
@lukyluket could you try to get it working with the new input system? You might need to change the device class in settings to get it started. If it works with the old one it should work with the new one, as the button behavior is practically the same.

**Comment by lehmanju** [comment]
@lukyluket would be helpful if you could provide some debugging information with the new input system as well: https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs

**Comment by lukyluket** [comment]
I will but cannot do it immediately, will try to do it by the end of this
week, thank you very much
Luca

**Comment by lukyluket** [comment]
Just a comment I have tried to at least prepare the build, and with the
manually built xournalpp I cannot reproduce the bug....
