### ISSUE TITLE
Request: Option to hide the scroll bar to avoid scrolling by accidental touch

### ISSUE THREAD

**Issue by lumaku** [xournalpp/xournalpp#1804]
**Is your feature request related to a problem? Please describe.**
During writing on the screen with a pen, my palm touches the side. On the side, there is the scroll bar, touching it causes the program to scroll to another part of the document. I did not find the option to turn the scroll bar off or hide it. In presentation mode or fullscreen view, it is also still switched on.

**Describe the solution you'd like**
Please provide an option to hide the scroll bar or move it to another side.

**Describe alternatives you've considered**
Locking the view to the current page, as many PDF readers do; and turn the page via button or gesture.

**Additional context**
Xournalpp version 1.0.17 on latest Gnome / Arch Linux.

**Comment by Technius** [comment]
Scroll bar hiding options are already present in the settings:
![image](https://user-images.githubusercontent.com/1066652/106373756-9fc57f80-6331-11eb-92f9-170a5540ba83.png)
