### ISSUE TITLE
Dropdown menu only reacts to stylus, but not to touch input

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1807]
OS: Manjaro
(Linux only) Desktop environment: X11
Which version of libgtk do you use
gtk3 1:3.24.14+9+g429a6287e0-1
gtk2 2.24.32-2
Version of Xournal++: 1.1.0+dev 12febf7lb
Installation method: pacman

**Describe the bug**
You can activate the dropdown menu but tapping on items of it shows no reaction

**Comment by lehmanju** [comment]
GTK issue, nothing we can do about.
