### ISSUE TITLE
Recording display needed

### ISSUE THREAD

**Issue by nail1962** [xournalpp/xournalpp#1809]
In last versions the sound recording was realized. To make lesson I need for recording display (working area of xournal++) with recording sound. In this case the xournal++ will be full tool to make lessons.

**Comment by Technius** [comment]
Implementing full recording capabilities is out of scope of this project. I would recommend using general purpose recording software such as [OBS](https://obsproject.com/) to record both your screen and your microphone. You can then livestream or upload (as video) your lessons.

**Comment by asanakoy** [comment]
But why is there sound recoding in xournal++ at the first place? Without video recording it doesn't make much sense, or am I missing some important use-case?

**Comment by LittleHuba** [comment]
Cause you can record a talk while you make notes and listen to the talk later on. The annotations should be the visualized content.

**Comment by asanakoy** [comment]
But you cannot record the process of annotation...

**Comment by LittleHuba** [comment]
Yes you can. The audio is associated with the strokes you make during recording. If you click on a stroke with the playback tool it starts the recording from the timestamp when the stroke was made.

**Comment by RichardJActon** [comment]
The feature of having any annotation/notes made during a recording be able to playback the audio from the time at which the note was made was one of my favourite features in OneNote when I used it to take lecture notes as an undergrad. I could just go to a place in my notes and relisten to what the lecturer was saying at the time I made the note! - I'd love to see this feature implemented.

**Comment by LittleHuba** [comment]
It is already implemented 😉 
Just go into settings to the Audio tab and select a directory for saving audio snippets and the correct devices for recording and playback. Then hit the record button (red circle) in the toolbar and start annotating. You can play the audio later by choosing the play object tool (Arrow with a small green play symbol) and clicking on any of the highlighted strokes. The recording will be played from the timestamp associated to the stroke. To start/stop/fast forward the playback see the tools in the toolbar next to the recording button.

**Comment by RichardJActon** [comment]
Awesome, thanks for letting me know! - I couldn't find the audio playback tool and this issue was still open so I assumed it was not implemented yet. FYI it took me an embarrassingly long time to locate the playback tool in the select tooltips dropdown even after you told me it existed. Maybe i'm just slow, but whilst I can see how it is a kind of select tool I think that it would make more sense to place it next to the record button by default to point the first time user in the right direction.

**Comment by LittleHuba** [comment]
So I'll close the ticket as we will not add video recording. It is just too far out of scope.

@RichardJActon the UI desparately needs some tidying up. I thought about a ribbon like revamp but it will take some time till we get there. We are currently bogged down with the new file format, a major rewrite of the internals and fixing bugs in the codebase. We are unfortunately only a small team compared to the size of this app.

**Comment by nail1962** [comment]
> So I'll close the ticket as we will not add video recording. It is just too far out of scope.
> 
> @RichardJActon the UI desparately needs some tidying up. I thought about a ribbon like revamp but it will take some time till we get there. We are currently bogged down with the new file format, a major rewrite of the internals and fixing bugs in the codebase. We are unfortunately only a small team compared to the size of this app.
> 
> If you have any other ideas or questions feel free to reach out to me on Gitter!

I think it is easy to make button that will call kazam for example (l use kazam separately to record video). You do not need to make special program for recording.
