### ISSUE TITLE
Cannot launch Xournal++ on Debian 10

### ISSUE THREAD

**Issue by myshao** [xournalpp/xournalpp#1810]
**Affects versions :**
 - OS: Debian 10.3 (Buster)
 - (Linux only) Desktop environment: Xfce 4.12
 - Which version of libgtk do you use: gtk-3
 - Version of Xournal++: 1.0.17
 - Installation method: dpkg -i xournalpp-1.0.17-Debian-buster-x86_64.deb

**Describe the bug**
When trying to launch xournalpp from command line, I got the following message:

> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card

The program does not start and does not terminate. The whole system got locked, in the sense that
- the mouse stops reacting, while keyboard still works
- the process xournalpp occupies 100% cpu
- the program cannot be terminated by CTRL+C or the kill command (*)
- the system cannot be restarted or shut down in a reasonable time (I wait a few
  minutes then I decided to press the power button...)
If launching the program from xfce menu, the same issue occurs, while no
output messages are seen since there is no terminal window.

**To Reproduce**
1. Execute the command "xournalpp" from terminal.
2. (*) Sometimes CTRL+C works for terminating the program.

**Expected behavior**
I expect the program to start normally.  In fact, I got xournalpp started
normally only once, before I realized that I would not be able to launch the
program again...  So I did not pay attention to the output messages for that
successful launch.

**Additional context**
I guess it would be difficult for the developers to reproduce my issue.
(Perhaps some other Debian user will have the same issue?)
But any suggestions/comments are welcome.

The error messages seem pointing to sound devices.  I know very little about them.
I only know that the speaker and microphone work normally in other programs...

Also one suggestion to the developers:
I am mainly interested in the note-taking functionality, not any sound-related
features.  Is it possible to launch a limited version (e.g., with all
sound-related features turned off) by specifying some command line arguments?

Thanks for your time!

**Comment by Technius** [comment]
There is #1642 but there hasn't been any progress on it recently.

**Comment by myshao** [comment]
Thanks for pointing to me #1642. I was not aware of it.
But I am more interested in getting the program started properly. I still do not know why it worked once, and only once...

**Comment by mennucc** [comment]
I have had a problem, possibly unrelated, but who knows.
When I tried 1.0.17 on Debian Buster, it would often hang and crash, in particular when I tried to use the `TeX` tool. After the crash it it was impossible to start it, and  I had to delete a temporary save from the ~/.xournal directory. 
Note that I am currently using 1.1 (*)) from the development branch, and it never crashed.
Bye. a.
(*) 2020-02-03 commit git 46a4dc82

**Comment by mmeinesz** [comment]
same problem, "Cannot connect to server".
it works fine, but compared to xournal (without pp) the startup takes much longer (2sec compared to 8sec). I think it is waiting for some "server" and then gets a timeout. What server might that be? It is a client only software as far as i see.

**Comment by rolandlo** [comment]
This was fixed in version 1.2.1 via #5068. Just start xournalpp via `xournalpp --disable audio` when you can't otherwise and then head to `Edit > Preferences` and disable audio in the `Audio Recording` tab.
