### ISSUE TITLE
Build problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#1811]
Hi All,
This was building fine on Ubuntu 20.04 until yesterday.  Now I get:

[ 16%] Building CXX object src/util/CMakeFiles/util.dir/serializing/ObjectEncoding.cpp.o
[ 16%] Building CXX object src/util/CMakeFiles/util.dir/serializing/ObjectInputStream.cpp.o
[ 16%] Building CXX object src/util/CMakeFiles/util.dir/serializing/ObjectOutputStream.cpp.o
[ 17%] Linking CXX static library libutil.a
[ 17%] Built target util
make: *** [Makefile:152: all] Error 2

This is after a git pull, cmake ../, make clean, and make.  I'm not good with Makefiles, and couldn't see what was wrong looking at this one.  It could be a problem with Ubuntu 20.04, as they are adding things left and right at this time.  Generally I have found it to work fine though.

Rob

**Comment by lehmanju** [comment]
@frohro As you can probably guess we can't really help you from that log output. Could you provide some more information? Set log output to verbose maybe?

**Comment by Febbe** [comment]
The problem is, that errorcodes can mean everything when the software does not implement a common standard. But when we assume it does, some file is missing.

**Comment by frohro** [comment]
Thanks for the tip about removing the build directory, and starting over.  That solved the issue!
Rob
