### ISSUE TITLE
No check for libopenjpeg in cmake

### ISSUE THREAD

**Issue by dmgerman** [xournalpp/xournalpp#182]
cmake finishes properly, but when I try to build I get this error:

[ 97%] Linking CXX executable xournalpp
/usr/bin/ld: cannot find -lopenjpeg
collect2: error: ld returned 1 exit status
src/CMakeFiles/xournalpp.dir/build.make:469: recipe for target 'src/xournalpp' failed
make[2]: **\* [src/xournalpp] Error 1
CMakeFiles/Makefile2:424: recipe for target 'src/CMakeFiles/xournalpp.dir/all' failed
make[1]: **\* [src/CMakeFiles/xournalpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by andreasb242** [comment]
This should be fixed in master now
