### ISSUE TITLE
Insert page at beginning

### ISSUE THREAD

**Issue by jvwowd** [xournalpp/xournalpp#1820]
**Is your feature request related to a problem? Please describe.**
To my knowledge there is no way to insert a new page at the beginning of a document. I.e. there is no way to insert a page before the first page.

**Describe the solution you'd like**
Maybe an option could be added to the new page drop down menu to choose if the new page should be before or after the current page.

**Describe alternatives you've considered**
I have to cut the contents of the first page, insert a new page, then paste the contents to what is now the second page.

**Comment by Technius** [comment]
There are a few ways to insert a page before the first page:
* Right click the first page in the sidebar and select `Insert Page Before`.
* Alternatively, select the first page and use `Journal > New Page Before`.
* Create a new page after the first page, and then right click the second page and select `Move Up`.
