### ISSUE TITLE
Edit default color palette

### ISSUE THREAD

**Issue by Dolland** [xournalpp/xournalpp#1825]
**Is your feature request related to a problem? Please describe.**
Hi! Can be very useful to be able to edit the default color palette.
In the actual stage, i can set only up to 11 colours on the toolbar, and all of theese are preset, so if i want to set a default pen color to, e.g. #006FFF, i have to go to "choose color" menu and click on that color.
If i change color and want to return to my default color, i've to re-open colors menu.
it's not so fast.

**Describe the solution you'd like**
I would like if you can implement the possibility to change default palette colors, so i want to put #006FFF to my favourites colors, i can do.
Thanks a lot!

**Comment by Technius** [comment]
Related to #1812.
