### ISSUE TITLE
Error: Recorder could not be started

### ISSUE THREAD

**Issue by kaugummiheld** [xournalpp/xournalpp#1826]
Hi, 
I'm using xournal++ for a while, got a graphic tablet to work with it and didn't have any issue up to now. 
Today I wanted to give the record function a try and ran into the Popup-Error "Recorder could not be started." I did not found any other issues or thread about this. 

I then fired up a terminal and the output looks as follows when I start `xounalpp`: 
```ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```
And as such when I press the record button.
```
** Message: 18:50:34.585: Start recording
** Message: 18:50:34.585: PortAudioProducer: Unable to open stream

** (xournalpp:62828): WARNING **: 18:50:34.587: Recorder could not be started.
```
A record directory is set. Can somebody point to where's my error? I'd be glad. 

I'm using an up to date Manjaro on a Thinkpad L13 and installed xournalpp from the community repo via pacman.

**Comment by LittleHuba** [comment]
Could you please check if the device set in the preferences of Xournal++ is an actual microphone? The error says that PortAudio (the underlying library we use for all audio features) is unable to connect to the device. Most likely you have some default device set that is actually not a device at all or has no real device attached.

**Comment by kaugummiheld** [comment]
Thank you for your quick response!
I changed it from system `system default` to `default`, the popup-error disappeared and I can record now. After restarting it automatically chosen `pulse` for both, input and output device, recording still working, 

Just fyi, the command line error messages still exists with these settings. Unfortunately, audio under linux is far over my expertise, so no idea why.

**Comment by LittleHuba** [comment]
You're welcome!
I assume you mean the first block of code in your oroginal issue?
This is written by PortAudio and unfortunately there is currently no way to make PortAudio not output that. You can savely ignore this though as it is only PortAudio checking every possible device for an actual physical device. When it does not find one it complains. 
But as you do not have 20 mics lying around, being connected to each and every possible interface of your machine that is kind of expected :wink:.

**Comment by kaugummiheld** [comment]
I see, makes sense to me. :smile:  
Thank you again for the explanation!
