### ISSUE TITLE
cmake: Could not find boost, but cmake continues, then build fails, but boost is installed

### ISSUE THREAD

**Issue by dmgerman** [xournalpp/xournalpp#183]
I am building from scratch:

(master) dmg@iodine build$ cmake -D BUILD_POPPLER=ON ..
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
...

I get an error from cmake:

..
-- Could NOT find Boost
...

yet cmake ends:

Configuration:
    Compiler:                   /usr/bin/c++
    Overlay Scrollbar enabled:  OFF
    Mathtex enabled:            ON
    CppUnit enabled:            OFF

Unstable features:
    Layers sidebar:             OFF

Static libraries:
    Poppler:                    ON
    Boost:                      OFF
    Glibmm:                     OFF

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dmg/git.w/xournalpp/build

however, when building, boost libraries are not found and linking aborts. Compilation passes, because I have the following boost libraries installed:

root@iodine ~$ dpkg -l | grep boost | grep dev
ii  libboost-atomic1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                                      amd64        atomic data types, operations, and memory ordering constraints
ii  libboost-chrono1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                                      amd64        C++ representation of time duration, time point, and clocks
ii  libboost-date-time1.58-dev:amd64            1.58.0+dfsg-5ubuntu3.1                                      amd64        set of date-time libraries based on generic programming concepts
ii  libboost-dev:amd64                          1.58.0.1ubuntu1                                             amd64        Boost C++ Libraries development files (default version)
ii  libboost-serialization1.58-dev:amd64        1.58.0+dfsg-5ubuntu3.1                                      amd64        serialization library for C++
ii  libboost-system-dev:amd64                   1.58.0.1ubuntu1                                             amd64        Operating system (e.g. diagnostics support) library (default version)
ii  libboost-system1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                                      amd64        Operating system (e.g. diagnostics support) library
ii  libboost-thread-dev:amd64                   1.58.0.1ubuntu1                                             amd64        portable C++ multi-threading (default version)
ii  libboost-thread1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                                      amd64        portable C++ multi-threading
ii  libboost1.58-dev:amd64                      1.58.0+dfsg-5ubuntu3.1                                      amd64        Boost C++ Libraries development files

**Comment by dmgerman** [comment]
Mmm, reading the CMakeLists.txt i foudn that I was missing some packages:

  apt-get install libboost-system-dev 
  apt-get install libboost-filesystem-dev 
  apt-get install libboost-locale-dev 
  apt-get install libboost-iostreams-dev 

I don't know if this is a cmake issue, or a CMakeList.txt one, but I think it would help to be more specific in terms of which package is missing. I found the same issue around the Gnome packages. The message I received was too generic and not specific enough to which specific dependency I was missing.

After that, my build completed successfully.

**Comment by nh2** [comment]
The easiest to install on Debian/Ubuntu is to install all boost libs with a single `sudo apt-get install libboost-all-dev`.

**Comment by andreasb242** [comment]
It's easy to google what packages are missing. I would like to have better messages, but I think this is a pgk-confi (not even cmake) issue, which cannot be fixed by us...

Therefore I close the issue now. If there has somebody a solution please reopen or create a pull request.

**Comment by nh2** [comment]
I'm not sure I understand this.

If I remember correctly, you can explicitly specify the boost sub-dependencies you need, so that CMake fails hard and early if they aren't installed, instead of continuing.
