### ISSUE TITLE
Xournal quits/crashes when I click on preferences

### ISSUE THREAD

**Issue by Kostas-F** [xournalpp/xournalpp#1831]
OS/Versions
----
| | |
|-|-|
 |OS:                              | Ubuntu 18.04.4 
 |Desktop environment: | xfce4
 |libgtk version:              | libgtk-3-0 (3.22.30)
 |Xournal++ version:      | 1.0.17 (12febf7e)

Bug
-----
Whenever I go to Edit -> Preferences Xournal++ closes.

![](https://i.imgur.com/ZiHOcK5.gif)

Unsure if it's something unique to my setup but it did not exist in my version 1.0.15 Ubuntu 16.04 install

**Comment by Febbe** [comment]
how you installed it? Can you try to install it over the ppa?

**Comment by Kostas-F** [comment]
Honestly I don't remember how I installed it. Definitely not the ppa so either from source or a deb package... 
Either way I did something wrong. The version from the ppa (1.1.0) works fine.
