### ISSUE TITLE
Zoom to selected area

### ISSUE THREAD

**Issue by jvwowd** [xournalpp/xournalpp#1832]
**Is your feature request related to a problem? Please describe.**
If a user wants to zoom to a specific area, there isn't an ideal way to do this.

**Describe the solution you'd like**
Have a zoom to selection toolbar button which can be clicked. Once clicked, the user can drag the mouse across a specific area of the screen (as would be done with a selection operation). This will deactivate the toolbar button (similarly to how zoom to fit button is deactivated when the zoom level changes), and the viewport will be such that the user can see all of the selected area and no more (expect what is necessary based on the aspect ratio of the rectangle and the max and min zoom levels (In particular, the rectangle being shown as the user selects should *not* be forced to math the aspect ratio of the viewport.)).

Ideally this could be mapped to clicking with a modifier key.

**Describe alternatives you've considered**
Zooming with the control key and scroll wheel does this to some effect, but it does not handle the horizontal placement of the document very well when zooming in.

**Additional context**
This is distinct from #1114 but could complement it since the feature I am suggesting would make the other easier to use.

**Comment by Febbe** [comment]
Closed this, as it is now handled by #1795
