### ISSUE TITLE
Add color control in plugin interface

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [xournalpp/xournalpp#1835]
**Is your feature request related to a problem? Please describe.**
I want to change the marker color via hotkeys. Since there are not hotkeys/shortcuts I want to implement this in a plugin. However, plugins only can access actions defined in `actionPerformed` (`Color.cpp:392`). However, color isn't handled there: `// nothing to do here, the color toolbar item handles the color` and I can't find another way to access color control via plugin or shortcuts.

**Describe the solution you'd like**
An extension of the plugin interface to allow for (marker) color control would be great.

**Describe alternatives you've considered**

* General hotkeys / shortcuts for controls such as color selection would be nice too and would make my plugin plan obsolete (in a good way).
* Instead of "properly"(?) extending the plugin interface one could just implement an extra function for marker color like was done for background color (`applib_changeCurrentPageBackground` in `luapi_application.h:185`).

**Additional context**
The reason I was trying to make this plugin is that I use a graphics tablet with stylus to write / make presentations now. I has buttons that I would like to use e.g. to cycle through colors or to change tools. 

Edit: I imagined something like this in `luapi_application.h`, I just don't have any idea where to get the necessary ColorToolItem from ...

    static int applib_changeColor(lua_State* L) {
        int color = 1;
        Plugin* plugin = Plugin::getPluginFromLua(L);
        ColorToolItem* cti = ???
        cti->enableColor(color);
    
        return 1;
    }

**Comment by rolandlo** [comment]
A PR for solving this issue is now available #2251.
