### ISSUE TITLE
Error when export a specified page

### ISSUE THREAD

**Issue by anti-destiny** [xournalpp/xournalpp#1840]
**Affects versions : 1.0.17**
 - OS: Windows 8.1
 - Which version of libgtk do you use: In the program folder, I found the file "libgtk-3-0.dll"
 - Version of Xournal++: 1.0.17
 - Installation method: official release

**Describe the bug**
Errors occured when export specified page.

**To Reproduce**
1. Step 1: open the application, draw something on it randomly;  
2. Step 2: open the tab "file", then choose "export as...(Ctrl + E)";  
3. Step 3: input a filename, choose the file type png or pdf.
4. Step 4: a dialog appears. Select the second Item, which means export current page only. Click "OK".
![Dialog](https://user-images.githubusercontent.com/24856363/78537625-59db8000-7822-11ea-874b-7d3b90d5e0f1.png)
5. Step 5: Nothing exported if you choosed file type png. A broken pdf file will be found if you choose to export pdf.

**Expected behavior**
I expected it will produce a png/pdf file on the folder.

**Screenshots of Problem**
![xournalpp_bin.exe stopped](https://user-images.githubusercontent.com/24856363/78538538-bee3a580-7823-11ea-9cd1-6945e7adc9ff.png)
It says that the xournalpp_bin.exe stopped.

**Additional context**
This bug only occurs when export a **specified** page.

**Comment by lehmanju** [comment]
Already fixed in the latest version (master). You might need to compile xournalpp yourself

**Comment by LittleHuba** [comment]
Or use a nightly 😉

**Comment by anti-destiny** [comment]
Thanks. I'll wait for your release.
