### ISSUE TITLE
Breaks when sharing screen (e.g.Skype) on Wayland

### ISSUE THREAD

**Issue by mkhalila** [xournalpp/xournalpp#1841]
**Affects versions :**
 - OS: Manjaro Gnome
 - (Linux only) Desktop environment: Wayland/XWayland/Gnome-Wayland
 - Which version of libgtk do you use: ?
 - Version of Xournal++: 1.0.17
 - Installation method: Manjaro extra repo

**Describe the bug**
When sharing screen (e.g. via Skype) on Gnome Wayland, the app will not display itself or open. When switched to X11, screen sharing with the app works fine.

**To Reproduce**
1. Ensure Wayland is being used
2. Share screen e.g. via Skype
3. Attempt to use the Xournal++ app

**Expected behavior**
Function as normal like with X11

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by lehmanju** [comment]
Skype can not record Wayland applications. Nothing we can do about.
