### ISSUE TITLE
Spline tool initial and maybe final point snap to grid when that is selected?

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#1845]
When I'm drawing with snap to grid using the spline tool, it doesn't start or stop at grid intersections like I want so my lines don't connect as they should.  

When snap to grid is selected, I want the start and end of the spline to end on a grid line so lines can be connected smoothly.

**Comment by rolandlo** [comment]
All the knots (not just the first and last one) should be snapped to grid, I think. Give me a moment. I will implement this together with the floating toolbox issue #1839).

**Comment by frohro** [comment]
Thanks Roland for tackling this for me.  I spent a little time looking at it, but didn't get anything to work, and don't have time to mess with it further at this point.
Rob
