### ISSUE TITLE
Translations for Turkish language

### ISSUE THREAD

**Issue by yasarciv67** [xournalpp/xournalpp#1851]
I completed the Turkish translation in Crowdin on Monday, but it not shown in here. Also, since I could not download the po file in Crowdin, I could not test my translation.

**Comment by Technius** [comment]
There's a big batch of pending translations (#1635) that we'll merge sooner or later. In the meantime, you can test it out by cloning and compiling #1635.

**Comment by Technius** [comment]
#1635 has been merged in master.
