### ISSUE TITLE
I find a PDF which can not be rendered correctly.

### ISSUE THREAD

**Issue by anti-destiny** [xournalpp/xournalpp#1878]
**Affects versions : 1.0.17**
 - OS: [Win 8.1]
 - Which version of libgtk do you use: In the program folder, I found the file "libgtk-3-0.dll"
 - Version of Xournal++: 1.0.17
 - Installation method: official release

**Describe the bug**
I found a pdf file which can be downloaded [here](https://github.com/changgyhub/leetcode_101/blob/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf).
This file cannot be correctly rendered. I opened it with Xournal++ and Adobe Reader, The difference is shown below
![image](https://user-images.githubusercontent.com/24856363/79739407-b9608200-8330-11ea-97db-7e65e18da9d4.png)

**To Reproduce**
1. Download this file;
2. Open this file.

**Expected behavior**
I hope there is no obvious difference when open this file with Xournal++ and Adobe Reader.

**Comment by LittleHuba** [comment]
Looks like an issue in poppler (the library rendering PDFs). First guess would be a missing font. You should look over at their [issue reporting site](https://gitlab.freedesktop.org/poppler/poppler/issues).

Should you file a new issue there, please link it here so we can follow. Thanks!

**Comment by anti-destiny** [comment]
I filed a [issue](https://gitlab.freedesktop.org/poppler/poppler/-/issues/907) in poppler, Please check it, @LittleHuba .

**Comment by Technius** [comment]
Renders fine on my Linux installation, probably just a Windows issue.

**Comment by Arnache** [comment]
I have a similar issue on Linux with a latex pdf file written in English: the font does not disappear but it is changed from latex's to some sans serif font that is difficult to read. Should I also file an issue to poppler?

**Comment by Febbe** [comment]
@Arnache yes, there is nothing we can do to fix that. You could try to install the font on your system.

**Comment by Arnache** [comment]
@Febbe I'll file an issue at poppler's bug tracker. It is not obvious to me that a font is missing, since it displays OK on Okular on the same machine (Ubuntu 18.04).

**Comment by Febbe** [comment]
I don't know enough about the PDF file format itself. But I can imagine, that the font is integrated in the format, but poppler only searches on the system, not in the PDF file. Hopefully it just get fixed by poppler.

**Comment by Arnache** [comment]
Wait: I just tried with the nighly release and the font shows right. The bug occured with the version 1.0.16-3-g1429879c5a I installed via "Ubuntu software" (the orange bag with a stylized A).
