### ISSUE TITLE
Snap to grid stopped working

### ISSUE THREAD

**Issue by superenginegit** [xournalpp/xournalpp#1879]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 19.10
 - (Linux only) Desktop environment: Gnome X11 
 - Which version of libgtk do you use: 3.24.12-1ubuntu1
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
The snap to grid tool is not working.

**To Reproduce**
1. Turn on snap to grid
2. Try drawing a line with start and end on the grid

**Expected behavior**
The start and endpoint should snap to the grid

**Comment by Technius** [comment]
I can't reproduce this. Can you upload a GIF showing what you're seeing?

**Comment by superenginegit** [comment]
![snap_to_grid_not_working](https://user-images.githubusercontent.com/62105577/79908611-14ff3e00-840b-11ea-9129-66751d89ec6a.gif)
This is what I am seeing.

**Comment by Febbe** [comment]
FYI: We reduced the grid snap distance ist now a quarter of the previous distance, so maybe you expect it to snap exactly to the background. There should be 3 extra steps now.

**Comment by superenginegit** [comment]
It's not that, it's far more steps if it's because of that, it's stepless
![Bildschirmfoto von 2020-04-22 00-39-14](https://user-images.githubusercontent.com/62105577/79921149-2a7f6280-8421-11ea-81f0-b134471eeec7.png)

**Comment by superenginegit** [comment]
I fixed it.
The default value 0.25 for snap to grid tolerance caused it. Increasing it to 2.0 fixed it for me.
