### ISSUE TITLE
Opening preferences causes a crash

### ISSUE THREAD

**Issue by paultpearson** [xournalpp/xournalpp#1882]
**Affects versions :**
 - OS: Ubuntu 18.04
 - Gnome 3
 - libgtk-3-0
 - Version of Xournal++: 1.0.17~git20200203.0247-12febf7e-xenial-1
 - Installation method: sudo dpkg -i xournalpp-1.0.17-Ubuntu-xenial-x86_64.deb

**Describe the bug**
When I navigate to the Preferences menu (i.e., select Edit -> Preferences), Xournalpp immediately crashes.

**To Reproduce**
1. Navigate to Edit -> Preferences

**Expected behavior**
Preferences menu would appear and Xournalpp would not crash.

**Screenshots of Problem**
None

**Additional context**
None

**Comment by Technius** [comment]
The Xenial (16.04) package is not compatible with Bionic (18.04). You should either use the AppImage or the PPA.

**Comment by KarlZeilhofer** [comment]
I can confirm this bug on Linux Mint 19.3 (which is based on Ubuntu 18.04). I installed the PPA, now it's fine.

**Comment by Febbe** [comment]
This is not a bug. It's caused by the incompatibility of xenial binaries with  Ubuntu 1804 Linux Mint 19.3 is also based on it. Please use the PPA.
