### ISSUE TITLE
Edit layer names

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#1886]
Hi,

I'm not sure if this would be difficult to implement (regarding the file structure), but it would be really nice, if yo were able to edit the layer names to something which describes the content better than layer 1, layer 2,...

**Comment by Technius** [comment]
This was implemented in #2321 but there is still room for improvement.

**Comment by atticus-sullivan** [comment]
Quite late (just cleaning up my issues), but for me with this renaming functionality this is solved
