### ISSUE TITLE
Text box displayed at wrong position when using image as paper background

### ISSUE THREAD

**Issue by alfkoehn** [xournalpp/xournalpp#1888]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: xfce 4.12 (xubuntu 18.04)
 - Which version of libgtk do you use: output of `dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'` is as follows:

    `ii  libgtk-3-0:amd64             3.22.30-1ubuntu4 amd64        GTK+ graphical user interface library`
    `ii  libgtk-3-bin                 3.22.30-1ubuntu4 amd64        programs for the GTK+ graphical user interface library`
    `ii  libgtk-3-common              3.22.30-1ubuntu4 all          common files for the GTK+ graphical user interface library`
    `ii  libgtk2.0-0:amd64            2.24.32-1ubuntu1 amd64        GTK+ graphical user interface library`
    `ii  libgtk2.0-bin                2.24.32-1ubuntu1 amd64        programs for the GTK+ graphical user interface library`
    `ii  libgtk2.0-common             2.24.32-1ubuntu1 all          common files for the GTK+ graphical user interface library`
    `ii  libgtk3-perl                 0.032-1          all          Perl bindings for the GTK+ graphical user interface library`

 - Version of Xournal++: 1.0.18
 - Installation method: `https://github.com/xournalpp/xournalpp/releases/download/1.0.18/xournalpp-1.0.18-Debian-buster-x86_64.deb` and then double-clicked

**Describe the bug**
Text boxes in a document with an image as page background are displayed at the wrong position (all at the same position). In the side bar preview, the text is displayed at the correct position.

**To Reproduce**
1. Create a new document
2. Journal -> Paper background -> Image
3. Use a png with e.g. 1280x720 pixel
4. Click on the "T" for Text (to write text into the document)
5. write some text
6. click for example on the Hand tool to finish writing text
7. the text box will jump to a certain position (not where you started to write the text). One cannot click on the text box where it appears to be - but if you click on the location where you started to write the text, you can select it (although there is nothing displayed). Note that the text box is displayed correctly in the sidebar preview.

**Expected behavior**
After finishing writing the text, the displayed box should not jump to a certain position.

**Screenshots of Problem**
If that would help, I can try to record a small screencast of the problem and insert it here as a gif/mp4 ?

**Additional context**
This behaviour does not appear in Xournal

Thanks for a great app!

**Comment by rolandlo** [comment]
This will be fixed with #2725
