### ISSUE TITLE
Compilation on Mac

### ISSUE THREAD

**Issue by Istarnion** [xournalpp/xournalpp#189]
I don't know if support for Mac is a wanted feature but wanted to let you know that I managed to compile it on a Macbook Pro running El Capitan with just a few changes:
- I undef'd ENABLE_NLS in xournal-thumbnailer.cpp and XournalMain.cpp as bindtextdomain and textdomain came up as 'use of undeclared identifier' errors.
- All calls to std::abs in InputHandler.cpp came up as ambigous, so I added my own abs function and replaced all the calls to std::abs to that one. Probably a better way to fix this.

Now the software seems to run fine.

**Comment by wbrenna** [comment]
Excellent news! Thanks for documenting. I'll add it to the Wiki - you used the development branch, or master?

**Comment by Istarnion** [comment]
I cloned the master branch.

**Comment by wbrenna** [comment]
I added a page to the wiki - feel free to edit with explicit details if you get the time! 
[Compilation-for-Mac-OS](https://github.com/xournalpp/xournalpp/wiki/Compilation-for-Mac-OS)

**Comment by andreasb242** [comment]
#32 

We have to check if GTK3 is still building - i have a MacBook here. We should create a release and offer it for downloading.

**Comment by TezRomacH** [comment]
Is there any progress about precompiled `.app` release for MacOS?

**Comment by andreasb242** [comment]
Currently not. But if you would like to do, I'll support you.
I have a macbook available, but - as usual - not enough time to everything ;-)

**Comment by morrolinux** [comment]
It does compile flawlessly on MacOS, and I've read that you could build the .app with cmake + cpack 
But I really don't have time for this

**Comment by andreasb242** [comment]
The Problem would probably be to pack the GTK Libraries. But I already solved this for Windows.
A macOS .app is only a folder with some XML and a defined structure, is therefore relative easy to create.

Currently I don't plan to work on this ticket.

**Comment by andreasb242** [comment]
Compiling on Mac is working, Packaging not yet so I close this ticket now
