### ISSUE TITLE
Desktop file is not associated with application

### ISSUE THREAD

**Issue by luyatshimbalanga** [xournalpp/xournalpp#1892]
Missing icon tray on GNOME Shell after starting xournalpp. A [suggested fix from Fedora bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1826395) resolve that issue

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**
Missing icon tray on GNOME Shell after starting xournalpp

**To Reproduce**
1. Start xournalpp

**Expected behavior**
The icon tray should be visible

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
The fix is to add `StartupWMClass=xournalpp` in the desktop file.

**Comment by Technius** [comment]
This might be occurring since `g_set_prgname` is not being called anywhere. https://honk.sigxcpu.org/con/GTK__and_the_application_id.html

**Comment by luyatshimbalanga** [comment]
Thank you for the prompt response!

**Comment by Technius** [comment]
Does this patch fix the bug?
```diff
diff --git a/src/control/XournalMain.cpp b/src/control/XournalMain.cpp
index a3e0c13b..4c4b1fd4 100644
--- a/src/control/XournalMain.cpp
+++ b/src/control/XournalMain.cpp
@@ -258,6 +258,7 @@ auto XournalMain::exportPdf(const char* input, const char* output) -> int {
 }
 
 auto XournalMain::run(int argc, char* argv[]) -> int {
+    g_set_prgname("com.github.xournalpp.xournalpp");
     this->initLocalisation();
 
     GError* error = nullptr;

```

**Comment by luyatshimbalanga** [comment]
> Does this patch fix the bug?
> 
Yes it does.
