### ISSUE TITLE
Additional Layer disappears

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#1893]
**Affects versions :**
 - OS: Linux (Distribution: Arch Linux)
 - (Linux only) Desktop environment: X11 with dwm (windowmanager)
 - Which version of libgtk do you use:
`pacman -Qs libgtk
local/gtk2 2.24.32-2
    GObject-based multi-platform GUI toolkit (legacy)
local/gtk3 1:3.24.18-1
    GObject-based multi-platform GUI toolkit`
 - Version of Xournal++:
`pacman -Q xournalpp
xournalpp 1.0.18-1`
 - Installation method: From the normal arch repository

**Describe the bug**
If you open a pdf in xournal, there are two layers, Layer1 and Background. And you can add additional layers to draw on them. But when I add a new Layer and draw on the new layer, after some time the new layer disappears. What I draw is now all on Layer1 and Layer2 is non existent.

**To Reproduce**
1. Open the pdf
2. Add a new Layer
3. Draw on this (this might work for some time, but eventually the new Layer will be deleted)

**Expected behavior**
What I draw on the new layer should be on the new Layer and it is not supposed to disappear.

I'm not quite sure, if this is enough to trace down the bug, so please let me know if you need any additional output.

**Comment by Munzu** [comment]
Same issue on Windows 10, v1.0.18

**Comment by unhandyandy** [comment]
I'm finding this too, on Ubuntu 20.10.

**Comment by rolandlo** [comment]
Can you check whether this happens on the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) as well?

**Comment by Zikoel** [comment]
I tried to reproduce this issue several time but without success!

OS: `Linux Mint 20.2 Cinnamon`
Which version of libgtk do you use: `3.22.30`
Version of Xournal++: `1.1.1 commit 4f113e94`
Installation method: `AppImage`

Due the old versione affected I suggest to close this issue.

**Comment by rolandlo** [comment]
I'm closing the issue. Reopen if the bug appears in the latest development version.
