### ISSUE TITLE
CTRL-Z deleting the wrong thing while drawing Bezier^WPolygons

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1894]
**Affects versions :**
Linux Ubutnu 18.04, version cb964dc44 

**Describe the bug**
Pressing CTRL-Z while in the middle of drawing a polygon (which should be a Bezier...) acts on the elements added before, not on the last point inserted in the polygon. 

**To Reproduce**

![Peek 2020-04-22 12-48](https://user-images.githubusercontent.com/6414907/79973367-bcc24d80-8497-11ea-91b3-21be064b3afd.gif)

**Expected behavior**

CTRL-Z should delete the last point added in the polygon. And by the way, the icons depicts a Bezier --- and the code is not here. I would advocate using a different icon/name until the tool is ready to draw a Bezier curve... ;-)

**Comment by rolandlo** [comment]
Yes, CTRL-Z acts on the last stroke added to the layer, not the currently drawn polygon/spline. You can delete the last point via the BACKSPACE key. 
Your version only has polygon courses. True Bezier splines have been introduced more recently (commit f3607f5). Update to benefit from it.

**Comment by Rmano** [comment]
> Your version only has polygon courses. True Bezier splines have been introduced more recently (commit [f3607f5](https://github.com/xournalpp/xournalpp/commit/f3607f5dff9d53ecafa3de1ac6ea93d935965fde)). Update to benefit from it

Wow! Didn't notice. Thank you! 

So I will close this because this is not a bug, but intended behavior.
