### ISSUE TITLE
Strokes look bad, touch input draws, stylus button doesn't work on Windows and I had to use OneNote :(

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1900]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows
 - Version of Xournal++: 1.0.18

**Describe the bug**
Touch input draws and the buttons don't react. I messed around with all the possible configurations. It seems that in the input system configuration the pen, eraser, mouse etc. don't point to the right inputs. I also don't know what to tick in Lenovo Pen Settings and Windows Pen settings. No configuration solved it. The app is really unusable like this.

**To Reproduce**
1. Get an X380 Yoga
2. Try to get Xournal++ to work

**Screenshots of Problem**
![grafik](https://user-images.githubusercontent.com/19779511/80134728-75bf7f80-859f-11ea-91e9-a4f53d450e9c.png)

![grafik](https://user-images.githubusercontent.com/19779511/80134851-a7d0e180-859f-11ea-8202-ccb6b2f214a8.png)

![grafik](https://user-images.githubusercontent.com/19779511/80134207-b10d7e80-859e-11ea-91e0-a19545f1471c.png)

![grafik](https://user-images.githubusercontent.com/19779511/80134325-e31ee080-859e-11ea-8b21-015c889ce959.png)

**Comment by LittleHuba** [comment]
Do you have the wintab driver installed? GTK+ does not yet support Windows Ink.

**Comment by coldspark29** [comment]
I downloaded the driver to install. It then said the WINTAB folder already exists. I installed it again. Now I am prompted to reinstall the driver, when I start Xournal++. The message says that the drivers are not the same. Whatever that means - it did not solve the problem. The inputs are still messed up, touch draws strokes and the buttons don't work.

**Comment by LittleHuba** [comment]
You'll have to play with the classes of your input devices then. System aggregated pointer might work better as touchscreen for your purposes for example. This is essentially a problem of GTK+ with Windows as it does not cleanly separate all the input devices. Unfortunately there is not really anything we can do about that. Equally for buttons of your stylus. You'll have to ask the guys from GTK. Most likely they don't recognize your stylus correctly.

**Comment by lf-** [comment]
@LittleHuba I'm having trouble with my Huion H640P, where the stylus buttons don't work (pressure sensitivity works perfectly though) and want to do some investigation before filing a bug. In the same vein as this issue, is there a GTK+ input test tool for Windows so I can figure out where the bug is? Kinda like xev but for GTK and the stylus?

**Comment by LittleHuba** [comment]
There is the GTK demo application. You'll have to build GTK on your machine though. Follow the instructions for compiling Xournal++ on Windows in our repository. Most likely the bug is within GTK itself.

**Comment by rolandlo** [comment]
This should be fixed with the release of Xournal++ version 1.1.0-hotfix.1
