### ISSUE TITLE
Unmet dependency: libzip4

### ISSUE THREAD

**Issue by Lilalas** [xournalpp/xournalpp#1905]
**Affects versions:**
 - OS: Ubuntu 20.04
 - Version of Xournal++: 10.0.18
 - Installation method: official release

**Describe the bug**
Trying to `apt install` the Debian packages of the official release. I get the following error message:
```
The following packages have unmet dependencies:
 xournal++ : Depends: libzip4 (>=1.0.1) but it is not installable
```
I tried all of the following package files with the same negative result:
- `xournalpp-1.0.18-Debian-buster-x86_64.deb`
- `xournalpp-1.0.18-Ubuntu-xenial-x86_64.deb`
- `xournalpp-1.0.16-Debian-buster-x86_64.deb`
- `xournalpp-1.0.16-Ubuntu-xenial-x86_64.deb`

**To Reproduce**
1. Download the DEB file
2. `apt install`

**Expected behavior**
The installation should succeed. The package should not depend on a specific (outdated?) version of `libzip`.

**Additional context**
This is a clean installation of Ubuntu 20.04. The only `libzip` version available on `apt` is `libzip5 (1.5.1-0ubuntu1)`.

**Comment by Technius** [comment]
Our official `DEB` packages currently only support Debian buster/Ubuntu 16.04 at this time. You should use either the PPA, the Flatpak, or the AppImage.

**Comment by Lilalas** [comment]
Thanks for the info! I see you have also updated the `README.md` to incorporate this information. I’m looking forward to a stable branch PPA.

**Comment by Lilalas** [comment]
Thanks for the info! I can confirm that the PPA version installs and launches without problem.

I see you have also updated the `README.md` to incorporate this information. I’m looking forward to a stable branch PPA.
