### ISSUE TITLE
Square shape does not align to grid

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1908]
**Affects versions :**
 - OS: Manjaro
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use 1:3.24.18-1
 - Version of Xournal++: 1.10 + dev 22a0dd89
 - Installation method: AUR

**Describe the bug**
Square shape doesn't align to grid anymore since recent update

**Comment by rolandlo** [comment]
This looks like a duplicate of  #1879.

**Comment by coldspark29** [comment]
Yes, possible
