### ISSUE TITLE
Support for Android Device

### ISSUE THREAD

**Issue by s1-ranjan** [xournalpp/xournalpp#1912]
I am using your product on my Linux computer and I was wondering with one more important feature, for the mobile devices it would be nice if there have been any support for the Android devices.

**Comment by Technius** [comment]
Not going to be possible within any reasonable amount of time. See #256.

**Comment by Rmano** [comment]
Hmmm... I had the original  `xournal`  "more or less" (the X server was really flaky on my tablet)  running on my tablet using  Termux: https://wiki.termux.com/wiki/Graphical_Environment but then I stopped experimenting. @s1-ranjan  if you have time to experiment maybe it could be worth trying...

**Comment by LittleHuba** [comment]
This will be tremendously easier with the new fileformat and rendering library. It will provide the necessary flexibility to draw using native Android libraries. 

It is still some months away though.

**Comment by s1-ranjan** [comment]
@Rmano thanks for suggesting a package, but I wonder how far does it'll be fulfilling xournalpp functionality...

**Comment by TheOneWithTheBraid** [comment]
@s1-ranjan Maybe this might help you: https://github.com/xournalpp/xournalpp/issues/256#issuecomment-661240300
