### ISSUE TITLE
It should be possible to access the Default Button via keyboard shortcut and mouse/pen button

### ISSUE THREAD

**Issue by AxelBoldt** [xournalpp/xournalpp#1913]
The Default Button's usefulness is hampered by the fact that it doesn't have a keyboard shortcut (or does it?) and that one cannot bind the Default action to a mouse or pen button (or can one?).

**Comment by rolandlo** [comment]
This is easily possible using a plugin. Check the [work-in-progress website](https://xournalpp.github.io/guide/plugins/) to learn how to create it.

**Comment by RaulDurand** [comment]
Excuse me but, what is the default button? Is a button in the stylus?

**Comment by AxelBoldt** [comment]
It can be found under Tools/Default Tools and also has an icon (white/green round arrows). It is configured under Edit/Preferences/Defaults.

**Comment by rolandlo** [comment]
It's the "Default Tool", which you can configure in the preferences and activate via button or (in version 1.1.0+dev) via `Shift+Control+D`. It has nothing to do with the stylus.
