### ISSUE TITLE
Corrupted file on closing without warning during pdf export

### ISSUE THREAD

**Issue by anusser** [xournalpp/xournalpp#1916]
**Affects versions :**
 - OS: Linux Debian 9
 - (Linux only) Desktop environment: KDE
 - Which version of libgtk do you use: 3.22.11-1 (I think)
 - Version of Xournal++: 1.0.16
 - Installation method: snap

**Describe the bug**
When editing a pdf (after opening it in xournal via the normal "open" dialogue), and then using "Export as PDF" to export the pdf with annotations, one can close xournalpp _during_ the export without any warning. The pdf file is then corrupted.

**To Reproduce**
See description.

**Expected behavior**
Either refuse to close while exporting pdfs, or warn the user that a pdf is currently exported and if he/she wants to stop the export and close.

**Additional context**
This is very serious as people can lose data by this. I almost lost three hours of work, but fortunately I could recover thanks to the autosave feature.

**Comment by Technius** [comment]
Can you elaborate on what you mean "during the export?" Is this the delay between when you close the file chooser and when the file is actually finished writing to disk?

**Comment by anusser** [comment]
Thanks for this quick response!

Yes, exactly, that's what I mean. I am saving a rather large annotated pdf file where it takes a few seconds, but xournal doesn't stop or warn me when I close it (the program) even though the file is still being written.

I also just tested this in 1.0.17 on Arch Linux and the behavior is the same.

**Comment by tobiasBora** [comment]
I can confirm the bug. If I can provide more info just ask. And the problem seems to occur more often with big pdf containing scans of documents.

**Comment by Rmano** [comment]
I can confirm too, +1.

To reproduce, just open a pdf, so some annotation on it, save the `.xopp`, and then "export as PDF". Then rapidly click on the close button of the window manager. 
It's clearly a race here, but sometimes the PDF comes out corrupted; it's easier to trigger it with big files.

Opening the `.xopp` you will have the "xournalpp crashed, do you want to recover the file" message; if you say yes, you have an error like this:

![image](https://user-images.githubusercontent.com/6414907/98253574-7b007c80-1f7b-11eb-9a92-b58b32df29ba.png)

...and that file must be deleted by hand.

Happening on 1.0.19, Linux Ubuntu 20.04

**Comment by Febbe** [comment]
I couldn't reproduce this with my PDF files and the newest dev version, can you attach a sample pdf here and retest this with the newest version?

**Comment by anusser** [comment]
Thanks a lot for fixing and creating such a wonderful software! :smile:
