### ISSUE TITLE
Problem at compiling

### ISSUE THREAD

**Issue by mesirendon** [xournalpp/xournalpp#192]
Hi guys.

I've been trying to compile the project once more in order to see if loading the settings work again.

I've installed all the dependencies CMake ask for, then I generate and once I `make` I got this at the very end:

```
[ 97%] Linking CXX executable xournalpp
util/libutil.a(XojPreviewExtractor.cpp.o): In function `XojPreviewExtractor::readFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/home/mesi/xournalpp/src/util/XojPreviewExtractor.cpp:115: undefined reference to `Glib::Base64::decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/xournalpp.dir/build.make:485: recipe for target 'src/xournalpp' failed
make[2]: *** [src/xournalpp] Error 1
CMakeFiles/Makefile2:424: recipe for target 'src/CMakeFiles/xournalpp.dir/all' failed
make[1]: *** [src/CMakeFiles/xournalpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

This is the version of Glib I did install:

```
ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by MarPiRK** [comment]
First of all glib is not the same as glibc. These are two separate
libraries. Second, do you have glibmm installed? It should be checked by
cmake, but who knows, maybe something's missing.

10 paź 2016 05:29 "Mesi Rendón" <notifications@github.com> napisał(a):

**Comment by larsschwegmann** [comment]
@mesirendon I currently have the same issue. Did you find a solution? Thanks! 😄

**Comment by andreasb242** [comment]
There were changes on this file, I hope the problem is fixed, if not reopen or create a new ticket.
