### ISSUE TITLE
Page defaults

### ISSUE THREAD

**Issue by unhandyandy** [xournalpp/xournalpp#1922]
I would like to be able to set default page properties, e.g. A5 landscape with grid bg.  I see no way to do this currently, so I have to open a blank file each time I run Xournalpp.

**Comment by Technius** [comment]
There is a `Journal > Configure Page Template` dialog that you can use to configure new pages. Unfortunately, the dialog is poorly-worded (#1524) so you'll have to experiment with the settings.

**Comment by unhandyandy** [comment]
Oh, I missed that, thanks!
