### ISSUE TITLE
AppImage doesn't start

### ISSUE THREAD

**Issue by scroom** [xournalpp/xournalpp#1924]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use: 3.24.18-1ubuntu1
 - Version of Xournal++: 1.0.18
 - Installation method: AppImage
**Describe the bug**
As decribed above.

**To Reproduce**
1. Download the AppImage
2. Make it executable
3. Try to run it

**Expected behavior**
App is running

**Additional context**
error.log is attached
[errorlog.20200502-000750.log](https://github.com/xournalpp/xournalpp/files/4566459/errorlog.20200502-000750.log)

**Comment by MassiminoilTrace** [comment]
On mine, AppImage does not start on Debian, in Plasma KDE
The funny thing is that at the first run it starts, then I click in the toolbar on "edit" and it crashes. From this point, it won't start anymore.
Deleting the entire ~/.xournalapp folder makes it starting again, but the problem repeats.
Error log attached
[errorlog.20200505-183208.log](https://github.com/xournalpp/xournalpp/files/4582177/errorlog.20200505-183208.log)

**Comment by Technius** [comment]
Looks like `libgobject` is not being bundled correctly since the system one is used.

**Comment by MagicFab** [comment]
Same here, but doesn't start at all using Debian 10 (Buster) + GNOME.

**Comment by LittleHuba** [comment]
> Looks like `libgobject` is not being bundled correctly since the system one is used.

That is one issue but it looks like some image ressources are missing as well. At least libpng tries to find a file and fails at some point.

**Comment by Technius** [comment]
Crashing still occurs on 1.0.19 and 1.0.20 (#2555).

**Comment by rolandlo** [comment]
I have tested all the AppImages (1.0.18, 1.0.19, 1.0.20 and 1.1.0+dev) on different Ubuntu versions and on Debian Buster (inside Virtualbox) and can say for all these AppImages:

- They work on Ubuntu 18.04, where it has been built on Azure-pipelines
- They also work on Xubuntu 16.04 (probably on Ubuntu 16.04 as well, although I have not tested that)
- They don't work on Ubuntu 20.04 and Ubuntu 20.10. If the sidebar is set to visible in the settings file (which it is by default) the app will crash on startup. If the sidebar is invisible, then it will crash (among other ways) after opening the preferences or the About dialog (which shows a Xournal++ icon). The error messages are like the ones reported by @scroom. I can make the AppImages work by extracting them (via `--appimage-extract` and commenting out the line `export GDK_PIXBUF_MODULE_FILE="$APPDIR"/usr/lib/gdk-pixbuf-2.0/loaders.cache` in the AppRun file. 
- On Debian Buster the AppImages crash on startup, independently on whether the toolbar is set to visible or not. The errorlogs look like the one provided by @MassiminoilTrace . Moreover on startup I get lots of warnings that the stock icons `image-missing`, `edit-delete`, `go-up` and `go-down`, `window-close` are not present in the gnome theme, before the AppImage crashes.

Some things I have noticed:
- When extracting the Appimages one can observe that there are no files in the `/usr/share/themes` folder, although the Adwaita theme folder is explicitly copied into this folder by the `build_appimage.sh` file. When I create an AppImage on my own Ubuntu 18.04 installation (in Virtualbox) via the same script file, this folder is NOT empty.
Quoting @Technius 

> Newer systems have newer GTK themes that are generally incompatible with the version on GTK in the AppImage, so I decided to bundle Adwaita inside. Hopefully, this won't increase the file size too much.

- On Azure-pipelines the AppImage is created on a Ubuntu 18.04 installation. Among its dependencies there is no `adwaita-icon-theme-full`. 
-  There are some instructions on the [AppImage documentation website](https://docs.appimage.org/packaging-guide/manual.html#bundling-gtk-libraries) for bundling GTK libraries. In contrast to these instructions we do not bundle GLib schemas and Theme engines. Do we need those? Other differences are explained in #1448. 

@TheAssassin Could you please help us figuring out how to make the AppImages work again?

**Comment by TheAssassin** [comment]
> They don't work on Ubuntu 20.04 and Ubuntu 20.10.

Please open an issue resp. check whether https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/7 is the culprit as well. The plugin is kind of "beta" and is looking for contributions. It's seen a few changes recently, some of which seem plausible but haven't really been tested on a variety of systems.

> They also work on Xubuntu 16.04

That seems implausible, if built on 18.04...

In general, if you identify problems, please don't hesitate open issues in the appropriate trackers or check for existing ones.

**Comment by rolandlo** [comment]
> > They don't work on Ubuntu 20.04 and Ubuntu 20.10.
> 
> Please open an issue resp. check whether [linuxdeploy/linuxdeploy-plugin-gtk#7](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/7) is the culprit as well. The plugin is kind of "beta" and is looking for contributions. It's seen a few changes recently, some of which seem plausible but haven't really been tested on a variety of systems.
> 
`linuxdeploy-plugin-gtk` cannot be the culprit, since we do not use it currently. But nice to know that it exists. I will try it out.

**Comment by TheAssassin** [comment]
What would set these environment variables then? linuxdeploy doesn't do that. You must use a custom AppRun script or something like that then.

**Comment by rolandlo** [comment]
Yes, we do. This is our [custom AppRun script](https://github.com/xournalpp/xournalpp/blob/master/azure-pipelines/util/appimage_apprun.sh)

**Comment by TheAssassin** [comment]
The script is pretty broken with regards to escaping. I recommend using shellcheck to avoid such problems.

I guess most of it can be replaced with the GTK plugin, the rest could be written as an AppRun hook (which have been supported by linuxdeploy for a while, and are used by plugins like the GTK plugin, too). This way, you benefit from the community around that plugin, and such fixes will reach a broader audience, too.
