### ISSUE TITLE
adding a new page sometimes shifts focus to beginning of the document

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1926]
**Affects versions :**
I'm using latest version (master) on ubuntu 18.04. 
My documents are usually in landscape format; but this should not be a requirement to see this bug. 

**Describe the bug**
Adding a new page (very often, but not always) via the +page button both adds a new page (this is a good thing), but also moves the user/interface/focus to the first page of the document. 

**To Reproduce**
1. Step 1
Create a new document, and scribble something.
2. Step 2
add a new page; it will be added, but sometimes the interface stays focused on the first page. 
3. Step 3
sometimes a few pages have to be added for this to be observed; also I notice that this happens more often (I think) if one scrolls to the bottom of the "current" page before adding a new one. 

**Expected behavior**
After adding a new page, the page should be added, and now in focus. 

thanks.

**Comment by michaelcadilhac** [comment]
I can confirm this, but same as @petergthatsme , not sure what's the correct recipe.

**Comment by Rmano** [comment]
Yes, it happens to me too. I think that it is related to copy and paste. I will attach a blank file here in a zip).

[Pizarra-Xournal++.zip](https://github.com/xournalpp/xournalpp/files/4581067/Pizarra-Xournal%2B%2B.zip)

Steps:
1. open the file
2. draw something in the first page
3. select it and do ctrl-c
4. go to page 2, ctrl-v
5. go to page 3, ctrl-v
6. optionally click to exit the selection mode (does not change things)
7. add a page, you'll jump to the first one.

![test](https://user-images.githubusercontent.com/6414907/81073479-fd828380-8ee7-11ea-8a12-3ea755008d38.gif)

**Comment by michaelcadilhac** [comment]
I wasn't using copy/paste, but it's good that we have a recipe!  Following exactly @Rmano 's instructions, I do jump back, although not to the top of the first page, but somewhere on the first page.

An easier recipe, for me, seems to open @Rmano 's document, scrolling and selecting the last page, and adding pages repetitively.   This is very erratic; first page is inserted while not moving, second jumps at the beginning, then it alternates between new page and first page, then I can't even follow the pattern :-D

**Comment by Technius** [comment]
Looks like another case of #1658.

**Comment by neldredge** [comment]
I've been trying a little bit to debug this.  It appears that `XournalView::scrollTo` is called on a page whose `dispX` and `dispY` are still zero.  They seem to get set to their correct values only later, within `Layout::layoutPages`.  So I am wondering if this is a race of some kind.

I will keep digging as time permits, but thought maybe this would ring a bell for someone.

**Comment by rolandlo** [comment]
@neldredge 
Great observation! I am also looking into this right now. `Layout::layoutPages` is only called from `gtk_xournal_size_allocate` in `XournalWidget.cpp` and from `ZoomControl::onWidgetSizeChangedEvent`. When inserting a new page (after scrolling to the last page of the document) I observe two different behaviors. Which of the two happens looks random:

A) 
  1) Page is inserted and selected
  2) Scrolling happens
  3) `Layout::layoutPages` is called from `gtk_xournal_size_allocate`
  4) `Layout::layoutPages` is called from `ZoomControl::onWidgetSizeChangedEvent`

B)
  1) Page is inserted and selected
  2) `Layout::layoutPages` is called from `gtk_xournal_size_allocate`
  3) `Layout::layoutPages` is called from `ZoomControl::onWidgetSizeChangedEvent`
  4) Scrolling happens
  5) `Layout::layoutPages` is called from `gtk_xournal_size_allocate`
  6) `Layout::layoutPages` is called from `ZoomControl::onWidgetSizeChangedEvent`

In behavior A) the focus is shifted to the beginning of the document
In behavior B) the focus is shifted to the inserted page

We want to have behavior B), but it seems we must actively trigger `Layout::layoutPages`.

Moreover it looks strange that  `Layout::layoutPages` is always called twice in very short succession (within 1 millisecond). There is no need for that.

I am also wondering why the page is selected before the scrolling. In the code it is written in opposite order, but the scrolling happens with `Util::execInUiThread`, which seems to reverse the order.

@Technius @Febbe Could you explain what the `execInUiThread` thing is about? When and why do we use it?

**Comment by rolandlo** [comment]
@neldredge Could you please test PR  #2312. It seems to almost solve the problem.
