### ISSUE TITLE
Erase stroke location is different from the pen pointer in rotated screen mode

### ISSUE THREAD

**Issue by duyhieubui** [xournalpp/xournalpp#193]
Hello,
I have a surface pro 3 with the default pen. Xournalpp works perfectly in normal (landcape) mode. But when I rotate the screen in the portrait mode, the erase pointer is away from the touched point of the surface pen and the screen. This is a bit annoying.
I'm using archlinux and gnome3.

**Comment by wbrenna** [comment]
And this doesn't happen with the erase pointer in other programs on your surface pro 3? On one of my laptops, I had to link xrandr commands, one for the pen tip and one for the eraser, to the screen rotation activity.

**Comment by duyhieubui** [comment]
I found the problem. My rotation script only set the property for the pen stylus device. Actually, I have to set the property after rotation for all the pen input.

`xrandr -o right;
xinput set-prop 'NTRG0001:01 1B96:1B05 Pen stylus' 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1; 
xinput set-prop 'NTRG0001:01 1B96:1B05 Pen eraser' 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1; 
xinput set-prop 'NTRG0001:01 1B96:1B05 Pen pad' 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1;`
Now it works perfectly.
Thank you.
