### ISSUE TITLE
Cannot build to provide debug info for input related bugs

### ISSUE THREAD

**Issue by jug007** [xournalpp/xournalpp#1931]
**Affects versions :**
 - OS: Linux Mint 19.3
 - Version of Xournal++: 0b85ea6b8bec943d50efd0a349d2478f014f7816

**Describe the bug**
Following https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs on my Linux Mint 19.3 system results in an error.
https://gist.github.com/jug007/2b6704afdd729ce4fa7a3f18c25e0672

**To Reproduce**
1. Follow https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs

**Expected behavior**
Build should finish

**Additional context**
I have the xournalpp PPA added and potentially some packages from ubuntu eoan.

**Comment by Technius** [comment]
Fixed by 13f7a5b.

**Comment by jug007** [comment]
I can confirm that this fixed it.
