### ISSUE TITLE
Xournal 1.10.18 : libzip4 dependencie

### ISSUE THREAD

**Issue by Aisyk** [xournalpp/xournalpp#1938]
Hi,

The latest version of Xournal don't install on a 19.10 based Ubuntu System (PopOS). Both deb have issues when installing.
![Capture d’écran du 2020-05-05 11-05-31](https://user-images.githubusercontent.com/5584650/81050894-1c215400-8ec1-11ea-8788-1763c0fc833b.png)

**Comment by sphh** [comment]
Looks like #2078 ...
