### ISSUE TITLE
Equilateral triangle grid

### ISSUE THREAD

**Issue by Etn40ff** [xournalpp/xournalpp#1942]
Hi,
I would like to add the option to have an equilateral grid line the one in this pdf [file](https://incompetech.com/graphpaper/custom/5mm%20TriDots.pdf) (possibly with the size of triangles being adjustable). Can someone familiar with the codebase give me hints on where to start from?

I know that I can have any pdf as a background but in this way I also hope get grid snapping.
Thanks

**Comment by rolandlo** [comment]
For drawing the grid you would have to write a class TriangleBackgroundPainter inherited from BaseBackgroundPainter. Start from DottedBackgroundPainter.cpp

In the PageType.h enum PageTypeFormat you would have to register your new background type.

For snapping you would have to modify the SnapToGridInputHandler class and the Snapping namespace.
For making the size of triangles adjustable you could use the grid size setting (settings->getSnapGridSize()) which is also used for the square grid.

Hope this helps.

**Comment by Etn40ff** [comment]
Sounds great, thanks. Now I only need to find time to do so :)

**Comment by LittleHuba** [comment]
Alternatively you wait for the new library where you can simply provide an SVG and a few additional settings which generate the background automatically.
