### ISSUE TITLE
desktop file misses StartupWMClass attribute - wrong icon for instances/windows + no grouping of windows

### ISSUE THREAD

**Issue by osirmuggler** [xournalpp/xournalpp#1946]
**Affects versions :**
 - OS: Manjaro Linux
 - Desktop environment: Gnome-Wayland 
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.0.18, commit: 535d261d
 - Installation method: official Manjaro Repository

**Describe the bug**
Application instances/windows of Xournal++ in the "Dash to Dock" Gnome Extension do not use the standard com.github.xournalpp.xournalpp icon, instead a fallback icon is used (in my case the settings gear). Additionally, normally when launching for example multiple Firefox windows, they are collected under one icon with multiple dots appearing next to the icon (see screenshots). For Xournal++ this doesn't happen.

**To Reproduce**
1. install Xournal++ on a system with Gnome as its DE
2. install the Dash to Dock extension (possibly also applies to other indicators for opened applications - I did not test this)
3. add Xournal++ to the favourite applications
4. launch an instance of Xournal++, the described bug should occur

**Expected behavior**
The Xournal++ icon should be used when a new instance is launched and the new instance should be related to the Xournal++ icon. Every additional instance/window should be collected at this one icon in the Dock.

**Proposed fix**
The problem seems to stem from a missing entry in the .desktop file.
When simply adding the `StartupWMClass` attribute, with value `xournalpp`, the system recognises the window as an instance of xournalpp and the expected behaviour occurs. (see again in Screenshots section)
I checked to make sure this wasn't already implemented in the master branch before opening this bug report and it wasn't.

**Screenshots of Problem**
 - expected:
![expected_behaviour](https://user-images.githubusercontent.com/52085040/81207900-98ee2400-8fce-11ea-95f3-f7602f94df88.png)

 - actual:
![xournalpp_behaviour](https://user-images.githubusercontent.com/52085040/81207943-a86d6d00-8fce-11ea-829f-5e7685ebae62.png)

 - after proposed fix:
![fixed](https://user-images.githubusercontent.com/52085040/81208040-c9ce5900-8fce-11ea-833f-151ae5efd541.png)

**Comment by Technius** [comment]
This has already been fixed in `master` branch. See #1892.

**Comment by badshah400** [comment]
This issue seems to have returned to haunt git master (tested at commit 58c823f).

**Comment by Technius** [comment]
Probably due to the startup initialization fix #2252.

**Comment by rolandlo** [comment]
This was fixed in #2881
