### ISSUE TITLE
Clicking "preferences" causes Xournal++ to immediately crash 

### ISSUE THREAD

**Issue by mihirus** [xournalpp/xournalpp#1949]
**Affects versions :**
 - OS: Ubuntu 18.04 LTS
 - Desktop environment: GNOME 
 - Which version of libgtk: libgtk-3-dev (3.22.30-1ubuntu4) 
 - Version of Xournal++: 1.0.18
 - Installation method: Official .deb release from releases page 

**Describe the bug**
When I try to open preferences, the program immediately crashes and exits. No freeze, nothing. 

**To Reproduce**
1. Click "Edit" in the toolbar
2. Click "Preferences" at the very bottom of the dropdown 

**Expected behavior**
The window immediately exits, as if I pressed the "X" button to close it. Like, open a terminal window and press the "X" button. The exact same animation that plays for closing windows, plays when clicking preferences in Xournal++. 

**Screenshots of Problem**
It closes so fast I can't even catch it in a screenshot! 

**Additional context**

**Comment by Febbe** [comment]
This is not a bug, you used an incompatible binary, please use the official PPA.
