### ISSUE TITLE
Cursor size update does not occur when moving from toolbar to page

### ISSUE THREAD

**Issue by idotobi** [xournalpp/xournalpp#1954]
(Please complete the following information, and then delete this line)

**Affects versions :**
 -   Operating System: Arch Linux
      Kernel: Linux 5.6.11-arch1-1
      Architecture: x86-64

 - X11
 - Which version of libgtk do you use: `3.24.20`
 - Version of Xournal++: 1.1.0+dev
 - Installation method: build

**Describe the bug**
The pen/highlighter/eraser-cursors size does not update immediately after moving the cursor back to the page from the toolbar. Only if another type of cursor (e.g. mouse pointer, hand) is triggered in between, by (for example getting out of the page area) the cursor is updated upon reentry.
This does not effect the size of the drawn lines just of the cursor.

**To Reproduce**
1. Change Pen/Highlighter/Eraser cursor size in toolbar
2. Move back to page

**Expected behavior**
Cursor size is update right when moving back to the page.

**Screenshots of Problem**

![xournalpp-cursor_size-update](https://user-images.githubusercontent.com/16611056/81496662-794e4880-92b9-11ea-9c30-eba4ce121c91.gif)

![xournalpp-cursor_size-update_eraser](https://user-images.githubusercontent.com/16611056/81496664-7ce1cf80-92b9-11ea-8623-14d3b37961fd.gif)

**Additional context**

For the pen and highlighter cursor this was introduced by my previous PR #1945 as the size was never updated before.
However the erase had this issue already before.

**Comment by idotobi** [comment]
I'd volunteer to fix this. I'd expect to do it within the next 1-2 weeks.

**Comment by Febbe** [comment]
That would be great, also it would be good, when the cursors will make a sort of review, what they will do if someone uses the tool. E.g. that the highlighter has the exact size and color+alpha of the future highlighting.

**Comment by idotobi** [comment]
> That would be great, also it would be good, when the cursors will make a sort of review, what they will do if someone uses the tool. E.g. that the highlighter has the exact size and color+alpha of the future highlighting.

Yeah, I think this is what should be the expectation. Also this would make it easy to maintain in the future as there's just one commons source of truth then.

**Comment by idotobi** [comment]
> And here something a bit of topic: It looks like you are interested to bring that project forward. Are you also interested to take over some responsibility?
Do you have gitter.im? Then we could chat about that. This would be a better place than in a issue.

I've sent you a message on gitter.im.
