### ISSUE TITLE
Export merge pdf and annotation from command line ?

### ISSUE THREAD

**Issue by jbreizh** [xournalpp/xournalpp#1956]
Hello,
i am using xournal under archlinux to correct the production of my student (lockdown in france). So i have a lot of pdf file + xournal annotation that i have to merge in pdf.
So is it a way to do this from shell ? It seems that xournal has no command line but i can be wrong...
Anyway thanks for your work

**Comment by Technius** [comment]
You can export PDFs with the following command:
```bash
xournalpp my_annotation.xopp -p my_output_file.pdf
```
The command can be combined with `find` or `ls | grep` to easily mass export.

**Comment by jbreizh** [comment]
ok, I rather like to spend time to make a script than doing 100 time the same thing.
Is there some place to find xournal command line manual ? I try `man xournalpp` but there is no manual entry.
Anyway thanks for your time

**Comment by Technius** [comment]
You can run `xournalpp --help` to get some usage information. There's not much documentation, though, so you'll have to play around with the flags.

**Comment by sergeigribanov** [comment]
> ok, I rather like to spend time to make a script than doing 100 time the same thing.
> Is there some place to find xournal command line manual ? I try `man xournalpp` but there is no manual entry.
> Anyway thanks for your time

Hello, I have a python script that allow to merge multiple annotations: https://github.com/sergeigribanov/xoppmerge

**Comment by jbreizh** [comment]
ok i will look at it but i solve my problem with this bash. Maybe not the prettiest but it work

```
#!/bin/bash
dossier="/home/jbreizh/Dropbox/Boulot/1-pedagogique/Confinement/Cours/5eme/DS"

find  "$dossier" -maxdepth 4  -name "*.xopp"  -type f | while read sousdossier ; 
do

#fullfilename=$(basename $sousdossier)
fullfilename=$sousdossier
filename=${fullfilename%.*.*}

echo $fullfilename
echo $filename

xournalpp $fullfilename -p $filename.corrige.pdf

done
```

**Comment by sergeigribanov** [comment]
A nice solution. But my script allow to place annotation in a different layers in a .xopp document. It can be a useful feature. After you can run "xournalpp $fullfilename -p $filename.corrige.pdf" to get a final PDF document. Thank you for another solution!
