### ISSUE TITLE
Xournalpp crash while opening Preferences option in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by NareshModhwadia** [xournalpp/xournalpp#1959]
**Affects versions :**
 - OS: [e.g. Linux (Ubuntu 18.04.1)]
 - (Linux only) Desktop environment: [ Gnome]
 - Which version of libgtk do you use
 - Version of Xournal++: [ 1.0.17]
 - Installation method: [deb file]

**Describe the bug**

xournalpp: symbol lookup error: xournalpp: undefined symbol: _ZN9portaudio6System14DeviceIteratorneERKS1_

**To Reproduce**
1. Run xournalpp from terminal
2. open preferences from Edit menu

**Expected behavior**
It should open preferences dialog box

**Comment by Febbe** [comment]
The used binary is incompatible to ubuntu18.04, please use the PPA
