### ISSUE TITLE
Button-related settings are saved and used in the wrong order.

### ISSUE THREAD

**Issue by lciti** [xournalpp/xournalpp#1961]
**Affects versions :**
 - OS: Linux (Kubuntu 20.04)
 - Version of Xournal++: 1.0.18
 - Installation method: deb from github

**Describe the bug**
The button-related settings entered from the settings dialog are saved and used in the wrong order.

**To Reproduce**
1. Edit->Preferences->Mouse->"**Right Mouse** Button" = "Insert Image"
2. Open .xournalpp/settings.xml, now `<data name=`**`"eraser"`**`><attribute name="tool" type="string" value="image"/></data>`

3. etc.

**Expected behavior**
Saving the settings for, e.g., Right Mouse should affect the behaviour of Right Mouse, etc.

**Additional context**
After a very quick look at the code, I think the problem comes from the fact that in [Settings.cpp](https://github.com/xournalpp/xournalpp/blob/bed6c310f46903c7e3a98b036a0f1bd07593508e/src/control/settings/Settings.cpp) the order of the button settings is inconsistent.
In particular, at line 25 the order is "**middle**", "**right**", "**eraser**", "touch", "default", "stylus", "stylus2" (this order is used in lines 471 and 627 to load/save the `buttonConfig` array from/to the config file) while lines 108-121 and 1458-1470 imply: **Eraser**, **Middle**, **Right**, Touch, Default, Pen button 1, Pen button 2 (this order is used to read from the `buttonConfig` array in the interface methods, e.g. `Settings::getEraserButtonConfig`, that the `Settings` class exposes to the rest of the code).
I suggest the entries in line 25 are reordered as follows:

        constexpr char const* BUTTON_NAMES[] = {"eraser", "middle", "right", "touch", "default", "stylus", "stylus2"};

**Comment by Technius** [comment]
Feel free to submit a pull request fixing the bug. That section of code is poorly-written in general.

**Comment by lciti** [comment]
I actually found that my original problem (could not set the right button to Text) is also due to an additional bug, i.e. missing code to address the case `type == "text"` in `toolTypeFromString` in [ToolEnums.cpp](https://github.com/xournalpp/xournalpp/blob/bed6c310f46903c7e3a98b036a0f1bd07593508e/src/control/ToolEnums.cpp). I have addressed both and I'll submit a pull request fixing the bug.
