### ISSUE TITLE
When annotating a PDF and opening new one, the new one won't show on the paper

### ISSUE THREAD

**Issue by Munzu** [xournalpp/xournalpp#1964]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
I grade homework that is submitted as PDF files. After I'm done grading one, I want to open the next one to annotate. When opening the new one, the paper resizes and the old PDF stays on the page. The new PDF won't load in. I have to close the program and open the new PDF again.

**To Reproduce**
1. Open a PDF with `File` > `Annotate PDF`
2. Annotate the PDF (I do it with the pen tool and my graphics tablet).
3. Open a new PDF with `File` > `Annotate PDF`

Reproduction rate: 100%

**Expected behavior**
The new PDF opens just like the first one.

**Comment by clemdc** [comment]
Same issue on Arch Linux with master

**Comment by michaelcadilhac** [comment]
For me, after opening a new PDF, just going to a different zoom level, scrolling through all the pages to force a reload, and then going back to the original zoom level brings up the new PDF.  Does this workaround do the job for you?

**Comment by Tai-Mai** [comment]
Oh you're right, that does load the new pages in. Interesting. Thanks for sharing. At least now I don't have to restart the program everytime.
