### ISSUE TITLE
Pressure sensitivity sometimes doesn't work

### ISSUE THREAD

**Issue by Munzu** [xournalpp/xournalpp#1965]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
When starting Xournal++, there's a chance that pressure sensitivity doesn't work. 

The buttons on my stylus also don't work as expected. Instead of grabbing the page for scrolling, the button will draw on the page like a left-click.

Simply restarting Xournal++ will solve those problems for that session.

**To Reproduce**
1. Start Xournal++
2. Use stylus to draw on the page / Press stylus button for scrolling the page and try scrolling

Reproduction rate:  10-20%?

**Expected behavior**
Pressure sensitivity should work. Button on my stylus should grab and scroll the page instead of drawing.

**Additional context**
I'm using the Wacom Bamboo tablet.

**Comment by Technius** [comment]
This is probably caused by #659. Unfortunately, there's not much we can do about it.

**Comment by Munzu** [comment]
I see, that's too bad. Let's hope it gets fixed. Thanks!
