### ISSUE TITLE
Recover deleted page

### ISSUE THREAD

**Issue by Arnache** [xournalpp/xournalpp#1966]
**Is your feature request related to a problem? Please describe.**
Page number 237 (12th page of the doc) disappeared while I was adding notes on a pdf. I never pressed Ctrl-Delete (so there may also be a nasty bug in Xournal++ here). It took me a while to notice it, until I reached page 236 and went to the next. I cannot find a way to ask Xournal++ to insert back  page 237 (it had no annotations). When I insert a page using before or after I get a copy of page 236 or 238. 

**Describe the solution you'd like**
A way to get back page 237.

**Describe alternatives you've considered**
Tried to save to pdf and do some merging with the original file, but PDFMod does not seem to work on Ubuntu 18.04. Fortunately PDF-Shuffler did the job. The problem, of course, is that now my  former annotations are preserved but cannot be edited.

**Comment by LittleHuba** [comment]
Please provide your file. We can repair it manually.

**Comment by Arnache** [comment]
Cool! Is the xopp enough or do you want the pdf too? How do I upload a xopp?

**Comment by LittleHuba** [comment]
Just the xopp is enough. You'll have to change the file name to `.txt`

**Comment by Arnache** [comment]
[Yampolsky-notes2.pdf.txt](https://github.com/xournalpp/xournalpp/files/4611303/Yampolsky-notes2.pdf.txt)

**Comment by LittleHuba** [comment]
Are you sure you sent the correct file? This one only has 31 pages which is a lot less than 238...

**Comment by Arnache** [comment]
Yes, the first page is page 227 and the missing page is number 237. Just
before saving this xopp, I duplicated the page 236 so one should just
replace the second 236 (the 11th page of this file) by 237.


Le lun. 11 mai 2020 à 20:32, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
Page 237 should still be there as page 15.

**Comment by Arnache** [comment]
True! Didn't see it.

Any idea how that happened?

Le lun. 11 mai 2020 à 20:52, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
I'd assume you shifted it by accident.

**Comment by Arnache** [comment]
ok, how do I shift it back ?

Le lun. 11 mai 2020 à 22:14, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
On the left of the drawing area you have the different pages as smaller thumbnails. Just right click on a page and you see all the options.

**Comment by Arnache** [comment]
Thanks!

I think I know how I shifted the page by accident : there are arrows on the
lower left:

[image: Screenshot from 2020-05-12 09-35-24.png]
I probably thought they were for navigating, pressed the down arrow 3 times
and saw thought it did not work.
Note that there is a wierd behaviour (I currently have the nightly build of
May 9th): when one presses the arrow the page moves but the view (the one
on the big frame) goes to the first page.

Arnaud.

Le lun. 11 mai 2020 à 23:43, Ulrich Huber <notifications@github.com> a
écrit :

**Comment by LittleHuba** [comment]
> Note that there is a wierd behaviour (I currently have the nightly build of
May 9th): when one presses the arrow the page moves but the view (the one
on the big frame) goes to the first page.

That is a known bug that is already looked into. But thanks for mentioning.
I'll close the issue as the inital problem is solved. If you have any other problems feel free to reach out via another issue or our channel on Gitter.
