### ISSUE TITLE
Modify pageup and pagedown behaviour (possibly as an option)

### ISSUE THREAD

**Issue by Arnache** [xournalpp/xournalpp#1969]
Today, the behaviour of pressing pageup in Xournal++ is to set the focus to the previous page and set the top left of this page on the top of the view frame and if the page is wider than the frame, to the top left. This is fine if the page is not longer than the frame but annoying when I zoomed so that the page is taller. Then I get to the top of the previous page instead of the bottom as I want, /and/ I loose the centering of the text (articles have wide margins, so I zoom a lot and then center the text). A workaround is to press shift-pageup. So to navigate in the document I am annonating (I need to zoom to 2765, for this, working confined with a laptop right now) I have to constantly switch between shift-pageup/shift-pagedown for seeing the rest of the text and non-shifted up/down keys for fine positionning. Every-time I forget the shift or mis-press it when doing page up or page down, I wail (internally). Note that as of today, doing ctrl-page up does the same as page up, whatever the zoom rate is.

**What I'd like**
I'd like either
- page up/down to do the same as shift-page up/down in any circumstances
- page up/down to do the same as shift-page up/down when the zoomed page is taller than the frame
This could be an option if this behaviour is preferred by a minority of users.

**Additional context**
Nightly build of Xournal++ of may 9th 2020
Ubuntu 18.04

**Comment by Arnache** [comment]
Seems to be a duplicate of #1412

**Comment by Technius** [comment]
Closing as duplicate.
