### ISSUE TITLE
Shortcuts for scrolling

### ISSUE THREAD

**Issue by dinojr** [xournalpp/xournalpp#1973]
On Gnome, xsetwacom can't be used to map the buttons on the pad of a tablet to mouse buttons (see [this issue](https:/gitlab.gnome.org/GNOME/gnome-control-center/issues/118))

I could map some buttons to access New Page, Previous Page, Zoom in and Zoom out but it seems scrolling up/down and left/right can only be accessed with mouse wheel and Shit+ mouse wheel.

Accessing these functions with something like "Shift +" and "Shift -" would be very convenient to map them to tablet buttons.

**Comment by dinojr** [comment]
Just figured out that the "hand tool" is designed for this use. Sadly it seems I'm affected by #1501 and cannot use it.

**Comment by Technius** [comment]
You can scroll up/down with up arrow, down arrow, or pg up/pg down.

**Comment by dinojr** [comment]
It's not working for me but the fix for #1501 is working for me, I'm happy with it
