### ISSUE TITLE
Improvement for Icon Naming Scheme

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp#1974]
**Is your feature request related to a problem? Please describe.**
The naming scheme used in xournalpp have some inconsistencies.
![image](https://user-images.githubusercontent.com/51940383/81802809-f2130600-9540-11ea-8e40-75882d94e431.png)

**Describe the solution you'd like**
As you can see here, many of the icon actually already use proper naming scheme, but there are some that simply breaks the rules.
Such as the drawing spline, line, arrow, rectangle, and circle. Their name should've been `draw-x`. `draw-spline`, `draw-rect`, etc. On the side note, the `draw-arrow` icon should've been named such instead of `ruler`.
Same could be said for the `addPage` and `delPage`. They should've been `page-add` and `page-delete`.
The `customize-toolbars` and `manage-toolbars` should've been named `toolbars-customize` and `toolbars-manage`.
The 'lasso' and `rect-select` should've been `select-lasso` and `select-rect`.
On another note, the rotation snapping icon is only named `snapping` which IMO, is incorrect. It should've been `snapping-rotation` and `snapping-grid`.

**Additional context**
This, in my opinion, should be done in relation to #1735 which I'm working on, but, I presume fixing this would involve changing the name coded in the app.

**Comment by rolandlo** [comment]
The file names are coded in ButtonConfigGui.cpp, ToolMenuHandler.cpp and ToolDrawCombocontrol.cpp. It would be easy to replace them. To me your suggestions sound very reasonable.

**Comment by Fatih20** [comment]
> The file names are coded in ButtonConfigGui.cpp, ToolMenuHandler.cpp and ToolDrawCombocontrol.cpp. It would be easy to replace them. To me your suggestions sound very reasonable.

If so, I'll make it part of my pull request.

**Comment by Fatih20** [comment]
I looked into it and turns out there are some other files that needed to be changed too.
`src/gui/dialog/ButtonConfigGui.cpp`
`src/gui/toolbarMenubar/ToolDrawCombocontrol.cpp`
`src/gui/toolbarMenubar/ToolMenuHandler.cpp`
`src/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp`
`src/gui/sidebar/indextree/SidebarIndexPage.cpp`

Putting this out there in case someone wanted to change it too.

**Comment by Fatih20** [comment]
Anywho I've made the change in #1735

**Comment by hyperupcall** [comment]
It looks like this can be closed since #3154 was merged. #1735, as mentioned directly above was superceeded by #2886, which was superceeded by #3154
