### ISSUE TITLE
When I use Highlighter tool with a button on stylus it only allows the usage of a specific color (missing option "Color - don`t change")

### ISSUE THREAD

**Issue by kostyfisik** [xournalpp/xournalpp#1975]
**Affects versions :**
 - OS: Ubuntu Linux 19.10
 - (Linux only) Desktop environment: Gnome
 - Which version of libgtk do you use 3.24
 - Version of Xournal++: 1.1.0-dev
 - Installation method: PPA

**Describe the bug**
When I use Highlighter tool with a button on stylus is only allow usage of black color

**To Reproduce**
1. Set stylus button to become a Highlighter
2. Select Highlighter color to be non-black
3. Try to highlight when it is selected on toolbar
4. Try it via button on stylus.

**Expected behavior**
Use the current color of the Highlighter tool 

*Additional context**

steps 3 and 4 from description above:

![our-final-product](https://user-images.githubusercontent.com/5239997/81811477-59bf5600-952d-11ea-868e-420a350bff3e.gif)

**Comment by rolandlo** [comment]
I can't reproduce this behaviour. Are you sure you set the highlighter color to something else than black in the pen settings? Could you post a picture of your pen settings, please?

**Comment by kostyfisik** [comment]
See new screencast with switch from HL to pen and back using a mouse (everything is OK) and stylus (the HL color is reset to black as soon as I use pen button)
![our-final-product](https://user-images.githubusercontent.com/5239997/81830060-44a1f180-9544-11ea-92bc-20a288b8234b.gif)

**Comment by rolandlo** [comment]
Still this doesn't answer what you have in the settings. Look at my settings then:
![image](https://user-images.githubusercontent.com/40485433/81831373-8da27780-953d-11ea-8760-c3eb4d1e34a5.png)
The pen buttons are mapped to the highliter with yellow and violet color (see on the right). If you have black color selected there, you will get a black highliter, whenever you use the pen button. It doesn't matter what you have selected in the toolbar when you use the highliter via pen button. All that counts is what is in your settings.

**Comment by kostyfisik** [comment]
Ok, I see. So, it is a missing default option for "Color - don`t change". 

It`s a bit strange (and non-consistent) to allow one parameter (thickness) of highlight to be unchanged (by default) and to force to set another to a specific value. This can be treated as UX bug.

A side note that I needed a second look to find a black color choice box using dark theme :)

See my options.

![Screenshot from 2020-05-13 23-33-46](https://user-images.githubusercontent.com/5239997/81862558-906b8f80-9572-11ea-8e84-3bbcb3757b82.png)

**Comment by idotobi** [comment]
@kostyfisik : I've been working on #2004 and I think it should solve your issue. 

It basically allows you to have an independent color set for (1) the tool that you selected via the toolbar and (2) the tool you selected by pressing the stylus button. Thus, you can change the color of the stylusbutton tool while the stylusbutton is pressed.

![animation](https://user-images.githubusercontent.com/16611056/86496599-77b37500-bd7e-11ea-853f-0c7399f7aa50.gif)

Would you consider this a fix to your problem?

**Comment by kostyfisik** [comment]
@idotobi Great! I would like to test it in release :)

**Comment by kostyfisik** [comment]
@idotobi I've checked it, now it wokrs fine (convinient from my point of view), however, it is a mess with settings. Probably you need to disable color choice option (as soon as it only depends from the current choice from the toolbar).

**Comment by idotobi** [comment]
@kostyfisik : Sorry I don't get it :sweat_smile:  What do you mean with "it is a mess with settings". Since I usually don't use the highlighter through one of the buttons I might have overlooked a usecase.

**Comment by kostyfisik** [comment]
@idotobi My settings look like this:
![Screenshot from 2020-10-08 09-01-04](https://user-images.githubusercontent.com/5239997/95420903-f8b57600-0944-11eb-8319-d0e0f0ecd11d.png)
however, at the moment the color used for the higligher tool does not depend on this.
