### ISSUE TITLE
Appimage crashes while I'm trying to open a file.

### ISSUE THREAD

**Issue by bitsandscraps** [xournalpp/xournalpp#1978]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.18
 - Version of Xournal++: 1.0.18
 - Installation method: Appimage

**Describe the bug**
When I click Open and traverse around some directories, it suddenly crashes.

**To Reproduce**
1. Click File > Open.
2. Go through the directory hierarchy to reach the file you want to edit.
3. It suddenly crashes.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Currently using [appimaged](https://github.com/AppImage/appimaged).
I think Korean file names are causing the problem.
It seems to work well when all of the files and subdirectories have English names.

Here's the error log.

Date: Thu May 14 23:43:43 2020
Error: signal 11
[bt]: (0) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp() [0x5b97b8]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f430b63b210]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(+0x18e6b6) [0x7f430b7836b6]
[bt]: (3) /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1baa5) [0x7f4308779aa5]
[bt]: (4) /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1bf5c) [0x7f4308779f5c]
[bt]: (5) /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1c151) [0x7f430877a151]
[bt]: (6) /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(png_process_data+0x3b) [0x7f430877a2cb]
[bt]: (7) /tmp/.mount_xourna6otc2N/usr/lib/gdk-pixbuf-2.0/loaders/libpixbufloader-png.so(+0x2b99) [0x7f42f80fcb99]
[bt]: (8) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0x10281) [0x7f430ceee281]
[bt]: (9) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_loader_write+0x1ba) [0x7f430ceeed5a]
[bt]: (10) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_new_from_file_at_scale+0x176) [0x7f430ceebfd6]
[bt]: (11) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1b6cfb) [0x7f430d71dcfb]
[bt]: (12) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1b5498) [0x7f430d71c498]
[bt]: (13) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1ba7b8) [0x7f430d7217b8]
[bt]: (14) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1ba82a) [0x7f430d72182a]
[bt]: (15) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1292d8) [0x7f430d6902d8]
[bt]: (16) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_hash_table_foreach+0x68) [0x7f430df03058]
[bt]: (17) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1291ab) [0x7f430d6901ab]
[bt]: (18) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x12e7a9) [0x7f430d6957a9]
[bt]: (19) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x219a43) [0x7f430d780a43]
[bt]: (20) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7f430ccb1a56]
[bt]: (21) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1038) [0x7f430ccd0b28]
[bt]: (22) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f430ccd10d3]
[bt]: (23) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_cell_area_apply_attributes+0xb6) [0x7f430d691d16]
[bt]: (24) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3307ed) [0x7f430d8977ed]
[bt]: (25) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x332357) [0x7f430d899357]
[bt]: (26) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3329e6) [0x7f430d8999e6]
[bt]: (27) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3389e5) [0x7f430d89f9e5]
[bt]: (28) /tmp/.mount_xourna6otc2N/usr/lib/libgdk-3.so.0(+0x273c8) [0x7f430d2a93c8]
[bt]: (29) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f430df14e8e]
[bt]: (30) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7f430df15240]
[bt]: (31) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7f430df15533]
[bt]: (32) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_dialog_run+0x160) [0x7f430d6ee420]
[bt]: (33) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN10XojOpenDlg9runDialogEv+0xcc) [0x4db07c]
[bt]: (34) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN10XojOpenDlg14showOpenDialogEbRb+0x20f) [0x4db55f]
[bt]: (35) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN7Control8openFileE4Pathib+0x1c9) [0x493a19]
[bt]: (36) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN7Control15actionPerformedE10ActionType11ActionGroupP9_GdkEventP12_GtkMenuItemP14_GtkToolButtonb+0xb1c) [0x49625c]
[bt]: (37) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN12AbstractItem9activatedEP9_GdkEventP12_GtkMenuItemP14_GtkToolButton+0xee) [0x565e4e]
[bt]: (38) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7f430ccb1802]
[bt]: (39) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x28814) [0x7f430ccc5814]
[bt]: (40) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x10ae) [0x7f430ccd0b9e]
[bt]: (41) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f430ccd10d3]
[bt]: (42) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_widget_activate+0x6e) [0x7f430d8ba0de]
[bt]: (43) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_menu_shell_activate_item+0x106) [0x7f430d797746]
[bt]: (44) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x230a74) [0x7f430d797a74]
[bt]: (45) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x21309a) [0x7f430d77a09a]
[bt]: (46) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7f430ccb1a56]
[bt]: (47) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7f430cccfdd1]
[bt]: (48) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f430ccd10d3]
[bt]: (49) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x350c3c) [0x7f430d8b7c3c]
[bt]: (50) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x2103be) [0x7f430d7773be]
[bt]: (51) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_main_do_event+0x72c) [0x7f430d7791bc]
[bt]: (52) /tmp/.mount_xourna6otc2N/usr/lib/libgdk-3.so.0(+0x5ad92) [0x7f430d2dcd92]
[bt]: (53) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f430df14fbd]
[bt]: (54) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7f430df15240]
[bt]: (55) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7f430df15533]
[bt]: (56) /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_main+0x85) [0x7f430d778395]
[bt]: (57) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x8c2) [0x4ac442]
[bt]: (58) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(main+0x30) [0x480560]
[bt]: (59) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f430b61c0b3]
[bt]: (60) /tmp/.mount_xourna6otc2N/usr/bin/xournalpp(_start+0x29) [0x480719]

Try to get a better stracktrace...
[bt] #1 /tmp/.mount_xourna6otc2N/usr/bin/xournalpp() [0x5b9b8d]
/home/vsts/work/1/s/build/../src/util/CrashHandlerUnix.h:102
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f430b63b210]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(+0x18e6b6) [0x7f430b7836b6]
??:0
[bt] #4 /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1baa5) [0x7f4308779aa5]
??:0
[bt] #5 /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1bf5c) [0x7f4308779f5c]
??:0
[bt] #6 /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(+0x1c151) [0x7f430877a151]
??:0
[bt] #7 /tmp/.mount_xourna6otc2N/usr/lib/libpng12.so.0(png_process_data+0x3b) [0x7f430877a2cb]
??:0
[bt] #8 /tmp/.mount_xourna6otc2N/usr/lib/gdk-pixbuf-2.0/loaders/libpixbufloader-png.so(+0x2b99) [0x7f42f80fcb99]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0x10281) [0x7f430ceee281]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_loader_write+0x1ba) [0x7f430ceeed5a]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_new_from_file_at_scale+0x176) [0x7f430ceebfd6]
??:0
[bt] #12 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1b6cfb) [0x7f430d71dcfb]
??:0
[bt] #13 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1b5498) [0x7f430d71c498]
??:0
[bt] #14 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1ba7b8) [0x7f430d7217b8]
??:0
[bt] #15 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1ba82a) [0x7f430d72182a]
??:0
[bt] #16 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1292d8) [0x7f430d6902d8]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_hash_table_foreach+0x68) [0x7f430df03058]
??:0
[bt] #18 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x1291ab) [0x7f430d6901ab]
??:0
[bt] #19 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x12e7a9) [0x7f430d6957a9]
??:0
[bt] #20 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x219a43) [0x7f430d780a43]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7f430ccb1a56]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1038) [0x7f430ccd0b28]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f430ccd10d3]
??:0
[bt] #24 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(gtk_cell_area_apply_attributes+0xb6) [0x7f430d691d16]
??:0
[bt] #25 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3307ed) [0x7f430d8977ed]
??:0
[bt] #26 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x332357) [0x7f430d899357]
??:0
[bt] #27 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3329e6) [0x7f430d8999e6]
??:0
[bt] #28 /tmp/.mount_xourna6otc2N/usr/lib/libgtk-3.so.0(+0x3389e5) [0x7f430d89f9e5]
??:0
[bt] #29 /tmp/.mount_xourna6otc2N/usr/lib/libgdk-3.so.0(+0x273c8) [0x7f430d2a93c8]
??:0
[bt] #30 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f430df14e8e]
??:0
[bt] #31 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7f430df15240]
??:0

**Comment by armsp** [comment]
I have the exact same issue. I don't think it has got anything to do with language cause for me everything is in English only.

**Comment by rolandlo** [comment]
Does this still happen with the latest version? Download from https://github.com/xournalpp/xournalpp/releases/tag/nightly

**Comment by bitsandscraps** [comment]
> Does this still happen with the latest version? Download from https://github.com/xournalpp/xournalpp/releases/tag/nightly

I think it works now.
