### ISSUE TITLE
Zooming with Ctrl+Scroll scrolls down the page

### ISSUE THREAD

**Issue by Munzu** [xournalpp/xournalpp#1984]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
When holding Ctrl and scrolling, zooming in simultanenously scrolls down the page. Conversely, zooming out scrolls up.

**To Reproduce**
1. Hold Ctrl
2. Scroll up/down

Reproduction rate 100%

**Expected behavior**
I expect to zoom in and out of the center of the screen

**Additional context**
I saw that there was an issue of the same problem in version 1.0.16 (#1753) but apparently it had been fixed and closed. I wasn't sure whether to comment on the old one or open a new one. If I did it wrong, I apologize.

**Comment by MisterPresident** [comment]
I think the expected behavior should be that it zoom to the Position the cursor is placed on.

**Comment by Tai-Mai** [comment]
Yes, you're right

**Comment by Technius** [comment]
We fixed it on master branch (#1830) but ended up causing another bug (#1935), so we still need to iron out the issue some more before we can bring the fix to the 1.0.x releases.
