### ISSUE TITLE
Add snap to installs methods?

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1985]
**Affects versions :**
 - OS: Linux (ubuntu)

**Describe the bug**
The current readme.md does not include instructions to install via snap, which is a very easy method, and provides updates, etc.. I would recommend adding it, or perhaps explaining why other methods are preferred. 

The snap info can be found here: https://snapcraft.io/xournalpp

The command-line install command is `sudo snap install xournalpp`

**Comment by LittleHuba** [comment]
Would you mind supplying a PR with the necessary information?

**Comment by markwmuller** [comment]
Done :)

**Comment by LittleHuba** [comment]
Thanks!

**Comment by Technius** [comment]
Note that this snap is 3rd party--we can't provide any support for it.
