### ISSUE TITLE
Merge annotations from multiple sources

### ISSUE THREAD

**Issue by sergeigribanov** [xournalpp/xournalpp#1987]
Hello! I think that a feature that allows you to merge .xopp files from various sources would be very useful. In particular, this feature is necessary for annotating the same .pdf file by different referees. Moreover, this feature is very relevant at the moment, during COVID-19. So, for example, I have to check PDF files with student exams together with other professors. After checking, the comments must be mergedt. At the moment, I use my own python script to merge .xopp files:
https://github.com/sergeigribanov/xoppmerge

More over, it would be nice to add the ability to merge .xopp
files in a console mode using regular expressions.

Thank you,
Sergei

**Comment by LittleHuba** [comment]
This feature will be part of the new fileformat. We base it on the [Automerge](https://github.com/automerge/automerge) algorithm for exactly this reason.

**Comment by sergeigribanov** [comment]
Thank you!
