### ISSUE TITLE
Humongous file size when document contains images 

### ISSUE THREAD

**Issue by sm8ps** [xournalpp/xournalpp#1988]
**Affects versions :**
 - Ubuntu 19.10
 - Xournal++ 1.1.0+dev (compiled May 15 2020 21:03:08)

**Describe the bug**
When including a single JPG image of e.g. dimension 960x702 pixels, the file size leaps up to 1.5 MB which is 2 MB without GZip compression. This corresponds to a 960x702 RGB bitmap image.

**To Reproduce**
1. Include a JPG image of dimension XxY into an empty Xournal++ document
2. Save as XOPP file
3. Uncompress GZipped XOPP file
4. Compare size to X*Y*3 B.

**Expected behavior**
I did expect Xournal++ to use disk size more efficiently. Embedding several images of WXGA-dimensions 1280x800 results in 3 MB disk usage per image.

**Additional context**
I see the point in embedding images pixel per pixel, though I would hope to have some more efficient compression for images. Maybe linking to image files that could be included in the GZip-archive? -- This all may have been discussed already though I have not found any related issue report yet.

**Comment by LittleHuba** [comment]
This is a known bug. Currently images are saved without compression as a Base64 string. The new file format will store images as blobs making this more efficient. Modifying the current format is not worth it anymore.

**Comment by sm8ps** [comment]
Thanks for your reply! Good to hear that a new file format is in the cooking, I am looking forward to it. The speed development is really impressive. Thanks to all the developers!

**Comment by LittleHuba** [comment]
Oh don't understand me wrong, we will still take quite some time until it is released but changing this behaviour in the current format would also take weeks if not months as it is quite tricky and changes to the file format have to be done with a lot of care...

**Comment by sm8ps** [comment]
That is well understood here and the current format works perfectly up to the few cases where I embed large images. My work-around is to shrink the image resolution down to a reasonable size before embedding.
I fully see the difficulties in changing the file format. So I understand that it is going to take some time. Nevertheless it is just good to know that progress lies ahead and that capable minds are taking care of such issues. Thanks again for keeping Xournal++ sailing ahead!
