### ISSUE TITLE
Make use of file versioning

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#1990]
**Is your feature request related to a problem? Please describe.**
Currently, there are a number of issues waiting on the new file format. Since there will be some time until it will be ready, we can accommodate some minor feature requests. However, we need to keep backwards compatibility as well as _forwards compatibility_ in mind. There is no code that checks if loaded files are actually supported by the version of Xournal++ loading it. This can be problematic if we introduce a new feature down the road (e.g. improved rotation support (#918) or journal-specific LaTeX settings (#1115)), as older versions of Xournal++ will fail loading or completely ignore the new features.

**Describe the solution you'd like**
A file format version is already stored in generated files, but we are not making use of it. A "supported file version" should be set at compile time. When loading an annotation file, we should check that the file's version is less than or equal to the supported file version. Otherwise, we should show a warning to the user and ask if they still want to load the file.

**Describe alternatives you've considered**
Wait for the new file format, but this means that we can't make any changes in _right now_.

**Additional context**
I have an accompanying PR that will follow shortly.

**Comment by LittleHuba** [comment]
Problem is that you can't modify older versions of the app to include this. You would need two versions by the way. A lower and an upper supported version.

**Comment by Technius** [comment]
> Problem is that you can't modify older versions of the app to include this.

Better late than never. If this is a large concern, we can change the file format slightly to make it impossible to load files generated by versions starting from the next release (e.g. by adapting the file format to a bare-bones "packaged file format" that makes use of the current annotations/data structures).

> You would need two versions by the way. A lower and an upper supported version.

The point of focus here is the upper supported version since we cannot change older releases to be forwards compatible. In contrast, we can always add code to newer releases for backwards compatibility.
