### ISSUE TITLE
Custom toolbar submenus for the pen and new page don't work until restarting xournalpp

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#1992]
Hi All,
I spent a  few minutes making a custom toolbar to fit my use case.  I find that on the pen and the new page, there is a down arrow menu selector that seems to do nothing when I click it.

Steps to reproduce:

- Go to View->Toolbars->Customize
- Remove the create new page or pen tool
- Replace it
- Close customize toolbar window
- Try to use the toolbar submenu
- Note nothing happens

Here is a screenshot when you do this.
![2020-05-17_12-09](https://user-images.githubusercontent.com/994565/82157597-3f3ff200-9837-11ea-98a0-24cca7480f68.png)

It works fine after restarting xournalpp.

**Comment by bhennion** [comment]
This seems to have been fixed in 1.2.1. Please reopen if you still encounter this issue with the latest version.
