### ISSUE TITLE
Strange (new) location of config files?

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1999]
**Affects versions :**
 - Linux Ubuntu 18.04, Gnome-X11
 - Version of Xournal++: a26797b4aed
 - Installation method: compiled by source
 - Run method: in the build directory, using `./src/xournalpp` to check before installing

**Describe the bug**

The application informed me that the config files were moved (good and nice!) to `.config/com.github.xournalpp.xournalpp` (?).

This could be ok, but all the other applications I have installed use a `.config/app-name` directory, like `.config/xournalpp`.

**To Reproduce**

1. Compile
2. Execute `./src/xournalpp`

**Expected behavior**

All the other application follow the `.config/xournalpp` style of config directory

**Screenshots of Problem**

![2020-05-20_13-15](https://user-images.githubusercontent.com/6414907/82441000-88917b00-9a9d-11ea-9439-16010fdaa5ea.png)

**Comment by Technius** [comment]
This was fixed by #2252.
