### ISSUE TITLE
poppler-config.h missing on Ubuntu 16.04

### ISSUE THREAD

**Issue by niosus** [xournalpp/xournalpp#200]
I am trying to build the master branch on Ubuntu 16.04 and it seems that `poppler-config.h` is missing here. I have installed it with `sudo apt-get install libpoppler-glib-dev`, and I see folder `/usr/include/poppler/gtk` but not the `poppler-config.h` file in this folder. Is this a known issue?

UPD: the CMake error in case it is of interest:
```
-- Checking for modules 'poppler;poppler-glib'
--   Found poppler, version 0.41.0
--   Found poppler-glib, version 0.41.0
-- Could not find poppler include dir
CMake Error at cmake/find/FindPoppler.cmake:74 (file):
  file STRINGS file
  "/home/igor/Code/xournalpp/POPPLER_INCLUDE_DIR-NOTFOUND/poppler-config.h"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)
```

But the reason is described in the first sentence.

**Comment by niosus** [comment]
Seems that there is just a need to install `libpoppler-private-dev` in addition to other packages. This seems to solve the issue for me.

**Comment by K0ertis** [comment]
Hi! Could you explain how you build it?

**Comment by niosus** [comment]
Yes, sure. Just the way it is stated in the readme. But again, I have built it successfully after installing the missing library.
