### ISSUE TITLE
Can we insert code snippets, with syntax coloring and proper alignment.

### ISSUE THREAD

**Issue by piyush2989** [xournalpp/xournalpp#2001]
Hi,

Is there a way to insert code fragments in the page. I just want to copy a piece of code and keep next to my note. I see it all gets converted to normal text.

Regards,

**Comment by Technius** [comment]
I would also like this, but it would be complicated to implement as a first-party feature.

Once #1952 is merged, you can use the LaTeX tool in combination with the `listings` package to typeset your code.

**Comment by rolandlo** [comment]
Now #1952 is merged and in case you update to the latest version, you can have syntax coloring as pointed out by @Technius . Just add `\usepackage{listings}` and your style definitions to your global template file (see LaTeX panel in the settings). Inside the LaTeX formula start and end with a $-sign to exit and reenter math mode, see here: 
![grafik](https://user-images.githubusercontent.com/40485433/90554353-0432bf00-e196-11ea-9eb2-96fc032255fd.png)
