### ISSUE TITLE
[Regression] Erasing with Pen Button isn't directly executed

### ISSUE THREAD

**Issue by jaykijay** [xournalpp/xournalpp#2003]
**Affects versions :**
 - OS: Archlinux
 - KDE
 - Which version of libgtk do you use: 1:3.24.20-1
 - Version of Xournal++: 1.1.0+ (a26797b4)
 - Compiled from AUR

**Describe the bug**
In the last Version i used (like 2Months old) everything worked fine. 
Now when i set the first pen button to be a eraser (erase whole lines) it does not erase it directly but just after i stopped pressing the Button. This is very uncomfortable.
If i choose the eraser tool manually it works perfectly fine..
I made a small gif to show the issue: First step: Erasing with Button, second Step: Erasing with manually choosing the tool.

**To Reproduce**
1. Configure Pen Button 1 to be a eraser
2. Write something
3. Press the button to delete it

**Expected behavior**
It should be deleted directly while still pressing the button. As it was before.

**Screenshots of Problem**

![Peek 2020-05-21 13-55](https://user-images.githubusercontent.com/24495677/82560936-ad0b5700-9b72-11ea-9c1b-07c2dde9e602.gif)

**Comment by 4VRDriver** [comment]
I can confirm this issue, but it only appears when the new input system is enabled. Try to disable it under Settings > Input system.

In my case the behaviour is slightly different: If the new input system is enabled, no strokes will be erased whatsoever even after letting the button go.

**Comment by Technius** [comment]
I can't reproduce this on my computer. Can one of you run `git bisect` to find the bad commit?

**Comment by 4VRDriver** [comment]
I did `git bisect` and in my case it narrows down to commit `baabf791a21aadbec9344558565ab8ad6ee26fb7`, so around when the new input system was added.  (so bisect wasn't a big help I guess :P)

But I have found something else that could be very interesting: There is a setting in the KDE wacom settings called "Tap to execute action". (where my cursor is)
![Screenshot_20200522_140938](https://user-images.githubusercontent.com/44267643/82666643-9d554680-9c36-11ea-93d9-b4c902b9be2c.png)

If this is selected and the old input system is enabled it behaves just as expected. But enabling the new input system causes to not to be able to erase strokes whatsoever by pressing the stylus button.

If this checkbox is not selected and the old input system is enabled, strokes get erased when the stylus isn't even touching the tablet. By enabling the new input system however, the eraser behaves now as expected (erasing only when the stylus is touching the tablet and by pressing the button).

So there is a small contradiction in the setting in my opinion.

**Comment by 4VRDriver** [comment]
Ok, there is already an setting for that problem... I must've missed that.
![Screenshot_20200523_120053](https://user-images.githubusercontent.com/44267643/82727833-35156c00-9ced-11ea-9cb9-54f3fc333582.png)
Does this fix your issue @jaykijay?

It may be a nice feature if Xournalpp would try to figure this out by itself and ask the user at the first run if it should set this setting.

**Comment by jaykijay** [comment]
Hi,
thanks for you posts :)


> Ok, there is already an setting for that problem... I must've missed that.
> Does this fix your issue @jaykijay?

-> As my Pen does return "off" for TabletPCButton i didn't set this setting. I tried it now and it does not change anything in this issue, so no, it does not solve it :(

Changing the driver settings like you mentioned before did not help either..

I did a really long git bisect which ended up to this:

> 98f54598240ad0abf46641261a9faafd6a5b7af6 is the first bad commit
>commit 98f54598240ad0abf46641261a9faafd6a5b7af6
>Author: tobidot <16611056+idotobi@users.noreply.github.com>
>Date:   Mon May 11 18:53:42 2020 +0200
>
>   Fixed cursor update to apply always
>  
>    Root Cause:
>   The functions createHighlighterOrPenCursor and getEraserCursor were
>    returning early if the cursor type had not changed. This prevented the
>    updated of the cursor size, based on the new setting.
>
> src/gui/XournalppCursor.cpp | 9 ---------
> 1 file changed, 9 deletions(-)

So i think.. that commit is the bad one, i don't know why but git bisect did a really great Job here and showed the real culprint.

**Comment by Technius** [comment]
Looks like the erased region is not being rerendered for some reason.

**Comment by tablesturn** [comment]
I can confirm this bug. Also, the same happens for me when I move hand-written stuff (e.g. selecting by region, then moving - also when only using the mouse).

**Comment by tablesturn** [comment]
I just found out that he bug does only occur in large documents.
