### ISSUE TITLE
cursorHighlight settings not available on Windows

### ISSUE THREAD

**Issue by singinwhale** [xournalpp/xournalpp#2006]
On Linux you can change the radius and border size/color of the cursor highlight but on Windows the settings are unavailable. I would like to have these settings on Windows as well.

Ubuntu 20.04:
![VirtualBoxVM_2020-05-23_12-45-06](https://user-images.githubusercontent.com/9344600/82728840-4e211b80-9cf3-11ea-9440-f0f0caf5d9f1.png)

Windows:
On Windows you can only enable the hightlight but can't change the settings. Don't mind the changed theme, this is still normal Windows 10.
![xournalpp_bin_2020-05-23_12-47-23](https://user-images.githubusercontent.com/9344600/82728880-8e809980-9cf3-11ea-815c-1ee355e1e658.png)
I'm on the latest version:
![xournalpp_bin_2020-05-23_12-46-35](https://user-images.githubusercontent.com/9344600/82728870-7f015080-9cf3-11ea-8532-ef4b036db038.png)

**Comment by LittleHuba** [comment]
If you tick the appropriate check box to highlight the cursor. These settings should appear.

**Comment by LittleHuba** [comment]
Linux and Windows share the exact same code base. So there shouldn't be any different behaviour in the GUI.

**Comment by singinwhale** [comment]
![xournalpp_bin_2020-05-23_14-01-18](https://user-images.githubusercontent.com/9344600/82730141-e4f2d580-9cfd-11ea-8ec3-75fc3fce1503.png)
they don't appear however

**Comment by LittleHuba** [comment]
If you leave the setting switched on and close and reopen the settings dialog do they appear then?

**Comment by Technius** [comment]
Cursor highlight settings are only available on `master` branch. If you'd like to use them on Windows, you should use the (unstable) nightly release.

**Comment by singinwhale** [comment]
> Cursor highlight settings are only available on `master` branch. If you'd like to use them on Windows, you should use the (unstable) nightly release.

I am using the prebuilt release binaries from the github page, I would assume they are from the `master` branch?
also, where would I get nightly releases without building the project myself?

**Comment by Technius** [comment]
[You can find the nightlies here](https://github.com/xournalpp/xournalpp/releases/tag/nightly).

It seems like the automated nightly build system has been disabled in the past 3 weeks for some reason. The cursor highlight feature was introduced slightly less than 3 weeks ago, so hasn't been included yet. I have reenabled the automated nightly builds just now, and you'll be able to see the feature once the build runs today or tomorrow.

**Comment by singinwhale** [comment]
It works in the nightly but the nightly is failing on OSX so the build pipeline is failing.
I had to download the nightly from the azure artifacts because the nightly tag is not updated.

**Comment by Technius** [comment]
We've been trying to fix the issue over the past few days, but it's been pretty hard to get it fixed correctly.
