### ISSUE TITLE
Using numbers as hotkey for colors

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp#2007]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when wanting to quickly use another color I have to reach to the top panel, write the thing I need, and then switch back to black by reaching the top bar again.

**Describe the solution you'd like**
Use the number row as a hotkey for the color palette. Similar to how the number row is how you switch between weapon in most FPS games.

**Comment by rolandlo** [comment]
You can use a plugin to do that. See the [plugin for cycling through a color list](#2251) and the website [section on plugins](https://xournalpp.github.io/guide/plugins/) and some more advice in issue #919. Note that you can register several shortcuts in the same plugin using multiple `registerUI` commands.

**Comment by fpesari** [comment]
I agree that this functionality would be very useful to have without having to use an external plugin. 

Right now, when the highlighter tool is selected, numbers aren't bound to any function that I know of, they are a no-op. So adding support for selecting the colors in the toolbar by pressing the relative number key (and maybe binding ` to toggle between the last selected colors) would only be beneficial, IMHO.
