### ISSUE TITLE
Xournal++ community gift

### ISSUE THREAD

**Issue by PellelNitram** [xournalpp/xournalpp#2008]
Hi,

I really like Xournal++! As it helps me daily to work with my handwritten notes, I prepared a small key chain as community gift.

![designs](https://user-images.githubusercontent.com/2728265/82738322-0de38c80-9d37-11ea-8b16-3adc2428bee3.jpg)

Let me know here or write me an email to martin.lellep.blog@gmail.com if you'd like to receive such a key chain. I restrict this offer to Germany as I live there. My budget is 10 Euro for shipping in Germany which makes around 13 key chains that I can send around.

See a small blog post on my website to get the file if you want to fabricate the key chain yourself, to get a bit more background story or if you just want to see a tiny video of the gift: http://lellep.xyz/blog/xournalpp-community-gift.html.

Cheers for developing Xournal++!

**Comment by LittleHuba** [comment]
Ohh nice one! They do look amazing! I'd be interested in version b.

**Comment by rolandlo** [comment]
That looks really nice. I like version (b) especially. Unfortunately I am not living in Germany. Anyway, thumbs up for your creation!

**Comment by PellelNitram** [comment]
Great to read your comments!

@LittleHuba : I'd need your address to ship it to. Doesn't have to be public, of course.
@rolandlo : According to Github, you live in Switzerland. Is that true? Given the current demand, & thereby shipping budget flexibility, I could also send it to Switzerland! :-) Hence the same for you: I'd need your address to ship it to. Doesn't have to be public, of course.

**Comment by rolandlo** [comment]
Thank you, @PellelNitram . Yes the info about the country I live in is correct. How can I send you my address privately?

**Comment by LittleHuba** [comment]
@PellelNitram best would be if you reach out to us via Gitter (link in the Readme).

**Comment by PellelNitram** [comment]
OK, I will do so now. Cheers!
