### ISSUE TITLE
stylus xp-pen deco 01v2 not detected

### ISSUE THREAD

**Issue by machoue** [xournalpp/xournalpp#2010]
**Affects versions :**
 - OS: Mac 10.15.3
 - Version of Xournal++ 1.0.18 

**Describe the bug**
My stylus xp-pen deco 01v2 is not detected. I can write with it, but have no pressure sensitivity. In the "PenTabletSetting" app, the pressure of the stylus is detected.

In Xournal++ preferences, in the input system tab, I have the message : 
"No devices were found. This seems wrong - maybe file a bug report ?"
I tried to activate and deactivate the "Enable new input system" and restarted but it did not help.

**Comment by Technius** [comment]
Duplicate of #1772.
