### ISSUE TITLE
Automatic create of new layout create crash of the app

### ISSUE THREAD

**Issue by Alfystar** [xournalpp/xournalpp#2028]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux, KDE neon 5.18
 - (Linux only) Desktop environment: KDE
 - Which version of libgtk do you use
    libgtk: 3.22.30 
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     Xournal++ 1.1.0+dev 
 - Installation method: PPA

**Describe the bug**
i normally use right hand layout, today i try to modify it to move the component, the system ask me if i want to create a copy and modify it, i say yes... and the app CRASH
I had seen that: the same procedure create crash with all layout, also if i copy before the layout and after try to change, the program crash agane
**To Reproduce**
Steps to reproduce the behavior: (i use italian version of the app, so i write the italian name of menù)
1. Select any one layout you want in Vista->Barre degli strumenti --> one loyout you chose
2. Select Vista->Barre degli strumenti -->Personalizza
3. the program show the screenshot and if i say yes, the program chrash

**Expected behavior**
the program create automaticaly new layout and can start my personalization

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/32840211/83391558-f15ce980-a3f3-11ea-8790-f93ea1516422.png)

**Additional context**
i test, same problem if i create manually the new layout as copy of one and after i try to change

**Comment by Febbe** [comment]
Please update your Ticket, where did you changed the hand layout. Also add a more precise list of steps to reproduce.

**Comment by Alfystar** [comment]
> Please update your Ticket, where did you changed the hand layout. Also add a more precise list of steps to reproduce.

I update with also the error

any way i thing your work is amazing, just so i think this program could have more potentialy than oneNote, GOOD work guy ;D

**Comment by colorizer** [comment]
I'm also facing the same problem in Ubuntu 20.04 (KDE environment). Here is the output thrown at terminal during the crash. 
```

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:07.842: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:07.842: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:07.842: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:07.842: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:20.103: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:20.104: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:20.104: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.xournalpp.xournalpp:30475): Gdk-CRITICAL **: 15:00:20.104: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)

** (com.github.xournalpp.xournalpp:30475): WARNING **: 15:00:20.134: [Crash Handler] Crashed with signal 6

** (com.github.xournalpp.xournalpp:30475): WARNING **: 15:00:20.134: [Crash Handler] Wrote crash log to: /home/colorizer/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20201021-150020.log

** (com.github.xournalpp.xournalpp:30475): WARNING **: 15:00:20.271: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:30475): WARNING **: 15:00:20.271: Successfully saved document to "/home/colorizer/.config/com.github.xournalpp.xournalpp/emergencysave.xopp"
```

**Comment by Alfystar** [comment]
The actual version 1.1.0 from the last commit of the code, solve this bug
Good Job =D
