### ISSUE TITLE
The hand command don't work...

### ISSUE THREAD

**Issue by Alfystar** [xournalpp/xournalpp#2029]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux, KDE neon 5.18
 - (Linux only) Desktop environment: KDE
 - Which version of libgtk do you use
    libgtk: 3.22.30 
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     Xournal++ 1.1.0+dev 
 - Installation method: PPA

**Describe the bug**
simply, when i try to move over the paper, the immage stay lock and i need to use mouse wheel to change the visual

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by Technius** [comment]
Can you see if the comments in #1501 solve your problem?

**Comment by Alfystar** [comment]
> Can you see if the comments in #1501 solve your problem?

Yes of course :D, 
i tested to change from new input system to old input system, but notthing to do...
also in the new input system when i click the button on the pen to use the hand, the pen stop to write (and this is right), but in the old input system when do the same, the hand go away and the pen restart to write

this is my current setting:
![image](https://user-images.githubusercontent.com/32840211/83613736-81ca3400-a584-11ea-8d8b-8774ba5114db.png)

And i use the "Deco 01 V2" to write

Thanks for the help ;-D

**Comment by Alfystar** [comment]
The actual version 1.1.0 from the last commit of the code, solve this bug
Good Job =D
