### ISSUE TITLE
Highlighter don't show any suggest about where is the cursor...

### ISSUE THREAD

**Issue by Alfystar** [xournalpp/xournalpp#2030]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux, KDE neon 5.18
 - (Linux only) Desktop environment: KDE
 - Which version of libgtk do you use
    libgtk: 3.22.30 
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     Xournal++ 1.1.0+dev 
 - Installation method: PPA

**Describe the bug**
when i select the Highlighter, on the windows i litteraly don't know where is now my cursor

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**
a little cursor like a rectangle with de current size of the pen, to undestand where i will write

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by 4VRDriver** [comment]
#1671

**Comment by Technius** [comment]
A temporary workaround is to enable the `Big cursor for pen` option in the `View` tab of the settings.

**Comment by Alfystar** [comment]
i now update the software, and the Highlighter have a small square for the cursor, isn't the best solution because the size of the Highlighter are unknow, but to start this is good ;-D

Thanks to listening ass, your work is greate !!!!

**Comment by Alfystar** [comment]
The actual version 1.1.0 from the last commit of the code, solve this bug
Good Job =D
