### ISSUE TITLE
A new Text Box widget, or a new opt-in word wrapping feature in a Text Box

### ISSUE THREAD

**Issue by scottnykl** [xournalpp/xournalpp#2033]
It would be great if there was a Text Box (or other named widget) that could support word wrapping of pasted text...

If you are worried about breaking backwards compatibility, perhaps a new Text Box could be added in that supports word wrapping. Or perhaps word wrapping could be an opt-in property that is settable after the text box is created).

I use xournal to create hand drawn lecture materials, but sometimes I need a block of text to format itself within a defined rectangular size to compliment my hand drawings. Having to manually insert newlines does not work when I have to resize the rectangle's dimensions.

Would either of these options be a viable alternative? It seems like it would be orthogonal and quick to implement?

We will brake compatibility, and the usage is not that high, I close this ticket (cleanup of old tickets...)

_Originally posted by @andreasb242 in https://github.com/xournalpp/xournalpp/issues/139#issuecomment-437701050_

**Comment by Jdude311** [comment]
Please, I need this, I use it to take notes and it's such a pain.

**Comment by nicolae-stroncea** [comment]
This might be related to https://github.com/xournalpp/xournalpp/issues/729 which mentions a lot of features that a new text box like this might include.

**Comment by KronosTheLate** [comment]
I would LOVE a textbox that wraps, where I could chose the text box size instead of manually inserting line-skips, which makes re-sizing a pain (without changing font size).

**Comment by rolandlo** [comment]
The text box deserves to be improved a lot. It is incredibly basic as of now. The main problem is backward compatibility for the file format indeed.

**Comment by KronosTheLate** [comment]
So how about adding a new and improved textbox in the next release, that replaces the old one in the next breaking release?

On my whishlist for a new textbox is bold and italic text, and colouring only parts of the box. Inline LaTeX would be a treat.

**Comment by rolandlo** [comment]
Not sure about inline LaTeX. For the other things (including word wrapping) we mainly need someone who has the time, dedication and skills to implement it.

**Comment by tobiasBora** [comment]
Regarding inline LaTeX that would be awesome and super useful. I don't know if it makes sense, but would it be imaginable to use a QWebEngineView + mathjax, like in https://stackoverflow.com/questions/56760843/how-to-display-mathematical-typesetting-mathjax-latex-etc-in-qt-using-pyqt5? Given the number of javascript engines that deal with markdown it might make the transition to markdown easier.

See also https://github.com/xournalpp/xournalpp/issues/1092

**Comment by rawfiul** [comment]
@bhennion  sorry for tagging but Im surprised yall are skipping this feature completely. I understand the backward comp issue but it makes me wonder if most users are using just pen tool because a note taking app without a text wrap is shocking. I spent 2 hours customizing toolbar, grid spacing,templates etc only to find out the text dont wrap :(
