### ISSUE TITLE
Text box bug

### ISSUE THREAD

**Issue by Yobeco** [xournalpp/xournalpp#2035]
**Affects versions :**
 - OS: [Ubuntu 18.04]
 - (Linux only) Desktop environment: [GNOME]
 - Which version of libgtk do you use
     - libgtk: 3.22.30 
 - Version of Xournal++: [Xournal++ 1.1.0+dev]
 - Installation method: [PPA]

**Describe the bug**
I can get a text box, but I cant write in... It's still empty...

**To Reproduce**
1. run Xournal
2. get Text tool
3. writing with keyboard

**Expected behavior**
It wil not write any lettre

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by Yobeco** [comment]
Very nice tool !!! Thank you very much !!!

**Comment by Technius** [comment]
Are you using a combined mouse/keyboard device, like a Logitech USB receiver? If so, try changing the device class of your keyboard to `Mouse+Keyboard Combo` in the settings under `Input System`.

**Comment by Yobeco** [comment]
No, I'm using an USB keyboard, a USB mouse, and at the same time a Wacom tablet ET-0405-U with a pen.

**Comment by LittleHuba** [comment]
Could you show us a screenshot of the "Input System" tab in the preferences dialog please?

**Comment by Yobeco** [comment]
How can I send a picture ?

**Comment by Yobeco** [comment]
Can you see it?

https://sites.google.com/lvh.edu.ni/cm2lvh/organisation/tutoriels/pdf-%C3%A9ditables/debug-xournal

**Comment by LittleHuba** [comment]
For the second to last `USB keyboard` please select the input class `Keyboard Mouse Combo`.

**Comment by Yobeco** [comment]
Super! Excellent! It is working!
Thank you very much!
You are making a great application!

**Comment by Yobeco** [comment]
I'm going to introduce this application to my students. :-)
