### ISSUE TITLE
Shortcuts not created for all users upon installation

### ISSUE THREAD

**Issue by blueWalrus** [xournalpp/xournalpp#2036]
**Affects versions :**
 - OS: Windows 10
 - ~~(Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]~~
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
No shortcuts were created during installation when "Do not create shortcuts" was not selected.

**To Reproduce**
1. Run the installation executable 
2. Make sure "Do not create shortcuts" is not selected.

**Expected behavior**
A shortcut will be made available in the start menu and on the desktop when "Do not create shortcuts" is not selected. 

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
I used xournalpp-1.0.18-windows.zip

**Comment by blueWalrus** [comment]
I looked into it further. Shortcuts are created but only for the user that installs it. This can be corrected by changing the shortcut folder location 

from 

<pre>
C:\Users\<b>username</b>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs 
</pre>

to   

 <pre>C:\ProgramData\Microsoft\Windows\Start Menu\Programs</pre>

Doing so will make it available to all users.

**Comment by LittleHuba** [comment]
That should be part of the installer routine to select where to store them. I assume many users do actually not want shortcuts for everybody when sharing their device with other people.

**Comment by maehne** [comment]
The current behaviour of the installer is irritating if you launch the Xournal++ installer as a normal user and then the installer process gets run via UAC in the context of a separate administrator user. In the end, Xournal++ is installed, but the normal user cannot find the start menu entry. Just through this bug report I got the idea to look in the start menu of the administrator user and move it to the global start menu.
