### ISSUE TITLE
I want to write a plugin

### ISSUE THREAD

**Issue by createyourpersonalaccount** [xournalpp/xournalpp#2037]
**Is your feature request related to a problem? Please describe.**
I write math documents in LaTeX and often I want to include images. I don't like having to "code" the images (with tikz, asymptote, gnuplot, etc). I would much rather be able to draw them; this is what I currently do in xournal++, but the exporting is not as streamlined as could be.

**Describe the solution you'd like**
I would like to write a plugin that makes this easier. It would work like this: You choose an area with the area selector and click "export to png"; it should automatically be placed in project/figures/N.png where N is an incrementing number (or some other such schema).

I have programming experience in C, C++ and other languages (hobbyist), but I have not contributed to any projects before. I was wondering if someone could help me with the relevant information: How to write a plugin for xournal++, and whether the idea I have in mind is feasible for someone like me.

Thank you for your time, and this awesome project!

**Comment by rolandlo** [comment]
@createyourpersonalaccount 

That should be rather simple, I think, although it may depend on the system you use. With a plugin you can execute system commands. Use `gnome-screenshot` or `scrot` to take a screenshot of a user-selected area and save it into a file. 
Your plugin will have an .ini file (see any of the existing plugins in the source code) and a lua-scriptfile. The latter (using `scrot`) would look about like this:

```
-- Register all Toolbar actions and intialize all UI stuff
function initUi()
  app.registerUi({["menu"] = "Take and save Screenshot", ["callback"] = "shot"});
end

function shot()
  os.execute("scrot -s '%Y-%m-%d-%T.png' -e 'mv $f ~/project/figures/' ")
end
```
Explanation: 

- scrot is a screenshot tool (under Linux)
- the option -s lets you specify the area
- the string '%Y-%m-%d-%T.png' indicates the filename defined by year (Y), month (m), day(d) and time of the day (T)
- the option -e executes the given command
- mv moves the file
- $f is the scrot-internal filename
- ~/project/figures is the path you want your file to be stored

If you want a more sophisticated file naming convention, you can use some lua scripting to produce it.

@Spiriz00 You can combine the screenshot-tool `scrot` with the convert-tool `convert` to get a pdf image

**Comment by createyourpersonalaccount** [comment]
@rolandlo Thank you, I will look into this. I am glad (and a bit surprised!) that @Spiriz00 already showed support for the idea.

I will try to make this happen within the week.

**Comment by Spiriz00** [comment]
Thanks Rolandlo, but the pdf file generated from a png file loose quality when zoomed. Code that I used:
convert file.png file.pdf

**Comment by Rmano** [comment]
I use a different strategy, that does not pass through raster images. 

1. Draw your diagram in `xournal++`
![image](https://user-images.githubusercontent.com/6414907/83805726-b1765a80-a6b0-11ea-9336-17ed043882db.png)

2. Export it using "Export as..." and choose "PDF with plain background" with a name like `graph.pdf`
3. Crop it using `pdfcrop graph.pdf` --- It will create a `graph-crop-pdf` which is the diagram you can use for inclusion. Look at this file manager shot:

![image](https://user-images.githubusercontent.com/6414907/83806077-395c6480-a6b1-11ea-9dbc-aa550fee2be5.png)

Now, having a plugin to "Export as" a cropped pdf (better if with no background at all) would be a very nice thing.

**Comment by createyourpersonalaccount** [comment]
@Rmano nice, thank you. I will update with my results in this issue sometime soon.

**Comment by createyourpersonalaccount** [comment]
I wrote the code. It looks like this
```lua
-- main.lua
-- Register all Toolbar actions and initialize all UI stuff
function initUi()
  ref = app.registerUi({["menu"] = "Quick SnapShot", ["callback"] = "myMain", ["accelerator"] = "<Control>t"}); -- TODO: Choose better shortcut
end

-- Callback if the menu item is executed
function myMain()
  local systemName = app.getSystemName();
  if systemName == "Windows"
    print("Windows not supported yet.");
  elseif systemName == "macOS"
    print("macOS not supported yet.");
  elseif systemName == "Unix"
    os.execute("gnome-screenshot -a"); -- TODO fill out more details
  else
    print(string.format("%s not supported.", systemName));
end
```

I also had to modify `src/plugin/luapi_application.h` to add this code
```cpp
/**
 * Return Windows/macOS/Unix accordingly.
 */
static int applib_getSystemName(lua_State* L) {
  // List of preprocessor directives taken from
  // https://sourceforge.net/p/predef/wiki/OperatingSystems/
  static constexpr string s =
#ifdef _WIN16 || _WIN32 || _WIN64
    "Windows"
#elseif macintosh || Macintosh || (__APPLE__ && __MACH__)
    "macOS"
#elseif __unix__
    "Unix"
#else
    "Unknown operating system"
    ;
  lua_pushlstring(L, s.c_str(), s.length());
  return 1;
}
```

Right now it is impartial, it doesn't work yet.
How can I ask the user where to save it? I need to create a dialogue box. Can someone help a bit with explaining where I can learn more about that?

**Comment by createyourpersonalaccount** [comment]
Another question -- how can I choose a better shortcut? For example, Control-Shift-1 might be a good one (sounds good to me at least). But I don't know how to have that shortcut.

**Comment by Technius** [comment]
> How can I ask the user where to save it? I need to create a dialogue box. Can someone help a bit with explaining where I can learn more about that?

You will want to create another applib function in `luapi_application.h` that calls the relevant [GTK file chooser API](https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html). We currently don't have any utility/library code that does this, it's all handled manually.

**Comment by createyourpersonalaccount** [comment]
Great, thank you. I will give it a try. My plan is to use `gnome-screenshot` or `scrot` on linux (with error checking to see which is available). What about Windows and macOS? Does anyone know what is usually available there for screenshots? I may leave those undone because I do not use these operating systems.

**Comment by rolandlo** [comment]
@createyourpersonalaccount 
On macOS you may use the [screencapture utility](https://ss64.com/osx/screencapture.html)
Some options under Windows are discussed on [this site](https://superuser.com/questions/75614/take-a-screen-shot-from-command-line-in-windows). I am not sure which one fits (best), tough.

`Scrot` will come pre-installed on most linux systems, while `gnome-screenshot `will only be available on gnome based linux distros. This would make `scrot` the preferred first choice.

Instead of calling the file chooser every time you take an image you might also hard-code a pre-defined path (depending on the operating system) and use a predefined filename scheme. The user can modify the pre-defined path by editing the plugin file. Make sure the user knows where to find it. The plugins path under Linux is /usr/local/share/xournalpp/plugins/. As far as I see, this would be more in the spirit of your original idea.

**Comment by createyourpersonalaccount** [comment]
Thank you @rolandlo I will try to do this soon. 

As for your pre-defined path idea, you are right that is the easiest way to do it for me. So I will do this:

1) I will write the above with pre-defined configuration file.
2) I will upgrade to file chooser later.
3) I will ditch "screenshot programs" and write it in "native" xournal++ code.

Of course step 3) is very far away from becoming reality (in part because I have no idea of xournal++'s internals) but I am sure I can pull of 1) very soon and maybe 2) as well, if I can write the gtk code required for it.

My idea was to document my plugin enough so that 3) may be one day implemented by someone else, if it turns out that my plugin is of interest.

**Comment by createyourpersonalaccount** [comment]
Here is my lua code right now

```lua
-- Register all Toolbar actions and initialize all UI stuff
function initUi()
  ref = app.registerUi({["menu"] = "Quick SnapShot", ["callback"] = "myMain", ["accelerator"] = "<Control>t"})
end

-- Return one of "Windows", "Linux", "Darwin", "FreeBSD",
-- "OpenBSD" or "NetBSD, etc.
function findOS()
  if package.config:sub(1,1) == '\\' then
     return "Windows"
  else
    local f = assert(io.popen("uname -s", 'r'))
    local s = assert(f:read('*a'))
    f:close()
    return s
  end
end

find existsUtility(utility)
  local f = assert(io.popen("command -v " .. utility))
  local s = assert(f:read('*a'))
  f:close()
  return s ~= ""
end

-- Callback if the menu item is executed
function myMain()
  local systemName = findOS()
  if systemName == "Windows" then
    print("Windows not supported yet.")
  elseif systemName == "Darwin" then
    print("macOS not supported yet.")
  elseif systemName == "Linux" or
         systemName == "FreeBSD" or
         systemName == "OpenBSD" or
         systemName == "NetBSD" then
    if existsUtility("gnome-screenshot") then
      os.execute("gnome-screenshot -a")
    elseif existsUtility("scrot") then
      os.execute("scrot")
    end
  else
    print(systemName .. " not supported.")
  end
end
```

I'm still quite dissatisfied with not allowing the user to select the filename and I realized that the solutions I had in mind don't work as well, in particular because it's a mess to come up with a new filename each time from inside lua. 

I need to use the gtk solution as mentioned. I might do that soon.

**Comment by createyourpersonalaccount** [comment]
Minor update: I am still working on this. I managed to get a Save As dialog to appear using GTK in my program. So now I just need to incorporate it into Xournal++.

**Comment by createyourpersonalaccount** [comment]
Okay! Done! I created a pull request, the feature is ready.

**Comment by createyourpersonalaccount** [comment]
JJJJJ

**Comment by rolandlo** [comment]
Thanks for contributing the PR and for extending our understanding of what to take into account when writing plugins. I'll take a look at your PR and the problem you encountered next week. Have a good rest.

**Comment by rolandlo** [comment]
PR #2086 closes this ticket. The issue raised by Spiriz00 can be discussed in a new ticket.
