### ISSUE TITLE
Title of exported PDF

### ISSUE THREAD

**Issue by piegamesde** [xournalpp/xournalpp#2038]
**Is your feature request related to a problem? Please describe.**
Currently, the exported PDF contains the whole absolute path to the `.xopp` file. This is information that isn't really useful in the title. It can also have privacy implications as well.

**Describe the solution you'd like**
Simply use the name of the file (without extension) as title. Alternatively, ask the use in the dialog.

**Describe alternatives you've considered**
Or maybe leave it blank, PDF viewers should fill in a sensible default when viewing.

**Comment by rolandlo** [comment]
This is fixed in PR #2039.

**Comment by piegamesde** [comment]
Thank you.
