### ISSUE TITLE
location of config file (MAC)

### ISSUE THREAD

**Issue by vrutten** [xournalpp/xournalpp#2041]
Hi,

I just installed xournalpp-1.0.18 for macos.
I'm running on Catalina 10.15.5

For the better of me I can't seem to locate the configuration file.
There is no .xournal folder anywhere on my paths.
There is a .xournalpp folder but it does not contain any config file.

I also don't have any option to "save preferences" when opening the app.

Thanks for letting me know how to resolve this,

Best

V

**Comment by LittleHuba** [comment]
Could you check if there is a directory `.config/com.github.xournalpp.xournalpp`?

**Comment by vrutten** [comment]
Thanks for the response

I do have a ~/.config folder but it doesn't contain any such file (nor do any of the subfolders).

**Comment by vrutten** [comment]
In case it helps:
I downloaded the app from: https://github.com/xournalpp/xournalpp/releases

**Comment by LittleHuba** [comment]
That should actually be a directory. It could be that GTK uses some special directory on macOS for its config directory...

**Comment by vrutten** [comment]
Not sure what you're referring to by "that" (?)

but I do see that there is a ~/.config/gtk-3.0/ folder but it is empty

**Comment by LittleHuba** [comment]
If you feel comfortable with it could you post a list of all the directories in this config directory? And maybe also a list of the hidden directories within you home directory?

**Comment by vrutten** [comment]
![Screenshot 2020-06-07 at 14 29 46](https://user-images.githubusercontent.com/15912669/83970058-5cfaf700-a8cb-11ea-963c-7fa5dbaec744.png)

Here they are

**Comment by LittleHuba** [comment]
Are you checking in `/Users/*/.config/`? The star should be your username.

**Comment by vrutten** [comment]
yup

and here are all the hidden directories:

> grep: .DigitalWave: Is a directory
> grep: .FLIKA: Is a directory
> grep: .IdentityService: Is a directory
> grep: .ServiceHub: Is a directory
> grep: .Trash: Is a directory
> grep: .anaconda_backup: Is a directory
> grep: .android: Is a directory
> grep: .bash_sessions: Is a directory
> grep: .bundle: Is a directory
> grep: .cabal: Is a directory
> grep: .cache: Is a directory
> grep: .conda: Is a directory
> grep: .config: Is a directory
> grep: .credentials: Is a directory
> grep: .cups: Is a directory
> grep: .designer: Is a directory
> grep: .docker: Is a directory
> grep: .dropbox: Is a directory
> grep: .emacs.d: Is a directory
> grep: .fresh: Is a directory
> grep: .gem: Is a directory
> grep: .ghc: Is a directory
> grep: .ipynb_checkpoints: Is a directory
> grep: .ipython: Is a directory
> grep: .iterm2: Is a directory
> grep: .jssc: Is a directory
> grep: .jupyter: Is a directory
> grep: .keras: Is a directory
> grep: .local: Is a directory
> grep: .m2: Is a directory
> grep: .matplotlib: Is a directory
> grep: .mono: Is a directory
> grep: .node-gyp: Is a directory
> grep: .npm: Is a directory
> grep: .nuget: Is a directory
> grep: .nvm: Is a directory
> grep: .nx: Is a directory
> grep: .opam: Is a directory
> grep: .oracle_jre_usage: Is a directory
> grep: .owl: Is a directory
> grep: .plotly: Is a directory
> grep: .pylint.d: Is a directory
> grep: .qt: Is a directory
> grep: .software: Is a directory
> grep: .spyder: Is a directory
> grep: .spyder-py3: Is a directory
> grep: .ssh: Is a directory
> grep: .subversion: Is a directory
> grep: .templateengine: Is a directory
> grep: .thumbnails: Is a directory
> grep: .vim: Is a directory
> grep: .vnc: Is a directory
> grep: .vscode: Is a directory
> grep: .xournalpp: Is a directory

**Comment by vrutten** [comment]
Here is the content of .xournalpp:

![Screenshot 2020-06-07 at 14 32 25](https://user-images.githubusercontent.com/15912669/83970096-b6632600-a8cb-11ea-9887-7e992cdcb8ec.png)

**Comment by LittleHuba** [comment]
Ahh okay my bad. The switch to the new config directory is not in `1.0.18`. What you see in .xournalpp is all the configuration data of Xournal++. What are you searching for that is not there?

**Comment by vrutten** [comment]
oh, I see.
so is the way to save our desired configurations (i.e.: in settings.xml)?

It's just that at the top of the file is the following sentence:
`<!--The Xournal++ settings file. Do not edit this file! The most settings are available in the Settings dialog, the others are commented in this file, but handle with care!-->`
so I assumed that there would be another config file which settings.xml got its parameters from. 
Here: http://www-math.mit.edu/~auroux/software/xournal/manual.html it talked about a "save preference" button on the app window which I didn't see either.

Happy to change the settings.xml file, just thought I was missing something.

**Comment by LittleHuba** [comment]
Ahh now I see where things got confused. Xournal++ is NOT Xournal. 😉 

We are a rewrite of the original Xournal but with a different GUI and a superset of the functionalities Xournal provided. All settings you as user can influence are within the Settings dialog, reachable from the main window (Edit > Preferences). If you close the settings dialog using the `Okay`-Button all the modified settings are stored in `settings.xml` and restored when you open a new instance of Xournal++.

**Comment by vrutten** [comment]
🙈  - oups
thanks for the clarifications!

**Comment by LittleHuba** [comment]
No issue you're not the first one assuming there is more in common than 5% of the source code 😉 
Enjoy using Xournal++!
