### ISSUE TITLE
latest master fails to build on ubuntu 18.04. 

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#2048]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: ubuntu 18.04 

**Describe the bug**
after running:

`cmake ..`

end up with:
```
[...]
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'portaudiocpp >= 12'
--   Found portaudiocpp , version 12
-- Checking for module 'sndfile >= 1.0.25'
--   Found sndfile , version 1.0.28
-- Checking for module 'gtk-mac-integration'
--   No package 'gtk-mac-integration' found
-- Checking for module 'lua5.3'
--   Found lua5.3, version 5.3.3
Enable Xournal++ Plugins
-- Found Gettext: /usr/bin/xgettext (found version "0.19.8.1") 
CMake Error at src/CMakeLists.txt:87 (target_link_libraries):
  Object library target "xournalpp-core" may not link to anything.

-- Configuring incomplete, errors occurred!
```

**To Reproduce**
following build steps: 
```
git clone http://github.com/xournalpp/xournalpp.git
cd xournalpp
mkdir build
cd build 
cmake ..    #fails here
cmake --build .
```

**Expected behavior**
build completes

**Additional context**
first noticed this a couple of weeks back.

**Comment by Technius** [comment]
Can you post the entire build log?

**Comment by petergthatsme** [comment]
sure, attached. 
thanks.
[cmake_output.txt](https://github.com/xournalpp/xournalpp/files/4755889/cmake_output.txt)
[CMakeError.log](https://github.com/xournalpp/xournalpp/files/4755892/CMakeError.log)
[CMakeOutput.log](https://github.com/xournalpp/xournalpp/files/4755893/CMakeOutput.log)

**Comment by Technius** [comment]
Should be fixed now. I tested on a fresh Ubuntu 18.04 docker image. Please let me know if anything else is broken.

**Comment by petergthatsme** [comment]
yup, fixed. Thanks!
