### ISSUE TITLE
Set Default Paper Properties

### ISSUE THREAD

**Issue by usrtrv** [xournalpp/xournalpp#205]
Xournal use to have a feature that would allow you to set the default paper when creating a new document.

**Comment by wbrenna** [comment]
Journal -> Paper Format isn't persistent?

**Comment by usrtrv** [comment]
As far as I can tell, no. I set the properties, save a page, restart xournalpp. I get the same default page layout. Neither the paper format nor the paper background are persistent for new documents.

**Comment by usrtrv** [comment]
Ok, it seems that the paper background setting is updated if you use Journal -> Insert New Page, but not via Journal -> Paper Background. I guess on purpose? On another note, changing Journal -> Paper Color updates the setting. So it isn't consistent or obvious.

**Comment by wbrenna** [comment]
I think probably unintended behaviour - this should be corrected.

**Comment by tigerjack** [comment]
For me, the wrong behavior still occurs. I'm not able to permanently store neither background nor width/height attributes: they are simply overwritten on restart.

**Comment by andreasb242** [comment]
Confirmed with the current master.

**Comment by andreasb242** [comment]
There is a new dialog which also allows to load / save the page template.

**Comment by marmistrz** [comment]
If anyone else has trouble finding this dialog: `Journal > Configure page template` (I expected to find it under preferences)

**Comment by m1nicrusher** [comment]
> (I expected to find it under preferences)

Agree, IMHO I would love to see it being put under ```Preferences > Defaults```.
![image](https://user-images.githubusercontent.com/19246983/187204850-2c31b33b-f6f8-4d1b-a74f-52a4d7655595.png)
It's also pretty empty here.

**Comment by rehanguha** [comment]
Is there any plan to add page layout and page style in the defaults menu? These options will help a lot. 
Thanks.

**Comment by Stalkerfish** [comment]
You can set default paper properties by editing the settings.xml file at $HOME/.config/xournalpp/settings.xml

**Comment by bhennion** [comment]
copyLastPageSettings is set via the "Copy current page background instead" check box.

I don't quite understand what the request is here. If there is indeed a feature request, please open a new issue and do not necrobump a closed one.

**Comment by achetronic** [comment]
Still happening here ✋🏼

**Comment by dev-null2019** [comment]
Same here ...

**Comment by sjmeans** [comment]
Any plans on addressing this?
