### ISSUE TITLE
Anchor highlighter and pen to text

### ISSUE THREAD

**Issue by mdeff** [xournalpp/xournalpp#2051]
**Is your feature request related to a problem? Please describe.**

Highlighting and crossing out text is hard as the highlighter and pen tools must be aligned with the text by hand. I often find myself deleting annotations to align them better with the underlying text.

**Describe the solution you'd like**

Highlighting and crossing out by selecting the text. That's done by evince, and I guess many other PDF readers with basic annotation capabilities.

Any other way to anchor annotations to the underlying text would however be fine.

**Describe alternatives you've considered**

Highlight text in evince, before doing more advanced annotations (like drawings or latex) in xournal++.

**Additional context**

Text highlighting in evince:
![highlight_evince](https://user-images.githubusercontent.com/6806065/84054416-a888d000-a9b3-11ea-9ad3-95866beaaa98.png)

**Comment by mdeff** [comment]
If anchoring is done by selecting text, this would depend on #1745.

**Comment by Technius** [comment]
This can be achieved by the recently added "Select PDF Text" tools.

**Comment by kojid0** [comment]
> This can be achieved by using the recently added "Select PDF Text" tools.

Select PDF Text tools are not yet available in the latest stable version 1.1.1, but will be there with 1.2, am I right?

**Comment by Technius** [comment]
Yes. If you are willing to risk a little bit of stability, you can also use them in the nighty builds.
