### ISSUE TITLE
Save moves to page top

### ISSUE THREAD

**Issue by tmelorc** [xournalpp/xournalpp#2052]
Using:

![Seleção_168](https://user-images.githubusercontent.com/15181573/84149400-cba89380-aa36-11ea-9333-725ebdd51083.png)

**Is your feature request related to a problem? Please describe.**
It is not a problem. Let me explain. 

When save a document, the pages moves to top of the current one. This is not good when we are presenting and save to make sure to keep the changes. Then the page goes to top and we have to scroll down it to go back where we were writing.

**Describe the solution you'd like**
A possible solution would be: does not change the view when saving.

**Comment by Technius** [comment]
This has been fixed in `master`, but not sure when it was fixed though.
