### ISSUE TITLE
Failing scrolling in document with arrow (cursor) keys

### ISSUE THREAD

**Issue by christiankral** [xournalpp/xournalpp#2062]
**Affects versions :**
 - OS: Linux
 - Linux Mint 19.3 XFCE
 - Which version of libgtk do you use: libgtk: 3.22.30
 - Version of Xournal++: Xournal++ 1.1.0+dev
 - Installation method: PPA

**To Reproduce**
- Open Xournal++
- Hit arrow (cursor) up and down: the document does **not** scroll
- Hit CTRL+- (minus) to zoom out
- Hit arrow (cursor) up and down again: the document does scroll
- Save document under any name
- Hit arrow (cursor) up and down: the document does **not** scroll
- Draw a line with the stylus
- Hit arrow (cursor) up and down: the document does scroll again

**Comment by kamdh** [comment]
Confirmed

**Comment by Technius** [comment]
Only seems to occur when the `Touch Workaround` is enabled. Can you confirm?

**Comment by christiankral** [comment]
When I do the same steps on my computer which does not have a stylus (but the same OS and software versions), it behaves partly differently:

**To Reproduce**
Steps to reproduce the behavior:
- Open Xournal++
- Hit arrow (cursor) up and down: the document does scroll `<= this is different`
- Hit CTRL+- (minus) to zoom out
- Hit arrow (cursor) up and down again: the document does scroll
- Save document under any name
- Hit arrow (cursor) up and down: the document does **not** scroll
- Draw a line with the ~~stylus~~ mouse `<= this is different`
- Hit arrow (cursor) up and down: the document does scroll again

**Comment by rolandlo** [comment]
Observation: After saving the document the cursor is somehow locked to the toolbar. You can move back to the document with the TAB key (and vice versa).

**Comment by rolandlo** [comment]
As pointed out in #2138 this is a problem of the XournalView requesting focus. Instead of zooming you can also use the hand tool to select the page, which gives back focus to the XournalView. Of course it should be done automatically.
