### ISSUE TITLE
layer for all pages instead layer for each page

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#2064]
**Is your feature request related to a problem? Please describe.**
When working on a large pdf often it's useful, if you can have multiple layers where you store the annotations of the different sessions so you can work on them separately.

Up to now xournalPP only provides the ability that the user can create new layers for each page (but then if you want to hide all annotations of the last session, you'd have to go to each page and hide the corresponding layer, not speaking of the massive creation of layers when making the annotations).

With general layers for all pages, one could create one layer once, make the annotations (not paying attention that the page changed and a new layer has to be created) and could later very easy hide/unhide the layer on all pages.

**Comment by rolandlo** [comment]
Using PR #2406 this can now be done via a Lua Plugin. The PR contains a test plugin, that contains a function to create a layer for all pages. It also contains a function to hide all layers (which can easily be modified to only hide the top layer, for example).

**Comment by atticus-sullivan** [comment]
Resolved
