### ISSUE TITLE
Export as PDF unable to open file in Adobe

### ISSUE THREAD

**Issue by ldaowen** [xournalpp/xournalpp#2067]
**Affects versions :**
 - OS: [Windows]
 - Xournal++ 1.0.18
 - Official release

**Describe the bug**
- Export as PDF unable to open file in Adobe

**To Reproduce**
1. Open a PDF with a signature behind/background image
2. Export as PDF
3. Open in Adobe Reader

**Expected behavior**
- Expected: To be able to open

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/52833875/84609442-980fb280-aee9-11ea-8e00-26416d21345d.png)

**Comment by Technius** [comment]
Can you open the exported PDFs in a web browser or another PDF viewer?

**Comment by ldaowen** [comment]
> Can you open the exported PDFs in a web browser or another PDF viewer?

It only applies to pdfs with a watermark behind, and no I'm not able to open it in web browser or pdf viewer.

**Comment by Technius** [comment]
Would it be possible for you to upload a sample PDF that has the issue?

**Comment by ldaowen** [comment]
> Would it be possible for you to upload a sample PDF that has the issue?

Not possible due to copyright, since this was only for reading, I can close the issue since I was able to open in the webrowser
