### ISSUE TITLE
Deficulty to figureout the position of pointer in page.

### ISSUE THREAD

**Issue by s1-ranjan** [xournalpp/xournalpp#2069]
**Is your feature request related to a problem? Please describe.**
Presently wile moving the pointer in the page area  when pencil tool or highlighter tool is selected the exact position of the pointer is difficult identify. 

**Describe the solution you'd like**
It would be good to use a default pencil and a marker icon in the paper area by default, this will help to identify the exact position of the cursor in the paper area.

**Describe alternatives you've considered**
OpenBoard can be considered with this functionality.

**Comment by Technius** [comment]
Try out the `Highlight cursor position` or `Big cursor for pen` settings:
![image](https://user-images.githubusercontent.com/1066652/84824562-00878e00-afd5-11ea-920b-890ebdc61ed4.png)
Note that `Highlight cursor position` color options are only available in the nightly builds.

**Comment by s1-ranjan** [comment]
@Technius , thanks for showing me the correct option, in the application, this is what I was looking for, your answer fixed this issue.
