### ISSUE TITLE
customize pad buttons similarly as stylus buttons

### ISSUE THREAD

**Issue by dkwo** [xournalpp/xournalpp#2072]
I'm using xournalpp on Arch linux with a Wacom intuos s.
The surface I'm writing on with the pen has four buttons.
I'd like to map each of the four buttons to a specific function in xournalpp, switch to red pen, switch to eraser, etc.
Right now, I only see in input devices the Wacom Intous S Pad pad(), which can be set to disabled, mouse, pen, eraser, touchscreen, but no finer options for each button.
Is there a way to do what I want?
Thanks.

Of course, if there's a keyboard shortcut to do exactly either 1 or 2, then I can just map my buttons to that shortcut via xsetwacom.

**Comment by dinojr** [comment]
Personnally I mapped the zoom +- page+- to these for buttons via xsetwacom, configure the stylus button for the hand tool and use the floating toolbar to store the useful tools (pen/eraser/geometric shapes...)

**Comment by dkwo** [comment]
Thanks, but do you know how to map one of these four buttons to say 'select
black pen'?

>

**Comment by dkwo** [comment]
Of course I can do
xsetwacom set "Wacom Intuos S Pad pad" Button 1 key "a"
The question is what 'a' should be to (say) select black pen?

>

**Comment by dinojr** [comment]
I don't know if that's possible, sorry.

**Comment by dkwo** [comment]
I think it could be a nice enhancement, to customize the pad buttons in the same way as we currently customize the stylus buttons, without using xsetwacom.

**Comment by dkwo** [comment]
#919 basically

**Comment by rolandlo** [comment]
@dkwo Just use a plugin to define the keyboard shortcuts. See #919 and the work-in-progress website [section on plugins](https://xournalpp.github.io/guide/plugins)

**Comment by dkwo** [comment]
@rolandlo Thank you, I did see that. Is it also possible to 'switch to pen', 'switch to eraser'?

**Comment by rolandlo** [comment]
Yes, sure. Use 

```
app.uiAction({["action"] = "ACTION_TOOL_PEN"})
```
(resp. `ACTION_TOOL_ERASER`, `ACTION_TOOL_HILIGHTER`)
For the eraser you can also select the eraser type via 
`ACTION_TOOL_ERASER_STANDARD`,
`ACTION_TOOL_ERASER_DELETE_STROKE`, 
`ACTION_TOOL_ERASER_WHITEOUT`

**Comment by Svampebob1** [comment]
Not sure if this is an issue any longer, but I was looking into this and found that you can bind keys to the tablet buttons in Gnome settings.
So ctrl+shift+E for the eraser and so on...
