### ISSUE TITLE
[CI] Ubuntu 20.04 DEB packages broken

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#2078]
**Affects versions :**
 - OS: Ubuntu 20.04
 - Version of Xournal++: All
 - Installation method: `.deb` packages

**Describe the bug**
The Ubuntu 20.04 `deb` releases link against `libzip4`, which is not available in Ubuntu 20.04 (use `libzip5` instead). This may be an Azure Pipelines bug since `libzip4` is a _newer_ version of libzip than `libzip5` on CI!

**To Reproduce**
Download and install the current nightly on a fresh Ubuntu 20.04 docker image.

**Expected behavior**
Installs and runs correctly.

**Screenshots of Problem**
N/A

**Additional context**
This has actually been a problem for some time but has only become noticeable after we added Ubuntu 20.04 to CI.

**Comment by sphh** [comment]
This not only happens on the nightly builds, but also with https://github.com/xournalpp/xournalpp/releases/download/1.0.18/xournalpp-1.0.18-Debian-buster-x86_64.deb and https://github.com/xournalpp/xournalpp/releases/download/1.0.18/xournalpp-1.0.18-Ubuntu-xenial-x86_64.deb

**Comment by rajaramk8** [comment]
@sphh  and Technius, 
    I was able to successfully complile on 20.04 just now. 
This is what i did to get past the libzip4 issue:
In the file at:
https://github.com/xournalpp/xournalpp/blob/master/CMakeLists.txt
Line 353:  
   Change libzip4  to libzip5  

and go from there.

**Comment by Technius** [comment]
This was a bug in Azure Pipelines, so nightly builds have been fixed. For stable, the next release 1.0.19 will have correctly built 20.04 packages.

**Comment by sphh** [comment]
Thanks. Any idea, when 1.0.19 will be rolled out?

**Comment by Technius** [comment]
Within the next two weeks; the exactly time will depend on how much free time I have.

**Comment by Technius** [comment]
This has already been fixed for a few months, just forgot to close the issue
