### ISSUE TITLE
Ongoing pages

### ISSUE THREAD

**Issue by munchkin99** [xournalpp/xournalpp#2079]
I have seen this on other similar software. When you arrive at the end of a page with what you are writing, a new page is generated automatically. So while writing you don't have to press the "add new page" button everytime you have finished a page.

Maybe this is already a feature but i haven't found it yet.

**Comment by rolandlo** [comment]
This is not already a feature in Xournal++. The behavior of adding a new page when arriving at the end of a page looks controversial to me. I certainly don't want that to happen when I annotate a pdf background and also do not always want it when working without pdf background. 
A future version of Xournal++, currently in development, will support infinity pages. This may be to your liking.
