### ISSUE TITLE
Setting default background

### ISSUE THREAD

**Issue by lhpt** [xournalpp/xournalpp#2080]
**Is your feature request related to a problem? Please describe.**
Maybe I oversaw it, but a feature to set a default background would be nice.
Every time when I start the program or create a new document the background is 
set to lined paper. As I almost exceptionally use squared paper I have to change the 
background every time.

**Describe the solution you'd like**
I'm thinking of a setting to set the default background (maybe in the defaults tab)

**Describe alternatives you've considered**
Saving an empty xopp document and copying it every time I want to create a new document.

**Comment by 4VRDriver** [comment]
AFAIK there should be a setting under Journal > Configure Page Template

**Comment by lhpt** [comment]
Thank you very much!
