### ISSUE TITLE
The object selection by tapping works only on the first layer.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#2081]
OS: Arch Linux
 - libgtk: 3.24.20
 - Version of Xournal++:  1.0.18

**Describe the bug**
There are two relating issues.
(1) The object selection by tapping works only on the first layer.
(2) On higher layer, tapping  an object of the first layer makes a copy of the object on current layer.

**To Reproduce**
Step 1. Draw something on the first layer. (Refer to the object as AAA.)
Step 2. Create second layer, and draw something on the layer. (Refer to the object as BBB.)
Step 3. On the second layer, tap the object BBB in object selection mode. You can't select the object.
Step 4. On the second layer, tap the object AAA in object selection mode. Then, a copy of AAA appears on the second layer.
Cf. 1. On the first layer, tapping the object BBB is ignored.
Cf. 2. On the first layer, tapping the object AAA select the object AAA.

**Expected behavior**
1. On the second layer, tapping the object BBB should select the object BBB.
2. On the second layer, tapping the object AAA should be ignored.

**Comment by rolandlo** [comment]
@tattsan Please checkout PR #2136 and check if it resolves the bug.

**Comment by tattsan** [comment]
Thanks @rolandlo !  It works fine!
I use the stable release 1.0.18, and modified the PR a bit to make it applicable to the release.
