### ISSUE TITLE
copy from background

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#2083]
**Is your feature request related to a problem? Please describe.**
As a student I often want to work on exercise sheeds with xournalpp, but often there is no or too less space on the pdf we get to work on.

**Describe the solution you'd like**
Therefore, it would be really nice to be able to copy things from the background layer (which is currently not possible from what I experienced) so that one can copy the question to work on to another sheed where is enough place.

**Describe alternatives you've considered**
- I already considered adding a bigger white border around the content in the pdf, but this mostly isn't enough place and it is difficult to add this border graphed.
- I already tried setting the view to one row to be able to simulate some kind of infinite space, but without the ability to copy parts of the question to work on this doesn't really help, since you're always scrolling to the left and right.

**Additional context**
I think this is something that would be very valuable too in upcoming exams written digitally.

Since I'm afraid my description isn't that clear, I added some pictures below, what I mean.
![2020-06-23-102210_1920x1080_scrot](https://user-images.githubusercontent.com/60581958/85379876-c9146680-b52b-11ea-8e90-5f1c2a7178fe.png)
This is just an example exercise I took from the Internet. This would then be the sheed I get.

![2020-06-23-102242_1920x1080_scrot](https://user-images.githubusercontent.com/60581958/85379879-ca459380-b52b-11ea-82d0-608f724b53ba.png)
Then I'd like to select an Area from the sheed, copy it and paste it on another page.

![2020-06-23-102252_1920x1080_scrot](https://user-images.githubusercontent.com/60581958/85379883-ca459380-b52b-11ea-9793-d50677c189fc.png)
This is what I'd wish to be able to work on afterwards.

**Comment by rolandlo** [comment]
You can always take a screenshot of a selected area using your favorite screenshot tool and paste it into the document where you want it to be. It is not a perfect solution, but it may be enough for your purpose. 
Moreover using a plugin as described in #2024 you might save some clicks. See also #2037.

**Comment by atticus-sullivan** [comment]
Thanks for the quick response,
