### ISSUE TITLE
Some texts in PDF are missing

### ISSUE THREAD

**Issue by chensun-hep** [xournalpp/xournalpp#2084]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.18-1ubuntu1
 - Version of Xournal++: 1.0.16, 07cb970f
 - Installation method: snapstore

**Describe the bug**
When Xournal++ opens certain PDF's, some texts are missing. In particular, this happens with plots inside PDF's, with labels and axis ticking missing. Now sure how much this is related to #1878. 

**To Reproduce**
1. Download either https://arxiv.org/pdf/1709.07882.pdf, 
2. open the file with Xournalpp, locate Fig. 1, and Fig. 3
3. open the file with anything else, say Okular, locate the same figure for comparison.
4. same behavior is experienced with this PDF file as well: or https://arxiv.org/pdf/hep-ph/0610203.pdf, Figs. 2, 4, 5.

**Comment by rolandlo** [comment]
Can you post screenshots showing the difference? I tried with Xournal++, Okular and Evince and couldn't spot any difference (in Fig. 1 and Fig. 3 of the first pdf-file).

**Comment by chensun-hep** [comment]
![Screenshot from 2020-06-23 20-42-17](https://user-images.githubusercontent.com/57478178/85436721-293df380-b592-11ea-9d49-262b7aa83dd2.png)
using Xournalpp, vs
![Screenshot from 2020-06-23 20-43-44](https://user-images.githubusercontent.com/57478178/85436815-4f639380-b592-11ea-8897-cc6194f0811a.png)
using okular. 

I'll be very happy to find out it's related to my local setup.

**Comment by rolandlo** [comment]
So in my setup (Version 1.1.0+dev with libgtk 3.24.18 on Ubuntu 20.04) I see the version you posted below, which is (I assume) the one you see in Okular. 
You could try installing the latest version (1.1.0+dev) from ppa (see [main page](https://github.com/xournalpp/xournalpp) under "Ubuntu and derivatives") or at least update to the latest stable version 1.0.18 (see [releases page](https://github.com/xournalpp/xournalpp/releases)). I cannot guarantee it will solve the problem, but there is a good chance it does.

**Comment by chensun-hep** [comment]
I'm checking out the release page and just realized that there's only deb for Ubuntu Xenial, which is not compatible with 20.04. The AppImage also doesn't run with the following crash error: 

~/Downloads$ ./xournalpp-1.0.18-x86_64.AppImage 

** (xournalpp:95365): WARNING **: 23:07:39.754: Failed to load "colornames.ini" (/home/chen/.xournalpp//colornames.ini): No such file or directory

ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (xournalpp:95365): WARNING **: 23:07:39.965: [Crash Handler] Crashed with signal 11

** (xournalpp:95365): WARNING **: 23:07:39.973: [Crash Handler] Wrote crash log to: /home/chen/.xournalpp/errorlogs/errorlog.20200623-230739.log

** (xournalpp:95365): WARNING **: 23:07:40.167: Trying to emergency save the current open document…

** (xournalpp:95365): WARNING **: 23:07:40.167: Successfully saved document to "/home/chen/.xournalpp//emergencysave.xopp"



I wonder if compiling from the source is the only way if I don't go with the nighly release ppa. If that's the case, could you point me to the instruction of compiling the source, e.g. prerequisites etc.?

**Comment by rolandlo** [comment]
Installation from source is highly discouraged, but the build (and installation) process is described on this [wiki page](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md). Another alternative would be to install the [flatpak](https://flathub.org/apps/details/com.github.xournalpp.xournalpp) (version 1.0.18, which might just work fine for you).

**Comment by chensun-hep** [comment]
just tried the ppa and I can verify the problem is fixed in 1.1.0+dev. Thanks.
