### ISSUE TITLE
Releases Page - add Link to Main README.md

### ISSUE THREAD

**Issue by niebert** [xournalpp/xournalpp#2089]
Due to removal of the release page from the GitHub-Userinterface, I want to request to add the release page link https://github.com/xournalpp/xournalpp/releases  at the beginning of the README.md e.g. by

* [Download Xournal++ Releases for Window, MacOSX, Linux, AppImage,...](https://github.com/xournalpp/xournalpp/releases)

Students battle a bit to find the binary links now. Thank you very much for your support

**Comment by pktiuk** [comment]
But the Release page was not deleted, its link was just moved.
![image](https://user-images.githubusercontent.com/45544416/87819261-35a12d80-c86c-11ea-9e72-7b74f1b05a50.png)

Moreover we are currently building new page for Xournal++, and that site will be focused on casual (not familiar with Github) users.  https://github.com/xournalpp/xournalpp.github.io

**Comment by niebert** [comment]
Thank you - Having a website for users (not developers) will help 
My question was just to add an extra link on the `README.md`  e.g. with
```markdown
[Download Xounral++](https://github.com/xournalpp/xournalpp/releases) 
```
That will not add additional maintenance for README.md if new releases are deployed.  Or is the default release URL depricated in general for all  Github-projects in the future (e.g. https://github.com/userA/softwareB/releases) ?

**Comment by rolandlo** [comment]
If you click on **Releases** you get exactly to the releases page (not specific to a particular release).
The section on the right is automated, see:
![grafik](https://user-images.githubusercontent.com/40485433/88535076-9c131200-d009-11ea-8098-05585896d444.png)
