### ISSUE TITLE
Pressure sensitivity no longer works

### ISSUE THREAD

**Issue by usrtrv** [xournalpp/xournalpp#209]
Pressure sensitivity no longer functions in xournal++/xournal but still functions correctly in Krita and gives correct looking 'xinput test' output.

I filed a bug report with the relevant package update here: https://bugzilla.redhat.com/show_bug.cgi?id=1435061
And received this response: "fwiw, the issue isn't a xorg-libinput update but rather that we started defaulting to libinput for tablets too, previously you used the evdev driver"

**Comment by wbrenna** [comment]
I don't have a redhat system to replicate this - did you go to Preferences->Input and try all of the configuration options under Extended Input? I'm a little surprised that xinput breaks as well...

**Comment by usrtrv** [comment]
No change with Extended Input options except Ignoring core events. Which disabled it all together.

**Comment by nairaner** [comment]
Im using Arch with libinput and for me it detects pressure correctly, althought sometimes I have to restart xournalpp for it to work

**Comment by albflo** [comment]
did some solve this problem?

**Comment by andreasb242** [comment]
The master is now on GTK3, with a lot of input refactoring.
Therefore I close this issue. If there is still an issue with the new GTK3 Build, create a new ticket.
