### ISSUE TITLE
AppImage 1.0.18 crash on start with numerous errors with Ubuntu 20.04 

### ISSUE THREAD

**Issue by deddc23efb** [xournalpp/xournalpp#2096]
(Please complete the following information, and then delete this line)

**Affects versions : AppImage 1.0.18 - others not test
 - OS: Linux Hostname 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - (Linux only) Desktop environment: Ubuntu 20.04 standard desktop install
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
This command doesn't work:
./xournalpp-1.0.18-x86_64.AppImage --version

** (xournalpp:39810): ERROR **: 09:14:51.846: Unknown option --version
/tmp/.mount_xournaHSzkLY/AppRun: line 21: 39810 Trace/breakpoint trap   (core dumped) "$APPDIR"/usr/bin/xournalpp $@

 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
This command doesn't work.  
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
AppImage 1.0.18

**Describe the bug**
AppImage does not run. Crashes at startup with all sorts of problems including complaining about Jack not being present - which I would be very reluctant to install given how it screws up a sound system.

Startup stderr output:

** (xournalpp:39632): WARNING **: 09:12:12.644: Failed to load "colornames.ini" (/home/username/.xournalpp//colornames.ini): No such file or directory

ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (xournalpp:39632): WARNING **: 09:12:12.983: [Crash Handler] Crashed with signal 11

** (xournalpp:39632): WARNING **: 09:12:12.998: [Crash Handler] Wrote crash log to: /home/username/.xournalpp/errorlogs/errorlog.20200704-091212.log

** (xournalpp:39632): WARNING **: 09:12:13.385: Trying to emergency save the current open document…

** (xournalpp:39632): WARNING **: 09:12:13.386: Successfully saved document to "/home/username/.xournalpp//emergencysave.xopp"

Errorlog Output:
Date: Sat Jul  4 09:12:12 2020
Error: signal 11
[bt]: (0) /tmp/.mount_xournacK21Mu/usr/bin/xournalpp() [0x5b97b8]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fa1949e6210]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(+0x18e495) [0x7fa194b2e495]
[bt]: (3) /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1baa5) [0x7fa191b24aa5]
[bt]: (4) /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1bf5c) [0x7fa191b24f5c]
[bt]: (5) /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1c151) [0x7fa191b25151]
[bt]: (6) /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(png_process_data+0x3b) [0x7fa191b252cb]
[bt]: (7) /tmp/.mount_xournacK21Mu/usr/lib/gdk-pixbuf-2.0/loaders/libpixbufloader-png.so(+0x2b99) [0x7fa17b57cb99]
[bt]: (8) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0x10281) [0x7fa196299281]
[bt]: (9) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_loader_close+0x175) [0x7fa196299b15]
[bt]: (10) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0xd233) [0x7fa196296233]
[bt]: (11) /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_new_from_stream+0x31) [0x7fa1962972c1]
[bt]: (12) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1dd994) [0x7fa196aef994]
[bt]: (13) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_info_load_icon+0x68) [0x7fa196af3198]
[bt]: (14) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_theme_load_icon_for_scale+0x108) [0x7fa196af33f8]
[bt]: (15) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0xb92c6) [0x7fa1969cb2c6]
[bt]: (16) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0xb9882) [0x7fa1969cb882]
[bt]: (17) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_set_render_icon_surface+0xe) [0x7fa1969cc07e]
[bt]: (18) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1d9f46) [0x7fa196aebf46]
[bt]: (19) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1da7af) [0x7fa196aec7af]
[bt]: (20) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1dabbb) [0x7fa196aecbbb]
[bt]: (21) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1edcf2) [0x7fa196affcf2]
[bt]: (22) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1eded7) [0x7fa196affed7]
[bt]: (23) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (24) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (25) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (26) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x120186) [0x7fa196a32186]
[bt]: (27) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1201fb) [0x7fa196a321fb]
[bt]: (28) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (29) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (30) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (31) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x11348d) [0x7fa196a2548d]
[bt]: (32) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (33) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (34) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (35) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x11348d) [0x7fa196a2548d]
[bt]: (36) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (37) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (38) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (39) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x24eda8) [0x7fa196b60da8]
[bt]: (40) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a87d4) [0x7fa196bba7d4]
[bt]: (41) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (42) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (43) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x11348d) [0x7fa196a2548d]
[bt]: (44) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (45) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (46) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (47) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x11348d) [0x7fa196a2548d]
[bt]: (48) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
[bt]: (49) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (50) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height+0x8a) [0x7fa196bba08a]
[bt]: (51) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x10f8a1) [0x7fa196a218a1]
[bt]: (52) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a87d4) [0x7fa196bba7d4]
[bt]: (53) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (54) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height+0x8a) [0x7fa196bba08a]
[bt]: (55) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x368342) [0x7fa196c7a342]
[bt]: (56) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a87d4) [0x7fa196bba7d4]
[bt]: (57) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
[bt]: (58) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
[bt]: (59) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a8d37) [0x7fa196bbad37]
[bt]: (60) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x369d93) [0x7fa196c7bd93]
[bt]: (61) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x36cb00) [0x7fa196c7eb00]
[bt]: (62) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7fa19605c802]
[bt]: (63) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x28962) [0x7fa196070962]
[bt]: (64) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x10ae) [0x7fa19607bb9e]
[bt]: (65) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fa19607c0d3]
[bt]: (66) /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_show+0xa5) [0x7fa196c6e715]
[bt]: (67) /tmp/.mount_xournacK21Mu/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x6af) [0x4ac22f]
[bt]: (68) /tmp/.mount_xournacK21Mu/usr/bin/xournalpp(main+0x30) [0x480560]
[bt]: (69) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fa1949c70b3]
[bt]: (70) /tmp/.mount_xournacK21Mu/usr/bin/xournalpp(_start+0x29) [0x480719]

Try to get a better stracktrace...
[bt] #1 /tmp/.mount_xournacK21Mu/usr/bin/xournalpp() [0x5b9b8d]
/home/vsts/work/1/s/build/../src/util/CrashHandlerUnix.h:102
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fa1949e6210]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(+0x18e495) [0x7fa194b2e495]
??:0
[bt] #4 /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1baa5) [0x7fa191b24aa5]
??:0
[bt] #5 /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1bf5c) [0x7fa191b24f5c]
??:0
[bt] #6 /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(+0x1c151) [0x7fa191b25151]
??:0
[bt] #7 /tmp/.mount_xournacK21Mu/usr/lib/libpng12.so.0(png_process_data+0x3b) [0x7fa191b252cb]
??:0
[bt] #8 /tmp/.mount_xournacK21Mu/usr/lib/gdk-pixbuf-2.0/loaders/libpixbufloader-png.so(+0x2b99) [0x7fa17b57cb99]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0x10281) [0x7fa196299281]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_loader_close+0x175) [0x7fa196299b15]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(+0xd233) [0x7fa196296233]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_new_from_stream+0x31) [0x7fa1962972c1]
??:0
[bt] #13 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1dd994) [0x7fa196aef994]
??:0
[bt] #14 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_info_load_icon+0x68) [0x7fa196af3198]
??:0
[bt] #15 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_theme_load_icon_for_scale+0x108) [0x7fa196af33f8]
??:0
[bt] #16 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0xb92c6) [0x7fa1969cb2c6]
??:0
[bt] #17 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0xb9882) [0x7fa1969cb882]
??:0
[bt] #18 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_icon_set_render_icon_surface+0xe) [0x7fa1969cc07e]
??:0
[bt] #19 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1d9f46) [0x7fa196aebf46]
??:0
[bt] #20 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1da7af) [0x7fa196aec7af]
??:0
[bt] #21 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1dabbb) [0x7fa196aecbbb]
??:0
[bt] #22 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1edcf2) [0x7fa196affcf2]
??:0
[bt] #23 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1eded7) [0x7fa196affed7]
??:0
[bt] #24 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
??:0
[bt] #25 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
??:0
[bt] #26 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
??:0
[bt] #27 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x120186) [0x7fa196a32186]
??:0
[bt] #28 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x1201fb) [0x7fa196a321fb]
??:0
[bt] #29 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a871b) [0x7fa196bba71b]
??:0
[bt] #30 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(+0x2a89af) [0x7fa196bba9af]
??:0
[bt] #31 /tmp/.mount_xournacK21Mu/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa6) [0x7fa196bbac76]
??:0

**To
 Reproduce**
1. run the appimage on Ubuntu 20.04
2. there is no step 2

**Expected behavior**
Expected it to run.

**Screenshots of Problem**
None

**Additional context**
None

**Comment by rolandlo** [comment]
There are open issues with the AppImage (which is only there since 1.0.18), see  #1978. It will most likely not be fixed soon. I would currently recommend you to try another installation method. For Ubuntu 20.04 you may want to install from the ppa as described under _Ubuntu and derivatives_ on the [main page](https://github.com/xournalpp/xournalpp).
