### ISSUE TITLE
Horizontal View

### ISSUE THREAD

**Issue by g4ugm** [xournalpp/xournalpp#2097]
I have been using the old xournal application which is now old to display music  for playing on my Organ. The one thing that makes it usable is the horizontal scroll of pages which is not in xournal++. 

On a 22" screen I can get three pages side-by-side and I can scroll sideways without any of this even/odd pairing. In this world of widescreen, this seems to make sense.

Was this mode there in xournal++ and removed, or just never implemented?

**Comment by rolandlo** [comment]
It is still there in Xournal++, just refined.  Choose (in the menubar) view -> Cols/Rows -> Set Rows and set the number of rows you wish (for example just one). Then you can scroll through your pages sideways. That's what you have been looking for, isn't it?

**Comment by g4ugm** [comment]
Rolandlo. Yes that is what I was looking for. Just about perfect now. Is there a "zoom to page height" hidden anywhere? I know I can do that manually? 
Dave

**Comment by rolandlo** [comment]
I don't think there is a "zoom to page height". You will have to do it manually.

**Comment by g4ugm** [comment]
No problems. If get desperate I can clone the source and add a one.,.
