### ISSUE TITLE
I loss all my notes, who can help me

### ISSUE THREAD

**Issue by FantDing** [xournalpp/xournalpp#2099]
**Affects versions :**
 - OS: manjaro 20.0
 - (Linux only) Desktop environment: KDE 5.70.0
 - Which version of libgtk do you use
 - Version of Xournal++: 1.0.18
 - Installation method: pacman

**Describe the bug**
All notes lost, but I can see that `xopp` file has `1.7MiB` size

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/21337200/86548517-48178f00-bf6f-11ea-87d5-19bfbf95604e.png)

**Comment by rolandlo** [comment]
If you upload your .xopp-file here (renamed as a .txt-file) or send it to me via gitter.im I will take a look at it and try to help you.

**Comment by FantDing** [comment]
I dont know how to upload file, you can visit this [page](https://cowtransfer.com/s/d9b4063a1e4a4e) to download. Thanks!!!

**Comment by rolandlo** [comment]
@FantDing 
Can you please tell me, how many pages the underlying pdf-document has and what the first annotated page is?
In your xopp-file there are 726 pages and only pages 63 - 160 have annotations.

**Comment by FantDing** [comment]
@rolandlo There are actually 726 pages in the pdf, but I annotated almost from page 35 to 220

**Comment by rolandlo** [comment]
@FantDing 
You may check yourself, that your xopp-file contains only annotations for page 63, 103-112, 117-118, 120-128, 131-132, 134-144, 146-149, 151-153, 155-156, 158 and 160 of the pdf-document. Between page 127 and 128 of the pdf you have an additional page in your xopp-file without pdf-background, These annotations are all visible from within Xournalpp (at least on my computer). You can also check it by making a copy of your .xopp-file, renaming the ending to .gz, and extracting it (in the file explorer or in the terminal via `gunzip` FILENAME.gz).

Unless some annotations are shifted (for which I see no evidence), there is simply no way to bring back annotations for the other pages just from the .xopp-file you provided. If you think you have more annotations you should check your autosave files (in ~/.xournalpp/autosave).
