### ISSUE TITLE
exchange the background of a journal

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#2103]
**Is your feature request related to a problem? Please describe.**
When I write on a script that changes slightly from time to time, it would be very convenient to be able to exchange the background pdf with the updated pdf (this might cause trouble if very much changed so the annotations aren't visible any more, but if only some words changed this causes no trouble) so that one have the slightly updated pdf (e.g. a Script) with the Annotations one have made in the past.

**Describe the solution you'd like**
I'd love a feature that allows the user to simply change the pdf Background of a .xopp File. (From my perspective this sounds very easy to implement too and would help me when studying with the sometimes slightly changing script of a Lecture)

**Describe alternatives you've considered**
I tried to find a way to somehow `diff` pdfs to be able to apply the diff containing the changes or the annotations to the pdf, but obviously diffing pdfs is very hard an so I didn't found something suitable.

**Additional context**

**Comment by rolandlo** [comment]
As long as you don't change the number of pages you can simply overwrite the pdf with the updated one with no issues. All you need to do is to reopen the xopp-file after the pdf has been updated (see e.g. issue #1527). 
It gets much more complicated if the page number changes (see e.g. issue #1588). This will be solved with the new file format. A workaround would be to keep the number of pages constant by adding empty pages.

**Comment by Dewkyz** [comment]
If I remember correctly it is possible, though not really intuitive. Enable the Autoloading Journals option ('If you open a PDF and there is a Xournal file with the same name it will open the xoj file."). That means that if you change the name of your new PDF it will automatically be used as the background. Not sure if it is an intended feature but I remember using it (could be wrong though).

**Comment by atticus-sullivan** [comment]
Oh right this works, but only when staying in the same Directory (seams like the `.xopp` File contains some kind of absulute Path not a relative one (what would be more convenient for this use case)

This will work for now for me, but in my opinion this could/should be implemented in a more intuitive way (when chosing a PDF with doesn't have enough pages one could simply warn the user (right now from what I've seen, xournalpp just duplicates the first page of the new PDF if it has fewer pages) or error the user).

**Comment by rolandlo** [comment]
@atticus-sullivan 
Yes, the .xopp-file contains the absolute path of the underlying pdf. Changing this (although simple) would require a change of file format. A new file format is already in the making, but with many more enhancements. See also issue #1725, where the same enhancement was requested.

**Comment by atticus-sullivan** [comment]
Oh, thanks didn't saw this.
