### ISSUE TITLE
Enable PPA for groovy and devel series

### ISSUE THREAD

**Issue by black-puppydog** [xournalpp/xournalpp#2107]
I love that you have a PPA for this, so thank you in any case for all the work, and packaging the application properly, it is much appreciated!

I just switched to the `devel` series of Ubuntu which always tracks the *next* release (so, currently `groovy` which will become 20.10) but the PPA doesn't offer builds for either of the two. 
If it's not too much of a hassle, it would be cool to always offer builds for the upcoming Ubuntu releases too. Apart from being useful for me (:innocent:) it might also help prevent bad surprises when the release happens, because builds would likely start failing before that. 

Again: only if it's not a major project. I know next to nothing about Ubuntu packaging, and even less about how launchpad and PPAs work and what this would mean.

**Comment by rolandlo** [comment]
I can only make @andreasb242 aware of this idea.

**Comment by apandada1** [comment]
The stable PPA hosts packages for Groovy. https://code.launchpad.net/~apandada1/+archive/ubuntu/xournalpp-stable

It also hosts packages for ARM and PowerPC.

**Comment by black-puppydog** [comment]
thanks @apandada1!
would still be cool to run the bleeding edge on the bleeding edge :D

**Comment by apandada1** [comment]
To enable packages for Groovy, one has to add Groovy to distribution series in the packaging recipe for the PPA https://code.launchpad.net/~andreasbutti/+recipe/xournalpp-daily, and Launchpad will automatically build it.

Only the owner of the recipe can do that.

**Comment by rolandlo** [comment]
The PPA packages for Groovy Gorilla (Ubuntu 20.10) and Hirsute Hippo (Ubuntu 21.04) have been added. Now we have the bleeding edge on the bleeding edge. :-) I have already tested out the Groovy Gorilla package and it seems to work fine.

The Devel series is not supported by launchpad, so it can't be added.
