### ISSUE TITLE
Blackboard-type background

### ISSUE THREAD

**Issue by JCBustamante** [xournalpp/xournalpp#2109]
I would like to have the background for a notebook looking like a blackboard (old ways : chalk dust and the like). I tried to set an image I have as background, both with "Configure page temlate", and with "Paper background -> Image". In all cases the app would crash after a few seconds.

It would be nice to add a blackboard style background, perhaps with tiiny little dots so that one can keep writing aligned. An option would be to have the "dotted" background with even smaller dots. I use it with a custom dark grey color.

**Comment by rolandlo** [comment]
@JCBustamante 
Clearly the app should not crash if you set the paper background. Please provide a bug report filling out the template form (with infos on OS, Xournal++ version etc.) and share your image, so we can try to reproduce the bug. 
Once the bug is fixed it will be much easier to see how we can further enhance to get help with alignment.

**Comment by JCBustamante** [comment]
I played around with xournal a bit. I had two version of it installed, one from the ubuntu asoftware center, and the other installed via ppa. Once I removed the one from the software center, everything went fine. Pretty strange. [Here](https://www.dropbox.com/s/nhva48umb5cbdc7/Fond-tableau.pdf?dl=0) is the image I want to use as background (this works now). The only enhancement on this side would be to ad very subtle llines like those in the "graph" paper, but with the squares much bigger.

**Comment by rolandlo** [comment]
Probably you installed the snap version from the software center. In my experience the ppa works best (it is the latest greatest; the snap version is only 1.0.16). If you had both versions installed, maybe the snap version got executed by default. I am glad that now everything goes fine. 
Now I suggest to add those lines (or dots, if you prefer) directly onto your pdf. That is easy to do with LaTeX (modify as you wish):

```
\documentclass[a4paper,landscape]{article}
\usepackage{tikz}
\pagestyle{empty}
\usepackage{background}
\backgroundsetup{scale = 1, angle = 0, opacity = 0.2, contents = {\includegraphics[width = \paperwidth, height = \paperheight]{Fond-tableau.pdf}}}

\newlength{\gridsize}
\setlength{\gridsize}{0.19680555555555555in} % that's 14.17/72 inch, the standard grid size used in Xournal++
\tikzset{dashed lines/.style={gray!75, very thin, dotted}}
	
\begin{document}

\newcommand{\factor}{2} % modify this if you want to have a smaller/larger grid

\begin{tikzpicture}[remember picture, overlay]
\draw[style=dashed lines,step=\factor*\gridsize,shift={(current page.north west)}] (current page.north west) grid +(\paperwidth,-\paperheight);
\end{tikzpicture}

\end{document}
```
