### ISSUE TITLE
Right hand notetaking on windows not showing snapshot of all pages

### ISSUE THREAD

**Issue by mazhar897** [xournalpp/xournalpp#2110]
I was using the right hand notetaking toolbar. Somehow the column with the snapshot of all the pages vanished. How would I get that back?

**Comment by rolandlo** [comment]
Usually you would just use the menu view -> show sidebar (or hit F12). Does that solve the problem?

**Comment by MichelReims** [comment]
And how configure drop-down menus for right handers (Windows 7 or 10)?

**Comment by rolandlo** [comment]
@MichelReims What exactly do you mean? You may want to ask your question on [gitter.im](https://gitter.im/xournalpp/xournalpp).

**Comment by MichelReims** [comment]
In Windows, there is a parameter in Tablet PC for right or left handers. It works with almost all windows applications but not with xournalapp

**Comment by mazhar897** [comment]
@rolandlo Thanks. It worked.
