### ISSUE TITLE
Stop showing unwanted menues with webrtc applicatons.

### ISSUE THREAD

**Issue by s1-ranjan** [xournalpp/xournalpp#2113]
**Is your feature request related to a problem? Please describe.**
I am trying to use xournalpp with bigbluebutton under the share the screen, but I wish to share only the drawing area under the red border with the bigbluebutton, but as of now I am able to share the whole screen of the applications including the menus.

**Describe the solution you'd like**
I wish to show only the drawing area of the xournalpp with bigbluebutton or with any webrtc application.

**Comment by cbm755** [comment]
I'm guessing this is off-topic for xournal++ dev's...  Would have to be supported by your browser or your OS or both.

Just FYI: I use Open Broadcast Studio (OBS) to capture the Xournal++ window, then crop it within OBS.  I also compose my webcam input into the feed.  This is a bit finicky to setup on GNU/Linux but works well enough with Jitsi and proprietary alternatives (and presumably would work with BigBlueButton too).

**Comment by s1-ranjan** [comment]
Thanks @cbm755 , for the information but for my me setting up OBS is not possible as my hardware doesn't fulfills the requirements of running OBS, Well I find something called Open Board,  I found this application useful for creating videos, but I don't find any way to share only the whiteboard area with the BBB.

**Comment by rolandlo** [comment]
You can actually remove the sidebar with F12 and the menubar with F10. If you use the empty toolbar you will only see the titlebar of the app and the drawing area.

**Comment by s1-ranjan** [comment]
Thanks @rolandlo for this information.

**Comment by rolandlo** [comment]
@s1-ranjan Now things have become easier (if you install from PPA): Use the floating toolbox, remove the sidebar with F12, the toolbar with F9 and go into full screen mode with F11. There is still some empty space around the document, but that may be removed in the near future as well, see #2025.
