### ISSUE TITLE
change latex font size

### ISSUE THREAD

**Issue by fugata** [xournalpp/xournalpp#2115]
My document has a mix of handwriting + typed text + latex.   I need to use 12-15 point fonts for the typed text, but the latex fonts are too small.

In (open)  issue #1852 I came across a reference to "standalone.cls" and "standalone.cfg".   But I could not find any information on how to implement these, and whether or not these files will affect my normal (pdf)latex setup.  And since my main concern is with font size, don't we normally do that at the beginning like

    \documentclass[12pt]{article}

in which case how might these custom config files come into play?

Many thanks for your help.

**Comment by rolandlo** [comment]
Yes, modifying standalone.cfg (or standalone.cls) as suggested in issue #1852 will affect your (pdf)latex setup that you use in normal tex-files outside of Xournal++. However I don't think changing font size is a (normal) configuration option for the standalone.cfg file. Correct me if I am wrong @tattsan

PR #1952 is likely getting merged this week. Then you will have a global template file, where you can customize font size and whatever you want, without affecting your (pdf)latex setup outside of Xournal++.

Meanwhile your options include: 
- start every tex-formula with $\large$ (which is 12pt) or $\Large$ (which is 14.4pt)
- checkout the PR and build from source
- just wait for the PR to be merged and install from PPA thereafter (assuming you are on Ubuntu or derivative)

**Comment by fugata** [comment]
Thanks

> Yes, modifying standalone.cfg (or standalone.cls) as suggested in issue #1852 will affect your (pdf)latex setup that you use in normal tex-files outside of Xournal++. However I don't think changing font size is a (normal) configuration option for the standalone.cfg file. Correct me if I am wrong @tattsan
> 
> PR #1952 is likely getting merged this week. Then you will have a global template file, where you can customize font size and whatever you want, without affecting your (pdf)latex setup outside of Xournal++.

Thanks!  I look forward to the new version.  (I'm using ubuntu ppa; I assume I will receive the update automatically, right?)

> Meanwhile your options include:
> 
> * start every tex-formula with $\large$ (which is 12pt) or $\Large$ (which is 14.4pt)
> * checkout the PR and build from source
> * just wait for the PR to be merged and install from PPA thereafter (assuming you are on Ubuntu or derivative)

\large and \Large work.  Interestingly \huge does not.

I have a somewhat related follow-up question:  Is there a way to "undo" the latex command?  --- as in after typing in the latex code, process it and pasting the image onto the document, is there a way to modify the initial latex code and generate a new image?  THANKS!

**Comment by rolandlo** [comment]
> Thanks! I look forward to the new version. (I'm using ubuntu ppa; I assume I will receive the update automatically, right?)
Yes, you will get it automatically.
> 
> > Meanwhile your options include:
> > 
> > * start every tex-formula with $\large$ (which is 12pt) or $\Large$ (which is 14.4pt)
> > * checkout the PR and build from source
> > * just wait for the PR to be merged and install from PPA thereafter (assuming you are on Ubuntu or derivative)
> 
> \large and \Large work. Interestingly \huge does not.
That's a bit strange. It works for me. Have you checked it in your favorite LaTeX-editor?
> 
> I have a somewhat related follow-up question: Is there a way to "undo" the latex command? --- as in after typing in the latex code, process it and pasting the image onto the document, is there a way to modify the initial latex code and generate a new image? THANKS!
Yes, there is. I do it with the selection tool "choose object" double clicking on the LaTeX image displayed.

**Comment by Rmano** [comment]
Notice that the LaTeX size commands `\large`, `\Huge` etc. **do not work** inside a formula. You have to issue them **before** the formula starts, and this is why you need the couple of `$` at the start: the first one *exits* math mode, than we change the size, and then we enter math mode again.

**Comment by fugata** [comment]
> > \large and \Large work. Interestingly \huge does not.
> 
> That's a bit strange. It works for me. Have you checked it in your favorite LaTeX-editor?

I use emacs so I don't know how that comes into play.  In any case, \huge etc works in my norm (pdflatex) setup.

> Yes, there is. I do it with the selection tool "choose object" double clicking on the LaTeX image displayed.

Thanks --- that works beautifully!

> Notice that the LaTeX size commands `\large`, `\Huge` etc. **do not work** inside a formula. You have to issue them **before** the formula starts, and this is why you need the couple of `$` at the start: the first one _exits_ math mode, than we change the size, and then we enter math mode again.

First, I was wrong --- I could not get a bigger tex output using \large, \Large etc -- the output size stays the same.  Re @Rmano's comment:  I'm not sure I understand your comment.  I tried typing each of the following into xournalpp's mathtex box but the output size stays the same:

  *  \large{x^2}   (ditto for \Large,\huge etc)
  *  $$\large{x^2}  (ditto for \Large, \huge etc)

But if the up-coming update will provide a proper fix that perhaps this is a moot point...

**Comment by rolandlo** [comment]
@fugata 
Neither \large{x^2} nor $$\large{x^2}$$ will work, but $\large$ x^2 will (and similarly $\huge$ x^2 will). As pointed out by Rmano the LaTeX formula within Xournal++ automatically puts you into math mode, so you will have to leave it with the first $ sign (before writing \large, \huge etc.) and enter it again with another $ sign thereafter. If you want to test it in emacs (or another LaTeX editor) you would have to add \\( before your formula and \\) after your formula to get the same situation as in Xournal++. 

So you can test e.g.\\( $\large$ x^2 \\) in emacs which corresponds to $\large$ x^2 in Xournal++.

**Comment by Rmano** [comment]
@fugata `\large` takes no argument and does not work in math mode. It's a font-changing switch: https://www.learnlatex.org/en/lesson-11

**Comment by rolandlo** [comment]
> Thanks! I look forward to the new version. (I'm using ubuntu ppa; I assume I will receive the update automatically, right?)

It took longer than expected, but it is now merged and you will receive it with the ppa.
