### ISSUE TITLE
Drawing with touch works with highlighter, other tools, but not pen tool

### ISSUE THREAD

**Issue by ave-63** [xournalpp/xournalpp#2123]
**Affects versions :**
 - OS: Linux (arch)
 - (Linux only) Desktop environment: X11, XFCE, OpenBox
 - Which version of libgtk do you use: unknown (but arch is up to date)
 - Version of Xournal++: 1.0.18, commit 535d261d
 - Installation method: pacman

**Describe the bug**
Drawing with touch is not working. I have a Lenovo Yoga 460, which has a version of the touch screen that is not compatible with most styli. I bought a stylus that looked like it might be compatible, but it's not, and instead the stylus works like touching with my finger. I still liked it more than the Lenovo stylus so I tried to set it up to draw with touch. I can draw the highlighter with this stylus (and my finger), and the eraser works too, as well as other tools I've tried, but the pen tool does not write with my finger (or this stylus).

**To Reproduce**
I tried toggling a bunch of settings:
Input System -> Enable new input system: Checked or unchecked (same result either way)
Input System -> Input Devices: Tried assigning the touchscreen to pen, as well as the default setting (same result either way)
Touchscreen -> Enable GTK Touch / Scrolling workaround: Checked or unchecked (when checked, I was able to use highlighter, eraser, lasso select, with finger, but not pen with finger. When unchecked, I couldn't use any tools with finger.)

**Expected behavior**
I expected to be able to draw with my finger.

**Additional context**
I am hesitant to submit this issue because it is a much lower priority for me than customizable keyboard shortcuts (issue 919), and I am hoping this doesn't distract a contributor from that, but I feel it is my duty to submit this bug report to help someone fix it some day!

**Comment by rolandlo** [comment]
I experience the same bug on my Lenovo Yoga X1 (3rd gen), no matter what version of Xournal++ I try. However on my Pinephone drawing with touch works with the pen as well. I only have to set the touchscreen input device to "Mouse" in the preferences.

**Comment by bhennion** [comment]
I have the same issue on a Dell Latitude 7410. PR #2435 did not fix it. However, PR #2622 changed the behaviour (and gives a hint of what's happening).

Prior to PR #2622, the pen tool did not draw anything. Actually, inspecting a file, we can see that the stroke is created but has pressure values set to 0 all the way.
Since PR #2622, there is a very thin stroke. (This PR introduced a minimal pressure value).

Enabling pressure inference does not change anything.

It could be that the affected devices are detected as being pressure sensitive (but they are not).

**Comment by rolandlo** [comment]
> t could be that the affected devices are detected as being pressure sensitive (but they are not).

That sounds plausible. Now that you found the cause, I observe that with Pressure sensitivity turned off (in the preferences) touch drawing always worked. Also with filling turned on touch drawing always created filled shapes.

Maybe we would have to modify `InputEvents::translateEvent`. There the pressure is simply copied: 
```c++
   // Copy the pressure data
    gdk_event_get_axis(sourceEvent, GDK_AXIS_PRESSURE, &targetEvent.pressure);
```

We could modify it such that the pressure is `Point::NO_PRESSURE`, if the `sourceEventType` comes from the touchscreen.

**Comment by rolandlo** [comment]
In fact moving the block 
```c++
    // Copy the event sequence if there is any
    if (sourceEventType == GDK_TOUCH_BEGIN || sourceEventType == GDK_TOUCH_UPDATE || sourceEventType == GDK_TOUCH_END ||
        sourceEventType == GDK_TOUCH_CANCEL) {
        targetEvent.sequence = gdk_event_get_event_sequence(sourceEvent);
    }
```in front of the return statement and adding 
```c++
        targetEvent.pressure = Point::NO_PRESSURE;
```
within this block seems to fix the problem.
