### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by mfauvain** [xournalpp/xournalpp#2127]
**Affects versions :**
 - OS: Linux (arch)
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
 - Version of Xournal++: 1.0.18
 - Installation method: pacman

**Describe the bug**
missing two icons - tried many different sets (including default Adwaita)

**To Reproduce**
Add a new page, popup window is missing the two icons for 'Apply to current page' and 'Apply to all pages'

**Expected behavior**
icons should show

**Screenshots of Problem**
![Screenshot from 2020-07-21 19-36-26](https://user-images.githubusercontent.com/14844435/88120844-80cb8100-cb89-11ea-8539-c405edb40292.png)

**Additional context**
Just need to know the name of missing icons...

**Comment by rolandlo** [comment]
The name of the icon you are missing is "gtk-apply".

**Comment by rolandlo** [comment]
And that's how it looks on my system: ![grafik](https://user-images.githubusercontent.com/40485433/88142305-95ddf980-cbf5-11ea-8779-7be16a898f21.png)

**Comment by mfauvain** [comment]
perfect. added now. thx
