### ISSUE TITLE
Grid Snapping broken?

### ISSUE THREAD

**Issue by unhandyandy** [xournalpp/xournalpp#2129]
**Affects versions :**
 - OS: Ubuntu 20.04
 - OpenBox
 -  libgtk 3.24.20
 -  Xournal++: 1.0.6-0~202007200844~ubuntu20.04.1
 - Installation method: apt

**Describe the bug**
Maybe I just don't understand how grad snapping is supposed to work, but it seems to be broken.

**To Reproduce**
Create document with grid bg
Turn on grid snapping
Select line tool
Draw line
Start and end points of line are **not** at grid points

**Expected behavior**
Start and end points of line **are** at grid points

**Screenshots of Problem**
![xournal](https://user-images.githubusercontent.com/2363767/88210614-77dabe00-cc22-11ea-8f26-a058a7998c6c.png)

**Comment by rolandlo** [comment]
Version 1.0.6 is quite an old one. Could you please upgrade and check if the problem remains? 
Moreover there is some tolerance (which you can configure in the settings at least in recent versions), so if you are not within some tolerance to the next grid point, the point will not be snapped to grid. In version 1.1.0+dev (which you can install via the PPA method) setting the "Grid snapping tolerance" to its maximal value 1.0 means that all points will be snapped to the closest grid point.

**Comment by unhandyandy** [comment]
Version 1.0.6 is what is says in synaptic, but in the About window it says 1.1.0+dev, built Jul 20 2020.

It's the grad snapping tolerance setting that I missed.  That fixes it, thanks.
