### ISSUE TITLE
Add blank pdf page in Annotate PDF

### ISSUE THREAD

**Issue by bhavinmoriya** [xournalpp/xournalpp#2132]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 18.4
 - Version of Xournal++ 1.1.0+

**Describe the bug**
I have opened a pdf using  Annotate PDF. Now I want to insert a graph style or ruled page at the end of 1st page. How do I do it. I tried to add page using add page button in the interface. But doing this will add the copy of the page that I am adding page after.

I will be grateful if anybody could help me with this.

cheers,

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.

**Expected behavior**

**Screenshots of Problem**

**Additional context**

**Comment by rolandlo** [comment]
First add a new page (with copied background) and then change the background of the new page (via journal->background). Does that work for you?

**Comment by bhavinmoriya** [comment]
Hi Roland,

Thank you very much for the information. It worked indeed.

Thanks a lot again.



Bhavin Moriya <https://sites.google.com/site/bhavinmoriya/>

Assistant Professor

The Federal University of Viçosa - Brazil.

Departamento de Matemática <http://www.dma.ufv.br/>

Av. P.H. Rolfs, s/n

36570-000 – Viçosa.

Minas Gerais

Brasil.

   My Blog

https://livelifemaverick.blogspot.com/


"Only the gentle are ever really strong."

- James Dean

**Comment by bhavinmoriya** [comment]
Hi Roland!
Finally I made a video on what you taught me. Here it is
https://youtu.be/191XMIg2g_8

Feel free to share it. Critics are more than welcome.
Thanks a lot again.
Bhavin.
