### ISSUE TITLE
Xopp file crashes Xournal++

### ISSUE THREAD

**Issue by createyourpersonalaccount** [xournalpp/xournalpp#2133]
**Affects versions :**
 - Linux Ubuntu 20.04
 - X11
 - libgtk 3.24.20
- Version: commit a320e1c544ab9364f9c7b8c5221b2fe6d1761f77
- Compiled from source

**Describe the bug**
Once the program is closed, when reopened it complains about a crash. I've tried both options (delete file, restore file) to no avail.

**To Reproduce**
1. Open attached file
2. Scroll down to last page
3. Try to erase something with whiteout (don't change the layers)
4. Restart Xournal++

**Expected behavior**
Xournal++ shouldn't complain about a crash
[example.tar.gz](https://github.com/xournalpp/xournalpp/files/4972094/example.tar.gz)

**Note**

- As @tattsan pointed out, my complaint about the eraser not working had to do with extra empty layers that I didn't notice. I edited my bug report to only mention the crash complaint.

- @rolandlo fixed some of the ways in which the crash is reproduced, see the commentshere and PR #2136

**Comment by tattsan** [comment]
There are four layers on the last page. It seems to be nothing on layer 2,3,4.
If you delete these empty layers, you can edit objects again.
Perhaps you hit Ctontrol-L, which create a new layer.

**Comment by createyourpersonalaccount** [comment]
Thank you @tattsan ! 

Xournal++ still says it crashes if you try what I have mentioned above, but if I switch the layers it no longer crashes. I will leave the bug report but edit my original message.

**Comment by rolandlo** [comment]
I can't reproduce the crash by erasing on the last page. However I do get a crash upon quitting the app when I try to select something from the last page with the "select object" selection tool. While selecting I get a warning `"Could not remove element from layer, it's not on the layer!"`, and get the backtrace printed, but only when quitting the app I get the crash. 

Please provide the following info:
- What eraser mode do you use (standard, whiteout or Erase stroke)?
- What messages do you get when starting xournalpp from the console while erasing and quitting the app?
- Can you reproduce the crash by selecting an element on the last page?

Note: On your last page there are four layers. On the first layer you have the actual content. The second and third layer are empty. On the fourth layer you have 4 eraser strokes (produced in whiteout mode), of which one is simply HUGE. The crash may be related to that huge eraser stroke.

**Comment by createyourpersonalaccount** [comment]
- I used Erase stroke.
- Here is the message after attempting an erase:
```
** (com.github.xournalpp.xournalpp:2764): WARNING **: 06:42:40.845: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:2764): WARNING **: 06:42:40.850: [Crash Handler] Wrote crash log to: ~/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200727-064240.log

** (com.github.xournalpp.xournalpp:2764): WARNING **: 06:42:41.067: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:2764): WARNING **: 06:42:41.067: Successfully saved document to "~/.config/com.github.xournalpp.xournalpp//emergencysave.xopp"
```

I did not get a message from the console when I restarted Xournal++, but I was greeted with the gui "Xournal++ crashed last time...".

I have also included the error log file.
[errorlog.20200727-064240.log](https://github.com/xournalpp/xournalpp/files/4981501/errorlog.20200727-064240.log)

- Selecting gives

```
** (com.github.xournalpp.xournalpp:3005): WARNING **: 06:48:33.759: Could not remove element from layer, it's not on the layer!
[bt] #1 ./code/git/xournalpp/build/src/xournalpp(_ZN10Stacktrace16printStracktraceEv+0x14) [0x558f615e6e46]
??:0
[bt] #2 ./code/git/xournalpp/build/src/xournalpp(_ZN5Layer13removeElementEP7Elementb+0x117) [0x558f615a8f4f]
??:0
[bt] #3 ./code/git/xournalpp/build/src/xournalpp(_ZN13EditSelectionC2EP15UndoRedoHandlerP7ElementP11XojPageViewRKSt10shared_ptrI7XojPageE+0x224) [0x558f614be632]
??:0
[bt] #4 ./code/git/xournalpp/build/src/xournalpp(_ZN12SelectObject2atEdd+0xd2) [0x558f6152d8c2]
??:0
[bt] #5 ./code/git/xournalpp/build/src/xournalpp(_ZN11XojPageView20onButtonReleaseEventERK17PositionInputData+0x5d9) [0x558f6152b827]
??:0
[bt] #6 ./code/git/xournalpp/build/src/xournalpp(_ZN15PenInputHandler9actionEndERK10InputEvent+0x100) [0x558f615664ac]
??:0
[bt] #7 ./code/git/xournalpp/build/src/xournalpp(_ZN18StylusInputHandler10handleImplERK10InputEvent+0x3c7) [0x558f61567f39]
??:0
[bt] #8 ./code/git/xournalpp/build/src/xournalpp(_ZN20AbstractInputHandler6handleERK10InputEvent+0x71) [0x558f61561e91]
??:0
[bt] #9 ./code/git/xournalpp/build/src/xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x347) [0x558f61563523]
??:0
[bt] #10 ./code/git/xournalpp/build/src/xournalpp(_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS_+0x2b) [0x558f615631d9]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e75ef) [0x7fa4593d85ef]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7fa458b11a56]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7fa458b2fdd1]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fa458b310d3]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x391bb9) [0x7fa459382bb9]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x24d128) [0x7fa45923e128]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x89b) [0x7fa4592403db]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3cf79) [0x7fa458f28f79]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x70106) [0x7fa458f5c106]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7fa4597f3fbd]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7fa4597f4240]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7fa4597f4533]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main+0x7d) [0x7fa45923f37d]
??:0
[bt] #24 ./code/git/xournalpp/build/src/xournalpp(_ZN11XournalMain3runEiPPc+0xbff) [0x558f614896cd]
??:0
[bt] #25 ./code/git/xournalpp/build/src/xournalpp(main+0x49) [0x558f6144fa42]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fa4582750b3]
??:0
[bt] #27 ./code/git/xournalpp/build/src/xournalpp(_start+0x2e) [0x558f6144f93e]
??:0

** (com.github.xournalpp.xournalpp:3005): WARNING **: 06:48:51.037: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:3005): WARNING **: 06:48:51.037: [Crash Handler] Wrote crash log to: ~/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200727-064851.log

** (com.github.xournalpp.xournalpp:3005): WARNING **: 06:48:51.066: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:3005): WARNING **: 06:48:51.066: Successfully saved document to "~/.config/com.github.xournalpp.xournalpp//emergencysave.xopp"
```

Here is the error log from the this crash (looks really small?): 
[errorlog.20200727-064851.log](https://github.com/xournalpp/xournalpp/files/4981535/errorlog.20200727-064851.log)

**Comment by rolandlo** [comment]
Thanks for your observations and error logs. I am not sure if we have two independent bugs here or just one.
The "selection bug" is easy to reproduce starting from an empty document with 2 layers as described in issue #2081. I will try to fix that bug first and then we can see whether the "eraser bug" is still unresolved.

**Comment by rolandlo** [comment]
@createyourpersonalaccount Please checkout PR #2136 and check which of the two bugs (selection bug and eraser bug) is still present, if any.

**Comment by createyourpersonalaccount** [comment]
@rolandlo After your fix I thought the bugs went away. Erase stroke did not give me an error, neither did the selection. I tried whiteout and I got this after closing Xournal++:
```
** (com.github.xournalpp.xournalpp:15809): WARNING **: 13:35:42.565: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:15809): WARNING **: 13:35:42.566: [Crash Handler] Wrote crash log to: ~/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200727-133542.log

** (com.github.xournalpp.xournalpp:15809): WARNING **: 13:35:42.756: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:15809): WARNING **: 13:35:42.757: Successfully saved document to "~/.config/com.github.xournalpp.xournalpp//emergencysave.xopp"
```

Here's the error log
[errorlog.20200727-133542.log](https://github.com/xournalpp/xournalpp/files/4983494/errorlog.20200727-133542.log)

**Comment by rolandlo** [comment]
I still can't reproduce the bug. The errorlog says the segmentation fault happens when touch is enabled again. However I don't see where the segmentation fault could happen.
Can you reproduce the bug both with the stylus and the mouse? Do you have the new input system enabled?

**Comment by createyourpersonalaccount** [comment]
Using commit 03963b53944329a3d26d9a8d6f0c111949aa717f (which as of now is the latest), this bug is no longer present! Nice work!

**Comment by createyourpersonalaccount** [comment]
Fixed.
