### ISSUE TITLE
Total page count not updated after removing a page.

### ISSUE THREAD

**Issue by chron-isch** [xournalpp/xournalpp#2134]
**Affects versions :**
 - ArchLinux
 - Wayland/Sway
 - gtk3 3.24.21
 - Version of Xournal++: 1.0.18, commit: 535s261d
 - Arch/extra repository

**Describe the bug**
If you add a page, the total page count rises to 2, but if you remove it again the total page counter stays at 2.

**To Reproduce**
1. Add 2. page
2. Remove 2. page
3. Watch the total page count remain at 2

**Expected behavior**
Update page count after removing page.

**Comment by rolandlo** [comment]
I can reproduce the bug in version 1.0.16. Interestingly if you add more than one page and remove them again, the page count will only be off by 1. 
The bug is not present in version 1.1.0+dev (installed from PPA) anymore.

**Comment by 4VRDriver** [comment]
> The bug is not present in version 1.1.0+dev (installed from PPA) anymore.

I can reproduce it also in 1.1.0+dev:
1. Open a new document.
2. Add a page.
3. Scroll to the second page.
4. Scroll back to the first page.
5. Remove the page.

The page counter will say page 1 of 2.

**Comment by rolandlo** [comment]
OK, I see. It always happens unless the current page is the last page.

**Comment by rolandlo** [comment]
The problem was that the deletePage method did only call the updatePageNumber method if a new page was selected (because of removing the last page). I have contributed PR #2135 to fix this bug.
