### ISSUE TITLE
Not able to scroll notes until I change the zoom

### ISSUE THREAD

**Issue by lbooz** [xournalpp/xournalpp#2138]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: Official Windows release

**Describe the bug**
When I open a saved file .xopp there is no way to scroll pages until I change zoom.

**To Reproduce**
With Xournal++ closed, open a saved .xopp file and try to scroll up/down.

**Expected behavior**
I would like to scroll pages without need changing zoom.

**Screenshots of Problem**
This is the default zoom grade when program opens up
![image](https://user-images.githubusercontent.com/68913630/88683478-25067800-d0f4-11ea-945a-05bbd4cdba31.png)

Decreasing or increasing zoom allows me to scroll pages
![image](https://user-images.githubusercontent.com/68913630/88683703-60a14200-d0f4-11ea-9953-8ec0f5043ff2.png)

**Comment by lbooz** [comment]
Update: problem arises up when fit screen zoom is active.

**Comment by MichelReims** [comment]
I have the same problem in windows 7 or 10

**Comment by rolandlo** [comment]
> Update: problem arises up when fit to screen zoom is active, either when a saved document is opened or with a new unsaved document.

This is related to issue #1694

**Comment by unhandyandy** [comment]
I've run into a similar problem - sometimes I have to scroll up with the wheel before I'm allowed to scroll down.

**Comment by rolandlo** [comment]
It also happens right after you save the document. Quite annoying.

**Comment by rolandlo** [comment]
The problem seems to be, that the xournal view widget loses focus. The up/down keys are then used to control other widgets (the toolbar, the sidebar etc.). The xournal view widget should grab the focus again (with `gtk_widget_grab_focus`).

**Comment by diegovnoble** [comment]
This problem affects Linux too.
![Peek 2020-09-26 18-32](https://user-images.githubusercontent.com/731763/94350653-b0ce4f00-0026-11eb-9755-0efb1acf98fe.gif)

**Comment by DavGatto** [comment]
Same problem on Ubuntu 20.04 LTS (Cinnamon): can't scroll if "fit to page" is active.

**Comment by rolandlo** [comment]
@DavGatto Try Xournal++ 1.1.0+dev or wait for stable version 1.0.20.

**Comment by DavGatto** [comment]
> @DavGatto Try Xournal++ 1.1.0+dev or wait for stable version 1.0.20.

Thank you, it's actually not a big problem once you find out you just need to unselect "fit to page".

**Comment by BMicraft** [comment]
The actual problem seems to be that xournalpp always tries to have the currently selected page fully in view. If it only gets one scroll event it will try to scroll and jump back if it the other page is still further away. If it can't have even one page fully in view because of the page does not fit in the window with the current zoom level it gets stuck at the top.

@rolandlo This is also still a problem in current master (7ab24766206264c179d0a1e405cb2c1d43c7e83c)

**Comment by rolandlo** [comment]
@BMicraft I don't think this is the cause of the problem. Xournal++ only tries to have the currently selected page fully in view if it scrolls to it via the `XournalView::scrollTo` method. There are other scrolling methods like `Layout::scrollAbs` and `Layout::scrollRelative` that do not try to have the page fully in view.

**Comment by BMicraft** [comment]
> @BMicraft I don't think this is the cause of the problem. Xournal++ only tries to have the currently selected page fully in view if it scrolls to it via the `XournalView::scrollTo` method. There are other scrolling methods like `Layout::scrollAbs` and `Layout::scrollRelative` that do not try to have the page fully in view.

I was just commenting on the behavior as it manifests in my testing, and this seems be exactly what it is doing.

**Comment by rolandlo** [comment]
To check your theory you could add a `g_message` in `XournalView::scrollTo` (or in `Layout::ensureRectIsVisible`) and see if the message pops up in the console repeatedly while you try to scroll. You will have to compile from source though.

**Comment by BMicraft** [comment]
> To check your theory you could add a `g_message` in `XournalView::scrollTo` (or in `Layout::ensureRectIsVisible`) and see if the message pops up in the console repeatedly while you try to scroll. You will have to compile from source though.

I'm sorry I have literally zero experience in gtk or gui programming in general. I could try to look further into that maybe next week, but I'm not sure I will get anywhere with that soon.

**Comment by rolandlo** [comment]
You don't need programming experience to check this. All that is required is building from source (as described in the [wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md), assuming that you are on Linux) and adding the line `g_message("Attempt to scroll");` as the first line of `Layout::ensureRectIsVisible` in the file `src/gui/Layout.cpp` before you compile and run (from the console by typing `src/xournalpp` in the build directory.

**Comment by BMicraft** [comment]
Thank you for that, I would not have been able to do that without your help

Now I am getting exactly two messages a millisecond apart every time I try to scroll (or change window size), but only when zoom to fit is enabled
```
** Message: 16:10:38.592: Attempt to scroll
** Message: 16:10:38.593: Attempt to scroll
** Message: 16:10:39.496: Attempt to scroll
** Message: 16:10:39.497: Attempt to scroll
** Message: 16:10:39.942: Attempt to scroll
** Message: 16:10:39.943: Attempt to scroll
```

**Comment by rolandlo** [comment]
@BMicraft 
Ok, we made a big step towards a fix. When I add the same line in the code, I don't see this message when I try to scroll (doesn't matter if I use the arrow keys, the mouse wheel or the scrollbar). Now we can follow the trace back to the method where this call originated. 
My best guess is, it comes from `XournalView::zoomChanged()`. Could you please add another g_messge (like "zoom changed in presentation or zoom fit mode") in that method before `scrollTo(currentPage);`

**Comment by BMicraft** [comment]
With the code in XournalView.cpp looking like this:
``` cpp
    if (zoom->isZoomPresentationMode() || zoom->isZoomFitMode()) {
        g_message("zoom changed in presentation or zoom fit mode");
        scrollTo(currentPage);
    } else {
```
... I am now always getting both messages twice.

**Comment by rolandlo** [comment]
> ... I am now always getting both messages twice.

This means we are on the right track. Now the zoom is set in `ZoomControl::setZoom` 

Please add the line     `g_message("Current zoom: %f, previous zoom: %f", this->zoom, zoomI);` on the first line of `ZoomControl::setZoom` in the file `src/control/zoom/ZoomControl.cpp` and report back to me.

**Comment by BMicraft** [comment]
```cpp
With
void ZoomControl::setZoom(double zoomI) {
    g_message("Current zoom: %f, previous zoom: %f", this->zoom, zoomI);
    this->zoom = zoomI;
    fireZoomChanged();
}
now the output from just scrolling looks like this
```
** Message: 16:54:06.580: Current zoom: 2.314410, previous zoom: 2.340415
** Message: 16:54:06.580: zoom changed in presentation or zoom fit mode
** Message: 16:54:06.580: Attempt to scroll
** Message: 16:54:06.581: Current zoom: 2.340415, previous zoom: 2.314410
** Message: 16:54:06.581: zoom changed in presentation or zoom fit mode
** Message: 16:54:06.581: Attempt to scroll
```

**Comment by rolandlo** [comment]
How many times do you get these messages in one second of trying to zoom? It looks like the zoom values are switching forth and back.

**Comment by BMicraft** [comment]
Two per scroll event, they don't seem limited. 360 overall messages from `17:03:02.761` to `17:03:03.811` when scrolling _fast_

**Comment by BMicraft** [comment]
Well, now that I said it it looks like 360/3/2 is just below my refresh rate of 60fps when considering the time frame

**Comment by rolandlo** [comment]
Do the zoom values switch back and forth between the same two values? Can you post more of those messages?

**Comment by BMicraft** [comment]
> Do the zoom values switch back and forth between the same two values? Can you post more of those messages?

They seem to alternate between two values, you can see for yourself
https://paste.ubuntu.com/p/yz889nRWMx/

**Comment by rolandlo** [comment]
Ok, we have to trace it back further. Please add g_messages before every call of `zoomSequenceChange` like
`g_message("From <method name> with zoom %f", <zoom value>);` 
_where you replace <method name> with the name of the method where you put the message and <zoom value> with the zoom value passed to that method_ 
in each of the following methods:
`ZoomControl::zoomOneStep`
`ZoomControl::zoomScroll`
`ZoomControl::zoom100`
`ZoomControl::zoomFit`
`ZoomControl::zoomPresentation`
`TouchInputHandler::zoomMotion`
`ToolZoomSlider::sliderChanged`

Example: `g_message("From zoomOneStep with zoom %f", newZoom);`

**Comment by BMicraft** [comment]
Now every scroll event generates this
```
** Message: 17:35:09.379: From zoomFit with zoom 2.340415
** Message: 17:35:09.379: Current zoom: 2.314410, previous zoom: 2.340415
** Message: 17:35:09.379: zoom changed in presentation or zoom fit mode
** Message: 17:35:09.379: Attempt to scroll
** Message: 17:35:09.380: From zoomFit with zoom 2.314410
** Message: 17:35:09.380: Current zoom: 2.340415, previous zoom: 2.314410
** Message: 17:35:09.380: zoom changed in presentation or zoom fit mode
** Message: 17:35:09.380: Attempt to scroll
```

**Comment by rolandlo** [comment]
That's enough. The problem is, that the `zoomFitValue` (which is set in `ZoomControl::updateZoomFitValue` alternates between two different values. This value is computed from `page->getWidth()` and `widget_rect.width`. We must find out which one of them alternates. Please add `g_message("updateZoomFitValue with widget width = %f and page width = %f", widget_rect.width, page->getWidth());` above the line starting with `double zoom_fit_width =`.

**Comment by BMicraft** [comment]
FYI I added the same message for updateZoomPresentationValue as well
```
** Message: 17:51:50.135: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591, from updateZoomPresentationValue
** Message: 17:51:50.135: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 17:51:50.138: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591, from updateZoomPresentationValue
** Message: 17:51:50.138: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 17:51:50.139: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591, from updateZoomPresentationValue
** Message: 17:51:50.139: updateZoomFitValue with widget width = 1440.000000 and page width = 595.275591
** Message: 17:51:50.140: From zoomFit with zoom 2.340415
** Message: 17:51:50.140: Current zoom: 2.314410, previous zoom: 2.340415
** Message: 17:51:50.140: zoom changed in presentation or zoom fit mode
** Message: 17:51:50.140: Attempt to scroll
** Message: 17:51:50.140: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591, from updateZoomPresentationValue
** Message: 17:51:50.140: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 17:51:50.141: From zoomFit with zoom 2.314410
** Message: 17:51:50.141: Current zoom: 2.340415, previous zoom: 2.314410
** Message: 17:51:50.141: zoom changed in presentation or zoom fit mode
** Message: 17:51:50.141: Attempt to scroll
** Message: 17:51:50.141: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591, from updateZoomPresentationValue
** Message: 17:51:50.141: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
```

**Comment by rolandlo** [comment]
The messages from updateZoomPresentationValue should start with `updateZoomPresentationValue` (and you can leave away the `from ...`. It does not update the zoomFitValue. 
Could you please post a longer list of these messages?

**Comment by BMicraft** [comment]
> The messages from updateZoomPresentationValue should start with `updateZoomPresentationValue` (and you can leave away the `from ...`. It does not update the zoomFitValue.

Yeah I noticed that too after actually reading the message ...

> Could you please post a longer list of these messages?
https://paste.ubuntu.com/p/mwwXHN5K3X/
The first few messages are the result from enabling zoom to fit.

**Comment by rolandlo** [comment]
In `ZoomControl::onWidgetSizeChangedEvent` could you please try replacing

```cpp    
    zoom->updateZoomPresentationValue();
    zoom->updateZoomFitValue(r);
```
by
```cpp    
    g_message("Allocated width: %u", allocation->width);
    zoom->updateZoomPresentationValue();
    zoom->updateZoomFitValue();
```

Note that the argument `r` of `updateZoomFitValue` was left away intentionally.

**Comment by BMicraft** [comment]
It seems to work perfectly now, this is all the output I got from scrolling (_after_ zoom to fit was already enabled).

```
** Message: 18:31:38.744: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.744: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.748: Allocated width: 1440
** Message: 18:31:38.748: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.748: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.794: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.794: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.796: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.796: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.796: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.796: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.798: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.798: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.798: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.798: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.800: Allocated width: 1440
** Message: 18:31:38.800: updateZoomPresentationValue with widget width = 1424.000000 and page width = 595.275591
** Message: 18:31:38.800: updateZoomFitValue with widget width = 1424.000000 and page width = 595.275591
```

Scrolling slower seems to produce more events, but I guess thats to be expected.
https://paste.ubuntu.com/p/dCcKhPGXdw/

**Comment by rolandlo** [comment]
Ok, seems we fixed the bug. All that is needed is to leave the argument `r` away. I will have to check PR #1213 carefully, where this was introduced.
If it does not create any other regressions I will put up a PR that includes the fix and make some simplifcations, which can then be made. So far everything seems fine with the fix.

**Comment by BMicraft** [comment]
I will report back if I notice anything, so far the only thing would be that it does not remember zoom level settings between restarts, but I don't know if that's intentional.

**Comment by BMicraft** [comment]
Just a reminder that #1699 and #2066 seem to be duplicates and can most likely be closed already.

**Comment by rolandlo** [comment]
The zoom level after restart does not need to be the same as the one with which you ended your last session. There is a metadata manager that stores the zoom level for each document that was recently opened. So the intention is that every document (that has been saved) will be opened with the same zoom level like last time before it was closed last time.

I will close the duplicates after I have opened a PR. Then I can add a link to the PR.

**Comment by BMicraft** [comment]
> The zoom level after restart does not need to be the same as the one with which you ended your last session. There is a metadata manager that stores the zoom level for each document that was recently opened. So the intention is that every document (that has been saved) will be opened with the same zoom level like last time before it was closed last time.

Well, that's not quite true. It does save the absolute zoom level, it does not seem to store the fact that it was zoomed to fit.

**Comment by rolandlo** [comment]
Yes, the metadata manager saves the absolute zoom level, not the fact that it was zoomed to fit.
