### ISSUE TITLE
Arrow keys set to page up and down, not scrolling

### ISSUE THREAD

**Issue by betheb** [xournalpp/xournalpp#2142]
**Affects versions :**
 - OS:  Linux - Kubuntu 20.04
 - Desktop environment: X11
 - Which version of libgtk: 3.24.20
 - Version of Xournal++: 1.1.0+dev 

 - Installation method: PPA

**Describe the bug**
Arrow keys = page up and down, not scrolling. 

**To Reproduce**
Happens every time...maybe for a reason, but...

**Expected behavior**
Already there are keys "page up" and "down", so I would expect arrow keys to scroll through pages, as happens when I use two fingers on the trackpad. 

**Additional context**
Sorry if I'm wrong about this, but I always used to use the arrow keys to scroll in the old Xournal.

**Comment by rolandlo** [comment]
In presentation mode Arrows keys work like Page Up and Page Down. Try disabling the presentation mode (via menu view). It is possible that the presentation mode appears disabled, but scrolling is still like in presentation mode. This is a bug and has already been reported in #1694. In that case (as a workaround) you can enable presentation mode and disable it again. 
After disabling presentation mode scrolling should work like you expect. Please check if it works for you.

**Comment by betheb** [comment]
That's it! I turned presentation mode on and off and now I can scroll with the arrow keys! Thanks! The problem, I also realize, was/is compounded by the other issue relating to the inability to scroll while "Zoom fit to screen" is enabled. If I zoom out even just ten percent, then I can scroll. I'm so happy! Thanks!
