### ISSUE TITLE
Freezes after pen input with tablet

### ISSUE THREAD

**Issue by vektorsigma** [xournalpp/xournalpp#2143]
**Affects versions**
 - OS: Windows 10 build 19041
  - Version of Xournal++: 1.0.18 Git commit: 535d261d
  - Installation method: official release from GitHub page.

**Describe the bug**
Once I start writing using pen, I will unable to click anything in Xournal++, but when I hover over icons, it still showing their name. Only thing I can keep doing is writing. I had to use Task Manager to close the app after it "freeze".

**To Reproduce**
1. Launch the app.
2. Start writing with tablet pen.
3. Then GUI is not clickable.

**Additional context**
1. My tablet is VEIKK A30, with their driver installed.
2. Under Preferences > Input System > Input Devices, it says "No devices were found...."
3. My tablet is recognized and working fine under other software.

**Comment by vektorsigma** [comment]
Additional Info: If I write using mouse, everything is normal.

**Comment by IgnatRU** [comment]
I believe I am having the same issue.

Soon after launch, the app stops responding to the mouse, only the wheel scrolling works.  Otherwise the app works fine, the keyboard shortcuts are there and pen is usable. 

Windows 10.0.18362, xournal 1.0.18
Wacom tablet.

**Comment by vektorsigma** [comment]
I finally found the solution. You may Google a driver called WinTab, I believe it's a tablet driver for Microsoft Surface. After install, eveeything works fine, and now the pen can be recognized.

**Comment by IgnatRU** [comment]
Then i must be having a different issue. My pen works all fine, it is the mouse that does not.

**Comment by mgavin** [comment]
Is it possible to close the issue then? I think it's a Windows particular issue. For example, I tried using a bamboo/wacom pen, and after downloading the drivers, I didn't get any better functionality or recognition than I did without it (Windows own Pen Input driver vs the Wacom Input driver...). I gave up and use linux now :)

**Comment by DvP17** [comment]
Sorry, but this does not sound like a solution for this issue. I installed WinTab and it still does not work.
