### ISSUE TITLE
Adding new pdf pages does not work

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#2144]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment:: X11
 - Which version of libgtk do you use: 3.24.20
  - Version of Xournal++: dev1.1.0+dev 
- Installation method: PPA

**Describe the bug**
Adding newly created pdf pages in a pdf was possible by adding new pages with "pdf background". Now this does not work any more. The app freezes after hitting the insert button.

**To Reproduce**
1.Open a pdf in Xournal++
2. Save the xopp-file
3. Add some pages to the pdf file (externally, for example using pdftk)
4. Open the xopp-file again
5. Set the background option for inserted pages to "pdf background"
6. Click on "Insert page" and choose one of the new pdf pages
7. Observe that the app freezes

**Expected behavior**
I expect that the app does not freeze and the new pdf page is inserted into the document (like it used to be)

**Additional context**
Running git-bisect shows that the regression was introduced with PR #1613. The freeze results from an infinite loop, in which firePageSelected and fireZoomChanged methods call each other.

**Comment by rolandlo** [comment]
A temporary fix is provided in PR #2146.

**Comment by Technius** [comment]
Same source problem as #1660.

**Comment by rolandlo** [comment]
Seems like PR #2312 fixes the bug. The temporary fix in PR #2146 (which made use of the fact that the focus shifted to the first page) can be removed then.
