### ISSUE TITLE
Binary for Windows on MS Surface (ARM processor)

### ISSUE THREAD

**Issue by latchr** [xournalpp/xournalpp#2145]
**Is your feature request related to a problem? Please describe.**
I downloaded and installed the windows build on a Microsoft Surface Pro tablet, but it did not run. Although the install process went smoothly, trying to run the program gave an error about not being able to run on this version of Windows. After a bit of digging around I think the problem is that this hardware runs an ARM processor rather than x86.

**Describe the solution you'd like**
I want to use this excellent software in Windows on the MS Surface Pro hardware.

**Describe alternatives you've considered**
I have considered trying to compile locally from source, but it is a work tablet and it will be difficult to get the compiler tool chain installed and ready to go. I do not have lots of experience compiling source on Windows.

**Additional context**
It took me a while to uncover the idea that the ARM processor architecture might be the issue. The install process went perfectly and gave no errors, and I couldn't find anything in the documentation about the windows release. Perhaps some mention of this could be included in the docs, because I suspect that Xournal++ is somewhat likely to interest MS Surface users.

**Comment by LittleHuba** [comment]
ARM and x86 are not binary compatible. You'll have to compile Xournal++ by hand.

**Comment by Technius** [comment]
I'm not sure if Azure Pipelines supports ARM builds, but we could do this pretty easily if it does.

**Comment by martinkoutecky** [comment]
I would like this too, and I can help test a build.

**Comment by elagobalus** [comment]
For the surface pro x, a windows arm 32 bit version would be excellent!

**Comment by fzhwenzhou** [comment]
#4585

**Comment by rolandlo** [comment]
Closing in favour of #4585. See https://github.com/xournalpp/xournalpp/issues/4585#issuecomment-2128014573 for how to install an ARM version via MSYS2.
