### ISSUE TITLE
Keyboard accelerators stop responding when the menubar is hidden

### ISSUE THREAD

**Issue by duncanawoods** [xournalpp/xournalpp#2147]
If you hide the menubar then keyboard shortcuts like f11 full screen stop working. I would expect them to still work.

- Version 1.10
- Ubuntu 18.04
- Gnome

I believe it is a default GTK behaviour. It can be fixed by binding the accelerators to the main window, not the menu items:

https://stackoverflow.com/questions/19707775/accelerators-stop-responding-when-menubar-gets-hidden

If this is acceptable, I will submit a PR.

**Comment by rolandlo** [comment]
This is basically a duplicate of  #2082, but I am happy if you fix it. Definitively these keyboard accelerators should work even if the menubar is hidden.

**Comment by duncanawoods** [comment]
Oops, quite right. I somehow missed that when I searched. I'll close this one and work on the other.
