### ISSUE TITLE
package xdg changes

### ISSUE THREAD

**Issue by rnxpyke** [xournalpp/xournalpp#2153]
The current release is from April 15, and isn't xdg base dir conformant.
This issue has already been reported in #1101 and apparently a fix is already merged into the master branch with #1384

Different Linux distributions generally only package official releases, so the fix for the xdg base dir still isn't available for users that don't build from source. 

It would be nice if you could create a new minor release, so that the fix lands on the different packet managers out there.

Thanks for creating such a useful open source application, keep up the good work!

**Comment by Technius** [comment]
Closing this since it will be done soon in 1.1.0.
