### ISSUE TITLE
Issue with cursor in drawing area

### ISSUE THREAD

**Issue by s1-ranjan** [xournalpp/xournalpp#2155]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Mint 20.04
 - Version of Xournal++ 1.1.0+dev, nogitfound, built on Aug 5 2020, 20:46:45

**Describe the bug**
The cursor on the drawing area does not works well when a big pen icon is selected.

**To Reproduce**
1. Click on Edit
2. Select Preferences
3. Select the View tab
4. Go to the cursor section
5. Change the option cursor icon for the pen.

**Expected behavior**
The pen should remain visible under the drawing area in both the state i.e., during the use time and secondly when it is not in use. it should not flicker as it creates a lot of distraction with this behavior. 

**Additional context**
Today after I performed my system upgrade and I noticed this strange behavior, the earlier version was working normally.

**Comment by rolandlo** [comment]
If you use the "big pen" icon with your pen (not with your mouse), this icon will be displayed the same way both if you draw or not. Do you use this mode with your mouse (or have you mapped the pen to "mouse" in the input settings)?

**Comment by s1-ranjan** [comment]
Following is the image of my xournal++ preferences Input System
![xournallpp](https://user-images.githubusercontent.com/20767253/89894485-c4009900-dbf7-11ea-95ac-ab13adde987c.png)
I found my issue got fixed when I select the Experimental Input System under the Xournal++ Preferences Input system tab, But I am wondering with the probable cause of strange behaviour with this new version.

**Comment by rolandlo** [comment]
I can reproduce your problem with the old input system. The old input system is planned for removal anyway, so you should definitively use the new input system. There are far less issues with the new input system than with the old one.
