### ISSUE TITLE
xournal returns to the "top layer" after deleting a layer

### ISSUE THREAD

**Issue by fugata** [xournalpp/xournalpp#2156]
- OS:  linux mint 18.02 xfce
 - (Linux only) Desktop environment: X11 (I think)
 - Which version of libgtk do you use:   3.22.30
 - Version of Xournal++:  1.1.0+dev, nogitfound, Aug 5 2020
 - Installation method:  github release

**Describe the bug**
In a page with multiple layers, once you delete a layer -- no matter what that is -- xournalpp stays on that page (which is correct) but goes back to layer 1 (which is not)

**To Reproduce**
1.  Take any page with multiple layers
2.  Go to any layer and delete it
3.  Xournalpp takes you back to layer 1 on that page

**Expected behavior**
Say you were at layer 16 and then delete it, you should now be on layer 15 --- that's also the default behavior in xournal 0.4.8

**Comment by rolandlo** [comment]
I can't reproduce this behavior. If I have 3 layers and delete the 3rd one, I'm on layer 2.
How do you delete the layer?

**Comment by fugata** [comment]
This is weird; I can't reproduce this now.  I will close this issue and revisit it only if I can reliably reproduce and make a video of it.
