### ISSUE TITLE
when scrolling down to a new (existing) page, have option to display that page at layer 1 instead of the last layer

### ISSUE THREAD

**Issue by fugata** [xournalpp/xournalpp#2157]
**Is your feature request related to a problem? Please describe.**
I use xournal++ to make hand-written powerpoint slides for my video lectures.  I use the "layer" feature to gradually reveal material as I go along (similar to \visible in beamer).  As I finish one page and scroll down to the next, the new page immediately jumps to the last layer; in particular, it reveals all the info on that page. 

**Describe the solution you'd like**
An option under preference where users can choose to start every page at layer 1 vs last layer.

**Describe alternatives you've considered**
As a temporary work-around, I tried to scroll up just a little bit of the new page, click up the new page and bring it back to layer 1, but I was not able to do that until I scroll up at least 1/5 of the new page.

**Additional context**
Recently I introduced xournal++ to my colleagues looking for ways to prepare for zoom lectures. After trying out a bit on their own, everyone independently pointed out to me this issue about layering.  For those of us who need to prepare video lectures, this is a mild annoyance -- we have to stop the recording, scroll up enough of the new page, reset the layer and then continue.  But for those who want to use xournal++ to prepare zoom recitations by preparing problem sets with solutions hidden in another layer, this issue makes it not usable.

Xournal++ is a great tool for online teaching, and adding this feature will greatly reduce to the pain point.  Thank you for your consideration.

**Comment by rolandlo** [comment]
Thanks for pointing this out. Shouldn't be too hard to implement. I added the priority:high label, since this seems to be something that a lot of people could benefit from during these Corona times.

**Comment by fugata** [comment]
Thanks for your prompt reply and consideration!

**Comment by rolandlo** [comment]
You should leave it to the developer. It will get closed once your requested feature is implemented.

**Comment by rolandlo** [comment]
@fugata I am looking more closely at the issue and have some questions:
- When you gradually reveal your handwritten slides, how do you do it? By gradually enabling the checkboxes for the layers in the layer preview on the sidebar?
- Why don't you simply hide all (non-background) layers on all pages and select the first layer on each page **before** the presentation? 

So maybe no new options must be added, you can already get the behavior you desire. By the way, hiding all layers on a page can be done via the dropdown menu in the toolbar.

**Comment by fugata** [comment]
@rolandlo:  Thanks for looking into this.  

I make my recording right after I finish the slides, at which point of course all layers are visible.  So as you suggested, hiding all layers on all pages will solve my problem.  Good idea!

I do NOT see an option on the top menu that would allow me to hide all layers on all pages; I probably just miss it.  Could you walk me through that?  (there is a menu at the bottom but that's for the current page only).

Thanks again!

**Comment by rolandlo** [comment]
@fugata You are right, currently you can only hide all layers on a single page and you must go through all pages to hide the layers. Maybe hiding all layers at once could be implemented as a plugin.

**Comment by rolandlo** [comment]
Hiding all layers at once will be easily possible after #2406 has been merged.

**Comment by rolandlo** [comment]
PR #2406 contains a test plugin, that contains a function to hide all layers except the footer and background layers. It can also easily be modified to only hide the top layer, or to hide all layers (except the background layer) for example.
