### ISSUE TITLE
Does Xournal++ support Wayland?

### ISSUE THREAD

**Issue by Hoeze** [xournalpp/xournalpp#216]
Hi,
i recently found out that Xournal does not support GTK3 / Wayland for stylus input.
Is Xournal++ capable to handle stylus input on Wayland?
I'd like to switch to Wayland due to its better touch support, but I don't want to miss Xournal...

**Comment by Gefrierbrand** [comment]
Wayland is currently not supported and probably never will be in GTK2:

> Denis Auroux - 2017-01-05
> 
> Wayland does not currently provide xinput device event support in a
> manner compatible with gtk2. Someday xournal will work on gtk3 and it
> will be possible to support wayland. Or someday wayland will have
> backward compatibility to provide wacom tablet support for gtk2
> applications. In the meantime, you should just use gnome on Xorg instead
> of Wayland. Sorry!
> 
> Denis

However you might try the experimental GTK3 build of Xournal:
https://github.com/dmgerman/xournal/tree/gtk3

**Comment by LeoUfimtsev** [comment]
Hello Hoeze, 

I got Xournal to work with Fedora 28/Wayland and my Wacom tablet. I think it ran it in X11 emulation thou.
export GDK_BACKEND=x11

I'm now experimenting / trying to get Xournal++ to work.

**Comment by LeoUfimtsev** [comment]
Btw, I can confirm, after building xournal++ on my Fedora 28 machine, Xournal works quite well on my Fedora 28 with Wayland backend and my Wacom Intuos 4 tablet. I'm quite impressed!

**Comment by andreasb242** [comment]
GTK3 is merged, therefor this should work. Close ticket for now.
