### ISSUE TITLE
Ctrl + scroll makes not only Zoom but actual Scroll as well

### ISSUE THREAD

**Issue by IgnatRU** [xournalpp/xournalpp#2164]
**Affects versions :**
Windows Home 10.0.18362 Build 18362
App version 1.0.18, Github commit 535d261, installed via official release

**Describe the bug**
When you scroll with Ctrl + scrool, there are two operations that seem to occur at the same time: the normal zoom (the one you obtain with Ctrl + +/-), but it also scrools the pages at the same time vertically, which gives a very weird behaviour as you zoom and move up/down the pages.

**To Reproduce**
1. Start App 
2. Open file 
3. Ctrl + scroll

**Expected behavior**
Ctrl-scroll It should zoom only of the current page, centered at the centre of the visible part

**Additional context**
Add any other information or context about the problem here.
Partly similar behaviour was reported in #2054. It was marked closed by #2160, but that one is about Linux. In any case, it is not yet in the latest Windows release.

**Comment by Febbe** [comment]
It's indeed partially fixed in master. Can you try the nightly?

**Comment by rolandlo** [comment]
This is related to #2054

**Comment by IgnatRU** [comment]
> It's indeed partially fixed in master. Can you try the nightly?

I am afraid I can only use 'official' releases on my current Win system.

**Comment by LittleHuba** [comment]
You can download a prebuilt nightly from our release page. If that is why you can't use a nightly?

**Comment by LittleHuba** [comment]
Got it fixed.
Here is the link to the latest nightly release: https://github.com/xournalpp/xournalpp/releases/tag/nightly
Within the assets you'll find the Windows installer as you are used from official releases. If you install a nightly and then want to move back to an official release you might have to remove your settings file. Please keep that in mind.

**Comment by IgnatRU** [comment]
> ~You can download a prebuilt nightly from our release page. If that is why you can't use a nightly?~
> 
> Scratch that... the pipeline is broken again. We'll fix it soon and then you'll be able to get it there.

I found now the nightly build page :) will try what is there, and will wait for the new one :)

**Comment by LittleHuba** [comment]
You can use the current one already. The nightly itself was sound. Just the way it was posted on Github was not.

**Comment by IgnatRU** [comment]
Yep, installed it! 
The issue does seem to be resolved, although scroll-zoom is VERY slow =))

**Comment by IgnatRU** [comment]
The issue closed in nightly

**Comment by renyhp** [comment]
I am on 1.0.20 (built Dec 17 2020) and I am affected by this issue on Xubuntu 20.04.2
