### ISSUE TITLE
Page Up / Down to jump one screen only

### ISSUE THREAD

**Issue by IgnatRU** [xournalpp/xournalpp#2165]
**Is your feature request related to a problem? Please describe.**
Page Up and Page Down keys jump literally one page up or one down unlike all other apps I personally know (from Acrobat to TexStudio). 

**Describe the solution you'd like**
Page Up and Page Down keys jump one **visible screen** up or one down. Left/right arrows or Ctrl Page Up/Down are used to jump a whole page.

**Comment by mgavin** [comment]
I too would enjoy some kind of separate functionality toggleable for page up/down vs screen up/down.

There's the plugin system, so I hope there's a way to add it in as a plugin. (haven't looked at it yet)

**Comment by Technius** [comment]
Duplicate of #1412.
