### ISSUE TITLE
Notes disappear on rectangle selection

### ISSUE THREAD

**Issue by legendofa** [xournalpp/xournalpp#2168]
Selections disappear on the second page of this document while using the rectangle tool,
region selection works as expected.

[2020-08-13-Note-12-05.xopp.zip](https://github.com/xournalpp/xournalpp/files/5078476/2020-08-13-Note-12-05.xopp.zip)

Input device:

- Mouse

Kernel:

- 5.7.12-arch1-1

Desktop Environment:

- i3 version 4.18.2

Xournalpp version:

- 1.0.18

Steps to reproduce:

- No idea, this functionality works properly in a new document

Expected behaviour:

- Selection does not disappear and gets highlighted

![disappearing_selection](https://user-images.githubusercontent.com/34162874/90310458-edb00d80-dee0-11ea-9ea0-cf1b4bf002ca.gif)

**Comment by rolandlo** [comment]
I can reproduce the bug with version 1.1.0+dev as well and will try to find out, why this happens.

**Comment by rolandlo** [comment]
Looking at the gunzip-ed xopp file I noticed that there are several (around 40-50) strange strokes of the form

`<stroke tool="pen" ts="0ll" fn="" color="#000000ff" width="-nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan">-nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan</stroke>`

I have no idea how they got in there. After removing these strokes, the file works fine. Check out the repaired file.
[2020-08-13-Note-12-05_repaired.zip](https://github.com/xournalpp/xournalpp/files/5078766/2020-08-13-Note-12-05_repaired.zip)

**Comment by legendofa** [comment]
The repaired file works fine, i will check for clues if it happens again.

**Comment by rolandlo** [comment]
Ok, I will close the ticket for now.

**Comment by alexispaz** [comment]
I can confirm this issue. After deleting the stroke line with "-nan" the problem disappears. I wondering what causes the "-nan" strokes in the first place.

Running xournalpp 1.0.19-1 on Linux 5.8.13-arch1-1 x86_64
