### ISSUE TITLE
Few motion events on GTK3 branch

### ISSUE THREAD

**Issue by oberien** [xournalpp/xournalpp#217]
On the GTK3 branch I notice that there are not a lot of `GdkEventMotion`. It feels like the function `motion_notify_event` is called at least three times more often on master in GTK2. This results in strokes consisting of way less points resulting in edgy font and circles. Going to the common ancestor of the branches master and gtk3, to 25d17d9, the issue does not exist. So my first (uneducated) guess would be that this is an issue with GTK3 as such.

**Comment by wbrenna** [comment]
Thanks for this discovery - I think this is progress towards understanding bug #109.
