### ISSUE TITLE
keyboard does not work in TEXT-fields

### ISSUE THREAD

**Issue by wojec** [xournalpp/xournalpp#2174]
**Affects versions :**
 - OS: Ubuntu 18.04
 - libgtk 3.22.30
 - Version of Xournal++:1.1.0+dev
 - Installation method: ppa

**Describe the bug**
Though the keyboard-shortcuts are working, there's no way to enter anything in the Text-fields (with the keyboard). 
Font and font-size are selected!

**Comment by rolandlo** [comment]
Under normal circumstances, typing in text fields should work (even if you don't change font and font-size settings). 

- Have you enabled the new input system in the settings?
- Do you use a mouse/keyboard combo? 

Sidenote: The same problem was reported in #1997 (on Windows).

**Comment by wojec** [comment]
Thanks for the quick response ;-)

The new input system is enabled and also the mouse/keyboard kombo (mouse only doesn't work either)
I'm using a cable mouse and cable keyboard. But this is exactly the problem!

*** SOLUTION
DISABLE the new input system, and everything works fine ;-) Thanks for the hint !!!

**Comment by 2xmax** [comment]
I solved the problem by going into Settings -> Input System. There, I found my keyboard and then switched from "Mouse" to "Mouse + Keyboard Combo," although I have a regular keyboard. I hope it helps someone.

**Comment by bb1950328** [comment]
![Image](https://github.com/user-attachments/assets/529e841e-321f-4637-b2f1-fc3a51c99ade)
I had the same problem. My solution was to change the last entry of the input device list from "Mouse" to "Mouse+Keyboard Combo".
