### ISSUE TITLE
Can't change Latex color

### ISSUE THREAD

**Issue by malnaanah** [xournalpp/xournalpp#2175]
The \color{red}  statement is not recognized by the Latex editor. Isn't it supposed to work? And if not, will it be possible in future versions?
I use:
Kubuntu 20.04
Xournalpp 1.1.0+dev

**Comment by rolandlo** [comment]
Try again tomorrow. The LaTeX tool enhancements #1952 have been merged today, so if you install from ppa you will get the update tomorrow.

**Comment by MichelReims** [comment]
On windows, I choose TEXT, puis the color ; then when I input a LaTeX formula, it's in the color I choose

**Comment by rolandlo** [comment]
@MichelReims This is also a solution, if you only need one color for the whole formula. Note however that the color will change if you edit the formula again and you have changed the text color in the meantime.
