### ISSUE TITLE
Releases need more organization

### ISSUE THREAD

**Issue by malnaanah** [xournalpp/xournalpp#2177]
I think the following things should be done regarding releases:
1 - The ppa page version says xournal 1.0.6 while it is in fact 1.1.0+dev. I think this need to be fixed. Also the versioning should take into account upgrading from previous versions.
2- The debian packages available in github releases are for xenial and they are not installable on [x]ubuntu 20.04. I think the debian package in the github page are better being for the current (20.04) and the previous (18.04) LSB ubuntu releases.
3- there is no appimages for the previous versions in the github releases. I think the appimage should be available along with windows, mac, and debian packages.

Best regards,

**Comment by Technius** [comment]
We've been working hard on trying to get releases set up correctly, but we've been really busy lately.

**Comment by Rmano** [comment]
> We've been working hard on trying to get releases set up correctly, but we've been really busy lately.

This is a minor comment, so please ignore it if too busy. I have a suggestion --- do not be too shy with release numbers. I have raised this in things like QUCS that is next to release a perfectly working circuit simulator with the deceiving release number `0.0.20`...

So I think the next version should be 1.1.0; there are plenty of new things that guarantee this. The third number should run alone only if a release if purely bug-fix... and I do not think this is the case here.

Thank you for the wonderful work!

**Comment by Febbe** [comment]
I also think we should release 1.1 quickly, but we can ship a last "old stable" with version number 1.0.19.

**Comment by Technius** [comment]
1.1.0 is nowhere near stable yet. If we do want to release, we should rollback some of the breaking changes (mainly the automatic page selection that's been the source of all of the zoom issues).

I've been considering doing a beta release, which would be good for users that care more about the new features than the occasional breakages.

**Comment by jasonbcox** [comment]
Related to this issue, but not really worth an issue itself: https://github.community/t/bug-report-pre-releases-trigger-notifications/134759

I reported to Github that I'm receiving daily notifications due to your nightly release process. In theory, there should be nothing wrong with retagging a pre-release, but I have no way to turn off these notifications without also turning off notifications for the stable releases that I care about. So this isn't something I expect the Xournalpp team to take action on, but I figured you should be aware that this is how I discovered the issue since many other projects I follow do not use the retag-nightly model.

**Comment by Technius** [comment]
This is actually an issue on our side: the CI configuration was changed to delete and recreate the release on every nightly build, triggering the notification. The change should be reverted and the CI configuration should instead be changed to force push the new nightly tag.

**Comment by jasonbcox** [comment]
Interesting. I still think the feedback to Github is valid, since there's no way to specify that I want notifications for releases vs pre-releases. But it's good know this could be fixed on your end. Thanks!

**Comment by rolandlo** [comment]
> I think the following things should be done regarding releases:
> 1 - The ppa page version says xournal 1.0.6 while it is in fact 1.1.0+dev. I think this need to be fixed. Also the versioning should take into account upgrading from previous versions.

This has just been fixed in #2701.

> 2- The debian packages available in github releases are for xenial and they are not installable on [x]ubuntu 20.04. I think the debian package in the github page are better being for the current (20.04) and the previous (18.04) LSB ubuntu releases.

This has been fixed a while ago.

> 3- there is no appimages for the previous versions in the github releases. I think the appimage should be available along with windows, mac, and debian packages.

The appimage has been included and is functional since #2600.

> 
> Best regards,

So I will close this issue.
