### ISSUE TITLE
Stylus buttons not working

### ISSUE THREAD

**Issue by 12jgy** [xournalpp/xournalpp#2187]
**Affects versions :**
 - OS: Windows 10 build 1903
 - Version of Xournal++: 1.0.18, commit 535d261d
 - Installation method: Official release

**Describe the bug**
When pressing any of the stylus buttons it doesn't switch to the configured tool, it instead seems to decrease the sensitivity of whatever tool is selected (This happens with both buttons).

**To Reproduce**
1. Press any of the buttons on the stylus 
2. Try to use the tool

**Expected behavior**
The configured tool is selected.

**Additional context**
My tablet is a Huion Inspiroy HS64, I've installed the driver for it, and Windows Ink is enabled if that helps
Xournal is identifying the tablet correctly, and the pressure sensitivity function is working as expected
I have the new input and "Merge button event with stylus tip events"options enabled, though the same issue occurs when I disable them, and the tablet input is set to "Pen"
Button 1 is set to "Eraser" and buttton 2 is set to "Hand"

**Comment by MichelReims** [comment]
I have a Huion kamvas pro with the same problem. I have configured the tablet for the shortcurts of xournal. It"s works

**Comment by 12jgy** [comment]
I just tried that, and it didn't work, at least with the buttons on the stylus, it's like it's identifying the input, overwriting whatever the tablet is configured to, but then is failing to execute what I configured inside xournal. That happens even when I trying to set the stylus buttons  on xournal to not change the tool, and have the buttons on the stylus configured to the shortcuts of the tools I want.

**Comment by RailRanger** [comment]
I have a similar issue on my Wacom Intuos Pro. The eraser function in the tablet software does not behave properly. It will erase sometimes? However it is a toggle and not push to hold. Works as expected in onenote or a program like photoshop.

**Comment by MichelReims** [comment]
I have a Huion kamvas pro 16 with the same problem. I have configured the tablet for the shortcurts of xournal. It"s works in Windows 7 but not in Windows 10. I don't know why

**Comment by MichelReims** [comment]
I found from where the problem came from in my windows 10. The Windows 10 tablet driver was not using the shortcuts I programmed.  Il faut demander au pilote de la tablette d'utiliser les privilèges administrateurs

**Comment by minimonk82** [comment]
Ubuntu 18.04 / PPA / 1.1.0+dev
HP Elitebook 2760p / wacom stylus

I configure Edit-preference-stylus 
stylus buttons - Button 2 as Select Region

when I push side button of stylus, Icon changed to Select region
But I can't selected anything. upper toolbar shows all rightly.

**Comment by luismpmatos** [comment]
Windows 10 / 1.1.0+dev
Huion Q620M inspiroy dial

I have the exact same issue as @12jgy. Shortcuts do not function both on the pencil and tablet itself (my model has 8 customisable keys and a dial), however the change in the sensibility settings in the HUION driver software affects the sensibility inside xournal++.

This is a very nice projects, if the shortcut keys bug is possible to solve it will be my main notetaking software for sure.

Keep up the good work.
Thanks in advance.

**Comment by LittleHuba** [comment]
Please make sure to use the experimental input system. If that one is activated and the device classes are correct there is nothing more we can do. You'll have to take this up with the GTK devs then as it is a driver issue or a bug in GTK itself.

**Comment by luismpmatos** [comment]
> 
> 
> Please make sure to use the experimental input system. If that one is activated and the device classes are correct there is nothing more we can do. You'll have to take this up with the GTK devs then as it is a driver issue or a bug in GTK itself.

I have the experimental input system option activated, what do you mean by device classes? sorry if its a dumb question. 
Thank you

**Comment by LittleHuba** [comment]
In the preferences dialog in the `input system` tab where you can select the experimental input system is a list of input devices. This list must have the correct input classes assigned. The auto assignment sometimes produces wrong results.

**Comment by luismpmatos** [comment]
> 
> 
> In the preferences dialog in the `input system` tab where you can select the experimental input system is a list of input devices. This list must have the correct input classes assigned. The auto assignment sometimes produces wrong results.

Thanks for the response. I see, I have the classes set correctly, the HUION pen set to pen and mouse to mouse. I suppose it is some kind of incompatibility, but I find it strange because in Inkscape, which is also built with GTK3, the tablet and shortcuts work perfectly.

**Comment by LittleHuba** [comment]
That is really strange. I just took a quick look at the source of Inkscape and could not find any magic done by the devs to handle input devices. Their setup seems to be straight forward GDK actually.

@Febbe could this be related to the bugs you mentioned being in mingw? My guess is that we use a version of GTK not having all necessary flags set for Windows.

**Comment by bulmust** [comment]
Unchecking 

Edit -> Preferences -> Input System -> Experimental Input System : Enable new input system (Requires restart) 

works for me. Now, I can erase with button 1 which I define in Stylus tab.

Version: 1.1.0+dev
Git commit: nogitfound
Built on: Dec 27 2020, 17:03:29
with libgtk: 3.23.20

----------------
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa"
-----------------

**Comment by rafisics** [comment]
- OS: Windows 10 Pro build 19041
- Version of Xournalpp: [1.0.20](https://github.com/xournalpp/xournalpp/releases/tag/1.0.20)-windows
- Tablet: [XP Pen Star G640S](https://www.xp-pen.com/product/54.html)

I am having the same problem. My stylus pen buttons and express keys on the tablet aren't working in Xournalapp.

**Comment by MichelReims** [comment]
You must use shortcuts with plugins

**Comment by rafisics** [comment]
> You must use shortcuts with plugins

The plugin manager window is appearing empty in Windows 10. What can I do?

**Comment by MichelReims** [comment]
You must create  files that contains shortcuts.

**Comment by MichelReims** [comment]
See https://xournalpp.github.io/guide/plugins/plugins/

**Comment by rolandlo** [comment]
@rafisics 
The plugin folder was somehow forgotten in the Windows installer until recently. If you install the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) it will be included. The plugin folder could also be copied manually from the source code folder. In any case you can also write your own plugins following the guide that @MichelReims pointed out.

**Comment by rafisics** [comment]
> If you install the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) it will be included.

Thank you, @rolandlo. My problem is solved in this [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly). But still, 2 of the 6 express keys (PageUp and PageDown) in my tablet are not functioning. The other 4 express keys and pen buttons are working fine. However, I am quite satisfied with these now. 
But some annoying problems are still not fixed: 
- Once I start writing/erasing with the pen for some moments, the mouse clicks stop working inside Xournalpp. And after some more time, the `Minimize`, `Restore` and `Close` buttons stop working. At that moment, I have to go to `File > Quit` to close it. Everything behaves normally when I reopen it. And the problem returns after using the pen again.
- The Dark Theme (`Edit > Preferences > View > Dark Theme`) is still not functioning properly in Windows 10. Its effect is only on the Icons' colors, but not on the window color. I wish it had the features like the `Switch Background` in `Onenote for Windows 10`.

**Comment by rolandlo** [comment]
@rafisics 

About the annoying problems: Please report them at the right place (if they have not yet been reported). This issue is only about stylus buttons. 
- The Dark Theme issue coincides with issue #2764 (please check) and will be fixed with PR #2771
- The issue with mouse clicks that stop working and window buttons stopping workings you might need to open a new issue. It may be related to #2628, so please check it first.

**Comment by rolandlo** [comment]
For my device I found stylus buttons work again as described in [this answer](https://github.com/xournalpp/xournalpp/issues/2894#issuecomment-794556611). Check if you can take a similar path.

**Comment by rolandlo** [comment]
The stylus button issues have been solved with the release of GTK+ 3.24.30, which is included in Xournal++ [version 1.1.0-hotfix.1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). So please upgrade. I will close the issue.
