### ISSUE TITLE
[filesystem] Xournal++ crashes on file save with SIGSEGV

### ISSUE THREAD

**Issue by jgrnst** [xournalpp/xournalpp#2193]
**Affects versions :**
 - OS: Linux KUbuntu 20.04
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: ppa

**Describe the bug**
~When xournalpp starts, it produces several error messages, all beginning with "Cannot create folder $HOME/.config/-com.github.xournalpp.xournalpp/"~

xournalpp crashes if I try to save the file.

**To Reproduce**

Start xournalpp from the command line, for example.
Save a file.

**Expected behavior**
This is not supposed to be happening.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

These are messages I got (from the start to the crash after I attempted to save a file)

ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:37:15.013: Could not create folder: /home/jacobg/.config/com.github.xournalpp.xournalpp/

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:37:15.021: Could not create folder: /home/jacobg/.config/com.github.xournalpp.xournalpp/

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:37:15.044: Could not create folder: /home/jacobg/.config/com.github.xournalpp.xournalpp/

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:37:15.048: Could not create folder: /home/jacobg/.cache/com.github.xournalpp.xournalpp/errorlogs

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:37:15.057: Could not create folder: /home/jacobg/.config/com.github.xournalpp.xournalpp/

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:38:05.103: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:38:05.103: [Crash Handler] Wrote crash log to: /home/jacobg/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200827-123805.log

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:38:05.140: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:188156): WARNING **: 12:38:05.141: Successfully saved document to "/home/jacobg/.config/com.github.xournalpp.xournalpp/emergencysave.xopp"

**Additional context**
Add any other information or context about the problem here.

**Comment by Febbe** [comment]
did you replaced your home_dir with: "$HOME" or is the path explicit?

**Comment by jgrnst** [comment]
I replaced my homedir with $HOME.

**Comment by jgrnst** [comment]
Upgraded to the new version. Warning on start-up disappeared, but xournalpp still crashes when I try saving a file.

**Comment by Febbe** [comment]
Can you test this with the newest Master? Probably this is fixed already.

**Comment by jgrnst** [comment]
The package version that I have now (from PPA) is 1.0.6-0~202008261852~ubuntu20.04.1
Is it the latest?

**Comment by Febbe** [comment]
The ppa is probably not the newest version, since the fix is 24h old. Also I pushed another fix. Can you update your log and add the crash dump? Also Signal 11 is not the error I expected, I exspected some sort of filesystem error.

**Comment by jgrnst** [comment]
Attached the latest crash log

[errorlog.20200827-140040.log](https://github.com/xournalpp/xournalpp/files/5138794/errorlog.20200827-140040.log)

**Comment by palvaradomoya** [comment]
I have the same crash with the very latest version in master, also in Kubuntu 20.04.1.  Attached my crash log.
[errorlog.20200827-163412.log](https://github.com/xournalpp/xournalpp/files/5139159/errorlog.20200827-163412.log)

I traced the crash down to src/util/PathUtil.cpp line 84.  It seems something went really wrong with the error pointer, which has an invalid pointer (0x1a) in the message string.   This causes the segfault.

**Comment by palvaradomoya** [comment]
Just initializing tthe error pointer at line 80 of PathUtil.cpp seems to fix this problem:

         GError* error = nullptr;

**Comment by Febbe** [comment]
Yes done this fix already in my local branch. But I found 3 other cases of undefined behavior I'll fix with my next push. Also the save function is broken, when the target drive is removed or the backup file already exist.

**Comment by unhandyandy** [comment]
I have an Aug 28 pull:
$ git log
commit c3df668922e8d7606a77b3d8dd0b219db838cfd2 (HEAD -> master, origin/master, origin/HEAD)
Author: Roland Lötscher <40485433+rolandlo@users.noreply.github.com>
Date:   Thu Aug 27 22:13:44 2020 +0200

    Update WindowsBuild.md (#2185)
    
    Update WindowsBuild.md

But I'm still getting the crash-on-save problem.

**Comment by Febbe** [comment]
It's not pushed yet got another regression last night and had to work till now.

**Comment by unhandyandy** [comment]
Is 1.0.18 the latest stable release?

**Comment by Febbe** [comment]
Yes

**Comment by Febbe** [comment]
Ok I fixed it.

**Comment by jgrnst** [comment]
Thank you! How long does it take to get pushed to the repository?

**Comment by Febbe** [comment]
To the ppa or nightly? PPA: I really can't tell, for me it's random when a ppa for a distribution is generated. But the nightly is generated at 0:00 GMT/MET

**Comment by jgrnst** [comment]
I was asking about the PPA. No problem, I will generate .deb from the
source code then. It looks like PPA is still at 1.0.6

**Comment by Febbe** [comment]
Normally we don't advance the package version in dev versions.

**Comment by jgrnst** [comment]
I didn't know that. Anyway, I now have a .deb with a working version. Thank
you very much,  I use xournalapp on a daily basis.
