### ISSUE TITLE
Latex tool crashes Xournal++

### ISSUE THREAD

**Issue by superenginegit** [xournalpp/xournalpp#2194]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use
     3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     1.1.0+dev
 - Installation method: ppa

**Describe the bug**
When starting the latex tool, the dialog comes up for a split second and then Xournal++ crashes

**To Reproduce**
1. start Xournal++
2. click on the latex tool
3. it crashes

**Expected behavior**
The latex tool should start and be usable.

**Additional context**
In the system log there are some messages messages:
 1. terminate called after throwing an instance of 'std::logic_error'
 2. what(): basic_string::_M_construct null not valid
 3. [Crash Handler] Crashed with signal 6

Also there is a crash log:
[errorlog.20200828-074603.log](https://github.com/xournalpp/xournalpp/files/5140231/errorlog.20200828-074603.log)

**Comment by rolandlo** [comment]
I get some more warnings, which have not been there before:
```
** (com.github.xournalpp.xournalpp:11515): WARNING **: 07:52:43.493: Error loading plugin «../../plugins/ToggleGrid»

** (com.github.xournalpp.xournalpp:11515): WARNING **: 07:52:43.493: Error loading plugin «../../plugins/Example»

** (com.github.xournalpp.xournalpp:11515): WARNING **: 07:52:43.588: GladeGui::get: Could not find glade Widget: "menuViewToolbarsVisible"

(com.github.xournalpp.xournalpp:11515): Gtk-CRITICAL **: 07:52:43.588: gtk_check_menu_item_set_active: assertion 'GTK_IS_CHECK_MENU_ITEM (check_menu_item)' failed

** (com.github.xournalpp.xournalpp:11515): WARNING **: 07:52:43.588: GladeGui::get: Could not find glade Widget: "menuViewToolbarsVisible"

(com.github.xournalpp.xournalpp:11515): GLib-GObject-WARNING **: 07:52:43.588: invalid (NULL) pointer instance

(com.github.xournalpp.xournalpp:11515): GLib-GObject-CRITICAL **: 07:52:43.588: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

```
This seems to be connected to the latest filesystem changes. @Febbe, can you look into it?

**Comment by Febbe** [comment]
I don't have this problem. Whats your exact Latex command you use? Or did you changed something in your configuration? But despite that in my case the tool just wont let me to parse my Latex code :D; not even better.

**Comment by rolandlo** [comment]
Strange. I do not have time to set a LaTeX formula, since Xournal++ crashes almost immediately after the LaTeX tool has been called (from the toolbar or menubar). So it is the default LaTeX formula, which runs fine, if I just test the configuration on the LaTeX panel.

**Comment by Febbe** [comment]
1. Mmh maybe I suddenly fixed it with my last 3 fixups. Can you test it with the newest Master?

**Comment by Febbe** [comment]
Oh shure I fixed it, after the last uninitialized pointer bug I searched for those occurences prematurely and fixed it.

**Comment by rolandlo** [comment]
You are right, it is fixed. Thanks!

**Comment by Febbe** [comment]
It seems that ubuntu18.04 does not provide scontents.sty in texlive. So I can't use that feature.

**Comment by rolandlo** [comment]
That's bad news. The `scontents` package can be downloaded from [CTAN](https://www.ctan.org/pkg/scontents), though.
