### ISSUE TITLE
Would you please provide a version suitable for ubuntu 20.04

### ISSUE THREAD

**Issue by amonpuschel** [xournalpp/xournalpp#2198]
Please excuse me filing this as feature request...

**Comment by jalonsomartinez** [comment]
Yes, please!
I am currently using the snap in Ubuntu 20.20 but I'm not able to use latex feature, as it doesn't find latex in my system.
I can see a nightly build for 20.20, but no stable release.
Thanks!

**Comment by Technius** [comment]
Please avoid the Snap package, as we have no control over it and cannot update it to the latest version. I would suggest using the [Flatpak installation method](https://github.com/xournalpp/xournalpp#flatpak), which we officially support.

We're working on getting Ubuntu 20.04 deb packages to work (#1013), but we've also been quite busy recently.

**Comment by Technius** [comment]
[A stable release is now available through a PPA thanks to @apandada1.](https://github.com/xournalpp/xournalpp/issues/1013#issuecomment-692656810)
