### ISSUE TITLE
Prefs window is bottomless

### ISSUE THREAD

**Issue by unhandyandy** [xournalpp/xournalpp#2201]
The master from Aug 28 has the irritating problem that the prefs window has no bottom - and there's no save and cancel buttons, so prefs cannot be saved.

**Comment by rolandlo** [comment]
Is that still the case if you upgrade to the Aug 29 version?

**Comment by unhandyandy** [comment]
I don't see any commits from Aug 29.

**Comment by rolandlo** [comment]
Commit d8570489c258efb90df932baa63fd799ada562b0 is from Aug 29. Maybe we live in different time zones. I assume you installed from PPA, so you can try to upgrade. The commit I mention has not been in the PPA version until very recently (less than 6 hours, I think).

**Comment by unhandyandy** [comment]
I've cloned the repo, I'm up to commit e3cb4607.  The bug is still there.

**Comment by rolandlo** [comment]
Hmm, I can't reproduce it. Maybe @Febbe has an idea, what the problem might be.

**Comment by unhandyandy** [comment]
I'm on Ubuntu 20.04.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/2363767/91645494-749dd380-ea13-11ea-83a5-ca7ae89b1367.png">
It seems the prefs window is stretched vertically to max, and cannot be resized.

**Comment by rickhg12hs** [comment]
Commit c3df6689 compiled on Fedora 29 works fine.

**Comment by Febbe** [comment]
Can you try to reset your settings (rename the folder ~/.config/com.github/xournalpp/xournalpp)

**Comment by unhandyandy** [comment]
Thanks, that fixed it.

**Comment by Febbe** [comment]
Ok thank you. It would be cool if you top the old folder for debug purposes

**Comment by unhandyandy** [comment]
It's over 10MB.  What should I leave out?

**Comment by Febbe** [comment]
All your emergency saves and xournal safe files(xopp)

**Comment by unhandyandy** [comment]
[badConfig.zip](https://github.com/xournalpp/xournalpp/files/5146256/badConfig.zip)
