### ISSUE TITLE
I cannot input any text in Windows 10

### ISSUE THREAD

**Issue by DannyAn** [xournalpp/xournalpp#2202]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS:  Windows
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
![image](https://user-images.githubusercontent.com/12059951/91652485-6b237280-eaca-11ea-8a2d-854a432d3d8d.png)

 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.18
     - commit: 535d261d
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
   Official release.
**Describe the bug**
    Click button text in toolbox, then try to input any text. unforturenately, nothing happened.    
    It seems the input box only accept TAB. English letters and numbers or any Chinese are not accepted.    
*To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/12059951/91652369-39f67280-eac9-11ea-8c5d-927eb7f38b1d.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Does this happen both with "new input system" enabled and disabled? Compare with #2174.

**Comment by mrjihun** [comment]
There is simple workaround here.

Install msys, install gtk, sync pacman database, update gtk.
and copy content of msys's binary.
Copy all of them to 'bin' of xournal++.

Then xournal++ will work again.

In short, just update gtk library.

**Comment by Technius** [comment]
This was probably fixed when we updated CI to reinstall msys dependencies on every build.

**Comment by hartmut27** [comment]
The problem re-arises, unfortunately. I've documented in #2573.

**Comment by rolandlo** [comment]
For the record: @hartmut27 's issue was solved by setting the correct device class.
