### ISSUE TITLE
Wacom One issues on Windows 10: only works as expected the first time

### ISSUE THREAD

**Issue by sbecuwe** [xournalpp/xournalpp#2203]
**Affects versions**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**

Launching Xournalpp a second time and moving it to the Wacom One display, results in a large distance between the pointer of the pen and the location where written text appears. To give an idea: writing above the first blue line, text appears between the second and third blue line below, and shifted approx. 1 cm to the left. As a consequence, it's impossible to use the pen to access the menus.

**To Reproduce**

1. Restart Windows, launch Xournalpp, move the app to the Wacom One display. Everything works as expected.
2. Close Xournalpp.
3. Restart Xournalpp. It's no problem to write on the main display (laptop) using a mouse and to control the menus.
4. Close Xournalpp.
5. Restart Xournalpp and move it to the Wacom One display. No problem using the mouse to draw or to control the menus.
6. Touch the Wacom One display with the pen and the described bug shows up. Once again, using the mouse afterwards does not show this behavior, as text appears exactly where the mouse cursor is shown.
7. Launch a program like Word and move it to the Wacom One display, while Xournalpp is running, to check whether the same issue shows up there. It's not the case. The written text appears exactly where you expect it in Word. 

**Expected behavior**
The pen should always behave in the same way in Xournalpp, whether you launch Xournalpp for the first or the second time.

**Comment by sbecuwe** [comment]
Additional comment: after some time (a few minutes?) even mouse control no longer works and you have to use the Task Manager to stop Xournalpp.

**Comment by Febbe** [comment]
Can you move xournalpp to the mainwindow before you close it an retry?

**Comment by sbecuwe** [comment]
I restarted the computer once again. The first time, the pen behaves as expected. I moved Xournalpp to the main window and closed it. I restarted Xournalpp, moved it to the Wacom One display and the described bug shows up. Using CTRL-Q to quit the program luckily still works ;-)  Although the pen works in programs like Word, I calibrated the pen again, but this doesn't change its erroneous behavior in Xournalpp.

**Comment by sbecuwe** [comment]
Issue seems to be solved after installing Windows 10 Preview update KB4566116!

_Updates a visual offset issue on a touchscreen. Edits you make with a pen or finger appear in a different region than expected if the device is connected to an external monitor._
