### ISSUE TITLE
LaTeX: \usepackage{scontents} no such package

### ISSUE THREAD

**Issue by kassbohm** [xournalpp/xournalpp#2206]
**Affects versions :**

Linux Debian/Ubuntu/Mint
Xournal++ 1.1.0+dev

**Bug?**

Testing Latex Support from Edit-Preferences-Latex Test Configuration produces **tex.tex**, in which one line is:

`\usepackage{scontents}`

This leads to the following output in **tex.log**:

`! LaTeX Error: File scontents.sty not found.`

A package scontents.sty does not exist in up-to-date latex installations... or am I wrong?

**Expected behavior**
LaTeX is rendered.

**Comment by Febbe** [comment]
Are you still on 19.x Mint? If yes, the installation of latex is more than 3 years old. Manually installing this package will fix your issue

**Comment by kassbohm** [comment]
Yes, Mint 19.1. Manual installation of just the scontents-package did not fix the issue. I did try this before - and got different errors... due to incompatabilities.

Is it necessary to include a package or file, which is not included in recent and common Linux editions? I could not find scontents.sty in Mint 20 either... or am I looking for the wrong file?

**Comment by Rmano** [comment]
The[ `scontents` package](https://github.com/pablgonz/scontents) is really recent, and it uses extensively `LaTeX3` functions, so it's not really probable that it could work with distributions with a LaTeX system older than 2019. 

So it would be better to not depend too much on it, if possible, at least until the 2018 LTS releases become older ;-) (sorry, I disconnected a bit from `xournalpp` development later, due to the preparation for the new academic year).

**Comment by kassbohm** [comment]
That makes it clear, thanks.

Just for completeness: Here is the error-message I get, after:

1. manually installing scontents-package and
2. trying to run one of the examples with either latex or lualatex or pdflatex: 

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/unknown-argument-type"
! 
! Unknown argument type '!' for the command '\Scontents'.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

**Comment by Rmano** [comment]
> !
> ! LaTeX error: "xparse/unknown-argument-type"
> !

Yes, this is probably because the LaTeX kernel is too old.

**Comment by rolandlo** [comment]
That's my mistake. If you can't update your Tex installation to have a working scontents package, then you best use the default_template.tex file before I made it use the scontents package (in [this commit](https://github.com/xournalpp/xournalpp/pull/1952/commits/5ca27301f73857f8d24589f79326c9672c07b68f)) You can do that by replacing your default_template.tex file by the .tex file in this zip-file:

[default_template_old.zip](https://github.com/xournalpp/xournalpp/files/5155888/default_template_old.zip)

You won't be able to do stuff like code syntax highlighting, where the code lines must be used verbatim, however.

**Comment by Rmano** [comment]
What about leaving both files in the distribution? Maybe a `legacy_template` that can be switched on the fly?

**Comment by kassbohm** [comment]
@rolandlo Just mentioning: Yes. It works with the "old" default_template.tex. Thanks.

**Comment by rolandlo** [comment]
@Rmano What exactly is your suggestion? Leaving the default_template.tex as currently provided and adding a legacy_template.tex which is the "old" default_template (the one without the scontents package)? That would certainly be possible.

**Comment by Rmano** [comment]
> @Rmano What exactly is your suggestion? Leaving the default_template.tex as currently provided and adding a legacy_template.tex which is the "old" default_template (the one without the scontents package)? That would certainly be possible.

Yes, that is the idea. I imagine there is a menu or drop down to choose among templates,  so having the "legacy" one at hand would be nice.

**Comment by rolandlo** [comment]
It's easy to switch templates. One just needs to press the button named after the global template file (in the LaTeX settings panel)
![grafik](https://user-images.githubusercontent.com/40485433/91907368-058ddc80-ecaa-11ea-962a-e8cd8fa5bc27.png)
to choose the file. 
But maybe using the template without scontents as default would be the safer choice, since some users will still complain if it does not work out of the box. Maybe we could call the global template file with scontents`advanced_template.tex`. I am open for better name suggestions.

**Comment by Rmano** [comment]
More than the name (could it be `modern`, but don't trust my English), it would be better to have some kind of discover-ability. One idea could be to put at the start of the template file a couple of lines like:
```
% XOPP-TEMPLATE-DESCRIPTION
% This template should work with most LaTeX installation, but will not allow for verbatim material (like listings). 
```
... and then display this message in the dialog, under the selection gadget? Will be handy also for contributed templates (for example, one that typeset text in Ti*k*Z shapes, a pgfplot one, etc...)

**Comment by Febbe** [comment]
I think we should add the possibility to either choose one of both from a dropdown or import one over an textview/open file.
- [ ] check if file default_template.tex and legacy_template.tex exist. If not create them in our config dir under eg ./tex.
- [ ] try to test default_template.tex and then legacy_template.tex
- [ ] In the preferences show a Dropdown and an text_view. If an non working template is selected show a warning next to the dropdown or directly below.
- [ ] Add one or two "+" buttons (in place or import(copy or link I don't know which is better)) and one "-" to remove an existing template.
- [ ] Add new templates with a file named <name>_template.tex or just <name>.tex in the template dir.
- [ ] Add a copy button
- [ ] Optionally add a "open external" button
- [ ] default and legacy can't be edited only viewed.

What do you think of those points?

**Comment by Rmano** [comment]
I think this is great --- much more than I thought. I still suggest keeping the information that will appear in the text_view  in the template file as a comment, it's easier to keep in sync and will be useful in the future.

**Comment by Febbe** [comment]
The text view should show exactly the contents of the file. So a user is not required to edit it externally. But he still can

**Comment by rolandlo** [comment]
@Febbe 
To me your suggestion looks rather sophisticated. What problems exactly are you trying to solve? 
In my opinion the templates can perfectly be edited (and commented) in an external editor. The main problem that remains to be solved is that the same xopp-file may produce different results with different .tex-templates. If you start modifying your template then you may not remember, with what template a .xopp-file was produced. This could be solved by attaching (a non-standard) .tex-template to the Xournal++ document (like the document background). Maybe similar to attached mode pdf-backgrounds it could be saved under the same name like the xopp-file with an additional extension (like foo.xopp.tex or foo.xopp.tpl.tex). This will be cleaner with the new file format (based on zip-archives that contain multiple files). If there is no attached tex-template the standard (default or legacy, what works) template could be used.
The second problem is that the standard templates may be overwritten. Maybe these templates could be made read-only and commented in a way that makes it clear what they are designed for.

Ok, I can't say what solution is optimal, but it is important to get a clear idea, what the problems to be solved are.

**Comment by Technius** [comment]
How about creating a folder for latex templates in the user config directory (`~/.config/xournalpp/latex-templates/`)? The default template will be packaged into `/usr/share/...` and will be copied into the latex template folder if the folder does not exist. This would make it convenient for the user to create custom global settings or project-specific settings.

**Comment by Rmano** [comment]
> How about creating a folder for latex templates in the user config directory

That's a good idea, but I would let the things separated. Suppose you have an update or a bug fixed in one of the standard templates, you want the user to use that even if they already have installed `xournalpp` in a previous version.
I think that 
- a "system" directory for templates and
- an "user" directory for templates, 
both searched, would be the best solution. Let's add the possibility to add informative text in the template visible in the phase of template selection, as I suggested in https://github.com/xournalpp/xournalpp/issues/2206#issuecomment-685373584, and I think that will be easy to implement and to understand.

**Comment by xabier8** [comment]
Thank you so much @rolandlo for providing the template file! Lifesaver!
