### ISSUE TITLE
File corrupted when adding/removing images

### ISSUE THREAD

**Issue by beijoca** [xournalpp/xournalpp#2207]
**Affects versions :**
 - OS: MacOS Catalina 10.15.6
 - Version of Xournal++: 1.0.17

**Describe the bug**
when adding and removing images in the MacOS Xournal++.app, files can become corrupted.

**To Reproduce**
updated: it is difficult to reproduce this bug. I am therefore closing this issue (see comment below), but am leaving the corrupted file as a reference

[corrupted_file.zip](https://github.com/xournalpp/xournalpp/files/5155823/corrupted_file.zip)

**Comment by beijoca** [comment]
update: I repaired the file myself:

-renaming .xopp to .gz
-unzipping using gzip
-editing in jedit using its XML-plugin (http://www.jedit.org/)
-removing the last page: \<page> ... \</page>
-gzipping
-renaming .gz to .xopp

After removing the last page in the XML tree i could handle the file in Xournalpp without any problems. I turns out, that the last page contained the following tags:

\<image left="421.32433488" top="298.13886968" right="420.32433488" bottom="297.13886968">\</image>
\<image left="421.32433488" top="298.13886968" right="420.32433488" bottom="297.13886968">\</image>
\<image left="421.32433488" top="298.13886968" right="420.32433488" bottom="297.13886968">\</image>

Clearly, the actual image information was missing. Indeed, when creating the original file I added an image to the last page and deleted this image again. I've updated the original issue to reflect this.

**Comment by Febbe** [comment]
Thank you for pointing this out!
