### ISSUE TITLE
Poppler Error

### ISSUE THREAD

**Issue by Jadamso** [xournalpp/xournalpp#221]
**I am not able to install due to a poppler error**

**My system is**
Linux x230-linux 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 12:04:35 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**The error is**
[Jadamso@x230-linux build]$ cmake ..
-- Could NOT find Boost
-- Could not find poppler include dir
CMake Error at cmake/find/FindPoppler.cmake:74 (file):
  file STRINGS file
  "/home/Jadamso/xournalpp/POPPLER_INCLUDE_DIR-NOTFOUND/poppler-config.h"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)

**Comment by andreasb242** [comment]
Boost needs to be installed, and for poppler there is now an additional build fix merged currently, so I close this ticket also because of age
