### ISSUE TITLE
"Save" command don't save existing file 

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2210]
I am working with windows 10 . I have installed last nightly release of xournalpp.
When I create a document and save it, there is no problem.
But when I modify an existing document and  I save it with the command "save", the file is not saved (There'is no message).
If I want it to be saved, I must make "save as".

**Comment by Febbe** [comment]
I just testet it on my windows mashine, to fix that ASAP, but I cant reproduce this.
Can you tell me the path and filename you are using?

**Comment by MichelReims** [comment]
I have installed the automated nightly release named "xournalpp-1.1.0+dev-nightly.20200902-windows.exe"

1) I open xournal++ and write something.
2) I save this document in folder "C:\temp", with filename "a.xopp" ; for this, I use the menu command "Save as" (Note : If I want save the document in "C:\" folder,  I have  the message : "Save file error : Error openning file "C:\temp\a.xopp" ; and the file is not saved)
3) I quit Xournal++ and I reopen it.
4) I open the file "a.xopp"
5) I write something else in the document "a.xopp"
6) I use the shortcut "Ctrl+S" to save the document.
7) Then I choose in menu "File->Recent Document"  and I choose "a.xopp". I see that changes have not been saved.

(Note : I remark that I find the autosave ".a.autosave.xopp" in "C:\temp")

**Comment by MichelReims** [comment]
I can't reproduce this problem every time.

**Comment by MichelReims** [comment]
I think that the file is not save with CTRL+S, if an autosave file has not been created. I Think that Xournal make a confusion between file and autosave file

**Comment by Febbe** [comment]
Ok I will have time today. I'll try to reproduce this again. Hopefully I'll find that.

**Comment by MichelReims** [comment]
Thank you

**Comment by MichelReims** [comment]
I'm sure there is a problem but I cannot reproduce each time. Version 1.0.18 does not have the problem

**Comment by Febbe** [comment]
When you opened xournal++ over console, there could be error messages.

**Comment by Febbe** [comment]
Thank you for the hint with the autosave file. I can confirm the issue.

**Comment by Febbe** [comment]
It seems like a bug in Mingw
```
#include <iostream>
#include <fstream>
#include <filesystem>

namespace fs = std::filesystem;

constexpr auto * f1 ="C:\\TEMP\\fred_test.txt";
constexpr auto * f2 ="C:\\TEMP\\fred_test.txt~";

void create_file(char const* p){
    std::ofstream ofs1{p};
}

int main() {
    try{
        fs::remove(f1);
        fs::remove(f2);
        create_file(f1);
        create_file(f2);
        fs::copy_file(f1, f2, fs::copy_options::overwrite_existing);
        std::cout << "success" << std::endl;
    } catch (fs::filesystem_error const& fe) {
        std::cout << fe.what() << std::endl;
    }
}
```
Results in: filesystem error: cannot copy file: File exists [C:\TEMP\fred_test.txt] [C:\TEMP\fred_test.txt~]
Which definitely should not happen, since I defined fs::copy_options::overwrite_existing

**Comment by Febbe** [comment]
should be fixed now.

**Comment by MichelReims** [comment]
Very much thanks
