### ISSUE TITLE
PDF from other file will be shown

### ISSUE THREAD

**Issue by chunyboy** [xournalpp/xournalpp#2216]
**Affects versions :**
 - OS: Linux (and Windows 10)
 - Linux Desktop environment: Gnome with X11
 - Which version of libgtk do you use: 3.24.5-1
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
I have two different .xopp files, both annotated a PDF (not the same PDF). First opening one of the .xopp File. Then opening the other file by the menu and the second file shows the PDF background from the first file.

**To Reproduce**
1. Having to file: e.g: p1.xopp and p2.xopp (both have annotated a PDF)
2. Opening p1.xopp.
3. In the opened file p1.xopp, click "File->Recent Documents->p2.xopp"
4. The PDF from file p1.xopp will be shown as background

**Expected behavior**
Show the expected PDF as background.

**Comment by rolandlo** [comment]
This has been fixed with PR #2009 (on May 25), but has not made it yet into the latest stable version (currently 1.0.18 from April 15)

**Comment by chunyboy** [comment]
Thank you for the information :+1:
