### ISSUE TITLE
No way for touch movement with touchWorkaround enabled

### ISSUE THREAD

**Issue by hashworks** [xournalpp/xournalpp#2217]
**Affects versions :**
 - OS: Linux (Arch Linux)
 - Version of Xournal++: 1.0.18
- Device: Microsoft Surface Go 2
- Desktop Environment: Wayland Gnome

**Describe the bug**
With `touchWorkaround` disabled moving around the document with a single finger works as expected. The pinch-to-zoom feature however is quite unreliable, causing the document to flicker around between unexpected zoom levels.

Enabling `touchWorkaround` fixes this - the pinch-to-zoom gesture works as expected. However, this also causes me to not be able to move in the document with one finger - instead it uses the eraser by default.

It seems like I'm not possible to change this behavior to "move in document" - in the "Touchscreen" menu I can not select my touchscreen, only my pen, eraser, mouse and touchpad.

In the "Input System" menu, the "Wayland Touch" input device is actually set to eraser - I can set it as "Touchscreen", which results in drawing when I touch with one finger, not movement. Same behavior for the options "Mouse" and "Pen", "Disabled" works as expected. Here an additional option "Hand" would be great.

**To Reproduce**
1. Enable `touchWorkaround` to fix pinch-to-zoom on a device that misbehaves
2. Expect movement by touch to work like it did before
3. Find no option to adjust the behavior

**Input Logs**
Please request if needed.

**Expected behavior**
It should be possible to adjust the single-touch behavior with `touchWorkaround` enabled to "Hand" or "move-in-document".

**Additional context**
I'm using the experimental input system, disabling it doesn't affect the bug.

**Comment by Febbe** [comment]
The touchWorkaround won't be fixed anymore, because it is deprecated. It will be removed in future releases.

**Comment by hashworks** [comment]
@Febbe That's alright, but is there any other way to fix my pinch-to-zoom? Or do you want me to open an issue about it?

**Comment by Febbe** [comment]
We have open issues for that, just search for the zoom tag. This is a very huge issue, we also thought about to rewrite the hole application with QT instead of gtk because of that.

**Comment by Febbe** [comment]
And for exactly your issue there is already a fix in the unstable nightly.
