### ISSUE TITLE
error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#2222]
The build of version 1.0.18 with clang-11 on FreeBSD 13 fails:

```
/wrkdirs/usr/ports/graphics/xournalpp/work/xournalpp-1.0.18/src/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp:274:2: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        g_return_val_if_fail(d != NULL, NULL);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gmessages.h:599:10: note: expanded from macro 'g_return_val_if_fail'
         return (val);                                                  \
                ^~~~~
```

Log: http://beefy18.nyi.freebsd.org/data/head-amd64-default/p547769_s365371/logs/xournalpp-1.0.18_4.log (IPv6 URL)

**Comment by Febbe** [comment]
This is fixed on the current master

**Comment by koobs** [comment]
@Febbe Thanks for resolving. Can you link the commit that addressed the issue?

**Comment by Febbe** [comment]
I did not fixed it I think. But you can find the commit, by using git blame over the GitHub page. Just open the file in the browser, search for the blame button and go to the corresponding line.

**Comment by Febbe** [comment]
@technius can you add the Bugfix to v.1.0.19?

**Comment by koobs** [comment]
@Febbe I looked at the last 30 days of history on master, but didn't identify anything obvious, but I may have missed it (apologies if i did)

A history on the file in question (toolbarCustomize/ToolbarAdapter.cpp) also showed no recent history.

**Comment by Technius** [comment]
> @Technius can you add the Bugfix to v.1.0.19?

I can't find the commit either. I already backported most of the minor patches made between June and September.

**Comment by yurivict** [comment]
@Febbe @Technius 

Any chance to fix this?

**Comment by Tejv1708** [comment]
if (root) {
        invertTree(root->left);
        invertTree(root->right);
        std::swap(root->left, root->right);
    }
    return root;

Line 25: Char 16: error: cannot initialize return object of type 'TreeNode *' with an lvalue of type 'TreeNode *[n]' return ans ; ^~~ 1 error generated ?

**Comment by bhennion** [comment]
Is this really still happening? On which compiler? Which version? Which Xournal++ branch (master, release, v1.1.1)?

@Tejv1708 You seem to be mentionning a different error, so please report it in a new ticket, with all the above info as well.

**Comment by Tejv1708** [comment]
@bhennion 
No , it is problem of compiler , Now it's ok .
Thanku :)
