### ISSUE TITLE
Recently used file with "no such device" causes Xournal++ to crash at start.

### ISSUE THREAD

**Issue by hashworks** [xournalpp/xournalpp#2225]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: Gnome-Wayland
 - Version of Xournal++: 45a619d83f97205c92ac146f13d5ae00af83af7e
 - Installation method: AUR ([xournalpp-git](https://aur.archlinux.org/packages/xournalpp-git/))

**Describe the bug**
When a file exists in the "recently used files" where the device is not available (f.e. a Samba mount) Xournal++ crashes at start.

**To Reproduce**
1. Mount a samba drive using a VPN interface
2. Open the file in Xournal++, close it
3. Make sure the VPN interface is not available without unmounting the Samba drive (`no such device`)
4. Re-open Xournal++

**Expected behavior**
Xournal++ ignores the unavailable file.

**Additional context**
Crash:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: No such device [/mnt/samba/mount/that/is/not/available/file.pdf]

** (com.github.xournalpp.xournalpp:26191): WARNING **: 12:39:29.368: [Crash Handler] Crashed with signal 6

** (com.github.xournalpp.xournalpp:26191): WARNING **: 12:39:29.369: [Crash Handler] Wrote crash log to: $HOME/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200908-123929.log
```

Error log: https://fb.hash.works/HMqP0W

File path is from `./.local/share/recently-used.xbel`:
```
<bookmark href="file:///mnt/samba/mount/that/is/not/available/file.pdf" added="2020-09-02T23:54:55Z" modified="2020-09-03T00:00:03Z" visited="1969-12-31T23:59:59Z">
```

This sounds like something that should've been fixed with #1730, but as I stated above I'm using the latest version in master.

**Comment by Febbe** [comment]
Does this still occur? I can't reproduce this with an unmounted hard drive.

**Comment by hashworks** [comment]
The problem is that the device is still mounted – it's the access that fails due to network issues. Works just fine if I properly unmount it.

**Comment by Technius** [comment]
Can you `git bisect` to see which commit caused this?

**Comment by hashworks** [comment]
Yes, maybe I can find time for that this evening.

**Comment by hashworks** [comment]
> Can you `git bisect` to see which commit caused this?

I now don't think this is a regression. First of, #1730 is unrelated to this– 1730 is about ignoring invalid paths. This bug is about paths that do exist and are valid but optionally have a long timeout and eventually result in a filesystem error "Host is down", "Resource temporarily unavailable" or "No such device" and other possible errors.
I went back to 1.0.18 / 535d261, same error.

Basically there are three problems:
1. Instead of just saving a list of the recent files on boot, Xournal++ accesses them all in some way. Those files might take forever to read due to a network issue. Instead, they should only be read when they are actually to be opened.
2. Filesystem timeouts might be too long. The user should have the option to abort any file access.
3. Instead of ignoring files that can't be read due to filesystem errors, Xournal++ crashes.

**Comment by hashworks** [comment]
This could happen [here](https://github.com/xournalpp/xournalpp/blame/d14f01d76fd32659e95ceb8f83d6bb1bc9774e8e/src/control/RecentManager.cpp#L133).

What happens when one runs `fs::exists` on a path that exists, but takes very long to access and eventually throws a filesystem error?
