### ISSUE TITLE
xournalpp doesn't show latex formula

### ISSUE THREAD

**Issue by afgoya** [xournalpp/xournalpp#2227]
Hi,

my name is Andres and I'm kind of new user of Ubuntu and Linux. My programming skill are quite basic.
I'm having problems to instert tex when using xournalapp. I installed xournalpp from the PPA following:
sudo add-apt-repository ppa:andreasbutti/xournalpp-master
sudo apt update
sudo apt install xournalpp

(Before that I installed xournalpp using the deb file but I wasn't able to enter Preferences to configure my pen buttons so I remove it and installed from PPA).

**Affects versions :**
 - OS: Ubuntu 18.04.t
 - Version of Xournal++ 1.1.0+dev

**Describe the bug**
When I try to insert latex into the notebook it doesn't show the compiled formula.

**To Reproduce**
1. Either press Crtl+Alt+X to add latex or go to the menu >Tools>Add/edit Latex
2.It doesn't show any formula as if the syntaxis was wrong
3. Going to Preferences >> LaTeX and clicking in test configuration, the following message appears:
Error: Child process exited with code 1. Please check the contents of /tmp/xournalpp-12495/tex
(with successive attemps the number changes)

**Input Logs**
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5203592/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5203594/debug_gdk_input.log)
[xinputlist.txt](https://github.com/xournalpp/xournalpp/files/5203600/xinputlist.txt)

**Expected behavior**
I would like to be able to insert latex in my xournal notebook

**Screenshots of Problem**
Screenshot step 2
![xournalppX](https://user-images.githubusercontent.com/71086772/92766851-fb847180-f36c-11ea-8ab5-a2126ed53bad.png)

Screenshot step 3
![xournalppError](https://user-images.githubusercontent.com/71086772/92766966-0f2fd800-f36d-11ea-9e18-3538e27af071.png)

Since my programming skills and my knowledge about Linux are quite basic I will be very grateful if the steps to achieve a possible solution are as much detail as possible.

Thanks in advance.

**Comment by rolandlo** [comment]
To find out what your problem is, you should follow the advice in the test configuration error message: "Please check the contents of ...". Most likely you lack the `scontents` LaTeX package and need a template that doesn't use this package (unless you manage to update your tex distribution). See issue #2206. A suitable template is provided there.

**Comment by afgoya** [comment]
@rolandlo Thank you very much for your answer!

After I post this issue I checked in `/tmp/xournalpp-12495/tex`  the `tex.log` file and found 
`! LaTeX Error: File `scontents.sty' not found.`
I tried to download `scontents.sty` but I couldn't.

The solution was to replace the template provided in [#2206](https://github.com/xournalpp/xournalpp/issues/2206) as you said.

Thanks.
