### ISSUE TITLE
xournal in ubuntu open file but in pop_os not open

### ISSUE THREAD

**Issue by catalunha** [xournalpp/xournalpp#2228]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
![image](https://user-images.githubusercontent.com/19995819/92810732-2df59500-f394-11ea-87e1-ea05fb1a5d68.png)

 - Which version of libgtk do you use
not find
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
![image](https://user-images.githubusercontent.com/19995819/92810275-cb03fe00-f393-11ea-9c16-dd5386e68472.png)
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
Flathub (flatpak)
**Describe the bug**
he can open the largest file but not the smallest. and they are the same. In ubuntu LTS 20 ok but in POP OS  LTS 20 not open.
![Screenshot from 2020-09-10 18-11-20](https://user-images.githubusercontent.com/19995819/92810843-4a91cd00-f394-11ea-871e-054c4cc42c26.png)
![Screenshot from 2020-09-10 18-12-00](https://user-images.githubusercontent.com/19995819/92810878-51b8db00-f394-11ea-8228-1d1e39bae93d.png)

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Comment by Febbe** [comment]
can you try the latest master if it does not work with 1.0.18?

**Comment by catalunha** [comment]
obrigado por responderem. 
este aplicativo é muito pratico pra edição de pdf. 
parabens. 
evitem complicar com funcoes demais. mantenham simples como esta: camadas, texto, lapis e imagens. acho q latex complica sem necessidade pode ser substituido por imagens de equações.
mas vamos ao problema desta issue.
sorry my english is still not so good. but trying hard. i am using google translator. I read better than I write.
in this figure the same file with 18MB and producer adobe does not open with two clicks via Files 2.26.3. I am using POP-OS 20LTS
![image](https://user-images.githubusercontent.com/19995819/93015363-3a920d00-f58f-11ea-9851-8786a0e4cc24.png)
but when I change the file to the 195MB cairo producer it opens in two clicks in the Files.
but see that on ubuntu 20LTS this did not happen. but I have no record of which version of xournal I used there. but it was installed via the ubuntu installation pattern. with two clicks you would normally open the 18M file (cairo). so I didn't need to generate 195 (cairo)
![image](https://user-images.githubusercontent.com/19995819/93015462-17b42880-f590-11ea-9047-898b55f2bcac.png)
I did a reinstallation via ppa to see if it worked. but the problem remained
![image](https://user-images.githubusercontent.com/19995819/93015486-492cf400-f590-11ea-84de-4a26bfa112f1.png)
![image](https://user-images.githubusercontent.com/19995819/93016007-53e98800-f594-11ea-94d7-878603a4aec8.png)

there something happened that I did not expect. 
see that with two clicks the 18M adobe file cannot be opened. via Files.
![image](https://user-images.githubusercontent.com/19995819/93015612-336bfe80-f591-11ea-88a7-d56907a1b567.png)
but when I opened it via terminal. see q opened xournal normally with the 18M adobe file. that is, via click does not open but via terminal yes.
![image](https://user-images.githubusercontent.com/19995819/93015651-762dd680-f591-11ea-96fe-94df8b6426d7.png)
and I have no way to get the shares out via two clicks on the Files.

********
another surprise.
********
I went to the pop shop and uninstalled the version via flatpak. maintaining the version via ppa. I used two clicks via file and normally opened the 18M file (cairo). that is.
I think the installation via the popshop flatpak brought me some problems as described above.
but now everything is normal.
I did tests on other xournal files that I have and the above problem didn't happen anymore. really flatpak was not a good installation choice in this case.
keep the descriptions above to solve for other users who install via flatpak

**Comment by Febbe** [comment]
Thank you for your detailed description. We know, that there are issues with flatpack. It runs every software in a sandbox and because of that permission issues occur.
