### ISSUE TITLE
Unusual pdf export not half erased (all) 'n' letter

### ISSUE THREAD

**Issue by hiteshhedwig** [xournalpp/xournalpp#2230]
**Affects versions :**
 - OS: Linux
 - Desktop environment: Ubuntu 18.04
 - Version of Xournal++: 1.0.16, 07cb970f, Built on Jun 2 2020, 17:07:56
 - Installation method: Ubuntu Software

**Describe the bug**
File details: 35MB
When ever i export this pdf after writing off my notes. The Exported version has all (only) 'n' letter crossed.
It did not happen in the pdf which were of low size. 

**Screenshots of Problem**
![Screenshot from 2020-09-12 09-29-59](https://user-images.githubusercontent.com/40434383/92986917-cf3b3300-f4db-11ea-9942-4dba900bd1ef.png)

**Comment by hiteshhedwig** [comment]
![Screenshot from 2020-09-12 09-29-59](https://user-images.githubusercontent.com/40434383/92987003-54bee300-f4dc-11ea-9634-ed64994fe792.png)

**Comment by rolandlo** [comment]
Can you provide the pdf page in question for testing purpose? You may use `pdftk IN:PDF cat PAGENO output OUT:PDF` replacing the capitalized strings appropriately. Or does is it only happen with the full pdf?

**Comment by hiteshhedwig** [comment]
> Can you provide the pdf page in question for testing purpose? You may use `pdftk IN:PDF cat PAGENO output OUT:PDF` replacing the capitalized strings appropriately. Or does is it only happen with the full pdf?

It happens with entire pdf. All 500+ pages.

**Comment by Febbe** [comment]
Is this PDF specific? And can you send us the PDF (one page is enough if it also fails with that)?

**Comment by Febbe** [comment]
Antother thing: You are using the snapcraft image, which is not supportet / maintained by the xournal++ team. A community manager is responsible for that. Can you check out the 1.0.18 or 1.1-dev version? Also update poppler and gtk.

**Comment by hshKUMAR** [comment]
@Febbe  Sorry for the late reply but that seems to work. Thanks!

**Comment by Technius** [comment]
Does this issue still occur?

**Comment by Febbe** [comment]
I think, even if yes, we need the PDF to debug it. And since @hiteshhedwig reacted with 🚀 I also believe my tip to update worked.

**Comment by hiteshhedwig** [comment]
Hi, It had worked. Sorry for late response. Closing the issue.
