### ISSUE TITLE
PPA not working on Debian, dependency issue with libzip5

### ISSUE THREAD

**Issue by Zocker1999NET** [xournalpp/xournalpp#2231]
**Affects versions :**
 - OS: Debian GNU/Linux Testing/Unstable
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: I couldn't obtain this using the **About** dialog (maybe due to an old version):
![2020-09-11_10-09-52](https://user-images.githubusercontent.com/1645646/92913269-22e54800-f41a-11ea-955f-f128b0f8cbc6.png)

 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
I cannot install/update Xournal++ from PPA (which is the official installation method for Debian as a "Ubuntu derivative" as you see it).

**To Reproduce**
Expecting Xournal++ was installed using the PPA on Debian before the renaming.
An extract of my `sources.list` files:
```
deb http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu focal main
```

The following error happens while trying to update only xournalpp using `aptitude update && aptitude install xournalpp`:
```
The following packages will be upgraded:
  xournalpp{b}
1 packages upgraded, 0 newly installed, 0 to remove and 329 not upgraded.
Need to get 904 kB of archives. After unpacking 72,7 kB will be used.
The following packages have unmet dependencies:
 xournalpp : Depends: libzip5 (>= 1.0) which is a virtual package and is not provided by any available package

The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     xournalpp [1.0.6-0~202002231917~ubuntu19.04.1 (now)]
```

**Expected behavior**
Upgrade without complaining about missing dependencies

**Screenshots of Problem**
![2020-09-11_10-09-58](https://user-images.githubusercontent.com/1645646/92914316-0e557f80-f41b-11ea-9986-7fe6835ad691.png)

**Additional context**
It seems that the team behind Debian not decided to rename libzip4 to libzip5 to prevent breaking dependencies of older or external packages. But the team behind Ubuntu decided to rename libzip4 to libzip5. Still it seems that both distributions provide the same version for their newest stable / LTS releases, see the version of [Debian package](https://packages.debian.org/buster/libzip4) and the version of [Ubuntu package](https://packages.ubuntu.com/focal/libzip5).

**Comment by Febbe** [comment]
We don't consider debian to be a "ubuntu derivate", thats why the ubuntu ppa is binary incompatible with debian. Please use the dowwnload in the release section.

**Comment by Zocker1999NET** [comment]
Okay, then the README should be changed to reflect that the PPA should not be used by Debian users. The following quote of the README lead me to the idea, that Debian may use the PPA too, because other projects try to make their PPA releases compatible to both Ubuntu and Debian:
> If your system is not one of the specific Debian or Ubuntu versions that are supported by the official binaries, we recommend you use either the PPA, the Flatpak, or the AppImage.
Also the README could reflect, that the releases on GitHub contain the only official supported Debian build (beside the fact that there are nightly builds available, this made me think that the GitHub releases **only** house nightly builds).
I will propose a change to the README.
