### ISSUE TITLE
Packaged File Format Project Status

### ISSUE THREAD

**Issue by Geo25rey** [xournalpp/xournalpp#2233]
I'm interested in contributing to Packaged File Format Project, but it seems to have not been active for about a year and it's unclear what the next step is further progression. It looks @LittleHuba was working on it, so I'd like your input on where I can begin. 

Based off of what has been discussed in the issues marked as "done", it seems like there is no detailed specification for the proposed file format. Would that be a good starting point?

**Comment by LittleHuba** [comment]
@Geo25rey sorry for the late answer. If you are still interested in helping, please reach out to me on Matrix (@littlehuba:matrix.org).

**Comment by Geo25rey** [comment]
> @LittleHuba:matrix.org

Done
