### ISSUE TITLE
Copying by holding the erase button doesn't work anymore

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#2234]
**Affects versions :**
 - OS: Manjaro Linux
 - Version of Xournal++: 1.1.0 dev e3cb4607

**Describe the bug**
Before you could select an object, hold the erase button and drag it to instantly make a copy. This was a pretty neat feature and now it is gone.

**To Reproduce**
1. Select object
2. Hold erase button and drag
3. You only drag, but it should make a copy

**Comment by Febbe** [comment]
- As I know it newer was a feature which actually worked, since it was a display bug. Someone seems to fixed that bug and the result is, that this behavior also vanished.

**Comment by coldspark29** [comment]
Well it was a pretty useful bug then... and I want it back! :D Or at least an option to activate it again

**Comment by Febbe** [comment]
Unfortunately we don't have a shortcut manager. Then it would be pretty easy to implement again. But currently I would have to hard code this for button type 'ERASER'. And that's pretty ugly.

**Comment by coldspark29** [comment]
Why? You will not erase anything while having on object selected. It blended perfectly into the environment. I haven't had any issues with it and it was honestly one of the most useful "features". At least I always thought it was. I was pretty enthusiastic about it. My prof once asked me how I drew that so fast. I would draw two lines, select them and multiply them. Then do the same with the four. I was awesome. Having a hotkey four this wouldn't make much sense, since you don't use the keyboard while dawing. At least I don't, since I have a convertible laptop.

**Comment by Febbe** [comment]
The eraser button is also a hotkey which can be assigned for that job. So shortcut / hotkey managers are not limited to keyboard devices 😅.

**Comment by coldspark29** [comment]
Okay, then I consent :100:

**Comment by ehremington** [comment]
oh i'm so glad i saw this before updating... so now i won't. this was an insanely useful feature. i'm a physics prof and the speed of drawing live in class is excellent. if i could only get quickly producing a mirror image like the old xournal i would be set!

**Comment by coldspark29** [comment]
Of course you only use the pen. Just think in terms of usability. In companies they have well paid usability engineers that come up with features like this to make working faster and smoother. This feature made Xournal++ a great experience. Please get it back!

**Comment by rolandlo** [comment]
@coldspark29 If you could find out, in what version this bug/feature was working and when exactly (with which commit) it stopped working, this would be a great help. One way to figure this out is to run `git bisect`

**Comment by coldspark29** [comment]
I will try out later. Thanks

**Comment by coldspark29** [comment]
Guess I need at least one version for this. @ehremington What version do you currently have?

**Comment by coldspark29** [comment]
Can someone confirm that what I am doing is right? I am creating new branches via

```
git checkout -b old-project-state 48b5da
```

and then I build them to test whether the feature was still working or not. 48b5da was the latest and it is 9 months old. I am pretty sure that the feature was still working back then. Is this the right way to go? I don't really understand bisect yet

**Comment by rolandlo** [comment]
Yes, you can do it that way. Creating branches is not really necessary.

Let me explain `git bisect`:
It has the advantage, that it automatically picks you the next commit to test using a binary search. You first start git bisect, then you have to indicate a good commit and a bad commit. This starts the binary search process, where in every step git chooses (and checks out) a commit to test. Then you build the commit and test it and tell git, whether it was good or bad.

So you could start by typing:
```
git bisect start
git bisect bad HEAD
git bisect good 48b5da
```
Git will choose a commit (in the middle between the good and the bad commit) and check it out. Then you build and test and either type `git bisect good` or `git bisect bad` depending on the success of the test. Repeat until the process finishes and note down the last good commit. A more detailed explanation is given in [this article](https://flaviocopes.com/git-bisect/).

**Comment by coldspark29** [comment]
Well, but if a 9 months old commit still doesn't contain the feature, there a hundreds of commits in between. I really need the commit number from @ehremington

**Comment by rolandlo** [comment]
With git bisect (which uses binary search) you need only n-1 steps if the number of commits is 2^n. For instance if you have <=1024 commits, you will only need <=9 steps. This is much more efficient than trying out all commits in between.

**Comment by coldspark29** [comment]
Ah I understand. It lists all the commits in a binary search tree. Interesting feature of git. Nonetheless, I can't find a commit that still has the feature. I went back to the beginning of 2019 and it was definitely still there then. So I assume it was actually it display bug caused by GTK or some other components. If this is the case, there is nothing to get back and it has to be implemented from scratch as @Febbe said

**Comment by rolandlo** [comment]
That's possible. Another possibility would be that it was some setting for input devices that caused that behavior. Anyway, I think it should not be that hard to implement it. It is a matter of modifying the condition in [these code lines](https://github.com/xournalpp/xournalpp/blob/master/src/gui/inputdevices/PenInputHandler.cpp#L118-L120?) from the pen input handler.

**Comment by coldspark29** [comment]
I would try if I had the time. I am in my last semester and can’t spare any of it.

**Comment by ehremington** [comment]
@coldspark29 i am on the ppa and it tells me version 1.1.0+dev, but I do not know what commit or build it is unless you can tell me how to do it. Mine says it was built on Aug18, 2020. I don't update it very often so that it does not break in the middle of a week of classes.

**Comment by ehremington** [comment]
And yes I use a wacom, so for me it is the second side button that makes a fast copy of whatever is highlighted/selected. I'm all for bug squashing, but this was one of those surprisingly useful "glitches" that I thought was a feature. But I have a keyboard handy, so ctrl-c, ctrl-v is almost as fast if it has to go away.

**Comment by ehremington** [comment]
also i'm on libgtk 3.22.30 if that helps

**Comment by coldspark29** [comment]
@ehremington The commit is a code like e2bf23 or similar. If you can give me that, I can try to build it, but I think it is not related to the Xournal++ version.

**Comment by rolandlo** [comment]
@coldspark29 Looking at the commit history, the PPA version from August 18, 2020 is probably 385a0d61a40bad5a58ad7157699e3d5774804555
This would include the LaTeX enhancements.  @ehremington If you don't have the LaTeX enhancements, then it must be commit b9a13dec6bae00f1fe57a1564a311dd5c4b5ada5
The LaTeX enhancements contain a LaTeX panel in the preferences. So that's easy to check.

It really might be related to the libgtk version; 3.22.30 is not very recent. I am on 3.24.20.

**Comment by coldspark29** [comment]
So I downgraded to gtk 3.22.30 and compiled a Xournal++ version from Frebruary 2019. Still the feature is not there.

**Comment by Febbe** [comment]
Maybe search for a commit by @idotobi he changed the behavior of the tool selection while pressing one of the stylus buttons.

**Comment by Febbe** [comment]
Also delete the build dir after each step of git bisect.

**Comment by coldspark29** [comment]
@Febbe I built the last build before his first commit and also deleted my config folder. The build folder also of course. The feature is not there. This is really strange.

**Comment by ehremington** [comment]
I tested this on an updated xournalpp on a second laptop and it still works for me. 

Linux Mint 20, xournal built on September 23, libgtk 3.24.20

i do have latex panel in the preferences menu. 

could this be related to the fact that the wacom stylus has two buttons and it is acting like a mouse button like @rolandlo mentioned? in other words its not my eraser button that does this but my select rectangle button.

**Comment by rolandlo** [comment]
@ehremington Yes, if you have a stylus with a button that is attached to "button 2" in the preferences, then it shouldl show this behavior. Do I understand correctly that you have 3 buttons on your stylus (including the eraser button)? Maybe a Wacom Pro Pen 3D stylus?
![grafik](https://user-images.githubusercontent.com/40485433/94036835-04416280-fdc5-11ea-8189-feb0c1e8355f.png)

**Comment by ehremington** [comment]
I actually only have two buttons. I am using the Intuos S, and have the button 1 set to eraser and button 2 set to select rectangle. If I select something and then press button 2 while the stylus is over my selection, I immediately get a copy of that selection to move around. 

So is this actually an intentional behavior or is this a glitch that for some reason went away for @coldspark29 but still works for me?

**Comment by coldspark29** [comment]
Maybe it does have to do with the Wacom settings. They are messing with Xournal++, e.g. you have to turn off gesture support in Wacom to have gestures in Xournal++. I recently set up my Linux from scratch and could be that it’s gone since then. Will check it out later, because I might have some different settings.

**Comment by rolandlo** [comment]
It has to do with the mapping of physical stylus buttons to the eraser button, button 1 and button 2, which is done by the stylus driver.
@coldspark29 
When you build from source, you can just make the following hack in your source code: In `StylusInputHandler::setPressedState` replace `modifier3` with `modifier2` and vice versa (2 occurences each). This switches button 1 (which you have) and button 2 (which you don't have). Then you get exactly the behavior you want. In the settings you will have to switch the tools for button 1 and button 2 assigned in the stylus panel to get the previous behavior when there is no selection. Just try it out!

Maybe the same thing could be achieved via `xsetwacom`, but I don't have any experience with it.

**Comment by rolandlo** [comment]
Indeed, instead of changing the source code, you can just type
`xsetwacom --list devices` to get the names of your devices. Look for "Pen stylus". The name on the left is your DEVICENAME. Then type
```
xsetwacom set "DEVICENAME" Button 2 *3*
xsetwacom set "DEVICENAME" Button 3 *2*
```
This is Linux specific, of course.

**Comment by coldspark29** [comment]
@rolandlo I could easily set this in the Wacom settings. I have exchanged button 2 and 3, as you said and now it works again. I would still be looking forward to a configuration environment for this, but this "bug" can be closed!
