### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [xournalpp/xournalpp#224]
Could you make a new release here on GitHub?

**Comment by baimafeima** [comment]
There's now been over 400 commits since the last release. Do you have any ETA when the next version will be made available? @xournalpp

**Comment by siliconninja** [comment]
I don't think their system is planned on a release schedule. Their readme.md file says that it's still unstable software and not completed yet:
> At the moment, Xournal is very stable software while Xournal++ is not.
If you want stability, you might be more interested in the original Xournal project,
which you can find at sourceforge or, for some in-development features of Xournal,
at github.com/dmgerman/xournal.

If you want to try out the newest features built in, git clone the master branch and build it for yourself (there are instructions in the readme.md file) or install `xournalpp-git` from the AUR if you're using Arch Linux.

I don't have free time to contribute full time to this project right now, if you're wondering. I'm just trying to improve the project with the free time that I have.

**Comment by piegamesde** [comment]
@siliconninja This is not the way to get users to know the project, to try it out, to report bugs and provide feedback. Even the most unstable release is better than having to compile it yourself.

**Comment by siliconninja** [comment]
I agree. It just seems that they aren't using their release system. Their last update was in 2014. I would encourage that to be used, but I can't force the developers to push out another release, it's up to them.

@wbrenna @mputzi Do you or the official developers have any input on this? What are your plans for the future of this project?

**Comment by wbrenna** [comment]
I'm happy to continue merging pull requests and offer advice but I've had some other priorities and haven't been updating my install environment to be able to test and work on new functionality. I wouldn't say there is much of a release system! A number of years ago I built and tested on a few different platforms and uploaded a set of release packages. This can be redone but it does require someone to spend the time on it. 

When I was last active developing on the project it looked like we were on track to redo threading and complete moving to GTK3 which was my milestone for the next release. Currently I think there is still work to go until then; a new release is probably justified with some of the other changes that have been made.

**Comment by siliconninja** [comment]
Hi wbrenna, thanks for your input! I appreciate the time that you have put into the project

**Comment by baimafeima** [comment]
@wbrenna I understand it's a lot of work but in case there's any chance to get the next release out, it'll significantly increase adoption among users. I would also like to suggest it to have it included in the repositories of my operating system of choice (which in turn will increase exposure and perhaps bring in more developers). It'll be a win-win situation for all. Are you currently the only main developer?

**Comment by andreasb242** [comment]
I think a ppa or something would bring much more than a release on github. But we should add official releases soon!

**Comment by andreasb242** [comment]
PPA is working. We probably don't do releases soon, but there is an automatically build for Ubuntu and Suse, and Windows is compiling (and mostly working) so I close this ticket now.
