### ISSUE TITLE
Add a Left hand Note Taking

### ISSUE THREAD

**Issue by sagudeloo** [xournalpp/xournalpp#2240]
I write with the left hand and I'd like use an alternative like Right hand Note Taking but in the opposite side, then one solution can to be add and option in customize to move the toolbar, or an other solution is implement the same feature but in the opposite side

![image](https://user-images.githubusercontent.com/38871678/93046073-863fc780-f61e-11ea-81c8-862746c3a752.png)

**Right hand Note Taking:** This haver two columns to add tools and the double toolbar are so useful
![image](https://user-images.githubusercontent.com/38871678/93047666-9a85c380-f622-11ea-9dfa-59e5f927671a.png)

**Toolbar Right:** but this only have one
![image](https://user-images.githubusercontent.com/38871678/93047828-f9e3d380-f622-11ea-84c0-ae3febeeb951.png)

**Comment by tattsan** [comment]
View --> ToolBars --> Toolbar Right

**Comment by sagudeloo** [comment]
> View --> ToolBars --> Toolbar Right

tattsan, Before add the issue I tried that option but It's not the same toolbar, but thanks for help

**Comment by tattsan** [comment]
You can customize your toolbar: View --> ToolBars --> Customize
And you can create new layout: View --> ToolBars --> Manage

If you create new layout, you can also edit the setting by a text editor.
The configuration file is ~/.xournalpp/toolbar.ini ( if you use stable version of Xournal++).

**Comment by sagudeloo** [comment]
tattsan thanks, I gonna look that

**Comment by sagudeloo** [comment]
Yeah that work pretty well

**Comment by RealDekkia** [comment]
I just game across this issue with the same request.

In case someone wants an "it just works" option, here's my config:
I basically just mirrored the right-handed version.

Screenshot:
![image](https://github.com/user-attachments/assets/57572c37-4bbb-4949-8ca2-efae2de8e806)

```
[Left hand Note Taking by Dekkia]
toolbarBottom1=SAVE,NEW,OPEN,SEPARATOR,SAVEPDF,PRINT,SEPARATOR,CUT,COPY,PASTE,SEPARATOR,UNDO,REDO,SEPARATOR,PEN,ERASER,HIGHLIGHTER,PDF_TOOL,IMAGE,TEXT,MATH_TEX,SEPARATOR,HAND,SEPARATOR,DEFAULT_TOOL,SEPARATOR,INSERT_NEW_PAGE,DELETE_CURRENT_PAGE,SEPARATOR,GOTO_BACK,GOTO_NEXT,SEPARATOR,FULLSCREEN,SEPARATOR,AUDIO_RECORDING,AUDIO_SEEK_BACKWARDS,AUDIO_PAUSE_PLAYBACK,AUDIO_STOP_PLAYBACK,AUDIO_SEEK_FORWARDS
toolbarRight1=COLOR(0),COLOR(1),COLOR(2),COLOR(3),COLOR(4),COLOR(5),COLOR(6),COLOR(7),COLOR(8),COLOR(9),COLOR(10),COLOR_SELECT,SEPARATOR,PAIRED_PAGES,PRESENTATION_MODE,ZOOM_100,ZOOM_FIT,ZOOM_IN,ZOOM_OUT
toolbarRight2=FINE,MEDIUM,THICK,SEPARATOR,TOOL_FILL,SEPARATOR,DRAW_ELLIPSE,DRAW_RECTANGLE,DRAW_ARROW,RULER,DRAW_COORDINATE_SYSTEM,DRAW_SPLINE,SHAPE_RECOGNIZER,SEPARATOR,ROTATION_SNAPPING,GRID_SNAPPING,SEPARATOR,VERTICAL_SPACE,SEPARATOR,SELECT_REGION,SELECT_RECTANGLE,SELECT_MULTILAYER_REGION,SELECT_MULTILAYER_RECTANGLE,SELECT_OBJECT,PLAY_OBJECT
name=Left hand Note Taking
```

Just add the block to the toolbar.ini in the [Config Folder](https://xournalpp.github.io/guide/file-locations/)
