### ISSUE TITLE
Strokes sometimes appear only after the pen is lifted

### ISSUE THREAD

**Issue by xXaRoXx** [xournalpp/xournalpp#2242]
**Affects versions :**
 - OS: Linux Debian 10 with gnome desktop
 - Version of Xournal++ 1.0.18
 - Hardware: Thinkpad Yoga X1 gen1
**Describe the bug**
In xournal++ a line sometimes gets only drawn after the pen is lifted and the stroke is finished, this does not happen in Xournal (see Screenshots)

**To Reproduce**
1. Open Xournal++
2. Draw a stroke
3. there appers no stroke on the screen but sometimes a pixel gets dark where the stroke will be
4. The Pen gets lifted
5. The stroke appears after a slight delay

**Input Logs**

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5218260/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5218266/debug_input.log)

**Expected behavior**
The stroke should be visible as soon as it gets drawn.

**Screenshots of Problem**
Xournal
![xournal](https://user-images.githubusercontent.com/70605987/93077858-bec8bb00-f689-11ea-8257-7d84f8474b57.gif)
Xournal++
![xournal++](https://user-images.githubusercontent.com/70605987/93077863-bf615180-f689-11ea-9274-06ffa96b8a41.gif)

**Additional context**
This happens primalary when on battery power, but sometimes even while i charge it. Maybe this happens because xournal++ is demanding not enough resources from the cpu? 

Edit: I noticed that the live previews of all tools are impacted.

**Comment by atticus-sullivan** [comment]
Not quite sure, but I might experience the bug too quite a while ago (I'm not sure if the stroke really appeared after lifting the pen or if the strokes simply were delayed).

**Comment by xXaRoXx** [comment]
After upgrading from Debian Buster to Debian Testing I havn't experienced the bug in a week (I will update this if this changes)
