### ISSUE TITLE
View preferences reset after closing and reopening

### ISSUE THREAD

**Issue by 392781** [xournalpp/xournalpp#2245]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Mint 20
 - (Linux only) Desktop environment: Cinnamon
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
Since my Xournal++ updated recently, when I close out of it and reopen it, the background color and border color reset every single time.

**To Reproduce**
1. Open Xounral++
2. Change colors in view preferences
3. Clouse Xournal++
4. Open again.  Colors have reset.

**Expected behavior**
View preferences should remain even if you close and reopen.

**Comment by Febbe** [comment]
Identified it:

**Comment by 392781** [comment]
Will this be added in a future release?

**Comment by 392781** [comment]
@Febbe will this fix be added at a future release version?

**Comment by Febbe** [comment]
You are on the development branch, so it's released with the next nightly. The bug also only occured there. Just wait until the next PPA update☺️
