### ISSUE TITLE
Copy/Paste doesn't work on MacOS

### ISSUE THREAD

**Issue by project-pantheon** [xournalpp/xournalpp#2246]
**Affects versions :**
Mac OSX 10.14.6
Xournalpp version 1.0.18

**Describe the bug**
- As per the title copy/paste does not work on MacOS. 
- It may work sporadically once every many attempts. 
- Using the keyboard shortcuts, the menu or the buttons does not change anything

**Comment by project-pantheon** [comment]
Hello,

I was wondering if there were any update on this matter.

**Comment by pgaussier** [comment]
Hello,
I have the same problem: impossible to copy/paste inside the document or paste something from another software.
Mac OSX 10.14.6
Xournal++ version 10.0.19
