### ISSUE TITLE
Please implement hidable rectangles for fill-in-the-blank texts

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#2250]
**Is your feature request related to a problem? Please describe.**

So far I used Xournalpp just for taking notes, annotating PDFs etc. However, I am now searching for a good app to be used as a digital whiteboard for maths and physics class. I got introduced into easyteach, a proprietary software developed specifically for this purpose, but besides of being proprietary its Linux version is heavily outdated and the binary they offer is compiled against 32bit libraries, so I wasn't able to make it work so far...

Long story short, there is one nifty feature which is useful, for example, when working on a fill-in-the-blank text with the class.

**Describe the solution you'd like**

You can place white rectangles which hide what is below them and can be hidden and unhidden with the right mouse button. 

**Describe alternatives you've considered**
It is similar to the layers feature which is already present in Xournalpp. Technically, I could create such rectangles and use a new layer for each of them, then hide the layer whenever I need to remove the rectangle and make visible what is below. Obviously this disrupts the workflow and is not really practicable. 

**Additional context**
I understand that Xournalpp is a note taking and PDF annotation app and not a digital whiteboard app, but since it is the best Linux app for stylus input I know so far, it already has high potential for digital whiteboard usage and is only missing little things like the one described here.

**Comment by Photon89** [comment]
Thinking about it a bit more, the whole problem could be solved by a "temporary eraser" tool which hides/unhides an object rather than permanently deleting it.

**Comment by rolandlo** [comment]
Maybe a solution with changing transparency of the rectangle combined with a shortcut could do the job. What do you think about that idea?

**Comment by Photon89** [comment]
Sounds like a nice workaround, thanks :) But actually I couldn't make rectangles hide anything below them though I put opacity to 100%, that's another problem...

**Comment by rolandlo** [comment]
Hmm, with the latest PPA version I can. 
![grafik](https://user-images.githubusercontent.com/40485433/93523556-82b88300-f933-11ea-926e-f5051ac14b30.png)

The circle and the rectangle above use 50% opacity, the rectangle below 100% opacity. It does hide (part of) the circle.

Do you use the PPA and have you upgraded to the latest version? Or what version do you use?

**Comment by Photon89** [comment]
Sorry, my bad, I think, I was using the marker by mistake. Opacity works as expected! 

Do you have something specific in mind regarding the shortcut idea? Actually, I don't even know how to set user defined shortcuts in Xournal++...

**Comment by rolandlo** [comment]
Actually it is even simpler. Just use 100% opacity and toggle between filled and not filled with the bucket symbol from the toolbar. You can select the rectangle easily in select object mode.

**Comment by Photon89** [comment]
Ok, I tried that, it works somewhat, but 

1. the selection is not reliable (you need to hit the rectangle's border, it won't select if you click somewhere inside the rectangle), 
2. it shows the selected rectangle in blue (depends on the GTK theme, I guess) and some controls around it,
3. it requires two clicks on the opacity button since the button is in OFF state even if the selected object has opacity

So in total, three clicks, first of them needs to be precise, controls pop up in the process...

Possibly, problem 3 can be solved if I set the opacity to on as standard tool setting, but the other two problems persist and really break the workflow...

Comparing the workflow to filling in the blanks by just writing the missing words into them with the stylus, I think, I'd prefer the writing. :)

**Comment by rolandlo** [comment]
1. Maybe it would make sense that filled objects can be selected even if we only click inside the object. I am not sure, how easily that behavior could be changed (for complicated shapes), but one could make an argument that that is how it should be.
2. The selection color can be configured in the preferences view panel. The (red) delete control color cannot be configured, though.. That's hard-coded.
3. Maybe that behavior should be changed. The toolbar button should be updated if a single object gets selected.

Still you would need to select the object somehow and make one more click (or keyboard shortcut, using a plugin). It is more cumbersome than just making a right click on the rectangle. I agree with that.

You would basically need a solution, where you can just toggle the opacity (without making it selected) of an object or at least of a rectangle (without selecting it) by right clicking inside it. That would do the job, wouldn't it?

**Comment by Photon89** [comment]
>     1. Maybe it would make sense that filled objects can be selected even if we only click inside the object. I am not sure, how easily that behavior could be changed (for complicated shapes), but one could make an argument that that is how it should be.
> 
>     2. The selection color can be configured in the preferences view panel. The (red) delete control color cannot be configured, though.. That's hard-coded.
> 
>     3. Maybe that behavior should be changed. The toolbar button should be updated if a single object gets selected.

Sounds plausible!

> Still you would need to select the object somehow and make one more click (or keyboard shortcut, using a plugin). It is more cumbersome than just making a right click on the rectangle. I agree with that.

Yeah, I'm just starting teaching pupils, only had experience with university students so far, and I think that a good workflow is extremely important when you need to tame the class at the same time...

> You would basically need a solution, where you can just toggle the opacity (without making it selected) of an object or at least of a rectangle (without selecting it) by right clicking inside it. That would do the job, wouldn't it?

Yes, exactly! The rectangles could also be in an extra layer, so actions on them wouldn't interfere with other objects which exist in the document.

**Comment by Photon89** [comment]
Actually, thinking about it, I can just use an eraser and delete the rectangles permanently during the lesson. Cannot think of a situation where I'd need to hide something again, which has been already uncovered (there is the undo button for the worst case). Will try it out next week and report back!

**Comment by Photon89** [comment]
Actually, it worked quite well, only problem being the large white eraser tool square, but that's just an optical problem and also a completely different issue.
