### ISSUE TITLE
All text is just boxes

### ISSUE THREAD

**Issue by rai02** [xournalpp/xournalpp#2253]
**Affects versions :**
 - OS: Linux(Ubuntu 20.04)
 - (Linux only) Desktop environment: [gnome version 3.36.3]
 - Which version of libgtk do you use
     -  command fives error so can't find out
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - again command gives error but i got this version from snap store site. 1.0.16-4-g07cb970f5a
 - Installation method: [snap]

**Describe the bug**
All text is just boxes.

**To Reproduce**
1. just open it.

**Expected behavior**
should show words
**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/29049680/93668534-6ab73f80-faaa-11ea-802b-a11a3ce2d9b2.png)

**Additional context**
I also tried the ppa method it works fine.
but i hate this form form of text selection 
![image](https://user-images.githubusercontent.com/29049680/93668586-d39eb780-faaa-11ea-9e0c-032a4e5976c6.png)
today the earlier snap version of xournall started behaving funny. so when i reinstalled it i got these boxes

**Comment by rolandlo** [comment]
We do not have control over the Snap version. We can't change it.
As of the PPA version: The color for selected text should be the same as for selections, not simply black. I can reproduce what you see, so this is a bug.

**Comment by rolandlo** [comment]
The black background for text selections was already there before the snapping enhancements. It is not there in version 1.0.18.
