### ISSUE TITLE
Short strokes can't be erased.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#2254]
This is a regression with the commit 6e5469874290871c501f14dbbca36099e96231d8 .

**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.1.0+dev  cdebec61151f968e6fafb2074be182aff970b0af
 - Installation method: build from source

**Describe the bug**
Small strokes can't be erased.

**To Reproduce**
1. Start with Pen tool.
2. Create extremely short strokes.
3. Try to erase them with an eraser tool (in 'standard" or "delete stroke"  mode).
4. You can't erase them, if the strokes are sufficiently short.

**Comment by rolandlo** [comment]
I can't reproduce that. Can you please save your document with "extremely short strokes" and upload it here (as a zip-archive).

**Comment by tattsan** [comment]
[ShortStroks.xopp.gz](https://github.com/xournalpp/xournalpp/files/5250075/ShortStroks.xopp.gz)

Not a dotted line, but many short strokes.

**Comment by rolandlo** [comment]
Thanks a lot for the xopp-file and the bug report. I can reproduce it with this file. You can still erase the strokes with the selection tool for the time being. I will have to take a look, what is wrong here.

**Comment by tattsan** [comment]
If we draw precisely horizontal (or vertical) lines with 'Draw Line Tool', they are also **not** erasable.
But if we rotate them to be sloped, they become erasable.

[UnErasableLine.xopp.gz](https://github.com/xournalpp/xournalpp/files/5251183/UnErasableLine.xopp.gz)

**Comment by rolandlo** [comment]
Thanks for the info. I think this has to do with the way bounding boxes are computed. Shouldn't be hard to fix.

**Comment by rolandlo** [comment]
The problem was that the coordinates for some rectangle were rounded to integer. This made it possible that the rectangle would get 0 height or 0 width and would suddenly not intersect the eraser box any more. A fix is now available with #2268.

**Comment by tattsan** [comment]
I've tested the patch, and the bug has disappeared.  Thank you so much!
