### ISSUE TITLE
Which is the last Ubuntu version compatible with the last Xournalapp version?

### ISSUE THREAD

**Issue by tormec** [xournalpp/xournalpp#2257]
Since https://github.com/xournalpp/xournalpp#installing is very clear when it says that:

> For example, if you are on Ubuntu 20.04, the binary whose name contains Ubuntu-xenial is only compatible with Ubuntu 18.04.

I'm wondering if Xournal++ 1.0.18, available for download at https://github.com/xournalpp/xournalpp/releases, is only for Ubuntu 16.04, code name Xenial Xerus, or is compatible with Ubuntu 18.04, code name Bionic Beaver.

**Comment by Febbe** [comment]
We are working on our pipeline to create a release for 20.04. Currently you would've to compile it by yourself or use the PPA. But the ppa is currently on the development branch, because the stable releases are extremely behind.

**Comment by tormec** [comment]
I thought there was a mismatch between the versions of xournalapp and ubuntu but evidently Xournal++ 1.0.18 is still not (fully) compatible with Ubuntu 18.04

> because the stable releases are extremely behind.
