### ISSUE TITLE
I've removed xournalpp pgp key by mistake, where is it's source so I can add it back again?

### ISSUE THREAD

**Issue by tifDev** [xournalpp/xournalpp#2258]
Hello,

By mistake I ran `sudo apt-key del 354C702D` and it removed my xournal++ pgp key. **How can I add it back?**

Now when I run `apt-update` I see this:

```
r:2 http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6AEB0CDA354C702D

```

I need the source key to place here:

`wget -qO - https://site.com/xournal.key | sudo apt-key add -`

Just FYI, I've installed the program this way:

```
sudo add-apt-repository ppa:andreasbutti/xournalpp-master
sudo apt update
sudo apt install xournalpp
```

Thanks

**Comment by Technius** [comment]
Can you try removing the PPA and then adding it again? You can remove it with:
```
sudo add-apt-repository --remove ppa:andreasbutti/xournalpp-master
sudo apt update
```

**Comment by tifDev** [comment]
Sorry I had solved it already this way:
Installed it in a VM that I have and then copy the pgp key to my other machine.

Thanks for your time and your answer. Keep the good work bro :)
