### ISSUE TITLE
Won't compile with poppler-glib 0.58+!

### ISSUE THREAD

**Issue by macxcool** [xournalpp/xournalpp#226]
With any poppler 0.58 or higher, compile throws a series of pdf/poppler errors and then exits with:
`
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:4215: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfObjectWriter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
Downgrading to poppler 0.57 fixes the problem. I'm running Archlinux 64-bit and am one of the maintainers of the Arch xournalpp-git package.

**Comment by peetCreative** [comment]
Hi,
I'm running arch and run in a similar problem with poppler.
I used `sudo pacman -U /var/cache/pacman/pkg/poppler-0.57.0-1-x86_64.pkg.tar.xz`
However it still is not compiling. 
`make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:4191: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by macxcool** [comment]
You may have to downgrade poppler-glib too.

**Comment by jaykijay** [comment]
This is fixed from @peetCreative with #227 .

**Comment by macxcool** [comment]
It is, indeed. Awesome!
