### ISSUE TITLE
The program crashes after changing an object's color followed by an undo command.

### ISSUE THREAD

**Issue by diegovnoble** [xournalpp/xournalpp#2263]
**Affects versions :**
 - OS: Xubuntu 20.04.01
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

Xournal++ closes unexpectedly after an undo operation preceded by a selection.

1. Draw something.
2. Select what you have drawn.
3. Change the color of what was previously selected.
4. Press Ctrl+z.

**Expected behavior**
The undo operation runs without Xournal++ crashing.

**Screenshots of Problem**
![Peek 2020-09-21 15-24](https://user-images.githubusercontent.com/731763/93806160-213c3100-fc1f-11ea-9af5-4c7bf5de8d81.gif)

**Comment by Technius** [comment]
Can you upload your latest crash log? You can find it in `~/.config/com.github.xournalpp.xournalpp/errorlogs/`.

**Comment by diegovnoble** [comment]
Hi!
Unfortunatelly there was no `errorlogs` inside the `~/.config/com.github.xournalpp.xournalpp/errorlogs/` folder.
![Screenshot_2020-09-21_15-38-00](https://user-images.githubusercontent.com/731763/93807137-965c3600-fc20-11ea-8ddf-a89caf7bb482.png)

**Comment by rolandlo** [comment]
I think I found the bug. One letter (e) fixes the bug. Line 12 in `ColorUndoAction.cpp`

```c++
ColorUndoActionEntry(Element* e, Color oldColor, Color newColor): e(), oldColor(oldColor), newColor(newColor) {}
```
should be

```c++
ColorUndoActionEntry(Element* e, Color oldColor, Color newColor): e(e), oldColor(oldColor), newColor(newColor) {}
```
The bug was introduced in ddbb7c6b12b4bca61be65281219767b52e67e0ae

**Comment by diegovnoble** [comment]
Thanks!
