### ISSUE TITLE
Default location for image import (?)

### ISSUE THREAD

**Issue by The9Cat** [xournalpp/xournalpp#2266]
When importing an image, I now get "Folder contents cannot be displayed" and I have to walk down the tree from my home directory to find the desired image.  This occurs even if I launch xournal++ from the desired working directory.

Previous behavior was (if I recall correctly) to open the working directory.

It would also be nice if one could specify a default image working directory.

**Comment by Technius** [comment]
Can you provide the following information?
 - OS: [e.g. Linux (which distro), Mac, Windows]
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Comment by The9Cat** [comment]
I'm sorry, I should have posted this detail yesterday . . . 

- OS: Linux Ubuntu 20.04
- Gnome-X11 desktop
- xournalpp version: 1.1.0-dev
- libgtk version: 3.24.20
- PPA: deb http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu focal main

**Comment by The9Cat** [comment]
I installed the snap package which is version 1.0.16 and this one _does_ correctly look for images in the working directory.

**Comment by Technius** [comment]
FYI, you may want to try the stable PPA that was created by a community contributor a few days ago: https://github.com/xournalpp/xournalpp/issues/1013#issuecomment-692656810

I was able to reproduce this bug with the AppImage on a Fedora 32 docker image.
