### ISSUE TITLE
Xournal++ issue on ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by Giorgio235** [xournalpp/xournalpp#2279]
-OS: Ubuntu 20.04.1 LTS with GNOME 3.36.3
-libgtk 3.24.20
-Xournal++ 1.1.0+dev, nogitfound
-installed with apt

**Describe the bug**
When using the stroke recognizer with the pen and while writing with a graphic tablet, when the lines are recognized as being perfectly vertical or perfectly horizontal the stroke cannot be erased other than with the whiteout option.

**To Reproduce**
1.open xournal++ and connect a graphic tablet (wacom intuos s in my case)
2. enable the stroke recognizer
3. make  vertical and  horizontal lines and try to delete with eraser (not the whiteout option)

**Expected behavior**
That the strokes would be erased

**Comment by 392781** [comment]
I've had a similar issue where just drawing lines using my tablet sometimes creates strokes that are not recognized by eraser.

**Comment by tattsan** [comment]
This bug is perhaps same as #2254 , and will be fixed by the PR #2268 .

**Comment by rolandlo** [comment]
PR #2268 is merged now, so this should be fixed with the next update.
