### ISSUE TITLE
Compilation Instructions for debian-based distros?

### ISSUE THREAD

**Issue by Hoeze** [xournalpp/xournalpp#228]
Are there any build instructions for debian-based distros?
What are the required Debian/Ubuntu dev packages?

**Comment by wbrenna** [comment]
There are (probably obsolete) build instructions on the Github wiki: https://github.com/xournalpp/xournalpp/wiki. Definitely feel free to add a new entry that's up to date!

**Comment by Hoeze** [comment]
I just tried to compile it, but it stops with the following error:
```
CMakeFiles/xournal-thumbnailer.dir/__/util/XojPreviewExtractor.cpp.o: In function `XojPreviewExtractor::readFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
XojPreviewExtractor.cpp:(.text+0x440): undefined reference to `Glib::Base64::decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```

**Comment by Hoeze** [comment]
I got the necessary packages together now (on Ubuntu bionic), but I got some other compilation errors now.
However, these are code errors, so I am going to open a new issue for them.

If I finally get a working build I will submit compilation instructions for Ubuntu :)
