### ISSUE TITLE
Problem with Files names containing accents in Windows 10

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2280]
OS : Windows 10
Version of Xournalpp : xournalpp-1.1.0+dev-nightly.20200924-windows.exe

Problem :
Under windows 10, when I double-click on a file whose name contains accents the pages are blank.
Under Windows 10, when I open it from menu "File->Open", I have the message "Could not open file"

When I rename the file without accents, there is no problem.

[Corrige.zip](https://github.com/xournalpp/xournalpp/files/5286274/Corrige.zip)

**Comment by Febbe** [comment]
It might be, that I fixed that unintentionally yesterday with this commit: https://github.com/xournalpp/xournalpp/commit/2a3581c5abde46464ce3f95c111225744d300abf
The PR: https://github.com/xournalpp/xournalpp/pull/2276
Can you test it? You could also just wait for the new nightly

**Comment by MichelReims** [comment]
I have compiled the last version. The filename "Corrigé.xopp" becomes "corrigÃ©.xopp"

**Comment by Febbe** [comment]
Do you know your encoding, I'll take a closer look into this, but I don't have a Windows OS till Wednesday

**Comment by MichelReims** [comment]
I don't know where I find it.
I am in France (western europe)

**Comment by Febbe** [comment]
> I don't know where I find it.
> I am in France (western europe)

Ok I am also located in western Europe, I think I can reproduce and fix this quite fast as soon I have time. Thank you for your report. If you want to acquire some experience in c++ you could also try to fix it, this is very easy to fix.

**Comment by MichelReims** [comment]
in previous versions of xournalpp,  I didn't have this problem when I compiled

**Comment by Febbe** [comment]
We made a huge refactoring regarding paths. I think that's the reason for the problems.
Eevery progress can always have (temporary) regressions and there is mostly no way to prevent that completely :/ .

**Comment by MichelReims** [comment]
I understand

**Comment by MichelReims** [comment]
Sorry. I have no experience in c++

**Comment by MichelReims** [comment]
I think there are still issues with annotated PDF files that contain accents
