### ISSUE TITLE
Resizing of 'the selection just after pasted' behaves oddly

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#2281]
This is a regression with the commit 6e5469874290871c501f14dbbca36099e96231d8 .

**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: master (after 6e5469874290871c501f14dbbca36099e96231d8 )
 - Installation method: built from source

**Describe the bug**
When a copied object is pasted, it appears as a selected object.
But if you click the corner or the edge to resize it, the object
will jump to another place or disappear.

**To Reproduce**
1. Create a stroke. Call the object AAA.
2. Select AAA and copy it to the clipboard.
3. Paste the object in the clipboard. Call the appeared object BBB.
4. BBB appears as a selected object. Click one of the corner of it with a pen.

**Additional context**
1. If you click the corner with a mouse, this bug does't appears.

2. If you use LaTeX tool, the object generated by LaTeX  also
appears as a selected object. This object also gets this bug.

3. If you apply the commit 6f29f1cc85a576461d927f1ce347da4293179d36 ,
this bug seems to be avoided if the paste is the first time.
But if you try another paste succesively, it gets this bug again.

**Comment by rolandlo** [comment]
Thanks for reporting the bug. Seems that is something I simply forgot to consider. Shouldn't be hard to fix, though.

**Comment by rolandlo** [comment]
@tattsan Can you please check if the bug is fixed in PR #2286?

**Comment by tattsan** [comment]
I've tested the patch. It works fine! 

The feature 'preserve line width when resizing' of commit 6e5469874290871c501f14dbbca36099e96231d8  is exactly what I've been waiting for.  Thank you so much!

**Comment by rolandlo** [comment]
Thanks for testing. Your precise bug reports and testing are of great value.
