### ISSUE TITLE
copy paste from pdf in xournal++

### ISSUE THREAD

**Issue by ggarr31** [xournalpp/xournalpp#2287]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**

I would like to copy and paste text from a pdf or text file. I can do this in Xournal, but when I try in Xournal++ it does not allow to paste. Hitting Ctrl+V does not work, and pressing Edit->Paste does not work either

**Comment by rolandlo** [comment]
I cannot reproduce this on Windows 10, version 1.0.18 (official release). Pasting appears to work fine. Anyone else experiencing the same problem?
On Linux the pasted text appears in White color and I have to change the font color to make the text visible.

**Comment by Febbe** [comment]
I tested this on Windows for the newest master and it worked for text. 
But I also got an error message: 
```
(com.github.xournalpp.xournalpp:1776): Gdk-WARNING **: 15:06:31.589: ../gtk+-3.24.22/gdk/win32/gdkdisplay-win32.c:561: GetClipboardOwner failed with code 203: Das System konnte die eingegebene Umgebungsoption nicht finden.

(com.github.xournalpp.xournalpp:1776): Gdk-WARNING **: 15:06:31.997: ../gtk+-3.24.22/gdk/win32/gdkdisplay-win32.c:561: GetClipboardOwner failed with code 203: Das System konnte die eingegebene Umgebungsoption nicht finden.
```

I believe, this could be resolved, when we address the other clipboard issues.

**Comment by ggarr31** [comment]
Thanks for your message. Today I tried again and could copy/paste from a pdf with no problem. The size of the copied text is a bit too large and one has to reduce the box, but otherwise it seems to work fine.
