### ISSUE TITLE
I come back to the top of the document when I add a new page at the end of a document

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2289]
I work under windows 10 with the nightly-automated release of the 28 september.
Sometimes, when I add a new page at the end of a document, I come back to the top of the document.

**Comment by rolandlo** [comment]
Thanks for the bug report. Please provide an update if you can clearly see the pattern of when the bug appears. If it is reproducible it can get fixed easier. I think it is very important to fix it, since it is connected with other problems like bug #2211.

**Comment by Rmano** [comment]
It happens all the time to me too. In the following video:

1. open `xournalpp`
2. write something, add a new page
3. scroll to the new page, write something.
4. new page, repeat
5. after (in this case 3) pages `xournapp` jumps back to the first page when adding a new one


![test](https://user-images.githubusercontent.com/6414907/94561993-0c861b80-0265-11eb-81b3-44c4f1e51674.gif)


I think it had something to do with the fit-to-page (which works strangely, as well as presentation mode --- shouldn't just show one page at a time in presentation mode?

**Comment by Rmano** [comment]
This seems the same: https://github.com/xournalpp/xournalpp/issues/1926

**Comment by rolandlo** [comment]
@Rmano Could you please test PR  #2312. It seems to almost solve the problem.

**Comment by Rmano** [comment]
Even if not perfect, the current state of PR #2312 solves this issue. I commented in the PR with more details.

**Comment by rolandlo** [comment]
Now PR #2346 should do it perfectly. PR #2312 was closed in favor of PR #2346
