### ISSUE TITLE
Crash when using 'Export as...' with File Type by extension

### ISSUE THREAD

**Issue by max-te** [xournalpp/xournalpp#229]
https://github.com/xournalpp/xournalpp/blob/62312496092f5f717246f87d2ca85a739f609adb/src/gui/dialog/ExportDialog.cpp#L389
Program crashes here on the first iteration, because `currentExtension` is null.
(It is set to null in https://github.com/xournalpp/xournalpp/blob/62312496092f5f717246f87d2ca85a739f609adb/src/gui/dialog/ExportDialog.cpp#L55)

Possible fixes are either checking for null, or not using null entries.

**Comment by andreasb242** [comment]
Should be solved
