### ISSUE TITLE
Crash on changing directory during "Save As"

### ISSUE THREAD

**Issue by Krzmbrzl** [xournalpp/xournalpp#2292]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: X11 (KDE Plasma)
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
Using File > Save As a popup appears that lets me choose a directory to save into. As soon as I change the directory in that FileBrowser, Xournalpp crashes. This is the terminal output when this happens:
```
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card

** (com.github.xournalpp.xournalpp:6438): WARNING **: 11:14:45.975: Error calculating zoom value

(com.github.xournalpp.xournalpp:6438): Gtk-WARNING **: 11:14:45.976: Theme parsing error: <data>:1:22: Junk at end of value for font-family
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)

** (com.github.xournalpp.xournalpp:6438): WARNING **: 11:14:51.818: [Crash Handler] Crashed with signal 6

** (com.github.xournalpp.xournalpp:6438): WARNING **: 11:14:51.820: [Crash Handler] Wrote crash log to: /home/user/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200930-111451.log

** (com.github.xournalpp.xournalpp:6438): WARNING **: 11:14:51.928: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:6438): WARNING **: 11:14:52.081: Successfully saved document to "/home/user/.config/com.github.xournalpp.xournalpp/emergencysave.xopp"
```

Not changing the directory and simply specifying a name and then hitting `Save` works as expected.

**To Reproduce**
1. Open Xournalpp
2. Choose `Save As`
3. Change the directory in the pop-up file-chooser

**Expected behavior**
No crash

**Additional context**
I want to emphasize that this also happens with an empty document, so it does not seem to be related to the document's content.

**Comment by rolandlo** [comment]
I cannot reproduce this on Ubuntu 20.04.

**Comment by Krzmbrzl** [comment]
> Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)

I assume there is a relation to the `breeze` icon pack. The main question that remains is: Is this problem even related to Xournalpp or might the FileBrowser it uses be broken (or the breeze theme) :thinking:

**Comment by rolandlo** [comment]
Looks like a duplicate of #2180. Try the solution provided there: 

> The problem is gone after installing the package adwaita-icon-theme-full

**Comment by Krzmbrzl** [comment]
The problem is indeed fixed this way. Thank you :+1:

**Comment by sfncrp** [comment]
Hello! I had the same problem, I spent a lot of time trying to figure out this problem, almost giving up to use another application.
You could maybe add the package adwait-icon-theme-full as a dependency?
