### ISSUE TITLE
Feature request: allow copy and paste between documents

### ISSUE THREAD

**Issue by MiHevoMo** [xournalpp/xournalpp#2294]
In recent months, I've learned to love xournal++. I'm using version 1.1.0+dev on Ubuntu 18.04.

But one thing has bothered me more than just once.
It appears, that presently xournal++ is not able to handle several open files at once. 
This means it is not possible to do Ctrl-C Ctrl-V between files (or at least I  haven't found a way to do this). 
This again has some profound effects on the workflow: it means it is not possible to fork something you've drawn in one document to modify it in another. Exporting to PDF is no option, because the result is no longer modifiable.
Plain copying of files becomes awkward as soon as notes span several pages and you only want to take out a bit to insert it into another file.

So my request is: please implement multi-file-handling with a common clipboard. 
Thanks a lot.

**Comment by rolandlo** [comment]
You can open two instances of Xournal++ at the same time and then simply "copy" in one instance and "paste" in the other instance. If it doesn't work (when two instances of Xournal++ are open), then something is wrong.

**Comment by MiHevoMo** [comment]
This does indeed work - when I start the second instance from command
line. Funny enough, starting it through the Gnome "Activities" menu
only brings up the already running instance, so I assumed this is
xournal++ behaviour, while its apparantly a Gnome "feature".
Thanks anyway, and a good night.

Am Mittwoch, den 30.09.2020, 08:12 -0700 schrieb Roland Lötscher:

**Comment by rolandlo** [comment]
In Gnome "Activities" the trick is to use right click and choose "new window"

**Comment by Technius** [comment]
Related to #1971.

**Comment by tobiasBora** [comment]
Note that I was experiencing issues with copy paste between documents. The reason was that I was copy/pasting between different xournal++ versions (one nightly and one provided by my system), so I guess different versions might add incompatibility, opening instead nightly twice fixes the issue.
