### ISSUE TITLE
PDF reference

### ISSUE THREAD

**Issue by Alfystar** [xournalpp/xournalpp#2298]
**Describe the bug**
For now, in linux, the PDF annotation features use the FULL path to link the resource , this is what i undestand with my reverse engineering.
This make many problems when only the PDF change location, and this is normal, but also CREATE problem if the structure in the file system are mantein, but is change the path of the directory that own they.

**To Reproduce**
1. Annotate pdf in sub-current folder and save 1 level up
2. move the own directory in another point of file system
3. reopen the xournall file

**Expected behavior**
The file shuld be show correctly

**Additional context**
When the sincronize are lost, please text in the infoBox, the precedent path (in particular the name), to make more easy reconnect the file if only the pdf was change in position

Maybe you can clone the pdf in this file and remove the necessity of soncronization, if the user want

**Comment by rolandlo** [comment]
This is no bug. You can "attach" mode as described in #2106 and then move the .xopp file along with the (attached) .pdf file into another folder without any problems.
