### ISSUE TITLE
Clicking on "default tool" (from the menu or via toolbar) does not change the tool at all

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2303]
Under windows 10 

I created a shortcut with the "Shift +Ctrl+ D" keys for the "Default Tool" menu command. When I use it, I see that the "Default Tool" command is correctly selected, but as soon as I move the stylus or the mouse, it is the eraser that appears instead of the stylus (which I programmed in "Default Tool"). 
When I use the shortcut and move the stylus, it's switch automatically from pen to eraser.

 Clicking on "default tool" (from the menu or via toolbar) does not change the tool at all.
This appareas since the last commit.

Maybe @idotobi will find a quick fix for it

**Comment by idotobi** [comment]
@MichelReims : Sorry to hear that I caused a regression. I think I still don't fully understand the bug.
Could you write down the Reproduction Steps, Observed Behaviour and Expeected Behaviour? A short screen capture would be nice if posible.

One additional question: How did you set the shortcut for the default tool? Is there a way to do this in xournalpp? If yes where would I set this?

**Comment by MichelReims** [comment]
This problem with "default Tool" has appeared since the pull request #2004. The problem is linked to the operation of the buttons.

Shortcut for default tool : Under Windows, unzip this zip-file in subdirectory "plugins" of  xournal++ (this create a folder "Raccourcis" in "Plugins" ; this folder contains 2 files). Then "SHIFT+CTRL+D" becomes a shortcut for "Default Tool"
[Raccourcis.zip](https://github.com/xournalpp/xournalpp/files/5382943/Raccourcis.zip)

**Comment by idotobi** [comment]
@MichelReims : I think I fixed your issue. If you have time it would be great if you could checkout the branch of my PR #2339  and verify if it fixes your problem.

**Comment by MichelReims** [comment]
@idotobi I just compiled your PR. It works. This problem is resolved. Thank you very much
