### ISSUE TITLE
Unable to compile, error in popplerdirect

### ISSUE THREAD

**Issue by airbete** [xournalpp/xournalpp#231]
I get the following errors when compiling:

/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:287:48: error: no matching function for call to ‘Dict::lookup(const char [7])’
/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:474:43: error: no matching function for call to ‘Page::getContents()’
/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:506:48: error: no matching function for call to ‘Object::arrayGet(int&)’
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:4191: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I'm on Fedora 26.
> rpm -qa | grep poppler | sort
poppler-0.52.0-5.fc26.x86_64
poppler-data-0.4.7-7.fc26.noarch
poppler-devel-0.52.0-5.fc26.x86_64
poppler-glib-0.52.0-5.fc26.x86_64
poppler-glib-devel-0.52.0-5.fc26.x86_64
poppler-qt5-0.52.0-5.fc26.x86_64
poppler-qt5-devel-0.52.0-5.fc26.x86_64
poppler-utils-0.52.0-5.fc26.x86_64

AB.

**Comment by Hoeze** [comment]
I got the same errors on Ubuntu 18.04 bionic.

**Comment by Hoeze** [comment]
You have to `git checkout c7fa9677a5a857b89e80ef9149741dce7a628f75`:
The latest two commits add compatibility to `poppler >= 0.58`. Since this breaks compatibility with `poppler < 0.58` you have to revert these changes.

**Comment by airbete** [comment]
Reverting to c7fa9677a5a857b89e80ef9149741dce7a628f75 works nicely. Thanks.
