### ISSUE TITLE
Add hacktoberfest repo tag

### ISSUE THREAD

**Issue by hashworks** [xournalpp/xournalpp#2313]
Hacktoberfest now [requries specific tags](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for valid PRs:
```
PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

I saw @Technius added some `hacktoberfest` labels to issues. For PRs to actually count one would need to label individual PRs as `hacktoberfest-accepted` or add the repository topic `hacktoberfest`.

**Comment by Technius** [comment]
Done, thanks for the heads-up.

Going to keep this open until November as a reminder to remove the tag.
