### ISSUE TITLE
Closing the Overwrite File prompt window when saving overwrites the file.

### ISSUE THREAD

**Issue by Eemkeks** [xournalpp/xournalpp#2315]
**Affects versions :**
 - Linux (Manjaro)
 - KDE 5
 - GTK3 version: 1:3.24.23-1
 - Version of Xournal++: 1.0.18 
 - Installation method: AUR

**Description**
When saving a document, clicking on a pre-existing file brings up an overwrite prompt window. If the x button is clicked instead of clicking either option in the window, the file is overwritten by default.

**Steps to reproduce the behavior:**
1. Click the save button with an unsaved document
2. Select a pre-existing file name.
3. When the pop-up window asks if you want to overwrite the existing file, close the window. 

**Expected behavior**
Closing the overwrite prompt takes the user back to the file name selection window.

**Comment by Technius** [comment]
This has already been fixed in #1989.
