### ISSUE TITLE
Pen rendering on Xournal and Xournal++

### ISSUE THREAD

**Issue by fernent** [xournalpp/xournalpp#2326]
I am comparing Xournal and Xournal++ on Fedora 32/33 using a Wacom Intuos tablet.

While I need features present in Xournal++ (such as Tex insertion, image insertion, ...) I don't really like the rendering of my text on Xournal++ compared to Xournal (see the two pictures below).

I don't think that I should modify the intrinsic configuration of my wacom tablet using _xsetwacom_ command ... but I believe I should configure Xournal++ correctly.
Maybe I should modify some options for the pen in Xournal++ such as "smoothing" or "aliasing" but I didn't find such options.

What are your ideas to improve pen rendering on Xournal++ ? Is it related to gtk ?

![Screenshot_20201020_112439](https://user-images.githubusercontent.com/66013123/96606188-4a6fe000-12f7-11eb-9342-c1fcca3b69db.png)
![Screenshot_20201020_112540](https://user-images.githubusercontent.com/66013123/96606192-4b087680-12f7-11eb-9518-3c09fb94e201.png)

**Comment by rolandlo** [comment]
I understand that you don't like this, but that's not what you should get. With my Wacom Intuos pro on Ubuntu 20.04 I don't see any difference between things I wrote on Xournal or on Xournal++ (and neither with my Lenovo convertible). Most likely it's not the rendering, but the input points that are reported to Xournal++. 
Are you sure that you had the same page zoom when writing these lines in Xournal and in Xournal++? You may get more jittering if you have a small zoom. 
Try writing something in Xournal, save it as a .xoj file and open it in Xournal++. Then you can see if the rendering is the same. Just compare it side by side with the same zoom.

**Comment by fernent** [comment]
_"Are you sure that you had the same page zoom when writing these lines in Xournal and in Xournal++? You may get more jittering if you have a small zoom."_
Yes I had the same zoom for both pictures. I can clearly see this jittering effect when the whole page is displayed. It also does not depend on the size of my text.

_"Try writing something in Xournal, save it as a .xoj file and open it in Xournal++. Then you can see if the rendering is the same. Just compare it side by side with the same zoom."_
Indeed the rendering is the same.

_"I understand that you don't like this, but that's not what you should get. With my Wacom Intuos pro on Ubuntu 20.04 I don't see any difference between things I wrote on Xournal or on Xournal++ (and neither with my Lenovo convertible). Most likely it's not the rendering, but the input points that are reported to Xournal++."_
Hum then the problem should be elsewhere. I will try on an other distribution.

**Comment by fernent** [comment]
I think I found a connection with the "xinput" feature.
In Xournal, when xinput is disabled, I recover the poor rendering of Xournal++. Is there away to enable xinput in Xournal++ ?

**Comment by LittleHuba** [comment]
There is but it requires major work on your part. You would have to write a backend for Xournal++ that parses xinput events for usage in our own input system. The input system of Xournal++ was decoupled from GTK+ for exactly this scenario some time ago. Never got to the point where I had time to write such backends though.

I can give you some pointers if you want to try your hand but I don't really have the time to do more.

**Comment by fernent** [comment]
Thanks for your help
