### ISSUE TITLE
Printer not shown

### ISSUE THREAD

**Issue by minimonk82** [xournalpp/xournalpp#2329]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 18.04.5 LTS 64bit 
 - (Linux only) Desktop environment: ubuntu default
 - Which version of libgtk do you use
     - i don't know (about page has no information about libgtk)
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.16
 - Installation method: PPA

**Describe the bug**
Xournal++ can't list printers

**To Reproduce**
1. execute xournal++
2. press ctrl-p
3. show printer list

**Expected behavior**
show list of installed printer

**Screenshots of Problem**
![스크린샷, 2020-10-21 16-40-30](https://user-images.githubusercontent.com/65176520/96689541-7bb2e380-13bd-11eb-9972-f69f555ad32d.png)
![스크린샷, 2020-10-21 16-48-22](https://user-images.githubusercontent.com/65176520/96689556-80779780-13bd-11eb-904c-4fb8c3b77230.png)

xournal's print dialog
![스크린샷, 2020-10-21 16-40-48](https://user-images.githubusercontent.com/65176520/96689577-8b322c80-13bd-11eb-90b3-42db89bce1f4.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
I'm a bit confused about the Xournal++ version you have: 1.0.16 git commit 07cb970f must be the snap package (installed via software center pressumably). Try running the PPA version (1.1.0+dev) and it should work.

**Comment by minimonk82** [comment]
> I'm a bit confused about the Xournal++ version you have: 1.0.16 git commit [07cb970](https://github.com/xournalpp/xournalpp/commit/07cb970f5ae5ea948839af87502a0440c2798153) must be the snap package (installed via software center pressumably). Try running the PPA version (1.1.0+dev) and it should work.

I found that how install xournal++ in my blog.
I installed it using ubuntu app, not PPA.
I'll install xournal++ where PPA repo. Thanks for reply

**Comment by eikelang** [comment]
I checked the snap and noticed that it does not declare/depend on the cups-control interface. With any luck, fixing the snap to depend on that interface and having it request permissions for it should solve the issue.
