### ISSUE TITLE
Button press on Wacom One stylus crashes app

### ISSUE THREAD

**Issue by obdacz** [xournalpp/xournalpp#2331]
**Affects versions :**
 - OS: Linux Ubuntu 20.04.1
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA (andreasbutti/xournalpp-master)

Button press on the stylus crashes xournalpp.

**To Reproduce**
1. open xournalpp
2. touch stylus to tablet and press the (only) button

**Expected behavior**
No crash. Eraser tool is used, as configured.

**Screenshots of Problem**

**Additional context**
I'm using the new input system. Relevant settings and the crash log are below:

![wacom1](https://user-images.githubusercontent.com/47979603/96719496-be6ac080-13a9-11eb-8ae3-28971c894663.png)

![wacom2](https://user-images.githubusercontent.com/47979603/96719532-c9255580-13a9-11eb-84e4-35d861e4b273.png)

[errorlog.20201021-142524.log](https://github.com/xournalpp/xournalpp/files/5415824/errorlog.20201021-142524.log)

**Comment by v--** [comment]
This issue is no longer present for me in the latest commit (97303a1 at the time of writing this comment). Can somebody else verify if the problem persists?

**Comment by bhennion** [comment]
Closing this as it seems to have been fixed for a while. @obdacz do not hesitate to reopen if you're still experiencing the crash.
