### ISSUE TITLE
Latex makes crash the App

### ISSUE THREAD

**Issue by ErgastiAlex** [xournalpp/xournalpp#2332]
**Affects versions :**
 - OS: Windows
 - libgtk: 3.24.23
 - Xournal: 1.1.0+ dev
 - Installation method: Official Release, nigthly Build.

 **Description**
When open the latex window if i press "Cancel" before the image of the example x^2 loads the app'll crash

**To Reproduce**
1- Open Math TEX
2- Press immediately cancel or the X symbols

**Expected behavior**
Simply close the windows without make the app crashes.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/20249175/96725859-ab5bee80-13b1-11eb-8fb9-9c0292474e24.png)
Press now the X button or "Annulla"

**Additional context**
I've follow the instruction to add the default_template.tex, i also have MikTex installed.

**Comment by rolandlo** [comment]
Instead of pressing cancel or the X symbol you can also press the ESC key to get this crash.

**Comment by Technius** [comment]
Simplest but dirtiest fix is to disable the close button in the dialog.

The proper fix would be to cancel the render finish callback (the pdflatex process callback) if the dialog is closed.
