### ISSUE TITLE
Hide layer feature request

### ISSUE THREAD

**Issue by voland66** [xournalpp/xournalpp#2333]
**Is your feature request related to a problem? Please describe.**
I would like to be able to hide a layer. For example, I would like an ability to have a diagram in a layer 1, a set of annotations in the layer 2, and a different set of annotations in the layer 3. I can go back to layer 2 if I only want to show annotations from that layer. But sometimes I would also like to show annotations from the layer 3 without showing annotations in the layer 2. And I do not see a way to do it at the moment.

**Describe the solution you'd like**
I would like to be able to select hidden layer(s) which are not necessarily sequential and not necessarily at the end of the layer list.

I would like to have a menu item (and a shortcut) which would allow me to hide the current layer. A more extensive option would be a dialogue box allowing to select a set of hidden/shown layers on a page.

**Describe alternatives you've considered**

**Additional context**

**Comment by rolandlo** [comment]
That's already possible. Either use the layer preview in the sidebar (where you can hide/unhide any layer via checkbox) 

![grafik](https://user-images.githubusercontent.com/40485433/96784949-699d6900-13ee-11eb-9952-1dbe8d285bca.png)

or use the dropdown menu from the toolbar for the same purpose.

![grafik](https://user-images.githubusercontent.com/40485433/96785200-c567f200-13ee-11eb-987d-bd6b7f80dcf0.png)
