### ISSUE TITLE
Wacom CTH-480 Pen Eraser Detection doesn't work

### ISSUE THREAD

**Issue by kir12** [xournalpp/xournalpp#2334]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: KDE Plasma on X11
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.19
 - Installation method: [Official Arch Linux Package](https://www.archlinux.org/packages/community/x86_64/xournalpp/) (i.e.`pacman`)

**Describe the bug**
The eraser end of my Wacom CTH-480 pen still registers according to xjournalpp as the pentip end.

**To Reproduce**
1. Start up a new instance of xournalpp
2. Add markings to paper using pen
3. Change the pen orientation so the eraser and is facing the tablet
4. xournalpp still interprets the eraser end as a pen

**Expected behavior**
When xournalpp starts registering the eraser end of my pen, it should automatically select the eraser. 

**Additional context**
I am running KDE Plasma Version 5.20.1, KDE Frameworks Version 5.75, and Qt Version 5.15.1.

**Comment by rojizo** [comment]
Same here! Installed from the unofficial ppa (apandada1) on a POP_OS system on Gnome

**Comment by rolandlo** [comment]
Just to be sure: You say version 1.0.18 worked fine for the pentip end eraser and version 1.0.19 does not?

Please post images of your settings in the input system, mouse and stylus panels of the preferences. Maybe something is wrong there.

**Comment by rojizo** [comment]
Dear @rolandlo... Yes, it was working perfectly in previous version. I did not change a thing in the settings... I'm did not open the setting until today to send you those pictures... nothing special there

**mouse**
![mouse](https://user-images.githubusercontent.com/11900271/97037540-b35e8e80-1569-11eb-9f67-48fd7c239bd3.png)

**stylus**
![stylus](https://user-images.githubusercontent.com/11900271/97037549-b5c0e880-1569-11eb-944a-fc3eba4f6516.png)

**wacom**
![wacom](https://user-images.githubusercontent.com/11900271/97037556-b78aac00-1569-11eb-9fd2-2b4482c14891.png)

Testing the tablet in the settings (with the button on top), the eraser works correctly

**Comment by rolandlo** [comment]
I meant Xournals++'s preferences (menu edit->preferences), not the system preferences.

**Comment by rojizo** [comment]
Haha... I'm an idiot! There is the something I can change to recover the previous... I not even take a look there... sorry for the inconveniences!!!

![wacom](https://user-images.githubusercontent.com/11900271/97043645-130d6780-1573-11eb-8969-e10c0d6dae9b.png)

It was in "Don't change"

**Comment by rolandlo** [comment]
No problem. @kir12 does that solve the problem for you as well?

**Comment by kir12** [comment]
Wow I can't believe I missed something like that -- yep that fixed things for me too!
