### ISSUE TITLE
Huion tablet is not recognized as pen input when using Wacom drivers

### ISSUE THREAD

**Issue by profran** [xournalpp/xournalpp#2340]
**Affects versions :**
 - OS: Arch Linux x86_64
 - Version of Xournal++: 1.0.18, 535d261d

**Describe the bug**
My tablet is recognized as mouse input when tricking xorg into thinking my Huion h950p is a Wacom tablet (because I want to be able to use the xsetwacom command). The on-pen buttons also don't work. It's probably something with Xournal, because Krita recognizes the tablet perfectly.

**To Reproduce**
1. Install digimend kernel drivers for h950p support.
2. Map the tablet to a Wacom one: https://wiki.archlinux.org/index.php/wacom_tablet#Non-Wacom_tablets
3. Pen won't draw

**Input Logs**
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5433949/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5433950/debug_gdk_input.log)

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d stylus                    	id=10	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d Pad pad                   	id=11	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d Touch Strip pad           	id=12	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d Dial pad                  	id=13	[slave  pointer  (2)]
⎜   ↳ Logitech USB Trackball                  	id=14	[slave  pointer  (2)]
⎜   ↳ SEMITEK USB-HID Gaming Keyboard Mouse   	id=20	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=22	[slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                   	id=23	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ C-Media USB Headphone Set               	id=15	[slave  keyboard (3)]
    ↳ SEMITEK USB-HID Gaming Keyboard         	id=16	[slave  keyboard (3)]
    ↳ SEMITEK USB-HID Gaming Keyboard System Control	id=17	[slave  keyboard (3)]
    ↳ SEMITEK USB-HID Gaming Keyboard Consumer Control	id=18	[slave  keyboard (3)]
    ↳ SEMITEK USB-HID Gaming Keyboard         	id=19	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=21	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=24	[slave  keyboard (3)]
```

**Expected behavior**
Tablet recognized properly as Krita does.

**Screenshots of Problem**
![2020-10-24_21-00](https://user-images.githubusercontent.com/26902524/97095952-0143c700-163c-11eb-98ab-0776334f87df.png)
![2020-10-24_21-00_1](https://user-images.githubusercontent.com/26902524/97095953-0274f400-163c-11eb-869f-c2461d628c36.png)

**Additional context**
Everything works fine when not using the Wacom map, but I really need the xsetwacom command to make use of the on-tablet buttons

**Comment by profran** [comment]
I don't know if it was the update (1.0.19) or something else, but it now works! I'm pretty sure I tried before this config and it did not work, but who knows... 

Thanks to all devs for this awesome piece of FOSS!

The config that works:
![2020-10-25_16-47](https://user-images.githubusercontent.com/26902524/97117342-cac08780-16e1-11eb-9547-5aca96c85cee.png)

**Comment by ghosh-r** [comment]
You just have to restart Xournal in order to alleviate this problem. Just close and open Xournal again. Everything should work file. In other words, *turning it off and on* solves the problem.

![image](https://user-images.githubusercontent.com/58001482/103889482-83586d80-510c-11eb-8d5a-c5523c6d418a.png)
That solves the problem.
