### ISSUE TITLE
Clicking outside the window with a stylus pointer makes it so the mouse isn't listened to anymore

### ISSUE THREAD

**Issue by ItsTehStory** [xournalpp/xournalpp#2341]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows
 - Version of Xournal++:  1.0.18

**Describe the bug**
When I use my Wacom Tablet to click anywhere else than the Xournal window, the Xournal window stop responding to mouse inputs.

**To Reproduce**
1. Open a empty xournal++ window 
2. Click outside the window WITH the pen input (mine is an old Wacom tablet CTL-460 and I don't have another with me...)
3. Now any mouse click is ignored

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.
Alright so I'll follow those instructions if you think it is needed, but since my Windows environnement isn't setup form C++ developpement I'll wait for your instructions.

**Expected behavior**
I expected for the mouse inputs (click on the menu bar and the GTK window) to be registered.

**Screenshots of Problem**
Hard to show, but basically, the buttons hover reaction doesn't appear.
![image](https://user-images.githubusercontent.com/18617578/97111658-823fa480-16b6-11eb-9b5c-ca4a3aa995c8.png)

**Additional context**
I apologize if for the lack of debug info, if they are needed I'll hop in Ubuntu to check out if the issue is OS dependent too and I'll attach debug logs! Thank you guys!
In the mean time, I'll simply not click outside the window ;)

**Comment by rolandlo** [comment]
I can't reproduce this on Ubuntu 20.10. It may very well be OS dependent. Rather than generating input debug logs you better check the behavior on Ubuntu. Also please tell: Does this only happen with the Wacom tablet pen or also with the mouse/touchpad?

**Comment by ItsTehStory** [comment]
@rolandlo I will try on Ubuntu, it might be a problem with how the Windows window manager (oh god that sounded horrible) handles the click or something. If I don't get anything on Ubuntu, it will be yet another reason to switch completely to Linux uh?

Also : I'm on a desktop computer, so only with Wacom tablet. When I use the mouse to change windows, it works perfectly. Although I get an issue listed already => it draws lines when the mouse enters the drawing area, but I really don't mind.

**Comment by ItsTehStory** [comment]
[I found this](https://github.com/xournalpp/xournalpp/issues/1789#issue-585645945) which seems to remove the blame on Xournal++ and put it on GTK. So I guess I'll close this issue since it's a duplicate!
