### ISSUE TITLE
PPA-Support for Ubuntu Groovy Gorilla?

### ISSUE THREAD

**Issue by AxelMKlein** [xournalpp/xournalpp#2343]
Hi dear Xournal++-Team,

when will the support for Ubuntu Groovy Gorilla happen in the PPA andreasbutti/xournalpp-master?

Great software! Love it.

Best regards
Axel

**Comment by Technius** [comment]
Duplicate of #2107.

**Comment by rolandlo** [comment]
The PPA support for Ubuntu Groovy Gorilla has been added.
