### ISSUE TITLE
Option to show pen tool cursor instead of system default when mouse not down

### ISSUE THREAD

**Issue by jeromew21** [xournalpp/xournalpp#2344]
**Is your feature request related to a problem? Please describe.**
In pen mode, I find the switching between a default cursor and pen tool to be visually unattractive and distracting.

**Describe the solution you'd like**
Either no longer switch to system default cursor when mouse/input device is not down, or have that behavior modifiable as a global option.

In terms of the change itself, it's a deletion of maybe 5 lines that I've been using on my personal build of the project.

Finally, I was wondering what the rationale behind this behavior was in the first place.

**Comment by rolandlo** [comment]
What version of Xournal++ do you use? This is already implemented in version 1.1.0+dev. Use the new input system (input system panel) and the "small dot icon" mode (view panel) in the preferences.

**Comment by jeromew21** [comment]
Using 1.1.0+dev, Linux, with new input system and small dot mode enabled in preferences. The pen tool still shows up as the system default cursor when mouse is not down.

**Comment by rolandlo** [comment]
It only does so if you use the mouse. It doesn't if you use a stylus. You can make your mouse act as a stylus. This must be configured in the input system panel.

**Comment by jeromew21** [comment]
That works, thank you!
