### ISSUE TITLE
Latex does not render

### ISSUE THREAD

**Issue by fallschirm9** [xournalpp/xournalpp#2345]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Win 10
 - 1.0.19
  - Installation method: official release

**Describe the bug**
Latex does not render when new text is generated-

pdflatex runs on code.

pdflatex gives following error in pdflatex.log:
...  INFO  pdflatex - this process (6656) started by 'unknown process' with command line: "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\\pdflatex.exe" -interaction=nonstopmode C:\\Users\\...\\AppData\\Local\\Temp\\xournalpp-12364\\tex\\tex.tex

If the cmd is entered with the filename in "....":
 "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\\pdflatex.exe" -interaction=nonstopmode "C:\\Users\\...\\AppData\\Local\\Temp\\xournalpp-12364\\tex\\tex.tex"
output is succesfully produced (tex.pdf).

**Comment by Technius** [comment]
Can you post the whole log (with your personal information removed)? The error message alone is not descriptive enough to indicate what the problem is.
