### ISSUE TITLE
Desktop integration disappeared...

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#2349]
**Affects versions :**
 - OS: Ubuntu 20.04
 - Desktop environment: gnome-shell 3.36.4
```
[romano:~/software/xournalpp/build] 1.0.x+* ± xournalpp --version
Xournal++ 1.0.19 
└──libgtk: 3.24.20 
```
 - Installation method: from source; make && sudo make install && sudo make desktop-install 

**Describe the bug**
I have no icon no app association for `xopp` (nor `xoj`) files:

![image](https://user-images.githubusercontent.com/6414907/97469062-428eec00-1946-11eb-8226-8fb202770dd8.png)

**To Reproduce**
Just save a  Xournalpp file.

**Comment by rolandlo** [comment]
Can you try building/installing following the [official guide](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md)?

**Comment by Rmano** [comment]
Will try --- basically the difference will be to install in `/usr` and not in `/usr/local`, if I understand correctly? So I suppose I need to remove the `/usr/local/` installation... is there a make shortcut for this?

**Comment by Rmano** [comment]
Ah, no, I suppose you are suggesting to create a package. But this is a bit of a pain when checking PR or things like that... Ok, will study the thing a little.

**Comment by rolandlo** [comment]
If I just want to check a PR I never install Xournal++ on my system. I only build (via `cmake ..` followed by `cmake --build .` and then run via `/src/xournalpp` from the terminal.

**Comment by Rmano** [comment]
Yep, probably a good idea. Will work on it. Thanks

**Comment by Rmano** [comment]
Ok, removing everything and generating and installing the deb package works. Will close this. Thanks and sorry for the noise.
