### ISSUE TITLE
Gtk3 branch crashes while saving

### ISSUE THREAD

**Issue by kelmes** [xournalpp/xournalpp#235]
Occasionally (twice so far in the last month or so), the gtk3 branch will crash while saving. It seems to happen after it begins writing the file, leaving a completely empty file after the crash. So far this has only happened on Ubuntu 17.10 with gnome 3.26, wayland session.

[errorlog.log](https://github.com/xournalpp/xournalpp/files/1463440/errorlog.log)

**Comment by badshah400** [comment]
I have seen this too. Typically, after the saved file is turned blank, I have to restore from the .autosave.xoj file, but it means I lose some unsaved work (the autosave time interval is set to a minute).

**Comment by andreasb242** [comment]
I merged the GTK3 branch into master, there were a lot of differences, and I also found some memory issues.
Therefore this Issue is probably not relevant anymore.

If the same error happens again, please reopen the ticket with the new log, but I don't hope so...
