### ISSUE TITLE
The new background pattern is too distracting under a dark page color.

### ISSUE THREAD

**Issue by sammdu** [xournalpp/xournalpp#2350]
## Affects versions :
 - OS: Linux/Ubuntu18.04.5
 - GNOME3 X11
 - Which version of libgtk do you use
     - 3.22.30
 - Version of Xournal++: 
     - 1.0.19
 - Installation method: bionic.deb via GitHub releases

## Describe the bug
New paper background (graph, dotted, etc) too distracting on top of a dark background color.

In an older version **this was not the case**. I always used a dark page background and the patterns would be very subtle and nice. The older version that worked well was `1.0.6` through the Unstable Ubuntu PPA:
```
http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu bionic/main amd64 xournalpp amd64 1.0.6-0~202008180544~ubuntu18.04.1
```

## To Reproduce
Choose a dark page background color (I use #111111)
Choose a paper background pattern, such as dotted or graph, but particularly bad with graph:
![image](https://user-images.githubusercontent.com/10665890/97528044-34ab8c00-1983-11eb-9937-9aaf79cbd095.png)

## Expected behavior
The background pattern should be subtle and not distracting:
![image](https://user-images.githubusercontent.com/10665890/97528303-c3200d80-1983-11eb-9ca4-4089a57d86aa.png)

## Suggestions
I know that depending on the light/darkness of the page background, the lightness of the patterns that is preferable will change. So maybe allow the use the set the color for background patterns?

**Comment by sammdu** [comment]
What is interesting is: in the past I was able to use background patterns with both light and dark page backgrounds, and the patterns would always be the right lightness, not distracting. But since upgrading to the new version, This behavior has changed. The background patterns are only subtle under a light background.

**Comment by rolandlo** [comment]
Would PR #2061 solve your problem?

**Comment by sammdu** [comment]
> Would PR #2061 solve your problem?

Looks like it might! Of course I haven't gotten a chance to try it but I hope it will work! I will wait for a newer release.

**Comment by rolandlo** [comment]
Speaking of newer releases: You may want to try out version 1.1.0+dev. Seems it already matches your desired pattern.

**Comment by sammdu** [comment]
Yep. Seems to work!
Although I don't see a UI element to set the foreground color, nor do I see anything in `pagetemplates.ini` (maybe I've overlooked), but I'm guessing a default was hardcoded?
The default works well, though. Thanks!

**Comment by robinp7720** [comment]
> > Would PR #2061 solve your problem?
> 
> Looks like it might! Of course I haven't gotten a chance to try it but I hope it will work! I will wait for a newer release.
> 
> I'm curious what the UI looks like, or is this still only available in the config file?
> 
> If you have yet to decide on the UI, I suggest putting the foreground color in `Journal` --> `Configure Page Template`. Maybe also augment the `Paper Color` menu to include both foreground and background color selection.

#2352, which is pretty much identical #2061, automatically alternates between a dark and light variant of the foreground color based on the color of the current background. There currently isn't a way to change the foreground color from the UI, and if one were added I would highly recommend not merging #2352 because it may over complicate things with the alternate backgrounds. I'm not a huge fan of either solution though.

**Comment by sammdu** [comment]
I suppose in real life if you buy a notebook you don't pick a color of the pattern - it just works.
So maybe if the implementation for automatic foreground color is solid we don't have to bother with the UI after all.

**Comment by sburris0** [comment]
This seems to be fixed. I've installed 1.1.2 and the contrast is much more subtle with greater legibility. Can this be closed now?

**Comment by rolandlo** [comment]
I agree (checking latest master), so I am closing the issue.
