### ISSUE TITLE
Freeze/hang on exit

### ISSUE THREAD

**Issue by BMicraft** [xournalpp/xournalpp#2351]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: KDE Plasma on X11
 - Which version of libgtk do you use: 3.24.23-4
 - Version of Xournal++: 1.0.18-2
 - Installation method: official package repo of Arch Linux

**Describe the bug**
Non-recoverable freeze on exit

**To Reproduce**
1. Close unsaved document using using window decorations
2. Be unlucky, it does not happen every time but about  1/5 - 1/10 during normal use

**Expected behavior**
No freeze (I'm not sure if it froze before asking whether to save, or while saving)

**Additional context**
```
** (xournalpp:3524257): WARNING **: 13:15:26.634: Type check: id was negative (-114), object is already deleted!?

** (xournalpp:3524257): WARNING **: 13:15:26.634: XojTypeCheck failed: expected XojPage but get XojPage on /build/xournalpp/src/xournalpp/src/model/XojPage.cpp:38

** (xournalpp:3524257): WARNING **: 13:15:26.634: Type check: id was negative (-185), object is already deleted!?

** (xournalpp:3524257): WARNING **: 13:15:26.634: XojTypeCheck failed: expected PageHandler but get PageHandler on /build/xournalpp/src/xournalpp/src/model/PageHandler.cpp:12

** (xournalpp:3524257): WARNING **: 13:15:26.634: Type check: id was negative (-185), object is already deleted!?

** (xournalpp:3524257): WARNING **: 13:15:26.634: XojTypeCheck failed: expected PageHandler but get PageHandler on /build/xournalpp/src/xournalpp/src/model/PageHandler.cpp:14
double free or corruption (!prev)
```

**Comment by rolandlo** [comment]
Looks like a duplicate of #1189. If would recommend to upgrade to version 1.1.0+dev (latest nightly release).

**Comment by BMicraft** [comment]
> Looks like a duplicate of #1189. If would recommend to upgrade to version 1.1.0+dev (latest nightly release).

I don't think it is similar at all, for me it did not crash, even after a day I still had the frozen window open. Also, I am pretty sure I did not touch the toolbar customization menu

**Comment by rolandlo** [comment]
Ok, not a duplicate. The only thing in common are part of the error messages: 
`Type check: id was negative (...), object is already deleted!?` 
emitted from the `XojPage` class. This class has had major changes from the 1.0.x series to the 1.1.0+dev version. That's why I recommend checking out version 1.1.0+dev. This may help us localize the bug and/or solve your problem.

**Comment by BMicraft** [comment]
>  That's why I recommend checking out version 1.1.0+dev.
I'm sorry I don't see where that is tagged. Which commit would that be? Or should I just use master?

**Comment by rolandlo** [comment]
Either use the automated nightly build or install from PPA. It's both descried on the work-in-progress [website](https://xournalpp.github.io/installation/#ubuntu-and-derivatives)

**Comment by BMicraft** [comment]
Has not occured since in ecb62bcb8689f3d18e719c4387294e9c85734ace
