### ISSUE TITLE
FormatException: Invalid GZip Signature

### ISSUE THREAD

**Issue by HugoCortell** [xournalpp/xournalpp#2356]
**Affects versions:**
 - I'm using the online version.

**Describe the bug**
FormatException: Invalid GZip Signature

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload file
2. FormatException: Invalid GZip Signature

**Expected behaviour**
It lets me edit the PDF.

**Comment by rolandlo** [comment]
Bugs for the online version must be reported on the [gitlab page](https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile/-/issues) of Xournal++ mobile.
