### ISSUE TITLE
Scrolling with Touchscreen

### ISSUE THREAD

**Issue by brightphaeton** [xournalpp/xournalpp#2361]
**Is your feature request related to a problem? Please describe.**
I use xournal++ at a Surface Go with Kubuntu 20.10 installed. The problem is, that I want to write without the keyboard attached, which works well, until you have to scroll down. For scrolling you have to use two fingers, which is very inconvenient if you use the app frequently.

**Describe the solution you'd like**
It would be very nice, if you could just scroll with only one finger like in every other touch-optimized program too. This could be implemented as an option in the Preferences.

**Describe alternatives you've considered**
Other methods of scrolling are the scrollbar or the hand in the toolbar, but both are not working with touch: With Plasma the scrollbar is very tiny in Xournal++ and vanish very fast, which is definitely not a problem in other programs. And the hand tool just doesn't work at all if you use it by touching at the screen.

**Comment by rolandlo** [comment]
Scrolling with one finger is usually possible. You may have some settings which prevent it. Can you please tell what version of Xournal++ you use and what are your settings in the input system panel and touchscreen panel of menu view->preferences?

**Comment by Podmornica** [comment]
I am also using Xournal++ with a Surface Go on Ubuntu 20.04 and I have the same issue. I can not scroll with one finger.
I am using Xournal++ 1.0.19 and under the input system panel I have an entry with touch (touchscreen) -> Touchscreen.

The interesting thing is that I can scroll for example in the Preferences->Touchscreen page, but I can not scroll on the main drawing page.

Any suggestion how can I enable scrolling?

**Comment by rolandlo** [comment]
Take screenshots of your input system and touchscreen settings and post them here. Maybe we can find the reason then.

**Comment by Podmornica** [comment]
Thank you for your response. Please find the screenshots below.
In the menu Preferences->Touchscreen->Device I can not select the touch device.

![Screenshot from 2020-10-31 21-37-23](https://user-images.githubusercontent.com/58565092/97789557-b5f06200-1bc1-11eb-88ac-8f084d335321.png)
![Screenshot from 2020-10-31 21-37-02](https://user-images.githubusercontent.com/58565092/97789558-b688f880-1bc1-11eb-86c8-c0e3de8c5178.png)

**Comment by rolandlo** [comment]
Have you tried setting the ELAN9038:00 04F3:261A stylus (touchscreen) device as Touchscreen?

**Comment by Podmornica** [comment]
I tried now and I can not write or move the page with the stylus.

**Comment by rolandlo** [comment]
Ok, that was the stylus then. Interesting that GTK+ recognizes it as a touchscreen.
Try disabling the zoom gesture (with restart) or enabling the GTK Touch/Scrolling workaround instead.

**Comment by rolandlo** [comment]
One more question: Are you in a Wayland or X11 session?

**Comment by Podmornica** [comment]
I disabled the Preferences->Touchscreen->Zoom Gestures, restarted Xournal++ and now the zoom gestures (two finger zooming) is not working, also the scrolling is not working.

I also tried to enable the Preferences->Touchscreen->Workaround, but the result is the same - the scrolling is not working.

In both cases I can scroll with the touch screen inside the Preferences window.

**Comment by Podmornica** [comment]
I am using X11.

**Comment by rolandlo** [comment]
I am running out of ideas, what could be wrong with the settings. Maybe the problem can be identified if you provide input logs as described on this [wiki page](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs).

**Comment by rolandlo** [comment]
Wait: One more idea would be to try it with the old input system.

**Comment by rolandlo** [comment]
A related, but not identical issue is #2217.

**Comment by brightphaeton** [comment]
Here are some more information about my system:
- X11
- [Surface Drivers](https://github.com/linux-surface/linux-surface)
- The Input Devices are absolutely correct, I have tested them carefully. Everything what is configured as mouse is really the mouse and so on
- As @Podmornica has already mentioned, scrolling works perfectly with one finger in the menus of xournal++
![Screenshot_20201031_225947](https://user-images.githubusercontent.com/70963316/97790961-d45c5a80-1bcd-11eb-989f-0bb04dffecda.png)
![Screenshot_20201031_230028](https://user-images.githubusercontent.com/70963316/97790962-d6261e00-1bcd-11eb-999e-819370b6765e.png)

**Comment by Podmornica** [comment]
I rebuild Xorunal++ with the debug features turned on and I can see GDK_TOUCH_UPDATE events when I try to scroll.
The source device is GDK_SOURCE_TOUCHSCREEN and the device class is INPUT_DEVICE_TOUCHSCREEN, but the scroll is not working.

Then I tried to download the latest unstable nightly version (1.1.0+dev).
With this version, if I disable the **Preferences->Touchscreen->Workaround**, the one finger scroll on the touchscreen is working. Hurray!

@rolandlo Thank you for your help.

**Comment by brightphaeton** [comment]
1.1.0+dev works also for me. Thanks a lot for your help @Podmornica and @rolandlo !

**Comment by tiagomarquescarvalho-dev** [comment]
Hi,

I have the same issue with a microsoft surface book 3 and Xournal++ V 1.2.7.

Any idea?

tks

**Comment by tiagomarquescarvalho-dev** [comment]
Found a solution:
edit>preferences>touch screen>disable GTK's ....
