### ISSUE TITLE
Question about 'dots' on page using Wacom Intuos Pro with Linux

### ISSUE THREAD

**Issue by The9Cat** [xournalpp/xournalpp#2367]
I love this program and use it regularly for 'blackboard' teaching.  But there is a minor nuisance that I don't know how solve: when taking the pen off the pad or flipping it over to use the eraser, I sometimes get a 'dot' on the page.  After a bit of hesitation, I often have too many of these dots.  They really aren't 'fatal' in any way, but is there a setting that will stop this?  I tried suppressing the first 2 to 4 events, but that does not do it.

Thanks!

**Comment by Rmano** [comment]
Can you specify which version are you using, and which tablet? It used to be like that for me, but with:

- new input system
- software palm rejection on
- and the "pad" function of my Wacom disabled

it doesn't happen anymore, or at least is so rare that I don't notice it.

**Comment by The9Cat** [comment]
I'm using:

- Xournal++ 1.1.0+dev
- Wacom Intuos Pro M
- Ubuntu 20.04

I do not have software palm rejection that I know about.  However, I turned off the touchpad on the Wacom device and the problem seems to be gone!   Thanks for that tip.

**Comment by The9Cat** [comment]
I played around some more with various settings (e.g. the touchpad palm negotiation build into Xournal++).   Suppressing touchpad events for a few seconds does help.  But the only thing that works well is turning off the touchpad function altogether.   I can use arrow keys (which I've mapped  to the Wacom shortcut keys) as a work around for scrolling.  So that's the answer, I think.

**Comment by Rmano** [comment]
I have a CTH-480 and the settings I have are these (1.0.19 on Linux):

![image](https://user-images.githubusercontent.com/6414907/98009002-62fef080-1df5-11eb-86a1-9a93d82d2e8f.png)

![image](https://user-images.githubusercontent.com/6414907/98009010-65f9e100-1df5-11eb-982d-cb058dcee634.png)

with that (and the hardware "touch" switch on the tablet in position "on") I can scroll and zoom with two fingers, and the "small dots" phenomenon has almost disappeared (sometime it happens, but it's really rare).  I hope it can help a bit...

**Comment by The9Cat** [comment]
Well that's interesting.  I've been using "new input system" by default so that was already on.  I tried the "hand recognition" an hour ago with the touchpad on.  It is better than with no "internal hand recognition" but I'm still getting dots.

**Comment by Rmano** [comment]
I don't know --- I have nothing about wacom drivers anywhere, just using the default configuration.

**Comment by The9Cat** [comment]
For now, I'm going to simply turn the touchpad off.  That definitely gets rid of the dots.  Thanks @Rmano !

**Comment by Rmano** [comment]
>  Thanks @Rmano !

You're welcome!
