### ISSUE TITLE
"fi" doesn't render correctly in exported pdf

### ISSUE THREAD

**Issue by airbete** [xournalpp/xournalpp#237]
1. Open Texte_1.pdf with xournalpp.
2. Add a plain page after the first page.
3. Add the text "finale" on the new page.
4. Save and export to pdf.

Result in the exported pdf is "fin a l  e"

5. Change "finale" to " finale" (add a space before).
6. Save and export to pdf.

Result in the exported pdf is "  À nale"

I note that "finale" is rendered correctly if
- it is added to page 1 instead of page 2 OR
- if I use no background at all.

[Texte_1.pdf](https://github.com/xournalpp/xournalpp/files/1484796/Texte_1.pdf)

**Comment by peetCreative** [comment]
Might be a Cairo bug...

**Comment by andreasb242** [comment]
Looks like an econding error. Probably an error on PDF Merging

**Comment by andreasb242** [comment]
I googled and found

 podofouncompress --help
 Usage: podofouncompress [inputfile] [outputfile]

       This tool removes all compression from the PDF file.
       It is useful for debugging errors in PDF files or analysing their structure.

 PoDoFo Version: "0.9.3"

And if I try to decompress the PDF, it crashes :-(
In the PDF are two characters, so this is not the issue.

I need an uncompressed PDF for debugging. PDFs are realative easy to read, if they are not compressed.

**Comment by andreasb242** [comment]
I currently think about a simple solution: Add a checkbox "Simple export" to the PDF export, and in this case simple draw the pages with Cairo to a PDF.

**Comment by andreasb242** [comment]
This bug is solved with the new PDF Export.

I use now the standard GLib APi, and export the PDF with Cairo.
The old implementation will still be available with -DADVANCED_PDF_EXPORT_POPPLER=ON
Currently Bookmarks are not exported, but with Cairo 1.16 it will also be possible.
So this should solve a lot of problems I hope.

**I Copy this texts to all related tickets **
