### ISSUE TITLE
export layers in different PDF pages

### ISSUE THREAD

**Issue by sanette** [xournalpp/xournalpp#2373]
I'm starting using Xournalpp for a seminar presentation.
I'm using the layers to progressively add new content to a page, this works nicely by
* make sure initially the page has only "Layer 1" activated (and background of course)
* use CTRL-SHIFT-RIGHT ('next layer') to activate next layer
* when everyhing has been shown, I go to next page and start again.

My request is: it would be nice that PDF export could save one page per layer, so that when we display the PDF page after page, this has the same effect as what is described above. This way, the presentation could be used on a computer that doesn't have xournalpp installed.

**Comment by fujtajlfik** [comment]
I would also appreciate this as a possibility for exporting PFD.

**Comment by sanette** [comment]
I have implemented this (on my local copy). I like it, I think it will make me use xournalpp more often for presentations!
My question now: how do we choose between this PDF export mode and the usual PDF export mode?
1. add a flag in the Preferences
2. add another choice in the File menu (like 'Export Layers to PDF')
3. ask with a popup when selecting 'Export as PDF' (something like 'Do you want to export all layers as separate pages?')

**Comment by sanette** [comment]
the code is here: https://github.com/sanette/xournalpp

**Comment by sanette** [comment]
Here is an example:

[2020-12-23-Note-09-06.pdf](https://github.com/xournalpp/xournalpp/files/5734090/2020-12-23-Note-09-06.pdf)

**Comment by rolandlo** [comment]
> EDIT: I have chosen option 4. You have to use "save as..." then select PDF, and the dialog will let you check a box "export all layers as separate pages"

Could you also add a command-line option?

**Comment by sanette** [comment]
> Could you also add a command-line option?

ok, done!
`xournalpp -p output.pdf --export-layers file.xopp`

**Comment by rolandlo** [comment]
Great! Please make a Pull request to the master branch (after you have pushed your latest commit including the command-line option).

**Comment by Technius** [comment]
Fixed in #2589.

**Comment by ventu06** [comment]
When writing a presentation, I noticed that sometimes I need more flexibility, for example, having layers that only appear in certain slides but not in subsequent ones.
So I wrote a small plugin that uses the layer names to decide which slides they should appear in and which they should not. You can find it [here](https://github.com/ventu06/xournalpp-plugins)!
