### ISSUE TITLE
Stylus not working in Plasma Wayland session

### ISSUE THREAD

**Issue by brightphaeton** [xournalpp/xournalpp#2377]
**Affects versions :**
 - OS: Linux Ubuntu 20.10
 - Desktop environment: Kubuntu (KDE Plasma 5.19.5) - Wayland
 - libgtk version: 3.24.23
 - Version of Xournal++: both 1.1.9 stable and 1.1.0+dev nightly not working
 - Installation method: PPA (apt)
 - Linux Kernel: linux-image-5.9.3-surface

**Used Hardware**
- Surface Go (64GB)
- Surface Pen

**Describe the bug**
When using xournal++ within the Plasma Wayland session, xournal++ recognizes different input devices compared to usually (e.g. Wayland Pointer or Wayland Touch). The pen and eraser are stil recognized separately, but they don't behave like that. Both pen and eraser are drawing at the document, the pen buttons aren't working either. I tried to change the input method to old, it doesn't make any difference. When disabling the eraser, nothing changes, when disabling the pen, neither the pen or the eraser are drawing.

**To Reproduce**
1. Install Kubuntu 20.10
2. Start Wayland session
3. Install and open xournal++

**Expected behavior**
The pen and the eraser should behave like two separate devices (as they do in X11 session). Also the buttons at the pen should work

**Screenshots of Problem**
![Screenshot_20201108_133708](https://user-images.githubusercontent.com/70963316/98465355-df644b80-21c8-11eb-8767-23d8382888ff.png)

**Additional context**
I want to use Wayland in future because of better touch support

**Comment by LittleHuba** [comment]
This is not Xournal++! This is xwayland and GTK+ not working together yet. You'll have to give the devs some more time. Nothing we can do about it. You'll have to restrict yourself to a X11 session for now.

**Comment by brightphaeton** [comment]
ah, I see. Thanks for this useful information!
