### ISSUE TITLE
Layer preview not updated instantly while drawing

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2378]
**Affects versions :**
 - OS: Linnux
 - X11
 - Which version of libgtk do you use
     - 3.24.23
 - Version of Xournal++: 1.1.0+dev (1e314821)
 - Installation method: AUR

**Describe the bug**
When painting on a new layer the layer preview in the side panel (F12) won't be updated.
It will first update and show the painting if a) a new layer is created or b) if one switches between page preview and layer preview back and forth.

**To Reproduce**
1. Open the side panel (F12)
2. Create a new layer
3. Paint on it

**Expected behavior**
The drawing appears on the layer preview instantly.

**Comment by rolandlo** [comment]
I have also observed this behavior and think it should be fixed. I am not sure, however, how often the layer previews should be updated. Maybe they should be updated upon elements (like strokes, images,...) have been completed and added to the layer.

**Comment by rolandlo** [comment]
I have looked at it today. This will most likely need several non-trivial changes to make it work well. Not that easy.

**Comment by dszgit** [comment]
I don't know if this has the same cause, but for me, page previews also do not update.  Switching between page and layer previews does not help.  Only reopening the document seems to make the page previews update.

As for when it *should* update, I would suggest updating (page preview, and also(?) layers) whenever focus changes to a new page.  I don't know anything about the code and how hard that would be to implement.  But as a user, I care more about seeing previews of the other pages than the one I'm currently editing.

**Comment by rolandlo** [comment]
@dszgit You are right that the page previews also do not update. Your suggestion makes sense to me for updating page previews. In contrast to updating previews instantly when drawing, that should not create performance problems. Moreover it should be easier to implement than what I had previously in mind.

**Comment by rolandlo** [comment]
Actually I found out that previews do update in version 1.0.19 and 1.0.20, not instantly, but after a little delay (which makes sense).

**Comment by rolandlo** [comment]
So I fixed the bug in #2630 by restoring the behavior from 1.0.19 and 1.0.20: previews of pages (and layers) that have changed are updated all 5 seconds.
