### ISSUE TITLE
Change "trasparency" to "opacity" in pen option -> fill transparency dialog

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#2381]
This is a very, VERY low priority thing...

**Affects versions :**
 - OS: Linux
 - 1.0.19 (and before)

**Describe the bug**
When setting the transparency on fills (which, by the way, should be better discoverable --- maybe a right click on the bucket tool?) you are asked to set "transparency", while really you set "opacity" (when put to 100% the result is solid fill, and 0% means totally transparent).

**To Reproduce**
Just select "Tools->Pen options->Fill transparency"

**Expected behavior**
The option should be called "opacity" or the values should act the other way around ;-)

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/6414907/98524922-15acd400-2278-11eb-80e1-75a71dad4feb.png)

**Comment by rolandlo** [comment]
I agree, that the name "transparency" should be changed to "opacity".
About right click I am not so sure. That would be a problem for users, who only work with the stylus (no mouse).

**Comment by Rmano** [comment]
> About right click I am not so sure. That would be a problem for users, who only work with the stylus (no mouse).

Yes, thinking about it, you are right. Maybe a separated icon for setting the opacity, by default near the bucket one... or a double tap...
