### ISSUE TITLE
Xournal++ can't open some directories

### ISSUE THREAD

**Issue by TheBluePingu** [xournalpp/xournalpp#2382]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
     - the command doesn't work 
 - Version of Xournal++: 
     - 1.0.16 commit 07cb970f
 - Installation method: 
     - Ubuntu software
**Describe the bug**
   When trying to open or save in some folders of my computer, have the window : "could not read the contents of DIRECTORY" "Error opening DIRECTORY : permission denied"

The directory is a nextcloud local directory on a other HDD, and accessed via a simlink DIRECTORY ->/mnt/... . This partition is a NTFS partition with mounting instructions : nosuid,nodev,nofail,x-gvfs-show,gid=1000,uid=1000,rw

When trying to navigate through my filesystem, have the same error when i try to reach /mnt/. Obviously /mnt/ owner is root:root and rights of /mnt is drwxr-xr-x. However /mnt/PartContainingDIRECTORY has current user as owner.
**To Reproduce** 
Have the same configuration (didn't tried to replicate)

**Expected behavior**
To save on any directory as the one one /home/ where it works perfectly.

**Additional context**
Tried to run xournalpp as sudo in order to see if i could override what appears to be a rights issue but when using 

`sudo xournalpp`

I get this error : ```

mkdir: cannot create directory '/run/user/0': Permission denied
No protocol specified
Unable to init server: Could not connect: Connection refused

(xournalpp:8828): Gtk-WARNING **: 12:16:33.317: cannot open display: :0
```

**Comment by Technius** [comment]
The Xournal++ in the snap store (Ubuntu software) is unofficial and unsupported. Can you install through Flatpak or with the [deb files in the releases page](https://github.com/xournalpp/xournalpp/releases)?

**Comment by TheBluePingu** [comment]
I thank you for your answer, I'll try that (wouldn't have guessed that Ubuntu Software shares unsupported package)

**Comment by Technius** [comment]
This issue is probably outdated, closing for now.

**Comment by unhandyandy** [comment]
I'm having the same problem on Ubuntu 25.10.
