### ISSUE TITLE
Xournal++ is not working on ubunto 18.04

### ISSUE THREAD

**Issue by modshareef** [xournalpp/xournalpp#2385]
i am using Xournal++ 1.0.16 version Git Commit 07cb970f in ubuntu 18.04.I connected wacom intuos tab CTL4100/KO-BX.  When bring my stylus closer to the tab its continuously toggling between pen and eraser and  unable to write.When stylus touch the tab, eraser square box is activating automatically.I restarted my system multiple times.No improvements,Screen casts available.(video)
![image](https://user-images.githubusercontent.com/74226786/98630015-9da3e400-2333-11eb-8fea-bc3968bf4f6e.png)

**Comment by rolandlo** [comment]
You seem to use the Snap Package, which is unofficial and unmaintained. Can you install through PPA, Flatpak or with the [deb files in the releases page](https://github.com/xournalpp/xournalpp/releases)?

**Comment by modshareef** [comment]
Dear team Members,

I really appreciate ur fast response, now it really working nice.

Let me check it for a week.

Thanks for your support ,really appreciate your wonderful programme,
Xournal will make millions of life easier.

Sure


Regards

Muhd shareef

**Comment by Technius** [comment]
I'm glad it works! Feel free to reopen this issue or submit another one if you run into any problems.
