### ISSUE TITLE
Debug popup when using "open with" functionality on Windows 10

### ISSUE THREAD

**Issue by TrevCan** [xournalpp/xournalpp#2387]
**Is your feature request related to a problem?**
Yes, I'm frustrated that I can't open it using the Open With feature of windows 10, the only things it returns is a small window called *Debug IN* with the path of my file. It would be nice if I could open PDF files just by clicking them and not opening xournal++ and then selecting File->Open->etc.. I don't know if xournal++ supports this in other versions.

**Describe the solution you'd like**
Add CLI functionality to open files from the terminal and add "open with" feature on windows 10. 

**Screenshot of what happens when I try to open a PDF file by double clicking it**
![image](https://user-images.githubusercontent.com/44383325/98712635-29c20580-234c-11eb-8cf4-345b10522a22.png)

**Comment by Technius** [comment]
This is unexpected behavior, so I'll leave this issue open until we've removed the debug message (or hidden it behind a flag).

**Comment by nop112233** [comment]
I have the same issue. Every time I open a pdf I get the Message "DEBUG IN..."

**Comment by rolandlo** [comment]
These messages will disappear once #2606 is merged.

**Comment by nop112233** [comment]
> These messages will disappear once #2606 is merged.
Super! Thank you

**Comment by jeffsantos** [comment]
Hi, I have the last Xournal++ release (1.0.20, which should include this fix) installed on Windows 10, but I am still receiving this debug message when launching a pdf with the "Open With" action. I didn't find any workaround on the web. Any tip?

**Comment by rolandlo** [comment]
@jeffsantos You need to install [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)
