### ISSUE TITLE
Under windows there is something wrong with the terminal messages:

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#2395]
Under windows there is something wrong with the terminal messages: 
![grafik](https://user-images.githubusercontent.com/40485433/99076716-dfdf5680-25bb-11eb-8c14-a6c66f53515f.png)

_Originally posted by @rolandlo in https://github.com/xournalpp/xournalpp/issues/2391#issuecomment-726762477_

**Comment by Technius** [comment]
This probably doesn't matter since the average Windows user is not going to be starting Xournal++ from the console.

If we really do care about fixing this, we should just reword the message so we don't need special characters, e.g. `Initializing UI of plugin FooPlugin`
