### ISSUE TITLE
Release key accelerators don't work for plugins.

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#2396]
**Affects versions :** 
 - OS: Ubuntu 20.10
 - (Linux only) Desktop environment: X11 
- Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
To activate plugin functions, we can assign accelerators. According to the official format accelerators like `<Release>z` should be activated when releasing a key (z in this example). This would be useful for obtaining temporary activation of tools via plugins. For example pressing z would activate the eraser and releasing the z key would switch back to the previous tool. However those release key accelerators don't work for plugins. 

**To Reproduce**
1. Write or reuse any plugin
2. Use the `app.registerUi` function to bind a release key accelerator (like `<Release z>`) to some callback function.
3. Activate the plugin and observe that (pressing and) releasing the key does not do anything.

**Expected behavior**
Releasing the key should activate the callback function defined in `app.registerUi`

**Additional context**
I tried adding the `GDK_KEY_RELEASE_MASK` in `InputContext::connect`, but it did not solve the problem.
In `Plugin:registerMenu` the accelerators are added to the main window.

**Comment by Nei8t** [comment]
I apologize for bringing something old up, but was this issue ever addressed? I am also unable to set release key accelerators in my plugin and haven't figured out how to make it work. It could really be benefiting me since using the pen buttons (mapped to middle and left mouse keys) to temporary activate certain tools causes issues when interacting with the toolbar and scrollbar (the mouse cursor would get stuck there until I physically move it)

**Comment by rolandlo** [comment]
The documentation of [gtk_accelerator_parse](http://web.mit.edu/ghudson/dev/nokrb/third/gtk2/docs/reference/gtk/html/gtk-Keyboard-Accelerators.html#gtk-accelerator-parse) is misleading, I think. I once looked into the code and didn't find anything related to key release. In GTK 4 the documentation was corrected, see https://docs.gtk.org/gtk4/func.accelerator_parse.html. So I think it's not possible in Gtk 3 and Gtk 4.

I'm closing the issue therefore.
