### ISSUE TITLE
High loads when drawing lines with wacom pen under Sway

### ISSUE THREAD

**Issue by bionade24** [xournalpp/xournalpp#2398]
Related sway issue: https://github.com/swaywm/sway/issues/5815
**Used versions :**
- Sway 1.5.1
- Xournal++ 1.0.19
- libgtk 3.24.23
- linux-wacom 5.9.8

**Describe the bug
(Either) Xournal++ or/and Sway get extremely high load increasing with the time you draw a line with a wacom pen under sway.

**To Reproduce**
1. Draw a line in Xournal++ with a pen under sway
2. Don't let the pen loose contact with the surface

**Input Logs**
debug_input.log http://ix.io/2E8t
debug_gdk_input.log http://server2.oscloud.info/debug_gdk_input.log
`libinput list-devices` http://ix.io/2E8x

**Expected behavior**
Expectable loads that don't increase over the time, like on kwin_x11 (screenshot 2)

**Screenshots of Problem**
![screenshot_sway](https://user-images.githubusercontent.com/42534613/99147665-12a05200-2683-11eb-83da-4caf7cf20a73.jpg)
![screenshot_kwinX11](https://user-images.githubusercontent.com/42534613/99147674-18963300-2683-11eb-848e-fb4f83bad5bf.png)

**Additional context**
If someone helps me getting my pen working under weston, I'll test the behaviour.
Write Stylus from http://www.styluslabs.com/ keeps the both loads under 10%.

**Comment by bionade24** [comment]
Input log added.

**Comment by bionade24** [comment]
Write Stylus from http://www.styluslabs.com/  keeps the both loads under 10%.

**Comment by bionade24** [comment]
Related Wlroots issue: https://github.com/swaywm/wlroots/issues/2471

**Comment by wisp3rwind** [comment]
See also the related GTK [issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3350) and [merge request](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2822) which is awaiting review.

I presume Write is running via XWayland, could you verify this?

**Comment by bionade24** [comment]
> I presume Write is either not a GTK application or running via XWayland, could you verify this?

Stylus Write is a Qt programm. So if it's a GTK/Wlroots issue, I'll close this.
