### ISSUE TITLE
Shift content upwards function (analog to shift content downwards)

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2402]
**Is your feature request related to a problem? Please describe.**

There's the "shift content downwards" function. However, if one tries to shift something the opposite direction, upwards, it doesn't work.

**Describe the solution you'd like**
Select the tool, click on the paper: If the mouse moves above the line, shift the content above upwards; if it moves below, shift the content below downwards.

**Describe alternatives you've considered**
The only alternative I currently see is selecting the content and moving it freely with the mouse.

**Comment by Febbe** [comment]
You need to place the line above the content you want to move upwards

**Comment by ericschdt** [comment]
> You need to place the line above the content you want to move upwards

Oh, this works. The other way was more intuitive to me though. :)
