### ISSUE TITLE
Sluggish performance

### ISSUE THREAD

**Issue by spuulis** [xournalpp/xournalpp#2403]
**Affects versions :**
 - OS: Mac (Both Catalina and Big Sur)
 - Version of libgtk: 3.24.10
 - Version of Xournal++: 1.0.19, 1.0.18, 1.0.12 (these are the ones I have tried)
 - Installation method: official release

**Describe the bug**
App in general runs very slowly. When drawing with the pencil tool the drawing lags about 400ms behind the pen leading to 
uneven sketches. The lag is especially prominent when using the erasing tool. When drawing, every ten or so seconds the lag for a moment becomes noticeably worse. Writing or drawing is nearly impossible, as drawings come out ragged.
Scrolling is affected as well, however that does not bother me as much. Disabling autosave, changing tools, background or zoom does not affect the issue in any way.

**To Reproduce**
Steps to reproduce the behaviour:
 - The behaviour is noticeable right after opening the app.
 - The delay between the drawing and the pen can be especially noticed when quickly drawing long lines.

**Additional context**
I doubt this is a hardware issue, as I have not noticed any issues when annotating .pdf documents in "Adobe Acrobat Reader" or sketching with stylus in "Sketchbook".

**Comment by Ninja243** [comment]
Could this be related to the following issue?

https://github.com/xournalpp/xournalpp/issues/2302
