### ISSUE TITLE
Feature request: Virtual laser pointer (like openboard)

### ISSUE THREAD

**Issue by arousta** [xournalpp/xournalpp#2410]
I love everything about xournal++ except it does not have virtual laser pointer similar to openboard. Can anyone implement this in an upcoming realese? :pray:

**Comment by rolandlo** [comment]
duplicate of #1778. See also #1822 and checkout [this implementation](https://github.com/michaelcadilhac/xournalpp/commits/universal-tap-and-laser-tool) by @michaelcadilhac
