### ISSUE TITLE
Lack of Spanish translation files

### ISSUE THREAD

**Issue by potero84** [xournalpp/xournalpp#2415]
**Affects versions :**
 - OS: Windows
 - Version of Xournal++: 1.0.19
 - Installation method: official Windows installer

**Describe the bug**
The official Windows installer does not include Spanish translation files

**To Reproduce**
1. Install and launch the program
2. You only get English GUI
3. Look into C:\Program files\Xournal++\share\locale\ and you can see there isn't "es\LC_MESSAGES" folder with *.mo files inside

**Expected behavior**
Spanish GUI available

**Comment by Technius** [comment]
Seems like a combination of issues:
* The CrowdIn bot is not sending new pull requests for some reason. CC @LittleHuba 
* 1.0.x is out-of-sync with master in terms of translations and will probably not be updated, so we should make a release soon.

**Comment by rojizo** [comment]
Same on Linux (Ubuntu focal)... No spanish translation (using the official deb)

**Comment by LittleHuba** [comment]
@Technius I'll take a look and unlock spanish translations if they are still locked.

**Comment by LittleHuba** [comment]
Not quite sure what happened but the integration of Crowdin and Github was removed... I reestablished it so we should get translations again. Spanish is unlocked and should be available on the Masterbranch at least.

**Comment by MichelReims** [comment]
And no french either

**Comment by LittleHuba** [comment]
Could you please check the development version (either via a nightly or by building from master branch)? If the translation is missing there as well, we need to find the issue, as it is then not caused by the removed integration.

**Comment by LittleHuba** [comment]
Okay don't bother I just found the cause.

https://github.com/xournalpp/xournalpp/blob/5dbd6f35f360746955331dfeed011e30f12c3776/windows-setup/build-setup.sh#L39

We need to get this list from Crowdin and remove this hardcoded version.
