### ISSUE TITLE
unable to edit latex formula

### ISSUE THREAD

**Issue by bderembl** [xournalpp/xournalpp#2417]
When I double click on a latex formula with the selection tool, nothing happens (so I can't edit the latex formula).
Writing a new formula works fine.

I am using version 1.0.19 (libgtk: 3.24.23) with archlinux (official repos) on gnome-wayland

**Comment by Technius** [comment]
As a temporary workaround, you can edit the formula by selecting it and then clicking the latex tool button.

I can't reproduce this issue. Can you follow [these steps](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) here to help us debug?

**Comment by bderembl** [comment]
Your workaround works and I can't reproduce this issue when building xournalpp from source.
Thanks!
