### ISSUE TITLE
Add "How to pronounce xournalpp" to the docs

### ISSUE THREAD

**Issue by rpagliuca** [xournalpp/xournalpp#2419]
**Is your feature request related to a problem? Please describe.**
I'm having trouble while communicating the name `xournalpp` with my teammates, as we do not know how to pronounce the name of the project.

**Describe the solution you'd like**
Please add it to the docs.

**Describe alternatives you've considered**
Add mp3 recording to the docs.

**Additional context**
Not knowing how to pronounce it is bad for my extraneous cognitive load.

**Comment by rolandlo** [comment]
Good question. I would like to know it myself. Maybe @andreasb242, who was already co-developing Xournal can tell? 
In the meantime I will keep pronouncing Xournal++ like in [this Infinitely Galactic video](https://youtu.be/W_frC1uaa6U?t=35)

**Comment by Technius** [comment]
I think the intended pronunciation is supposed to be like "journal" but with an X sound instead of a J sound, based on the original description of Xournal:
> Xournal is an application for notetaking, sketching, keeping a journal using a stylus. (from the [SourceForge](http://xournal.sourceforge.net/) page)

A few friends of mine say "Xournal PP" instead of "Xournal++" because the former rolls off the tongue more easily.

I'm not sure what the official consensus is though.

**Comment by cbm755** [comment]
> but with an X sound instead of a J sound

This does not narrow it down much for an international audience...

FWIW, I say the X like in "Xylophone" + root of "Journal" as @Technius says.  Something like "Zur-nal".   Definitely not "Ex-ur-nal" (which I've heard colleagues say).  Not Chinese "X" (like in "xiao peng you", roughly Shur-nal).

I have no opinion on "pp" versus "plusplus": long term I would guess people will not need to disambiguate.

**Comment by Febbe** [comment]
I pronounce it like journal ([ˈdʒɜː(r)n(ə)l]) with an X instead of an J pronounced as [ks].
Like [ksʒɜː(r)n(ə)l] or [ks]ournal. Wheter someone chooses to say 'P P' or 'Plus Plus' is in my opinion irrelevant.

**Comment by andreasb242** [comment]
I never thought about an official name, I'm located in Switzerland (German Part) and therefore also pronounce it German, with an X at start and with spoken plus-plus.

I don't call it Journal, because the MS Application is called like this ;-)

**Comment by cbm755** [comment]
I posted a ticket at Xournal to see if Denis Auroux has a preference: https://sourceforge.net/p/xournal/bugs/218/

**Comment by jakubk0** [comment]
I'm not an English native speaker, but during my learning I've put some stress on pronunciation, [IPA](https://en.wikipedia.org/wiki/Help:IPA/English) etc. Most of the time I use [Merriam-Webster learner's dictionary](https://learnersdictionary.com/) as a source. I've checked pronunciation of some English words there, starting with the letter "x" and it appears that all of them are pronounced as with "z" (/z/). Examples:
- xenophobia /ˌzɛnəˈfoʊbijə/ or /ˌziːnəˈfoʊbijə/
- xerox /ˈziɚˌɑːks/
- xylophone /ˈzaɪləˌfoʊn/
- xenon /ˈziːˌnɑːn/

The notation on the right is [IPA](https://en.wikipedia.org/wiki/Help:IPA/English).
Therefore, I think that it is safe to establish that Xournal for the sake of consistency should be pronounced /ˈzɚnl̟/.

**Comment by cbm755** [comment]
Regarding the original Xournal, Denis Auroux said:

> I just pronounce it 'ksournal' but I'm very open minded about how people choose to pronounce it. And if your language has a 'kh' sound (greek chi, russian X, ...) it's definitely fine to use it to pronounce 'Xournal' if you wish to.

**Comment by jjspace** [comment]
I was just looking for something like this and couldn't find it. Any update on adding a section like this to the main page? It doesn't even have to point to a "one true way" to pronounce it, just something saying "pronounce it how you want, here are some that we use" would be enough.

**Comment by rolandlo** [comment]
I agree, we may have to add something like that to the website. Most importantly Xournal++ is neither Xournal nor XournalApp. There is a lot of confusion about that.
