### ISSUE TITLE
problem with generating LaTeX formulas

### ISSUE THREAD

**Issue by lszk-pl** [xournalpp/xournalpp#2423]
**Affects versions :**
 - OS: Windows 10 
 - Version of Xournal++:  1.0.19
 - Installation method: official release

**Describe the bug**
The LaTeX formulas do not generate pictures for some users. Appears an error: "_The formula is empty when rendered or invalid_".
The error generated by pdflatex suggests, that the problem is connected with ~ in the name of the user in the path to the processed file:

```
! Emergency stop.
<to be read again> 
                   \protect 
<*> C://Users//PIENIA~
                      1//AppData//Local//Temp//xournalpp-23540//tex//tex.tex
*** (job aborted, file error in nonstop mode)
```
Users with shorter names which do not use windows short aliases in their profile username do not encounter the problem on the same machine.

**Comment by Technius** [comment]
Superceded by #2910.
