### ISSUE TITLE
Chops off pages

### ISSUE THREAD

**Issue by tarandalinux** [xournalpp/xournalpp#2427]
OS: Triskel 9
libgtk: 3.22.30
Version: 1.0.19
Installation Method: .deb file I think

**Describe the bug**
Just like the tile says.  It chops off pages.

**To Reproduce**
1. Load The fifth Discipline by Peter M. Senge on both Xournal and Xournal++
2. Do a side by side comparison
3. notice the chopped off pages

**Expected behavior**
That it would have the same pages and not chop any of them off.

**Screenshots of Problem**
![Screenshot_20201120_052344](https://user-images.githubusercontent.com/74770376/99795010-b01adc00-2af0-11eb-8517-c4dd115eea31.png)
![Screenshot_20201120_052322](https://user-images.githubusercontent.com/74770376/99795052-c0cb5200-2af0-11eb-9a23-6e65979b724c.png)

**Comment by rolandlo** [comment]
Thanks for your bug report. How should we reproduce the bug without having The fifth Discipline by Peter M. Senge available? If you can, please provide a download link.

**Comment by Febbe** [comment]
I don't see a chopped off page. You activated the book mode. Thus, 2 pages are laid out, side by side. Just scroll to the right or deactivate it in the Bar at the bottom right.
