### ISSUE TITLE
Default pen is ignored

### ISSUE THREAD

**Issue by thecandyman** [xournalpp/xournalpp#2428]
**Affects versions:**
 - OS: Ubuntu 20.04 (Gnome Desktop)
 - libgtk: 3.24.20
- Xournal++ 1.1.0+dev 
 - Installation method: PPA (http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu)

**Bug description:**
The default pen (set in "Defaults" section in "Preferences") is not used by Xournal++.

**Comment by rolandlo** [comment]
This is a duplicate of  #2303 and should get fixed in #2339
