### ISSUE TITLE
Customizable icons for selecting more pen properties at once (like in stylus buttons customization)

### ISSUE THREAD

**Issue by Fef0** [xournalpp/xournalpp#2431]
**Is your feature request related to a problem? Please describe.**
First of all thank you very much for your hard work, Xournal++ is an awesome app!
I've used Xournal++ on my tablet with a stylus for a few days now and I know that I can use the buttons on my pen to do a very similar thing but it would be great to have a way to select more pen properties at once, so that we can select **more** than N+1 templates real quick (where N is the number of buttons that our pen has + 1 for the tip).
For example if I want to write a title during my note-taking I'd use a thick red stroke, when I start writing normal text I'd use a fine black stroke, when I write questions I'd use a medium blue stroke, when I draw graphs I sometimes use a fine red dotted lines and so on.
If I only have 2 buttons and the tip I can only have 3 custom templates (and no place for the eraser), so for the others I have to enable every single property manually and this is sometimes time-consuming during lectures.

**Describe the solution you'd like**
It would be fantastic to have more quick-select fully customizable icons that can be inserted in the floating toolbar or anywhere else to have access to all the templates.

**Comment by rolandlo** [comment]
This is an interesting suggestion. One solution would be to create toolbar icons that are defined by (the file path of) an icon image and a keyboard accelerator (which is evoked when the icon is pressed). The accelerators can be defined via plugins. It is pretty easy to define accelerators that do the things you require above (like changing color, thickness, line style). This would be a very flexible solution (although maybe not the most user friendly one).
Since toolbars are already pretty customizable, it would probably not require that much work to add this functionality.

**Comment by Fef0** [comment]
Thanks @rolandlo, that's good to hear!
Maybe a tab in the settings could be added to create new templates (and maybe use some default icons with only different colors to avoid complexity). 
Now it's just a matter of choosing the easiest way to implement that, because I see two possibilities:
- **A simple templates creator**: you can only define **pen** behaviors (such as color, thickness, line style and, why not, enable/disable pen pressure which is useful for titles) 
- **A complex templates creator**: you can also define **other tools** behaviors (eraser, highlighter, ..) and maybe define some customizable macros (e.g. pen + thickness + color + draw circle mode)

I don't know how Xournal++ works under the curtains so I can't really help to add those functions (even though I'd like to contribute someday)

**Comment by langfingaz** [comment]
I just tried to use the tool `PEN` multiple times in `toolbar.ini` in the hope that one can individually configure two (or more) pens in the toolbar and quickly switch between them. But apparently one can only use it once per profile.

So I ended up with some questions / thoughts:

1) What is the reason that one can only insert the `PEN` tool once? How much effort would it be to insert two or more pens?
2) What do you think of a second pen tool analogous to `COLOR(0x3333cc)` and `COLOR_SELECT`: `PEN_FIXED(DOTTED,COLOR(0x3333cc),MEDIUM)` and `PEN`. `PEN_FIXED` can be configured in the .ini file and used multiple times per toolbar profile (similar to `COLOR(0x3333cc)`). `PEN` can only be used once (as it currently is the case) but can be configured from within the xournal++ user interface.

Well, I guess the answer to 2) is the one from above to rather write a small lua plugin ;) But I would still be interested in what you think about this idea.

And I've looked into already existing [plugins](https://github.com/xournalpp/xournalpp/blob/master/plugins/) and as far as I can tell all of them can either be invoked with a shortcut or through the menu `Plugin > Plugin-Name`.

3) How can I invoke a custom plugin through an icon from the toolbar. Ideally the `PEN`-icon? This would help with writing a plugin :)

**Comment by rolandlo** [comment]
Some answers:

1. Currently every icon can only be used once in the toolbar (including floating toolbox). PR #2735 attempts to get rid of this limitation.
2. Sounds like an interesting suggestion. However different pens would need different icons, otherwise it would be hard to keep them apart. 
3. Yes, this would help, but it is not possible yet. See 3 comments above.

**Comment by langfingaz** [comment]
Thanks for the quick reply.

> Currently every icon can only be used once in the toolbar (including floating toolbox). PR #2735 attempts to get rid of this limitation.

That sounds great! I'll have an eye on that PR.

**Comment by nicolae-stroncea** [comment]
Here is a possible implementation. Not sure how much effort it would require(seems like a lot), but leaving this here to generate ideas:

We add another option in "Preferences", which mimics the "Defaults" option that allows you to create a customized default tool.

1. User creates their own tool using same code and options as available in the "Defaults" category. So far everything is the same.
![image](https://user-images.githubusercontent.com/39338488/114811565-4e4b5f00-9d7c-11eb-9dd4-29a5a30538e4.png)
2. User writes the shortcut they want to trigger the tool. Probably needs to be validated.
3. User clicks "Create Tool".
* X++ then automatically generates an svg icon given user-selected options. Here is my bad drawing attempt for icons using all possible customizations available in the "Defaults" section.
![image](https://user-images.githubusercontent.com/39338488/114810987-38896a00-9d7b-11eb-8cfc-143686680c9d.png)
![image](https://user-images.githubusercontent.com/39338488/114811005-4212d200-9d7b-11eb-9ecb-cb0e729dbbcd.png)
![image](https://user-images.githubusercontent.com/39338488/114811057-640c5480-9d7b-11eb-9d60-8459389b6905.png)
* X++ automatically generates the plugin folder with the `.lua` and `.ini` files for the plugin which will define these settings.
* X++ saves the plugin and the svg icon in the appropriate folders.

**Comment by nicolae-stroncea** [comment]
Thinking more on it, most of the above (specifying the tool properties and the shortcut, SVG generation, Plugin code generation), could be created through another Lua plugin provided that:
* It is possible to build GUI's with Lua (I think I read plans somewhere for that, but not sure if it was implemented)
* X++ allows Plugins to now have a related icon, with the path specified in `.ini` for the plugin. Users can then place the icon anywhere they want on any toolbar and activate it by clicking or calling the shortcut for it.

**Comment by rolandlo** [comment]
@nicolae-stroncea GUI's in Lua can be created with the [`lua-lgi` package](https://github.com/pavouk/lgi). See the [MigrateFontSizes plugin](https://github.com/xournalpp/xournalpp/tree/master/plugins/MigrateFontSizes) and #2176 for some examples how to use it. The examples in the `samples/gtk-demo` folder that come with `lua-lgi` are also a good source to study.

**Comment by rolandlo** [comment]
See #4671 for a pull request implementing the feature.
