### ISSUE TITLE
Background color not applied to existing pages despite the page template configuration

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2437]
(Version of Xournalpp : xournalpp-1.1.0.dev-nightly.20201121-windows)

I open an existing document with several pages.
I choose a color for background (Menu : "Journal"->"Configure Page Template"-> "Background Color"), 
Then I choose in menu : "Journal"->"Paper Background"->"Apply to All pages".

Problem : Color is not applied to any page

**Comment by bhennion** [comment]
Duplicate fo #1782
