### ISSUE TITLE
Command line option --page not working in 1.1.0+dev

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#2445]
**Affects versions :**
 - OS: Linux, Windows 
- (Linux only) Desktop environment: X11
- Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.1.0+dev (at least from git commit 8afb3841 to the latest version)
 - Installation method: All of PPA, flatpak and building from source
**Describe the bug**
The command line options `-n` (in short) and `--page` (in long) for scrolling to the specified page do not work any more in version 1.1.0+dev. Simply no scroll is taking place.

**To Reproduce**
1. Create a multipage document, say `foo.xopp` with >2 pages
2. Run xournalpp with the --page option, e.g. `xournalpp --page=2 foo.xopp`
3. Observe that the document loads without scrolling to the 2nd page.

**Expected behavior**
I would expect scrolling to the specified page after the document has loaded.

**Additional context**
- In version 1.0.18 and 1.0.19 the options
`--page=2` or `--page 2` or `-n 2` work, the option `-n=2` does not (and probably is not supposed to work). 
In version 1.1.0+dev the page number is still correctly read with the former 3 options, but the scrolling does not take place.

- Even with working --page (or -n) option the page number is shifted. According to `xournalpp --help` the first page number should be 1, but it is 0 indeed. So `--page=2` scrolls to the 3rd page instead of the 2nd one. That should be corrected, too.

- The error seems to happen because of an invalid Metadata entry.

**Comment by rolandlo** [comment]
The bug comes from the change in file path handling. The two file paths are not the same in v1.1.0+dev:
![grafik](https://user-images.githubusercontent.com/40485433/100394581-eea71e00-303d-11eb-9544-97b479396774.png)

In version 1.0.x they are handled as strings and are considered equal (which they should be).

The comparison is made in `MetadataManager::getForFile`

@Febbe Can you take a look at it? Which path is wrong or what's the problem here?

**Comment by rolandlo** [comment]
That path in the files list has been constructed via
```cpp
entry.path = line
```
in `MetadataManager::loadMetadataFile`

where `line` corresponds to the line `"/home/roland/xournalpp-code-analysis/ann_06.xopp"` in the metadata file read via `getline(infile, line)`

The actual line in that metadata file reads:
`"/home/roland/xournalpp-code-analysis/ann_06.xopp"` 

It becomes the string variable:
`"\"/home/roland/xournalpp-code-analysis/ann_06.xopp\""`

If I remove the quotation marks in the metadata file (i.e. change`"/home/roland/xournalpp-code-analysis/ann_06.xopp"` 
 to `/home/roland/xournalpp-code-analysis/ann_06.xopp`) 
everything works.

So either the metadata should be stored without quotation marks (in `MetadataManager::storeMetadata`) or it should be read differently in `MetadataManager::loadMetadataFile`

**Comment by rolandlo** [comment]
I suggest replacing the line

https://github.com/xournalpp/xournalpp/blob/59f4f22a482b99801b286b4c784a8919373b9589/src/control/settings/MetadataManager.cpp#L193

by `out << m->path.u8string() << "\n"; `

Then the quotation marks are not stored in the metadata file and the path is read correctly, which makes the `--page` command line option work.

**Comment by Febbe** [comment]
Mhh I would first try to fix the read.
In should look like something like this:
`in >> m->path;`

**Comment by rolandlo** [comment]
> Mhh I would first try to fix the read.
> In should look like something like this:
> `in >> m->path;`

Thanks @Febbe, that works. See PR #2453, which fixes this issue.
