### ISSUE TITLE
Default Button Error

### ISSUE THREAD

**Issue by Wisehh** [xournalpp/xournalpp#2447]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11 
 - libgtk 3.24.23 
 - Version of Xournal++: 1.1.0+dev commit 59f4f22a
 - Manual build and AUR git package with yay

**Describe the bug**
Exactly the same that #2339 

**To Reproduce**
Just build xournalpp from masterbranch and try to use the default button tool.

**Comment by rolandlo** [comment]
PR  #2339 is not yet merged. That's why it doesn't work currently.
