### ISSUE TITLE
Command line option for selecting pages to export

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#2448]
How would you feel about a command line option (such as --export-pages="2-4,6-") to cherry pick which pages are exported when using --create-{img,pdf}?

It seems easy enough to implement (as the export jobs already support page ranges) and I am willing to do it. I'll open up a PR as soon as I have something sensible.

**Comment by rolandlo** [comment]
If you can do it, great!

**Comment by rolandlo** [comment]
This was solved in PR #2449
