### ISSUE TITLE
stylus buttons to select pen with specific color/thickness temporarily and not permanently

### ISSUE THREAD

**Issue by akoun** [xournalpp/xournalpp#2452]
When using the pen tool with a specific color/thickness config and using stylus buttton 2 or button 3 to select an alternative colour/thickness configuration this second configuration should be effective only as long as the button is pressed and once released we should revert to the previous pen configuration.

For example:
I'm using pen blue/medium/standard
pressing button 2 makes it pen green/thick/dashed
releasing the button takes me back to the pen blue/medium/standard

PS: the same goes for eraser and highlighter tools

**Comment by rolandlo** [comment]
@idotobi Will PR #2339 fix that?

**Comment by idotobi** [comment]
@rolandlo : Yes PR #2339 will fix that. (To my shame I think I introduced that strange behaviour when fixing another bug :sweat_smile: ).
