### ISSUE TITLE
Add "colour picker"

### ISSUE THREAD

**Issue by DavGatto** [xournalpp/xournalpp#2456]
I'm still using both Xournal and Xournal++, and the former has the "colour picker" tool in the custom colour selection box, which allows you to select a colour by clicking on any part of the picture that is coloured that way.
This feature comes in particularly handy when you have to wipe out something (usually dotted lines) from pdf modules you are annotating, and the paper colour is not white. It is also useful when you are making use of weird colours and want to reproduce them without copy-pasting the colour code.

**Comment by rolandlo** [comment]
Sounds useful to me, too. We use the GTK+ 3 color chooser, which does not have a pipette (color picker). The GTK+ 2 color chooser had one, it seems, see the first image on [this wikipedia page](https://en.wikipedia.org/wiki/Color_picker). So it's probably not going to be easy.

**Comment by rolandlo** [comment]
There is actually a pipette (color picker). When you choose the color (with the rectangle color button in the toolbar), press the + button to create a new color. Then you will have this dialog, which has a pipette and serves to pick a color from any place on the screen:
![grafik](https://user-images.githubusercontent.com/40485433/100538279-17423a00-322f-11eb-832f-9e5efc7324bc.png)

So I will close this issue.

**Comment by DavGatto** [comment]
Hi,
it does not show up for me!
![image](https://user-images.githubusercontent.com/7951448/100628163-340e6880-3328-11eb-9230-4407ade19cbc.png)

I'm running Xournal++ 1.0.19 on Ubuntucinnamon 20.04 LTS (which is of course a flavour of Ubuntu 20.04 LTS, using Cinnamon as default DM).

**Comment by ahmedelq** [comment]
Any updates on this? Color picker isn't there as of version 1.2.2 (Dec 5 2023)
![image](https://github.com/xournalpp/xournalpp/assets/11134754/c9fd4e18-5df3-48f0-a035-d81bb401652b)

**Comment by rolandlo** [comment]
That's nothing we can fix (except migrating to Gtk 4 I guess). See https://gitlab.gnome.org/GNOME/gtk/-/issues/5135
