### ISSUE TITLE
Resizing on the diagonal line leads glitches

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2460]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Manjaro KDE
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
     - 3.24.23
 - Version of Xournal++: commit 639cd78e
 - Installation method: AUR-git

**Describe the bug**
![Screen Capture_select-area_20201129131508](https://user-images.githubusercontent.com/43318127/100541589-dea95d00-323c-11eb-82d4-7347d80817c7.gif)

**Additional context**
I use a Wacom Intuos M, but same issue using the mouse.

**Comment by rolandlo** [comment]
I can't reproduce this. Have you experienced that before?

**Comment by ericschdt** [comment]
No, I didn't, it's new to me. If you cannot reproduce it will be hard to debug it I'm afraid.

**Comment by rolandlo** [comment]
So it happens for the lower left corner and does not happen for the other 3 corners?

**Comment by ericschdt** [comment]
> So it happens for the lower left corner and does not happen for the other 3 corners?

Right, that's what I tried to say. :)

**Comment by rolandlo** [comment]
Ok, then I may be able to suggest a fix, by making the behavior of the bottom left corner identical to the behavior of the top right corner (just with x and y coordinates and width and height switched). I have noticed a minor difference, which may or may not cause the problem observed by you. It will require your help to test out the changes though. Do you know how to check out a Pull Request? (c.f. #2444, where I explained how to do it).

**Comment by ericschdt** [comment]
> Ok, then I may be able to suggest a fix

Sounds great!

> Do you know how to check out a Pull Request?

You push a branch with the fix and I switch to it? Sure :)

**Comment by rolandlo** [comment]
Hmm, I can reproduce it now as well. Just had to turn the snapping to grid off.

**Comment by rolandlo** [comment]
Found it! PR #2463 will fix it.

**Comment by ericschdt** [comment]
Can confirm, fixed it for me. Thanks so much!

**Comment by Technius** [comment]
Seems like this was a regression introduced by #2011, so it doesn't affect the 1.0.x versions.
