### ISSUE TITLE
The name "Draw spline" is missing (in the "Tools" menu) before the radio button

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2461]
Xournalpp version : xournalpp-1.1.0.dev-nightly.20201124-windows

In the "Tools" menu, the radio button for drawing splines exists, but the name "Draw Spline" does not appear in front of the radio button

**Comment by rolandlo** [comment]
Thanks for reporting. This is fixed with PR #2462.

**Comment by MichelReims** [comment]
Thanks.
