### ISSUE TITLE
Invalid stroke width or image dimensions leading to disappearing selections and missing parts in pdf export

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#2464]
**Affects versions :**
 - OS: doesn't matter, I guess
  - Which version of libgtk do you use: doesn't matter, I guess
 - Version of Xournal++: 1.0.18, 1.0.19, 1.1.0+dev (possibly others)
 - Installation method: doesn't matter, I guess

**Describe the bug**
Xournal++ sometimes stores `-NaN` as a stroke width (see #2372, #2168), which causes trouble using the selection tools (parts of the document disappear, the cursor update looks flawed, and exporting the pdf can make Xournal++ crash

Xournal++ also sometimes stores images with 0 width and height (and 0's as x and y-offsets) and strokes with all 0's as width, see [this file](https://files.gitter.im/5647729516b6c7089cbab6bf/UfoH/aula11.xopp) reported on the Gitter channel, which leads to similar misbehavior.

**To Reproduce**
It's not clear yet, how these strokes and images are created. Once they are created it's easy to reproduce following the steps described in #2372. 

**Expected behavior**
Width `-NaN` should not be possible. Such strokes should get filtered out immediately when they are created. Similarly for strokes with all 0's as width and images with 0 width and/or height. 

**Screenshots of Problem**
See #2372. 

**Additional context**
The problem with images of zero width and height may be related to undo operation. If you insert an image and undo its insertion, you will see the edit selection at the top left corner of the document with 0 width and height. I couldn't reproduce getting it saved in the xopp-file though.

**Comment by Technius** [comment]
Likely source is floating point rounding errors from scaling operations.

**Comment by BMicraft** [comment]
A college just sent me a broken file (image dimensions = 0) and I involuntarily created another `-NaN` stroke a couple hours ago. This may be more even more common than the few bug reports lead us to believe?

It seems to me that it is particularly likely for something to go wrong when grid snapping is in use, but that's just a thought.
Maybe publish a quick and dirty fix that just removes invalid xml elements when opening or saving?

**Comment by Technius** [comment]
We should probably add a build option that, when enabled, will warn/log whenever NaN / 0 occurs. This would make it easier to debug at least. 

> Maybe publish a quick and dirty fix for stable that just removes invalid xml elements when opening or saving?

It would be frustrating if things disappear on export, but I suppose it's better than crashing or whatever.

**Comment by BMicraft** [comment]
> It would be frustrating if things disappear on export, but I suppose it's better than crashing or whatever.

Xournal could also just restore invalid stroke widths to 1 and invalid images to default dimensions?

**Comment by PaulCombal** [comment]
Still occurring in 1.0.20 (see #2556 )

**Comment by tattsan** [comment]
> Xournal could also just restore invalid stroke widths to 1 and invalid images to default dimensions?

There was a PR with a similar idea: #2125 , which is now closed.
This PR was intended to debug another issue,  but I usually build Xpp with this patch
in order to detect unintended strokes.

**Comment by rolandlo** [comment]
I found a reproducible way to produce image width zero width and height or with NaN's. This is related to paste action undo/redo #2740 .

To reproduce:

1. select the image tool, click on the document and select an image to get it inserted into the document
2. select the image with the selection tool (select rectangle, for instance)
3. Press CTRL+C and CTRL+V to copy and paste the image at a different location
4. Press CTRL+Z (or use the undo button) and save the document.
5. You can check (by unzipping the document and reading it in XML format) that you still have two images, but the second one of them has all rectangle coordinates equal to zero (in particular height and width 0)
  Like this: `<image left="0.00000000" top="0.00000000" right="0.00000000" bottom="0.00000000">`
6. Press CTRL+Y (or use the redo button) and save the document.
7. You can check that you have two images and the second one has NaN's as rectangle coordinates. 
   Like this: `<image left="-nan" top="-nan" right="-nan" bottom="-nan">`

**Comment by rolandlo** [comment]
I can now see from where these zeroes and Nan's come. When an object is pasted, not only an `InsertUndoAction` is added, but also a `ScaleUndoAction`. The `ScaleUndoAction` comes from `selection->mouseUp` which calls `EditSelection::updateContent`, which has the lines
```c++
    double fx = snappedBounds.width / this->lastSnappedBounds.width;
    double fy = snappedBounds.height / this->lastSnappedBounds.height;
```
in it. The `lastSnappedBounds` are all 0 in this situation, that`s how we get the NaN`s. 
I will try to fix the problem.

**Comment by rolandlo** [comment]
A PR (#2857) is now available to fix this ugly bug.
