### ISSUE TITLE
Xournal++ LaTeX does not allow for multiline inputs

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2466]
I'm on Windows 10, using xournal++ 1.0.19 with MikTeX. 
I'm trying to add a multiline TeX comment on a PDF, but when I try this: (B, D) \cup (F,H), \text{as since $g \prime(x)$ is the rate of change}\\
\text{of }

It does not split the input into two lines, like it's supposed to, but instead ignores the \\.

**Comment by rolandlo** [comment]
You need to write two backslashes instead of one, don't you? At least in version 1.1.0+dev it works.

**Comment by DUOLabs333** [comment]
@rolandlo I did put two slashes, GitHub must have treated the other slash as an escape character.

**Comment by rolandlo** [comment]
OK. Maybe allowing for line breaks was only introduced with the LaTeX enhancements in version 1.1.0+dev. Not sure. 
You could work around it using the `aligned` environment:
```
\begin{aligned}&(B, D) \cup (F,H), \text{as since $g \prime(x)$ is the rate of change} \\
&\text{of }\end{aligned}
```

**Comment by DUOLabs333** [comment]
@rolandlo Ok. Is there a way to get this dev version?

**Comment by rolandlo** [comment]
Sure, use the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly).

**Comment by DUOLabs333** [comment]
@rolandlo Ok. I got the dev version, but what is a "global latex template file"?

**Comment by rolandlo** [comment]
The global template file is a file where you can define your includes (via `usepackage`) and macros. It should be in the resource folder. If it is missing or you don't find it, use [this file](https://github.com/xournalpp/xournalpp/blob/master/resources/default_template.tex).

**Comment by DUOLabs333** [comment]
@rolandlo It worked! Thanks so much.
