### ISSUE TITLE
Laggy/delayed stylus input while drawing/writing

### ISSUE THREAD

**Issue by chron-isch** [xournalpp/xournalpp#2473]
**Affects versions :**
 - OS: ArchLinux/Sway (Wayland)
 - Version of Xournal++:  
```
xournal++ 1.1.0+dev 
└──libgtk: 3.24.2
```
- Hardware: MS Surface Go + Stylus

**Describe the bug**
Anything being drawn with stylus is laggy/takes a long time to appear since 1.1.0-dev, used to work in 1.0.19 (see screenshots). It seems like input only gets rendered when you stop writing for a second or two.

**Screenshots of Problem**
Working in 1.0.19:
![xournalpp1 0 19](https://user-images.githubusercontent.com/1332352/100742511-32ea4380-33db-11eb-81f6-5f5bf89ca7e3.gif)

Current behaviour in 1.1.0-dev:
![xournalpp1 1 0-dev](https://user-images.githubusercontent.com/1332352/100742563-439ab980-33db-11eb-806a-534ac6f2e303.gif)

If you need further information I'm happy to help. I hope the gifs are good enough otherwise i'll redo them with a different pointer/highlighted pointer.

**Comment by LittleHuba** [comment]
Do you know your way around git? If yes could you try to find out which commit caused the issue?

**Comment by personalizedrefrigerator** [comment]
Does focusing on some other window, then focusing the Xournalpp window cause the missing strokes to appear? If so, I am experiencing the same issue (with touchscreen drawing).

**Comment by chron-isch** [comment]
A little, I'll give it a try.

**Comment by chron-isch** [comment]
I spend a couple of hours bisecting this (not fun on a Pentium Gold!), the bug was introduced by commit 534a45944e9e010d63d66170c7cf9a6a9ea19c94.

**Comment by personalizedrefrigerator** [comment]
PR #2339 might fix this!

**Comment by chron-isch** [comment]
@personalizedrefrigerator It doesn't just fix the issue, it actually makes writing feel better/more responsive than before! Thanks!

**Comment by personalizedrefrigerator** [comment]
@idotobi Can you link this issue to your PR (#2339)?
@chron-isch I would suggest waiting until #2339 is merged.

**Comment by idotobi** [comment]
> @idotobi Can you link this issue to your PR (#2339)?
> @chron-isch I would suggest waiting until #2339 is merged.

@personalizedrefrigerator : Sure. Will Do. 

> @personalizedrefrigerator It doesn't just fix the issue, it actually makes writing feel better/more responsive than before! Thanks!

Thanks for the feedback :pray:
