### ISSUE TITLE
Merging xopp files through the command line

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2474]
I am sometimes in the situation where I want to add a PDF page(s) to my existing xopp file. According to [here](https://github.com/xournalpp/xournalpp/issues/1956), this is being worked for the GUI, but in the meantime, is there something similar for the command line where I can convert a PDF to xopp, then merge the two xopp files together.

**Comment by friciwolf** [comment]
Hi!
I've faced the same issue as a student, as my teacher extends his previous lecture notes with the new material before every new lecture, so I've written a small python script ([https://github.com/friciwolf/XournalppUtils/blob/master/XournalppUtils.py](https://github.com/friciwolf/XournalppUtils/blob/master/XournalppUtils.py)), which merges fileN, fileN-1.... file2 into file1, and creates an output file.
You can invoke it via:
```
Xournalpputils.py file1 file2 file3 output.xopp
```
It only covers my primitive needs; as I'm not a python expert either, it can contain unwanted bugs too (like, sometimes gzip cannot extract the .xopp file). But it works, if a pdf gets new pages added and there are 2 .xopp files (one with the old pdf background and one with the new), it can merge both into one. Requirements are only gzip and python.

Hope it helps and covers some of your needs :)

**Comment by DUOLabs333** [comment]
@friciwolf This looks perfect, but I can't seem to find gzip to download for Windows.

**Comment by DUOLabs333** [comment]
@friciwolf This looks promising (may fix it up, and put a nice gui in front), but when I tried a test, it told me i needed "cp". What is that?

**Comment by DUOLabs333** [comment]
@friciwolf This seems to be broken on Windows. Could you tell me how you did it, so I can rewrite it with Windows in mind?

**Comment by rolandlo** [comment]
> But it works, if a pdf gets new pages added and there are 2 .xopp files (one with the old pdf background and one with the new), it can merge both into one. Requirements are only gzip and python.

In case of pdf backgrounds that get updated with new pages, there is a simpler solution: Replace the old pdf file with the new one (physically), reload your document in Xournal++ and choose "Append New Pdf Pages" from the menubar (menu journal). This is only in version 1.1.0+dev though.

**Comment by friciwolf** [comment]
@DUOLabs333:
The script basically copies ``fileN.xopp``` (```cp``` is the copy command on linux) the  and renames it to ```fileN.xml.gzip```, then calls gzip the extract the resulting files. It then reads the extracted xmls and merges the first layer in each file with that of file1.
On Windows, you might need to call the equivalent commands of cp, mv and gzip, and the rest should work as on linux.
Replacing background files didn't work previously, so that's why I did that small workaround...

**Comment by MrPancakes39** [comment]
I hope the native app in future has the feature of merging two xopp files together without the need for this python script. (But it's great thanks!)

**Comment by MrPancakes39** [comment]
The python script seems to stopped working so I created a webapp for easy of merging files.
WebApp: [xopp-merger-app](https://xopp-merger-salmannhassan39.koyeb.app/)
Repo: [xopp-merger-app repo](https://github.com/MrPancakes39/xopp-merger-app)

**Comment by friciwolf** [comment]
Hi @MrPancakes39! Could you report on the issue you're getting? There should not be any reason why the script should have stopped working as there has not been any release update since February (version 1.1.1); the script still does the job on my machine. Could you also elaborate on the platform and environment you're using?

**Comment by MrPancakes39** [comment]
Sure thing @friciwolf currently it's night time on my side on the world so I'll try it asap tomorrow, thanks for understanding.

> Could you also elaborate on the platform and environment you're using?

I'm using EndeavorOS Linux.

**Comment by MrPancakes39** [comment]
@friciwolf Here is my output:
```console
$ ./XournalppUtils.py notebook1.xopp notebook2.xopp output2.xopp
Unpacking notebook1.xml.gz...

Unpacking notebook2.xml.gz...

Traceback (most recent call last):
  File "/home/sal/Desktop/XournalppUtils.py", line 51, in <module>
    pageNb = elements[0].attrib["pageno"]
KeyError: 'pageno'
```
Not sure what's causing the issue tbh.

Also you need to have better parsing of arguments since `./XournalppUtils.py ./notebook1.xopp ./notebook2.xopp ./output2.xopp` doesn't work. (Not judging more of recommendation.)

**Comment by friciwolf** [comment]
Hm. Could you provide the files and the backgrounds you get these issues with? It's weird because it seems the the xopp-files do not contain any information about the page number.
Regarding the usability: yeah, that's right. I might look into that :D

**Comment by MrPancakes39** [comment]
> Could you provide the files and the backgrounds you get these issues with?

Sure thing! I just tried a simple example nothing important really.
[example.zip](https://github.com/xournalpp/xournalpp/files/9984682/example.zip)

**Comment by friciwolf** [comment]
Thanks, I see now where the issue is! As indicated in the [source](https://github.com/friciwolf/XournalppUtils/blob/master/XournalppUtils.py#L10), the python script only supports 1 layers files.
I might look into the script and fix the bug later; until then, using your site or a single layer should both work for everyone else.

**Comment by MrPancakes39** [comment]
@friciwolf Sorry, I did send you files with multiple layers but here is an example of files with only one layer failing.

[Example2.zip](https://github.com/xournalpp/xournalpp/files/9997496/Example2.zip)

**Comment by friciwolf** [comment]
No worries, this makes the issue then crystal clear to me. The script first looks for the ```pagenb``` attributes in the ```<background>```  tags (which define a "page" for the script) which are missing for files with built-in background layouts/models (i.e. those without a pdf background, like the attached files). In other words, the script should not skip the <page> tags to work properly.
Honestly, I should just rewrite it in a complete all-layer-, all-background-supporting and platform-independent way with much cleaner code.

I really appreciate your work and feedback btw.! I'll see what I can do with the "CLI/offline" solution (unless we want to wrap your solution in an electron app, making it nice, easy-to-use and user-friendly).

**Comment by MrPancakes39** [comment]
Here is the [xopp-merger-cli](https://github.com/MrPancakes39/xopp-merger-cli) tool written in Rust as mentioned.

**Comment by AyushmaanAggarwal** [comment]
I've heavily modified [friciwolf](https://github.com/friciwolf)'s code so that I can merge all the .xopp files in a folder in alphabetical order. Since each layer in the xml file is inside each page, this should work with multiple layers and should be pretty easy to hack and modify to your needs since it is written in python. 

You can run it using the following line where input folder can be `.` for the current directory
``python3 xournalppMergeFolder.py input_folder output_file ``

Here's the modified file [xournalppMergeFolder.py](https://github.com/AyushmaanAggarwal/XournalppUtils/blob/master/xournalppMergeFolder.py).
