### ISSUE TITLE
Trying to save a .xopp file as "a.b.xopp" saves it as "a.xopp"

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2475]
I am on Windows 10, with Xournal++ 1.1.0 (dev version). When trying to save a file as "a.b.xopp", it instead saves it as "a.xopp". This seems to be because Xournal automatically cuts off everything after the period. This is relatively benign (easily fixed by just cutting off after the last period), but is still a minor inconvenience.

**Comment by rolandlo** [comment]
Good catch. On Linux it works normally, by the way.
