### ISSUE TITLE
Separate Touchscreen and Mouse Inputs

### ISSUE THREAD

**Issue by xx299x** [xournalpp/xournalpp#2495]
I have a touchscreen that I want to use separately from my main display. Now when I use my touchscreen for example this app, whenever I draw a line to show it my mouse moves from my main display. I wasn't my mouse to stay on my main display. 

I already searched for this problem on all websites. M.S Edge can separate Touchscreen and Mouse Inputs.

I've found some useful ways.

https://stackoverflow.com/questions/24570410/disable-cursor-moving-from-touch-input
https://stackoverflow.com/questions/47683618/prevent-touch-input-moving-mouse-cursor-on-windows

Thank you!

**Comment by LittleHuba** [comment]
This is an issue of GTK and not Xournal++. Please head over to [their issue tracker](https://gitlab.gnome.org/GNOME/gtk/-/issues) and create the ticket over there.
