### ISSUE TITLE
Explain the "merge button events with stylus tip events" setting

### ISSUE THREAD

**Issue by piegamesde** [xournalpp/xournalpp#2496]
**Is your feature request related to a problem? Please describe.**
I didn't know it existed and I had to enable it and without I had a pretty bad time using Xournal (see #2470). The hint "(Check this if `xsetwacom get *deviceId* TabletPCButton` resurns `on`)" is pretty useless, because a) not all tablets use `xsetwacom` and b) `xsetwacom` does not work on Wayland. This gives the false impression that the setting should be off.

**Describe the solution you'd like**
Add a description of what it does. Okay, its title already does this, but from that description I can't deduce what it *means*.

**Comment by LittleHuba** [comment]
From the technical perspective we just delay stylus button presses until the tip touches the screen. Some devices require this setting and others don't. Some devices support either way some need a specific setting. The situation is not fully clear unfortunately... 

Best would be if you as a user try to describe it. For us this is hard as with the technical knowledge we are prone to describe it in a way that makes no sense to the normal user of Xournal++ or give them details they don't really need (see above).

**Comment by piegamesde** [comment]
> as with the technical knowledge we are prone to describe it in a way that makes no sense to the normal user

Yes, once I know what the setting does I can see where its current description comes from :D

> Best would be if you as a user try to describe it.

Okay, I'll try. From my perspective and with my setup, the setting behaves like this:

- Off: Pressing a stylus button switches to that tool, but I still need to use the pen tip to actually do something with it.
- On: Pressing a stylus button directly uses the bound tool.

Assuming this generalizes to other users, I consider the following information relevant to know:

- This setting is a workaround some hardware quirks and may be needed depending on the setup
- Toggle this if tools mapped onto stylus buttons don't behave "correctly"
- If you can't tell any difference, leave it off

**Comment by Zamundaaa** [comment]
> Okay, I'll try. From my perspective and with my setup, the setting behaves like this:
>Off: Pressing a stylus button switches to that tool, but I still need to use the pen tip to actually do something with it.
>On: Pressing a stylus button directly uses the bound tool.

Hmm, I'm having the exact opposite effect (on Plasma Wayland, with the latest master).
Turning it on made it work as expected (I have to touch down to use the tool) while having it off makes it trigger the tool when hovering but once I touch the tablet with the pen it starts drawing again.

**Comment by LittleHuba** [comment]
The thing is this setting is only half of the deal. The other half is how your driver provides the events of the input device. Both halfs have to match. Your experience is what happens if they don't.

**Comment by piegamesde** [comment]
So ideally, we'd be able to detect what the driver does in order to provide a consistent setting about that behavior.

**Comment by LittleHuba** [comment]
Ideally that would be the case. But this would require linking against Wacom library (Which is a dependeny I'd like to not have) or parse some console output manually (OS dependency hard to manage for us). 

Additionally this approach only works for Linux. I have no idea how to get that data on Windows or MAC.

**Comment by Technius** [comment]
An explanation of the "Merge button events with stylus tip events" setting [has been added](https://github.com/xournalpp/xournalpp.github.io/pull/82) to the official guide: https://xournalpp.github.io/guide/config/preferences/#input-options

If you find an issue with this description or would like to suggest improvements, feel free to open an issue or PR here: https://github.com/xournalpp/xournalpp.github.io
