### ISSUE TITLE
feature request: key shortcut for next and previous page

### ISSUE THREAD

**Issue by sevku** [xournalpp/xournalpp#250]
There should be a key shortcut for next and previous page. My suggestion: left and right arrow.

**Comment by andreasb242** [comment]
Already done, PageUp and PageDown are working...

**Comment by sevku** [comment]
It's been a while since I've posted this. In the meantime I am using a laptop with better positioning of the PageUp and PageDown keys, and therefore this wouldn't be an issue for me anymore. But most keyboards have their key down and up key s positioned in a bad positioned and therefore, it would be helpful if key left and right would have the same functionality. That's probably what I intended with this issue.
