### ISSUE TITLE
System font misdetected on Fedora Linux

### ISSUE THREAD

**Issue by nekohayo** [xournalpp/xournalpp#2506]
With Xournal 1.0.19 from the Fedora 33 distro packages, running under a GNOME 3.38 Xorg/X11 session, Xournal's toolbar font button defaults to a nonexistent/nonsensical font family and size:

![Screenshot from 2020-12-07 23-10-32](https://user-images.githubusercontent.com/479401/101439076-c0e59300-38e1-11eb-860f-06b729c11b0b.png)

On the terminal, I see:

```Gtk-WARNING **: 22:13:00.142: Theme parsing error: <data>:1:22: Junk at end of value for font-family```

And yet, in dconf-editor, I see that the value of org.gnome.desktop.interface's "document-font-name" property is 'Cantarell 11' (just like org.gnome.desktop.interface's "font-name" property), which is the default, and nothing unusual...

**Comment by london111** [comment]
I have the same issue on ubuntu 20.04 (using xmonad) and xournalpp 1.0.20.

**Comment by Photon89** [comment]
Manjaro Linux, and version 1.0.20-hotfix here, same problem.

**Comment by rolandlo** [comment]
This may have been fixed by PR #2620 in the latest master. You can try it out via the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) of version 1.1.0+dev.

**Comment by Photon89** [comment]
It's fixed for me in the latest git commit (g2123d2f2), thanks!

**Comment by rolandlo** [comment]
I will close this issue then. If anyone experiences the problem in version 1.1.0+dev, please comment/reopen.
