### ISSUE TITLE
Instant maximum zoom when pinching with zoom gestures disabled

### ISSUE THREAD

**Issue by eliasrg** [xournalpp/xournalpp#2509]
**Affects versions :**
 - OS: Manjaro Linux
 - Version of Xournal++: 1.1.0+dev (5cf01b77)

**Describe the bug**
When zoom gestures are disabled, pinching with two fingers instantly zooms in to 700%.

**To Reproduce**
1. Start Xournal++.
2. Make sure that "Enable zoom gestures" is unticked.
3. Turn off "Zoom fit to screen".
4. Pinch with two fingers on the screen.

**Input Logs**
Input logs attached according to https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs.
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5663227/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5663226/debug_gdk_input.log)

**Expected behavior**
Nothing. Zoom gestures are turned off, so the zoom level should stay fixed even if I (accidentally) put two fingers on the screen.

**Screenshots of Problem**
Below is a video showing the instant zooming when I pinch.
![zoom-snap](https://user-images.githubusercontent.com/7657466/101567685-8eb35e80-39d1-11eb-89fd-d0684f7572b0.gif)

**Additional context**
I frequently trigger this by accident while writing. When I press the "Zoom to 100%" button to return to normal zoom, the document also scrolls back to page 1, which is of course adds to the frustration.

In case it is relevant, the "new input system" is enabled.

**Comment by personalizedrefrigerator** [comment]
#2435 should also fix this...
