### ISSUE TITLE
One more warning that I receive on startup of the installed version:

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#2513]
One more warning that I receive on startup of the installed version:
![grafik](https://user-images.githubusercontent.com/40485433/100267892-816b8e00-2f54-11eb-882f-88f6fc86c72f.png)

Moreover if I open a file with the installed version from the MinGW command line or via double clicking the file in the file manager I get this window:
![grafik](https://user-images.githubusercontent.com/40485433/100268782-ce039900-2f55-11eb-8c56-4bfdbce39010.png)
After clicking OK, it loads normally. 

Similarly if I use the -p option to export to pdf or the -i option to export as an image I get three debug info windows, that I must close before the export is made. Exporting works.

**Those debug windows should not appear** 

If I use the --name option like ` bin/xournalpp.exe --name="MyTestName"`
(which I expected to only change the window title) I get an error message like this:

![grafik](https://user-images.githubusercontent.com/40485433/100274960-8e41af00-2f5f-11eb-9720-ea4f33f0b0e3.png)

**This warning should be an information. When no settings exist they must be created obviously.**

_Originally posted by @rolandlo in https://github.com/xournalpp/xournalpp/issues/2252#issuecomment-733918333_

**Comment by rolandlo** [comment]
> This warning should be an information. When no settings exist they must be created obviously.

I don't understand why the `settings.xml` file is searched in the subdirectory indicated by the `--name` parameter I pass to Xournal++. Shouldn't this parameter only change the window title, not the directory where settings (and other things) are searched for?

**Comment by Febbe** [comment]
This will be fixed by my PR. I already changed the usage of the program name to the hard coded string "xournalpp"

**Comment by Febbe** [comment]
Probably, unfortunately I did not linked the PR. The current master executed on windows only has the gdbus problem, but that's nothing problematic since the GTK features reliingbon gdbus are not supported anyways.
