### ISSUE TITLE
Stroke recognizer: minimum feature size

### ISSUE THREAD

**Issue by piegamesde** [xournalpp/xournalpp#2519]
**Is your feature request related to a problem? Please describe.**
I love the stroke recognizer, I have it almost always enabled and it works fairly well for me. However, when writing normally, it sometimes recognizes small lines or dots (mostly affecting the 'i', but also 't' and 'l').

**Describe the solution you'd like**
This is only a minor nuisance, but I think it could easily be fixed by only recognizing strokes larger than a certain size.

**Describe alternatives you've considered**
I don't know how to formally specify "small" in this context. Also maybe one could tweak the recognition algorithm parameters based on the feature size (different thresholds for different line lenghts or such).

**Additional context**
Related: #2275 about some other stroke recognizer improvements.

**Comment by rolandlo** [comment]
Closing this issue in favor of the duplicate #2531
