### ISSUE TITLE
Closing then reopening file removes all line breaks in "edit LaTeX" mode

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2526]
I'm using Windows 10 and Xournal 1.1.0. When I add LaTeX annotations, I usually add line breaks to the input (though not the actual output), so when I'm typing, I don't have to edit one run-on line. However, when I close the file, then reopen it, all those line breaks are removed, so I have to put them back in all over again. I can't tell if this is expected behavior or not though.

**Comment by rolandlo** [comment]
I can reproduce it on Linux as well. Looks like a (minor) bug.

**Comment by DUOLabs333** [comment]
@rolandlo Oh, ok. I thought this was one of those "it's not a bug, it's a feature" type of things.
