### ISSUE TITLE
Minimum stroke distance for shape recognizer

### ISSUE THREAD

**Issue by fallingcats** [xournalpp/xournalpp#2531]
**Is your feature request related to a problem? Please describe.**
Block shape recognizer for strokes that don't exceed some minimum of length, so that handwriting does not get messed up.

**Describe the solution you'd like**
It would probably be best to have a setting to change the minimum distance in Drawing Area. A sane default could be 10mm (or two boxes on graph paper), depending on your size of handwriting.

**Describe alternatives you've considered**
A workaround would be to disable grid snapping and shape recognizer with snapping for recognized shapes, but I kind of need that because I can't for the life of me draw straight line without them. I also increased the grid snapping distance to 0.50 because I could not get that to work for long strokes otherwise, but that makes the whole problem even worse.

**Additional context**
I regularly use Xournal++ for math and engineering homework where I need to write fractions or do simple drawings that greatly benefit from shape recognizer, but I just cant keep it turned on currently.

**Comment by BMicraft** [comment]
I tried so hard not to make this a duplicate but somehow I missed the other issue.
Oh well...

**Comment by piegamesde** [comment]
@BMicraft I thought the same until I realized that *this one* is the actual duplicate ^^
