### ISSUE TITLE
Stylus button causes CRASH if toolbar doesn't contain COLOR_SELECT.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#2533]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11
 - libgtk: 3.24.24
 - Version of Xournal++: 1.1.0+dev ( 7ab24766206264c179d0a1e405cb2c1d43c7e83c )
 - Installation method: build from source

**Describe the bug**
Using stylus button will cause crash if toolbar doesn't contain COLOR_SELECT.

**To Reproduce**

1. Edit toolbar.ini and create an item **without COLOR_SELECT** .

```
[Crash Test]
toolbarRight1=COLOR(0x3333cc)
name=Crash Test
```
2. Start xournalpp.
3. Configure stylus button1 to invoke eraser tool.
4. Select View -> Toolbars -> Crash Test
5. **Exit xournalpp, and restart the app**
6. Use stylus button1.

then the app crashes.

**Additional context**
If we add COLOR_SELECT, the app doesn't crash.
```
[Crash Test]
toolbarRight1=COLOR(0x3333cc),COLOR_SELECT
name=Crash Test
```

**Comment by tattsan** [comment]
This is a regression with the commit f092d02bdf8333408d1acbc7f007314c088f263b .

**Comment by idotobi** [comment]
@tattsan : Thank you again for finding my mistakes :pray: 

The linked PR (#2537 ) should fix it.

**Comment by tattsan** [comment]
I've confirmed the bug has been fixed. I will close this issue.

**Comment by idotobi** [comment]
@tattsan :  I'd leave the issue still open until it's merged, but thank you for confirming.
