### ISSUE TITLE
Regression: Xournal++ forgets pen options

### ISSUE THREAD

**Issue by BMicraft** [xournalpp/xournalpp#2535]
**Affects versions :**
 - Version of Xournal++:
    the problem occurs in 7ab24766206264c179d0a1e405cb2c1d43c7e83c
    It was working fine in ce4a13a0d0ca6aeb5456daaef782e0167a19fc1e
 - OS: Arch Linux (5.4.82-1-lts)
 - (Linux only) Desktop environment: KDE Plasma 5.20.4 on X11
 - Which version of libgtk do you use
     3.24.24
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
     Arch Linux PKGBUILD with custom release.

**Describe the bug**
Xournalpp always starts up with a black pen of small size. I don't know whether xournalpp previously remebered that per document or globally, but is does not seem to be saved anywhere anymore.
Quick edit: It also forgets shape settings like which shape was selected and whether it was enabled.

**To Reproduce**
1. Change the pen to a color != black or a size > small, or enable a shape tool
2. Save doc and close xournal
3. Open the same doc. 

**Expected behavior**
I would expect Xournalpp to behave like it did previously and remember my pen settings.

**Comment by tattsan** [comment]
It seems to be fixed by PR #2530 .

**Comment by BMicraft** [comment]
I'm not sure how I would go about testing this pr, I will try it and report back once it reaches master

**Comment by idotobi** [comment]
@BMicraft : This was introduced by my code changes in fea6d9eb28e18411defda11267cfe23ce68ce56b.
Basically what changed was that the default Tool is now always used at startup. But I can see how this would break some workflows.

The fix is quite small I'm currently checking if it works.

**Comment by rolandlo** [comment]
The same thing seems to happen after opening and closing the preferences.

**Comment by idotobi** [comment]
@rolandlo : Yes that's because of the same two code lines.

**Comment by BMicraft** [comment]
> @BMicraft : This was introduced by my code changes in [fea6d9e](https://github.com/xournalpp/xournalpp/commit/fea6d9eb28e18411defda11267cfe23ce68ce56b).
> Basically what changed was that the default Tool is now always used at startup. But I can see how this would break some workflows.
> 
> The fix is quite small I'm currently checking if it works.

Well that certainly explains it. Maybe initially set the default to what was used before that fix was there?

**Comment by idotobi** [comment]
Yes exactly :+1: . You can already check it out it in #2536.

**Comment by BMicraft** [comment]
> Yes exactly +1 . You can already check it out it in #2536.

Well, that was certainly quick. I still don't know how to build a pull request, my PKGBUILD only lets me give it a commit from master...
I'm in no hurry to fix that though, I guess I'll just wait until it lands in master
