### ISSUE TITLE
Ctrl+Z doesn't undo in "Add/Edit TeX"

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2542]
I use Windows 10, with version 1.1.0. When adding or editing TeX on a document, I tried to do Ctrl+Z to undo (and similarly, Ctrl+Shift+Z to redo) in the text box, but nothing happened.

**Comment by rolandlo** [comment]
So what would you expect to happen?

**Comment by DUOLabs333** [comment]
@rolandlo I would have expected it to undo the last edit, similar to most text boxes in browsers and word processing systems.

**Comment by rolandlo** [comment]
@DUOLabs333 OK, that behavior, which would be the same as for Text elements, makes sense. There are no Undo/Redo actions implemented for the LaTeX editor, but it shouldn't be that hard. It's a enhancement what you suggest.
