### ISSUE TITLE
Clang format inconsistency

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#2544]
**Affects versions :**
master

**Describe the bug**

The [pipeline clang format test asks for](https://dev.azure.com/xournalpp/xournalpp/_build/results?buildId=8262&view=logs&j=8af2c752-b8c3-5474-5b0a-7b1f58b7bf90&t=0928bceb-a691-5a8f-98f6-852338e7281a&l=30)

```
diff` --git a/src/control/XournalMain.cpp b/src/control/XournalMain.cpp
index 2c648d4f..2c252a93 100644
--- a/src/control/XournalMain.cpp
+++ b/src/control/XournalMain.cpp
@@ -354,7 +354,7 @@ struct XournalMainPrivate {
     XournalMainPrivate() = default;
     XournalMainPrivate(XournalMainPrivate&&) = delete;
     XournalMainPrivate(XournalMainPrivate const&) = delete;
-    auto operator=(XournalMainPrivate&&) -> XournalMainPrivate = delete;
+    auto operator=(XournalMainPrivate &&) -> XournalMainPrivate = delete;
     auto operator=(XournalMainPrivate const&) -> XournalMainPrivate = delete;
```

while either a ```git-clang-format``` or a  ```git --no-pager diff -U0 HEAD -- '*.cpp' '*.c' '*.h' '*.hpp' | perl azure-pipelines/util/format_diff_lines.pl``` generates

```
diff --git a/src/control/XournalMain.cpp b/src/control/XournalMain.cpp
index 2c252a93..2c648d4f 100644
--- a/src/control/XournalMain.cpp
+++ b/src/control/XournalMain.cpp
@@ -354,7 +354,7 @@ struct XournalMainPrivate {
     XournalMainPrivate() = default;
     XournalMainPrivate(XournalMainPrivate&&) = delete;
     XournalMainPrivate(XournalMainPrivate const&) = delete;
-    auto operator=(XournalMainPrivate &&) -> XournalMainPrivate = delete;
+    auto operator=(XournalMainPrivate&&) -> XournalMainPrivate = delete;
     auto operator=(XournalMainPrivate const&) -> XournalMainPrivate = delete;
 
     ~XournalMainPrivate() {
```

**To Reproduce**
1. Add a space somewhere around ```auto operator=(XournalMainPrivate &&) -> XournalMainPrivate = delete;```, `git add` the file.
2. Apply ```git --no-pager diff -U0 HEAD -- '*.cpp' '*.c' '*.h' '*.hpp' | perl azure-pipelines/util/format_diff_lines.pl```
3. See the output of `git diff`

**Expected behavior**
Well, the test and the perl script should agree.

**Comment by Technius** [comment]
What version of clang-format are you using? The version actually makes a difference IIRC.

You could also copy and paste the diff from CI if it's too much of a hassle to get it working locally.

**Comment by bhennion** [comment]
> What version of clang-format are you using? The version actually makes a difference IIRC.
```
$ clang-format --version
clang-format version 11.0.0
```

The azure pipeline uses version 10 ([see here](https://dev.azure.com/xournalpp/xournalpp/_build/results?buildId=8262&view=logs&j=8af2c752-b8c3-5474-5b0a-7b1f58b7bf90&t=5c8b0431-77ef-572a-7b30-b56c5bd12556&l=162))

**Comment by bhennion** [comment]
> I'll try installing clang 10

Ok, I can confirm it's a question of clang version. Version 10 on my machine does as the CI prescribes.
Is it possible to set clang's behaviour more precisely in the .clang-format to avoid those issues?

**Comment by Febbe** [comment]
I am aware of those issues, unfortunately, the different clang-tidy versions do not support each other.
IMO we should support 2 versions, the newest and the old stable maybe.

A failing clang-format check will not prevent a merge, if the reason is a different clang-format version.
Actually clang-format-11 has the correct behaviour.
