### ISSUE TITLE
Next and previous page shortcuts don't work on macOS

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#2546]
**Affects versions :**
 - OS: macOS Catalina 10.15.6
 - libgtk: 3.24.10
 - xournalpp: 1.0.19
 - official release

In Navigation tab it's written that the shortcut to move to next or previous page is CMD+ArrowUp and CMD+ArrowDown, but if I press them, nothing happens.

**Comment by bhennion** [comment]
#4811 most likely fixed that. Please reopen otherwise.
