### ISSUE TITLE
Official snap package

### ISSUE THREAD

**Issue by PaulCombal** [xournalpp/xournalpp#2553]
**Is your feature request related to a problem? Please describe.**

I am having an issue where a PDF doesn't export properly. I wanted to report this, only to find my version is over a year old, so I gave up.

I've installed Xournalpp from Snap, which is the recommended way to install apps, according to the Ubuntu team.

That also means I might be missing a lot of the work you have done :(

**Describe the solution you'd like**

In my dreams, you take over [the current xournalpp snap package](https://snapcraft.io/xournalpp), and ship updates for every releases. The current Snap ships version 1.0.16, which, referring to your tags, released over a year ago.

**Describe alternatives you've considered**

Using apt or flatpak. But if I had to do this, I'd rather keep using the old snap.

**Additional context**

Thank you so much for your work!

**Comment by rolandlo** [comment]
We are well aware of the problem and will try to look for a solution.

**Comment by personalizedrefrigerator** [comment]
I think [this](https://ubuntu.com/blog/author/ken-vandine) is the maintainer of the Snap!

**Comment by personalizedrefrigerator** [comment]
@kenvandine Could you take a look at this?

**Comment by personalizedrefrigerator** [comment]
It looks like [this](https://github.com/kenvandine/xournalpp) is the repository for the snap package!

**Comment by kenvandine** [comment]
I'm happy to update it.  I've been planning to submit the packaging upstream but never seem to find the time.  Maybe that'll be something I can knock out over the holiday break :)

**Comment by kenvandine** [comment]
Xournalpp 1.0.20 is now published in the stable channel.

I also confirmed that exporting as a PDF is working now :)

**Comment by rolandlo** [comment]
Wonderful! Thanks a lot!
