### ISSUE TITLE
using Xournalpp on Android

### ISSUE THREAD

**Issue by dkrenn** [xournalpp/xournalpp#256]
Is it possible to run the Xournalpp on Android?

- If yes, how to do this.
- If no, what would it need to make it run? How difficult would it be to do so?

**Comment by kelmes** [comment]
No, GTK+ doesn't exist on android. Either Xournalpp would need to be rewritten in something that does (which would be rewriting pretty much the whole thing), or GTK+ needs to be ported to android, (and I don't even want to think about how long that would take)

**Comment by dkrenn** [comment]
Ok, thank you for the answer; that is unfortunate to hear.

**Comment by TheOneWithTheBraid** [comment]
@dkrenn I began to create a port. As there does not seems to be a solution coming soon, I started a Xournal++ reader (and maybe later editor too) for mobile platforms including Chrome OS, Android, iOS and web browsers.

https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile

The project is using Flutter and currently only supports opening and parsing the `.xopp` files. Except of the page size and the number of pages in the bottom bar, they can not yet be shown properly. If anyone is interested too in having a mobile port of Xournal++, feel free to contribute.

You can get a online preview here: https://theonewiththebraid.gitlab.io/xournalpp_mobile/#/
