### ISSUE TITLE
Fractions, then semicolon, then text makes single character denominators of the fractions disappear

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2561]
Happens on Windows 10, with version 1.1.0. This latex snippet: 
0+\frac{4-0}n=0+\frac4n; \ $G$
causes the two n's on the bottom disappear. This is solved by removing the two dollar signs on either side of the 'G', or more interestingly, if you replace "\frac{4-0}n" with "\frac{4-0}{n+1}".

**Comment by rolandlo** [comment]
i can't reproduce it. It looks alright: 
![grafik](https://user-images.githubusercontent.com/40485433/102665797-c5ce0080-4185-11eb-9702-3dad9ca67f3d.png)

**Comment by DUOLabs333** [comment]
Huh. Strange...

**Comment by DUOLabs333** [comment]
@rolandlo You're right. Did it on a completely new document, and it worked. Must have been a fluke.
