### ISSUE TITLE
Exporting to PDF a xopp file with LaTeX annotations creates some errors with the PDF and LaTeX

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2564]
Windows 10, version 1.1.0. I recently used [this pdf](https://github.com/xournalpp/xournalpp/files/5718093/055.The.Fundamental.Theorem.of.Calculus.pdf) to create an xopp file (can't attach, as GitHub doesn't support it). I made some LaTeX annotations, then hit "Export as PDF". However, when I opened it to view
[the result](https://github.com/xournalpp/xournalpp/files/5718117/055.The.Fundamental.Theorem.of.Calculus.2.pdf), I saw that the LaTeX was messed up in a few places and that parts of the PDF were missing. This was weird, as all I thought Xournal did was place a stamp on the PDF.

**Comment by rolandlo** [comment]
Please provide the xopp-file (you can zip it), so we can try to find out the cause of your problem.
One more question: What Tex-distribution do you use?

**Comment by DUOLabs333** [comment]
I user MikTeX and here's
[the file](https://github.com/xournalpp/xournalpp/files/5718350/055.The.Fundamental.Theorem.of.Calculus.2.zip).

**Comment by rolandlo** [comment]
This is the pdf-file. We need the xopp-file.

**Comment by DUOLabs333** [comment]
Sorry, fixed it.

**Comment by rolandlo** [comment]
Here is my export. Doesn't look anything wrong with it. Can you reproduce the faulty export with the xopp-file you provided?
[export_FundamentalTheorem.zip](https://github.com/xournalpp/xournalpp/files/5718385/export_FundamentalTheorem.zip)

**Comment by DUOLabs333** [comment]
Hmm... That is the xopp file I used to create the pdf in my original comment-- I'm confused, what are you asking me to do?

**Comment by rolandlo** [comment]
I was just asking if you did indeed export from exactly that xopp-file (like me). It's puzzling. Maybe a problem with the Cairo library.

**Comment by DUOLabs333** [comment]
I'm guessing that you use Linux?

**Comment by DUOLabs333** [comment]
I'm going to try TeX Live to see if anything changes.

**Comment by rolandlo** [comment]
I can reproduce the problem on Windows.

**Comment by DUOLabs333** [comment]
Any update on this issue? Even with newer additions, the problems persist (for example, with the newest version, all but one LaTeX notation was fine-- the last one was all jumbled up:
![image](https://user-images.githubusercontent.com/49244768/106953427-6198d900-6700-11eb-8362-31ae87732658.png)

**Comment by DUOLabs333** [comment]
The newest update fixed this issue so closing.
