### ISSUE TITLE
Can't replace a pdf exporting again

### ISSUE THREAD

**Issue by vilarinux** [xournalpp/xournalpp#2566]
**Affects versions :**
 - OS: Linux arch-desktop 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
 - (Linux only) Desktop environment: X11 & i3, nvidia-455
 - Which version of libgtk do you use 3.24.24
 - Version of Xournal++: 1.0.19
 - Installation method: pacman

**The problem** 
I can't replace any pdf (this did not caused harm, you can easily remove the file, but it's annoying). So when I once exported a pdf, exporting it again **DOES NOT REPLACE** the old folder. Tried it right now, even if I change things, don't change, it just doesn't replace, and dialog still there.

**To Reproduce**
1. Create a new file
2. Just export it as pdf
3. Make some changes (or not)
4. Write it *as the same name before*
5. Get GTK replace message
6. Click Replace

**Expected behavior**
A replacement.

**Additional context**
Tried to look at .../xournalpp/xournalpp/src/util/*, and XojMsgBox.cpp and .h, nothing that I really found about, but there are some replace and GTK calls. Didn't find the functions that executes the replacement.

**Comment by rolandlo** [comment]
This is fixed in 1.0.20, so please upgrade.
