### ISSUE TITLE
The typewriter / texteditor doesn't work in Xournal++

### ISSUE THREAD

**Issue by holgervoss** [xournalpp/xournalpp#2573]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Ubuntu Focal 20.04
 - (Linux only) Desktop environment: GNOME (without Wayland)
 - Which version of libgtk do you use: libgtk: 3.24.20
 - Version of Xournal++: Xournal++ 1.1.0+dev, 
 - Installation method: http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu

**Describe the bug**
The texteditor / typewriter doesn't work. 

**To Reproduce**
Steps to reproduce the behaviour:
1.  Click on the T-button --> you only see a little frame and the cursor within
2. Typing on the keyboard has no effect.

**Expected behavior**
can add a text with the keyboard

**Screenshots of Problem**
![Bildschirmfoto von 2020-12-20 10-14-14](https://user-images.githubusercontent.com/76280359/102709889-d037e980-42ae-11eb-812e-0230d473839f.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Compare #2174. It has to be said that deactivating the new input system is not a solution that will work for a long time, since the old input system will be removed soon.

**Comment by Rmano** [comment]
Do you have a mouse + keyboard wireless combo?  If yes, look at https://github.com/xournalpp/xournalpp/issues/1769

**Comment by tattsan** [comment]
I've also experienced a similar issue.  In  my case, the cause was a keyboard and mouse remapping program ([xkeysnail](https://github.com/mooz/xkeysnail)).  In xournalpp menu of 'Input Devices', it appears as 'py-evdev-uinput'. I configured it as 'Mouse+Keyboard Combo', and the trouble went away.

**Comment by holgervoss** [comment]
I don't have a keyboard and mouse dongle. But the reference in number # 2174 works for me. I don't remember ticking the box, but disabling it was helpful! First off...  Thank you very much for the hints!

![Bildschirmfoto von 2020-12-20 21-47-02](https://user-images.githubusercontent.com/76280359/102724094-3d7a6780-430d-11eb-957f-0f15d1236d5e.png)

**Comment by hartmut27** [comment]
The problem occurs in version 1.1.3, where deactivating the new input system is not an option any more.
if I press and hold a key (key repeat), then text gets entered, e.g. aaaaaaaaaaaa. 
Also pasting text from the clipboard works.
but single press key, no input.
I am using Manjaro 22.0.0, X11, Xfce.

**Comment by rolandlo** [comment]
@hartmut27 Have you tried mapping your keyboard device in the input system panel of menu `Edit > Preferences` to the  "Mouse + Keyboard Combo" device class?

**Comment by hartmut27** [comment]
@rolandlo following your advice to set an keyboard device to "Mouse+Keyboard Combo" did solve the issue! Thanks a bunch :-)
![image](https://user-images.githubusercontent.com/752620/210170296-a0fe77a3-0a01-49f9-923d-f5680498380f.png)
