### ISSUE TITLE
import PDF documents into xournalpp as pages

### ISSUE THREAD

**Issue by gri573** [xournalpp/xournalpp#2574]
**Describe the solution you'd like**
Xournalpp already allows for importing PDF documents as a page background, but requires to create a new document in order to do so. I would love to see an option to import PDF documents into existing xournalpp files as new pages, acting as background.

**Comment by gri573** [comment]
just found that this is a duplicate

**Comment by thekswenson** [comment]
@gri573 Could you please post a link to the duplicate?

**Comment by gri573** [comment]
It's issue number #1815
