### ISSUE TITLE
Ruler + Rotation Snapping sometimes results in jumpy lines when using pen or highlighter

### ISSUE THREAD

**Issue by francium** [xournalpp/xournalpp#2581]
**Affects versions :**
 - OS: Linux (Arch, Gnome 3.38, X11)
   - Issue is not new, have noticed it since migrating from Xournal to Xournal++ (probably close to 1 year now if I had to guess)
 - Version of Xournal++ `1.0.19` (as per `xournalpp --version`) and `libgtk 3.24.24`

**Describe the bug**
See video: https://user-images.githubusercontent.com/15352422/102906411-9566ba80-4442-11eb-972e-80b72efaee92.mp4

I'm using a [Thinkpad with a pen input](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.pxIXahO0t7szJcqgRTObAAHaHa%26pid%3DApi&f=1) under X11. Please note this issue only occurs sometimes. I can also see it when using the mouse as well. So it may be bug in the rotation snapping logic rather than pen/mouse input handling.

Notice during the video rotation snapping is enabled and through out this video I am using the pen input. At around 1:00 of this video, you will notice the issue occur, the jumping is very small, but it's noticeable. I am not intentionally moving my pen up/down to cause this, I was moving the pen from left/right smoothly as horizontally as I could, but the rotation snapping logic appears to have a bug causing the snapping to be offset at certain internals under some unknown conditions.  

**To Reproduce**
1. Enable `rotation snapping` from the `edit` menu
2. Select `pen` or `highlighter`
3. Enable `ruler` from the toolbar
4. Move the cursor horizontally and draw/highlight
5. Occasionally the rotation snapping jumps/down up a few pixels instead of remaining at a 0 degree angle

**Input Logs**
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5731057/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5731058/debug_input.log)

**Expected behavior**
The drawn line should not jump up/down a few pixels when it's close to a snapping angle, 0, 45, 90, etc degrees

**Screenshots of Problem**
See video linked aboved in `Describe the bug`

**Additional context**
I can look into this myself, but I haven't looked into the code yet. If someone could point me to, what they believe, would be the relevant files/modules/classes/functions, I'd be happy to look into it when I get the chance.

**Comment by rolandlo** [comment]
A couple of comments and questions:

1) Does this also appear if you only activate rotation snappiing and no grid snapping?
2) You are using version 1.0.19. The snapping methods have been completely reworked and improved for version 1.1.0+dev. I would advise you to try out the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and check the behavior there.
3) Version 1.0.20 will be no different with respect to snapping than version 1.0.19. Moreover version 1.0.20 is presumably the latest releases in the 1.0.x series. So it's unlikely we will fix this bug in the 1.0.x series.
4) If you want to try to fix the 1.0.19 (or 1.0.20) version yourself, you will find the relevant code in the `RulerHandler` class.
5) I haven't checked you input logs (yet). If you choose to go for the 1.1.0+dev version (which I would really recommend), then it has no point of inspecting the problem any further.

**Comment by francium** [comment]
> 2. You are using version 1.0.19. The snapping methods have been completely reworked and improved for version 1.1.0+dev. I would advise you to try out the nightly build and check the behavior there.

I built from source (checked out repo when I made this issue) and still saw this happening.

**Comment by rolandlo** [comment]
Two more comments:
6. You better test this out with graph paper background, since you can see better what happens (and the background has no influence on snapping behavior).
7. In version 1.1.0+dev you could also play around with the snap to grid tolerance and the snap rotation tolerance in the drawing area settings panel of the preferences.

**Comment by francium** [comment]
Haven't noticed as issues with the grid snapping disabled, in past two days. Going to close this issue for now and will reopen if anything new comes up.
Thanks for mentioning the settings for the tolerances, I'll keep them in mind for the future.
