### ISSUE TITLE
Add Xournal to the "Open With" context menu on Windows

### ISSUE THREAD

**Issue by LCarmi** [xournalpp/xournalpp#2585]
**Is your feature request related to a problem? Please describe.**
On Windows 10, if Xournal is not your default pdf editor and but you want to open a file with Xournal, this actions are needed:
Right click on file -> Open With -> Choose another app -> xournalpp.exe
Many common applications are shown as suggestions in the "Right click on file -> Open With " menu, which is much more useful from a UX point of view

**Describe the solution you'd like**
I looked forward to see how to add Xournal to that menu.

While debugging the Registry Entries, I found out this solution:
[https://superuser.com/questions/1199648/strange-open-with-list-inconsistent-with-registry/1256482#1256482](https://superuser.com/questions/1199648/strange-open-with-list-inconsistent-with-registry/1256482#1256482)

By adding an entry ending in .ApplicationCompany as suggested by the linked resource, i fixed the problem. 
However it is to be noted that this fix is only temporary because it seems that Windows 10 refreshes the MuiCache, and that probably such a fix should be done during the app registration in Windows.

Unfortunately I'm no expert of windows installation procedures and so on, but still I'm sharing this usability improvement if useful to be integrated in future releases.

Moreover, the .FriendlyAppName can be changed to "Xournal++" instead of "xournalpp.exe"

**Comment by Technius** [comment]
Anyone interested in contributing, this can be done by editing the the NSIS install script in `windows-setup/xournalpp.nsi`. The windows install script actually needs an overhaul in my opinion...

**Comment by rolandlo** [comment]
> Anyone interested in contributing, this can be done by editing the the NSIS install script in `windows-setup/xournalpp.nsi`. The windows install script actually needs an overhaul in my opinion...

I agree. In particular the plugin folder and resource folder should get installed.

**Comment by Technius** [comment]
I installed a fresh version of Xournal++ and I got a `Edit Xournal++ file` menu option when right clicking an xopp file. Do you not have that option?

**Comment by DUOLabs333** [comment]
@Technius I think LCarmi is referring to opening PDFs in Xournal++.

**Comment by Technius** [comment]
This has been fixed in #2606.
