### ISSUE TITLE
Scroll Up/Down not working if the arrow is not over the scrollbar

### ISSUE THREAD

**Issue by ErgastiAlex** [xournalpp/xournalpp#2588]
**Affects versions :**
 - OS: Windows
 - libgtk 3.24.23
 - Installation method: Nightly Build V1.1.10+ dev Commit a92fcac0

**Describe the bug**
If the arrow is not over the right scrollbar the command scroll up or scroll down is not readed

https://user-images.githubusercontent.com/20249175/103035693-26838180-4568-11eb-85d7-ee41f3808e94.mp4

**To Reproduce**
Put the mouse everywhere over the page and try to scroll, the page will not move.
Move the mouse over the right scrollbar, then the page will react to the command.

**Expected behavior**
With the previous version i could scroll while having the mouse on the page.

**Comment by ErgastiAlex** [comment]
Duplicated #2523

**Comment by MichelReims** [comment]
You must compile source on your computer. This fix the problem
