### ISSUE TITLE
buster package xournalpp-1.0.20-Debian-buster-x86_64.deb buggy?

### ISSUE THREAD

**Issue by in3mug** [xournalpp/xournalpp#2593]
Hello, i am a newbie.

After trying to install Debian Buster package i got an error
> root@pc:/home/user/Downloads# dpkg -i xournalpp-1.0.20-Debian-
> buster-x86_64.deb 
> dpkg: Fehler beim Bearbeiten des Archivs xournalpp-1.0.20-Debian-
> buster-x86_64.deb (--install):
>  Parsen der Datei »/var/lib/dpkg/tmp.ci/control«, nahe Zeile 3:
>  nach Feldname »flexibility,« muss ein Doppelpunkt folgen
> Fehler traten auf beim Bearbeiten von:
>  xournalpp-1.0.20-Debian-buster-x86_64.deb

Mr. Andreas Butti encouraged me to open a bug report.
"This is not your fault, it look like the Package contains an error."

Thank you very much. Kind regards.

**Comment by rolandlo** [comment]
Yes, the 1.0.20 Debian package doesn't work. A repaired one is already in the pipelines and will be released in the next couple of days.

**Comment by LittleHuba** [comment]
This is fixed with the just now released 1.0.20-hotfix.

**Comment by tarikgraba** [comment]
> This is fixed with the just now released 1.0.20-hotfix.

Are you sure?

```bash
md5sum xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb &&  sudo dpkg -i ./xournalpp-1.0.20-hotfix-hotfix-Debian-buste      r-x86_64.deb
9230dd069073f668850875f6f90ae6bf  xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb
dpkg: error processing archive ./xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7:
 blank line in value of field 'Description'
Errors were encountered while processing:
 ./xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb
```

**Comment by rolandlo** [comment]
It's not the right package, that got deployed to the github page. You will need some more patience.

**Comment by tarikgraba** [comment]
> It's not the right package, that got deployed to the github page. You will need some more patience.

Ok thanks  :)

**Comment by rolandlo** [comment]
Ok, solved now.
