### ISSUE TITLE
Add the ability for temporary highlighting of text & graphics

### ISSUE THREAD

**Issue by BillM-Penfield-NY** [xournalpp/xournalpp#2596]
**WHAT:**  Add the ability to hightlight text in a way such that the highlighted text disappears automatically within a few seconds after creating the highlighting.

**WHY:**  This suggestion is being made because this feature has been found to be a useful teaching tool in the past, and its implementation would help an instructor focus more on the teaching and less on the mechanics of how lessons are taught.

**DETAILS:** This is a feature found in Sketch Together which has been found to be very useful in the past when teaching / tutoring students online.  There is an obvious workaround: to highlight some text / graphic, then UNDO that highlighted text / graphic.  The problem with this workaround is that it takes time away from the instructor being able to focus entirely on course instruction.

**Comment by rolandlo** [comment]
Do you mean this tool in Sketch Together? 

![grafik](https://user-images.githubusercontent.com/40485433/103159748-554e6180-47cd-11eb-9c6b-68843aacf56f.png)

Something like that also exists in Google Jamboard (mentioned in PR #1822). It is related to issue #1778

**Comment by BillM-Penfield-NY** [comment]
_"... Do you mean this tool in Sketch Together?..."_

Roland, yes - the Sketch Together feature is the one associated with the icon you've noted above.  Thanks for noting other instances of the same suggestion...which I think would be a good one to eventually implement in xournal++.

**Comment by rolandlo** [comment]
I close this issue in favor of #1778.
