### ISSUE TITLE
cannot install: xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb

### ISSUE THREAD

**Issue by plc-user** [xournalpp/xournalpp#2597]
Error-message on actual debian unstable:
-----------
dpkg: error processing archive xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7:
 blank line in value of field 'Description'
Errors were encountered while processing:
 xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb
-----------

**Comment by rolandlo** [comment]
That should be solved now. Just download once more.
