### ISSUE TITLE
highlighter fill transparency/opacity not working

### ISSUE THREAD

**Issue by domenicozambella** [xournalpp/xournalpp#2599]
- Version: 1.0.20
 - OS: Kubuntu 20.04
 - Installation method: PPA

**Highlighter** fill opacity does not reach 100% (which is useful to hide part of a the text/background). 

F.Y.I. **Pen** fill transparency works as expected (from fully transparent to completely opaque), so there is a workaround - though inconvenient.

**Comment by rolandlo** [comment]
That "bug" is intended, I think, and contrasts highlighter and pen.
