### ISSUE TITLE
Fullscreen + presentation doesn't look right

### ISSUE THREAD

**Issue by WPettersson** [xournalpp/xournalpp#260]
I didn't catch this earlier, but when I "fixed" presentation mode it didn't work with full screen, the pages weren't sized right. It seems the layout was updated after the whole window was resized, but before the pages and/or XournalWidget was resized.

**Comment by WPettersson** [comment]
Actually, having used this for a while now, maybe there are more changes we want here. For instance:

Remove scroll bar and red borders in full-screen presentation mode.

Make toolbars auto-hide in full-screen presentation mode. I'm trying to think of a nice way of having the toolbars available when needed here. Maybe they could slide out when the cursor nears the edge - if they do slide out, do we want them to shrink the display when they slide out, or should they appear "over the top" of the display so the page doesn't change scale?

**Comment by wbrenna** [comment]
Thanks, yes - having toolbars, scrollbar, and borders hide in full screen presentation is good. I'd personally rather they don't change scale in presentation mode; I like the idea of a fixed scale in that mode. I'll merge your pull after you make some more changes?

**Comment by wbrenna** [comment]
I intend only to use presentation mode in full-screen.

**Comment by andreasb242** [comment]
On this ticket was already some changes. For me it's not clear what to do now. I close it. For new bugs please open a new Ticket.
