### ISSUE TITLE
Export to PDF creates corrupted PDFs with Xournal++ 1.0.20

### ISSUE THREAD

**Issue by Markus74a** [xournalpp/xournalpp#2601]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.20 / 1.0.19
 - Installation method: Official Windows Installer

**Describe the bug**
Xournal++ "Export to PDF" feature will create partially corrupted PDFs with Xournal++ 1.0.20.
Using Xournal++ 1.0.19 will export PDFs working correctly.

I compared the PDFs created by Xournal++ 1.0.19 and 1.0.20. They will be identical with exception of the date and the **FontName** and **BaseFont** entries

Examples from 1.0.19 (each **/FontName** will have a matching **/BaseFont** string not printed here)
```
/FontName /GZMBAL+LMRoman10-Regular
/FontName /HQLXHP+CMMI10
/FontName /IGGRRB+CMMI8
/FontName /TJYQRQ+CMR6
/FontName /ZBREYI+CMR10
/FontName /AWBOZU+CMR8
/FontName /WIZMEQ+Tahoma
```
Same locations in PDF file with Xournal++ 1.0.20
```
/FontName /;(5@A6+LMRoman10-Regular
/FontName /:16*:2+CMMI10
/FontName /9;;00@+CMMI8
/FontName /.8)101+CMR6
/FontName /(@0=)9+CMR10
/FontName /A+@3(-+CMR8
/FontName /+9(5=1+Tahoma
```

**Additional context**
- The 1.0.20 exported PDFs can be opened with some viewers (like *Chrome*, *SumatraPDF*)
- Official *Adobe Acrobat* will just give a "*there has been some error processing this page*" message and show nothing
- *Firefox* will render the page only until the point where the first annotation added with Xournal++ would show

I assume there is some set of characters *Acrobat* and *Firefox* expect when parsing font names, so they will fail loading the PDF if they encounter forbidden characters.

**Comment by rolandlo** [comment]
Can you provide a sample xopp-file, so that we can test if that is Windows-specific? I think this must be a dependency issue, since we didn't change anything in PDF export from version 1.0.19 to version 1.0.20.

**Comment by Markus74a** [comment]
Commands used:
```
c:\xournal1019\bin\xournalpp_bin.exe test.xopp -p test1019.pdf
c:\xournal1020\bin\xournalpp_bin.exe test.xopp -p test1020.pdf
```
[test.zip](https://github.com/xournalpp/xournalpp/files/5752182/test.zip)

test1019.pdf: `/FontName /QNSAVZ+Tahoma`
test1020.pdf: `/FontName /14/A,(+Tahoma`

**Comment by rolandlo** [comment]
The difference seems to be that the `test1019.pdf` file was produced by cairo `1.17.3`, whereas `test1020.pdf` was produced by cairo `1.17.4`. This can be read off the files near the end (byte 7430). Probably a regression in cairo, which you could report upstream. It doesn't look like Xournal++'s fault (other than we may need to avoid cairo 1.17.4 in future)

**Comment by personalizedrefrigerator** [comment]
Link to the upstream bug report: https://gitlab.freedesktop.org/cairo/cairo/-/issues/449

**Comment by rolandlo** [comment]
Xournal++ 1.1.0+dev also uses Cairo 1.17.4, so the bug should be in the nightly release as well. So we must fix it by avoiding Cairo 1.17.4, I think.

**Comment by Technius** [comment]
We'll have to build our own cairo then: https://github.com/msys2/MINGW-packages#using-packages

This shouldn't be difficult though.

**Comment by Elephant34** [comment]
I feel like this issue is worthy of a tagged release sooner then v1.1.0 milestone- exporting to pdf is a major feature which is not working in the version any new user like myself would install.

**Comment by Technius** [comment]
> I feel like this issue is worthy of a tagged release sooner then v1.1.0 milestone- exporting to pdf is a major feature which is not working in the version any new user like myself would install.

`1.1.0` _is_ the next tagged release, ETA end of this month.

**Comment by psychon** [comment]
Since this already has a pointer at the upstream bug report, here is a MR that (supposedly - I did not test it in any way) fixes the bug: https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/125

**Comment by Technius** [comment]
The MinGW package has been patched in msys2/MINGW-packages#7963, so the fix should appear in today's nightly build.

**Comment by rolandlo** [comment]
Azure Pipeline still uses `mingw-w64-x86_64-cairo-1.17.4-1-any.pkg.tar.zst...`. When I upgraded manually on my Windows installation (using `pacman -Syuu` twice) I got an upgrade to `mingw-w64-x86_64-cairo-1.17.4-2`. So the Azure Pipeline still uses the old Cairo package.

**Comment by rolandlo** [comment]
After building manually I can confirm that the PDF export works again on Windows with `mingw-w64-x86_64-cairo-1.17.4-2`. It doesn't work with 1.17.4-1.

**Comment by DUOLabs333** [comment]
@rolandlo You can't manually upgrade it in Azure Pipeline?

**Comment by rolandlo** [comment]
I don't know if and how, that's the problem. Otherwise I would do it.

**Comment by Technius** [comment]
In the CI configuration, we need to sync the msys repository with `pacman -Sy` before we run the install command. This will slightly increase build times though.

**Comment by rolandlo** [comment]
@Technius You mean like this: #2871, right?

**Comment by DUOLabs333** [comment]
@rolandlo This is just an idea, but you could always host the package inside Azure Pipeline (not sure exactly how it works) or on a GitHub repository and pull from there.

**Comment by rolandlo** [comment]
Comparing `Install dependencies` times with the msys2 package repository update and without the update: It takes almost 15 minutes longer (20 min 4 sec instead of 5 min 36) to install those dependencies with the update.

**Comment by DUOLabs333** [comment]
This seems to have been fixed with the newest dev update.

**Comment by binaondrej** [comment]
Where can I downlod this dev update for windows?

**Comment by rolandlo** [comment]
@binaondrej In the [nightly releases](https://github.com/xournalpp/xournalpp/releases/tag/nightly)
