### ISSUE TITLE
French localization issue

### ISSUE THREAD

**Issue by Kekun** [xournalpp/xournalpp#2605]
Here is the same dialog in English and French, I think the issue is pretty clear. :)

![Screenshot from 2020-12-31 00-41-57](https://user-images.githubusercontent.com/2536339/103378024-50492500-4ae1-11eb-9784-236d50f97206.png)

![Capture d’écran de 2020-12-30 20-42-29](https://user-images.githubusercontent.com/2536339/103378026-53441580-4ae1-11eb-9984-80e4e34509f3.png)

**Comment by Febbe** [comment]
which version do you use?
On https://crowdin.com/translate/xournalpp/6/en-fr?filter=basic&value=0#q=Discard
It's 'Abadonner' but I think Jeter would be better here.

**Comment by Kekun** [comment]
I use 1.0.20 (commit 09ec499) from Flathub.

After thinking about this a bit more, I think de core of the issue lies in the whole dialog as its actions are not clear:
- Save actually means "save and quit"
- Discard actually means "quit anyway"
- Cancel means "cancel the request to quit"

I think the dialog is wrongly designed, it's asking for a confirmation to quit, but it mixes it with two different destructive actions: whether the document should be saved, overwriting the open document, or whether it should be abandoned.

I'd suggest to have this instead:
- Cancel (first, as it's a non-action)
- Quit (as that's the action we want to confirm, last as it's the actual action, and with the destructive style class as it's destructive)

If the user want to save, they can easily cancel and save or save as a different file.

Alternatively we could borrow Gedit's design but I remember designers complaining about it having 3 buttons so I'd suggest my 2-buttons suggestion instead. Note Gedit doesn't offer to save but to save as, which isn't a destructive action.

![Capture d’écran de 2020-12-31 09-21-07](https://user-images.githubusercontent.com/2536339/103401570-ac479400-4b49-11eb-8570-4df4cddbdce6.png)

**Comment by Febbe** [comment]
This Dialog is used on several places. For example, when we change the document. So we either need to add another CloseDialog, or use something like `Save Changes` | `Discard Changes` | `Cancel Operation`. We also make a difference between `Save`and `Save As...` . Whenever a Document has no path or the file is removed we use the `Save As...`. Button

I think the main problem is, that somehow the wrong translation is used, can you check if this is still the case in the newest French translation?
For other languages this Dialog is still clear:
en:    `Save` | `Discard` | `Cancel`
de:    `Speichern` | `Verwerfen` | `Abbrechen`
fr:     `Sauvegarder` | `Jeter` | `Annuler` or `Sauvegarder` | `Abandonner` | `Annuler` I don't know?

**Comment by bhennion** [comment]
With the master version, the french translation seems to be fixed:
![Screenshot_20210102_180354](https://user-images.githubusercontent.com/17818041/103462375-1bc5ab00-4d25-11eb-93b6-5979ab73c665.png)

**Comment by Febbe** [comment]
Some examples from LibreOffice.
![grafik](https://user-images.githubusercontent.com/2228627/103463021-7bbe5080-4d29-11eb-8777-6b2190c99458.png)
![grafik](https://user-images.githubusercontent.com/2228627/103463040-b0320c80-4d29-11eb-8915-e9571517be55.png)
![grafik](https://user-images.githubusercontent.com/2228627/103463071-fd15e300-4d29-11eb-96cf-8e25fd088ccf.png)

**Comment by sanette** [comment]
I remember having read articles about these "not so clear dialogs", eg: https://uxmovement.com/buttons/why-the-ok-button-is-no-longer-okay/
and the requirement is always to use more "natural language" dialogs; so I would vote for doing the same as Libreoffice, including the sentence above the 3 buttons

**Comment by sanette** [comment]
ha, another example: like many I tried to install Signal today, and here is a nice dialog:
"Do you want to cancel blabla... ?" with 2 buttons "OK" and "Cancel"  hehe ;)

**Comment by xunam** [comment]
Hello,

Adding my two cents to his issue, because I regularly stumble upon it. Indeed my most frequent usage of xournalpp is for filling forms: open a PDF, write something on it, export it as PDF and send it back; I have no use for the xopp file most of the time.

> With the master version, the french translation seems to be fixed:
> ![Screenshot_20210102_180354](https://user-images.githubusercontent.com/17818041/103462375-1bc5ab00-4d25-11eb-93b6-5979ab73c665.png)

I think this translation does not fix anything. For most users, *Abandonner* and *Annuler* are mostly equivalent. Moreover, *Abandonner* without a complement means renouncing to what you were about to do, i.e. exit the program in this case. If the dialog keeps its structure with three answers, the approaches of gedit or LibreOffice mentioned above seem much clearer to me.

Besides, this dichotomy between *saving* (in the application-specific format) and *exporting* (in standard formats) is reminiscent of a similar debate that happened with Gimp some years ago and the choices that were made apparently still generate regular frustration among some users. What should be done probably depends on what most users would expect. I have no opinion on that issue though (my specific use case certainly makes me biased).

**Comment by Febbe** [comment]
I am also up to it to change this, but it will break all languages when I do this on source-code side. But everyone can change this over crowdin.com. Just change the translation to something like Save, Don't Save, Cancel.

**Comment by rolandlo** [comment]
I changed it to "Fermer sans enregistrer" on Crowdin, which was the most popular vote.
https://crowdin.com/translate/xournalpp/6/en-fr?filter=basic&value=3#q=Annuler

**Comment by MichelReims** [comment]
There is no change in xournalpp of 20210711

**Comment by rolandlo** [comment]
That's because Crowdin updates #3202 are not yet merged. You can check the updated files [here](https://github.com/xournalpp/xournalpp/pull/3202/files)

**Comment by MichelReims** [comment]
Thank you

**Comment by bhennion** [comment]
Closing this. It has been fixed in master since #3202 was merged on July 17.
