### ISSUE TITLE
libzip version error when started on Ubuntu 20.04

### ISSUE THREAD

**Issue by mrcrutch** [xournalpp/xournalpp#2610]
**Affects versions :**
 -  Xournal++ 1.0.20-hotfix installed on LinuxLite 5.2 (**based on Ubuntu 20.04 Focal**)

**Describe the bug**
In described environment, xournalpp when trying to launch, complains about missing libzip.so.4 shared object file.

**To Reproduce**
1. Installed using .deb package available on Releases page, using dpkg -i command.
(sudo dpkg -i xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb)
2. Solve missing dependences with apt-get -f install
3. Try to launch executing 'xournalpp' from within a shell

**Expected behavior**
Xournalpp should run, but it complains about missing libzip.so.4 shared object file.

**Screenshots of Problem**
Message at shell prompt:
`xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory`

**Workaround Solution**
libzip dependency is correctly solved by .deb package. Anyway, xournalpp expect to open file libzip.so.4 which is not available due to a version issue: version on the system, obtained by apt-get, is at 5.0.

Problem is solved simply by creating a symlink linking the 'old name' to the last version:
```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libzip.so.5.0 libzip.so.4
```

**Comment by rolandlo** [comment]
You should install the [Ubuntu 20.04 package](https://github.com/xournalpp/xournalpp/releases/download/1.0.20/xournalpp-1.0.20-Ubuntu-focal-x86_64.deb). The hotfix version was only for Debian users.

**Comment by mrcrutch** [comment]
Oh, god! I'm very sorry for my stupid mistake! :)
I can confirm that with the package you linked everything goes fine!
