### ISSUE TITLE
Configurable tool loadouts

### ISSUE THREAD

**Issue by AlexanderKosnac** [xournalpp/xournalpp#2616]
**Is your feature request related to a problem? Please describe.**
I use xournal for taking notes and I often have to switch between different pen modes (normal pen, rectangles, lines or highlighter plus different combinations of color and thicknesses). When you have to do this quite often, it gets quite annoying to select all the options again and then switch back. (just to then realize you messed up and need to switch back again, ahhh! 😬)

**Describe the solution you'd like**
As I often use the same combinations I would really like an option to configure "tool loadouts" and activate them via some hotkey. Examples of common configurations I use:
  - "medium width, black pen for writing"
  - "fine width, black draw line for underlining"
  - "medium with blue highlighter" 

I guess the normal keyboard numbers 1-9 aren't used for anything right now, so I would see those as nice candidates.

**Describe alternatives you've considered**
I haven't found an existing feature which would help me with this, is there one? Seems like this is could be doable with a plugin (see [plugin documentation](https://xournalpp.github.io/guide/plugins/#using-plugins-to-define-shortcuts-for-ui-actions)) but I have no experience in Lua.

What do you guys think?

**Comment by Technius** [comment]
Have you tried the experimental floating toolbox? https://github.com/xournalpp/xournalpp/pull/1161#issuecomment-498477503

**Comment by AlexanderKosnac** [comment]
Oh, you are quick! Yes, I have tried that, but it just seems to bring "the clicking" closer to the cursor.

A problem maybe more specific to me is that my pen only has two quick access buttons and I use one for quick deletion (medium eraser) and the other one to move the page. So spending one on the toolbox is quite a big deal for me :/

**Comment by tattsan** [comment]
I use 'Tap Action' to envoke floating toolbox.

**Comment by AlexanderKosnac** [comment]
Whats 'Tap Action'? Is this a xournal setting or something on OS level you have rebound? I don't see anything in the preferences ...

**Comment by tattsan** [comment]
It is in the xournal++ menu: Preference -> Drawing Area

**Comment by AlexanderKosnac** [comment]
True, found it. Ill try it out for some time, but I dont think this will cut it for me.

Do you guys know if what I described would be doable as a plugin?

**Comment by Technius** [comment]
This could certainly be done as a plugin, but we would need to expose the functionality to the plugin API. I don't think there is support for custom keyboard bindings yet.

@rolandlo could offer some more helpful comments.

**Comment by rolandlo** [comment]
@AlexanderKosnac Something like this should do what you want (untested). Try it out and then you can ask again, if the plugin needs to be modified.

```lua
-- Register all Toolbar actions and intialize all UI stuff
function initUi()
  app.registerUi({["menu"] = "medium width, black pen for writing", ["callback"] = "mode1", ["accelerator"] = "1"});
  app.registerUi({["menu"] = "fine width, black draw line for underlining", ["callback"] = "mode2", ["accelerator"] = "2"});
  app.registerUi({["menu"] = "medium with blue highlighter", ["callback"] = "mode3", ["accelerator"] = "3"});
end

function mode1()
app.uiAction({["action"]="ACTION_TOOL_PEN"})
app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
app.changeToolColor({["color"] = 0x000000, ["selection"] = false})
end

function mode2()
app.uiAction({["action"]="ACTION_TOOL_PEN"})
app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_FINE"})
app.changeToolColor({["color"] = 0x000000, ["selection"] = false})
end

function mode3()
app.uiAction({["action"]="ACTION_TOOL_HIGHLIGHTER"})
app.uiAction({["action"]="ACTION_TOOL_HIGHLIGHTER_SIZE_MEDIUM"})
app.changeToolColor({["color"] = 0x0000ff, ["selection"] = false})
end

```

**Comment by AlexanderKosnac** [comment]
@rolandlo very cool, thanks! It seems to work for the most part, but I get the error:

```
attempt to call a nil value (field 'changeToolColor')
```

I tried printing the members of `app` with: 

```
for key,value in pairs(app) do
    print("found member " .. key);
end
```

which returns only those:

```
changeCurrentPageBackground
uiActionSelected
registerUi
uiAction
msgbox
```

Compared to the functions defined in `luapi_application.h` there are quite a lot missing. All examples I could find do it just like you did. Do you know whats going on?

I tested it with 1.0.19 and then updated to 1.0.20, neither works.

**Comment by Fef0** [comment]
@rolandlo I'm actually using a plugin I wrote which is very similar to yours, but I think that we probably need an API exposure in order to create customizable buttons which are quick to select and deselect even when using a tablet (that doesn't have a keyboard) like I suggested in #2431

**Comment by rolandlo** [comment]
> @rolandlo very cool, thanks! It seems to work for the most part, but I get the error:
> 
> ```
> attempt to call a nil value (field 'changeToolColor')
> ```
> 
> I tested it with 1.0.19 and then updated to 1.0.20, neither works.
> 
> **Edit:** Just tested the [ColorCycle plugin](https://github.com/xournalpp/xournalpp/tree/master/plugins/ColorCycle) and this one doesnt work for me either, same error.

For `app.changeColor` (and all the pages and layer API commands that I implemented recently), you need version 1.1.0+dev. You can download the nightly build from the [release page](https://github.com/xournalpp/xournalpp/releases/tag/nightly).

**Comment by rolandlo** [comment]
> @rolandlo I'm actually using a plugin I wrote which is very similar to yours, but I think that we probably need an API exposure in order to create customizable buttons which are quick to select and deselect even when using a tablet (that doesn't have a keyboard) like I suggested in #2431

I agree, we need to think of a solution like that. It just takes time to figure out all the details how it should work and to implement it.

**Comment by atticus-sullivan** [comment]
Related https://github.com/xournalpp/xournalpp/issues/3833#issuecomment-2509679702

I think all open issues here have been addressed by now.
- Accelerators were already implemented back then
- Toolbaricons were added as well

So I'd close this in favor of https://github.com/xournalpp/xournalpp/issues/3833 since the font tool is the only tool that can't be configured properly via `uiAction` calls. Or am I missing something here?

**Comment by rolandlo** [comment]
> Related [#3833 (comment)](https://github.com/xournalpp/xournalpp/issues/3833#issuecomment-2509679702)
> 
> I think all open issues here have been addressed by now.
> 
>     * Accelerators were already implemented back then
> 
>     * Toolbaricons were added as well
> 
> 
> So I'd close this in favor of #3833 since the font tool is the only tool that can't be configured properly via `uiAction` calls. Or am I missing something here?

I agree, this can be closed now.

**Comment by atticus-sullivan** [comment]
Maybe quickly providing an example plugin:

```lua
-- Register all Toolbar actions and intialize all UI stuff
function initUi()
	app.registerUi({menu = "mode1", callback= "main", mode=1, toolbarId="mode1", iconName="starred-symbolic"})
	app.registerUi({menu = "mode2", callback = "main", mode=2})
end

function main(mode)
	if mode == 1 then
		app.uiAction({["action"]="ACTION_TOOL_PEN"})
		app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
		app.changeToolColor({["color"] = 0x000000, ["selection"] = false})
	elseif mode == 2 then
		app.uiAction({["action"]="ACTION_TOOL_PEN"})
		app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_FINE"})
		app.changeToolColor({["color"] = 0x000000, ["selection"] = false})
	end
end
```

the possible `iconName`s can be obtained by looking at the current icon theme and what icons are included there. The `toolbarId` probably should be more expressive (probably even contain something that marks this in a way that it's obvious this element belongs to this plugin as the id could clash with other plugins)

**Comment by rolandlo** [comment]
> the possible `iconName`s can be obtained by looking at the current icon theme

You are not restricted to using existing icons. You can also add new icons into 
```term
~/.local/share/icons/hiclor/scalable/actions
```
on Linux or
```term
C:\Users\<user>\AppData\Local\share\icons\hicolor\scalable\actions
```
on Windows.
