### ISSUE TITLE
Stylus pressure multiplier

### ISSUE THREAD

**Issue by caph1993** [xournalpp/xournalpp#2619]
**Is your feature request related to a problem? Please describe.**

My typical stroke renders very thin on the screen, even with the thick tool.

![image](https://user-images.githubusercontent.com/5473460/103489903-095f7600-4de6-11eb-9437-bb47b371d127.png)

**Describe the solution you'd like**

A menu for selecting the **input-output pressure curve**, like those used in image editors would be fantastic.

Example:

![image](https://user-images.githubusercontent.com/5473460/103490314-0ca83100-4de9-11eb-9838-1e88cd83f5c9.png)

**Describe alternatives you've considered**

A simple scale factor for the stylus pressure may work. I had the same issue using [another app](http://www.styluslabs.com/), and they provided a 'pressure scale factor' that improved the minimum width a lot, although slower and harder strokes became extremely wide.

**Comment by personalizedrefrigerator** [comment]
#2622 doesn't add a pressure curve, but I think it addresses this!

**Comment by tattsan** [comment]
The PR #2622 works fine!  Thank you so much.  The line thickness of  draw tool is the one for 100% pressure, but normal writing pressure is not so high. For this reason, when both are mixed, the balance of thickness becomes unbalanced.  The PR solved this issue! 

The PR will fix #1015 and #2545 .  The solution is similar to #1361 , but from a different point of view.
