### ISSUE TITLE
Does not find libpoppler.so.72

### ISSUE THREAD

**Issue by piegamesde** [xournalpp/xournalpp#262]
I installed xournalpp from the AUR on Arch, and it worked fine previously, but since a few updates it crashes with the following error:

    xournalpp: error while loading shared libraries: libpoppler.so.72: cannot open shared object file: No such file or directory

I have version 74 installed, but xournalpp does not recognize it. Workaround:

    sudo ln -s /usr/lib/libpoppler.so.74 /usr/lib/libpoppler.so.72

**Comment by acuerol** [comment]
Try this https://itsfoss.com/solve-open-shared-object-file-quick-tip/

**Comment by piegamesde** [comment]
Nope, does not help. This is what the command does:

	libpoppler-cpp.so.0 -> libpoppler-cpp.so.0.4.0
	libpoppler-qt5.so.1 -> libpoppler-qt5.so.1.13.0
	libpoppler-glib.so.8 -> libpoppler-glib.so.8.9.0
	libpoppler.so.74 -> libpoppler.so.74.0.0

**Comment by acuerol** [comment]
Try to build specific Poppler version:

$ cd xournalpp/
$ mkdir build/
$ cd build/
$ cmake-gui ..

Clic on Configure
Check BUILD_POPPLER box
Clic on Generate

$ make poppler

Now, go to ./poppler-prefix/src/poppler/

$ mkdir build/
$ cd build/
$ cmake ..
$ make 
$ sudo make install

Now in xournalpp/build/

$ make
$ sudo make install

Finally,
$ sudo /sbin/ldconfig -v

**Comment by piegamesde** [comment]
I tried it out on git master. Nothing changed

**Comment by golvok** [comment]
what do you mean by that you tried it out on master? I had the same problem, and I just re-installed the AUR package (which involves rebuilding of course) and it started working again...

**Comment by piegamesde** [comment]
I tried the steps acuerol suggested on different branches first. I also reinstalled the AUR package and it didn't help.
