### ISSUE TITLE
Possible touchscreen bug after #2435 commits

### ISSUE THREAD

**Issue by Fef0** [xournalpp/xournalpp#2626]
**Affects versions :**
 - OS: Arch Linux with Gnome on X
 - Version of Xournal++: latest commit

**Describe the bug**
Probably after the commits related to #2435, when you disable the touchscreen from the input settings the touch scrolling is still active.

**To Reproduce**
1. Disable the touchscreen from input systems
2. Try to scroll on a page

**Expected behavior**
As it used to happen, when you disable the touchscreen from the settings then the scrolling must be disabled completely. This helps for tablets that actually have not-so-great palm rejection (enabling the hand recognition from xournalpp settings doesn't help).

**Comment by Fef0** [comment]
Hey @personalizedrefrigerator since you worked on the new functionalities, is that expected?

**Comment by personalizedrefrigerator** [comment]
@Fef0 I can't reproduce this... 

Is this how you're disabling touch input?
![image](https://user-images.githubusercontent.com/46334387/103896417-c8e24f80-50a6-11eb-9680-d672e37665ee.png)

Thank you for reporting this!

**Comment by Fef0** [comment]
Yes, that's how I'm disabling it.
It worked before so I think that something happened somewhere.
![Screenshot from 2021-01-07 14-25-04](https://user-images.githubusercontent.com/19290442/103897930-79c30b80-50f4-11eb-9536-dce93e6e9e1a.png)

**Comment by personalizedrefrigerator** [comment]
@Fef0 Would you be willing to `mv ~/.config/xournalpp ~/.config/xournalpp_backup` and test with the most recent AppImage?

**Comment by personalizedrefrigerator** [comment]
I think I found the issue!!!

In `MainWindow.h`, ```std::atomic_bool gtkTouchscreenScrollingEnableds;``` is left un-initialized!!!

**Comment by Fef0** [comment]
@personalizedrefrigerator nice, I'm already on the latest release compiled just this morning from source so it might be definitely the issue you just addressed

**Comment by personalizedrefrigerator** [comment]
@Fef0 Would you be willing to check whether changing MainWindow.h, line 177 from ```std::atomic_bool gtkTouchscreenScrollingEnableds;``` to  ```std::atomic_bool gtkTouchscreenScrollingEnableds {true};``` fixes the issue?

**Comment by Fef0** [comment]
@personalizedrefrigerator I confirm that it works with the latest commit, thank you very much!
