### ISSUE TITLE
Xournal++ crashes constantly

### ISSUE THREAD

**Issue by GODxEVO** [xournalpp/xournalpp#2629]
**v1.0.19 (Oct 21 2020) :**
 - OS: Windows 10 Home
 - Which version of libgtk do you use
     3.24.23
 - Version of Xournal++: 1.0.19, commit: d376e7a6
 - Installation method: installed with installer

**Describe the bug**
I am using Windows 10 Home and every now and then (like every 5-10min) the xournalapp crashes. Sometime it crashes when I scroll using the hand feature. 
I am using a Huion Tablet as input Method if that helps.
i don't know what could cause the problem, i tried doing my best to fix it on my own (trying other settings, only running xournal++ and nothing else) but it keeps happening.
Is there some type of crash report i can look into? 

**To Reproduce**
In my cause just open xournal++ and scroll a little bit with the hand tool or just leave xournal open for like 5min and it will crash.

**Expected behavior**
xournal++ crashes.

**Comment by Febbe** [comment]
can you retry it with version 1.0.20?
Also appending the crashlog would be good.

**Comment by GODxEVO** [comment]
where can i find the crashlog?
Otherwise i just noticed, that when i run xournal++ with the command prompt , it doesn't seem to crash, I have to try it again for a longer working period, tho.

and sure thing i will try it with 1.0.20

**Comment by Febbe** [comment]
You can find it either in homedir/. xournalpp or ~/AppData/Local/com.github.xournalpp.xournalpp

**Comment by GODxEVO** [comment]
I couldnt find a folder in ~/AppData/Local/com.github.xournalpp.xournalpp

And the errorlogs folder in homedir/.xournalapp was empty.
Any idea why that could be?

**Comment by GODxEVO** [comment]
Update:
I tried v1.0.20 but it still keeps crashing.
Errorlogs folder is still empty.

**Comment by GODxEVO** [comment]
Note:
It seems like xournal++ only crashes when I use the handtool for scrolling.

**Comment by rolandlo** [comment]
Please activate the new input system. This looks like another duplicate of #2306.

**Comment by GODxEVO** [comment]
I'll give it a try and report my results soon!

**Comment by GODxEVO** [comment]
Activating new input system seems to work no crash for now. Thank you for the help.

**Comment by egl-1-rul** [comment]
Sorry, I have the same problem however I can't seem to find the "new input system". Can someone help me ?
I tried going to Edit > Preferences > Input system. What do I do next ? I am using version 1.1.3 and libgtk 3.24.34

**Comment by Febbe** [comment]
> Sorry, I have the same problem however I can't seem to find the "new input system". Can someone help me ?
> I tried going to Edit > Preferences > Input system. What do I do next ? I am using version 1.1.3 and libgtk 3.24.34

Your crashed and those described here, are unrelated, since the new input system is activated by default. The old ist removed
