### ISSUE TITLE
Regression: Pages not rendered when Gtk Touch Workaround Disabled

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2631]
**Affects versions :**
 - OS: Linux (KDE Neon)
 - (Linux only) Desktop environment: Plasma/X11
 -  libgtk 3.22.30 and 3.24.23
 - Version of Xournal++: 1.1.0+dev (commit 94d93c9cf7bb75a58d7eab1b6f9a94e6b1a0cd07)
 - Built from source and also occurs with nightly AppImage

**Describe the bug**
Regions of the screen that must be scrolled to are not rendered.

**To Reproduce**
1. Disable the touch workaround
2. Open a document
3. Move the view to a different part of the document

**Expected behavior**
I should be able to see the part of the page I tried to scroll to.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/46334387/103977070-4a7cc080-512d-11eb-864a-0b3a5162b1b4.png)
![image](https://user-images.githubusercontent.com/46334387/103977010-1c977c00-512d-11eb-9063-f0d0c3499cd5.png)

**Comment by personalizedrefrigerator** [comment]
@Febbe Please look at this.

**Comment by rolandlo** [comment]
I can confirm. This only happened to me after updating today.

**Comment by rolandlo** [comment]
PR #2633 fixes this regression.

**Comment by Febbe** [comment]
jet the touch workaround is completelly messed up.

**Comment by rolandlo** [comment]
@Febbe You tried to fix the touch workaround, but some of your changes had impact on the mode without touch workaround. If you think the fixed version is wrong for the touch workaround, then we could make a case distinction in `gtk_xournal_get_preferred_width` and `gtk_xournal_get_preferred_height`.
