### ISSUE TITLE
How to configure GUI language ?

### ISSUE THREAD

**Issue by bvisi** [xournalpp/xournalpp#2637]
Hello,

I can't get Xournal++ to display menus in french. I'm using Linux Mint (based on Ubuntu 20.04) and I have tried the FlatPak package and the the one from apandada1 repository, but in both cases, everything remains in english. I guess I have to manually configure something, but I don't know what. Can someone give me a starting point ?

Thanx,

BV

**Comment by rolandlo** [comment]
Do you have a directory `/usr/share/locale/fr_FR/LC_MESSAGES/` That's where your French localization should be stored. Xournal++ version 1.0.20 (or older) tries to use the system language. You can't choose the language from the gui. 
In Xournal++ version 1.1.0+dev you can select the language from the GUI (language panel in menu edit->preferences)

**Comment by bvisi** [comment]
That's exactly what I needed to know ! I moved the file xournalpp.mo from fr_FR to fr_CA and I'm good to. Thank you very much.

**Comment by GravuTrad** [comment]
Installer must do it alone. Strange to have to do it ourself manually.
