### ISSUE TITLE
Does not build with poppler 0.64.0 due to const chages

### ISSUE THREAD

**Issue by golvok** [xournalpp/xournalpp#264]
The update contained some const fixes... see https://poppler.freedesktop.org/releases.html

I'm just starting to work on a patch now

(if anyone else is farther along, please let me know. I don't see anything here https://github.com/xournalpp/xournalpp/network)

**Comment by eages** [comment]
Looks like I chose exactly the wrong time to try out xournalpp. Thanks for working on this, looking forward to trying your commit.

**Comment by andreasb242** [comment]
This should be fixed now (if not, reopen the ticket)
