### ISSUE TITLE
Any empty lines in a LaTeX edit box doesn't allow for it to be compiled

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2650]
Windows 10, version 1.1.0. If you open a new "Add/edit TeX" box (or open an existing one), and have an empty line, the compiler refuses to compile to source. I don't know if this is a problem with the compiler, or with Xournal++ itself, or what is supposed to happen.

**Comment by rolandlo** [comment]
Does that only happen in Math mode (which you are put into right from the start)? Then this is normal, I think. My LaTeX editor also doesn't show different behavior.

**Comment by DUOLabs333** [comment]
Yes. If this is normal, I guess you can work around it by parsing the string before passing it to the LaTeX compiler to remove "\n" characters.
