### ISSUE TITLE
Landscape orientation

### ISSUE THREAD

**Issue by runesen** [xournalpp/xournalpp#2657]
Hi, is there any way I can use Xournal++ in landscape mode? I am using the app for notetaking, i.e., I am writing on a blank piece of "paper" (which I'd like to be in landscape orientation).

**Comment by rolandlo** [comment]
Yes, there is. Menu Journal -> Paper format. In the dialog you should see a landscape symbol.

**Comment by runesen** [comment]
Wow, that was fast. Thanks a lot!

On 12 Jan 2021, at 16.52, Roland Lötscher <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes, there is. Menu Journal -> Paper format. In the dialog you should see a landscape symbol.
