### ISSUE TITLE
Xournal++ crashes all the time with a Gaomon Tablet M106k Pro

### ISSUE THREAD

**Issue by Engehausen** [xournalpp/xournalpp#2662]
**Affects versions :**
 - Windows 7
 - Version of Xournal++ [1.0.20 / 17 Dec 2020]

**Describe the bug**
A soon as I touch the pen on the tablet to draw in Xournal++ the program crashes. See additional context.

**To Reproduce**
1. Start program
2. Pick up pen (Gaomon M106k Pro)
3. Try to draw
--> Xournal crashes

I also tried different settings in the preferences. It just crashes. It's interesting that xournal also crashes (see additional context2), but you see the stroke before xournal crashes. It might be related. No other application crashed so fare using this tablet.

**Additional context**
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	**xournalpp_bin.exe**
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5fdb93e7
  Fehlermodulname:	libgdk-3-0.dll
  Fehlermodulversion:	3.24.23.0
  Fehlermodulzeitstempel:	00000000
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	0000000000023c29
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	9260
  Zusatzinformation 2:	926049112ab165f955fbfc232c496108
  Zusatzinformation 3:	e350
  Zusatzinformation 4:	e350ef1ec07efdb9565f71a7defeafcf

---------------
**Additional context2 (maybe related)**
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	**xournal.exe**
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5e5896be
  Fehlermodulname:	xournal.exe
  Fehlermodulversion:	0.0.0.0
  Fehlermodulzeitstempel:	5e5896be
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	00036304
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by rolandlo** [comment]
Windows 7 is not supported from what I know.

From the About:
> Xournal++ is a handwriting notetaking software with PDF annotation support. Written in C++ with GTK3, supporting Linux (e.g. Ubuntu, Debian, Arch, SUSE), macOS and Windows 10.

**Comment by Engehausen** [comment]
Oh no! :-( ... Okay, this issue can be closed ... (I can confirm that Xournal++ works with Windows 10 with this Gaomon Tablet.)

**Comment by justproblems** [comment]
I unse the same graphic tablet under Windows10 and Xournal++ crashes. Therefore it's not just Win10 that solved this problem.

**Comment by Engehausen** [comment]
This is quite sad ... :-(

**Comment by justproblems** [comment]
> This is quite sad ... :-(

Did you do anything else but installing the Gaomon driver and Xournal++ to solve this problem?

**Comment by rolandlo** [comment]
There is a driver issue on some Gamon Tablets, see #3117 and the [upstream issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3860). Maybe it is fixed in Gtk 3.24.30 which will soon make it into Xournal++. For a current workaround check out [this advice](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907)

**Comment by lb90** [comment]
Hi! This Wintab input issue [has been fixed](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3644), the fix will be available in the next GTK3 release (3.24.31).

For now you can use the Windows Ink input as explained by Roland

**Comment by justproblems** [comment]
> For a current workaround check out [this advice](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907)

Thanks. That worked for me.
