### ISSUE TITLE
Snapping doesn't work when moving selected objects.

### ISSUE THREAD

**Issue by cuppajoeman** [xournalpp/xournalpp#2669]
It's annoying when you try to move stuff in a graph because it doesn't line up

**Comment by rolandlo** [comment]
Please read about how snapping works when moving selected objects in #2011. If you give me an example where it doesn't work, I will explain you why.

**Comment by cuppajoeman** [comment]
This is what I'm experiencing right now, which seems a little weird compared to #2011

![image](https://i.imgur.com/ZAcljAp.gif)

**Comment by cuppajoeman** [comment]
![image](https://user-images.githubusercontent.com/19198104/104643326-41827680-567a-11eb-9f10-9e98477e65fb.png)

**Comment by rolandlo** [comment]
Well, you need version 1.1.0+dev to profit from the snapping enhancements #2011.

**Comment by cuppajoeman** [comment]
Oh I see. I am learning new things about github every day, this is the version that your work applies to right?

![image](https://user-images.githubusercontent.com/19198104/104644193-72af7680-567b-11eb-9cf1-d99dac8e19ee.png)

**Comment by rolandlo** [comment]
That is only the milestone, but yes for the correct version. You can download Xournal++ 1.1.0+dev from the releases page (nightly tag) https://github.com/xournalpp/xournalpp/releases/tag/nightly
