### ISSUE TITLE
Layer sidebar uses "page" wording

### ISSUE THREAD

**Issue by mjg** [xournalpp/xournalpp#2672]
**Affects versions :**
 - OS: Linux Fedora 33
 - Desktop environment: X11/i3
 - Which version of libgtk do you use:  3.24.24
 - Version of Xournal++: 1.1.0+dev (current master at 1b718289)
 - Installation method: built from git

**Describe the bug**
The sidebar has three different views/tabs (`AbstractSidebarPage` in code): bookmarks, pages and layers. The tooltips for the buttons (copy, move up/down, delete) always refer to "pages" even when the layers tab is selected and they in fact operate on layers.

**To Reproduce**
1. open an empty file
2. create a second layer
3. switch the sidebar to layers
4. observe the tooltips and check that the buttons work on layers (e.g. copy), not pages

**Expected behavior**
I expect the tooltips to refer to "layers" when the button operates on layers.

**Additional context**
`Sidebar::setSelectedPage()` in `src/gui/sidebar/Sidebar.cpp` needs to switch the button tooltips, I just don't know where to put the additional strings ("Swap the current layer ...") in glade or in code. Alternatively, having different button bars (with appropriate tooltips) and toggling their visibility might be cleaner.

Also, I noticed the following: if you have a PDF with bookmarks (so that the bookmarks sidebar is usable) then switching between the three tabs is somewhat wonky: sometimes the buttons show up in the bookmarks view (but do nothing), sometimes the empty replacement for the buttons (which is the right one for the bookmarks view) shows up for the pages view and get's replaced by the buttons only when I switch from page to layers. So something else may be wrong, too, and the "cleaner" approach mentioned above is already implemented partially (?).

I'm no c++ expert, but the hand rolled index increment in the range for of the mentioned method seems - in terms of wonkyness - to correspond to the button bar behaviour ;-)

**Comment by hyperupcall** [comment]
This has been fixed by https://github.com/xournalpp/xournalpp/pull/2776. Can someone please close this?
