### ISSUE TITLE
To many different icon styles

### ISSUE THREAD

**Issue by daholzfeind** [xournalpp/xournalpp#2676]
**Is your feature request related to a problem? Please describe.**
Not a technical but a design problem. 

**Describe the solution you'd like**
A consistent icon design. 

**Additional context**
![toolbar](https://user-images.githubusercontent.com/22816159/104851142-7e0cd700-58f3-11eb-898d-be2782c2147d.jpg)
I use Xournal++ on different OS, with different desktop environments. I think Xournal++ should use a consistent icon design strategy. In the screenshot below you can see how many different icon styles in the default toolbar are used. One can clearly see that some of them seems to be from the same author, e.g., eraser, fill, rotate, ..., while others, e.g., the pencil doesn't fit at all into the toolbar design. The fine stroke is just a black dot in the dark theme variant, this seems to be a bug. 

Overall i found a PR that works on a new icon set: https://github.com/xournalpp/xournalpp/pull/1735 
Maybe this could be the new default icon set, would be nice enhancement of Xournal++.

**Comment by rolandlo** [comment]
Switching to the icon set (3 variants) from PR #1735 is the plan. It just takes some time to integrate it fully into Xournal++.

**Comment by rolandlo** [comment]
Fixed by #3154.
