### ISSUE TITLE
Ctrl+Del shortcut should conform to usual text editing conventions

### ISSUE THREAD

**Issue by schachmett** [xournalpp/xournalpp#2679]
_This comment was edited: Ctrl+Backspace is actually working while Ctrl+Del is not. In the original comment, I accidentally got that backwards_

**Affects versions :**
OS: Linux Ubuntu 20.04 (Gnome)
Versions: Xournal++ 1.0.20,  libgtk: 3.24.20 
Installation method: I think it was regular apt official release

**Describe the bug**
Xournalpp overwrites the default Ctrl+Del shortcut. Usually, Ctrl+Del deletes the word succeeding the cursor. Xournal++ however overwrites this so that it deletes the current page.

**To Reproduce**
1. add a text field to a document
2. write something
3. hit Ctrl+Del
4. the page disappears (not sure if this is also the case in single-page documents)

**Expected behavior**
The word succeeding the cursor should be deleted

**Describe the solution you'd like**
Please remove the current Ctrl+Del shortcut or change it to different keys. The default functionality should then automatically work (I guess the OS does this).

**Additional context**
I use Xournal++ mainly for annotating and highlighting regular pdfs, so I use the text feature often. It can be a bit of a shock when you are typing something and suddenly the whole page vanishes. It can also lead to severe data loss, depending on when you figure out what happened.
For Ctrl+Backspace, the word preceding the cursor is deleted. This is the normal behavior and is working as expected in Xournal++.

Sorry if this is in the wrong category. I was not sure if this is bug or a feature request. To me it feels like a bug.

**Comment by personalizedrefrigerator** [comment]
For me, Ctrl+Backspace works, but Ctrl+Del doesn't (it deletes the current page). I'm running KDE Neon/Plasma X11 and Xournal built from a recent commit.

Please try version 1.1.0+dev. Nightly AppImages can be found here: https://github.com/xournalpp/xournalpp/releases/tag/nightly.

**Comment by personalizedrefrigerator** [comment]
Related issue: https://github.com/xournalpp/xournalpp/issues/919

**Comment by schachmett** [comment]
Thank you and sorry, I actually meant it the other way around. Ctrl+Backspace works, but Ctrl+Del does not.
Would it be enough to just change the glade file? What would be a sensible alternative? Maybe Ctrl+Shift+Del?
If that would be all it takes and if it is okay to just change this shortcut, I could make a PR.
