### ISSUE TITLE
Background is deleted on file when overwriting original PDF file

### ISSUE THREAD

**Issue by oconnellamethyst** [xournalpp/xournalpp#268]
When saving a PDF file from xournal over the original pdf, all of the information in the original PDF is deleted, which saves a strange file with just the changes.

**Comment by fzhu2e** [comment]
Thanks for the nice work on Xournal++. I think that overwriting the original PDF file is a necessary feature, otherwise we have to save multiple PDF files every time we make annotations. Is that possible to get this feature?

**Comment by andreasb242** [comment]
Technical yes, but I don't currently see any reason to overwrite the original background, then you have the annotations twice, once on the background, and once on the Xournal++ file.
You can replace the background at any time with a file manager.

**Comment by fzhu2e** [comment]
Thanks for the reply! 

I hope Xournal++ could eventually be a PDF reader like PDF Expert, which is not available on Linux. Foxit PDF reader is capable of full feature annotation, but with a bad support for active stylus and markup rendering, while Xournal++ has advantages regarding these aspects. I guess the critical feature is to enable editing previous markups exported to a PDF file. If that is feasible, then it would make much sense to add the "overwriting background" feature.

The own format of Xournal++ works fine, but my own experience with apps like Notability is that, app-specific format is not a safe plan for long-term note taking. Once I stop using Notability, I basically lost my old notes, at least I cannot erase my old markups anymore with a image-like PDF file. So, for the long-term, the best format for markups is still PDF. That is basically the reason I am not willing to use the own format of Xournal for serious purpose.

**Comment by LittleHuba** [comment]
As far as I know Poppler (the library we use for handling PDF) still has some problems working with annotations. But that could have changed between when I looked that up and now.

**Comment by andreasb242** [comment]
https://people.freedesktop.org/~ajohnson/docs/poppler-glib/PopplerAnnot.html#poppler-annot-callout-line-new


May this will be possible, but this also means: you can not add new pages, you can only add annotations to existing pages.

**Comment by fzhu2e** [comment]
When the scenario is pure note taking or scratching, I find the own format of Xournal++ is not bad, and exporting to PDF for the long-term archive is enough.

I believe for many programmers/engineers/scientists, PDF annotation is the first priority, plus that a nicely-done app is currently missing on Linux. Xournal++ could make those 2-in-1 laptops running Linux a perfect device for both intensive serious work and PDF reading in tablet mode.

**Comment by embeddedt** [comment]
Xournal++ works well for adding simple annotations (like text) to a PDF file and re-exporting it, but as mentioned above, you have to manually replace the original PDF afterwards.

The solution proposed in https://github.com/xournalpp/xournalpp/issues/268#issuecomment-467618823 seems relatively straightforward to implement (it could even be done with an external wrapper) and would work well, in my opinion, for the needs of many users.

**Comment by kacperkan** [comment]
Regarding the [#268 (comment)](https://github.com/xournalpp/xournalpp/issues/268#issuecomment-467618823), I wrote a small bash script that uses `inotify-tools` (`apt-get install inotify-tools on Debian based systems):

```bash
#!/bin/bash

pdfFile=$1
baseNameFile=`basename "${pdfFile}"`
xoppFile="/tmp/xopp/${baseNameFile}.xopp"

mkdir /tmp/xopp

cp "${pdfFile}" "/tmp/xopp/${baseNameFile}"

o=$IFS
IFS=$(echo -en "\n\b")
inotifywait -m /tmp/xopp/ -e create -e moved_to |
    while true
    do
        for f in `ls "/tmp/xopp"`;
        do
            if [[ ${f} == "${baseNameFile}.xopp"  ]]
            then
                echo "Monitoring ${f}"
                inotifywait -e modify "${xoppFile}" | xournalpp ${xoppFile} -p ${pdfFile}
            fi;
        done
    done &

IFS=${o}
xournalpp "/tmp/xopp/${baseNameFile}" || rm "/tmp/xopp/${baseNameFile}"  "/tmp/xopp/${baseNameFile}.xopp"
```
Let me know, if the script can be improved. Generally, it implements mentioned idea.

The script (let's say, saved as `annotate.sh`) is used as:
```bash
./annotate.sh <pdf-to-annotate>.pdf
```
The annotation file should be then saved in `/tmp/xopp/<pdf-to-annotate>.pdf.xopp`. Such a path is selected automatically if you press `Ctrl+S` and then `Enter` on Ubuntu.

**Comment by embeddedt** [comment]
It would be great if the script could then convert that `.xopp` file back to a PDF and overwrite the input file.

**Comment by kacperkan** [comment]
But this is exactly what that script does:
1. It copies the original pdf file to `/tmp/xopp`
2. Runs it in `xournalpp`
3. All the operations and annotations are executed on that copy.
4. You have to then save the `xopp` file in the form `<original-name>.pdf.xopp` in `/tmp/xopp`
5. Now, on every save of `<original-name>.pdf.xopp`, the script will export the annotated pdf and overwrite the original pdf.

**Comment by embeddedt** [comment]
Whoops, sorry. I wrote that reply late at night and evidently missed reading half of the script.

**Comment by Mosfak** [comment]
> Regarding the [#268 (comment)](https://github.com/xournalpp/xournalpp/issues/268#issuecomment-467618823), I wrote a small bash script that uses `inotify-tools` (`apt-get install inotify-tools` on Debian based systems):
> 
> ```shell
> #!/bin/bash
> 
> pdfFile=$1
> baseNameFile=`basename "${pdfFile}"`
> xoppFile="/tmp/xopp/${baseNameFile}.xopp"
> 
> mkdir /tmp/xopp
> 
> cp "${pdfFile}" "/tmp/xopp/${baseNameFile}"
> 
> o=$IFS
> IFS=$(echo -en "\n\b")
> inotifywait -m /tmp/xopp/ -e create -e moved_to |
>     while true
>     do
>         for f in `ls "/tmp/xopp"`;
>         do
>             if [[ ${f} == "${baseNameFile}.xopp"  ]]
>             then
>                 echo "Monitoring ${f}"
>                 inotifywait -e modify "${xoppFile}" | xournalpp ${xoppFile} -p ${pdfFile}
>             fi;
>         done
>     done &
> 
> IFS=${o}
> xournalpp "/tmp/xopp/${baseNameFile}" || rm "/tmp/xopp/${baseNameFile}"  "/tmp/xopp/${baseNameFile}.xopp"
> ```
> 
> Let me know, if the script can be improved. Generally, it implements mentioned idea.
> 
> The script (let's say, saved as `annotate.sh`) is used as:
> 
> ```shell
> ./annotate.sh <pdf-to-annotate>.pdf
> ```
> 
> The annotation file should be then saved in `/tmp/xopp/<pdf-to-annotate>.pdf.xopp`. Such a path is selected automatically if you press `Ctrl+S` and then `Enter` on Ubuntu.


Original Author of the Script:  https://github.com/xournalpp/xournalpp/issues/268#issuecomment-608449929

**Xournalpp** is an awesome tool for **annotating** pdf. But there is one problem.
You can't save the file as pdf  but you can export the file as pdf.
But that is a problem too. 
When Exporting a pdf you **can't overwrite** the original file you opened as that is being used as background for the .xopp file . 
**Result**:
- copies the pdf opend by xournalpp to /temp/xopp folder
- there you create .xopp file
- so it uses the pdf file located in /temp/xopp folder as background
- and you can safely overwrite the file you opened

**Let's Get Started:**
Create a file called annonate.sh on location "/home/$USER/reserved/programs/"
This location could be anywhere you feel comfortable.
which contains the following code:

```
#!/bin/bash
if [ "$1" == "" ]
  then  xournalpp    
  exit
fi

pdfFile=$1
baseNameFile=`basename "${pdfFile}"`
xoppFile="/home/$USER/temp/xopp/${baseNameFile}.xopp"

mkdir /home/$USER/temp/xopp

cp "${pdfFile}" "/home/$USER/temp/xopp/${baseNameFile}"

o=$IFS
IFS=$(echo -en "\n\b")
inotifywait -m /home/$USER/temp/xopp/ -e create -e moved_to |
    while true
    do
        for f in `ls "/home/$USER/temp/xopp"`;
        do
            if [[ ${f} == "${baseNameFile}.xopp"  ]]
            then
                echo "Monitoring ${f}"
                inotifywait -e modify "${xoppFile}" | xournalpp ${xoppFile} -p ${pdfFile}
            fi;
        done
    done &

IFS=${o}
xournalpp "/home/$USER/temp/xopp/${baseNameFile}" || rm "/home/$USER/temp/xopp/${baseNameFile}"  "/home/$USER/temp/xopp/${baseNameFile}.xopp"
```
Then execute this annonate.sh as ./annonate.sh <file name.pdf> 

**To automate** this boring thing edit .bashrc file :
```
alias pdf="/home/$USER/Reserved/programs/annotate.sh"
```
and add this line at the end. which creates a shortcut for **execution** of above file. 

Now all you have to do is type "pdf <filename.pdf>" to open the pdf in xournalpp . Which will do the following:
- This command will create a directory /temp/xopp in your home directory
- copy filename.pdf file to /temp/xopp 
- sets default save directory to /temp/xopp , so when you press ctrl+s it directs to to /temp/xopp to save the temporary .xopp file in /temp/xopp .
- And finally the main intention behind all of this which is to let you overwrite the file you just opened with xournalpp to annotate by exporting as pdf in the same directory.


If you use xournalpp primarily for annonating pdf or just want to avoid typing in terminal all the time I would suggest to edit the desktop entry of xournalpp app and replace the command with:
```
/home/$USER/reserved/programs/annotate.sh %f
```
if you can't find the desktop entry it is usually located in /home/$USER/.local/share/applications 

Good Luck!
