### ISSUE TITLE
the "x" icon in a selection is too small

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#2685]
It looks like recently (last few weeks, maybe a couple of months), the "x" icon that shows up in the top left corner when one makes a selection and that can be used to cut/get-rid off the selected stuff, was made smaller. 
Could this be undone? on 4k laptop screens (eg. x1 yoga) this "x" is too small and next to impossible to click. 
I would vote for the icon to be made much larger.. 2 or even 3 times as large.... 
I'm attaching a screenshot so that it's clearer what I'm talking about. 

Thanks!
![screenshot_1](https://user-images.githubusercontent.com/4156234/105281815-92aad280-5b72-11eb-92c4-87230caee970.png)

PS. Having this icon there is a really great idea and is very useful... another thing that could be nice would be to have another icon/button that would "copy" the selection.

**Comment by rolandlo** [comment]
The size of the anchors and "x" icon for selections depends on your dpi setting in the Zoom panel of the preferences. The default value is 72, which is usually much lower than what you really have. You could adjust that value. Note however, that this will currently create trouble with how font sizes are displayed/stored (a problem which will be solved with PR #2182). If you don't need the text tool (much), that would solve your problem right now.

**Comment by petergthatsme** [comment]
ok, thanks for clarifying that. Will close this, given that the other issue is already being tracked.
