### ISSUE TITLE
Crash: Invalid enum value for ActionType: «ACTION_AUDIO_SEEK_BACKWARDS

### ISSUE THREAD

**Issue by unhandyandy** [xournalpp/xournalpp#2688]
**Affects versions :**
 - OS: Linux
 - (Linux only)     OpenBox
 - Which version of libgtk do you use
    3.24.23
 - Version of Xournal++:
     1.0.20-hotfix
 - Installation method: 
      git clone, built deb for Ubuntu 20.10

**Describe the bug**
Crashes on startup
```
$ xournalpp
ALSA lib pcm_dsnoop.c:642:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

** (com.github.xournalpp.xournalpp:13958): ERROR **: 13:05:56.579: Invalid enum value for ActionType: «ACTION_AUDIO_SEEK_BACKWARDS»
Trace/breakpoint trap (core dumped)
```

**Comment by rolandlo** [comment]
This is an incompatibility between the Xournal++ version you run and the `main.glade` file that is installed on your system (either in `/usr/share/xournalpp/ui/main.glade` or `~/.local/share/xournalpp/ui/main.glade`). In the glade file you will see that `menuAudioSeekBackwards` is passing `ACTION_AUDIO_SEEK_BACKWARDS` to the `activate` signal. This should be handled in `Control::actionPerformed`, but it is not in version 1.0.x. I hope this helps.

**Comment by rolandlo** [comment]
Try running `xournalpp` from a different folder. This can influence which `main.glade` file is picked.

**Comment by unhandyandy** [comment]
Thanks, that helped.

But now I've discovered the bug with the preferences pane is back:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2363767/105401190-e4477180-5bf3-11eb-9345-c18d98eda8d8.png">

**Comment by rolandlo** [comment]
I don't quite remember when that was reported and when and how it was fixed. Maybe it was only fixed in version 1.1.0+dev. You now have version 1.0.20.

**Comment by unhandyandy** [comment]
And in v. 1.0.20-hotfix, how do I set the location of default_template.tex?

**Comment by unhandyandy** [comment]
But the git clone doesn't show tags for v. 1.1.

**Comment by rolandlo** [comment]
There is no v1.1.? tag because version 1.1.0 has not yet been released. The master branch yields the 1.1.0+dev version.

**Comment by unhandyandy** [comment]
Ah, sorry, thanks.

**Comment by rolandlo** [comment]
> And in v. 1.0.20-hotfix, how do I set the location of default_template.tex?

The LaTeX enhancements are only part of version 1.1.0+dev, not of version 1.0.x.

**Comment by unhandyandy** [comment]
By the way, I want to sincerely thank you for xournalpp, I've been using it almost every day during covid to prepare lecture slides.  Is there some way I can make a contribution?

**Comment by rolandlo** [comment]
I am glad you like Xournal++. Some ideas how to make a contribution can be found in #2045. Contributions to the [website](https://xournalpp.github.io/) are particulary welcome at this stage. The completed website will help a lot of users to use Xournal++ better. If you have some programming skills you may also look into completing PR #2408 (creating a nice presentation mode). It might be useful for you when presenting lecture slides as well.
