### ISSUE TITLE
Ability to draw a perfect circle

### ISSUE THREAD

**Issue by Izerpizer** [xournalpp/xournalpp#2693]
**Is your feature request related to a problem? Please describe.**
Currently when you want to try and draw a circle, you use the "Draw Circle" tool and you drag your cursor and a an ellipse of varying dimensions, depending on where your mouse is appears. This ellipse will have a width and height based on the current position of your cursor with reference to where it was when you first click. This functionality makes it difficult, if not impossible to create a circle which has a uniform radius instead of an ellipse with a varying radius.

**Describe the solution you'd like**
Change the current "Draw Circle" tool to "Draw Ellipse" so that it is more accurate to its functionality. When you draw the ellipse,  if what you are drawing is close to the shape of a perfect circle, it will automatically snap to a perfect circle. 

**Describe alternatives you've considered**
Another option is another snapping setting that is specifically for the snapping of shapes that can be toggled. This would allow the user the ability to disable the perfect shape snapping if they, in reality, want a shape that is close to the snapping point of the shape/circle.

**Additional context**
This feature could be expanded to other shapes as well. For example, with the "Draw Rectangle" tool, it is difficult, if not impossible, to draw a perfect square. With this feature, if you are close to the shape of a square, the tool will snap to the shape of the square.

**Comment by rolandlo** [comment]
You can draw a perfect circle in two ways:
1) With keyboard: Holding `Shift` while drawing the ellipsis
2) Without keyboard: Activate using the drawing direction to activate modifiers (in the Drawing Area panel of the preferences). Draw left to get a circle. You can also make the center to be the point from which you start by drawing (left) up. 

See also the explanations on the [website](https://xournalpp.github.io/guide/tools/pen/#shapes-defined-by-two-points)

**Comment by Izerpizer** [comment]
@rolandlo That is glorious! Thank you! 

I do still think that "Draw Circle" should be changed to "Draw Ellipse", though. Its more accurate to what it does.
