### ISSUE TITLE
Change the name of "Draw Circle" to "Draw Ellipse"

### ISSUE THREAD

**Issue by Izerpizer** [xournalpp/xournalpp#2694]
**Is your feature request related to a problem? Please describe.**
It's more accurate to what it does. Follows the same idea as how "Draw Rectangle" is used to draw general rectangles as well as squares which are just special cases of rectangles. A circle is just a special case of an ellipse, so all ellipses shouldn't be called circles. 

**Describe the solution you'd like**
Change the name of the "Draw Circle" tool to "Draw Ellipse".

**Comment by Baseng0815** [comment]
I guess changing the labels would not be enough, we'd also need to change tool names like `ACTION_TOOL_DRAW_CIRCLE` to `ACTION_TOOL_DRAW_ELLIPSE` and class names like `CircleHandler` to `EllipseHandler`. Could this break plugins and other code?

**Comment by rolandlo** [comment]
We don't have official plugins that use ACTION_TOOL_CIRCLE. It may break custom plugins of users, but they are easy to repair. Other than that it should break any code, as long as the Xournal++ version running uses the correct glade files.
