### ISSUE TITLE
Document how to contribute to the project development

### ISSUE THREAD

**Issue by PellelNitram** [xournalpp/xournalpp#270]
I believe that if there was some documentation on how to contribute to this project, this could help speed up the development pace.

There was still some activity in this project this year, visible by all the issues here, and I would be interested in contributing to the project.

However, I have a hard time determining which bits and pieces of the code are relevant and suitable for my - yet - limited C++ skills.

What do you think?

**Comment by andreasb242** [comment]
The project is not really active anymore, therefore I appreciate any help!

You can do a simple bug or improvement, don't matter. You can ask a question in the comments, may mention my name, then I should get a Mail, and I help you.
If you think you got it, create a pull request, then I can review your work, there is an automatically build, which checks if your code still compiles.

You can fork the repo, and create a branch for each try, so if you fail you simple delete the branch. Do only one thing in one branch - if you fail you can simple go back, if you do 3 things in one branch, and one fails, you have to split it...

We all started with limited C++ skills! ;-)

**Comment by andreasb242** [comment]
I documented the Issue #249 which is really easy to start. You can take it if you whish.

**Comment by andreasb242** [comment]
I close this ticket, I'm cleaning up tickets, and here is currently nothing to do anymore.
