### ISSUE TITLE
Pinch-to-zoom results in trembling effect in large PDFs

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#2703]
**Affects versions :**
 - OS: Manjaro
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     3.24.24
 - Version of Xournal++
     01107eb
 - Installation method: AUR

**Describe the bug**
This occurs since the scrolling bug while zooming was fixed. It now just scrolls up and down rapidly which results in a trembling affects.

**To Reproduce**
1. Open large PDF > 50 pages
2. Pinch-to-zoom
3. See the trembling effect

**Comment by Technius** [comment]
Are you sure you're using the right version? ` 1.0.15.r49.gf2535dd5-1` is pretty old.

**Comment by coldspark29** [comment]
Are you referring to the 1.0.15? I guess the version shown in the AUR has not been updated in a while. It actually builds from source. I just did it again and have 01107eb which is the latest commit.

**Comment by Technius** [comment]
Do you know which PR/commit `scrolling bug while zooming was fixed` came from?

**Comment by coldspark29** [comment]
Found it https://github.com/xournalpp/xournalpp/issues/1843. I already forgot about it. @Febbe marked it as fixed and then I complained. Before it was just scrolling up endlessly. I think he did something to make up for the scrolling. It seems like it immediatley scrolls down again. More like a workaround than a fix.

**Comment by personalizedrefrigerator** [comment]
#2435 touched code related to this. See https://github.com/xournalpp/xournalpp/pull/2435#issuecomment-734790455 for the explanation.

This trembling happened prior to the PR, though, when the margin between pages was set to zero.

This may or may not be relevant, but I hope it is useful!

**Comment by coldspark29** [comment]
It is fixed! After all these years :D
