### ISSUE TITLE
Exported PDF file not found

### ISSUE THREAD

**Issue by jerwansyah** [xournalpp/xournalpp#2706]
**Affects versions :**
 - OS: Windows 1909
 - Version of Xournal++: 1.0.20
 - Installation method: Official release for Windows

**Describe the bug**
Exported PDF file is missing. The export options window rarely pops up.

**To Reproduce**
1. Export as PDF

**Expected behavior**
A PDF file should be created.

**Additional context**
I tried exporting a xopp file on an older version so I tried uninstalling that version (I forgot which version but I installed it around September-October of 2020) and installing the latest version. I still can't export it.

**Comment by rolandlo** [comment]
The export options window only pops us if you use "Export as..." rather than "Export as PDF" in menu "File".
Note that version 1.0.20 has a problem with PDF export due to a bug in Cairo, see #2601 . Currently you better use version 1.0.19 if you need PDF export.

**Comment by jerwansyah** [comment]
Thanks rolandlo.

**Comment by bhennion** [comment]
Has this been fixed in 1.1.1 (via an update of cairo)?

**Comment by rolandlo** [comment]
> Has this been fixed in 1.1.1 (via an update of cairo)?

Yes, it has.
