### ISSUE TITLE
Implement a "Save as PDF" button

### ISSUE THREAD

**Issue by jclsn** [xournalpp/xournalpp#2709]
I think it would be really nice to have a button to instantly save as PDF like in Libreoffice.

**Comment by robinp7720** [comment]
There already exists an "Export as PDF" item in the "File" menu to do exactly this

**Comment by coldspark29** [comment]
I know but I want a button. Less clicks, less trouble. It is also more touch friendly.

**Comment by personalizedrefrigerator** [comment]
For anyone interested in working on this, here are some relevant areas of the code!
https://github.com/xournalpp/xournalpp/blob/2e075041db66ba0b776c9556b93c203a41b8f2ae/src/enums/ActionType.enum.h#L27
https://github.com/xournalpp/xournalpp/blob/2e075041db66ba0b776c9556b93c203a41b8f2ae/src/gui/toolbarMenubar/ToolMenuHandler.cpp#L318-L494
https://github.com/xournalpp/xournalpp/blob/2e075041db66ba0b776c9556b93c203a41b8f2ae/src/control/Control.cpp#L363-L942

Additionally, it looks like `ACTION_EXPORT_AS_PDF` already exists! We might be able to implement this by adding something similar to the following to ToolMenuHandler.cpp!
```c++
    ADD_STOCK_ITEM("EXPORT_AS_PDF", ACTION_EXPORT_AS_PDF, "some-gtk-icon-name-here", _("Export as PDF"));
```

I think [this](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names) is a list of icons that `some-gtk-icon-name-here` could be replaced with.

**Comment by bhennion** [comment]
This has been fixed a while back
