### ISSUE TITLE
compiling question for other platforms

### ISSUE THREAD

**Issue by 0lm** [xournalpp/xournalpp#271]
hi there.
thats probably a novice question but.. compiling for windows is not possible at the moment, is it?

**Comment by Febbe** [comment]
All of the used libraries are platform independent, it should work with some configuration changes.

**Comment by andreasb242** [comment]
Try it with Cygwin or Mingw, or try to use the Win10 Linux Subsystem, and install X11 on Windows, should work also

**Comment by andreasb242** [comment]
![xournalpp-win10](https://user-images.githubusercontent.com/822958/49702563-d6902700-fbf9-11e8-81c7-b15a97b40de0.png)

After a lot of small fixes and some Hacks it's running on my Win10 Test Notebook.

My Building notes (but needs a lot of Code changes! I'll need some time to bring this to Master!)

`install msys2-x86_64-20180531.exe

Start Mingw-w64 64bit. NOTHING ELSE!

Update MSYS (do this multiple times,
close Terminal after each update)
$ pacman -Syuu


$ pacman -S git
$ git clone https://github.com/xournalpp/xournalpp.git

$ cd xournalpp/

$ mkdir build
$ cd build/

$ pacman -S mingw-w64-x86_64-cmake 
$ pacman -S make
$ pacman -S mingw-w64-x86_64-toolchain
-> enter -> yes

$ pacman -S mingw-w64-x86_64-gcc

$ pacman -S mingw-w64-x86_64-boost
$ pacman -S mingw-w64-x86_64-poppler

$ pacman -S --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain                     mingw-w64-i686-cmake mingw-w64-x86_64-cmake
-> enter multiple times


$ pacman -S mingw-w64-x86_64-gtk3


cmake -G 'MSYS Makefiles' .. -DENABLE_MATHTEX=OFF


make -j2

`

**Comment by andreasb242** [comment]
The branch with the changes, and some Hacks, therefore can not be merged in this stage:

https://github.com/andreasb242/xournalpp/tree/win-build

**Comment by andreasb242** [comment]
Build on Windows 10 is working, the howto is here:
https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md
