### ISSUE TITLE
Ink and images disappear 

### ISSUE THREAD

**Issue by Joshuaalbert** [xournalpp/xournalpp#2714]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux 5.8.0-34-generic #37~20.04.2-Ubuntu
 - (Linux only) Desktop environment: unsure, default with Ubuntu
 - Which version of libgtk do you use
 - Xournal++ 1.1.0+dev
└──libgtk: 3.24.20
     
 - Installation method: ppa I think. 
 
**Describe the bug**
When annotating a pdf, images and ink disappear.

**To Reproduce**

1. I start by opening the pdf, and writing with a pen. This works fine. 
2. Then I add a few images by clicking on the image icon, clicking on the page, selecting an image, resizing, and pressing escape. 
3. I add two images. On several pages. 
4. Then the third image fails to stay. When I press escape the image disappears. 
5. The previous images and ink remain however.
5. I save the progress and restart xournal++. Newly added images still disappear as soon as I add ithem.
6. I also try writting on the page, and the ink disappears about 3 seconds after I write it.
7. While all new additions to the page disappear, the original ink and two images stay.

**Expected behavior**

I should be able to write and add as many images as desired.

**Comment by redweasel** [comment]
can you try to recude the reproduce description to the bare minimum? I can not reproduce this on a similar system as yours. Maybe also try different images and if it is specific to some images try to include information on those or upload them if you can.

Also can you post the commit from the about dialog of xournalpp, because 1.1.0+dev doesn't really say anything except that it is no official release.

**Comment by Joshuaalbert** [comment]
I just inspected the pdf I was operating on, and it seems that during one of the edit operations it became corrupt. I loaded the original copy of the pdf and the problem is now gone. What I can conclude is that the corruption of the pdf is the culprit but that will be hard to track down without a debugger running while it happens. You can close this then.
