### ISSUE TITLE
Crash on erasing ghost strokes after undo of copy action

### ISSUE THREAD

**Issue by redweasel** [xournalpp/xournalpp#2720]
**Affects versions :**
 - OS: Linux Debian testing
 - Desktop environment: X11
 - libgtk version: 3.24.24
 - Version of Xournal++: 1.1.0+dev, commit https://github.com/xournalpp/xournalpp/commit/2e075041db66ba0b776c9556b93c203a41b8f2ae, master
 - Installation method: `make package` then `apt install ...`

**Describe the bug**
Copied strokes sometimes (in a reproducible way) are left behind after undo. The resulting ghost strokes will cause a crash when trying to erase.

Also just for good measure: the bug happens with both input systems (new and old).

**To Reproduce**
1. make any kind of stroke or geometric shape
2. select it
3. copy and move it twice without any other actions inbetween (e.g. use rightclick-move twice)
4. undo everything until the button becomes disabled (note the ghost geometry of the second copy here)
5. try erasing the ghost stroke (standard or delete stroke eraser) -> crash here

**Comment by rolandlo** [comment]
Great, looks like I can reproduce it. That should make it much simpler to find a fix.

**Comment by rolandlo** [comment]
It's even simpler to reproduce the bug. You don't have to copy twice:

0. Start `xournalpp` in the terminal
1. make any kind of stroke or geometric shape
2. select it
3. copy it via mouse right click (you can also move it, but it is not necessary; you can also unselect it at the end, but it is not necessary)
4. undo everything until the button becomes disabled 
5. Observe the message `** (xournalpp:24284): WARNING **: 09:09:16.693: Could not remove element from layer, it's not on the layer!` in the terminal, followed by the backtrace.

**Comment by rolandlo** [comment]
I think I have found the root of the problem:
After the selection is copied, we have two elements, the old one and the new one. An undo action is created for inserting the old (!) element, not the new one. If we undo the copy insertion, the old element is removed and the new one is still there. Then we undo the creation of the old element, which is not on the layer anymore.

**Comment by rolandlo** [comment]
@redweasel Could you check out #2733 to see, if it fixes the bug for you as well?
