### ISSUE TITLE
Create a Picture from Camera

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#273]
The newer Tablets not only have a low resolution webcam, they usually have also a high resolution camera on the back, which can be used to take a picture.

Technical I'm currently thinking starting cheese and get the output image.
I have to check this, or, if there is a better solution: tell me please.

**Comment by andreasb242** [comment]
The camera is not as good as a handy camera. Probably better spend time to the drag & drop handling.

**Comment by andreasb242** [comment]
The Camera is good enough.
May use Cheese: https://help.gnome.org/users/cheese/stable/
https://github.com/GNOME/cheese/blob/master/src/cheese-application.vala

**Comment by LittleHuba** [comment]
I think this is out of scope and better solved using external tools. Additionally I do not see a lot of use cases for this.
