### ISSUE TITLE
CI: clang format pipeline failing -- Unable to install git-clang-format-12

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2731]
**Affects versions :**
 - OS: Azure Pipelines
 - (Linux only) Desktop environment: N/A
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** windows
 - Version of Xournal++: building PR with recent source
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**
![image](https://user-images.githubusercontent.com/46334387/106368670-47c25500-6300-11eb-9c27-cc9e8291c5ca.png)

**To Reproduce**
1. Attempt to run all Azure pipelines

**Expected behavior**
It should be able to install git-clang-format.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/46334387/106368726-b1dafa00-6300-11eb-8c1d-7ecdeeae0b6f.png)

**Comment by Technius** [comment]
The LLVM ubuntu repository is broken. Can't install clang-format on a Ubuntu docker image.

**Comment by Technius** [comment]
Nevermind, it's because we didn't pin the LLVM version.
