### ISSUE TITLE
Adding new pages 

### ISSUE THREAD

**Issue by kgozdziewski** [xournalpp/xournalpp#2734]
**Affects versions :**

 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
recent gentoo, X11
 - Which version of libgtk do you use
 xournalpp --version
Xournal++ 1.1.0+dev
└──libgtk: 3.24.24

 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
 GitHUB version compiled on my system and installed in /usr/local

**Describe the bug**
In the prior version I could resize the window the same as in the current stable version (xournalpp-1.0.20-hotfix). For some time, the code compiled from  the GitHUB source does not make it possible to add a new page without simultaneously resizing the X-window (see figures attached). Also, once a new page is added, I cannot resize the window with mouse, since the window extends vertically. More pages, the window is more extended.

**To Reproduce**
1. Step 1
Get and compile the recent GitHUB version; I admit that lua5.3 and gtk-mac-integration are missing in my system (gentoo), since they are masked and I do not force to include them
[chris@beta]:[..]/xournalpp/build>cmake ..
Found: TRUE
-- Checking for module 'gtk-mac-integration'
--   No package 'gtk-mac-integration' found
-- Checking for module 'lua5.3'
--   No package 'lua5.3' found
-- Checking for module 'lua >= 5.3'
--   No package 'lua' found
Installing desktop files
Configuration:
	Compiler:                   /usr/bin/c++
	CppUnit enabled:            OFF
	Filesystem library:         std::filesystem
-- Configuring done
-- Generating done

Compile and install.

2. Step 2
Open the programme, and  try to add a new page after existing one.

3. Step 3
Try to resize the whole X11 window or change the page; also try to add new pages (before or after the present one).
**Expected behavior**
As in the stable version, or prior to GitHUB version around the middle of January 2021. I regularly clone and re-compile the code, and the problem appeared 2-3 weeks ago (not sure when).

**Screenshots of Problem**

![xournalpp1](https://user-images.githubusercontent.com/47242377/106385361-3a749b80-63d0-11eb-9461-0c762f2ecaa2.png)
![xournalpp2](https://user-images.githubusercontent.com/47242377/106385362-3b0d3200-63d0-11eb-8f29-893f5b08a131.png)

**Additional context**
The bug (if it is a bug) may be related to the missing lua package (its a notorious problem with lua versions on gentoo; now I have 5.1).

Many thanks for your help and hints; Xournal++ is a great software, which I frequently use.

**Comment by rolandlo** [comment]
I can't reproduce the problem on Ubuntu 20.10. It can't have to do anything with the missing lua package, since we only use that for plugins. Could you please try to find out the exact commit, which has introduced the problem? Maybe start with commit 1b7182891b9ccb268d214a9032f88a2fc6804b7d (`git checkout` 1b7182891b9ccb268d214a9032f88a2fc6804b7d). You could also use `git bisect` to find the bad commit.

**Comment by kgozdziewski** [comment]
Many thanks, I am trying to compile the branch 1b71828...
Unfortunately, the same :(

I will try to figure out the last-good commit in the past and will report my findings here.

**Comment by kgozdziewski** [comment]
At the moment, I compiled X++ with the branch 095beaa after
git checkout 095beaa
and it works fine w.r.t. the pages add/scroll behavior. Btw. the right-hand side scrollbar is present and works (I realized that it is missing in the apparently "buggy" version).

At the moment I found the incorrect behavior  in a29b11d. So that may be the right one.

Many thanks, I am very grateful for your time!

**Comment by rolandlo** [comment]
Hmm, that's strange. Commit a29b11d was only supposed to update preview pages. It did not quite fix the problem and got replaced by 4afa20a0b11966d324201f1a450327bb671a8593 (which is similar). 
Maybe try commenting out the line `control->firePageChanged(p);` in `Control::checkChangedDocument` and see if that makes a difference. If it does, try to find which of the `pageChanged` methods causes the problem. It could be `ScrollHandler::pageChanged`, for example.

**Comment by kgozdziewski** [comment]
I did as you advised but there is no change, it does make any difference.

After the program starts, I see the main window with one page slowly expanding vertically. Kind of weird... Unfortunately I am too "short" in GTK/C++ programming for finding a source of this bug/issue.

I reverted to a29b11d and it works again.

Many thanks!

**Comment by kgozdziewski** [comment]
A small update: I compiled the recent github version (as on Jan 30, 2021, commit 02f671d) on OpenSuse Leap15.2. Everything went smoothly and there is not that issue I still have on gentoo. Btw.
Xournal++ 1.1.0+dev
└──libgtk: 3.24.20
cmake found all required packages and libraries.

So it is likely related to a package in my gentoo system.

**Comment by kgozdziewski** [comment]
A new update: This time I compiled the recent github version , commit d1f3d4c9 on a different gentoo  Intel-CPU based machine,

Xournal++ 1.1.0+dev
└──libgtk: 3.24.24

and there is any issue. 

It must be related to a package in my gentoo AMD Ryzen system (the distros are tuned differently).
