### ISSUE TITLE
GTK3-Branch

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#275]
The GTK3 Branch has a lot of differences, e.g. in formatting, which are not really differences.

They should be merged, so the real differences are visible. The GTK2 Support will end some time, so it should be prepared to move to GTK3, as soon as possible. But the master has also some improvements, which are not in the GTK3 Branch.

**Comment by Febbe** [comment]
I also aprechiate to Switch to gtkmm, optionally to gtkmm4 because they switched to stdlib c++11 datastructs. I have the idea to do this with the help of llvm, but i dont know anougth about it. I will look into this after i finished my Bachelor thesis.

**Comment by andreasb242** [comment]
I'm currently wringing a script for diffing, and ignoring e.g comments and formatting.
If there are only small changes, what I expect (i already did some manual diffing) I'll create a build option, to get GTK3 working on the Master.

@Febbe Good Luck for your Bachelor thesis! I already have mine ;-)
(Therefore I didn't work much on Xournal++, as I didn't need it, but now I bought again a Tablet PC...)

**Comment by andreasb242** [comment]
There are really much differences, the formatting int the GTK3 branch is not really consistent, and a lot of improvements are not merged into this branch, therefor it will not be possible to merge this branch in the future... (or only with a lot of work)...
For today I leave it...

**Comment by andreasb242** [comment]
I'm currently merging the GTK3 branch with the master together, my current target is that the master is building with GTK2 and GTK3 (GTK3 is not yet building).

See my current work:
https://github.com/xournalpp/xournalpp/pull/280

**Comment by andreasb242** [comment]
Merged
