### ISSUE TITLE
Add simple possibility to change layer of an object

### ISSUE THREAD

**Issue by Oli72** [xournalpp/xournalpp#2750]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I want to change the layer of an object: I have to cut the object, change the layer, and paste it. But then the position changes.

**Describe the solution you'd like**
It would be nice to have a direct possibility to change the layer of an object, e.g. by a context menu entry.

**Describe alternatives you've considered**
./.

**Additional context**
./.

**Comment by forgottosave** [comment]
I think this would be very useful. I'll take a look at this
