### ISSUE TITLE
Fill icon turns off even though filling is still on

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2752]
**Affects versions :**
 - OS: Ubuntu 20.04, Gnome X11.
 - libgtk: 3.24.21
 - Version of Xournal++: 1.0.20
 - Installation method: Flatpak

**To Reproduce**
1. Select pencil and "fill" option.
2. Draw something.
3. Choose "Select rectangle" tool, select some element with it and delete it.
4. Switch back to pen tool. "Fill" icon is inactive/off but filling is still enabled.

Note: This doesn't happen on PPA on  1.1.0+dev with libgtk: 3.24.20.

Possible reasons could be: it's already fixed in new version, it's a Flatpak issue, libgtk issue(since versions are different), or something else.

**Comment by bhennion** [comment]
This seems to have been fixed on master.
