### ISSUE TITLE
Undoing "insert page" moves user to another page if user is on non-new page

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2757]
**Affects versions :**

 - Ubuntu 20.04, Gnome X11
- Xournal++ 1.1.0+dev
- libgtk: 3.24.20
- PPA

**Description**:
As specified in title.

**To Reproduce**
1. Create a new page in the middle of 2 other pages.
2. Move to a page that is not the new page.
3. Click "Undo page".

Results:
* Xournal++ moves you to the next page in the document. This makes sense if you were on the new page, as it doesn't exist and you need to be moved somewhere(either previous or next page, both make sense). If you were on a different page, you should not be moved at all.

**Expected behavior**
User stays on the same page.

**Comment by p0mm** [comment]
I have reproduced this & would like to work on this.
I agree that you should not be moved if you are no longer on the new page that is deleted & hope to implement this behavior!

**Comment by Technius** [comment]
Fixed by #4875.
