### ISSUE TITLE
GtkPaned eats some touch events when the sidebar is closed

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2759]
**Affects versions :**
 - OS: Linux (Manjaro, Neon)
 - (Linux only) Desktop environment: Plasma/X11
 - Which version of libgtk do you use
     - 3.24.24 and 3.24.23
 - Version of Xournal++: 1.1.0+dev (8efd4e9a790651af439d74ad61c000cae035f737)
 - Installation method: `make`

**Describe the bug**
Closing the sidebar creates a region in which strokes cannot start if writing with a touchscreen<strike>/stylus</strike>.

**To Reproduce**
1. Open Xournal++
2. Move the edge of the sidebar near the center of the screen.
3. Close the sidebar.
4. With touch drawing enabled, where the edge of the sidebar was, touch the screen and swipe right.
<strike>5. At the same location, attempt to start a horizontal stroke using the stylus.</strike>

**Expected behavior**
I should be able to start a horizontal stroke where the edge of the sidebar was.

**Screenshots of Problem**
![The aforementioned region](https://user-images.githubusercontent.com/46334387/107119612-ad04d180-683d-11eb-8905-fdbaa254ffda.png)

**Additional context**
 * I can start horizontal strokes in the above region using a mouse. In settings, if I tell Xournal++ to treat my stylus/touchscreen like a mouse, I still cannot start horizontal strokes in this region.
 * Running `GTK_DEBUG=interactive  ./src/xournalpp`, I see this:
![Gtk inspector: states the paned widget is capturing horizontal swipes.](https://user-images.githubusercontent.com/46334387/107119729-5e0b6c00-683e-11eb-9ade-8525f6c8dc8e.png)
Changing "Capture" to "Bubble" fixes the issue.
![Gtk inspector: Changing 'capture' to 'bubble'](https://user-images.githubusercontent.com/46334387/107119758-7e3b2b00-683e-11eb-8bd5-cf234170ee15.png)

https://user-images.githubusercontent.com/46334387/108098143-de4c8100-7037-11eb-86a8-03c9a1b7f8c4.mp4

**Comment by rolandlo** [comment]
I can't reproduce the problem on Ubuntu 20.10 with libgtk 3.24.23 (neither on Wayland nor on X11).

**Comment by personalizedrefrigerator** [comment]
This could be a KDE Plasma issue -- I've only tested this on Plasma.

**Comment by bhennion** [comment]
I tried for a while to reproduce on plasma X11 (archlinux, gtk 3.24.25, plasma 5.20.5). I could not reproduce it either.

**Comment by personalizedrefrigerator** [comment]
Thank you for testing this! 

I just tested this on a different device (Plasma/X11, KDE Neon, gtk 3.24.23) on master and I'm still experiencing the issue. I'm using a touchscreen -- this doesn't occur when using a mouse. 

@bhennion Were you testing this with a stylus/mouse?

**Comment by personalizedrefrigerator** [comment]
Thank you for testing this! 

I just tested this on a different device (Plasma/X11, KDE Neon, gtk 3.24.23) on master and I'm still experiencing the issue. I'm using a touchscreen -- this doesn't occur when using a mouse. 

@bhennion Were you testing this with a stylus/mouse?

**Comment by bhennion** [comment]
> @bhennion Were you testing this with a stylus/mouse?

With a stylus. I just retested with the touchscreen and **I can now reproduce** with both X11 and Wayland, and both Plasma and Gnome (so all 4 possibilities). The stylus works fine in any case.

**Comment by personalizedrefrigerator** [comment]
Thanks for testing this again!
 I'm changing the issue name/description. Testing this again, I'm not experiencing the issue with my stylus.

**Comment by rolandlo** [comment]
Just tested once more and I realize that I can also reproduce it with the touchscreen (but not with the stylus).
