### ISSUE TITLE
Xournal 1.1.0 Update broke Dark Theme

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2764]
Windows 10, Xournal 1.1.0. The newest update broke the dark theme I was using at the time, detailed [here](https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-612533873). So, instead of everywhere being dark, everywhere is light mode.

**Comment by personalizedrefrigerator** [comment]
Inkscape allows the user to select which GTK theme to use in settings. We could try to do something like that!
This is [how Inskscape does it](https://gitlab.com/inkscape/inkscape/-/blob/master/src/ui/themes.cpp).

Once we have a GTK theme, we can set it using [GtkSettings](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-theme-name) or loading the CSS resource.
 * For this, see this [StackOverflow thread](https://stackoverflow.com/questions/42881112/pygtk3-how-to-change-application-theme). It's in Python, but should be similar to how we would do it with C++.

**Comment by Technius** [comment]
The latest changes updated the installer to "properly" perform installation. This involved some housekeeping on the previous version, which may have deleted the `etc\gtk-3.0\settings.ini` file. Can you check to see if the file got deleted?

**Comment by DUOLabs333** [comment]
@Technius Nope, it's still there.

**Comment by gerroon** [comment]
I cna confirm that this is broken on Windows 10 x64. I tried enabling and disabling after restarts. It did not help.

**Comment by Technius** [comment]
I can't reproduce the issue. I used the following steps:
* Install the latest 1.1.0+dev nightly.
* Create `C:\Program Files\Xournal++\etc\gtk-3.0\settings.ini` as described here https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-612533873.
* Open Xournal++ using the start menu shortcut.
* Observe that the Xournal++ window is dark, with dark icons.
* Open settings and enable `View > Dark theme`, and restart. Observe that the icons are bright.

**Comment by gerroon** [comment]
Ok, adding the ini works, although I still do not have pen pressure. Why does not the installer or the app creates those? Sounds like an installr bug

**Comment by Technius** [comment]
Pen pressure is an issue out of our control, see #1346. The config files are also not really something we want to touch, as it's up to the user to create/tweak them. We could potentially add an option directly in settings dialog to change theme as suggested above.

**Comment by Technius** [comment]
@DUOLabs333 Was this issue fixed for you?

**Comment by DUOLabs333** [comment]
@Technius Yeah, it was solved a long time ago, probably by the next update after that one. I just forgot to close it.
