### ISSUE TITLE
Add "Open with Xournal++" to context menu for PDFs

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2765]
The newest update for Xournal++ adds the option to open with Xournal++. However, it is not in the context menu, like with .xopp files. So, instead, I would like an option to click "Open with Xournal++" when I right click a PDF in File Explorer, like with .xopp files.

**Comment by rolandlo** [comment]
If you make Xournal++ the default application to open pdf-files, then you will have the same "Edit with Xournal++" entry in the context menu like with xopp-files.

**Comment by Technius** [comment]
It's better to have a dedicated PDF viewer as a default though. I think we can _additionally_ add an "Edit with Xournal++" entry using [registry entries similar to the ones outlined here](https://stackoverflow.com/a/34571628).

**Comment by Technius** [comment]
For the record, did you close this issue because the feature was implemented or because you're no longer interested in it?

**Comment by DUOLabs333** [comment]
I can no longer check if it's been implemented, so I shouldn't keep this open. If someone else want this, they'll either open up a new issue or find this one -- in which case, I will reopen it.
