### ISSUE TITLE
Xournalpp lagging in general

### ISSUE THREAD

**Issue by AetherPrior** [xournalpp/xournalpp#2769]
**Affects versions :**
 - OS: Arch Linux [kernel 5.4.94-1-lts]
 - Desktop environment KDE Plasma version 5.20.5
 - Version 1.1.0+dev

**Description**
Everything is lagging, including scroll, text input and pen input. Pen input is less laggy in xournalpp-git but very laggy in the non-aur package.

**To Reproduce**
1. Open xournalpp
2. Try to scroll or enter text, or insert an image

**Additional context**
I don't have any dedicated graphics, only Intel UHD graphics 620.

**Comment by personalizedrefrigerator** [comment]
Some questions:
 * Is the slowness independent of zoom/window size? I.e. if you zoom out and try writing, is it noticeably faster? 
 * Are you using the new input system?

Thank you for reporting this!

**Comment by AetherPrior** [comment]
Hey,
- The slowness is not just for the pen but for the eraser and scrolling and image input as well. And this is independent of zoom, yes.
- I'm not sure what you mean by the new input system... is there something I should check out?

**Comment by personalizedrefrigerator** [comment]
![The location of the new input system in settings](https://user-images.githubusercontent.com/46334387/107177010-a4b7ae00-6985-11eb-957a-b1d4806bee01.png)

**Comment by AetherPrior** [comment]
Yes, thanks @personalizedrefrigerator , I tried it, but it seems to be independent of it, even after restart of xournalpp, I faced a lag.

**Comment by bhennion** [comment]
@AetherPrior Is the lag only happening on Xournal++? Have you tried other apps that would rely on graphics acceleration?

> I don't have any dedicated graphics, only Intel UHD graphics 620.

I have a similar setup (Arch 5.10.12, Plasma 5.20.5), with an Intel UHD, and no performance issues. Are you sure your drivers are properly set up (see [here](https://wiki.archlinux.org/index.php/Intel_graphics))?

**Comment by AetherPrior** [comment]
Maybe, it's a problem with intel graphics, I'll check it out

**Comment by chron-isch** [comment]
Same here, ArchLinux on a MS Surface Go and I can't reproduce your proboem. The dev version has only become more responsive recently if you ask me.

The things that are still slow/laggy/annoying for me are the eraser with delete stroke in combination with a tablet tool and scrolling using the hand tool with a tablet tool, when you use the mouse or mouse-wheel it works fine.

**Comment by AetherPrior** [comment]
@chron-isch I have reverted to my older settings of the graphics drivers back when xournalpp was still doing okay, and it still didn't fix the issue.  
A more specific issue would be that when I paste an image, and when i try to move it across the page, there exists an auto scroll that lags quite a bit, so I can't judge where my image would be going.
Eraser is quite laggy too.  
It'd be great if there's a way to disable autoscrolling when moving images.

**Comment by AetherPrior** [comment]
I'm not sure what just happened, but I ran an upgrade and BAM... fixed. Everything.   
Maybe it was the fault of my drivers.  
Closing.
