### ISSUE TITLE
Ubuntu 18: cannot open files on other disk

### ISSUE THREAD

**Issue by anastasiusz** [xournalpp/xournalpp#2772]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 18.04.05 TLS 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 
 - (Linux only) Desktop environment: Gnome
 - libgtk-3-0: 3.22.30-1ubuntu4

Xournal++ 1.0.20 ea457v9f Dec 17 2020 21:55:32

On my computer, the solid-state disk is on / and I can access files on it from Xournal++. In the File open dialog cannot access any files on the harddisk (mounted on /DataDisk; this directroy is invisible). I also cannot open devices mounted on /media, it gives me 'permission denied', although the directory has rwxr-xr-x permissions and it contains at least one subdirectroy where I have r-x access.
The file open dialog does not show symbolic links either, so no way to access the harddisk this way either.

**To Reproduce**
File>Open and try to navigate to something that is not on the root disk (could also be a USB pen drive)

**Expected behavior**
Like all other file open dialogs, being able to access all disks, USB pen drives, following symbolic links.

Other note: I am a normal user, not superuser, no sudo.

**Comment by Technius** [comment]
What installation method did you use?

**Comment by lparolari** [comment]
@anastasiusz I had the same issue on Ubuntu 20.04 with Xournal++ installed from the "Ubuntu Software" app.

In my case the **solution** was easy:

1. search Xournal++ in the "Ubuntu Software" app;
2. click on "Permissions" button;
3. check the "Read/write files on removable storage devices" option.

![xournalpp](https://user-images.githubusercontent.com/12633062/110449161-39671600-80c2-11eb-9ed7-897f19dcf694.png)
