### ISSUE TITLE
Presentation mode: Hide Menu bar, Hide SIdebar in Preferences is ignored

### ISSUE THREAD

**Issue by anastasiusz** [xournalpp/xournalpp#2773]
OS: Ubuntu 18.04.05 TLS 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64
    (Linux only) Desktop environment: Gnome
    libgtk-3-0: 3.22.30-1ubuntu4
    Xournal++ 1.0.20 ea457v9f Dec 17 2020 21:55:32, from github

**Describe the bug**
Presentation mode ignores Preferences>View: Presentation mode "Hide Sidebar", "HIde Menubar"

**To Reproduce**
In Preferences>View: Presentation mode: Chcek "Hide Sidebar", "HIde Menubar"
View> Presentation mode
Sidebar & Menu bar are still visible

**Expected behavior**
Sidebar & Menu bar should disappear

**Screenshots of Problem**
![Screenshot](https://user-images.githubusercontent.com/43650300/107213094-3536d280-6a08-11eb-9c93-b4845d719f15.png)

**Additional context**
Also the red frame around the PDF should disappear in presentation mode.

**Comment by rolandlo** [comment]
These settings are currently only applied when entering presentation mode via the `F5` key. 
Also see #2408 where the presentation mode is improved (although currently nobody appears to be working on it).

**Comment by dliessi** [comment]
On my system (Fedora 34, Xournal++ 1.1.0), View -> Presentation mode (or Presentation mode button) changes the zoom and disables scrolling and the hand tool; F5 does the same and activates the full screen mode using the full screen hide settings and not the presentation mode hide settings.
Moreover (but that may be a separate issue) only the setting for the menu bar is applied, both with F5 and F11, while the setting for the sidebars is ignored.

(A further separate issue is that F5 does not deactivate the presentation mode.)

**Comment by forgottosave** [comment]
This issue got solved in #4514

The (further separate) issue @dliessi mentioned, with exiting the presentation mode with F5, is still open though.
