### ISSUE TITLE
Localization missing in the deb

### ISSUE THREAD

**Issue by rojizo** [xournalpp/xournalpp#2780]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux (PopOS 20.04)
 - X11
 - Xournal++ 1.0.20 
└──libgtk: 3.24.20 
 - Installation method: official release deb

**Describe the bug**
There is no locales in the released deb...

**Comment by rolandlo** [comment]
Do you get localization files installed in `/usr/share/locale`, for instance `/usr/share/locale/de_DE/LC_MESSAGES/xournalpp.mo`?
The issue may be fixed in version 1.1.0+dev (see [nightly releases](https://github.com/xournalpp/xournalpp/releases/tag/nightly)).

**Comment by rojizo** [comment]
yes... /usr/share/locale contains localization files... but there are no xournalpp.mo for my language... I listed installed files and there where no localization files

❯ dpkg-query -L xournalpp
/usr
/usr/bin
/usr/bin/xournal-thumbnailer
/usr/bin/xournalpp
/usr/share
/usr/share/applications
/usr/share/applications/com.github.xournalpp.xournalpp.desktop
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/com.github.xournalpp.xournalpp.svg
/usr/share/icons/hicolor/scalable/mimetypes
/usr/share/icons/hicolor/scalable/mimetypes/application-x-xojpp.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-xopp.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-xopt.svg
/usr/share/icons/hicolor/scalable/mimetypes/gnome-mime-application-x-xopp.svg
/usr/share/icons/hicolor/scalable/mimetypes/gnome-mime-application-x-xopt.svg
/usr/share/metainfo
/usr/share/metainfo/com.github.xournalpp.xournalpp.appdata.xml
/usr/share/mime
/usr/share/mime/packages
/usr/share/mime/packages/com.github.xournalpp.xournalpp.xml
/usr/share/mimelnk
/usr/share/mimelnk/application
/usr/share/mimelnk/application/x-xojpp.desktop
/usr/share/mimelnk/application/x-xopp.desktop
/usr/share/mimelnk/application/x-xopt.desktop
/usr/share/thumbnailers
/usr/share/thumbnailers/com.github.xournalpp.xournalpp.thumbnailer
/usr/share/xournalpp
/usr/share/xournalpp/plugins
/usr/share/xournalpp/plugins/Example
/usr/share/xournalpp/plugins/Example/main.lua
/usr/share/xournalpp/plugins/Example/plugin.ini
/usr/share/xournalpp/plugins/Example/var_dump.lua
/usr/share/xournalpp/plugins/ToggleGrid
/usr/share/xournalpp/plugins/ToggleGrid/plugin.ini
/usr/share/xournalpp/plugins/ToggleGrid/togglegrid.lua
/usr/share/xournalpp/ui
/usr/share/xournalpp/ui/about.glade
/usr/share/xournalpp/ui/exportSettings.glade
/usr/share/xournalpp/ui/fillTransparency.glade
/usr/share/xournalpp/ui/goto.glade
/usr/share/xournalpp/ui/icons
/usr/share/xournalpp/ui/icons/hicolor
/usr/share/xournalpp/ui/icons/hicolor/24x24
/usr/share/xournalpp/ui/icons/hicolor/24x24/actions
/usr/share/xournalpp/ui/icons/hicolor/24x24/actions/pageSpinner.png
/usr/share/xournalpp/ui/icons/hicolor/icon-theme.cache
/usr/share/xournalpp/ui/icons/hicolor/index.theme
/usr/share/xournalpp/ui/icons/hicolor/scalable
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/addPage.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/arrow-draw.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/audio-playback-pause.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/audio-playback-stop.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/audio-record.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/centerPage.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/circle-draw.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/coordinate-system-draw.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/customize_toolbars.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/default.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/delPage.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/fill.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/floating_toolbox.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/fullscreen.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/goto.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/grid_snapping.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/hand.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/lasso.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/layer.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/line-style-dash-dot.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/line-style-dash.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/line-style-dot.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/line-style-plain.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/manage_toolbars.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/nextAnnotatedPage.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/object-play.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/object-select.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/presentation-mode.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/rect-draw.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/rect-select.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/ruler.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/shape_recognizer.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/showpairedpages.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/sidebar-page-preview.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/sidebar_bookmarks.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/sidebar_index.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/snapping.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/stretch.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/thickness_fine.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/thickness_medium.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/thickness_thick.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/thickness_very_fine.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/thickness_very_thick.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_camera.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_eraser.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_highlighter.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_image.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_math_tex.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_pencil.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/tool_text.svg
/usr/share/xournalpp/ui/icons/hicolor/scalable/actions/transparent.svg
/usr/share/xournalpp/ui/icons/hicolor/update-icon-cache.sh
/usr/share/xournalpp/ui/iconsDark
/usr/share/xournalpp/ui/iconsDark/hicolor
/usr/share/xournalpp/ui/iconsDark/hicolor/icon-theme.cache
/usr/share/xournalpp/ui/iconsDark/hicolor/index.theme
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/arrow-draw.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/audio-playback-pause.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/audio-playback-stop.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/audio-seek-backwards.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/audio-seek-forwards.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/circle-draw.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/coordinate-system-draw.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/fill.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/grid_snapping.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/line-style-dash-dot.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/line-style-dash.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/line-style-dot.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/line-style-plain.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/presentation-mode.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/rect-draw.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/ruler.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/shape_recognizer.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/snapping.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/thickness_fine.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/thickness_medium.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/thickness_thick.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/thickness_very_fine.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/thickness_very_thick.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/tool_highlighter.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/tool_math_tex.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/scalable/actions/tool_text.svg
/usr/share/xournalpp/ui/iconsDark/hicolor/update-icon-cache.sh
/usr/share/xournalpp/ui/images.glade
/usr/share/xournalpp/ui/main.glade
/usr/share/xournalpp/ui/pageTemplate.glade
/usr/share/xournalpp/ui/pagesize.glade
/usr/share/xournalpp/ui/pagetemplates.ini
/usr/share/xournalpp/ui/pdfpages.glade
/usr/share/xournalpp/ui/pixmaps
/usr/share/xournalpp/ui/pixmaps/application-x-xojpp.svg
/usr/share/xournalpp/ui/pixmaps/application-x-xopp.svg
/usr/share/xournalpp/ui/pixmaps/application-x-xopt.svg
/usr/share/xournalpp/ui/pixmaps/com.github.xournalpp.xournalpp.png
/usr/share/xournalpp/ui/pixmaps/com.github.xournalpp.xournalpp.svg
/usr/share/xournalpp/ui/pixmaps/default.svg
/usr/share/xournalpp/ui/pixmaps/gnome-mime-application-x-xopp.svg
/usr/share/xournalpp/ui/pixmaps/gnome-mime-application-x-xopt.svg
/usr/share/xournalpp/ui/pixmaps/xopt.svg
/usr/share/xournalpp/ui/plugin.glade
/usr/share/xournalpp/ui/pluginEntry.glade
/usr/share/xournalpp/ui/settings.glade
/usr/share/xournalpp/ui/settingsButtonConfig.glade
/usr/share/xournalpp/ui/settingsDeviceClassConfig.glade
/usr/share/xournalpp/ui/texdialog.glade
/usr/share/xournalpp/ui/toolbar.ini
/usr/share/xournalpp/ui/toolbarCustomizeDialog.glade
/usr/share/xournalpp/ui/toolbarManageDialog.glade
/usr/share/xournalpp/ui/xournalpp.css

**Comment by rolandlo** [comment]
Hmm, the 1.0.20 .deb-file does contain localizations in 14 languages (as you can see from opening the .deb file with the archive manager), amongst which there is `es_ES`. I don't quite get why they are not installed. 
Could you try version 1.1.0+dev? The .deb file contains localizations in 44 languages.

**Comment by rojizo** [comment]
I checked the deb files... the focal .deb has no locales, but the bionic one has

**Comment by rolandlo** [comment]
> I checked the deb files... the focal .deb has no locales, but bionic and debian ones has the files (in nightly build)

You are right about that. Checking the Azure Pipelines I discovered that the difference lies in the gettext package being installed (on bionic) or not (on focal)

```
-- Could NOT find Gettext (missing: XGETTEXT_EXECUTABLE GETTEXT_MSGMERGE_EXECUTABLE GETTEXT_MSGFMT_EXECUTABLE GETTEXT_MSGCAT_EXECUTABLE) 
ERROR Gettext not found!
```
I will fix that.
