### ISSUE TITLE
Drawing mode is quite annoying

### ISSUE THREAD

**Issue by amalnn** [xournalpp/xournalpp#2790]
While writing, the mouse pointer changes its appearance frequently from an arrow pointer to a dot pointer which is quite annoying.

**Comment by rolandlo** [comment]
It doesn't happen with the stylus. In the input system panel of the preferences (in menu Edit) you can make your mouse act like a stylus, so you won't experience this problem any more. In the view panel of the preferences you can modify the appearance of the cursor. Part of that assumes you are using version 1.1.0+dev.

**Comment by Izerpizer** [comment]
you can change that in the settings. `Edit->Preferences->View->Cursor` and check out `Cursor icon for pen`
