### ISSUE TITLE
Cannot export to PDF files

### ISSUE THREAD

**Issue by ntualue** [xournalpp/xournalpp#2792]
**Affects versions :**
 - OS: Windows
 - Version of Xournal++: 1.0.18 / 1.0.19
 - Installation method: Official release for Windows

**Describe the bug**
Try to export to PDF files but it did not succeed.
There is a popup but when I click a save button, there is nothing happening.

**To Reproduce**
1. Export to PDF / Export as...

**Expected behavior**
A PDF file should be created.

**Additional context**
I tried uninstalling and reinstalling with both versions, like a method in #2706, and tried exporting PDF files again. It still did not work.

**Comment by rolandlo** [comment]
I cannot reproduce the problem. Could you please try out version 1.1.0+dev ([nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly)), if pdf export works for you there? Note however that currently 1.1.0+dev uses a buggy Cairo version, so this won't be quite the fix for you yet.

**Comment by yojoza** [comment]
I had an issue exporting to PDF in version 1.0.20 but only when text was included in the header or footer of the document. Immediately after removing the text, the document exported to PDF without issue. Drawing in the header or footer did not affect the export.

**Comment by ntualue** [comment]
@rolandlo I've already used version 1.1.0+dev now. It can export PDF files, but the files are corrupted.

A popup appears like this when I try to open the PDF files.
![image](https://user-images.githubusercontent.com/78845341/107902478-19d44600-6f79-11eb-8423-73108fd53289.png)

**Comment by rolandlo** [comment]
@ntualue That was to be expected in view of #2601. The bug comes from Cairo 1.17.4. Once we change to a working Cairo version (which we plan to do pretty soon), you will be fine.
