### ISSUE TITLE
xournalpp cannot start audio record

### ISSUE THREAD

**Issue by OtacilioNeto** [xournalpp/xournalpp#2796]
**Affects versions :**
 - OS:Ubuntu 20.04
 - (Linux only) Desktop environment: X11]
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: 1.0.20 git commit ea457c9f
 - Installation method:  sudo snap install xournalpp

**Describe the bug**
After start xournalpp terminal shows:

ota@rigel:~$ xournalpp

(com.github.xournalpp.xournalpp:11183): Gtk-WARNING **: 10:34:21.701: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name

(com.github.xournalpp.xournalpp:11183): Gtk-WARNING **: 10:34:21.704: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name

(com.github.xournalpp.xournalpp:11183): Gtk-WARNING **: 10:34:21.705: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
ALSA lib conf.c:3710:(snd_config_hook_load) cannot stat file/directory /usr/share/alsa/cards/aliases.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.dmix
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

(com.github.xournalpp.xournalpp:11183): Gtk-WARNING **: 10:34:21.786: Theme parsing error: <data>:1:22: Junk at end of value for font-family

================================================================

After click Record Audio/Stop Record button a window shows "Recorder could no be started"
and terminal shows: 
** Message: 10:35:41.581: Start recording
** Message: 10:35:41.581: PortAudioProducer: Selected input device not found - fallback to default input device
Caused by: Internal PortAudio error
** Message: 10:35:41.581: PortAudioProducer: Unable to open stream

** (com.github.xournalpp.xournalpp:11183): WARNING **: 10:35:41.655: Recorder could not be started.

====================================================================

Edit->preferences->Audio Recording Input Device and Output Device only shows "System default" and no other dropbox option

**To Reproduce**
1. start xournalpp
2. click record button

**Expected behavior**
Start record audio

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/10184059/107643904-7d970000-6c55-11eb-8de1-230995533806.png)

![image](https://user-images.githubusercontent.com/10184059/107643991-9bfcfb80-6c55-11eb-9c8a-db0c432580c6.png)

**Comment by OtacilioNeto** [comment]
After install the  latest unstable nightly release the audio record is working

sudo add-apt-repository ppa:andreasbutti/xournalpp-master
sudo apt update
sudo apt install xournalpp

![image](https://user-images.githubusercontent.com/10184059/107645371-5c371380-6c57-11eb-8b04-2c726f2b69c8.png)

**Comment by rolandlo** [comment]
Ok, I will close this issue then, since all future versions will be based on the current master.
