### ISSUE TITLE
Draw spline tool missing

### ISSUE THREAD

**Issue by verga** [xournalpp/xournalpp#2797]
**Affects versions :**
 - OpenSuse Tumbleweed
 - KDE plasma last version
     Xournal++ 1.0.20 
    └──libgtk: 3.24.24 
     ** Message: 16:57:17.458: MemoryLeak: sum 0 objects.
     - 1.0.20
 - zyyper

**Describe the bug**
The DRAW SPLINE tool do not appear in the Tools menu; adding it to toolbar.ini do not work.

**To Reproduce**
1. open xournallpp
2. open Tools menu
3. search Draw Spline in the list

**Expected behavior**
Draw Spline does appear in the menu, and in the toolbar

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

![xour_spline_absent](https://user-images.githubusercontent.com/997307/107663719-fa44d100-6c8b-11eb-8a95-b1cb797e87b9.png)

**Comment by rolandlo** [comment]
The spline drawing type has only been introduced in version 1.1.0+dev. It is not included in version 1.0.20. So you must upgrade to version 1.1.0+dev ([nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)) if you want to use it.
