### ISSUE TITLE
Xournal++ Pop-Up Windows Are Not Independant of the Xournal++ Main Window

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#2799]
**Affects versions :**
 - OS: Linux - Ubuntu
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.1.0+dev
 - Installation method: apt with deb file

**Describe the bug**
When you click "Export to PDF", a new file explorer window will pop up allowing you to choose the saving location of the PDF; however this new window, which should be independent of  the main Xournal++ window, is not independent. What i mean by this is if you drag the new file explorer window around, the main Xournal++ window remains anchored to the file explorer window and as such, it gets dragged around with it. You are unable to move the file explorer window without having everything move around on your desktop. 

I've noticed this as a pretty big annoyance if I have the Xournal++ window tiled to half of my display. When I go to export a PDF from this configuration, the new file explorer window will half appear off screen prompting me to drag it to be able to see it, and as explained above, this makes the main Xournal++ window get dragged around with it breaking it out of its tiled position.

**To Reproduce**
1. Click on the "Export to PDF" option so that the file explorer window pops up.
2. Grab the top of the file explorer window to drag it around on the desktop.
3. Observe that all of Xournall++ moves as one unit, not just the file explorer window moving.

**Expected behavior**
I expect that the window which pops up, acts as a separate window entirely from the main Xournal++ window. I would like to be able to interact with this window, and move it around without having it affect the main Xournal++ window.

**Additional Context**
I have also observed this happening with other pop up windows such as the file explorer window for saving a Xournal file. Beyond this, however, I have not tested any of the other pop up windows. That being said, I would expect that they would behave in the same fashion. 

EDIT: I have tested the preferences window, and it moves how I would expect it to move, (albeit a little glitchy) independent of the main Xournal++ window.

**Comment by Technius** [comment]
IIRC GTK+ forces all dialogs to be modal. You can change this with the tweak tool.

It would be great if someone can find a way to make the dialogs _not_ modal!

**Comment by personalizedrefrigerator** [comment]
**Glade:**
![image](https://user-images.githubusercontent.com/46334387/108644333-64ffc480-7463-11eb-9740-ba4522b42a15.png)

I think changing `hint` to `normal` makes dialogs _not_ modal.

**Comment by bhennion** [comment]
I think this is really a GTK bug. Our dialogs must be modal (so they don't end up hidden by the main window, and to block interactions with the main window while a dialog is shown). https://docs.gtk.org/gtk3/method.Window.set_modal.html

I'll close this as a dependency issue.
