### ISSUE TITLE
Option to Mirror Selection About a Specified Axis

### ISSUE THREAD

**Issue by Izerpizer** [xournalpp/xournalpp#2803]
**Is your feature request related to a problem? Please describe.**
Right now you can only rotate objects, and have no way to mirror them.

**Describe the solution you'd like**
When you select an object, it would be nice to click a button and have the object mirror itself about a specified axis (X or Y axis should be enough).

**Comment by tattsan** [comment]
See [here](https://github.com/xournalpp/xournalpp/pull/2723#issuecomment-771154398).

**Comment by rolandlo** [comment]
The problem description is factually wrong in view of #2723. I am closing this issue therefore.
