### ISSUE TITLE
Wacom pen tablet not recognized by Xournal++ on Mac OS

### ISSUE THREAD

**Issue by runesen** [xournalpp/xournalpp#2815]
**Affects versions :**
 - OS: Mac 
 - version of libgtk: 3.24.10 
 - Version of Xournal++: 1.0.19 (since 1.0.20 always crashes directly upon opening)
 - Installation method: I installed the mac app on the official release page here: https://github.com/xournalpp/xournalpp/releases/tag/1.0.19

**Describe the bug**
The pen tablet is not recognized. Under Preferences > Input system, it says "No devices found [...]". 

**To Reproduce**
1. Open Xournal++
2. Find yourself writing like a 7yo child

**Expected behavior**
Smooth writing, pressure sensitivity

**Screenshots of Problem**
![Screen Shot 2021-02-17 at 08 15 55](https://user-images.githubusercontent.com/30272332/108169436-005a0800-70f9-11eb-885b-3727fd802710.png)
![Screen Shot 2021-02-17 at 08 16 54](https://user-images.githubusercontent.com/30272332/108169448-04862580-70f9-11eb-90a9-9a007df3806a.png)

**Additional context**
I am aware that this bug is almost identical to other ones, e.g. [this](https://github.com/xournalpp/xournalpp/issues/1772). However, the solution desribed in that post "build gtk in branch gtk-3-24 using macports" uses language that I do not understand. I am a regular Mac OS user, with no developer experience. In order to solve the problem, I would need easy-to-follow, step-by-step instructions.

**Comment by rolandlo** [comment]
This should be fixed in version 1.1.0
