### ISSUE TITLE
Missing version number in latest macOS download (1.0.20)

### ISSUE THREAD

**Issue by suschizu** [xournalpp/xournalpp#2820]
**Affects versions :**
 - OS: macOS (https://github.com/xournalpp/xournalpp/releases/download/1.0.20/xournalpp-1.0.20-macos.zip)
 - Version of Xournal++: 1.0.20 
     - can be obtained by running `xournalpp --version` or in the **About** window

**Describe the bug**
The ShortVersionString and BundleVersion keys are missing in the info.plist 

should look like that:

`<key>CFBundleShortVersionString</key>
	<string>1.0.20</string>
…
	<key>CFBundleVersion</key>
	<string>11111</string>
`
![image](https://user-images.githubusercontent.com/16004333/108265702-667e7380-7169-11eb-994b-d6aba9098019.png)

**Comment by rolandlo** [comment]
Doesn't happen any more in version 1.1.0

**Comment by core-code** [comment]
is this going to be fixed in the next release?
