### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by perebalazs** [xournalpp/xournalpp#2831]
**Affects versions :**
 - OS: Linux (Ubuntu 20.04)
 - Desktop environment: Gnome, X11
 - Version of libgtk: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
When I copy and paste objects (or group of objects) the scale changes (cannot resize to the original), and objects which were selected together form one object after paste. This big object cannot be broken down into the original elements.

**To Reproduce**
1. draw some lines
2. select them
3. copy
4. paste
5. try to select individual lines
6. try to resize to the orginal size

https://user-images.githubusercontent.com/43467760/108488996-510c6500-72a1-11eb-8da0-1c241b3c20eb.mp4

**Comment by Technius** [comment]
I can't reproduce this bug. Based on your video, it looks like the selection is being pasted as an image (note the color / stroke options being greyed out).

**Comment by perebalazs** [comment]
Problem is solved. After an update (today) everything works fine.

**Comment by perebalazs** [comment]
The same problem came back again (see video above). Selection is inserted as an image, and the size is bigger than the original. I don't understand, it worked well 2 days ago. Or do I something wrong?
Today morning I got an update of xournal (the same version number but the build date is 21 Febr.). Could it be the source of the issue?

**Comment by rolandlo** [comment]
Not sure what the problem is (can't reproduce), but as a workaround you could clone objects (via the right mouse button) rather than copy/paste it.

**Comment by perebalazs** [comment]
I got it! When I change background (maybe the same as the current), paste begins work as it should work normally.

https://user-images.githubusercontent.com/43467760/108701339-18ba9000-7508-11eb-8875-feeaae5b1970.mp4

**Comment by perebalazs** [comment]
And the problem is with "copy", and not with "paste"! If I change background after "copy" and before "paste", nothing changes. But If I change background before "copy", "paste" inserts the selection as separate strokes.

**Comment by ronandalton** [comment]
I think this issue should be reopened. I'm having the same issue on the latest version.

**Comment by yasmah74** [comment]
I have the same Problem and the Workaround works for me too. (@perebalazs  tnx for that)

OS: Linux (Ubuntu 22.04.01)
Desktop environment: Gnome Version 42.5
Version of libgtk: 3.24.33
Version of Xournal++: 1.1.1
Installation method: over Ubuntu Software

**Comment by rolandlo** [comment]
It looks like Xournal++ is unable to establish the correct selection data target. There are three possibilites: 
1) Xournal data
2) Text
3) Image
https://github.com/xournalpp/xournalpp/blob/18376c22a06a91f26383d0010f22be9254f63ac7/src/core/control/ClipboardHandler.cpp#L305-L307

When you copy some strokes (without text) in Xournal++, then Xournal++ puts Xournal data and an image into the clipboard. Now when you paste and Xournal++ thinks there is no Xournal data, but an image in the clipboard, then it will paste the image. Note that in the video there are no rotation anchors around the selection after pasting, so the selection contains an image and not strokes. 

Now the question is, how does Xournal++ establish the selection data target? It does so first when Xournal++ is started. Later it solely listens to the `owner-change` signal. Only when that signal is received, it establishes the selection data target. Xournal data takes preference over Text and Text over image. See https://github.com/xournalpp/xournalpp/blob/18376c22a06a91f26383d0010f22be9254f63ac7/src/core/control/ClipboardHandler.cpp#L44-L63

In the second video (`xournal.mp4`) there is already some image in the clipboard at startup of Xournal++ and no Xournal data. So Xournal++ will establish the selection data target "Image". Now when the strokes are copied in Xournal++, in theory the `owner-change` signal should make Xournal++ establish selection data target "Xournal data". Most likely you don't receive that signal. On MacOS no signal is sent (and there are similar issues reported, see #4274 and https://gitlab.gnome.org/GNOME/gtk/-/issues/1757). On X11, this information is only available if the X server supports the XFIXES extension according to https://docs.gtk.org/gdk3/struct.EventOwnerChange.html. If you don't receive that signal, Xournal++ will continue to think that there is no "Xournal data" (and no Text), but an "Image" in the clipboard and will paste an image therefore. 

Could you try again on Wayland? Maybe it works there.

**Comment by yasmah74** [comment]
@rolandlo It didn't worked or me.
But i realized something: One of the Buttons of my pen, is set to "Select region" (and it works as it should). If i click the button after a selection, it will duplicate the selection and i can move it then to the right place.

This is a good wourkaround if the Place for the Paste is near to the copy-place.
