### ISSUE TITLE
Fedora nightly RPM: Last build 1 month ago?

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2832]
**Affects versions :**
 - OS: Fedora
 - xournalpp version: 1.1.0+dev

**Describe the bug**

**To Reproduce**
1. Follow the [link to the nightly release](https://github.com/xournalpp/xournalpp#fedora) in the README.
2. Click "Packages"

**Expected behavior**
The README states that this package is rebuilt daily/as git master changes. As such, I expect the package to have been re-built recently.

**Screenshots of Problem**
![screenshot reading 'last build: 1 month ago'](https://user-images.githubusercontent.com/46334387/108508581-e2afae80-7270-11eb-8ded-309e54c92b05.png)

**Comment by Technius** [comment]
@luyatshimbalanga do you know what happened? I think we shuffled some dependencies around a while ago so that may have broken the nightly builds.

**Comment by luyatshimbalanga** [comment]
@Technius That missing dependency is librsvg. I added it on [my forked repository](https://github.com/luyatshimbalanga/xournalpp/blob/master/rpm/fedora/xournalpp.spec). The build should work at this time of writing.

**Comment by mjg** [comment]
I guess this goes to confirm my comment in #2148 . The spec file currently in this project is out-of-sync with the source tree in this project as well as with the current Fedora spec file. (And I use my own for local build.)

**Comment by jghauser** [comment]
Not sure if I should open a new issue or not. I think the COPR is out of date again. The [page](https://copr.fedorainfracloud.org/coprs/luya/xournalpp/) says that the last build was 2 months ago. It would be great if the builds started working again :).

**Comment by luyatshimbalanga** [comment]
Let see that.

**Comment by jghauser** [comment]
Thanks so much for looking into this so quickly! It works perfectly! :)

**Comment by luyatshimbalanga** [comment]
No problem. I think this ticket can be closed.
