### ISSUE TITLE
Windows installer with all Multilingual support

### ISSUE THREAD

**Issue by GravuTrad** [xournalpp/xournalpp#2838]
Hello.

Is it planified to implement all the languages availables?

Thanks

**Comment by GravuTrad** [comment]
I see the files:

https://github.com/xournalpp/xournalpp/tree/master/po

but don't see how it's managed by the program.

**Comment by rolandlo** [comment]
Which version of Xournal++ do you use? If you use version 1.1.0+dev, what languages are listed in the language settings panel in menu `edit -> preferences`? All 44 of them? 
In case you use version 1.0.20 (or older) the language cannot be set manually, but Xournal++ will try to use the system language.

**Comment by GravuTrad** [comment]
I would to use use french

**Comment by rolandlo** [comment]
Compare #2637

**Comment by rolandlo** [comment]
See #2844 for version 1.1.0+dev. I will close this issue. Version 1.0.20 was the last in the 1.0.x series.
