### ISSUE TITLE
Fedora: Package `texlive-scontents` missing from dependency list in README

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2841]
**Affects versions :**
 - OS: Fedora 33
 - Installation method: `make`

**Describe the bug**
`texlive-scontents` needed to be installed in addition to the LaTeX packages listed in the `README` to use the LaTeX tool on Fedora.

**Expected behavior**
I should be able to use the latex tool without installing dependencies not in the list in https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md.

**Additional context**
**tex.log**
```tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2021.2.21)  21 FEB 2021 15:36
entering extended mode
... Omitted ...

! LaTeX Error: File `scontents.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
... Omitted ...
```

**Comment by rolandlo** [comment]
This is part of a larger (yet unresolved) problem #2206

**Comment by rolandlo** [comment]
The problem has been fixed with a workaround, adding a `legacy_template.tex`. So I am closing this issue.
