### ISSUE TITLE
Xournalpp just drag the page and not draw anything

### ISSUE THREAD

**Issue by shoshtari** [xournalpp/xournalpp#2848]
when i use my stylus, xournalpp not draw anything! no pen no highlight and no eraser it is like i use hand tool but i have not select  it but it works well with my mouse.

Tablet and Stylus model: Huion HS64

OS: Arch linux

**Comment by rolandlo** [comment]
Which version of Xournal++ do you use? Have you activated the new input system in the preferences? Have you tried to play around with the settings in the input system panel of menu `edit -> preferences`? Maybe your device is wrongly configured. If you need help take a screenshot of the input system panel and post it here.

**Comment by shoshtari** [comment]
The Output of  `xournalpp --version`
`xournalpp --version
Xournal++ 1.0.20-hotfix 
└──libgtk: 3.24.24 
** Message: 01:05:30.755: MemoryLeak: sum 0 objects.`

and the screenshot of input system tab:
![2021-02-23_01-07](https://user-images.githubusercontent.com/45182735/108773454-9ff11d80-7573-11eb-9361-367f0e8359ea.png)

**Comment by personalizedrefrigerator** [comment]
Please check the "Enable new input system" checkbox!

**Comment by rolandlo** [comment]
Try activating the new input system (enable the checkbox) and restart. Then HUION Huion Tablet_HS64 stylus (touchscreen) may be a stylus, not a touchscreen. So try to change that to stylus.

**Comment by shoshtari** [comment]
Sorry for my absence! i was away from my system so i couldn't do anything with it.

i try to change the settings in xournalpp but there was not any change.

i try to delete the input-xf86-wacom and then the stylus work! there is only one problem that i can't cofigure my stylus buttons.
