### ISSUE TITLE
xournalpp_bin.exe has stopped working when I click on the close button. every other things seem to be fine. I have installed xournalpp-1.0.18 on windows 10

### ISSUE THREAD

**Issue by Raj2588** [xournalpp/xournalpp#2853]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by Raj2588** [comment]
![xournalPP](https://user-images.githubusercontent.com/79496286/108801642-452fe400-75bc-11eb-99ff-5715f86845bf.png)



xournalpp_bin.exe has stopped working when I click on the close button. every other things seem to be fine. I have installed xournalpp-1.0.18 on windows 1

**Comment by rolandlo** [comment]
Version 1.0.18 does not receive any updates any longer (version 1.0.20 was the last one in the 1.0.x series). Can you try out version 1.1.0+dev (from the [nightly releases](https://github.com/xournalpp/xournalpp/releases/tag/nightly))?

**Comment by Technius** [comment]
This issue has already been fixed in nightly.
