### ISSUE TITLE
Error opening file (Mimetype missing)

### ISSUE THREAD

**Issue by rafisics** [xournalpp/xournalpp#2855]
I am using Xournalpp 1.1.0+dev in Ubuntu 20.04 LTS. 

I am creating `.xopp` file named `fuad_ju_qm.xopp`.
It had 48 pages of notes. My last modification was done almost one hour ago.
After reopening my machine, I opened the Xournal++ app. I tried opening it by `File > Recent Documents > 1. fuad_ju_qm.xopp`. It shows me this error:
```
Error opening file "/home/rafi/Documents/fuad_ju_qm.xopp"
The file is no valid .xopp file (Mimetype missing): "/home/rafi/Documents/fuad_ju_qm.xopp"
```
I got confused and went to the `Properties` of the file. I am shocked to see that the file type is `plain text document` and its size is 0 bytes. I don't understand how it happened!
I am getting really afraid to lose all my writings. Kindly tell me what I can do to get back my `.xopp` file.

**Comment by rolandlo** [comment]
You should check your autosave files. They could be
A) In `~/.config/com.github.xournalpp.xournalpp/autosave`
B) In `~/.config/xournalpp/autosave`
C) In the same folder as your document (`~/Documents`)

**Comment by rafisics** [comment]
Thank you so much, @rolandlo. I found a hidden autosave file in the same directory. I am relieved now.
Can you please tell me what should be done to prevent from happening this issue again?

**Comment by rolandlo** [comment]
Happy the system worked! I really don't know why that happened and we haven't had such bug reports, I think. When there is no way to reproduce the problem, it's hard to come up with a solution.

**Comment by rafisics** [comment]
Oh, okay. Thanks a lot for your help.

**Comment by rolandlo** [comment]
You're welcome. I will close this issue now.

**Comment by georanth** [comment]
I had the same issue (also using Ubuntu 20.04 LTS and xournalpp 1.1.0 (gitcommit 9d1277de)). I couldn't find any autosave files. I'm 100% sure I saved the file before closing xournalpp.

**Comment by Shahin-rmz** [comment]
Hello,
Same issue here for me.
I am student and all my notes are perished now. any idea where can I find autosaves?

**Comment by rolandlo** [comment]
@Shahin-rmz See [above](https://github.com/xournalpp/xournalpp/issues/2855#issuecomment-784105642) and [website](https://xournalpp.github.io/guide/file-locations/)

**Comment by Shahin-rmz** [comment]
Thanks @rolandlo, I couldn't find the autosave files as I have installed snap. I played around the directories under snap and could find it. You also saved my life. Thanks.
for those who installed snap package, go to `/home/USER/snap/xournalpp/current/.config/xournalpp`
