### ISSUE TITLE
Highlighter is not rendered properly while using it

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#2858]
**Describe the bug**
Using the highlighter, only a very thin line is drawn. Once the stroke is finished and a repaint happened, the storke is as is should be.

![Screenshot_20210223_213613](https://user-images.githubusercontent.com/17818041/108904756-329ac680-761f-11eb-8a68-d0ab9056b890.png)

This is most likely related to my PR #2512. 

Edit: It seems to only happen with pressure inference on.

**Comment by rolandlo** [comment]
I only experience this with input debug flag set on.

**Comment by personalizedrefrigerator** [comment]
Can reproduce with pressure inference off (and a stylus that has pressure sensitivity) on Linux.
