### ISSUE TITLE
Regression: Cannot select whole words with (Ctrl+Shift+right/left arrow) in text mode

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2861]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: Ubuntu 20.04,  Gnome X11
 - Which version of libgtk do you use: libgtk: 3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - Xournal++ 1.1.0+dev
 - Installation method: From source

**Describe the bug**
Used to be able to use common shortcuts ctrl+shift+right/left arrow in text mode to select multiple words in a specific direction _in version 1.0.20_ .

**To Reproduce**
1. Use Text tool
2. Write something
3. Try to select word using: Ctrl+Shift+right/left arrow.
4. Shortcut doesn't work anymore

**Comment by personalizedrefrigerator** [comment]
It looks like the shortcut is now being used for switching layers...

**Comment by personalizedrefrigerator** [comment]
We could maybe disable these (and other shortcuts that interfere with text editing) when editing text. See https://stackoverflow.com/questions/1707188/how-to-disable-inactive-some-of-the-gtkmenu-items

**Comment by personalizedrefrigerator** [comment]
Should be fixed by #2766
In the long term, though, we should enable/disable related shortcuts when editing text.
