### ISSUE TITLE
In Raspberry Pi, the writing pad vanishes after zooming in

### ISSUE THREAD

**Issue by apandada1** [xournalpp/xournalpp#2875]
**Affects versions :**
 - OS: GNU/Linux - (armhf/armv7h) Raspberry Pi OS (based on Debian Buster) and Arch Linux Arm
 - (Linux only) Desktop environment: LXDE (RPi OS) and XFCE (Arch)
 - Which version of libgtk do you use
     - 3.24.25 (Arch Linux Arm)
 - Version of Xournal++: 1.0.20-hotfix
 - Installation method: Stable PPA in Raspberry Pi OS and official Arch Repositories in Arch Linux Arm 

**Describe the bug**
When I zoom in beyond 60-70%(may depend on the screen size), the writing pad suddenly vanishes, and cannot be found by scrolling.

**To Reproduce**
1. Install Xournal++ from either the stable PPA (which hosts armhf version) in Raspberry Pi OS or from the official Arch Linux Arm/Manjaro repositories (with either LXDE or XFCE, I have not tested other DEs).
2. Keep zooming in
3. Suddenly the writing area vanishes

**Expected behavior**
The area of writing should not vanish (it does not vanish in the same version of xournalpp in x86_64 architecture)

**Screenshots of Problem**
Before zooming in
![Screenshot_2021-02-25_12-09-08](https://user-images.githubusercontent.com/3063132/109123059-6c7ae280-776f-11eb-83c6-979eb22ffb44.png)
After zooming in
![Screenshot_2021-02-25_12-07-58](https://user-images.githubusercontent.com/3063132/109123066-6e44a600-776f-11eb-8810-ba4f743e393f.png)

**Additional context**
I am using a Raspberry Pi 2, if it is relevant. This bug is absent in XFCE in my x86_64 computer, so the problem may not be DE specific.
I am compiling the master branch in Raspberry Pi to see if the bug is present there too, but it would take some time to compile (please enable armhf builds in the daily builds PPA, that would make bug tracking on a Raspberry Pi much more convenient).

**Comment by apandada1** [comment]
The bug is absent in a armv8 (arm64) version of Manjaro XFCE chroot running in Termux in my Android phone. Maybe the bug is only present in armv7h (stable versions of Raspberry Pi OS is still only available for armv7h).

**Comment by apandada1** [comment]
The bug is fixed in the master branch as of commit https://github.com/xournalpp/xournalpp/commit/e5cdd5f2a15546386e49ed31461f8a394eec1bb0 (I used the `xournalpp-git` from AUR in Arch Linux Arm, XFCE). 

Please enable the daily builds for armhf in the PPA, so that it can be installed (without compiling) in Raspberry Pi OS too.

I will close the issue once I verify that the master branch does fix the bug in Raspberry Pi OS.

**Comment by rolandlo** [comment]
> Please enable the daily builds for armhf in the PPA, so that it can be installed (without compiling) in Raspberry Pi OS too.

Are you sure the Ubuntu PPA builds will work for (the Debian based) Rasperry Pi OS?

**Comment by apandada1** [comment]
@rolandlo  Adding the PPA to Debian is discouraged because the PPA can cause dependency issues, in case the PPA hosts updated dependencies which are incompatible with other packages in debian.

But I manually downloaded the .deb file from the PPA and then installed it with gdebi. This way, if the dependencies are not available, then it can't be installed, and if all dependencies are satisfied, it would work without breaking anything (and it won't cause any issue in future, because I am not adding the repository).

I have used the armhf .deb file from the stable PPA in RPi OS, and there were no dependency issues. Also, Ubuntu (server image) is available in armhf for RPi 2, and that version would fully support the PPA.

**Comment by rolandlo** [comment]
>  have used the armhf .deb file from the stable PPA in RPi OS, and there were no dependency issues.

What series did you use? Bionic, Focal, Groovy or Hirsuite?

**Comment by apandada1** [comment]
I used bionic. But the packages in the PPA most likely have identical dependencies, as no distro-specific libraries are included in them (unlike those in GitHub releases). 

Anyway, I can check and report back if releases for Focal or recent versions cause any issue in RPi OS.

**Comment by rolandlo** [comment]
You can try out this [test build](https://code.launchpad.net/~rolandlo/+archive/ubuntu/xournalpp-test/+build/21083128) and report back, if it works.

**Comment by apandada1** [comment]
> You can try out this test build and report back, if it works.

It refuses to install due to missing dependencies (e.g. older version of glib, missing libzip5) in RPi OS Buster. Bionic is based on Debian Buster, and `1.1.0+dev` [fails to build on bionic](https://github.com/xournalpp/xournalpp/pull/506#issuecomment-695328275) too. It worked with bionic (and buster) until 1.0.20.

We would have to wait till RPi OS Bullseye is released (I would see in the Raspberry Pi forums if some early builds are available). In the meanwhile, I would test it in Ubuntu 20.10 for Raspberry Pi 2, which is based on Bullseye.

**Comment by apandada1** [comment]
@rolandlo It turns out that there is no `libzip5` package in Debian Bullseye, so xournalpp (1.1.0+dev) is not installable. And, it refuses to run (due to missing `libzip5`) when I manually install `libzip4`, and force install the package in Bullseye.
Possibly the bug is fixed, because it worked on Arch XFCE, but I want to be sure before this is closed (otherwise, someone may create a duplicate bug report in future, which may cause confusion in case this bug report is closed as fixed).

@Barak Any suggestions? Does your debian package work without `libzip5`? Do you already have a package build for `armhf`?  Then I could easily test it. Otherwise, it takes more than an hour to build on RPi2.

**Comment by barak** [comment]
@apandada1 The numbering of the shared binary library has diverged between Ubuntu and Debian. My recollection is vague, but I think Ubuntu made some horrible mistake that forced them to retire the name `libzip4` and go to `libzip5`, and this issue did not affect Debian.

In any case, the generated binary package's dependency on `libzipX` is generated during the build process. The actual build-time dependency is on `libzip-dev`, which works on both Debian and Ubuntu. It's only the generated binary packages that manifest this difference. So if someone with a Raspberry Pi downloads the source and builds it for themselves (cross-compilation on a beefy desktop should work) this shouldn't be an issue.

**Comment by apandada1** [comment]
This is most likely a duplicate of #2514

**Comment by apandada1** [comment]
I can confirm that this has been fixed in version 1.1.0
