### ISSUE TITLE
In the sidebar, the content of the pages does not appear

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2877]
OS : Windows 10
Version of xournal : 1.1.0.dev-nightly.20210226

When I choose "pages" in sidebar, the content of the pages does not appear in the sidebar (all the page thumbnails are completely white).

**Comment by rolandlo** [comment]
I can't reproduce it. Please provide more information. Does this happen for all documents or only e.g. for specific backgrounds. Provide a test document. The sidebar should update all 5 seconds. It does not update immediately.

**Comment by MichelReims** [comment]
indeed, there was a lot of writing on my pages and I hadn't waited long enough to see the text appear in the thumbnails.
Thank you
