### ISSUE TITLE
Give the possibility to manage default color pickers

### ISSUE THREAD

**Issue by vfractal** [xournalpp/xournalpp#2884]
Hello,

Need the possibility to be able to manage/configure default color pickers.

When i work I have some predefined colors and for changing I have to  click on "select  color" and then select the color.

So i would to propose to add the possibility to customize default predefined colors for a better and faster work.
+ default colors are too aggressive.

Best regards.

**Comment by rolandlo** [comment]
This will soon be realized in Xournal++, see PR #2379

**Comment by kauesena** [comment]
Is this already possible?

**Comment by LittleHuba** [comment]
No as soon as #2379 is merged, you can try this in the nightly releases.

**Comment by kauesena** [comment]
Thanks. I'll surely try it once it is merged.

**Comment by bhennion** [comment]
Fixed via #2379
