### ISSUE TITLE
Crash when scrolling through PDF with sidebar open on Layer/Layerstack Preview

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2887]
**Affects versions** :
* OS: Linux
* Desktop environment: Ubuntu 20.04, Gnome X11
* libtk: libgtk: 3.24.20
* Xournal version: Xournal++ 1.1.0+dev
 * Installation method: From source

**To Reproduce**

1. Open PDF with X++.
2. Open sidebar on **Layer preview**.
3. Scroll through PDF. *Note*: It typically crashes within 1-10 seconds of continuous scrolling.
4. X++ crashes.

Random PDF I found online to test on, but I think this problem occurs on any pdf.
[Report_Writing_Process_principles_and_styles.pdf](https://github.com/xournalpp/xournalpp/files/6057657/Report_Writing_Process_principles_and_styles.pdf)

**Additional Details**
* I've gotten this crash many times in the past but this is the first time I was able to find a reproducible patern for it.
* Don't think it occurs for 1.0.20

**Comment by nicolae-stroncea** [comment]
Stack trace:



stack trace:
Date: Sat Feb 27 13:21:44 2021
Error: signal 11
[bt]: (0) xournalpp(+0x4311c2) [0x55d6e6d4e1c2]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f60d4191210]
[bt]: (2) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_queue_draw+0x32) [0x7f60d5288812]
[bt]: (3) xournalpp(+0x2addf3) [0x55d6e6bcadf3]
[bt]: (4) xournalpp(+0x2ae71e) [0x55d6e6bcb71e]
[bt]: (5) xournalpp(_ZNKSt8functionIFvvEEclEv+0x36) [0x55d6e6d58772]
[bt]: (6) xournalpp(+0x43af9d) [0x55d6e6d57f9d]
[bt]: (7) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x30f4d) [0x7f60d4e19f4d]
[bt]: (8) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f60d56f0e6e]
[bt]: (9) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52220) [0x7f60d56f1220]
[bt]: (10) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f60d56f12c3]
[bt]: (11) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f60d4b3cfd5]
[bt]: (12) xournalpp(_ZN11XournalMain3runEiPPc+0x5ef) [0x55d6e6bbdb12]
[bt]: (13) xournalpp(main+0x29) [0x55d6e6b7b2d2]
[bt]: (14) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f60d41720b3]
[bt]: (15) xournalpp(_start+0x2e) [0x55d6e6b7b1ee]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x431734) [0x55d6e6d4e734]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f60d4191210]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_queue_draw+0x32) [0x7f60d5288812]
??:0
[bt] #4 xournalpp(+0x2addf3) [0x55d6e6bcadf3]
??:0
[bt] #5 xournalpp(+0x2ae71e) [0x55d6e6bcb71e]
??:0
[bt] #6 xournalpp(_ZNKSt8functionIFvvEEclEv+0x36) [0x55d6e6d58772]
??:0
[bt] #7 xournalpp(+0x43af9d) [0x55d6e6d57f9d]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x30f4d) [0x7f60d4e19f4d]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f60d56f0e6e]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52220) [0x7f60d56f1220]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f60d56f12c3]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f60d4b3cfd5]
??:0
[bt] #13 xournalpp(_ZN11XournalMain3runEiPPc+0x5ef) [0x55d6e6bbdb12]
??:0
[bt] #14 xournalpp(main+0x29) [0x55d6e6b7b2d2]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f60d41720b3]
??:0
[bt] #16 xournalpp(_start+0x2e) [0x55d6e6b7b1ee]
??:0

**Comment by nicolae-stroncea** [comment]
Update: **Layerstack preview** in the sidebar has the same issue, though **Page Preview** does not.

**Comment by personalizedrefrigerator** [comment]
This is the backtrace I'm getting from GDB:
![Backtrace from GDB](https://user-images.githubusercontent.com/46334387/109927296-d5cf8980-7c78-11eb-8305-bef1cf93a7fd.png)

**Comment by personalizedrefrigerator** [comment]
I'm working on a fix for this!
