### ISSUE TITLE
Moving selections is unstable/highly sensitive when selection is only partially in view

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2889]
**Affects versions** :
* OS: Linux
* Desktop environment: Ubuntu 20.04, Gnome X11
* libtk: libgtk: 3.24.20
* Xournal version: Xournal++ 1.1.0+dev
 * Installation method: From source

**Describe the bug**

Moving a selection (a selected image, group of shapes, text, etc) throughout the page is unstable if you move a selection that is only partially on display(with the rest of it being out of your current view but still on the same page). For the best example of this consider when the  zoom level is more than 100%. 

By unstable I mean that the selection moves extremely quickly, maybe about 6-7 pages per second, if you even _lightly/accidentally_ move some selected region which is not fully on display _in the direction of where the rest of the selection is(i.e rest of selection is above, and you move selection slightly up._ This is especially inconvenient and disorienting when you make a large selection, which makes the issue much more likely to occur.

**Expected behavior**

Selections are moved **significantly slower** for this case.

**Screenshots of Problem**

Below is a screencast of 2 examples. For reference, the selection moves quicker than shown here, where it seems slowed down due to framerate.
[webcast_of_issue.zip](https://github.com/xournalpp/xournalpp/files/6058203/webcast_of_issue.zip)

**Comment by Photon89** [comment]
I can confirm and have the same issue. I guess, the algorithm starts scrolling when the upper or lower edge of the object comes into the vicinity of the upper or lower edge of the visible part of the page, but when the object is already at (or even over) the edge, the scrolling is triggered immediately and doesn't stop as the object keeps being over the edge.

Proposal for a fix: If the object's edge is already past the visible page's edge, start scrolling but don't move the object till its edge gets visible. Once the object's edge is visible, switch to usual mode.

**Comment by personalizedrefrigerator** [comment]
See
https://github.com/xournalpp/xournalpp/blob/5e78a44f8668418ad34468b2e9bfa27f9a61740e/src/gui/inputdevices/PenInputHandler.cpp#L416-L449

**Comment by nicolae-stroncea** [comment]
Wanted to add a further detail. If you hit "Undo" once this happens, X++ freezes up for a couple of seconds. It doesn't crash and recovers but you get a long stack trace with warnings

**Comment by tattsan** [comment]
Confirmed. I also observed that unintentional copies are created.
Perhaps these are the mentioned objects which the backtrace says 
``Could not remove element from layer, it's not on the layer!``

**Comment by Technius** [comment]
The "out of view" issue is #1232, which I have reopened. We can consider it to be irrelevant for the purposes of this issue.

**Comment by Esokrates** [comment]
Same issue here. Here is a file I can reproduce this very easy with:
[move-bug.zip](https://github.com/xournalpp/xournalpp/files/6335769/move-bug.zip)

1. Make sure you set Zoom to "Fit to screen".
2. Select the lower text box and try to move it with a STYLUS (mouse does not seem to be affected)
3. Notice the textbox being accelerated so fast that you end up anywhere in the document.

Reproduced with current master (self compiled) on Linux (Gnome-Wayland).

**Comment by mjg** [comment]
In fact, even when it works as intended I find it annoying because it basically keeps you from lining up a large item with something else that would be in view if xournalpp didn't try to keep all edges of the moving selection in view.

Auto-scrolling based on the cursor position should be enough and would solve this issue here, as well :)

**Comment by Photon89** [comment]
Just tested, works much better now, thanks!

**Comment by Quantenzitrone** [comment]
I still have this issue when trying to align a large selection perfectly

I have Xournal++ 1.1.1 installed from nixpkgs

**Comment by Quantenzitrone** [comment]
As an alternative behavior, I think the scrolling should only happen if the cursor moves close to the border of the drawing area.

I think an option in the settings to switch between: "drag scrolling on selection being outside the drawing area", "drag scrolling on cursor being close to the drawing area border" and "no drag scrolling" would be the solution that would make everyone happy.

**Comment by Quantenzitrone** [comment]
should i open a new issue for this?
