### ISSUE TITLE
Option for enforcing a language for GUI in Settings menu

### ISSUE THREAD

**Issue by wuffi** [xournalpp/xournalpp#2895]
Xournal++ currently tries to guess the language of the GUI by determining the language used by the underlying operating system.
This sometimes goes wrong for me and also other users, who reported similar issues here: see <https://github.com/xournalpp/xournalpp/issues/1265>, <https://github.com/xournalpp/xournalpp/issues/1470> and <https://github.com/xournalpp/xournalpp/issues/1848>

A quick workaround is to set a "LANG" environment variable with a valid country code (for example "IT" for Italian), which will however also affect all other programs.

For convenience and inexperienced users, an option to choose between languages in the Settings menu (under "Edit" in the menu bar) would be helpful.  
This would also be helpful for users who use Xournal++ for presentations in foreign languages and switch between languages for different presentations.

**Comment by tattsan** [comment]
It is already in 1.1.0-dev. Try [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly).
