### ISSUE TITLE
Please implement an option for a default PDF export file name including wildcards 

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#2897]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a PDF file with Xournal++, annotate it, then export the annotated file as PDF and the proposed file name matches the file name of the original PDF which cannot be overwritten. So I have to change from tablet to laptop mode each time I export the annotated file to use the keyboard and modify the file name.

**Describe the solution you'd like**
Provide a setting for the exported PDF default file name similar to the already existing setting for the default file name of the saved .xopp file. A possible wildcard could be the file name of the original PDF file (if existent) or .xopp file's name (if no background PDF existent) which then could be modified by some suffix, say %{original file name}_annotated.pdf

**Describe alternatives you've considered**
Another possible solution is already discussed in https://github.com/xournalpp/xournalpp/issues/2363.

**Comment by nicolae-stroncea** [comment]
I think the benefit of a default _editable_ export name extension (like "%{original file name}_annotated") is twofold:
* Users don't need to change the name every time they export, as the current default is you get an error until you change it.
* Users can be allowed to forcefully export to the same name as the original pdf, by changing name to name of PDF. Because the default will be set to something like "_annotated.pdf", this would get rid of any errors where the user accidentally overrides the default. Moreover, a confirmation box can be displayed to confirm that the user will override the background if they choose to do so.

**Comment by Technius** [comment]
Upgrading to high priority as this would solve all of the various complaints and differences in opinion about expected filename of exported files.

**Comment by forgottosave** [comment]
I can take a look at this in the next week(s).

After implementing the logic for this, which shouldn't be too difficult (famous last words :P), I'd probably implement a new point in the settings in `Load / Save` named something like `Default pdf-export name` where a string can be entered using wildcards (similar to the suggestion in the issue) to change the default name.

**Comment by forgottosave** [comment]
Should there be more wildcards, other than the original file name? I couldn't come up with any, other than maybe the current date and time.

And if the name is the only wildcard option, should I still implement it in a way, that future wildcards are easy to add? Because this does make a difference in the changed code.

**Comment by Technius** [comment]
> I can also open a PR with my current changes to discuss implementation details, if this is preferred over the issue thread

That would be very helpful. It would also be great if you could include a list of wildcards that you plan to support.

**Comment by bhennion** [comment]
Fixed via #4599

**Comment by Photon89** [comment]
@bhennion I completely missed that this has been fixed, great news! I installed the latest git version and can see that the default file name for PDF export is not ${name}_annotated.pdf, but I cannot find any setting where the file name structure can be set. I'd expect it in the Load/Save settings tab where the default .xopp file name is set as well, but couldn't find it there (and nowhere else as well). Am I missing something or is there some problem yet to be solved? :smiley:

**Comment by forgottosave** [comment]
The UI settings implementation is not done yet.
What you can do is change it manually in your xourbal config file and search for the line `defaultPdfExportName` to whatever you want

**Comment by Photon89** [comment]
Ah, I see, thanks for the clarification! Can we have this reopened to track the UI implementation progress? Thanks! And also thanks for the work done so far!

**Comment by Photon89** [comment]
@bhennion Great, thanks for this new feature  making it into the GUI!

I tested it and have another, rather luxury, idea: One could make the wildcards dependent from the context (PDF editing vs. note taking).

Say, when annotating a PDF, it would be good to have something like `%{name}_annotated`, while when making notes, it would be good to have just `%{name}`. I don't know if this would be hard to implement, and also if it would make the settings dialog too overloaded.

One possible implementation would be some kind of operator for the wildcards, which only shows the following variable when in a specific context. Say, `%p{...}` would only show in PDF annotation mode but not in note taking mode, while `%n{...}` would only show in note taking mode but not in PDF annotation mode.

In my use case, I'd then set `%{name}%p{_annotated}` and have the suffix only for annotated PDFs and not for notes.

No idea if the operators naming makes sense this way, but I think, you get my idea!

**Comment by alqualin82** [comment]
I find the current implementation very confusing. When I annotate a pdf file, and save this as an xopp file, giving it perhaps a new name, then when I export to pdf it uses the name of the original pdf file rather than my given xopp file name. So I keep having to change the file names twice.

**Comment by Photon89** [comment]
Maybe there should be %{pdf-name} and %{xopp-name} instead of just %{name}?
