### ISSUE TITLE
Stylus input on Ubuntu 20.10

### ISSUE THREAD

**Issue by derEisbaerX** [xournalpp/xournalpp#2898]
Dear all,
is Ubuntu 20.10 supported? My graphic tablet is no longer working with xournalpp after the system update.
More detailed information are attached below.
Best regards,
derEisbaerX

**Affects versions :**
 - OS: Ubuntu 20.10
 - Desktop environment: X11
 - Version of Xournal++: latest stable and nightly release (1.1.0+dev)
 - Version of libgtk: 3.24.23
 - Installation method: ppa

**Describe the bug**
I can no longer draw with the pen/stylus of my huion tablet. I can select the tools (pen, eraser,...) but they have no effect on the behavior of the pointer. The pointer is moving correctly but only scrolls the page when applying pressure.

**To Reproduce**
1. Install Ubuntu 20.10 (xournalpp was fully functional with LTS 20.04)
2. Add one of the two xournalpp apt repos, update, install xournalpp
3. Launch application and try to draw

**Expected behavior**
I expect that I can draw with the stylus after selecting the pencil tool.

**Additional context**
The problem occured after updating to ubuntu 20.10 from ubuntu 20.04

**Comment by personalizedrefrigerator** [comment]
Please post a screenshot of input system/input devices -- it might be the stylus is being recognized as a touchscreen.

![image](https://user-images.githubusercontent.com/46334387/109736319-fa443c80-7b78-11eb-8bd3-32a413f7f81a.png)
<i>The above is what mine looks like, on a computer without a stylus.</i>

Ubuntu 20.10 should be supported! Thank you for reporting this!

**Comment by personalizedrefrigerator** [comment]
If the above doesn't work, or if you don't have pressure sensitivity after designating your stylus as a stylus, (if you have time :)), please try any/all:
 * [The AppImage](https://github.com/xournalpp/xournalpp/releases/tag/nightly)
 * [Building from source](https://github.com/xournalpp/xournalpp/blob/nightly/readme/LinuxBuild.md)
 * If you have an option to select GNOME/Wayland or GNOME/X11 on login, try selecting GNOME/Wayland (or GNOME/X11 if you were using Wayland before).

Additional information that might be helpful in resolving this:
 * Output of `xinput --list` from a terminal (gives some information about input devices, probably somewhat redundant because Preferences/Input System mostly does this).

**Comment by rolandlo** [comment]
@derEisbaerX I can also confirm that Xournal++ runs fine on Ubuntu 20.10 (with stylus). So probably something is wrong with your input system settings.

**Comment by derEisbaerX** [comment]
Thank you all for the quick help!
My input system settings looked weird (e. g. pen and pen(0) registered) and I decided to purge the digimend-driver (https://github.com/DIGImend/digimend-kernel-drivers) and xournalpp. After several tries and some disappointing intermediate results  my tablet is working again like it was before the system update.

I think the steps should be:
1. Disconnect tablet
2. Purge xournalpp and digimend-driver
3. Delete settings from xournalpp, located in home
4. Reinstall digimend-driver and xournalpp
5. Reconnect tablet
6. Open xournalpp

My configuration now looks like:
`lars@lenovo:~$ xsetwacom list

lars@lenovo:~$ xinput --list

⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ BTL Gaming Mouse Consumer Control       	id=11	[slave  pointer  (2)]
⎜   ↳ BTL Gaming Mouse                        	id=12	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=18	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d Dial                      	id=20	[slave  pointer  (2)]
⎜   ↳ HID 256c:006d Pen (0)                   	id=23	[slave  pointer  (2)]
`
![image](https://user-images.githubusercontent.com/71793357/109789157-573f0180-7c10-11eb-9bb9-e0fabefb5367.png)

I will close this issue now :)

**Comment by derEisbaerX** [comment]
I want to give an update on this issue:
After a restart of my computer the problems returned. I got the following output:
`$ xsetwacom list
HID 256c:006d stylus            	id: 15	type: STYLUS    
HID 256c:006d Pad pad           	id: 16	type: PAD       
HID 256c:006d Touch Strip pad   	id: 17	type: PAD       
`
The configuration which solved the problem for me this time is:
![Screenshot from 2021-03-05 14-17-21](https://user-images.githubusercontent.com/71793357/110120598-88a90000-7dbd-11eb-91d7-4ef65fb9304a.png)
