### ISSUE TITLE
Clang-format broken in Azure pipelines

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2899]
**Affects versions :**
 - Azure Pipelines/CI

**Describe the bug**
`clang-format` is failing. 

**To Reproduce**
1. Change files that require a re-run of the formatting pipeline.
2. Run clang format on files locally
3. Run files through pipeline.

**Expected behavior**
The pipeline shouldn't fail.

**Screenshots of Problem**
![Error message complains of an issue with a value in a YAML file: Invalid boolean on line 10, column 16; Align is not a boolean](https://user-images.githubusercontent.com/46334387/109758064-e95af180-7b9f-11eb-8c4a-8050cff37bb6.png)

**Additional context**
This seems to be due to what seems to be an issue with a configuration file (`.clang-format`?).
The line 
https://github.com/xournalpp/xournalpp/blob/81982f8af782efb0718d033633c35efda58f66f7/azure-pipelines/util/format_diff_lines.pl#L70
runs `clang-format`, which fails.

This portion of `clang-format --help` (from `clang-format` version 11) seems relevant.
```
  --style=<string>           - Coding style, currently supports:
                                 LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.
                               Use -style=file to load style configuration from
                               .clang-format file located in one of the parent
                               directories of the source file (or current
                               directory for stdin).
                               Use -style="{key: value, ...}" to set specific
                               parameters, e.g.:
                                 -style="{BasedOnStyle: llvm, IndentWidth: 8}"
```

**Comment by personalizedrefrigerator** [comment]
I think this is the line it was complaining about:
https://github.com/xournalpp/xournalpp/blob/81982f8af782efb0718d033633c35efda58f66f7/.clang-format#L10

**Comment by Febbe** [comment]
Gonna take a look. The clang-format team breaks every version by changing those options without support for older/newer options. :angry:

**Comment by Technius** [comment]
The clang-format version is pinned for a good reason: to avoid random sudden breakage, like in this case.

**Comment by Febbe** [comment]
According to the [clang-format-12 doc](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) it's correct. Maybe the script is not using clang-format-12.

**Comment by Febbe** [comment]
We installed clang-format-12, but did not use it. The search order was clang-format -> clang-format-9, but it should be clang-format-12 -> clang-format.
