### ISSUE TITLE
Bring up the floating toolbox without tapping the screen

### ISSUE THREAD

**Issue by jpoiret** [xournalpp/xournalpp#2901]
**Is your feature request related to a problem? Please describe.**
For now, the Floating toolbox is considered a tool that you have to tap in order to bring up, which for example prevents the user from keeping some strokes selected and applying color via the toolbox, as using the floating toolbox deselects everything.

**Describe the solution you'd like**
I think bringing up the toolbox directly whenever the corresponding stylus button is pressed would be more natural, and also resolve the problem above.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by reedrs** [comment]
I have been using the floating toolbox feature in version 1.0.20 for a while now, and it had been behaving exactly as this enhancement request suggests: pressing a button on my stylus would activate the toolbox, without having to tap the screen.

I just upgraded to version 1.1.0, and now the behavior has changed back to having to tap on the screen before the toolbox will appear.

I thought this was a regression in 1.1.0, but after seeing this enhancement request, I'm not so sure. Was this feature ever implemented in the first place?

**Comment by redtrumpet** [comment]
> I have been using the floating toolbox feature in version 1.0.20 for a while now, and it had been behaving exactly as this enhancement request suggests: pressing a button on my stylus would activate the toolbox, without having to tap the screen.
>
> I just upgraded to version 1.1.0, and now the behavior has changed to having to tap on the screen before the toolbox will appear.

Same for me. However, if I enable the "new input system" in the preferences for 1.0.20, then it doesn't work.
 
> I thought this was a regression in 1.1.0, but after seeing this enhancement request, I'm not so sure. Was this feature ever implemented in the first place?

Apparently, the old input system was replaced by the new one in version 1.1.0. So this is somewhat consistent with the behavior I experience in 1.0.20.

Enabling the "Merge button events with stylus tip events" makes this work again with the new input system (for both 1.0.20 and 1.1.0).

**Comment by reedrs** [comment]
> Same for me. However, if I enable the "new input system" in the preferences for 1.0.20, then it doesn't work either.

I was not using the new input system in 1.0.20, so that makes sense.

> Apparently, the old input system was replaced by the new one in version 1.1.0. So this is somewhat consistent with the behavior I experience in 1.0.20.
> 
> Enabling the "Merge button events with stylus tip events" makes this work again with the new input system (for both 1.0.20 and 1.1.0).

Oh, neat! I'm not quite sure what that option is meant for, but I can confirm it makes the floating toolbox appear without tapping. Seems like a useful workaround.

**Comment by redtrumpet** [comment]
> Oh, neat! I'm not quite sure what that option is meant for, but I can confirm it makes the floating toolbox appear without tapping. Seems like a useful workaround.

Here is some additional info about that option, the hint is a bit misleading: #2496 

I got some other troubles with that option though, and this might not be the right thing to do, if `TabletButtonPC` is set to `off`.
