### ISSUE TITLE
"Error opening file" on SD card

### ISSUE THREAD

**Issue by kg6gfq** [xournalpp/xournalpp#2905]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux - Ubuntu 20.04
 - (Linux only) Desktop environment: Gnome (X11, I think)
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: 1.0.20 commit ea457c9f
 - Installation method: Snap

**Describe the bug**
When opening a .xopp file stored on a 128 GB microSD card formatted as exFAT, xournal++ raises a dialog box that says:
> Error opening file "/path/to/filename"
> Could not open file: "/path/to/filename"

with an "OK" button at the bottom.  

**To Reproduce**
Steps to reproduce the behavior: see above

**Expected behavior**
Xournal++ opens the file.

**Comment by Febbe** [comment]
Can you try if this is fixes with the newest nightly, v.1.0.20 is the last release of the 1.0.x cycle, and we probably addressed that issue with the change to `std::filesystem`.

**Comment by kg6gfq** [comment]
You're right; the latest nightly works just fine.  Thank you!
