### ISSUE TITLE
Scanned PDF showing grid lines

### ISSUE THREAD

**Issue by J4gQBqqR** [xournalpp/xournalpp#2908]
Hi I am trying to use Annotation PDF feature on Windows.
However, the opened PDF file is showing a lot of ugly grids on Windows Xournalpp:
![image](https://user-images.githubusercontent.com/77554817/110127193-5682a880-7d93-11eb-896d-23902445981f.png)

Could any one help to identify is this an issue or is this my software misconfiguration?

**Comment by tattsan** [comment]
This PDF probably contains a lot of image data on each page, not just one image per page. I once received such data and converted it to a PDF with one image per page by printing it on a virtual PDF printer.

**Comment by tattsan** [comment]
I'm wondering why such PDFs are produced, but maybe there is a distortion correction function in the scanning software that produces this kind of output.

**Comment by J4gQBqqR** [comment]
Thank you for the help! I will print it to another PDF and work on single image.
:+1:
