### ISSUE TITLE
Missing `cmath` include

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#291]
I have problem compiling (on Ubuntu 18.04) from missing `#include <cmath>` in several files. I added it manually to a bunch of them, but probably this is not the exact strategy, so I stopped. The first file to fail was `src/control/tools/ArrowHandler.cpp ` (with unkwon function `sin()`) --- I fixed this and several more but stopped because there must be a more general place where to put the needed `#include <cmath>`. 

Thanks for the nice job on `xournalpp`!

**Comment by Rmano** [comment]
By the way, the patch I needed to apply to compile `xournalpp` is attached. Feel free to use, change or throw it away ;-). 

A couple more nitpicks (not worth a pull request): in the `README.md`, please remove the newlines in the `sudo apt-get install ...`, so that it could ne copied and pasted. Also, in Ubuntu 18.04 there is no `libopenjpeg" (nor it seems it's needed). 

[xournalpp-cmath.zip](https://github.com/xournalpp/xournalpp/files/2571365/xournalpp-cmath.zip)

**Comment by JoeKays** [comment]
The easiest solution I found is to just add:
`#include <cmath>`
to **src/util/XournalType.h**

**Comment by Rmano** [comment]
Fixed after the pull. Although probably the correct fix was to change math.h to cmath...  https://stackoverflow.com/questions/15656434/include-cmath-vs-include-math-h-in-a-c-program
