### ISSUE TITLE
Insert Tex does not work if windows username is too long.

### ISSUE THREAD

**Issue by mitzal** [xournalpp/xournalpp#2910]
Hi,
I have a problem with inserting Tex equations on Windows 10. I have already tracked down the reason and I think it should be fairly easy to fix.  

**Affects versions :**
 - OS: Windows
 - libgtk: 3.24.25
 - Version: tested with 1.0.18, 1.0.20, 1.1.0+ dev
 - Installation method: official release

**Describe the bug**
Cannot insert latex equations (pdflatex does not find tex.tex file). Problem appears only, if windows username is too long. 

**Description of the problem**
On Windows, `g_get_tmp_dir` gets temp dir from TEMP environment variable, which is,
for compatibility reasons, in short form (8.3 naming convention). Long file names are 
shortened to prefix and index of that prefix in folder (e. g. LongProfileName -> LONGPR~1).
Because pdflatex has problems with short names, after retrieved from `g_get_tmp_dir`, 
temp path should be converted to long form.

On MSVC, std::filesystem::weakly_canonical does the trick, but I'm not sure for other implementations.
Alternatively, GetLongPathName could be used.

**To Reproduce**
1. Set long profile names to TMP and TEMP variables (e.g. C:\Users\LongProfileName\AppData\Local\Temp).
2. Create needed folders (TEMP path should exist).
3. Retrieve the path (e. g. ps> $env:TEMP), should be in short form (C:\Users\LONGPR~1\AppData\Local\Temp).
4. Run Xournal++ and try to insert tex equation.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Short example of getting normal path:
```
#include <iostream>
#include <Windows.h>
#include <filesystem>
using namespace std;

int main() {
	std::wstring p, longPath;

	auto sz = GetEnvironmentVariableW(L"TEMP", p.data(), (DWORD)p.size());
	p.resize(sz);
	sz = GetEnvironmentVariableW(L"TEMP", p.data(), p.size());

	sz = GetLongPathNameW(p.c_str(), longPath.data(), longPath.size());
	longPath.resize(sz);
	sz = GetLongPathNameW(p.c_str(), longPath.data(), longPath.size());

	std::wcout << "env path:       " << p << '\n';
	std::wcout << "canonical path: " << std::filesystem::weakly_canonical(p).wstring() << '\n';
	std::wcout << "long path:      " << longPath << '\n';
	
	return 0;
}

/* MSVC output
env path:        C:\Users\LONGPR~1\AppData\Local\Temp
canonical path : C:\Users\LongProfileName\AppData\Local\Temp
long path :	     C:\Users\LongProfileName\AppData\Local\Temp
*/
```

Pdflatex output (with short and long name):
```
PS C:\Users\LongProfileName\AppData\Local\Temp\xournalpp-1432\tex> pdflatex -interaction=nonstopmode 'C:/Users/LONGPR~1/AppData/Local/Temp/xournalpp-1432/tex/tex.tex'
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.2)
entering extended mode
! I can't find file `C:/Users/LONGPR'.
<to be read again>
                   \protect
<*> C:/Users/LONGPR~
                    1/AppData/Local/Temp/xournalpp-1432/tex/tex.tex
Please type another input file name
! Emergency stop.
<to be read again>
                   \protect
<*> C:/Users/LONGPR~
                    1/AppData/Local/Temp/xournalpp-1432/tex/tex.tex
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.


PS C:\Users\LongProfileName\AppData\Local\Temp\xournalpp-1432\tex> pdflatex -interaction=nonstopmode 'C:/Users/LongProfileName/AppData/Local/Temp/xournalpp-1432/tex/tex.tex'
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.2)
entering extended mode
(C:/Users/LongProfileName/AppData/Local/Temp/xournalpp-1432/tex/tex.tex
LaTeX2e <2020-10-01> patch level 4
...
Output written on tex.pdf (1 page, 16051 bytes).
Transcript written on tex.log.
```
This was run from powershell, but when run from xournal++, error log was the same as here (when runned with short path).

**Comment by personalizedrefrigerator** [comment]
@mitzal Would you (or someone else with a Windows build environment) be willing to submit a PR for this?

Here are some relevant parts of the codebase (most relevant to least relevant):
https://github.com/xournalpp/xournalpp/blob/1002c131e1d7a1cb1243d955c611979b7faec488/src/util/PathUtil.cpp#L218-L230

https://github.com/xournalpp/xournalpp/blob/1002c131e1d7a1cb1243d955c611979b7faec488/src/util/PathUtil.h#L119

https://github.com/xournalpp/xournalpp/blob/1002c131e1d7a1cb1243d955c611979b7faec488/src/control/LatexController.cpp#L28

https://github.com/xournalpp/xournalpp/blob/1002c131e1d7a1cb1243d955c611979b7faec488/src/control/latex/LatexGenerator.cpp#L41

**I don't know which preprocessor macros/etc are defined when on Windows (i.e. for #ifdef #endif).**

**Comment by rolandlo** [comment]
@personalizedrefrigerator We use
```C++
#ifdef _WIN32
```
