### ISSUE TITLE
Xournal++ PDF auto-open: Not opening [filename].xopp, only [filename].pdf.xopp

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#2911]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/46334387/110197598-7355c500-7e01-11eb-9e50-d74837305552.png)
Xournal++ requires PDF files to have a corresponding `.pdf.xopp` file to auto-load the Xournal++ file with the same name. This is not the default filename when saving an annotated PDF for the first time.

**Describe the solution you'd like**
I would like Xounal++ to also auto-load `[filename].xopp`, in addition to `[filename].pdf.xopp`.

**Describe alternatives you've considered**
The default export name could be changed back to `[filename].pdf.xopp`/Xournal++ could stop removing the trailing `.pdf` before appending `.xopp` when exporting (which is what I think it used to do).

**Additional context**

**Comment by ngoonee** [comment]
This would be very convenient (and I think not very hard).
