### ISSUE TITLE
Control over pen size?

### ISSUE THREAD

**Issue by Kreijstal** [xournalpp/xournalpp#2913]
As far as I know  there are only 5 options, `very fine, fine, medium, thick, very thick`, which imho it's pretty limited, is this due to a inherent limitation or could the user choose an arbitrary value?

**Comment by rolandlo** [comment]
The file format would support arbitrary pen size, but the Gui only has these 5 options.

**Comment by Technius** [comment]
Related: #1361

**Comment by personalizedrefrigerator** [comment]
A workaround available in 1.1.0+dev:

![](https://user-images.githubusercontent.com/46334387/111021106-feddd180-837e-11eb-91dd-207db42bc4da.png)
Change the "Pressure Multiplier" under Settings > Stylus > Pressure Sensitivity. Unfortunately, this requires opening and closing settings.

**Comment by Technius** [comment]
Closing as duplicate of #1361.
