### ISSUE TITLE
LaTeX tables don't work

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2921]
Windows 10, nightly release. I tried to use both of these examples in creating a table, but none of them work:
```\begin{center}
\begin{tabular}{ c c c }
 cell1 & cell2 & cell3 \\ 
 cell4 & cell5 & cell6 \\  
 cell7 & cell8 & cell9    
\end{tabular}
\end{center}
```
and
```
\begin{table}[]
\begin{tabular}{lllll}
 &  &  &  &  \\
 &  &  &  &  \\
 &  &  &  &  \\
 &  &  &  & 
\end{tabular}
\end{table}
```

**Comment by rolandlo** [comment]
> Windows 10, nightly release. I tried to use both of these examples in creating a table, but none of them work:
> 
> ```
> \begin{tabular}{ c c c }
>  cell1 & cell2 & cell3 \\ 
>  cell4 & cell5 & cell6 \\  
>  cell7 & cell8 & cell9    
> \end{tabular}
> \end{center}
> ```
> 
> and
> 
> ```
> \begin{table}[]
> \begin{tabular}{lllll}
>  &  &  &  &  \\
>  &  &  &  &  \\
>  &  &  &  &  \\
>  &  &  &  & 
> \end{tabular}
> \end{table}
> ```

The first one works, if you leave out the `\end{center}`. Please test your LaTeX formulas with a LaTeX editor and the `standalone` document class

```tex
\documentclass[varwidth=true, crop, border=5pt]{standalone}
```
assuming you use the default LaTeX template.
