### ISSUE TITLE
The lock in positions on the zoom slider are incorrect with different DPI calibration values

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#2923]
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11 (Xfce)
 - Which version of libgtk do you use: 3.24.24
 - Version of Xournal++: 1.1.0+dev
 - Installation method: Repository package and AUR package (built from latest git)

**Describe the bug**
The zoom slider has two positions which are marked with vertical ticks and used to correspond to useful zoom levels (as far as I remember, "fit width" and "fit height"). Now they are set at 132% (for 95 DPI or 172% for 125 DPI) and 208% (independent of the DPI) and neither of them hits any of the two useful zoom levels (fit width would be at 119%).  

**To Reproduce**
1. Start Xournal++
2. Move the zoom slider to match one of the lock in positions
3. Observe that the zoom level is not particularly useful

**Expected behavior**
Maybe I'm mistaken (if so please close the issue) but I thought, the lock in positions had some useful zoom level like "fit width", this should be the case again. Otherwise, maybe they have some other meaning which is not documented via tooltip info text or in the Zoom settings.

**Screenshots of Problem**
![Ungespeichertes Dokument - Xournal++_001](https://user-images.githubusercontent.com/1191480/110373669-0b48ee00-8050-11eb-8296-c8c28fa45a2f.png)

**Comment by Technius** [comment]
If you set the DPI to 72 (the default), the left tick will be set to 100% and the right tick will be set to the zoom fit value. So I think the behavior observed here is a bug.
