### ISSUE TITLE
Cannot open a file with certain characters in the file name

### ISSUE THREAD

**Issue by sykoram** [xournalpp/xournalpp#2929]
**Affects versions :**
 - OS: Windows
 - Version of libgtk: 3.24.23
 - Version of Xournal++: 1.0.20, commit 09ec4999
 - Installation method: official release

**Describe the bug**
Cannot open a (PDF) file when there are certain characters in the file name.
It seems that Xournal++ removes some diacritics and does not recognize some special characters. When I open file `char-ě.pdf`, it is shown `char-e.pdf` in the DEBUG IN. (And this file does not exist of course, so the program cannot open it)

I've tested this with these strings:
`æ ɑ ꞵ ð ǝ ə ɛ ɣ ı ɩ ŋ œ ɔ ꞷ ʊ ĸ ß ʃ þ ʋ ƿ ȝ ʒ ʔ`
`ą a̧ ą̊ ɓ ç đ ɗ ɖ ę ȩ ə̧ ɛ̧ ƒ ǥ ɠ ħ ɦ į i̧ ɨ ɨ̧ ƙ ł m̧ ɲ ǫ o̧ ø ơ ɔ̧ ɍ ş ţ ŧ ų u̧ ư ʉ y̨ ƴ`
`á à ȧ â ä ǟ ǎ ă ā ã å ǻ ǽ ǣ ḅ ć ċ ĉ č ď ḍ ḑ ḓ é è ė ê ë ě ĕ ē ẽ e̊ ẹ ǵ ġ ĝ ǧ ğ g̃ ģ ĥ ḥ`
`í ì i î ï ǐ ĭ ī ĩ ị ĵ ķ ǩ ĺ ļ ľ ŀ ḷ ḽ m̂ m̄ ŉ ń n̂ ṅ n̈ ň n̄ ñ ņ ṋ ó ò ô ȯ ȱ ö ȫ ǒ ŏ ō õ ȭ ő ọ ǿ ơ`
`p̄ ŕ ř ŗ ṛ ś ŝ ṡ š ş ṣ ť ț ṭ ṱ ú ù û ü ǔ ŭ ū ũ ű ů ụ ẃ ẁ ŵ ẅ ý ỳ ŷ ÿ ȳ ỹ ź ż ž ẓ ǯ`
And there are lots of characters which are either replaced with a different one (`ř` -> `r`) or with question marks (`ꞵ` -> `?`). See the screenshots.

**To Reproduce**
1. Rename any PDF file to a name with some of these characters.
2. Try to open it with Xournal++
3. You can see that the file name is not same in the DEBUG IN (and therefore the program cannot find the file)

**Expected behavior**
Xournal++ should open a file with these characters in the file name successfully.

**Screenshots of Problem**
![screenshots](https://user-images.githubusercontent.com/41990490/110605657-9f6aa080-8189-11eb-8a2a-e05d3a02ff5c.jpg)

**Comment by rolandlo** [comment]
This may have been fixed in [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly). Please try it out and report back.

**Comment by sykoram** [comment]
Yes, looks as if it's really been fixed. No problems opening a file with these characters in the file name.

I think this issue can be closed now.
