### ISSUE TITLE
Don't show git commit information in the About dialog when not running the dev/git version

### ISSUE THREAD

**Issue by nekohayo** [xournalpp/xournalpp#2935]
This line could be hidden entirely when running a stable release in a system-installed packaged version from a distro:

![Screenshot from 2021-03-11 22-04-59](https://user-images.githubusercontent.com/479401/110886140-2a48b980-82b6-11eb-9619-513f232fa78d.png)

**Comment by Technius** [comment]
I don't think so.

**Comment by bhennion** [comment]
You're right. I don't know what made me believe it was.
