### ISSUE TITLE
Partial PDF export

### ISSUE THREAD

**Issue by Globulle** [xournalpp/xournalpp#2937]
**Is your feature request related to a problem? Please describe.**
I frequently use Xournal++ to add examples or solutions to exercises to the main lecture PDF and I need to sent the notes to students afterwards.

**Describe the solution you'd like**
I would like to be able to export the only pages I've added or annotated, not the whole file.

**Describe alternatives you've considered**
Currently I export the whole file, then extract the relevant pages with another tool (such as pdftk).

**Comment by rolandlo** [comment]
This is already implemented in [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly), both from the GUI (menu File -> Export As...) and the command line.
