### ISSUE TITLE
Shortcuts configuration menu

### ISSUE THREAD

**Issue by Globulle** [xournalpp/xournalpp#2938]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by not being able to customizing or adding shortcuts. For example, I would like to select red color by simply pressing the R key.

**Describe the solution you'd like**
A menu to configure shortcuts should be useful.

**Comment by rolandlo** [comment]
Duplicate of 919.

**Comment by Globulle** [comment]
Sorry, I did my best to find a previous similar issue but I missed this one...
