### ISSUE TITLE
Crashing all the time on latest stable Debian

### ISSUE THREAD

**Issue by GithubUser699** [xournalpp/xournalpp#2939]
**Affects versions :**
 - OS: **Debian GNU/Linux 10 (buster), 64-bit**
 - (Linux only) Desktop environment: **Wayland, according to synaptic (how do I find out?)**
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
     - **It's libgtk: 3.22.30**
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
     - **It's Xournal++ 1.0.20**
 - Installation method: **Snap. I also tried 'xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb' and 'xournalpp-1.0.20-x86_64.AppImage' but they didn't even install/start.**

**Describe the bug**
**The app crashes if I use control+s to safe that document, control+e to export it as pdf, if I close is using the x button in the top right corner (see additional information below) and randomly too. That is why I cannot even use this app for 5 minutes straight.**

**To Reproduce**
1. See `Describe the bug'. If you do that, it should crash (not always, but very often).

**Expected behavior**
It shouldn't crash.

**Additional context**
I added the output which got printed in the terminal if I start the app using `xounalpp' (launching from terminal or from app list didn't change anything regarding this bug) and I added the crash log which has been automatically created.
[terminal_output.txt](https://github.com/xournalpp/xournalpp/files/6133190/terminal_output.txt)
[errorlog.20210312-220234.log](https://github.com/xournalpp/xournalpp/files/6133192/errorlog.20210312-220234.log)

I don't think it has something to do with it, but that x button in the top right corner looks a bit strange:
![screenshot_x_button_top_right_corner](https://user-images.githubusercontent.com/74927253/111002769-e325fb80-837d-11eb-8fe1-5957326abd67.png)

EDIT: I also cannot use math tex, eventhough it's installed... It says "Could not find the LaTeX package 'standalone'. Please install standalone (found in texlive-latex-extra) and make sure it's accessible by your LaTeX installation."
I never used latex, but installed it with that very command via terminal which xournal++ suggests.

**Comment by rolandlo** [comment]
Can you please try out the Appimage for [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and report back if you get crashes with that one as well?

**Comment by GithubUser699** [comment]
Yes, I'll try and report back.
Thanks for answering that fast!

**Comment by rolandlo** [comment]
By the way, to find out if you are in a wayland session, see [this stackexchange post](https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used)

**Comment by GithubUser699** [comment]
Yep, it's wayland.

`prompt:~$ loginctl show-session 2 -p Type
Type=wayland
`

You AppImage didn't crash a single time until now.
Is this AppImage any different from the dev .deb file?
If not, I'm going to install this one.

Since I made a few settings in AppImage already: Can I just migrate its settings if I install the debian package?

**Comment by rolandlo** [comment]
The AppImage may package slightly older dependencies. It's larger in file size. Otherwise it should just work the same like the .deb package. AppImages can't really be installed. It's just a one-file executable that basically contains everything except of settings/autosave/errorlogs/metadata files. Once you don't need it anymore, just delete the file. If you want to upgrade it, just replace it with a newer version. If you install the Debian package, you will still use the same settings files.

One question though:
About `xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb`: Did it not install? Can you report, what the output of `lintian ./xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb` is?

**Comment by GithubUser699** [comment]
It installed if I remember right, but couldn't be started.
It needed some *zip* libs, which I installed manually. However, one of those I had to install couldn't be installed because it wasn't found (but referenced by another package, due to the terminal).
`lintian` doesn't exist on my system.

**Comment by GithubUser699** [comment]
The xournalpp-1.1.0.dev-nightly.20210311-Debian-buster-x86_64.deb cannot be installed either.

But this one says that near line 3 after field name "flexibility" a colon (:) must be followed.
If you wan't, I'll open a new issue for that one.

**Comment by rolandlo** [comment]
Strange that it needs libzip5 as well, libzip4 should suffice. You could also install libzip-dev instead.

I'm just working on fixing xournalpp-1.1.0.dev-nightly.20210311-Debian-buster-x86_64.deb (and making some improvements to it) in #2701 . You don't need to open a new issue for that one. It's already reported in #2687.

**Comment by GithubUser699** [comment]
I guess I'll stay with the AppImage for now. 
I'll try to add a (keyboard) shortcut to use this image easily and more conveniently.

Since my issue has been fixed in the dev version, my issue report is some kind of redundant.
Feel free to close it, if you agree.

Thank you for all of your efforts!

**Comment by rolandlo** [comment]
You're welcome. I'm closing the issue.

**Comment by GithubUser699** [comment]
@rolandlo I have a short question if you don't mind.
I actually decided to manually install `xournalpp-1.1.0.dev-nightly.20210311-Debian-buster-x86_64.tar.gz` and extracted it to `/usr/share`. I had to manually install `libportaudiocpp0` and `libzip4` and then I added my xournal path to $PATH.
I can use xournal now, if I do `xournalpp` in a terminal.

However, there are two things I'd like to have:
1) I would like to have an icon in the app list, so I can easily search for it.
2) If I right click on a pdf, for instance, I would like xournal++ to be in the list of apps I could open it from.

How do I do that?

**Comment by personalizedrefrigerator** [comment]
Open a shell:
```sh
$ cd ~/.local/share/applications
$ touch xournalpp.desktop
```

Set the contents of xournalpp.desktop to something similar to the following:
```desktop
[Desktop Entry]
Type=Application

Name=Xournal++
Comment=Take handwritten notes
Keywords=Tablet;Wacom;Pen Input;PDF Annotation;Markup
Name[fr]=Xournal++
Comment[fr]=Prise de notes manuscrites
Name[ca]=Xournal++
Comment[ca]=Preneu notes a mà
Name[cs]=Xournal++
Comment[cs]=Dělejte si rukou psané poznámky
Name[de]=Xournal++
Comment[de]=Handnotizen erstellen
Name[pl]=Xournal++
Comment[pl]=Notatki odręczne
Name[zh_CN]=Xournal++
Comment[zh_CN]=手写注释工具，可为PDF文件添加各种元素的注释标记
Name[ru]=Xournal++
Comment[ru]=Делайте рукописные заметки

Exec=xournalpp %f
Terminal=false
StartupNotify=true
MimeType=application/x-xoj;application/x-xojpp;application/x-xopp;application/x-xopt;application/pdf;
Icon=com.github.xournalpp.xournalpp
Categories=Office;GNOME;GTK;
```
The above is what my `.desktop` file looks like (as installed by `gnome-builder`).

I hope this is helpful!

See also:
 * https://askubuntu.com/questions/1116198/gnome-shell-doesnt-detect-custom-desktop-file
 * https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

**Comment by personalizedrefrigerator** [comment]
Also, for me, [building from source](https://github.com/xournalpp/xournalpp/wiki/Installing) and running `sudo make install` adds Xournal++ to the apps list (GNOME/KDE Plasma).

**Comment by rolandlo** [comment]
Actually what @personalizedrefrigerator suggests should not be necessary for getting Xournal++ in the apps list, as you already have 
`/usr/share/applications/com.github.xournalpp.xournalpp.desktop` for the desktop file
and
`usr/share/icons/hicolor/scalable/apps/com.github.xournalpp.xournalpp.svg` for the icon.

Can't you just run `xournalpp` from the terminal, see the icon in the dock, right click on it and add it to favorites?

Note that the `.desktop`-file contains one important line that is missing in @personalizedrefrigerator 's `.desktop`-file, namely `StartupWMClass=xournalpp`. Without that adding `xournalpp` to Favorites is more complicated.

The installer also does 
```
update-desktop-database
sudo update-mime-database /usr/share/mime
sudo gtk-update-icon-cache -f -t /usr/share/icons/hicolor/
```

Not sure it is really needed though.
@personalizedrefrigerator am I missing something?

**Comment by GithubUser699** [comment]
Thank you two for helping me out!

I tried

> update-desktop-database
sudo update-mime-database /usr/share/mime
sudo gtk-update-icon-cache -f -t /usr/share/icons/hicolor/

first, and it worked!

However, I found something else isn't working as well.
If I go to settings it says my current language isn't available anymore but it still displays everything in english.
Also, I cannot change the language in the settings anymore, since the drop down menu is empty.

I manualy installed such a tar.gz for the first time, so I might do something wrong.
**What I did**
I extracted that tar.gz and moved its content to the folders in `/usr/`.
E.g. the contents of `/xournalpp-1.1.0+dev-Debian-buster-x86_64/share/locale/en_US/LC_MESSAGES/` into `/usr/share/locale/en_US/LC_MESSAGES/`.
Well and, that's it.

Since the installer seems to do some other things as well, do I have to do something else in order to make this work?
I definetly have those files there, I checked that.


While I am fine with the language selection not working, maybe something else isn't working (properly) as well because I missed something...
I appreciate every help and hint, and I want to thank both of you for your efforts, @personalizedrefrigerator @rolandlo !

**Comment by rolandlo** [comment]
If you run `xournalpp` from the console, you should see a message (on the first line) like this one:
```
** Message: 15:49:35.002: TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /usr/share/locale, chosen directory = /usr/share/locale
```
Can you post your message here?

**Comment by GithubUser699** [comment]
Mine says `** Message: 15:51:46.203: TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /__w/1/s/build/staging/share/locale, chosen directory = /__w/1/s/build/staging/share/locale
`

**Comment by rolandlo** [comment]
Interesting, maybe that's something we have to fix. Anyway, what you can do is to set the environment variable `TEXTDOMAINDIR` to `/usr/share/locale`

Temporarily: 
```
export TEXTDOMAINDIR=\usr\share\locale
```
Permanently: put this line in `~/.bashrc` (e.g. on the last line)

**Comment by GithubUser699** [comment]
Yep, I had to use slashes instead of backslashes.
Now the first line says

> ** Message: 16:04:43.721: TEXTDOMAINDIR = /usr/share/locale, PACKAGE_LOCALE_DIR = /__w/1/s/build/staging/share/locale, chosen directory = /usr/share/locale

and it works fine in the settings too.

Just to make sure: The way I extracted and moved the tar.gz files was all correct?

**Comment by rolandlo** [comment]
Well, it's not exactly how a package is installed usually, but the files are at the right place. I am trying to find out what else `dpkg` does.

**Comment by rolandlo** [comment]
If I do `dpkg -i xournalpp-1.1.0.dev-nightly.20210311-Debian-buster-x86_64.deb` (with `Debian` replaced by `Ubuntu-focal` in my case) I can see what more actions are triggered:

```
Trigger für bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) werden verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...
Trigger für desktop-file-utils (0.24-1ubuntu4) werden verarbeitet ...
Trigger für gnome-menus (3.36.0-1ubuntu1) werden verarbeitet ...
Trigger für mime-support (3.64ubuntu1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Trigger für man-db (2.9.3-2) werden verarbeitet ...
Trigger für shared-mime-info (2.0-1) werden verarbeitet ...
```
These are related to icons, mime-types, man pages. 

The problem with localizations also appears when installing via `dpkg -i`. Looks like something is wrong in our `cmake` script.

**Comment by rolandlo** [comment]
I have reported the localizations issue in #2945

**Comment by GithubUser699** [comment]
Okay, I guess it's all set up if the files are in the right path (/usr/bin && /usr/share) and if

> update-desktop-database
sudo update-mime-database /usr/share/mime
sudo gtk-update-icon-cache -f -t /usr/share/icons/hicolor/

has been used.

Even though xournalpp doesn't have a man-db entry in my case (xournal does), I don't think that's much of an issue. Maybe xournalpp doesn't even have a man entry using the "normal" install.
Here's what I get using `man xournalpp`:

> Kein Handbucheintrag für xournalpp vorhanden
Siehe auch »man 7 undocumented« für Hilfe, wenn Handbuchseiten nicht verfügbar sind.

**Comment by rolandlo** [comment]
The man page will be added in #2701
