### ISSUE TITLE
Resizing rectangular image (corner drag handle) down to minimum and up again leaves a square

### ISSUE THREAD

**Issue by solarjoe** [xournalpp/xournalpp#2941]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Mint 18.3
 - 
 - Which version of libgtk do you use
     - 3.18,9
 - Version of Xournal++:
     - xournalpp-1.0.20-x86_64
 - Installation method:
     - AppImage

**Describe the bug**
Resizing rectangular image (using the corner drag handle) down to minimum and up again leaves a square.
Not really critical, just accidentally discovered this when working with small images.

**To Reproduce**
1. Insert a rectangular image
2. Shrink it down to zero, dragging a corner drag handle
3. Pull it up again.

**Expected behavior**
Keep the original scaling.

**Comment by rolandlo** [comment]
This was fixed in [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly). Try it out (via the AppImage)

**Comment by solarjoe** [comment]
Yes, it's fixed.
