### ISSUE TITLE
localizations don't work in released .deb packages

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#2945]
**Affects versions :**
 - OS: Linux
 - Version of Xournal++: 1.1.0+dev 
 - Installation method: official release

**Describe the bug**
After installing an officially relased .deb package (built on Azure Pipelines) localizations don't work, i.e. Xournal++ doesn't have the right path for the localizations and setting the language via `language` panel in the preferences is not possible. 

**To Reproduce**
1. Download one of the .deb-packages from the [releases page](https://github.com/xournalpp/xournalpp/tags)
2. Install via `dpkg -i PACKAGE_NAME`
3. Start xournalpp and try to change the language in the preferences

**Expected behavior**
Localizations should work out of the box like they do with the `.deb` packages from the PPA

**Additional context**
The problem is that we set the flag 
```
-DCMAKE_INSTALL_PREFIX=$PWD/staging
``` 
in the `release.yml` and `release_Ubuntu.yml` files, and use 
```
set (PACKAGE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/share")
```
and 
```
set (PACKAGE_LOCALE_DIR ${PACKAGE_DATA_DIR}/locale PARENT_SCOPE)
```
in the `CMakeLists.txt` files.

Then you can see from the message (after starting xournalpp from the console):

``` 
** Message: 15:51:46.203: TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /__w/1/s/build/staging/share/locale, chosen directory = /__w/1/s/build/staging/share/locale
```
that the wrong `locale` folder is chosen. 

A workaround is to set the environment variable `TEXTDOMAINDIR` to `/usr/share/locale/`, but we better repair our `cmake`scripts and/or `.yml` files to fix this.

**Comment by GithubUser699** [comment]
I would like to add something to it.

After setting the _TEXTDOMAINDIR_ to _/usr/share/locale_, the localisation only works if xournalpp has been opened using the terminal, but it doesn't work if I do it using the app list.
With the latter, it still shows no languages in that drop down menu in the settings.

**Comment by rolandlo** [comment]
Did you set the TEXTDOMAINDIR variable in `~/.bashrc`? Seems that is the problem. I think it should be set in `~/.profile` instead.

**Comment by GithubUser699** [comment]
Yes, I did.
I changed it right away, but the same problem persists.

Maybe I have to reboot first? I'll try and report back.
