### ISSUE TITLE
Sidebar actions move up / down in Lua API crash the program

### ISSUE THREAD

**Issue by raw-bacon** [xournalpp/xournalpp#2950]
**Affects versions :**
All versions. Tested on 1.1.0+dev.

**Describe the bug**
Calling `app.sidebarAction("MOVE_DOWN")` on the last page and `app.sidebarAction("MOVE_UP")` on the first page crashes Xournal++.
This only happens if there is more than one page.

**To Reproduce**
1. Create a plugin with the contents
```lua
-- main.lua
function initUi()
  app.registerUi({["menu"] = "Move up",   ["callback"] = "onMoveUpKey",   ["accelerator"] = "w"});
  app.registerUi({["menu"] = "Move down", ["callback"] = "onMoveDownKey", ["accelerator"] = "s"});
end

function onMoveUpKey()
  app.sidebarAction("MOVE_UP")
end

function onMoveDownKey()
  app.sidebarAction("MOVE_DOWN")
end
```

(also create a working `plugin.ini`).

2. Activate the plugin and restart Xournal++.
3. Open Xournal++ and create a new page.
4. Press `d`. Xournal++ crashes.
5. Open Xournal++ again and create a new page.
6. Press `w` twice. Xournal++ crashes.

**Expected behavior**
Nothing happens. The API shouldn't be able to crash Xournal++ this easily (the corresponding button in the sidebar is not clickable).

**Comment by rolandlo** [comment]
Thanks for reporting the bug and providing the Lua file. I will look into fixing this.

**Comment by rolandlo** [comment]
Pull request #2951 fixes the bug. @raw-bacon Do you know how to build from source and test a Pull request?

**Comment by raw-bacon** [comment]
I will try and report back!

**Comment by raw-bacon** [comment]
Works perfectly, thanks for the amazingly quick fix!

**Comment by rolandlo** [comment]
Thanks for checking. I have merged the PR.
