### ISSUE TITLE
Missing send to back, bring to front options

### ISSUE THREAD

**Issue by framazz** [xournalpp/xournalpp#2952]
I paste an image and then write on it with various colors, so I create many small objects. If I copy and paste the image into another position, all my writing disappears (behind the image). Is there a way to bring back and tell it has to stay in front? I'm missing a send to back button to apply to the image ...

**Comment by rolandlo** [comment]
In version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) there is menu `Edit -> Arrange -> Send to Back`
