### ISSUE TITLE
The "Ruler" Button Should be Renamed to Draw Line

### ISSUE THREAD

**Issue by Izerpizer** [xournalpp/xournalpp#2959]
**Is your feature request related to a problem? Please describe.**
The "Ruler" button should be renamed as it isn't consistent with the rest of the program (in the tools panel it is called "Draw Line"), nor is it accurate to its functionality (it allows you to draw lines, not measure anything).

**Describe the solution you'd like**
Change the name of the button from "Ruler" to "Draw Line"

**Comment by rolandlo** [comment]
Thanks for pointing that out @Izerpizer . Fixed it.
