### ISSUE TITLE
Make the Selecton "X" (delete) Button a Little bit Easier to Click

### ISSUE THREAD

**Issue by Izerpizer** [xournalpp/xournalpp#2960]
**Is your feature request related to a problem? Please describe.**
When you make a selection, in the top left of the selection there is a little red "X" which you can click to delete the selection. This little button can be a little tricky to hit accurately with a styuls at times, I have found.

**Describe the solution you'd like**
I'm not 100% certain on the proper solution, but maybe increase the "hitbox size" of the X or increase the physical size of the X. Whatever would make it easier to hit quickly and easily.

**Comment by personalizedrefrigerator** [comment]
Try `Edit > Preferences > Zoom` and increasing the display DPI.
