### ISSUE TITLE
GPG Signed PDFs generated with Xournal++ have distorted images.

### ISSUE THREAD

**Issue by deragon** [xournalpp/xournalpp#2962]
**Affects versions :**
Ubuntu 20.04 LTS, X11, PPA used.
$ xournalpp --version
Xournal++ 1.1.0+dev
└──libgtk: 3.24.20

**Describe the bug**
When I sign a PDF generated with Xournal++ with the GPG command below, the resulting PDF has its image distorted.  Now one would think that this problem has nothing to do with Xournal++, but I found out that this problem occurs ONLY with PDFs generated with Xournal++.  Searching the web, I cannot find anybody reporting this problem with gpg signing PDFs, suggesting that there is something particular with the PDFs generated by Xournal++ that is causing the problem.  I have signed many other PDFs not generated with Xournal++ and never reproduced the problem.  Notice that if the image is too simple, the problem does not occur.  I reproduced it with PNG files; I have not tried other graphical formats like JPG.

    gpg --clearsign --output='blank - signed with gpg - xournalpp.pdf' 'blank - unsigned - xournalpp.pdf'

This is a bummer because I use (like many others) Xournal++ to fill up PDF forms which I then want to sign with GPG.  Including with these PDF forms is my hand written signature, but it get distorted once the PDF is signed with GPG.

**To Reproduce**
1. Open `blank - unsigned.pdf` with Xournal++
2. Insert `dices.png`.
3. Export to PDF to file `dices - unsigned - xournalpp.pdf`
4. Verify and confirm that the image in the PDF display correctly.
5. Execute: `gpg --clearsign --output='dices - signed with gpg - xournalpp.pdf' 'dices - unsigned - xournalpp.pdf'` (of course, this assumes there is already a gpg key pair configured). 
6. Open `dices - signed with gpg - xournalpp.pdf` and notice the distortion of the image.

**Expected behavior**
No distortion on the image.

**Files**
[blank - unsigned.pdf](https://github.com/xournalpp/xournalpp/files/6164684/blank.-.unsigned.pdf)
[dices.png](https://user-images.githubusercontent.com/7698377/111639356-8e491180-87d1-11eb-9034-4d33657b336a.png)  -> This file was fetched from Wikimedia and thus it is ok to make use of it here.
[dices - unsigned - xournalpp.pdf](https://github.com/xournalpp/xournalpp/files/6164708/dices.-.unsigned.-.xournalpp.pdf)
[dices - signed with gpg - xournalpp.pdf](https://github.com/xournalpp/xournalpp/files/6164685/dices.-.signed.with.gpg.-.xournalpp.pdf)  **<<<< CHECK THIS FILE;  IT SHOWS THE PROBLEM**
[dices - unsigned.xopp.zip](https://github.com/xournalpp/xournalpp/files/6164717/dices.-.unsigned.xopp.zip) -> Had to zip it because GitHub does not allow adding *.xopp files directly. :(

**Additional context**
You can verify the signature of a GPG signed PDF with the following command:

    gpg --verify 'dices - signed with gpg - xournalpp.pdf'
    gpg: Signature made Jeu 18 Mar 2021 10:04:07 EDT
    gpg:                using DSA key 3E379DEF380469B04E1F0D8D927D539F57B16E48
    gpg: Good signature from "Hans Deragon <hans@deragon.biz>" [ultimate]

**Comment by robinp7720** [comment]
This really isn't a bug with xournalpp. I can reproduce the issue, and the problem however is that gpg modifies the file content. I'm not sure why, but apart from appending the armored signature and the gpg prefix, it also modifies the file content.

**Comment by deragon** [comment]
@Technius, you are wright.  One should not use --clearsign with anything but text files.  See:  https://dev.gnupg.org/T5367
