### ISSUE TITLE
Isometric grid does not line up in landscape

### ISSUE THREAD

**Issue by mjg** [xournalpp/xournalpp#2964]
**Affects versions :**
 - OS: Fedora Linux 33
 - Desktop environment: none (X11/i3)
 - libgtk: 3.24.27
 - Xournal++ 1.1.0+dev

**Describe the bug**
In an isometric grid, 3 lines are supposed to intersect in one point. In landscape mode, the lines do not always intersect in one point but leave a little trangle instead (the 3 lines intersect pairwise, for the 3 pairs, in 3 different points).

**To Reproduce**
1. Choose isometric grid
2. Switch journal page to landscape
3. Observe the intersections

**Expected behavior**
3 lines are supossed to intersect in 1 point.

**Screenshots of Problem**
xopp (zipped for GH's sake)
[isometricLandscape.zip](https://github.com/xournalpp/xournalpp/files/6170571/isometricLandscape.zip)
pdf
[isometricLandscape.pdf](https://github.com/xournalpp/xournalpp/files/6170562/isometricLandscape.pdf)

**Additional context**
The problem shows up in xournalpp itself (document view) as well as the PDF export.
It shows up in parts of the page only which indicates some sort of rounding problem.

I also noticed that "grid snapping" uses the rectangular grid, not the isometric one, but this may be completely unrelated.

**Comment by rolandlo** [comment]
Thanks for reporting this.
Yes, the "grid snapping" is currently always to the rectangular grid. We have not implemented background dependent grid snapping yet.

**Comment by mjg** [comment]
That code really makes me shrug (the wrapping around the corner...). But maybe there's no other wary "around", haha.

If you zoom out (for the attached xopp/pdf) you can even see visually how the lines are not even parallel. The problem comes from the two bottom corners and how the coordinates are computed there. From a cursory look it's either the offsets not taken into account properly and/or an off-by-1-error (is the right most coordinate really at width or at width-1) when some coordinates are computed relative to the bottom resp. right instead of from the top resp. left, leading to a double offset or none instead of one.

**Comment by mjg** [comment]
So, in fact it's the issue of `2*hdiags == cols` or not (the same vertically), and landscape simply exposed that due to the change in width and height. This messes things up when you compute from the "wrong" bottom or right. On it ...
