### ISSUE TITLE
After using the XP-PEN pen, the mouse stops working and the program crashes

### ISSUE THREAD

**Issue by nes99** [xournalpp/xournalpp#2966]
Affects versions :
Windows 10 Pro
Xournal++ 1.0.20
└──libgtk: 3.24.23

**Comment by personalizedrefrigerator** [comment]
Please provide version information!
What version of Xournal++ are you using? If not 1.1.0+dev, please re-try with [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly).
Are you running Windows, Linux, something else?

**Comment by nes99** [comment]
I'm using the 1.0.20 version on windows 10 pro. Thanks for your suggestion, I'll try it!
