### ISSUE TITLE
MigrateFontSizes plugin does not work with lua other than 5.3

### ISSUE THREAD

**Issue by mjg** [xournalpp/xournalpp#2968]
This is with the current git version of xournalpp, any platform. The reason is:
- `src/plugin/Plugin.cpp` resets the module search path "for security and compatibility reasons"
- `MigrateFontSizes` needs a module (lgi) and sets the path assuming lua 5.3

This affects all plugins which need to require modules. Now, it would be easy to patch this plugin to use the lua `_VERSION`, but I'm wondering: If a plugin can simply set `package.path` then what is the point of resetting it in `Plugin.cpp`?

In fact, relying on the system path appears to be much more secure than allowing a plugin to change it freely, doesn't it?

**Comment by rolandlo** [comment]
If nobody minds, I will undo resetting the `package.path` (introduced by @andreasb242) and avoid setting the `package.path` manually in the `MigrateFontSizes` plugin. I have no ideas though, with what other version other than Lua 5.3 the plugins will work. 
@mjg Have you perhaps tried Lua 5.4?

**Comment by mjg** [comment]
> If nobody minds, I will undo resetting the `package.path` (introduced by @andreasb242) and avoid setting the `package.path` manually in the `MigrateFontSizes` plugin. I have no ideas though, with what other version other than Lua 5.3 the plugins will work.
> @mjg Have you perhaps tried Lua 5.4?

Yes, `MigrateFontSizes` works with Lua 5.4.2 (Fedora 33), as well as the other standard plugins.
