### ISSUE TITLE
Editing toolbar button configuation - button locations get mixed up

### ISSUE THREAD

**Issue by Flinxcoder** [xournalpp/xournalpp#2970]
**Affects versions :**
 - OS: WIN10, Linux Mint 19
 - (Linux only) Desktop environment:  X11
 - Version of Xournal++: xournalpp-1.1.0.dev-nightly.20210318
 - Installation method: AppImage / Win-Exe

**Describe the bug**
Changes in toolbar configuration (-> location of buttons) are not stored after restart of Xournal++.
See also attached images

**To Reproduce**
1. Step 1
Open toolbar configuration editor

2. Step 2
Add and rearrange buttons for page-moving |<    <    X    >     >|
(see --> Image 01

3. Step 3
Close toolbar configuration editor

4. Step 4
Check location of buttons (seems to be ok --> Image 02)

5. Step 5
Restart Xournal++

**Expected behavior**
Location of butons should be as in Step 4.

But position of buttons are mixed --> Image 03
Re-editing of toolbar and restarting of Xournal++ don't solve the issue.

**Screenshots of Problem**
Image 01
![Image01](https://user-images.githubusercontent.com/49238945/112138558-f03eb800-8bd1-11eb-980c-e92ad29fed11.png)

Image 02 - as it should be
![Image02](https://user-images.githubusercontent.com/49238945/112138592-fcc31080-8bd1-11eb-9658-0969b002ee70.png)

Image 03 - as it is
![Image03](https://user-images.githubusercontent.com/49238945/112138602-00ef2e00-8bd2-11eb-97ad-9daa6c93b796.png)

**Additional context**
Add any other information or context about the problem here.
toolbar.ini

================================================================

## Here you can customize the Toolbars
# Delete this file to generate a new config file with default values
#
# Available buttons:
# File: NEW,SAVE,OPEN,PRINT
#
# Edit: CUT,COPY,PASTE,SEARCH,UNDO,REDO,INSERT_NEW_PAGE
#
# Navigation: GOTO_FIRST,GOTO_BACK,GOTO_NEXT,GOTO_LAST,GOTO_NEXT_ANNOTATED_PAGE
#
# Zoom: ZOOM_OUT,ZOOM_IN,ZOOM_FIT,ZOOM_100,FULLSCREEN,PAIRED_PAGES
#
# Color: COLOR(0xffffff),COLOR(0xffff00),COLOR(0xff8000),COLOR(0xff00ff),COLOR(0x00ff00),COLOR(0x00c0ff),COLOR(0x808080),COLOR(0x008000),COLOR(0xff0000),COLOR(0x3333cc),COLOR(0x000000),COLOR_SELECT
#  Notice: This are the default Xournal colors, each other color in HEX can also be used, eg COLOR(0x12ABCF);
#
# Tools: ERASER,PEN,HIGHLIGHTER,IMAGE,TEXT,IMAGE,SELECT,SELECT_REGION,SELECT_RECTANGLE,VERTICAL_SPACE,HAND
#  Notice: ERASER also has a drop down menu to select the eraser type, SELECT are all selection tools, with drop down menu
#
# Tool settings: SHAPE_RECOGNIZER,RULER,FINE,MEDIUM,THICK,SELECT_FONT
#
# Components: PAGE_SPIN,ZOOM_SLIDER,LAYER
#  PAGE_SPIN: The page spiner, incl. current page label
#  ZOOM_SLIDER: The zoom slider
#  LAYER: The layer dropdown menu
#
#

[Right hand Note Taking Copy Copy]
toolbarTop1=SAVE,NEW,OPEN,SEPARATOR,CUT,COPY,PASTE,SEPARATOR,UNDO,REDO,SEPARATOR,SEPARATOR,FULLSCREEN,HAND,SEPARATOR,DEFAULT_TOOL,SEPARATOR,PEN,HILIGHTER,IMAGE,ERASER,SEPARATOR,SHAPE_RECOGNIZER,TEXT,SEPARATOR,SELECT_FONT,INSERT_NEW_PAGE,DELETE_CURRENT_PAGE,SEPARATOR,GOTO_BACK,GOTO_NEXT_ANNOTATED_PAGE,GOTO_FIRST,GOTO_NEXT,GOTO_LAST,PAGE_SPIN,SEPARATOR,SEPARATOR
toolbarLeft1=COLOR(0xffffff),COLOR(0xffff00),COLOR(0xff8000),COLOR(0xff00ff),COLOR(0x00ff00),COLOR(0x00c0ff),COLOR(0x808080),COLOR(0x008000),COLOR(0x3333cc),COLOR(0xff0000),COLOR(0x000000),COLOR_SELECT,SEPARATOR,ZOOM_OUT,ZOOM_IN,ZOOM_FIT,ZOOM_SLIDER,ZOOM_100,SEPARATOR
toolbarLeft2=VERY_FINE,FINE,MEDIUM,THICK,VERY_THICK,SEPARATOR,TOOL_FILL,DRAW_CIRCLE,SEPARATOR,DRAW_RECTANGLE,DRAW_ARROW,RULER,SEPARATOR,DRAW_COORDINATE_SYSTEM,DRAW_SPLINE,ROTATION_SNAPPING,GRID_SNAPPING,SEPARATOR,VERTICAL_SPACE,SELECT_REGION,SEPARATOR,SELECT_RECTANGLE,SELECT_OBJECT,DELETE
name=Test_V01 

================================================================

**Comment by idotobi** [comment]
This is an off-by one index bug when persisting the toolbar information. I can take this up as I already fixed this in #2379, but since it will take some time until I get to merge #2379 I'll rather fix the bug here independently.

**Comment by idotobi** [comment]
I solved the bug in #2980

I also added a very extensive comment as this bug was caused by a rather strange indexing behaviour of `gtk_toolbar_get_drop_index`.
In short `gtk_toolbar_get_drop_index` seems to be `1-indexed` apart from `0` being used for insertions at the very beginning.
Hence, the resulting positions were `[0, 2, 3, 4, ...]` which lead to the off-by-1 error for any position apart from `0`.

Below you can see this behaviour when customizing the position of the `Delete` ToolItem:

![2021-03-27_16-32](https://user-images.githubusercontent.com/16611056/112726052-a9c3c300-8f1b-11eb-981c-4f6112cdba52.png)
![2021-03-27_16-31](https://user-images.githubusercontent.com/16611056/112726053-aaf4f000-8f1b-11eb-81e6-4a6419632172.png)
