### ISSUE TITLE
Print dialog box not appearing

### ISSUE THREAD

**Issue by ary1733** [xournalpp/xournalpp#2974]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use: 3.24.23
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: 1.0.20
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**
This happens randomly but when it happens I am not able to print the document and the print dialog box doesn't show up. However on some documents ctrl + p or the print option from file menu works fine.

**To Reproduce**
1. Step 1 Open xournal app through start menu
2. Step 2 Save the document
3. Step 3 Choose file->print

**Expected behavior**
I expect that every time when I choose print from file menu, A dialog box should appear.
![image](https://user-images.githubusercontent.com/54475659/112430565-58250800-8d64-11eb-99d9-12786501a518.png)

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/54475659/112430405-1b591100-8d64-11eb-8fa2-c17e45f16698.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by ary1733** [comment]
![image](https://user-images.githubusercontent.com/54475659/112430836-b225cd80-8d64-11eb-98c7-0a203295be27.png)

**Comment by MichelReims** [comment]
I also had the same problem under windows 10 with the last nightly release (18 march).
I did not know how to solve the problem.  I reinstalled xournalpp on a new version of windows and the problem disappeared

**Comment by ary1733** [comment]
@Febbe The image of Print dialog box shows what I expect. But the appearance of the dialog box is random sometime it comes and sometimes it does not.

**Comment by MichelReims** [comment]
I just installed the version of april 4. No dialog box for printing is opened. Impossible to print

**Comment by Febbe** [comment]
It might be, that the dialog is spawned in the background or at another screen / view. If this was the case, I fixed it in the upcoming PR. Also, if an error occurs, an error should be shown.

**Comment by MichelReims** [comment]
I checked: no dialog box is open in the background.  I have the same problem under windows 7 and windows 10

**Comment by MichelReims** [comment]
Thank you. I will test this PR tomorrow.

**Comment by MichelReims** [comment]
I do not understand :
1) I had installed a version of Xournalpp (march 18th) where the dialog box for printing appeared (Xournalpp had never been installed on this Windows version).
2) I installed more recent versions of Xournalpp (nightly-versions)
3) One day, I realized that the dialog box for printing did not appear anymore.
4) The, I uninstalled the latest version of Xournalpp that was problematic and I reinstalled the version of March 18th (which had correctly worked in the past). The dialog box for printing did not appear anymore !!!!
5) Then, I uninstalled this version of March 18th and  installed the April 5th version of xournalpp. The dialog box for printing did not appear either (Dialog box for printing appear for others applications).
6) I deleted completely windows and installed a new version of Windows with the version of Xournalpp of March 18th. The dialog box for printing would feel good.
7) To do tests, I uninstalled the version of March 18 and I reinstalled the April 5 version: Miracle, the dialog  box for printing appears !!!!!

Very very mysterious !!!!!!

**Comment by MichelReims** [comment]
Same problem on an other computer under Windows 7

**Comment by Febbe** [comment]
There is a config file created after printing. Can you find it and erase the file?

**Comment by Febbe** [comment]
Or even better: share it, I can forward it to gtk

**Comment by MichelReims** [comment]
I will try to find it because I don't know which folder it is in

**Comment by Febbe** [comment]
@MichelReims it should be in `%XDG_CONFIG_DIR%/Xournalpp`
Which is most likely `%AppData%/Xournalpp` or `%HOME%/Roaming/Xournalpp`

**Comment by MichelReims** [comment]
I find it  : print-config.ini. 
This solve the problem.
I can now print again.
In fact there was no bug in xournalpp.
Congratulations on finding the right solution so quickly. Thank you !!!

**Comment by MichelReims** [comment]
I forgot to send you the file that I destroyed.  It's in the trash;  I will send it to you tomorrow

**Comment by MichelReims** [comment]
@Febbe Here is the file "print-config.ini" that was problematic
[print-config.zip](https://github.com/xournalpp/xournalpp/files/6262118/print-config.zip)
