### ISSUE TITLE
Problem with xournal++ after using xsetwacom command

### ISSUE THREAD

**Issue by Luke-101** [xournalpp/xournalpp#2981]
**Affects versions :**
 - OS: Linux(Pop!_OS 20.10 x86_64)
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.20 
 - Installation method: PPA

**Describe the bug**
I wanted to setup my graphic tablet (Huion H640P) which was working on any of my graphical applications (Xournal++ and krita),
but it lacked button mapping and the ability to write on just one screen, so after some research I found this solution:

```
sudo dpkg -i digimend-dkms_10_all.deb
sudo mkdir /etc/X11/xorg.conf.d 
cd /etc/X11/xorg.conf.d 
sudo gedit 50-tablet.conf
#### Add this lines
Section "InputClass"
Identifier "Tablet"
Driver "wacom"
MatchDevicePath "/dev/input/event*"
MatchUSBID "256c:006d"
EndSection
####
#id "256c:006d" of the graphic tablet found from "lsusb" command
reboot
#check from "xsetwacom list"

xsetwacom set "HID 256c:006d Pad pad" button 1 key Ctrl Z
xsetwacom set "HID 256c:006d Pen stylus" MapToOutput HDMI-A-0
```

After that the 2 problems were fixed but I can't write anything anymore with Xournal++ while still being able to interact with every gui elements.
On krita it works even after the new configuration.

**To Reproduce**
1. Attach a huion h640p tablet to a new PopOS release
2. Configure it as I wrote in the previous point
3. Reboot
4. Start xournal++ and try to write

**Expected behavior**
It should write/draw on the papers

**Screenshots of Problem**
this was the input settings before and after.
![xournall++ before](https://user-images.githubusercontent.com/53636779/112746223-c9a3c700-8fad-11eb-8e0a-d7ab77686ef1.jpg)
![xournal++ after](https://user-images.githubusercontent.com/53636779/112746226-cd374e00-8fad-11eb-86a2-2c10494da2a7.png)

**Comment by thirschbuechler** [comment]
Does this happen after one particular `xsetwacom` call or are both required?

Since they appear to not be permanent and have to be re-entered after each reconnect or restart (at least with my Wacom Intuos S BT (CTL-4100WL) on 1.1.0+dev Aug18, 2020) `xsetwacom` might not be the smoking gun

**Comment by Luke-101** [comment]
It's true that they require reentering after a reboot but if I power on my pc and then immediately open xournal++ it still doesn't work
And I was thinking that the only permanent thing that I've done was to install the drivers and the configuration file described before. So I've tried to delete it's content and reboot the pc but xournall++ still doesn't work (will krita remains working)
I've also tested gimp to be sure  (because I use the kde desktop environment and I think that xournall++ is written in gtk) and the tablet works on it.

P.S. even with the configuration file empty the command "xsetwacom list" returns:
HID 256c:006d stylus                    id: 9   type: STYLUS    
HID 256c:006d Pad pad                   id: 10  type: PAD       
HID 256c:006d Touch Strip pad           id: 11  type: PAD   
so I think that this configuration is redundant.

**Comment by mm-crj** [comment]
I have the same problem, on the same setup pop_os 20.04, xournalpp 1.0.20 , huion 950p. xournalpp would start drawing after a double tap on the touch pad. which ideally should be active on the first tap. But it works on the old xournal app.

**Comment by Luke-101** [comment]
While checking your solution I tried to do everything I said in the first post excluding the first step and It seem to be perfectly working. But to be sure that it worked not because of others software that I have installed in the meantime I have to test it with a new linux installation.

**Comment by thirschbuechler** [comment]
My guess would be that all of the glitchy-ness is related to enabling finger operation on the touchpad; I turned that off completely. 

I'd suggest investigating the touchpad (A/B testing settings), renaming the issue, and looking through & linking other touchpad issues here

**Comment by Luke-101** [comment]
ok, so I just reinstalled my Linux partition and I can confirm that now everything seems to work.
Thanks to everyone who replied !
P.S. I will leave how I managed to make it work for anyone as inexperienced as me:
1) Create the file (as I described in the first post) to make the kernel know how to communicate with the drawing tablet
```
sudo mkdir /etc/X11/xorg.conf.d 
cd /etc/X11/xorg.conf.d 
sudo gedit 50-tablet.conf
#### Add this lines
Section "InputClass"
Identifier "Tablet"
Driver "wacom"
MatchDevicePath "/dev/input/event*"
MatchUSBID "256c:006d"
EndSection
####
#id "256c:006d" of the graphic tablet found from "lsusb" command
reboot
```
2) check the output of the "xsetwacom list", it should ONLY be 2 rows: one for the STYLUS, and one for the PAD
3) use the xsetwacom commands, BUT these commands are enabled until the tablet is disconnected (or when the computer is turned off), so to make the settings permanent you can follow this ( or any other guide in the internet): https://askubuntu.com/questions/9242/how-do-i-change-xsetwacom-and-make-the-settings-stay-on-startup
3b) if you are using KDE there is a cleaner way to configure the drawing tablet, go to discover -> search for "wacom" -> install the extension
	now search the app called: "wacom tablet finder" to configure the tablet (the number of button is referring to ONLY the number on the PAD) and then go to system settings -> input devices and there should be a new entry called "Graphic Tablet", in there you can configure everything you want and it saves the settings between sessions.
