### ISSUE TITLE
Exporting notes into PDFs does not embed used fonts.

### ISSUE THREAD

**Issue by Flinxcoder** [xournalpp/xournalpp#2991]
Affects versions :

    OS: WIN10, Linux Mint 19
    (Linux only) Desktop environment: X11
    Version of Xournal++: xournalpp-1.1.0.dev-nightly.20210329
    Installation method: AppImage / Win-Exe

**Describe the bug**
Sometimes my documents contain "printed" text-elements (not hand-written).

When I export the document to PDF the required fonts are not embedded into the PDF-file.
You won't notice if you reopen the PDF in the same OS-environment because all used fonts are pre-installed.

If I open the exported PDF-file on a different OS (e.g. Linux) the PDF reader can't find the needed fonts.
I recommend to add an export option for embedding all used fonts.

Regards

**Comment by Esokrates** [comment]
This sounds similiar to a bug that I just filed: https://github.com/xournalpp/xournalpp/issues/2998
Is this what you are observing?

**Comment by Flinxcoder** [comment]
Yep, it seems to be the same bug like in #2998
Since fonts are not embedded, exported PDFs may look very different on different computers / OS if the needed fonts are not pre-installed. That's why I prefer to embed fonts in my PDFs.

Regards

**Comment by rolandlo** [comment]
I will close this issue, since this is a dependency issue that will be solved once more recent dependencies are available.
