### ISSUE TITLE
Unable to playback audio recording without crashing xournal++

### ISSUE THREAD

**Issue by nomatica** [xournalpp/xournalpp#2992]
- OS: Windows 10
  - Xournal++ Dec 17 2020 libgtk: 3.24.23 Commit; 09ec4999
  - Installation method: [https://xournalpp.github.io/installation/windows/
  - 
**Describe the bug**
Designated folder for xournal++ to save audio recordings
-Set recording device and playback
After creating new Xournal++ page, click record button.  Record audio while also making annotations to screen ( typing text)
Save note.
Click on "play object" 
Xournal++ program window closes (crashes)

Notes:  I have tried to save before recording and after recording. I have tried closing and reopening. Occasionally I will hear a little of the audio recording before it crashes.  I am unsure if the "stop" recording button is working.  I can pres the record button (red dot) and it will stop recording.  I can tell it has stopped recording by checking windows 10 and also checking the folder that recordings are saved to and looking to see if there is a new file. 

**Expected behavior**
I expect Xournal++ to play back the audio with the text that was typed.

**Comment by rolandlo** [comment]
I couldn't reproduce the problem on Windows with version 1.1.0+dev (you are using version 1.0.20). So maybe give the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) a try.
