### ISSUE TITLE
Can't print a PDF from xournalpp

### ISSUE THREAD

**Issue by ohthehugemanatee** [xournalpp/xournalpp#2995]
**Affects versions :**
 - OS: Linux Manjaro latest
 - (Linux only) Desktop environment: swaywm (wayland)
 - Which version of libgtk do you use 3.24.27
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: 1.1.0+dev cc9b32f0
 - Installation method: https://aur.archlinux.org/packages/xournalpp-git
**Describe the bug**
When viewing a PDF in xournalpp, the print dialog does not submit jobs to the (cupsd) print queue. Other programs (firefox, ePDFViewer) can print the same document without issue.

**To Reproduce**
1. Open a pdf
2. Press print or ctrl+p and press OK  on the print dialog
3. Observe that nothing enters the print queue and no error is displayed

**Expected behavior**
The PDF should be queued to print.

**Comment by Febbe** [comment]
A workaround is to export the document as pdf

**Comment by personalizedrefrigerator** [comment]
For me (Fedora 33, Xournal++ built from a recent commit), `Print > Print to File` works for me. Is it just physical-printer-related printing that isn't working for you?

**Comment by Febbe** [comment]
I just found out, that there were no error handling at all. So I added some in the mentioned PR

**Comment by Febbe** [comment]
@ohthehugemanatee can you retest this with the newest nightly?

**Comment by Technius** [comment]
I'm going to assume that this issue is fixed, closing.
