### ISSUE TITLE
Touchscreen shown in "Input System" does not show up under "Devices", pinch zoom jumpy

### ISSUE THREAD

**Issue by Esokrates** [xournalpp/xournalpp#3001]
**Versions / Environment:**

 - OS: Linux (Ubuntu 21.04, Gnome 3.38)
 - (Linux only) Desktop environment: Gnome-Wayland
 - Version of libgtk: 3.24.21 
 - Version of Xournal++: 1.0.20
 - Installation method: Flatpak

**Describe the bug**

I'm pretty sure touch input does not work for me as it should. My device is a Dell XPS 13 9310 2-in-1 and my "Input Settings" look as follows:

![Screenshot from 2021-04-04 19-29-06](https://user-images.githubusercontent.com/17780185/113516746-40c3f700-957c-11eb-9a8d-c228a7984c80.png)

Notably there is a touchscreen registered two times: "Wayland Touch" and "Wacom HID 48ED Finger Touch". However, when I assign a pen to the latter, nothing happens when I try to draw with my fingers. When I assign the pen tool to the former, drawing works with the finger.

Now ideally I want to have the hand tool when touching the screen with my finger, since I only want to scroll and pinch zoom. When going to Touchscreen settings however, none of the two devices show up in the drop down menu:

![Screenshot from 2021-04-04 19-35-19](https://user-images.githubusercontent.com/17780185/113516884-0d359c80-957d-11eb-8acc-7fe9cc8152e8.png)

This makes using Xournalpp pretty inconvenient for me as I do have to select the hand tool manually everytime I just want to navigate around, while I whish that the hand tool is selected automatically when I touch the display with my finger.

**Pinch zoom** works anyway, even if I disable both touchscreen entries in the settings, but it is rather jumpy, i.e. practically unusable. 

With Stylus Labs Write I do not have any problem at all, so this is really a problem of Xournalpp.

**Hardware Info**

[libinput_devices.txt](https://github.com/xournalpp/xournalpp/files/6255048/libinput_devices.txt)
I'm happy to provide any info you need. Also I should be able to compile xournalpp myself to test out patches.

**Comment by Febbe** [comment]
Does this also apply to 1.1.0~dev? At least the view issues should be fixed there.

**Comment by rolandlo** [comment]
@Esokrates I don't think the "Touchscreen shown in Input System" should show up under "Devices" to configure, that are **NOT** identified by GTK as touchscreens. Seems like you may have misinterpreted these settings. In any case please follow the advice of @Febbe by trying out the [nightly release of version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly).

**Comment by Esokrates** [comment]
Compiled master from source, all described problems gone, very nice work!
Sorry for the noise and thanks for the hints!
