### ISSUE TITLE
PPA updates always reported as "System upgrade"

### ISSUE THREAD

**Issue by Krzmbrzl** [xournalpp/xournalpp#3011]
**Affects versions :**
 - OS: Linux (KDE Neon)
 - (Linux only) Desktop environment: X11 KDE
 - Installation method: PPA

**Describe the bug**

The updates shipped via the PPA are always reported as "System upgrades" since a couple of updates ago. This will then make the system think that a restart is required to apply the changes.

**To Reproduce**
1. Install xournalpp via PPA
2. Receive update

**Expected behavior**

The update being listed as a regular update

**Additional context**

I am not 100% sure that this is an issue with xournalpp and not with Discover (KDE's update software manager). I have not received any other updates for a while. Thus if you have not touched the PPA or anything affecting it in a while, I'll report a bug against KDE instead :point_up:

**Comment by Febbe** [comment]
Which ppa, there are two?

**Comment by Krzmbrzl** [comment]
This one:
```
deb http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu focal main
```

**Comment by Febbe** [comment]
@andreasb242 do you know something about that?

**Comment by Febbe** [comment]
@Krzmbrzl on my system, I am not required to restart.

**Comment by Febbe** [comment]
I am more confused by the fact, that the version does not change.
![grafik](https://user-images.githubusercontent.com/2228627/113716184-9ae2ca80-96ea-11eb-8e82-7dd33f76a914.png)

![grafik](https://user-images.githubusercontent.com/2228627/113716234-a9c97d00-96ea-11eb-8fed-a336fc0ec4ce.png)

**Comment by Febbe** [comment]
The PPA should be up to date tomorrow, but the version itself and the PPA recipe did not change.

**Comment by Krzmbrzl** [comment]
Well then I guess something broke on KDE's side...
