### ISSUE TITLE
Drawing outside of borders not working 

### ISSUE THREAD

**Issue by itsKia2** [xournalpp/xournalpp#3013]
- OS: Manjaro 5.10 Linux
 - BSPWM with X11
 - libgtk version 3.24.27
 - xournalpp version 1.0.20
 - Official repositories of Manjaro/Arch

Drawing is still not possible outside the borders of a pdf/canvas after enabling it through Input System > Experimental Input System Options. Drawing is only possible inside the borders and the feature does not work. 
Alternatively, in Settings > Drawing Area, adding additional working space has no effect either.

Both features have been tested after restarts, enabling and disabling Experimental Input System, however to no effect. Drawing is still not possible outside the borders. 
Screenshots have been included of settings and canvas (hope it helps)

![2021-04-07_18-11_1](https://user-images.githubusercontent.com/63405223/113871916-d05fe480-97cc-11eb-8fd0-76e52fc69e7e.png)
![2021-04-07_18-11_2](https://user-images.githubusercontent.com/63405223/113871922-d1911180-97cc-11eb-8ea4-c0a88eb61bcb.png)
![2021-04-07_18-11](https://user-images.githubusercontent.com/63405223/113871926-d229a800-97cc-11eb-893f-f0726e161f27.png)

**Comment by personalizedrefrigerator** [comment]
I think the purpose of that feature is to allow drawing outside the Xournal++ window, not the canvas. For example,

https://user-images.githubusercontent.com/46334387/113945113-866e0300-97ba-11eb-9f04-fb0c06074013.mp4

Drawing outside the canvas would be really nice for notes, though!

**Comment by Febbe** [comment]
An infinite canvas is a long planned feature, which is not supported by any of our file formats. That's one of the reason, we worked on a new version. But the person who primarily worked on this is stuck in other work.

**Comment by itsKia2** [comment]
> I think the purpose of that feature is to allow drawing outside the Xournal++ window, not the canvas. For example,
> untitled.mp4
> 
> Drawing outside the canvas would be really nice for note taking, though!

Ah that would be my bad, thank you for the clarification! 

> An infinite canvas is a long planned feature, which is not supported by any of our file formats. That's one of the reason, we worked on a new version. But the person who primarily worked on this is stuck in other work.

Good to know. That's a feature I've really been missing from apps like Onenote, but it's good to know it could be a feature in the future.
