### ISSUE TITLE
Problem with export to PDF

### ISSUE THREAD

**Issue by PierreB59** [xournalpp/xournalpp#3014]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.20
 - Installation method: official release

**Describe the bug**
Bug with PDF export: some characters are not displayed correctly. Il appears as an encoding problem.

**To Reproduce**
1. Install Xournall++ 1.0.20 (there is no problem with 1.0.19 version) on Windows 10 (up to date).
2. Export as PDF a pdf document edited with pdfLatex (and some additionnals fonts).
3. Open the exported pdf. Some characters will not display correctly.

**Screenshots of Problem**
You can find here a capture of this problem.
[https://drive.google.com/file/d/1L2Qn59M_KCIleejeLC7InZsSe0xUdn3o/view?usp=sharing](url)
I can send the pdf file if you want to.

**Additional context**
It's hard to reproduce the problem because with some other Tex documents, the bug does not appear.

**Comment by rolandlo** [comment]
We have had this bug, which is due to a Cairo bug, reported several times (see e.g. #2601). Please upgrade to [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly), where pdf export works normally.
