### ISSUE TITLE
Crash when scrolling out of the window with tablet pen

### ISSUE THREAD

**Issue by gianmarcogg03** [xournalpp/xournalpp#3016]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: KDE Plasma 5.21.3 on X11
 - Which version of libgtk do you use: 3.24.27
 - Version of Xournal++: 1.0.20-hotfix
 - Installation method: official Arch repos

**Describe the bug**
When I scroll with my tablet pen (by holding the middle button) and put the cursor outside of the window the program crashes.

**To Reproduce**
1. Hold the scroll button on the tablet pen
2. Move the cursor outside the window while still holding the button

**Expected behavior**
Should continue scrolling until the cursor stops at the bounds of the X screen.

**Screenshots of Problem**
Better, I have a video and the error log.
https://streamable.com/aan360
[errorlog.20210407-192811.log](https://github.com/xournalpp/xournalpp/files/6273518/errorlog.20210407-192811.log)

**Additional context**
My tablet is a Huion Kamvas 13 (2020).

**Comment by rolandlo** [comment]
You can enable the new input system in menu `Edit -> Preferences` or switch to [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) where this bug should not appear.

**Comment by gianmarcogg03** [comment]
I'm not getting the bug anymore after changing that setting, thank you.
