### ISSUE TITLE
Remove inserted image

### ISSUE THREAD

**Issue by anishmittal2020** [xournalpp/xournalpp#3027]
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]Ubunto 20.04
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]Gnome
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window

Xournal++ 1.0.20 
└──libgtk: 3.24.20 

 - Installation method: [e.g. PPA, Flatpak, official release, etc.] Deb package from github

**Describe the bug**
Image can be inserted from GUI, but I am unable to delete, or move or resize an inserted image.

**Comment by rolandlo** [comment]
No description provided. Please resubmit.
