### ISSUE TITLE
Configurable key Shorcuts

### ISSUE THREAD

**Issue by confusement** [xournalpp/xournalpp#3030]
Default shortcuts for tools selection and operations are based on naming conventions which is unnecessary and rather affecting the productivity negatively, e.g. pen tool from ctrl+shift+p, highly inefficient design to work with if you have a pen in your other hand.

Since you can configure the source yourself, the shortcuts can be configured before building but if you are regular user, ability to change shortcuts from preferences is not there.

A solution would be to either change the default shortcuts to simpler one hand shorcuts, e.g. why is there a need of ctrl+shift when just the key p is not assigned to anything, and rather why use 'p' which is so far apart from left hand use, 
Therefore the default shortcuts should be changed to some easier alternatives.
Additionally the preferences window can also provide the same functionality. 

Additional Information : I would also prefer to work on this as I love this program from a long time and has helped me a lot. (If I get approved)

**Comment by TuningYourCode** [comment]
Kind of duplicate of https://github.com/xournalpp/xournalpp/issues/919 ?

**Comment by confusement** [comment]
> Kind of duplicate of #919 ?

yep, I searched and couldn't find that particular issue idk why, anyways thanks for pointing out, #919  solves this problem so closing mine hereafter.

**Comment by personalizedrefrigerator** [comment]
> yep, I searched and couldn't find that particular issue idk why, anyways thanks for pointing out, #919 solves this problem so closing mine hereafter.

>  I would also prefer to work on this as I love this program from a long time and has helped me a lot. (If I get approved)

There's still a lot of work to be done on this! I suggest you [submit a pull request](https://github.com/xournalpp/xournalpp/discussions/3059) if you want to work on it!

**Comment by rolandlo** [comment]
@confusement If you work on this and try to simplify keyboard shortcuts, please also read #2755, as currently simple shortcuts break the text tool.
