### ISSUE TITLE
Missing Pen icons/dark theme in Flatpak version

### ISSUE THREAD

**Issue by daholzfeind** [xournalpp/xournalpp#3034]
**Affects versions :**
 - OS: Linux Mint
 - (Linux only) Desktop environment:  Cinnamon
 - Which version of libgtk do you use
     - 3.24.21
 - Version of Xournal++: 1.0.20
 - Installation method: Flatpak

**Describe the bug**
Beside the missing dark themes icons, which i mentioned here: https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-818915809 there is also no pen icon. When writing there is just a big white circle around the current position.  

**To Reproduce**
1. Install Xournalpp Flatpak 
2. Try to launch it with a dark GTK Theme in Desktop 
3. Write something. 

**Expected behavior**
- A pen icon like in the PPA version of Xournalpp.
- Icons for a dark GTK theme, see the other issue. 

**Screenshots of Problem**
Sadly one cannot take a screenshot of this.

**Comment by daholzfeind** [comment]
Issue with missing dark theme icons got fixed by installing a dark icon theme. So the only thing that leftover is the missing pen icon.

**Comment by personalizedrefrigerator** [comment]
This might be fixed by #2886!

**Comment by rolandlo** [comment]
The issue seems fixed in version 1.1.0. Please reopen if this does not apply.
