### ISSUE TITLE
Broken shell scripts, including AppRun script

### ISSUE THREAD

**Issue by TheAssassin** [xournalpp/xournalpp#3035]
*I'll be ignoring the template, since I'm going to send a PR soon-ish that fixes a bunch of these issues.*

Affected are likely all AppImages released so far (I tested 1.0.18-20, but `git blame` shows it's been an issue all the time). 

The shell scripts in this repository are not written very well. Many contain syntax that only works with paths that don't contain spaces.  A good example is the AppRun script contained in the AppImages:

```sh
#!/usr/bin/env bash
#
# Custom AppRun for Xournal++

export APPDIR=${APPDIR:-$(readlink -f $(dirname "$0"))}
export PATH="$APPDIR"/usr/bin/:"$PATH"
export XDG_DATA_DIRS="$APPDIR"/usr/share:"$XDG_DATA_DIRS"

export GDK_PIXBUF_MODULEDIR="$APPDIR"/usr/lib/gdk-pixbuf-2.0/loaders
export GDK_PIXBUF_MODULE_FILE="$APPDIR"/usr/lib/gdk-pixbuf-2.0/loaders.cache
export GTK_PATH="$APPDIR"/usr/lib/gtk-3.0
export PANGO_LIBDIR="$APPDIR"/usr/lib

export LD_LIBRARY_PATH="$APPDIR"/usr/lib:"$GDK_PIXBUF_MODULEDIR":"$LD_LIBRARY_PATH"

# It's possible to use the system GTK theme, but different GTK versions can
# break themes. The user can set this manually if he or she really wants the
# theme to match.
export GTK_THEME=${GTK_THEME:-Adwaita}

"$APPDIR"/usr/bin/xournalpp $@
```

Here, we have a bunch of less and one really critical issue. Most of the variable usages are not escaped properly. This becomes really problematic in the last line. The lack of quotes around `$@` effectively causes word splitting. This then breaks when you're trying to open paths that contain spaces: they're passed as separate parameters, making Xournal++ show an error message that only one parameter is supported at most.

The fix is simple: just escape. But it'd be only a half-hearted attempt to fix a larger issue. Most shell scripts contain issues. A quick check with the excellent [shellcheck](https://www.shellcheck.net/) reveals numerous issues.

I will send a PR fixing at least the `AppRun` script, allowing me and other users of the AppImage to open paths with spaces properly. But I really urge you to take shell script syntax more seriously. I myself had many wrong assumptions about how shell script syntax works, but I had to change a few of my habits as well when I discovered shellcheck and included it in my workflows.  We even included CI jobs in a few linuxdeploy plugin repos to by default check all scripts with the linter.

CC @Technius

**Comment by TheAssassin** [comment]
Looks like I the need for a custom AppRun was eliminated in 1869f3a0d02a913f7b114e799542ab9b70e9edd0, thus fixing this one issue. There's a few other ones, though. I'll fix the more critical ones soon-ish.

**Comment by rolandlo** [comment]
Closing, since the AppRun script got removed in version 1.1.0
