### ISSUE TITLE
Crash when scrolling over slides with different format

### ISSUE THREAD

**Issue by KonstantinHebenstreit** [xournalpp/xournalpp#3036]
Affects versions :

    OS: Linux 20.04
    (Linux only) Desktop environment: Gnome 3.36, X11
    Which version of libgtk do you use: 3.24.20
    Version of Xournal++: 1.1.0+dev
    Installation method: sudo apt 

**Describe the bug**
I work on Powerpoint Slides. When I insert a new blank page this has another Format than the Powerpoint slides.
If I let Xournal maximize the slides and scroll up and down through the different size slides it crashes. And it really crashes, it unfortunately does not save the current state (as it normally does :-) ), and when you restart you can easily recover it, as a pop up just gives you the option. It really crashes and then you can only search for the recovery file yourself, which is often missing a lot, since it was autosaved a minute before it crashed.

**To Reproduce**
1. Open the file I uploaded
[Crash-Test-Slides.zip](https://github.com/xournalpp/xournalpp/files/6309858/Crash-Test-Slides.zip)

2. Make sure 'Zoom fit to screen' is activated
3. Scroll up and down through the empty slides with different formats
4. For me it crashes every time

**Expected behavior**
Normal Scrolling from slide to slide. Changing automaically the Zoom fit to screen.

**Additional context**
Is there an option to make Xournal insert new empty pages with the same size as the page before?
(At the moment this can only be done with first duplicating page and then apply 'Plain' to current page. This is more of a feature request, but I think it would be in general very nice if it just inserted pages of the same size as a standard.

**Comment by mjg** [comment]
I can confirm this here. CPU goes up to 100%, at some point there's a seg fault. Everything is fine at fixed zoom.

**Comment by Technius** [comment]
This is probably the same infinite recursion issue that's been plaguing us all this time (https://github.com/xournalpp/xournalpp/pull/2821#issuecomment-782254331), though probably triggered by some other cause.
