### ISSUE TITLE
Crash on double-click outside of page

### ISSUE THREAD

**Issue by nburo** [xournalpp/xournalpp#3041]
Hi! I love Xournal++. I use it as a virtual board for my online class to show my students.

**Affects versions :**
 - OS: Windows 10
 - libgtk : 3.24.23
 - Version of Xournal++: 1.0.20 09ec4999
 - Installation method: official release

**Describe the bug**
When I double-click the area outside a page (the grey "background" area), with my mouse or with my pen, Xournal++ instantly crashes. No crash window.

**To Reproduce**
1. Open Xournal++
2. Put the cursor over the "outside-of-page" area
3. Double click using any (L/M/R) mouse button or tap my tablet twice with a pen (Huion pen tablet, in my case)
4. Instant crash

**Expected behavior**
Not crashing when double clicking the described area

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/5957405/114957965-10a80e00-9e30-11eb-9e46-f6bc4f0f9ca9.png)

**Comment by personalizedrefrigerator** [comment]
Hi,
I'm not able to reproduce this with version 1.1.0+dev (on Linux). It might have been fixed!

**Comment by nburo** [comment]
> I'm not able to reproduce this with version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) (on Fedora Linux). It might have been fixed!

Alright, I just tested 1.1.0+dev on Win10 and no crash occurs. Thanks for suggesting it, I don't when I didn't think of it sooner.

BTW : I really enjoy the new features of that version. Can't wait for the official version. Good job devs.
