### ISSUE TITLE
Please delete the Italian translation duplicate it_IT.po

### ISSUE THREAD

**Issue by ciampix** [xournalpp/xournalpp#3049]
In master source there are two Italian translations: it.po and it_IT.po. Please delete it_IT.po (and all its references so it won't be rebuild again) since there is (practically) no other Italian translation than it.po for _ANY_ apps out there.
If you do not believe me just see the content of:

/usr/share/locale/it_IT/LC_MESSAGES

and compare to

/usr/share/locale/it/LC_MESSAGES

in any Linux distro you may know.

TIA

**Comment by rolandlo** [comment]
We can easily delete the `it_IT.po` file, but how can we prevent it to be regenerated? In Crowdin I only see these settings:

![grafik](https://user-images.githubusercontent.com/40485433/122631655-75504500-d0cd-11eb-8dfb-aefbd781d786.png)

![grafik](https://user-images.githubusercontent.com/40485433/122631846-fbb95680-d0ce-11eb-86bf-c1dd420d03fe.png)

Maybe we need to adjust our [configuration file](https://support.crowdin.com/configuration-file/) `crowdin.yml` to exclude `it_IT`

**Comment by rolandlo** [comment]
I figured it out. Just had to correct the placeholders in the Language Mapping:
![grafik](https://user-images.githubusercontent.com/40485433/123275178-64a43280-d504-11eb-9897-b91a6f17f92b.png)

The Placeholder `locale`stands for strings with hyphen like `it-IT` (which we don't have)
The Placeholder `locale_with_underscore`stands for strings with underscore like `it_IT` (which we do have)

**Comment by Technius** [comment]
Fixed by #3166.

**Comment by ciampix** [comment]
Thanks!
