### ISSUE TITLE
Xournalpp does not launch under Kubuntu 21.04 Hirsute Hippo

### ISSUE THREAD

**Issue by friciwolf** [xournalpp/xournalpp#3066]
**Affects versions :**
 - OS: Kubuntu 21.04. Hirsute Hippo
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
     - `xournalpp --version` does not execute, it returnes:
 
`xournalpp: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory`

 - Version of Xournal++: the latest available under Groovy
 - Installation method: ppa

Xournalpp does not launch, since the upgrade from groovy to hirsute. From the terminal, it gives the following error message:
```xournalpp: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory```

apt-file search libzip.so yields however only the following results:

ark: /usr/lib/x86_64-linux-gnu/qt5/plugins/kerfuffle/kerfuffle_libzip.so
libzip-dev: /usr/lib/x86_64-linux-gnu/libzip.so
libzip4: /usr/lib/x86_64-linux-gnu/libzip.so.4
libzip4: /usr/lib/x86_64-linux-gnu/libzip.so.4.0
openjdk-11-jre-headless: /usr/lib/jvm/java-11-openjdk-amd64/lib/libzip.so
openjdk-15-jre-headless: /usr/lib/jvm/java-15-openjdk-amd64/lib/libzip.so
openjdk-16-jre-headless: /usr/lib/jvm/java-16-openjdk-amd64/lib/libzip.so
openjdk-17-jre-headless: /usr/lib/jvm/java-17-openjdk-amd64/lib/libzip.so
openjdk-8-jre-headless: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so

whereas I have libzip4 installed.

On groovy, everything worked fine, this issue appeared only after the upgrade. Before the upgrade I completed a university assignment, after the upgrade nothing worked.

**Comment by rolandlo** [comment]
What happens if you `sudo apt remove xournalpp` and `sudo apt install xournalpp` again? I'm also on Ubuntu 21.04 (though not Kubuntu) and `apt-file search libzip.so` yields the same result.

**Comment by friciwolf** [comment]
same error occurs after reinstallation...

**Comment by friciwolf** [comment]
In my case, could it be that libzip5 was removed during the upgrade procedure, as it was flagged obsolete? I automatically went for "yes" as it asked me whether to get rid of those...

**Comment by rolandlo** [comment]
Probably it must be related to that. I never had `libzip5` installed (I think). What does `apt-cache depends xournalpp` return in your case?

**Comment by friciwolf** [comment]
My setup is french, so a bit of translation: Dépend means "depends" and "Suggère" means "suggested". 
```xournalpp
  Dépend: libglib2.0-0
  Dépend: libgtk-3-0
  Dépend: libpoppler-glib8
  Dépend: libxml2
  Dépend: libportaudiocpp0
  Dépend: libsndfile1
  Dépend: liblua5.3-0
 |Dépend: libzip4
  Dépend: <libzip5>
  Dépend: zlib1g
  Dépend: libc6
  Suggère: texlive-base
  Suggère: texlive-latex-extra
```

**Comment by rolandlo** [comment]
Hmm, I get more dependencies displayed, although the same for `libzip4` and `libzip5`. Which PPA do you use? The one for the stable version or the one for the latest master?

**Comment by friciwolf** [comment]
The stable one:
 http://ppa.launchpad.net/apandada1/xournalpp-stable/ubuntu/ hirsute main

**Comment by rolandlo** [comment]
Please try the latest master `ppa:andreasbutti/xournalpp-master`

**Comment by friciwolf** [comment]
Thanks a million, this has magically worked!
Out of curiosity: What was wrong with the old unofficial ppa? Since when do you have this ```master``` branch? Is it going to replace the old unofficial one?

**Comment by rolandlo** [comment]
With the stable PPA I can reproduce the problem. @apandada1 Anything to do about it? 

@friciwolf I don't know what is wrong with the stable (unofficial PPA). The official PPA for the latest master exists for longer, (at least) since end of 2018.

**Comment by friciwolf** [comment]
Alright, but the master ppa is the cutting-edge git-based rolling release version of Xournalpp isn't it? My only question would be than, if I should revert some time later to the unofficial ppa once this has been fixed to avoid bugs?

**Comment by rolandlo** [comment]
From the buildlogs I can see that the stable PPA version is built with `libzip5`, whereas the latest master PPA is built with `libzip4`. That explains part of the difference.

@friciwolf Yes, the latest master PPA is the cutting-edge rolling release. If you are happy with the current (cutting-edge) version you have, just remove the PPA (with `add-apt-repository --remove ppa:/andreasbutti/xournalpp-master`) so you don't receive any upgrades. Then you won't run into occasional bugs (regressions) that we freshly introduce.

Since we will soon release version 1.1.0, the stable PPA will also get an update. You could also revert to that after the release.

**Comment by apandada1** [comment]
I am not on 21.04, that's why did not notice this issue.

It seems that libzip5 has been [removed]((https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libzip5&searchon=names)) from Ubuntu 21.04. It may be that when the PPA was built (in December), then 21.04 did have libzip5, and the built package expects that, but it has been removed to make it compatible with Debian.

I will rebuild the package for 21.04 again in Launchpad.

**Comment by rolandlo** [comment]
@apandada1 You are right about `libzip5` being removed from Ubuntu 21.04. See also [this link](https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg48138.html) for more information.

**Comment by friciwolf** [comment]
A million thanks for your kind and quick-to-point answers! I'll keep the things you said in mind @rolandlo, that's good to know.
With that, I'm closing this issue as the new build should resolve the problem.

**Comment by friciwolf** [comment]
I've just reverted to the unofficial repository; thank you very much @apandada1 for your quick response, now everything works perfectly! Thank you guys for your amazing support and this wonderful piece of program, you are the best!
