### ISSUE TITLE
xjournal installs smoothly on (new) MacBook Air (processor M1; OS BigSur 11.2.3), but crashes instantly at any launch.

### ISSUE THREAD

**Issue by ChristopheMargerin** [xournalpp/xournalpp#3067]
**Affects versions :**
 - OS: Mac, BigSur 11.2.3
 
 - Which version of libgtk do you use
     no idea, can't open it! the app is from 12-17-2020
 - Version of Xournal++: again don't have access
 - Installation method: latest stable release on github

**Describe the bug**
the app is installed in the relevant folder (apllications); when I open it it crashes instantly: I can see a window opening and closing instantly.

**To Reproduce**
1. download from github, uncompress, install
2. launch the app
3. watch the instant collapse

**Expected behavior**
expect the app to open and run smoothly!

**Comment by rolandlo** [comment]
You are trying to run an old version (appeareantly 1.0.20) which doesn't work on BigSur. Please try [version 1.1.0+dev (nightly release)](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and report back.

**Comment by WieMaKa** [comment]
Hi community
Thanks for the question and answer.
I use a MBPro BigSure 11.2.3 and had exactly the same problem.
The version 1.1.0+dev works fine for me.
thanks for sharing
