### ISSUE TITLE
Horizontal page

### ISSUE THREAD

**Issue by qwuy1290** [xournalpp/xournalpp#3069]
I would like to have horizontal pages.
They would be more handy that vertical ones for logic derivations and graphs drawing.
An example is [this](https://i.stack.imgur.com/WmNR7.png).

**Comment by rolandlo** [comment]
You can use any page format you like. See menu `Journal > Page Format`.

**Comment by qwuy1290** [comment]
Oh lord, don't know how I missed it.
Thanks a lot!
