### ISSUE TITLE
Ignore first point from pen

### ISSUE THREAD

**Issue by pviscone** [xournalpp/xournalpp#3070]
A lot of device are very imprecise in recognizing the first point from pen.
This led to problems like this one in the pic.

![5ede8032-c68e-4135-99b1-72feedc7c96b](https://user-images.githubusercontent.com/31247066/115996497-c36e2e00-a5df-11eb-80f9-e6588f469416.jpg)

A feature that would resolve the problem is an option for ignoring just the first point from pen

**Comment by personalizedrefrigerator** [comment]
![See Stylus settings.](https://user-images.githubusercontent.com/46334387/116002547-1085dc00-a5af-11eb-8022-b9ddcd604e40.png)
I think [v1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) might have this!
