### ISSUE TITLE
Text Tool: Selection/Highlighting does not always match actual selected text.

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#3071]
**Affects versions :**
 - OS: Linux/Manjaro
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.28
 - Version of Xournal++: 1.1.0+dev (built from fork)
 - Installation method: Build from source

**Describe the bug**
Highlighted regions in selected regions of text do not always match the actual selected region.

**To Reproduce**
1. Create a blank document.
2. Add the text: "This is a test..." with the text tool.
3. Select (using Shift + Left_Arrow * 9) "a test..."
4. Unselect "a test..." (using Shift + Right_Arrow * 2)
5. Press backspace.

**Expected behavior**
The "a " should not be highlighted after unselecting it.

**Screenshots of Problem**
![See bug description](https://user-images.githubusercontent.com/46334387/116002975-f6e59400-a5b0-11eb-991f-f72c5ed95025.png)

**Comment by Technius** [comment]
Is this a regression or a bug that also exists in 1.0.x?

**Comment by rolandlo** [comment]
No regression, the bug was there in 1.0.20 as well.
