### ISSUE TITLE
Selection: Shift+Click should extend it

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#3072]
**Is your feature request related to a problem? Please describe.**
Clicking with the shift key held should extend the currently selected region when using tools like "Select Region", "Select Rectangle", or "Select Object".

**Describe the solution you'd like**
Objects selected while holding the shift key should extend the current selection, rather than clearing it.

**Additional context**
I think this is similar to how selection-extension works in other programs.
I'm working on a PR for this (but haven't gotten very far yet :) ).

**Comment by Technius** [comment]
Duplicate of #1838.
