### ISSUE TITLE
touchscreen pen does not draw in xournalpp on Dell touchscreen monitor

### ISSUE THREAD

**Issue by wgunruh** [xournalpp/xournalpp#3077]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS:Linux Mageia 7 updated running XFCE desktop
 - (Linux only)X11
 - Which version of libgtk do you use   3.24.21
  
 - Version of Xournal++: 1.0.20
 - Installation method:flatpak, and Mageia 8 version of xournalpp (which also does not work)

**Describe the bug**
On a Dell 2418HT touchscreen, using a pen, it does not work. The cursor follows the pen, but all that happens is that the page scrolls up or down following the pan. No lines drawn. If I use a mouse, it does (left click held down) it does draw on the screen, but the pen does not. 

**To Reproduce**
1 start xjournalpp\
2 try using the pan (eg rubber tipped) to draw on screen. all that happens is that the screen scrolls up or down following the pan cursor. It does not draw. Note this system works fine using xournal, rather than xournalpp.

.

**Expected behavior**
When you move the pen over the screen lines get drawn. 

**Screenshots of Problem**
Sorry, cannot do so.

**Additional context**
None that I know of .

**Comment by rolandlo** [comment]
Can you try out Xournal++ [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and see if it works there? The quickest way is to use the AppImage. Also, please check your settings in the input system panel in menu `Edit > Preferences`. Maybe something is wrorng there.

**Comment by personalizedrefrigerator** [comment]
In version 1.1.0+dev, you can also enable touchscreen drawing (Settings > Touchscreen > Enable Touchscreen Drawing).

**Comment by wgunruh** [comment]
I finally got the AppImage to work-- it was the the localtion of the xournalpp appimage file. And yes, I got the pen to work on the touchscreen. I also got it to work in 1.6.0 by changing the Input System, and selecting Pen as the type, and using the experimental input process. I am using the 1.1.0 AppImage now.  When will this become a stable release?
Thanks

**Comment by rolandlo** [comment]
> I am using the 1.1.0 AppImage now. When will this become a stable release?

I cannot name a concrete date, but pretty soon.
