### ISSUE TITLE
From cmdline to plugin

### ISSUE THREAD

**Issue by ElModdy** [xournalpp/xournalpp#3081]
**I would like to...**
I would like to setup xournal differently when I launch it from a script.

**Context**
All the files I edit through the script mentioned have the same filename pattern.

**Solution that I thought**
I could get the filename from a plugin and do the UI manipulation in the plugin,
if the filename match the pattern but I have no idea how to get the name of the current file using the plugin api.

**Comment by rolandlo** [comment]
In case these files have a PDF background and you only need the name of the PDF background, you can use 
```lua
local doc = app.getDocumentStructure()
local pdfName = doc["pdfBackgroundFilename"]
```
In case you need the filename of the xopp-file, you would have to slightly extend the Lua Plugin API by adding a `filename` key to the Lua table returned by `applib_getDocumentStructure` in the file `luapi_application.h`. 

There are workarounds as well. For example when running `xournalpp` from a script you could set an environment variable to the filename and use `os.getenv` in the Lua plugin to read it.

**Comment by ElModdy** [comment]
Thank you very much
