### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#309]
Hi,
this is more a community problem.
Would it be possible to move the travis CI to the project account?
I'm not part of the github organization. What do you think?

**Comment by andreasb242** [comment]
And I created an official account for Code Coverage:
https://scan.coverity.com/projects/xournal

(Yes, Xournal, they removed the ++ out of the URL....)

**Comment by andreasb242** [comment]
@peetCreative

You should get the rights for Travis now, so I think here should noting be to do.
If not, feel free to reopen the ticket.
