### ISSUE TITLE
System crash with stylus when other touch or scolls occur.

### ISSUE THREAD

**Issue by punyidea** [xournalpp/xournalpp#3095]
**Affects versions :**
 - OS: Ubuntu 20.04 LTS
 - Version of Xournal++ 1.0.20
 - HP ZBook x360 Studio G5 with HP Activepen 2

**Describe the bug**
This bug happens when I take notes on my computer, using my stylus. I haven't been able to exactly crack the steps necessary to reproduce the bug. I know that the stylus must be in close proximity to the screen, at the same time that there is input on the touchscreen (or possibly a two-finger scroll on the touchpad).

The system

**To Reproduce**
1. Have the hand on the screen, far enough so that the stylus is not on the screen.
2. Not sure here, sometimes scrolling with two fingers on touchpad, or multifinger zoom on screen (possibly unintentionally)
3. Press stylus onto screen
4. System crash requiring reboot

**Input Logs**

In both cases, the system crashed right at the last entry to each file.

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/6428209/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/6428210/debug_input.log)

Inputs
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48DE Pen stylus               	id=11	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48DE Finger touch             	id=12	[slave  pointer  (2)]
⎜   ↳ SYNA307B:00 06CB:CD46 Mouse             	id=13	[slave  pointer  (2)]
⎜   ↳ SYNA307B:00 06CB:CD46 Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=18	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48DE Pen eraser               	id=21	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ HP HD Camera: HP HD Camera              	id=10	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=15	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=16	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=17	[slave  keyboard (3)]
    ↳ HP Wireless hotkeys                     	id=19	[slave  keyboard (3)]
    ↳ HP WMI hotkeys                          	id=20	[slave  keyboard (3)]

```

**Expected behavior**
Inputs are recorded and the system does not crash. ;)

Thanks in advance for any input you may have! I do have the experimental input feature activated.

**Comment by rolandlo** [comment]
Can you please try out [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? Easiest is to download the `AppImage` (no installation required). In case it crashes as well, provide the crashlog, if there is one, and the terminal messages.

**Comment by Technius** [comment]
This shouldn't cause a system crash--sounds more like a driver bug to me.

**Comment by punyidea** [comment]
> This shouldn't cause a system crash--sounds more like a driver bug to me.

For the moment I can only replicate this in xournal++. I haven't experienced the issue outside of the app.

**Comment by punyidea** [comment]
> Can you please try out [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? Easiest is to download the `AppImage` (no installation required). In case it crashes as well, provide the crashlog, if there is one, and the terminal messages.

I haven't been able to replicate the issue with the version thus far. I also cannot replicate the issue if the "experimental input" feature is not activated in 1.20.0.

**Comment by punyidea** [comment]
An update: my system did crash with a multitouch /scroll  event in 1.20.0, without experimental input activated. I've switched to the 1.1.0 dev version and so far have not experienced a system crash.

**Comment by Technius** [comment]
The multi-touch crash is due to #1507.
