### ISSUE TITLE
Hand tool make xournalpp crash

### ISSUE THREAD

**Issue by GammaPi** [xournalpp/xournalpp#3101]
**Affects versions :**
 - OS: Ubuntu 20.04
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: 
     - 1.0.20
 - Installation method: apt

**Describe the bug**
Xournal will crash once hand tool move to side bar.
If you select hand tool and use mouse left button to move the page, then there's no problem.
If you map hand tool to mouse right click button and click right button and move the page, once the cursor move to sidebar it will crash.

**To Reproduce**
1. Map mouse right button to hand tool
2. Click right mouse key and move the cursor real quick to the left side bar

**Screenshots of Problem**
![Peek 2021-05-08 12-27](https://user-images.githubusercontent.com/19838874/117546524-d37f0800-aff8-11eb-8700-1ea38f3999e8.gif)

**Comment by Technius** [comment]
I managed to reproduce a crash once on 1.0.20, but it's very unreliable. Can you try seeing if the 1.1.0+dev version also crashes?

**Comment by rolandlo** [comment]
This was a bug with the old input system. Doesn't happen in version 1.1.0 any more, so I am closing the issue.
