### ISSUE TITLE
Track Copyright for downstream packagers convenience

### ISSUE THREAD

**Issue by idotobi** [xournalpp/xournalpp#3103]
**Feature Request**
I as a packager of xournalpp for various Linux distributions,
would like to have a easily parse able source of truth for copyright information on the xournalpp project.
This enables me to easily package xournalpp without the need for any detective work on which files have special copyright/licenses. 

**Solution**
Have a `COPYRIGHT.md` file in the root of the project as a more fine grained version of the `AUTHORS.md` file.
The "only" strict requirement right now is that it covers at least all information in `/debian/copyright` in a consistent structure.

**Alternatives**
We could also consider to make it machine readable with something like:

 - `.toml`
 - `.yaml`
 
However, I'm unsure if any packager would ever really use a script for automatically getting the information out of our copyright format.

Another alternative would be to just use the https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ as it might be more thought through then any format we could come up with for our own copyright file.

**Additional context**
This issue came up in the discussion https://github.com/xournalpp/xournalpp/issues/2148#issuecomment-749476885

In general I would argue that we should keep the information in the Copyright file as coarse as possible, while still being precise enough to fulfill the requirements for packaging. This would follow the advice given by the [linuxfoundation](https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/) and this [blog post](https://opensource.com/article/20/10/copyright-notices-open-source-software).

**Comment by rolandlo** [comment]
> Another alternative would be to just use the https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ as it might be more thought through then any format we could come up with for our own copyright file.

That sounds like a reasonable alternative to me.

> In general I would argue that we should keep the information in the Copyright file as coarse as possible, while still being precise enough to fulfill the requirements for packaging.

I fully agree with that.

**Comment by idotobi** [comment]
So I just started on getting an overview on the license ocurances in strings.

Seems that all header files are nicely commented apart from two

```sh
$ rg license --files-without-match | rg "\.h"
src/gui/widgets/gtkmenutooltogglebutton.h
src/gui/inputdevices/InputUtils.h
```
The first one was copied from gimp so it's a legit exception.
The second file is actually my mistake :sweat_smile:. Didn't know/notice that there was this rule.

```cpp
/**
 * @file InputUtils.h
 * @author idotobi
 * @brief Helper functions in use in the different InputHandlers as for example StylusInputHandler.h
 *
 */
```

:facepalm: :rofl:  I will change that in a PR.

I think this would be a nice/simple check we could add to the CI. Basically apart from Whitelisted files there should be no header file without this header.

We could also add a check for authors to make sure that unless someone really insists they use the default Xournal++ header by default:

```sh
rg "@author Xournal++" --files-without-match | rg "\.h"src/gui/widgets/gtkmenutooltogglebutton.h
src/gui/inputdevices/InputUtils.h
src/gui/GladeSearchpath.h
src/gui/dialog/LatexDialog.h
src/util/hashcombine.h
src/util/safe_casts.h
```

**Comment by idotobi** [comment]
Does anyone know why only Header files have the consistent header of 

```cpp
/*
 * Xournal++
 *
 * <Description on File>
 *
 * @author Xournal++ Team
 * https://github.com/xournalpp/xournalpp
 *
 * @license GNU GPLv2 or later
 */
```

and `.cpp` files only sporadically?

```sh
$ rg "@author" --files-with-matches | rg "\.cpp"
test/control/LoadHandlerTest.cpp
test/util/PathTest.cpp
test/util/StringUtilsTest.cpp
test/util/I18nTest.cpp
test/util/ColorTest.cpp
test/TestMain.cpp
test/SpeedTest.cpp
test/util/XojPreviewExtractorTest.cpp
src/Xournalpp.cpp
src/xoj-preview-extractor/xournalpp-thumbnailer.cpp
```

**Comment by idotobi** [comment]
The script I would use for finding files licensed differently would be

```sh
$ rg --files-without-match "@author Xournal++" $(rg "license" -li) | rg -v "\.po"
cmake/include/clang-tidy.cmake
cmake/include/GitRepo.cmake
cmake/find/Gettext.cmake
cmake/find/FindFilesystem.cmake
cmake/find/FindICU.cmake
rpm/fedora/xournalpp.spec
CMakeLists.txt
cmake/include/ExternalDeb.cmake
LICENSE
src/util/safe_casts.h
src/util/pixbuf-utils.cpp
src/util/hashcombine.h
src/gui/dialog/LatexDialog.h
debian/copyright
src/gui/widgets/gtkmenutooltogglebutton.cpp
src/gui/widgets/gtkmenutooltogglebutton.h
src/gui/GladeSearchpath.h
windows-setup/xournalpp.nsi
desktop/com.github.xournalpp.xournalpp.appdata.xml
ui/iconsDark/hicolor/scalable/actions/tool_highlighter.svg
ui/iconsDark/hicolor/scalable/actions/presentation-mode.svg
ui/iconsDark/hicolor/scalable/actions/tool_math_tex.svg
ui/icons/hicolor/scalable/actions/tool_highlighter.svg
ABOUT-NLS
ui/icons/hicolor/scalable/actions/tool_math_tex.svg
ui/icons/hicolor/scalable/actions/tool_image.svg
ui/icons/hicolor/scalable/actions/presentation-mode.svg
ui/about.glade
ui/icons/hicolor/scalable/actions/goto.svg
```

In words: every file which 
* contains the string license (regardless of casing)
* **and** is not authored by Xournal++ team
* **and** is not a `.po` file (to many false positives)

That's 29 files so it should not take to long.

Does anyone see a problem with this way of checking? Is there anything I would systematically miss?

**Comment by idotobi** [comment]
I noticed that I forgot to add a search for copyright.

The hopefully final version should be:

```sh
$ rg --files-without-match "@author Xournal++" $(rg -i -e copyright -e license -l) |  rg -v "\.po"
plugins/ColorCycle/plugin.ini
plugins/QuickScreenshot/plugin.ini
plugins/Example/plugin.ini
plugins/LayerActions/plugin.ini
plugins/ToggleGrid/plugin.ini
plugins/MigrateFontSizes/plugin.ini
cmake/include/clang-tidy.cmake
cmake/include/ExternalDeb.cmake
cmake/include/GitRepo.cmake
cmake/include/Copyright.txt
cmake/find/Gettext.cmake
cmake/find/FindFilesystem.cmake
cmake/find/FindICU.cmake
rpm/fedora/xournalpp.spec
CMakeLists.txt
ui/icons/hicolor/scalable/actions/tool_image.svg
ui/icons/hicolor/scalable/actions/tool_math_tex.svg
ui/icons/hicolor/scalable/actions/goto.svg
ui/icons/hicolor/scalable/actions/presentation-mode.svg
ui/icons/hicolor/scalable/actions/tool_highlighter.svg
ui/iconsDark/hicolor/scalable/actions/tool_highlighter.svg
ui/iconsDark/hicolor/scalable/actions/tool_math_tex.svg
ui/iconsDark/hicolor/scalable/actions/presentation-mode.svg
windows-setup/xournalpp.nsi
ui/about.glade
LICENSE
src/util/pixbuf-utils.cpp
src/gui/dialog/LatexDialog.h
src/gui/GladeSearchpath.h
src/util/safe_casts.h
src/gui/widgets/gtkmenutooltogglebutton.cpp
src/gui/widgets/gtkmenutooltogglebutton.h
src/util/hashcombine.h
debian/copyright
src/win32/xpp.rc.in
desktop/com.github.xournalpp.xournalpp.appdata.xml
license_files.code-search
ABOUT-NLS
```

So that's 38 in total :crossed_fingers:

**Comment by rolandlo** [comment]
> So that's 38 in total crossed_fingers

Your script looks good to me. The list will become shorter after #2886 is merged. 


> oes anyone know why only Header files have the consistent header of
> 
> ```c++
> /*
>  * Xournal++
>  *
>  * <Description on File>
>  *
>  * @author Xournal++ Team
>  * https://github.com/xournalpp/xournalpp
>  *
>  * @license GNU GPLv2 or later
>  */
> ```
> 
> and `.cpp` files only sporadically?

I have no idea. Maybe it just grew that way. 

> I think this would be a nice/simple check we could add to the CI. Basically apart from Whitelisted files there should be no header file without this header.

Sounds good to me. It would simplify our task considerably.

**Comment by idotobi** [comment]
While going through the copyright files I found the [Coypright.txt](https://gitlab.kitware.com/cmake/cmake/raw/master/Copyright.txt) from cmake and they use a nice wording with regards to copyright:

```
The following individuals and institutions are among the Contributors:

* ...
* ....

See version control history for details of individual contributions.
```

That's something that we could copy.

**Comment by idotobi** [comment]
I put up a first draft in  #3120. Once the Icons are merged I can rebase and check once more with the script.

**Comment by idotobi** [comment]
I just tried to understand the rational behind the existing `debian/copyright` file and I was wondering where we actually got the information from that the `svg`'s have a different license than the main project.
Is there some project rule that `.svg`s and `.png`s are licensed with a CC license by default? 

My naive assumption would have been that any committed file gets the license of the project if there's no indication for a different license :thinking: 

@rolandlo : Do you know anything on this?

**Comment by rolandlo** [comment]
> My naive assumption would have been that any committed file gets the license of the project if there's no indication for a different license thinking
> 
> @rolandlo : Do you know anything on this?

I would assume so, too. Only @barak (who created this `debian/copyright` file) can tell why he assumed something different. Maybe it is because of the field `   xmlns:cc="http://creativecommons.org/ns#"` contained in those svg-files, but as I understand that is only a link to a website explaining the Creative Commons Rights Expression Language.

**Comment by barak** [comment]
I tried to put in comments for where the info was coming from, and I was just rapidly trying to put something together. But, the SVG files had embedded info, some of which is picked up by automated tools, and also I grovelled around in the git commit history to see if the relevant logs had any info and followed some of that up.

**Comment by idotobi** [comment]
@barak : Cool. I just was confused with some of the Comments especially where the Ubuntu Humanity Theme was involved but I think I understand it mostly now :crossed_fingers: 

@rolandlo : I guess all the icons in `ui/icons/*` will be replaced, right? If so I think I've got all the other icons covered. However, we should maybe ask the designer  of #1735 whether he is fine with GPL license or whether he would like to have it under CC of some sorts. Just to make sure we have a clear license for these from the get go.

On the same note: I currently have the following for the `ui/pixmaps/*` icons

```
Files: ui/pixmaps/com.github.xournalpp.xournalpp.svg
       ui/pixmaps/com.github.xournalpp.xournalpp.png
       ui/pixmaps/application-x-xojpp.svg
       ui/pixmaps/application-x-xopp.svg
       ui/pixmaps/application-x-xopt.svg
       ui/pixmaps/gnome-mime-application-x-xopp.svg
       ui/pixmaps/gnome-mime-application-x-xopt.svg
       ui/pixmaps/xopt.svg
Copyright: 2020 Luya Tshimbalanga <luya@fedoraproject.org>
License: GPL-2+
Comment: See https://github.com/xournalpp/xournalpp/pull/2557
         ??? Should this be GPL or CC0
```

@luyatshimbalanga : As you're the creator, is the license correct or should it be CC0. I saw that @barak had it as CC0 but I couldn't find any source for that.

**Comment by rolandlo** [comment]
> @rolandlo : I guess all the icons in `ui/icons/*` will be replaced, right? 

Yes, they will all be replaced.

> If so I think I've got all the other icons covered. However, we should maybe ask the designer of #1735 whether he is fine with GPL license or whether he would like to have it under CC of some sorts. Just to make sure we have a clear license for these from the get go.

I am glad you already asked.

**Comment by luyatshimbalanga** [comment]
> @luyatshimbalanga : As you're the creator, is the license correct or should it be CC0. I saw that @barak had it as CC0 but I couldn't find any source for that.
@idotobi : the correct license is [CC-SA](http://creativecommons.org/licenses/by-sa/4.0/)

**Comment by idotobi** [comment]
Thanks @luyatshimbalanga for clarifying! I'll add `CC BY-SA 4.0` then in the copyright file.

**Comment by idotobi** [comment]
@Fatih20 : If I understood right you're designing the new Icons. If so, did you already think about what license they should have? By default they would get licensed as the code (i.e. GPL-v2+). However, since icons are a bit different then code you might want to consider a different license.
I would then take it up to track this in our `copyright.txt` file :innocent:

**Comment by barak** [comment]
@idotobi made a quick pass over your copyright.txt file, pushed to barak/xournalpp branch feature/copyright-txt

**Comment by idotobi** [comment]
@barak: Thanks I merged most of your changes in :pray: and also updated the file a bit further. Once the icons are merged I think we should be ready to merge :nerd_face: if you agree.

Only the license for `cmake/find/FindICU.cmake` I kept with `BSD-2-clause` (not taking up https://github.com/barak/xournalpp/commit/b2471c760e37a8fa33710792d8ad0c7aeacb2d31) as the linked repo  https://github.com/julp/FindICU.cmake indicates this license. Do you agree with this or did I miss anything?

**Comment by Fatih20** [comment]
> @Fatih20 : If I understood right you're designing the new Icons. If so, did you already think about what license they should have? By default they would get licensed as the code (i.e. GPL-v2+). However, since icons are a bit different then code you might want to consider a different license.
> I would then take it up to track this in our `copyright.txt` file

Yes keep it GPL because some of the icons were modified elementary OS because that was my design approach.

**Comment by idotobi** [comment]
@Fatih20 : Cool. Just to be sure, you mean these Icons https://github.com/elementary/icons? Then I'd add GPL-3+ as the license.

Should I add elementary OS for copyright information as well or was elementary OS merely a style guide/inspiration?

**Comment by Fatih20** [comment]
> @Fatih20 : Cool. Just to be sure, you mean these Icons https://github.com/elementary/icons? Then I'd add GPL-3+ as the license.
> 
> Should I add elementary OS for copyright information as well or was elementary OS merely a style guide/inspiration?

Yes those icons specifically. It's just an inspiration but a few of them are pretty similar so I'd say add it as well.

**Comment by barak** [comment]
@idotobi When I took a quick glance it looked like pretty much the same boilerplate as the other cmake files with BSD-3-clause. But if you're sure it's BSD-2-clause, there has to be a stanza actually giving the license, like there is for BSD-3-clause.

PS Who uses 2-clause? That brings back some ancient memories.

PPS Pushed a tiny typo fix.

**Comment by idotobi** [comment]
@barak : Thanks for the typo fix :pray:  I merged it it

**Comment by barak** [comment]
@idotobi your commit reads "- keep BSD-2-clause for cmake/find/FindICU.cmake  as this is the license mentioned in the linked repo", couldn't figure out what you meant there. Anyway, need to also include the text of the BSD-2-clause license, probably in another stanza at the bottom.
```

License: BSD-2-clause
Comment: See https://opensource.org/licenses/BSD-2-Clause
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 .
 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 .
 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 .
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by idotobi** [comment]
@barak : I meant that during the merge I kept the BSD-2-clause and didn't include your change to BSD-3-clause. This is because the repository mentioned in the comment of the respective section in the `copyright.txt` uses BSD-2-clause.
I thought I add this detail to the commit for transparency, but I guess there was still some clarity missing in my writing :sweat_smile: .

Cool I'll add the BSD-2-clause license text as well then.
