### ISSUE TITLE
Cannot open file with PDF extension (renaming to pdf works)

### ISSUE THREAD

**Issue by ngoonee** [xournalpp/xournalpp#3104]
Am on Linux, in KDE
1.1.0+dev and libgtk-3.24.29
Installed using PKGBUILD from AUR (xournalpp-git) on 17 April

When opening a file with the extension PDF (all capital letters) xournalpp opens a blank document. A blank messagebox shows with no context except the 'OK' button. Renaming the exact same document to having .pdf extension, xournalpp has no problems opening it.

I've tried with various other combinations of capital letters, it seems any capital letters in the extension fail.

**Comment by bhennion** [comment]
Fixed on master
