### ISSUE TITLE
Maths Geomertical tools

### ISSUE THREAD

**Issue by mandypreet** [xournalpp/xournalpp#3105]
Hello Sir,
Sir, I am requesting a new feature ---**"Maths Geometrical tools"** including ruler, protractor, Compass, setsquare, basic 2D -shapes and 3D-shapes etc. So, it make us easy to teach maths online.

**Comment by personalizedrefrigerator** [comment]
See also #1937

**Comment by rolandlo** [comment]
Closing this, since it is a duplicate of #1937. Also for the setsquare see PR #3082
