### ISSUE TITLE
Problems with some plugins

### ISSUE THREAD

**Issue by Flixx2** [xournalpp/xournalpp#3108]
Unfortunately I can't run some of the bundled plugins, especially `ColorCycle` and `Layer Actions`. I get these error messages:

`Error in Plugin: «LayerActions», error: «/usr/bin/plugins/share/xournalpp//plugins/LayerActions/main.lua:9: field 'geunfortunatelytDocumentStructure' is not callable (a nil value)»`

`Error in Plugin: «ColorCycle», error: «/usr/bin/../share/xournalpp//plugins/ColorCycle/main.lua:34: field 'changeToolColor' is not callable (a nil value)»`

I have tested it on two machines (1. Archlinux + I3, 2. Manjaro KDE) with 
Xournal++ 1.0.20-2.

My Lua-Experience is little so every help is appreciated.

Thanks, *Flixx2*

**Comment by rolandlo** [comment]
It's simple as that: You need Xournal++ [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) to have these plugins running.
