### ISSUE TITLE
Cannot export large pdfs

### ISSUE THREAD

**Issue by Alphaoo1** [xournalpp/xournalpp#3111]
**Affects versions :**
 - OS: Kubuntu 18.04 LTS
 - (Linux only) Desktop environment: KDE 5.44.0 / Plasma 5.12.9
 - Which version of libgtk do you use
     - Couldn't run command
 - Version of Xournal++: Version 1.0.18, Commit 535d261d built on April 15 2020, 19;11:11

 - Installation method: official release

**Describe the bug**
I have a note with 80+ pages. When I try to convert it to pdf only 23 pages are being converted.
Although when I convert other note I have with 45 pages, all the pages are exported in the pdf.
I am unsure why it is happening to this specific file. 

**To Reproduce**
1. Open a note, with written notes, images, text etc.
2. Export as pdf
3. Save

**Expected behavior**
A pdf with exact same pages should be available after exporting the notes.

**Screenshots of Problem**
1. Screenshot of PDF: In the screenshot, you may see after the 22nd page it just goes blank. 
![Screenshot_20210511_163258](https://user-images.githubusercontent.com/27627601/117833737-e43cb180-b276-11eb-888d-a47b6b1388ba.png)

2. Screenshot of Xournal++ for the same pages
![Screenshot_20210511_163435](https://user-images.githubusercontent.com/27627601/117833755-e737a200-b276-11eb-95d0-4431014c0436.png)

**Comment by rolandlo** [comment]
You are using quite an old version. Could you try again with [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? Simplest is to use the AppImage. If it doesn't work would you mind sharing the xopp-file? You can also do it privately with one of the devs in the [Gitter chat](https://gitter.im).

**Comment by Alphaoo1** [comment]
Thank you for the help and suggestions.
