### ISSUE TITLE
Xournal++ crash

### ISSUE THREAD

**Issue by fmbonobo** [xournalpp/xournalpp#3114]
**Affects versions :**
 - OS: Linux Mint 20.1
 - (Linux only) Desktop environment: X11
 - libgtk  3.24.20

 - Version of Xournal++: xournalpp - 1.1.0+dev~202105130555~ubuntu20.04.1
   
 - Installation method:  PPA

Xournal++ crashes on start since version 20210507.....

**To Reproduce**
1. Launch Xournal++

**Expected behavior**
Software opens a window
[errorlog.20210513-160741.log](https://github.com/xournalpp/xournalpp/files/6474167/errorlog.20210513-160741.log)

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Terminal output:

[term_output.txt](https://github.com/xournalpp/xournalpp/files/6474190/term_output.txt)

**Comment by rolandlo** [comment]
A similar bug, also introduced by #2624, shows up under MS Windows, see #2316. 
On Ubuntu 21.04 I don't get it.

@Technius Can you shed some light into this? Do we need to revert 432b70c?

**Comment by fmbonobo** [comment]
Same problem with  1.1.0+dev~202105131557~ubuntu20.04.1
