### ISSUE TITLE
Crash after Ubuntu 21.04 update

### ISSUE THREAD

**Issue by Goneiross** [xournalpp/xournalpp#3116]
**Affects versions :**
 - OS: Ubuntu 21.04
 - (Linux only) Desktop environment: Wayland, with GNOME 3.38.5
 - Which version of libgtk do you use
     -  3.24.11
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - Xournal++ 1.1.0+dev
 - PPA or from git, I don't remember

**Describe the bug**
After updating to Ubuntu 21.04, Xournalpp keep crashing. I can't use it for more than 5 minutes.

**To Reproduce**
Launch it and use it for a few minutes or seconds.

**Logs**
[launch logs.txt](https://github.com/xournalpp/xournalpp/files/6479558/launch.logs.txt)
[errorlog.20210514-154233.log](https://github.com/xournalpp/xournalpp/files/6479526/errorlog.20210514-154233.log)
[errorlog.20210514-154317.log](https://github.com/xournalpp/xournalpp/files/6479530/errorlog.20210514-154317.log)
[errorlog.20210514-155341.log](https://github.com/xournalpp/xournalpp/files/6479531/errorlog.20210514-155341.log)
[errorlog.20210514-155445.log](https://github.com/xournalpp/xournalpp/files/6479532/errorlog.20210514-155445.log)
[errorlog.20210514-155528.log](https://github.com/xournalpp/xournalpp/files/6479533/errorlog.20210514-155528.log)
[errorlog.20210514-155623.log](https://github.com/xournalpp/xournalpp/files/6479534/errorlog.20210514-155623.log)
[errorlog.20210514-155940.log](https://github.com/xournalpp/xournalpp/files/6479536/errorlog.20210514-155940.log)
[errorlog.20210514-163858.log](https://github.com/xournalpp/xournalpp/files/6479537/errorlog.20210514-163858.log)
[errorlog.20210514-164301.log](https://github.com/xournalpp/xournalpp/files/6479538/errorlog.20210514-164301.log)

**Comment by Technius** [comment]
Weird, the error logs don't seem to capture anything useful. Can you try running Xournal++ from console and posting the whole log?

**Comment by Goneiross** [comment]
The file named [launch logs.txt](https://github.com/xournalpp/xournalpp/files/6479558/launch.logs.txt) contains the log while launching Xournal++ from the console :)

**Comment by rolandlo** [comment]
@Goneiross How come your Gtk version (3.24.11) is so old on Ubuntu 21.04? Default is 3.24.25, see https://pkgs.org/search/?q=libgtk-3-0

**Comment by Goneiross** [comment]
Hmm no idea why, I just upgraded :  
```
goneiross@goneiross-bubuntu:~$ apt-cache policy libgtk-3-0
libgtk-3-0:
  Installed: 3.24.25-1ubuntu4
  Candidate: 3.24.25-1ubuntu4
  Version table:
 *** 3.24.25-1ubuntu4 500
        500 http://ch.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```

I tried for a few minutes, I had no crash. I don't have much time to test it this morning, but I'll mark as fixed if I don't see any other crashes today or tomorrow :) Thank you for your help !
