### ISSUE TITLE
Cursor not moving with Stylus

### ISSUE THREAD

**Issue by DevastatingRPG** [xournalpp/xournalpp#3119]
**Affects versions :**
 - OS: Windows 10
 - Which version of libgtk do you use
     - 3.24.23
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.20
 - Installation method: Official Release Stable

**Describe the bug**
The cursor is visually stuck at one place when I'm moving my stylus pen around but when I use it it actually draws according to where it should be drawing, cursor moves if I move the mouse but not if I use the stylus. The cursor does move with the stylus if I use another program.

**To Reproduce**
1. I do not know how to reproduce it on other systems as I'm not that well versed with all this but for me this is a constant issue sometimes it goes away after changing input system but comes back again

**Expected behavior**
The cursor should move with the stylus where it actually is going to draw

**Comment by rolandlo** [comment]
Please try version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and see, if the problem persists there.

**Comment by DevastatingRPG** [comment]
Unfortunately it still seems to be there

**Comment by DevastatingRPG** [comment]
After restarting a few times it's gone now, so perhaps a very rare bug
