### ISSUE TITLE
Infinite page option?

### ISSUE THREAD

**Issue by The-Linux-User** [xournalpp/xournalpp#3123]
Would it be possible to add an infinite page option? I picture it like in OneNote where the page gets bigger and bigger the more you scroll horizontally / vertically.
This would help with long flowcharts or big images since you are not restricted by the size of a DIN A4 page.

**Comment by ericschdt** [comment]
Duplicate: 
* https://github.com/xournalpp/xournalpp/issues/2683
* https://github.com/xournalpp/xournalpp/issues/1174
