### ISSUE TITLE
No pressure sensitivity nor eraser tip detected with Wacom Bamboo craft cth-461

### ISSUE THREAD

**Issue by Torkin1** [xournalpp/xournalpp#3128]
**Affects versions :**
 - OS: Fedora release 33 (Thirty Three) x86_64
 - (Linux only) Desktop environment: Plasma 5.20.5
 - Which version of libgtk do you use: 3.24.
 - Version of Xournal++: 1.0.20
 - Installation method: updates fedora 33 kde plasma

**Describe the bug**
In Xournalpp Pressure sensitivity is not enabled despite having corresponding setting enabled. Eraser tip writes instead of actually erasing. Everything works fine in Xournal and OpenBoard. Same bug occurs in Jarnal.

**To Reproduce**
1. Plug in Wacom board
2. Open Xournalpp
3. Draw some lines
4. Try to erase them with eraser tip

**Expected behavior**
Strokes should be more or less thin reflecting pressure of pen. Using eraser tip should erase strokes instead of drawing them

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
```
[daniele@T540p ~] $ dnf list installed | grep wacom
kcm_wacomtablet.x86_64                           3.2.0-2.fc33                           @fedora                                          
libwacom.x86_64                                  1.9-2.fc33                             @updates                                         
libwacom-data.noarch                             1.9-2.fc33                             @updates                                         
xorg-x11-drv-wacom.x86_64                        0.39.0-3.fc33                          @fedora                                          
xorg-x11-drv-wacom-serial-support.x86_64         0.39.0-3.fc33                          @fedora

[daniele@T540p ~] $ lsusb | grep Wacom
Bus 003 Device 008: ID 056a:00d2 Wacom Co., Ltd CTH-461 [Bamboo Fun/Craft/Comic Pen & Touch (S)]

[daniele@T540p ~] $ dnf list installed | grep xournalpp
xournalpp.x86_64                                 1.0.20-3.fc33                          @updates                                         
xournalpp-plugins.noarch                         1.0.20-3.fc33                          @updates                                         
xournalpp-ui.noarch                              1.0.20-3.fc33                          @updates

[daniele@T540p ~] $ xournalpp --version
Xournal++ 1.0.20 
└──libgtk: 3.24.29

[daniele@T540p ~] $ neofetch
          /:-------------:\          daniele@T540p 
       :-------------------::        ------------- 
     :-----------/shhOHbmp---:\      OS: Fedora release 33 (Thirty Three) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: 20BE0087GE ThinkPad T540p 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.11.21-200.fc33.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 22 mins 
,------------:MMMd--------    ---:   Packages: 4098 (rpm), 30 (flatpak), 19 (snap) 
:------------:MMMd-------    .---:   Shell: bash 5.0.17 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080 
:--     .+shhhMMMmhhy++   .------/   DE: Plasma 5.20.5 
:-    -------:MMMd--------------:    WM: KWin 
:-   --------/MMMd-------------;     WM Theme: Gently-Blur 
:-    ------/hMMMy------------:      Theme: Gently [Plasma], Adwaita [GTK2], Breeze [GTK3] 
:-- :dMNdhhdNMMNo------------;       Icons: breeze [Plasma], breeze-dark [GTK2], breeze [GTK3] 
:---:sdNMMMMNds:------------:        Terminal: yakuake 
:------:://:-------------::          CPU: Intel i7-4700MQ (8) @ 3.400GHz 
:---------------------://            GPU: Intel 4th Gen Core Processor 
                                     GPU: NVIDIA GeForce GT 730M 
                                     Memory: 3391MiB / 15691MiB 

                                                             
                                                             

```

**Comment by rolandlo** [comment]
Sorry for the late response, but could you please try with version 1.1.0 again and post a screenshot of your settings in the input system panel in menu `Edit > Preferences`?

**Comment by Torkin1** [comment]
@rolandlo  thank you for your response. Issue still persist.
```
$ xournalpp --version
Xournal++ 1.1.0
└──libgtk: 3.24.29
```
![immagine](https://user-images.githubusercontent.com/32265040/127768043-83c1c75f-57b4-41de-8723-44d7eff71938.png)

**Comment by rolandlo** [comment]
No devices were found. That's the strange thing. Maybe it's a Gtk+ 3 bug. Do you also experience that problem with Inkscape? Xournal uses Gtk+ 2 and Openboard uses Qt instead of Gtk.

**Comment by Torkin1** [comment]
@rolandlo same behaviour happens in inkscape, i've never used it tho so i don't know if I have to do additional setup. Only setting i enabled before giving a try was the pressure sensitivity (see screenshot)
![immagine](https://user-images.githubusercontent.com/32265040/127769189-93e6d6f5-80bf-43e4-89a3-bc1461c13083.png)

**Comment by rolandlo** [comment]
I'm no Inkscape expert, but it doesn't look like there is an additional setup required. Your problem is most likely Gtk+ 3 related, so I would advice you to try your luck at the Gtk+ issue ticker https://gitlab.gnome.org/GNOME/gtk/-/issues

Otherwise you could also generate some more info via [input debug logs](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs)

**Comment by Torkin1** [comment]
I've [filed a bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/4143) at Gtk guys, let's see what happens next.
I'm also following the steps to generate the debug log, I'll post the results when they will be available

**Comment by Torkin1** [comment]
@rolandlo here are the results
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/6912655/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/6912656/debug_input.log)

**Comment by rolandlo** [comment]
As I can see from the input debug logs, the only input device (apart from the keyboard) is `GDK_SOURCE_MOUSE`, so your pen is clearly not recognized as a pen by `GTK/GDK`.

**Comment by Torkin1** [comment]
so are we confident enough to say that this is a gtk+3 related issue?

**Comment by rolandlo** [comment]
You could try out the `gtk3-demo` from the `gtk-3-examples` package. There is a little `Paint` demo, where pressure sensitivity should work if it is not a Gtk+ 3 related thing.
Maybe you also have some system settings related to stylus handling. On Gnome there is the `Wacom graphics tablet` tab where one can also test pressure sensitivity.

**Comment by Torkin1** [comment]
@rolandlo i tried such paint application, but I'm unable to produce any strokes, with neither stylus nor mouse.

**Comment by rolandlo** [comment]
> @rolandlo i tried such paint application, but I'm unable to produce any strokes, with neither stylus nor mouse.

The mouse also doesn't produce any strokes for me. The stylus does. 

> In my system settings there is a test util for visualizing intensity of pen pressure, It works fine, as you can see in the little demo. It comes for the kde settings tho, so i would assume it doesn't use gtk3 but qt instead

That would also support the assumption that it is a Gtk+ 3 thing. You could also check if Gtk+ 4 (which is not supported by Xournal++) works for you. Just use the Gtk4-demo.

**Comment by Torkin1** [comment]
just tried gtk4 version of paint demo and it works just fine. Both pen pressure sensitivity and eraser tip are enabled.
Is there any chance xournalpp will switch to this version of gtk? :)

**Comment by rolandlo** [comment]
> I've tried gtk4 version of paint demo and it works just fine. Both pen pressure sensitivity and eraser tip are enabled.
> Is there any chance xournalpp will switch to this version of gtk? :)

That is going to happen in future, but it is a lot of work to migrate from Gtk+ 3 to Gtk 4.

**Comment by Torkin1** [comment]
I see. Thank you for all your help!

**Comment by Torkin1** [comment]
Gtk guys helped me to find the problem. Full details of solution [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/4143#note_1242261).
Also I found this issue is related to #1073

Thank's everyone for your help!
