### ISSUE TITLE
Language not available

### ISSUE THREAD

**Issue by dein-spec** [xournalpp/xournalpp#3132]
The language is not set up according to the system language. My language is German, the program language is English. 
I use Debian Buster.

**Comment by rolandlo** [comment]
What Xournal++ version do you use? Try [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly).

**Comment by dein-spec** [comment]
I use xournalpp-1.0.20-hotfix-hotfix-Debian-buster-x86_64.deb

**Comment by dein-spec** [comment]
Version 1.1.0+dev. is significantly better. Arrange not translated.

**Comment by rolandlo** [comment]
It will be translated after #2689 is merged, see [here](https://github.com/xournalpp/xournalpp/pull/2689/files#diff-40f15e10e30a261044aef38a094ba2c2ab5f9575de33df7fd7e510d48165ff87)
