### ISSUE TITLE
Add option to clear entire page

### ISSUE THREAD

**Issue by matheusunitt** [xournalpp/xournalpp#3137]
**Is your feature request related to a problem? Please describe.**
When the page is full of content, I have to add another page so I can keep adding more content, but sometimes it would be easier just to keep using the same page instead.

**Describe the solution you'd like**
A shortcut and button option to clear the current's page content. Of course that would be useful when doing quick notes, since it's not really a feature to be used when you want to have multiple pages or saving the file.

**Describe alternatives you've considered**
Allow deletion of the first and only page avaliable, and when it gets deleted, a new blank page is added automatically.

**Additional context**
Not applicable.

**Comment by Technius** [comment]
This could probably be done with a plugin. Something like:
```lua
function initUi()
    app.registerUi({["menu"] = "Clear page", ["callback"] = "clearPage");
end

function clearPage()
    app.uiAction({["action"]="ACTION_NEW_PAGE_AFTER"})
    app.uiAction({["action"]="ACTION_GOTO_BACK"})
    app.uiAction({["action"]="ACTION_DELETE_PAGE"})
end
```
(I have not tested this)

**Comment by matheusunitt** [comment]
Thank you @Technius for your reply.

Where is this button supposed to be located at? I added the script and it's now enabled in the plugin manager, but I couldn't find a menu entry "Clear page".

**Comment by rolandlo** [comment]
After fixing the missing curly bracket after `"clearPage" in `initUi` It should be found in the menu `Plugin`.

**Comment by matheusunitt** [comment]
Oh I see. Thanks @rolandlo for helping. I totally missed out the curly bracket there.
And thank you @Technius for the code.

After trying the script the desired feature worked as intended.

**Final code**:
`function initUi()
    app.registerUi({["menu"] = "Clear page", ["callback"] = "clearPage"});
end

function clearPage()
    app.uiAction({["action"]="ACTION_NEW_PAGE_AFTER"})
    app.uiAction({["action"]="ACTION_GOTO_BACK"})
    app.uiAction({["action"]="ACTION_DELETE_PAGE"})
end`
