### ISSUE TITLE
I see mouse cursor instead of dot even with new input system selected.

### ISSUE THREAD

**Issue by ajr-dev** [xournalpp/xournalpp#3141]
On Windows 10 I checked enable new input system and Dark Theme in the options and then I restarted the computer. I'm supposed to see a dot but when the stylus is not touching the tablet I see the typical mouse cursor. And the theme hasn't changed. How do I manage to see a dot all the time instead of the mouse cursor and how do I get the Dark Theme?

**Comment by Technius** [comment]
What version of Xournal++ are you using?

> I'm supposed to see a dot but when the stylus is not touching the tablet I see the typical mouse cursor.

What does the `Input System` tab in the preferences window look like for you?

---

For dark theme on Windows, see https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-612533873

**Comment by ajr-dev** [comment]
https://ibb.co/85gLdND
https://ibb.co/QdSFr3w

When I didn't have xp-pen driver installed it worked, correctly, except it didn't write. After installing the driver it did write but it only showed the mouse cursor. It didn't show a dot.

**Comment by rolandlo** [comment]
@ajr-dev Please try changing `Pentablet Stylus Pen (pen)` from "Mouse" to "Pen".

**Comment by ajr-dev** [comment]
That fixed it.
