### ISSUE TITLE
switching to another application causes xournal++ to move to the top of the page (or previous page)

### ISSUE THREAD

**Issue by waynongithub** [xournalpp/xournalpp#3146]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: linux mint 19.3
 - (Linux only) Desktop environment: mate
 - Which version of libgtk do you use 1 0 20
 
 - Version of Xournal++:3 18 9
  
 - Installation method: appimage

**Describe the bug**
switching to another application causes xournal++ to scroll back to the top of the page, or the top of the previous page, even when the cursor is positioned inside a textbox 

**To Reproduce**
1. add a text annotation on the bottom of the page
2. alt-tab to or click on another application -> this will make xournal++ scroll back to the top of the page
3. when you return to xournal++ you have to scroll back down to return to the previous position

**Expected behavior**
I would expect xournal++ to retain it's position so i don't have to scroll back to where i was

thank you

**Comment by rolandlo** [comment]
Please try out the [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) AppImage. It may be fixed there.

**Comment by waynongithub** [comment]
Thank you, that seems to work well. It also solves issue #3134 (cannot open document by double-clicking the file or choosing "open with" from context menu).
Thanks for the swift response!
