### ISSUE TITLE
Embedded browser

### ISSUE THREAD

**Issue by maresb** [xournalpp/xournalpp#3148]
**Describe the solution you'd like**

I'd like to embed a web browser in a Xournal document so that I could, for example, conduct an online poll while sharing only my Xournal window.

**Describe alternatives you've considered**

I looked through the menus and didn't find anything related. I also looked briefly at the Lua plugins and didn't find anything there. There is a browser called Luakit, but it seems to be WebKit based, and only Lua-extensible. Thus I don't have any ideas for how to achieve a browser without programming something. (Unfortunately I'm not so strong in C++.)

**Comment by mjg** [comment]
I think this is more a question about how to share 2 windows at the same time. There is no interaction between the xournal document and the browser; xournal content is statis, browser is dynamic, so I don't really see any meaning in embedding.

How to share 2 windows - a few options:
- some tools allow this directly (zoom on some platforms)
- put them on one screen and share that screen (with all the advantages and disadvantages)
- create a virtual screen, put the windows there (Xnest, Xephyr if you're on X11) and share that screen
- create a window containing the 2 windows (e.g. using obs) and share that window

**Comment by Technius** [comment]
I agree with @mjg; I think implementing this would be complicated and would go beyond the scope of Xournal++, so I'm going to close this issue.
