### ISSUE TITLE
Unable to see the cursor/pointer when using some tools

### ISSUE THREAD

**Issue by souzamarcelo** [xournalpp/xournalpp#3157]
Hi!

**Affects versions :**
 - OS: Linux Mint 20
 - Desktop environment: Cinnamon (version 4.6.7)
 - Which version of libgtk do you use: 3.24.21
 - Version of Xournal++: 1.0.20, commit 09ec499
 - Installation method: PPA

**Describe the bug**

When selecting some tools (details below), the cursor becomes white, and it is not possible to see it (since the background of the paper is white). This happens with input system enabled and disabled. However, when disabled, it is possible to see the mouse pointer, before start writing.

This happens with the following tools:
- Pen using colors: gray, light blue, dark green, light green, orange, yellow, white
- Highlighter
- Eraser

**To Reproduce**
1. Select pen with green color
2. Start writing and check the cursor

**Expected behavior**
I think the application identify that a light color is being used, and make the cursor white. Instead, it should check the paper background color to make it white only when it is dark.

**Comment by rolandlo** [comment]
Can you please try out version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? Easiest is to use the AppImage.

**Comment by souzamarcelo** [comment]
I tested the [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) version and it is fixed now. Thank you for pointing this. I'm closing this issue.
