### ISSUE TITLE
Hide/show bottombar

### ISSUE THREAD

**Issue by bagustris** [xournalpp/xournalpp#3160]
**Is your feature request related to a problem? Please describe.**
No. it is not related to problem, but a suggested improvement.
Working with pen tablet means we only have limited space in the bar to write and draw. A lot of bar in the GUI of xournalpp will reduce our working area in the pad. Since there are already features to show/hide sidebar and menubar, why we didn't give the option to hide bottom bar? It will add more space when giving lecture/presentation, especially with the following setting: Edit > Toolbar > xournal++ > full screen mode, paper format: 16x9

**Describe the solution you'd like**
Option to hide bottombar (Edit > show bottombar) with shortcut

**Describe alternatives you've considered**
Full screen mode will hide all menu except menu bar. It also good alternative.

**Additional context**
![2021-06-15-Note-11-49](https://user-images.githubusercontent.com/3158361/122168363-25983080-ceb7-11eb-966e-b3b818aa8812.png)

**Comment by VivekThazhathattil** [comment]
Did you try View->Toolbars and then choosing a different toolbar layout?

**Comment by bagustris** [comment]
Thanks for the information. The closest one is `empty bar`, but no menu bar shown. So far,  the toolbar left/right is the most convenient. Thanks!
