### ISSUE TITLE
How use option stock icons ?

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#3161]
There is no change when I check in preferences "use stock icons" (windows 10)

**Comment by rolandlo** [comment]
Did you restart Xournal++? Note that there are relatively few stock icons, so only a couple of icons will change. See (some of) the difference here:

With available stock icons:
![grafik](https://user-images.githubusercontent.com/40485433/122221443-92103100-ceb1-11eb-9ac1-10c540f2a94c.png)

Only custom icons:
![grafik](https://user-images.githubusercontent.com/40485433/122221670-c97edd80-ceb1-11eb-8907-6da8800cd561.png)

**Comment by MichelReims** [comment]
Thank you. 
Notice that the icon for thickness-ticker is not of the same color of others (it is not present in the directory)

**Comment by rolandlo** [comment]
> Notice that the icon for thickness-ticker is not of the same color of others (it is not present in the directory)

Indeed, you are right! Thanks for noticing. We simply forgot to port the `thickness-thicker` icon to the light theme. It should have been part of [this commit](https://github.com/xournalpp/xournalpp/pull/2886/commits/d0620cbd970dc6f2bed302534b877bfbd3803495)
@Fatih20 Could you please do that (port the thickness-thicker icon to light theme)?

**Comment by Fatih20** [comment]
> > Notice that the icon for thickness-ticker is not of the same color of others (it is not present in the directory)
> 
> Indeed, you are right! Thanks for noticing. We simply forgot to port the `thickness-thicker` icon to the light theme. It should have been part of [this commit](https://github.com/xournalpp/xournalpp/pull/2886/commits/d0620cbd970dc6f2bed302534b877bfbd3803495)
> @Fatih20 Could you please do that (port the thickness-thicker icon to light theme)?

Whoops that's a huge oversight on my part. Will do.
