### ISSUE TITLE
PDF background not found dialog suggestion

### ISSUE THREAD

**Issue by betheb** [xournalpp/xournalpp#3164]
First, thank you to the developers and community. 

This is a suggestion, and maybe there will be a reason not to implement it, but I figured I'd make the suggestion in case...

When I use Xournal (the original), after moving the files the link between the .xoj and the .pdf background are disassociated. But Xournal will announce: 

"Could not open background..." and then it will list the file name, as well the choice to select a different background. That is really useful.

When I use Xournal++, after the moving the files, when the link becomes disassociated, it displays this message:

"The background PDF could not be found." and gives a choice to select another file. But it doesn't have the name of the pdf that used to be the background.

It would be useful, to me, if that filename were displayed in the popup dialog (as happens in Xournal) because then I could browse to it. 

My usage is pretty specific, I know. And I could figure out a way around this, but it was my habit to rely on that filename being listed in the popup.

Thanks

**Comment by rolandlo** [comment]
You must be using an older version. Please upgrade to [version 1.1.0+dev](). The message reads like:

```
The background file `ABC.pdf` could not be found. It might have been moved, renamed or deleted. 
It was last seen at: full/path/name
```
and you have the choice to replace, remove or cancel.

**Comment by betheb** [comment]
Thank you. That was it! I got the latest, and the dialog box shows me what I needed to know.
