### ISSUE TITLE
Images used as background are not saved.

### ISSUE THREAD

**Issue by alexanderFell** [xournalpp/xournalpp#3165]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Debian Buster
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.5
 - Version of Xournal++: 1.1.0+dev (nightly 20210618)
 - Installation method: Automated nightly build

**Describe the bug**
I use a PNG file as a background for some pages. After applying the background image, saving the document and reopening it, only the first page has the background image. All following pages have a gray "PDF background missing" instead.

**To Reproduce**
1) Go to Journal -> Paper background -> Image.
2) Select the PNG image and then select Journal -> Paper background -> Apply to all pages.
3) Confirm the background page individually for each page by clicking the OK button (50 times in my case) to apply the background to all pages 
4) save the document and close xournalpp
5) reopen the file in xournalpp

**Expected behavior**
The document should look like as it has been saved including the background images.
![Before saving](https://user-images.githubusercontent.com/11865235/122563039-0549ac80-d044-11eb-8b20-66cc2f28cd57.png)
![After loading the same document](https://user-images.githubusercontent.com/11865235/122563044-05e24300-d044-11eb-85d6-8042c4f15f3b.png)

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Looking at the extracted xopp-file, I can see how the page backgrounds get stored (for a file with 3 pages with the same png background):
```xml
<page width="1746.00000000" height="212.00000000">
<background type="pixmap" domain="absolute" filename="/path/to/file"/>
<layer/>
</page>
<page width="1746.00000000" height="212.00000000">
<background type="pixmap" domain="clone" filename="0"/>
<layer/>
</page>
<page width="1746.00000000" height="212.00000000">
<background type="pixmap" domain="clone" filename="0"/>
<layer>
```
This is consistent with [Xournal user's manual]()
> A value of "clone" indicates that the bitmap is identical to the background of a previous page of the journal; the filename attribute then specifies the page number, starting with 0 for the first page. For example, if a filename value of "1" indicates that the background bitmap is identical to that of the second page.

So the bug must be in the load handler, not in the save handler.

**Comment by rolandlo** [comment]
The same problem also appears in versions 1.0.19 and 1.0.20. 

PR #3170 fixes the problem in the load handler.
