### ISSUE TITLE
Dark Mode Does Not Function Properly in Windows

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3168]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use
     - 3.24.29
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.0+dev git commit 99df9684
 - Installation method: Windows Install from Zip folder off of github

**Describe the bug**
Dark mode is not working properly. The tool bar and icons remain in light mode even after switching to dark mode.

**To Reproduce**
1. Enable Dark Mode and restart
2. Observe that only the page viewer background, and the icons are dark, and nothing else (toolbar backgrounds etc).

**Expected behavior**
I expect the standard dark mode, as seen in the linux version.

**Screenshots of Problem**
Light mode:
![image](https://user-images.githubusercontent.com/7829231/122630554-72c40000-d079-11eb-95c0-437f57f7887f.png)

Enable dark mode:
![image](https://user-images.githubusercontent.com/7829231/122630567-88392a00-d079-11eb-9edf-60bdd6a454e1.png)

Xournalpp after restart:
![image](https://user-images.githubusercontent.com/7829231/122630575-a0a94480-d079-11eb-9697-bf2b0faa4d55.png)

**Comment by rolandlo** [comment]
Does [this answer](https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-612533873) help?

**Comment by K4LCIFER** [comment]
> 
> 
> Does [this answer](https://github.com/xournalpp/xournalpp/issues/1746#issuecomment-612533873) help?

Yes, thank you. The solution there solved the problem.
