### ISSUE TITLE
In xournalpp-1.0.20-windows.exe, fr_FR locale folder is missing:

### ISSUE THREAD

**Issue by jerome7373** [xournalpp/xournalpp#3171]
In xournalpp-1.0.20-windows.exe, fr_FR locale folder is missing:
\Xournal++\share\locale\fr_FR\LC_MESSAGES\ 
    |_ gdk-pixbuf.mo
    |_ glib20.mo, gtk30.mo
    |_ gtk30-properties.mo
    |_ xournalpp.mo
I have copied them from the flatpak-1.0.20 installation folder to Xournal++ windows installation folder. It works.

**Comment by rolandlo** [comment]
This should be fixed in version 1.1.0+dev.
