### ISSUE TITLE
Select dark mode icons have poor contrast

### ISSUE THREAD

**Issue by siddhantladdha** [xournalpp/xournalpp#3179]
**Affects versions :**
 - OS: Pop OS 20.04 LTS (Based on Ubuntu 20.04 LTS) Linux
 - Desktop environment: Gnome X11
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++:1.0.20
 - Installation method:  Official release .deb package. (xournalpp-1.0.20-Ubuntu-focal-x86_64)

**Describe the bug**
Following dark mode icons have poor contrast. 
1. Eraser
2. Text
3. Add/Edit Tex
4. Hand
5. Presentation Mode

**To Reproduce**
1. Select Adwaita (Light) theme. You will be able to see the icons clearly as shown in Image 1.
2. Select Adwaita (Dark) theme / Any dark theme. The mentioned icons will have poor contrast as shown in Image 2.

**Expected behavior**
User should be able to see all the icons clearly even when using a system dark theme. Any suggestions for working dark theme and how to enable it for specifically Xournal++ are welcome.

**Screenshots of Problem**
![Image 1 Light Mode](https://user-images.githubusercontent.com/25705822/123188642-00f51780-d4ba-11eb-9e78-dec429a0c1c4.png)
![Image 2 Dark Mode](https://user-images.githubusercontent.com/25705822/123188637-ff2b5400-d4b9-11eb-88dc-1c02e239e637.png)

**Comment by siddhantladdha** [comment]
It has recently come to my notice that the issue may be with the icon theme I am using (On Pop OS it is default [Pop Dark](https://github.com/pop-os/icon-theme)).

I tried changing themes to Advaita and Breeze dark. However, it seems that the icons that I have mentioned (which have poor contrast) are overriden by Xournal++ since they do not change with the icon themes. (Please see the attached screenshots below).

![adwaita](https://user-images.githubusercontent.com/25705822/123246678-b00a1100-d503-11eb-9274-867be0a6d384.png)
![breeze_dark](https://user-images.githubusercontent.com/25705822/123246733-bd270000-d503-11eb-838f-b3c2ce1b6ea4.png)

**Comment by siddhantladdha** [comment]
Upon further searching, it seems like [#677](https://github.com/xournalpp/xournalpp/issues/677) and [PR 696](https://github.com/xournalpp/xournalpp/pull/696) should have solved this issue, but they do not.

**Comment by rolandlo** [comment]
Please try out [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly), enable Dark theme icons in the `View` panel in menu `Edit > Preferences` and restart Xournal++.

**Comment by siddhantladdha** [comment]
Kinda works.

1. Without enabling the "Dark Theme" I get the following.
![dev](https://user-images.githubusercontent.com/25705822/123252532-037f5d80-d50a-11eb-90f3-d329956f2021.png)
2. After enabling the "Dark Theme" I get the following.
![dark_theme](https://user-images.githubusercontent.com/25705822/123252578-12fea680-d50a-11eb-8e3c-903c00183a05.png)

Why is the "Dark Theme" enabled version still having poor contrast?
Note: I am using Appimage to test it out.
Thank you.

**Comment by rolandlo** [comment]
> Why is the "Dark Theme" enabled version still having poor contrast?
> Note: I am using Appimage to test it out.
> Thank you.

Have you restarted Xournal++ after enabling/disabling "Dark Theme"? Otherwise it won't work as expected.
Dark Theme icons are the ones in the picture above, light theme icons (although without light theme enabled in the system) look like in the picture below.

**Comment by siddhantladdha** [comment]
Yes. I restarted every time. For reference, see [this video](https://upload.disroot.org/r/F8kF8R4B#Cv4+O/1/bKZV63x/3c4EfVk9ZtqL4KyvJEH5CsJUfVg=) (valid for 30 days)

**Comment by rolandlo** [comment]
Thanks for the video. I checked the AppImage. It does indeed flip behavior in comparison with the other releases. I don't know why that happens. Maybe because it has a different GTK+ version packed.

**Comment by siddhantladdha** [comment]
Maybe I can given nightly .deb file a shot. Just one question. Can installing this nightly build via .deb file(not adding PPA) cause any dependency issues with Pop OS 20.04 LTS?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rolandlo** [comment]
> Maybe I can given nightly .deb file a shot. Just one question. Can installing this nightly build via .deb file(not adding PPA) cause any dependency issues with Pop OS 20.04 LTS? 

I don't think so, but you can use `gdebi` as described in [this blog post](https://itsfoss.com/gdebi-default-ubuntu-software-center/) to check if all dependencies are already available on your system before installing Xournal++.

**Comment by siddhantladdha** [comment]
So I gave the `xournalpp-1.1.0.dev-nightly.20210625-Ubuntu-focal-x86_64.deb` a shot and yes it does work well as intended. (The dark mode icons have improved contrast). In short, the appimage version might have the problem you mentioned.

>  It does indeed flip behavior in comparison with the other releases. I don't know why that happens. Maybe because it has a different GTK+ version packed.

Should I close this issue and file a new issue for AppImage and mention this issue there?

**Comment by rolandlo** [comment]
> Should I close this issue and file a new issue for AppImage and mention this issue there?

That would be ideal, yes!

**Comment by siddhantladdha** [comment]
#3190
