### ISSUE TITLE
Notifications being sent out about "release" of automated nightly builds

### ISSUE THREAD

**Issue by eyalroz** [xournalpp/xournalpp#3184]
This is not a bug with the app itself, but with the way the project is being managed on GitHub.

Somehow, I am getting notifications about new releases, repeatedly, which aren't actually releases but rather nightly builds:
```
@xournalpp
xournalpp / xournalpp
Automated nightly build

Automated nightly build for Xournal++ 1.1.0

Changes
etc. etc.
```
This doesn't happen to me with any other project on GitHub. I would actually want to be notified of proper releases, which is why I watch the project.

Can you please arrange for these faux announcement not to happen? I don't want to have to fully unsubscribe... :-(

**Comment by Technius** [comment]
This is because our CI config is, for some reason, set up to delete and create the release every time. We'll have to change our CI to 1) only update the release; and 2) re-tag `nightly`.

**Comment by Technius** [comment]
This has already been fixed for some time.
