### ISSUE TITLE
Dark Theme icons have poor contrast in Appimage as compared to .deb

### ISSUE THREAD

**Issue by siddhantladdha** [xournalpp/xournalpp#3190]
Affects versions :

    OS: Pop OS 20.04 LTS (Based on Ubuntu 20.04 LTS) Linux
    Desktop environment: Gnome X11
    Version of Xournal++: 1.1.0+dev. Git commit: 07f2aa68. (Nightly release)
    Build date: June 25, 2021.
    Version of libgtk: 3.22.30
    Installation method: AppImage

Describe the bug
Following dark mode icons have poor contrast in the dark theme, but have great contrast in the non-dark theme. The behavior is flipped when compared to the same nightly version installed in `.deb` format.

    Eraser
    Text
    Add/Edit Tex
    Hand
    Presentation Mode

To Reproduce
1. Install the recent nightly builds (version mentioned above) via both AppImage and `.deb` version.
2. Navigate to `Edit -> Preferences -> View -> Select Dark Theme (requires restart)`.
3. Restart Xournal++.
4. Notice the above-mentioned icons.

Expected behavior
User should be able to see all the icons clearly when using a system dark theme. The correct behavior can be obtained in the `.deb` version of the nightly build (built with libgtk 3.24.20). [This](https://github.com/xournalpp/xournalpp/issues/3179#issuecomment-867666255) might be the possible reason.

Reference [this video](https://upload.disroot.org/r/F8kF8R4B#Cv4+O/1/bKZV63x/3c4EfVk9ZtqL4KyvJEH5CsJUfVg=) to observe the flipped behavior in App image.

Screenshots.

- Dark Theme disabled - AppImage
![Dark Theme disabled - AppImage](https://user-images.githubusercontent.com/25705822/123505231-8aa01300-d67b-11eb-95e4-2c6a16db4bb3.png)

- Dark Theme enabled - AppImage
![Dark Theme enabled - AppImage ](https://user-images.githubusercontent.com/25705822/123505234-8bd14000-d67b-11eb-92c0-7ebacf6b616c.png)

- Dark Theme disabled - .deb
![Dark Theme enabled - AppImage](https://user-images.githubusercontent.com/25705822/123505447-c687a800-d67c-11eb-8248-20bb0855aeb3.png)

- Dark Theme enabled - .deb
![Dark Theme enabled - AppImage](https://user-images.githubusercontent.com/25705822/123505458-d4d5c400-d67c-11eb-92ce-8b36cfb0fcb3.png)

See #3179 for additional details.

**Comment by myrkgard** [comment]
![Screenshot from 2021-06-26 12-59-27](https://user-images.githubusercontent.com/75583910/123510970-da340e00-d67e-11eb-9c20-856c87de7490.png)

It's even worse on Ubuntu 21.04 when installed via Ubuntu's snap store ("Ubuntu Software") and using the system's dark theme.

**Comment by rolandlo** [comment]
@myrkgard On the snap store you don't get version 1.1.0+dev.

**Comment by myrkgard** [comment]
@rolandlo Aye, sorry!

**Comment by rolandlo** [comment]
When the next AppImage is built (next nightly build), this issue should be fixed. 
1) The AppImage will be built on Ubuntu 20.04 instead of Ubuntu 18.04 and there is no flipped behavior anymore.
2) Whether the user uses dark mode or not is determined by the color-scheme gsetting instead of the gtk-theme gsetting
https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/pull/49
