### ISSUE TITLE
Cannot see the pen/eraser/highlighter tool when Flatpak version.

### ISSUE THREAD

**Issue by siddhantladdha** [xournalpp/xournalpp#3194]
**Affects versions :**
 - OS: Pop OS 20.04 LTS (Linux)
 - Desktop environment: Gnome X11
 - Which version of libgtk do you use: libgtk: 3.24.21
 - Version of Xournal++: 1.0.20 (commit 09ec499)
 - Installation method: Flatpak

**Describe the bug**
Cannot see the pen/eraser/highlighter tool when using the respective tool. This bug is exclusive to Flatpak. 

**To Reproduce**
1. Download Flatpak and `.deb`/Appimage.
2. Run the `.deb`/Appimage version.
3. Go to `Edit -> Preferences -> View -> Cursor`. Select `Big Cursor For Pen`.
4. Use the Pen, You will be able to see a Big Cursor for pen, Block eraser for Eraser and normal mouse cursor when using highlighter. **You will be able to see cursor when mouse is not clicked and tool when mouse is clicked (i.e. when writing/erasing/highlighting).
5. Run the flatpak version using `flatpak run com.github.xournalpp.xournalpp`
6. Go to `Edit -> Preferences -> View -> Cursor`. Select `Big Cursor For Pen`.
4. Use the Pen. Normal mouse cursor can't be seen when not using any tool. Not able to see a Big Cursor for pen, Block eraser for Eraser and normal mouse cursor when using highlighter. Basically not acting as expected in step 4.

**Expected behavior**
Flatpak version should work as mentioned in Step 4.

**Screenshots of Problem**
- Cursor/Tool Not seen in Flatpak (Bug)
![cursor_notseen](https://user-images.githubusercontent.com/25705822/123722862-cd91fe80-d8a6-11eb-8dd6-381b503b5112.gif)
- Cursor/Tool Seen in `.deb` (Expected Behavior)
![cursor_seen](https://user-images.githubusercontent.com/25705822/123722901-e13d6500-d8a6-11eb-9b7e-fed1ede2dd3e.gif)

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Please try running the flatpak version as suggested in [this issue](https://github.com/xournalpp/xournalpp/issues/2375#issuecomment-781482931)

**Comment by siddhantladdha** [comment]
Using the command given and substituting with 3.38 works!

Sent from ProtonMail mobile

-------- Original Message --------
