### ISSUE TITLE
"Select Object" tool having trouble selecting things.

### ISSUE THREAD

**Issue by MckinleyX** [xournalpp/xournalpp#3195]
Hi!
I've noticed that the "select object" tool often has trouble selecting objects when said objects intersect.
Attached is more or less the minimum setup required for me to reproduce this issue.
![screenshot1624941894](https://user-images.githubusercontent.com/32435060/123738790-ff9a6500-d894-11eb-8aaf-1c37823a6f00.jpg)
In the specific configuration above I seem to be unable to consistently select the circle unless I select it from the 11-12-o-clock region.
Adding the following line seems to make that break as well.
![screenshot1624942791](https://user-images.githubusercontent.com/32435060/123739848-d975c480-d896-11eb-96cb-26abbce0dc9a.jpg)
I'm also finding it difficult to select the upper right line of the triangle above approximately its midpoint.
(I doubt this is OS-dependent, but I'm using xournalpp 1.0.20-hotfix on Linux)

**Comment by Technius** [comment]
Duplicate of #2477. This is no longer be an issue in the nightly 1.1.0+dev version (alternatively, you can wait for the full 1.1.0 release, which we will be releasing shortly as we have addressed almost all of the blockers).
