### ISSUE TITLE
Xournal icon disappears in windows taskbar when pinned

### ISSUE THREAD

**Issue by atutal** [xournalpp/xournalpp#3199]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows
 - libgtk: 3.24.23
 - Version of Xournal++: 1.0.20
 - Installation method: Execute xournalpp-1.0.20-windows.exe from the zip file (Stable) 
 here https://xournalpp.github.io/installation/windows/

**Describe the bug**
When you pin Xournal++ to the windows taskbar, the icon changes unexpectedly. 

**To Reproduce**
1. Start Xournal++
2. Right-click Xournal++ on the windows taskbar on the bottom
3. Click "Pin to taskbar"

**Expected behavior**
Xournal++ icon should not change.

**Screenshots of Problem**
![xournalIssue](https://user-images.githubusercontent.com/72972822/124032193-8ae03b80-d9f8-11eb-8df6-6b060e124cbb.png)

**Additional context**
Not extremely important obviously.

**Comment by rolandlo** [comment]
That should not happen in version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) any more.

**Comment by atutal** [comment]
My bad. Works with dev version.
