### ISSUE TITLE
"Previously selected language not available anymore" all the time with Arabic after simplifying the names

### ISSUE THREAD

**Issue by noureddin** [xournalpp/xournalpp#3200]
**Affects versions:**
 - OS: Linux, Ubuntu 20.04.
 - Desktop environment: both KDE5 and Unity (Gnome3).
 - libgtk: 3.24.20.
 - Version of Xournal++: 1.1.0+dev (the latest commit "New Crowdin updates and simplification of names" of 2021.06.28).
 - Installation method: both the official PPA, and by manually building from the repo.

**Describe the bug:**

After the recent simplification of language names, when the Language is set to Arabic, this happens:

Whenever I open Preferences, it complains that "Previously selected language not available anymore!", and if I don't select Arabic again, it is reset to "System Default" upon restarting.

But if I use Xournal++ without ever opening Prefrences, no issues occur at all (and Arabic remains after restarting).

Side note: "System Default" uses the English strings in KDE5 regardless of KDE's language, but the Arabic strings in Unity if the DE's primary language is set to Arabic.

It may be because the name of the language is still `ar_SA` somewhere. I thought it is the 9th line in [`l10n_master/po/ar.po`](https://raw.githubusercontent.com/xournalpp/xournalpp/l10n_master/po/ar.po) (as it still is `"Language: ar_SA\n"`), but changing that and building doesn't solve the problem.

**To Reproduce:**
1. Install the latest version from the official PPA.
2. Launch Xournal++, Edit > Preferences > Language, and choose "ar", then "OK".
3. Restart Xournal++. (The language now is Arabic.)
4. Select the second menu («تحرير», Edit) > the last item («التفضيلات», Preferences).
5. It complains that «اللغة المختارة سابقا لم تعد متاحة», which is "Previously selected language not available anymore".
6. Click «نعم» (OK) to dismiss the message. Now it opens the Preferences window.
7. Click «نعم» (OK) to close the Preferences window, and restart Xournal++.
8. The language is now set to System Default (which likely uses the English strings).

An interesting observation: if you close the Preferences window with ESC or "Cancel" («ألغِ») instead of "OK" («نعم»), it doesn't change the language.

**Comment by rolandlo** [comment]
When you build from source, you should set the `CMAKE_INSTALLATION_PREFIX` to `/usr`. Default is `/usr/local` and there is probably no file in `/usr/local/share/locale/ar/LC_MESSAGES/xournalpp.mo`, which gives the error.
So please compile using 
```
cmake -DCMAKE_INSTALL_PREFIX = /usr ..
cmake --build .
```
Also check, in which of the following directories you have the file `xournalpp.mo`:
- `/usr/local/share/locale/ar_SA/LC_MESSAGES/xournalpp.mo` 
- `/usr/local/share/locale/ar/LC_MESSAGES/xournalpp.mo` 
- `/usr/share/locale/ar_SA/LC_MESSAGES/xournalpp.mo` 
- `/usr/share/locale/ar/LC_MESSAGES/xournalpp.mo` 
If the latest PPA version is correctly installed it should be only in the last directory.

**Comment by rolandlo** [comment]
One more thing, when starting `xournalpp` from the terminal, you should see a message like
`TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /usr/share/locale, chosen directory = /usr/share/locale`
Can you report please, what directory is chosen for you?

**Comment by noureddin** [comment]
> When you build from source, you should set the CMAKE_INSTALLATION_PREFIX to /usr. Default is /usr/local and there is probably no file in /usr/local/share/locale/ar/LC_MESSAGES/xournalpp.mo, which gives the error.
So please compile using...

I will try now. But I just want to mention that the all the strings appear normally in the UI.

> Also check, in which of the following directories you have the file xournalpp.mo...

With the PPA, only the last one (`/usr/share/locale/ar/LC_MESSAGES/xournalpp.mo`) exists, but...

```
$ strings /usr/share/locale/ar/LC_MESSAGES/xournalpp.mo | grep SA
Language: ar_SA
```

I have no `/usr/local/share/locale` or any `ar_SA` locale.

.

>  One more thing, when starting `xournalpp` from the terminal, you should see a message like ... Can you report please, what directory is chosen for you?

For the PPA, the chosen directory is `/usr/share/locale`:
```
TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /usr/share/locale, chosen directory = /usr/share/locale
```

**Comment by noureddin** [comment]
> So please compile using
>
>      cmake -DCMAKE_INSTALL_PREFIX = /usr ..
>      cmake --build .

I just checked, and I already have `-DCMAKE_INSTALL_PREFIX=/usr`.

I'm currently using this script to build Xournal++ on Ubuntu (primarily suggested by LittleHuba in the Matrix room):

```bash
# clean
sudo apt-get autoremove --purge xournalpp -y
sudo snap remove xournalpp
rm -rf xournalpp/
# get the repo
git clone https://github.com/xournalpp/xournalpp/ --depth 1 --branch master
cd xournalpp/
# get the latest translation
wget https://raw.githubusercontent.com/xournalpp/xournalpp/l10n_master/po/ar.po -O po/ar.po
# ...and fix its name
sed 's/"Language: ar_SA\\n"/"Language: ar\\n"/' po/ar.po -i
# build
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_CPPUNIT=ON -DDEBUG_COMPILE=ON -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_GENERATOR="DEB"
cmake --build . --target pot
cmake --build . --target translations
cmake --build . --target package
# install
sudo dpkg --install packages/xournalpp-1.1.0+dev-Ubuntu-focal-x86_64.deb
```

**Comment by rolandlo** [comment]
I have now checked all 32 languages, every time setting the next language in the preferences and restarting Xournal++. The only language, which results in this "Previously selected language not available anymore" complaint, is Arabic. Even languages like Chinese, Russian etc. worked fine.
I really don't think the the language name shortening introduced the problem (all other languages work just fine). There must be some problem in the `ar.po` file. Let's check if Crowdin has highlighted some issues.

**Comment by noureddin** [comment]
Thank you for taking the time and effort to check all 32 languages!

All the QA issues highlighted by Crowdin are:
- "Tags mismatch" (for using `<b>` instead of all caps in two strings),
- "Special characters mismatch" (extra `(`, for clarifying some things), and
- many false positive "Spelling" issues.

I don't see anything fatal.

.

I can assure you that the latest commit introduced this issue, not the translation. I've built the `HEAD^1` commit with the latest translation, and I couldn't see any issues (except for the first time only, because `ar` is, for real this time, not available anymore). I built it with the following script:

```bash
# clean
sudo apt-get autoremove --purge xournalpp -y
sudo snap remove xournalpp
rm -rf xournalpp/
# get the repo, with the latest two commits
git clone https://github.com/xournalpp/xournalpp/ --depth 2 --branch master
cd xournalpp/
git checkout HEAD^  # <= ADDED!
# get the latest translation (without fixing its name!)
wget https://raw.githubusercontent.com/xournalpp/xournalpp/l10n_master/po/ar.po -O po/ar_SA.po
# build
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON  \
         -DENABLE_CPPUNIT=ON -DDEBUG_COMPILE=ON  \
         -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_GENERATOR="DEB"
cmake --build . --target pot
cmake --build . --target translations
cmake --build . --target package
# install
sudo dpkg --install packages/xournalpp-1.1.0+dev-Ubuntu-focal-x86_64.deb
```

**Comment by rolandlo** [comment]
I think I have found the problem. It is related to the facts that
1) Arabic (`"ar"`) is the first language in the list (except of System Default)
2) The string comparison between "ar" and the arabic name for System default considers "ar" to be smaller. (In most languages, it would be the opposite, e.g. "de" is considered larger than "Systemstandard"

The relevant lines in the code are these:
https://github.com/xournalpp/xournalpp/blob/5e7cb07d4118e591428af563d3793c1c0569595b/src/gui/dialog/LanguageConfigGui.cpp#L64-L69

When you set language to Arabic, `preferred` will take the value `"ar"` and `prefPos` will get the value of the arabic string for "System Default" (and not "ar" like it should) because of facts 1 and 2. That's why you see the error message.

A quick fix would be to remove the Arabic translation of "System Default". A proper fix requires changing the code segment above.

**Comment by noureddin** [comment]
Yes, removing the translation for "System Default" solves it! :tada: 

And yes, the Arabic string is sorted after `ar`, because all Arabic character are after the ASCII character.

I still don't know how or why this code caused this issue in this commit specifically.

Thank your for your time and effort. :smiley:

**Comment by rolandlo** [comment]
> I still don't know how or why this code caused this issue in this commit specifically.

The reason is, that the commit added the Arabic translation for "System default". It had nothing to do with simplifying the names.
Since we are about to release version 1.1.0 (in order not to accidentally break something else), I suggest to make the quick fix for now, merging the updated Arabic translations (which already go without "System default" translation, as I see). We can add a proper fix later, before the next release or before the next time Crowdin translations are merged. Does that sound fine for you?

**Comment by noureddin** [comment]
I'm OK with that. And I've already removed the Arabic translation for "System Default" from Crowdin.

What I don't understand is why the previous commit with the same exact translation file does not have this issue, if it's triggered by the translation?

**Comment by noureddin** [comment]
I can see that the last commit affects only the translation files. :sweat_smile:
No problem. I'll try if I can provide a proper fix for this issue.
Thank you for time again. :smiley:

**Comment by noureddin** [comment]
Thank you. I restored the translation for "System Default" (and translated the new strings that were added in the mean time).
