### ISSUE TITLE
Text input doesn't work after changing initial settings

### ISSUE THREAD

**Issue by ethpi** [xournalpp/xournalpp#3203]
**Affects versions :**
 - OS: Ubuntu 20.04.2 LTS
 - Desktop environment: Plasma/KDE shipped with Kubuntu 20.04.2 
 - libgtk:  3.24.20
 - Version of Xournal++:  1.1.0+dev from 1st of july 2021
 - Installation method: PPA

**Describe the bug**
Text input with keyboard doesn't work after changing the inital settings. Its possibe to activate  a textfiled, but no pressed key will be displayed.

**To Reproduce**
1. Remove settings: rm ~/.config/xournalpp/settings.xml
2. Start xournalpp and add to the initial document some text with your keyboard. Everthing works fine.
3. Change any setting, e.g. disable autosave.
4. Save the settings.
5. Try to add some more text in another textfield with your keyboard: No sign will be shown.

**Expected behavior**
Textfield stays empty although pressing some keys on the keyboard.

**Additional context**
Insertings text from the clipboard still works.
If you delete the changed settings.xml file and restart xournalpp you will be able to insert text in textfields agan.

**Comment by rolandlo** [comment]
Could you please zip the settings.xml file that works and the one that doesn't work, or report the `diff` between the two files?
```
diff settings_new.xml settings_old.xml
```
Most likely it's something with the input devices that is wrongly recognized.

**Comment by rolandlo** [comment]
One more question: Is your keyboard part of a keyboard+mouse combo?

**Comment by ethpi** [comment]
`diff settings_initial_textinput_works.xml settings_disabled_autosave_textinput_fails.xml`

```
51c51
<   <property name="autosaveEnabled" value="true"/>
---
>   <property name="autosaveEnabled" value="false"/>
66,68c66,68
<   <property name="selectionBorderColor" value="16711680"/>
<   <property name="backgroundColor" value="14473941"/>
<   <property name="selectionMarkerColor" value="7512015"/>
---
>   <property name="selectionBorderColor" value="4294901760"/>
>   <property name="backgroundColor" value="4292664021"/>
>   <property name="selectionMarkerColor" value="4285702095"/>
114c114
<       <attribute name="color" type="hex" value="000000"/>
---
>       <attribute name="color" type="hex" value="ff000000"/>
142a143,146
>     <data name="HID 046a:0023">
>       <attribute name="deviceClass" type="int" value="1"/>
>       <attribute name="deviceSource" type="int" value="0"/>
>     </data>
146a151,166
>     <data name="Wacom Intuos BT M Pad pad">
>       <attribute name="deviceClass" type="int" value="0"/>
>       <attribute name="deviceSource" type="int" value="8"/>
>     </data>
>     <data name="Wacom Intuos BT M Pen cursor">
>       <attribute name="deviceClass" type="int" value="0"/>
>       <attribute name="deviceSource" type="int" value="3"/>
>     </data>
>     <data name="Wacom Intuos BT M Pen eraser">
>       <attribute name="deviceClass" type="int" value="3"/>
>       <attribute name="deviceSource" type="int" value="2"/>
>     </data>
>     <data name="Wacom Intuos BT M Pen stylus">
>       <attribute name="deviceClass" type="int" value="2"/>
>       <attribute name="deviceSource" type="int" value="1"/>
>     </data>
214c234,240
<   <data name="touch"/>
---
>   <data name="touch">
>     <attribute name="cmdDisable" type="string" value=""/>
>     <attribute name="cmdEnable" type="string" value=""/>
>     <attribute name="disableTouch" type="boolean" value="false"/>
>     <attribute name="method" type="string" value="auto"/>
>     <attribute name="timeout" type="int" value="1000"/>
>   </data>
```
> One more question: Is your keyboard part of a keyboard+mouse combo?

No I don't use a keyboard/mouse combo. I use an old "normal" german Cherry keyboard and a seperate Logitech mouse. Both connected via USB.

I added the suffix "txt" to the settings-files. XML-files aren't allowed.

[settings_initial_textinput_works.xml.txt](https://github.com/xournalpp/xournalpp/files/6754537/settings_initial_textinput_works.xml.txt)
[settings_disabled_autosave_textinput_fails.xml.txt](https://github.com/xournalpp/xournalpp/files/6754539/settings_disabled_autosave_textinput_fails.xml.txt)

**Comment by rolandlo** [comment]
Frankly, I don't see the problem from the settings file. You could try removing device by device from the failing settings file and see what makes the difference.

**Comment by ethpi** [comment]
Thanks for this hint. When I delete 

```
<data name="HID 046a:0023">
       <attribute name="deviceClass" type="int" value="1"/>
       <attribute name="deviceSource" type="int" value="0"/>
</data>
```
in my settings file, textinput with my keyboard is possible again. BTW, `046a:0023` is the ID of my keybord (shown by `lsusb | grep 0046:0023`).
But every time I change any settings, the deleted section will be added to my settingsfile once more and the keyboard input fails again. 

Because I don't change my settings frequently, this workaround is ok for me. But is there a way to avoid this fail?

**Comment by rolandlo** [comment]
Ok, so the problem is, that `HID 046a:0023` is your keyboard and GTK recognizes it as your mouse. Does it help to either turn it into a `Mouse+Keyboard combo` or to deactivate it in the input system panel of menu `Edit > Preferences`?

**Comment by ethpi** [comment]
Yes, that's it. If I select `Mouse+Keyboard combo` my keyboard works properly.

Many thanks.
