### ISSUE TITLE
Surface book  2, windows 10, surface pen not well recognized (treated as mouse)

### ISSUE THREAD

**Issue by deb75** [xournalpp/xournalpp#3205]
**Affects versions :**
 - OS: windows 10
 - Version of Xournal++ 1.0.20

**Describe the bug**

Xournalpp detects two inputs : 
- wacom tablet with pen
- system aggregated pointer (mouse)

I attached the first one to pen, but I cannot write on the surface book 2 touchscreen
I can only write with the pen if I attach the second to the pen. But then, the pen is treated
as a mouse, no pressure sensitivity, the touchpad/touchscreen also draws, which is annoying.

Did anyone got the surface pen to work as expected with xournalpp on a surface book 2 ?
If yes, may you tell me how you configured it ?

It should work, another app `styluslab/write` is working flawlessly on windows 10 in the same time.

Regards

**Comment by rolandlo** [comment]
Please compare #3176

**Comment by deb75** [comment]
It is not clear whether it is related or not.

The point is that I have an external USB wacom stylus tablet, which is well recognized and whose pen is fully functional under xournalpp.

The trouble appears when I use the built-in pen and tablet of the surface book 2, which is known to rely on IPTS firmware.

Again, I do not think it should exceptionaly difficult to make the surface book 2 firmware work with xournalpp as other free/open source projects manage to.

Regards

**Comment by rolandlo** [comment]
You may refer to other free/open source projects that don't use GTK+ 3. Projects like GIMP and Inkscape have struggled with the same issues. As I read now, the patched GTK+ 3 is [ready to be merged](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1563#note_1196906) and should be part of the next GTK+ 3 release.

**Comment by rolandlo** [comment]
The patched GTK+ 3 has now been merged. You can copy the `libgdk-3-0.dll` and `libgtk-3-0.dll` into your [Xournal++ 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) installation as described [here](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907)

**Comment by deb75** [comment]
Indeed,

I can now see the pen, the erasor. They all work well now.

Regards

**Comment by rolandlo** [comment]
The issue should be fixed in [Version 1.1.0-hotfix+1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Please report if you experience otherwise.
