### ISSUE TITLE
My digitizing table does'n work with Xournall++

### ISSUE THREAD

**Issue by caiosilva1993** [xournalpp/xournalpp#3213]
I installed version 1.0.20 for Windows and I have a digitizing table Huion HS64  but Xournall++ doesn't recognize to write, I can only move the mouse. In other applications and the old Xournall I can use it perfectly. Any solution?
![Table](https://user-images.githubusercontent.com/81496717/124832584-3df9e900-df53-11eb-964a-f4597f6b9181.png)

**Comment by rolandlo** [comment]
Please try installing version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and follow [these instructions](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907) to replace two libraries with patched versions, which work better for input handling.

**Comment by rolandlo** [comment]
Reported as working with the above instructions. I am closing the issue therefore.
