### ISSUE TITLE
French translation of a box

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#3216]
OS : Windows 10
Version of Xournal :  1.1.0+dev (Jul 06 2021)

I use the French translation of Xournal.
When I close Xournal and I have not saved the document yet, a box opens in which there are 2 identical buttons, which is not normal.
![Box](https://user-images.githubusercontent.com/66552896/125065415-11a8ae80-e0b2-11eb-9572-1ba8e11da0b5.jpg)

**Comment by rolandlo** [comment]
Duplicate of #2605.
