### ISSUE TITLE
Stylus button functionality - alternative tool is disabled on screen contact

### ISSUE THREAD

**Issue by jeanpierrevanzyl** [xournalpp/xournalpp#3225]
**Affects versions :**
 - OS: Linux: Ubuntu 20.04
 - Version of Xournal++: 1.0.20-9-gea457c9fd1

**Describe the bug**
When using the buttons on the stylus, i.e. the eraser function, the primary button works as expected.
However, using any tool on the secondary button creates the bug that the selected too can only be used when hovering the stylus. The previously selected tool is automatically used again as soon as the stylus makes contact with the screen.

**To Reproduce**
1. Enter settings, go to stylus settings
2. Choose an alternative tool (not pen) for Button 1
3. Exit settings and select pen
4. Hover over screen and hold button 1, alternative tool should function
5. Still holding button 1, contact the stylus to the screen, the pen should now be in use

**Expected behavior**
It is expected that the alternative tool should remain in operation when the stylus makes contact with the screen, as is seen with the eraser function.

**Comment by rolandlo** [comment]
Can you please check out version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and report if that already solves the problem. Other check whether enabling or disabling the "Merge button events with tip events" checkbox in the input system panel of menu `Edit > Preferences` makes a difference.

**Comment by jeanpierrevanzyl** [comment]
Hi @rolandlo just setting "Merge button events with tip events" did not resolve the issue, however updating to 1.1.0+dev did resolve the issue. Even without the "Merge button events with tip events" setting.
Thank you for your help and for the great product.
