### ISSUE TITLE
100% CPU on one core?

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#323]
I have yet to investigate the nature of the issue.
Do any of you experience 1 core stuck at 100% CPU when running xournalpp, or is it just me?

**Comment by andreasb242** [comment]
Does this always happen or only if you use some specific PDFs as background? There is already a ticket, that PDFs with Booksmarks produces such an issue.

**Comment by morrolinux** [comment]
Not sure it's quite the same as this happens on application launch with a new empty project

**Comment by andreasb242** [comment]
Can you may debug it and pause and check which thread it is?

**Comment by morrolinux** [comment]
I haven't managed to debug it yet, but it doesn't show up if settings.xml is not present on application startup. 'll keep you updated on this

**Comment by andreasb242** [comment]
Maybe linked to #184

**Comment by andreasb242** [comment]
I could reproduce it. So I probably can fix it ;-)

**Comment by andreasb242** [comment]
Issue found: SidebarPreviewBase::scrollToPreview is looping... I have to check whats the problem...

**Comment by morrolinux** [comment]
@andreasb242 just out of curiosity: how did you debug this? I tried with vscode but seem not to be able to attach to a specific thread
