### ISSUE TITLE
Show cursors as a black dot regardless of input colour

### ISSUE THREAD

**Issue by tomaz-suller** [xournalpp/xournalpp#3238]
**Is your feature request related to a problem? Please describe.**
In the new input system (which I enabled to prevent crashes as per other issues posted here, can't find which), the cursor appears as a small dot that is difficult to see, especially when you for example select light colours on the light background. It gets hard to write that way since you can't easily follow where the cursor is going.

**Describe the solution you'd like**
A toggle to let the cursor dot remain black regardless of the selected colour for drawing.

**Describe alternatives you've considered**
There are cursor highlight features (in `Edit > Preferences > View > Cursor`), though I find them rather obtrusive. Another possibility other than the one I described would be to add a setting (maybe something like a slider?) for the user to increase the dot size.

**Comment by rolandlo** [comment]
Have you tried [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? There are more options there.

**Comment by tomaz-suller** [comment]
Yeah, the options with the latest release address this issue already, thanks!
