### ISSUE TITLE
Double clicking a .xopp opens a debug windows

### ISSUE THREAD

**Issue by slemal** [xournalpp/xournalpp#3240]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows 10 Home Edition
 - Version of libgtk 3.24.23
 - Version of Xournal++: 1.0.20, commit 09ec4999
 - Installation method: .exe from [this](https://xournalpp.github.io/installation/windows/) page

**Describe the bug**
Clicking a .xopp file opens an error window (see screenshot).
Clicking "OK" opens xournalpp as expected.

**To Reproduce**
1. Install xournal++ from the .exe.
2. Create a dummy .xopp.
3. Double click it.

**Expected behavior**
Double clicking a .xopp file should open it without opening an debug window.

**Screenshots of Problem**
<img width="171" alt="Capture" src="https://user-images.githubusercontent.com/50544150/126050254-f63ebfab-48c8-48f0-aa0f-58f529bd3937.PNG">

**Comment by rolandlo** [comment]
That doesn't happen in version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) any more.
