### ISSUE TITLE
Pressure sensitivity not working on 1.1.0

### ISSUE THREAD

**Issue by gallrt** [xournalpp/xournalpp#3248]
**Affects versions :**
 - OS:    Windows 10
 - Which version of libgtk do you use:    3.24.29
 - Version of Xournal++:    1.1.0
 - Installation method:    via the windows download on github releases, and then the EXE-Installer

**Describe the bug**
The Xournal++ does not react on different pressure on my Wacom Tablet, as it did on the earlier version 1.0.19

**To Reproduce**
Use a Wacom Tablet
Write/Draw on it.....

**Expected behavior**
The line width varied on the earlier version.
So it was possible to create a small and a thick line, or one that starts as small and ends as a thick line.

**Additional context**
I did the update to 1.1.0 as I need the PDF-Output after annotating student exercises.

**Comment by rolandlo** [comment]
Please follow the [advice](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-876286601) mentioned in the releases notes. We will have to wait for libgtk 3.24.30 until this works out of the box.

**Comment by gallrt** [comment]
Thanks for the hint.
Unfortunately, this does not help to recover the pressure sensitivity

**Comment by rolandlo** [comment]
Maybe it is a wrong setting then? Can you post a screenshot of your `input system` settings in menu `Edit > Preferences`? Also check that pressure sensitivity is enabled in the Stylus panel of the preferences.

**Comment by gallrt** [comment]
Here the screenshots of the `input system` and of the `pen settings`.
I hope that German text is okay.

![Srceenshot001](https://user-images.githubusercontent.com/49808209/126145215-0ee4b6da-1bf6-4135-913d-09a5bc75611e.jpg)
![Srceenshot002](https://user-images.githubusercontent.com/49808209/126145234-9ac60233-0fca-4465-acbf-55b3a3152833.jpg)

**Comment by gallrt** [comment]
I finally got it working by playing with the WACOM settings.
There, it is possible to specify seperate settings for some programs.
If doing this for Xournal++ (again), then there is pressure sensitivity in the notetaking.
I did it the last time for the earlier version.
But obviously the settings don't survive when updating Xournal++.

Thanks for the help!!!
