### ISSUE TITLE
Ability to switch between a GUI and text filepath in the file explorer window

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3252]
**Is your feature request related to a problem? Please describe.**
When you go to save a file, you're presented with a window that looks something along the lines of the following:
![test](https://user-images.githubusercontent.com/7829231/126425723-ebd3fdee-ef6a-4327-a7e9-73943466a001.png). To look for the location that you want to save the file, you would have to manually click through the GUI items and buttons which can be really slow for some long filepaths. In Nautilus, you have the option to turn this bar
![image](https://user-images.githubusercontent.com/7829231/126425838-d0d181f4-de51-435f-bb99-daa160a4f694.png)
into a file URL bar by hitting `<CTRL> + L`; however, this functionality does not seem to exist in xournalpp.

A sort of workaround that xournalpp has is that you can type in a complete filepath manually in the "Name" section with the file at the end; however, this can be quite arduous for long filepaths and it would be much better if there was a way to switch between the gui filepath and a text filepath.

**Describe the solution you'd like**
I would like for there to be a way to switch between a text URL bar and a GUI URL bar for locating file locations, similar to that of nautilus (Personally I'm not super fond of only having the key combo as the option to switch, and would also like a button to allow me to switch, but that is extra.)

**Describe alternatives you've considered**
Surprisingly enough, windows actually seems to have gotten that somewhat right with the file explorer by allowing you to seamlessly switch between the file GUI icons and a text based view.

**Additional context**
Something interesting that I have noticed is that if you do hit the `<CTRL> + L` key-combo, instead of switching the GUI filepath to a text one, it instead focuses to the file "Name" input field.

**Comment by personalizedrefrigerator** [comment]
At least for me (libgtk 3.24.25 on PoP OS 21.04), I can enter **partial** paths into the `name` box, press `Enter`, and it updates the GUI:

https://user-images.githubusercontent.com/46334387/126438952-abb3f637-6597-4eec-bf4d-f60f6402b8dc.mp4

I agree that this UI is currently confusing! `xournal++` currently uses `GtkFileChooser`. [Consider reporting this bug on their GitLab repository!](https://gitlab.gnome.org/GNOME/gtk/-/issues?scope=all&state=opened&search=file+chooser) It is possible, however, that this has already been fixed. `Xournal++` uses `gtk3` and `gtk4` has been released...

**Comment by Technius** [comment]
This seems to be a GTK/gnome problem that we can't fix. For example, gedit has the same problem.
