### ISSUE TITLE
Graph line color changes according to background color

### ISSUE THREAD

**Issue by UnknownPerson-0x00** [xournalpp/xournalpp#3256]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: Wayland
 - libgtk: 3.24.25
 - Version of Xournal++: 1.1.0
 - Installation method: PPA

**Describe the bug**
I have been using the method provided by #https://github.com/xournalpp/xournalpp/issues/2137 to change the configuration of the graph. However on the new update to Xournalpp 1.1.0, the color of the graph's lines turn grey anytime I use a dark page background color. I expect the color of the graph's lines to be the color I specified regardless of the background color of the page.

**To Reproduce**

1.
edit /usr/share/xournalpp/ui/pagetemplates.ini by adding the following lines to the end of the file:
[graphRed]
name=Red Graph
format=graph
config=m1=0,rm=1,f1=0xFF0000

2.
open xournalpp

3.
select Journal->Paper Color and select white

4.
observe the graph has red lines

5.
select Journal->Paper Color and select black

6.
observe the graph has grey lines

**Expected behavior**
I expect the graph to have the same color lines regardless of the background color. More to the point, I expect the graph to always have the config specified in the /usr/share/xournalpp/ui/pagetemplates.ini file. 

**Screenshots of Problem**
Light background with Red Graph selected
![Screenshot from 2021-07-22 18-53-39](https://user-images.githubusercontent.com/58747994/126719030-f0f2b169-0f70-4c88-a52d-4316babb0409.png)

Dark background with Red Graph selected
![Screenshot from 2021-07-22 18-54-55](https://user-images.githubusercontent.com/58747994/126719081-0bb8247e-6ed3-456b-b85c-71a03c7f8c50.png)

**Comment by rolandlo** [comment]
> [graphRed]
> name=Red Graph
> format=graph
> config=m1=0,rm=1,f1=0xFF0000

I have updated the explanations in #2137 The trick is to add `af1=0xFF0000` to your `config`.
