### ISSUE TITLE
Undo/redo does not work properly with layer renaming

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#3257]
**Affects versions :** 1.1.0
 - OS: Ubuntu 21.04 (probably doesn't matter)
 - (Linux only) Desktop environment: Wayland, X11 (probably doesn't matter)
 - libgtk: 3.24.25 (probably doesn't matter)
 - Installation method: PPA (probably doesn't matter)

**Describe the bug**
After renaming multiple layers and renaming a layer, undoing the renaming does not only rename the renamed layer, but also the currently selected layer

**To Reproduce**
1. Open a new document
2. Create multiple (at least 2) layers via the dropdown menu in the toolbar (and use the "layer preview" in the sidebar to see their names)
3. Rename one of the layers via CTRL+R
4. Select a different layer in the layer preview
5. Undo via CTRL+Z
6. Observe that not only the renamed layer got its original name, but also the selected layer gets the original name of the renamed layer

**Expected behavior**
The undo operation should only change the name of the layer that was renamed. Similarly with redo.

**Additional context**
I have already mentioned that issue in #3204.

**Comment by ja-he** [comment]
The main issue causing this is that there are these lines
```cpp
    control->getLayerController()->setCurrentLayerName(layer->getName());
```
in both the undo and redo action implementation (after renaming the layer name properly!)

However even fixing that, it's not immediately obvious that it actually works, because the sidebar doesnt show the updated name when un-/redoing. (Opening the rename dialog box shows the correct name though)

**Comment by ja-he** [comment]
> However even fixing that, it's not immediately obvious that it actually works, because the sidebar doesnt show the updated name when un-/redoing. (Opening the rename dialog box shows the correct name though

In #3204 I called `LayerController::fireRebuildLayerMenu()` to force this type of update to be shown, but I had to make the undo action a friend of the `LayerController` and am not sure if this was the "proper" way of doing it.
