### ISSUE TITLE
Configuring Microsoft Pen as stylus

### ISSUE THREAD

**Issue by ckarren** [xournalpp/xournalpp#3264]
**Affects versions :**
 - OS: Windows 10 64bit
 - Version of libgtk: 3.24.29
 - Version of Xournal++: 1.1.0

 - Installation method: official release

**Describe the bug**
On Microsoft Surface Go 2 with Microsoft Surface Pen, only 1 input device shows up so I can't specify the Microsoft Pen as a pen and can't configure it as a stylus. 

**Expected behavior**
Configure Microsoft Pen as a stylus so button and eraser work as a button and an eraser.

**Comment by rolandlo** [comment]
Please upgrade to [version 1.1.0-hotfix.1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1)

**Comment by ckarren** [comment]
This did the trick! Thank you so much!
