### ISSUE TITLE
Text tool stop working after setting preferences

### ISSUE THREAD

**Issue by renatocan** [xournalpp/xournalpp#3277]
**Affects versions :**
 - OS: Arch Linux kernel 5.13.4-arch1-1
 - (Linux only) Desktop environment: Xfce 4.16
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0 9d1277de
 - Installation method: Arch Linux local repo

**Describe the bug**
After opening the preferences window, the text tool stops working (does not recognize key presses).

**To Reproduce**
1. Delete the ~/.config/xournalpp directory to reset the configs
2. Start Xournal++ - the text tool works
3. Enter Edit->Preferences
4. Click ok without changing anything
5. Check the text tool. In my system, it stopped recognizing the key presses.

**Comment by rolandlo** [comment]
Maybe you experience the same problem as #3203. If it cannot be fixed like that please post a screenshot of the settings you got in the input system panel in menu `Edit > Preferences` and tell, if you use a Keyboard+Mouse combo.

**Comment by renatocan** [comment]
Yes, it is the same problem as [#3203](https://github.com/xournalpp/xournalpp/issues/3203).

I have a Keyboard+Mouse combo. The problem was fixed when I selected `Mouse+Keyboard combo` in Edit->Preferences->Input.

Thank you!
