### ISSUE TITLE
dark mode switching not working 

### ISSUE THREAD

**Issue by suisseWalter** [xournalpp/xournalpp#3278]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: ubuntu 20:04
 - (Linux only) Desktop environment: i3 on X
 - Which version of libgtk do you use
     -3.22.30 for appimage
     -3.24.20 for .deb over dpkg
 - Version of Xournal++: 
     - 1.1.0 commit 9d1277de for both
 - Installation method: appimage and .deb installed with dpkg

**Describe the bug**
I can't switch darkmode on or off in either version. they both have darkmode enabled in the settings. but in the .appimage it's always in darkmode, no matter what the toggle says, and the .deb install is always in light mode. 
note that the settings option can be changed, but it doesn't change the appearance on restart of xournalpp. 

**To Reproduce**
1. install both version
2. observe the toggle not working properly(restart between toggles)

**Expected behavior**
the settings toggle works and turns darkmode on and off. 

**Screenshots of Problem**
![screenshot_20210728_094138](https://user-images.githubusercontent.com/42143099/127283591-3e79e7c3-cfb9-4ce3-97dc-ce8153f93241.png)

**Additional context**
It might be that it uses the default of the OS, and due to I3, which doesn't know what darkmode is, one takes the gnome default that exists in the background(as gnome is also installed) and is set to darkmode, while the other doesn't find this preset and therefore just runs with the default lightmode. but not sure if the OS-default could have a influence on this. 

also I'm rather confident that this worked in the past, maybe even in old 1.1.0-dev branches, but not sure when it stopped.

**Comment by rolandlo** [comment]
This is related to #3190, where it was noticed that dark/light theme icons are switched in the AppImage (and with older Gtk+ version in general). Note that the `Dark Theme` toggle mainly selects the appropriate icons (plus the sidebar and floating toolbox background via the `xournalpp.css` file). The switch the application theme, you would still need to use your OS settings. On Gnome one can use the Gnome Tweak tool. 
![grafik](https://user-images.githubusercontent.com/40485433/127286256-0404a3f5-948c-44e3-9932-7b7923127323.png)

The AppImage detects the OS's theme via a startup hook that includes the following lines:

```
gsettings get org.gnome.desktop.interface gtk-theme 2> /dev/null | grep -qi "dark" && GTK_THEME_VARIANT="dark" || GTK_THEME_VARIANT="light"
APPIMAGE_GTK_THEME="${APPIMAGE_GTK_THEME:-"Adwaita:$GTK_THEME_VARIANT"}" # Allow user to override theme (discouraged)
CACHEDIR="$(mktemp --tmpdir --directory .AppRun.XXXXXXXX)"

export APPDIR="${APPDIR:-"$(dirname "$(realpath "$0")")"}" # Workaround to run extracted AppImage
export GTK_DATA_PREFIX="$APPDIR"
export GTK_THEME="$APPIMAGE_GTK_THEME" # Custom themes are broken
```

Hope that helps. I have no experience with `i3`.

**Comment by suisseWalter** [comment]
that makes sense. so the appimage runs a different hook then the install? because that would explain why the appimage finds the gnome hook, while the .deb install doesn't. which would in theory be the correct thing, as gnome isn't running. 
I'm able to set the theme by using other tools(lxappearance) and then it's set properly for both versions. 
thanks for the hint. 
would it maybe make to make this clear to the user that the toggle doesn't switch the application theme? but I guess that's just a problem for window manager that don't set their own gtk theme. which is probably quite rare. Or for people who would like to run the app in a different theme to the OS. 
if you feel like that would be desired I will leave the issue open. otherwise I will close it in 24h.

**Comment by personalizedrefrigerator** [comment]
#2771 might not be the correct solution to this, but I would like to link it to this issue.

**Comment by suisseWalter** [comment]
> #2771 might not be the correct solution to this

Why would you think so? I think this would perfectly solve this issue. as it makes the button do exactly what a layman would expect it to do. and it makes the default detection nearly irrelevant, as it would only happen on installation. so there would be no need to make it consistent between appimage and deb versions in my opinion.
in my opinion #2771 could be marked as a potential solution to this issue. bot not sure if I can even do that, or if that would have to be done from your side.

**Comment by personalizedrefrigerator** [comment]
> after reading the PR again and what rolando wrote above: I'm confused, as rolando says the settings toggle just switches the icon theme. and you say that the PR makes the application theme dependant on the icon theme. but you also say that it ignores the settings toggle, so what is it now?

The `Dark Mode` toggle in settings used to only change the icon theme (in older versions of Xournal++). That's what I meant by the "icon theme". The toggle now adds additional dark-mode-specific styling to Xournal++, such as the color of its sidebar. Sorry for the confusion!

The **current** issue with #2771 is that it can cause Xournal++ to completely disregard the user's **system** preference for a light/dark theme. This could be annoying if the user has the system theme change with the time of day (e.g. dark mode at night, light mode during the day), as Xournal++'s theme would often not match the current system theme.

**The old (no-longer relevant) issue with this:**
 * Xournal++ used to use many of the system's icons by default (It now has its own icon theme).
   * Enabling dark mode used to only toggle the theme of the Xournal++-specific icons, the others would need to be updated via system settings.
   * Changing the GTK theme, but leaving many of the icons used in Xournal++ could be very confusing.

**Comment by suisseWalter** [comment]
>This could be annoying if the user has the system theme change with the time of day (e.g. dark mode at night, light mode during the day), as Xournal++'s theme would often not match the current system theme.

I never even considered that people could have dynamic system theme. 

> The solution to this would be to (somehow -- I'm not sure how!) detect the user's OS theme preference and use this to change the icon/sidebar/floating toolbox theme based on this (while preserving a "theme override" setting to ignore the system's default theme).
wouldn't the following alternative work?:
use two toggle:
1) use system default [on/off]  
2) darkmode (is overwritten by 1) [on/off]
 if 1) is [on] change nothing from the current master branch, if 1 is [off] use your PR.
this way no one needs to go into the settings if the system theme is correctly recognized.

**Comment by rolandlo** [comment]
I opened an [issue](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/48) for `linuxdeploy-plugin-gtk` 
Actually starting the AppImage via
```
APPIMAGE_GTK_THEME="Adwaita-dark" ./appimageName
```
starts the AppImage in dark mode.

**Comment by szymongul** [comment]
If you're still approaching this problem while using gnome try to use gnome extension like this [gtk3 auto dark](https://extensions.gnome.org/extension/7547/gtk3-auto-dark/)
