### ISSUE TITLE
Stroke Recognizer should preserve endpoints for recognized lines.

### ISSUE THREAD

**Issue by kenballus** [xournalpp/xournalpp#3279]
Affects Versions: All

The Bug: When drawing a line with the stroke recognizer on, the endpoints of the line are not preserved. 99% of the time that I'm trying to draw a line, I can get the endpoints to be right; I need help only with drawing a straight line between them. This is the behavior in many competing stroke recognizers (i.e. the one used in GoodNotes) This behavior is especially frustrating when trying to draw a straight line between two preexisting points.

To Reproduce: Use the stroke recognizer to draw a line that is straightest in the middle. The endpoints will change to match the middle.

Expected Behavior: Whenever a stroke is recognized as a line, it is transformed by preserving its endpoints and extending a straight line between them.

**Comment by rolandlo** [comment]
Your suggestion makes sense to me as an enhancement and shouldn't be hard to implement. I wouldn't call it a bug, though.

**Comment by kenballus** [comment]
I'm glad to see that you like the suggestion. I just submitted PR #3282, which implements this new behavior.
