### ISSUE TITLE
New icon does not have transparent background in KDE

### ISSUE THREAD

**Issue by WillNilges** [xournalpp/xournalpp#3280]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: KDE 5 (X11)
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: Pacman

**Describe the bug**
It looks like the new icon for Xournalpp does not have a transparent background. Instead, it looks like there's a black border around the actual icon. Oops?

**To Reproduce**
1. Step 1: Install Xournalpp via `pacman`
2. Step 2: Add Xournalpp to Icons Only Task Manager in KDE

**Expected behavior**
Icon is added and appears normal

**Screenshots of Problem**

![image](https://user-images.githubusercontent.com/42927786/127400924-35d12501-857d-48e1-910f-0dc0484f3b67.png)
My system tray

![image](https://user-images.githubusercontent.com/42927786/127401338-9eea0d8b-54ea-4539-b629-1bd9740630d0.png)
What appears on the GitHub org, the same icon as viewed raw, and the icon downloaded and opened in EoG.

**Additional context**
It seems like the icon is not supposed to have a background/border of any kind, yet that's how it appears.

**Comment by personalizedrefrigerator** [comment]
I'm only noticing this on KDE Plasma (flatpak), not on GNOME (built from source):
![GNOME Xournal++ icon](https://user-images.githubusercontent.com/46334387/127416068-39b543c3-90f3-46b6-903e-75a0182769f3.png)

**Comment by matzebond** [comment]
As far as I can see, all of the logos in https://github.com/xournalpp/xournalpp/tree/master/ui/pixmaps have a transparent background when viewed in firefox.

Can you verify that the icon in /usr/share/icons/hicolor/scalable/apps/com.github.xournalpp.xournalpp.svg has no border?

**Comment by WillNilges** [comment]
`/usr/share/icons/hicolor/scalable/apps/com.github.xournalpp.xournalpp.svg `
![image](https://user-images.githubusercontent.com/42927786/127497141-33a78ce9-4817-4a9c-88c5-695d2611d5d9.png)

That looks correct to me. Must be a KDE thing. Odd, none of my other apps are doing that. I wonder what would happen if I tried re-saving it in inkscape.

**Comment by baschi29** [comment]
Can confirm this bug. Environment:
```
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
```
The black border is also present when viewing the icon in `/usr/share/applications/`
![grafik](https://user-images.githubusercontent.com/55055342/127622451-58b41fc2-e649-4e87-b428-142165458d9b.png)

**Comment by matzebond** [comment]
There is a `sodipodi:namedview` item in the svg that defines 
```
pagecolor="#ffffff"
bordercolor="#666666"
```
which could be the culprit. 

> I wonder what would happen if I tried re-saving it in inkscape.

@WillNilges this sounds like a good idea also mentioned in [this SO question](https://stackoverflow.com/questions/27607174)

**Comment by WillNilges** [comment]
Darn, that didn't work.

Tried re-saving it as plain SVG, replaced the icon, logged out and in, still had the black background. Tried rebooting, still had the black background. Also tried switching to light KDE theme, but it still had the black background.

> There is a `sodipodi:namedview` item in the svg that defines
> 
> ```
> pagecolor="#ffffff"
> bordercolor="#666666"
> ```
> 
> which could be the culprit.
> 
> > I wonder what would happen if I tried re-saving it in inkscape.
> 
> @WillNilges this sounds like a good idea also mentioned in [this SO question](https://stackoverflow.com/questions/27607174)

**Comment by bhennion** [comment]
Could you try this icon? It works for me. (I had to zip it for github to accept it)
[com.github.xournalpp.xournalpp.zip](https://github.com/xournalpp/xournalpp/files/7030418/com.github.xournalpp.xournalpp.zip)

There is most likely an underlying bug in KDE or Qt (to be filled there). It is triggered by the use of `mask`'s and `clip-path`'s: if the mask or clip-path partially covers the background, then said mask is applied to the background.

What I did in the attached icon was to flatten the colors (so the colors of the horizontal lines are now hardcoded and not `some value + some mask that applies transparency`). TBH, there was no reason at all to have a mask here to begin with. Even without hardcoding the color, the opacity could be set directly with a `fill-opacity`.

After glancing at the `.svg` code here, it may also be a good idea to apply `svgo` everywhere.

**Comment by LittleHuba** [comment]
A small follow-up for people like me that are stuck with the wrong icon even after a re-log. You can fix this by removing the file `~/.cache/icon-cache.kcache` followed by a reboot.
