### ISSUE TITLE
Stylus input sometimes scrolls page instead of draw

### ISSUE THREAD

**Issue by trydercal** [xournalpp/xournalpp#3281]
Sometimes when I write on my drawing tablet, the page will scroll on Xournal++ instead of drawing. Other times it will behave as normal. I am using the digimend drivers, but I don't think that would be the issue since it works with normal xournal.
https://youtu.be/prfX4tDlODM
Above is a link to the video of the bug. The only input I am actively using is my drawing tablet. As you can see, I can draw, but sometimes I can't and it scrolls. I don't know what is causing the undesirable behavior though.

**Comment by personalizedrefrigerator** [comment]
It looks like GTK 3 thinks your stylus is a touchscreen, and this is triggering GTK's scrolling behavior. Xournal uses GTK 2, which (I think) handles touchscreen scrolling differently.

Can you post a screenshot of Settings > Input System (particularly the input devices section)?

**Comment by trydercal** [comment]
![image](https://user-images.githubusercontent.com/77823686/127427821-37ce179b-892f-4034-8d33-c0b207229e1b.png)

**Comment by rolandlo** [comment]
I do experience this behaviour as well (on Ubuntu 21.04) [since July 11](https://github.com/xournalpp/xournalpp/pull/3221#issuecomment-877809589). It only happens if I run Xournal++ from Visual studio code. When I had input debug logging (`-DDEBUG_INPUT=ON`) on the stylus was indeed recognized as touchscreen.

**Comment by personalizedrefrigerator** [comment]
<details><summary>This could be a temporary workaround: Tell Xournal++ that the stylus is a touchscreen and enable touchscreen drawing.</summary>


 1. Check `Enable Pressure Inference`
![](https://user-images.githubusercontent.com/46334387/127464085-631504b9-963c-44c9-92df-2998531d0cd9.png)
 2. Change the following to `Touchscreen`
![Select touchscreen for device's source](https://user-images.githubusercontent.com/46334387/127463104-8107013f-97c2-4e12-80ba-2dd7df79aa2f.png)
 3. Enable touchscreen drawing (`Touchscreen` > `Touchscreen Drawing`)
![Enabling Touchscreen Drawing](https://user-images.githubusercontent.com/46334387/127466733-20381e6b-1bd0-4fb9-9268-ccd58e402bc3.png)

This isn't ideal (requires two fingers to pan the view), but it is an option!

</details>

In terms of what we can do to fix the issue, 
 * When we get input from a device GTK thinks is a touchscreen, but we have mapped to a pen, (beginning of input sequence)
   * Disable GTK kinetic scrolling (by calling https://github.com/xournalpp/xournalpp/blob/97c20f62c5a5c16ce6dbb21ffd19240f4fe55961/src/gui/MainWindow.cpp#L277)
   * Re-enable kinetic scrolling at the end of the input sequence.

The above may not work if GTK stops the propagation of single-touch events...

**Comment by trydercal** [comment]
> ## Potential workaround with current Xournal++
> This could be a temporary workaround: Tell Xournal++ that the stylus is a touchscreen and enable touchscreen drawing.
> 
>     1. Check `Enable Pressure Inference`
>        ![](https://user-images.githubusercontent.com/46334387/127464085-631504b9-963c-44c9-92df-2998531d0cd9.png)
> 
>     2. Change the following to `Touchscreen`
>        ![Select touchscreen for device's source](https://user-images.githubusercontent.com/46334387/127463104-8107013f-97c2-4e12-80ba-2dd7df79aa2f.png)
> 
>     3. Enable touchscreen drawing (`Touchscreen` > `Touchscreen Drawing`)
>        ![Enabling Touchscreen Drawing](https://user-images.githubusercontent.com/46334387/127466733-20381e6b-1bd0-4fb9-9268-ccd58e402bc3.png)
> 
> 
> This isn't ideal (requires two fingers to pan the view), but it is an option!
> ## What we might be able to do to fix the issue
> 
> In terms of what we can do to fix the issue,
> 
>     * When we get input from a device GTK thinks is a touchscreen, but we have mapped to a pen, (beginning of input sequence)
>       
>       * Disable GTK kinetic scrolling (by calling https://github.com/xournalpp/xournalpp/blob/97c20f62c5a5c16ce6dbb21ffd19240f4fe55961/src/gui/MainWindow.cpp#L277
>         )
>       * Re-enable kinetic scrolling at the end of the input sequence.
> 
> 
> The above may not work if GTK stops the propagation of single-touch events...

Hey that worked good enough for me! Thanks!!

**Comment by Zelberor** [comment]
I did some digging around and it seems like GTK decides based on the device's (xinput) name.
So if the device contains 'pen' in its name its a pen, and its a touchscreen if not.
So the main problem seems to be that the xf86-input-wacom driver only appends 'stylus' to stylus/pen devices, not 'pen'.
I also did modify the xf86-input-wacom driver to always add 'pen' to any stylus device name and tadaa: the stylus gets properly recognized as pen and the scrolling issue is gone.

**Comment by lucamarini22** [comment]
Hi @Zelberor, can you please explain how to do that practically step by step?

**Comment by LittleHuba** [comment]
> I did some digging around and it seems like GTK decides based on the device's (xinput) name.
So if the device contains 'pen' in its name its a pen, and its a touchscreen if not.
So the main problem seems to be that the xf86-input-wacom driver only appends 'stylus' to stylus/pen devices, not 'pen'.
I also did modify the xf86-input-wacom driver to always add 'pen' to any stylus device name and tadaa: the stylus gets properly recognized as pen and the scrolling issue is gone.

That seems to be fixable through a new udev-rule instead of modifying the driver itself.

**Comment by LittleHuba** [comment]
Sorry not udev but an xorg.conf file setting the value for the input device. See https://www.x.org/releases/current/doc/man/man5/xorg.conf.5.xhtml#heading8

You can specify the identifier of the device to end with 'pen'.

**Comment by lucamarini22** [comment]
Thanks,

so, for example I should modify the file "etc/X11/xorg.conf.d/50-tablet.conf":

    Section "InputClass"
        Identifier "Huion on wacom"
        MatchProduct "HUION"
        MatchDevicePath "/dev/input/event*"
        Driver "wacom"
    EndSection

into this?

    Section "InputClass"
        Identifier "Huion on wacom pen"
        MatchProduct "HUION"
        MatchDevicePath "/dev/input/event*"
        Driver "wacom"
    EndSection

**Comment by LittleHuba** [comment]
Yes that should do the trick.

**Comment by Zelberor** [comment]
Hmm I tried it with the xorg (and udev) rules, but did not find the right option to change the name. The Identifier in an InputClass section does not seem to change anything and I don't know how to use InputDevice sections.
Could you maybe provide an example?

---

I know that modifying the wacom driver is overkill and user-unfriendly, but here is a quick explanation how to do it:

1. Uninstall xf86-input-wacom
2. Download this [Patch.zip](https://github.com/xournalpp/xournalpp/files/7091938/Patch.zip) and extract it (Note that the patch is a bit 'hacky')
3. git clone https://github.com/linuxwacom/xf86-input-wacom.git
4. cd xf86-input-wacom
5. git apply path/to/names.patch
6. Follow the instructions [here](https://github.com/linuxwacom/xf86-input-wacom/wiki/Building-The-Driver#building-from-source) to build from source and install
7. Make sure with an xorg rule that your tablet uses the wacom driver
8. ?Success?

Or: If you are running arch just use the PKGBUILD in [Patch.zip](https://github.com/xournalpp/xournalpp/files/7091938/Patch.zip)
Hope that helps..

**Comment by lucamarini22** [comment]
Yes I confirm that adding "pen" to the Identifier name in /etc/X11/xorg.conf.d/50-tablet.conf didn't work

**Comment by LittleHuba** [comment]
That is sad. Well then you have a solution for now. Maybe it would be a good idea to head over to the driver repository and create a pull request that adds this device quirk in a nicer way so that it can be included in the driver.

**Comment by rolandlo** [comment]
> I did some digging around and it seems like GTK decides based on the device's (xinput) name. So if the device contains 'pen' in its name its a pen, and its a touchscreen if not. So the main problem seems to be that the xf86-input-wacom driver only appends 'stylus' to stylus/pen devices, not 'pen'. I also did modify the xf86-input-wacom driver to always add 'pen' to any stylus device name and tadaa: the stylus gets properly recognized as pen and the scrolling issue is gone.

This has recently been [fixed](https://gitlab.gnome.org/GNOME/gtk/-/commit/8984b13d84249c17d37750d14c9e9832cf0b3b8c) in Gtk. We just need to wait for a new Gtk 3 version to be released.
