### ISSUE TITLE
Starting Xournal++ from the KDE taskbar opens it using a new, second icon

### ISSUE THREAD

**Issue by baschi29** [xournalpp/xournalpp#3289]
**Affects versions :**

- Operating System: Kubuntu 21.04
- KDE Plasma Version: 5.21.4
- KDE Frameworks Version: 5.80.0
- Qt Version: 5.15.2
- libgtk Version:  3.24.25
- Xournal++ Version: 1.1.0
- Installation method: (unstable) ppa

**Describe the bug**
When Xournal++ is pinned to the KDE taskbar and you try to start it from there KDE does not show the new windows associated with the original icon but instead creates a new one in the taskbar.

**To Reproduce**
1. Pin Xournal++ to KDE taskbar
2. Launch Xournal++ (from the taskbar or by opening a document)
3. Xournal++ opens, but is shown under a new icon in the taskbar

**Expected behavior**
The pinned Icon should be the host of all newly created Xournal++ instances.

**Screenshots of Problem**
Pinned icon:
![grafik](https://user-images.githubusercontent.com/55055342/127624294-06c08a9f-a080-45d1-8370-6c82593e2225.png)
After starting Xournal++:
![grafik](https://user-images.githubusercontent.com/55055342/127624423-86c9d071-604e-45dc-aed4-889b565ed95c.png)

Please not that there is also Issue #3280 present in those screenshots. The new icon doesn't have the issue though.

**Comment by apandada1** [comment]
Does it help if you add the line `StartupWMClass=xournalpp` to the .dsektop file in /usr/share/applications?

**Comment by baschi29** [comment]
The line `StartupWMClass=xournalpp` is already in my .desktop file:

```
[Desktop Entry]
Type=Application
Name=Xournal++
Comment=Take handwritten notes
Keywords=Tablet;Wacom;Pen Input;PDF Annotation;Markup
Name[fr]=Xournal++
Comment[fr]=Prise de notes manuscrites
Name[ca]=Xournal++
Comment[ca]=Preneu notes a mà
Name[cs]=Xournal++
Comment[cs]=Dělejte si rukou psané poznámky
Name[de]=Xournal++
Comment[de]=Handnotizen erstellen
Name[pl]=Xournal++
Comment[pl]=Notatki odręczne
Name[zh_CN]=Xournal++
Comment[zh_CN]=手写注释工具，可为PDF文件添加各种元素的注释标记
Name[ru]=Xournal++
Comment[ru]=Делайте рукописные заметки

Exec=xournalpp %f
StartupWMClass=xournalpp
Terminal=false
StartupNotify=true
MimeType=application/x-xoj;application/x-xojpp;application/x-xopp;application/x-xopt;application/pdf;
Icon=com.github.xournalpp.xournalpp
Categories=Office;GNOME;GTK;
```

**Comment by apandada1** [comment]
Can you extract the StartupWMClass of the xournalpp window by following this method?
https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

**Comment by baschi29** [comment]
Sure:
`WM_CLASS(STRING) = "xournalpp", "Xournalpp"`

**Comment by apandada1** [comment]
Editing the .desktop file and check if `StartupWMClass=Xournalpp` works.

**Comment by baschi29** [comment]
Unfortunately changing it has no effect.

**Comment by bhennion** [comment]
Using the icon provided [here](https://github.com/xournalpp/xournalpp/issues/3280#issuecomment-903575040), unpinning xournal++, emptying the `.cache` and re-pinning xournal++ solved this for me. @baschi29 Could you try?

**Comment by baschi29** [comment]
Weird, I tried and it fixed bug #3280 , but unfortunately not this bug. I unpinned, emptied the .cache and re-pinned and even logged in again, but it had no effect.

**Comment by baschi29** [comment]
Tried it, but it also didn't fix it.
As you aren't able to replicate it anymore, can you maybe hint me to where to report this at the kde side?

**Comment by bhennion** [comment]
Here is the dedicated bugtracker [https://bugs.kde.org/](https://bugs.kde.org/). You may also find other bug reports there that may discuss the same issue.

Closing this issue.
