### ISSUE TITLE
Continues toggle for stylus shortcut buttons

### ISSUE THREAD

**Issue by ShamanthMurali** [xournalpp/xournalpp#3291]
### Feature
I would like to have continues toggle(or switch permanently) to tool from the stylus buttons
For Example:
Button 1 clicked once : switch to eraser
Button 1 clicked again : switch back to default (i.e pencil)
Button 2 clicked once : switch to Hand tool
Button 2 clicked again : switch back to default (i.e pencil)

### My Problem
I have wacom battery Free stylus and it works only when stylus is really close to tablet
I use shortcut button for hand tool extensively
Every time I lift the stylus it switches back to pencil

### Solution
It would be convenient to have a continues toggle check box in the menu show below
![image](https://user-images.githubusercontent.com/71114618/127670558-6dba11d6-cb24-466c-a5b2-788358f85981.png)

**Comment by kenballus** [comment]
What is it that you would like this toggle to do, exactly? Swap between the current tool and a previously selected tool, or swap between the current tool and a preset tool?

**Comment by ShamanthMurali** [comment]
Yes, I would like to 'swap between the current tool and a preset tool'.

The way it works right now is you press and hold the stylus button to switch to tool, and the moment the button is released it switches back to previous tool

And I don't want to click and hold, instead I want to just click to switch and click button again to switch back.
(As Click and hold does not work smoothly in battery free stylus)

Here is a representation
![image](https://user-images.githubusercontent.com/71114618/127767205-17b6a2fa-c3c5-4fda-b0c5-2a657f0037ac.png)


Thank you for your patience.

**Comment by ShamanthMurali** [comment]
Hurray!! . The new Update is doing the job.
