### ISSUE TITLE
Centered pinch-to-zoom

### ISSUE THREAD

**Issue by 2001herne** [xournalpp/xournalpp#3298]
**Describe the solution you'd like**
While zooming with the scroll wheel the page zooms around the mouse pointer. Ideally, when zooming with pinch-to-zoom the zoom would be centred about the midpoint of the user's fingers. Currently, the zoom is relative to the top-left corner of the document.

**Comment by rolandlo** [comment]
What version of Xournal++ do you use?

**Comment by 2001herne** [comment]
My bad, I should have included that.
Version 1.1.0 on Arch Linux

**Comment by rolandlo** [comment]
Then I don't understand why you think zooming is relative to the top-left corner of the document. Zooming with pinch-to-zoom on my convertible is centred about the midpoint of my fingers.

**Comment by 2001herne** [comment]
Ah, figured it out. Looks like it does, but it doesn't take into account the values set inside "Preferences > Drawing Area > Scrolling outside the page"

**Comment by robinp7720** [comment]
This should be fixed by #3372, can you confirm that @2001herne?
If so, @personalizedrefrigerator can you close this issue?

**Comment by 2001herne** [comment]
I can confirm that this looks like it fixes this. Drew a circle, and when using pinch-to-zoom my fingers maintained the same relative position on the circle. All looks good.
