### ISSUE TITLE
Trying to move partially off-screen elements causes vertical "teleportation"

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp#3307]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: elementaryOS 5.1
 - (Linux only) Desktop environment: Pantheon
 - Which version of libgtk do you use
     - 3.22.30
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1
 - Installation method: .deb for Ubuntu Bionic
 
**Describe the bug**
Trying to move partially off-screen elements causes vertical "teleportation" due to Xournal++ automatically scrolling up or down when the element being manipulated is at the top or bottom.

**To Reproduce**
1. Have an element partially off screen at the top or bottom of the screen
2. Select the element
3. Try moving the element
4. You're now at the start or the end of the document

**Expected behavior**
Just move the element without teleporting me.

**Screenshots of Problem**
https://user-images.githubusercontent.com/51940383/128454537-d2d9c21e-8d01-4935-ac5f-68ac7d98fb5b.mp4

**Comment by rolandlo** [comment]
What's the date of the .deb file? Please use the latest nightly release.

**Comment by Fatih20** [comment]
> What's the date of the .deb file? Please use the latest nightly release.

This one. https://github.com/xournalpp/xournalpp/releases/tag/1.1.0

**Comment by mjg** [comment]
> What's the date of the .deb file? Please use the latest nightly release.

By the way, the nightlies should not be versioned as 1.1.0, rather 1.1.1-dev or such I think (dev for the next release).

**Comment by rolandlo** [comment]
> > What's the date of the .deb file? Please use the latest nightly release.
> 
> This one. https://github.com/xournalpp/xournalpp/releases/tag/1.1.0

@Technius improvement for edge scrolling in #2893 has only been merged after that. So either use the nightly release or wait for the 1.1.1 release, if you want to experience a much improved behavior.

**Comment by Fatih20** [comment]
Okay then.
