### ISSUE TITLE
Random  crash linked to pipewire 

### ISSUE THREAD

**Issue by aiace9** [xournalpp/xournalpp#3320]
**Affects versions :**
 - OS: Fedora 34
 -  X11 (i3), pipewire for audio.
 - libgtk 3.24.30
 - Xournal++:  1.1.0
 - Installation method: via dnf, default repository 

**Describe the bug**
Random crash, probably when audio is required.
It happened 5/10 times at this point.

**To Reproduce**
1. Open
2. Do something.
3. wait a random time (mins/hours)

Not completely sure but now it crash when I open any other applications
that use the Audio (eg: vlc, youtube trough firefox) 

**Additional context**
- libpipewire 0.3.33
Log of the crash.
```
Error: signal 11
[bt]: (0) xournalpp(+0x1af818) [0x565215ecb818]
[bt]: (1) /lib64/libc.so.6(+0x3d320) [0x7fd9ed612320]
[bt]: (2) /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x21bd4) [0x7fd9e9ebabd4]
[bt]: (3) /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x13690) [0x7fd9e9eac690]
[bt]: (4) /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x13c60) [0x7fd9e9eacc60]
[bt]: (5) /usr/lib64/spa-0.2/support/libspa-support.so(+0xb16b) [0x7fd9eb84316b]
[bt]: (6) /lib64/libpipewire-0.3.so.0(+0x7ab06) [0x7fd9ebfcbb06]
[bt]: (7) /lib64/libpthread.so.0(+0x9299) [0x7fd9edc2d299]
[bt]: (8) /lib64/libc.so.6(clone+0x43) [0x7fd9ed6d5353]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1afcbd) [0x565215ecbcbd]
??:0
[bt] #2 /lib64/libc.so.6(+0x3d320) [0x7fd9ed612320]
??:0
[bt] #3 /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x21bd4) [0x7fd9e9ebabd4]
??:0
[bt] #4 /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x13690) [0x7fd9e9eac690]
??:0
[bt] #5 /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so(+0x13c60) [0x7fd9e9eacc60]
??:0
[bt] #6 /usr/lib64/spa-0.2/support/libspa-support.so(+0xb16b) [0x7fd9eb84316b]
??:0
[bt] #7 /lib64/libpipewire-0.3.so.0(+0x7ab06) [0x7fd9ebfcbb06]
??:0
[bt] #8 /lib64/libpthread.so.0(+0x9299) [0x7fd9edc2d299]
??:0
[bt] #9 /lib64/libc.so.6(clone+0x43) [0x7fd9ed6d5353]
??:0
```

**Comment by mjg** [comment]
Are you using audio annotations in your xournalpp document, or is this without doing any audio stuff there?

**Comment by robinp7720** [comment]
I cannot reproduce this behavior with gnome 41.rc.1, pipewire 0.3.35 and xournalpp build from git head.
I'd assume this is an issue with pipewire 0.3.33 or some other dependency, and not something that can be solved on xournalpp's end.

**Comment by aiace9** [comment]
> Are you using audio annotations in your xournalpp document, or is this without doing any audio stuff there?

No but I have an unrelated weird behavior of the sound buttons on save.

Can confirm that recently the problem disappeared by itself, so yes, it was very likely due to pipewire. Now I also have the 0.3.35 version.
I will close the issue, I will reopen it if it happens again.
Thanks!
