### ISSUE TITLE
Multiple Screen Tool Selection Issue

### ISSUE THREAD

**Issue by Tydblair** [xournalpp/xournalpp#3324]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use
     - 3.24.29
 - Version of Xournal++
     - 1.1.0
 - Installation method
     - Offial Release

**Describe the bug**
A clear and concise description of what the bug is
When using xournal with multiple screens in a verticle orientation with Xournal++ running on the bottom screen, trying to select a tool style from the drop down menu results in the drop down menu appearing on the top screen, out of reach of my drawing tablet

**Expected behavior**
The drop down menu should appear to drop *Down* Not Up

**Comment by Tydblair** [comment]
Aditional Information:

The behaviour only happens if the 'below' screen is set to the main monitor. That may be an issue with windows, I'm not sure

**Comment by Technius** [comment]
This is a GTK issue that we cannot fix at the moment: https://gitlab.gnome.org/GNOME/gtk/-/issues/1477
