### ISSUE TITLE
Feature request: A way to track what tool is active through the Plugin API

### ISSUE THREAD

**Issue by dylif** [xournalpp/xournalpp#3332]
**Is your feature request related to a problem? Please describe.**
My drawing tablet stylus buttons do not work in the program, so I have developed a plugin to reproduce eraser toggling behavior. However, this will only work if I hard code which tools to switch between (e.g., pen and eraser, highlighter and eraser, etc.), and thus breaks if I were to switch from the pen to the highlighter, for example. There is no way to track what tool is selected, and hence I created this request. 

**Describe the solution you'd like**
Add a function to the Plugin API which returns the active tool.
Example:
```Lua
activeTool = app.getActiveTool()
print(activeTool)
if activeTool == "TOOL_PEN" then
...
```

**Describe alternatives you've considered**
I've tried binding two separate buttons, one to select the pen, and one to select the eraser, in my drawing tablet software, but found this to be uncomfortable and unnatural. In my research, I found that the stylus button issues should be fixed, but I have tried multiple different configurations with my stylus buttons in Xournal++ and no solution has arisen.

**Additional context**
I am using a HUION Inspiroy H1060P if it means anything.
For reference, my plugin implementation is here: [EraserToggle](https://github.com/dylif/EraserToggle)

**Comment by rolandlo** [comment]
I agree that the plugin API should be extended to provide the possibility to get the active tool. In the C++ code this info can be obtained via the `ToolHandler`. There is more info (than just the tool type) that can be obtained from the `ToolHandler`:

- the color of the active tool
- the fill opacity of the active tool
- the drawing type of the active tool
- the line style of the active tool
- the thickness of the active tool
- the pen size
- the eraser size
- the highlighter size
- whether pen fill is enabled
- the opacity of the pen
- whether highlighter fill is enabled
- the opacity of the highlighter
- the eraser type

All of this should be accessible via the plugin API, I think.
Technically I would suggest implementing 4 functions:

- `app.getActiveToolInfo()`
- `app.getPenInfo()`
- `app.getHighlighterInfo()`
- `app.getEraserInfo()`

that return Lua tables containing all the info. 

Then you would have to write something like:

```lua
local activeTool = app.getActiveToolInfo()["tool"]
print(activeTool)
if activeTool == "TOOL_PEN" then
```

Does that sound like a reasonable solution? I don't think it would be hard to implement.

**Comment by dylif** [comment]
> I agree that the plugin API should be extended to provide the possibility to get the active tool. In the C++ code this info can be obtained via the `ToolHandler`. There is more info (than just the tool type) that can be obtained from the `ToolHandler`:
> 
> * the color of the active tool
> * the fill opacity of the active tool
> * the drawing type of the active tool
> * the line style of the active tool
> * the thickness of the active tool
> * the pen size
> * the eraser size
> * the highlighter size
> * whether pen fill is enabled
> * the opacity of the pen
> * whether highlighter fill is enabled
> * the opacity of the highlighter
> * the eraser type
> 
> All of this should be accessible via the plugin API, I think.
> Technically I would suggest implementing 4 functions:
> 
> * `app.getActiveToolInfo()`
> * `app.getPenInfo()`
> * `app.getHighlighterInfo()`
> * `app.getEraserInfo()`
> 
> that return Lua tables containing all the info.
> 
> Then you would have to write something like:
> 
> ```lua
> local activeTool = app.getActiveToolInfo()["tool"]
> print(activeTool)
> if activeTool == "TOOL_PEN" then
> ```
> 
> Does that sound like a reasonable solution? I don't think it would be hard to implement.

You actually got it spot on! Initially I was thinking of writing something like this as my solution, but was unsure as to how hard it would be to implement. But an API like this would prove to be very useful.

**Comment by personalizedrefrigerator** [comment]
We could also do something like this, which has the advantage of being <i>very</i> easy to implement:
```cpp
/**
 * Get the name of the tool currently in use.
 * 
 * Example 1: app.getCurrentToolType() -> "none"
 * When no tool is selected.
 *
 * Example 2: app.getCurrentToolType() -> "pen"
 *
 * Example 3: app.getCurrentToolType() -> "hand"
 */
static int applib_getCurrentToolType(lua_State* L) {
    Plugin* plugin = Plugin::getPluginFromLua(L);
    Control* ctrl = plugin->getControl();
    ToolHandler* toolHandler = ctrl->getToolHandler();

    std::string toolName = toolTypeToString(toolHandler::getToolType());

    lua_pushstring(L, toolName.c_str());
    return 1;
}
```

**Comment by rolandlo** [comment]
Please take a look at #3364
