### ISSUE TITLE
[Feature request] Add dotted paper

### ISSUE THREAD

**Issue by JoeKays** [xournalpp/xournalpp#334]
Hi,

dotted paper would be really great, I have locally implemented it by changing the contents of 'void DocumentView::paintBackgroundGraph()' (the method painting the graph paper in my case) to:

```
cairo_set_line_width(cr, 1.5);
cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);

for (double x = graphSize; x < width; x += graphSize)
{
	for (double y = graphSize; y < height; y += graphSize)
	{
		cairo_move_to(cr, x, y);
		cairo_line_to(cr, x, y);
	}
}
```

However I am not sure what else has to be changed to not overwrite the current graph paper and adding a new paper type.
Maybe someone else knows how to do that?

Also I propose to let the user choose the colour of the pattern. The blue is not really my favourite...

Thanks!

**Comment by andreasb242** [comment]
At the moment this is a little bit complicated, but I'm currently thinking about refactoring this part, so it should be possible to e.g. choose the line color.

I'ts OK with this ticket here, so the status will be tracked.

**Comment by JoeKays** [comment]
This is awesome! 
I also like they grey graph paper. We could maybe make every 5th line in red or something, then it would be even better I think.
Have you already changed the way the drawing is done so the colour can be selected?
As I imagine it there could be a setting for main and secondary colour and a setting for line width and line spacing. It would be really easy to customise with that.

**Comment by andreasb242** [comment]
I have changed the model, so we can supply an argument string to each background. So the most work is done, but I didn't change the painting yet. This will be the second step.
The string also will be read / stored in the xoj file.

**Comment by morrolinux** [comment]
Have you already checked if that doesn't break file backcompatibility and stroke timestamp reading/storing from/to file?

**Comment by andreasb242** [comment]
I haven't changed a lot on the load / save handling.
As long as you use the Backgrounds supported by Xournal, the file looks 100% the same.

If you used a dotted page (or also additional features, which are not yet ready) Xournal will not open the file.
But for me this is the better solution, than to do a hack and save it somewhere els, save e.g. lined background, and you only have to open the file once by Xournal and save it, you will lost all those information, without any notification!

So the discussion is open

**Comment by andreasb242** [comment]
I discussed with @morrolinux and we decided, to store Xournal++ files as .xojpp. We allow to export as .xoj, but then you loose e.g. your dotted background.

It's not a big change, the fileformat keeps the same, as long as you don't use e.g. a new background, the file will be identical, don't matter if saved as .xoj or as .xojpp.

**Comment by morrolinux** [comment]
Yeah right now I'm kind of regretting the choice of name "xojpp" maybe simply "xopp" would look better, don't hesitate to argue about it if I'm not the only one ;-)

**Comment by andreasb242** [comment]
Ok, xopp :-)

**Comment by andreasb242** [comment]
Technical all is ready now. I need to handle the .xoj export, and .xopp save, and then I can enabled the Dotted Background

**Comment by andreasb242** [comment]
![grafik](https://user-images.githubusercontent.com/822958/48978035-df371800-f0a5-11e8-89c7-41833ac9cdef.png)

**Comment by JoeKays** [comment]
@andreasb242 Very cool!
