### ISSUE TITLE
Under Windows 10, the brush can not work normally when using the digital board

### ISSUE THREAD

**Issue by songzongquan** [xournalpp/xournalpp#3346]
**Affects versions :**
 - OS: Windows10
 - Version of Xournal++： 1.1.0

**Describe the bug**
Under Windows 10, when using a digital board (Brand: gaoman), the brush does not work normally。
Every time you write with a brush, the pen line will not be echoed for a short time at the beginning, and will be displayed continuously after a while. This happens again as soon as the pen leaves the tablet, which is basically unusable when writing. Another problem is that the driver provided by the digital board manufacturer must be turned off. Otherwise, as long as the digital board starts writing with a little brush, this program will automatically close and exit.

But it's normal to write with the mouse... But the experience of writing with the mouse is too bad.

**To Reproduce**
1. Connecting digital board

2. Start gaoman's driver tool

3. Connect the mouse

4. Pick up the brush and click or draw on the tablet

(the above steps can make the program crash and exit immediately)

If step 2 is not done, or close the driver. When step 4 is executed, it will not crash and exit, but the line will not echo at the beginning of line drawing.

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.

**Expected behavior**

**Screenshots of Problem**

**Additional context**

**Comment by lb90** [comment]
Hello @songzongquan! This issue should be fixed in the latest hotfix release: https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1. Could you test and tell us how it works for you?

**Comment by songzongquan** [comment]
OK, I'll test it and tell you the results




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 凌晨1:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xournalpp/xournalpp] Under Windows 10, the brush can not work normally when using the digital board (#3346)





 
Hello @songzongquan! This issue should be fixed in the latest hotfix release: https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1. Could you test and tell us how it works for you?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songzongquan** [comment]
After testing, the problem has been solved. But a new problem was found: unable to input Chinese.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xournalpp/xournalpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 凌晨1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xournalpp/xournalpp] Under Windows 10, the brush can not work normally when using the digital board (#3346)





 
Hello @songzongquan! This issue should be fixed in the latest hotfix release: https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1. Could you test and tell us how it works for you?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songzongquan** [comment]
ok,i have opened it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xournalpp/xournalpp] Under Windows 10, the brush can not work normally when using the digital board (#3346)





 
Thank you very much for the follow-up! Can you open a separate issue for the input problem?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Technius** [comment]
Closing since the original problem has been fixed.
