### ISSUE TITLE
Bug: Page container colour

### ISSUE THREAD

**Issue by JoeKays** [xournalpp/xournalpp#335]
And a tiny bug with the background behind the paper:
When zooming out from normal zoom the background colour changes from the normal grey to a really unpleasant black.

I am not sure why this happens but it is weird and a little annoying.

Thanks again!

**Comment by andreasb242** [comment]
This does not happen on my system. Can you create a video / screenshot or so and supply which distribution you are using?

Or if this happen on some special cases, e.g. if the screen is rotated or something like this. As long I cannot reproduce it, I probably cannot fix it.

**Comment by JoeKays** [comment]
Funny.
Here's a screenshot of what happens.

Bottom picture is after scrolling out with the mouse wheel.
![xournalpp-bug](https://user-images.githubusercontent.com/24915259/48715669-cc3fc600-ec15-11e8-9ead-c1967325f53a.png)

**Comment by JoeKays** [comment]
It happens always. I just have to start the program and scroll out and it immediately happens. No flickering, nothing, just black and it stays that way forever.

**Comment by andreasb242** [comment]
I found a scrolling issue. I have to check this later. Maybe I need to fix this...

**Comment by taaem** [comment]
I have this too, when totally zoomed out I can get rid of it by disabling the sidebar

**Comment by andreasb242** [comment]
I have some ideas, there were some deprecated GTK functions, where I get the colors from....

**Comment by andreasb242** [comment]
>gtk_style_context_set_background has been deprecated since version 3.18 and should not be used in newly-written code.
>
>Use gtk_render_background() instead. Note that clients still using this function are now responsible for calling this function again whenever context is invalidated.


This is the Problem I think.

**Comment by andreasb242** [comment]
I couldn't reproduce the error on my machine.
Please check if working, and if not, reopen the ticket.

**Comment by taaem** [comment]
For me this is fixed now!
