### ISSUE TITLE
Cannot add texts near each other due to snap

### ISSUE THREAD

**Issue by akiross** [xournalpp/xournalpp#3352]
**Affects versions :**
- NixOS Linux
- Xournalpp 1.0.20 and 1.1.0
- LibGTK 3.24.30
- nixos packages (`nix-shell -p xournalpp`, `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p xournalpp` for 1.1.0).

**Describe the bug**
Possibly related to [overly snappy behavior](https://github.com/xournalpp/xournalpp/issues/3107), I noticed since a while that snap is applied when placing text as well and it's not possible anymore to place two texts nearby. It seems there is no way to disable this snapping behavior.

**To Reproduce**
1. Open a new document,
2. write a line of text,
3. try inserting a text *just below it*, so that space between the lines is basically non-existing,
3. snap will select the text above instead of adding a new text in the document.

**Expected behavior**
 - Snap doesn't get in the way of creating new texts, 
 - and/or a button allows to disable snap when adding text.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
This issue makes hard to fill forms when lines are nearby each other, especially because while it's possible to modify the font size, it's AFAIK not possible to change the line height. My current workaround is to write lines where possible, then export the document as PDF, open it again and add missing lines so snap doesn't go in the way.

**Comment by ronandalton** [comment]
A better work around would be to type the text somewhere else and then use the move tool to drag it closer to the text you have snapping issues with.
