### ISSUE TITLE
Add Pen Input Support for XP-Pen Brand Graphics Tablets.

### ISSUE THREAD

**Issue by zLadin** [xournalpp/xournalpp#3367]
XP-Pen currently officially supports (and has been supporting for 1-2 years) Linux Platform and multiple distributions. XP-Pen has been making quality products that they have good amount of market share to be seen as a contender in graphics tablets scene. Therefore, support for this functions to work with this brand is necessary and beneficial to Xournal++ 

Drivers Page of XP-Pen: https://www.xp-pen.com/download-421.html

**Comment by LittleHuba** [comment]
Please head over to the bug tracker of GTK as they have to enable support for this device type.
