### ISSUE TITLE
Crash after opening non-PDF file with Annotate PDF menu option

### ISSUE THREAD

**Issue by ronandalton** [xournalpp/xournalpp#3368]
**Affects versions :**
 - OS: Linux
 - Desktop environment: X11
 - libgtk version 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
When a non-PDF file is chosen from the file picker dialog when using the "Annotate PDF" action, the drawing area goes blank and changing tools triggers a crash.

**To Reproduce**
1. Go to File -> Annotate PDF.
2. Change the file type in the file selection dialog from "PDF files" to "All files".
3. Select a non-PDF file (eg. a JPG image file) and open it.
4. Click OK when the error message is given. The drawing area will go blank.
5. Select a different tool (eg. the highlighter tool). The program will crash.

**Expected behavior**
The program would not crash and continue to be functional.

**Additional context**
This does not happen if File -> Open is used instead of File -> Open PDF.

**Comment by Technius** [comment]
Opening a non-PDF file should show a warning at the very least.

**Comment by Technius** [comment]
There is a warning shown, but the problem is that the current document is cleared, putting the application into an invalid state. It would be better if the document is only cleared after the new document is successfully loaded.
