### ISSUE TITLE
Select text in imported PDF file

### ISSUE THREAD

**Issue by raffaem** [xournalpp/xournalpp#3369]
**Is your feature request related to a problem? Please describe.**
I am reading the guide to an R package, which is in PDF format. I need to select the text that is already in the PDF and copy it

**Describe the solution you'd like**
Possibility to select the text that is already in the imported PDF

**Describe alternatives you've considered**
Copy the text manually?

**Comment by raffaem** [comment]
Uhm, it looks like the PDF is imported like a bitmap. Correct me if I'm wrong....

**Comment by LittleHuba** [comment]
Will be fixed by #3326

**Comment by raffaem** [comment]
Thank you so much to @aeghn for the PR and the hard work.

Let us know if you guys (Xournal++ or @aeghn) need donations.

Closing as duplicate of  #1745

**Comment by aeghn** [comment]
@raffaem

I have a full time job now, so thanks for the kind words.

And I'm so busy these days that I won't have time to continue fixing the bugs in the pr until two or three weeks from now.

**Comment by raffaem** [comment]
@aeghn maybe I should have said if you *want* donations rather than *need*.

We lack a "well-featured" open-source PDF editor on Linux. I had to look for PDF editors back and forth, and I had to rely on proprietary software at least (I currently cannot annotate on Evince, and I cannot select text on Xournal++).

Your PR is extremely useful, and in fact there is lot of appreciation for #1745.

This is one of the very few things that prevents me from going fully open-source (well, despite some binary blobs in the kernel to be nitpicking).

I would be more than happy to pay you rather than the proprietary software.

I'm sure you would raise quite a lot of money from donations with your skills if you could spare some time on the weekends.

Best

**Comment by raffaem** [comment]
> @raffaem
> 
> I have a full time job now, so thanks for the kind words.
> 
> And I'm so busy these days that I won't have time to continue fixing the bugs in the pr until two or three weeks from now.

I meant if you *want* donations rather than if you *need* it.

We lack a good PDF editor on Linux and your patch is very useful and very popular (together with Xournal++ of course).

I currently have to rely on proprietary software.

**Comment by Technius** [comment]
@raffaem We currently don't accept donations (we're more pressed for time than money anyways), but contributions of any other form (e.g., documentation, code, testimonials, etc.) would be very helpful!

**Comment by aeghn** [comment]
@raffaem I must point out that I am a person who works according to my hobbies, I have a job to provide my daily expenses, and the rest of the time I want to work according to my hobbies and do not want them to be too much connected with money, at least for now.
