### ISSUE TITLE
Text Tool Broken?

### ISSUE THREAD

**Issue by unhandyandy** [xournalpp/xournalpp#3389]
**Affects versions :**
 - OS: Linux
 - OpenBox
 - Which version of libgtk do you use: libgtk: 3.24.20
 - Version of Xournal++: 1.1.0, 1.0.6
 - Installation method: git clone, apt
**Describe the bug**
Text tool does not produce text: typing in a text field results in no text

**To Reproduce**
click Text tool
click on canvas to create text field
type
nothing happens

**Expected behavior**
characters should be printed

**Screenshots of Problem**
![Screenshot_2021-09-11_12-21-41](https://user-images.githubusercontent.com/2363767/132954528-7107ec5e-62f2-4df0-bd3c-e4720d6ee710.png)

**Additional context**
I've tried both version 1.0.6 from the Ubuntu archive and 1.1.0 from the git repo.

**Comment by personalizedrefrigerator** [comment]
What does settings > input devices show?
See also #3377.

**Comment by unhandyandy** [comment]
![image](https://user-images.githubusercontent.com/2363767/132956454-09be9d60-b022-4d50-b6f1-332b272a4207.png)

**Comment by personalizedrefrigerator** [comment]
Try re-assigning "dell wired keyboard" to "keyboard" and "dell wired keyboard consumer control to "keyboard". If that doesn't work, try assigning them to "mouse+keyboard combo". (It looks like GTK thinks your keyboard is a mouse!)

**Comment by personalizedrefrigerator** [comment]
**Semi-unrelated note:** Also, if you're drawing with a touchscreen, you may want to consider assigning the touchscreen to "Touchscreen", enabling "Pressure Inference" (in input device settings), and turning on touchscreen drawing (under touchscreen settings).

**Comment by unhandyandy** [comment]
OK, here's the problem:  there's no "keyboard" option:

![image](https://user-images.githubusercontent.com/2363767/132958069-a88c0553-b2f2-46ea-b2f3-ad548f48d5c3.png)

**Comment by unhandyandy** [comment]
Setting "dell wired keyboard" to Mouse+Keyboard seems to fix the problem.  Thanks!

**Comment by anishmittal2020** [comment]
@personalizedrefrigerator I am facing the same issue on Ubuntu 20.04

```bash
$ xournalpp --version
Xournal++ 1.1.0
└──libgtk: 3.24.20
```

Also, in Settings, there is no option related to input devices

![image](https://user-images.githubusercontent.com/42092626/134341869-338905d3-5e8a-4dac-a3ab-3de7ca4c31c2.png)

![image](https://user-images.githubusercontent.com/42092626/134341892-b78d1194-c07b-4b9f-a0f2-c698c10de536.png)
