### ISSUE TITLE
PDF pages are arranged from bottom to top

### ISSUE THREAD

**Issue by jeanravenclaw** [xournalpp/xournalpp#3401]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - Windows
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0 
 - Installation method: Official Release (on github)
 
**Describe the bug**
The pages in the editor are arranged from bottom to top.
```
page 3
page 2
page 1
```
In the sidebar they are arranged just fine, but the arrangement in the editor is just weird.

**To Reproduce**
1. Open PDF with 3+ pages in Xournal++
2. Scrolling up is next page
3. Scrolling down is previous page
4. etc

**Expected behavior**
The next page is below the current page and the previous page is above the current page.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/75297066/133543878-d8fc43cd-b5be-41df-be12-507de1caa4a7.png)
(sorry this is my math homework)

**Comment by rolandlo** [comment]
Please switch the layout in menu `view > layout` from `bottom to top` to `top to bottom`

**Comment by jeanravenclaw** [comment]
Oh, that fixed the problem. Sorry and thanks!
