### ISSUE TITLE
Xournalpp doesn't work with existing TeXLive installation

### ISSUE THREAD

**Issue by marchersimon** [xournalpp/xournalpp#3404]
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
     - 3.24.30
 - Version of Xournal++:
     - commit f59c3c4a400c9117aba719ee0011b952c532aa1d, version 1.1.0
 - Installation method: build from source

**Describe the bug**
In the Manjaro repos, Xournalpp depends on texlive-bin. But this package broke my existing TeXLive installation, I installed from the official website. So I tried building Xournalpp from source and use my existing TeXLive installation. But now I have the problem, that Xournalpp doesn't find the `pdflatex` executable. It claims it isn't in my path, which it is. I can run `pdflatex` in the terminal.

**To Reproduce**
1. Install TeXLive from the [official website](https://tug.org/texlive/quickinstall.html)
2. Build Xournalpp without its dependency `texlive-bin`
3. Try to add a LaTeX field in Xournalpp

**Expected behavior**
It finds `pdflatex` in my `PATH` and works.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/50295997/133889929-23c061bd-8e10-425e-abc9-92aee92b8d1b.png)

**Additional context**
`echo $PATH`: `/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/usr/local/texlive/2021/bin/x86_64-linux`

`whereis pdflatex`: `pdflatex: /usr/local/texlive/2021/bin/x86_64-linux/pdflatex`

**Comment by robinp7720** [comment]
Are you sure you're setting the PATH variable before your desktop has started? Glancing at the code, xournalpp uses `g_find_program_in_path` to find the executable. I doubt glib has a bug here.

Anyways, I would highly recommend **not** installing applications without the use of a package manager. Things are bound to break as seen here.

**Comment by marchersimon** [comment]
I think my issue was that I was setting my PATH in `.zshrc`, which get's loaded after the DE. I just specified the full path to the executable and now it works. 

The reason I didn't install LaTeX through my package maneger is because it doesn't provide many tools like `tlmgr` and in my experience it breaks constantly. 

Anyways thanks for helping, even if the issue wasn't related to Xournalpp.
