### ISSUE TITLE
The Pen Stylus does not work as a mouse alternative anymore !!

### ISSUE THREAD

**Issue by Prajj-10** [xournalpp/xournalpp#3422]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows , I don't know about other OS
 - Version 1.1.0
 - Git commit is 9d1277de
 - with libgtk 3.24.29

 - Installation method: Official Release

**Describe the bug**

Previously on Xournal++ version 1.0.20 I used to use my pen as a mouse alternative and it worked fantastic. Now I cannot use it as a mouse alternative even if there is an option that says to choose input system. I tried various ways but it is not working. It does not write as it does with the mouse. On top of that I cannot switch if I start writing from pen and back to mouse. I use an XP-Pen Star-03 and it has created a lot of problems while teaching.

**To Reproduce**

Connect your pen stylus and keep it in mouse mode.
Check the input system is set to mouse for pen/stylus
try to write with pen 

**Expected behavior**

The pen should work as if it is a mouse.

**Additional context**

This previously worked perfectly on Xournal ++ 1.0.20 when it had no input devices section to choose differently for pen and mouse in the preferences/Input System. I tried reinstalling 1.0.20 but I still had problems. I checked every other way but now it has just stopped working.

**Comment by LittleHuba** [comment]
Hi, sorry to hear that you have problems with the new input system. Could you please go into more detail what your issues are exactly?

**Comment by Prajj-10** [comment]
Hello I have attached a video here showing how when i write with the mouse
for the first time, it works fine but the moment I start using my pen it
does not and the right click nothing works. I have tried all kinds of input
system in settings but it does not work. The pen is far away from where I
write and none of the shortcuts of the mouse work.

Here's a video to the problem I am facing


https://drive.google.com/file/d/19dV_-V_xShkAwUcu965ydoSgm26oAaZI/view?usp=sharing

**Comment by LittleHuba** [comment]
Can you please install https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1 and try if that fixes your issues?

**Comment by Prajj-10** [comment]
Wow I feel like an idiot for not trying that hotfix. I am extremely sorry
to bother you. Thank you so much !!

**Comment by LittleHuba** [comment]
I assume that closes the issue.

**Comment by Prajj-10** [comment]
It does. Thank you !!
