### ISSUE TITLE
Multiple Windows support

### ISSUE THREAD

**Issue by sharod** [xournalpp/xournalpp#3424]
I am unable to open multiple windows in Xournal++. When I open a new document, the old document closes down. Please help me about this setting.

**Comment by LittleHuba** [comment]
Please start the instances from console and report the output.

**Comment by rolandlo** [comment]
@sharod 
Yes, when you open a new document, the old document is closed. In order to edit multiple documents at once, you must run multiple instances of Xournal++.

**Comment by funnym0nk3y** [comment]
I think there should be a setting like in VLC, if Xournalpp should start a new instance or close the current document and open a new one. Especially in Windows Table Mode running a new instance is cumbersome.
