### ISSUE TITLE
Doesn't it support Chinese?

### ISSUE THREAD

**Issue by yjcjdfh** [xournalpp/xournalpp#3429]
How to change the language?Chinese
![Screenshot_20211001_173839](https://user-images.githubusercontent.com/90547519/135599291-dd03a719-7e18-46f7-be5b-52d0f3e479f1.jpg)

**Comment by tattsan** [comment]
xournalpp_mobile  is developed at another site:
https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile
