### ISSUE TITLE
UX issue: The label for the "Draw Line" button is "Ruler" in many parts of the GUI, which mean different things

### ISSUE THREAD

**Issue by siliconninja** [xournalpp/xournalpp#343]
**EDIT: a better explanation is in this comment: https://github.com/xournalpp/xournalpp/issues/343#issuecomment-440803325 This affects Xournal++ entirely, not just the "Toolbar Left" layout.**
**Here is what I initially discovered that made me decide to report this issue:**

When using the "Toolbar Left" layout in View > Toolbars, when hovering over the "RULER" tool, it shows up as "Ruler", not "Draw Line". For reference, I'm using the latest version on Manjaro, poppler 0.67.0, with the fix @JoeKays is suggesting for GTK2->GTK3 in CMakeCache.txt. (I've attached my fixed copy in issue #292 so people working on that issue can refer to a copy that works.)

Screenshot:
![screenshot_20181120_230817-xournalppbug](https://user-images.githubusercontent.com/29907828/48819370-9ede3f80-ed1d-11e8-982b-f7f322645344.png)

Relevant code files:
https://github.com/xournalpp/xournalpp/blob/master/ui/toolbar.ini#L52
I tried changing "RULER" to "DRAW_LINE" but that just hid the toolbar icon, probably because the label didn't exist in ToolMenuHandler.cpp near line 424: https://github.com/xournalpp/xournalpp/blob/1d177cfc781965b489aeeb2f090036cbff1b6d1c/src/gui/toolbarMenubar/ToolMenuHandler.cpp#L424.
DRAW_LINE exists in this file: https://github.com/xournalpp/xournalpp/blob/1d177cfc781965b489aeeb2f090036cbff1b6d1c/src/gui/toolbarMenubar/ToolDrawCombocontrol.cpp
I tried "ACTION_RULER" but that still hid the icon.

So when I'm using the default "Portrait" layout, ToolDrawCombocontrol is showing with the 5 types of drawing shape tools: rectangle, circle, arrow, line, and recognize lines. The draw line button still shows up (as expected, because the toolbar.ini shows "DRAW" which refers to the combo control box containing the 5 elements).

I also propose that the "RULER" name in the code be changed to "DRAW_LINE_BUTTON" or something similar so it's less confusing, because there's also a ruler in the settings, and that's different.

**Comment by andreasb242** [comment]
Not sure if I understand you right.

>I also propose that the "RULER" name in the code be changed to "DRAW_LINE_BUTTON" or something similar so it's less confusing, because there's also a ruler in the settings, and that's different.

1. I'm not a native english speaking person, but ruler sounds OK for me
2. You mean the RULER if you map Mouse / Stylus button? This is the same ruler as the Ruler in the Toolbar, I checked now, if I map the right mouse button to a pen with Ruler exactly this ruler button is activated, so for me it looks right.

So I currently don't see any problem.

---
Ok, there is a Problem, but not what you mean, if I release the the right button, the ruler is not disabled anymore. I probably can fix it easy, but this is offtopic...
---

**Comment by siliconninja** [comment]
@andreasb242 
Sorry about that, here's a more clear explanation.

I noticed that in Xournal++, the "Draw Line" tool is referred to as "Ruler" (in the "Input Device" part of the settings menu, and the Tools menu), except in the combo box with the different drawing tools (Draw Circle, Draw Square, etc), where it correctly shows "Draw Line", which are in the View>Toolbars>"Portrait" layout (which I'll refer to as "Portrait" layout), View>Toolbars>"Xournal++" layout (which I'll refer to as "Xournal++" layout), and View>Toolbars>"Toolbar Right" layout (which I'll refer to as "Toolbar Right" layout).

Good:
![screenshot_20181121_150311](https://user-images.githubusercontent.com/29907828/48867487-4b630480-eda4-11e8-9896-b9b6d2e5756c.png)

**If I ever say "X" layout here, I mean the option View>Toolbars>"X", which means I click a button called "X" in that specific menu, View>Toolbars, and the option is selected. I'm doing this to make my explanations clear.** For example, for the "Toolbar Left" layout, I mean when I click the button called "Toolbar Left" in the View>Toolbars menu and it is selected.

The problem is in the "Toolbar Left" layout: when you hover over the "Draw Line" tool, I feel that it should show "Draw Line" instead of "Ruler" so it's consistent with the other layouts.

Issue:
![screenshot_20181120_230817-xournalppbug](https://user-images.githubusercontent.com/29907828/48867513-5e75d480-eda4-11e8-9554-989769226e7b.png)


There's a "zoom ruler" in the settings to calibrate the level of how much to zoom in/out based on the dpi of a screen. **There are also no issues in this menu.** The zoom ruler tab in the settings menu is OK and uses the right words.

https://github.com/xournalpp/xournalpp/blob/master/src/gui/widgets/ZoomCallib.cpp

https://github.com/xournalpp/xournalpp/blob/master/ui/settings.glade#L701

I find that having different names for accomplishing the same task is confusing. Because I see "Ruler" throughout the app, not just in the "Toolbar Left" layout, I'm going to change this issue's title to "UX issue: The label for the "Draw Line" button is "Ruler" in many parts of the GUI, which mean different things", because I feel that this should be changed throughout the app to avoid confusion from users. (UX means user experience, and this issue impacts user experience)

And I'm deciding to create a new issue which has the title "Code style issue: Change "Ruler" to "Draw Line" in code" to make the changes to the code that I proposed separate from this issue. I feel that might help contributors to the project understand the difference between these tools.

I was off-topic and unclear with the way that I wrote the issue, and I apologize for that. The reason why I mentioned it was because I saw "Ruler" and "Draw Line" in different places when I was looking at the code, which confused me. Next time I'll just give details that are related to that specific issue, and put proposed changes in other issues separately.

I am a native English speaker, and I know the difference between these two names. I've explained the difference below.

-----
The definition of a ruler is that it measures the distance between 2 points, but doesn't draw a line on the note page.

For example, if I make a drawing of a house, and I want to see what the distance is from the left wall to the right wall, when I click on the ruler tool, it would have its starting point at the left wall, and I would drag it to the right wall, showing a line on the screen to see what 2 points I'm measuring, but not drawing it directly on the note page. After it's connected between the 2 points, it would report a measurement of distance, like "74 pixels" or "1.2 centimeters", so the actual distance of the walls of the house that I drew is the amount I measured with the ruler.

This would be like placing a separate object (ruler) on a piece of paper, but not drawing a line from the left wall to the right wall of the house.

The definition of a line drawing tool is that it draws a line on the note page from 2 points.
In the example, it would actually draw a line from the left wall to the right wall.

You can use a ruler to draw a line (a ruler is called a "straight edge" because you can put a pencil on the ruler and it neatly draws a line), but a ruler does not draw a line on a page.

In a similar drawing program called Photoshop, there are shape drawing tools that draw a shape on the page, but don't do the same thing as a ruler. Photoshop has both, and you can see the difference between these tools and why they're named differently.

Ruler tool: https://www.youtube.com/watch?v=AWHocqJwp1s

Draw line tool: https://www.youtube.com/watch?v=sot0gcdX_9Y

When I have a tool to draw a line on a computer, I usually want to draw an exact line, so I don't have to make it straight or be exact with my hand.


-----

I am fine if you keep the label as "Ruler", I just find that it's confusing for me to understand, because there is a difference, and it might help people and contributors to the project understand the difference between drawing a straight line on the screen versus using the ruler calibration tool in the settings menu.

Glad that you found a different issue with button shortcuts though! You're really making a lot of progress on getting Xournal++ to be more stable.

Please let me know if you don't understand what this means. I am happy to answer any questions you have.

**Comment by andreasb242** [comment]
My pull is merged, and see the comments in the other tickets.

Thank you for your work, and I'm now feeling bad to close also the third ticket...
One Thing: The naming can be changed with an IDE like Eclipse really simple, but you always have to carefully check, if it's really working after... (thats the main problem).
