### ISSUE TITLE
The saved file is not opened in the default language

### ISSUE THREAD

**Issue by ikanakova** [xournalpp/xournalpp#3433]
**Affects versions :**
 - OS: Windows 10
 - version of libgtk: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
The saved *.xopp file is not opened in the application in the default / selected language, but in English.

**To Reproduce**
1. Open Xournal++, the application is in the correct language (Czech). 
2. Save file as *.xopp.
3. Exit Xournal++.
4. Open *.xopp file.
5. Xournal++ is in English instead of Czech.

**Expected behavior**
Application in Czech even after opening the file.

**Screenshots of Problem**
New session:
![new](https://user-images.githubusercontent.com/38765251/135758436-fbd3779f-2b27-4c97-81d9-ac3adb8af9de.png)
Opened file:
![opened](https://user-images.githubusercontent.com/38765251/135758462-7f2f9ec9-79ae-4746-b817-e95787fcbdb1.png)

**Comment by ikanakova** [comment]
I think my issue is not related to issue #3371 but I think @emonhossainraihan's  is related to #3371.

**Comment by LittleHuba** [comment]
That is what happens when issues get mixed... I'll reopen it for now, but I think the issue has the same origin. Please join in on the other thread and try the fixes there as well. Please also provide the console output as mentioned in the other thread.

**Comment by LittleHuba** [comment]
> From the release notes of 1.1.0:
> 
> > Localizations to other languages than English only work when Xournal++ is executed from the Start menu or
> from the bin folder in which the executable is located (#3215).
> 
> The mixing between English and Czech comes from the fact that some strings come from Gtk (gtk30.mo) and some come from Xournal++ (xournalpp.mo). 

We should still leave this open as reminder to fix this.
