### ISSUE TITLE
Keyboard input not accepted

### ISSUE THREAD

**Issue by DaveDixon** [xournalpp/xournalpp#3446]
Text widget tool does not accept input from keyboard. I can type into a text document and cut-and-paste into the text tool, but keyboard input is ignored. Ubuntu 20.04, Xournal++ 1.1.0

**Comment by rolandlo** [comment]
Usually the cause for this problem is a device which should be mapped to "Mouse-Keyboard combo" in the input system panel of menu `Edit > Preferences`. See e.g. #3389

**Comment by yurivict** [comment]
Selecting "Mouse-Keyboard combo" helped.
However, this should be a default on desktops.
