### ISSUE TITLE
Autoreplace TeX commands for Unicode math

### ISSUE THREAD

**Issue by gjvnq** [xournalpp/xournalpp#3468]
**Is your feature request related to a problem? Please describe.**
Feature request.

**Describe the solution you'd like**
An auto replace chacracters with symbols feature like the AutoCorrect on LibreOffice.

Basically, whenever the users presses the space bar while typing text, the application checks the last few characters against an internal table and applies a replacement if a match is found. Example: if the users enters `\forall `, that segment is replaced with `∀`.

There would be some small UI indicator (like a trafic light near the zoom level) to show and toggle the autoreplace feature as well as a keyboard shortcut to toggle it.

The default replacement table would include:

  * The "commands" used by [unicode-math](https://ctan.org/pkg/unicode-math?lang=en)¹ (e.g. `\forall` becomes `∀`)
  * The [HTML entites](https://dev.w3.org/html5/html-author/charref) (e.g. `&phone` becomes `☎`)
  * The [VIM digraphs](https://vimhelp.org/digraph.txt.html) but probably prefixed by some character like `:`. (e.g. `:RT` becomes `√`)

¹ There is a [pdf with all the unicode-math symbols](https://ctan.dcc.uchile.cl/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf) but it is proabbly easier to extract that info from the [`unicode-math-table.tex`](https://ctan.dcc.uchile.cl/macros/unicodetex/latex/unicode-math/unicode-math-table.tex) file.

Aside from the above sources, it may be a good idea to include some basic symbols without any prefix. I thought of the following: (roughly from most to least important)
```tsv
--	–	U+2013	EN DASH
---	—	U+2014	EM DASH
----	―	U+2015	HORIZONTAL BAR
.-	·	U+00B7	MIDDLE DOT
.=	•	U+2022	BULLET
...	…	U+2026	HORIZONTAL ELLIPSIS
-a	ª	U+00AA	FEMININE ORDINAL INDICATOR
^o	°	U+00B0	DEGREE SIGN
-o	º	U+00BA	MASCULINE ORDINAL INDICATOR
*X	×	U+00D7	MULTIPLICATION SIGN
No	№	U+2116	NUMERO SIGN
S!	§	U+00A7	SECTION SIGN
%o	‰	U+2030	PER MILLE SIGN
%oo	‱	U+2031	PER TEN THOUSAND SIGN
.>	›	U+203A	SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
.<	‹	U+2039	SINGLE LEFT-POINTING ANGLE QUOTATION MARK
>>	»	U+00BB	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
<<	«	U+00AB	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
>'	‘	U+2018	LEFT SINGLE QUOTATION MARK
<'	’	U+2019	RIGHT SINGLE QUOTATION MARK
>"	“	U+201C	LEFT DOUBLE QUOTATION MARK
<"	”	U+201D	RIGHT DOUBLE QUOTATION MARK
+-	±	U+00B1	PLUS-MINUS SIGN
!?	‽	U+203D	INTERROBANG
?!	⸘	U+2E18	INVERTED INTERROBANG
P!	¶	U+00B6	PILCROW SIGN
tm	™	U+2122	TRADE MARK SIGN
(c)	©	U+00A9	COPYRIGHT SIGN
(r)	®	U+00AE	REGISTERED SIGN
(p)	℗	U+2117	SOUND RECORDING COPYRIGHT
Rx	℞	U+211E	PRESCRIPTION TAKE
->	→	U+2192	RIGHTWARDS ARROW
<-	←	U+2190	LEFTWARDS ARROW
<=	≤	U+2264	LESS-THAN OR EQUAL TO
>=	≥	U+2265	GREATER-THAN OR EQUAL TO
!!	¡	U+00A1	INVERTED EXCLAMATION MARK
??	¿	U+00BF	INVERTED QUESTION MARK
<==	⇐	U+21D0	LEFTWARDS DOUBLE ARROW
==>	⇒	U+21D2	RIGHTWARDS DOUBLE ARROW
-/>	↛	U+219B	RIGHTWARDS ARROW WITH STROKE
</-	↚	U+219A	LEFTWARDS ARROW WITH STROKE
1/4	¼	U+00BC	VULGAR FRACTION ONE QUARTER
1/2	½	U+00BD	VULGAR FRACTION ONE HALF
3/4	¾	U+00BE	VULGAR FRACTION THREE QUARTERS
1/7 	⅐	U+2150	VULGAR FRACTION ONE SEVENTH
1/9 	⅑	U+2151	VULGAR FRACTION ONE NINTH
1/10	⅒	U+2152	VULGAR FRACTION ONE TENTH
1/3 	⅓	U+2153	VULGAR FRACTION ONE THIRD
2/3 	⅔	U+2154	VULGAR FRACTION TWO THIRDS
1/5 	⅕	U+2155	VULGAR FRACTION ONE FIFTH
2/5 	⅖	U+2156	VULGAR FRACTION TWO FIFTHS
3/5 	⅗	U+2157	VULGAR FRACTION THREE FIFTHS
4/5 	⅘	U+2158	VULGAR FRACTION FOUR FIFTHS
1/6 	⅙	U+2159	VULGAR FRACTION ONE SIXTH
5/6 	⅚	U+215A	VULGAR FRACTION FIVE SIXTHS
1/8 	⅛	U+215B	VULGAR FRACTION ONE EIGHTH
3/8 	⅜	U+215C	VULGAR FRACTION THREE EIGHTHS
5/8 	⅝	U+215D	VULGAR FRACTION FIVE EIGHTHS
7/8 	⅞	U+215E	VULGAR FRACTION SEVEN EIGHTHS
0/3 	↉	U+2189	VULGAR FRACTION ZERO THIRDS
```

**Describe alternatives you've considered**
There is the TeX plugin but the UI is a bit annoying and it requires LaTeX to be installed.

**Comment by DUOLabs333** [comment]
How would this be better, then say, a Compse key (native on Linux, wincompose for Windows)?

**Comment by gjvnq** [comment]
1. It is easier to configure for most users. Editing the .Xcompose
file can be frightening.
2. It would be portable, so users can just copy their Xournal config
files between their machines if they use multiple operating systems.

**Comment by gjvnq** [comment]
That's amazing! What IME are you using?

**Comment by tattsan** [comment]
Thank you. I've never heard of IBus Typing Booster before.
> but is a bit cumbersome as it uses the Unicode character name for search.

It can be improved by creating an appropriate dictionary. You can create it yourself, or you can do a feature request at [their github site](https://github.com/mike-fabian/ibus-typing-booster).

**Comment by tattsan** [comment]
As for the `SKK`, I used `/implies` in the video to input `⇒`, but you can actually use `/=>` as well. `/` is the prefix for the conversion, and is shown as ▽ on the screen.
