### ISSUE TITLE
Keyboard input for text objects doesn't work

### ISSUE THREAD

**Issue by KobKobson** [xournalpp/xournalpp#3470]
Affects versions :

OS: Arch Linux x86_64, kernel release 5.14.11-arch1-1
Desktop environment: none, window manager i3, version 4.19.2 (2021-02-27)
Which version of libgtk do you use: 3.24.30
Version of Xournal++: 1.1.0, 9d1277de

Describe the bug

Keyboard input doesn't work for text input - neither for existing objects nor for newly created ones.
Strangely, paste, cut and delete still work, but backspace and all other keyboard inputs are ignored.

1. Open an arbitrary file
2. choose text tool
3. try to insert text

Debugging information will be added

**Comment by GscheadaHamme** [comment]
Thanks a lot, that solved the issue.
