### ISSUE TITLE
"Cut" and "Copy" do not work with the last nightly version

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#3472]
I installed xournalpp-1.1.0+dev-nightly.20211014-windows.exe on windows 10.
But "Cut" and "Copy" commands dont work (but work with xournalpp-1.1.0+dev-nightly.20211007-windows.exe)

**Comment by Technius** [comment]
@jetSett @LittleHuba Possible regression caused by #2870.

**Comment by LittleHuba** [comment]
We can set up a PR that reverts #2870 and create the installers. That way we can be sure if this is indeed what caused the regression.

**Comment by OtacilioNeto** [comment]
I confirm this bug on Ubuntu 20.04.3 LTS. It past images from transference area, but select -> copy -> past is broken
