### ISSUE TITLE
Cannot display Chinese characters in some pdf files correctly.

### ISSUE THREAD

**Issue by clq9920** [xournalpp/xournalpp#3474]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS:  Windows
 - Which version of libgtk do you use
     - 3.24.30 
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.0 dev 816b113d 
 - Installation method: official release

**Describe the bug**
Cannot display  Chinese characters in some pdf,the pdf is generated by latex(https://github.com/ElegantLaTeX/ElegantBook), other pdf software displays normally.
**To Reproduce**
1. Open [elegantbook-cn.pdf](https://github.com/xournalpp/xournalpp/files/7345472/elegantbook-cn.pdf) by Xournal.

**Expected behavior**
Display  Chinese characters normally.
**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/48880318/137305817-ff5b5373-6e17-479a-ac96-a5a3492377bf.png)

**Additional context**

This is a great project.

**Comment by DUOLabs333** [comment]
Interestingly enough, Okular does not display the characters either.

**Comment by LittleHuba** [comment]
Package the right files in terms of the PDF or Xournal++?

**Comment by LittleHuba** [comment]
Please check out #3477 where you will find an installer with a potential fix. Please install this version and report if it solves the bug.

**Comment by clq9920** [comment]
> Please check out #3477 where you will find an installer with a potential fix. Please install this version and report if it solves the bug.

It has solved the bug (windows).
