### ISSUE TITLE
Add close/quit button that can be added to the toolbar

### ISSUE THREAD

**Issue by mvgorcum** [xournalpp/xournalpp#3514]
**Is your feature request related to a problem? Please describe.**
I would like to basically only use xournal++ in full screen mode on my touchscreen device (open a PDF from another app and open it full screen in xournal++ immediately). This can probably work fine, except there is no way to exit or close the pdf with a touchscreen on full screen.

**Describe the solution you'd like**
Adding an icon that closes the app that can be dragged onto the toolbar should probably be enough to work with.

**Describe alternatives you've considered**
Maybe a touch gesture could work, and of course I can just click the exit full screen button and then close the application normally, but that makes the whole experience less seamless.

**Comment by bhennion** [comment]
Closing as subsumed by #3669
