### ISSUE TITLE
Drawing (rectangle etc) not possible after Text entry

### ISSUE THREAD

**Issue by glassel** [xournalpp/xournalpp#3516]
(Please complete the following information, and then delete this line)

**Affects versions : 1.1.0
 - OS: Ubuntu 20.04 LTS
 - (Linux only) Desktop environment: libgtk 3.24.25
 - Version of Xournal++: 1.1.0
 - Installation method: snap

**Describe the bug**
selection of drawing option (rectangle, ellipse etc) and activation of the drawing tool is possible after start, but not anymore
after 'Text' has been used. Buttons and options in Tools menu are then greyed out.

**To Reproduce**
1. Step 1 Start xournalpp on some pdf
2. Step 2 Annotate with 'Text'
3. Try to select drawing tool with button: no response,  Text button stays selected

Expected: Draw button should be activated when clicked, Mouse should do the selected drawing option, e.g. draw line

(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by bhennion** [comment]
@glassel Could you give us a screenshot of Xournal++ when those buttons are greyed out?

**Comment by glassel** [comment]
Dear Benjamin,
    the first answer clarified the problem. I have to activate the pen to 
use the shapes. I was only confused because in a previous version drawing 
was possible w/o activating the pen, by selecting 'default tools' in the 
menu. Now I realize that this was a work-around (of a non-existing 
problem).

         Cheers ... Peter

On Fri, 29 Oct 2021, Benjamin Hennion wrote:

> 
> @glassel Could you give us a screenshot of Xournal++ when those buttons are greyed out?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> [ACP2S6NPBGA6FUXXXXBWEWTUJOERVA5CNFSM5G2CB3VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHDXHAGA.gif]
> 
> 
>

-----------------------------------------------------------------
| Peter Glässel                 ***@***.*** |
| Physikalisches Institut der Universität Heidelberg            |
| Im Neuenheimer Feld 226                                       |
| D-69120 Heidelberg                                            |
| Telefon                                                       |
| official: +49-6221-5419517    CERN mobile +41-764873426       |
| private:  01749775666                                         |
-----------------------------------------------------------------
