### ISSUE TITLE
Error en el formato de los  cuadros de texto

### ISSUE THREAD

**Issue by JosueMV** [xournalpp/xournalpp#3526]
(Please complete the following information, and then delete this line)

**1.1.0 :**
 - OS: [Windows 8.1]

 - Which version of libgtk do you use 3.24.29
     
 - Version of Xournal++: [ 1.1.0]
    
 - Installation method: [installación por ejectuble de windows.]

**Describe the bug**
El texto agregado pierde el formato, y no se visualiza bien, aparecen cuadrados en vez letras

**To Reproduce**
Usualmente sucede cuando se abre un archivo xopp creado previamente que contiene cuadros de texto. 
No hay pasos porque sucede de manera espontánea y sólo en algunas ocasiones

**Expected behavior**
Parece ser que los cuadros de texto pierden el tipo de letra y tamaño predefinido con los que fueron creados

**Screenshots of Problem**
![Captura de pantalla (15)](https://user-images.githubusercontent.com/88124777/139510179-d882e9f4-42cc-430c-8d51-b97dc07a0a69.png)

**Additional context**
Los cuadros de texto recuperan su forma al cambiar el tipo y tamaño de letra

**Comment by bhennion** [comment]
Duplicate of #3371.
