### ISSUE TITLE
Opción de agregar numeración de página

### ISSUE THREAD

**Issue by JosueMV** [xournalpp/xournalpp#3527]
Me gustaría que fuera agregada una función que agregue numeración a las paginas

**Additional context**
Me gustaría que la función agregue a cada pagina un numera de manera automática o que incluya opciones para que el usuario elija cuales numerar. Además sea posible elegir donde colocar el numero, en el pie de página o en la cabeza de página, y que pueda ser posible elegir a ubicación del numero: centrado, a la izquierda o la derecha. Finalmente, si fuera posible agregar algunos estilos distintos de formato del texto o numeración

**Comment by bhennion** [comment]
Duplicate of #1053.
