### ISSUE TITLE
Cannot draw when using the touchscreen, just scroll

### ISSUE THREAD

**Issue by patri9ck** [xournalpp/xournalpp#3529]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: No DE, just BSPWM
 - `xournalpp --version`:
 ```
Xournal++ 1.1.0
└──libgtk: 3.24.30
```
 - Installation method: pacman, official repository

**Description**
I don't think it is a bug. I hope it is a configuration problem. I use a notebook with a touchpad and a touchscreen. When I use the touchpad, Xournal++ works fine. But when I try to draw something on my touchscreen, I can only scroll. Nothing is drawn. I think I have the same issue as #683 but I couldn't figure out how to fix it by reading the issue.

**Comment by bhennion** [comment]
There is a "Enable touch drawing" tickbox in the Touch screen tab of the configuration windows. Is it enabled?

**Comment by patri9ck** [comment]
That's it, thank you.

**Comment by yurigba** [comment]
> There is a "Enable touch drawing" tickbox in the Touch screen tab of the configuration windows. Is it enabled?

Also worked for me on my RasPad 3 with Fedora Phosh 39.
