### ISSUE TITLE
Erasing dotted line causes rendering artifact

### ISSUE THREAD

**Issue by Ninja-Koala** [xournalpp/xournalpp#3537]
**Affects versions :**
```
>> xournalpp --version
Xournal++ 1.1.0
└──libgtk: 3.24.30
```
Installed from archlinux repos and used with i3wm (X11).

**Describe the bug**
When using the Pen with dotted style (or dashed...) and the line (or ellipse...) tool and then erasing
the line partially with the eraser in standard mode, the wrong pen style flickers on and off.

**Expected behavior**
The pen style is maintained during erasing.

**Screenshots of Problem** here.
![Screenshot from 2021-11-03 18-36-14](https://user-images.githubusercontent.com/8513665/140165504-c3e37daf-5909-42f5-b929-6a1d70f7294b.png)

**Comment by bhennion** [comment]
Thanks for reporting this. A partial fix is in the works (see #3532).
