### ISSUE TITLE
Stamp Button

### ISSUE THREAD

**Issue by mptrv** [xournalpp/xournalpp#3543]
Hi!

A useful resource is a **"stamp button"**, like the one in Moodle (see image below).

![image](https://user-images.githubusercontent.com/11620491/140526413-8076cf4e-75db-4926-9c3a-46e1970b40f2.png)

The images of the stamp could be fixed or customizable.

Some applications should be: in correcting tests, adding signatures, quickly point text or graphic material.

Best regards!

**Comment by rolandlo** [comment]
That would sound like a useful addition to me.

**Comment by bhennion** [comment]
This looks like a duplicate of #1652. Closing this in favor of #1652, as a (temporary) workaround is proposed therein.

**Comment by mptrv** [comment]
Ok.
