### ISSUE TITLE
Unable to open PDF with capitalized extension "foo.PDF"

### ISSUE THREAD

**Issue by Cris70** [xournalpp/xournalpp#3548]
**Affects versions :**
 - OS: Linux openSuse Tumbleweed
 - (Linux only) Desktop environment: KDE X11
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
Cannot open an otherwise perfectly working PDF.
This PDF (attached) can be opened without problem with Okular and with Master PDF Editor 5.
Opening with Xournal++ I get an xmlparser error (see screenshot below).

**To Reproduce**
1. Open the attached PDF file with Xournal++

**Expected behavior**
The file should be opened and shown by Xournal++

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/5107224/140626571-f0f134e3-cf95-4a5a-b341-e56b2f6e9e6e.png)

[Dichiarazione sostitutiva certificato di morte pdf_9 T.PDF](https://github.com/xournalpp/xournalpp/files/7491392/Dichiarazione.sostitutiva.certificato.di.morte.pdf_9.T.PDF)

**Comment by Cris70** [comment]
Same screenshot but in English:
![image](https://user-images.githubusercontent.com/5107224/140626687-14100d6e-2a81-4bc1-8fca-29986d56029f.png)

**Comment by tattsan** [comment]
If you rename the file *.PDF to *.pdf, the error will disappear.

**Comment by Cris70** [comment]
> If you rename the file `*.PDF` to `*.pdf`, the error will disappear.

Doh! It's true... I am stunned.
Why is that?
A fix is due, I think, even if the problem is easy to circumvent.

**Comment by tattsan** [comment]
> A fix is due, I think, even if the problem is easy to circumvent.

I agree.

**Comment by suisseWalter** [comment]
it works if you choose "annotate PDF" from the FILE menu(choosing "all files" in the select dialog). I think the problem has to do that it tries to open it as a xopp file if the file ending isn't ".pdf" (no caps no other characters) but not sure about that. with "annotate PDF" you can open any pdf file, no matter the name.
