### ISSUE TITLE
Cannot write with the Text tool

### ISSUE THREAD

**Issue by Cris70** [xournalpp/xournalpp#3550]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux openSuse Tumbleweed
 - (Linux only) Desktop environment:  KDE X11
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
When I try to write on a PDF using the "Text" tool, nothing happens. The cursor blinks but text is not written.
I can copy/paste, however.

**To Reproduce**
1. Open a PDF with Xournal++
2. Click on the Text tool in the toolbar
3. Click in a spot on the PDF document: a text box will appear with a blinking cursor
4. Try to write by using the keyboard

**Expected behavior**
Text should appear in the text box. Instead, nothing happens.

**Additional context**
If, instead of trying to write, I copy text from another application and paste (CTRL+V) in Xournal++, text correctly appears.
A previous release worked without problems.
It may be a problem specific to the openSuse official release.

**Comment by tattsan** [comment]
Does #3377 help you?

**Comment by Cris70** [comment]
> Does #3377 help you?

Unfortunately not :-(
Deleting (renaming) the settings-related files does not work, and using the appimage does not work either.

**Comment by LittleHuba** [comment]
You are most likely using a wireless mouse keyboard combo that communicates via a single dongle. Please go into the preferences dialog to the tab "Input System" and select the appropriate input device class for this device. You want `Mouse+Keyboard Combo".

**Comment by Cris70** [comment]
> You are most likely using a wireless mouse keyboard combo that communicates via a single dongle. Please go into the preferences dialog to the tab "Input System" and select the appropriate input device class for this device. You want `Mouse+Keyboard Combo`.

Hey, thank you!! It worked a treat!!
That's not my case BTW, I do not have a mouse+keyboard wireless combo. I have a KVM to share mouse, monitor and keyboard between two computers, but that's probably the same if seen from the attached computer perspective.

**Comment by tattsan** [comment]
I should have quoted  https://github.com/xournalpp/xournalpp/discussions/3377#discussioncomment-1297628 .

By the way, I find this question to be very common.
I think it might be better to make `Mouse+Keyboard Combo` the default for keyboard-like devices.

**Comment by LittleHuba** [comment]
It wouldn't hurt to fold this combo into the mouse class. It has no impact on the behavior of the mouse and as you already mentioned, this question is quite common.
