### ISSUE TITLE
Text can't be pasted into the search box - it gets added to the document instead

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#3556]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: FreeBSD
 - (Linux only) Desktop environment: xfce4
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: package

**Describe the bug**
After some text was painted using the text function and Ctrl-F to open the search box text pasted into the focused search box gets added to the document itself.

**Comment by personalizedrefrigerator** [comment]
Can confirm. Right-click paste works but ctrl+V pastes in the document.

**Comment by bhennion** [comment]
Fixed on master
