### ISSUE TITLE
Installing package after running tests includes GoogleTest files

### ISSUE THREAD

**Issue by MithicSpirit** [xournalpp/xournalpp#3561]
**Affects versions :**
 - OS: Only tested on Linux (Arch)
 - Version of Xournal++: 269167da8a0a7a9c3322157220cb8676ca0fefaa or newer
 - Installation method: Build from source

**Describe the bug**
Installing after running tests causes gtest and gmock files to also be installed, such as `/usr/include/gmock/*`, `/usr/include/gtest/*`, `/usr/lib/cmake/GTest/*`, etc.

**To Reproduce**
1. Build xournalpp with `cmake -DCMAKE_INSTALL_PREFIX="/usr/" -DENABLE_GTEST=ON ..; cmake --build .`
2. Run tests with `make test-units; make test`
3. Install with `make install`

**Expected behavior**
GoogleTest files should not be included in order to not conflict with system files.

EDIT: oops just noticed I still had the flag for `CPPUNIT` instead of `GTEST`. Guess I copied from the old script before I tried patching it for `GTEST`.

**Comment by bhennion** [comment]
Thanks for reporting this!

@idotobi Have you seen this? Would you mind having a look?

**Comment by idotobi** [comment]
@MithicSpirit : Thanks for reporting!
@bhennion : Thanks for pinging!

Who would have thought that GoggleTest by default installs itself (https://github.com/google/googletest/blob/1b18723e874b256c1e39378c6774a90701d70f7a/CMakeLists.txt).

I'll fix that right away.

**Comment by idotobi** [comment]
@MithicSpirit : If you want you can try out the test available at https://github.com/xournalpp/xournalpp/pull/3576. As far as I tested this should fix it.
