### ISSUE TITLE
Automatically export to svg (or bind a key to do it) 

### ISSUE THREAD

**Issue by jfab-123** [xournalpp/xournalpp#3565]
**Is your feature request related to a problem? Please describe.**
I want to have a quick way of drawing diagrams in latex. I have a snippet in my text editor (vim) which works this way: 

I type ```xournal``` and press ```<tab>```. Then the snippet opens xounralpp and creates a file based on the name I gave it. I now can draw something, and then export it to svg. However, I find annoying always having to press ```<c-e>``` and then open a menu, select ```export to svg``` and a ton of other options in order to export to svg. 

**Describe the solution you'd like**

I want to configure a shortcut so that whenver I press ```<c-s>``` for example, the figure is automatically saved and automatically exported to svg in the same directory that  the .xopp file is saved

**Describe alternatives you've considered**

I have the setup I want with inkscape, however xournalpp gives me better functionality to draw by hand my figures. I have also considered using the terminal application of xournal but it is the same thing: whenever I save a figure.xopp, I have to go into the directory in which it is located and type:

``` xournalpp figure.xopp -i=figure.svg --export-no-background```

**Additional context**
Here is a video of my setup for better understanding. I first show the setup for inkscape and then for xournalpp: 

https://user-images.githubusercontent.com/81712003/141533348-a5173a70-6c2a-4f75-ac80-00641b1e4975.mp4

**Comment by rolandlo** [comment]
I think we should include some exporting capabilities to our plugin API. That would probably benefit lots of users. Your workflow (with inkscape) looks quite comfortable.

**Comment by jfab-123** [comment]
Thanks! Hopefully it can be made soon

**Comment by bhennion** [comment]
For whoever does this, see #2618 for a PR implementing silent export jobs (I guess we'll want the plugins to be able to export in the background).

**Comment by rolandlo** [comment]
@jfab-123 Please take a look at #3566
