### ISSUE TITLE
xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thilop** [xournalpp/xournalpp#3570]
**Affects versions :**
 - OS: Linux Mint 20.2
 - (Linux only) Desktop environment: MATE
 - Which version of libgtk do you use
   3.24.20
 - Version of Xournal++: 1.1.0

 - Installation method: Debian package

**Describe the bug**
If I started the binary xournalpp I got 
"xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory"

**To Reproduce**
1 start "xournalpp"

**Expected behavior**

Start the application, opening a window.

**Additional context**

Fix that I did:
```
$ cd /usr/lib/x86_64-linux-gnu
$ sudo ln -s libzip.so.5.0 libzip.so.4
```
Now its just working. So maybe the package should just do the symbolik link? I havent played a lot with the app, but it seems to be working. I guess with Ubuntu should be a solution, too.

**Comment by rolandlo** [comment]
Which .deb package did you download exactly? Maybe you got the wrong one. Linux Mint 20.2 is based on Ubuntu 20.04 (focal fossa), so you should have installed that one. According to the logs (of the nightly releases) the focal fossa version should link against libzip 5, not libzip 4.
We had some issues with that prior to the 1.1.0 release, but it was fixed upstream then, see  [this issue](https://github.com/actions/virtual-environments/issues/1084)

**Comment by thilop** [comment]
Oh I downloaded the Debian package, sorry! With the Ubuntu focal fossa it works allright

**Comment by rolandlo** [comment]
@usernamenottakenyet Do you have `libgtksourceview-4-0` installed? 
What is the output of the following commands:
```term
ldd /usr/bin/xournalpp | grep source
```
and
```term
apt search libgtksourceview-4
```
executed in the terminal?

**Comment by efernbach** [comment]
With Ubuntu 24.04.1 I downloaded the Debian/Ubuntu .deb and installed with App center. The result: when starting the app, nothing happens, when starting it in terminal (xournalpp) the error described above appears.

**Comment by andrewkrck** [comment]
```
wget http://mirrors.kernel.org/ubuntu/pool/universe/libz/libzip/libzip5_1.5.1-0ubuntu1_amd64.deb
sudo apt install ./libzip5_1.5.1-0ubuntu1_amd64.deb
```
Try this
