### ISSUE TITLE
Sidebar page preview stuck and not responding

### ISSUE THREAD

**Issue by fabian-thomas** [xournalpp/xournalpp#3585]
**Affects versions :**
I guess all versions.

**Describe the bug**
When annotating a pdf with the same amount of pages as the document edited before the sidebar page preview is stuck and does not respond on clicking on page previews.

**To Reproduce**
1. Open a fully new Xournalpp instance
2. Annotate any pdf with exactly one page

**Comment by bhennion** [comment]
Fixed via #3593 via #3599
