### ISSUE TITLE
No autosave folder

### ISSUE THREAD

**Issue by b1sk1** [xournalpp/xournalpp#3604]
Hello! I'm not sure if my question is relevant, because I am not experienced Ubuntu user, but I have a following problem:

When I go Edit -> Preferences -> Autosaving, I have Autosaving enabled every minute. An app is saying "if the file was not yet saved you can find it in your home directory, in ~/.xournalpp/autosave". 

I'm writing a few lines with pencil in file, which was automatically created with a start of the app. Then I wait for 1-2 minutes and type: 
`cd ~/.xournalpp`
in my terminal. After that I have an answer:
`bash: cd: /home/artyom/.xournalpp: No such file or directory`

Well, I thought that autosave directory might be located somewhere else. As far as I know, autosave files should have .xopp extension. I tried to run a search for any .xopp files from a root folder, but found nothing. Search for "autosave" brought me the same result.

Could someone please help me with the problem? What should I do to view autosaved files?

P.S. If it matters, I use Ubuntu 20.04.3 LTS, and Xournal++ was installed via snap. I was also using Stable PPA installed as shown in readme.md of this repository, but faced the same issue. Reinstall was caused by a problem described in #3510. It appeared after I set "autoloading of most recent file on application startup" enabled.

**Comment by personalizedrefrigerator** [comment]
Please check `~/.config/xournalpp` and `~/.local/xournalpp`.

**Comment by bhennion** [comment]
This wrong documentation will be corrected with #3587 (and the subsequent translation updates).

**Comment by b1sk1** [comment]
> Please check `~/.config/xournalpp` and `~/.local/xournalpp`. The configuration directory for Xournal++ was changed from `~/.xournalpp` to `~/.config/xournalpp`, so this might be outdated documentation.



> This wrong documentation will be corrected with #3587 (and the subsequent translation updates).

Huge thanks! It really helped. 

Old autosave files for Xournal++ installed via
`sudo add-apt-repository ppa:apandada1/xournalpp-stable`
`sudo apt update`
`sudo apt install xournalpp` 
are in `~/.config/xournalpp/autosave`.

New ones for Xournal++ installed via snap are in `~/snap/xournalpp/62/.config/xournalpp/autosave`.

Now I can view all of autosaved files. Issue is closed.

**Comment by jc-costa** [comment]
> 

Thank you so much!
