### ISSUE TITLE
Palette migration fails, leading to crash

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#3606]
**Affects versions :**
 - master [1496256](https://github.com/xournalpp/xournalpp/commit/149625635708e5b08eb635a934c4dc7d160726c2)
 - OS: ArchLinux

**Describe the bug**
Trying to run the latest master, I get a popup saying
```
There has been a problem parsing the color palette file at /home/benjamin/.config/xournalpp/palette.gpl

What happened:
The line 4 is malformed.
What to do:
Please fix your palette file, or rename it so xournalpp creates a new default palette file for you. This file can then be used as a template.
What will happen now:
The application will start with the default color palette.
```

The app then crashes.

I certainly never modified the incriminated palette file. Here it is, just in case [palette.gpl](https://github.com/xournalpp/xournalpp/files/7586110/palette.txt)

**To Reproduce**
Launch and see...

**Additional context**
The logs:
[CLI_log.txt](https://github.com/xournalpp/xournalpp/files/7586130/CLI_log.txt)
[errorlog.20211123-072740.log](https://github.com/xournalpp/xournalpp/files/7586133/errorlog.20211123-072740.log)

@idotobi Could you have a look?

**Comment by bhennion** [comment]
BTW, removing the incriminated palette file and running the app just recreates the palette faile and crashes too.

**Comment by idotobi** [comment]
@bhennion : This is very strange.

For me it's running (also Arch, and same commit) and I even have a testcase for loading the default palette which also ran on the CI (just double checked).

Two questions:
 1. When you click on OK in the dialog xournalpp does not start, right? (As at least in my case it does)
 2. Could you send me the following for comparison (**via a private message** as this might contain some sensitive info)  `cat /proc/${xournalpp_procID}/environ | tr \\0 \\n`

The only difference I can think of that our two systems might have is the environment variables :thinking:

**Comment by bhennion** [comment]
The test is running fine here too!

As to your questions:
1. when I click OK, the app crashes.
2. sent it to you via PM. I'm running KDE X11 (should is matter).

**Comment by bhennion** [comment]
@idotobi Did you try removing the palette file in your .config to see if it runs as expected? I imagine you already have a custom one :-)

**Comment by LittleHuba** [comment]
It runs without issues on Arch with KDE Wayland. So this is definitely something specific to your device/setup...

**Comment by LucieBlanvillain** [comment]
I'm having the same problem on Ubuntu 20.04.3 LTS, running GNOME 3.36.8. I had to download an older version from snap to be able to run the app again. I never changed the default palette. I also get the exact same ALSA lib error messages.

**Comment by LittleHuba** [comment]
@bhennion you should have your device set up for debugging. Could you check what the underlying error is?

That should speed up the process tremendously!

**Comment by bhennion** [comment]
Yes, will do, hopefully later today

**Comment by idotobi** [comment]
@bhennion : Thanks for the `.env` dump.

@bhennion , @LucieBlanvillain : Could it be that both of you have set `LANG=fr_FR.UTF-8`. That's the most suspicious difference I found on a quick check.

If yes could you try running it with `LANG=en_US.utf8 $YOUR_XOURNALPP_BIN` or similar?

**Comment by LucieBlanvillain** [comment]
I tried it and sadly got the same result as without `LANG=en_US.utf8`

**Comment by idotobi** [comment]
> @idotobi Did you try removing the palette file in your .config to see if it runs as expected? I imagine you already have a custom one :-)

@bhennion :Good ponint. I also tried it and on my system it's working :thinking:

**Comment by LucieBlanvillain** [comment]
I'm starting to think this might be an issue with ALSA, my system doesn't detect my microphone or sound output anymore.

**Comment by rolandlo** [comment]
Like @idotobi I don't get any errors. Deleting the `palette.gpl` also doesn't create trouble.

**Comment by bhennion** [comment]
(Oh, BTW, the tests do pass because the global locale is not set in the test units!)

**Comment by idotobi** [comment]
> Uh? Do you still have the french locale generated?

@rolandlo : I also had the problem. Following the [archwiki](https://wiki.archlinux.org/title/Locale#Generating_locales) you need to
 1. comment out the respective line in `/etc/locale.gen`
 2. then run `locale-gen`

Then the bug is reproducible.

**Comment by idotobi** [comment]
@bhennion : You're right! :exploding_head:

![Peek 2021-11-23 20-12](https://user-images.githubusercontent.com/16611056/143088962-4ba820ed-d3d9-4e0b-a7fb-b7884942950c.gif)

TIL: space is not the same as space.

**Comment by bhennion** [comment]
See #3606 for a fix.

**Comment by ersiq** [comment]
I have the same problem. Yesterday everything was OK, today after update it crashes. Renaming o deleting palette.gpl doesn't work. The app doesn't open.

**Comment by idotobi** [comment]
> See #3606 for a fix.

I think you meant #3610 :wink:

**Comment by bhennion** [comment]
@ersiq @LucieBlanvillain For now, you should be able to run the app by running `LANG=C xournalpp`, or by building with the patch from #3610.
This patch should land in master soon enough anyway.
