### ISSUE TITLE
some toolbar configurations reset after switching the config or restarting

### ISSUE THREAD

**Issue by emhl** [xournalpp/xournalpp#3609]
**Affects versions :**
 - OS: Pop!_os 
 - (Linux only) Desktop environment:  X11 GNOME
 - Which version of libgtk do you use 3.24.30
 - Version of Xournal++: 1.1.0 9d1277de-dirty
 - Installation method: Flatpak

**Describe the bug**
some toolbar configurations reset after switching the config or restarting

**To Reproduce**
1. create a custom toolbar config or duplicate an existing one
2. enter the edit mode for your toolbar
3. move some buttons around
4. exit xournal++ or change to another toolbar config
5. reopen xournal++ or change back to your custom toolbar config

**Expected behavior**
the positions of the items in the toolbar shouldn't change

**Screenshots of Problem**
this
![image](https://user-images.githubusercontent.com/36165088/143083493-0c4a84aa-9786-48dd-8aea-6da22fbd431d.png)

always gets reset to this
![image](https://user-images.githubusercontent.com/36165088/143083423-42e10e78-28d9-4675-9f62-89e044cc768d.png)

**Comment by tylerlm** [comment]
I'm experiencing this too -- all the separators load one position forward from what they were:

![before](https://user-images.githubusercontent.com/4705507/148074960-719c31f0-280d-45d9-8d0f-6799ae6dfce6.png)

![after](https://user-images.githubusercontent.com/4705507/148075008-815ed089-b2dc-4425-953b-883ec0343b36.png)

At some point icons were changing position too, the only way to prevent it was to remove all separators from the toolbar.

Perhaps related to #2970 and #2980?

 (Linux, built from 1.1.0-hotfix.1)

**Comment by bhennion** [comment]
I think this has been fixed in 1.1.1 by #2980. Please reopen if I'm wrong.
