### ISSUE TITLE
Make toolbar button to show sidebar

### ISSUE THREAD

**Issue by thekswenson** [xournalpp/xournalpp#3612]
As far as I can tell, there are two ways to open the sidebar:

1. use the view menu "Show Sidebar"
2. press the F12 hotkey

I use xournalpp in fullscreen mode with my stylus and no keyboard, as though my tablet is a piece of paper. In this setup the second option is not possible. This means that when I want to navigate through the thumbnails I need to:

1. exit fullscreen
2. use the stylus to open the file menu
3. click on the "Show Sidebar" menu item

It is easy to then close the sidebar with the x in the corner. Things would be much easier if there were a button that I could place where I'd like in the sidebar.

**Comment by bhennion** [comment]
Closing as subsumed by #3669
