### ISSUE TITLE
Cursor size

### ISSUE THREAD

**Issue by jayu9493** [xournalpp/xournalpp#3615]
The cursor size when I choose pen is very small. Is there any way i can increase tha
![Screenshot from 2021-11-24 23-05-18](https://user-images.githubusercontent.com/87773845/143288277-a15378f6-9381-4851-9308-c827ef811920.png)
t?

**Comment by Photon89** [comment]
I don't see a cursor at all on the screenshot. :confused:

**Comment by jayu9493** [comment]
> I don't see a cursor at all on the screenshot. :confused: 

Yes, that is the issue.sometime it shows arrow and sometimes very small dot. For windows there is app called pen-attention for linux there are not.

**Comment by Photon89** [comment]
It looks like you chose it to show the dot. :smiley: You can choose a pen icon instead though:
![Xournal++ Preferences_001](https://user-images.githubusercontent.com/1191480/143681060-ac70297e-9097-4144-99ac-581fc0a31614.png)

**Comment by Febbe** [comment]
@jayu9493 did this solve you issue?

**Comment by jayu9493** [comment]
> @jayu9493 did this solve your issue?

yes,I am closing this issue log. Thanks bud.

**Comment by Photon89** [comment]
Great, you're welcome!
