### ISSUE TITLE
f1=color in templates not working

### ISSUE THREAD

**Issue by willggv** [xournalpp/xournalpp#3617]
I've just installed the linux version 1.1.0 and my custom template (see below) does not accept the line color

[XournalappGraphGreen]
name=Graph-Green 
name[de]=Kariert mit rand
format=graph
config=f1=2e6562,m1=40,rm=1,r1=20

With the version 1.0.2 it worked.

**Comment by robinp7720** [comment]
You will need to select the paper background again after changing the template. The drop down applies the template to the current page. If the template is changed, it must be applied again.

If the page background is darker then middle gray, the color defined by `af1` is used instead.

**Comment by MichelReims** [comment]
I did not know the option for the lines color. Do you know other options ?

**Comment by rolandlo** [comment]
Please check [this description](https://github.com/xournalpp/xournalpp/issues/2137#issuecomment-799956788).

**Comment by rolandlo** [comment]
Closing the issue, since the question is answered and the problem should be solved.
