### ISSUE TITLE
Refactor hardcoded Colors into one single include/source file.

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#3625]
The change looks good.

I'm just wondering if this should be taken from the default palette :thinking: in a followup PR.
Do you know for what these Colors are used in the application?

_Originally posted by @idotobi in https://github.com/xournalpp/xournalpp/pull/3623#discussion_r757884747_

**Comment by RuleOfThrees** [comment]
I'd like to work on this one, if it's ok!
