### ISSUE TITLE
Option to autosave after a change is made to the document

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3629]
**Is your feature request related to a problem? Please describe.**
The current autosave feature will only save periodically, with the quickest period being 1 minute.

**Describe the solution you'd like**
I would like for there to be an option to autosave immediately after any change is made to the document.

**Comment by rolandlo** [comment]
Since the file format currently does not allow incremental save and saving the full document can take a few seconds, your suggestion is currently not feasible.

**Comment by Febbe** [comment]
Why you require this feature? Only, when your computer crashes, this can be a problem.
Also, the current file format and the data representation requires a complete lock of the document. This will interrupt input.
Therefore, your feature is not implementable.

The only solution which could work is, to wait, e.g. 5 seconds after an input. But if you want to draw directly after the 5s, the document will be frozen until the autosave is done.

**Comment by Febbe** [comment]
Closing, since we can't do anything about this :/.
