### ISSUE TITLE
Strokes sometimes disappear when recognized as lines by the recognizer

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#3642]
**Affects versions :**
 - OS: Linux
 - Ubuntu 21.10
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0+dev (from December 1, 2021)
 - Installation method: PPA
 
**Describe the bug**
When I draw strokes that are fairly straight and (should) get recognized as lines, those lines sometimes disappear immediately after the pen tip is released.

**To Reproduce**
1. Turn on the shape recognizer.
2. Draw lots of (nearly) lines by hand
3. Observe that some of them disappear right when they should be recognized

**Expected behavior**
The lines should not disappear.

**Additional context**
It is probably a regression, either from #3042 or #3285

**Comment by bhennion** [comment]
I can reproduce.

This creates a very weird file once saved: in this example, the first 3 strokes are shown, but the 4th disappeared:
```
<stroke tool="pen" ts="0" fn="" color="#008000ff" width="0.71281455">278.92842945 196.16156419 278.92842945 95.97742992</stroke>
<stroke tool="pen" ts="0" fn="" color="#008000ff" width="0.79135091">312.43711457 110.39304640 312.43711457 195.37485777</stroke>
<stroke tool="pen" ts="0" fn="" color="#008000ff" width="1.89231725 1.71940800">355.03609679 119.19620917 385.56142803 215.74422242</stroke>
<stroke tool="pen" ts="0" fn="" color="#008000ff" width="0.88823520 -1.96169226">387.50834931 90.20150165 423.01232008 193.38708575</stroke>
```

There are two very weird things in this file:

1. The 3rd stroke has two width values (corresponding to `stroke.width` and `stroke.points.front().z`). There should only be one corresponding to `stroke.width`. `stroke.points.front().z` should be `Point::NO_PRESSURE`.
2. The 4th stroke has two width values and the second is negative! This explains the vanishing of the stroke.

Remains to find out why this is happening.

**Comment by bhennion** [comment]
I think the issue here is two-fold:

1. https://github.com/xournalpp/xournalpp/blob/f7c0750af76531132cebf917a5f2262be877e7cd/src/core/control/shaperecognizer/ShapeRecognizer.cpp#L313-L319
The points added here should not have a pressure value at all
2. #3643 gives points negative pressure values, thus making them disappear
