### ISSUE TITLE
Shortcut for exporting directly with no ruling

### ISSUE THREAD

**Issue by SinTan1729** [xournalpp/xournalpp#3645]
**Is your feature request related to a problem? Please describe.**
I always write with ruling on but export to PDF with no ruling. But for that I have to select the option for no ruling every single time while exporting, which can get really frustrating when I have to make small edits just before a submission of assignment for example.

**Describe the solution you'd like**
Let me configure a shortcut for exporting directly without ruling.

**Describe alternatives you've considered**
Let me choose default export settings/remember last settings.

**Comment by rolandlo** [comment]
This will be possible after #3566 has been merged.

**Comment by rolandlo** [comment]
Closing the issue as this can now be done via a plugin (small modification of the [Export plugin](https://github.com/xournalpp/xournalpp/tree/master/plugins/Export)). See [website](https://xournalpp.github.io/guide/plugins/plugins/) for more infos on plugins.
