### ISSUE TITLE
Floating point numbers are loaded incorrectly from pagetemplates.ini

### ISSUE THREAD

**Issue by DielN** [xournalpp/xournalpp#3655]
**Affects versions :**
 - OS: Ubuntu
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - latest of 1.1-release branch (01737d1)
 - Installation method: from source

**Describe the bug**
Floating point numbers in page template configs are converted to integers when they're loaded by Xournal++. That is a problem because the line width config needs floating point numbers to be set in a meaningful way.

I think the problem is located [here](https://github.com/xournalpp/xournalpp/blob/bc5f6047910a9978b440a6234eaebd831062bdd4/src/core/view/background/BackgroundConfig.cpp#L45). The string is converted to a (unsigned) long, truncating the decimal places. That method is used by [BaseBackgroundPainter](https://github.com/xournalpp/xournalpp/blob/bc5f6047910a9978b440a6234eaebd831062bdd4/src/core/view/background/BaseBackgroundPainter.cpp#L57) to load the value in.

After building release-1.1 from source and changing that line so it converts to double (stod) everything works as expected for me.

**To Reproduce**
Put this in your pagetemplates.ini and select the page background in Xournal++ (or use a plugin to change your background config). If you change the line width to 1.0, the lines should be visible again. If you set it to anything between 0 and less than 1, no lines should be visible.

```
[FloatingPointBug]
name=Example of line width not working
format=graph
config=lw=0.9
```

In my case there are no lines since the .9 seems to be truncated, only leaving a 0 as the value.

**Expected behavior**
The floating point values should be loaded correctly and the lines should be clearly visible when setting the line width to 0.9.

**Comment by rolandlo** [comment]
@DieN Thanks for the report and the analysis. Would you mind creating a PR that fixes the problem?
