### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by RJDan** [xournalpp/xournalpp#3659]
**Is your feature request related to a problem? Please describe.**
I use the app for note taking during meetings and I don't have time to use the mouse to format section headings etc.

**Describe the solution you'd like**
 It would be super useful if I could use markdown convention while typing to format text on the fly. 

**Describe alternatives you've considered**
I considered formatting with Tex but it is far more clunky than markdown.

**Comment by rolandlo** [comment]
Please take a look at pull request #3408

**Comment by bhennion** [comment]
Duplicate of #729
