### ISSUE TITLE
Eraser only triggers with a highlighted line when the eraser passes through the middle of the highlighted line.

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3668]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use 3.24.30
 - Version of Xournal++: 1.1.0
 - official release with pacman

**Describe the bug**
When you erase a highlighted line, it will not erase to erase until the eraser is at the middle of the highlighted line. By middle, I mean the middle path that the highlighter would follow.

**To Reproduce**
1. draw a thick highlighted line
2. set the eraser to delete stroke, and pick a small size of eraser
3. bring the eraser into the highlighted line, and observe that the line will only be erased when the eraser passes the middle of the highlighted line.

**Expected behavior**
I expect the eraser to remove the highlighted line as soon as it touches the highlighter.

**Comment by bhennion** [comment]
This issue is subsumed by #997. Also PR #3532 addresses it, albeit maybe not quite like you'd want. You're welcome to test #3532 and report there if the solution chosen doesn't satisfy you.

Closing this issue.
