### ISSUE TITLE
"Preserve line width" in preferences doesnt work

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#3683]
Xournal version : xournalpp-1.1.0+dev-nightly.20211218-windows
OS : Windows 10

"Preserve line width" in preferences doesnt work.  

The width of the lines is not preserved despite the option "preserve line width" is checked in preferences

**Comment by rolandlo** [comment]
I checked it on Linux and it still works.
Are you sure it doesn't work? Note that this option means that after you have unselected the objects you scaled up or down, the line width will be the same as it was originally. During scaling you only get a preview, where line width looks scaled.

**Comment by MichelReims** [comment]
You are right.  It works.  Sorry.  thank you
