### ISSUE TITLE
Crash when clicking on "fonts"

### ISSUE THREAD

**Issue by SeeDborg** [xournalpp/xournalpp#3696]
As saif in the title, Xournal++ on my desktop PC is crashing when I click on "fonts"... No error message, just the program closing.

![Animation1](https://user-images.githubusercontent.com/7523821/148130388-3cb5e5df-e01e-4dc3-9c07-891043d11a46.gif)

**Comment by rolandlo** [comment]
What OS do you use? What version of Xournal++ is this? Have you started from terminal to see if there are error messages (or errorlogs)?

**Comment by LittleHuba** [comment]
Please start from console and reproduce the crash. Then post the output of the console.

**Comment by SeeDborg** [comment]
My OS is Windows 11. I have Xournal++ latest version, running on another PC with Windows 11 without problems...

How can I launch it from console ? I tried with Powershell but it does not want to launch.

**Comment by rolandlo** [comment]
On Windows it is more difficult to get console messages. You should basically install and run an [MSYS2](https://www.msys2.org/) console to get them. See https://github.com/xournalpp/xournalpp/discussions/3673#discussioncomment-1840352 for details.

**Comment by SeeDborg** [comment]
(xournalpp.exe:8640): GLib-GIO-WARNING **: 23:25:06.609: win32 session dbus binary not found: C:\Program Files\Xournal++\bin\\gdbus.exe
** Message: 23:25:07.221: TEXTDOMAINDIR = (NULL), PACKAGE_LOCALE_DIR = ../share/locale/, chosen directory = ../share/locale/

** (xournalpp.exe:8640): WARNING **: 23:25:07.222: XournalMain: System default locale could not be set.
 - Caused by: locale::facet::_S_create_c_locale name not valid
 - Note that it is not supported to set the locale using mingw-w64 on windows.
 - This could be solved by compiling xournalpp with msvc
Segmentation fault


The last line "Segmentation fault" appears when the program is crashing.

**Comment by SeeDborg** [comment]
Did I do it right ?

**Comment by rolandlo** [comment]
Yes, you did it right. I can see the line:
```(xournalpp.exe:8640): GLib-GIO-WARNING **: 23:25:06.609: win32 session dbus binary not found: C:\Program Files\Xournal++\bin\gdbus.exe```
which looks problematic. This should have been fixed in #3426. Do you use the latest stable version or the nightly release. In the first case please try the [nightly release](https://github.com/xournalpp/xournalpp/releases)

**Comment by SeeDborg** [comment]
It seems fine with the nightly build !

**Comment by rolandlo** [comment]
> It seems fine with the nightly build !

Great that it works. Closing the issue then.
