### ISSUE TITLE
Appending new pdf pages does not work

### ISSUE THREAD

**Issue by holgervoss** [xournalpp/xournalpp#3703]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux - Ubuntu 21.10
 - GNOME Xorg
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0+dev
 -  Installation method: PPA andreasbutti

**Describe the bug**
It's not possible, to append a new PDF file - see screenshot. Whatever I do...

**To Reproduce**
1. Open Programm
2. Open PDF File (or not - it doesn't matter)
2. --> Journal --> Append new pdf pages ... error!

**Expected behavior**
Opening a dialog box or working after loading a pdf

**Screenshots of Problem**
![Bildschirmfoto von 2022-01-06 19-59-06](https://user-images.githubusercontent.com/76280359/148438741-e1a28cc1-e3cd-4a30-8132-d973328e84c4.png)
![Bildschirmfoto von 2022-01-06 19-58-48](https://user-images.githubusercontent.com/76280359/148439003-490f7f40-3b14-4df0-92c9-3392307d38c5.png)

**Additional context**
Closing an Opening the document doesn't help

**Comment by rolandlo** [comment]
It seems you misunderstand what this command does. You can only add new pages of the current pdf background file. It is not possible (without external tool) to annotate two pdf's in one Xournal++ document. Only use this for pdf documents that are created incrementally (for example you write lecture notes incrementally during a course; each time you have added some pages to your lecture notes you append the new pages in Xournal++).

**Comment by holgervoss** [comment]
OK, now I see more clearly. But the message is not easy to understand. May I suggest (in German):
Es stehen keine weiteren ungenutzten Seiten eines hinterlegten PDF-Dokuments zur Verfügung
(There are no other unused pages of a deposited PDF document available) 
If I delete a page, I can quickly add it again using this option. But only then. Otherwise I have to go to Journal -> Page Background. 
Thank you for your prompt reply!

**Comment by rolandlo** [comment]
I'm not completely happy with your suggestion. For of all there is only one "deposited" PDF document. Secondly only those pages following the last pdf page in the document are appended. If you delete a pdf page in the middle of a multi-page document, it won't be appended.
I'm closing the issue. Feel free to make a PR to change the source string in 
https://github.com/xournalpp/xournalpp/blob/6f28fd5c7c1194ecc0436828dd27157acc77d676/src/core/control/Control.cpp#L1267
