### ISSUE TITLE
Creating a "portable" Windows version

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#3714]
**Rationale**
I often use `xournal++` to give classes and talks. In several venues, I am forced to use a computer where I can't install any software. It would be nice to have a version of `xournal++` for windows that can run off a pen-drive (a *portable* version, I think it's called in the Windows-land).

**Describe the solution you'd like**
A version of the Windows executable that can just run out of a pen drive, or of a directory without the need for administration rights. 

**Describe alternatives you've considered**
There are really no alternatives... Unfortunately, my knowledge of Windows is nil, so I do not know how difficult this can be.

**Additional context**
An example on GitHub program that has a "portable windows" version: https://github.com/pdfarranger/pdfarranger/releases

**Comment by rolandlo** [comment]
@Rmano Have you tried putting the `Xournal++` installation folder onto a USB stick and trying to run from it? What goes wrong? There are environment variables to control the location of the `config`, `cache` and temporary folders (see [file locations section on the website](https://xournalpp.github.io/guide/file-locations/) for what these folders are and [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for environment variables). There is a chance to get it working like that, but I'm not sure how dependencies behave. So you really need to try it out and see what happens.

**Comment by Rmano** [comment]
Ok, I will try this weekend. Thanks for the hints --- I am a complete newbie in Windows ;-), but fortunately, I have a completely locked down windows machine (my daughter's school laptop) for testing...

**Comment by Technius** [comment]
This should be straightforward for us to support in CI, as we already generate a "portable" installation before we run NSIS to generate the installer executable.

**Comment by berteh** [comment]
The existing installer works for me as portable as-is, just got to *unpack* the NSISI installer (xournallapp-setup.exe), eg using 7-zip, instead of executing it, and then run *xournalpp-1.2.2/bin/xournalpp.exe*
