### ISSUE TITLE
Increase page width of imported PDFs for better annotation

### ISSUE THREAD

**Issue by ShrutheeshIR** [xournalpp/xournalpp#3715]
**Is your feature request related to a problem? Please describe.**
When opening PDFs (lecture PDFs) in xournal++, if the slides have too much content, it becomes difficult to annotate on the slides directly, due to the clutter. The best way in the current setting is to add a new page, and write down content on the new page, however this gets difficult for navigation (and does not really work as annotation). We should have a way of noting down our thoughts and annotations on the side of the slides.

**Describe the solution you'd like**
One could have a solution where we can increase the width of the current PDF, which empty space to the right. i.e. if the initial slide pages were A4 landscape, we could add 10 cm to the right, making the page 21x39, where the first 21x29 would have the content of the slides and the next 21x10 would be empty space.

**Describe alternatives you've considered**
Currently, I add a new page, and setting the view to be 2 column, but this obviously does not work when imported to PDFs.

**Additional context**
Any other solution is also appreciated.

**Comment by rolandlo** [comment]
What is the problem with adding a new page (after each page), changing its background to empty, its width to e.g. 10cm, and setting the view to be 2 column? You could even automate that via a [plugin](https://xournalpp.github.io/guide/plugins/plugins/).
Otherwise you could also try out the solution described in this [stackexchange answer](https://unix.stackexchange.com/questions/441888/add-extra-margin-on-right-to-a-pdf-without-losing-outline)

**Comment by Grijnak** [comment]
I'd like to voice my support for a similar feature: A view where all the PDF pages are in the leftmost column and all the non-PDF pages after a PDF page are in a row next to it.

In the current state, if I need more annotation pages than the previous maximum of annotation pages, I have to update the column count and then add a new blank page before every PDF page in the entire document. This is a lengthy process which my ADHD brain is not set up for (ooh thats an interesting thought on page x lets think about that and discard the entire thought process of what it is that I was actually working on). 

Automating would be ok too, so I've looked at the plugin API, but cant find a way of seeing how the user has organized their view. Which would be necessary if I want to add a new page after every n pages, where n is the amount of columns currently selected. Also the documentation is really sparse on how to execute a ui action, so I wouldn't know how to add new pages without diving into the source code.

**Comment by ShrutheeshIR** [comment]
@rolandlo the stackexchange answer is quite neat! Did not think of that. Thanks!
I'll try to perhaps integrate the answer into xournal so I could do this size change within xournal itself.
