### ISSUE TITLE
When saving a PDF file as an edited Xournalpp file, the .pdf extension is included in the defualt name

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3726]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Gnome Wayland
 - Which version of libgtk do you use 3.24.31
 - Version of Xournal++: 1.1.0
 - Installation method: Arch Linux official repositories

**Describe the bug**
When you save an annotated PDF file, in the popup dialog the default name that it gives to the file is <filename.pdf>.xopp

**To Reproduce**
1. Open a pdf file in Xournalpp
2. Save the file in Xournalpp
3. Observe that in the pop up save dialog at the top that the file name it gives is <filename.pdf>

**Expected behavior**
I would expect that for some file <filename>.pdf, when I save an annotated version of that file in xournal, I would expect xournalpp to save it as <filename>.xopp instead of <filename.pdf>.xopp

**Comment by rolandlo** [comment]
One can agree or disagree with your suggestion. I wouldn't call it a bug by any stretch. The combination NAME.xopp, NAME.pdf is also used for .xopp-files that get exported to PDF.

**Comment by Febbe** [comment]
That is actually the intended behavior.
