### ISSUE TITLE
The title of Xournal++'s webpage should be clickable, and lead back to the homepage

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3728]
**Is your feature request related to a problem? Please describe.**
On the webpage, the logo of Xournal++ is clickable and leads back to the homepage, but the text right beside it that says "Xournal++" is not.

**Describe the solution you'd like**
Make the full logo and name combo clickable, and lead back to the homepage.

**Additional context**
This is the part that I am talking about:
![image](https://user-images.githubusercontent.com/7829231/150064639-23dcfa55-144b-4743-a555-1fdf738d1df3.png)
This is cliackable
![image](https://user-images.githubusercontent.com/7829231/150064658-aee70bbc-d0a8-4a88-aa50-fe22799b0160.png)
This is not:
![image](https://user-images.githubusercontent.com/7829231/150064684-c45d065a-a4ce-4437-98c3-b1d38a1d92a8.png)

**Comment by rolandlo** [comment]
Please report website related issues [here](https://github.com/xournalpp/xournalpp.github.io/issues).
