### ISSUE TITLE
Xournal++ crashes on startup when autoloadMostRecent is true and no recent files are available

### ISSUE THREAD

**Issue by namlit** [xournalpp/xournalpp#3734]
**Affects versions :**
 - OS: Linux (Ubuntu 20.04)
 - (Linux only) Desktop environment: KDE
 - libgtk: 3.22.30
 - Xournal++ 1.1.0
 - Installation method: Appimage, official Release

**Describe the bug**
When Xournal++ is installed for the very first time and the setting "autoloadMostRecent" is set to true, but no file is actually ever saved and thus no recent files are available, Xournal++ crashes on the next start and can not be started again. After manually editing `~/.config/xournalpp/settings.xml` and resetting "autoloadMostRecent" everything works as expected.
I was able to reproduce this issue by removing all relevant recent files from `~/.local/share/recently-used.xbel`.

**To Reproduce**
1. Activate autoloadMostRecent
2. Close Xournal++
3. Remove all entries referring to Xournal++ files (*.xopp) from `~/.local/share/recently-used.xbel` (This is the state when you first install Xounal++ and have never opened any *.xopp files). It seems that the file ending is actually the relevant part that is used for discovering recent files. Just changing the file ending was enough for me to reproduce the error. Might be better to remove the complete `<bookmark></bookmark>` section though. The mime-type should be `application/x-xoj`, but changing the mime-type does apparently not influence discovery of recent files.
4. Try to restart Xournal++
5. Xournal++ instantly crashes. The only way to recover is to manually edit ~/.config/xournalpp/settings.xml and set `<property name="autoloadMostRecent" value="false"/>`

**Expected behavior**
Xournal++ can be started and does not crash.

**Comment by namlit** [comment]
I just had a deeper look. There was a nullptr check missing in the startup. I created a PR to fix this issue.

**Comment by Technius** [comment]
Will close with 1.1.1 release.
