### ISSUE TITLE
Dark Mode Button Windows

### ISSUE THREAD

**Issue by TheTRCG** [xournalpp/xournalpp#3735]
**Is your feature request related to a problem? Please describe.**
Enabling dark mode in Windows 10 button

**Describe the solution you'd like**
Add a button to create the settings.ini file needed for dark mode in the UI of the program

**Describe alternatives you've considered**
Not really

**Additional context**
If anyone can point me in the direction of how to add this I'll be glad to work on it myself

**Comment by rolandlo** [comment]
Why do you want a button for that? Since Xournal++ has to be restarted anyway to switch modes, it looks more appropriate to only allow changing the settings in menu `Edit > Preferences`

**Comment by TheTRCG** [comment]
@rolandlo sorry, by button I meant to add a setting in an appropriate menu. Not a button in the toolbar

**Comment by rolandlo** [comment]
Ok, then use the `View` panel in the preferences and enable "Dark mode" there. Note that you need to restart Xournal++ after checking/unchecking this checkbox.

**Comment by TheTRCG** [comment]
@rolandlo that does not activate dark mode, it only changes the icons to a dark theme icon set, it's inappropriately named
a settings.ini folder in etc/gtk3.0 in the install directory of xournal to get dark mode.
Would be nice to have that option within xournal itself instead of needing to create a new file

**Comment by rolandlo** [comment]
On my Windows 10 system it works as you would hope, see #3730. Please try again with the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly)

**Comment by TheTRCG** [comment]
It appears it's there in the nightly release so I'll close this, thanks for pointing that out for me
