### ISSUE TITLE
Xournal++ leaking dialog widgets

### ISSUE THREAD

**Issue by danemtsov** [xournalpp/xournalpp#3743]
**Affects versions:**

 - OS: Windows
 - libgtk version: 3.24.30
 - Xournal++ version: nightly (bc5f6047910a9978b440a6234eaebd831062bdd4)
 - Installation method: official release

**Describe the bug**

After closing a dialog (e.g. settings, background, ~~font selection~~, ...) the window is not destroyed, but the next time the dialog is opened, a new window is created anyway.
It doesn't matter if the dialog is closed via OK/Cancel/... or the title bar button.

Apart from unnecessary use of system resources this e.g. pollutes Aero Peek on Windows.

**Comment by rolandlo** [comment]
Thanks for reporting. Is that specific to Windows 11? On Windows 10 I have never observed something like that.

**Comment by danemtsov** [comment]
As far as I understand GTK keeps references to toplevel widgets until they are explicitly destroyed, so I believe this isn't specific to any OS. It's just that on Windows it shows (btw I am on Win 10, sorry for not clarifying).

This is Aero Peek (the thing that is displayed when hovering the window preview in the taskbar) after opening and closing the About dialog three times:
&emsp;&emsp;<img alt="Aero Peek" src="https://user-images.githubusercontent.com/49734973/151072656-e56ce6be-8454-4f93-9379-1c3777dfb557.png" width="500px">
&emsp;&emsp;(cursor is somewhere around the red dot)

GTK inspector (run Xournal++ with env var GTK_DEBUG=interactive):
&emsp;&emsp;<img alt="GTK Inspector" src="https://user-images.githubusercontent.com/49734973/151071820-36213615-ab42-41cf-b440-962b4d281bd3.png" width="369px">
&emsp;&emsp;The dialogs are only hidden no matter how they are closed.

From the documentation of `gtk_widget_destroy` (emphasis mine):
> Destroys a widget.
>
> When a widget is destroyed all references it holds on other objects will be released:
>
> * if the widget is inside a container, it will be removed from its parent
> * if the widget is a container, all its children will be destroyed, recursively
> * if the widget is a top level, it will be removed from **the list of top level widgets that GTK+ maintains internally**

I created #3748 (more specifically 79545bc0d4cab7ce60bc7a1c07896814e375d09d) to call `gtk_widget_destroy` in the destructor of `GladeGui` if the managed widget is a toplevel one. If not then destruction will be handled by GTK when the parent widget is destroyed (and nothing else is keeping a reference to the widget).

**Comment by danemtsov** [comment]
I just noticed the font selection dialog is **not leaked**. Though it does pollute Aero Peek once it has been opened and closed, it gets reused the next time you select a font.
Anyway this doesn't affect #3748 since the font selection dialog isn't based on `GladeGui`.

The 'pollution' comes from GTK only *hiding* the dialog windows instead of *closing* them (which seems to be the only way if the window shouldn't be destroyed).

**Comment by Febbe** [comment]
Can you open a bug report at gtk's issue tracker? TThis is most likely a bug in gtk itself.
https://gitlab.gnome.org/GNOME/gtk/-/issues

Also, dialogs should be deleted directly after use, via signals. (The run function is deprecated.)
