### ISSUE TITLE
Menu on Kde

### ISSUE THREAD

**Issue by Daddie2** [xournalpp/xournalpp#3752]
Affects versions :

OS: debian 11
(Linux only) Desktop environment: Plasma-Wayland
Version of Xournal++: stable, unstable
Installation method: snap, deb

Step 1 install xournal with deb or snap
Step 2 enable dark mode

today i tried to install on my surface kde and notice many bug on plasma with the menu, i had 175% of scale maybe this create some problem but i click on view and nothing append or file open,everything was not working as it should so it force me to come back to gnome.

**Comment by bhennion** [comment]
I cannot reproduce on Archlinux. Can you be more specific:

- What exactly is "not working"? You cannot click on the buttons?
- Are you using a mouse, or a touchscreen, or a stylus?
- Do other GTK apps work fine on your KDE setting?
- Does it work with Plasma on X11?
- What's the plasma version?
- What's the glib version?
- What's the wayland version?

**Comment by Daddie2** [comment]
> I cannot reproduce on Archlinux. Can you be more specific:
> 
> - What exactly is "not working"? You cannot click on the buttons?
> - Are you using a mouse, or a touchscreen, or a stylus?
> - Do other GTK apps work fine on your KDE setting?
> - Does it work with Plasma on X11?
> - What's the plasma version?
> - What's the glib version?
> - What's the wayland version?

I was because I unistall it on the last kde version for debian unstable I don't know more for the version sorry, I use a mouse a touchscreen and a stylus but I think it is possible that the 175% of scale was break everything so it is a kde problem
