### ISSUE TITLE
Latex can't be inserted (again)

### ISSUE THREAD

**Issue by naturalmechanics** [xournalpp/xournalpp#3762]
**Affects versions :**
 - OS:  Linux Manjaro.
     - Output of uname -a    : Linux glassplanet 5.15.16-1-MANJARO #1 SMP PREEMPT Thu Jan 20 13:58:19 UTC 2022 x86_64 GNU/Linux
 - (Linux only) Desktop environment: X11 
     - Output of $ pacman -Q plasma-desktop    : plasma-desktop 5.23.5-1

 - Which version of libgtk do you use
     - Xournal++ 1.1.0
          └──libgtk: 3.24.31

 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - see above
 - Installation method:  using pacman from repo community.

**Describe the bug**

The latex insert does not work.
 - There is no preview rendered, even if i use a simple formula like x^2. 
 - The okey button is gray.
 - The message "the formula is empty when rendered or invalid" is visible above the latex formula text box
 - I checked the log files in /tmp. It contains : 
      ! LaTeX Error: File `standalone.cls' not found. 
      Type X to quit or <RETURN> to proceed,
      or enter new name. (Default extension: cls)
 - But texlive-latexextra is installed.
 - Output of : $ pacman -Q texlive-latexextra                                      
   texlive-latexextra 2021.61405-1
 - Output of : $ sudo pacman -F standalone.cls                              
   extra/texlive-latexextra 2021.61405-1 (texlive-most) [Installiert] 
   usr/share/texmf-dist/tex/latex/standalone/standalone.cls

**To Reproduce**
1. Try to insert latex formula in a text using the version and linux described above

**Expected behavior**
At least a rendering of the formula should appear in the latex insert and preview window, and the "okay" button should be active.

**Comment by rolandlo** [comment]
What happens if you compile the `tex.tex` file in the `/tmp` folder manually, using 
```shell
pdflatex -halt-on-error -interaction=nonstopmode tex.tex
```
in the terminal (from the folder, where the `tex.tex` file is located)?

**Comment by jonas-w** [comment]
After installing texlive-latexextra, texlive-core and texlive-bin it worked for me

**Comment by thelastindian** [comment]
I second @jonas-w 

I actually installed texlive (not texlive-full) and after it didn't work, I had to install texmaker to make it work. I would suggest you to first install the packages mentioned by @jonas-w and if it doesn't work, do what I did and install the packages using command 
`sudo apt install texlive -y && sudo apt install texmaker -y`
