### ISSUE TITLE
No input in textbox after scrolling gives focus to other page

### ISSUE THREAD

**Issue by fpesari** [xournalpp/xournalpp#3765]
**Affects versions :**
 - OS: openSUSE Tumbleweed
 - (Linux only) Desktop environment: KDE Plasma 5.23.5 on X11
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 1.1.0
 - Installation method: openSUSE repository

**Describe the bug**
Text boxes stop taking any input when scrolling gives focus to a different page than the one which contains said textbox

**To Reproduce**
1. Open a PDF with more than one page to annotate (or create an empty document with > 1 pages)
2. Put a textbox inside a page
3. Scroll with the mouse wheel until the next (or previous) page is focused (red outline)
4. Type something on your keyboard. The text cursor will keep blinking inside the text box but nothing will happen

**Expected behavior**
Either:
1. (my preferred option) The textbox too goes out of focus and becomes "closed"; in other words, editing mode for that textbox is turned off (the equivalent of pressing Escape after typing something)
2. You can keep writing into the textbox, despite its page being unfocused

**Comment by bhennion** [comment]
This has been fixed in the release branch.
