### ISSUE TITLE
Create a tool named "Scale Strokes"

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#3772]
It would be nice to have a new tool named (for example) : "Scale  Strokes"  that would work as follows  :
- Select one or more objects, one page or several pages.
- Choose the new tool "Scale Strokes".
- Choose the coefficient of scale (a positive number)
- Confirm

Then, the width of each selected stroke in the document is multiplied by the coefficient.
This makes it possible to change or personalize the thickness of the pen in the document already existing.

**Comment by rolandlo** [comment]
That's functionality we should offer through the plugin API. My goal is to provide API to create, manipulate and filter selections and to apply various transformations to these filtered selections. That will require a decent amount of work though.

**Comment by atticus-sullivan** [comment]
Now with https://github.com/xournalpp/xournalpp/pull/6034, we've moved one step forward regarding this issue.

What did you mean with "filtered selections" though? @rolandlo

**Comment by rolandlo** [comment]
> Now with #6034, we've moved one step forward regarding this issue.
> 
> What did you mean with "filtered selections" though? @rolandlo

I thought about putting a filter (e.g. by color or whatever) on an existing selection without modifying the selection. It's not relevant any more. Doing what the issue asks is already possible now except that you can only create selections from objects on the same page (and layer), not from multiple pages.

**Comment by atticus-sullivan** [comment]
Yes it is possible. Should we add the corresponding plugin before closing this issue (not sure if it fits to one of the existing plugins, but creating a new "StrokeActions" plugin with just this feature seems a bit small for one plugin) or should we close it just as it is?

**Comment by rolandlo** [comment]
Yes, an official plugin for just scaling strokes is a bit thin. Let's close the issue without it.
