### ISSUE TITLE
support pdf forms

### ISSUE THREAD

**Issue by ari-s** [xournalpp/xournalpp#3774]
It would be great if xournalpp would support pdf forms ([example](https://www.w3.org/WAI/WCAG20/Techniques/working-examples/PDF23/form-fields-keybd.pdf)) - the areas that work like TextInput widgets in graphic toolkits.

These documents often need to be signed as with a pen, and xournalpp would be a nice tool to fill these documents with this enhancement.

**Comment by ari-s** [comment]
This is clearly an enhancement, but I'm not able to set labels on this.
I'm not so familiar with how github works currently, if I could do something better please tell or point to some documentation.

**Comment by rolandlo** [comment]
Duplicate of #3147
