### ISSUE TITLE
Wrong selection in new 'select linear text' tool

### ISSUE THREAD

**Issue by jghauser** [xournalpp/xournalpp#3790]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 7f6f107e
 - Installation method: AUR xournalpp-git package

**Describe the bug**
When using the 'select linear text tool' too much text is selected when the selection is longer than one line and the start of the selection on the first line is further to the right than the end of the selection on the last line. In the screenshot below I (tried) selecting the text from the beginning of the word 'Around' to the end of the word 'age'.

**To Reproduce**
1. Using the 'select linear text tool' make a selection that spans multiple lines, making sure that the beginning of the selection on the first line is further to the right than the end of the selection on the last line.
2. As soon the mouse button is let go and the toolbox appears, additional text is selected.

**Expected behavior**
Only the text from beginning to end of selection is selected.

**Screenshots of Problem**
![20220208_19h16m28s_grim](https://user-images.githubusercontent.com/10319377/153050888-e9cd3430-1b27-4ae7-944d-73182fed8295.jpeg)

**Comment by Technius** [comment]
Can you provide the PDF that you used?

**Comment by bhennion** [comment]
I can reproduce with this test PDF:
[toc.pdf](https://github.com/xournalpp/xournalpp/files/8038663/toc.pdf)


https://user-images.githubusercontent.com/17818041/153351638-79dfb973-892d-495c-88ec-0e4b80df34a7.mp4

**Comment by jghauser** [comment]
Thank you so much for the (super speedy) fix! Works perfectly on my end. And thanks so much for adding this feature, it's a game changer for me! :tada:
