### ISSUE TITLE
When changing the line style of something which is already drawn, if you already have the line style that you want selected, you must switch off the current line style and back to be able to change the items line style

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3793]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Gnome Wayland
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 1.1.0
 - Installation method: Official package from the Arch Linux repositories

**Describe the bug**
If you have an item which is drawn with a specific line style, and you select the item to switch the line style, if you currently have the line style that you want the item to be switched to already seleced, and you try and select it again to switch the item, nothing happens. Instead you must switch off of the line style, select the item, then reselect the desired line style.

**To Reproduce**
Using a circle as an example
1. Select the pen tool
2. Select the standard line style
3. select the draw ellipse tool
4. Draw an ellipse
5. switch the pen to the dashed line line-style
6. select the ellipse
7. try and switch the ellipse to the dased line style by selecting the already selected dased line style, and observe that you cant switch the line style of the ellipse
8. switch back to the standard line style
9. reselect the ellipse
10. select the dased line style and observe that the ellipse is now using the dashed line style

**Expected behavior**
I expect that the selected item will change to whatever line style that I select regardless of what line style is currently selected.

**Comment by forgedOctopus** [comment]
Hi, 

found this issue, while looking for a good start to contribute. 
I'll try to come up with a pull request next week.
