### ISSUE TITLE
Textmarker with fill has a cutout at starting point

### ISSUE THREAD

**Issue by Tetralingua** [xournalpp/xournalpp#3795]
**Affects versions :**
 - OS: Linux, Ubuntu 20.04 LTS
 - (Linux only) Desktop environment: Gnome
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
When using Textmarker with options fill and rectangle or ellipse the starting points have a cutout. 

**To Reproduce**
1. Choose Textmarker 
2. Choose Draw Rectangle or ellipse
3. Choose Fill
4. Draw

**Expected behavior**
A rectangle with rounded corner or an ellipse fully filled

**Screenshots of Problem**
![grafik](https://user-images.githubusercontent.com/33201457/153197983-cb06d3a6-d1d7-4059-b208-c6231631deb8.png)

**Comment by Technius** [comment]
Seems to only happen with highlighter, but not pen. I'd be interested to know where these cutouts are coming from.

**Comment by bhennion** [comment]
Probably some missing `cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);`. This looks like a `CAIRO_LINE_CAP_BUTT` to me.

**Comment by danemtsov** [comment]
It's this:
```diff
# src/core/view/StrokeView.cpp
# index e78d3b0b..cd47a1ad 100644
@@ -115,7 +115,19 @@ void StrokeView::paint(bool dontRenderEditingStroke, bool markAudioStroke, bool
     }
 
     cairo_set_line_join(crEffective, CAIRO_LINE_JOIN_ROUND);
+
+    cairo_line_cap_t capType;
+    switch (s->getStrokeCapStyle()) {
+        case StrokeCapStyle::BUTT:
+            capType = CAIRO_LINE_CAP_BUTT;
+            break;
+        case StrokeCapStyle::SQUARE:
+            capType = CAIRO_LINE_CAP_SQUARE;
+            break;
+        default:
+            capType = CAIRO_LINE_CAP_ROUND;
+    }
-    cairo_set_line_cap(crEffective, CAIRO_LINE_CAP_ROUND);
+    cairo_set_line_cap(cr, capType);
 
     if (auto fill = s->getFill(); fill != -1) {
         /**
```
at https://github.com/xournalpp/xournalpp/commit/ffa681e8ad17ef242c427c0b1f48a18d602ac5bd#diff-97de8db7ed24b73c62022855e8cf56719381262591a0f955480215d275439cceR130 (deletion moved for clarity).

Drawing happens on crEffective, which is != cr i.a. when using filled highlighter.

**Comment by Technius** [comment]
This should be fixed in the next nightly build thanks to @danemtsov.
