### ISSUE TITLE
Adding Arabic language 

### ISSUE THREAD

**Issue by 0xf4h3d** [xournalpp/xournalpp#3809]
**Hey Xournal Developers , 
Thanks for this helpful application**

**Adding ability to write text in arabic**
as many using this application i suggest adding ability to write using text button in arabic as sometimes we need to explain something to non english speakers or who are weak in understanding engilsh 

Thanks

**Comment by Technius** [comment]
Hi @0xf4h3d, could you explain your problem in more detail? The text tool supports non-English text, and Xournal++ itself has an Arabic translation.

**Comment by hyperupcall** [comment]
Possibly related to #3125
