### ISSUE TITLE
Does not save changed UI layout

### ISSUE THREAD

**Issue by funnym0nk3y** [xournalpp/xournalpp#3813]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Win10
 - libgtk: 3.24.30
 - Version of Xournal++: 9d1277de
 - Installation method: exe

**Describe the bug**
When changing the arrangement of existing symbols on my own UI view, it is not saved.

**To Reproduce**
1. Create custom UI view
2. Change location of symbol
3. Exit
4. Restart Xournalpp

**Expected behavior**
Symbols should stay where I put them.

**Comment by Technius** [comment]
I believe this bug was fixed in version 1.1.1, which was released just a moment ago. Please try it and let me know if you're still encountering the problem.
