### ISSUE TITLE
Eraser Glitches when erasing highlighted areas

### ISSUE THREAD

**Issue by sortedcord** [xournalpp/xournalpp#3838]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows 10 21H2
 - Which version of libgtk do you use: 3.24.29
 - Version of Xournal++: 1.1.0
 - Installation method: Official Release

**Describe the bug**
Eraser does not erase highlighted areas properly and seemingly makes it darker or solid to be exact.

**To Reproduce**
![xournalpp highlighter glitch](https://user-images.githubusercontent.com/37407370/154797896-f1df32a9-6aed-4e1c-a9fa-450e5e99c0f0.gif)

This only happens with standard eraser mode. Delete stroke and whiteout still work fine

**Comment by ja-he** [comment]
This particular behavior (the temporary rendering glitch while erasing) seems to be resolved in #3532

![xournalpp-erase](https://user-images.githubusercontent.com/63857598/155196986-45ee2af8-5199-42c3-8812-36d8fad68508.gif)

this issue will probably be resolved whenever that gets merged :)
