### ISSUE TITLE
First two paired pages are not placed next to each other

### ISSUE THREAD

**Issue by tooxo** [xournalpp/xournalpp#3840]
**Affects versions :**
 - OS: Linux (elementary OS 6.1 Jólnir)
 - (Linux only) Desktop environment: Pantheon
 - Which version of libgtk do you use
     -  3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.1+dev
 - Installation method: PPA

**Describe the bug**
The first two pages in paired mode are not actually placed next to each other.

**To Reproduce**
1. Enable Paired Pages
2. Add another Page

**Expected behavior**
The pages should be next to each other

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/17050196/154822766-c2c476c5-4dd5-474a-b8c0-b7a2f85b5672.png)

**Additional context**
-

**Comment by LittleHuba** [comment]
You have most likely set an offset. Please check the menu for paired pages. There is a sub menu that allows you to specify an offset.
