### ISSUE TITLE
include background pdf in selection

### ISSUE THREAD

**Issue by tubbadu** [xournalpp/xournalpp#3843]
Usually when taking notes on a PDF it would be very useful being able to select instead of just the text you just drawed, also the pdf background, for example images in that pdf, as if it was a screenshot

It would be very nice if there was a tool called something like "screenshot selection" or something like this, that just does this, takes a screenshot of that part of the page and allows you to paste it somewhere else.

whithout this tool I always have to exit fullscreen mode, search for the screenshot app launcher in the menu, do the screenshot, and return back to the paper

**Comment by rolandlo** [comment]
What OS do you use? Have you considered using the QuickScreenshot plugin for that purpose?

**Comment by tubbadu** [comment]
> What OS do you use? Have you considered using the QuickScreenshot plugin for that purpose?

I'm running kubuntu 22.04
quickscreenshot is good but I usually need to screenshot a part of the drawing and then paste it right after, I don't need to save it to a file, I'd need the image to be copied to clipboard instead
perhaps I can modify the plugin?

**Comment by Zelmoghazy** [comment]
I think the shortcut for copying portion of the screen to clipboard in ubuntu is `Ctrl+Shift+PrtScrn`

**Comment by tubbadu** [comment]
> I think the shortcut for copying portion of the screen to clipboard in ubuntu is `Ctrl+Shift+PrtScrn`

yes it is, but I have no access to the keyboard when I'm taking notes on my tablet, so it would be useful a "only touch" way

**Comment by tubbadu** [comment]
okay I wrote this simple plugin to use scrot and xclip to copy the selection into the clipboard:
`-- This is an example Xournal++ Plugin - copy this to get started


-- Register all Toolbar actions and intialize all UI stuff
function initUi()

  ref = app.registerUi({["menu"] = "SelectionToClipboard", ["callback"] = "exampleCallback", ["accelerator"] = "<Control>p"});
end

-- Callback if the menu item is executed
function exampleCallback()
  local command = "scrot -s - | xclip -selection clipboard -t image/png"
  local runCommand = assert(io.popen(command .. " &"))

end
`

(i just changed a bit the example plugin)

is there an easy way to activate this plugin (or any other plugin) with a tool in the xournalpp toolbar? because if i'm fullscreen I can't access the plugin directly

**Comment by Technius** [comment]
The "accelerator" field in the `registerUi` line will add a keybinding. In your case, the plugin will be activated with <kbd>Ctrl</kbd><kbd>p</kbd>. There's currently no other way to activate the plugin besides menu option and key binding.

**Comment by tubbadu** [comment]
> The "accelerator" field in the `registerUi` line will add a keybinding. In your case, the plugin will be activated with Ctrlp. There's currently no other way to activate the plugin besides menu option and key binding.

Okay so I'll need to exit fullscreen in order to use the plugin and take a screenshot
Thank you anyway! It would be useful in the future a tool which activate plugins in the toolbar
