### ISSUE TITLE
Copy + paste between instances broken on Wayland when copying text

### ISSUE THREAD

**Issue by joeriexelmans** [xournalpp/xournalpp#3852]
**Affects versions :**

 - OS: NixOS 21.09
 - Linux 5.10.99
 - Desktop environment: Gnome-Wayland
 - libgtk: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: Nixpkgs stable 21.09

**Description**

Copy + paste of a selection between multiple instances of Xournal++ **stops working when the selection contains at least one Text node**.

This happens only with the native Wayland backend. When I run Xournal++ with the X11 backend (so, therefore, with XWayland in a Gnome-Wayland session), the bug does **not** occur:
```
$ GDK_BACKEND=x11 xournalpp
```

**Steps to reproduce**
1. Under wayland, launch 2 instances of Xournal++:
2. In once instance, draw some stuff and create at least one text node.
3. Select everything and copy it
4. Attempt to paste it in the other instance.

You'll notice that nothing happens. Instead, was expecting copy+paste to work just fine :)

**Screenshot**
Example of a selection that I cannot copy + paste between instances:
![image](https://user-images.githubusercontent.com/37209254/155136692-a8ae0d5a-9541-48b6-bea1-00a02210de95.png)

**Comment by rolandlo** [comment]
I can't reproduce the issue on Ubuntu 21.10 (under Wayland). Copying/pasting of a combination of strokes and text elements just work fine between 2 instances. Can you try the 1.1.1. version of Xournal++ as well?

**Comment by mesonium** [comment]
Works fine for me on Plasma 5.24.1 Wayland and Xournalpp 1.1.1 with libgtk 3.24.31 (on openSUSE TW).

**Comment by joeriexelmans** [comment]
Just tried version 1.1.1 and indeed the bug seems to have been fixed.
Thanks for the quick response!
