### ISSUE TITLE
Setsquare tool doesn't recognize inputs from wacom express keys

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#3862]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11 with xmonad
 - Libgtk: 3.24.31
 - Xournal++: 45f3059c07708d7db299d7838f172c872e2dca22
 - Installation method: built from source

**Describe the bug**
I've been using wacom `ExpressKey Remote (ACK-411050)` with `Xournal++` for two years and a half.
Today I assigned `alt r` and `alt shift r` to the wheel of `ExpressKey Remote` in order to rotate the new `setsquare tool`,  but it won't rotate.

**Comment by tattsan** [comment]
I got the following warnings:
```
Device class 6 not handled by setsquare
```
I've also tried other device class settings for `ExpressKey Remote`, but no setting was successfull.

**Comment by rolandlo** [comment]
Device class 6 is `INPUT_DEVICE_IGNORE`. Would you please provide [debug info for input related bugs](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs)?

Also please tell if assigning a keyboard shortcut to the wheel of `ExpressKey Remote` works for other functionalities in Xournal++.

**Comment by tattsan** [comment]
> Device class 6 is `INPUT_DEVICE_IGNORE`

I usually disable the `ExpressKey Remote` in Xournal++ preference setting, and configure the device with `xsetwacom`.
On this setting, I've been using the device over two years. As I wrote, I tried all device classes today.

> Also please tell if assigning a keyboard shortcut to the wheel of ExpressKey Remote works for other functionalities in Xournal++.

It works well. For example, if we assign `ctrl 1` to the wheel of `ExpressKey Remote`, we can change the drawing type with the wheel.

> Would you please provide debug info for input related bugs?

Which device class should I set for `ExpressKey Remote`?  `Mouse+Keyboard combo`? or `Disabled`?

**Comment by tattsan** [comment]
This debug info is taken under my usual setting: `ExpressKey Remote` is disabled.

[debug_input.log](https://github.com/xournalpp/xournalpp/files/8132222/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/8132223/debug_gdk_input.log)

**Comment by tattsan** [comment]
This debug info is taken under the setting: `ExpressKey Remote` is set to `Mouse+Keyboard Combo`.

[debug_input.log](https://github.com/xournalpp/xournalpp/files/8132286/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/8132288/debug_gdk_input.log)

**Comment by tattsan** [comment]
This is the result of `xinput list`
```
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen stylus        id=10   [slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Finger touch      id=11   [slave  pointer  (2)]
⎜   ↳ Lenovo ThinkPad Thunderbolt 3 Dock USB Audio      id=19   [slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                    id=25   [slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen eraser        id=27   [slave  pointer  (2)]
⎜   ↳ Wacom Cintiq Pro 32 Pen stylus            id=14   [slave  pointer  (2)]
⎜   ↳ Wacom Cintiq Pro 32 Pen eraser            id=15   [slave  pointer  (2)]
⎜   ↳ Wacom Cintiq Pro 32 Pad pad               id=16   [slave  pointer  (2)]
⎜   ↳ Wacom Cintiq Pro 32 Touch Finger touch    id=18   [slave  pointer  (2)]
⎜   ↳ Wacom Express Key Remote Pad pad          id=17   [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=24   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Video Bus                                 id=8    [slave  keyboard (3)]
    ↳ Sleep Button                              id=9    [slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C           id=12   [slave  keyboard (3)]
    ↳ Integrated Camera: Integrated I           id=13   [slave  keyboard (3)]
    ↳ TOPPING C1                                id=20   [slave  keyboard (3)]
    ↳ Logitech Webcam C930e                     id=21   [slave  keyboard (3)]
    ↳ sof-hda-dsp Headphone                     id=22   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=23   [slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                    id=26   [slave  keyboard (3)]
    ↳ C-Media Electronics Inc. USB Advanced Audio Device        id=28   [slave  keyboard (3)]
```

**Comment by rolandlo** [comment]
How about the setting: ExpressKey Remote is set to Keyboard?
The Mouse+Keyboard Combo is not supported yet by the setsquare, although it should probably be.

**Comment by tattsan** [comment]
There's no keyboard only setting on Xournal++'s preferences.

**Comment by rolandlo** [comment]
Ok, didin't know about that. Then please add the lines:
```cpp
        case INPUT_DEVICE_MOUSE_KEYBOARD_COMBO:
            return this->handlePointer(event) || this->handleKeyboard(event);
```
after line 38 of `SetsquareInputHandler.cpp` and try again with the Mouse+Keyboard Combo option.

**Comment by tattsan** [comment]
That's successful! Thank you so much for your quick response. And thank you for the joyful tool!
