### ISSUE TITLE
Autosaves create separate files, and do not save to the main file

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3868]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Gnome Wayland
 - Which version of libgtk do you use 3.24.31
 - Version of Xournal++: 1.1.1
 - Installation method: Official Release in the Arch Linux Repositories

**Describe the bug**
When the `.xopp` file that I'm working on is autosaved, it seems to create a separate file with the `.autosave.xopp` extension, and doesn't actually autosave to the main document for some reason.

**To Reproduce**
1. Create a file
2. Edit the file
3. Wait for an autosave
4. Observe that a new autosave file is created.

**Expected behavior**
I expect that Xournal would autosave to the main `.xopp` file, and not create a separate one.

**Comment by rolandlo** [comment]
No, Xournal++ should not autosave to the main `.xopp` file. If there would be a problem during autosave, you would loose everything.

**Comment by K4LCIFER** [comment]
This is rather bothersome, though. The autosave file is by default hidden since it is prepended with a `.`. When I need to recover from the autosave, I first need to view hidden files (which I would imagine the average user would not know how to do), load the autosave, and then re-save the autosave as the original file. This is all rather tedious and not overtly obvious.

Perhaps save first the hidden autosave document as a backup, then save to the main file after?
