### ISSUE TITLE
Xournal does not detect `default_template.tex` even though set in settings on Debian Bullseye

### ISSUE THREAD

**Issue by Tauheed-Elahee** [xournalpp/xournalpp#3877]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Debian Linux Bulleseye
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
     - `Xournal++ 1.1.1
└──libgtk: 3.24.24`
 - Version of Xournal++: [e.dsfgafd agrevgwfg. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
     - 1.1.1
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
 - `.deb` package from official release

**Describe the bug**

**To Reproduce**
1. Install tex
2. Install Xournalpp `.deb` package
3. Paste `default_template.tex` in `~/.config/xournalpp/default_template.tex`
4. Relaunch `xournalpp`

**Expected behavior**
Latex works.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

Preferences set here:
![image](https://user-images.githubusercontent.com/36247967/155922405-594fb393-7d0d-4bbc-9dd2-17d86a5aa27e.png)

Cannot render Latex
![image](https://user-images.githubusercontent.com/36247967/155922205-54c6193b-2050-4389-b168-1b0e1af6eeb2.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by Tauheed-Elahee** [comment]
![image](https://user-images.githubusercontent.com/36247967/155922437-316b9020-9159-41b8-a2c0-9146e9ae5219.png)

**Comment by Tauheed-Elahee** [comment]
![image](https://user-images.githubusercontent.com/36247967/155922457-64b7e500-8d24-4f26-a6e8-b4f887b1ccd7.png)

**Comment by rolandlo** [comment]
Can you please try to install the `scontents` latex package or use `legacy_template.tex`?

**Comment by Tauheed-Elahee** [comment]
Still did not work.

**Comment by rolandlo** [comment]
Then please go to the LaTeX panel in `Edit > Preferences` and hit the `Check configuration` button. You may have to check a `tex.log` file in a folder like `/tmp/xournalpp-.../tex/` afterwards.

**Comment by Tauheed-Elahee** [comment]
It works when I installed `texlive-full` on Debian.
