### ISSUE TITLE
Confusing Autosave Path Location on Windows [Nightly]

### ISSUE THREAD

**Issue by CptDinosaur** [xournalpp/xournalpp#3883]
I have autosave set to every three minutes.

Upon force shutting down and realising my mistake, I checked Appdata/Local/xournalpp

There is no autosave folder (clean install of latest nightly, windows version)

Just settings and another file

**Comment by rolandlo** [comment]
The autosave files for not previously saved .xopp-documents are in the Cache folder. The location of this folder depends on the OS you use. Please consult [the Xournal++ website](https://xournalpp.github.io/guide/file-locations/) for file locations.

**Comment by CptDinosaur** [comment]
The path is incorrect for Windows 8+, see https://www.thewindowsclub.com/temporary-internet-files-folder-location
It should be `C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache`

At any rate, the internet explorer cache folder is an inappropriate location for Xournal's files, it makes sense to use the cache folder on Linux but for windows, sharing `C:\Users\<user>\AppData\Local\xournalpp` with the config folder makes much more sense.

**Comment by rolandlo** [comment]
> The path listed is incorrect for Windows 8+, see https://www.thewindowsclub.com/temporary-internet-files-folder-location
> It should be `C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache`

For the website I opened a pull request in https://github.com/xournalpp/xournalpp.github.io/pull/67. Please check.

**Comment by danemtsov** [comment]
See https://github.com/xournalpp/xournalpp.github.io/issues/66

I'd speculate GLib's choice has something to do with automatic cleanup (the "Temporary Internet Files" folder is listed in the disk cleanup utility).
E.g. I hate the fact that some apps use `%USERPROFILE%\AppData\...` as their cache folder but neither communicate that in any way nor cleanup after themselves and I end up wondering how I got several Gigabytes less space on my harddisk...

**Comment by rolandlo** [comment]
Ok, I linked the PR to the issue.

**Comment by Technius** [comment]
Closing this issue, as the website has been updated. Let us know if you run into any other issues regarding the autosave location.
