### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jayu9493** [xournalpp/xournalpp#3886]
Not a big features request but here is the list:
--} Infinite scroll like okular
--} customise key-board shortcuts

**Comment by bhennion** [comment]
About the shortcuts: duplicate of #919.

About the infinite scroll, I don't really know what you mean. Could you elaborate?

**Comment by jayu9493** [comment]
> About the shortcuts: duplicate of #919.
> 
> About the infinite scroll, I don't really know what you mean. Could you elaborate?
The reference for okualr js this project `https://okular.kde.org/download/` and it has features like if you have reached the end of screen than cursor comes out from opposite side of screen and it is extremely useful tool to have.

**Comment by K4LCIFER** [comment]
Infinite scroll is a duplicate of #1174

**Comment by bhennion** [comment]
Closing as not-planned
