### ISSUE TITLE
1.1.1 Latex error message re: damaged PDF document

### ISSUE THREAD

**Issue by NelkonParker** [xournalpp/xournalpp#3899]
I'm using the 1.1.1 release on Windows 10.

I'm editing a pdf document. I've generated latex output without issue in this document, but now I'm getting the following message:

"Could not load LaTeX PDF file: PDF document is damaged"

I've attached a screenshot where you can see the offending latex

![Screenshot 2022-03-08 210137](https://user-images.githubusercontent.com/88211140/157325031-ed53b36f-9707-4a92-a167-d36a42299d9f.png)
.

Edit: the following latex works fine however:

![Screenshot 2022-03-09 104519](https://user-images.githubusercontent.com/88211140/157426681-88d42f08-6ee7-4414-80ed-2f55af5aced5.png)

**Comment by rolandlo** [comment]
On my system (Ubuntu 22.04) I don't get an issue with the `\cdots` LaTeX formula. You could try to find the temporary `tex.tex` and `tex.log` files in a subfolder of `C:\Users\<user>\AppData\Local\Temp` to find the reason why it fails for you.

**Comment by NelkonParker** [comment]
> On my system (Ubuntu 22.04) I don't get an issue with the `\cdots` LaTeX formula. You could try to find the temporary `tex.tex` and `tex.log` files in a subfolder of `C:\Users\<user>\AppData\Local\Temp` to find the reason why it fails for you.

This may be Windows specific then.

I have no tex.tex or tex.log files in that directory, however. Could they be elsewhere? This is with MikTex 2.9. Or do I need to turn on logging somehow?

**Comment by Technius** [comment]
The files should be located in a directory named something like `C:\Users\<user>\AppData\Local\Temp\xournalpp-<numbers>\tex`

Note to self: we should add a button in the settings that opens the temp folder, so that issues like this are easier to debug.

**Comment by NelkonParker** [comment]
I can't find anything obviously useful in any of the xournalpp-* files (though I'm not familiar with them). 

However, I've discovered that the problem is caused by a change that I made to the default_template.tex file re: font sizes; when the commented lines are made active, the problem occurs, without them, all is well:

================================================================

\documentclass[varwidth=false, crop, border=5pt, 14pt]{standalone}

%\documentclass[varwidth=false, crop, border=5pt]{standalone}
%\usepackage{lmodern}
%\usepackage{scrextend}
%\changefontsizes{12pt}

=================================================================

Maybe this is a clue to someone familiar with the latex handling code?

**Comment by Technius** [comment]
Xournal++ mostly only substitutes the formula, runs the TeX generation command (see the settings for the exact command used), and then loads the resulting PDF file. Currently, we don't know which step is failing, but based on the message, it seems like the generated PDF file is corrupt.

To debug this, I would recommend trying to manually generate the TeX file and running the command. You could also run your the TeX command on the `tex.tex` file generated by Xournal++. A snippet of the resulting logs would be helpful for debugging.

**Comment by tattsan** [comment]
`scrextend.sty`  is a part of `KOMA-Script` package bundle, but `MiKTeX` doesn't seem to contain this bundle. So you should install `KOMA-Script`. I will add this info to #3858.

**Comment by rolandlo** [comment]
I'm closing the issue, since this is clearly not Xournal++'s fault.
