### ISSUE TITLE
Window is movable in fullscreen mode

### ISSUE THREAD

**Issue by HerrNamenlos123** [xournalpp/xournalpp#3901]
**Affects versions :**
 - OS: Windows
 - libgtk 3.24.31
 - Version 1.1.1, commit 4f113e94

**Describe the bug**
When you click anywhere on the top tool bar and you drag it, the entire window is moved with it. This is very annoying, because I'm using a pen and when you don't hit the buttons correctly and hit inbetween them, the window moves and I constantly have to restore fullscreen mode. I think the window should certainly not be draggable in fullscreen mode.

**Expected behavior**
Nothing should happen when you 'click' and drag a blank space which is not the title bar.

Is this a known issue or is there a setting I can adjust or is it a feature?

**Comment by rolandlo** [comment]
I can't reproduce this on Ubuntu 22.04 (in fullscreen mode). Maybe it's a Windows issue. When I'm not in fullscreen mode the Window is dragged with the top toolbar though.

**Comment by HerrNamenlos123** [comment]
I just tried it on Ubuntu 20.04 and the situation is better there. The window is not draggable in fullscreen mode, but it still is when it is maximized.

On Windows it is also draggable in maximized mode so that's the same, but when in fullscreen mode it is still draggable, but without a title bar and window borders, which looks really weird. ​

I don't know about you but I think the window should not be draggable from the tool bar in any mode

**Comment by rolandlo** [comment]
> I don't know about you but I think the window should not be draggable from the tool bar in any mode

I agree, it's an annoying behaviour in any case. It looks like the Window is only dragged once the coursor leaves the toolbar (and enters the document widget).

**Comment by rolandlo** [comment]
The solution is actually pretty simple: Just add the CSS rule

```CSS
#mainMenubar, #tbTop1, #tbTop2, #tbBottom1, #tbBottom2, #tbLeft1, #tbLeft2, #tbRight1, #tbRight2 {
    -GtkWidget-window-dragging: false
} 
``` 
to `ui/xournalpp.css` in the `Shared Resources folder`, see [file locations](https://xournalpp.github.io/guide/file-locations/)
Then dragging from the menubar or toolbars is not possible anymore.

**Comment by LittleHuba** [comment]
Should we add this to the release as default?

**Comment by rolandlo** [comment]
> Should we add this to the release as default?

That looks like a good idea to me. I will make a PR.

**Comment by HerrNamenlos123** [comment]
> The solution is actually pretty simple: Just add the CSS rule
> 
> ```css
> #mainMenubar, #tbTop1, #tbTop2, #tbBottom1, #tbBottom2, #tbLeft1, #tbLeft2, #tbRight1, #tbRight2 {
>     -GtkWidget-window-dragging: false
> } 
> ```
> 
> to `ui/xournalpp.css` in the `Shared Resources folder`, see [file locations](https://xournalpp.github.io/guide/file-locations/) Then dragging from the menubar or toolbars is not possible anymore.

This works perfectly for me!
