### ISSUE TITLE
Stroke delete eraser takes a long time to erase with 200% display scaling

### ISSUE THREAD

**Issue by dylanlinux** [xournalpp/xournalpp#3903]
- OS: Arch Linux
 - Desktop environment: GNOME 41, wayland or X11
 - libgtk version 3.24.33
 - Xournal++ version 1.1.1 (commit 4f113e94)
 - Installation method: Arch repo (pacman)

When using 200% display scaling, the "delete stroke" eraser takes several seconds to delete strokes. If you want to erase a line of text for example, you would run the eraser across that line of text, wait a couple of seconds, and then it will all erase at the same time. This happens with both wayland and X11. Setting the display scaling to 100% in GNOME settings fixes this issue; with 100% scaling, strokes are deleted immediately when touched with the eraser.

1. Set display scaling to 200% in GNOME settings
2. Open Xournal++
3. Open or create a document with at least a few lines of handwriting
4. Select the "delete stroke" eraser
5. Try to erase a line of text with the eraser tool. It will take a second or more for the line to be deleted

Expected behavior: Strokes should be deleted as soon as the eraser touches them, rather than a few seconds after. This is how it works with 100% display scaling.

Video of the issue: https://youtu.be/KIoZmCGSCxI

If there is anything I can do to make troubleshooting this easier, let me know

**Comment by bhennion** [comment]
Thanks for reporting this.

I guess this is due to this line

https://github.com/xournalpp/xournalpp/blob/5ddad8d7017f19419f97c5a850bfd2d202cda83b/src/core/control/jobs/RenderJob.cpp#L88

I don't know why it was made this way, but with HiDPI scaling the entire page gets rerendered every time, instead of just the small part that has been modified. This is obviously suboptimal.

Hopefully, fixing this should fix this issue.

**Comment by LukasBraendli** [comment]
Hello all. 
I can confirm this issue. Besides the problem with stroke eraser taking a long time to erase, I am facing general performance issues, especially while zooming and panning (I am also annotating PDFs with large images, which probably increases the computational load for rendering). 

- OS: Manjaro Linux (Arch derivate)
- Desktop Environment: Gnome 41.3, Wayland
- Xournal++ Version: 1.1.1
- Device: Thinkpad X1 Yoga 4th, i7-8565, Intel UHD Graphics 620
- Display: 3840x2160 @200% scaling

I tried to build xournal++ with the modification that @bhennion mentioned. That is removing the clause `|| dpiScaleFactor > 1` clause from "xournalpp/src/core/control/jobs/RenderJob.cpp" line 88. This however resulted in a weird behaviour where the part of the document that was being erased was rendered at a different location with a different scaling on the screen. The erase performance was not improved. See this video for a demonstration (pay attention to top left).

Setting global Gnome display scaling to 100% drastically improves overall performance.

**Comment by bhennion** [comment]
@LukasBraendli @dylanlinux: Could one of you try out the PR #4082 and see if this improves the performances for you?
If you don't know how to, I can help with the process.
