### ISSUE TITLE
Switching to default tool doesn't un-highlight the previous tool icon

### ISSUE THREAD

**Issue by mhaiman** [xournalpp/xournalpp#3918]
When switching to the default tool using the tool bar, the icon for the previously selected tool remains highlighted until after the new tool is used.  I suspect the cause has to do with the fact that the default tool doesn't highlight its own icon.

Xournal++ version 1.1.1 of Feb 13, 2022, installed from [xournalpp-1.1.1-Ubuntu-bionic-x86_64.deb]
OS Linux Mint 19.3 (based on Ubuntu 18.04), Cinnamon desktop
libgtk 3.22.30

BTW, apart from this and another minor bug (which I'll report separately), I really like the new version.  Thank you for all your work!

**Comment by rolandlo** [comment]
Fixed by PR #3947 (on the `release-1.1` branch)
