### ISSUE TITLE
Converting .xopp file to .svg in Node JS

### ISSUE THREAD

**Issue by adamAfro** [xournalpp/xournalpp#3926]
I am writing my notes with Xournal++, and say: I want them saved on a server (running with Node JS) and be able to view them without additional computing, like on my PC for example.

My idea is to convert them remotely to `.svg` so that browser can handle it. It is [pointed](https://klein.mit.edu/~auroux/software/xournal/manual.html#file-format) that `.xopp` file is just gzipped XML, so it seems enough to just unzip it ([maybe with some NPM dependency](https://www.npmjs.com/package/tar-pack)) and then convert that XML into SVG.

My guesses are:

- I could wrap some C++ from Xournal (no idea how does it work with Node *yet*);
- I could learn how does the format works - how does it converts between `.svg` and `.xopp`, like: what is what;

In both cases having the file that makes `.svg` conversion would be helpful (which I failed to locate :(), possibly some docs I could read

**Comment by rolandlo** [comment]
Why exactly are you trying to convert the XML to SVG when there is an export option for SVG (which can be used both from the command line and via a plugin)?

**Comment by adamAfro** [comment]
The thing is I am saving my files as `.xopp` and then putting on a server for both: backup and rendering as I may need to check my notes on mobile or something. `.xopp` is default so it seems reasonable to keep just it - I can edit it later on, if something happens... additionally it is less clicking while saving ;)
 
Yeah it is possible to just convert it with Xournal++, which I do now using Node's `exec()`. I actually made it to make PDFs and I am content with it so the issue is **not that important**... I just thought it would be more optimal to do it with some not-so-much external function and as it is XML, I am guessing it is not tragically complicated

Still, **despite app's possibilities**, I think it may be helpful to know the format

**Comment by LittleHuba** [comment]
Well the XML format just carries the basic information. You would need to duplicate the drawing algorithms of Xournal++. Certainly possible but I do not really see the benefit to tell the truth. Whenever we change our drawing algorithms you would need to do so as well. And it might not be obvious that we changed something until your visualization renders obviously wrong results.

**Comment by adamAfro** [comment]
Yhm, I see your point. Thanks for replying and clearing that out for me

**Comment by MrPancakes39** [comment]
@adamAfro why don't you use Xournalpp ability to export as PDF? PDFs are viewable in the browser both mobile and desktop (if I recall correctly). Furthermore if you need it as an SVG you could always convert the PDF to SVG using inkscape or an npm package.

So something like xopp -> pdf -> svg.

**Comment by adamAfro** [comment]
@MrPancakes39 hey, thank for reply :smile:! I've sticked to PDF eventually. Didn't know one can do :factory: more with pdf, tho :speech_balloon: *PDF to SVG using inkscape or an npm package*

I think I will just close the issue
