### ISSUE TITLE
Don't rasterize SVG images

### ISSUE THREAD

**Issue by haizaar** [xournalpp/xournalpp#3936]
Good day,
I'm a new xournalpp user here so not sure if this behavior is intended.

I noticed that when I insert SVG images into the notes they are rasterized instead of being kept as vector.
As a result, the images looks pixelized in the final PDF when zoomed.

Consider the classic [tiger.svg](https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg). Put in on the notes, then zoom into eye (note the pixels)

![Screenshot_20220330_145444](https://user-images.githubusercontent.com/58201/160748594-e028da95-3cb0-4af5-a4f6-ab80c4500074.png)

The same image if put directly on pdf e.g. using Inkscape:
![Screenshot_20220330_145455](https://user-images.githubusercontent.com/58201/160748645-3e2c98bf-3a56-4874-be5e-39ef70265030.png)

**Describe the solution you'd like**
Is it possible to keep SVGs as vectors (including when exporting to PDFs) ? 

Thank you again for developing this amazing software!

**Comment by K4LCIFER** [comment]
See #1288
