### ISSUE TITLE
Unable to build on MacOS Monterey

### ISSUE THREAD

**Issue by psloh** [xournalpp/xournalpp#3949]
**Affects versions :**
 - OS: Mac
 - Which version of libgtk do you use: unable to build GTK
 - Version of Xournal++: Commit 428fba2680049abcfa98d77942c62e851e1c2a7e
 - Installation method: Trying to build from source

**Describe the bug**
I'm trying to follow the build instructions on https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md, but they don't work. Specifically, in the `build-gtk3.sh` step, when `itstool` fails, I don't have the fallback option to use Python 2, because MacOS Monterey only has Python 3. Is there a workaround? I have tested this on a fresh user account which I just created, to avoid conflicts with Homebrew.

**To Reproduce**
1. Simply clone the git repo, and run the first step: `build-gtk3.sh`. It fails at `itstool`.

**Expected behavior**
The build was supposed to complete.

**Comment by rolandlo** [comment]
First of all, building GTK via Jhbuild on MacOS is complicated and it's always a struggle to get through it. None of us has Monterey installed and we really can't provide much support. 
You could try to run the steps from `build-gtk3.sh` and figure out which step fails. If it's a `gtk-osx` problem, you can either open an issue on the `gtk-osx` [issue tracker](https://gitlab.gnome.org/GNOME/gtk-osx/-/issues) or sign up to the `gtk-osx-users-list` [here](https://mail.gnome.org/mailman/listinfo/gtk-osx-users-list) and ask there.

If all you don't necessarily want to build the latest Gtk yourself, but to build Xournal++ on top of it, consider downloading the Gtk blob (built by the Xournal++ team) as in https://github.com/xournalpp/xournalpp/blob/master/azure-pipelines/steps/build_mac.yml#L15-L16

**Comment by Technius** [comment]
As a temporary workaround, you could [try installing Python 2.7 with pyenv](https://stackoverflow.com/a/67274521), but I'm not sure how reliable of a method that is.

If you're interesting in using MacPorts instead of homebrew, I'm currently working on fixing some remaining issues in #2390 (a MacPorts-based build) to make building on macOS simpler and easier. I managed to get latest master to build from source on my M1 Mini with Monteray, but there's still some remaining work that needs to be done to produce a full application bundle.

**Comment by K-W-Li** [comment]
In my humble opinion, I would recommend using Homebrew as it ensures reliable dependencies.

I can confirm xournal++ build on MacOS Monterey with Homebrew.
However it only works for tag [v1.1.1](https://github.com/xournalpp/xournalpp/tree/v1.1.1).

The current [master branch](https://github.com/xournalpp/xournalpp/tree/7b6d84956d6bbe8615b2123c64dd0cac80afb81a) failed build with Homebrew.
The error message shows ```cairo/cairo.h not found```, probably something not right in cmake file.
