### ISSUE TITLE
Images distorted and cropped in version 1.1.1+dev

### ISSUE THREAD

**Issue by TheDoctorT** [xournalpp/xournalpp#3951]
**Affects versions:**
 - OS: Ubuntu 20.04
 - Desktop environment: GNOME Desktop
 - Version of libgtk: 3.24.20
 - Version of Xournal++: 1.1.1+dev

**Describe the bug**
Images (imported or pasted) get distorted: the image is compressed horizontally and the bottom part is cropped. Sometimes they are also compressed vertically.

**To Reproduce**
1. Save image or copy it in clipboard
2. Paste or import image into document

**Expected behavior**
The image should be imported or copied without being distorted

**Screenshots of Problem**
1.1.1+dev
![Schermata da 2022-04-11 19-55-30](https://user-images.githubusercontent.com/46628728/162802084-47bf9b0d-dc18-4d00-9de4-beac08afd611.png)

1.1.0+dev
![Schermata da 2022-04-11 20-10-39](https://user-images.githubusercontent.com/46628728/162802758-973fbd2c-c866-4a77-a246-e221d41d3581.png)

**Additional context**
This happens with files created with previous versions of Xournal++ as well. Rolling back to 1.1.0+dev solves the issue. Files created with 1.1.1+dev still have distorted images, old files return normal if they haven't been edited, otherwise they stay distorted. It affects jpg and npg.

**Comment by rolandlo** [comment]
That must be a recent regression. With the version from March 29, 2022 it worked fine. Now it doesn't.

**Comment by rolandlo** [comment]
The culprit is 72be311a7fb5bfa38cd0b1b74e3c830b02420a2f

**Comment by Technius** [comment]
A fix has just been merged and will appear in the next nightly build. If you overwrote any files while using the bugged version, you may want to load an autosave if possible (located in [the cache folder as shown here](https://xournalpp.github.io/guide/file-locations/#where-to-find-xournal-files)) or restore a file from backup. Apologies for the inconvenience.
