### ISSUE TITLE
macOS Monterey : some input methods for non-English text

### ISSUE THREAD

**Issue by YangThinking** [xournalpp/xournalpp#3956]
(Please complete the following information, and then delete this line)
**Affects versions :**
 - OS: macOS Monterey & M1Max

**Describe the bug**
Unable to enter Chinese text, Can only enter English text.

**To Reproduce**
1. Step 1 : open Xournal++ APP
2. Step 2 : enter Chinese text
3. Step 3 : Can only enter English text.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
This may have been fixed in #4090. Currently it is only in the `release-1.1` branch though.

**Comment by rolandlo** [comment]
This has most likely been fixed with the 1.1.2 release. I'm closing the issue therefore.
