### ISSUE TITLE
[Enhancement] Allow modifier key to disable line tool snapping.

### ISSUE THREAD

**Issue by macxcool** [xournalpp/xournalpp#397]
Enhancement:
When using the line tool I sometimes want to turn off the snapping behaviour near the horizontal and vertical. It would be nice to be able to use a modifier key (Ctrl, Shift, Alt??) to disable snapping temporarily so I can draw a line that's close to vertical or horizontal.

**Comment by andreasb242** [comment]
Done. Additional: draw a square instead of a rectangle, if shift is pressed.
