### ISSUE TITLE
Can't use the new "Select PDF text" tool after I added a page

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#3971]
**Affects versions :**
 - OS: ArchLinux GNOME 42 Wayland, but also on Ubuntu 20.04 GNOME 3.36.8 Xorg, so I don't think it's a distro fault
 - Which version 
     - Arch: xournalpp 1.1.1+dev ibgtk: 3.24.33
     - Ubuntu: xournalpp 1.1.1+dev ibgtk: 3.24.20
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
     - Arch: AUR git version
     - Ubuntu: don't remember

**To Reproduce**
1. Open a PDF
2. Insert a page
3. Select text with the new "Select PDF text" tool, and try to click on one of the options. No option actually do anything. In the pages BEFORE the inserted page, it works. In the pages AFTER the inserted page, does not work.

**Expected behavior**
Should work as expected.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Thanks for reporting. I can confirm the bug.

**Comment by All3xJ** [comment]
If I move the inserted page to the last page of the document, I "bypass" the bug, because the bug only happens on pages AFTER the inserted page, so if no page is after the insterted page because it's the last page, the bug does not happen
