### ISSUE TITLE
Paint lags of text tool under large zoom maginification.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#3977]
This is not so serious.
**Affects versions :**
 - OS: Linux
 - Desktop environment: X11 with xmonad
 - libgtk: 3.24.33
 - Version of Xournal++: 1.1.1+dev (176e95ac05e30fbf5a5971af6ce2750cf90fe50f or after)
 - Installation method: built from source

**Describe the bug**
When the zoom magnification is set to maximum and a wide letter like W is typed in text tool, the right half of the letter may not be displayed for about 0.5 seconds. If you type letters in succession with key repeats, only the last letter get this delay.

**Screenshots of Problem**

https://user-images.githubusercontent.com/6355486/164603514-8c0ada12-3604-443d-945b-b809f5ef19b2.mp4

**Additional context**
This was introduced by the commit 176e95ac05e30fbf5a5971af6ce2750cf90fe50f.

**Comment by Technius** [comment]
Also affects 1.1.x branch, so we'll need to fix this bug before 1.1.2 release.

I think the issue might be that the text bounds are not being multiplied by the zoom level. Will need to double check.

**Comment by bhennion** [comment]
Fixed on the release branch, soon to be merged into master. Closing.
