### ISSUE TITLE
Text fields immediately close when created with middle mouse button

### ISSUE THREAD

**Issue by AstusRush** [xournalpp/xournalpp#3983]
**Affects versions :**
 - OS: Linux (_confirmed under_ Kubuntu 22.04 _and_ Tuxedo_OS (Ubuntu) 20.04 _(both using Xournal++ v1.1.1)_)
 - Desktop environment: KDE Plasma Desktop
 - Graphics Platform: X11
 - libgtk version: 3.24.29
 - Version of Xournal++: 1.1.1 (Git commit 4f113e94)
 - Installation method: Discover Software Centre (Source: ubuntu-jammy-universe (Ubuntu 22.04 LTS))

**Describe the bug**
When I select the text tool for the middle mouse button I can only type for as long as I hold down the button (except if I also select the text button for the left mouse button).

**To Reproduce**
1. Select the Pen tool for the left mouse button
2. Select the Text tool for the middle mouse button
3. Click inside the document with the middle mouse button

**Expected behavior**
The expected behaviour is that the text field stays open until I explicitly exit it e.g. by pressing Esc.

**Additional context**
This behaviour is caused by the tool always switching back to the one of the left mouse button after releasing the right or middle mouse button. The problem is, that this should not close the active text field. Xournal (not ++) handles this case correctly.

**Comment by Jared234** [comment]
I am currently working on a fix for this bug. I will create a pull request in the next few days.

**Comment by Technius** [comment]
From #4309:
> @Jared234: This is an attempt to fix the bug mentioned in #3983. After testing and debugging I realized that this bug not only appears if you use the middle mouse button, but also if you choose the right mouse button to open a text field.appears if you use the middle mouse button, but also if you choose the right mouse button to open a text field.

I can confirm that stylus side buttons also have the same issue. I believe this bug occurs whenever the text tool is assigned to any "non-primary" input button.

**Comment by rolandlo** [comment]
Fixed via #4309.
