### ISSUE TITLE
Loads of `g_closure_unref: assertion 'closure->ref_count > 0` in terminal after app closing

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#3986]
When closing the app, the terminal gets flooded with messages 
```
(xournalpp:94971): GLib-GObject-CRITICAL **: 20:08:08.640: g_closure_unref: assertion 'closure->ref_count > 0' failed
```
(dozens/hundreds of them).

A `git bisect` lead to f2cdd55bdb925dbb6be2234c50d102976cea7ce2 being responsible.

@Febbe, do you know what could be causing this?

**Comment by Febbe** [comment]
Fixed by [951a41b](https://github.com/xournalpp/xournalpp/commit/951a41ba0f4331ddf4fdfa7d2640d85e7aae23e0)
