### ISSUE TITLE
Writing/Drawing is not smooth

### ISSUE THREAD

**Issue by sharkEater18** [xournalpp/xournalpp#3991]
**Affects versions :**
 - OS: Linux, Ubuntu 22.04
 - (Linux only) Desktop environment:  Gnome-Wayland
 - Which version of libgtk do you use
     3.24.33
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     1.1.1
 - Installation method: apt

**Describe the bug**
Drawing is no longer smooth after I upgraded from Ubuntu 21.10 to 22.04. One thing to note down is that drawing is(was) only in Ubuntu 21.10 for my case at least.

**Expected behavior**
I want drawing to be smoother like one note in windows.

**Screenshots of Problem**
![Screenshot from 2022-05-01 00-58-39](https://user-images.githubusercontent.com/74261929/166120000-7d98078a-0ce3-4456-a583-d79fe5824671.png)

**Comment by K4LCIFER** [comment]
What tablet do you use?

**Comment by sharkEater18** [comment]
> What tablet do you use?

I don't use any tablet or similar external drawing devices. I just use my mouse (decent one from Logitech) to visualize some problem I'm working on.

**Comment by Technius** [comment]
The right side version looks a lot more pixelated ("not smooth") than the left side version. If you insert an image, does it also look pixelated?

**Comment by sharkEater18** [comment]
> The right side version looks a lot more pixelated ("not smooth") than the left side version. If you insert an image, does it also look pixelated?

You mean just insert an image, then no. The image appears as it is. And the LEFT  side is some work that I have done before updating my OS.

**Comment by sharkEater18** [comment]
Seems like messing with the settings work for me. 
Solution: 
Edit-> Preferences-> Input Stabilization
Averaging Method: Arithmetic Mean
Preprocessor: Inertia
It wasn't an OS issue neither was the mouse fault.
