### ISSUE TITLE
Xournal++ unable to write LaTeX: failed to find pdflatex

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3996]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: GNOME 42.1, Wayland
 - Which version of libgtk do you use: 3.24.33
 - Version of Xournal++: 1.1.1
 - Installation method: Flatpak

**Describe the bug**
Clicking the "Add/Edit TeX" button results in the following error: 
![image](https://user-images.githubusercontent.com/7829231/166132308-a6ac2fe8-ef5f-46dd-acb3-bd172768744e.png)

**To Reproduce**
Unknown. I simply clicked the button.

**Additional context**
I have pdflatex installed (3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux))

**Comment by rolandlo** [comment]
That's due to the sandboxing for the flatpak. See https://github.com/flathub/com.github.xournalpp.xournalpp#latex-support if you want to add latex-support to the flatpak. Alternatively use a different package (AppImage, snap package or xournalpp-git on Arch)

**Comment by Technius** [comment]
I think this error is frequent enough that we should probably add a more prominent explanation of how to setup latex correctly on Flatpak. Perhaps a note in the latex tab of the preferences window, or an explicit check for Flatpak?
