### ISSUE TITLE
The bottom menu bar is way too big.

### ISSUE THREAD

**Issue by Mrestof** [xournalpp/xournalpp#4005]
**Affects versions : latest (1.1.1)**
 - OS: Linux
 - Desktop environment: Wayland (Sway)
 - libgtk version: "3.24.33"
 - Version of Xournal++: 1.1.1
 - Installation method: from `extra` repository using Arch's `pacman`

**Describe the bug**
The bottom menu bar is enormously large and I can't make it smaller.

**To Reproduce**
Install the Xournal++ and run it without passing any options or arguments.

**Expected behavior**
Obvious from description

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/23293364/166508544-5cd8d902-f265-439b-a280-89e13f5976bb.png)

**Comment by danemtsov** [comment]
I'm not sure what exactly you're referring to, but if it's the bottom tool bar, it is larger than the top ones due to the zoom slider. If that bothers you, you can remove the slider with _View > Toolbars > Customize_ and dragging it out from the toolbar.

**Comment by Mrestof** [comment]
Oh, that's way better, thanks for advice.
