### ISSUE TITLE
Lag when writing with pen

### ISSUE THREAD

**Issue by ProudBeluga** [xournalpp/xournalpp#4011]
**Affects versions :**
 - OS: Windows 11 (Surface Pro 8)
 - Version of libgtk: 3.24.33
 - Version of Xournal++: 1.1.1+dev
 - Installation method: Downloaded via the website then ran the installer with all default parameters

**Describe the bug**
When writing with a pen the stroke disappear after lifting the pen. take some time then appears back. Also writing near previous strokes makes them disappear as well. 

**To Reproduce**
1. Open new document
2. Write with pen

**Expected behavior**
The strokes should appear almost instantly and should not make near ones disappear 

**Video of Problem**
https://user-images.githubusercontent.com/93699537/167195069-15492e40-aa24-4520-b283-67be286522ea.mp4

**Comment by MichelReims** [comment]
I will receive a surface pro 8 this week. I will test xournalpp

**Comment by Technius** [comment]
What is the "Git commit" listed in the `Help > About` window? This could help narrow down the problem.

**Comment by ProudBeluga** [comment]
eed169fb-dirty

[image: image.png]

Pascal Bérubé
***@***.***
cell: 418-965-7410

*Avis de confidentialité / Privacy Notice *: Ce message peut contenir de
l'information confidentielle ou protégée. Il s'adresse uniquement à la
personne destinataire visée. Si vous l'avez reçu par erreur, nous vous
prions de nous en informer et de le supprimer complètement de votre
système. / This message may contain confidential or privileged information.
It is intended only for the addressee person. If you have received it in
error, please notify us and delete it completely from your system.

**Comment by bhennion** [comment]
There has been some recent changes to the StrokeHandler class https://github.com/xournalpp/xournalpp/commit/f66a5e67fd91bc12d37937b304c8ea9c6b66115b.

@ProudBeluga would you happen to know if the app was working as expected before that (i.e. in April)?

**Comment by ProudBeluga** [comment]
Yes, everything was fine up until last week.

Pascal Bérubé

**Comment by bhennion** [comment]
Thanks! I'll have a closer look at what could trigger this.
@xournalpp/core Can anyone reproduce on any other OS? I definitely cannot on Linux.

**Comment by danemtsov** [comment]
#4016 is the same on Linux (Kubuntu)

**Comment by bhennion** [comment]
> #4016 is the same on Linux (Kubuntu)

Oh right, thanks!

**Comment by bhennion** [comment]
And do affected people happen to have a HiDPI screen? This could explain my inability to reproduce

**Comment by MichelReims** [comment]
I confirm the problem on surface pro 8 with the last dev-nightly version of xournalpp.
On the other hand, xournalpp version 1.1.1 of Feb 13 2022 has not the problem

**Comment by bhennion** [comment]
Ok, I managed to reproduce by faking a HiDPI setting. A fix is available in #4019, and installers for various platforms are available in [this post](https://github.com/xournalpp/xournalpp/pull/4019#issuecomment-1121397499).

You are all invited to check out the fix and tell me (in #4019) if it works for you.

**Comment by bhennion** [comment]
> Seems to have done the trick. Thanks a lot

The fix has been merged and will appear in the next nightly build. Thanks for reporting and for the help tracking the issue down
