### ISSUE TITLE
lag and flickering when using pen

### ISSUE THREAD

**Issue by domenicozambella** [xournalpp/xournalpp#4016]
**Affects versions :**
   - Kubuntu 20.04
   - libgtk: 3.24.20
   - xournalpp: 1.1.1+dev
   - Installation method: PPA

The problem begun end of April after an upgrade.

https://user-images.githubusercontent.com/26542246/167398403-a68206bf-0bac-4ac2-8512-2e642a5b9dbe.mp4

**Comment by danemtsov** [comment]
Probably duplicate of #4011
