### ISSUE TITLE
LaTex not working all time in xournalpp

### ISSUE THREAD

**Issue by IliHanSoLow** [xournalpp/xournalpp#4020]
Hello,
My OS is Linux and I am using Plasma on EndeavourOS; the GTK-Version is 3.24.33 and the xouurnalpp Version is 1.1.1. I cloned the git-release from aur using pacman.

What happened to me multiple times now is, that I tried to use a add a equation (e.g. "m_2=m" or "F_{grav}=6,67*10^{-11} \frac {m^3}{ks*s^2}*\frac {(69kg)^2}{(1m)^2} \approx 2,8*10^{-7}N")  with LaTex which worked once per system-boot but when I tried it again, normal letters work except you add numbers or special characters like "_".

1. Strg+Shift+X to open LaTex
2. type in anything
3. Try to change something or add a new LaTex - Window with numbers or special characters

I expect, LaTex showing the corrected or new equation in the preview and embedded in the document.
But instead this happens:

In Coding Window:
![image](https://user-images.githubusercontent.com/92159488/167463811-e965d8c6-6aec-4d60-8a86-eac8e72161aa.png)

Out of coding Window:
![image](https://user-images.githubusercontent.com/92159488/167463982-3c5c67d7-8967-4c1b-828c-2af64117eeed.png)

Or this happens if I start a document again:
![image](https://user-images.githubusercontent.com/92159488/167464163-81632432-5a45-42b7-8aa5-4317dbed69f2.png)

Out of coding window:
![image](https://user-images.githubusercontent.com/92159488/167465390-d84fffe0-f7b8-483b-a98a-a8cdb05e5590.png)

Over all LaTex does only work one time per boot fine and then it just stops working correctly.
This happens only in xournalpp, not in an normal latex editor.
Maybe this is all on me but I cant think of a mistake I have done.

Thank you in advance.

**Comment by tattsan** [comment]
@IliHanSoLow 
As discussed at #4018 , this seems to be poppler's bug. For a workaround, try to revert poppler-* to 22.03.0 .

**Comment by IliHanSoLow** [comment]
Ok, but how do I downgrade?

**Comment by tattsan** [comment]
To downgrade the packages, see
https://discovery.endeavouros.com/pacman/downgrade-packages/2021/03/

Btw, the forthcomming 22.05.0-2 will fix the issue.

**Comment by IliHanSoLow** [comment]
Ok thank you, if this is the case ill wait, because otherwhise I had to downgrade all packages depending on poppler, hadnt I

**Comment by tattsan** [comment]
You don't have to downgrade packages depending on poppler.
The packages that need to be downgraded are:
`poppler`,  `poppler-glib`,  `poppler-qt5`,  `poppler-qt6`.

**Comment by IliHanSoLow** [comment]
I tried it now with the new Version and it works. So I guess I'll close this issue. Thanks for the help.
