### ISSUE TITLE
Assertion 'GTK_IS_WIDGET` failed upon quiting when individual layer preview has been opened

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#4026]
**Affects versions :** latest master 7da9a156b5e9bf9ee5167559966f7cde9c497321

**Describe the bug**
A series of messages 
```
(xournalpp:30974): Gtk-CRITICAL **: 22:04:37.161: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```
appear when quitting the app if the preview sidebar has been set to either individual layers or layer stack.
There seem to be 1 such message per layer (background included) if you only used one of individual-layers or layer-stack modes, and twice as many message if both modes have been used (sequentially) before quitting the app.

The bug does not seem to manifest itself when opening a new document (instead of quitting).

**To Reproduce**
1. Open Xournal++ from a terminal and add a stroke to the default empty file.
2. Open the preview sidebar, and set it to show the layers individually
3. Close the app (and click on Quit without saving)
4. Read the terminal output

**Comment by danemtsov** [comment]
This is the sidebar preview entries destroying a widget they don't own a reference to:
https://github.com/xournalpp/xournalpp/blob/7da9a156b5e9bf9ee5167559966f7cde9c497321/src/core/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.cpp#L58-L61

The issue surfaced after 18e7ddfaddc71c94574ea7ff1d71ccbb09b141ba.

As seen here,
https://github.com/xournalpp/xournalpp/blob/7da9a156b5e9bf9ee5167559966f7cde9c497321/src/core/control/XournalMain.cpp#L276-L304
MainWindow is destroyed before Control, so at the time the destructors of the SideBarPreviewEntries run, the actual preview widgets are already destroyed. Adding a pair of `g_object_ref/unref` to SidebarPreviewLayerEntry fixes the issue.

As alluded in https://github.com/xournalpp/xournalpp/pull/3999#discussion_r862512831, there are more potential ref management issues/inconsistencies (searching in conjunction with `gtk_widget_destroy` I found GladeGui, TextEditor, XournalView, BaseElementView and SidebarPreview{Base, BaseEntry, LayerEntry}).
IMHO these should be addressed by replacing owning references with a RAII construct. We could start with the above mentioned and then gradually remove the use of raw `g_object_ref/unref` alltogether.

**Comment by bhennion** [comment]
> IMHO these should be addressed by replacing owning references with a RAII construct. We could start with the above mentioned and then gradually remove the use of raw `g_object_ref/unref` alltogether.

You're right, this is the most sensible long term strategy
