### ISSUE TITLE
The hand tool icon is misaligned

### ISSUE THREAD

**Issue by taaem** [xournalpp/xournalpp#403]
The hand tool is misaligned and cut off, see the screenshot.
![bildschirmfoto von 2018-11-28 17-04-58](https://user-images.githubusercontent.com/7108647/49164719-f5580900-f32f-11e8-93fb-0693623c1adb.png)

**Comment by andreasb242** [comment]
This does not happen on my system.
Please try to replace the hand.svg icon with another one, which is working, and tell us, if it's then working (so there is an issue with the Icon) or if it's still not working.

Thank you.

**Comment by taaem** [comment]
I looked at the files a bit and indeed it is an issue with that specific svg, I can open it in inkscape just fine, but if I open it in any Gnome app (like any image viewer) or even VLC it is offset, I digged a bit in the xml and I did find out that if I remove the second viewBox property it moves but unortunally it then offset down left.
So Firefox and Inkscape show the SVG correctly but any Gnome software and VLC shows it offset to the top, like in the screenshot.

**Comment by andreasb242** [comment]
I would copy and open a working Icon in Inkscape, delete everything, copy the contents from the other to the new one, and align it (right toolbar somewhere, you have icons to align it to center).
Try if you can fix the icon. If you have fixed it, I would appreciate a pull request with the fixed Icon ;-)
(else: you can also upload it here)

**Comment by andreasb242** [comment]
fixed: https://github.com/xournalpp/xournalpp/pull/409

So I close this ticket. Thank you!
And feel free to fix other bugs :-)
