### ISSUE TITLE
Application becomes unresponsive to touch and pen input

### ISSUE THREAD

**Issue by hrdl-github** [xournalpp/xournalpp#4031]
I mentioned a "third issue" in https://github.com/xournalpp/xournalpp/issues/4023, which I describe here in more detail.

**Affects versions :**
 - OS: Arch Linux (arm64)
 - Version of Xournal++: https://github.com/xournalpp/xournalpp/commit/7da9a156b5e9bf9ee5167559966f7cde9c497321

**Describe the bug**
Occasionally the application stops receiving touch input events and pen input events. Changing workspaces still results in `event_type=GDK_FOCUS_CHANGE, source_device=GDK_SOURCE_KEYBOARD, device_class=INPUT_DEVICE_KEYBOARD` events. Touch input and pen input result in the following warning:

`Gtk-CRITICAL **: 00:30:15.724: gtk_css_gadget_queue_allocate: assertion 'GTK_IS_CSS_GADGET (gadget)' failed`

Pen input only results in the cursor being moved displayed and moved. This can be temporarily fixed by moving the scrollbar using the touch input, which yields this event:

```
Event type:	GDK_ENTER_NOTIFY
Source device:	GDK_SOURCE_MOUSE
Device Class:	INPUT_DEVICE_MOUSE
```
Afterwards pen and touch input is accepted as usual, starting with the `GDK_ENTER_NOTIFY` events.

**Input Logs**
[xournal-input.log](https://github.com/xournalpp/xournalpp/files/8696204/xournal-input.log) (annotated, comments start with #)
[libinput-devices.log](https://github.com/xournalpp/xournalpp/files/8696206/libinput-devices.log)

**Expected behavior**
Touch and pen input events should be received, logged, and processed as expected.

**Additional context**
This often happens when my wrist is close to the right edge while writing with my right hand. My best guess is that this is another GTK bug, but I'm happy to hear some more qualified opinions.

**Comment by Febbe** [comment]
do you use the X11-handrecognition in the xournalpp settings?

**Comment by 0ceanlight** [comment]
I've encountered this issue as well. I'm on Arch Linux running Xournal++ version 1.1.3 on Wayland.

**Comment by rolandlo** [comment]
@hrdl-github 
I'm sometimes experiencing the same issue on Ubuntu 22.10 (Gnome 43.1) as well. I then close Xournal++, put the stylus back in its case in my Lenovo laptop, take it out again and restart Xournal++. Then everything works again.

**Comment by 0ceanlight** [comment]
> Which window manager / compositor do you use, @0ceanlight?

@hrdl-github I'm on the most recent version of Hyprland.

**Comment by stscheff** [comment]
Is this related to what I'm getting on Windows? If so I might give the gtk dev branch a try.

The program pretty frequently stops responding to normal touch input. I can still draw by holding one finger on the screen and drawing with a second. 

Clicking into to the window with a mouse or the on screen touch pad thing fixes it for a while.

**Comment by stscheff** [comment]
Ok thanks, I'll check it out.
