### ISSUE TITLE
FR: Allow default page decoration/size settings

### ISSUE THREAD

**Issue by DarkTrick** [xournalpp/xournalpp#4034]
**Problem**
Everytime I start xournalapp, I need to reconfigure the page layout: 
- No lines
- Different size

**Solution**
Allow default settings for 
- page size 
- page decoration

**Alternatives**
When creating a new file, use the last used settings. (This might be a totally different FR)

**Additional context**
none

**Comment by rolandlo** [comment]
You're not correctly describing the current situation. Please use menu `View > Configure Page Template` for that purpose.

**Comment by DarkTrick** [comment]
@rolandlo 
I appologize for trying to work around the templates. I changed it accordingly.

**Comment by bhennion** [comment]
I guess this is resolved. Closing
