### ISSUE TITLE
[Request] Feather/Lucide Icons

### ISSUE THREAD

**Issue by SnoutBug** [xournalpp/xournalpp#4039]
I would love to see some new icons, like feather or lucide, for a more modern look.

![Screenshot from 2022-05-19 20-52-24](https://user-images.githubusercontent.com/71790678/169378875-539392f5-0a02-4bb4-9312-521bf5fcc353.png)

I've used them for a about a week now without any issues and I think they are distinct enough to be used without color

**Comment by ericschdt** [comment]
Looks lovely!

> like feather or lucide

Do you have a link to their sources and which license do they use?

**Comment by SnoutBug** [comment]
> Do you have a link to their sources and which licenses do they use?

Sure:
https://github.com/feathericons/feather with an MIT License and
https://github.com/lucide-icons/lucide with an ISC License

**Comment by Technius** [comment]
That looks very nice!

Given that we spent quite a lot of effort changing the default icons in 1.1.0, I'm not sure we want to switch the default icon set so soon. But you could manually mod the icons by by replacing the files in `${prefix}/share/xournalpp/ui/iconsColor-light`, where `${prefix}` is the install prefix (e.g., `/usr/`, `~/.local/`, the folder containing a "portable" installation of Xournal++, etc.).

**Comment by ericschdt** [comment]
> I'm not sure we want to switch the default icon set so soon.

Would you be fine to ship the alternative icons at least together with the project by default, so that the user does not need to replace them manually? :)

**Comment by SnoutBug** [comment]
> ship the alternative icons at least together with the project by default

I think that would be a nice compromise.

This would probably fit in nicely with the already existing checkbox to use system icons and the general already existing customizability.

Perhaps an implementation similar to the one found in libre office would work well?

**Comment by rolandlo** [comment]
> Perhaps an implementation similar to the one found in libre office would work well?

I like the idea (having an `Icon Style` combo-box, where you could choose between the two existing icon styles and the new ones). 
@SnoutBug How do the `xopp-` icon names translate to icon names for the feather/lucide icons?

**Comment by SnoutBug** [comment]
> How do the xopp- icon names translate to icon names for the feather/lucide icons?

@rolandlo I'm not exactly sure whether I understood your question correctly or not. But the process of replacing the icons was pretty straight forward and I was able to use most directly from the repo (or [lucide.dev](https://lucide.dev) to be precise) and I did it as described above.

> But you could manually mod the icons by by replacing the files in `${prefix}/share/xournalpp/ui/iconsColor-light`, where `${prefix}` is the install prefix (e.g., `/usr/`, `~/.local/`, the folder containing a "portable" installation of Xournal++, etc.).

Some I had to modify, like the "Draw Line" icon which does not exist by default, but can be created from [`move-diagonal`](https://lucide.dev/icon/move-diagonal-2).
Additionally I found that the maintainers of lucide are really helpful and my [icon request of a magnet](https://github.com/lucide-icons/lucide/pull/652) (the one you see in the screenshot) was quickly added.

If required, I can contribute the already finished icon pack.

**Comment by rolandlo** [comment]
> If required, I can contribute the already finished icon pack.

Yes, please make a PR with the finished icon pack. You should create a new subfolder in `xournalpp/ui` (named after the icon theme) and keep the same structure (and the same icon file names) as in the `iconsColor-dark` folder. In #3230 we have applied [`svgo`](https://www.npmjs.com/package/svgo) to the icons to decrease file size, which we should do for every icon theme, I think. We will also have to update the file `copyright.txt`. 

I can then take care of replacing the current `Use dark theme` checkbox by a combobox that lets the user choose the icon style (unless you want to do it yourself, which would be fine, too). 
The icon theme name should make it clear if it should be used in dark mode or not, since that will affect the styling of the sidebar, the floating toolbox and the pdf tool.

**Comment by SnoutBug** [comment]
> You should create a new subfolder in `xournalpp/ui`

Just to clarify: I would have created a new folder called `lucide` inside of `xournalpp/ui/iconsColor-dark` next to `hicolor` (which I thought was the current theme's name) instead of `xournalpp/ui`

> The icon theme name should make it clear if it should be used in dark mode or not

While testing I noticed that - depending on the theme - Icons for toggle buttons may be not as easy to discern. A possible solution would be to let the icon adapt to the currently selected theme (i.e. mirroring the "would have" text color of that button to be the icon's color)
![image](https://user-images.githubusercontent.com/71790678/170888127-3801ea8b-f441-47ef-896d-a3ce03f5cbf7.png) Screenshot from Nautilus
Do you think something like this is doable? I found something that sounds promising [here](https://stackoverflow.com/questions/9848101/how-can-i-dynamically-change-the-color-of-an-element-in-an-svg-image-in-gtk), but I have no experience working with GTK.
That would also remove the necessity of having two different icon packs for light and dark theming.

**Comment by rolandlo** [comment]
> > You should create a new subfolder in `xournalpp/ui`
> 
> Just to clarify: I would have created a new folder called `lucide` inside of `xournalpp/ui/iconsColor-dark` next to `hicolor` (which I thought was the current theme's name) instead of `xournalpp/ui`
> 
No, I think you should create a new folder (say `iconsLucideDark`) inside `xournalpp/ui`, also containing a `hicolor` subfolder; `hicolor` is just the name of the default fallback theme. See [this explanation](https://wiki.gnome.org/HowDoI/ThemedIcons) as a reference. 

> > The icon theme name should make it clear if it should be used in dark mode or not
> 
> While testing I noticed that - depending on the theme - Icons for toggle buttons may be not as easy to discern. A possible solution would be to let the icon adapt to the currently selected theme (i.e. mirroring the "would have" text color of that button to be the icon's color) ![image](https://user-images.githubusercontent.com/71790678/170888127-3801ea8b-f441-47ef-896d-a3ce03f5cbf7.png) Screenshot from Nautilus 

I didn't get what you mean with the "would have" text color. How is it determined?

If it's just about dark theme and light theme, we can do like for the existing dark and light icon themes. Only the icons that are different need to be duplicated in the light variant theme, the others are taken from the dark variant folder.

**Comment by SnoutBug** [comment]
> I didn't get what you mean with the "would have" text color. How is it determined?

What I meant is this:
In the screenshot you can see that the color of the icon for the desktop has the color #BDBDBD, while the icon of the toggled button for documents has a darker color (#5D5D5D). If that wasn't the case the icon would be harder to see.
It's probably easier to see in the image below without a color picker.
![image](https://user-images.githubusercontent.com/71790678/170892634-0a176832-71b9-4c1f-87cd-a12a532e1dfe.png)
As you can see, the text color (and icon color) changed depending on whether the button is toggled or not.
Let's say you have a white icon and the button highlight is also white, like it's the case with the zoom fit icon inside Xournal++
![image](https://user-images.githubusercontent.com/71790678/170892756-747ebc13-ca72-413b-9351-fa9353db3ab9.png)
![image](https://user-images.githubusercontent.com/71790678/170892759-99dc5418-0887-439b-af4d-dd1ab3a3e65c.png)
In this case you can't see the icon anymore.

So I was wondering if you could get the default text color of the button while the button is toggled (which would be #5D5D5D) and color the icon the same. I did something like this in a QT QML application by having only one set of white icons and coloring them after the fact to match the current user theme.
That way the icon would always remain visible.

**Comment by rolandlo** [comment]
@SnoutBug Would you mind making a PR for the feather theme icons as well? Code-wise there is very little that must be changed now.

**Comment by SnoutBug** [comment]
Feather icons are Lucide icons. Lucide is just a fork of Feather, since the maintainers of feather don't accept pull requests in a frequent manner and therefore Lucide has a wider variety of icons available. They both follow the same design principles.

**Comment by rolandlo** [comment]
Ok, never mind!
