### ISSUE TITLE
Xournal++ Windows installer crashes

### ISSUE THREAD

**Issue by checkraisefold** [xournalpp/xournalpp#4041]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: N/A
 - Version of Xournal++: 1.1.1
 - Installation method: GitHub release

**Describe the bug**
The installer on Windows crashes on both the nightly and stable build. It crashes late enough that the resulting installation is runnable (except on nightly, which instantly crashes upon opening for me, did not look into) but is still an annoyance nonetheless. The crash has something to do with System.dll (?) calling into SHChangeNotify which crashes.

On the stable installer EXE (https://github.com/xournalpp/xournalpp/releases/download/v1.1.1/xournalpp-1.1.1-windows.zip), the memory location triggering crashing is xournalpp-1.1.1-windows.exe+0x2164

**To Reproduce**
1. Run installer
2. Gets almost to the end
3. Crash

**Expected behavior**
Program to be installed without crashing

**Screenshots of Problem**
![xournalpp-1 1 1-windows_zAE9wCljR7](https://user-images.githubusercontent.com/19525688/169420811-6887993b-ca30-4bc2-bdcf-984c63e152b8.png)

**Comment by Technius** [comment]
What version of Windows are you using?

**Comment by checkraisefold** [comment]
> What version of Windows are you using?

Windows 21H1 Build 19043.1110

**Comment by windows-fryer** [comment]
Same issue on Windows 11 22H2 (OS Build 22616.100) Enterprise

![IMG_0241](https://user-images.githubusercontent.com/90010895/169635328-978374db-be6b-4699-b59e-bed4475fec22.jpg)

**Comment by Technius** [comment]
I managed to reproduce the issue on my Windows computer. For me, the installer just closes without any indication.

**Comment by checkraisefold** [comment]
> I managed to reproduce the issue on my Windows computer. For me, the installer just closes without any indication.

On some computers, including my friend's windows 11 computer, it can instantly close instead of displaying a crash dialog. Dunno why.

**Comment by Technius** [comment]
Crash occurs when refreshing the created icons:
https://github.com/xournalpp/xournalpp/blob/bd6d5c2362700c7cbc875e1ccc99cf5c00e733f9/windows-setup/xournalpp.nsi#L203-L205

**Comment by Technius** [comment]
I tried using a fresh build in my Windows 10 VM. In the VM, without changing anything, the installer is able to run to completion without crashing. However, If I add `Unicode true` at the top of the install script, then I get a crash in the line noted above. I'm guessing there's some problem with the way we're passing in strings to that function above.

**Comment by Technius** [comment]
I assume this will be fixed when I merge #4073. If not, please let me know after the merge closes this issue so I can reopen the issue.
