### ISSUE TITLE
Support alpha channel

### ISSUE THREAD

**Issue by matkoniecz** [xournalpp/xournalpp#4046]
**Is your feature request related to a problem? Please describe.**

I opened PDF file in xournalpp

I opened file with transparency in Gimp.

I copied image from Gimp to xournalpp.

Transparency become lost

**Describe the solution you'd like**

Transparency is not lost

Version, part of not-transparent file

![screen](https://user-images.githubusercontent.com/899988/169796058-cb217808-dceb-476c-994b-99a7374a6f1c.png)

**Comment by matkoniecz** [comment]
As workaround I edited background to be white, what almost worked in this specific case.

**Comment by Rmano** [comment]
Maybe it's a problem in the copy-and-paste? I just tried with the "add image" and the transparency under my image has been respected:

![image](https://user-images.githubusercontent.com/6414907/169804349-8b20dbb7-4167-4013-baa6-dc57f7aff2a6.png)

**Comment by Rmano** [comment]
I have uploaded the PNG so that you can use it for testing:

![UovoPasqua](https://user-images.githubusercontent.com/6414907/169816947-76286fdc-e06a-4af2-b0ba-87e562a252a8.png)
