### ISSUE TITLE
ErasableStroke.testIntersectWithPaddedBox test fails with `-O2 -march=native`

### ISSUE THREAD

**Issue by MithicSpirit** [xournalpp/xournalpp#4050]
**Affects versions :**
 - OS: Arch Linux (probably affects all Linux distros)
 - (Linux only) Desktop environment: WM-only X11
 - Which version of libgtk do you use: 3.24.34
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: latest commit (though has happened for quite a while)
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: build from source

**Describe the bug**
When compiling and running tests with `-O2 -march=native` (or higher optimization level), the test `ErasableStroke.testIntersectWithPaddedBox` fails.

**To Reproduce**
1. Make sure docker is installed and the `archlinux:base-devel` image is available
2. Open a terminal and place the following file in the PWD: 
```sh
#!/usr/bin/env sh

export MAKEFLAGS="-j5"

# echo "======================================================================="
sudo pacman --noconfirm -Syu git cmake help2man gtest texlive-bin gtk3 \
	poppler-glib libxml2 portaudio libsndfile lua53 lua53-lgi libzip
cd ~


echo "CLONING ==============================================================="
git clone 'https://github.com/xournalpp/xournalpp.git' --depth=1
cp -r xournalpp xournalpp-o1
cp -r xournalpp xournalpp-o2
cp -r xournalpp xournalpp-o3

echo "BUILDING =============================================================="
cd ~/xournalpp
mkdir build; cd build
export CFLAGS=" -march=native "
export CXXFLAGS=" $CFLAGS "
cmake -DCMAKE_INSTALL_PREFIX="/usr/" -DENABLE_GTEST=ON ..
cmake --build .
echo "RUNNING TESTS ========================================================="
cmake --build . --target test-units
cmake --build . --target test

echo "BUILDING (O1) ========================================================="
cd ~/xournalpp-o1
mkdir build; cd build
export CFLAGS=" -march=native -O1 "
export CXXFLAGS=" $CFLAGS "
cmake -DCMAKE_INSTALL_PREFIX="/usr/" -DENABLE_GTEST=ON ..
cmake --build .
echo "RUNNING TESTS (O1) ===================================================="
cmake --build . --target test-units
cmake --build . --target test

echo "BUILDING (O2) ========================================================="
cd ~/xournalpp-o2
mkdir build; cd build
export CFLAGS=" -march=native -O2 "
export CXXFLAGS=" $CFLAGS "
cmake -DCMAKE_INSTALL_PREFIX="/usr/" -DENABLE_GTEST=ON ..
cmake --build .
echo "RUNNING TESTS (O2) ===================================================="
cmake --build . --target test-units
cmake --build . --target test

echo "BUILDING (O3) ========================================================="
cd ~/xournalpp-o3
mkdir build; cd build
export CFLAGS=" -march=native -O3 "
export CXXFLAGS=" $CFLAGS "
cmake -DCMAKE_INSTALL_PREFIX="/usr/" -DENABLE_GTEST=ON ..
cmake --build .
echo "RUNNING TESTS (O3) ===================================================="
cmake --build . --target test-units
cmake --build . --target test
```
3. Run `sudo docker run -it --rm -v "$PWD:/repro" --cpuset-cpus="0-4" archlinux:base-devel /repro/repro`
4. The test will fail for the O2 and O3 cases, but not for O1 and no optimization.

**Expected behavior**
The tests should at least succeed on `-O2`, since that is usually considered stable (failing on `-O3` is not ideal but understandable).

**Screenshots of Problem**
N/A

**Additional context**
My CPU is an AMD Ryzen 5 2600, though I suspect that this can be at least reproduced on other Ryzen 5 CPUs.

**Comment by bhennion** [comment]
Thanks for reporting this. I can reproduce. Note however that every thing works if you omit the flag `-march=native`.

I don't know what triggers this weird bug. Let me investigate.

**Comment by MithicSpirit** [comment]
Yes, from my testing both `-march=native` and `-O2` (or `-O3`) are necessary. According to the gcc documentation,
```
           -O2 turns on all optimization flags specified by -O1.  It also turns on the following
           optimization flags:

           -falign-functions  -falign-jumps -falign-labels  -falign-loops -fcaller-saves
           -fcode-hoisting -fcrossjumping -fcse-follow-jumps  -fcse-skip-blocks
           -fdelete-null-pointer-checks -fdevirtualize  -fdevirtualize-speculatively
           -fexpensive-optimizations -ffinite-loops -fgcse  -fgcse-lm -fhoist-adjacent-loads
           -finline-functions -finline-small-functions -findirect-inlining -fipa-bit-cp  -fipa-cp
           -fipa-icf -fipa-ra  -fipa-sra  -fipa-vrp -fisolate-erroneous-paths-dereference -flra-remat
           -foptimize-sibling-calls -foptimize-strlen -fpartial-inlining -fpeephole2
           -freorder-blocks-algorithm=stc -freorder-blocks-and-partition  -freorder-functions
           -frerun-cse-after-loop -fschedule-insns  -fschedule-insns2 -fsched-interblock
           -fsched-spec -fstore-merging -fstrict-aliasing -fthread-jumps -ftree-builtin-call-dce
           -ftree-loop-vectorize -ftree-pre -ftree-slp-vectorize -ftree-switch-conversion
           -ftree-tail-merge -ftree-vrp -fvect-cost-model=very-cheap
```
so I think that the best way forward might be to try these to see which ones cause issues and which ones don't.

**Comment by MithicSpirit** [comment]
I have been able to narrow this down to `-march=native -fexpensive-optimizations -O1`, but I am unable to determine which optimization flag under `-O1` causes this issue. Even manually enabling all `-O1` optimization flags (as determined by `g++ -Q --help=optimizers -O1 | grep enabled`) I still don't get the error. If you have any ideas please let me know.

**Comment by bhennion** [comment]
I made a PR #4054 fixing this (at least for me). @MithicSpirit, please tell me if that fixes it for you.

The bottom line, in any case, is that you can safely ignore this failing test for now. I do not think it detects an actual problem with the app.
