### ISSUE TITLE
Some fonts "NOT" available despite installed

### ISSUE THREAD

**Issue by joepurin2000** [xournalpp/xournalpp#4066]
**Affects versions :**
 - OS: Windows 10 21H2
 - libgtk: 3.24.31
 - Version of Xournal++: Stable 1.1.1
 - Installation method: Official stable release

**Describe the bug**
When I had installed version 1.1.1, I didn't find my installed fonts.
I tried to type the fonts name, but it didn't appear their name to be chosen, especially for recently installed fonts.
Minimal font taskbar shows "None" as image.

**To Reproduce**
1. Step 1: Open Xournal++ normally
2. Step 2: click font box to choose a font
3. Step 3: Type the names of recently installed fonts name.

**Expected behavior**
Find every installed font

**Screenshots 
![Screenshot 2022-05-31 173349](https://user-images.githubusercontent.com/75898167/171154370-e5e3d1bc-d9eb-49b6-a821-859ce9657868.png)
of Problem**

**Comment by rolandlo** [comment]
First two questions: In which directory were your fonts installed? Were they installed for all users (in administrator mode) or not?

The task of finding fonts is given to `fontconfig`, see #3534. With [MSYS2](https://www.msys2.org/) installed (as in the [wiki]()) you can execute 
```term
fc-list.exe
``` 
in the MinGW64 console to get the list of all fonts that `fontconfig` finds. 
At startup of Xournal++ I currently get the message 
```term
Fontconfig error: cannot load default config file: No such file: (null)
```
Using the environment variable `FONTCONFIG_FILE` I can specify a valid file, e.g. with MinGW64 and Xournal++ installed in default locations:
```term
FONTCONFIG_FILE=/mingw64/etc/fonts/fonts.conf "/C/Program Files/Xournal++/bin/xournalpp.exe"
```
makes that error go away.
Maybe it's enough to modify that `fonts.conf` file (if fonts are installed in a non-default location) and (possibly) run 
```term
fc-cache.exe -r -v
```
see https://refspecs.linuxfoundation.org/LSB_3.1.1/LSB-Desktop-generic/LSB-Desktop-generic/fc-cache.html

I haven't tried. Can you point me to example font files which are not detected automatically?

**Comment by ktrNozomi** [comment]
Inspired by @rolandlo , I found the problem. You install fonts usually for a single user whose path is in `C:/Users/<username>/AppData/Local/Microsoft/Windows/Fonts`, however, xournal++ only allows installation for all users, so you can't find fonts which only available for a single user. You can right click the font file to install in `C:/Windows/fonts`.
![Snipaste_2022-08-19_10-18-29](https://user-images.githubusercontent.com/86712470/185528420-60ccf783-771d-43bd-bfac-fdf23153f0c5.png)
![Snipaste_2022-08-19_10-19-05](https://user-images.githubusercontent.com/86712470/185528427-5c517197-dd84-4610-b1c3-d688280e68e7.png)
