### ISSUE TITLE
failed to find LaTeX generator program in PATH: pdflatex

### ISSUE THREAD

**Issue by farzadmohseni-ir** [xournalpp/xournalpp#4069]
### **Error:** 

> failed to find LaTeX generator program in PATH: pdflatex

**Hello
What is the reason for this error?
How do I fix this error to make the math formulas look better?**

1. https://prnt.sc/PyapKfuGAQOD
2. https://prnt.sc/-1palO1PL35G

**Comment by Technius** [comment]
Did you install a latex program like MikTeX?

**Comment by farzadmohseni-ir** [comment]
> Did you install a latex distribution such as [MikTeX](https://miktex.org/)?

**After installing the package from the following website, the problem was solved.
Thank you🌹**

1. https://miktex.org/download
2. https://prnt.sc/jtjgxO1IkLZ4
3. https://prnt.sc/G50UtGY-STXy
