### ISSUE TITLE
macOS launcher executable

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp#4087]
We need a macOS launcher executable to solve the following problems:
* Entry point is a bash script, which means USB device, file system, etc. permissions cannot be granted: #1757 
* The default launcher script created by gtk-mac-bundler is based on GTK2 and may not be correct. Furthermore, upstream gtk-mac-bundler no longer generates the default launcher script by default (thanks to @rolandlo for pointing this out).
* According to @rolandlo, the current macOS nightly build does not run since the launcher script is not being created. We can work around this in the short term by using a launcher script from an older build.

**Comment by rolandlo** [comment]
See #4090. Once this works we can setup code signing on Azure Pipeline. This will require some work, but it will eventually fix #1757
