### ISSUE TITLE
pen circle is too small

### ISSUE THREAD

**Issue by soumyaranjan191819** [xournalpp/xournalpp#4101]
(Please complete the following information, and then delete this line)

**Affects versions :**
  window
**Describe the bug**
while i write i can not see where is my pen due to small pen arrow .
make it mouse arrow or big circle.

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**
make pen circle big or arrow while writing in pen tab
**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![Screenshot 2022-06-18 003823](https://user-images.githubusercontent.com/92353506/174387542-db5a04cf-08a5-4cec-9296-d8a51e2113b9.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by MichelReims** [comment]
See in preferences of Xournal

**Comment by Febbe** [comment]
You can alter the pen cursor in the preferences. If this does not help you, please reopen it with a concise description.
