### ISSUE TITLE
Automate signing a document

### ISSUE THREAD

**Issue by los2pollos** [xournalpp/xournalpp#4111]
Hi there, I'm using the version 0.4.8.2016 on Linux Mint.
I need to sign every page in several files, but always in the same spot. Is there a way to automate this?
I see there is no command interface

**Comment by rolandlo** [comment]
For clarity: 
- How do you sign the pages? By inserting an image or by handwriting with the stylus?
- From the version you specified it seems you are using Xournal and not Xournal++. That may make a difference.

**Comment by Febbe** [comment]
There are better tools out there to do this in an automated fashion:
https://superuser.com/questions/452759/how-to-add-a-picture-onto-an-existing-pdf-file

**Comment by Febbe** [comment]
@xournalpp/core I vote for closing this, we might want to also define a policy, when we should close enhancements.
Currently, our issue tracker is flooded by enhancements we neither can implement nor support, if someone creates a PR for this. 

Also, the benefit for the default user is very limited. Like in this case.

**Comment by Technius** [comment]
Agreed. Closing as out of scope.
