### ISSUE TITLE
One click copy of version information

### ISSUE THREAD

**Issue by funnym0nk3y** [xournalpp/xournalpp#4113]
**Is your feature request related to a problem? Please describe.**
When reporting bugs copying the version information is somewhat tedious. 

**Describe the solution you'd like**
Implement a `Copy version` button which copies the verion information to the clipboard. 

**Describe alternatives you've considered**
Or maybe make the version text markable and copyable.

**Comment by Febbe** [comment]
On UNIX systems, you can just type `xournalpp --version` in the console.

**Comment by Febbe** [comment]
> Except xournalpp --version does not give the commit number for instance.

Then this should be added too.

**Comment by VivekThazhathattil** [comment]
> Making the text markable and copyable in the About window seems to be the best way to get everything.

Hi, can I tackle this issue? 

> > Except xournalpp --version does not give the commit number for instance.
> 
> Then this should be added too.

should the output of `xournalpp --version` be something like `xournalpp 1.1.1+dev (d0a1da37)` if including the commit number?

**Comment by bhennion** [comment]
> Hi, can I tackle this issue?

You're more than welcome to do it, yes! And your suggestion for the terminal output is good too.
