### ISSUE TITLE
Vector-graphics in PDFs sometimes don't render correctly 

### ISSUE THREAD

**Issue by Malex14** [xournalpp/xournalpp#4114]
**Affects versions :**
 - OS: Windows (other OSes not tested)
 - libgtk: 3.24.34
 - Version of Xournal++: 1.1.1+dev (Git commit 0d471f2e-dirty)
 - Installation method: nightly installer

**Describe the bug**
In some PDF document vector graphics are not displayed correctly.

Example:
![grafik](https://user-images.githubusercontent.com/39774812/175542983-c7bef7bf-5663-41e1-a9f3-2810163d017f.png)

How it should look like:
![grafik](https://user-images.githubusercontent.com/39774812/175543205-e07f04ea-60f1-40f4-88f7-02aff1292402.png)

**To Reproduce**
1. Open the attached pdf-file in xournalpp
2. Open the attached pdf-file in some other pdf-viewer
3. Compare the arrows in the drawing. In xournalpp the lines are wiggly and arrow-heads have some artifacts

[xpp.pdf](https://github.com/xournalpp/xournalpp/files/8976440/xpp.pdf)

**Expected behavior**
Vector-graphics in PDFs look as they do in other programs

**Comment by tattsan** [comment]
This bug seems to be introduced by d9424c6bb686fa1f7fd0f693a99573e729203c52, @bhennion.

**Comment by bhennion** [comment]
Thanks a lot for reporting. This should be fixed with #4115.
