### ISSUE TITLE
Icons missing in menu in GNOME

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#4122]
![image](https://user-images.githubusercontent.com/20903913/176432896-357ee8c2-06d1-4459-b8e8-8222757d1f5a.png)

I have GNOME 42.2, ArchLinux.
xournalpp-git 1.1.1.r175.gdcad93630-1

Setting "gtk-menu-images" to 0 (this is in ~/.config/gtk-3.0/settings.ini ) "fixes" the icons by simply removing them:
![image](https://user-images.githubusercontent.com/20903913/176433422-020b6e83-04f2-434c-8a57-8efe3a3efebc.png)

I have this bug since months.

**Comment by bhennion** [comment]
@MatsG23 Thanks for noticing this!
