### ISSUE TITLE
[feature request] Add a toolbar option / icon to change "fill opacity"

### ISSUE THREAD

**Issue by GithubUser699** [xournalpp/xournalpp#4123]
### Problem
Instead of going to _tools → pen / textmarker → fill-opacity_ it would be nice to have an icon that I can place in the toolbar, just the same as there is an icon to turn on _fill_.

![Bildschirmfoto von 2022-06-29 17-47-05](https://user-images.githubusercontent.com/74927253/176480041-1da51496-7b31-4360-971e-7f83dc044390.png)
Here, on the right column the last item, we have an icon to turn on _fill_. Beneath it, I'd like an icon to change _fill-opacity_.

### Usecase
I want to change fill opacity (especially of the marker) quite often (I draw pictures in my notes, they help me a lot), but currently it's quite a long way to change it.

### Version information from _help → info_
Version: 1.1.1
Git commit: nogitfound
Compiled: Feb. 13 2022, 19:40:23
with libgtk: 3.24.24

**Comment by Jared234** [comment]
I am currently working on adding this feature. I will create a pull request in the next few days.
