### ISSUE TITLE
select which layers to export to pdf from command line

### ISSUE THREAD

**Issue by giampierosalvi** [xournalpp/xournalpp#4131]
When exporting to PDF from the GUI, it is possible to select the layers of interest as visible and these are the only layers that will be exported. This is a great feature for creating incremental illustrations (for example for research papers). It would be great if this functionality was made available from the command line. This way, we could have a single source file and a Makefile that automatically creates all the PDFs that we need.

As a comparison, in Xfig, you can run:

`fig2dev -L pdf -D +/-rangelist input.fig output.pdf`

where D stands for depths (which corresponds to layers in xfig terminology). The `rangelist` argument can be complicated, for example +10,40,55:70,80 keeps in total 18 layers, -15 only removed layer 15.

This is different from the `--export-layers` option for two reasons:
1. we usually want to export a combination of layers onto each illustration (there may be a common layer for example, and some additions)
2. we want to export to single-page PDF files for inclusion of each illustration in, for example, a research paper.

Thanks in advance

**Comment by bhennion** [comment]
I had written code to do exactly that a very long time ago. I just submitted it as PR #4143. You can try it out and see if this fits your needs.
