### ISSUE TITLE
we cant select text and copy it directly from pdf files using your awesome software xournal ++ ,

### ISSUE THREAD

**Issue by ALAWIII** [xournalpp/xournalpp#4134]
the problem is :
we are unable to select text and copy it in pdf directly:
the solution is :
make an extension that makes that possible

**Comment by Technius** [comment]
This feature is currently available in the nightly builds. For instructions on how to use the feature, see https://github.com/xournalpp/xournalpp/issues/1745#issuecomment-1028593122
