### ISSUE TITLE
Auto Filenameing missing 

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#414]
I remember that  xournalpp intended automatically filenames. This doesn't seem to work anymore.
Filenames like: `2018-04-18-Note-15-17.xoj`

**Comment by andreasb242** [comment]
This is working for me.
The API of GTK3 has changed, I did some changes.

Have a look at:
bool Control::showSaveDialog()

**Comment by andreasb242** [comment]
https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#gtk-file-chooser-set-filename

**Comment by morrolinux** [comment]
I have the same issue

**Comment by andreasb242** [comment]
If you create a new file? Or when?

**Comment by morrolinux** [comment]
If I open a pdf with xournalpp, when I hit save, the predefined filename is missing instead of having the name of the pdf + xopp suffix

**Comment by andreasb242** [comment]
Confirmed. But if you create a new file without .pdf, it's working, right?

**Comment by morrolinux** [comment]
I think the whole point of the thing was to have the title defaulted to the name of the pdf so that I don't have to copy and paste it in the save dialog ^^
