### ISSUE TITLE
Invalid PageTypeFormat::Copy assigned to actual Page model

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#4142]
I (=@Technius) think I found why the copy format is being produced. Here's a simpler crash reproducer:

1. New document with 2 pages.
2. Use the page format dialog in the toolbar (not the menu) to set page type to copy.
3. Apply page format to current page.
4. Observe segfault.

The issue is in `PageBackgroundChangeController::commitPageTypeChange()`, which does not seem to have the correct handling for the copy page type.

The problem also affects `release-1.1`, so we will need to backport the corresponding fix.

_Originally posted by @Technius in https://github.com/xournalpp/xournalpp/issues/4127#issuecomment-1177231277_

**Comment by WillNilges** [comment]
Working on fixing this in: https://github.com/WillNilges/xournalpp/tree/willnilges/copy-background-crash-fix

**Comment by WillNilges** [comment]
Hamfisted idea is to add a check that straight-up avoids the crash by checking if the background on the current document is the `Copy` type, and refusing to set the background if that's the case.
