### ISSUE TITLE
How to add a new PDF page to the journal?

### ISSUE THREAD

**Issue by MatsG23** [xournalpp/xournalpp#4147]
Hi,
I want to add a new PDF page from a file in the xournalpp file in between the pages (not the "annotate pdf" feature).
I tried using the option 4th option of the "Journal" menu (should be something like "Attach new PDF pages" in English). But it showed me the error "No PDF pages to attach available. You must probably re-open the document.".

How can I do this?

**Comment by rolandlo** [comment]
Currently you can only have PDF pages from one single PDF document. So does your document already have a PDF background and if so, do you want to add a page of the same PDF or from some other PDF?

**Comment by rolandlo** [comment]
One thing that would work is to merge all the PDF's you need into one PDF, using a tool like `pdftk`.

**Comment by Fornball** [comment]
Unfortunately the only way that I have found that will actually import the pdfs into the file is as pictures. You get the pdf, then split it into pictures with the pdftoppm tool. Then paste them onto an empty page, resize them and create a new layer on top. 
You can use my pdftoppm-gui tool if you want a gui tool for the splitting
