### ISSUE TITLE
Being able to add stamps or graphic shapes created to reuse them

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#4169]
_I place this as (improvement). but I apologize because in reality as part of the creation I am useless aspiring to someday be able to program and create my own software or contribute as functions, I'm just a student._ 

**Is your feature request related to a problem? Please describe it.**

NO

**Describe the solution you would like**

I want to be able to open a dockable window to the sidebar or it can be floating and ,can be called as the author wishes, I would like that when I create shapes mostly with the pencil tool and then select all the objects and go to the window click on + to add appears the box to fill some data (name , size, etc.. .. and save) , then when I want to use them enable that window select the shape I want to use at the moment and a stamp icon will appear and every time I click on the canvas paste or just go to the window drag my shape I want and drop it on the canvas and then I can change the color. 

**Describe the alternatives you have considered**

I have not found any alternative to help me speed up the process of creating shapes that I use frequently (different types of triangles). try creating triangles in corel draw and exporting them in .svg format xournal++ interprets them as images and at low resolution.

**Additional context**.

I really like Xournal++ because unlike PDF Annotator Xournal ++ allows me to configure the stroke, I think both are used for the same purpose (notebook and annotate on pdf) used by educators and students in short, there is a tool in PDF Annotator that allows you to save your creations of geometric shapes triangles or any creation and this was very useful. for example when solving geometry problems as a student facilitated to reuse the various forms previously created by me.

**Attached ScreenShot**
**1) I create the Object shape and select what I want to save as stickers or stamps.** 
![image](https://user-images.githubusercontent.com/28522011/181474424-679869d0-6416-4f74-8e24-3f1e063590c1.png)

**2) I click on add + or delete - or edit and I get the box to fill in some data.**
![image](https://user-images.githubusercontent.com/28522011/181475042-213c2ee3-ce86-4ce9-8c72-f75b89cb1486.png)
![image](https://user-images.githubusercontent.com/28522011/181475136-8d30fbbe-fc86-4e76-b322-08986b0f330f.png)

**3) select the object I want to use to be able to use it on the canvas**
![image](https://user-images.githubusercontent.com/28522011/181475367-172dedfd-8d48-4fda-bacf-fdcf23010132.png)

**4) paste as many times as you need the object and allow to change color**
![image](https://user-images.githubusercontent.com/28522011/181475750-81bde78e-cb4e-4ac1-a400-acb31109fd57.png)

**Comment by bhennion** [comment]
Thanks for the feature request. This has already been requested in #1652. It would certainly be an interesting addition to the software, but it's not very high on the priority list. So don't hold your breath :)

Closing as duplicate.

**Comment by vladQll** [comment]
thank you, sorry for not investigating earlier
