### ISSUE TITLE
Pen eraser jumps around and erases unexpected areas.

### ISSUE THREAD

**Issue by guraltsev** [xournalpp/xournalpp#417]
My stylus acts like a pen and the second button makes it appear as an eraser (at the hardware or linux system level, not xournalpp config). This causes an annoying behavior:
 I erase something by holding down the second button (erase key) and touching the canavas in the top left corner of the screen. Now I release the key and remove the stylus. Now suppose that I want to erase something in the lower right corner so I hold down the erase key and touch the canavas in the lower right corner. Often the result is that the pen shape becomes an eraser however centered in the previous position (upper left) and then it quickly races or "jumps" to my current position (lower right) erasing things on its way. It doesn't erase everything but only some places at random on the way. 

This seems largely unpredictable and independent of the timing: it is the same whether I touch the screen with the pen first and then hold the erase button or vice versa. Seemingly the same problem happens. I have noticed (but this is mainly an impression) that this happens worse when the system is under some load. 
I seem to have bettered the situation a little by doing

`guraltsev@malevich:/home/guraltsev$ xinput set-prop 18 303 5 1` 
where

```
guraltsev@malevich:/home/guraltsev$ xinput list-props 18
Device 'ELAN2514:00 04F3:2595 Pen eraser':
        Device Enabled (151):   1
        Coordinate Transformation Matrix (153): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Accel Profile (282):     0
        Device Accel Constant Deceleration (283):       1.000000
        Device Accel Adaptive Deceleration (284):       1.000000
        Device Accel Velocity Scaling (285):    10.000000
        Device Node (274):      "/dev/input/event9"
        Wacom Tablet Area (297):        0, 0, 18344, 10580
        Wacom Rotation (298):   0
        Wacom Pressurecurve (299):      0, 0, 100, 100
        Wacom Serial IDs (300): 9621, 0, 10, 0, 0
        Wacom Serial ID binding (301):  0
        Wacom Pressure Threshold (302): 1
        Wacom Sample and Suppress (303):        5, 1
        Wacom Enable Touch (304):       0
        Wacom Enable Touch Gesture (306):       0
        Wacom Touch Gesture Parameters (307):   0, 0, 250
        Wacom Tool Type (308):  "ERASER" (344)
        Wacom Button Actions (309):     "Wacom button action 0" (310), "Wacom button action 1" (311), "Wacom button action 2" (312), "None" (0), "None" (0), "None" (0), "None" (0), "Wacom button action 3" (313)
        Wacom button action 0 (310):    1572865
        Wacom button action 1 (311):    1572866
        Wacom button action 2 (312):    1572867
        Wacom button action 3 (313):    1572872
        Wacom Pressure Recalibration (314):     1
        Wacom Panscroll Threshold (315):        832
        Device Product ID (275):        1267, 9621
        Wacom Debug Levels (316):       0, 0
```

and by default the parameter:         ``Wacom Sample and Suppress (303):        5, 1``
was set lower (4,6 maybe?)

My stylus setup is as follows:
```
guraltsev@malevich:/home/guraltsev$ xinput
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ ELAN2514:00 04F3:2595                     id=11   [slave  pointer  (2)]
⎜   ↳ ELAN2514:00 04F3:2595 Pen stylus          id=12   [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=15   [slave  pointer  (2)]
⎜   ↳ ELAN2514:00 04F3:2595 Pen eraser          id=18   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ HP Wide Vision FHD Camera: HP W           id=9    [slave  keyboard (3)]
    ↳ HP Wide Vision FHD Camera: HP I           id=10   [slave  keyboard (3)]
    ↳ Intel Virtual Button driver               id=13   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=14   [slave  keyboard (3)]
    ↳ HP Wireless hotkeys                       id=16   [slave  keyboard (3)]
    ↳ HP WMI hotkeys                            id=17   [slave  keyboard (3)]
```

**Comment by morrolinux** [comment]
Looks more like an hardware problem to me... I'm able to reproduce the "jumping" issue just fine even on the desktop:
1) position the pen to one corner of the screen
2) distance the pen from the screen (leaving the pointer in the corner)  
3) get the pen back on the screen near the opposite corner 
4) if you do that slowly enough you'll be able to see the cursor "racing" from where it was to where it is supposed to be now.

Also, the fact that changing driver options will affect this behaviour, leads me to think that's actually an hardware issue.

SD1: I noticed it happens more likely if I do that pressing the second button like you said
SD2: I have a Surface Pro 3

let me know if you're able to reproduce this outside xournalpp as well.

**Comment by guraltsev** [comment]
I wouldn't really know another program to test it in. I believe that the problem is in the hardware, but it seems that there is no way to fix it reliably in the ``libinput`` and/ar ``xsetwacom`` settings. Would you have a suggestion to where to report it and/or if maybe xournal should implement a filter to drop these events. Thanks!

**Comment by andreasb242** [comment]
@guraltsev So there is not always a crash if you use the eraser?

I cannot reproduce this with the eraser, I can reproduce this with the Touchscreen and the Pen.
And then I also got Xournal++ crashed once. I did two tries to get rid of this events from the Touchscreen, without success yet. There are already two tickets open for this.

First: It may has something to do with: #412 (same Author).

So I may need to find out, why it crashes on Touch / Pen Input.

**Comment by andreasb242** [comment]
@guraltsev Can you also check if this is better, or if there is nothing changed? Thank you.

**Comment by guraltsev** [comment]
I am working now with the new patchset and nothing changed. The eraser jumps sometimes and erases on its way

**Comment by andreasb242** [comment]
I changed the complete input handling, now we have one handler instance for each device. It may changes the behavior, but probably not.
But can you may retest?

**Comment by neldredge** [comment]
I'm seeing similar behavior with recent master.  It's fairly frequent but not 100% reproducible.  Is there anything I could do that would help trace it, or determine if it's hardware or software?

**Comment by LittleHuba** [comment]
Hi!

I hope you are aware that this ticket is about 2 years old and our code base shifted from back then quite significantly and therefore all previous information is not of much use for us. It is always a good idea to create a new ticket if all matching ones are closed for more then a year as the reason behind the bug most likely changed. Thus please create a new ticket and follow the steps mentioned in the issue template. That will already help us tremendously with finding the actual issue.

Additonally please do these steps and put your findings in the description of the new issue:
1. https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs
2. Check if the new input system is enabled (if not activate and try to reproduce the bug)
3. Check if you need to activate the "Merge button events with stylus events" in the preferences of Xournal++
