### ISSUE TITLE
Previous saved file open error

### ISSUE THREAD

**Issue by dmohanty640** [xournalpp/xournalpp#4178]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [Windows]
 - Which version of libgtk do you use : 3.24.31.0
 - Version of Xournal++: 1.1.1.0
 - Installation method: windows installer

**Describe the bug**
Not able to open previously created or saved file. Getting this error message. Please share a fix.

![xournalerror1](https://user-images.githubusercontent.com/39370965/182065103-137afee1-94f0-41cb-bc46-ccf9f87a62b8.PNG)

**To Reproduce**
1. Open the file Diary.xopp (Or any file , it happened to particularly to this file.)
2. Getting the above error message.
3. 

**Expected behavior**
It should open the file as it does for others .xopp files.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
Attaching properties of the file (Diary.xopp)
![xournalerror](https://user-images.githubusercontent.com/39370965/182065520-23e2447a-a6da-4c2c-8768-7b4f771a4de8.PNG)

**Additional context**
Can we open this files content in any other medium. I am not able to open it with any other medium.

Waiting for an resolution to fix this at my side.

Thanks.

**Comment by vladQll** [comment]
try to install version 1.1.1+dev

**Comment by rolandlo** [comment]
@dmohanty640 Please share the `.xopp`-file with (one of) us. It looks like it is corrupted somehow and we could check if it can be fixed.

**Comment by dmohanty640** [comment]
Thanks Roland for your help.
After sharing .xopp file with roland, the file seems corrupted due to some reason.
