### ISSUE TITLE
Application crash if called by different User than the one that installed it.

### ISSUE THREAD

**Issue by TI-Admin** [xournalpp/xournalpp#418]
After cmake install on archlinux to /usr/local done by User XXX, User YYY can't start xournalpp without a crash.

strace reveals that the application is trying to load files like pagetemplates.ini from /home/XXX/xournalpp/ui instead from /usr/local/share/xournalpp/ui and crashes because it can't access /home/XXX/xournalpp/ui

**Comment by andreasb242** [comment]
GladeSearchpath::findFile searches at multiple locations.

XournalMain::initPath set up this files, and this probably should cleaned up, or at least the setup directory needs to be moved first.

**Comment by andreasb242** [comment]
No, move the setup directory at the first location would be a bad idea for all developers, as the new edited files would not be loaded.

**Comment by andreasb242** [comment]
@TI-Admin The Buildpath is now not integrated anymore, so it should be fixed. If not: Reopen the Ticket.
