### ISSUE TITLE
Quick shortcuts via radial menue

### ISSUE THREAD

**Issue by funnym0nk3y** [xournalpp/xournalpp#4184]
**Is your feature request related to a problem? Please describe.**
Changing tools like pen, or color, favorite pen etc. requires the hand to move to one side of the display. It slows down the writig flow. This is better than taking another pen but could be imporoved. 

**Describe the solution you'd like**
Wacom drivers for Lenovo offer a radial menue. It looks like this: 

![Screenshot 2022-08-04 214233](https://user-images.githubusercontent.com/41870754/182939071-2e832d1a-ce22-4284-bc99-03ea9a4d5339.png)

One configures a button on the pen to activate the radial menue which then pops up exactly at the pen position. From there the different buttons can be choosen with the pen. 
I'd like to have a radial menue in xournalpp where I can configure my most needed tools like a specific pen style (color, line, thickness) or any other tool offered by the UI like selection tool and so on.

**Comment by funnym0nk3y** [comment]
I've seen that this is already tackeld with the floating toolbox. Closing this for now.

**Comment by rolandlo** [comment]
Please also check out [this 3rd party plugin](https://github.com/baf57/Xournalpp_FlyPie) based on [FlyPie](https://github.com/Schneegans/Fly-Pie)

**Comment by rolandlo** [comment]
See also [this post](https://github.com/xournalpp/xournalpp/issues/919#issuecomment-1206677921) that features a demo of the FlyPie plugin.

**Comment by funnym0nk3y** [comment]
Unfortunately I can't use FlyPie as I'm on windows but I really like the concept of several hierachies. Probably even better than the current floating toolbox.
