### ISSUE TITLE
ScrollBar for Add Latex Box(Enhancement)

### ISSUE THREAD

**Issue by pasmon79** [xournalpp/xournalpp#4189]
I found this software great for my note taking and research purposes. The latex box is an excellent add on besides handwriting for scientific community.

**The latex box needs a scroll bar handler for code entering area in case we need to enter large amount of tex code.**

**Comment by rolandlo** [comment]
The LaTeX box already has a scrollbar for the code entering area in the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly). It's on the right side of that area (and fades out, if your mouse cursor is away from it for some time). 
You probably have the stable release installed, where this is not available.

**Comment by pasmon79** [comment]
You are correct, Got the nighty build installed. It works great
