### ISSUE TITLE
Canvas sometimes hangs on typing text and moving images/elements

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#42]
Sometimes, especially with larger files, the canvas hangs on dragging objects around or typing text until a stroke is drawn, the window is scrolled in, etc. I suspect this is similar to bug #17 as it might be sporadic due to a lazy gtk_main but certainly there should be a canvas repaint from those actions, which I think is not done.

**Comment by andreasb242** [comment]
Moved to GTK3 - and close because of age
