### ISSUE TITLE
Silent Installation Defaults to "Current User" [Windows]

### ISSUE THREAD

**Issue by CheezWizTN** [xournalpp/xournalpp#4209]
Would it be possible to code the windows installer package so that when the /S command line option is used, the software will install for "All Users"?

I noticed that during a GUI install, "all users" is the only option, so I was hoping that it would install for all users when silently deploying the software. However, it seems to be defaulting to the current user instead.

We have a lot of faculty at our school that love this app and we would like to centrally deploy it to their machines.

**Comment by CheezWizTN** [comment]
Actually, the stand-alone version will do what I need.

**Comment by ljoets** [comment]
I have the same problem.
I tested /ALLUSERS and /ALLUSERS=1 switches but xournalpp is still installed for the current user and I need a system-wide silent installation.
Standalone version does not add files associations and contextual menu, and I need it :-/

**Comment by rolandlo** [comment]
This was fixed in the release branch via  via #5988.
