### ISSUE TITLE
Solution to laggy drawing on Apple Silicon M1

### ISSUE THREAD

**Issue by cevenkadir** [xournalpp/xournalpp#4212]
**Affects versions :**
 - PC: MacBook Air M1 (16 GB RAM, 256 GB SSD)
 - OS: MacOS Monterey 12.5.1
 - libgtk 3.24.33
 - Version of Xournal++: 1.1.11+dev, e76862e6
 - Installation method: Dragging Xournal++.app to Applications folder

**Describe the bug**
When using a touchpad or a Wacom tablet, the drawing experience is laggy if "Disable scrollbar fade out" is disabled. Normally this feature is disabled by default, I guess. I figured out the lag disappears when you enabled this feature. 

**To Reproduce**
1. Go to Edit -> Preferences -> View -> Scrollbars
2. Disable, i.e., untick "Disable scrollbar fade out"
3. Draw something with the pen via a mouse, a touchpad, or a Wacom tablet.

**Additional context**
After finding out the source of this problem, many MacOS users with Apple Silicon can use Xournal++ without a problem except laggy scrolling.

**Comment by rolandlo** [comment]
The latest nightly build uses Gtk `3.24.35`. The lag is fixed there. Please install the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) or wait for the release of version 1.2.0.
