### ISSUE TITLE
Menu bar disappeared

### ISSUE THREAD

**Issue by jgrnst** [xournalpp/xournalpp#4213]
Menu disappeared from xournalpp window. I tried all Fn keys but none of them brought it back. Without the menu, it does not seem to be possible to export files as PDF (at least, I wasn't able to find a keyboard shortcut for that).
The .xml file found in .config/xournalpp shows "menubarVisible" as "true"

**Comment by rolandlo** [comment]
The menubar hiding can be toggled via `F10`, fullscreen mode via `F11`. If nothing helps, you could also try to rename the `settings.xml` file in `.config/xournalpp`, which gets you back to default settings.
Exporting is possible via `Ctrl+E` by the way.

**Comment by jgrnst** [comment]
> The menubar hiding can be toggled via `F10`, fullscreen mode via `F11`. If nothing helps, you could also try to rename the `settings.xml` file in `.config/xournalpp`, which gets you back to default settings. Exporting is possible via `Ctrl+E` by the way.

Thank you. Ctrl-E indeed worked. I tried removing or renaming settings.xml before but it didn't help. When I press F10, nothing happens.

**Comment by jgrnst** [comment]
It turned out to be a KDE - Plasma problem. Somehow a global menu was created and added (I couldn't remember, for the life of me, when and how), which shadowed menus in all apps.
