### ISSUE TITLE
USI Pen, eraser doesnt erase

### ISSUE THREAD

**Issue by Apacelus** [xournalpp/xournalpp#4225]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Pop!_OS 22.04
 - Version of Xournal++: 1.1.1
 - Ubuntu .deb version

**Describe the bug**
When holding down the erase button, the tool switches to erase(as it should) and touching down on the screen the erase rectangle is present, yet it doesnt erase anything.
(Drawing normally does work, binding secondary button to eraser does work too)

**To Reproduce**
1. Hold Eraser button on pen
2. Touch tip of the pen to the screen(Eraser rectangle appears
3. Move pressed down tip across the screen

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.
(Ill do that later)

**Expected behavior**
The erase tool should erase.

**Screenshots of Problem**
N/A

**Additional context**
I have a chromebook with Pop!_OS installed and a USI pen.

**Comment by Xemorr** [comment]
I can also reproduce this on Windows 11, using Version 1.1.1 of Xournal using my One by Wacom tablet.

**Comment by rolandlo** [comment]
Version 1.1.1 is quite old. Please try out the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)

**Comment by Apacelus** [comment]
I dont have that pen anymore and I do not use PopOS anymore. Also, the issue was about USI pens, not Wacom

**Comment by Xemorr** [comment]
I've opened a new issue as I can reproduce it on latest, I imagine these two issues are strongly connected which was why I commented.
