### ISSUE TITLE
cannot save files

### ISSUE THREAD

**Issue by brocolliki** [xournalpp/xournalpp#4233]
**Affects versions :**
 - OS:  Windows
 
 - Which version of libgtk do you use: 3.24.34
     
 - Version of Xournal++: 1.1.1+dev
     

**Describe the bug**
installed the App and can't save my file, therefore cant export as pdf

**To Reproduce**
1. file>save as>
2. choose folder
3. save button turns grey and cannot be used 

**Expected behavior**
to save the file

**Additional context**
if anyone has a fix please tell, i found a related post but it doesnt fix it for me

**Comment by rolandlo** [comment]
> if anyone has a fix please tell, i found a related post but it doesnt fix it for me

Do you mean  #2205? Did you get a dialog with an error message as well?
Also have you tried renaming your `settings.xml` file in your `config` folder (see [file locations](https://xournalpp.github.io/guide/file-locations/)), so that a fresh version of it gets generated?

**Comment by brocolliki** [comment]
thanks for your quick reply

i didnt get that error message , what i get is just a grey save button
![Screenshot_13](https://user-images.githubusercontent.com/113547605/190387693-51280f43-cf41-4d44-a30b-0865a8ec5d1c.png)
i renamed the file you mentioned but it didnt change anythink sadly

**Comment by rolandlo** [comment]
The filename is empty. Maybe all you have to do is to fill in a filename (on the top of the dialog).

**Comment by brocolliki** [comment]
omg..you are right!!!! so many hours lost over this little thing!!!!
thank you thank you

**Comment by rolandlo** [comment]
You're welcome. :smile I'm closing the issue.
