### ISSUE TITLE
Automatically extend the page number if background PDF has been changed to have more pages

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#4247]
**Is your feature request related to a problem? Please describe.**
I am currently writing a script (LaTeX PDF file) and then annotate it in my class. Usually, I add some pages every day, so the number of pages increases gradually. If I open the .xopp annotation file, it only recognizes the pages which have been there on the .xopp file's creation time. so I have to manually append pages and choose the appropriate PDF background page for each page I have added. 

**Describe the solution you'd like**
I'd like Xournal++ to check, if the number of PDF pages has changed in the PDF background file, and if it has been increased, automatically add further pages such that the changes in the PDF file are reflected in Xournal++-

**Describe alternatives you've considered**
Currently I have to add each page manually.

**Additional context**
None that comes to mind.

**Comment by rolandlo** [comment]
Please use menu `Journal > Append new PDF pages` for that purpose. It will add all new pages at once. You may need to reload the document, if it was open while you added the pages in LaTeX.

**Comment by Photon89** [comment]
Nice, didn't know of this option! Thanks for the hint!
