### ISSUE TITLE
Change Latex default text x^2

### ISSUE THREAD

**Issue by mfauvain** [xournalpp/xournalpp#4251]
Hi, is there a way to set the default Latex text different from `x^2`. I have a use case where I would like to insert current date easily and clicking on the Latex button with a default `$\today` would be helpful.

**Comment by rolandlo** [comment]
The formula `x^2` is currently hard coded in `LatexController::showTexEditDialog()` and also in `LatexSettingsPanel::checkDeps()`, so you can only change it by modifying the source code.
