### ISSUE TITLE
Inserted Image cannot be dragged precise in vertical direction

### ISSUE THREAD

**Issue by phytonian** [xournalpp/xournalpp#4275]
**Affects versions :**
 - OS: Ubuntu 22.04
 - (Linux only) Desktop environment: Wayland
 - 3.24.33
 - 1.1.1
 - Snap-store

**Describe the bug**
Facing difficulty in dragging image vertically up or down
Inserted image cannot be dragged to precise location vertically up or down.
If the inserted image is dragged across horizontally or vertically, the background page scrolls too fast.

**To Reproduce**
1. Insert image
2. Drag the image vertically up or down
3. etc.

**Expected behavior**
The image drag should be incremented precisely. Like in Xournal (Lua version : 0.4....) I never faces same issue

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.
![Screenshot from 2022-10-03 14-42-42](https://user-images.githubusercontent.com/12186712/193541889-0e02b40d-efcd-46fb-9da5-b5c438dca415.png)

**Comment by rolandlo** [comment]
Please try modifying the `Selection Edge panning` settings in the `View` panel of menu `Edit > Preferences`
![grafik](https://user-images.githubusercontent.com/40485433/196020211-adf094e7-f9b9-4511-a966-f76b6f592183.png)

**Comment by phytonian** [comment]
Thank you
