### ISSUE TITLE
Synchronization of notes with google drive or outlook using login with google or login with microsoft

### ISSUE THREAD

**Issue by AmritPant** [xournalpp/xournalpp#4284]
**Feature**
I'm always frustrated when I need to check my notes in another system, I find it very painful to copy and paste xournal files into another system. I wish there could be some feature to synchronize my notes in the Cloud. 

**Solution**
As an open source project, It's very hard to store the data of 1000s of users for free and its practically impossible to keep that much data without monetization. Why not user signup with their google drive, or Microsoft outlook account so you don't need to purchase any database or server and the user gets the feature? Even WhatsApp does the same to store messages.

**Comment by hyperupcall** [comment]
You can separately create a Google Drive / OneDrive / Dropbox / Box account, link that up with your computer, and then just store your notes in that software's syncing directory? The way I see it, Xournallpp doesn't have to do anything special here, and we can close the issue, as this project is pretty constrained as it is

Also possibly a dup of #2000

**Comment by AmritPant** [comment]
Hi,

Yes, it is possible, but there is a lot of manual hard work needed which is an entry barrier for a lot of people to use the xournal app. Imagine just clicking the "Login with google" button and every note or journal is now synced with google drive. How magical that would be!.
