### ISSUE TITLE
Windows Installer Crashes When Creating Shortcuts (with System Locale set to Japanese)

### ISSUE THREAD

**Issue by Meloninga54** [xournalpp/xournalpp#4288]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 1.1.1
 - Installation method: Windows zip from Github page

**Describe the bug**
When you try to install Xournal++ using the installer AND ask it to create shortcuts, the installer crashes at the last step where it creates shortcuts.

**To Reproduce**
Download and install the 1.1.1 github release on windows. I installed it to `D:\Programs\Xournal++`

**Additional context**
**I have my system locale set to Japanese.**  This means the that for non-Unicode software, the language is used is Japanese. I believe 
this might be related to the issue as even when I'm inside Xournal, some menu options are in Japanese while others are in English. 

**[How to change system locale to reproduce, if necessary.](https://www.top-password.com/blog/2-ways-to-change-system-locale-in-windows-10/)**

![image](https://user-images.githubusercontent.com/42913997/194016868-c404a1d5-84c7-42f1-844a-a951459c82c8.png)

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/42913997/194014330-01c4fe82-4302-45e4-af0f-0e40a45884e4.png)
![image](https://user-images.githubusercontent.com/42913997/194014704-fefd5fcb-5740-4344-b81f-80acd3a763a9.png)

**Comment by Meloninga54** [comment]
The uninstaller seems to be crashing similarly.
![image](https://user-images.githubusercontent.com/42913997/194019763-43bb4e5c-015b-4728-ace4-e5eac4efe464.png)

**Comment by rolandlo** [comment]
Can you try the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) as well? It might be fixed there.

**Comment by Meloninga54** [comment]
@rolandlo thanks!
The nightly build worked out.

Out of curiosity, any idea what caused this issue?

**Comment by rolandlo** [comment]
@Meloninga54 Please consult https://github.com/xournalpp/xournalpp/issues/4041 and https://github.com/xournalpp/xournalpp/issues/4062 about that issue.
