### ISSUE TITLE
Unable to save files to gfvs smb share

### ISSUE THREAD

**Issue by 4ndyZ** [xournalpp/xournalpp#4289]
**Affects versions :**
 - OS: Fedora 37
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.1
 - Installation method: Fedora 37 repository

**Describe the bug**
When trying to save a file to a SMB share mounted with gfvs the app crashes. Saving files to /home or other places works fine.

**To Reproduce**
1. Mount SMB network file share using Gnome Files App (mounts shares via gvfs)
2. Open Xournal++
3. Try to save file under SMB network file share
4. App crashes

**Expected behavior**

**Screenshots of Problem**
```bash
** Message: 11:28:10.475: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
** Message: 11:28:10.983: Plugin "MigrateFontSizes" UI initialized
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: Keine Berechtigung [/run/user/1000/gvfs/smb-share:server=nas.server,share=dateien/2022-10-05-Notiz-11-28.xopp]

** (xournalpp:18215): WARNING **: 11:28:20.010: [Crash Handler] Crashed with signal 6

** (xournalpp:18215): WARNING **: 11:28:20.011: [Crash Handler] Wrote crash log to: /home/andyz/.cache/xournalpp/errorlogs/errorlog.20221005-112820.log

** (xournalpp:18215): WARNING **: 11:28:20.585: Versuche eine Notfall-Speicherung des aktuell geöffneten Dokuments…

** (xournalpp:18215): WARNING **: 11:28:20.586: Dokument erfolgreich nach "/home/andyz/.config/xournalpp/emergencysave.xopp" gespeichert.
```

**Additional context**
Saving files to a SSH gfvs mounted file share works fine, only SMB seams to be affected.

**Comment by rolandlo** [comment]
The error message says `
  what():  filesystem error: status: Keine Berechtigung [/run/user/1000/gvfs/smb-share:server=nas.server,share=dateien/2022-10-05-Notiz-11-28.xopp]` Is there something you can change about that?

**Comment by 4ndyZ** [comment]
Xournal++ opens the file without problems on my other PC running Fedora 36 with the same SMB user and mountpoint.

I guess it might be a change or bug in the upstream gvfs implementation of Fedora 37.

I will try to dig deeper into this problem this weekend and report back.

**Comment by 4ndyZ** [comment]
Upstream bug in Fedora 37 (Samba and gvfs).

See:
https://gitlab.gnome.org/GNOME/gvfs/-/issues/651
https://bugzilla.redhat.com/show_bug.cgi?id=2127301
https://bugzilla.samba.org/show_bug.cgi?id=15195
