### ISSUE TITLE
中文输入问题

### ISSUE THREAD

**Issue by KangJieyu** [xournalpp/xournalpp#4290]
Mac版Xournal++在输入法为中文的条件下无法输入中文信息
- 操作系统：Mac
- Xournal++版本：1.1.1

**Comment by rolandlo** [comment]
Google translate says that the bug report is about a problem with input of Chinese characters.

**Comment by KangJieyu** [comment]
> Google translate says that the bug report is about a p

**Comment by KangJieyu** [comment]
> Google translate says that the bug report is about a p

所以我需要改应用程序的编码吗

**Comment by KangJieyu** [comment]
> Google translate says that the bug report is about a problem with input of Chinese characters.
 @rolandlo hello!So,我应该如何解决这个问题！

**Comment by rolandlo** [comment]
@KangJieyu I don't know, I have no experience with input of Chinese characters. Maybe @tattsan has some advice (although Japanese and Chinese are different and MacOS and Linux are different as well).

**Comment by KangJieyu** [comment]
@rolandlo 哦，好的！感谢您的回答和建议！

**Comment by KangJieyu** [comment]
@tattsan Can you give me some advice?? Thank you!

**Comment by tattsan** [comment]
Sorry, I have no experience with MacOS nor Windows, and the issue is OS dependent.

**Comment by KangJieyu** [comment]
> Sorry, I have no experience with MacOS nor Windows, and the issue is OS dependent.

@tattsan 好的！感谢您的回应。我在问问其他人。

**Comment by tattsan** [comment]
There is one OS-independent thing. The PDF library `poppler` requires `poppler-data` to display CJK characters.
This is about display, not about input, but it is a prerequisite for usual input process.

**Comment by rolandlo** [comment]
In any case, please upgrade to version 1.1.2 and check if the issue is fixed there.

**Comment by KangJieyu** [comment]
> 
可惜我不懂这个

**Comment by KangJieyu** [comment]
> If you can paste CJK chars from another application, this may be related to #4291.

可惜我不懂这个东西。

**Comment by KangJieyu** [comment]
> In any case, please upgrade to version 1.1.2 and check if the issue is fixed there.

好的，我先将这个软件升级。

**Comment by KangJieyu** [comment]
@tattsan @rolandlo 在最新版本 1.1.2 中已经解决了这个问题，感谢你们的帮助。

**Comment by rolandlo** [comment]
@KangJieyu Great that it works in version 1.1.2. I will close the issue.
