### ISSUE TITLE
Technical Documentation Improvements?

### ISSUE THREAD

**Issue by hyperupcall** [xournalpp/xournalpp#4295]
**Is your feature request related to a problem? Please describe.**

I was recently attempting to build and run the tests, and that experience led me to a few thoughts that could improve our documentation:

1. There seems to be a lot of duplication between the `{Linux,Windows,Mac}Build.md` files, such as the clone / building. This makes it a bit harder to manage it, and less intuitive (for example, if building on Windows, one would have to look into `LinuxBuild.md` to figure out how to run tests)
    - A solution may be to have a `Build.md` file, and link there with common steps from each of the platform-specific files
    
2. I think shared titles could make navigation a bit easier. For example, instead of "Compiling" and "Build xournal++" steps, make them both "Compiling" or something similar.

3. Maybe move the "Branching Strategy" section from `Releases.md` to `CONTRIBUTING.md`? I didn't know abuot the branching procedures until looking at `Releases.md`, which most people probably don't read

4. Styling is also a bit inconsistent - maybe it would be good to add a markdown linter like `markdownlint`, and add that to CI so everything is more readable at the source level?

Thoughts on this? For me, documentation is one of the most important aspects of a project, and doing this can make it much easier for people to contribute (myself included :laughing:). If others are onboard I'd definitely be willing to create a PR to address these things :)

**Comment by Technius** [comment]
I changed the title of this issue to clarify that it is about the technical documentation. The [documentation site](https://github.com/xournalpp/xournalpp.github.io) is another problem...

> There seems to be a lot of duplication between the `{Linux,Windows,Mac}Build.md` files, such as the clone / building

I agree that there is duplication that can be refactored out, but the focus is on setting up the environment and creating the distribution files, which is the hardest part. The Linux setup is _very_ easy compared to the others but depends on distro; Windows requires MSYS and a couple of hacky setup scripts; and Mac is so complicated to get working that I can't even reproduce the build on my own machine. Furthermore, the packaging steps are different for each platform/redistributable.

That being said, it would be helpful to pull out information like how to run CMake, what settings to provide to CMake, how to run tests, etc.; and put them into a file such as `Compile.md` or something. Not sure where we would put platform-specific settings like disabling X11, however.

> Maybe move the "Branching Strategy" section from `Releases.md` to `CONTRIBUTING.md`?

The maintenance team doesn't expect contributors to understand the branching strategy, because we will take of the details. But I agree in that we should at least incorporate a link to the `Releases.md` document.

> Styling is also a bit inconsistent - maybe it would be good to add a markdown linter like `markdownlint`, and add that to CI so everything is more readable at the source level?

I don't find syntactic linters, esp. for a markup language like markdown, to be very helpful because they raise too many false positives and still require manual effort to make the changes. It would be better to use an opinionated automatic markdown formatting tool (something like `mdformat`? -- disclaimer, I've never tried it).

**Comment by hyperupcall** [comment]
> Furthermore, the packaging steps are different for each platform/redistributable.

Yeah, I would still keep the packaging part separate

> That being said, it would be helpful to pull out information like how to run CMake, what settings to provide to CMake, how to run tests, etc.; and put them into a file such as Compile.md or something. Not sure where we would put platform-specific settings like disabling X11, however.

Yeah, I feel some sort of `Compile.md` would be helpful. If there is something platform-speciifc maybe we can have the section in the platform-specific file, and link to the relevant part in Compile.md along with mentioning the platform-specific part

> The maintenance team doesn't expect contributors to understand the branching strategy, because we will take of the details. But I agree in that we should at least incorporate a link to the Releases.md document.

:+1: 

 > I don't find syntactic linters, esp. for a markup language like markdown, to be very helpful because they raise too many false positives and still require manual effort to make the changes. It would be better to use an opinionated automatic markdown formatting tool (something like mdformat? -- disclaimer, I've never tried it).

Hm yeah, yeah a formatter is good too - I'd recommend [Prettier](https://prettier.io/) for that, it's pretty battle tested and I use it all the time. It also supports YAML files as well. What do you think if I add a Prettier config and format the files with Prettier in a separate PR?

**Comment by Technius** [comment]
> > That being said, it would be helpful to pull out information like how to run CMake, what settings to provide to CMake, how to run tests, etc.; and put them into a file such as Compile.md or something. Not sure where we would put platform-specific settings like disabling X11, however.
> 
> Yeah, I feel some sort of `Compile.md` would be helpful. If there is something platform-speciifc maybe we can have the section in the platform-specific file, and link to the relevant part in Compile.md along with mentioning the platform-specific part

Sounds good.

> > I don't find syntactic linters, esp. for a markup language like markdown, to be very helpful because they raise too many false positives and still require manual effort to make the changes. It would be better to use an opinionated automatic markdown formatting tool (something like mdformat? -- disclaimer, I've never tried it).
> 
> Hm yeah, yeah a formatter is good too - I'd recommend [Prettier](https://prettier.io/) for that, it's pretty battle tested and I use it all the time. It also supports YAML files as well. What do you think if I add a Prettier config and format the files with Prettier in a separate PR?

That would be nice, but we should be wary of bugs that would make automatic formatting more annoying than helpful. For example, it seems like Prettier has some major bugs with its markdown formatter (e.g., the following issue would be a show-stopper for some of our docs: https://github.com/prettier/prettier/issues/13188). Other formatters probably also similar major bugs.

> > The [documentation site](https://github.com/xournalpp/xournalpp.github.io) is another problem
> 
> Is it just like, sorta out of date?

The application was just not really well documented to begin with. I think most users here have typically resorted to sifting through the issue tracker or the source code to learn how to use the application.

We now have a website (linked above) with an installation guide and a user guide, but it is still rather incomplete. Contributions there would be very helpful!

**Comment by hyperupcall** [comment]
> That would be nice, but we should be wary of bugs that would make automatic formatting more annoying than helpful. For example, it seems like Prettier has some major bugs with its markdown formatter (e.g., the following issue would be a show-stopper for some of our docs: https://github.com/prettier/prettier/issues/13188). Other formatters probably also have similar major bugs.

I personally haven't run into any of those major bugs and I would still strongly wish to use Prettier in spite of that - but ah, if there isn't much support for it, then I guess it's kind of a moot issue and it would be pointless to try to add it. I didn't mention this before, but I think an [EditorConfig](https://editorconfig.org) is a good bare minimum for cross-editor formatting compatibility. It doesn't do mass-reformatting and allows new collaborators to get on board without any editor tweaking.

> The application was just not really well documented to begin with. I think most users here have typically resorted to sifting through the issue tracker or the source code to learn how to use the application.
> We now have a website (linked above) with an installation guide and a user guide, but it is still rather incomplete. Contributions there would be very helpful!

Ah, I understand now, thank you :+1:
