### ISSUE TITLE
Tool Toggle ability

### ISSUE THREAD

**Issue by SunkenHero** [xournalpp/xournalpp#4310]
So i am going to get a new stylus for my tablet, which got a button on the back of the Pen.
I want to use this button too toggle between Pen and Highlighter

A Checkbox next to a button assignment that creates a second assignment box, so you can choose two tools to toggle between and an option that toggles back to the previous tool used. Like if you press the button you change from pen to highlighter and if you press again you toggle back to the pen

**Additional context**

**Comment by tattsan** [comment]
If you could find or bind  some key sequence to the pen buttons, you could write a plugin like this:
```
-- Register all Toolbar actions and intialize all UI stuff
function initUi()
  app.registerUi({["menu"] = "Toggle Pen and Highlighter", ["callback"] = "togglePenOrHighlighter", ["accelerator"] = "<Super>F20"});
end

-- Toggle Pen state and Highlighter state.
local PenOrHighlighter = 0
function togglePenOrHighlighter()
  if (PenOrHighlighter == 0) then
    PenOrHighlighter = 1
    app.uiAction({["action"]="ACTION_TOOL_HIGHLIGHTER"})
  else
    PenOrHighlighter = 0
    app.uiAction({["action"]="ACTION_TOOL_PEN"})
  end
end
```
Here `"<Super>F20"` is the sequence which my lenovo stylus emits with a single click of the top button.
To make your own plugins, please see:
https://xournalpp.github.io/guide/plugins/plugins/

**Comment by SunkenHero** [comment]
How did you find the sequence out you pencil emits

**Comment by tattsan** [comment]
I used `xev` command (X11 application) on Linux.
