### ISSUE TITLE
Mac电脑中文输入

### ISSUE THREAD

**Issue by KangJieyu** [xournalpp/xournalpp#4321]
**Affects versions :**
 - OS: MacOS
 - Version of Xournal++ : 1.0.10

**Describe the bug**
在中文输入法下，在xournalAPP中输入中文时只能输入拼音，并不能输入汉字。

**Comment by chenzhiy2001** [comment]
这个问题应该已经被修复了。试试1.1.2

**Comment by tattsan** [comment]
Duplicate of #4290. Let's discuss at #4290, and close #4321 please.
