### ISSUE TITLE
[Feature] Upgrade to GTK4 / libadwaita

### ISSUE THREAD

**Issue by martinszeltins** [xournalpp/xournalpp#4339]
**Describe the solution you'd like**

Since most GNOME apps are now moving to GTK4 / libadwaita, it would be nice to port Xournal++ also to it for a more modern experience and to bettter integrate with GNOME.

**Comment by rolandlo** [comment]
That's definitely something we plan to do. See  #2722. We have also made some preparatory steps https://github.com/xournalpp/xournalpp/pull/3306 for the GTK3->GTK4 porting. Still a lot of work needs to be done and we need to learn more about GTK4/libadwaita. @martinszeltins In case you want to help, we would be happy to accept.

**Comment by bhennion** [comment]
Closing as a duplicate to #2722

**Comment by rolandlo** [comment]
See #4561 for a discussion of the redesign with Gtk 4 / libadwaita.
