### ISSUE TITLE
synchronize layers of different pages

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#4355]
**Is your feature request related to a problem?**
I use xournalpp in teaching to be able to make handwriting notes on my presentation slides. As I create these presentations with LaTeX where "animations" result in multiple pdf pages, it would be nice to be able to keep annotations from one slide to another (especially if the change is just adding something new (portion of an image, a new bulletpoint etc.)).

**Describe the solution you'd like**
As a first step it would be nice to be able to somehow mark two layers of the different pdf pages (in my use case: same slide, just another step of the animation) resulting in these layers being synchronized. Meaning everything written/drawn on one of them immediately gets written/drawn on the other one as well (not quite familiar with the architecture of xournalpp, but maybe we can simply use the same layer for multiple pages, downside is how we're gonna reflect this in the fileformat, workaround would possibly be that on save the link is removed and the layer is copied to all pages, downside of this: one would need to create that link after every save/open once again).

**Describe alternatives you've considered**
Currently in most cases I just copy the annotations manually or redraw them (if it's not that time-consuming), but that's not such a nice workflow.

**Additional context**
I already thought of solving this via a plugin, but if it's possible to share the same layer between multiple pages, I think that's just much more clean (no pulling/pushing changes needed that way).

**Comment by rolandlo** [comment]
Have you tried the `LayerActions` plugin to help you a bit (copy all non-background layers to the next page)?

**Comment by atticus-sullivan** [comment]
Oh that's a nice workaround which suffices for my use case (in a presentation usually one goes from first to last page so manually pushing the annotations down should be possible). Maybe with the WIP `getStrokes` and the present `addStrokes` we can further improve / make a new plugin which is able to append layers to the next page (therefore not overwriting the next page).

Somehow I still like the idea of syncing layers (and thereby eliminating the need of manually pushing annotations), but tbh I've got no real use case (and since I can already imagine this could lead to many problems, let's wait until someone really has a usecase for it)
