### ISSUE TITLE
Pages appear in reverse order in the main view window

### ISSUE THREAD

**Issue by MrPancakes39** [xournalpp/xournalpp#4364]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.2
 - Installation method: Official release

**Describe the bug**
Pages appear in reverse order (3 2 1) in the main view window.
The Sidebar displays them correctly (1 2 3) and so exporting as PDF.

**To Reproduce**
1. Step 1: Create a Document and Add Pages.
2. Step 2: Done.

**Expected behavior**
Pages appear in correct order in the main view window.

**Comment by rolandlo** [comment]
What are your settings in menu `View > Layout`?

**Comment by MrPancakes39** [comment]
> What are your settings in menu `View > Layout`?

That was it 😅
Sorry for wasting your time and Thank you! ❤️
