### ISSUE TITLE
Cannot delete selected items if the hand tool is active

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#4367]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Gnome 42.5, Wayland
 - Which version of libgtk do you use 3.24.34
 - Version of Xournal++: 1.1.2
 - Installation method: flatpak

**Describe the bug**
if you select an item, you are unable to delete the selected item if the hand tool is active.

**To Reproduce**
1. Create an item (text etc)
2. select it (eg with the lasso select tool)
3. select the hand tool, and observe that you cannot delete it

**Expected behavior**
I'm not sure if this is intended behaviour, or not. I initially expected that I would be able to click the x, but I could understand an argument for why that would be undesirable

**Screenshots of Problem**
![test2](https://user-images.githubusercontent.com/7829231/197945028-952bb629-3723-4f79-8859-04d2c8e41593.gif)

**Comment by RuleOfThrees** [comment]
Hello! I'd like to take a look at this one.

**Comment by Jared234** [comment]
I agree with @forgottosave that the "delete" button shouldn't be shown when the hand tool is selected. I am interested in working on this issue and can create a PR request soon.

**Comment by mjg** [comment]
Apparantly, the hand tool is the only tool which does not de-select an existing selection when it is activated. Changing that would be the more uniform solution than the one from #4419 . Otherwise, expect users to ask why the anchors disappear ...

**Comment by Technius** [comment]
We "fixed" this issue by hiding the selection controls when using the hand tool (#4419).
