### ISSUE TITLE
Ubuntu 22.04 doesn't support libzip5 in apt

### ISSUE THREAD

**Issue by lamyergeier** [xournalpp/xournalpp#4369]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows] Ubuntu 22.04.1
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11] Wayland
 - Which version of libgtk do you use (xournal is not starting)
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch] 1.1.2
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.] deb file from github

**Describe the bug**

```
$ xournalpp
xournalpp: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
```
Ubuntu 22.04 does not support libzip5 but libzip4

Refer: 
- [[Ubuntu – Package Search Results -- libzip5](https://packages.ubuntu.com/search?keywords=libzip5)](https://packages.ubuntu.com/search?keywords=libzip5)
- [[Ubuntu – Details of package libzip-dev in jammy](https://packages.ubuntu.com/jammy/libzip-dev)](https://packages.ubuntu.com/jammy/libzip-dev)

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**

```bash
$ sudo apt install libzip4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libzip4 is already the newest version (1.7.3-1ubuntu2).
libzip4 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt install libzip-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libzip-dev is already the newest version (1.7.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt install libzip5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libzip5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libzip5' has no installation candidate
```

**Comment by rolandlo** [comment]
The packages on the releases page of the Github repo for Linux are for Bionic Beaver (18.04) and Focal Fossa (20.04). The AppImage provided there works on more recent Ubuntu version as well. If you want to use a `.deb`-package for Jammy Jellyfish (22.04) you should use the one from the PPA, either [stable version](https://launchpad.net/~apandada1/+archive/ubuntu/xournalpp-stable) or [nightly release](https://code.launchpad.net/~andreasbutti/+recipe/xournalpp-daily). See also [website](https://xournalpp.github.io/installation/linux/).

Note to @xournalpp/core : We should include a .deb package for Ubuntu Jammy Jellyfish (22.04) next time. 
Also update the website (v1.1.2 is the latest stable version)

**Comment by lamyergeier** [comment]
@rolandlo  Those are unofficial PPA. I would prefer to install from Github deb file.

**Comment by rolandlo** [comment]
@lamyergeier Please upgrade to version 1.1.3. We have included a .deb package for Jammy Jellyfish this time.
