### ISSUE TITLE
Plugins not working when using AppImage

### ISSUE THREAD

**Issue by AlanVoore** [xournalpp/xournalpp#4389]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 18.04
 - libgtk version 3.22.30
 - Version of Xournal++: 1.1.2
 - Installation method: Using Appimage

**Describe the bug**
I am trying to use plugins to customize shortcuts but placing the `myplugin.ini` and `mymain.lua` file inside the directory `/home/username/.config/xournalpp/plugins` does not work. I am using AppImage and there is no directory called `usr/share/xournalpp` since I have not actually installed the app as I am using an AppImage.

But i noticed that under the menu there is `Plugin > Plugin Manager` which list the available plugins. And when I select and click on `enable` on any of them, they start working(after closing and reopening the app). This leads me to the conclusion that these available plugins must be stored somewhere from which we're using them.

So I want to know where are these plugins stored so that I can also store my custom plugins there and use them with the appimage. Should I manually create the directory `/usr/share/xournalpp/plugins` and then paste my custom plugins there or something else. 

**Expected behavior**

Custom plugin should work with appimage.

**Comment by rolandlo** [comment]
Either 
```
sudo apt install gcc-10 g++-10
```
like we do when building the AppImage or use the stable version 1.1.2 as you did before (and follow the steps above). Or does that version not work either?

**Comment by rolandlo** [comment]
See the post above:
> Either
> 
> ```
> sudo apt install gcc-10 g++-10
> ```
> 
> like we do when building the AppImage or use the stable version 1.1.2 as you did before (and follow the steps above). Or does that version not work either?

**Comment by rolandlo** [comment]
First of all, custom plugins are not yet available in version 1.1.2 ( #2422 was merged into `master`, not into `release-1.1`). So storing plugins in the `.config`-folder does not help. I would recommend to use the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) instead.

If you want to stick with the stable version 1.1.2:
The AppImage contains the plugins. You can inspect the AppImage either by obtaining the mount-point via the `appimage-mount` option like 
```term
./xournalpp-1.1.2-x86_64.AppImage --appimage-mount
```
(something like ` /tmp/.mount_xournaKTxNc1`). You can inspect that folder in the terminal.

Alternatively you can extract the AppImage via the `appimage-extract` option like
```term
./xournalpp-1.1.2-x86_64.AppImage --appimage-extract
```
That creates a `squashfs-root` directory with all contents of the Appimage. It can be examined and modified.
If you want to add a custom plugin to the 1.1.2 AppImage, just add the plugin to the extracted `squashfs-root/usr/share/xournalpp/plugins` folder. Then you can repack it again with the [`appimagetool`](https://github.com/AppImage/AppImageKit#appimagetool-usage) ([download link](https://github.com/AppImage/AppImageKit/releases)), like
```term
./appimagetool-x86_64.AppImage squashfs-root/
```
or run the extracted AppImage by executing `squashfs-root/.AppRun`.

**Comment by AlanVoore** [comment]
@rolandlo Unfortunately when I try to use the nightly build I get the error saying:

```
/tmp/.mount_xourna5wpttR/AppRun.wrapped: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_xourna5wpttR/AppRun.wrapped)
```

I think the reason for this error is that I am using gcc 7.5 but the nightly build you suggested requires at least gcc 8. Can you suggest an old nightly build(or stable version if the old nightly build is not available) which can work with gcc 7.5. 

Thanks, again.

**Comment by AlanVoore** [comment]
@rolandlo I applied your suggested method of first extracting the appimage and then modifying as you explained and it works. Thank you.

**Comment by AlanVoore** [comment]
@rolandlo Can you tell me how can I find the list of all the actions that can used. For example, there is `TOOL_DRAW_RECT`, `TOOL_DRAW_CIRCLE`, `ERASER` and so on. Is there a documentation page where all of this is listed.
