### ISSUE TITLE
Double Arrow is not recognised

### ISSUE THREAD

**Issue by AlanVoore** [xournalpp/xournalpp#4391]
**Affects versions :**
 - OS: Ubuntu 18.04
 - X11
 - libgtk 3.22.30
 - Xournal 1.1.2
 - Appimage

**Describe the bug**

When I try to use the action `ACTION_TOOL_DRAW_DOUBLE_ARROW` for shortcut, it gives the error saying:

```
** (AppRun.wrapped:17833): WARNING **: 16:37:08.502: Invalid enum value for ActionType: "ACTION_TOOL_DRAW_DOUBLE_ARROW"
ACTION_TOOL_DRAW_DOUBLE_ARROW
```
And the double arrow is not drawn on the screen. 

I have the following in `main.lua`
```
function myarrow()
  app.uiAction({["action"] = "ACTION_TOOL_DRAW_DOUBLE_ARROW"})
  print("ACTION_TOOL_DRAW_DOUBLE_ARROW")
end
```

**To Reproduce**
Step 1. Place the following in your main.lua file
```
function chooseDArr()
  app.uiAction({["action"] = "ACTION_TOOL_DRAW_DOUBLE_ARROW"})
  print("ACTION_TOOL_DRAW_DOUBLE_ARROW")
end
```
then use this as callback.
Step 2. Then restart the app and use the shortcut key which you set for that callback.
Step 3. You'll get a warning when you use the shortcut:
```
** (AppRun.wrapped:17833): WARNING **: 16:37:08.502: Invalid enum value for ActionType: "ACTION_TOOL_DRAW_DOUBLE_ARROW"
ACTION_TOOL_DRAW_DOUBLE_ARROW
```
and no double arrow will be drawn on the screen.

**Expected behavior**

Double arrow should be drawn just like any other shape. 

Below is the screenshot showing the same.
![Screenshot](https://user-images.githubusercontent.com/115527008/200167487-452222f9-89f9-4224-a73e-bd36a2b6c761.png)

**Comment by rolandlo** [comment]
The double arrow was only introduced in #3946 (as a new feature merged into `master`, not into `release-1.1`) and is not part of Xournal++ version 1.1.2.
