### ISSUE TITLE
Allow any obect to be selected just by clicking on it without having to switch to "select object" shortcut

### ISSUE THREAD

**Issue by AlanVoore** [xournalpp/xournalpp#4393]
I am using Xournalpp and I noticed that to select any object, the user have to first choose the "Select Object" option from the `Tools` menu(or using `Shift + Ctrl + O`). But this is very inconvenient as every time I create an object and want to select that object I've to first repeat the same process. 

Also this is time consuming and very unproductive as well as boring. This should be the default behavior so that user don't have to manually choose that "Select Object" option again and again. Almost all other apps have this feature by default so I think this should be the default here as well.

I mean when the user clicks on any of the object, they should by default, be able to select that object and move it around. This will make the app much more productive.

**Comment by rolandlo** [comment]
You could assign the "Select Rectangle" tool to one of your stylus buttons. Then you only need to press the button and hit the object and don't need to change tools.

**Comment by AlanVoore** [comment]
@rolandlo That is a possible workaround but I want that the user should not have to think about having to move back and forth between the options. The less the user have to think the better the app gets. In other words, the less choices the user have to make for such simpler and *trivial* tasks the better will be the flow. Having to manually choose the option again and again breaks(disrupts) user's flow and becomes unproductive. 


I really think this is a much needed feature as every other notetaking app(afaik) has this feature and also the user also already expects that the object that they create on the canvas are selectable by default.

**Comment by rolandlo** [comment]
Unless I'm mistaken neither OneNote (Web App), Notability, Openboard, Xournal, Stylus Labs Write nor RNote have this feature. What notetaking apps are you talking about?

In general I agree with the idea that the less the user has to think and move back and forth, the better. I also think that Xournal++ has the potential to improve quite a bit in that regard.
It is however not clear how the app should decide whether a new stroke should be started or an object nearby should be selected when you don't switch the tool. Moreover the suggested behavior has a performance cost. That can all be discussed, but it's probably not that easy to come up with a completely satisfactory solution.

**Comment by Malex14** [comment]
@AlanVoore I think the function you are proposing already exists. You can enable "Action on Tool Tap" in the drawing area settings. When you tick the "Try to select object first" checkbox, objects are selected if you shortly tap on them.

**Comment by rolandlo** [comment]
Closing in view of the existing "Action on Tool Tap". Thanks @Malex14 for pointing that out.
