### ISSUE TITLE
[lua Api] sidebarActions not reliably working

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#4394]
**Affects versions :**
 - OS: Ach Linux
 - (Linux only) Desktop environment: X11 with bspwm
 - Which version of libgtk do you use: libgtk: 3.24.34
 - Version of Xournal++: 1.1.2
 - Installation method: arch linux repo

**Describe the bug**
I'm testing the `clone`-function of the provided `LayerActions` plugin. The trouble I've got is that sometimes simply the current page is deleted while the annotations go to the next page.
I already had a look at the code and I'm pretty sure the problem is that `app.sidebarAction("COPY")` isn't executed.

In my tests this problem didn't occur on documents without a table of contents (sections, ... in LaTeX). After some more testing I figured out that if I manually open the sidebar and select the `page preview` "tab" is still works.
My conclusion is that the correctness of `app.sidebarAction` depends on the "tab" which is selected in the sidebar (`content`s seems to be selected by default if available -> not working, if not available `page preview` is selected -> working).

*Not working example*
![Peek 2022-11-06 20-44](https://user-images.githubusercontent.com/60581958/200192348-e900def7-dffd-4629-b96b-882c3cd0e6ed.gif)
Here I just opened the pdf, draw some stuff and applied the plugin function. Note that in the first line of the slide there is `1` and `A` indicating that (sub)sections are being used.

*Working example*
![Peek 2022-11-06 20-45](https://user-images.githubusercontent.com/60581958/200192390-099284dc-010b-4c87-aa6a-155833b16eeb.gif)
Here I only opened the sidebar and selected `page preview` before applying the plugin function.

**possible fix**
I'm not sure how the sidebar works (not into gui stuff yet) and if it's possible to call sidebar actions from another sidebar tab, but maybe a (bit dirty, since we might interfere a bit with the user) workaround could be exposing the sidebar tab to the lua api so that the plugin can switch the right tab and then switch back just before calling the sidebar action.

**Comment by rolandlo** [comment]
I think `Sidebar::setSelectedPage(size_t page)` can be used for that.
`page = 0`: sidebar index page
`page = 1`: pages previews
`page = 2` : layer previews (not stacked)
`page = 3 `: layer previews (stacked)
See `Sidebar::initPages`. 
We need page 1. Not sure how to switch back though (how to know on which page we are). Maybe a little refactoring of the Sidebar class (in particular `Sidebar::setSelectedPage`) is needed (so that one could add a function `getCurrentSidebarPageNo()` without duplicating code).

**Comment by atticus-sullivan** [comment]
Hm, right now we'd need to cycle over the `this->pages` list to find out, which page is the `this->currentPage` (btw, this actually should be possible using an iterator and just increment it by the searched index).

To avoid cycling, we could simply store the currently active index along with the `this->currentPage` pointer (as we don't expose the `this->pages` list directly to the ouside (just `push_back`), the index shouldn't change unexpectedly due to an insert other than at the end).

As part of a bigger refactoring we also might switch from `std::list` to `std::vector`. (And use indices instead of pointers. *Hm using pointers is most probably better anyhow to avoid going to the vector/array with the index over and over again.*) This way we would get constant time for searching a specific page (no cycling over the list or so). *Hm, at least in `Sidebar::setSelectedPage` there is no huge benefit from this, as we need to disable the other pages anyhow (EDIT: actually if we know which one was active before, it should suffice to disable that one (at least it sounds logically))*

Sorry if this is a bit unstructured, I just wrote this while reading/thinking about the code.

Is this what you imagined when you thought of some refactoring, or did you have something else in mind?

**Comment by atticus-sullivan** [comment]
Well I thought about this again:
- *using an iterator for `currentPage`*
  \+ can be used the same like pointers (current implementation)
  \+ `std::distance` to find out the index of the current page
  \- gets invalidated if we append to the list. And this is a big disadvantage!
- *store an index along with the pointer*
  \+ almost no additional overhead
  \+ fast to get the index
  \- needs to be synchronized with the `currentPage` pointer
- *use `std::vector`* for `pages`
  \+ random access
  \+ using index instead of the pointer possible since we only `push_back` to `pages`. Disadvantage of using the index of course is that we always first need to get the `page` we want to work with from the vector.
  \- might need to copy when expanding (but as usually 4 pages are present, we might as well preallocate 4 slots when constructing the sidebar)

Currently, I'd suggest doing both, switch to `std::vector` and use the iterator for `currentPage`. This way, we'll have a way of getting the index of the current page pretty fast (`std::distance` on a random access iterator). The interface for `currentPage` stays the same.
Only thing we need to be careful of is iterator invalidation. But we can circumvent this by get the current index, then do the `push_back` and afterwards get a new iterator with `pages.begin() + captured_idx`.

What do you think?

Of course if you plan to implement adding pages somewhere else than at the end (`push_back`), my approach is not so nice because of the vector. But this design decision is your (the maintainers) call. (I don't know what you plan for the sidebarpages)

**Comment by rolandlo** [comment]
Currently we have a fixed number (only 4) pages (which are constructed at the application startup), so I don't think we need to worry about performance or about appending pages to the list. There are no plans to add more pages.
I think using a `std::vector` and using an iterator is a good choice. So please go ahead with it.

**Comment by bhennion** [comment]
I think this is a bit dangerous. I'm confident this will work right now, but I'm scared about maintainability. This could lead to nasty bugs if someone someday tries to add another "Page".

IMO, in this case, we can either use an std::array, an std::vector (and remember the index), or an std::vector<std::unique_ptr> (and remember a pointer).

**Comment by atticus-sullivan** [comment]
> This could lead to nasty bugs if someone someday tries to add another "Page".

I see the problem of iterator invalidation as well. Nonetheless I think `pages` is a private member of the sidebar so it should be doable to constrain accesses/modifications. If such a modification should be needed we can still calculate the index (something like `std::distance(pages.begin(), currentPage)`, do the modification and then restore the iterator (`pages.begin() + temp_index`).
Thus, I think we can handle this problem of iterator invalidation (of course we need to document this in the comments for the `pages` member)
