### ISSUE TITLE
Be able to change default annotation colors

### ISSUE THREAD

**Issue by forgottosave** [xournalpp/xournalpp#4396]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I want to use different colors to annotate, that are not the xournalpp predefined colors.
The current approach with only one custom color in the top bar makes it unnecessarily hard to switch between previously used colors.

**Describe the solution you'd like**
Being able to change the default colors in the settings would offer a simple way to work with multiple custom colors.
It would be great to be able to permanently store those new default colors. 

**Describe alternatives you've considered**
I thought of 2 alternatives, although I think changing the standard colors in the settings as described above would be the best way.
1. An alternative would be to add a small arrow under each predefined color, to be able to change the color of that slot.
This could look something like this:
![image](https://user-images.githubusercontent.com/88790311/200624500-0a421c4e-5b8b-4a97-b418-c08c7a94b58f.png)

2. The second alternative would be to show previously used colors in the top bar (not only one slot)

**Comment by rolandlo** [comment]
I'm closing the issue, since the feature is already there.
