### ISSUE TITLE
Make LaTex dependencies optional

### ISSUE THREAD

**Issue by MatsG23** [xournalpp/xournalpp#4398]
I had to install like >100 dependencies all starting with the prefix "texlive-". I am not using LaTex at all in Xournal++.
I propose that you make installing the dependencies optional (do not require them at the installation, just say that they are needed to use LaTex in the settings).

I am using the xournalpp package provided by the openSUSE Repo.

**Comment by Indomitable** [comment]
Similar story here, just when I saw all Perl and texlive dependencies uninstalled the xournalpp and installed it using flatpak.

**Comment by rolandlo** [comment]
You should probably complain at the OpenSUSE `xournalpp` Repo. Here we don't require any `texlive` (or other `TeX`-related) installation. This [xournalpp.spec](https://build.opensuse.org/package/view_file/openSUSE:Factory/xournalpp/xournalpp.spec?expand=1) from OpenSUSE does however.

**Comment by SafwanElmadani** [comment]
Same with fedora.

**Comment by SafwanElmadani** [comment]
> > Same with fedora.
> 
> If the Fedora repository uses the package file given in the repo, LaTeX is optional. You can choose not to install the recommended (not necessarily needed) packages. See: L.47ff. https://github.com/xournalpp/xournalpp/blob/master/rpm/fedora/xournalpp.spec
Thank you! I was able to skip all the LaTeX stuff by ignoring weak dependencies:
```zsh
sudo dnf install --setopt=install_weak_deps=False xournalpp
```

**Comment by rolandlo** [comment]
I'm closing the issue, since we do not require LaTeX anywhere at this repository.

**Comment by badshah400** [comment]
> ...we don't require any `texlive` (or other `TeX`-related) installation. This [xournalpp.spec](https://build.opensuse.org/package/view_file/openSUSE:Factory/xournalpp/xournalpp.spec?expand=1) from OpenSUSE does however.

No, that is misleading; it clearly does not. LaTeX is recommended, _not_ required, as part of these two lines:

```
Recommends:     tex(scontents.tex)
Recommends:     tex(standalone.tex)
```

Please try `sudo zypper install --no-recommends` and see for yourself.

**Comment by rolandlo** [comment]
@badshah400 
I don't have an OpenSUSE installation to play with, but I was talking about this line:
```
BuildRequires:  texlive-latex-bin
``` 
The `scontents` and `standalone` packages are just two packages on top of that.

**Comment by badshah400** [comment]
`BuildRequires` is what packages require to build the RPMs, they are not automatically installed by the app on a user's system as dependencies of the app/package itself.

Packages listed as `Requires` install to a user's machine as mandatory dependencies when they install xournalpp, and there is no `Requires` on any texlive packages from that spec file.

**Comment by rolandlo** [comment]
Ok, thanks for the explanations. I take my words back then.
