### ISSUE TITLE
Latex editing Maths equation

### ISSUE THREAD

**Issue by mandypreet** [xournalpp/xournalpp#4415]
**Affects versions :**
 - OS: Windows 10 pRo
 - Version of Xournal++: 1.1.2
   
 - Installation method: official release

**Describe the bug**
While editing the latex used to insert maths symbol or equation. The position of the symbol or text gets changed. We have to drag it again to its original position, very much time consuming for maths inputs. Please fix this bug as soon as possible. With lot of thanks.

**Comment by Chrisimx** [comment]
I will work on this.
