### ISSUE TITLE
macOS - cannot navigate the menubar using mouse

### ISSUE THREAD

**Issue by imartayan** [xournalpp/xournalpp#4433]
**Affects versions :**
 - OS: macOS 13.0.1
 - Version of libgtk: 3.24.33
 - Version of Xournal++: 1.1.2
 - Installation method: official release

**Describe the bug**
When clicking on the menubar, the menu opens but clicking on any of the options closes the menu without doing anything.
Note that navigating the menubar using keyboard works fine.

**To Reproduce**
1. Click on "Edit"
2. Click on "Preferences"

**Expected behavior**
Clicking on an option should perform the corresponding action.

**Comment by rolandlo** [comment]
This was already reported upstream https://gitlab.gnome.org/GNOME/gtk/-/issues/5305#note_1598624
GIMP has some patches ready: https://gitlab.gnome.org/Infrastructure/gimp-macos-build/-/merge_requests/158/diffs

**Comment by zbyju** [comment]
I have the same issue.

For now it is possible to hover over the menu using mouse and then use keyboard arrows to navigate through the menu; sometimes this even fixes the issue for a little bit and the mouse is usable again

**Comment by rolandlo** [comment]
The issue may be fixed with the upgrade of Gtk from 3.24.35 to 3.24.36. So please wait for the next fresh [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and try again. Check that it uses Gtk 3.24.36 in menu `Help > About`.

**Comment by imartayan** [comment]
Indeed, the issue has been fixed with the new version of Gtk! I'm closing this issue
