### ISSUE TITLE
Windows installer not fully functional with system account

### ISSUE THREAD

**Issue by ljoets** [xournalpp/xournalpp#4445]
**Affects versions :**
 - OS: Windows 10
 - Xournalpp-1.1.1
 - Xournalpp-1.1.2

**Describe the bug**
Installation with command line is not fully functional when launched with SYSTEM account (non-interactive).
With an admin account everything is ok.

We use WPKG for large-scale software deployment in high schools.

Based on the solution found here : https://community.chocolatey.org/packages/xournalplusplus#files, it is possible to install the software silently. We use this 2 command lines :

Install :
`xournalpp-1.1.2-windows.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /S /quiet` (from the link above), but `xournalpp-1.1.2-windows.exe /S` seems to works fine too.

Uninstall :
`%PROGRAMFILES%\Xournal++\Uninstall.exe /S`

These two commands work perfectly when using an admin user account.
Unfortunately, the silent installation by WPKG is done with the SYSTEM account.

When the installation is silently launched by the SYSTEM account, the software files are correctly copied into the `%PROGRAMFILES%` directory and the executable located in `/bin` is launched, the software works.

BUT...
- No shortcut is created in the Start menu.
- The Xournal++ entry is missing from the list of installed software in the configuration panel.
- The Xournal++ entry is missing from the context menu when you right-click on a PDF file.

**Comment by ljoets** [comment]
Problem is still present in 1.1.3 version.
I think the cause is that the installation in silent mode is systematically done for the current user.
The installer does not have a setting to make silent installation for all users.
It it the same problem reported here : #4209

**Comment by macxcool** [comment]
@ljoets 
The install switches you are using are for JRSoft's 'Inno Setup', but I'm pretty sure Xournal++ uses the Nullsoft Installer. You want to use '/S /NCRC' to make the Nullsoft Installer silent.

**Comment by macxcool** [comment]
I think that #4919 is the reason for your problem. The solution right now is to create a shortcut in the System Start Menu after installation. Everything installs into C:\Program FIles\ just fine. It's the just shortcuts that are missing.

**Comment by rolandlo** [comment]
This was fixed in the release branch via  via #5988.
