### ISSUE TITLE
Poppler qt4 is build though disabled

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#445]
I saw, that on my arch machine as well as in travis CI CMAKE_ARGS for poppler are just ignored.
So the compilation of these components prolong the build time. 
On my uptodate debian server the components are disabled and not compiled as configured.

**Comment by andreasb242** [comment]
Not relevant anymore.

I use now the standard GLib APi, and export the PDF with Cairo.
The old implementation will still be available with -DADVANCED_PDF_EXPORT_POPPLER=ON
Currently Bookmarks are not exported, but with Cairo 1.16 it will also be possible.
So this should solve a lot of problems I hope.

**I Copy this texts to all related tickets **
