### ISSUE TITLE
Feature to paste image matching the screen resolution (Screenshot pasting)

### ISSUE THREAD

**Issue by ModProg** [xournalpp/xournalpp#4457]
**Is your feature request related to a problem? Please describe.**
When I make a screenshot and paste it in xournalpp it always gets resized, which is anoying when I for example copy together a bunch of snippets from some slides/exercises and they get pasted with widly different scale due to having different image sizes.

**Describe the solution you'd like**
An option to make paste always paste matching the screen resolution, meaning when you paste a screenshot, it has exactly the same size in xournalpp as it had before.

Or even better, make it a secondary paste-action, so you can choose between resizing paste and non resizing paste.

Alternatively, make it screen resolution independent, i.e. allow setting a ppi for a document and scale the paste to match the ppi. Meaning that while the paste doesn't necessarily keep the exact size, you can at least paste multiple screenshots of different sizes, and they have the same scale.

**Describe alternatives you've considered**
Manually resize each paste

**Additional context**
A good way to test this is to make a screenshot of something drawn in xournalpp and paste it.

**Comment by rolandlo** [comment]
I think there is already an issue about that (to which @Technius replied), but I couldn't find it. Looking at the situation, it seems to me that the image size is correct when the windows are zoomed at 100%. For example if you take a screenshot in Xournal++ or Evince with a zoom of 100% and paste it into Xournal++ (at any zoom level) and then zoom in Xournal++ to 100% the pasted screenshot has the same size on the screen as it was displayed originally.

**Comment by ModProg** [comment]
The top left circle is the original, without zooming, I made two screenshots and pasted them.

The scale was set tp `1`. I used `grim -t png - | wl-copy -t image/png` for screenshotting.
![grafik](https://user-images.githubusercontent.com/11978847/204637276-b5e0b73d-3917-4a52-8160-a18bcfdfeae5.png)

**Comment by rolandlo** [comment]
@ModProg That looks strange indeed. Could you please provide some details on your setup (Linux distribution, x11 or wayland)
Which is the first screenshot, which one the second?

**Comment by ModProg** [comment]
DPI is 72, I'm using sway(wayland) and Arch Linux.

After adjusting the DPI to match my screen better (something around 110) it actually seemed to get worse: 
![grafik](https://user-images.githubusercontent.com/11978847/204762568-74a21d21-1a38-4f5b-aaa0-a03a7acbbfb1.png)

**Comment by ModProg** [comment]
> Which is the first screenshot, which one the second?

I first drew the circle in the top left, then I made and pasted the screenshot in the top right.
Afterwards the one at the bottom.

**Comment by rolandlo** [comment]
It looks like `grim` is scaling the image by default, see 
https://github.com/emersion/grim/blob/47e2658619c6b5a790732c5876fb84e8273f08a9/main.c#L309-L320

You may need to use the `-s 1` option, i.e. 
```term
grim -s 1 -t png - | wl-copy -t image/png
```

**Comment by ModProg** [comment]
So setting the scale to one, in both xournal and grim makes it work. For some reason, grim then produces strange artifacts in the image, but that is probably an issue with grim and a screen with a high resolution, I guess.

I might have to look into a different screenshotting tool then, or ask them if that is something they could fix.

**Comment by rolandlo** [comment]
I'm closing the issue, since Xournal++ is not at fault here.
