### ISSUE TITLE
Flathub version won't start

### ISSUE THREAD

**Issue by alexeymuranov** [xournalpp/xournalpp#4475]
**Affects versions :**

 - OS: Linux Mint 21.
 - (Linux only) Desktop environment: X11, Cinnamon.
 - Version of libgtk: 3.24.34.
 - Version of Xournal++: 1.1.3.
 - Installation method: Flatpak, from Flathub.

**Describe the bug**

When trying to launch, the GUI does not show up. In the terminal I get:

```console
$ flatpak run com.github.xournalpp.xournalpp
Gtk-Message: 13:39:24.428: Failed to load module "xapp-gtk3-module"
** Message: 13:39:24.473: TEXTDOMAINDIR = (null), Platform-specific locale dir = /app/share/xournalpp/../locale, chosen directory = /app/share/xournalpp/../locale
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib ../../../src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib ../../../src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib ../../../src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib ../../../src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
```
The process does not exit, I have to hit `Ctrl-C`.

**To Reproduce**

Try to launch from terminal or from application manager.

**Expected behavior**

The GUI should appear.

**Additional context**

I believe it used to work before some recent `flatpak update`. But I haven't used it in a while.

**Comment by ovari** [comment]
Error reproduced with [Linux Mint 21.1 Cinnamon beta](https://ftp.heanet.ie/pub/linuxmint.com/testing/linuxmint-21.1-cinnamon-64bit-beta.iso).

**Comment by ovari** [comment]
Error **not** reproduced with Linux Mint 20.3 Cinnamon with Xournal++:
* Version: 1.1.3
* Git commit: 2dbd16d2
* Built on: Nov 28 2022, 08:07:58
* with libgtk: 3.24.34

Hopefully this can help discover and fix the source(s) of the error(s).

**Comment by K4LCIFER** [comment]
Issue not present on Arch Linux gnome 43.1 wayland, xournal++ installed through flatpak.
- Version 1.1.3

**Comment by rolandlo** [comment]
Does it work on Wayland instead of X11?

**Comment by alexeymuranov** [comment]
@rolandlo , there is not Wayland on Mint. I tried it on Ubuntu, and on Ubuntu it works on both X11 and Wayland. So the bug could be in Mint.

**Comment by TechD123** [comment]
Same error here on LM 21.

> Gtk-Message: 11:07:20.438: Failed to load module "xapp-gtk3-module"
** Message: 11:07:20.475: TEXTDOMAINDIR = (null), Platform-specific locale dir = /app/share/xournalpp/../locale, chosen directory = /app/share/xournalpp/../locale
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib ../../../src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)


Works flawlessly when running as root though :)

**Comment by Kazutadashi** [comment]
Same error as well

> flatpak run com.github.xournalpp.xournalpp
> Gtk-Message: 11:18:57.443: Failed to load module "xapp-gtk3-module"
> ** Message: 11:18:57.471: TEXTDOMAINDIR = (null), Platform-specific locale dir = /app/share/xournalpp/../locale, chosen directory = /app/share/xournalpp/../locale
> 
> ** (xournalpp:2): WARNING **: 11:18:57.472: configfile does not exist /home/username/.var/app/com.github.xournalpp.xournalpp/config/xournalpp/settings.xml
> 
> ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
> ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
> ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib ../../../src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
> ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
> ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
> ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
> ALSA lib ../../src/confmisc.c:160:(snd_config_get_card) Invalid field card
> ALSA lib ../../usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
> ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)

If I try and run as root as TechD123 mentioned, it works correctly. 

I'm running on OS: Linux Mint 21.1 x86_64 
Kernel: 5.15.0-75-generic 
DE: Cinnamon 5.6.8
NVIDIA Driver: nvidia-driver-530

**Comment by rolandlo** [comment]
Closing in favor of  #5020
