### ISSUE TITLE
Stylus keeps drawing if pen is lifted on another page

### ISSUE THREAD

**Issue by fakefred** [xournalpp/xournalpp#4491]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: Plasma 5.26.4 X11
 - libgtk 3.24.35
 - Xournal++ 1.1.3, commit 2dbd16d2
 - Installation method: official release via pacman

**Describe the bug**
When I draw a freehand line over the border of a page, lift the stylus and move it back, stylus keeps drawing.

The tablet I'm using is a Wacom CTH-490, connected via USB.

**To Reproduce**
1. Prepare two adjacent pages in Xournal++ and connect tablet.
2. Activate free-hand line in Pen mode or Highlighter mode.
3. Depress stylus on page 1 and begin drawing free-hand line.
4. Keep drawing, move cursor to page 2.
5. Release and hover stylus.
6. Move cursor back to page 1.
7. The free-hand line continues although stylus is not touching tablet.
8. The line only ends if I click the stylus, or physically move it away from tablet.

**Expected behavior**
Line ends when cursor moves to page 2; no line is drawn when pen is lifted.

**Screenshots of Problem**
[Screencast](https://fkfd.me/static/xournalpp.mp4)

**Additional context**
This bug occurs *sometimes* with a mouse, by releasing LMB on page 2.

This bug occurs both in single- and paired-page mode.

After step 8, the line sometimes stays; other times it vanishes to a single point.

**Comment by K4LCIFER** [comment]
I can reproduce this issue.

![test1](https://user-images.githubusercontent.com/7829231/214730998-20ca424c-fb13-4ca9-b2bb-b756aa489a06.gif)

- Xournal++ v1.1.3
- Arch Linux
- Gnome 43.2 Wayland
