### ISSUE TITLE
Pen pressure stop working after rises a little the pen on Windows 7 

### ISSUE THREAD

**Issue by Nistek** [xournalpp/xournalpp#4496]
**Affects versions :**
 - OS: Windows 7 Professional 64 bits.
 - Which version of libgtk do you use: 3.24.35
 - Version of Xournal++: 1.1.3+dev c9ac931b
 - Installation method: Official release, Windows Installer

**Describe the bug**
When I start to writing/drawing in Xournal++ or after the tip rises a little (it does not lose "connection" with the surface, it remains within the electromagnetic field of the tablet), for example to put a separation between two words, the program detect maximum pressure, no matter how much I press the pen. 

To make it detect the pressure again, I need to move the pen out of contact with the tablet (out of its magnetic field). When I bring the pencil closer again and write the pressure sensitivity work again until I rise a little the tip (e.g. to make a separation, that it's very common) then the pressure get fixed to maximum for Xournal++, other programs detect pressure correctly.

The tablet I'm using is a Xp-pen Deco v02, connected via USB.

**To Reproduce**
Star Xournal++ and star writing.
Or
Rise the tip a little (e.g. to make a separation).

**Expected behavior**
At start or rising the tip a little you expect that the pressure keep working.

**Screenshots of Problem**
Video: https://user-images.githubusercontent.com/61591806/206913767-76a1fed6-76f2-4200-b48f-3ed7ed935ad6.mp4

**Additional context**
It's something related with Windows 7. 
Windows Vista and 8 weren't tested. Windows 10 doesn't have this problem, if I activate Windows Ink, works fine. 
On Ubuntu 22 and worked fine too.

**Comment by rolandlo** [comment]
This looks like a duplicate of #3311. Note that Windows 7 doesn't have Windows Ink. You might consider following https://github.com/xournalpp/xournalpp/issues/3311#issuecomment-894242781.

**Comment by Nistek** [comment]
Oh, sorry i'm searching something related with bring near or move away the tip and i didn't notice this previous bug thread.

Yeah, look like the same issue/bug. And yes, it is as mentioned by @lb90 on https://github.com/xournalpp/xournalpp/issues/3311#issuecomment-894242781 patching to an older version of GTK, works fine.

Thank you very much @rolandlo
