### ISSUE TITLE
Unable to install (Poppler 0.69)

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#450]
Hi!
I've got a problem: I did manage to successfully install Xournalpp something like 3 days ago in order to add a feature, but now that I updated my fork in order to be in sync with your master I can't install it anymore.
`cmake` command returns an error saying that my Poppler version (0.69) isn't supported yet, but it used to work few days ago and I didn't upgrade my Poppler version ever since.
I noticed that the CMake file has been updated adding a line in particular which is 
set (POPPLER_MAX_VER  "0.68")
is there a workaround or a way to update Poppler max version?
I'm actually on Debian Testing 
Thank you

**Comment by morrolinux** [comment]
You can statically build poppler with
cmake -DBUILD_POPPLER=ON ..

**Comment by morrolinux** [comment]
I see... Have you tried to get this package via backports? https://packages.debian.org/sid/libopenjpeg-dev
But maybe this dependency should be updated in xournalpp in the first place @andreasb242 what do you think?

**Comment by andreasb242** [comment]
The Poppler stuff is really complicated, may the best way would be to allow to switch to a standard installation which don't need additional poppler headers, which useses cairo for export.
So there would not be the issue, that some poppler version is working and some not.
The big issue: No Bookmarks, no Links, all will be lost on export.

**But for now:**

> command returns an error saying that my Poppler version (0.69) isn't supported yet, but it used to work few days ago and I didn't upgrade my Poppler version ever since.
I noticed that the CMake file has been updated adding a line in particular which is
set (POPPLER_MAX_VER "0.68")

If you are sure it was working with 0.69, simple set the max Version to 0.69.
If it's building, you can add this change to the next Pull request, if not, it will probably be more to do...

**Comment by luco5826** [comment]
Thank you very much for your replies!
I tried to modify the MAX_VERSION from 0.68 to 0.69 and the installation goes fine, but then when I try to launch it, a dialog shows up saying that xournal couldn't find any UI file, neither in the relative path nor in the absolute one or in /usr/local/share. 
Maybe this is related to another issue but since it came after modifying the CMake file i thought that submitting a new Issue regarding that wouldn't have been a smart idea

**Comment by andreasb242** [comment]
try to start it from build directory, does it work then? Some time ago we compiled in the build directory, and this caused errors, so the files should be loaded relative. Sorry for this :-(

**Comment by andreasb242** [comment]
I'll do a short fix for this, I have an idea...

**Comment by morrolinux** [comment]
Anyway trying to build on my Mac (where POPPLER_ENABLED=ON is by default) is now a problem because of the poppler build:
`UnboundLocalError: local variable 'object_name' referenced before assignment`

**Comment by andreasb242** [comment]
https://github.com/xournalpp/xournalpp/pull/452

Will fix the resource loading, but not the Poppler build on Mac ;-)

**Comment by luco5826** [comment]
Modifyng Poppler Max Version now fixed it! Now even the resources works perfectly!
