### ISSUE TITLE
Add in Markdown Feature when inserting text

### ISSUE THREAD

**Issue by COD1995** [xournalpp/xournalpp#4503]
**Is your feature request related to a problem? Please describe.**
I love taking notes on xournal. The current equation insertion is good, but if we can just incorporate markdown into the text feature and delete the latex one, it will be much more succinct.

**Comment by forgottosave** [comment]
Actually I think this could be a great, but bigger feature, if combined with text-layers, similar to Notabililty.

For Xournal++ I'd suggest having a new layer type, a "text-layer", where the whole page is one textblock. This would allow to use the page like a normal "word document", which you can take notes in and additionally annotate stuff on top of it. This text-layer could then also support markdown, which many students (including me) love to use to write notes.

**Comment by oa01** [comment]
> Actually I think this could be a great, but bigger feature, if combined with text-layers, similar to Notabililty.
> 
> For Xournal++ I'd suggest having a new layer type, a "text-layer", where the whole page is one textblock. This would allow to use the page like a normal "word document", which you can take notes in and additionally annotate stuff on top of it. This text-layer could then also support markdown, which many students (including me) love to use to write notes.

I would make heavy use of this feature in classes where i need to write lots of text.
The only thing i am concerned is that this would probably mean i could not have individual textboxes that i can move arround. (Maybe this could be a Feature of the annotation layer) 

_Sorry for my bad English, its not my first language_

**Comment by MattiaGrigoli** [comment]
how can i use this feature? i cannot find it anywhere
