### ISSUE TITLE
Pressure detection on wayland GTK backend

### ISSUE THREAD

**Issue by l0wl3vel** [xournalpp/xournalpp#451]
When using my Wacom One or the Elan Touchscreen from my Envy X360 with the wayland backend no pressure sensitivity is available. As soon as I switch to GTK_BACKEND=x11 the pressure is picked up correctly. Built from source on Arch Linux and using libinput.

**Comment by andreasb242** [comment]
Hi @l0wl3vel 

There are GTK functions to get pressure, but they cause random crashes, if the System has a Touchscreen and a Tablet input at the same time. Really hard to find ;-)

Therefore we use now a Workaround, which solves this crashes. For this I query the axes on the Pen.

can you please open the file: src/control/tools/StrokeHandler.cpp
go to StrokeHandler::getPressureMultiplier (Line 278)

after
>int axesCount = gdk_device_get_n_axes(device);

add
> 	printf("axesCount: %i\n", axesCount);

This will print the axes of your pen.
On X11 this will be Probably 6. At least 5, else it would not work.

Can you thell me the output if you are running it on Wayland?

**Comment by andreasb242** [comment]
At line 285,
> 	if (axesCount <= 4)

if you change to

>	if (axesCount <= 2)

it will be working, right?
Can you check the axes of an USB Mouse / Touchpad if you have, if they have 2 or less axes?

**Comment by andreasb242** [comment]
Ah, wait, Elan Touchscreen will probably not working anymore, as I don't think this has pressure.
I Probably have to query if the device is a pen. I don't do this today, but probably soon. Do you may have time to retest?

**Comment by l0wl3vel** [comment]
We are talking about an Elan Digitizer, which has the capabilities for a stylus. The 3 axes for the Elan were for the stylus. And I tested it with "if (axesCount <= 2)" and it worked for the Elan stylus. For the Wacom though it was very faded. Touchpad and a mouse worked normally. I attached an example.
[ElanWacomPressure.zip](https://github.com/xournalpp/xournalpp/files/2641256/ElanWacomPressure.zip)

**Comment by andreasb242** [comment]
Ok, thank you for the information.

There are probably two things to do:
- Create a Test Dialog, where a pen can be tested, and which outputs debug information for the developer
- Allow to configure the pen thickness per device

The best option would be to detect it automatically, or create a database e.g. if users tell us problems like this ticket, add a entry to a config file, so this will be fixed for other users.

**Comment by andreasb242** [comment]
This should work now. If not, reopen.
