### ISSUE TITLE
XML Parser Error: Wrong count of points (21)

### ISSUE THREAD

**Issue by Linuxsploit2019** [xournalpp/xournalpp#4513]
**Affects versions :**
 - OS: 

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

 - libgtk and xournal version: 
    Xournal++ 1.1.1
    libgtk: 3.24.33

 - Installation method:
   Ubuntu Software 

Description of the bug:  

I suddenly cannot open a specific file when just one day ago, it was still working fine. I keep getting the error "XML Parser Error: Wrong count of points (21)" for a file that i store all of my university math notes in. Despite this error, the other xournal files seem to be opening just fine.

**To Reproduce**
I think its an error due to that specific file so their are no general steps to reproducing it. 

**Expected behavior**
File opens up instead of giving me the error "XML Parser Error: Wrong count of points (21)". 

Screenshot of Problem:  
![Screenshot from 2022-12-17 20-33-17](https://user-images.githubusercontent.com/63708230/208263316-96d907f7-0418-4c5b-86c4-c52a4747bdee.png)

**Additional context**

None

**Comment by rolandlo** [comment]
Your document is probably corrupted. We can try to fix it (maybe only partially). Can you share it with us (in private on the Gitter channel if you like).

**Comment by Linuxsploit2019** [comment]
> Your document is probably corrupted. We can try to fix it (maybe only partially). Can you share it with us (in private on the Gitter channel if you like).

absolutely, thankyou!

**Comment by Technius** [comment]
I'm going to assume this has been fixed and close this issue. Let me know if you're still running into this problem.
