### ISSUE TITLE
Ctrl+A with Text Tool selects all elements instead of the text

### ISSUE THREAD

**Issue by mandypreet** [xournalpp/xournalpp#4518]
i have installed the xournal++ 1.1.3 dev nightly build.
While editing the text in text box, when i give command ctrl+A to select all text within the text box, it selects the whole text of the page. which is annoying while editing the whole text. It should select only the text within the text box while giving the command ctrl+A.
![Selecting text](https://user-images.githubusercontent.com/83940423/208921820-a7d1f926-41b7-4b70-8d3a-1723881f9a37.jpg)
![Selecting text](https://user-images.githubusercontent.com/83940423/208922008-c0b91321-89a3-4c0b-a801-ad1f47ec2924.jpg)

**Comment by Technius** [comment]
Possible regression due to #4024.

**Comment by bhennion** [comment]
Fix via #4797
