### ISSUE TITLE
Select Color Dialog Window

### ISSUE THREAD

**Issue by kacago22** [xournalpp/xournalpp#4519]
- OS: Windows10
 - Which version of libgtk do you use 3.24.35
 - Version of Xournal++:  1.1.3 dev (Dec 18)
 - Installation method: install.exe

It's not really a "bug".  I run xournal on the second screen - when I press the color square at the end of the color selector toolbar to open the Select Color Dialog Window it opens in the upper right corner of the first screen - where I cannot even reach with my stylus (on a Huion Graphical Screen) ...

**Comment by rolandlo** [comment]
The Select Color Dialog opens up on the first screen on Windows for me as well when the main Window is displayed on the second screen.

**Comment by jhilmer** [comment]
Think this is solved with my latest commit to #4543 - the parent attribute was not initilized

**Comment by jhilmer** [comment]
Fix is in master now. Should be closed.
