### ISSUE TITLE
[lua API] work with pictures (add and possibly get them as well)

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#4529]
We already have `app.getStrokes` and `app.addStrokes`, in my opinion, these are the most important ones. But there are other use cases, where it would be nice to work with pictures (and text/tex -> different issue) as well.

My use case is to kinda diff beamer presentations. I've thought of
1. backupping the pdf
2. rerun latex
3. convert the pages of the backup to images with a specific transparency (e.g. with imagemagicks `convert`)
4. xournalpp -> add these transparent images on the corresponding page (new layer)

With the rerun of latex and backupping the pdf we might not be able to fully automate this (just maybe provide some defaults), but the essential aspect missing is the ability of adding images via the api.

Just to make it complete, it would be nice to have (like with `addStrokes`) also the corresponding inverse function (like with `getStrokes`).

Note: I'm willing to work on this, I've just not the time right now, so if someone else wants to... feel free (just write here, so that there's no duplicated work on this). One point to start with possibly is `src/core/gui/toolbarMenubar/ToolMenuHandler.cpp:476` where the image-tool is registered (starting to find the function how images usually are added manually with the image-tool)

**Comment by rolandlo** [comment]
@atticus-sullivan In what form (datatype) do you want to pass the images around between C++ and Lua? As a string?

**Comment by atticus-sullivan** [comment]
Hm, initially I thought of passing paths to files. The downside of this is that this won't work with clipboard stuff, and more bad is that this way the `getStrokes` is impossible.
I think I've seen passing images encoded in base64 if I remember correctly, so maybe this would be an option (-> yes this would be strings, I guess).
The cons on this solution is that we've got some overhead in handling the strings (due to two times the memory allocation on both (lua and cpp) sides and string interning on the lua-side). I'm just not quite sure how this turns out on the performance side.

So maybe it's worth to implement both (`addImages` with base64 encoded image (as reverse of `getImages`, and in general for images not being stored in the filesystem, e.g. for clipboard like stuff) and `addImages` with the path to a png/jpg/... file).

**Comment by rolandlo** [comment]
I don't know yet what to suggest. It would be great if `app.getImages` and `app.addImages` could work hand in hand with a Lua image library like [lua-vips](https://github.com/libvips/lua-vips) (preferably) or [lua-imageick](https://github.com/isage/lua-imagick). So you could manipulate the images in a meaningful way via that Lua library. Unfortunately  Lua-vips requires Lua-Jit and Lua-imagick works with Lua 5.1 and 5.2, but apparently not 5.3/5.4 yet and looks unmaintained.

**Comment by atticus-sullivan** [comment]
Oh ok. Tbh that's not what i thought of when thinking about adding/getting images, but sounds like a nice idea to plugging in a generic image processing library.
I'll search for libraries which can be used as well, maybe I find something (if so the goal is to check them out and make a small comparison).

---
Just to explain where I was coming from:
My initial goal was to make some kind of an overlay of LaTex beamer presentations (by converting one pdf to images with transparency) to be able to visually "diff" them).
That's also where that "for me adding images with a filepath identifying the image would be enough" came form.

**Comment by rolandlo** [comment]
I suggest you add some command like `app.addImagesFromFilepaths`. Then `app.addImages` is still reserved for adding real image data with a proper "inverse" `app.getImages`.

Thanks for finding `simpleITK`. That looks quite interesting. By the way `lua-vips` also has a chance to eventually run on Lua 5.3 (see https://github.com/libvips/lua-vips/issues/9)

**Comment by atticus-sullivan** [comment]
Ok, then I think the plan will be something like this
1. implement `app.addImagesFromFilepaths` (this shouldn't be too complicated I think as it is mostly replicating stuff that is currently possible via the GUI). Also this function will always be available (even if `lua-vips` or the library we choose is not installed)
2. decide what library to use
    1. [`simpleITK`](https://github.com/SimpleITK/SimpleITK) (I still didn't test this so far)
    2. [`lua-vips`](https://github.com/libvips/lua-vips) only for LuaJIT, but see maybe portable for PUC Lua (to replace FFI I also found this project https://github.com/q66/cffi-lua, but as I have 0 experience with LuaJIT so far I can't really talk about LuaJIT stuff yet).
      Talking about our search for an image-manipulation library with other lua users, I also got the recommendation to completely switch over to LuaJIT (it's not an old version of Lua, it's just something like a different branch) but I'm not sure about the changes to the project this would mean.
    4. [`lua-imageick`](https://github.com/isage/lua-imagick) so far only for Lua5.1/5.2
    5. other libraries?
3. implement functions to use that library

And just a note about the possibilities, maybe with the proper image-manipulation library we could do basic (no realtime/interactive due to the lack of hooking into the GUI) image rotation (which is something that comes up now and then when working with images in xournalpp).

**Comment by rolandlo** [comment]
One thing that would also be possible via the integration of adding and getting images via Lua image libraries would be to automatically compress all images in a document. That would help a lot to those correcting scanned homework with a huge resolution.

I'm currently see if I can get `lua-vips` to work on Lua 5.3. I have also tested the cffi. It doesn't seem to have nearly the performance that is promised on the luaffi repo and is a complete reimplementation, apparently not compatible with `lua-vips`.

Switching to LuaJIT could be considered, as it definitely has its advantages (performance and support), but it will break some user stuff.

**Comment by atticus-sullivan** [comment]
> but it will break some user stuff

I also was at this point since LuaJIT "branches" of at Lua5.2 (or 5.1 not completely sure). But looking at the changes which were made since then ([lua5.3](https://www.lua.org/manual/5.3/readme.html) [reference](https://www.lua.org/manual/5.3/manual.html#8) (and [lua5.4](https://www.lua.org/manual/5.4/readme.html#changes) [reference](https://www.lua.org/manual/5.4/manual.html#8))) actually I mainly see three bigger issues:
1. some stuff regarding strings (e.g. `gmatch` changed) since many lua scripts work with these functions
2. numbers vs integers (mainly an issue with the api)
3. some stuff regarding math (some operators were introduced in 5.3 afaik) this too are things that users might use more widely

Typically these issues are not that problematic when it comes to porting to the older lua version capabilities (at least on the lua side, I've no other experience with the api than xournalpp), but I don't know how many user-Plugins (not shipped with xournalpp) are out there. These could become an issue.

**Comment by rolandlo** [comment]
I got `lua-vips` to work partially on Lua 5.3. At least I can already create an image from text or from a memory buffer.

**Comment by rolandlo** [comment]
Now my fixed `lua-vips` version https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3 works on Lua 5.3.6 (only one I tested) in combination with my fixed `luaffifb` version https://github.com/rolandlo/luaffifb

It can create images from file path or from string buffer, manipulate the image in various ways and write the modified image to a file or to a string buffer. It's pretty fast.

I think `app.getImages` should pass the images as Lua strings (apparently using `lual_buffer` API avoids copies, see https://stackoverflow.com/questions/74135260/handling-binary-data-between-c-and-lua) and `app.addImages` should also pass them as Lua strings. Note that Lua strings can hold arbitrary binary data.

Then 
- use `app.getImages` to get the image strings from a layer or selection
- create the images from those strings using `vips.Image.new_from_buffer`
- manipulate the images (e.g. compress them, apply some filters, rotate or flip them)
- use `image:write_to_buffer` (specifying the desired image format)  from `lua-vips` to write the images to strings
- use `app.addImages` to add the modified images back into Xournal++

We may need a better solution for deleting the old elements than deleting a whole selection. This does not only apply to images, but also to strokes (and potentially other elements). Maybe in `app.getStrokes`, `app.getImages` we should add pointers to the elements passed (via `lua_pushlightuserdata`) and add a function `app.removeElements`, which removes all elements pointed to by the list of pointers passed. Maybe `addImages` (and similar) could also return the pointer to the image added instead of nil, if it was successful.

**Comment by atticus-sullivan** [comment]
Oh that's nice. Can you write a short intro how to install/test your lua-vips? (`luarocks --local --lua-version=5.3 make` for `luaffifb` and `lua-vips` in the corresponding directories did not work for me) Maybe it makes more sense to put this along with your forks.

**Comment by atticus-sullivan** [comment]
And on the last point of deleting elements, I think we should separate this for now from this issue and put this into a new one. It affects the strokes and all other elements as well after all.

**Comment by atticus-sullivan** [comment]
> I think `app.getImages` should pass the images as Lua strings (apparently using `lual_buffer` API avoids copies [...]

Not sure about `luaL_buffer` at this place. In the [docs](https://www.lua.org/manual/5.4/manual.html#luaL_Buffer) I read this like some sort of a string builder. So in the end lua will create a string which resides in the lua space (which means to be interned, reference counted and copied). Also [`luaL_addvalue`](https://www.lua.org/manual/5.4/manual.html#luaL_addvalue) (which is the function to add to a `luaL_buffer`) will add the top value from the stack, but at this point the value already got copied to the lua-space.

But I have to admit I've got no real workaround here. The [solution mentioned in the so post you linked](https://stackoverflow.com/questions/11689135/share-array-between-lua-and-c) passes a `userdata` object which most probable won't be compatible with `lua-vips` loading from a string (and using `userdata` (not light) involves copying anyhow).

I'm afraid getting around copying the image data will be hard as the c-side manages the lifetime of the object and this is incompatible with working with lua strings.
So if we want to avoid copying we might end up either using vips's `new_from_memory_ptr`/`new_from_memory` if we can somehow manage the lifetime of the memory from the c-side (still not quite sure about ffi at this point) or using `light_userdata` (needs to be freed explicitly on the lua-side which isn't that nice) and writing our own `new_from_userdata` vips function. (And we'd need to think about if sharing the memory where the image-data is stored with lua-vips is really a good idea).

Disclaimer: That's how I understand/read the lua reference in this case, not sure if this is all correct

**Comment by rolandlo** [comment]
> Oh that's nice. Can you write a short intro how to install/test your lua-vips? (`luarocks --local --lua-version=5.3 make` for `luaffifb` and `lua-vips` in the corresponding directories did not work for me) Maybe it makes more sense to put this along with your forks.

Installation instructions have been added to the [README](https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3) in meantime. You can then
1) run `lua5.3` and type all the commands from the example below the installation instructions, just without typing `local` and by providing a correct image path.
  or
2) checkout and compile the PR #4884 and then create a plugin with callback specified in the [PR description](https://github.com/xournalpp/xournalpp/pull/4884#issue-1717656388) and trigger the callback with a document containing a layer (current one) with >=two images.

**Comment by rolandlo** [comment]
> > I think `app.getImages` should pass the images as Lua strings (apparently using `lual_buffer` API avoids copies [...]
> 
> Not sure about `luaL_buffer` at this place. In the [docs](https://www.lua.org/manual/5.4/manual.html#luaL_Buffer) I read this like some sort of a string builder. So in the end lua will create a string which resides in the lua space (which means to be interned, reference counted and copied). Also [`luaL_addvalue`](https://www.lua.org/manual/5.4/manual.html#luaL_addvalue) (which is the function to add to a `luaL_buffer`) will add the top value from the stack, but at this point the value already got copied to the lua-space.
> 
> But I have to admit I've got no real workaround here. The [solution mentioned in the so post you linked](https://stackoverflow.com/questions/11689135/share-array-between-lua-and-c) passes a `userdata` object which most probable won't be compatible with `lua-vips` loading from a string (and using `userdata` (not light) involves copying anyhow).
> 
> Disclaimer: That's how I understand/read the lua reference in this case, not sure if this is all correct
> 
> PS: (some thoughts on this, not sure if they are really qualified due to my lack of experience with ffi and lua-vips) I'm afraid getting around copying the image data will be hard as the c-side manages the lifetime of the object and this is incompatible with working with lua strings. So if we want to avoid copying we might end up either using vips's `new_from_memory_ptr`/`new_from_memory` if we can somehow manage the lifetime of the memory from the c-side (still not quite sure about ffi at this point) or using `light_userdata` (needs to be freed explicitly on the lua-side which isn't that nice) and writing our own `new_from_userdata` vips function. (And we'd need to think about if sharing the memory where the image-data is stored with lua-vips is really a good idea).

Maybe just let's keep it as simple as it is now (simply pushing the string via `lua_pushlstring`) until we are sure that a better solution exists. I think the C side and Lua side are not supposed to share the same memory anyway.

**Comment by atticus-sullivan** [comment]
> Installation instructions have been added to the [README](https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3) in meantime

Just two small note (here since issues are not activated in that other fork). I needed to install the `openslide` package and I get a segfault if the file to which the path of `new_from_file` points does not exist.

**Comment by atticus-sullivan** [comment]
> Maybe just let's keep it as simple as it is now (simply pushing the string via `lua_pushlstring`) until we are sure that a better solution exists. I think the C side and Lua side are not supposed to share the same memory anyway.

This sounds reasonable for playing around. We should though think about whether we want to merge it this way (keep being backwards compatible can be a nasty thing)

**Comment by rolandlo** [comment]
> > Installation instructions have been added to the [README](https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3) in meantime
> 
> Just two small note (here since issues are not activated in that other fork). I needed to install the `openslide` package and I get a segfault if the file to which the path of `new_from_file` points does not exist.

I have also made the experience that using invalid data can result in segfaults. E.g. in the [watermark example](https://github.com/rolandlo/lua-vips/blob/fix-lua-5.3/example/watermark.lua) it is necessary to use integer division (`//` instead of `/`) so that it doesn't segfault. That can probably be improved either in `lua-vips` or `luaffifb`, but for playing around it seems sufficient to be careful to check all data and commands that are used.

**Comment by rolandlo** [comment]
> > Installation instructions have been added to the [README](https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3) in meantime
> 
> Just two small note (here since issues are not activated in that other fork). I needed to install the `openslide` package and I get a segfault if the file to which the path of `new_from_file` points does not exist.

The segfaults (not only when the file doesn't exist, but also if you use a function name which does not exist) are fixed now in the `fix-lua-5.3` branch.

**Comment by atticus-sullivan** [comment]
Nice, works for me as well :+1:

**Comment by atticus-sullivan** [comment]
To finally complete this feature request, this would be example code for the plugin I initially thought of:
```lua
function testA()
    local vips = require("vips") -- TODO place this globally?
    local struct = app.getDocumentStructure()
    local fn = struct.pdfBackgroundFilename

    for p,page in ipairs(struct.pages) do
        if page.pdfBackgroundPageNo ~= 0 then
            local image = vips.Image.pdfload(fn, { page = page.pdfBackgroundPageNo-1, background = 0 })
            local r, g, b = table.unpack(image:bandsplit())
            image = r .. g .. b .. (0.7*255)
            app.setCurrentPage(p)
            app.addImages{images={{data=image:write_to_buffer('.png')}}}
            -- TODO work nicely with layers
            app.refreshPage()
        end
    end
end
```
I think back then the idea was being able to check whether things moved in my LaTeX beamer presentation when changing some code.

---

Just one note: While testing various things, I stumbles over `Illegal instruction (core dumped)` errors which were present only from time to time (rerunning the same lua script sometime simply exited successfully) => Pretty ugly to track down where the issue originates, though here is example code:
```lua
-- I ran this with lua5.3 (gave me nice error messages than with lua5.4 where errors resulted often in a plain segfault)

local vips = require "vips"
local inputImage = vips.Image.new_from_file("/path/to/my.pdf", {page = 0, background = 0})
print(inputImage)
local r, g, b = table.unpack(inputImage:bandsplit())
local rgbaImage = r .. g .. b .. 50
print(rgbaImage)
rgbaImage:write_to_file("output.png")
```
So far in my tests the plugin-code worked fine (but as already written, the error only appears from time to time)

**Comment by rolandlo** [comment]
About the `Illegal instruction (core dumped)`: 
Does it help to  keep a reference
```lua
loader = vips.Image.find_load(fn)
```
to the loader before actually loading pages of the PDF?

**Comment by atticus-sullivan** [comment]
No not really:
```bash
# without calling find_load
$ failed=0 ; for ele in {1..50} ; do lua5.3 test.lua > /dev/null || (( failed++ )) ; done ; echo $failed
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
5
# with calling find_load
$ failed=0 ; for ele in {1..50} ; do lua5.3 test-loader.lua > /dev/null || (( failed++ )) ; done ; echo $failed
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
3
```
(just comparing numbers here doesn't work, I also got runs where the script calling find_load caused more errors). When increasing the sample, I also got some raw segfaults (no `Illegal instruction` as description)

**Comment by atticus-sullivan** [comment]
And a general thing: Not sure how to handle this best regarding to github. I saw you disabled the bug tracker/issues in your lua-vips fork. So should such bugs/errors be collected here?

**Comment by rolandlo** [comment]
I have just enabled the bug tracker in my lua-vips fork. I will forward any unresolved issues to upstream in case these contributions are upstreamed.
