### ISSUE TITLE
Hide menu bar in normal use

### ISSUE THREAD

**Issue by Hedronmx** [xournalpp/xournalpp#454]
Is it possible to hide the menu bar while in normal usage? I rarely use that menu

**Comment by andreasb242** [comment]
No, but this is easy to implementiert

**Comment by andreasb242** [comment]
Keyboard shortcut to show / hide menu is F10. If the menu is hidden, other menu shortcuts are not working anymore. F10 will show the menu again, and a restart will show the menu also again.
If there is a global menu active, the Menu item will be hidden.
If you like to hide the menu permanently, create a new bug. I'm currently not sure if this makes sense, and I don't use this anyway, as I have global menu enabled.

**Comment by leolca** [comment]
@andreasb242 I have noticed the same here... as the menu is hidden (F10), the shortcuts are no longer functional (Ctrl+z, for example).
