### ISSUE TITLE
Crashed when using eraser

### ISSUE THREAD

**Issue by l0wl3vel** [xournalpp/xournalpp#455]
[errorlog.20181204-133358.log](https://github.com/xournalpp/xournalpp/files/2643935/errorlog.20181204-133358.log)
[errorlog.20181204-133741.log](https://github.com/xournalpp/xournalpp/files/2643942/errorlog.20181204-133741.log)

Happened when switching from pen to eraser and back via the pen button and erasing again with the pen button in a short timespan

**Comment by andreasb242** [comment]
Does this happen always, or only sometimes?

Does this also happen on X11, or only on Wayland (if you have X11 also installed)

There was already such a crash (X11 / GTK) where I did a workaround.
Do you have a touchscreen? if yes:

can you move with the finger on the screen, and in parallel draw with the other hand with the pen some lines? Does this crash Xournal++?
This way I could easy reproduce the other Bug... So I would like to now, if they are common.

Thank you for reporting!

**Comment by andreasb242** [comment]
Ok, so I need wayland to reproduce it.
So erasing does not work with your device at all with X11?

**Comment by l0wl3vel** [comment]
Since erasing with the Elan Touchscreen in X11 doesn't work in general, I can't be sure. I also can't test it with my wacom, since it has no eraser

**Comment by andreasb242** [comment]
This should be fixed now. if not, reopen.

**Comment by l0wl3vel** [comment]
> This should be fixed now. if not, reopen.

Still segfaults with the latest build

**Comment by andreasb242** [comment]
I have now a System set up with Ubuntu 18.04, Wayland and a Wacom Tablet with Eraser. I don't have an eraser button, I have an eraser on the back of the Pen.

> Still segfaults with the latest build
When did you build? Now? The changes I did were merged a short time before ticket close.

Can you tell me which hardware and Software you have installed?
Is it a Wacom Tablet or something else?
Which Distribution / Version?

Can you may run it in the Debugger?
>[bt]: (0) xournalpp(+0x2c3b28) [0x556ff246bb28]

This address doesen't say really much (theoretically the second entry should get symbols, but it's mostly not working...)

Thank you.

**Comment by l0wl3vel** [comment]
```
(gdb) run
Starting program: /home/benjamin/xournalpp/build/src/xournalpp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffefc78700 (LWP 18500)]
[New Thread 0x7fffef477700 (LWP 18501)]
[New Thread 0x7fffeec3a700 (LWP 18502)]
[New Thread 0x7fffee428700 (LWP 18503)]
[New Thread 0x7fffed219700 (LWP 18504)]

(xournalpp:18496): Gdk-CRITICAL **: 20:36:57.024: gdk_device_get_state: assertion 'gdk_device_get_device_type (device) != GDK_DEVICE_TYPE_SLAVE || gdk_display_device_is_grabbed (gdk_device_get_display (device), device)' failed

** (xournalpp:18496): WARNING **: 20:36:57.027: Input was not stopped correctly!

(xournalpp:18496): GLib-GObject-CRITICAL **: 20:36:57.221: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

Thread 1 "xournalpp" received signal SIGSEGV, Segmentation fault.
0x00007ffff74f4d52 in ?? () from /usr/lib/libgdk-3.so.0
(gdb) 

```

Ran a debug build with gdb

**Comment by andreasb242** [comment]
Can you get a full backtrace in GDB?
(I think "bt" but not sure, I usually use an IDE)

**Comment by l0wl3vel** [comment]
Running an HP Envy X360 15-bq102ng with Arch 4.19.8 AMD Ryzen 5 2500U and ELAN 0732:00 Touchscreen/Pen Digitizer Combo. 
```
(gdb) run
Starting program: /home/benjamin/xournalpp/build/src/xournalpp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffefc78700 (LWP 19535)]
[New Thread 0x7fffef477700 (LWP 19536)]
[New Thread 0x7fffeec3a700 (LWP 19537)]
[New Thread 0x7fffee428700 (LWP 19538)]
[New Thread 0x7fffed219700 (LWP 19539)]

(xournalpp:19531): Gdk-CRITICAL **: 20:49:28.783: gdk_device_get_state: assertion 'gdk_device_get_device_type (device) != GDK_DEVICE_TYPE_SLAVE || gdk_display_device_is_grabbed (gdk_device_get_display (device), device)' failed

** (xournalpp:19531): WARNING **: 20:49:28.786: Input was not stopped correctly!

(xournalpp:19531): GLib-GObject-CRITICAL **: 20:49:29.466: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

Thread 1 "xournalpp" received signal SIGSEGV, Segmentation fault.
0x00007ffff74f4d52 in ?? () from /usr/lib/libgdk-3.so.0
(gdb) bt
#0  0x00007ffff74f4d52 in  () at /usr/lib/libgdk-3.so.0
#1  0x00007ffff750b53a in  () at /usr/lib/libgdk-3.so.0
#2  0x00007ffff7548eb3 in  () at /usr/lib/libgdk-3.so.0
#3  0x00007ffff2a836d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#4  0x00007ffff2a830a0 in ffi_call () at /usr/lib/libffi.so.6
#5  0x00007ffff3070f5f in  () at /usr/lib/libwayland-client.so.0
#6  0x00007ffff306d6ca in  () at /usr/lib/libwayland-client.so.0
#7  0x00007ffff306ec0c in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#8  0x00007ffff7551f75 in  () at /usr/lib/libgdk-3.so.0
#9  0x00007ffff74efce2 in gdk_display_get_event () at /usr/lib/libgdk-3.so.0
#10 0x00007ffff7551c64 in  () at /usr/lib/libgdk-3.so.0
#11 0x00007ffff70303cf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff7031f89 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff7032f62 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff77f82af in gtk_main () at /usr/lib/libgtk-3.so.0
#15 0x00005555556cdd52 in XournalMain::run(int, char**) (this=0x5555559093d0, argc=1, argv=0x7fffffffe1f8)
    at /home/benjamin/xournalpp/src/control/XournalMain.cpp:339
#16 0x00005555556885ae in main(int, char**) (argc=1, argv=0x7fffffffe1f8) at /home/benjamin/xournalpp/src/Xournalpp.cpp:32
(gdb) 
```

**Comment by andreasb242** [comment]
With this Stacktrace it looks for me like a GDK Problem. But it may also be a memory corruption from Xournal++ (really hard to find).

I get the Inputhandling from GTK Examples.
Can you install gtk3-examples, which contains the "gtk3-demo".

Start gtk3-demo, and in the left tree go to the second last entry "Touch and Drawing Tablets", and click the "Run" botton on the top left.

Now do the same what Xournal++ crashes, it it's also crashing, we talk about a GTK/GDK Issue. If not, it has something to to with Xournal++, and it gets complicated ;-)

**Comment by l0wl3vel** [comment]
Tried it the demo and it segfaults. So it is apparently an gtk3 problem.

**Comment by andreasb242** [comment]
Thank you. You may create a backtrace from the demo and Report it to GTK or to Arch.
I'll close this Ticket, as it's not a Xournal++ bug.

If you create an Upstream Ticket, can you please post the link here? As may other users are affected by this bug.

Thank you really much for your detailed post - it's nearly impossible to find bugs like this without the help from reporters!
