### ISSUE TITLE
Touchscreen not working as intended 

### ISSUE THREAD

**Issue by Hedronmx** [xournalpp/xournalpp#456]
I've seen the following issue #194 but on my machine is not working as intended.
My setup is to use my touchscreen as hand tool, and that setup currently works on default Xournal App.
What's puzzling is that when I move the screen with my fingers and then touch with my pen, the hand tool movement works. But I have to keep touching with my finger and then with my pen.

I am running Elementary OS Juno on a Lenovo Flex 5. Xournal++ version 1.0.2, built from github

**Comment by andreasb242** [comment]
Wit the GTK3 merge now Touch is handled different. This causes a lot of issues, and also some workarounds.
There needs to be a new configuration page for touch, which is not finished yet #439 .

Currently if the pen is near screen, the touch is disabled (at least it should). Is that may the reason?

**Comment by Hedronmx** [comment]
It actually works after touching with the pen, it's like the touch movement gets buffered and only after using the pen it does what it supposed to do.

It might be because on my machine both touch and pen are on the same device.

**Comment by andreasb242** [comment]
But they should be technical two different devices, can you check this e.g. in settings dialog, in input devices, in the touch section?

**Comment by Hedronmx** [comment]
They are, I have Wacom HID (pen) and Wacom HID (Touch)

**Comment by andreasb242** [comment]
I reworked the input handling, I hope this is fixed.

Currently the thouch won't be disabled on drawing, which is an issue, but really hard to solve (only with hacks).

So I close this ticket, I created one for the Touch disable #541

If the problem still exists, you can reopen the ticket.
