### ISSUE TITLE
Copy paste not working

### ISSUE THREAD

**Issue by Lolol4572** [xournalpp/xournalpp#4563]
Hi,
I use Xournalpp 1.1.2 on MacOs Catalina
Copy paste not working; It may work randomly after autosave. I cannot copy and paste selections with command C command V
What I expect: Self-explanatory

Affects versions : 1.1.2
Mac

To Reproduce
Open Xournal++ , draw stuff, and try copying and pasting. Try selecting many things and copy pasting

**Comment by Lolol4572** [comment]
E

**Comment by Lolol4572** [comment]
EDIT: It happened again after a day. I temporarily fixed it by redownloading xournal++ but it is bound to happen again.

**Comment by rolandlo** [comment]
What version did you (re)-download?

**Comment by Lolol4572** [comment]
The latest version.

**Comment by rolandlo** [comment]
@Lolol4572 Ok, then please try the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly). It should be fixed there.

**Comment by Lolol4572** [comment]
@rolandlo Works for now, I'll update in a few days (it took a day last time for it to stop working)

**Comment by Lolol4572** [comment]
@rolandlo It seemed to work, so thank you. I'll reopen it if the issue returns.
