### ISSUE TITLE
Text Tool Typing Does Not Render Anything

### ISSUE THREAD

**Issue by sid-the-sloth** [xournalpp/xournalpp#4572]
Version 1.1.3 (AppImage) installed from Releases page on github. Operating system: Debian 11 bullseye.

Steps to re-produce the bug:

- open Xournal++
- select Text Tool (with mouse)
- click on the empty page, a small box and blinking cursor appears
- type any letters: nothing gets rendered on the page.

**Comment by rolandlo** [comment]
Most likely you need to change some device setting (switch to Mouse+Keyboard Combo) in the `Input system panel` in menu `Edit > Preferences`. See [website](https://xournalpp.github.io/guide/whirlwind-tour/#input-device-setup)

**Comment by sid-the-sloth** [comment]
> Most likely you need to change some device setting (switch to Mouse+Keyboard Combo) in the `Input system panel` in menu `Edit > Preferences`. See [website](https://xournalpp.github.io/guide/whirlwind-tour/#input-device-setup)

Wow! Thank you!
My keyboard was mapped in Xournal++ as "Mouse" -- switched it to "Mouse+Keyboard Combo" and typing now works in Text Tool.
