### ISSUE TITLE
BUG: Page Icons for adding, deleting, and switching pages are missing.

### ISSUE THREAD

**Issue by Michael679089** [xournalpp/xournalpp#4591]
**Affects versions :**

- **OS:** Windows
- **Which version of libgtk do you use?**
    - with libgtk: 3.24.34
- **Version of Xournal++:**
    - Version: 1.1.3
    - Git Commit: 2dbd16d2-dirty
    - Built on Nov 27, 2022
- **Installation method:** Official Release. Latest

**Describe the bug**

The icons of the insert and delete pages aren’t working.

**To Reproduce**

1. Open Xournal.

**Expected behavior**

- The icons are still not there.

**Screenshots of Problem**

![image](https://user-images.githubusercontent.com/90962435/212605724-f6f79230-5e65-44d6-8c14-5543f9ded8ac.png)

**Additional context**

- NA

**Comment by rolandlo** [comment]
Please install the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) or apply the changes from https://github.com/xournalpp/xournalpp/pull/4544/files to `main.glade` (and `settings.glade`,  `fillOpacity.glade`) contained in `share/xournalpp/ui/` manually

**Comment by Michael679089** [comment]
> Please install the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) or apply the changes from https://github.com/xournalpp/xournalpp/pull/4544/files to `main.glade` (and `settings.glade`, `fillOpacity.glade`) contained in `share/xournalpp/ui/` manually

Hello rolandlo,

Thank you for the help, the icons are now showing again. Here's the proof that it worked.
![image](https://user-images.githubusercontent.com/90962435/212717040-a3c3935b-aa11-4f2d-a01b-1f5e9d5bc5b6.png)

I appreciate the help, sir.

Kind Regards,
Michael
