### ISSUE TITLE
Positioning of PDF docs when larger than 100 pages on touch screen causes jittering of the position

### ISSUE THREAD

**Issue by rako233** [xournalpp/xournalpp#4597]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows 11
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use : 3.24.35
 - Version of Xournal++: 1.1.3+dev
  - Installation method: installer

**Describe the bug**
I'm loading a large PDF book for annotation. And when trying to get to the next page with a finger by swiping, the documents is jittering in it's position

**To Reproduce**
1. Load a large PDF document
2. Try to get to the next page with a swipe at the end of a page

**Expected behavior**
The pdf should scroll to the next position without jitter

**Screenshots of Problem**

**Additional context**

**Comment by rolandlo** [comment]
Does the jittering also happen if you disable "GTK's built-in inertial scroll functionality" in the Touchscreen tab of menu `Edit > Preferences`?

**Comment by rako233** [comment]
This solved the problem for me!

Thx
