### ISSUE TITLE
Notes on PDF periodically appears as squares until the font is changed

### ISSUE THREAD

**Issue by Bobbelino** [xournalpp/xournalpp#4605]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use : 3.24.29
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
When annoting a PDF with text boxes, sometimes the font changes to squares. It happens when I save the .xopp file and leaving it for a while. The annotations are still there, it's just the font that changes to squares. I can change the font to something else and get a read-able font again, but it will eventually change to squares too. The problem started when I used the default font to annotate my PDF. I changed every .xopp file to "arial normal" at size 7 and it has changed my notes again. 

**To Reproduce**
1. Use a text box to annotate a PDF
2. Save the .xopp file
3. Exit Xournal++ or read another PDF with Xournal++
4. After a while, open the first PDF. The notes won't show as expected to, with every letter showing as squares.

**Expected behavior**
I expect the font I'm using to... stay as it is when I'm saving my document?

**Screenshots of Problem**
![Sans titre](https://user-images.githubusercontent.com/91352298/213557700-6a86f5b6-699f-41e3-a882-977fa8f97246.png)

**Additional context**
I would like to know a permanent fix because I'm using Xournal++ to annotate my scientific articles for my master's essay. I'm constantly "losing" my notes.

**Comment by rolandlo** [comment]
The solution is simply. Please upgrade! The latest stable version 1.1.3 and the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) should both be fine.

**Comment by Bobbelino** [comment]
Sorry for the late response, updating to the latest nightly build for windows seems to have fixed my issue! Thank you!
