### ISSUE TITLE
Clicking "Undo" does not deselect a selection

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#4609]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: Gnome 43.2, Wayland
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3 (2dbd16d2)
 - Installation method: Flatpak

**Describe the bug**
I'm not entirely sure if this is intended behaviour, but if you make a selection and then click on undo, the previous action will be undone, but the selection will remain.

**To Reproduce**
A method to reproduce what I mean is as follows:
1. Draw 2 lines
2. Delete one of the lines
3. Select the remaining line
4. While the line is selected, click undo and observe that the previous line reappears while the selection remains.

**Expected behavior**
My initial reaction was that I thought that clicking undo would remove the selection, or perhpas bring back the previous stroke, AND remove the selection.

**Screenshots of Problem**
![example](https://user-images.githubusercontent.com/7829231/213846649-6877c168-9f28-4a9d-9355-bdc9fd39c340.gif)

**Comment by Technius** [comment]
Not sure what the expected behavior should be, and there's a similar problem with redo, I guess. I think the main obstacle is taht "finalizing" a selection will push an item on to the undo/redo stack.
