### ISSUE TITLE
Standard eraser rendering artifacts at high zoom level/thick strokes

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#4610]
**Affects versions :**
 - OS: Ubuntu 22.10
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: latest master (commit 3971c1a051293f6ef45f68a80ba49b96354062dd)
 - Installation method: PPA 

**Describe the bug**
When erasing thick strokes (in particular highlighter strokes) at high zoom level (say 700%) there are lots of rendering artifacts. This only occurs with the standard eraser.

**To Reproduce**
1. Draw some strokes with the highlighter (make it as thick as possible to get even more visible results)
2. Zoom to 700%
3. Erase using the standard eraser and notice the rendering artifacts.

**Expected behavior**
No rendering artifacts

**Screenshots of Problem**

https://user-images.githubusercontent.com/40485433/213873549-5b0d7526-99d8-423d-a55a-3b66f70601e6.mp4

**Comment by bhennion** [comment]
Was this introduced by #4493?

**Comment by rolandlo** [comment]
> Was this introduced by #4493?

Yes, c0a91f02afbfb67a60f7088b4c579a796693e05d is the first bad commit.
