### ISSUE TITLE
Installing themes on Windows isn't possible due to privilege restrictions.

### ISSUE THREAD

**Issue by Luminaire13** [xournalpp/xournalpp#4619]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows 10 Version 1909
 - GTK Version 3.24.35
 - Version of Xournal++: 1.1.3+dev, bac5ca039-dirty
 - Installation method: official release

**Describe the bug**
Trying to set Xournal to have a dark theme. However changing the relevant setting requires creating/editing access to Program Files directory on Windows, which is [prohibited even for administrators](https://answers.microsoft.com/en-us/windows/forum/all/have-administrative-rights-but-cant-save-a-file-to/30e93b75-ea54-407f-a122-80a56259b390). So it's impossible for me to use a dark theme on Windows.

**To Reproduce**

Follow steps here:
[Xournal Wiki](https://xournalpp.readthedocs.io/en/latest/Old%20Wiki/Frequently-Asked-Questions-&-Problem-Solving/)
_"On Windows, the default Adwaita theme that is distributed with the official Xournal++ Windows installer comes with dark theme enabled. You can enable it by creating a file called etc\gtk-3.0\settings.ini inside of the Xournal++ installation folder, with the following contents:

[Settings]
gtk-application-prefer-dark-theme=1"_

**Expected behavior**
Expected to be able to create/modify the file in the C:\Program Files\Xournal++ directories, and then open Xournal++ and select a dark theme, and see a dark theme.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/16496833/214712668-c2effb19-1c84-467f-9ec6-763588f3c446.png)
As you can see, windows does not allow me to create a file here, only folders. Monkeying with file privileges has not been a working workaround so far.

**Additional context**
None

**Comment by rolandlo** [comment]
I think this info is outdated. Doesn't enabling "Use dark theme" in the View tab of menu `Edit > Preferences` inside Xournal++ already do the job here?
Otherwise you might consider trying the portable installation.

**Comment by rolandlo** [comment]
Closing since the issue seems to be fixed already.
