### ISSUE TITLE
Add page numbers to the page overview sidebar

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#4624]
**Is your feature request related to a problem? Please describe.**
It would be nice to have page numbers in the page overview sidebar

**Describe the solution you'd like**
Simple page numbers where the red circles are: 

![image](https://user-images.githubusercontent.com/7829231/214778204-ef48181e-2bd3-4b0b-9c4a-77d19b460600.png)

**Describe alternatives you've considered**
There could be toggleable setting to allow users who want a cleaner look to diasable numbers in the page overview sidebar.

**Additional context**
This is related to #1053

**Comment by CruzeBlade** [comment]
Hi K4LCIFER, 

I had a look at your feature request and tried to implement it. Here is what I have come up with so far. 
![Bildschirmfoto vom 2023-02-11 13-38-15](https://user-images.githubusercontent.com/37212628/218258622-9d0baba5-6f89-47ad-864f-a04a0f3ee8d9.png)

After playing around a little bit I think that it's best to add the page numbers below the previews. This is more standard and makes it easier to see which page they correspond to when there are multiple pages in a row. 

Is that how you imagined it?

**Comment by K4LCIFER** [comment]
This is awesome! One note: I think that it would be more natural if the page numbering started at 1.

**Comment by K4LCIFER** [comment]
Aother version that I have thought of is something like this:
![v1](https://user-images.githubusercontent.com/7829231/218292864-efcaa4ec-4235-4f61-895c-05c9d01c689a.png)

**Comment by K4LCIFER** [comment]
Or perhaps even this: 
![v2](https://user-images.githubusercontent.com/7829231/218293045-da573e0a-c729-447d-a493-c6c9433cb4af.png)

**Comment by K4LCIFER** [comment]
These two examples make it much more explicit what page that the numbers are referring to.

**Comment by CruzeBlade** [comment]
Hi, please excuse the long delay, but the last weeks were quite busy. I have now implemented all three styles and made them selectable through the preferences. You are totally right that the page indexes should start with one. Just an old programmers' habit to start at zero xD. I have changed it now. 

I will try to submit a pull request, let’s see what the project maintainers think of it. As it is the first time I'm doing this, I cannot guess how long this will take. I will keep you updated.
