### ISSUE TITLE
Mouse cursor as cursor icon for pen

### ISSUE THREAD

**Issue by kauesena** [xournalpp/xournalpp#4626]
It would be nice also to be able to select the mouse cursor as pen cursor icon because I find it easier to track than the dot but I do not really like the down-pointing pen.

**Comment by rolandlo** [comment]
At least in the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) you can select the mouse cursor as pen in the View tab (mouse cursor) of menu `Edit > Preferences`
