### ISSUE TITLE
macOS version of Xournal should have global menu

### ISSUE THREAD

**Issue by M-Rick** [xournalpp/xournalpp#4633]
**Is your feature request related to a problem? Please describe.**
Xournal is a nice quality application, but unfortunately, it doesn't respect macOS guidelines and doesn't provide a global menu like it should have.

It is a GTK based application, but GNUCash, Inkscape or Gimp which are GTK based too, all have a global menu under macOS.

![Capture d’écran 2023-02-04 à 15 14 14](https://user-images.githubusercontent.com/2520948/216782987-6d8a4013-a3a6-4479-bce5-66bfe431b189.png)

**Comment by rolandlo** [comment]
I agree that integration into the global menu would be nice to have. We had this via Gtk-Mac-Integration, but it's deprecated. According to [GTK wiki](https://wiki.gnome.org/Projects/GTK/OSX/Integration):

> Older Gtk applications that aren't based around GApplication can be adapted to use the macOS menu bar and to integrate with the Dock using GtkOSXApplication. The Gtk API that GtkOSXApplication uses is deprecated in Gtk3 and has been removed from Gtk4. Since macOS integration is available directly in Gtk using GApplication GtkOSXApplication will not be updated for the new menu API and is deprecated. Application maintainers are strongly encouraged to redesign their programs around GApplication, particularly before migrating to Gtk4. 

> Naming Note: Gtk-mac-integration reflects an old Carbon implementation that has been removed as Apple has removed most of the public Carbon API. It was called ige-mac-integration before being moved to Gnome from Github, and you will find older repositories on Github still using that name.

**Comment by bhennion** [comment]
Could #4372 be doing the trick?

**Comment by bhennion** [comment]
This is fixed in #4372.
See this screenshot (VM, Catalina)
![Screenshot_20230207_141440](https://user-images.githubusercontent.com/17818041/217254922-e4eeb7eb-35dc-4e1d-8ce0-050e50861cd3.png)

**Comment by M-Rick** [comment]
Thank you that's awesome. This little piece of application is so great and simple.
