### ISSUE TITLE
"Big cursor for pen" shows up as normal mouse icon

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#464]
Selecting "big cursor for pen" from Preferences/view shows a mouse icon where the pen is. Preferable would be a pen icon / cursor.

**Comment by andreasb242** [comment]
No, it's a combination of the pointer and the pen Point.
Please check: There is a colored icon (the normal Pen Cursor) combined with a standard Cursor.

I cannot create a Screenshot with cursor (yes, I can, but it contains my system cursor).
Please recheck. I don't see there anything to change at the moment.

**Comment by andreasb242** [comment]
@markwmuller Do you have a High DPI Screen? Please change the Color of the Pen, to check, black is bad visible, thats true.

**Comment by luco5826** [comment]
Hi @andreasb242  ! I think he meant somwthing like this!
(This is just a montage)
![window](https://user-images.githubusercontent.com/38291180/49601249-93c61900-f985-11e8-9abb-0c30759bcdd6.png)

**Comment by andreasb242** [comment]
I also need to take a Photo

![grafik](https://user-images.githubusercontent.com/822958/49603647-25388980-f98c-11e8-9ce0-703c5dee12a6.png)

Do you see the red dot?

**Comment by andreasb242** [comment]
@markwmuller Please explain why a Pen Cursor would be better?
Even gimp uses such a standard cursor, OK gimp adds the pen icon at the bottom right, but the Main cursor is still looking like the one in Xournal++.

**Comment by luco5826** [comment]
I modified my version in order to look like this
![Uploading photo_2018-12-06_19-29-23.jpg…]()
What do you think guys? I think that for the pen tool, only in Big Cursor mode, this could be nicer!

**Comment by andreasb242** [comment]
I personally have the big cursor only enabled on my PC, not on a Tablet, because if the point is controlled with the mouse, it's really hard to seed. But in this case I like a normal looking cursor, which makes sense for me.

When I write with the Tablet, I use the small cursor, because I can control the point really precise with my Pen.

So I currently don't understand why @markwmuller would change this.


@luco5826 I see you are now really a Xournal++ developper :+1:  :-)

**Comment by markwmuller** [comment]
Usually, the mouse icon conveys information on what you're doing: "normal" mouse pointer is for clicking: selecting an area, activating a box, etc. Hand icon is for dragging. "arrow-stop" pointer for resizing windows. 
Thus, having a pointer that looks like a pen signals that what I'm doing is writing. The mock-up of @luco5826 is exactly the kind of thing I'm thinking of. 
@andreasb242 I use the tablet during lectures -- I'd like it to be very visible on the projector, where the "mouse" is, since the audience cannot see my pen. It's also good when pointing at things, without writing (e.g. going back to something I had written earlier). For the guy writing, it doesn't really matter (I can see the tip of the pen), the main benefit is for the audience.

**Comment by andreasb242** [comment]
Hmm Ok.

@luco5826 Can you create a Pull request?
Can you leave the code for the old cursor comment out, so if we may need to add an option for both, we can get them easy?
Thank You!

**Comment by andreasb242** [comment]
Is merged now, thank you @luco5826 

@luco5826 If you write "fixes #ticketID" somewhere in the commit, the Ticket will automatically be closed and liked to the Pull Request.

**Comment by 2L40K** [comment]
This cursor is really, really primitive and ugly.
Can it be made, so it uses external .CUR file, so anybody can change it?
