### ISSUE TITLE
Missing icons in the Sidebar

### ISSUE THREAD

**Issue by manueljrcsm** [xournalpp/xournalpp#4640]
**Affects versions :**
 - OS: Confirmed on Mac and Windows
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.3
 - Installation method: official installer.

**Describe the bug**
When opening Xournal++, there are a couple of missing icons in the Sidebar. Namely, window-close button on the upper-right corner of the sidebar and the 4 buttons on the bottom (go-up, go-down, edit-copy and edit-delete). Go-up and go-down icons are also missing from the Search bar (same icons).

**To Reproduce**
1. Open Xournal on Windows or Mac.
2. Open the Sidebar if hidden.
3. Icons are missing.

**Expected behavior**
The icons should be there.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/50916078/217508033-225aaa76-25f3-48b9-92bd-361ff6161e4f.png)

**Additional context**
I think I found the culprit. The [main.glade](https://github.com/xournalpp/xournalpp/blob/master/ui/main.glade) file uses two types of icons: original icons drawn for Xournal++, which are included in the ui folder of this repository; and Gtk icons from the Adwaita theme, that come with the Gtk 3 dependency. It is these second type of icons that are missing. Namely, the Adwaita icon theme that comes with the Gtk 3 dependency does not implement full color versions of the icons. It only implements symbolic versions, which are monochrome and named accordingly. As such, in the [main.glade](https://github.com/xournalpp/xournalpp/blob/master/ui/main.glade) file you can find lines such as 
![image](https://user-images.githubusercontent.com/50916078/217509999-bf057a30-d5db-411c-948e-5e0f14c70d07.png)
for the "close Sidebar button" (upper-right corner of the sidebar in the screenshot above). But in the Adwaita icon folder, there is only a icon named `window-close-symbolic.svg`. The same thing happens with the `go-down`, `go-up`, `edit-copy` and `edit-delete`, which only exist in the Adwaita icon theme in their symbolic versions. Notably, the search lens icon the search bar is appropriately named `edit-find-symbolic` and displays correctly. Also, the fallback icon theme `hicolor` no longer comes with the scalable images in the Gtk3 dependency that is bundled with Xournal++.

**What could be a solution:**
1.  To replace `window-close` by `window-close-symbolic` in the [main.glade](https://github.com/xournalpp/xournalpp/blob/master/ui/main.glade) and likewise, for `go-down`, `go-up`, `edit-copy` and `edit-delete`. These are the only missing icons that I noticed, but there could be more. Perhaps there is an error log somewhere in the dev version that is listing all the missing icons from the Adwaita theme. Here is what it looks like if you manually rename the symbolic .svg files into the non-symbolic counterparts:
![image](https://user-images.githubusercontent.com/50916078/217514154-9aa4e7ad-65cb-4b7f-945d-71c65f214c64.png)
2. However, the monochromatic icons don't look particularly nice with the rest of the Xournal++ icons which are more colorful. And perhaps more importantly, I don't know if this solution would be compatible with **dark-mode**. Because the Adwaita icon theme does not come with dark color versions of the icons as one can check in the installation folder (\Xournal++\share\icons\Adwaita\). Unless there is some kind of automatic Gtk conversion of icons, the default symbolic icons would be invisible on the dark mode of Xournal++.
![image](https://user-images.githubusercontent.com/50916078/217514312-c53f072a-0001-41be-bf45-4df9a7b8808a.png)
3. Adding original Xournal++ colored versions of these icons would be a permanent solution , but I am not a graphical designer and it is not my call to make.
4. I know that some part of this is Gtk' and Adwaita's fault and not really Xournal++, but the way it looks right now affects the usability.

**Comment by bhennion** [comment]
This is a duplicate of #3945, which has been fixed upstream -- see https://gitlab.gnome.org/GNOME/gtk/-/commit/5a0ffbbb4568e39bdf26006e1bf18c1c1d0d597a.
This commit is included in GTK 3.24.34, are you sure this is the version your using? Wat's the output of
```
$ xournalpp --version
```
Also, how did you install the app (flatpack, reps, ...)?

**Comment by rolandlo** [comment]
@bhennion It's only in combination with https://github.com/xournalpp/xournalpp/pull/4544 that fixed the problem. 
@manueljrcsm You can upgrade to version 1.1.3+dev to see the icons.

**Comment by bhennion** [comment]
> @bhennion It's only in combination with #4544 that fixed the problem.

Thanks for the correction! It makes sense.

**Comment by manueljrcsm** [comment]
> This is a duplicate of #3945, which has been fixed upstream -- see https://gitlab.gnome.org/GNOME/gtk/-/commit/5a0ffbbb4568e39bdf26006e1bf18c1c1d0d597a. This commit is included in GTK 3.24.34, are you sure this is the version you're using? What's the output of
> 
> ```
> $ xournalpp --version
> ```
> 
> Also, how did you install the app (flatpack, reps, ...)?

Yes, I had 1.1.3 with GTK 3.24.34. All I had done was install the Windows installer from [](https://xournalpp.github.io/installation/windows/) and asked a friend to do the same on Mac.

> @bhennion It's only in combination with #4544 that fixed the problem. @manueljrcsm You can upgrade to version 1.1.3+dev to see the icons.

Upgrading to 1.1.3+dev fixed the issue. I can also confirm that it is working as indended in the dark-mode. Thanks for help guys!
