### ISSUE TITLE
Need a SPACER for toolbar customizing

### ISSUE THREAD

**Issue by Cleansweep7** [xournalpp/xournalpp#4644]
**Is your feature request related to a problem? Please describe.**

I found the default toolbar configurations "Portrait" and "Xournal++" do have some tools on the right hand of their bottom toolbars, which looks good. I checked the file "toolbar.ini" and found there might be a SPACER in the middle. But when I try to customize my toolbar, all I can do is easily remove the invisible SPACER but cannot add it again from the tool box, because there wasn't one. (As for the toolbox, there are tools and colors that not on the toolbar, and a SEPARATOR, but not a SPACER). Also, I cannot find a ini file to customize my tool bar with codes.(My system is windows10, Xournal++ v1.1.3)

**Describe the solution you'd like**
Help me find a way to add a SPACER to my toolbar.

**Describe alternatives you've considered**

**Additional context**

**Comment by rolandlo** [comment]
You should find the file `toolbar.ini` in the `ui` subfolder of the "Shared resources folder" (for default toolbars) and in the "config folder" (for user defined/copied toolbars). See [file locations](https://xournalpp.github.io/guide/file-locations/)

**Comment by rolandlo** [comment]
I can confirm that the SPACER is missing for drag&drop when it is not on any toolbar. That should be fixed.

**Comment by vladQll** [comment]
![image](https://user-images.githubusercontent.com/28522011/218950885-ab34da78-b480-498c-b90e-d63dd80c0028.png)
yo tengo configurado asi
