### ISSUE TITLE
LaTeX insertion pop-up window cut off

### ISSUE THREAD

**Issue by jasper1378** [xournalpp/xournalpp#4646]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: X11, i3-wm
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3
 - Installation method: Official Arch Linux repository via pacman

**Describe the bug**
When inserting very long LaTeX text (vertical space / number of lines), the LaTeX preview will expand and the text insertion box at the bottom of the `Insert Latex` pop-up window will eventually be moved off-screen, making editing the LaTeX text very difficult.

**To Reproduce**
1. Tools > Add/Edit TeX
2. Create long LaTeX snippet (many lines).

**Expected behavior**
LaTeX preview should shrink, or allow scrolling. Text insertion box should not move off-screen.

**Screenshots of Problem**
Video of the problem: https://jasper.onthewifi.com/xournalpp.mkv

**Additional context**
The LaTeX preview will also expand past the sides of the screen in the horizontal direction if typing very long lines, however this is less of a problem due to the fact that it won't interfere with the text insertion box.

**Comment by rolandlo** [comment]
Would you please try out the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? The LaTeX tool has gotten lot of care therein (in particular it has a resizable preview).

**Comment by jasper1378** [comment]
I'll give it a try. Thanks for the help!

**Comment by jasper1378** [comment]
Just tried out the nightly build. The LaTeX tool is so much better! Thank you so much!
