### ISSUE TITLE
Stroke recognizer line thickness (diagonal lines) issue

### ISSUE THREAD

**Issue by NNoah18** [xournalpp/xournalpp#4650]
**Affects versions :**
 - OS: [Windows 11]
 - Which version of libgtk do you use 
       3.24.34
 - Version of Xournal++: [e.g. 1.1.3, 2bdb16d2-dirty, specific branch] 
 - Installation method: [official release]

**Describe the bug**
When using the stroke recognizer and drawing a diagonal line, it will change the stroke thickness, however this issue does not occur when drawing horizontal or vertical lines.

**To Reproduce**
1. click the pen tool and then select a thickness of thick ( all or most thickness seem to have this issue)
2. turn on the stroke recognizer
3. draw a diagonal line

**Expected behavior**
I expect a diagonal line to be draw with the same thickness that the I would get when normally drawing and/or drawing horizontal and vertical lines, that are generated with the stroke recognizer.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/4433959/218291702-b4cadf01-b4a2-496e-b540-4cead8d1bf51.png)
Those where all drawing using the same thickness option.

**Comment by NNoah18** [comment]
I also just noticed that this issue does not happen when I use my mouse, it only seems to happen when I use my pen/stylus. For reference I use the windows surface slim pen 2, and I write on the windows surface laptop studio.

**Comment by shschulze** [comment]
Hi Noha, 
is it possible, that you are ending your diagonal strokes with less pressure? (the stroke recognizer is pressure sensitive)

**Comment by NNoah18** [comment]
No, however, I downloaded the nightly version and it seems to be fixed in that version.
