### ISSUE TITLE
Merging layers does not work

### ISSUE THREAD

**Issue by matenestor** [xournalpp/xournalpp#4654]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: KDE Plasma, X11
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3
 - Installation method: pacman -S xournalpp

**Describe the bug**
I have two layers with different notes inside them and I need to merge them. I saw PR #3204 and tried what the author described. However, there is neither a context menu on RMB in the layers preview, nor option "Merge layer down" in the "Journal" menu tab. And Ctrl+m is also doing nothing.

**To Reproduce**
1. Create second layer
2. Try to merge it with the first layer

**Expected behavior**
After merge, there should be only one layer with all content from the two previous layers.

**Screenshots of Problem**
No option for merging. Clicking on the layer thumbnail with RMB does not show context menu.

![2023-02-16-102052_4480x1440_scrot](https://user-images.githubusercontent.com/44382264/219322828-c46b9fa9-18be-40f4-94aa-4be5a1ea9a49.png)

**Comment by matenestor** [comment]
Sorry, I accidentally pressed enter and the issue got submitted earlier... I am writing the description now

**Comment by rolandlo** [comment]
I think you need the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) for this feature to work.

**Comment by matenestor** [comment]
It does not seem to be included in the nightly build changelog. But anyway, the PR had been merged in Feb 22, 2022 and there have been two versions since -- 1.1.2 released in Oct 17, 2022 and 1.1.3. released in Nov 27, 2022. So the feature was not included either, even though it is in the master branch?

**Comment by rolandlo** [comment]
1.1.1. and 1.1.2 and 1.1.3 were bugfix releases building on the features of 1.1.0. New features since 1.1.0 were merged into master (not into the release-1.1 branch) and are available in the nightly build. What is currently 1.1.3+dev will become 1.2.0 when released.
