### ISSUE TITLE
Wrong font size when opening "old" files or how do I compress xopp files?

### ISSUE THREAD

**Issue by isaacalbert** [xournalpp/xournalpp#4664]
Hello all,
first of all I would like to thank the developers. I can't imagine my work as a teacher without this great tool! 
Now about my problem:
So far I use Kubuntu 18.04 with Xournal++ 1.0.20. The installation was difficult, then somehow it worked and since then I left the system like this. Now we have new boards (Promethean) and I want to use the math tools. So I'm just switching to Kubuntu 22.04.. I have tried version 1.1.3 and 1.1.3+dev and everything works fine with three screens two of which are touch screen.
The only problem is the font size: when I open the old files with the newest versions, the font size is changed (too small). If I save in the new version with wrong font size and open with the old version, the font is ok. Is it possible to force a specific font size when opening? The default values for the font only apply to a new text field and not to the old text from an old file. Or does this have something to do with system wide font settings?

Old computer: Kubuntu 18.04.6 with Xournal++ 1.0.20 (from 17 Dec 2020), libgtk 3.22.30
new machine: Kubuntu 22.04.2 with Xournal++ 1.1.3 and 1.1.3+dev, libgtk 3.24.33

Maybe someone has an idea? I need the new version with math tools in the next weeks.

Update: As I write this, it occurred to me to unzip the old files. In them, the font size is indeed too small (10). If I change that to 20 in the XML file and then compress it, the file will no longer open with Xournal: XML Parser Error Error on line 1 char 1: Document must begin with an element (e.g. <book>). I would also go the distance and manually set all my current files to the correct font size. How do I compress the xopp files correctly?

Thanks a lot.
Jo

**Comment by rolandlo** [comment]
You can use the `Migrate Font Sizes` plugin (see menu `Plugin`) to fix the font sizes. From that plugin: 
> In Xournal++ versions 1.0.x and earlier version of 1.1.0+dev font sizes were relative 
to the display DPI setting from the preferences (slider in the zoom panel). Only
with the standard setting of 72 DPI the fonts were saved with their true size. With a 
20 pt Sans Regular font, two subsequent lines of text should be separated exactly 
by the distance between two subsequent lines of the ruled paper background. 
With 144 DPI (i.e. the doubled value) you however needed a font size of 10 pt
(the half value) for that purpose. This was confusing. 

> We have changed that so that 20 pt Sans Regular will always fit to the ruled paper 
background lines regardless of the display DPI setting.

> If you have created documents with a different display DPI setting than 72, you will 
now see font sizes that are of different size then they looked like when you created 
them. This plugin allows to correct that in the current document for once and 
forever. For that purpose we need to scale all font sizes of the document with the 
factor f = OldDPI / 72, where OldDPI is the display DPI value with which the 
document was created.

By the way, what display Dpi have you set in the zoom tab of menu `Edit > Preferences`?

**Comment by isaacalbert** [comment]
Hello Roland,

thank you for your answer. That sounds very good. 
The DPI value is 125 for me.
I tried the plugin right away, but it shows me that:

![grafik](https://user-images.githubusercontent.com/87916000/220122833-8a4fef2a-be25-41f4-90a2-1124efd76a45.png)

Do I have to install something else there (Lua)?

Thanks a lot!
Jo

**Comment by rolandlo** [comment]
If you want to use the GUI ("Show font size migration dialog") for that plugin, you need `lua-lgi` installed.
```term
sudo apt install lua-lgi
```
should do on your system.
Lua itself is clearly installed on your system and you can use "Migrate font sizes with factor displayDpi / 72" without having `lua-lgi` installed. In your case that would scale the text by the factor 125/72 = 1.736

**Comment by isaacalbert** [comment]
It works!
At first it looked like nothing was happening because the pages didn't update.
Thanks a lot!

My students will be happy tomorrow!

With best regards
Jo

**Comment by isaacalbert** [comment]
closed
