### ISSUE TITLE
Incorrect bounding box for strokes with varying pressure

### ISSUE THREAD

**Issue by hrdl-github** [xournalpp/xournalpp#4668]
**Affects versions :**
 - OS: GNU/Linux, probably others as well
 - Version of Xournal++: https://github.com/xournalpp/xournalpp/commit/517ce512a709d2951e84d7427a7d5399959270f2

**Describe the bug**
Rendering issue in connection to pressure-sensitive strokes. Affects eraser, undo, and redo and possibly other actions.

**To Reproduce**
1. Activate pressure sensitivity and set pressure multiplier to 4, as the effect is less visible at 1.
2. In my test: set the brush size to large and the eraser size to small. Set zoom to maximum.
3. Create a single "stroke" using the stylus, interleave it with button presses to activate the stroke-based eraser without lifting the stylus from the tablet. Stop until a stroke that causes artefacts was deleted.

**Expected behavior**
No artefacts when handling above stroke.

**Screenshots of Problem**
Erasure: https://user-images.githubusercontent.com/31923882/220463326-4ecf8ef7-f472-4a20-b3fa-716ac7b1e9f2.mp4

Redo / undo: https://user-images.githubusercontent.com/31923882/220464807-81d18891-8d19-4b92-982b-92410bac3a45.mp4

Stroke: [bug_stroke.zip](https://github.com/xournalpp/xournalpp/files/10798009/bug_stroke.zip)

**Additional context**
Originally mentioned here: https://github.com/xournalpp/xournalpp/pull/4659#issuecomment-1438169890

**Comment by bhennion** [comment]
Isn't something like that doing the trick?
```
--- a/src/core/model/Stroke.cpp
+++ b/src/core/model/Stroke.cpp
@@ -399,7 +399,10 @@ void Stroke::setLastPressure(double pressure) {
 void Stroke::setSecondToLastPressure(double pressure) {
     auto const pointCount = this->getPointCount();
     if (pointCount >= 2) {
-        this->points[pointCount - 2].z = pressure;
+        Point& p = this->points[pointCount - 2];
+        p.z = pressure;
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, p, 0.5 * pressure);
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, this->points.back(), 0.5 * pressure);
     }
 }
 ```

**Comment by bhennion** [comment]
Ah yes of course, you're right! The problem lies in using `updateBounds` wrongly in a`addPoint`.
