### ISSUE TITLE
Tool to trigger plugin

### ISSUE THREAD

**Issue by Celleforst** [xournalpp/xournalpp#4669]
Hello guys,
I was trying to adapt the screenshot plugin for my workflow but in order to really make it work I would like to trigger the plugin from my toolbar. Thus I was wondering if you could add a tool for the toolbar to trigger a chosen plugin. You could even take this idea further and create a tool to run a custom script or something like that. I find it quite frustrating that the plugin implementation is so hidden and difficult to access. I think that this tool to trigger plugins would make it much more attractive to use plugins.
Besides that it would also be nice if users could create custom tools in a similar fashion to plugins. I don't know if you are already planing to implement this but the toolbar customizer kind of already suggests it with the heading "Default Tools". It would be wonderful if you could implement some method to add more tools to this list.

Cheers.

**Comment by rolandlo** [comment]
That's one thing that I have also missed badly. I have created a Pull request #4671 which adds this feature. Thanks for the inspiration. :-)
