### ISSUE TITLE
Xournalpp - no error message when saving file with no write permission

### ISSUE THREAD

**Issue by Davide-sd** [xournalpp/xournalpp#4675]
**Affects versions :**
 - OS: Ubuntu 22.04
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3
 - Installation method: Flatpak

**Describe the bug and Steps To Reproduce**

I have two OS installed on my system: Ubuntu 22.04 and Windows 11. Sometimes I takes note from Windows 11 and I save them in the main NTFS partition.

Then, I might need to modify the files when I'm running Ubuntu. With Xournal++ I open the files from the NTFS partition and edit them. When I click the save button, no error message is shown, so I'm confident that the edits have been saved. Then I reopen the file just to discover that my edits were not saved. :|

So I opened the folder in the NTFS partition with my file manager in Ubuntu: turns out that I don't have write permission.

Then, I did another test: from Ubuntu, open Xournal++ and creates a new note. Save it under the same folder in the NTFS partition. This time I get an error message:

![Screenshot_20230224_112552](https://user-images.githubusercontent.com/9921777/221156461-9445ad40-48f6-470b-9bfd-7d742550aa2d.png)

I click OK and after a few seconds another error messages pops up:

![Screenshot_20230224_112621](https://user-images.githubusercontent.com/9921777/221156598-959dce34-bc0c-422c-bb05-2feb2d295dc8.png)

The last error message pops up rather frequently.

**Expected behavior**

Once I open an existing file, it would be really nice if Xournal++ would notify me right away that I don't have write permission. Knowing that, I wouldn't spend time editing the file...

Also, I found the error message rather cryptic: in particular, the _"Error operning file"_ part.... I'm trying to save the file. Maybe a _"Don't have write permission"_ would be better...

**Comment by jhilmer** [comment]
There is a bug in the current version, where we don't shows a error message if we can't backup the current file, before saving. We then just skip saving :-(

I will shortly open PR with a solution to this issue.
