### ISSUE TITLE
File extension xopp vs xoj

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#469]
What was the motivation to introduce the new extension? How is the aimed handling of xoj?

**Comment by andreasb242** [comment]
If there is a new Attribute or e.g. the new Backgrounds are stored, Xournal will not open the file anymore.
Therefore .xoj is fully backward compatible, and can be opened by Xournal, .xopp is not, you may can read it with Xournal, may not.
Xournal does e.g. not accept a new attribute, or a new value.

Full description:
https://github.com/xournalpp/xournalpp#fileformat
