### ISSUE TITLE
Select Linear Text Hightlighter with more opacity

### ISSUE THREAD

**Issue by zodiecko** [xournalpp/xournalpp#4691]
**Is your feature request related to a problem? Please describe.**
When I use the Hightlighter the color is stronger than the Select Linear Text Hightlighter in the pdf which is very weak.
Windows 11. xournalpp-1.1.3+dev-nightly.20230302-windows

**Describe the solution you'd like**
a little more opacity

**Additional context**
![Captura de tela 2023-03-02 191444](https://user-images.githubusercontent.com/19830572/222600328-a7b22ad1-7f2b-4c53-bcae-86c707c46db2.png)

**Comment by octaskin** [comment]
I was trying to figure out how to redact entries from a bank statement. I was able to highlight with black but without opacity setting it wasn't useful. 

Currently I draw some thick black lines and copy paste them but when this is available the functionality would be much bettter. 

If anyone else has a better idea to redact, or the opacity of the highlight via selection of text was configurable already, I'm all ears :eyes:

**Comment by EasperOne** [comment]
I got the same problem here. Looks like this hasn't been fixed yet.
