### ISSUE TITLE
Crash on TextTool

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#470]
Hi! I don't know if it's only me but I select the TextTool from the toolbar and add a Text box to my document; as I type Xournal++ crashes.
Do you experience the same issue?

**Comment by andreasb242** [comment]
No, but do you have an exception log? it should be in your home, .xournalpp

is it reproducible on your system?

**Comment by luco5826** [comment]
Yes, every time I add a Text box, right in the moment when I press a letter on my keyboard, it crashes. 
I would wait to create the PR about the Pen cursor in order to be sure that my changes didn't cause it, even if I changed only one file in a small portion

[errorlog.20181206-210729.log](https://github.com/xournalpp/xournalpp/files/2654677/errorlog.20181206-210729.log)

**Comment by andreasb242** [comment]
You may set a breakpoint in TextEditor::onKeyPressEvent and then debug. I don't think this has something to do with the cursor... But yes, you can never be sure, It's C++ ;-)

**Comment by luco5826** [comment]
I checked it before! 
I think that is 
`gtk_im_context_filter_keypress(this->imContext, event)` the point giving troubles

**Comment by luco5826** [comment]
Hi @andreasb242 ! I found a workaround, and as I thought, the problem is not in Xournal++.
Googling around I found this very similar issue
[](url)https://github.com/p-e-w/finalterm/issues/364
and his fix worked for me!
As my debugging process found out, the problem is in `gtk_im_context_filter_keypress` but I don't know why this happens, neither how to permanently fix it!

**Comment by andreasb242** [comment]
unset GTK_IM_MODULE fixes this issue, as a workaround.

What is then your value before you unset it?

mine is ibus.

$ echo $GTK_IM_MODULE
ibus

**Comment by luco5826** [comment]
Mine is `xim` , but I sincerely don't know what that means, I'm on Debian Buster (testing) with 4.18.0-3-amd64

**Comment by luco5826** [comment]
And now if I launch Xournal++ with
`GTK_IM_MODULE=ibus ./src/xournalpp ` it works!

**Comment by andreasb242** [comment]
And if I set it to xim it crashes!

`GTK_IM_MODULE=xim xournalpp`

So this is not solved yet. If we cannot fix it, we should at least show an error to the user, that we don't support this configuration!

**Comment by andreasb242** [comment]
https://unix.stackexchange.com/questions/260601/understanding-setting-up-different-input-methods

>Now what about XIM? XIM is a pretty obsolete input method protocol which both ibus and fcitx implement for legacy support reasons only. There is no real reason why you would want to use XIM nowadays over any of those two.

Hopefully this is true, so my Idea would be to check for xim, and set the environment var BEFORE the gtk_init to ibus.
Should be not more than a few lines of code, and add a g_warning so the user see there is an issue.

What do you think? You may do this?
