### ISSUE TITLE
Png-export for documents with PDF background bug

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#4704]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: Gnome (Wayland)
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.3+dev
 - Installation method: built from source

**Describe the bug**
When exporting documents with PDF-background to png parts of the background are transparent.
Bisecting showed that d9424c6bb686fa1f7fd0f693a99573e729203c52 is the bad commit.

**To Reproduce**
1. Open a PDF
2. Export as .., choose png format, export
3. Observe the transparent background in the exported png(s)

**Expected behavior**
Not transparent background

**Screenshots of Problem**
Use dark theme to see the difference on one glance.
Good:
![Kreis_U2e-1](https://user-images.githubusercontent.com/40485433/223834458-a20dc4b1-6ecf-4b1e-ba7c-39804b8764dd.png)

Bad:
![Kreis_U2e-1](https://user-images.githubusercontent.com/40485433/223834575-c649a1bc-f9b3-4317-af21-2c4f707d7ecd.png)

**Comment by bhennion** [comment]
I'm guessing it's
https://github.com/xournalpp/xournalpp/blob/b2d11d9717ebe51a0a9dcf991c096ec08397950d/src/core/control/jobs/ImageExport.cpp#L180
It should be `popplerPage->render(cr)` when exporting to a raster format (for us only PNG), but not when exporting to SVG.
A simple test here should do the trick.
