### ISSUE TITLE
Can't use the four Gaomon graphic tablet buttons

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#4730]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Fedora
 - Gnome-Wayland
 - Which version of libgtk: 3.22.30
 - Version of Xournal++: 1.1.3+dev (be01b216)
 - Installation method: appimage from official github repo

**Describe the bug**
I can't use the four Gaomon buttons:
![image](https://user-images.githubusercontent.com/20903913/225005950-98917511-8747-4b94-8701-97b279c77067.png)
The buttons in the pen, instead, work.

**To Reproduce**
1. Open Xournalpp
2. Try to use these buttons
3. Nothing happens.

**Expected behavior**
Should do something or be configurable.

**Comment by rolandlo** [comment]
You could map those buttons to keyboard shortcuts that activate certain tools or [plugins](https://xournalpp.github.io/guide/plugins/plugins/).

**Comment by All3xJ** [comment]
> You could map those buttons to keyboard shortcuts that activate certain tools or [plugins](https://xournalpp.github.io/guide/plugins/plugins/).

you are right, I used this tool: https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md
