### ISSUE TITLE
Emoji is very small rendered

### ISSUE THREAD

**Issue by gitalm** [xournalpp/xournalpp#4731]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux 22.04
 -  X11
 - Which version of libgtk do you use
     - 3.24.34
 - Version of Xournal++: 1.1.1
 - Installation method: Snap

**Describe the bug**
When i type text this is normally rendered, But when i include Emojis, this are very tiny (1) and hard to ZoomIn

**To Reproduce**
1. Copy with Ctrl+V an EMoji Character (Font size ist indicated by **Test**)
2. Increase the size
3. Large image is rendered by clicking somewhere else (lost focus)

**Expected behavior**
EMojis characters should be rendered in the same font size

**Screenshots of Problem**

![image](https://user-images.githubusercontent.com/7422149/225273154-ae16fa24-016b-45e4-b05b-7757f107c326.png)

**Comment by rolandlo** [comment]
Can you please try the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? It would be simplest to use the AppImage to try it out.

**Comment by gitalm** [comment]
Dear @rolandlo ,

thanks for the tip. This is a strange behaviour of the snap package. The AppImage is working as expected.
I als tried the Snap Edge Version 1.1.3 but there the same occured.

Best wishes Johannes

**Comment by rolandlo** [comment]
@gitalm Is it really related to the Snap version or is it the same for the AppImage of version 1.1.3? Note that there has been a lot of development between stable version 1.1.3 and the current development version 1.1.3+dev.

**Comment by gitalm** [comment]
Thanks for your Tip. I installed the flathub version 1.1.3 and everything works fine.
