### ISSUE TITLE
Error with rendering LaTeX syntax (chemfig package - benzeen ring) in xournal++ (windows)

### ISSUE THREAD

**Issue by Marijkevandesteene** [xournalpp/xournalpp#4740]
**Affects versions : 1.1.3 - windows**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.3
 - Installation method: official release (https://xournalpp.github.io/installation/)

**Describe the bug**
In windows the LaTeX syntax for a chemical figure for benzene can not be rendered to a picture. I am using a template in which the chemfig package is listed (https://github.com/Marijkevandesteene/WetenschappelijkeNotatie/blob/main/all_template.tex). 
For entering other notations using the chemifig package (fe. \chemfig{?-[:-50]-[:10]-[:-10]-[:130]O-[:190]?}) there is no issue.
On an other computer (Linux) this works perfectly. 

With the other packages (bohr, mchem, chemformula) in the template and in the document used in [https://www.overleaf.com/read/zmynxxrhmpzd](url) there is no issue. 
This syntax also gives no issues in a LaTeX document (see Overleaf).

**To Reproduce**
1. define to use the LaTeX template in [https://github.com/Marijkevandesteene/WetenschappelijkeNotatie/blob/main/all_template.tex](url)
2. open a document / pdf in Xournal++
3. enter the syntax to draw a benzeen molecule: \chemfig{*6(-=-=-=)}

**Expected behavior**
The syntax gets rendered as a drawing of the benzeen molecule

**Screenshots of Problem**
![afbeelding](https://user-images.githubusercontent.com/19363349/226096345-da05b2b7-8050-4c6d-ac5c-1c662b810672.png)
In this image you see the error I get when entering the syntax for a Benzeen molecule I get the error displayed.
For entering the other chemical notations via the chemfig package there is no error.

**Additional context**
I am investigating xournal++ to allow entering mathematical and other scientific notations on a pdf. This is to help students who have trouble with handwriting.

**Comment by rolandlo** [comment]
Thanks for reporting. If you try again with the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) you have a tab with the TeX output. This would help to investigate the issue. Moreover you might enjoy the LaTeX tool, which has improved quite a lot since the last stable release.

**Comment by Marijkevandesteene** [comment]
Thank you for your answer. I have downloaded and installed the nightly build. The LaTeX tool has changed and the syntax colouring is very helpful.
Entering \chemfig{*6(=-=-=-)} still gives the same error.
I have attached the command output. Hopes this helps, ...

[20230318 - CommandOutput for rendering chemfigBenzeen.txt](https://github.com/xournalpp/xournalpp/files/11008163/20230318.-.CommandOutput.for.rendering.chemfigBenzeen.txt)

**Comment by rolandlo** [comment]
The TeX output doesn't show any problems. I get a very similar output on Linux. 

On the top of the output you can see the path of the generated `.tex`-file inside the temporary folder. The generated `.pdf`-file has the same location, but it is named `tex.pdf` instead of `tex.tex`. Can you try the following:
1) Open the generated `tex.pdf` file in a PDF viewer and check if it displays correctly or gives some hints on what is wrong.
2) Compile the `tex.tex` file manually in your LaTeX editor of choice and see if it displays correctly?
3) Upload both files here so we can examine them as well.

**Comment by Marijkevandesteene** [comment]
The tex.pdf in c:/Users/jokin/AppData/Local/Temp/xournalpp-7836/tex looks ok. I could not attach tex.tex (not supported), but have compressed all files in the temp folder and attached as zip.

[tex.pdf](https://github.com/xournalpp/xournalpp/files/11008246/tex.pdf)
[tex.zip](https://github.com/xournalpp/xournalpp/files/11008247/tex.zip)

**Comment by rolandlo** [comment]
Thanks for the files. It looks like the PDF is OK. At least it displays on Linux with no issues. The error message comes from Poppler in https://github.com/xournalpp/xournalpp/blob/ef61e679b14790f41f43d633e5372d94df35dfd2/src/core/model/TexImage.cpp#L94-L95
I don't know why that happens. Can you open the `tex.pdf` in Xournal++ without error?

**Comment by Marijkevandesteene** [comment]
I can open it without error 
![afbeelding](https://user-images.githubusercontent.com/19363349/226101005-10f922b0-59b2-4e89-976f-735949f7050f.png)
But I had to move the pdf because I could not open it from the temp folder. I did not have the app data folder 
![afbeelding](https://user-images.githubusercontent.com/19363349/226101081-9687365d-5b3f-4dc8-a604-12f9679e1def.png)
The temp folder ( as listed in command output): 
![afbeelding](https://user-images.githubusercontent.com/19363349/226101112-c1223bf6-acfe-4992-97ba-1073ce642a14.png)

**Comment by Marijkevandesteene** [comment]
I was looking at this problem with the new version of Xournal++. I still get the same error. Apparently it is the poppler routine https://poppler.freedesktop.org/api/glib/PopplerDocument.html#poppler-document-new-from-data that gives the error POPPLER_ERROR_DAMAGED.
 I can not find or debug the issue, but have noticed that it occurs when I use an asterix or - sign to start my formula within \chemfig.
 I do not know if that rings a bell to someone, but help would be very welcome.
 
 This to be able to use Xournal++ as a tool to help students in taking notes or filling in an exam or a task in pdf.

**Comment by Marijkevandesteene** [comment]
The solution in fix #5174 resolved this issue. 

This resolution will be available in version 1.2.2 and all future versions of Xournal++ (1.2.3, 1.3.0 etc.). It will not arrive in the nightly builds right away though. We first have to merge back the release-1.2 branch back into master.
