### ISSUE TITLE
The .desktop file created by AppImage xournalpp version, does not allow to "Open with" Xournalpp a .xopp file from file manager

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#4741]
**Affects versions :**
 - OS: Fedora
 - Desktop environment: Gnome-Wayland
 - xournalpp 1.1.3+dev (be01b216)
└──libgtk: 3.22.30
 - Installation method: AppImage
 
**Describe the bug**
In file manager, I can't open a .xopp file with Xournalpp. It does not show up in the list of applications in "Open with". The only way to open a file was to open Xournalpp and open the .xopp from there. [After investigation](https://askubuntu.com/questions/1367121/how-to-ad-appimage-to-open-with-menu), I just found that Xournalpp wasn't showing in "Open with" apps because the .desktop has the "Exec" line without the %f at the end. So appending %f at the end of "Exec" line, fixed the issue and now Xournalpp shows up and I can open a .xopp directly from file manager.

**Comment by Technius** [comment]
How was the `.desktop` file created? For non-AppImage installations, [the `.desktop file`](https://github.com/xournalpp/xournalpp/blob/5c4c1bd5ddc0d740616c57aaf80826a88b4bab99/desktop/com.github.xournalpp.xournalpp.desktop#L17) already has the `%f` in the `Exec` line.

**Comment by rolandlo** [comment]
Closing the issue, since the AppImage also contains the `.desktop` file with `Exec=xournalpp %f` entry and tools like AppImageLauncher take the desktop file from within the AppImage. @All3xJ must have had an old `.desktop` file around or produced one manually.
