### ISSUE TITLE
Changing Toolbar makes app crash

### ISSUE THREAD

**Issue by sglbl** [xournalpp/xournalpp#4751]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [Windows]
 - Which version of libgtk do you use
     - 3.24.34
 - Version of Xournal++: 
     - 1.1.3
 
 Official release downloaded from website

**Describe the bug**
When pdf is open and I want to change from one toolbar to another, app crashes.

**To Reproduce**
1. Open a pdf with xournal++
2. Change toolbar from x to y 1 or 2 times.
3. App crashes.

**Expected behavior**
App shouldn't crash and change toolbar option "Toolbar left" without any problem.

**Comment by rolandlo** [comment]
Does that also happen with the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) for you?

**Comment by EigenBeaver** [comment]
> Does that also happen with the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) for you?

Yes. The Xournal++ software(nightly build) also crashes, when I change "Toolbars" such as "Toobar right". 

Affects versions :

OS: [Windows 7]
Version of Xournal++:
1.1.3 nightly build, windows-portable.zip
Official release downloaded from website.

**Comment by bhennion** [comment]
Could you try installing the last version (1.2.1) and report back?

**Comment by bhennion** [comment]
This is probably the same issue as https://github.com/xournalpp/xournalpp/issues/5106, which has been fixed in 1.2.1.
Closing.
Please reopen if the crash still happens in 1.2.1 or later versions.
