### ISSUE TITLE
Windows 10 smartscreen is blocking the app as untrusted

### ISSUE THREAD

**Issue by Koladweep** [xournalpp/xournalpp#4754]
**I prefer not to use apps from unidentified sources... This is a well known app and Microsoft should give it some recognition. Please collaborate with them for to incorporate whatever they reasonably expect into the app so that they whitelist it in the windows defender smartscreen.**

**Please request Microsoft to add this app to their trusted apps list**

**Describe alternatives you've considered**
I am using MS edge for Zoom calls, but this would be a better annotation alternative.

**Additional context**
![image](https://user-images.githubusercontent.com/102764937/226817419-51de9922-101a-4753-94cb-7f0ee34ce896.png)

**Comment by rolandlo** [comment]
@Koladweep Are you aware that to "Collaborate with them [Microsoft] for to incorporate whatever they reasonably expect into the app" includes paying significant fees (at least 200$ a year) for code signing certificates?

**Comment by Koladweep** [comment]
That's what I anticipated and hence the word 'reasonably'. If someone is already working hard to develop an open source and free alternative(competetively so) for welfare of those who cannot afford enterprise grade tools like Adobe, then there should be no problem. I am not going to enter a debate. I like linux and was working on it. I just started using windows due to dependencies and lack of time to troubleshoot and learn. Hectic college term. 
Thank you for providing this tool.

**Comment by archisman-panigrahi** [comment]
Please try the Microsoft Store version. Microsoft signs it for free https://apps.microsoft.com/detail/9nn1hhct0p1x?hl=en-US&gl=US.

Also, there is a way to get the exe validated without any payment. It is possible to submit the exe file for analysis https://www.microsoft.com/en-us/wdsi/filesubmission. Afterwards, Microsoft will find out that the app is not a virus. They will send a Windows update with updated virus database and after sometime the app will not be detected as "unknown". However, this needs to be repeated after each app update. The Microsoft Store version is more convenient and provides automatic updates.

Apple, on the other hand, does not provide such "free" workarounds.
