### ISSUE TITLE
Xournal++ can't remember last viewed page when tries to open a file whose name (or its folder's name) contains accented letters

### ISSUE THREAD

**Issue by simone-amighini** [xournalpp/xournalpp#4767]
**Affects versions :**
 - OS: Windows
 - libgtk: 3.24.34
 - Xournal++: 1.1.3
 - Installation method: official download from GitHub

**Bug and expected behaviour**
If .xopp file is saved in a folder whose name contains accented letters or the filename contains itself accented letters, the software always opens the document at the first page. With other filenames, Xournal++ opens the file directly at the last viewed page.
If I rename the file (for example, from "Probabilità" to "Probabilita' ") the bug disappears!

**Comment by TobySkarting** [comment]
Same when there is non-English character (say, Chinese).

**Comment by TobySkarting** [comment]
It has been six months since v1.1.3 released https://github.com/xournalpp/xournalpp/releases/tag/v1.1.3

I tried nightly build and it has been fixed.
https://github.com/xournalpp/xournalpp/releases/tag/nightly
