### ISSUE TITLE
Toolbar doesn't show and cannot be shown.

### ISSUE THREAD

**Issue by odinsbane** [xournalpp/xournalpp#4774]
**Affects versions :**
 - OS: Linux Fedora
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use
  
 >     └──libgtk: 3.24.37
 
- Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     
> xournalpp 1.1.3+dev (4d8b2107)
    
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

> Compiled from github master  
> commit 4d8b2107565c42435bbc222faba7932f9544745b (HEAD -> master, tag: nightly, origin/master, origin/HEAD)

There is nothing in the toolbar

![image](https://user-images.githubusercontent.com/3462801/229466001-e55e8378-d24a-4fe3-96ec-5b033f0e6e3c.png)

If I remove the toolbar under the view menu item you can see that there is/was a space for the toolbar.

![image](https://user-images.githubusercontent.com/3462801/229466261-1df01634-0c50-47cb-8cba-5fd96b791182.png)

When I start the application from the command line, I get the following messages.

```
** Message: 11:13:36.712: TEXTDOMAINDIR = (null), Platform-specific locale dir = /home/melkor/.local/share/xournalpp/../locale, chosen directory = /home/melkor/.local/share/xournalpp/../locale
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
** Message: 11:13:36.825: Plugin "MigrateFontSizes" UI initialized
```

Everything builds and installs fine, and there are no obvious errors. I can install a different version and see the toolbar. Maybe there is something obvious I am missing.

Thank you

**Comment by rolandlo** [comment]
Which toolbar do you use (menu `View > Toolbars`)? Could it be that you use the empty toolbar?

**Comment by odinsbane** [comment]
Ha! That is exactly it. I don't know how I missed that. Actually, I wasn't using the empty toolbar, but none of them were selected. Once I selected one everything appears.
