### ISSUE TITLE
Audio playback doesn't work on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [xournalpp/xournalpp#4779]
Hi,

OpenBSD developer here. I'm trying to package xournalpp.

**Affects versions :**
 - OS: OpenBSD
 - (Linux only) Desktop environment: xfce
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3
 - Installation method: built from source under the ports tree

**Describe the bug**

**To Reproduce**
1. set audio device in recording prefs
2. toggle record on, speak
3. toggle record off
4. How do you playback? All of the playback buttons (Back, Pause/Play, Stop, Forward) remain grayed out.

![image](https://user-images.githubusercontent.com/604955/229905365-11475245-f2c6-4a95-89d3-be39dd94fff5.png)

Correct ogg vorbis files are being placed in the audio directory, just I don't know how to play them using the xournalpp gui. I suspect a bug.

I've been prodding in the source code looking for a place where it enumerates ogg files, but can't see one.

**Expected behavior**

Playback buttons light up after recording first clip (?)

Thanks!

**Comment by rolandlo** [comment]
In order to playback, use the `Play Object` option from the selection dropdown and click on the object (e.g. what you drew while recording) associated with the audio recording.
![grafik](https://user-images.githubusercontent.com/40485433/229906900-0693317f-e674-4c9b-8ee7-8ab394421105.png)

**Comment by vext01** [comment]
OK, it seems to work for pen and text at least, but not highlight. The forward and back buttons don't seem to work during playback. Also not sure how to see which objects have audio.

I never would have figured this out on my own. It's kind of a strange UI. I had expected to record some audio and attach it after the face.

**Comment by edgimar** [comment]
I agree that the current interface is very unintuitive.  A better interface would allow one to create a recording object (or annotated normal xournal object) which can be seen visually (where visibility can be toggled) with controls on the canvas.
