### ISSUE TITLE
Rescale LaTeX editor/preview 

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#478]
When writing "long" latex parts (> 10 words) the preview starts to get too big to fit the screen, and the editor is no longer usable (see the screenshot: https://imgur.com/a/xhbVNtc)
It would be nice for it to scale and stay under a certain size (and maybe even have a multiline textbox)

**Comment by morrolinux** [comment]
@luco5826 Do you think you can acheive that?

**Comment by luco5826** [comment]
@morrolinux I could totally try!
I should modify the LatexDialog and search for an option in mathex for the preferred output size!

**Comment by andreasb242** [comment]
You can scale it wit cairo. Code hints (not compiling, but in general complete, copied from Xournal++ source)

```
	this->surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32,
											   width * this->pngDpi / 72.0,
											   height * this->pngDpi / 72.0);
	this->cr = cairo_create(this->surface);
	double factor = this->pngDpi / 72.0;
	cairo_scale(this->cr, factor, factor);

	cairo_set_source_surface(cr, ORIGINAL_GRAPHIC, 0, 0);
	cairo_paint(cr);
	cairo_destroy(this->cr);

```

**Comment by morrolinux** [comment]
So.. It is better! but I would have scaled it more (or prevented it to go over a certain size)
See how it's changed on my previous example: https://imgur.com/a/srVKd3D
Do you have it significantly smaller? maybe you're on a HiDPI screen?

**Comment by morrolinux** [comment]
Ok, I just realized that that happens when I edit an existing latex.
If I create a new one from scratch and paste the same text, here's the result: https://imgur.com/a/YCxY09C
Which is just perfect.
So I guess it's fine overall :)
Thank You! @luco5826

**Comment by luco5826** [comment]
@morrolinux Awesome! 
I'm so happy you found it useful. It still needs some tweaks, including the multi-line editor which is harder then I thought, but when I'll have that implemented i'm gonna focus on the scale factor in order to optimize the size!

**Comment by andreasb242** [comment]
g_source_remove(this->rescaleId); to remove it from queue and g_timeout_add with a timeout from 500ms or so on each key press.

So if the user 500ms does not type, the preview will be updated

**Comment by luco5826** [comment]
Hi @andreasb242 sorry to bother you but I'm struggling with the timeout
```
void LatexController::handleTexChanged(GtkTextBuffer* buffer, LatexController* self)
{
	XOJ_CHECK_TYPE_OBJ(self, LatexController);

	if(self->getRescaleId() != 0)
	{
		g_source_remove(self->getRescaleId());
	}
	self->setRescaleId(g_timeout_add_seconds(1, (GSourceFunc) handleTexChanged, self));
```
Is this the right place where to place the timeout? And then, how can i call the same static functions with two arguments? I'm not quite sure about the right way to do it

**Comment by andreasb242** [comment]
I'll do you an example, I have to try it first....

**Comment by andreasb242** [comment]
First: you are in LatexController, you don't need Getter / Setter.
You can direct access member. (you can use getter / setter, but don't make them Public!)

self->setRescaleId(g_timeout_add_seconds(1, (GSourceFunc) timerCallback, self));
You cannot pass two parameter, you need to create a function with one Parameter.

void LatexController::timerCallback(LatexController* self)
{
	XOJ_CHECK_TYPE_OBJ(self, LatexController);

// This should work
}
