### ISSUE TITLE
network shared folder not available under windows! render useless to people who solely use network shared folders

### ISSUE THREAD

**Issue by ccchan234** [xournalpp/xournalpp#4780]
hi,

i put all my files on a samba/cifs server

and mount it to edit files.

the folder is NOT able to be show up in window's xournal.

this renders xournal completely useless to me.

i guess "user who use folder share" consists of majority of the users.

this is not a bug, but is a problem!

thanks

**Comment by Febbe** [comment]
You should be more polite and descriptive, when you want this problem to be solved.

First, use our issue template, and fill out all the information.

Which xournalpp version do you use?
How is the smb/cifs drive mounted?
Are all files in the mounted directory accessible via the file protocol?

I am missing some screenshots, how it is, and how you would expect it. 
The latter is not required to be a modified xournalpp screenshot, it can be from a completely different application.

**Comment by ccchan234** [comment]
that's why foss sucks.
those volunteer programmers are too self-centered.
they don't listen, and shout when others give feedback.
