### ISSUE TITLE
Newly added pages comes diagonally

### ISSUE THREAD

**Issue by manasjana** [xournalpp/xournalpp#4785]
### (Please complete the following information, and then delete this line)

**Affects versions**
 - OS:  Windows 11
 - version: 1.1.13
 

**Describe the bug**
When I'm adding new pages it comes diagonally instead of vertically. Please solve this issue. 

**Screenshots of [Problem]**

![Screenshot 2023-04-06 091645](https://user-images.githubusercontent.com/78194837/230268674-72187d4d-369e-4533-bd61-6e06c94c8ceb.png)

**Comment by rolandlo** [comment]
You are in "paired pages" mode, which you apparently don't want. Just click on the "paired pages" icon on the bottom right (leftmost symbol) 
![grafik](https://user-images.githubusercontent.com/40485433/230282835-88b88973-06cf-4d3a-8ac3-c22a2275f1c9.png)

**Comment by manasjana** [comment]
I removed the "paired pages" mode it still was coming diagonally.
![Screenshot 2023-04-06 112654](https://user-images.githubusercontent.com/78194837/230284572-da548235-fbcc-4042-a5e6-8be7b4d9ca6c.png)

**Comment by manasjana** [comment]
![Screenshot 2023-04-06 113057](https://user-images.githubusercontent.com/78194837/230285075-a03bbfec-eb57-4d1f-85e7-16de887df764.png)

**Comment by rolandlo** [comment]
Check your settings in menu `View > Layout` and `View > Cols/Rows` then. You probably want to `Set Columns > 1 Column`

**Comment by manasjana** [comment]
Done!! Thank you.
