### ISSUE TITLE
Cannot see cursor clearly when drawing on PDF with drawing tablet

### ISSUE THREAD

**Issue by cybercoder-naj** [xournalpp/xournalpp#4794]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: EndeavourOS
 - (Linux only) Desktop environment: Xorg
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3
 - Installation method: Pacman

**Describe the bug**
When I connect my input tablet, and select the draw/erase/highlight mode, I only see a tiny dot to indicate my cursor. It is quite hard to track this tiny dot. However, when I give a mouse input, the dot becomes a pointer.

**To Reproduce**
1. Step 1: Connect a input tablet (I use Wacom)
2. Step 2: Try to draw on the PDF

**Expected behavior**
I would like to see a bigger cursor on the screen when using my drawing tablet, so that I can easily track it while working/studying.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
In the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) you have multiple options for the pen cursor, one of which is using the system cursor:
![grafik](https://user-images.githubusercontent.com/40485433/230792986-6e415fb4-069b-412b-80da-51455a7d6d0c.png)

**Comment by cybercoder-naj** [comment]
That took some finding to get it. Thank you for your help!
