### ISSUE TITLE
extremely laggy load and scroll of pdf files on Mac M1, M1 Max, M2

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#4799]
Mac OS Ventura, Monterey - all the latest versions over the past 6 months
all official versions and nightly builds for the last six months or more... today is 4/13 2023

Loading a 4-page pdf (2.8mb scanned music pages from imslp - tried many different files with same results) takes several minutes to load. Thumbnail for first page will appear after 10 to 20 seconds. Other page thumbnails take a similarly long time as well. Scrolling through document with hand tool (mouse scroll wheel doesn't work on Mac M1, M2) will present user with a spinning wheel which can sometimes take up to 15 seconds and more to reposition... Too many handgrabber page move attempts without waiting for a reaction from Xournal++ will likely hang and require a force-quit.

PDF files containing few images and mostly text and simple vector graphics (lines and such) behave much more responsively = "somewhat laggy" - versus the "impossible laggy" of the image pages.

**To Reproduce**
Try to open an xournal file (xopp) which contains a pdf (originally created by 'Annotate PDF'). Sit back and feel the pain.
It is basically unusable in its current state.
The same file with the same Preferences, settings, toolbars, etc, done on a Windows 10 machine performs as would be expected - smoothly, with no lag. Scroll wheel moves the page up and down in time with the movement of the scroll wheel with no lag.
Perhaps an arm version of Xournal++ would help?

**Comment by rolandlo** [comment]
Probably there is no way around building Xournal++ on ARM to get a usable version. From the dev team only @Technius has some experience with it as far as I know.

**Comment by Technius** [comment]
I think this is likely due to Rosetta 2 emulation. The native ARM64 version is significantly better in terms of performance, but there's no easy way to build an ARM64 version on CI.

**Comment by lcalder** [comment]
I tried to compile using the instructions in the Wiki, however ran into errors along the way. Should it be possible, or does some code/libraries actually have to be changed..?

**Comment by lcalder** [comment]
It seems the jhbuild always fails - Is it not M1/M2 compatible?

**Comment by lcalder** [comment]
I found a solution to some of the lagginess... Turning off Gtk inertial scrolling in the Touchscreen tab of menu Edit > Preferences helps.

**Comment by OskarZyg** [comment]
> I found a solution to some of the lagginess... Turning off Gtk inertial scrolling in the Touchscreen tab of menu Edit > Preferences helps.

Doesn't appear to solve anything for me. Lag is still there. Does azure still not support ARM yet?

**Comment by lantex** [comment]
> I found a solution to some of the lagginess... Turning off Gtk inertial scrolling in the Touchscreen tab of menu Edit > Preferences helps.我找到了一个解决办法...在菜单Edit > Preferences的Touchscreen选项卡中关闭Gtk惯性滚动会有所帮助。

It doesn’t work for me.

**Comment by rolandlo** [comment]
If you wish to try out an ARM build for a recent 1.2.3+dev version, see [this post](https://github.com/xournalpp/xournalpp/issues/5643#issuecomment-2083480167)

**Comment by rolandlo** [comment]
A MacOS ARM build was released with version 1.2.4. Closing this issue therefore.
