### ISSUE TITLE
Crash when pressing Ctrl+V while clipboard provides only image/svg+xml

### ISSUE THREAD

**Issue by stiglers-eponym** [xournalpp/xournalpp#4800]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: both Wayland (sway) and XWayland
 - libgtk version: 3.24.37
 - Version of Xournal++: 1.1.3
 - Installation method: official release (Arch Linux)

**Describe the bug**
When pasting an image, it seems like it is implicitly assumed that this is a pixel-based image. Pasting a vector graphic can result in a crash.

**To Reproduce**
1. copy a valid SVG graphic to the clipboard such that the clipboard only povides the Mime type `image/svg+xml`. To check this, use (in wayland) `wl-paste -l`, which should only list `image/svg+xml`.
2. press Ctrl+V in Xournal++
3. Xournal++ crashes

**Expected behavior**
Even in this rare case that the clipboard only provides the type image/svg+xml, Xournal++ should not crash.

**Additional context**
Output of Xournal++ during the crash:
```
(xournalpp:28314): GdkPixbuf-CRITICAL **: 20:28:13.298: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(xournalpp:28314): GdkPixbuf-CRITICAL **: 20:28:13.298: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(xournalpp:28314): GdkPixbuf-CRITICAL **: 20:28:13.298: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(xournalpp:28314): GdkPixbuf-CRITICAL **: 20:28:13.298: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(xournalpp:28314): GdkPixbuf-CRITICAL **: 20:28:13.298: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (xournalpp:28314): WARNING **: 20:28:13.298: [Crash Handler] Crashed with signal 11

** (xournalpp:28314): WARNING **: 20:28:13.299: [Crash Handler] Wrote crash log to: .../.cache/xournalpp/errorlogs/errorlog.20230414-202813.log

** (xournalpp:28314): WARNING **: 20:28:13.742: Trying to emergency save the current open document…

** (xournalpp:28314): WARNING **: 20:28:13.743: Successfully saved document to ".../.config/xournalpp/emergencysave.xopp"
```

I guess that an additional check in `ClipboardHandler::pasteClipboardImage` (in src/core/control/ClipboardHandler.cpp) might solve the problem.
If you need more debugging output, just let me know.

**Comment by Technius** [comment]
Does this issue also occur in the nightly version? There were some changes some time ago that made the image tool logic more robust.

**Comment by stiglers-eponym** [comment]
You're right, it's fixed! This version does not crash anymore:
xournalpp 1.1.3+dev (0d132dfd)
└──libgtk: 3.24.37
I should have checked that before open the issue. Thank you!
