### ISSUE TITLE
Extra padding around the scrollbars and toolbars

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#4814]
**Affects versions :**
 - OS: Linux (Arch)
 - Desktop environment: X11
 - Version of libgtk: 3.24.37
 - Version of Xournal++: 1.1.3+dev, built on April 17
 - Installation method: manual

**Describe the bug**
After opening Xournal++ there is extra padding around the scrollbars and toolbars (see the screenshots).
Pressing `Customize Toolbars` (need not change anything) or switching the toolbar style makes the extra paddings go away.

**Expected behavior**
The extra padding should not be present.

**Screenshots of Problem**
Freshly started Xournal++
![xournalpp_freshly_opened](https://user-images.githubusercontent.com/19737748/233457178-7a09a618-ef4b-4378-b80c-62a135849f09.png)

After pressing `Customize Toolbars` (and then `Close`)
![xournalpp_after_Customize_toolbars](https://user-images.githubusercontent.com/19737748/233457223-19019f5f-2fda-4ff8-9281-586296d33e82.png)

**Additional context**
If I had to guess when I first noticed the paddings, it would be month to couple of months ago.

**Comment by bhennion** [comment]
Fixed for the next release 1.2.2
