### ISSUE TITLE
Make PDF links clickable

### ISSUE THREAD

**Issue by vext01** [xournalpp/xournalpp#4817]
**Is your feature request related to a problem? Please describe.**

When annotating a PDF, often there are internal links to tables and figures (and sometimes external links to websites). These cannot be followed in xournal.

**Describe the solution you'd like**

Links should be clickable.

**Comment by vext01** [comment]
P.S.

I committed an OpenBSD package of xournalpp the other day :)

https://marc.info/?l=openbsd-ports-cvs&m=168189220330451&w=2

**Comment by rolandlo** [comment]
Links are clickable in the development version ([nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)) using the PDF selection tool.
