### ISSUE TITLE
Copy issue from Xournal to another application

### ISSUE THREAD

**Issue by AllInASpin** [xournalpp/xournalpp#4818]
Affects versions :
    Windows 10
    Version of Xournal++: 1.1.3
   
Describe the bug
Upgrading from 1.1.0 to version 1.1.3 you are unable to copy  from xournal to excel or word any more.
You simply get a blank place holder.

To Reproduce
    Copy a selection to the clipboard from xournal++.
    Switch to to excel /word  and  paste into the application.

Expected behaviour
  It would paste the selected item from Xournal++ into  another application as previous.

**Screenshots of Problem**
![Bug_1 13](https://user-images.githubusercontent.com/126408154/233716036-e7e6f4ea-b8d0-4e50-abf2-36aa2bc4149e.PNG)

**Comment by rolandlo** [comment]
Can you try the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) as well? When I copy and paste into Libre Office on Linux, it works just fine.

**Comment by AllInASpin** [comment]
I can confirm that the bug is no longer present on the nightly build version.

Wow it also has some additional features which makes annotating even easier - double ended arrows.
Many thanks to all who have made this such versatile program.
I have been recommending xournal to all my colleagues.
Many thanks for response.

( Clipboard History - Last five items #4682)

**Comment by netlimpopo** [comment]
Also in microsoft word sometimes I actively have to select .png after inserting pictures, otherwise it leaves the above mentioned white square.

**Comment by AllInASpin** [comment]
Some thing strange going on here. 
The problem seems to be still present in the  1.13 -nightly dev version. 
They only thing I did was shut the laptop and booted it back up this afternoon after i tested the Dev version yesterday reporting that it been fixed in the nightly version.
I have compared both 1.1.3 and the 1.13 nightly version directly. 
![image](https://user-images.githubusercontent.com/126408154/233867117-4528848a-aa8f-4537-9dcb-50ff2004fed2.png)

Also at times when you do a simply [ ctrl + v ] you get partial paste

![image](https://user-images.githubusercontent.com/126408154/233867376-77d329c0-44ff-41fe-adae-aa9fb2b5d446.png)
  

However, you can work round this this Bug / quirkiness by doing a paste special [ Picture (PNG) ].
Its just a pain you that you have to do this each time.

I have verified that the problem is not unique to my windows 10 laptop.
The same problem persists on both 1.13 and 1.13+Dev on my desktop also which has window 10.

Any insight would be most grateful!

**Comment by rolandlo** [comment]
Generally speaking, Xournal++ puts various targets onto the clipboard and each application decides what target to use. Here is the list of targets (obtained by `wl-paste --list-targets`) I get on Linux after copying some hand-drawn stroke onto the clipboard:
```
application/xournal
image/svg+xml
image/svg
audio/x-riff
image/webp
image/tiff
text/ico
image/icon
image/ico
application/ico
image/vnd.microsoft.icon
image/x-win-bitmap
image/x-ico
image/x-icon
image/x-MS-bmp
image/x-bmp
image/bmp
image/jpeg
image/png
```
Libre Office uses the `image/png` target, which works fine. We should find out what target MS Word uses.

**Comment by rolandlo** [comment]
Thanks for the detailed report @netlimpopo 
I will take a look what can be done about it. It looks more like a bug on Microsoft's side though.

**Comment by AllInASpin** [comment]
Switched back to xournal++ 1.1.0 to see if its a windows 10 issue  due recent window/office updates.
[ Crtl + V ] and paste as PNG  functions  flawlessly  across the entire office suite.
So it appears that the issue has arisen after  version 1.1.0 if that helps in anyway.
