### ISSUE TITLE
100% zoom level isn't actually 100%

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#4821]
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: X11, Xfce
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3+dev, commit c827d80e
 - Installation method: AUR package: https://aur.archlinux.org/packages/xournalpp-git

**Describe the bug**
When set to 100% zoom, the page size isn't actually 100%, it rather resembles "fit window height". Sometimes it is necessary to have the page in original size, e.g. to see if the font size is suiting. I attached a screenshot where Xournal++ and a PDF viewer (Atril) show the same page and both have the zoom level set to 100%, but in Xournal++ the page is too small. If I compare it to a physical sheet of A4 paper then Atril has the correct page size and Xournal++ doesn't.  

**To Reproduce**
1. Launch Xournal++
2. Set the zoom to 100%
3. Observe that the page size isn't correct.

**Expected behavior**
The page size should match the actual page size if zoom level is set to 100%.

**Screenshots of Problem**
![Auswahl_270](https://user-images.githubusercontent.com/1191480/233794602-4a7068c4-2ed6-4983-98fd-11a91d58984f.png)

**Additional context**
None.

**Comment by rolandlo** [comment]
In Xournal++ you have to calibrate the display DPI in the Zoom tab of menu `Edit > Preferences`. Afterwards zoom will be as expected.

**Comment by Photon89** [comment]
Thanks! It's better now, but still not the same:

![Auswahl_274](https://user-images.githubusercontent.com/1191480/233803926-42d80562-04b5-463f-be12-89b701284cd9.png)

For some reason, I cannot choose 128 as DPI value, it always changes to 127...

**Comment by rolandlo** [comment]
I don't know why you can't set 128 as a value in the GUI, but you could also manually edit the file `~/.config/xournalpp/settings.xml` (search for `displayDpi`).

**Comment by Photon89** [comment]
>  Also note that the font DPI value may refer to something entirely different than display DPI.

@rolandlo I see, thanks for the support and the explanation, this solves the issue for me!
