### ISSUE TITLE
Crash when pressing `ESC` during spline drawing.

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#4822]
**Affects versions :**
 - OS: Linux (Arch)
 - Desktop environment: X11
 - Version of libgtk: 3.24.37
 - Version of Xournal++: 1.1.3+dev, built on April 17
 - Installation method: manual

**Describe the bug**
Pressing `ESC` during spline drawing results in a crash.

**To Reproduce**
1. Choose `Draw Spline` tool
2. Start to draw a spline
3. Press `ESC` to stop drawing the spline
4. Trying to draw another spline (or doing other actions) results in a crash.

**Expected behavior**
Pressing `ESC` should properly stop drawing the spline, so it is possible to draw another spline (or to do other actions) without crash.

**Additional context**
Following line of output when running `xournalpp` from the terminal is probably relevant:
```
xournalpp: .../xournalpp/src/core/control/tools/SplineHandler.cpp:211: virtual void SplineHandler::onButtonPressEvent(const PositionInputData&, double): Assertion `this->knots.empty() && this->tangents.empty()' failed.
```

**Comment by rolandlo** [comment]
Thanks for reporting. I can confirm the issue.
