### ISSUE TITLE
Fill indicator in toolbar doesn't update after "ACTION_TOOL_FILL".

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#4823]
**Affects versions :**
 - OS: Linux (Arch)
 - Desktop environment: X11
 - Version of libgtk: 3.24.37
 - Version of Xournal++: 1.1.3+dev, built on April 17
 - Installation method: manual

**Describe the bug**
Toggling `Fill` via plugin works, but the indicator in the toolbar does not change.

**To Reproduce**
Create a simple plugin with the following following action bound to any key:
```
app.uiAction({ ["action"] = "ACTION_TOOL_FILL" })
```
Fill is enabled, but the fill indication in the toolbar is not updated.

**Expected behavior**
Fill indicator in the toolbar changes automatically.

**Additional context**
Similar to #3090.

**Comment by rolandlo** [comment]
Looks like
```Lua
  app.uiAction({["action"]="ACTION_TOOL_FILL"})
  app.uiActionSelected("GROUP_FILL", "ACTION_TOOL_FILL")
```
is currently needed for that.

**Comment by rolandlo** [comment]
You can also use 
```Lua
app.uiAction({ ["action"] = "ACTION_TOOL_PEN_FILL" })
```
for pen or
```Lua
app.uiAction({ ["action"] = "ACTION_TOOL_HIGHLIGHTER_FILL" })
```
for highlighter.
I'm not sure that what you report is a bug. You can also use `ACTION_TOOL_FILL` for selections, where I don't think the toolbar button should be toggled.

**Comment by jdujava** [comment]
I would expect similar behaviour to `ACTION_SIZE_...`, where for selection the appropriate toolbar button is toggled (and hopefully also for any other tool after #4807). Using
```lua 
app.uiActionSelected("GROUP_FILL", "ACTION_TOOL_FILL")
```
one can only toggle ON the fill button, right?

Ideally the following toggle function would work:
```lua
function filltoggle()
    local filled = app.getToolInfo("active")["fillOpacity"] or -1
    app.uiAction({ ["action"] = "ACTION_TOOL_FILL", ["enabled"] = (filled == -1) })
end
```
As of now it works for pen and highlighter (but the toolbar button is not updated). 

It would be awesome, if the `fillOpacity` worked also for selection, similarly as
```lua
app.getToolInfo("active")["size"]["name"]
```
works (after initial selection it returns `nil`, but after changing the size of selection it returns the correct value).

**Comment by rolandlo** [comment]
See #4831 for a fix. The `filltoggle()` function works now.

**Comment by jdujava** [comment]
Awesome, thank you very much!

Should I open separate feature request for `getToolInfo` to return `fillOpacity` also for selections?

**Comment by jdujava** [comment]
I can confirm that `filltoggle()` works also for selections in #4831 :+1: .

I noticed that calling `filltoggle()` on selection emits the following warning to terminal:
`** (xournalpp:XXXXX): WARNING **: 16:16:49.363: Request size of "selectRect"`
Similarly `app.getToolInfo("active")["size"]["name"]` when called on selection.
It probably isn't anything important, just mentioning.

**Comment by rolandlo** [comment]
About the warning: The "selectRect" tool doesn't have a thickness (only pen, eraser and highlighter have one), so `toolHandler->getThickness()` returns 0 and displays a warning. We could check the tool type before requesting the thickness in 
https://github.com/xournalpp/xournalpp/blob/9c8538bac50574fd17917437b077e7a39650f62d/src/core/plugin/luapi_application.h#L1273
to avoid these warnings.
