### ISSUE TITLE
Changing linestyle for selection doesn't work properly.

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#4827]
**Affects versions :**
 - OS: Linux (Arch)
 - Desktop environment: X11
 - Version of libgtk: 3.24.37
 - Version of Xournal++: 1.1.3+dev, built on April 17
 - Installation method: manual

**Describe the bug**
Changing linestyle for selection results in weird behaviour, see screencast below.

**Expected behavior**
As in #4089. Ideally also everything works with plugins, see #4823.

**Screencast of Problem**

[select_linestyle_1.webm](https://user-images.githubusercontent.com/19737748/234007051-60f260c8-2e06-49ec-b7fb-ab1f36e2461e.webm)

**Comment by rolandlo** [comment]
This should also be fixed in #4831 
@jdujava Can you try the PR out? An installer is created for that purpose.
