### ISSUE TITLE
Missing part of PDF background

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#4830]
[errorlog.20220503-000106.log](https://github.com/xournalpp/xournalpp/files/11315757/errorlog.20220503-000106.log)

**Comment by lcalder** [comment]
This was generated on a Mac Mini M2 Pro with latest OS. Annoted PDF background was missing chunks... as if a large white rectangle had been drawn to cover lower half or even the entire page for about 25% of the pages (60 page document in landscape format...)
Looking at the pdf original in a pdf reader didn't show any such rectangular missing areas.

**Comment by lcalder** [comment]
I tried loading the file using the latest "stable" release but was unable to tell if the pages had missing segments as Xournal++ kept crashing after scrolling through a few pages....

**Comment by lcalder** [comment]
[Alfred small x.pdf](https://github.com/xournalpp/xournalpp/files/11315819/Alfred.small.x.pdf)
 This is a copy of the offending PDF file...

**Comment by rolandlo** [comment]
There are also missing chunks when using the flatpak (version 1.1.3). The AppImage 1.1.3 doesn't have this issue. For the flatpak this issue is most likely related to fonts and sandboxing, but we haven't figured it out yet. The same issue has been reported in #4615 and #2568

Your errorlog seems to be related to the eraser though, nothing to do with the PDF background.

**Comment by bhennion** [comment]
You should try the latest nightly build, as performances got improved quite a bit
With it, I see no problem with your Pdf file (although it is pretty heavy and pages take a noticeable time to load).

**Comment by lcalder** [comment]
The AppImage is for Linux though... Not MacOS... Plus it's also X86/x64 so running as a virtual machine which has to go through Rosetta emulation as well probably won't work well...

**Comment by rolandlo** [comment]
I didn't suggest you use the AppImage on MacOS. I'm just trying to locate the problem, which must be in the dependencies or permissions somewhere.

**Comment by lcalder** [comment]
Thanks

**Comment by lcalder** [comment]
After no being able to use the above-referenced Alfred file for months on Xournal++, I finally saw a comment someone had made: "Maybe turning off Gtk inertial scrolling in the Touchscreen tab of menu Edit > Preferences helps."
My machine doesn't have a touchscreen so I would have never thought of this... BUT, I WORKS NOW! and NOT SO LAGGY!
Yay!

**Comment by lcalder** [comment]
I also have tried multiple times to compile Xournal for the M2 Mac, but all attempts fail, even with the new instructions. It seems the jhbuild thing doesn't work on M1/M2's.... ?? Anyone know of a work-around?
