### ISSUE TITLE
Voice Dictation doesn't work on MacOS Ventura

### ISSUE THREAD

**Issue by nOw-Ay** [xournalpp/xournalpp#4833]
**OS:** Affects MacOS Ventura 13.3.1 (22E261)
**Libgtk Version:** 3.24.36
**Version of Xournal++ :** xournalpp-1.1.3+dev-nightly.20230425-macos

Installation via Nightly Builds to avoid some issues that have not been fixed yet in latest stable release.

**Description:** 

I can't use the native MacOS voice dictation within Xournal++. When I use the shortcut that I defined in System Settings, nothing happens  while everything is works normally within the other applications.

1. Define a shortcut for Dictation using System Settings > Keyboard > Dictation
2. Check if voice Dictation works within the other applications
3. Nothing happens when you try to use your Dictation shortcut inside Xournal++

A little mic icon should appear, a jingle should be played and you should be able to dictate text within Xournal++. 

I only downloaded your software today but as far I can tell, it looks very nice and I would be happy to use it on a daily basis:)

Thanks you!

**Complete Log :**

/Applications/Xournal++.app/Contents/MacOS/xournalpp ; exit;
** Message: 17:50:29.407: Continue with GDK_PIXBUF_MODULE_FILE = /Applications/Xournal++.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
** Message: 17:50:29.407: Setting LANG and LC_MESSAGES to en_GB.UTF-8
** Message: 17:50:29.508: TEXTDOMAINDIR = (null), Platform-specific locale dir = /Applications/Xournal++.app/Contents/Resources/share/locale, chosen directory = /Applications/Xournal++.app/Contents/Resources/share/locale
** Message: 17:50:29.712: Plugin "MigrateFontSizes" UI initialized

(xournalpp:2110): Pango-WARNING **: 17:50:29.881: couldn't load font "Noto Sans Kannada Italic Condensed Not-Rotated 12", modified variant/weight/stretch as fallback, expect ugly output.

(xournalpp:2110): Gtk-WARNING **: 17:50:30.074: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

(xournalpp:2110): Gtk-WARNING **: 17:50:30.074: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(xournalpp:2110): Gtk-WARNING **: 17:50:30.074: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(xournalpp:2110): Gtk-WARNING **: 17:50:30.074: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(xournalpp:2110): Gtk-WARNING **: 17:50:30.074: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

Saving session...completed.

[Process completed]

**Comment by rolandlo** [comment]
What's the shortcut you use?

**Comment by nOw-Ay** [comment]
> What's the shortcut you use?

"Press Control Key Twice".

**Update:** Dictation works with the "Press FN twice" shortcut which is convenient for me... (even if I can't manage to make the ""Press Control Key Twice" works on my side). You can close this issue if needed. Many thanks for your time.
