### ISSUE TITLE
how to create specific directory for xopp files

### ISSUE THREAD

**Issue by tjallemaal** [xournalpp/xournalpp#4834]
OS: [Mac Catalina]

I would like to have all my .xopp files in one directory, independent of the pdf location.
My problem: When pdf and .xopp are separated, I don't get the annotations.
How do I make xournal++ search a specific directory for a corresponding .xopp file?

This is not a bug, just me nooby.

**Comment by rolandlo** [comment]
What do you mean by "I don't get the annotations"? Why don't you just open the .xopp-file in Xournal++?

**Comment by tjallemaal** [comment]
I didnt know that that's the way it's supposed to be.
I get an error message when I try opening the .xopp file itself. 
<img width="756" alt="Screenshot 2023-04-05 at 13 05 57" src="https://user-images.githubusercontent.com/69585777/234517582-1953e258-94dd-40fc-9347-caf7ba4cf878.png">

**Comment by tjallemaal** [comment]
I see! thanks
