### ISSUE TITLE
Undo Doesn't Undo Moving Annotations

### ISSUE THREAD

**Issue by TheSaneWriter** [xournalpp/xournalpp#4835]
**Affects versions :**
 - OS: Linux (Manjaro 22.1)
 - (Linux only) Desktop environment: KDE Plasma 5 (Qt 5, KDE Frameworks 5, X Window System, Wayland)
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3+dev (4c8acc1d)
 - Installation method: AUR install using yay. Package build attached:
[PKGBUILD.txt](https://github.com/xournalpp/xournalpp/files/11325222/PKGBUILD.txt)

**Describe the bug**
After moving annotations manually (using one of the select tools), the undo button will not restore the annotations to their original position.

**To Reproduce**
1. Select drawn annotations using one of the select tools.
2. Move the selection using the mouse or arrow keys.
3. Click the undo button.

**Expected behavior**
Upon clicking the undo button or hitting control+z, the annotations that have been moved are reverted back to their original position, and the redo button is set to redoing that undone movement.

**Screenshots of Problem**
I have attached a short video to demonstrate my issue:
[Xournal++ Undo Bug.mp4](https://user-images.githubusercontent.com/93878758/234356353-a2744703-0f59-4b3e-ab5d-6a2d4b64843e.mp4)

**Comment by rolandlo** [comment]
Thanks for reporting. That's pretty bad. I can confirm it in both current master and version 1.1.3.

**Comment by TheSaneWriter** [comment]
It's all good. It seems to be a long-standing issue; I vaguely remember this happening even as long as a few months ago. I'll be glad to see it fixed.
