### ISSUE TITLE
Error log on opening Xournal++

### ISSUE THREAD

**Issue by KlumpRasmus** [xournalpp/xournalpp#4836]
I got this when opening Xournal++:

Date: Sun Aug  7 17:54:05 2022
Error: signal 11
[bt]: (0) xournalpp(+0xafc88) [0x55c4a464bc88]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4843e0c520]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x55c4a46983eb]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc3f) [0x55c4a468c60f]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x55c4a467a159]
[bt]: (5) xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x55c4a467a5ab]
[bt]: (6) xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x86b) [0x55c4a467b5ab]
[bt]: (7) xournalpp(+0xb2504) [0x55c4a464e504]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f484470dd2f]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30b76) [0x7f4844729b76]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f484472b554]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f484472b7a3]
[bt]: (12) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f48448690f1]
[bt]: (13) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe085e) [0x7f484486985e]
[bt]: (14) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f4844869c16]
[bt]: (15) xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x55c4a4649d8f]
[bt]: (16) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f4843df3d90]
[bt]: (17) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f4843df3e40]
[bt]: (18) xournalpp(_start+0x25) [0x55c4a4647cc5]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xb012d) [0x55c4a464c12d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4843e0c520]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x55c4a46983eb]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc3f) [0x55c4a468c60f]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x55c4a467a159]
??:0
[bt] #6 xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x55c4a467a5ab]
??:0
[bt] #7 xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x86b) [0x55c4a467b5ab]
??:0
[bt] #8 xournalpp(+0xb2504) [0x55c4a464e504]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f484470dd2f]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30b76) [0x7f4844729b76]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f484472b554]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f484472b7a3]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f48448690f1]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe085e) [0x7f484486985e]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f4844869c16]
??:0
[bt] #16 xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x55c4a4649d8f]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f4843df3d90]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f4843df3e40]
??:0
[bt] #19 xournalpp(_start+0x25) [0x55c4a4647cc5]
??:0

**Comment by rolandlo** [comment]
This (quite old) bug report is about loading colors from the palette at startup. Did the problem occur again after Aug 7, 2022. Otherwise it's probably just a one time issue (maybe related to an upgrade or a change of palettes) and we can close this.
By the way an errorlog doesn't contain other needed info, like what OS and what version of Xournal++ you use. It's just the stacktrace from a crash.

**Comment by bhennion** [comment]
Closing in favor of #4940
