### ISSUE TITLE
Compiling scripts for MacOS ARM on M1 keep getting killed with no furthe explanation 

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#4838]
- OS: MacOS Ventura 13.3.1
 - Which version of libgtk do you use
     - can't get it to compile

Following the MacBuild.md instructions, whenever I try to run "./build-gtk3.sh" in the /Users/[name]/xournalpp/mac-setup folder a lot of the subprocesses are killed without any further error messages... (shown  below). 

>>>>> ./build-gtk3.sh

...(100's of lines of output)

+ curl -L -O https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9060  100  9060    0     0  14303      0 --:--:-- --:--:-- --:--:-- 14380
+ chmod +x gtk-osx-setup.sh
+ ./gtk-osx-setup.sh
./build-gtk3.sh: line 10: 71573 Killed: 9               ./gtk-osx-setup.sh
+ jhbuild bootstrap-gtk-osx
./build-gtk3.sh: line 11: 71574 Killed: 9               jhbuild bootstrap-gtk-osx
+ jhbuild build python3
./build-gtk3.sh: line 12: 71575 Killed: 9               jhbuild build python3
+ jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
./build-gtk3.sh: line 13: 71576 Killed: 9               jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3

>>>>> next command prompt here...

These messages were preceeded by a huge output that seemed to compile and work fine until the errors.

So I tried individually running many of the scripts in the mac-setup folder... Some of them seemed to work ok, but several would just exit, saying "killed" and no further comment. I show a few commands and responses like this below:

ludwig@Ludwigs-MacBook-Pro mac-setup % ~/.new_local/bin/jhbuild shell
zsh: killed     ~/.new_local/bin/jhbuild shell
ludwig@Ludwigs-MacBook-Pro mac-setup % ./gtk-osx-setup.sh            
zsh: killed     ./gtk-osx-setup.sh

**Comment by Technius** [comment]
Hi @lcalder, please follow the steps in #4371, which are more up-to-date. I noticed this issue a few weeks ago, and it appears to have been fixed in the latest version of gtk-osx.
