### ISSUE TITLE
Plugin API: missing shapeTool functionality

### ISSUE THREAD

**Issue by ave-63** [xournalpp/xournalpp#4845]
Howdy. The lua plugin API is missing some useful features:

- There is ACTION_TOOL_DRAW_ELLIPSE, ACTION_TOOL_DRAW_RECT, ACTION_TOOL_DRAW_COORDINATE_SYSTEM, and ACTION_TOOL_DRAW_SPLINE, but there is no ACTION_TOOL_DRAW_LINE for straight lines. (For example, `app.uiAction({["action"] = "ACTION_TOOL_DRAW_ELLIPSE"})`)

- Once you have done any of the above actions, there's no way to turn it off with the API. Or at least I don't know how. I know it is possible to do this with the built-in keyboard shortcuts like Ctrl+6, but unfortunately I have a weird keyboard that makes it so I can't reach Ctrl+6 with one hand.

Motivation: I'm using my left hand to do a variety of keyboard shortcuts using my custom [plugin](https://github.com/ave-63/xournal-keys) while I write with my right hand, and I keep the toolbars hidden for extra real estate (while teaching math).

**Comment by rolandlo** [comment]
1) Use `ACTION_RULER`. 
2) Use the `enabled` key, e.g. 
```lua
app.uiAction({["action"] = "ACTION_RULER", ["enabled"] = false})
```

**Comment by ave-63** [comment]
That is perfect, thank you so much!
