### ISSUE TITLE
Don't scroll on >2 fingers touch inputs

### ISSUE THREAD

**Issue by hrdl-github** [xournalpp/xournalpp#4850]
I use a handful of 3/4-finger gestures with lisgd to e.g. switch workspaces or manage windows in combination with a touch screen. When performing these xournalpp performs a scroll event, which I would like to avoid.

Ideally xournalpp should ignore inputs when more than two fingers are present until an appropriate handler is implemented for these.

Do you think this behaviour makes sense in general or should the behaviour be configurable perhaps?

**Comment by rolandlo** [comment]
In https://github.com/trevorshelton/xournalpp/blob/3614258800b7540a16ca1c3717d2841bb27baaef/src/core/gui/inputdevices/TouchInputHandler.cpp#L25-L31 and https://github.com/trevorshelton/xournalpp/blob/3614258800b7540a16ca1c3717d2841bb27baaef/src/core/gui/inputdevices/GeometryToolInputHandler.cpp#L77-L82 we do disable touch gestures with more than two fingers. Also it is recommended by the Gnome HIG if I remember correctly. So I think in general Xournal++ should not handle touch gestures with more than two fingers.

**Comment by florian-sabonchi** [comment]
> I use a handful of 3/4-finger gestures with lisgd to e.g. switch workspaces or manage windows in combination with a touch screen. When performing these xournalpp performs a scroll event, which I would like to avoid.
> 
> Ideally xournalpp should ignore inputs when more than two fingers are present until an appropriate handler is implemented for these.
> 
> Do you think this behaviour makes sense in general or should the behaviour be configurable perhaps?

Hello I agree I currently have the problem that I have a Matebook with pen but it is only recognized as a touchscreen. When I try to draw and put my hand on the tablet it is often misinterpreted as scrolling.
