### ISSUE TITLE
unknown bug

### ISSUE THREAD

**Issue by yasmah74** [xournalpp/xournalpp#4881]
i dont know exactly what happend, but i recievd this errorlog.

Date: Thu May 18 19:57:11 2023
Error: signal 11
[bt]: (0) /usr/bin/xournalpp(+0xbf5d9) [0x55e659fb95d9]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7f113683c4b0]
[bt]: (2) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_device_is_shadowed+0x53) [0x7f11379482c3]
[bt]: (3) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x352560) [0x7f1137952560]
[bt]: (4) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x170) [0x7f113724d010]
[bt]: (5) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x423d6) [0x7f113727a3d6]
[bt]: (6) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x102a) [0x7f113726a69a]
[bt]: (7) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (8) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f66e0) [0x7f11377f66e0]
[bt]: (9) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
[bt]: (10) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2eb140) [0x7f11378eb140]
[bt]: (11) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc5ee0) [0x7f11376c5ee0]
[bt]: (13) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
[bt]: (14) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x226fc4) [0x7f1137826fc4]
[bt]: (15) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
[bt]: (16) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x35cb19) [0x7f113795cb19]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f6857) [0x7f11377f6857]
[bt]: (19) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1faa48) [0x7f11377faa48]
[bt]: (20) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_popup+0x73) [0x7f11377fafe3]
[bt]: (21) /usr/bin/xournalpp(+0x10a764) [0x55e65a004764]
[bt]: (22) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
[bt]: (23) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (24) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8460) [0x7f11376d8460]
[bt]: (25) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
[bt]: (26) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (27) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8234) [0x7f11376d8234]
[bt]: (28) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x99e55) [0x7f1137699e55]
[bt]: (29) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
[bt]: (30) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (31) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1ad70e) [0x7f11377ad70e]
[bt]: (32) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x96) [0x7f1137251946]
[bt]: (33) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
[bt]: (34) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (35) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1a4c77) [0x7f11377a4c77]
[bt]: (36) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1acf7b) [0x7f11377acf7b]
[bt]: (37) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1adb75) [0x7f11377adb75]
[bt]: (38) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_event_controller_handle_event+0x75) [0x7f1137774715]
[bt]: (39) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x343865) [0x7f1137943865]
[bt]: (40) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x98508) [0x7f1137698508]
[bt]: (41) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
[bt]: (42) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
[bt]: (43) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x352784) [0x7f1137952784]
[bt]: (44) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f6dee) [0x7f11377f6dee]
[bt]: (45) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0xcfa) [0x7f11377f7c3a]
[bt]: (46) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x398c3) [0x7f113753d8c3]
[bt]: (47) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x707a6) [0x7f11375747a6]
[bt]: (48) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2ad) [0x7f113714c49d]
[bt]: (49) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xb6178) [0x7f11371a7178]
[bt]: (50) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7f113714b1b0]
[bt]: (51) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1dd) [0x7f11373a6c5d]
[bt]: (52) /usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x5e2) [0x55e659fb66f2]
[bt]: (53) /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f1136823a90]
[bt]: (54) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f1136823b49]
[bt]: (55) /usr/bin/xournalpp(_start+0x25) [0x55e659fb4af5]

Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0xbfa1d) [0x55e659fb9a1d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7f113683c4b0]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_device_is_shadowed+0x53) [0x7f11379482c3]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x352560) [0x7f1137952560]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x170) [0x7f113724d010]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x423d6) [0x7f113727a3d6]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x102a) [0x7f113726a69a]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f66e0) [0x7f11377f66e0]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2eb140) [0x7f11378eb140]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc5ee0) [0x7f11376c5ee0]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x226fc4) [0x7f1137826fc4]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x35cb19) [0x7f113795cb19]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f665b) [0x7f11377f665b]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f6857) [0x7f11377f6857]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1faa48) [0x7f11377faa48]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_popup+0x73) [0x7f11377fafe3]
??:0
[bt] #22 /usr/bin/xournalpp(+0x10a764) [0x55e65a004764]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8460) [0x7f11376d8460]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
??:0
[bt] #28 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8234) [0x7f11376d8234]
??:0
[bt] #29 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x99e55) [0x7f1137699e55]
??:0
[bt] #30 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11cc) [0x7f113726a83c]
??:0
[bt] #31 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f113726a923]
??:0

**Comment by bhennion** [comment]
Do you remember what you were doing when it crashed?
The backtrace is sadly not very helpful in this case...

**Comment by bhennion** [comment]
Closing in favor of the very similar bug report #4931 (same backtrace...)
