### ISSUE TITLE
Can't save file 

### ISSUE THREAD

**Issue by SleepyFrof** [xournalpp/xournalpp#4909]
**Affects versions :**
 - OS: Windows 11 
 

 - Version of Xournal++: 1.1.3 and 1.1.3+dev
 
 - Installation method: official release from Github 

**Describe the bug**

When selecting "save" or "save as" and selecting a folder to save (in my case its named "notas") an error message will appear. In the normal stable version the file "seems" to save but when looking for the file again, its nowhere to be found and Xournal cant open it in the "recent documents" either.

**To Reproduce**
1. Open Xournal
2. Select save 
3. Error message appears

**Expected behavior**
The file should be saved in the folder of choice and thus be available to be changed again in Xournal later

**Screenshots of Problem**
[
![image](https://github.com/xournalpp/xournalpp/assets/135474741/fb91c7ae-3c4d-40e1-8bac-43ccc1266586)
](url)

**Additional context**
I spent some time trying to figure out how Xournal works and then more time trying to find a way out of this problem. Reinstalled, tried the nightly version, same issue. Have no idea of what I could have done to cause this. I am on Windows 11.

**Comment by rolandlo** [comment]
Maybe you don't have the permission to save into that system folder. Can you try putting the file somewhere into the Documents folder and see if it works?

**Comment by SleepyFrof** [comment]
Turns out it was that, thought I could keep it neatly in the same folder. Im not very knowledgeable about these kinda things, sorry for the inconvenience and thank you.

**Comment by lamteteeow** [comment]
> Maybe you don't have the permission to save into that system folder. Can you try putting the file somewhere into the Documents folder and see if it works?

@rolandlo do you know how you could provide Xournal++ the permission in Windows? It would be nice if you could share. Thank you in advance.
