### ISSUE TITLE
Error report dialog partially dysfunctional

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#4910]
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11 (Xfce)
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++:  latest git (1.1.3+dev, commit 7544c64a 
 - Installation method: AUR package from https://aur.archlinux.org/packages/xournalpp-git

**Describe the bug**
In the git version there is a dialog which pops up on launch if there are errorlog files currently present. However, some of the buttons are dysfunctional (the other ones work though): "Delete Logfile" and "Open Logfile directory" just close the dialog without any further action. "Send Bugreport" tries to open the following URL: https://github.com/xournalpp-git/xournalpp/issues/new Probably at least the latter problem is due to the packaging, as the package is called "xournalpp-git" rather than just "xournalpp". Maybe something should be changed in packaging?

**To Reproduce**
1. Build xournalpp-git
2. Run it
3. Try pressing the dysfunctional buttons "Delete Logfile", "Open Logfile directory" and "Send Bugreport".

**Expected behavior**
All buttons should work.

**Screenshots of Problem**
The dialog in question:
![Namenloses Fenster_001](https://github.com/xournalpp/xournalpp/assets/1191480/b118b252-1daa-4a3e-825a-bc21fe81282c)

**Comment by Photon89** [comment]
Now I installed the new release version https://archlinux.org/packages/extra/x86_64/xournalpp/ and observe the following:

- "Send Bugreport" tries to open https://github.com/srcdest/xournalpp/issues/new This is probably due to the fact that Arch Linux builds the contents of a package in a folder called `srcdest`.
- The "Open Logfile directory" still fails. The terminal gives

sh: line 1: nautilus: command not found
sh: line 1: dolphin: command not found
sh: line 1: konqueror: command not found

None of these file managers is available, here on Xfce it would be Thunar. Why not use `xdg-open /path/to/folder` instead of trying various file managers?

**Comment by bhennion** [comment]
There are several issues here

1. The bugreport link is computed from the git repository: 
 https://github.com/xournalpp/xournalpp/blob/ff6c7ab3612f91ef0dd0258b75b845f93326895b/cmake/include/GitRepo.cmake#L49
    I'm not sure why that is. @xournalpp/core does anyone know of any advantage of this? Why don't we simply hardcode the url, like is done when git is not found?
https://github.com/xournalpp/xournalpp/blob/ff6c7ab3612f91ef0dd0258b75b845f93326895b/cmake/include/GitRepo.cmake#L53
2. Yes, we should just rely on xdg-open for folders as well

**Comment by bhennion** [comment]
> 2\. Yes, we should just rely on xdg-open for folders as well

Actually, we do already in the upcoming version 1.2.1, available on branch `release-1.2`. This fix will be ported to the master branch as well.

**Comment by Photon89** [comment]
> Actually, we do already in the upcoming version 1.2.1, available on branch release-1.2. This fix will be ported to the master branch as well.

Great! 

Forgot to mention, the deleting works correctly now. So if the switch to `xdg-open` is in master as well, only the GitHub link is left to consider!

**Comment by rolandlo** [comment]
> 1. I'm not sure why that is. @xournalpp/core does anyone know of any advantage of this? Why don't we simply hardcode the url, like is done when git is not found?

It kind of makes sense to me to send bug reports to the repository origin owner (obtained via `git remote get-url origin`, the part between the last two slashes).

https://github.com/xournalpp/xournalpp/blob/cee58c573417b65f90c2368433bb920e426ba48e/cmake/include/GitRepo.cmake#L30-L41

Otherwise if someone clones the repo, bugreports will still be sent to us. 

I don't understand though, how `GIT_ORIGIN_OWNER` evaluated to `srcdest` for the arch linux package.
For the snap package and the flatpak `GIT_ORIGIN_OWNER` is `xournalpp`.

**Comment by Photon89** [comment]
I assume that the package metadata for Arch Linux is itself located in a git repo (Arch hosts its package metadata on a Gitlab instance: https://gitlab.archlinux.org/archlinux/packaging/packages/xournalpp/-/tree/main However, I couldn't find a literal `srcdest` searching the Gitlab...

**Comment by bhennion** [comment]
The way Arch's `makepkg` works with git repository is

1. it clones the repo into a directory containing sources to everything one builds
2. it clones the clone in the directory where the compilation and packaging will actually happen (so the original clone is left unaltered and only downloaded once -- this matters for huge repositories I guess).

When running `git remote get-url origin` in the clone of a clone, we get the local path to the first clone, and not the original distant. So you can get esentially anything depending on you building environment, but certainly not our url.

**Comment by Photon89** [comment]
Interestingly, on my initial test with the xournalpp-git AUR package, it correctly recognized "xournalpp-git", so, analogously, it should be "xournalpp" in the official xournalpp package. Both have been built with makepkg. Maybe the Arch package maintainers use some tools which mess up stuff though...

**Comment by rolandlo** [comment]
Ok, so we shouldn't rely on `git remote get-url origin`. Shall we just hard-code  `PROJECT_BUGREPORT` or shall we just fall back to it when`git remote get-url origin` returns a path instead of a internet resource?

**Comment by bhennion** [comment]
I would say hardcoding it would be best.

**Comment by rolandlo** [comment]
Fixed by #5084.
