### ISSUE TITLE
Windows Silent Installer puts shortcuts in User context

### ISSUE THREAD

**Issue by macxcool** [xournalpp/xournalpp#4919]
**Affects versions :** 1.1.3
 - OS: Windows
 - Which version of libgtk do you use
     - 3.24.34
 - Version of Xournal++: 1.1.3
 - .exe from Github

**Describe the bug**
When Xournal++ is installed using the Nullsoft '/S' switch (for silent installation), the program files are installed for the system (i.e. in c:\Program Files), but the shortcuts are put in the user profile (i.e. AppData\Roaming\Microsoft\Windows\Start Menu\Programs). The graphical installer (i.e. without '/S') defaults to the system Menu folder, so the silent install should do the same.

**To Reproduce**
1. Download the Xournal++ .exe from Github
2. Install on the command line using the '/S' Nullsoft installer switch

**Expected behavior**
I would expect the shortcuts to go into the system menu folder like they do with the graphical installer (by default),

**Comment by macxcool** [comment]
This is also related to #4445 and is the reason, I think, for that perceived behaviour.

**Comment by rolandlo** [comment]
This was fixed in the release branch via #5988.
