### ISSUE TITLE
Verify app

### ISSUE THREAD

**Issue by ovari** [xournalpp/xournalpp#4922]
It would be great to have this app as a verified app on [Flathub](https://flathub.org/apps/com.github.xournalpp.xournalpp).

Can this app please be [verified on Flathub](https://flathub-docs.vercel.app/docs/for-users/verification)?

Possible code pointers at https://github.com/flathub/eu.betterbird.Betterbird/issues/80

Thank you

**Comment by rolandlo** [comment]
Verification is under way now as I have been added to the members list on the flathub/com.github.xournalpp.xournalpp repo. Thus closing the issue.

**Comment by ovari** [comment]
Should this issue only be closed once verified on Flathub that is is verified? Thank you

**Comment by rolandlo** [comment]
It is verified now:

![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/1cb98633-ee68-46e0-908e-455ec889dcdd)
