### ISSUE TITLE
Error: Signal 11

### ISSUE THREAD

**Issue by avidseeker** [xournalpp/xournalpp#4923]
- OS: Arch Linux
 - libgtk: 3.24.38
 - Version of Xournal++: 1.1.3+dev (b1041980)
 - Manual compilation

Stack trace: https://paste.debian.net/1282564/

**Comment by bhennion** [comment]
This is going to be very difficult to track down. Does it happen often (with a similar backtrace)?

**Comment by bhennion** [comment]
This is most likely a duplicate of #4931
