### ISSUE TITLE
Allow customisation of keyboard shortcuts

### ISSUE THREAD

**Issue by Jeremy-Stafford** [xournalpp/xournalpp#4924]
When switching between tools using keyboard shortcuts, I find the default (eg. ctrl+shift+e) slow and difficult to press, due to the requirement to press 2 modifier keys. This is particularly the case for switching to the pen tool (ctrl+shift+p): I have to move my right hand (from either a mouse or stylus) to press the p key. 

This could be solved by allowing customisation of keyboard shortcuts.

Additionally, for users with more than 3 mouse buttons, you could allow tool selection using these.

**Alternatives**

1. Use 2-key (ctrl+blah) shortcuts as the default for tools. **Drawback**: changing keyboard shortcuts for existing users will be disruptive.
2. Signpost users to a system-level macro program (eg AutoHotKey). **Drawback**: Xournal++ should not require other software to be used productively.

**Comment by netlimpopo** [comment]
Hello! 
When moving to GTK4 custom shortcuts is one major goal to implement (will take a while least a year min.). It's a frequently asked feature, thats why the discussion is pinned on the top of the main page of the issues cathegory (#919) 
As a temporal work around there is Alt +Shift +D, which can be pressed with one hand only. 
It takes some practice to press those 2 modfier buttons. 
The is also the possibility to to write a plugin for button events. Autohotkey is pretty amazing 👍.

**Comment by Jeremy-Stafford** [comment]
Since there's already an issue with many more ideas than mine (which I managed to completely miss), I'll close this one. 

I'll have a look at plugins and I probably should learn AHK anyway.
