### ISSUE TITLE
parts of LaTeX equations not resizing in clipboard

### ISSUE THREAD

**Issue by RichardScharf** [xournalpp/xournalpp#4926]
**Affects versions :**
- OS: Linux Mint 20.3 x86_64
- Version of Xournal++: 1.1.3+dev
- Version of Inkscape: 1.2.2

**Describe the bug**
Equations containing square roots, fractions or boxes don't resize correctly when copied to clipboard

**To Reproduce**
1. Open the LaTeX tool
2. Type an equation containing square roots, fractions or boxes, e. g. `$\boxed{\sqrt{\frac{x^2}{4}}}$`
3. Press ok
4. Resize the equation to ~0.5 or less of its original size
5. Copy the equation to your clipboard
6. Paste the equation into Inkscape 

**Expected behavior**
The equation should not change in appearance after pasting from Xournal++ to Inkscape.

**Additional context**
Related to closed issue #4555 which was fixed by #4566

also related to #4916

**Comment by rolandlo** [comment]
Please use the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) to profit from the fix of #4555.

**Comment by RichardScharf** [comment]
@rolandlo 

Issue #4555 only fixed this behavior when exporting to .pdf and the rendering by Xournal++ respectively.

When copying a resized LaTeX formula (containing strokes) to clipboard the unwanted behavior remains.

When pasting into Inkscape the strokes are not resized.

I think it's strange that clipboard behavior was overlooked here.

**Comment by RichardScharf** [comment]
This issue seems to be similar to #3692
