### ISSUE TITLE
Corrupted autosave files

### ISSUE THREAD

**Issue by Badhunter0303** [xournalpp/xournalpp#4934]
![image](https://github.com/xournalpp/xournalpp/assets/135560450/29b8d4e4-ca53-4e91-8b76-b7cad1da65b4)

I had a power outage and the autosave/backup file isn't opening.

Windows 10, version: 1.1.3 +dev, gtk version: 3.24.38,

**Comment by rolandlo** [comment]
That doesn't look good. Is the file empty or what's its size? Do you have an autosave file (in the same folder, as the original document as the document has been saved already)? If you send me the original file and autosave file I can take a look to see what can be recovered. You can do that privately via the [Matrix channel](https://matrix.to/#/#xournalpp_xournalpp:gitter.im).

**Comment by Badhunter0303** [comment]
@rolandlo I sended a file there, it's another one cause I had another power outage (I hate the italian power company Enel Group)

**Comment by Badhunter0303** [comment]
"maybe the end is cut off??" 
![image](https://github.com/xournalpp/xournalpp/assets/135560450/e2afbe44-066a-49e5-9a13-ef1420acca60)

**Comment by rolandlo** [comment]
The files are corrupt, but I'll look into it and see what I can restore.

**Comment by Badhunter0303** [comment]
Ok, sad
![main-qimg-830acbc53c0ca15376dc8b251fef6e68-lq](https://github.com/xournalpp/xournalpp/assets/135560450/17b2f35e-e064-4521-a4d9-17e67a3b1f40)

**Comment by rolandlo** [comment]
Here is what I could restore (4 pages)
[restore.zip](https://github.com/xournalpp/xournalpp/files/13422414/restore.zip)

**Comment by Badhunter0303** [comment]
Yay, at least I don't have to rewrite everything.

@rolandlo I have a question: isn't the autosave file meant to protect against those types of things (power outages)? Why does it gets corrupted too?

**Comment by rolandlo** [comment]
Yes, the autosave files should protect against those types of things. I don't know, how it could happen, that the autosave file is corrupted. It should be investigated.

**Comment by rolandlo** [comment]
I'm closing the issue in view of #5361.
