### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Fefeffefe** [xournalpp/xournalpp#4941]
Date: Tue Mar  8 00:53:07 2022
Error: signal 11
[bt]: (0) xournalpp(+0xc46a0) [0x55815ecd96a0]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7fed788110c0]
[bt]: (2) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x6664d) [0x7fed795fd64d]
[bt]: (3) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x70989) [0x7fed79607989]
[bt]: (4) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x704cc) [0x7fed796074cc]
[bt]: (5) /lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_get_event+0x44) [0x7fed795cf0e4]
[bt]: (6) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x700e6) [0x7fed796070e6]
[bt]: (7) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7fed78eda17d]
[bt]: (8) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7fed78eda400]
[bt]: (9) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fed78eda4a3]
[bt]: (10) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7fed7911dfe5]
[bt]: (11) xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x55815ecda891]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fed787f20b3]
[bt]: (13) xournalpp(_start+0x2e) [0x55815ecd8e1e]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xc4b3c) [0x55815ecd9b3c]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7fed788110c0]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x6664d) [0x7fed795fd64d]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x70989) [0x7fed79607989]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x704cc) [0x7fed796074cc]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_get_event+0x44) [0x7fed795cf0e4]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x700e6) [0x7fed796070e6]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7fed78eda17d]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7fed78eda400]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fed78eda4a3]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7fed7911dfe5]
??:0
[bt] #12 xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x55815ecda891]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fed787f20b3]
??:0
[bt] #14 xournalpp(_start+0x2e) [0x55815ecd8e1e]
??:0

**Comment by bhennion** [comment]
Sorry for the late reply. The crashlog reported is from March 2022. The underlying problem has most likely been resolved since. I'm closing this issue. Please reopen if this happens again and if so, please provide a more recent crashlog.
