### ISSUE TITLE
Bug report, crash, assert(p.z > 0.0) in StrokeViewHelper.cpp

### ISSUE THREAD

**Issue by Simbi0z** [xournalpp/xournalpp#4943]
**Affects versions : 1.1.3+dev
 - OS: Archlinux
 - (Linux only) Desktop environment: sway
 - Which version of libgtk do you use: 3.24.38
 - Version of Xournal++: b1041980, master I guess.
 - Installation method: PKGBUILD trough yay package manager

**Describe the bug**
Complete crash, application closes.

**To Reproduce**
I wasn't even using the application when it crashed, I was messing with the xp-pen configuration app. The app has crashed several times I have not identified a pattern to follow to reproduce the bug, it may be at random. It has also crashed while not using the factory config app. 

**Expected behavior**
Not to crash

**Additional context**

```
** Message: 14:29:34.342: Autosaving to /home/user/.cache/xournalpp/autosaves/187965.autosave.xopp
** Message: 16:17:34.326: Info: autosave document...
** Message: 16:17:34.342: Autosave renamed from /home/user/.cache/xournalpp/autosaves/187965.autosave.xopp to /home/user/.cache
/xournalpp/autosaves/187965.old.autosave.xopp
** Message: 16:17:34.343: Autosaving to /home/user/.cache/xournalpp/autosaves/187965.autosave.xopp
xournalpp: /home/user/.cache/yay/xournalpp-git/src/xournalpp/src/core/view/StrokeViewHelper.cpp:42: xoj::view::StrokeViewHelper
::drawWithPressure(cairo_t*, const std::vector<Point>&, const LineStyle&, double)::<lambda(const Point&, const Point&)>: Assert
ion `p.z > 0.0' failed.

** (xournalpp:187965): WARNING **: 16:18:25.879: [Crash Handler] Crashed with signal 6

** (xournalpp:187965): WARNING **: 16:18:25.887: [Crash Handler] Wrote crash log to: /home/user/.cache/xournalpp/errorlogs/erro
rlog.20230623-161825.log

** (xournalpp:187965): WARNING **: 16:18:26.079: Trying to emergency save the current open document…

** (xournalpp:187965): WARNING **: 16:18:27.969: Successfully saved document to "/home/user/.config/xournalpp/emergencysave.xop
p"
```
I attach two error logs, one that refers to this specific crash and other from the previous day.

[errorlog.20230623-161825.log](https://github.com/xournalpp/xournalpp/files/11852913/errorlog.20230623-161825.log)
[errorlog.20230622-172031.log](https://github.com/xournalpp/xournalpp/files/11852921/errorlog.20230622-172031.log)

**Comment by Simbi0z** [comment]
BTW I have a xp-pen Deco 01 V2
Driver: xp-pen-tablet 3.2.3.230215-2
This happened while using the xanmod kernel, now I returned to stock kernel for unrelated reasons.
Is the driver informing negative pressures values or is xournal not reading them correctly?
In the diagnostic xp-pen tool pressure is shown as always > 0.

**Comment by bhennion** [comment]
This seems to be the same issue as in #5025. @Simbi0z could you have a look at [this post](https://github.com/xournalpp/xournalpp/issues/5025#issuecomment-1669878074)?

I'm closing this ticket (although it was there before...) in favor of #5025.
