### ISSUE TITLE
New latex bug

### ISSUE THREAD

**Issue by Badhunter0303** [xournalpp/xournalpp#4947]
I wrote something math related in latex but it's not showing for some reason

<img width="216" alt="Screenshot_5" src="https://github.com/xournalpp/xournalpp/assets/135560450/3d170d78-34ff-404e-b78a-90816170aaca">

Version: 1.1.3+dev   GTK 3.24.38

**Comment by Badhunter0303** [comment]
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(c:/Users/Vinicius/AppData/Local/Temp/xournalpp-22188/tex/tex.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30>
(c:/texlive/2023/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(c:/texlive/2023/texmf-dist/tex/latex/tools/shellesc.sty)
(c:/texlive/2023/texmf-dist/tex/generic/iftex/ifluatex.sty
(c:/texlive/2023/texmf-dist/tex/generic/iftex/iftex.sty))
(c:/texlive/2023/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(c:/texlive/2023/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(c:/texlive/2023/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(c:/texlive/2023/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(c:/texlive/2023/texmf-dist/tex/latex/standalone/standalone.cfg)
(c:/texlive/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(c:/texlive/2023/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/2023/texmf-dist/tex/latex/varwidth/varwidth.sty))
(c:/texlive/2023/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(c:/texlive/2023/texmf-dist/tex/latex/amsmath/amstext.sty
(c:/texlive/2023/texmf-dist/tex/latex/amsmath/amsgen.sty))
(c:/texlive/2023/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(c:/texlive/2023/texmf-dist/tex/latex/amsmath/amsopn.sty))
(c:/texlive/2023/texmf-dist/tex/latex/amsfonts/amssymb.sty
(c:/texlive/2023/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(c:/texlive/2023/texmf-dist/tex/latex/was/icomma.sty)
(c:/texlive/2023/texmf-dist/tex/latex/scontents/scontents.sty
(c:/texlive/2023/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
(c:/texlive/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)))
(c:/texlive/2023/texmf-dist/tex/generic/scontents/scontents-code.tex))
(c:/texlive/2023/texmf-dist/tex/latex/base/ifthen.sty)
(c:/texlive/2023/texmf-dist/tex/latex/xcolor/xcolor.sty
(c:/texlive/2023/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(c:/texlive/2023/texmf-dist/tex/latex/graphics-def/pdftex.def)
(c:/texlive/2023/texmf-dist/tex/latex/graphics/mathcolor.ltx)) (./tex.aux)
(c:/texlive/2023/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (c:/texlive/2023/texmf-dist/tex/latex/amsfonts/umsa.fd)
(c:/texlive/2023/texmf-dist/tex/latex/amsfonts/umsb.fd) [1{c:/texlive/2023/texm
f-var/fonts/map/pdftex/updmap/pdftex.map}] (./tex.aux) )<c:/texlive/2023/texmf-
dist/fonts/type1/public/amsfonts/cm/cmr10.pfb><c:/texlive/2023/texmf-dist/fonts
/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on tex.pdf (1 page, 23312 bytes).
Transcript written on tex.log.

**Comment by tmelorc** [comment]
All the code inserted is in math mode by default, so to insert text you have to use some trick. 

For example:
`\text{utilizamos $\approx$ para expressar aproximação}`

![Inserir camada_001](https://github.com/xournalpp/xournalpp/assets/15181573/f45697a5-ec1b-4e9c-9a83-3804f6dc86db)

**Comment by rolandlo** [comment]
I think this issue is resolved. Closing therefore.
