### ISSUE TITLE
black text on black active area can't be read

### ISSUE THREAD

**Issue by Whyglobaleyes** [xournalpp/xournalpp#4951]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Desktop environment: Regolith:GNOME-Flashback:GNOME
 - Session type: X11
 - Which version of libgtk: libgtk-3-0:amd64             3.24.24-4+deb11u3
 - Version of Xournal++: 1:0.4.8.2016-7 amd64
 - Installation method: official release via apt-get

**Describe the bug**
When adding text (ctrl-shft-t) I see a black "active area box" on the document. When I (run a test and) use coloured text I can read it while editing, However my normal usage is to insert black text to a pdf and I can't see that on the black active area while editing. The black text shows properly once editing is finished.

**To Reproduce**
1. open a pdf for annotation
2. ctrl-shft-t -or- click the "T" icon on the toolbar
3. click anywhere in the pdf to add text ==> black active area box appears

**Expected behavior**
(a) I would anticipate a semi-transparent active area box (so that I can still see the original PDF underneath and 
(b) I would hope for the colour of the active area to change depending on the active text colour - and be contrasting to the text colour

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment]
Are you using Xournal++ or Xournal? From the version 0.4.8.2016-7 it seems you are using Xournal. Then we can't help, since that's a different software. 
I don't get a black active area. Can you please add a screenshot?

**Comment by bhennion** [comment]
Closing this, assuming this related to Xournal and not Xournal++. Please reopen if this assumption was wrong.
