### ISSUE TITLE
Ukrainian language adding

### ISSUE THREAD

**Issue by chymax3m** [xournalpp/xournalpp#4953]
Hi,
I'd like to ask to unlock the Ukrainian language in Crowdin.
I do not promise to translate much, but some times I have a will and some extra time)
Thank you in advance.

**Comment by bhennion** [comment]
@rolandlo I don't have the rights to do that on Crowdin. Would you mind taking care of it?

**Comment by rolandlo** [comment]
> @rolandlo I don't have the rights to do that on Crowdin. Would you mind taking care of it?

Done!
