### ISSUE TITLE
No text display on android and online apps

### ISSUE THREAD

**Issue by flckf** [xournalpp/xournalpp#4955]
**Affects versions :**
 - OS: Android and xournal.online
  - Version of Xournal++: 1.1.11

**Describe the bug**
If I open any of my many xournalpp files with text the text doesn't appear, but everything else appears (i.e. pasted images/ handwritten notes etc). Formatting and everything is present and correct, just there isn't any text displayed. I have tried this on the android app and also using xournal.online on a windows desktop computer (firefox). The windows app works fine (which is where all the files were created). I have tried with multiple different files and it is always the same.

**To Reproduce**
As above

**Expected behavior**
It should display the text 

.

**Comment by rolandlo** [comment]
Can you provide us one of these .xopp files where the text doesn't appear? It may be a problem with fonts, so let us investigate. We can't do anything about the Android app and xournal.online though. Issues with the mobile version should be reported at https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile. Unfortunately the (only) developer of the mobile app is currently not responding to any isssues.

**Comment by flckf** [comment]
Many thanks - xopp file attached. I didn't consider fonts as a possibility so on the file I tried several different fonts but none of them displayed. I'll report the issue there just in case!

The file is uploaded as a zip as it tells me .xopp files aren't supported. If you want to download it directly you can get it from my dropbox [here](https://www.dropbox.com/s/xuvybxtkvaz06up/Font%20test.xopp?dl=0).
[Font test.zip](https://github.com/xournalpp/xournalpp/files/12077560/Font.test.zip)

**Comment by rolandlo** [comment]
The file looks fine. I can reproduce the issue on `xournal.online`.

**Comment by rolandlo** [comment]
Ok, I will close the issue therefore.
