### ISSUE TITLE
Dark papers

### ISSUE THREAD

**Issue by fMagVen** [xournalpp/xournalpp#4957]
Dark coloured papers would be cool, similar to how we can tap switch background and set them dark on OneNote and write with light coloured ink. Nice touch for those who go full dark mode on their systems for tired eyes.

![switch background](https://github.com/xournalpp/xournalpp/assets/78576546/e48c056f-5208-43c7-b27a-77499ec2ebea)

**Comment by bhennion** [comment]
Paper colors are entirely configurable already. You can pick a dark color if you want.
Closing this ticket.

**Comment by fMagVen** [comment]
Thank you for your help, I didn't see it, is there a way to change colors of these areas marked with the blue whirls?
![Unsaved Image 1](https://github.com/xournalpp/xournalpp/assets/78576546/3282b61d-4ad8-43a2-b928-1e67f81f29de)

**Comment by KlausBlum** [comment]
Edit > Preferences > View > Background color between pages  
  
  
![Zwischenablage01](https://github.com/xournalpp/xournalpp/assets/25407329/1e0d3770-ba14-48b2-848c-c53ed3d1b1d5)  
![Zwischenablage02](https://github.com/xournalpp/xournalpp/assets/25407329/d7d4ef5d-0a07-4bb8-9c78-1216d6c3abc4)

**Comment by fMagVen** [comment]
Most beautiful looking app, I thank you the devs for such a wonderful tool
![xourn](https://github.com/xournalpp/xournalpp/assets/78576546/87b56e1f-c226-45ef-826b-6889bf1f220c)

**Comment by ethanc8** [comment]
Would it be possible to make these colors change when the system dark/light mode is changed? It would be annoying to manually configure it every time I switch. (I switch between dark and light mode depending on the time of day and how brightly lit my room is.)
