### ISSUE TITLE
Font typeface and other characteristics get stuck and won't change when selecting new fonts

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#4958]
MacOS (using M2 rosetta)

Currently using latest nightly build of 20230717

I am able to change the font typeface one or two times, then it gets stuck, even between launches somehow. So while I can change certain characteristics such as Bold, Italic, etc by choosing fonts that have such features, Other aspects get stuck: for example I was using a sans-serif Arial and then switched to any of a list of serif fonts, but the sans-serif got stuck. If I selected a Bold serif font, my arial style would become more bold, but would still not have serifs. Same with selecting a serif typeface with Italics. The font would show italic, but the sans serif would stick.

Had been able to use Arial or any other font, including fonts with ligatures (I use MusAnalysis font) and they would work just fine. Then I returned to Arial, and since then it has been stuck. The MusAnalysis font with ligatures just show Arial, Outline fonts just show Arial, Scripts fonts just show Arial, Times Roman just shows Arial, etc.

To make matters worse, once this problem starts, and one tries to select a different font (possibly by typing fontname in searchbar), the mouse right-click and middle-click and left-click functions get scrambled... For example I have my middle mouse button set to open the floating toolbar, my right-mouse set to hand, and my left-mouse set to default or pen. Well after trying to select a different font face, my right-mouse, left-mouse AND middle-mouse buttons are all mapped into the middle mouse click, and no matter which button I click the floating toolbar opens. This can go on for about 10 to 50 clicks before suddenly returning to normal mouse function, with no obvious and repeatable reason why...

This is new behavior which I have never noticed before and I am a daily user of the program for more than a year. I could be that because I have started using this new font (MusAnalysis) I am hitting this bug because I am switching fonts whereas I used to go months without switching fonts, and then only once.

**Comment by natobsid** [comment]
Just searched for this—seems like it's happening for me too. I'm on MacOS 11.2 Big Sur. What's odd is that though I've had font issues with Xournal++ in the past, they were to do with Xournal not seeing the font. Now it finds them in the menu but doesn't apply them so I get a san-serif font (probably Arial) no matter what I choose. I **can** change font size though.

**Comment by ilanag1** [comment]
I have the very same problem on an Ubuntu 20.04.6.

**Comment by rolandlo** [comment]
This issue has been solved in the meantime. By the way a MacOS ARM build has been released with version 1.2.4.
