### ISSUE TITLE
Deleting text in empty text box 

### ISSUE THREAD

**Issue by scorelowless** [xournalpp/xournalpp#4959]
**Affects versions :**
 - OS: Windows 10
 - Version of libgtk: 3.24.34
 - Version of Xournal++: 1.1.3
 - Installation method: official release

**Describe the bug**
When I try to tap backspace/delete on the keyboard while in a text box that doesn't have any text written, windows plays an error sound

**To Reproduce**
1. Open Xournal++
2. Make sure your system audio volume is non zero 
3. Select "Text" tool
4. Create a text box by clicking anywhere on the page
5. Click backspace/delete key and listen if there's any system sound played

**Expected behavior**
Tapping backspace/delete key shouldn't do anything if the text box is empty

**Additional context**
Changing device classes of input devices in preferences doesn't make any difference

**Comment by scorelowless** [comment]
But it doesn't happen almost anywhere else. I have a feeling that the devs simply forgot to add a check if the text length is 0 before deleting a character, thus it throws the error

**Comment by bhennion** [comment]
https://github.com/xournalpp/xournalpp/blob/030727652542b3af8d11279558668c34b0054ba2/src/core/control/tools/TextEditor.cpp#L852-L857

It looks like it's on purpose in the code.

You should be able to configure the error bells though, via `GtkSettings:gtk-error-bell` (see [here](https://docs.gtk.org/gtk3/method.Widget.error_bell.html)).
Adding a line with `gtk-error-bell=false` in your Gtk's `settings.ini` (somewhere in etc/gtk-3.0/settings.ini in your installation directory) should do the trick.

Closing this ticket.
