### ISSUE TITLE
Replace color with alpha on pasted image (Plugin?)

### ISSUE THREAD

**Issue by RichardScharf** [xournalpp/xournalpp#4960]
**Is your feature request related to a problem? Please describe.**
Most images I paste into Xournal++ tend to be screenshots taken from .pdf files.
Before pasting I usually paste into GIMP first, then select pixels by color (using ctrl+o) click on a white pixel, invert the selection (using ctrl+I) then copy the image again to remove the white background.

**Describe the solution you'd like**
I'd like to have a plugin that replaces all white pixels inside an image on paste/embed with (transparent) alpha pixels. 
- Optionally with a menu that allows choosing the color to be replaced

**Describe alternatives you've considered**
There are of course a lot of alternative ways to make this work on Linux, but I still wonder if it's possible to implement this functionality as a simple plugin directly in Xournal++ as this seemed to be fit for a "good first issue" (or enhancement) to contribute?

**Additional Context**
As I am neither familiar with the sourcecode of Xournal++ itself nor the plugin API I wondered if anyone more familiar with it could gauge the difficulty/feasibility before I would attempt such a contribution myself

**Comment by rolandlo** [comment]
That's an interesting idea. I will work on adding and manipulating images through plugins (see #4884 for a start). On the Lua side images can be manipulated through [lua-vips](https://github.com/rolandlo/lua-vips/tree/fix-lua-5.3). The plugin could then first paste the image and then manipulate it to replace pixels of any color with transparent background. It will take work to get there, but I think adding some ways to manipulate images through the plugin API can be interesting for many reasons.
You can already check how to replace pixels of some color by transparent background via lua-vips (or at least via vips).

**Comment by rolandlo** [comment]
The plugin  in #4884 can now basically do what you wanted. See here:

[TransparencyDemo.webm](https://github.com/xournalpp/xournalpp/assets/40485433/32c0a93a-2b6d-435a-aa70-1223596a9eb3)

**Comment by rolandlo** [comment]
Closing in view of #4884 being merged.
