### ISSUE TITLE
GCC-13 Compilation Failure

### ISSUE THREAD

**Issue by barak** [xournalpp/xournalpp#4961]
The Debian automated QA systems are flagging packages that fail to build using GCC-13. The Xournal++ package, which is at release version 1.1.3, has this issue.

Bug report here: https://bugs.debian.org/1037904

Sample of errors:
```
   28 |     bool loadValueHex(const std::string& key, uint32_t& value) const;
      |                                               ^~~~~~~~
/<<PKGBUILDDIR>>/src/view/background/BackgroundConfig.h:28:10: error: ‘bool BackgroundConfig::loadValueHex(const std::string&, int&) const’ cannot be overloaded with ‘bool BackgroundConfig::loadValueHex(const std::string&, int&) const’
...

/<<PKGBUILDDIR>>/src/view/background/BackgroundConfig.cpp: At global scope:
/<<PKGBUILDDIR>>/src/view/background/BackgroundConfig.cpp:62:56: error: ‘uint32_t’ has not been declared
   62 | auto BackgroundConfig::loadValueHex(const string& key, uint32_t& value) const -> bool {
      |                                                        ^~~~~~~~
/<<PKGBUILDDIR>>/src/view/background/BackgroundConfig.cpp:62:6: error: redefinition of ‘bool BackgroundConfig::loadValueHex(const std::string&, int&) const’
   62 | auto BackgroundConfig::loadValueHex(const string& key, uint32_t& value) const -> bool {
      |      ^~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/src/view/background/BackgroundConfig.cpp:52:6: note: ‘bool BackgroundConfig::loadValueHex(const std::string&, int&) const’ previously defined here
   52 | auto BackgroundConfig::loadValueHex(const string& key, int& value) const -> bool {
      |      ^~~~~~~~~~~~~~~~
...
```

**Comment by bhennion** [comment]
This has been fixed in master by #4912.

**Comment by barak** [comment]
That's great.

Xournal++ will be removed from Debian testing on 4th August if this isn't dealt with before then. So here are my options:

- If there's going to be a release soon, like before then, I can use that.
- If you think the current master tip is stable, I can use that.
- Or I can backport the fix, which looks like a bit of a pain.

Any recommendation?

**Comment by rolandlo** [comment]
I think we can release version 1.2 before 4th August. Next week I will have lots of time to update the authors list, check and update the changelog. Other than that we are ready to go for the release.

**Comment by barak** [comment]
Excellent.

I'll test-package the current master to make sure all the scripts are in shape for 1.2 when it drops.
