### ISSUE TITLE
Windows uninstall.exe leaves Registry entries in Uninstall

### ISSUE THREAD

**Issue by macxcool** [xournalpp/xournalpp#4978]
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 
     - 1.2
 - Official Windows release - .zip/Nullsoft installer

**Describe the bug**
The Nullsoft Uninstall (uninstall.exe) leaves "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Xournal++" instead of deleting it after the uninstall is complete.

**To Reproduce**
1. Install Xpp with Windows Nullsoft installer
2. Uninstall Xpp 
3. Check registry for Xournal++ key under Uninstall

**Expected behavior**
The Xournal++ key under Uninstall should be removed as part of the uninstall process.

**Comment by rolandlo** [comment]
This was fixed in the release branch via #5988.
