### ISSUE TITLE
The web app is not available at xournal.online.

### ISSUE THREAD

**Issue by Dtrieb** [xournalpp/xournalpp#4987]
The web app is **NOT** available at [xournal.online](https://xournal.online/).

**Comment by JohnEdChristensen** [comment]
The Readme links to this site, so it may make sense to remove this link as it looks like the web app is not maintained. 

The web app is going to be the first place people go to check out the project, since it doesn't require an install. It's not a good look to have a dead link be the first experience with the project.

**Comment by rolandlo** [comment]
> The Readme links to this site, so it may make sense to remove this link as it looks like the web app is not maintained.
> 
> The web app is going to be the first place people go to check out the project, since it doesn't require an install. It's not a good look to have a dead link be the first experience with the project.

I can confirm that the website `xournal.online` is down, having tried it. Although we have lost contact to the developer of the mobile version, we can for sure remove the link to the mobile version and explain the situation. Unfortunately the mobile version looks dead (no update for more than 1.5 years) and we can only hope that someone steps up, forks the repo and gets in contact with us, so we can link to the new project.

**Comment by SaphireLattice** [comment]
A lot of places link towards `xournal.online`, including the current version of the readme. The Xournal++ website links to repo and that in turn links to the zombie domain redirecting to malicious and advertising sites.

Not really a pleasant thing to get when looking around, overall.
