### ISSUE TITLE
Please add a pdf word selector~

### ISSUE THREAD

**Issue by adcemdmf** [xournalpp/xournalpp#4990]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bhennion** [comment]
PDF text can aleady be selected, copied, highlighted and so on.

**Comment by adcemdmf** [comment]
hello，i am using the latest stable version，but i didn't find the pdf selector. could you tell me which tool i should use to select the text ?



---Original---
From: "Benjamin ***@***.***&gt;
Date: Wed, Aug 2, 2023 03:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xournalpp/xournalpp] Please add a pdf word selector~ (Issue#4990)




 
PDF text can aleady be selected, copied, highlighted and so on.

**Comment by moriro** [comment]
I found it
Tools/Select Linear Text （Shift+Ctrl+W）

**Comment by adcemdmf** [comment]
thank you， i found it in dev version.



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 3, 2023 15:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xournalpp/xournalpp] Please add a pdf word selector~ (Issue#4990)




 
I found it
 Tools/Select Linear Text （Shift+Ctrl+W）
