### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by YuruiHong** [xournalpp/xournalpp#4994]
Date: Sat Jul  2 10:21:40 2022
Error: signal 11
[bt]: (0) xournalpp(+0xbe431) [0x557179e30431]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7f01ec0b4d60]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x17) [0x557179e8bec7]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe22) [0x557179e802f2]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x557179e6e239]
[bt]: (5) xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xd3) [0x557179e6e5f3]
[bt]: (6) xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0xa9c) [0x557179e6f53c]
[bt]: (7) xournalpp(+0xc4cde) [0x557179e36cde]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x182) [0x7f01ec9bd0a2]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x26413) [0x7f01ec9cf413]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xbbf) [0x7f01ec9d56cf]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f01ec9d5c3f]
[bt]: (12) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x122) [0x7f01ecb09d92]
[bt]: (13) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xdf17a) [0x7f01ecb0a17a]
[bt]: (14) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x12e) [0x7f01ecb0a4ae]
[bt]: (15) xournalpp(_ZN11XournalMain3runEiPPc+0x49c) [0x557179e3317c]
[bt]: (16) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f01ec09fd0a]
[bt]: (17) xournalpp(_start+0x2a) [0x557179e2fb7a]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xbe9ad) [0x557179e309ad]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7f01ec0b4d60]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x17) [0x557179e8bec7]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe22) [0x557179e802f2]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x557179e6e239]
??:0
[bt] #6 xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xd3) [0x557179e6e5f3]
??:0
[bt] #7 xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0xa9c) [0x557179e6f53c]
??:0
[bt] #8 xournalpp(+0xc4cde) [0x557179e36cde]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x182) [0x7f01ec9bd0a2]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x26413) [0x7f01ec9cf413]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xbbf) [0x7f01ec9d56cf]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f01ec9d5c3f]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x122) [0x7f01ecb09d92]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xdf17a) [0x7f01ecb0a17a]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x12e) [0x7f01ecb0a4ae]
??:0
[bt] #16 xournalpp(_ZN11XournalMain3runEiPPc+0x49c) [0x557179e3317c]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f01ec09fd0a]
??:0
[bt] #18 xournalpp(_start+0x2a) [0x557179e2fb7a]
??:0

**Comment by Febbe** [comment]
Thank you for the bug report, your app crashed on Date: Sat Jul 2 10:21:40 2022, since v.1.20 we show old crashes on startup. Since that crash is so old, it is possibly fixed already, just delete the log and carry on. Please reopen an issue, when you have a more recent crash or when you can reproduce this crash.
