### ISSUE TITLE
It keeps saying my xournalpp has error log files everytime i open the app.

### ISSUE THREAD

**Issue by Arnab-Chowdhury** [xournalpp/xournalpp#4998]
Date: Sun Sep 18 14:13:35 2022
Error: signal 11
[bt]: (0) xournalpp(+0x2060a9) [0x5631c491a0a9]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x39510) [0x7f675bdba510]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x1456e3) [0x7f675bec66e3]
[bt]: (3) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_param_spec_pool_lookup+0x67) [0x7f675c641697]
[bt]: (4) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_get_valist+0xc1) [0x7f675c63ced1]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_get+0xff) [0x7f675c63d44f]
[bt]: (6) xournalpp(_ZN21ToolbarDragDropHelper31gdk_context_set_icon_from_imageEP15_GdkDragContextP10_GtkWidget+0x112) [0x5631c48bab72]
[bt]: (7) xournalpp(_ZN14ToolbarAdapter17toolitemDragBeginEP10_GtkWidgetP15_GdkDragContextPv+0x4b) [0x5631c48b709b]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__OBJECTv+0x76) [0x7f675c637e66]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x17798) [0x7f675c634798]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x104b) [0x7f675c64ed6b]
[bt]: (11) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_by_name+0x220) [0x7f675c64f1c0]
[bt]: (12) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3f3917) [0x7f675cf5d917]
[bt]: (13) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d290) [0x7f675cce7290]
[bt]: (14) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xa6e81) [0x7f675cc10e81]
[bt]: (15) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x179) [0x7f675c634569]
[bt]: (16) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2afbf) [0x7f675c647fbf]
[bt]: (17) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x9db) [0x7f675c64e6fb]
[bt]: (18) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f675c64ef83]
[bt]: (19) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a3e84) [0x7f675cf0de84]
[bt]: (20) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23033f) [0x7f675cd9a33f]
[bt]: (21) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x7bc) [0x7f675cd9bfec]
[bt]: (22) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x418e2) [0x7f675ca9f8e2]
[bt]: (23) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9f2af) [0x7f675cafd2af]
[bt]: (24) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x19b) [0x7f675d3f2cdb]
[bt]: (25) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5a1e8) [0x7f675d3f31e8]
[bt]: (26) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34) [0x7f675d3f32b4]
[bt]: (27) /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1ad) [0x7f675c77725d]
[bt]: (28) xournalpp(_ZN11XournalMain3runEiPPc+0x56c) [0x5631c47fad9c]
[bt]: (29) /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f675bda4b80]
[bt]: (30) xournalpp(_start+0x2e) [0x5631c47d239e]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x2065bb) [0x5631c491a5bb]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x39510) [0x7f675bdba510]
[bt] #3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x1456e3) [0x7f675bec66e3]
[bt] #4 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_param_spec_pool_lookup+0x67) [0x7f675c641697]
[bt] #5 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_get_valist+0xc1) [0x7f675c63ced1]
[bt] #6 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_get+0xff) [0x7f675c63d44f]
[bt] #7 xournalpp(_ZN21ToolbarDragDropHelper31gdk_context_set_icon_from_imageEP15_GdkDragContextP10_GtkWidget+0x112) [0x5631c48bab72]
[bt] #8 xournalpp(_ZN14ToolbarAdapter17toolitemDragBeginEP10_GtkWidgetP15_GdkDragContextPv+0x4b) [0x5631c48b709b]
[bt] #9 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__OBJECTv+0x76) [0x7f675c637e66]
[bt] #10 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x17798) [0x7f675c634798]
[bt] #11 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x104b) [0x7f675c64ed6b]
[bt] #12 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_by_name+0x220) [0x7f675c64f1c0]
[bt] #13 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3f3917) [0x7f675cf5d917]
[bt] #14 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d290) [0x7f675cce7290]
[bt] #15 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xa6e81) [0x7f675cc10e81]
[bt] #16 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x179) [0x7f675c634569]
[bt] #17 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2afbf) [0x7f675c647fbf]
[bt] #18 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x9db) [0x7f675c64e6fb]
[bt] #19 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f675c64ef83]
[bt] #20 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a3e84) [0x7f675cf0de84]
[bt] #21 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23033f) [0x7f675cd9a33f]
[bt] #22 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x7bc) [0x7f675cd9bfec]
[bt] #23 /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x418e2) [0x7f675ca9f8e2]
[bt] #24 /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9f2af) [0x7f675cafd2af]
[bt] #25 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x19b) [0x7f675d3f2cdb]
[bt] #26 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5a1e8) [0x7f675d3f31e8]
[bt] #27 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34) [0x7f675d3f32b4]
[bt] #28 /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1ad) [0x7f675c77725d]
[bt] #29 xournalpp(_ZN11XournalMain3runEiPPc+0x56c) [0x5631c47fad9c]
[bt] #30 /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f675bda4b80]
[bt] #31 xournalpp(_start+0x2e) [0x5631c47d239e]

**Comment by rolandlo** [comment]
You can delete the errorlog, then the message won't appear again.
