### ISSUE TITLE
Highlighted text not recognised by other applications.

### ISSUE THREAD

**Issue by polarlicht** [xournalpp/xournalpp#5001]
**Is your feature request related to a problem? Please describe.**
When I import a .pdf, highlight some text with the new "Select Linear PDF Text"-Tool and export it as a .pdf again, other programs do not truly recognise the highlighted parts as what they are.

**Describe the solution you'd like**
It would be useful to have Xournal export highlights done with the "Select Linear PDF Text"-Tool save in a way that makes it compatible (editable/recognisable) with popular pdf-readers/editors like Okular, Adobe Reader, Chromium, Foxit Reader etc.

_Example why this is useful 1_
Green highlight done in XPP, Yellow highlight done in Okular. Opened the document in Chromium:
![image](https://github.com/xournalpp/xournalpp/assets/39636399/02a783b7-0adc-47e7-88a9-a6e8b4602c57)

When disabling annotations, only the highlight from Okular disappears:
![image](https://github.com/xournalpp/xournalpp/assets/39636399/2505a8a8-83c2-428d-99c9-ca853605f261)

_Example why this is useful 2_
Some programs display only the highlighted bits of your document (very useful), e.g. JabRef, a program to organise scientific literature. 
After importing the same .pdf from example 1, JabRef only recognises the highlight from Okular:
![image](https://github.com/xournalpp/xournalpp/assets/39636399/919bb3e5-cb24-40af-933d-08beea789c9e)

**Describe alternatives you've considered**
I don't know what else to do other than do my highlights with another program.

**Comment by alvaroars** [comment]
In general, all the handwritten comments should be editable once the pdf has been created. That is, the annotations should be recognized by, for instance, Adobe Reader.

**Comment by polarlicht** [comment]
> In general, all the handwritten comments should be editable once the pdf has been created. That is, the annotations should be recognized by, for instance, Adobe Reader.

I am not

**Comment by polarlicht** [comment]
> In general, all the handwritten comments should be editable once the pdf has been created. That is, the annotations should be recognized by, for instance, Adobe Reader.

I am not sure we are talking about the same thing... Everything I do in xpp is shown in other program, thats true, but text-highlight is not recognized as such, for other programs its just a coloured box basically...

**Comment by aromaniega** [comment]
https://xournalpp.github.io/guide/pdfs/#exporting-to-pdf this is related
