### ISSUE TITLE
Again: Xournal++ does not stop to send a warning. Ubuntu 22.04.

### ISSUE THREAD

**Issue by LautaroVergara** [xournalpp/xournalpp#5005]
Date: Tue Mar 28 10:41:06 2023
Error: signal 11
[bt]: (0) /snap/xournalpp/69/usr/bin/xournalpp(+0x435b8a) [0x559a17af9b8a]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fe5ac0a2090]
[bt]: (2) [0x559a1864f5f0]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/69/usr/bin/xournalpp(+0x4360fc) [0x559a17afa0fc]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fe5ac0a2090]
??:0
[bt] #3 [0x559a1864f5f0]
??:0

**Comment by Febbe** [comment]
Since version 1.2 we show the user, that xournalpp crashed and that a crash log has been created. Since xournalpp also created crashlogs before, many users have a bunch of them in their log directory. Just open the directory and clean it.
