### ISSUE TITLE
Error: signal 6

### ISSUE THREAD

**Issue by bmany** [xournalpp/xournalpp#5006]
Date: Fri Aug  4 11:41:38 2023
Error: signal 6
Xournal++ version 1.2.0
Gtk version 3.24.20

[bt]: (0) xournalpp(+0xe2ec6) [0x5613da9f8ec6]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f5a902c3090]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f5a902c300b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f5a902a2859]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(+0x22729) [0x7f5a902a2729]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x33fd6) [0x7f5a902b3fd6]
[bt]: (6) xournalpp(+0x216592) [0x5613dab2c592]
[bt]: (7) xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x35c) [0x5613dab64adc]
[bt]: (8) xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0xf4) [0x5613daae1aa4]
[bt]: (9) xournalpp(+0x14b8d7) [0x5613daa618d7]
[bt]: (10) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (11) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (13) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2a3131) [0x7f5a911ee131]
[bt]: (14) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x38d709) [0x7f5a912d8709]
[bt]: (15) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (16) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x38e441) [0x7f5a912d9441]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (19) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (20) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (21) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d156d) [0x7f5a9121c56d]
[bt]: (22) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (23) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (24) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2cf845) [0x7f5a9121a845]
[bt]: (25) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (26) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (27) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (28) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12deb8) [0x7f5a91078eb8]
[bt]: (29) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (30) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (31) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1307d5) [0x7f5a9107b7d5]
[bt]: (32) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (33) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (34) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (35) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12deb8) [0x7f5a91078eb8]
[bt]: (36) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (37) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (38) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1307d5) [0x7f5a9107b7d5]
[bt]: (39) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (40) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (41) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (42) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12deb8) [0x7f5a91078eb8]
[bt]: (43) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (44) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (45) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1307d5) [0x7f5a9107b7d5]
[bt]: (46) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (47) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (48) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (49) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12deb8) [0x7f5a91078eb8]
[bt]: (50) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
[bt]: (51) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
[bt]: (52) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1307d5) [0x7f5a9107b7d5]
[bt]: (53) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (54) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (55) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (56) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (57) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
[bt]: (58) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
[bt]: (59) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3ab555) [0x7f5a912f6555]
[bt]: (60) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
[bt]: (61) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a5de0) [0x7f5a912f0de0]
[bt]: (62) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x874) [0x7f5a9119a164]
[bt]: (63) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3cf69) [0x7f5a90e80f69]
[bt]: (64) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4e2b1) [0x7f5a90e922b1]
[bt]: (65) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4f485) [0x7f5a90e93485]
[bt]: (66) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4f644) [0x7f5a90e93644]
[bt]: (67) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7f5a90b8ea56]
[bt]: (68) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1038) [0x7f5a90badb48]
[bt]: (69) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f5a90bae0f3]
[bt]: (70) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x46cc3) [0x7f5a90e8acc3]
[bt]: (71) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x30f4d) [0x7f5a90e74f4d]
[bt]: (72) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7f5a90aa0be8]
[bt]: (73) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f5a90aa004e]
[bt]: (74) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f5a90aa0400]
[bt]: (75) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f5a90aa04a3]
[bt]: (76) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f5a90ce4fe5]
[bt]: (77) xournalpp(_ZN11XournalMain3runEiPPc+0x50f) [0x5613da9fa5ff]
[bt]: (78) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f5a902a4083]
[bt]: (79) xournalpp(_start+0x2e) [0x5613da9f837e]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xe345a) [0x5613da9f945a]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f5a902c3090]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f5a902c300b]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f5a902a2859]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(+0x22729) [0x7f5a902a2729]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x33fd6) [0x7f5a902b3fd6]
??:0
[bt] #7 xournalpp(+0x216592) [0x5613dab2c592]
??:0
[bt] #8 xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x35c) [0x5613dab64adc]
??:0
[bt] #9 xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0xf4) [0x5613daae1aa4]
??:0
[bt] #10 xournalpp(+0x14b8d7) [0x5613daa618d7]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2a3131) [0x7f5a911ee131]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x38d709) [0x7f5a912d8709]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x38e441) [0x7f5a912d9441]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d156d) [0x7f5a9121c56d]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2cf845) [0x7f5a9121a845]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ca94) [0x7f5a912e7a94]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x1eb) [0x7f5a910c811b]
??:0
[bt] #28 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17d1ed) [0x7f5a910c81ed]
??:0
[bt] #29 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12deb8) [0x7f5a91078eb8]
??:0
[bt] #30 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x182491) [0x7f5a910cd491]
??:0
[bt] #31 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18733c) [0x7f5a910d233c]
??:0

Execution log:

DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/many/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/many/.cache/xournalpp/autosaves/29726.autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/many/.cache/xournalpp/errorlogs/errorlog.20230804-114138.log

**Comment by Febbe** [comment]
Can you elaborate, what you did exactly before the crash?

**Comment by bhennion** [comment]
Closing in favor of #5025
