### ISSUE TITLE
Got prompt that bug occurred when opening application

### ISSUE THREAD

**Issue by Barrcap** [xournalpp/xournalpp#5007]
attaching log that was opened when I pressed open bug, for some reason the date is from August 2021.

Date: Wed Aug 25 15:52:50 2021
Error: signal 6
[bt]: (0) /snap/xournalpp/61/usr/bin/xournalpp(+0x437bac) [0x56088fbd3bac]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1328f63210]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f1328f6318b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f1328f42859]
[bt]: (4) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x1db5c) [0x7f132a579b5c]
[bt]: (5) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message_error+0xb6) [0x7f132a5e7076]
[bt]: (6) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d72b0) [0x7f1329f1d2b0]
[bt]: (7) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7c70) [0x7f1329f1dc70]
[bt]: (8) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7e76) [0x7f1329f1de76]
[bt]: (9) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1ee471) [0x7f1329f34471]
[bt]: (10) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
[bt]: (11) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
[bt]: (12) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1eec17) [0x7f1329f34c17]
[bt]: (13) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c3c13) [0x7f132a009c13]
[bt]: (14) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
[bt]: (15) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
[bt]: (16) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
[bt]: (17) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xe4897) [0x7f1329e2a897]
[bt]: (18) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c3c13) [0x7f132a009c13]
[bt]: (19) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f132a009999]
[bt]: (20) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
[bt]: (21) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
[bt]: (22) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f132a00adfb]
[bt]: (23) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32a87a) [0x7f132a07087a]
[bt]: (24) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
[bt]: (25) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
[bt]: (26) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x329bea) [0x7f132a06fbea]
[bt]: (27) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
[bt]: (28) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
[bt]: (29) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd7652) [0x7f1329e1d652]
[bt]: (30) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
[bt]: (31) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
[bt]: (32) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd6937) [0x7f1329e1c937]
[bt]: (33) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c3c13) [0x7f132a009c13]
[bt]: (34) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f132a009999]
[bt]: (35) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd12f9) [0x7f1329e172f9]
[bt]: (36) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
[bt]: (37) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f132a009999]
[bt]: (38) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x397c2a) [0x7f132a0ddc2a]
[bt]: (39) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
[bt]: (40) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
[bt]: (41) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f132a00adfb]
[bt]: (42) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39ac96) [0x7f132a0e0c96]
[bt]: (43) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a298e) [0x7f132a0e898e]
[bt]: (44) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14986) [0x7f13297c6986]
[bt]: (45) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f13297e6ab4]
[bt]: (46) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f13297e70c3]
[bt]: (47) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127128) [0x7f1329e6d128]
[bt]: (48) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14986) [0x7f13297c6986]
[bt]: (49) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f13297e6ab4]
[bt]: (50) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f13297e70c3]
[bt]: (51) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x48a4a) [0x7f1329c82a4a]
[bt]: (52) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x33d1d) [0x7f1329c6dd1d]
[bt]: (53) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x59f9f) [0x7f132a5b5f9f]
[bt]: (54) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15e) [0x7f132a5b52ce]
[bt]: (55) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x596a0) [0x7f132a5b56a0]
[bt]: (56) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f132a5b5743]
[bt]: (57) /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f13298f8415]
[bt]: (58) /snap/xournalpp/61/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x5ef) [0x56088fa40fd3]
[bt]: (59) /snap/xournalpp/61/usr/bin/xournalpp(main+0x29) [0x56088f9fd272]
[bt]: (60) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1328f440b3]
[bt]: (61) /snap/xournalpp/61/usr/bin/xournalpp(_start+0x2e) [0x56088f9fd18e]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/61/usr/bin/xournalpp(+0x43811e) [0x56088fbd411e]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1328f63210]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f1328f6318b]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f1328f42859]
??:0
[bt] #5 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x1db5c) [0x7f132a579b5c]
??:0
[bt] #6 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message_error+0xb6) [0x7f132a5e7076]
??:0
[bt] #7 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d72b0) [0x7f1329f1d2b0]
??:0
[bt] #8 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7c70) [0x7f1329f1dc70]
??:0
[bt] #9 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7e76) [0x7f1329f1de76]
??:0
[bt] #10 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1ee471) [0x7f1329f34471]
??:0
[bt] #11 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
??:0
[bt] #12 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
??:0
[bt] #13 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1eec17) [0x7f1329f34c17]
??:0
[bt] #14 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c3c13) [0x7f132a009c13]
??:0
[bt] #15 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
??:0
[bt] #16 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
??:0
[bt] #17 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
??:0
[bt] #18 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xe4897) [0x7f1329e2a897]
??:0
[bt] #19 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c3c13) [0x7f132a009c13]
??:0
[bt] #20 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f132a009999]
??:0
[bt] #21 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
??:0
[bt] #22 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
??:0
[bt] #23 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f132a00adfb]
??:0
[bt] #24 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32a87a) [0x7f132a07087a]
??:0
[bt] #25 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
??:0
[bt] #26 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x134988) [0x7f1329e7a988]
??:0
[bt] #27 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x329bea) [0x7f132a06fbea]
??:0
[bt] #28 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c413a) [0x7f132a00a13a]
??:0
[bt] #29 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f132a00aafe]
??:0
[bt] #30 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd7652) [0x7f1329e1d652]
??:0
[bt] #31 /snap/xournalpp/61/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee47) [0x7f1329e74e47]
??:0

**Comment by rolandlo** [comment]
Ok, that's a really old crash you got with the snap package. There doesn't seem to be much useful information in it. Some problem with Gtk. I will close this issue therefore. Feel free to reopen this issue if the crash occurs again. Otherwise I would advise you to just delete the errorlog. Then the message won't appear again.

**Comment by Barrcap** [comment]
Thanks for the reply!

I recently update my unubutu 22.04 and started to have package dependancies
issues, after deleting my snap instalation and reinstalling through apt
everything went back to normal.


Thanks again for the quick response,
Barr
