### ISSUE TITLE
Erro na abertura do software

### ISSUE THREAD

**Issue by marceloliveirali** [xournalpp/xournalpp#5010]
O software dá erro na abertura.
> The software gives an error when opening.

**Comment by Febbe** [comment]
Please speak english and improve your feedback. Without the error message or a screenshot, we can't help you. Most likely it's the info box, that the software crashed **before**. This message box will appear, until you delete the error log. Delete the log and everything is fine.

But w would like to see it, to fix the reason of the crash.

> Por favor, fale inglês e melhore os seus comentários. Sem a mensagem de erro ou uma captura de ecrã, não podemos ajudá-lo. O mais provável é que seja a caixa de informação de que o software falhou **antes**. Esta caixa de mensagem aparecerá até apagar o registo de erros. Elimine o registo e tudo ficará bem.
>
> Mas gostaríamos de o ver, para corrigir o motivo da falha.
