### ISSUE TITLE
New installation of Xournal++ does not show toolbars

### ISSUE THREAD

**Issue by apandada1** [xournalpp/xournalpp#5011]
**Affects versions :**
 - OS: Kubuntu 22.04 and Linux Mint 21.2 (possibly all Ubuntu versions are affected)
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.33
 - Version of Xournal++: 1.2.0
 - Installation method: apandada1/xournalpp-stable PPA

**Describe the bug**
In a new installation of Ubuntu, installing Xournalpp does not have any toolbars.

The workaround is to select `View -> Toolbars -> Portrait (or something else)` (once and for all), but this may be super confusing for new users.

**Expected behavior**
The default installation should have some toolbar enabled.

**Screenshots of Problem**
![image](https://github.com/xournalpp/xournalpp/assets/3063132/c7d761bf-e9df-4266-91a1-fad2fcf6f46d)

**Additional context**
Please release a new version which has a default configuration, because it may confuse new users otherwise.

**Comment by bhennion** [comment]
Fixed via #5015
