### ISSUE TITLE
Update on closed issue #4951 

### ISSUE THREAD

**Issue by Whyglobaleyes** [xournalpp/xournalpp#5024]
@bhennion & @rolandlo 
re: https://github.com/xournalpp/xournalpp/issues/4951 
Hi, 
Thank you both for your help - I can't believe how stupid I was being. 
You're right and `xournalpp` behaves beautifully with no black on black, that's a problem with `xournal` !! 

Best wishes

PS: sorry to clutter up the issues list with *another* item but I really wanted to say thanks - it must be demoralising for devs working through queries and not getting a response but I really am grateful.

**Comment by bhennion** [comment]
No problem! :)
