### ISSUE TITLE
I can't get the Huion Q630M stylus buttons to work and I get unexpected results with the eraser. 

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#5027]
**Affected versions
 - OS: Windows 11.
 - Xournal++ version : 1.2.0 +dev

**Describe the error**.
the Button 1 and Button 2 pen settings section in xournal does not work with the Huion pen, that means that I can't configure in the toolboxfloating buttons or other tools of course I could configure it in the huion driver with a keyboard shortcut without touching the xournal settings but for toolboxfloating there is no shortcut and that is not the desired behavior also it is worth mentioning the eraser is recognized but to use it I have to to configure and check in the huion driver the option "change brush" but its operation in xournal is a bit clumsy because to use the eraser I have to tap on the canvas after pressing the assigned button to erase and if I want to stop using it and go back to the pencil I have to press the button again and tap again on the canvas to go back to the pencil.

**Playback**
this is going to be a little difficult to demonstrate but I will try to send the screenshots. 

**Expected behavior
I was previously using a wacom tablet and my driver configuration was as follows 
![image](https://github.com/xournalpp/xournalpp/assets/28522011/cb46e260-8802-47c4-af53-e0181c61e36d)

as we can see in the image, button 1 is configured as "right click" and button 2 as eraser
for this to work in xournal I must configure button 2 with the tool that I will use. with this configuration I get that when I press button 1, the floating drawer opens and when I press the eraser it works properly, here is a general picture

![general](https://github.com/xournalpp/xournalpp/assets/28522011/5a10fd21-e559-4ca2-adc6-1c745c6af67f)

so i try to replicate that configuration in the huion driver but the result is not expected. 
to start with to make the eraser work in the driver i have to check the option change brush. but to try to make the other button work i imitate the wacom configuration like right click button1 and then choose the tool (i tried on both buttons 1 and 2) but 
it didn't work in fact i can't get it to work.

![image](https://github.com/xournalpp/xournalpp/assets/28522011/34724c5d-f739-492e-893f-0621f19aaca4)

**Additional context
for some reason I don't know or understand why when I connect my wacom it detects the pencil and eraser but when I connect the huion it detects up to 4 and especially 2 which I don't know if they are the correct ones.
![image](https://github.com/xournalpp/xournalpp/assets/28522011/3c74fdf4-b86f-4ae9-9fc1-483273784f4a)

**Comment by clcarrasco1993** [comment]
Hola! encontraste una solución a este problema? me pasa lo mismo, saludos!
