### ISSUE TITLE
Xournal++ troubles

### ISSUE THREAD

**Issue by ramaswamysriram** [xournalpp/xournalpp#5033]
When I open a pdf file in Xournal++ I get error messages and a prompt to send a bug report.

**Comment by rolandlo** [comment]
And what are the error messages and errorlog?

**Comment by ramaswamysriram** [comment]
Thanks for responding so fast.

Error message on the screen when I open the pdf file with Xournal++ reads:

There are errorlogfiles from Xournal++. Please find a Bugreport, so the bug may be fixed.
You're using "xournalapp/HEAD" branch. The most recent log file name: /home/sriram/snap/xournalapp/common/errorlogs/errorlog.20220715-194331.log

Error logfile:

Date: Fri Jul 15 19:43:31 2022
Error: signal 11
[bt]: (0) /snap/xournalpp/69/usr/bin/xournalpp(+0x435b8a) [0x5611cea47b8a]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f94e1da8090]
[bt]: (2) /snap/xournalpp/69/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x5611cea06a52]
[bt]: (3) /snap/xournalpp/69/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x5611cea3a3d2]
[bt]: (4) /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x5611cea3a67c]
[bt]: (5) /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x5611cea3aeea]
[bt]: (6) /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x5611ce8c2666]
[bt]: (7) /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x5611ce8c2a25]
[bt]: (8) /snap/xournalpp/69/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x5611ce8c19f5]
[bt]: (9) /snap/xournalpp/69/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x5611ce8c5f36]
[bt]: (10) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8b6a1) [0x7f94e34336a1]
[bt]: (11) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f94e23a9609]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f94e1e84133]


Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/69/usr/bin/xournalpp(+0x4360fc) [0x5611cea480fc]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f94e1da8090]
??:0
[bt] #3 /snap/xournalpp/69/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x5611cea06a52]
??:0
[bt] #4 /snap/xournalpp/69/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x5611cea3a3d2]
??:0
[bt] #5 /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x5611cea3a67c]
??:0
[bt] #6 /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x5611cea3aeea]
??:0
[bt] #7 /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x5611ce8c2666]
??:0
[bt] #8 /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x5611ce8c2a25]
??:0
[bt] #9 /snap/xournalpp/69/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x5611ce8c19f5]
??:0
[bt] #10 /snap/xournalpp/69/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x5611ce8c5f36]
??:0
[bt] #11 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8b6a1) [0x7f94e34336a1]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f94e23a9609]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f94e1e84133]
??:0

Thanks and regards -- Sriram


Sriram Ramaswamy
http://www.physics.iisc.ac.in/~sriram/
Department of Physics
Indian Institute of Science
Bengaluru 560 012 India


________________________________

**Comment by Febbe** [comment]
Since v.1.2 we show previous crash logs on start, unfortunately this also includes very old crash logs. 
You can safely delete such old logs. In this case, the bug can't happen anymore, the member function has been refactored away.
