### ISSUE TITLE
The app works, but tells me at the start that there is a bug

### ISSUE THREAD

**Issue by blaham17** [xournalpp/xournalpp#5035]
[errorlog.20220117-191954.log](https://github.com/xournalpp/xournalpp/files/12313928/errorlog.20220117-191954.log)

**Comment by Febbe** [comment]
Thank you for the crash log. Since v. 1.2 we show the first crash log found in the crash log directory, since that log is very old and the bug probably fixed, you can just delete it. Until there are no more logs in your directory, xournalpp will show you that info.

From the crashlog:
```
Date: Mon Jan 17 19:19:54 2022
Error: signal 11
```

**Comment by Febbe** [comment]
Same as: #5033, fixed
