### ISSUE TITLE
crashed when selecting View->Toolbars->Xournal++

### ISSUE THREAD

**Issue by cfblaeb** [xournalpp/xournalpp#5050]
Installed snap of 1.2.0 on Ubuntu 23.04
Opened app.
Drew a shape on the paper.
Clicked View->Toolbars->Xournal++
Program exited without any messages.
Upon re-opening it, it gave me a crashlog and offered to restore my work and also the Xournal++ toolbar is enabled and it doesnt crash on switching anymore.

[errorlog.20230814-085543.log](https://github.com/xournalpp/xournalpp/files/12332186/errorlog.20230814-085543.log)

**Comment by bhennion** [comment]
Duplicate fo #4997.
A fix has already been accepted. It will appear in version 1.2.1.
