### ISSUE TITLE
F9 to show/hide Toolbars now shows empty toolbars

### ISSUE THREAD

**Issue by Ka1zza** [xournalpp/xournalpp#5051]
### Operating System

Linux

### (Linux only) Distribution

Fedora

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Official RPM

### Xournal++ Version

1.2.0

### libgtk Version

3.24.38

### Bug Description

Recently updated to 1.2.0
F9 (Toolbar toggle) now toggles empty toolbars on/off along with the desired toolbar.
![image](https://github.com/xournalpp/xournalpp/assets/94217495/d553f585-8ade-45a3-9c69-d658a3923573)

### Expected Behaviour

Only the toolbar with tools in it should be shown as when selecting through View -> Toolbars
![image](https://github.com/xournalpp/xournalpp/assets/94217495/f699a710-e6bd-455a-9e7b-acfee4dd7d19)

### Steps to Reproduce

Toggle toolbar off then on with F9 or View option "Show Toolbars".

**Comment by Mikhailov972** [comment]
I have some problem, but my system is Ubuntu 22.04 on Xorg.
![image](https://github.com/xournalpp/xournalpp/assets/34601192/98abc6cb-efa7-4282-a6c1-c9b24f602a21)
