### ISSUE TITLE
Tools Submenu too large

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#5053]
### Operating System

Linux

### (Linux only) Distribution

Arch

### (Linux only) Desktop Environment

bspwm

### (Linux Only) Display Server

X.Org

### Installation Method

arch repository

### Xournal++ Version

1.2.0 (10ed72c9)

### libgtk Version

3.24.38

### Edit Annotation:
I'm not sure if I used the terms menu and submenu the right way in the following descriptions. By submenu I mean the thing appearing when clicking onto an entry in the menu-bar at the top.

### Bug Description

When opening the `Tools` submenu from the menu bar, the submenu being displayed is (almost -> can work this way but it is irritating see the picture) too large for my screen.
![image](https://github.com/xournalpp/xournalpp/assets/60581958/d65c310c-ec24-4a9c-86e8-37b0cf357621)

### Expected Behaviour

I expect the submenu to fit my screen and the menubar on the top to be fully visible. Only this way can I select other menu-entries on the right side of `Tools` like `Plugins`. 

### Steps to Reproduce

1. Open xournalpp
2. Click onto the `Tools` entry in the menu-bar

### Additional Context

I suggest to either make the submenu "scrollable" or group different tools like all selection tools or the various shapes (arrow, line, rectagle, ...) together and by that reduce the number of entries in the submenu.

**Comment by vladQll** [comment]
![image](https://github.com/xournalpp/xournalpp/assets/28522011/373f4576-0943-4468-89f2-edaa3ce85219)
these are the arrow and double arrow tools

**Comment by atticus-sullivan** [comment]
I don't quite get what you mean. I don't refer to the toolbar on the left-hand side or the icons. Could you please elaborate?
