### ISSUE TITLE
When exporting pdf, previously saved pdfs do not show in file picker

### ISSUE THREAD

**Issue by ebits21** [xournalpp/xournalpp#5063]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

1.2.0

### libgtk Version

Unsure

### Bug Description

When exporting to pdf, the file picker dialog does not show the already saved .pdfs in the folder.

### Expected Behaviour

Show previously saved pdfs.

### Steps to Reproduce

See above

**Comment by ebits21** [comment]
In addition to windows, I've confirmed this using the flathub flatpak on fedora as well.

**Comment by Stebf** [comment]
If you start a search in the file picker (by just starting to type), all of the already saved .pdfs appear.

**Comment by ebits21** [comment]
This was fixed with the 1.2.3 release
