### ISSUE TITLE
SegFault in SidebarPreviewLayerEntry()

### ISSUE THREAD

**Issue by sandrobarone** [xournalpp/xournalpp#5074]
Date: Sun Aug 20 21:09:30 2023
Error: signal 11
Xournal++ version 1.2.0
Git commit: 10ed72c9
Gtk version 3.24.38

[bt]: (0) xournalpp(+0xe69ba) [0x5610ef35e9ba]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f34802630c0]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_destroy+0x25) [0x7f34812f2c85]
[bt]: (3) xournalpp(_ZN24SidebarPreviewLayerEntryD0Ev+0x26) [0x5610ef4e0fa6]
[bt]: (4) xournalpp(_ZN18SidebarPreviewBaseD1Ev+0x87) [0x5610ef4e03f7]
[bt]: (5) xournalpp(_ZN20SidebarPreviewLayersD0Ev+0x7d) [0x5610ef481cad]
[bt]: (6) xournalpp(_ZN7SidebarD1Ev+0x5f) [0x5610ef47ebaf]
[bt]: (7) xournalpp(_ZN7SidebarD0Ev+0x15) [0x5610ef47ec65]
[bt]: (8) xournalpp(_ZN7ControlD2Ev+0x2dd) [0x5610ef3fad6d]
[bt]: (9) xournalpp(_ZN7ControlD0Ev+0x15) [0x5610ef3fb375]
[bt]: (10) xournalpp(_ZN11XournalMain3runEiPPc+0x617) [0x5610ef361c97]
[bt]: (11) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a) [0x7f348024d54a]
[bt]: (12) /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f348024d60b]
[bt]: (13) xournalpp(_start+0x25) [0x5610ef35de35]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xe70a9) [0x5610ef35f0a9]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f34802630c0]
[bt] #3 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_destroy+0x25) [0x7f34812f2c85]
[bt] #4 xournalpp(_ZN24SidebarPreviewLayerEntryD0Ev+0x26) [0x5610ef4e0fa6]
[bt] #5 xournalpp(_ZN18SidebarPreviewBaseD1Ev+0x87) [0x5610ef4e03f7]
[bt] #6 xournalpp(_ZN20SidebarPreviewLayersD0Ev+0x7d) [0x5610ef481cad]
[bt] #7 xournalpp(_ZN7SidebarD1Ev+0x5f) [0x5610ef47ebaf]
[bt] #8 xournalpp(_ZN7SidebarD0Ev+0x15) [0x5610ef47ec65]
[bt] #9 xournalpp(_ZN7ControlD2Ev+0x2dd) [0x5610ef3fad6d]
[bt] #10 xournalpp(_ZN7ControlD0Ev+0x15) [0x5610ef3fb375]
[bt] #11 xournalpp(_ZN11XournalMain3runEiPPc+0x617) [0x5610ef361c97]
[bt] #12 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a) [0x7f348024d54a]
[bt] #13 /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f348024d60b]
[bt] #14 xournalpp(_start+0x25) [0x5610ef35de35]

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /app/share/xournalpp/../locale, chosen directory = /app/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /app/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
WARNING : xopp :: Could not remove element from layer, it's not on the layer!
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/errorlogs/errorlog.20230820-210930.log

**Comment by bhennion** [comment]
Fixed in 1.2.2
