### ISSUE TITLE
pagetemplates.ini - Not found and Configure Page Templates Crash

### ISSUE THREAD

**Issue by IkeEisenhauer** [xournalpp/xournalpp#5081]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Daily Release

### Xournal++ Version

1.2.0+dev

### libgtk Version

3.24.39

### Bug Description

Modified pagetemplate.ini to add new page type
Now, on start up...get a popup saying it can not be found.
Modified page type is selectable and usable
However, if I go to Configure Page Template, app closes without warning.

### Expected Behaviour

If pagetemplate.ini exists, but edited app should find it and not claim it can not.
Configure Page Template should got to configure page template options...and not close app

### Steps to Reproduce

1. Add new page type to pagetemplate.ini

[EngineeringGraph]
name=EngineeringGraph
format=graph
config=rm=2,f1=D3D3D3

2. Restart app
3. Seelct Configure Page Template menu option

**Comment by IkeEisenhauer** [comment]
It is a very rare situation, only happens if you make a new style, set the default to that style, then delete that style definition.

**Comment by Ainson** [comment]
I had similar when I tried to edit pagetemplate.ini with notepad in Windows. (cannot read pagetemplate.ini)

The solution was to use SciTE, a dedicated program language editor. (there are other free ones like Scintilla, Visual Studio Code etc). Seems normal notepad editor screws up the file.
