### ISSUE TITLE
Recieved request to file bug report when I started xournal++

### ISSUE THREAD

**Issue by Frederik-Kris** [xournalpp/xournalpp#5085]
Ran xournal++ from the "start menu" in ubuntu 22.04 gnome. Noticed the icon had changed to a gear. on startup got message that there were error logs, and a request to file them. App seems to work fine now, but icon is still a gear.

Here is the error log:

Date: Tue Apr  5 18:02:35 2022
Error: signal 6
[bt]: (0) /snap/xournalpp/69/usr/bin/xournalpp(+0x435b8a) [0x55cf834acb8a]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7f2f042be0c0]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f2f042be03b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f2f0429d859]
[bt]: (4) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x1db5c) [0x7f2f058e8b5c]
[bt]: (5) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message_error+0xb6) [0x7f2f05956076]
[bt]: (6) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d72d0) [0x7f2f0528b2d0]
[bt]: (7) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7c90) [0x7f2f0528bc90]
[bt]: (8) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7e96) [0x7f2f0528be96]
[bt]: (9) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1ee491) [0x7f2f052a2491]
[bt]: (10) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
[bt]: (11) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
[bt]: (12) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1eec37) [0x7f2f052a2c37]
[bt]: (13) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c47a3) [0x7f2f053787a3]
[bt]: (14) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
[bt]: (15) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
[bt]: (16) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
[bt]: (17) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xe48d7) [0x7f2f051988d7]
[bt]: (18) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c47a3) [0x7f2f053787a3]
[bt]: (19) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f2f05378529]
[bt]: (20) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
[bt]: (21) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
[bt]: (22) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f2f0537998b]
[bt]: (23) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32b4fa) [0x7f2f053df4fa]
[bt]: (24) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
[bt]: (25) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
[bt]: (26) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32a86a) [0x7f2f053de86a]
[bt]: (27) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
[bt]: (28) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
[bt]: (29) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd7692) [0x7f2f0518b692]
[bt]: (30) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
[bt]: (31) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
[bt]: (32) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd6977) [0x7f2f0518a977]
[bt]: (33) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c47a3) [0x7f2f053787a3]
[bt]: (34) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f2f05378529]
[bt]: (35) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd1339) [0x7f2f05185339]
[bt]: (36) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
[bt]: (37) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f2f05378529]
[bt]: (38) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3988aa) [0x7f2f0544c8aa]
[bt]: (39) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
[bt]: (40) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
[bt]: (41) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f2f0537998b]
[bt]: (42) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x39b916) [0x7f2f0544f916]
[bt]: (43) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a360e) [0x7f2f0545760e]
[bt]: (44) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14986) [0x7f2f04b24986]
[bt]: (45) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f2f04b44ab4]
[bt]: (46) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f2f04b450c3]
[bt]: (47) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127148) [0x7f2f051db148]
[bt]: (48) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14986) [0x7f2f04b24986]
[bt]: (49) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f2f04b44ab4]
[bt]: (50) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f2f04b450c3]
[bt]: (51) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x48a6a) [0x7f2f04ff0a6a]
[bt]: (52) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x33d3d) [0x7f2f04fdbd3d]
[bt]: (53) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x59f9f) [0x7f2f05924f9f]
[bt]: (54) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15e) [0x7f2f059242ce]
[bt]: (55) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x596a0) [0x7f2f059246a0]
[bt]: (56) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7f2f05924993]
[bt]: (57) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_dialog_run+0x147) [0x7f2f0521e5d7]
[bt]: (58) /snap/xournalpp/69/usr/bin/xournalpp(_ZN7Control5closeEbb+0x2e9) [0x55cf832e9981]
[bt]: (59) /snap/xournalpp/69/usr/bin/xournalpp(_ZN7Control4quitEb+0x2a) [0x55cf832e95ce]
[bt]: (60) /snap/xournalpp/69/usr/bin/xournalpp(_ZN10MainWindow19deleteEventCallbackEP10_GtkWidgetP9_GdkEventP7Control+0x29) [0x55cf833dadbb]
[bt]: (61) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x9aeef) [0x7f2f0514eeef]
[bt]: (62) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14986) [0x7f2f04b24986]
[bt]: (63) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e0) [0x7f2f04b43dd0]
[bt]: (64) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f2f04b450c3]
[bt]: (65) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x37f730) [0x7f2f05433730]
[bt]: (66) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x929) [0x7f2f052cdff9]
[bt]: (67) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3f809) [0x7f2f04fe7809]
[bt]: (68) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9d616) [0x7f2f05045616]
[bt]: (69) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x28d) [0x7f2f059243fd]
[bt]: (70) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x596a0) [0x7f2f059246a0]
[bt]: (71) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f2f05924743]
[bt]: (72) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f2f04c58415]
[bt]: (73) /snap/xournalpp/69/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x5ef) [0x55cf83319559]
[bt]: (74) /snap/xournalpp/69/usr/bin/xournalpp(main+0x29) [0x55cf832d5292]
[bt]: (75) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f2f0429f0b3]
[bt]: (76) /snap/xournalpp/69/usr/bin/xournalpp(_start+0x2e) [0x55cf832d51ae]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/69/usr/bin/xournalpp(+0x4360fc) [0x55cf834ad0fc]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7f2f042be0c0]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f2f042be03b]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f2f0429d859]
??:0
[bt] #5 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x1db5c) [0x7f2f058e8b5c]
??:0
[bt] #6 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message_error+0xb6) [0x7f2f05956076]
??:0
[bt] #7 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d72d0) [0x7f2f0528b2d0]
??:0
[bt] #8 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7c90) [0x7f2f0528bc90]
??:0
[bt] #9 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1d7e96) [0x7f2f0528be96]
??:0
[bt] #10 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1ee491) [0x7f2f052a2491]
??:0
[bt] #11 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
??:0
[bt] #12 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
??:0
[bt] #13 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1eec37) [0x7f2f052a2c37]
??:0
[bt] #14 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c47a3) [0x7f2f053787a3]
??:0
[bt] #15 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
??:0
[bt] #16 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
??:0
[bt] #17 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
??:0
[bt] #18 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xe48d7) [0x7f2f051988d7]
??:0
[bt] #19 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c47a3) [0x7f2f053787a3]
??:0
[bt] #20 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x199) [0x7f2f05378529]
??:0
[bt] #21 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
??:0
[bt] #22 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
??:0
[bt] #23 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_size+0x10b) [0x7f2f0537998b]
??:0
[bt] #24 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32b4fa) [0x7f2f053df4fa]
??:0
[bt] #25 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
??:0
[bt] #26 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1349a8) [0x7f2f051e89a8]
??:0
[bt] #27 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x32a86a) [0x7f2f053de86a]
??:0
[bt] #28 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2c4cca) [0x7f2f05378cca]
??:0
[bt] #29 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0x1ee) [0x7f2f0537968e]
??:0
[bt] #30 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd7692) [0x7f2f0518b692]
??:0
[bt] #31 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12ee67) [0x7f2f051e2e67]
??:0

BR, Frederik

**Comment by rolandlo** [comment]
The missing icon for the snap package should get fixed via https://github.com/kenvandine/xournalpp/pull/14
Let's hope this PR gets merged soon.

The crash log is from April 5, 2022. So the crash might be already fixed. I would advise you to delete the crash log, so the dialog doesn't appear again.

**Comment by kenvandine** [comment]
The icon issue in the snap has been fixed, thanks!

**Comment by bhennion** [comment]
Closing this, assuming the source of the crash has been fied in the most recent version. Please reopen if a similar crashlog appears again.
