### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by diogoolsen** [xournalpp/xournalpp#5089]
Date: Thu Nov 17 15:45:07 2022
Error: signal 6
[bt]: (0) xournalpp(+0x201a75) [0x55558212aa75]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f1622c3f0c0]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x91184) [0x7f1622c91184]
[bt]: (3) /usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e) [0x7f1622c3f00e]
[bt]: (4) /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f1622c287fc]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9a79) [0x7f16230a9a79]
[bt]: (6) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb580a) [0x7f16230b580a]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5875) [0x7f16230b5875]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0x7f16230b5b00]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x44) [0x7f16230ac355]
[bt]: (10) xournalpp(_ZN14LatexGenerator8asyncRunERKNSt10filesystem7__cxx114pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x606) [0x555582023c56]
[bt]: (11) xournalpp(_ZN15LatexController18triggerImageUpdateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xb2) [0x5555820002f2]
[bt]: (12) xournalpp(_ZN15LatexController16handleTexChangedEP14_GtkTextBufferPS_+0x3c) [0x5555820003ec]
[bt]: (13) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x172) [0x7f162382b4f2]
[bt]: (14) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c1e8) [0x7f16238401e8]
[bt]: (15) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf95) [0x7f1623847155]
[bt]: (16) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (17) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2db7aa) [0x7f1623edb7aa]
[bt]: (18) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x172) [0x7f162382b4f2]
[bt]: (19) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c303) [0x7f1623840303]
[bt]: (20) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf95) [0x7f1623847155]
[bt]: (21) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (22) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_text_buffer_set_text+0xde) [0x7f1623edef5e]
[bt]: (23) xournalpp(_ZN11LatexDialog4showEP10_GtkWindowb+0x40) [0x5555820b35a0]
[bt]: (24) xournalpp(_ZN15LatexController17showTexEditDialogB5cxx11Ev+0x105) [0x555582000de5]
[bt]: (25) xournalpp(_ZN15LatexController3runEv+0x54) [0x555582001eb4]
[bt]: (26) xournalpp(_ZN7Control8runLatexEv+0x3b) [0x555581ff91eb]
[bt]: (27) xournalpp(_ZN12AbstractItem9activatedEP9_GdkEventP12_GtkMenuItemP14_GtkToolButton+0xce) [0x5555820d889e]
[bt]: (28) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (29) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt]: (30) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_by_name+0x206) [0x7f1623847546]
[bt]: (31) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (32) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt]: (33) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (34) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xf2848) [0x7f1623cf2848]
[bt]: (35) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (36) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt]: (37) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (38) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xf09fd) [0x7f1623cf09fd]
[bt]: (39) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xad6f3) [0x7f1623cad6f3]
[bt]: (40) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (41) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt]: (42) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (43) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1c6563) [0x7f1623dc6563]
[bt]: (44) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x9a) [0x7f162382e9ca]
[bt]: (45) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (46) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt]: (47) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (48) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1c32f8) [0x7f1623dc32f8]
[bt]: (49) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1c4aa3) [0x7f1623dc4aa3]
[bt]: (50) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1c7ed5) [0x7f1623dc7ed5]
[bt]: (51) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_event_controller_handle_event+0x77) [0x7f1623d8b597]
[bt]: (52) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x36b378) [0x7f1623f6b378]
[bt]: (53) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xa6bd7) [0x7f1623ca6bd7]
[bt]: (54) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt]: (55) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x39e) [0x7f162384655e]
[bt]: (56) /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt]: (57) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x36ce34) [0x7f1623f6ce34]
[bt]: (58) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x212510) [0x7f1623e12510]
[bt]: (59) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x6e6) [0x7f1623e14086]
[bt]: (60) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x42861) [0x7f1624486861]
[bt]: (61) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9ee9e) [0x7f16244e2e9e]
[bt]: (62) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x191) [0x7f16245ac681]
[bt]: (63) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5bbd8) [0x7f16245acbd8]
[bt]: (64) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f16245acc73]
[bt]: (65) /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1ed) [0x7f1623971bad]
[bt]: (66) xournalpp(_ZN11XournalMain3runEiPPc+0x59b) [0x55558200f33b]
[bt]: (67) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a) [0x7f1622c2954a]
[bt]: (68) /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f1622c2960b]
[bt]: (69) xournalpp(_start+0x25) [0x555581fe82d5]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x202096) [0x55558212b096]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f1622c3f0c0]
[bt] #3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x91184) [0x7f1622c91184]
[bt] #4 /usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e) [0x7f1622c3f00e]
[bt] #5 /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f1622c287fc]
[bt] #6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9a79) [0x7f16230a9a79]
[bt] #7 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb580a) [0x7f16230b580a]
[bt] #8 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5875) [0x7f16230b5875]
[bt] #9 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0x7f16230b5b00]
[bt] #10 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x44) [0x7f16230ac355]
[bt] #11 xournalpp(_ZN14LatexGenerator8asyncRunERKNSt10filesystem7__cxx114pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x606) [0x555582023c56]
[bt] #12 xournalpp(_ZN15LatexController18triggerImageUpdateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xb2) [0x5555820002f2]
[bt] #13 xournalpp(_ZN15LatexController16handleTexChangedEP14_GtkTextBufferPS_+0x3c) [0x5555820003ec]
[bt] #14 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x172) [0x7f162382b4f2]
[bt] #15 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c1e8) [0x7f16238401e8]
[bt] #16 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf95) [0x7f1623847155]
[bt] #17 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt] #18 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2db7aa) [0x7f1623edb7aa]
[bt] #19 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x172) [0x7f162382b4f2]
[bt] #20 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c303) [0x7f1623840303]
[bt] #21 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf95) [0x7f1623847155]
[bt] #22 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f1623847323]
[bt] #23 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_text_buffer_set_text+0xde) [0x7f1623edef5e]
[bt] #24 xournalpp(_ZN11LatexDialog4showEP10_GtkWindowb+0x40) [0x5555820b35a0]
[bt] #25 xournalpp(_ZN15LatexController17showTexEditDialogB5cxx11Ev+0x105) [0x555582000de5]
[bt] #26 xournalpp(_ZN15LatexController3runEv+0x54) [0x555582001eb4]
[bt] #27 xournalpp(_ZN7Control8runLatexEv+0x3b) [0x555581ff91eb]
[bt] #28 xournalpp(_ZN12AbstractItem9activatedEP9_GdkEventP12_GtkMenuItemP14_GtkToolButton+0xce) [0x5555820d889e]
[bt] #29 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1770a) [0x7f162382b70a]
[bt] #30 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf5f) [0x7f162384711f]
[bt] #31 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_by_name+0x206) [0x7f1623847546]

**Comment by rolandlo** [comment]
You experienced a crash with the LaTeX tool on Nov 17, 2022, which is a while back. This might be already fixed in the latest version. I would advise you to simply delete the crash log and move on.
