### ISSUE TITLE
view mode changing error

### ISSUE THREAD

**Issue by halak0013** [xournalpp/xournalpp#5097]
I installed deb package on my system. then open a pdf file. its ui was so so i want to change it then it crash. when try to open again, there is no problem
my sytem info 
OS: Pardus GNU/Linux 23 (yirmiuc) x86_64 
Host: 82K2 IdeaPad Gaming 3 15ACH6 
Kernel: 6.1.0-11-amd64 
DE: Plasma 5.27.5

<details><summary>Bug output</summary>
<p>

Date: Sat Aug 26 20:31:16 2023
Error: signal 11
Xournal++ version 1.2.0
Gtk version 3.24.37

[bt]: (0) /usr/bin/xournalpp(+0xd5ce6) [0x55e0e702ace6]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0) [0x7f154a77bfd0]
[bt]: (2) /usr/bin/xournalpp(_ZNK7Palette10getColorAtEm+0x17) [0x55e0e7089487]
[bt]: (3) /usr/bin/xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe2a) [0x55e0e707c8ea]
[bt]: (4) /usr/bin/xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x50) [0x55e0e706b3e0]
[bt]: (5) /usr/bin/xournalpp(+0x124396) [0x55e0e7079396]
[bt]: (6) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x160) [0x7f154b0d53b0]
[bt]: (7) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x29076) [0x7f154b0e8076]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf35) [0x7f154b0eebf5]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
[bt]: (10) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe629e) [0x7f154b23229e]
[bt]: (11) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x5f) [0x7f154b230a2f]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x223686) [0x7f154b823686]
[bt]: (13) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x160) [0x7f154b0d53b0]
[bt]: (14) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x29076) [0x7f154b0e8076]
[bt]: (15) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf35) [0x7f154b0eebf5]
[bt]: (16) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_activate+0x54) [0x7f154b96c834]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_shell_activate_item+0x136) [0x7f154b81f936]
[bt]: (19) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x21fc71) [0x7f154b81fc71]
[bt]: (20) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x90cb4) [0x7f154b690cb4]
[bt]: (21) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x165a9) [0x7f154b0d55a9]
[bt]: (22) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x39e) [0x7f154b0ee05e]
[bt]: (23) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
[bt]: (24) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3697d4) [0x7f154b9697d4]
[bt]: (25) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2077de) [0x7f154b8077de]
[bt]: (26) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x746) [0x7f154b809296]
[bt]: (27) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3c815) [0x7f154bf14815]
[bt]: (28) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x96702) [0x7f154bf6e702]
[bt]: (29) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7f154afdb7a9]
[bt]: (30) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x54a38) [0x7f154afdba38]
[bt]: (31) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f154afdbacc]
[bt]: (32) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1dd) [0x7f154b22965d]
[bt]: (33) /usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x4fa) [0x55e0e702df8a]
[bt]: (34) /lib/x86_64-linux-gnu/libc.so.6(+0x271ca) [0x7f154a7671ca]
[bt]: (35) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f154a767285]
[bt]: (36) /usr/bin/xournalpp(_start+0x2a) [0x55e0e7029e3a]

Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0xd6348) [0x55e0e702b348]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0) [0x7f154a77bfd0]
??:0
[bt] #3 /usr/bin/xournalpp(_ZNK7Palette10getColorAtEm+0x17) [0x55e0e7089487]
??:0
[bt] #4 /usr/bin/xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe2a) [0x55e0e707c8ea]
??:0
[bt] #5 /usr/bin/xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x50) [0x55e0e706b3e0]
??:0
[bt] #6 /usr/bin/xournalpp(+0x124396) [0x55e0e7079396]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x160) [0x7f154b0d53b0]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x29076) [0x7f154b0e8076]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf35) [0x7f154b0eebf5]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe629e) [0x7f154b23229e]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x5f) [0x7f154b230a2f]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x223686) [0x7f154b823686]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x160) [0x7f154b0d53b0]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x29076) [0x7f154b0e8076]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xf35) [0x7f154b0eebf5]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_activate+0x54) [0x7f154b96c834]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_shell_activate_item+0x136) [0x7f154b81f936]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x21fc71) [0x7f154b81fc71]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x90cb4) [0x7f154b690cb4]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x165a9) [0x7f154b0d55a9]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x39e) [0x7f154b0ee05e]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f154b0eedbf]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3697d4) [0x7f154b9697d4]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2077de) [0x7f154b8077de]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x746) [0x7f154b809296]
??:0
[bt] #28 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3c815) [0x7f154bf14815]
??:0
[bt] #29 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x96702) [0x7f154bf6e702]
??:0
[bt] #30 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7f154afdb7a9]
??:0
[bt] #31 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x54a38) [0x7f154afdba38]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
WARNING : xopp :: configfile does not exist /home/user_name/.config/xournalpp/settings.xml

INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/user_name/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Using default latex template in /usr/share/xournalpp/resources/default_template.tex
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/user_name/.cache/xournalpp/errorlogs/errorlog.20230826-203116.log

</p>
</details>

**Comment by rolandlo** [comment]
That is related to color palettes and shouldn't happen in version 1.2.1 anymore. I'm closing the issue therefore.
