### ISSUE TITLE
Handwriting Recognition

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#51]
This is a challenging and ambitious project. One lead is the <a href="http://www.dklevine.com/general/software/tc1000/jarnal-recog.htm">jarnal</a> software. It's in Java but it's GPLv2 and written to be ported to other projects. I'm not sure how well it works.

**Comment by andreasb242** [comment]
There are handwriting recognition tools running on the OS, which can be used.

As you didn't implement it I close this ticket now (cleanup / because of age)

**Comment by novoid** [comment]
Hi @andreasb242,

May I ask what handwriting recognition tools you have tried? My research so far did not yield any usable tools for English/German offline handwriting recognition.

xournalpp would be able to profit from the much better recognition capabilities of an on-line OCR... https://en.wikipedia.org/wiki/Handwriting_recognition
