### ISSUE TITLE
Unerased white background outside the pages

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#5102]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

No DE

### (Linux Only) Display Server

X.Org

### Installation Method

Built from source

### Xournal++ Version

Master  (since 9d4f59c0d560fba8c69ab695b75695d74a1c32ed )

### libgtk Version

3.24.38

### Bug Description

When I jump to the first page or the last page, white background is sometimes displayed outside pages. This happens since 9d4f59c0d560fba8c69ab695b75695d74a1c32ed .

https://github.com/xournalpp/xournalpp/assets/6355486/9fdea859-822d-449f-b827-b64e29a860a2

### Expected Behaviour

No white background seen.

### Steps to Reproduce

1. Open .xopp file which have more than 10 pages.
2. Use [End] or [Home] key to jump to the last page or the first page.

### Additional Context

If you jump to non-cached page using side-bar click, the bug also sometimes appears.

**Comment by itshog** [comment]
Can confirm the bug, this happens to me as well

**Comment by rolandlo** [comment]
Closing as fixed by #5399.
