### ISSUE TITLE
`Send Bugreport` opens non-existent URL

### ISSUE THREAD

**Issue by h-b** [xournalpp/xournalpp#5103]
### Operating System

Linux

### (Linux only) Distribution

Manjaro

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

X.Org

### Installation Method

pacman -S xournalpp

### Xournal++ Version

1.2.0 (10ed72c9)

### libgtk Version

3.24.38

### Bug Description

After Xournal++ crashes, a dialog is shown after the next start offering to send a bug report:

![image](https://github.com/xournalpp/xournalpp/assets/24413995/798d473f-3678-4825-8c96-aaf805801531)

After clicking "Send Bugreport", this non-existant URL is opened:

https://github.com/srcdest/xournalpp/issues/new

### Expected Behaviour

The dialog should open

https://github.com/xournalpp/xournalpp/issues/new

instead.

### Steps to Reproduce

Crash Xournal++ by closing it, executing `rm -rf ~/.config/xournalpp` and opening it again. In the first attempt, it only crashed after selecting `View` --> `Toolsbars` --> `Xournal++`, in the second attempt it crashed instantly.

**Comment by rolandlo** [comment]
The URL is already fixed in version 1.2.1 via #5084. The crash has also been fixed in version 1.2.1.
