### ISSUE TITLE
Crash on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by denysok** [xournalpp/xournalpp#5104]
Date: Wed Aug 30 01:16:16 2023
Error: signal 11
Xournal++ version 1.2.0
Git commit: 10ed72c9
Gtk version 3.24.33

[bt]: (0) xournalpp(+0xdc040) [0x558419502040]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f33e7242520]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x558419565e3b]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe80) [0x558419558440]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x58) [0x558419546098]
[bt]: (5) xournalpp(+0x12eb5a) [0x558419554b5a]
[bt]: (6) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f33e7e02d2f]
[bt]: (7) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f33e7e1ec36]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f33e7e20614]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f33e7e20863]
[bt]: (10) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe5016) [0x7f33e7f63016]
[bt]: (11) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x65) [0x7f33e7f61a55]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x263606) [0x7f33e8663606]
[bt]: (13) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f33e7e02d2f]
[bt]: (14) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f33e7e1ec36]
[bt]: (15) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f33e7e20614]
[bt]: (16) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f33e7e20863]
[bt]: (17) /lib/x86_64-linux-gnu/libappmenu-gtk3-parser.so.0(+0x8497) [0x7f33e2942497]
[bt]: (18) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x332ad) [0x7f33e832c2ad]
[bt]: (19) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x174) [0x7f33e7d09c44]
[bt]: (20) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f33e7d5f258]
[bt]: (21) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f33e7d073e3]
[bt]: (22) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f33e7f5efb5]
[bt]: (23) xournalpp(_ZN11XournalMain3runEiPPc+0x5eb) [0x55841950562b]
[bt]: (24) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f33e7229d90]
[bt]: (25) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f33e7229e40]
[bt]: (26) xournalpp(_start+0x25) [0x558419501065]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xdc687) [0x558419502687]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f33e7242520]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x558419565e3b]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xe80) [0x558419558440]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x58) [0x558419546098]
??:0
[bt] #6 xournalpp(+0x12eb5a) [0x558419554b5a]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f33e7e02d2f]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f33e7e1ec36]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f33e7e20614]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f33e7e20863]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe5016) [0x7f33e7f63016]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x65) [0x7f33e7f61a55]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x263606) [0x7f33e8663606]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f33e7e02d2f]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f33e7e1ec36]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f33e7e20614]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f33e7e20863]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libappmenu-gtk3-parser.so.0(+0x8497) [0x7f33e2942497]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x332ad) [0x7f33e832c2ad]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x174) [0x7f33e7d09c44]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f33e7d5f258]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f33e7d073e3]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f33e7f5efb5]
??:0
[bt] #24 xournalpp(_ZN11XournalMain3runEiPPc+0x5eb) [0x55841950562b]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f33e7229d90]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f33e7229e40]
??:0
[bt] #27 xournalpp(_start+0x25) [0x558419501065]
??:0

Execution log:

DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
WARNING : xopp :: configfile does not exist /home/denis/.config/xournalpp/settings.xml

INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/denis/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Using default latex template in /usr/share/xournalpp/resources/default_template.tex
DEBUG   : -- :: Name com.canonical.AppMenu.Registrar on the session bus is owned by :1.32

WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/denis/.cache/xournalpp/errorlogs/errorlog.20230830-011616.log

**Comment by rolandlo** [comment]
That crash is already fixed in version 1.2.1.  So please upgrade (and delete the crash log).
