### ISSUE TITLE
Space on the right of a page is white on launch but gets gray after any mouse event

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#5120]
### Operating System

Linux

### (Linux only) Distribution

Manjaro Linux

### (Linux only) Desktop Environment

Xfce with Compiz

### (Linux Only) Display Server

X.Org

### Installation Method

Official Release

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

See screenshot:

![Workspace 1_004](https://github.com/xournalpp/xournalpp/assets/1191480/30e13b56-fdf0-4040-aa30-a485d6c370e6)

When launching Xournal++ by opening a .xopp file which contains annotations for a PDF file, the space right of the page is white. As soon as any mouse event is triggered (a click, a scroll etc) the space becomes gray like it is supposed to be.

### Expected Behaviour

It should be symmetrically gray left and right of the page.

### Steps to Reproduce

1. Annotate a PDF file and save in a .xopp file.
2. Open the .xopp file.
3. Observe the issue.
4. Click a mouse button and observe the issue disappear.

### Additional Context

I think, the issue is present since the 1.2.0 release.

**Comment by tattsan** [comment]
Duplicate of #5102 .  This bug was introduced by  9d4f59c0d560fba8c69ab695b75695d74a1c32ed .

**Comment by Photon89** [comment]
Thanks, I'll subscribe to updates there then!
