### ISSUE TITLE
Configure Page Template Crashes Windows 10

### ISSUE THREAD

**Issue by IkeEisenhauer** [xournalpp/xournalpp#5122]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Dev install from GitHub

### Xournal++ Version

1.2.1+dev

### libgtk Version

3.24.39

### Bug Description

Journal>Configure Page Template 

Closes app immediately

### Expected Behaviour

Should open Configure Page Template Dialog and not close app

### Steps to Reproduce

1. Start app
2. Select Configure Page Template from menu

**Comment by rolandlo** [comment]
I can't confirm the issue. It works fine on Windows 10 for me. Could it be that you have an invalid `pagetemplates.ini` file somewhere?

**Comment by IkeEisenhauer** [comment]
I found the issue, it was a corrupt settings.xml.

The issue is if you make a new page style in pagetemplate.ini, then set it to the default template (used by settings.xml), then subsequently delete that style from pagetemplates.ini. 

The settings.xml gets corrupted and the configure page template can not locate the, now missing, style and crashes.

This is a one off anomaly and I will close the issue.
