### ISSUE TITLE
error when creating a copy and customizing the toolbar

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#5136]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official launching

### Xournal++ Version

1.2.1 +dev

### libgtk Version

3.24.39

### Bug Description

when i choose any mode or toolbar configuration and then i want to customize it, it tells me that in order to do that i have to create a copy, i click on accept and xournal closes. it doesn't even let me save my progress.

### Expected Behaviour

I just want it to allow me to customize as before

### Steps to Reproduce

view > toolbar > customize

**Comment by Febbe** [comment]
Do you have a crash log, I can't reproduce this on my machine (1.2.1)?
