### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PushkinKachroo** [xournalpp/xournalpp#5138]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 22.04

### (Linux Only) Display Server

None

### Installation Method

terminal apt

### Xournal++ Version

xournalpp 1.2.1

### libgtk Version

3.24.38

### Bug Description

crashed

### Expected Behaviour

it crashed while working on a pdf file

### Steps to Reproduce

it crashed while working on a pdf file

**Comment by rolandlo** [comment]
Do you have a crash log? There is not enough info without to do anything about it.
