### ISSUE TITLE
Crash when messing with the pen

### ISSUE THREAD

**Issue by audunmg** [xournalpp/xournalpp#5141]
### Operating System

Linux

### (Linux only) Distribution

Arch linux

### (Linux only) Desktop Environment

Arch

### (Linux Only) Display Server

Wayland

### Installation Method

aur, git version

### Xournal++ Version

1.2.0+dev (7f5814ee)

### libgtk Version

3.24.38

### Bug Description

Crash when messing around with a pen.

### Expected Behaviour

Not crash.

### Steps to Reproduce

Not sure how to reproduce.

I was just messing around, lifting and making lines repeatedly and erasing them again.

### Additional Context

The document I was working on was autosaved not too long ago, so my notes were safe.

I really appreciate that.

I'm not sure how helpful the crash log and description is.

If this crash log is of no help, I wouldn't mind if you just close off this issue, especially since I wasn't able to reproduce the crash.

Here's the error log. The filename and username has been changed so I'm more comfortable sharing this file publicly:
[errorlog.20230913-133748.log](https://github.com/xournalpp/xournalpp/files/12593543/errorlog.20230913-133748.log)

**Comment by rolandlo** [comment]
Thanks for reporting. This was an assertion failure 
```term
Assertion failed: p.z > 0.0
```
an issue, we know of, see e.g. #5087.
