### ISSUE TITLE
InsertNewPageIcon and BackGroundSelectButon remain horizontal even in vertical toolbar.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#5145]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

no DE

### (Linux Only) Display Server

X.Org

### Installation Method

Built from source.

### Xournal++ Version

Master ( 86eeda5afd1f0a7bcbe9fbe960794011cd388c76 or after )

### libgtk Version

3.24.38

### Bug Description

InsertNewPageIcon and BackgroundSelectButon should be laid out  vertically in vertical toolbar.
But since 86eeda5afd1f0a7bcbe9fbe960794011cd388c76 , it is laid out horizontally.

### Expected Behaviour

InsertNewPageIcon and BackgroundSelectButon should be laid out  vertically in vertical toolbar.

### Steps to Reproduce

1. Create a left toolbar or a right toolbar.
2. Put InsertNewPage icon on that toolbar.

### Additional Context
![HorizontalIcons](https://github.com/xournalpp/xournalpp/assets/6355486/966cd313-5da4-4377-baf0-1603d2381b11)

**Comment by tattsan** [comment]
PenIcon and LineTypeSelectButon are laid out normally.

**Comment by bhennion** [comment]
Nice catch. I'll issue a quick fix
