### ISSUE TITLE
Translation mistake [fr-FR]

### ISSUE THREAD

**Issue by Sieger14** [xournalpp/xournalpp#5146]
### Feature Description

The word "[Rapporteur](https://fr.wikipedia.org/wiki/Rapporteur)" should be used instead of "[Boussole](https://fr.wikipedia.org/wiki/Boussole)".

**Comment by rolandlo** [comment]
Please report translation mistakes to our [Crowdin project](https://crowdin.com/project/xournalpp). All the translations are managed there.
