### ISSUE TITLE
Crash when clicking simultaneously right  and left mouse button

### ISSUE THREAD

**Issue by EmmanuelEngineer** [xournalpp/xournalpp#5149]
### Operating System

Linux

### (Linux only) Distribution

Pop!_OS 22.04 LTS x86_64

### (Linux only) Desktop Environment

GNOME 42.5 

### (Linux Only) Display Server

X.Org

### Installation Method

Apt

### Xournal++ Version

xournalpp 1.2.1

### libgtk Version

libgtk: 3.24.33

### Bug Description

When clicking with right mouse button and simultaneously left button the whole app crashes, or at least only the focused window of the app.
I noticed this when selecting a text block with the right button and than clicking with the left mouse to move the block in another place, leaving the right button still pressed in for a split second.

### Expected Behaviour

Not crash and substitute the right key-down event of the button with a left key-down event

### Steps to Reproduce

Open the app (even on a new file)  -> Press right Button without letting it go -> Press left Button

### Additional Context

Date: Tue Sep 12 14:52:33 2023
Error: signal 6
Xournal++ version 1.2.1
Gtk version 3.24.33

[bt]: (0) xournalpp(+0xc046d) [0x55c3df5bd46d]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f785dc42520]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f785dc96a7c]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f785dc42476]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f785dc287f3]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f785dc2871b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f785dc39e96]
[bt]: (7) xournalpp(_ZN11XojPageView18onButtonPressEventERK17PositionInputData+0x8dc) [0x55c3df6880ec]
[bt]: (8) xournalpp(_ZN15PenInputHandler11actionStartERK10InputEvent+0x29f) [0x55c3df5fa6df]
[bt]: (9) xournalpp(_ZN17MouseInputHandler10handleImplERK10InputEvent+0x143) [0x55c3df5f5333]
[bt]: (10) xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x3d4) [0x55c3df5f5084]
[bt]: (11) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e6eb8) [0x7f785ede6eb8]
[bt]: (12) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1290) [0x7f785e649700]
[bt]: (13) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f785e649863]
[bt]: (14) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3ae5cb) [0x7f785edae5cb]
[bt]: (15) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x251680) [0x7f785ec51680]
[bt]: (16) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0xd3a) [0x7f785ec5252a]
[bt]: (17) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x39743) [0x7f785e932743]
[bt]: (18) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x70f56) [0x7f785e969f56]
[bt]: (19) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x26b) [0x7f785e532d3b]
[bt]: (20) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f785e588258]
[bt]: (21) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f785e5303e3]
[bt]: (22) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f785e787fb5]
[bt]: (23) xournalpp(_ZN11XournalMain3runEiPPc+0x646) [0x55c3df5bb046]
[bt]: (24) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f785dc29d90]
[bt]: (25) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f785dc29e40]
[bt]: (26) xournalpp(_start+0x25) [0x55c3df5b8cc5]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xc0a46) [0x55c3df5bda46]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f785dc42520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f785dc96a7c]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f785dc42476]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f785dc287f3]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f785dc2871b]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f785dc39e96]
??:0
[bt] #8 xournalpp(_ZN11XojPageView18onButtonPressEventERK17PositionInputData+0x8dc) [0x55c3df6880ec]
??:0
[bt] #9 xournalpp(_ZN15PenInputHandler11actionStartERK10InputEvent+0x29f) [0x55c3df5fa6df]
??:0
[bt] #10 xournalpp(_ZN17MouseInputHandler10handleImplERK10InputEvent+0x143) [0x55c3df5f5333]
??:0
[bt] #11 xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x3d4) [0x55c3df5f5084]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e6eb8) [0x7f785ede6eb8]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1290) [0x7f785e649700]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f785e649863]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3ae5cb) [0x7f785edae5cb]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x251680) [0x7f785ec51680]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0xd3a) [0x7f785ec5252a]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x39743) [0x7f785e932743]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x70f56) [0x7f785e969f56]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x26b) [0x7f785e532d3b]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f785e588258]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f785e5303e3]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f785e787fb5]
??:0
[bt] #24 xournalpp(_ZN11XournalMain3runEiPPc+0x646) [0x55c3df5bb046]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f785dc29d90]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f785dc29e40]
??:0
[bt] #27 xournalpp(_start+0x25) [0x55c3df5b8cc5]
??:0

Execution log:

DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/emmavico/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
DEBUG   : GLib :: Failed to set scheduler settings: Operazione non permessa
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/emmavico/.cache/xournalpp/errorlogs/errorlog.20230912-145233.log

**Comment by bhennion** [comment]
I can't reproduce. All I managed to get with 1.2.1 is a warning
```
(com.github.xournalpp.xournalpp:247894): xopp-WARNING **: 10:26:06.801: InputHandler already exists upon XojPageView::onButtonPressEvent. Deleting it (and its views)
```
I guess it has to depend on which tools are linked to your buttons. So I'd need a screenshot of your Mouse settings tab.
Also, is something like "Emulate middle button when both left and right buttons are pressed" available/enabled on your DE?

Finally, if you can reproduce this consistently, it would help to run the program from a terminal and post here the output after it crashed.

**Comment by EmmanuelEngineer** [comment]
Sorry the wait, i didn't logged in git for a while.
I will insert the log from the terminal and some screenshot on the input settings i have.
![image](https://github.com/xournalpp/xournalpp/assets/83717867/216e5350-01ec-46d3-bc0b-ad160bed7827)
![image](https://github.com/xournalpp/xournalpp/assets/83717867/8f9a2621-7ca0-4805-a64b-4cee02a67107)
![image](https://github.com/xournalpp/xournalpp/assets/83717867/28d3f378-c9ee-4b5c-ac6f-80c0a08c6b4b)
![image](https://github.com/xournalpp/xournalpp/assets/83717867/c8b97ed8-6f0b-4ef4-833b-e526fedb948e)
![image](https://github.com/xournalpp/xournalpp/assets/83717867/7cc93f62-bdad-4f10-b4fc-41a318265c4b)

```

TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
xopp-Message: 17:17:37.702: Plugin "MigrateFontSizes" UI initialized
xopp-Message: 17:17:37.704: Plugin "vi-xournalpp" UI initialized
xournalpp: ./src/core/gui/PageView.cpp:316: bool XojPageView::onButtonPressEvent(const PositionInputData&): asserzione "settings->getInputSystemTPCButtonEnabled() && "the selection has already been created by a stylus button press while the stylus was " "hovering!"" non riuscita.

(com.github.xournalpp.xournalpp:57002): xopp-WARNING **: 17:17:46.539: [Crash Handler] Crashed with signal 6

(com.github.xournalpp.xournalpp:57002): xopp-WARNING **: 17:17:46.545: [Crash Handler] Wrote crash log to: /home/emmavico/.cache/xournalpp/errorlogs/errorlog.20231006-171746.log

(com.github.xournalpp.xournalpp:57002): xopp-WARNING **: 17:17:46.669: Tentativo di salvataggio d'emergenza per il documento corrente…

(com.github.xournalpp.xournalpp:57002): xopp-WARNING **: 17:17:46.671: Salvataggio avvenuto con successo in "/home/emmavico/.config/xournalpp/emergencysave.xopp"
```

**Comment by bhennion** [comment]
Ok. I can reproduce now. This is related to your setting

![Screenshot_20231007_071914](https://github.com/xournalpp/xournalpp/assets/17818041/598836c6-5974-4670-a3f3-2f871f32b86d)

As a workaround, change it to None (except #5182 makes it hard to change back...)
