### ISSUE TITLE
Dark mode not working since 1.2.0

### ISSUE THREAD

**Issue by mpeter50** [xournalpp/xournalpp#5152]
### Operating System

Linux

### (Linux only) Distribution

openSUSE Leap 15.5

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

Wayland

### Installation Method

AppImage

### Xournal++ Version

1.2.1

### libgtk Version

3.24.20

### Bug Description

When I open Xournal, its user interface uses a bright background everywhere (behind buttons at the top and side menus, in context menus, etc) except behind the paper, where it is dark.

### Expected Behaviour

Xournal should use the dark background as it did before the update, in version 1.1.3.

### Steps to Reproduce

0. Set dark theme in Desktop Environmen't settings tool
1. Download the Xournal 1.2.1 AppImage from the releases section of this repo
2. Run the AppImage
3. Observe Xournal using a bright background

### Additional Context

On my system a dark background is set globally. The Plasma Global Theme is set to Breeze Dark, and the Gnome/GTK Application Style is set to Adwaita-dark in the System Settings.

As far as I can tell both 1.1.3 and the 1.2.1 versions of Xournal use the same configuration files, and I run both of them as appimages, but 1.2.1 and even 1.2.0 uses a bright theme.
The "View -> Colors -> Dark Theme" checkbox in the Preferences has no effect after restarting Xournal.

If I run the 1.1.3 AppImage, it still uses the dark mode.

**Comment by rolandlo** [comment]
The way the AppImage determines dark/light mode is defined in the [linuxdeploy-plugin-gtk](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/pull/49/files) we use to build the AppImage.
Internally it uses `gsettings get org.gnome.desktop.interface color-scheme` to decide whether to use dark or light mode. This behavior can be overridden by the user using the environment variable `APPIMAGE_GTK_THEME`. 

Two questions:
- Does 
```term
gsettings get org.gnome.desktop.interface color-scheme
```
return anything on your system? Maybe not, since you are using KDE.
- Does
```term
APPIMAGE_GTK_THEME=Adwaita-dark ./xournalpp-1.2.1-x86_64.AppImage
``` 
run in dark mode?

**Comment by mpeter50** [comment]
> Does
> ```
> gsettings get org.gnome.desktop.interface color-scheme
> ```
> return anything on your system? Maybe not, since you are using KDE.

It says `No such key "color-scheme"`.

> 
> Does
> ```
> APPIMAGE_GTK_THEME=Adwaita-dark ./xournalpp-1.2.1-x86_64.AppImage
> ```
> run in dark mode?

Yes, it does this way.

**Comment by rolandlo** [comment]
And does `settings get org.gnome.desktop.interface gtk-theme` return something?

**Comment by mpeter50** [comment]
Yes, it says `Adwaita-dark`

**Comment by mpeter50** [comment]
For the record, this is Plasma 5.27.4. I don't know if more recent versions make use of the `color-scheme` setting

**Comment by bhennion** [comment]
I cannot reproduce. I have Plasma 5.27.7 and `gsettings get org.gnome.desktop.interface color-scheme` returns `prefer-dark`. Resetting it via `gsettings reset org.gnome.desktop.interface color-scheme` does not change the behaviour (but the value is now `default`).

I doubt this changed since 5.27.4 though. It's more likely a configuration issue.

**Comment by mpeter50** [comment]
[It seems](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/commit/e3c2c421d78a8bfff466ad2180781cbaacce0319) it needs version 42 of the `gsettings-desktop-schemas` package ([source](https://reddit.com/r/gnome/comments/rzknul/how_do_i_switch_the_freedesktop_colorscheme/hrvxp0r/?context=3)). The latest available on my system is 41.0.

I have also asked in a KDE channel, and someone [told me](https://matrix.to/#/!gYaaEyvNWxTzXssOmq:kde.org/$LNeW_qOZOISgYj-2S5q4TtXVh0SnT8O7T3CY3pl9EW4?via=matrix.org&via=im.kde.org&via=kde.org) it would be more appropriate to use the freedesktop color preference instead of `org.gnome.desktop.interface color-scheme`.
What do you think about it?

Regarding that, I have found [this page](https://www.freedesktop.org/wiki/Specifications/colorscheme-spec/), but the links to the actual specification are broken.
I have found [this](https://github.com/telegramdesktop/tdesktop/issues/17061), according to which the freedesktop setting is at `org.freedesktop.appearance color-scheme`, but on my system there is no `org.freedesktop.appearance` schema either, according to `gsettings list-schemas`.

**Comment by mpeter50** [comment]
Update: the freedesktop setting is to be retrieved over dbus, not gsettings.
It seems that way is supported on my system:
```
$ qdbus-qt5 --literal org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.ReadAll org.freedesktop.appearance
```
```
[Argument: a{sa{sv}} {"org.freedesktop.appearance" = [Argument: a{sv} {"color-scheme" = [Variant(uint): 1]}], "org.freedesktop.appearance" = [Argument: a{sv} {"color-scheme" = [Variant(uint): 0]}]}]
```

**Comment by bhennion** [comment]
> I have also asked in a KDE channel, and someone told me it would be more appropriate to use the freedesktop color preference instead of org.gnome.desktop.interface color-scheme.
> What do you think about it?

I'm not sure we don't already. In any case, this is handled directly by Gtk. I don't think we have a say in this.

**Comment by bhennion** [comment]
Also, the fact it works when explicitely setting APPIMAGE_GTK_THEME=Adwaita-dark suggests it is not about the color-scheme key.

**Comment by rolandlo** [comment]
> > I have also asked in a KDE channel, and someone told me it would be more appropriate to use the freedesktop color preference instead of org.gnome.desktop.interface color-scheme.
> > What do you think about it?
> 
> I'm not sure we don't already. In any case, this is handled directly by Gtk. I don't think we have a say in this.

It's handled by the [`linuxdeploy-gtk-plugin`](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) maintainers. We use that plugin to build the AppImage.

**Comment by rolandlo** [comment]
> > > I have also asked in a KDE channel, and someone told me it would be more appropriate to use the freedesktop color preference instead of org.gnome.desktop.interface color-scheme.
> > > What do you think about it?
> > 
> > 
> > I'm not sure we don't already. In any case, this is handled directly by Gtk. I don't think we have a say in this.
> 
> It's handled by the [`linuxdeploy-gtk-plugin`](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) maintainers. We use that plugin to build the AppImage.

Indeed they have fixed it right away, see https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/pull/56
