### ISSUE TITLE
Cannot find flathub pdflatex package

### ISSUE THREAD

**Issue by Kibranoz** [xournalpp/xournalpp#5155]
### Operating System

Linux

### (Linux only) Distribution

Pop_OS

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

X.Org

### Installation Method

from the store

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Cannot add latex, I installed the latex version that was specified in the error message, but it still does not work

![image](https://github.com/xournalpp/xournalpp/assets/35783229/4b334100-eec7-4cea-aad0-e73b96f8aa4f)

### Expected Behaviour

It should be working if I have installed the required software

### Steps to Reproduce

1.flatpak install flathub org.freedesktop.Sdk.Extension.texlive
2. open a xournal pp file
3. try to add latex
4. see the error message is still there

**Comment by rolandlo** [comment]
Can you try 
```term
flatpak run --command=sh --devel com.github.xournalpp.xournalpp
pdflatex --version
```
to see if pdflatex can be accessed inside the app sandbox?

**Comment by Kibranoz** [comment]
The command is not found

**Comment by Kibranoz** [comment]
pdflatex is not found.

**Comment by rolandlo** [comment]
The flatpak wants the 22.08 texlive extension, not the 23.08 (or any other) version. Maybe the error message should have said that, but it's a bit hard to keep in sync with the flathub repo, which can get updated at any time.

So either you must install the 22.08 version (e.g. directly via) 

```term
flatpak install flathub org.freedesktop.Sdk.Extension.texlive//22.08
```

or the flatpak manifest must be updated (and all users must install the 23.08 version). If you give it some time the later will happen. You can also keep both versions installed (if you don't mind about disk space; those extensions are huge).

**Comment by rolandlo** [comment]
I tested upgrading the texlive extension version to 23.08. It doesn't work though. It seems to be compiled with a too recent version of the Gnu C Library. So let's stick with 22.08 for now.

**Comment by rolandlo** [comment]
Closing the issue, since the 22.08 extension must be used until the Gnome 45 runtime comes out.

**Comment by rolandlo** [comment]
The runtime has now been updated to Gnome 45 and the texlive extension to 23.08.
