### ISSUE TITLE
Number key inputs do not get passed to plugin

### ISSUE THREAD

**Issue by raw-bacon** [xournalpp/xournalpp#5156]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

Sway

### (Linux Only) Display Server

Wayland

### Installation Method

Community repository

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

When mapping an action to a number key in a plugin, the action is not executed and instead the tool color changes.

### Expected Behaviour

The tool color does not change and the plugin binding gets executed.

### Steps to Reproduce

First, make a plugin `main.lua` which has a keybinding on a number key. E.g.,
```lua
function initUi()
    ref = app.registerUi({["menu"] = "Fine", ["callback"] = "fine", ["accelerator"] = "1"});
    ref = app.registerUi({["menu"] = "Thick", ["callback"] = "thick", ["accelerator"] = "2"});
end

function fine()
    app.uiAction({["action"] = "ACTION_SIZE_FINE"})
end

function thick()
    app.uiAction({["action"] = "ACTION_SIZE_FINE"})
end
```
together with a `plugin.ini`, e.g.,
```dosini
[about]
author=Test

description=Test

version=1.2.x

[default]
enabled=true

[plugin]
mainfile=main.lua
```

Enable the plugin in the plugins settings and press `1`, draw a stroke, press `2`, draw a stroke. The two strokes have different colors but the same thickness (whereas they should have the same color but different thicknesses).

### Additional Context

I was made aware of the problem in an [issue](https://github.com/raw-bacon/vi-xournalpp/issues/20) in my plugin vi-xournalpp.

**Comment by rolandlo** [comment]
I'm sorry your nice plugin broke. But the changes 
- to use number keys for switching colors #4416
- to have the Xournal++ widgets first handle keyboard presses before plugins can handle them #4797
were both intentional

So can you find a solution using different accelerators maybe?!

**Comment by raw-bacon** [comment]
Oh, the key event handling refactor is actually great news - I had not noticed.

Sure, I can use other accelerators :) Thanks, for letting me know!
