### ISSUE TITLE
extent.IsValid assertion error after hitting undo several times

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#5162]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.1+dev

### libgtk Version

3.24.37

### Bug Description

While undoing the insertion of some strokes (that were generated through the function plotter plugin) I got a crash due to an assertion error 

```term
MESSAGE : xopp :: Autospeicherung nach /home/roland/Unterricht/Klasse_M5a_GF/LaTeX/.Folgen_Reihen_Grenzwerte_M5a.autosave.xopp
CRITICAL: xopp :: Assertion failed: extent.isValid()
    Message: Invalid range in Mask(): X  179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000 -- 1.000000
                             Y  179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000 -- 1.000000
    in function constructorImpl
    at line 61 of ./src/core/view/Mask.cpp
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/roland/.cache/xournalpp/errorlogs/errorlog.20230920-093656.log
```

<details>
<summary>Here is the crash log</summary>

Date: Wed Sep 20 09:36:56 2023
Error: signal 6
Xournal++ version 1.2.1+dev
Gtk version 3.24.37

[bt]: (0) /usr/bin/xournalpp(+0xc236e) [0x55972e3d736e]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7fc44d03c4b0]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11b) [0x7fc44d090ffb]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x16) [0x7fc44d03c406]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7fc44d02287c]
[bt]: (5) /usr/bin/xournalpp(+0xb8162) [0x55972e3cd162]
[bt]: (6) /usr/bin/xournalpp(+0x1d0f33) [0x55972e4e5f33]
[bt]: (7) /usr/bin/xournalpp(_ZN3xoj4view4MaskC2EiRK5Ranged14_cairo_content+0xd5) [0x55972e4e62b5]
[bt]: (8) /usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x99) [0x55972e4fb2f9]
[bt]: (9) /usr/bin/xournalpp(_ZN9RenderJob3runEv+0xab) [0x55972e4fb47b]
[bt]: (10) /usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x101) [0x55972e3d6d11]
[bt]: (11) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x87361) [0x7fc44da63361]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(+0x8f18a) [0x7fc44d08f18a]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6(+0x11dbd0) [0x7fc44d11dbd0]

</details>

I don't know if the autosaving played a role here.

### Expected Behaviour

No crash

### Steps to Reproduce

I will see if I can make it reproducible.

### Additional Context

It looks like the PPA is still compiled in Debug mode despite of #5118. Otherwise why would the app crash on assertion error?

**Comment by bhennion** [comment]
Probably the same kind of problem as in #5046
