### ISSUE TITLE
Autosave file may be corrupted

### ISSUE THREAD

**Issue by F4DiS** [xournalpp/xournalpp#5165]
### Operating System

Linux

### (Linux only) Distribution

Gentoo

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

X.Org

### Installation Method

emerge -avq xournalpp

### Xournal++ Version

1.1.3

### libgtk Version

3.24.38

### Bug Description

an autosave file is created on top of the previous one meaning that when a new one is created, u loose the previous one, but whats interesting is that if it fails to create u actually loose your autosave. my old hard drive just randomly disconnected when trying to write to autosave file leading to 0 bytes size autosave file. maybe this program could somehow create the second autosave file first, and only if it is created successfully then replace the first autosave file with it, so that in any moment of time we have a working copy.

### Expected Behaviour

1) open xournalpp and write anything
2) wait for autosave process starts
3) turn off ur computer while its autosaving (or just have an old unreliable laptop that dies at any moment like i do)
4) turn it back on
5) have the last autosave file that opens correctly

### Steps to Reproduce

1) open xournalpp and write anything
2) wait for autosave process starts
3) turn off ur computer while its autosaving (or just have an old unreliable laptop that dies at any moment like i do)
4) turn it back on
5) your **only** autosave file is damaged and can not be opened

**Comment by bhennion** [comment]
We are already renaming the old autosave file (to `something.old.autosave.xopp`) before saving. Don't you have such a file in your autsave folder?

**Comment by F4DiS** [comment]
no, my system stopped working properly after the hard drive fall, and when i rebooted i only saw the single ### `.something.autosave.xopp` file with 0 bytes size

maybe my hard drive just feel too bad and that's why i haven't seen the .old.autosave file. if the renaming before creating new autosave file already happens then well i appreciate how thoughtfull and elaborate this program is, and this issue can be closed
