### ISSUE TITLE
Publisher:  Unknown publisher

### ISSUE THREAD

**Issue by 4i8** [xournalpp/xournalpp#5171]
### Feature Description

![image](https://github.com/xournalpp/xournalpp/assets/76555623/2072443c-e524-41ca-9e9c-30fd3d487bbe)
Why isn't a certification included in the program?

**Comment by rolandlo** [comment]
Simply put: It costs. 

An Extended Validation" (EV) code signing certificate costs between 250 and 700 dollars per year. See https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by 4i8** [comment]
> Simply put: It costs.
> 
> An Extended Validation" (EV) code signing certificate costs between 250 and 700 dollars per year. See https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

Damn capitalism.

**Comment by archisman-panigrahi** [comment]
Please try the Microsoft Store version. Microsoft signs it for free https://apps.microsoft.com/detail/9nn1hhct0p1x?hl=en-US&gl=US
