### ISSUE TITLE
program crashing when i change function of stylus button's function

### ISSUE THREAD

**Issue by yodavid1984** [xournalpp/xournalpp#5182]
### Operating System

Linux

### (Linux only) Distribution

linux mint 20

### (Linux only) Desktop Environment

cinnamon 4.6.6

### (Linux Only) Display Server

None

### Installation Method

sudo apt get install xournalpp

### Xournal++ Version

1.2.1+dev

### libgtk Version

3.24.18

### Bug Description

i set up the buttons of the stylus to open the floating menu (experimental). now when i try to change one of the button's function back to "no function", the progrm crashes

### Expected Behaviour

the function of the selected button should change to the one i selected

### Steps to Reproduce

change the function of the three stylus buttons and the mouse right button to floating menu. then try to change back

**Comment by BattyBoopers** [comment]
I have pretty much the same problem, but for me the stylus config works just fine, but the same option in the mouse config causes the crash.
Using latest nightly version

**Comment by bhennion** [comment]
I can reproduce, try to set mouse button to any selection tool.
I bisected. The first bad commit is 48aa8b87a690c7f6b8d53f68d66b87e73c079e97. I'll have a look.
