### ISSUE TITLE
Crashes if the mouse moves while you draw, with the pen tool only

### ISSUE THREAD

**Issue by murfra** [xournalpp/xournalpp#5186]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

i3wm

### (Linux Only) Display Server

X.Org

### Installation Method

sudo pacman -S xournalpp

### Xournal++ Version

1.2.1 (b48932a2)

### libgtk Version

3.24.38

### Bug Description

The program crashes if, while drawing with the pen tool, you accidentally touch the mouse.

### Expected Behaviour

Of the Pen tool: The same of "Region Select" tool

### Steps to Reproduce

1. Select "Region Select"
2. Use the stylus pen to draw
3. While drawing move the mouse
4. Repeat the same process with the Pen Tool selected

### Additional Context

I don't know if it's difficult to implement, but it would be better if the pen tool had the same behavior as the region selection tool (when you move the mouse while drawing). In Krita, something I noticed is that the movements on the mouse, while it is drawn with the graphics tablet, are not "processed", I don't know if it helps in any way.

https://github.com/xournalpp/xournalpp/assets/66890436/26402d90-d7df-4c11-9a5c-b7e910f04ff1

**Comment by rolandlo** [comment]
The bug has been fixed with #5170 in the release-branch. It's not in master yet, but it will arrive there, and be part of release 1.2.2.
