### ISSUE TITLE
Error with plugin when pressing a key combination assigned to the pen button

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#5192]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release

### Xournal++ Version

1.2.1 +dev

### libgtk Version

3.24.39

### Bug Description

for personal reasons I had to reinstall xournal, but first I have already configured a plugin with the shortcuts for my pen and tablet, it has always worked for me just copy it in the correct folder and activate it in the add-ons section, back to the topic reinstall xournal++ then copy the folder containing the plugin as usual. the tablet pen has 2 buttons one is configured with the alt_s key and the other with alt_b, pressing the alt_b button works normally, but pressing alt_s now I get a window that I don't understand what it means. 
![image](https://github.com/xournalpp/xournalpp/assets/28522011/15e0d4a4-7fad-4f61-95eb-cb5fec367fc4)

### Expected Behaviour

pues me gustaria que funcion normalmente ese boton recorria entre las herramientas flechas , lapiz , circulos lineas cuadrados

### Steps to Reproduce

1 ) paste plugin in the corresponding folder
2 ) activate the check in the plugin manager 
3 ) use the pencil and press the button that is linked with alt_s

### Additional Context

none

**Comment by rolandlo** [comment]
Can you please add the plugin in a zip-file, so we can try and debug the issue?

**Comment by vladQll** [comment]
[ShortcutsPlugin.zip](https://github.com/xournalpp/xournalpp/files/12792629/ShortcutsPlugin.zip)
@rolandlo este es el archivo

**Comment by rolandlo** [comment]
For me the plugin works fine. Moreover `luapushfstring` is only used for `app.addImages`, `app.setSidebarPageNo` and `app.glib_rename`. None of these commands are used in the `tool` callback function.

Do you have any other plugins activated in the plugin manager than the ShortcutsPlugin? Does any of those plugins use the `<Alt>s` shortcut?

**Comment by vladQll** [comment]
me he fijado y estaba activado por defecto el complemento MigrateFontSizes ya lo desactive y volvi a abrir xournal , pero igual sigue apareciendo esa ventana cada que presiono el boton

**Comment by vladQll** [comment]
![image](https://github.com/xournalpp/xournalpp/assets/28522011/f4626ef6-446b-47e0-b65d-565a4955ecc4)
I also have configured the alt_r key to cycle through the colors 

but when I use it I get the following problem
![image](https://github.com/xournalpp/xournalpp/assets/28522011/04423bd9-28dc-41ca-a4cf-c96064c9509c)

**Comment by rolandlo** [comment]
The error with color cycling is clear: You haven't defined `currentColor` anywhere in the `main.lua` file.
Add a line like `local currentColor = 0` on line 38 or so.

The error with the tool cycling must have to do with this error message:
https://github.com/xournalpp/xournalpp/blob/d6b7d5df081d36cac31f2d35e6764b860f0899af/src/core/plugin/luapi_application.h#L1470-L1474
in `changeToolColor`.

I discovered that the error message is issued by Lua itself when `lua_pushfstring` (or similar) is used to push a message that contains `%x`. 
Looks like `%x` for hexadecimal is not supported in Lua 5.4. 

Can you replace the line 
```lua
	activeColor = app.getToolInfo("active")["color"]
```
by
```lua
	activeColor = app.getToolInfo("pen")["color"]
```
Looks like the previously active tool (eraser) doesn't have a valid color.

**Comment by rolandlo** [comment]
The problem was introduced in https://github.com/xournalpp/xournalpp/pull/4652/files
`g_warning` can use `%x` for hexadecimals, `luaL_error` can't.

**Comment by vladQll** [comment]
ah so that makes sense because previously I also added the colors of my preference in rgb in the palette.gpl file and when I opened it I got an error I didn't report it because it disappeared when I deleted a color I had added but it seems a little strange I will try to send you a screenshot, but first I will try the solution from the messages above.

**Comment by vladQll** [comment]
hi @rolandlo if you are referring to line 92 replace as you said but I still get the error when I try to switch tools . to clarify that pen button refers to the alt_s combination and manages two tools the pen and the eraser , then when I use the pen when I first open xournal , if after writing anything I want to switch to eraser it changes normally , but if I press again to return to use the pen jumps that message
![image](https://github.com/xournalpp/xournalpp/assets/28522011/d98ee609-c9e1-4b9b-92c2-20354ab53640)

**Comment by rolandlo** [comment]
See #5253 for a fix
