### ISSUE TITLE
Bug message

### ISSUE THREAD

**Issue by andremiziara** [xournalpp/xournalpp#5196]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Official release

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

I didn't see the problem. The app show me a error message when I start it.

### Expected Behaviour

Do not show me a error message when I open a program.

### Steps to Reproduce

1. Open a pdf;
2. Use a pen tablet to take notes;
3. Save the notes;
4. Open the file with notes again;

**Comment by tmoerschell** [comment]
Do you have an errorlog in `~/.cache/xournalpp/errorlogs`? 
Did anything strange happen the time just before you began seeing this error message (Xournal++ closed unexpetedly, or your Desktop environment crashed, ...). 

For you not to see the error message anymore, you have to delete the error logs either through the popup you see on startup, or by removing all file in the directory mentioned above, BUT PLEASE... send the error log on here first so we can have a closer look!

**Comment by bhennion** [comment]
Closing as we can't do anything without the crashlog. Please reopen if you want to post it here.
