### ISSUE TITLE
SegFault when trying to customize the toolbar (Windows only)

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#5199]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release

### Xournal++ Version

1.2.1 +dev

### libgtk Version

3.24.39

### Bug Description

I choose a toolbar of my preference but I need to customize it but to customize it it asks me to create a copy when I click on make copy the program closes.

https://github.com/xournalpp/xournalpp/assets/28522011/54bef992-e142-4d49-a292-72e671abb149

### Expected Behaviour

pues solo espero el funcionamiento habitual

### Steps to Reproduce

1 choose toolbar
2 click on customize 
3 accept create copy to be able to customize

**Comment by bhennion** [comment]
Sorry about that. I must have broken something in #4372 . It is fixed by #5154 though. We might need to issue a faster fix if #5154 takes a long time to merge.

**Comment by vladQll** [comment]
I am very involved in the use of this program but not in the development or implementation because I do not have the necessary knowledge of programming, my question is: when can I download the new version where this problem has been solved? could you tell me I understand that xournal does not have an online update system, that is why many times I have had to delete the program and reinstall the new version.

**Comment by vladQll** [comment]
oh crap, I don't really understand how this works on github, or I'm very bad at this I can't find a link that allows me to find the file this bug solved, I deleted the xournal and downloaded it again thinking it already included the patch but I got the same problem, sorry to ask could you tell me if there is a link where I can download or still have not applied these solutions

**Comment by rolandlo** [comment]
@vladQll It's not yet fixed. We're still working on it.

**Comment by vladQll** [comment]
i understand @rolandlo thank you very much by the way i apologize if the translator translated my expressions wrong. well about that as i read that bhennion linked a pull request i thought he meant that he created a link to download the program with the problem solved, my fault i must get more familiar with the github terms.

**Comment by bhennion** [comment]
Yeah, I thought it was fixed in #5154 but it is not (yet). Sorry about that.

**Comment by bhennion** [comment]
Could anyone confirm that it worked prior to #4372 (e.g. with a nightly build from 20230930 or directly with commit 82711eda2ca04f962fbc615a77f8a6ae61b7d3a7)?

**Comment by vladQll** [comment]
I had to go back to the stable version, is there much difference in the changes between the stable version and the development version?

**Comment by bhennion** [comment]
Actually, this might have been fixed by 814b4f9d7b6b. Could anyone try the latest master?

**Comment by bhennion** [comment]
Fixed via #5200
