### ISSUE TITLE
Export as Dialog don't change extension

### ISSUE THREAD

**Issue by Hedronmx** [xournalpp/xournalpp#521]
When using "Exporting as ..."  If I change the format on the dropdown, the file extension doesn't change. 
The default extension is used which is .xopp
![Imgur](https://i.imgur.com/jnHYl1O.png)

I chose PNG but the file is being saved as .xopp

**Comment by luco5826** [comment]
Hi!
Confirmed on my system, right now the only way is to set PNG graphics on the dropdown menu AND manually changing the extension from .xopp or .pdf to .png
We are gonna fix it!

**Comment by luco5826** [comment]
@andreasb242 I found a problem:
when using the Export As.. dialog, Xournal++ does its checks only on the extension name, so we could set in the ComboBox PDF Document but, if we name the file with .png it will be exported as PNG.
So I suggest to modify the workflow, instead of checking on the extension after clicking on Export, we check on the value of the ComboBox appending the relative extension to the file name overwriting the one in the text entry
What do you think?

**Comment by morrolinux** [comment]
I did figure this out while trying to add some export tweaks (like "export with no background"):

We need to get the current filter from `BaseExportJob`:
```
string BaseExportJob::getFilterName()
{
	XOJ_CHECK_TYPE(BaseExportJob);
	
	GtkFileFilter* filter = gtk_file_chooser_get_filter(GTK_FILE_CHOOSER(dialog));  //gets the filter
	return gtk_file_filter_get_name(filter);   //gets the name (you can get the extension as well)
}
```

And we can call this method somewhere when the dialog hasn't been destroyed yet, like, for example, in `PdfExportJob::isUriValid`:

```
string filterName = BaseExportJob::getFilterName();
std::cout<<"FilterName: "<<filterName<<"\n";
```
You get the choosen filter name printed out

**Comment by morrolinux** [comment]
Next challenge will be to find a way to call it each time the filter has changed

**Comment by morrolinux** [comment]
I think it would be acceptable :) what do you think @andreasb242 ?

**Comment by andreasb242** [comment]
Yes, for me would this be OK, but you have to think about the "Do you want to overwrite" check, which you may need to reimplement.

I checked how GIMP handle this: They add additional to the filter a Type selection.
![grafik](https://user-images.githubusercontent.com/822958/50348893-63ac7780-053a-11e9-81ac-059ac15d9832.png)

If you don't add an extension, and don't select an extension, they don't allow to save you the image.
This would be the easiest solution.
(Sorry, yes, the Texts are German... But it's easy to reproduce)

![grafik](https://user-images.githubusercontent.com/822958/50348953-8dfe3500-053a-11e9-9df0-aaadc1b49819.png)

**Comment by andreasb242** [comment]
Fixed with https://github.com/xournalpp/xournalpp/pull/594
