### ISSUE TITLE
It close the window unexpectedly.

### ISSUE THREAD

**Issue by lourenko** [xournalpp/xournalpp#5222]
### Operating System

Linux

### (Linux only) Distribution

Debian 12

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

X.Org

### Installation Method

apt

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Close the window unexpectedly. 

### Expected Behaviour

Just save, without shut the application off. 

### Steps to Reproduce

Cannot reproduce. 

### Additional Context

Date: Fri Oct  6 18:08:33 2023
Error: signal 6
Xournal++ version 1.2.1
Gtk version 3.24.38

[bt]: (0) /usr/bin/xournalpp(+0xd7645) [0x558bc6b7b645]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3c510) [0x7f042477b510]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(+0x8a0fc) [0x7f04247c90fc]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x12) [0x7f042477b472]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f04247654b2]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x263d5) [0x7f04247653d5]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x353a2) [0x7f04247743a2]
[bt]: (7) /usr/bin/xournalpp(_ZN3xoj4view12TexImageViewD1Ev+0) [0x558bc6cc7930]
[bt]: (8) /usr/bin/xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x25b) [0x558bc6d0451b]
[bt]: (9) /usr/bin/xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0x10c) [0x558bc6c705cc]
[bt]: (10) /usr/bin/xournalpp(+0x143e55) [0x558bc6be7e55]
[bt]: (11) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (13) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (14) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x254744) [0x7f0425654744]
[bt]: (15) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x345e89) [0x7f0425745e89]
[bt]: (16) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x346d11) [0x7f0425746d11]
[bt]: (19) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (20) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (21) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (22) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2835de) [0x7f04256835de]
[bt]: (23) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (24) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (25) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x281205) [0x7f0425681205]
[bt]: (26) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (27) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (28) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (29) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xca528) [0x7f04254ca528]
[bt]: (30) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (31) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (32) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xcb9f5) [0x7f04254cb9f5]
[bt]: (33) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (34) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (35) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (36) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xca528) [0x7f04254ca528]
[bt]: (37) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (38) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (39) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xcb9f5) [0x7f04254cb9f5]
[bt]: (40) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (41) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (42) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (43) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xca528) [0x7f04254ca528]
[bt]: (44) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (45) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (46) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xcb9f5) [0x7f04254cb9f5]
[bt]: (47) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (48) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (49) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (50) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xca528) [0x7f04254ca528]
[bt]: (51) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
[bt]: (52) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
[bt]: (53) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xcb9f5) [0x7f04254cb9f5]
[bt]: (54) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (55) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (56) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (57) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (58) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
[bt]: (59) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
[bt]: (60) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
[bt]: (61) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x35ea80) [0x7f042575ea80]
[bt]: (62) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x7bf) [0x7f04255fe7df]
[bt]: (63) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3ba49) [0x7f042533ca49]
[bt]: (64) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4a419) [0x7f042534b419]
[bt]: (65) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4c096) [0x7f042534d096]
[bt]: (66) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4c29c) [0x7f042534d29c]
[bt]: (67) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x16749) [0x7f04250c9749]
[bt]: (68) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2b5bf) [0x7f04250de5bf]
[bt]: (69) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x36) [0x7f04250e4186]
[bt]: (70) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f04250e4243]
[bt]: (71) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x44596) [0x7f0425345596]
[bt]: (72) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3088b) [0x7f042533188b]
[bt]: (73) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5afee) [0x7f0424fc7fee]
[bt]: (74) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x57099) [0x7f0424fc4099]
[bt]: (75) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5a2d7) [0x7f0424fc72d7]
[bt]: (76) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7f0424fc78f0]
[bt]: (77) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x16d) [0x7f04251f9b5d]
[bt]: (78) /usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x636) [0x558bc6b7ec26]
[bt]: (79) /lib/x86_64-linux-gnu/libc.so.6(+0x276ca) [0x7f04247666ca]
[bt]: (80) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f0424766785]
[bt]: (81) /usr/bin/xournalpp(_start+0x21) [0x558bc6b7a5f1]

Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0xd7d54) [0x558bc6b7bd54]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x3c510) [0x7f042477b510]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(+0x8a0fc) [0x7f04247c90fc]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x12) [0x7f042477b472]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f04247654b2]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x263d5) [0x7f04247653d5]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x353a2) [0x7f04247743a2]
??:0
[bt] #8 /usr/bin/xournalpp(_ZN3xoj4view12TexImageViewD1Ev+0) [0x558bc6cc7930]
??:0
[bt] #9 /usr/bin/xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x25b) [0x558bc6d0451b]
??:0
[bt] #10 /usr/bin/xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0x10c) [0x558bc6c705cc]
??:0
[bt] #11 /usr/bin/xournalpp(+0x143e55) [0x558bc6be7e55]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x254744) [0x7f0425654744]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x345e89) [0x7f0425745e89]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x346d11) [0x7f0425746d11]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2835de) [0x7f04256835de]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x127a9f) [0x7f0425527a9f]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x281205) [0x7f0425681205]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x350344) [0x7f0425750344]
??:0
[bt] #28 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x241) [0x7f042551b0c1]
??:0
[bt] #29 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11b1cd) [0x7f042551b1cd]
??:0
[bt] #30 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xca528) [0x7f04254ca528]
??:0
[bt] #31 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x121901) [0x7f0425521901]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/marcos/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "HighlightPosition" UI initialized
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Plugin "MyColorCycle" UI initialized
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Salvamento automático para /home/marcos/.cache/xournalpp/autosaves/303296.autosave.xopp
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: O salvamento automático foi renomeado de /home/marcos/.cache/xournalpp/autosaves/303296.autosave.xopp para /home/marcos/.cache/xournalpp/autosaves/303296.old.autosave.xopp
MESSAGE : xopp :: Salvamento automático para /home/marcos/.cache/xournalpp/autosaves/303296.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: O salvamento automático foi renomeado de /home/marcos/.cache/xournalpp/autosaves/303296.autosave.xopp para /home/marcos/.cache/xournalpp/autosaves/303296.old.autosave.xopp
MESSAGE : xopp :: Salvamento automático para /home/marcos/.cache/xournalpp/autosaves/303296.autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/marcos/.cache/xournalpp/errorlogs/errorlog.20231006-180833.log

**Comment by rolandlo** [comment]
This assertion failure should be fixed in upcoming release 1.2.2.
