### ISSUE TITLE
One extra pressure data than number of points, with negative pressure.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#5238]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

no DE

### (Linux Only) Display Server

X.Org

### Installation Method

Built from source.

### Xournal++ Version

release-1.2 (d07309bf8abdf81e06b72c57ad8f0257485fd2fd or after), master (eea49ce695dbe94dfb2cc59cdeeddb3a394143e3 or after)

### libgtk Version

3.24.38

### Bug Description

Pressure sensitive strokes are saved with one redandant data  with negative value.
```
--- foo-0.xopp  2023-10-15 23:13:05.048136928 +0900
+++ foo-1.xopp  2023-10-15 23:13:10.864136700 +0900
@@ -5,7 +5,7 @@
 <page width="595.27559" height="841.88976">
 <background type="solid" color="#ffffffff" style="lined"/>
 <layer>
-<stroke tool="pen" ts="0" fn="" color="#3333ccff" width="1.41 0.60424576" capStyle="round">126.9369 60.364519 126.9369 60.364519</stroke>
+<stroke tool="pen" ts="0" fn="" color="#3333ccff" width="1.41 0.60424576 -1" capStyle="round">126.9369 60.364519 126.9369 60.364519</stroke>
 </layer>
 </page>
 </xournal>
```
foo-0.xopp is a normal file. foo-1.xopp is a file saved with recent Xournal++.

### Expected Behaviour

No `-1` pressure data.

### Steps to Reproduce

1. Open a new .xopp file.
2. Draw something with a pressure sensitive tool.
3. Save the .xopp file and quit, and look into the .xopp file.
4. If you reopen the file, then you'll get something like:
```
xopp-WARNING **: 23:39:03.471: Found a stroke with some non-positive pressure values. Removing the affected points.
```

### Additional Context

Perhaps `pts.end()` in

https://github.com/xournalpp/xournalpp/blob/32208bb8a66cfb95e8f78790c5bb9f1a6f0ad67b/src/core/control/xojfile/SaveHandler.cpp#L125

should be `pts.end() - 1 `

**Comment by rolandlo** [comment]
Thanks for your report and analysis @tattsan. You're right. Can you please create a PR (based on the release-1.2 branch) with your fix?

**Comment by tattsan** [comment]
Thank you!
