### ISSUE TITLE
The window scaling can be memorized

### ISSUE THREAD

**Issue by Nephino** [xournalpp/xournalpp#5245]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Github Realease

### Xournal++ Version

1.2.2

### libgtk Version

3.0

### Bug Description

The window scaling can be memorized.

This is the origin description in Chineses, I'm not very good at English: 
窗口大小不能自动记忆。

### Expected Behaviour

As the picture shows: I maximize my window before I close the app, the window scale will become this scale (show in picture) next time I start the app but keep maximization. This condition always happen.
![1697463123027](https://github.com/xournalpp/xournalpp/assets/50948786/eb0b7e31-c3a9-4a48-b381-8061b750d0ed)

This is the origin description in Chineses: 
如图所示：我在关闭软件前最大化了窗口，可是下次打开软件后，窗口就变成了图片中的样子，而不是保持最大化。这种情况一直在出现。

### Steps to Reproduce

1. Maxmize the windows
2. close the application
3. then reopen app

**Comment by tmoerschell** [comment]
This is now fixed and will be available in the next release. Thank you very much for reporting it! If you want to use the fix already now, you can build Xournal++ from the latest `release-1.2` branch.

**Comment by Nephino** [comment]
> This is now fixed and will be available in the next release. Thank you very much for reporting it! If you want to use the fix already now, you can build Xournal++ from the latest `release-1.2` branch.
