### ISSUE TITLE
Pointer has no effect when using a Wacom tablet

### ISSUE THREAD

**Issue by Neraste** [xournalpp/xournalpp#5249]
### Operating System

Linux

### (Linux only) Distribution

OpenSUSE Tumbleweed

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

X.Org

### Installation Method

Official release

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

When using a Wacom Intuos pen tablet, clicking anywhere on the app window with the pen disables the effect of the cursor. No button can be pressed, no menu can be open, and nothing can be written on the document. Alt-tabbing to another window liberates the pointer, but then clicking anywhere again has the same effect.

There are no problem when using the mouse.

### Expected Behaviour

When using the pen, the cursor should behave as when using the mouse.

### Steps to Reproduce

1. Connect Wacom Intuos tablet (by Bluetooth or USB);
2. Open Xournal++;
3. Tap anywhere on the app window, the action has no effect;
4. Tap anywhere again, the action has still no effect.

### Additional Context

Updated my system just in case, but it did not solve anything. Similar problem with GIMP, so it is possible that this is a GTK issue.

**Comment by rolandlo** [comment]
I can reproduce the issue on X11 (Ubuntu 23.10) with every version of Xournal++ (and also with GIMP) I tried. No need to take a Wacom tablet, already my Lenovo stylus does the same thing. It's definitely not something we have changed in Xournal++. If it were a GTK issue, then the AppImage should just work fine. Also Mutter (I'm on 45.0-3ubuntu3) is a suspect.

**Comment by rolandlo** [comment]
On wayland everything works fine, by the way.

**Comment by rolandlo** [comment]
@Neraste Do you get a message like:
```term
Okt 18 07:18:26 roland-ThinkPad-X1-Yoga-Gen-6 kernel: wacom 0018:056A:5276.0004: wacom_idleprox_timeout: tool appears to be hung in-prox. forcing it out.
```
as well when running
```term
journalctl -e
```
after using the stylus in Xournal++?

**Comment by Neraste** [comment]
I forgot to mention, but everything was working fine about one-two months ago (but I don't know what OpenSUSE Tumbleweed updating cycles are).

I can't use Wayland for now, as I use proprietary Nvidia drivers, which forces to use X11.

Let me tell you about `journaltcl` output when I get back to my machine.

**Comment by rolandlo** [comment]
The journalctl message comes from the kernel: https://lore.kernel.org/all/20220715230519.2183-1-jason.gerecke@wacom.com/

**Comment by Neraste** [comment]
> @Neraste Do you get a message like:
> 
> ```
> Okt 18 07:18:26 roland-ThinkPad-X1-Yoga-Gen-6 kernel: wacom 0018:056A:5276.0004: wacom_idleprox_timeout: tool appears to be hung in-prox. forcing it out.
> ```
> 
> as well when running
> 
> ```
> journalctl -e
> ```
> 
> after using the stylus in Xournal++?

No, I do not get such a message.

**Comment by rolandlo** [comment]
What Linux kernel are you using?

**Comment by Neraste** [comment]
```
uname -a
Linux gumi 6.5.6-1-default #1 SMP PREEMPT_DYNAMIC Fri Oct  6 11:20:48 UTC 2023 (c97c2df) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fritzeline** [comment]
I'm not using Xournal++ but this is the only place I found that described that problem.

I use gnome on Arch Linux with X11 and 6.5.7 kernel using the proprietary nvidia driver, xorg wacom driver and a wacom Intuos. I have that problem ("hung" input when touching the touchpad with the pen) for every non-gnome application (gimp, firefox, etc.) but for gnome applications like settings or files it works fine.
When switching to wayland everything works.
When uninstalling the wacom driver it works but when interacting with gnome applications the gnome-shell sometimes crashes but I don't know how to reproduce that.

I also tested it with a fresh ubuntu 22.04.4 installation (kernel 6.2.0 and nouveau driver).
There everything works fine with X11 and wayland.

By the way I just recently acquired the wacom tablet so I don't know if it ever worked or if my rather old Arch installation is the problem.

**Comment by rolandlo** [comment]
On X11 (on Ubuntu 23.10) all Xournal++ versions and also other Gtk 3 apps like Inkscape, GIMP, MyPaint and even Gtk 3 demo (Drawing Area demo) are affected.

I use a Lenovo ThinkPad X1 Yoga Gen 6.

**Comment by rolandlo** [comment]
Interestingly the Paint demo in the Gtk 3 demo is not affected in the same way. I can draw with my stylus there and the issue only appears when trying to resize the window.

**Comment by OsniWinkelmann** [comment]
I have this same problem, after installing Ubuntu 23.10, using MyPaint and Krita and both work correctly on Wayland. The pen in GIMP is working normally in XORG.
I don't know if there's a relationship, but I installed some old brushes from MyPaint (https://krita-artists.org/t/fizzyflowers-ultimate-mypaint-brush-collection/31580/10) and a bundle named Off-Set brushes (https://github.com/mypaint/libmypaint/issues/8), in MyPaint and Krita, and, no I'm not sure if they were working before. 
I also installed it in GIMP using MyPaint brushes and I had no problems.

**Comment by OsniWinkelmann** [comment]
I noticed that the Wacom Tablet in MyPaint on Xorg appears (Preferences/Devices) as having 8 axes (as if the tablet recognizes Tilt) but my Wacom One is simple and only has pressure. In MyPaint in Wayland, there are only 4 Axes for Pen and 2 Axes for Eraser.

![2023 11 03 - 18:10:43](https://github.com/xournalpp/xournalpp/assets/66883113/982ec439-1d31-461e-9935-06883041da37)

There is some confusion in Xorg's recognition of the Wacom One Tablet, specifically in MyPaint and Krita.
In GIMP, under Input Devices, the program only recognizes Tablet Pressure, the other Axis appears empty.

![2023 11 03 - 18:47:44](https://github.com/xournalpp/xournalpp/assets/66883113/62536de9-e5ba-4e5b-ae5f-2e4f25c2d52c)

**Comment by maffelbaffel** [comment]
Is this related to [this problem](https://www.davidrevoy.com/article995/how-a-kernel-update-broke-my-stylus-need-help)?

**Comment by frohro** [comment]
I have too this problem on a Lenovo Yoga 260 and on a Fujitsu T935 in Xorg, but not Wayland.

**Comment by frohro** [comment]
I have opened up a bug report on [Launchpad under the xorg package.](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/2043215)

**Comment by rolandlo** [comment]
This issue appears to be solved with `libmutter` 45.2, which arrived in the Ubuntu repos today (and earlier so on Arch).
@frohro You can close the bug report on Launchpad (assuming it works for you too).

**Comment by frohro** [comment]
@rolandlo thanks for the note.  For me, it is slightly better.  The stylus actually works for about 30 seconds after I switch to xournalpp, but then it does not, at least on the Fujitsu U729x I just tried it on.

**Comment by frohro** [comment]
So it appears that the changes were there for a while and then were reverted, and now are in the works again to be put into Ubuntu 23.10.  In the meantime, you can follow the instructions on[ this bug report page](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2043027) and install the proposed update.
