### ISSUE TITLE
Arrows with filling behave weirdly -- please make this bug a feature!

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#5257]
### Operating System

Linux

### (Linux only) Distribution

Manjaro Linux

### (Linux only) Desktop Environment

Xfce with Compiz

### (Linux Only) Display Server

X.Org

### Installation Method

AUR package xournalpp-git

### Xournal++ Version

1.2.1+dev

### libgtk Version

3.24.38

### Bug Description

When activating the "Fill" button and drawing an arrow, it looks weird:

![Auswahl_001](https://github.com/xournalpp/xournalpp/assets/1191480/476408d6-43e6-409f-89ad-3c35be1cbd9e)

### Expected Behaviour

I propose to use the "Fill" option to enable solid arrow heads which look like that:

![Auswahl_002](https://github.com/xournalpp/xournalpp/assets/1191480/7729f659-e35f-41a6-be31-dbafe02ff123)

Just connect the three points constituting the arrowhead instead of the starting point and two of the arrowhead points.

### Steps to Reproduce

1. Use the pen tool with activated "Fill" and "Draw arrow" options.
2. Observe the ugly arrow

### Additional Context

I frequently need arrows with filled arrowheads and it would be great if Xournal++ could offer them. The fill option seems like a good way of implementing this.

**Comment by rolandlo** [comment]
The arrow should be a connected stroke. The fill can be toggled from the selection tool (when the arrow doesn't know it is an arrow anymore), so we can't do anything else than toggle the fill property of the stroke. Currently the arrow is drawn like this:
tail -> head -> side 1 of head -> head -> side 2 of head
This can be improved easily with respect to fill by adding the head point once more. See  #5258

A solution with filled arrow heads is already suggested in
https://github.com/xournalpp/xournalpp/pull/4055#issuecomment-1140418565, but this requires a change in the file format.

**Comment by Photon89** [comment]
I'm very happy with both the minimal invasive solution adjusting the order of points when drawing the arrow and then using fill, and also the long run solution requiring file format changes! Thanks for the quick fix/PR!

**Comment by Photon89** [comment]
Ah, I see, this won't enable filled arrowheads... 

The following would enable filled arrowheads: tail -> head -> side 1 of head ->  side 2 of head -> head

But without filling there would be an extra line connecting the two sides...

**Comment by rolandlo** [comment]
> Ah, I see, this won't enable filled arrowheads...
> 
> The following would enable filled arrowheads: tail -> head -> side 1 of head -> side 2 of head -> head
> 
> But without filling there would be an extra line connecting the two sides...

Exactly. That's not what we want. And not only that, the head would be split by a line with full opacity.

**Comment by Photon89** [comment]
I think, the middle line could be worked around:

tail -> head start -> side 1 of head -> head end -> side 2 of head -> head start

where head start is the center of the two side points.

But yeah, it would change the unfilled arrow style to the worse.

Maybe it is possible to have the "tail -> head -> side 1 of head -> side 2 of head -> head  + fill" tool as a "Solid arrowhead arrow" pen style?

**Comment by rolandlo** [comment]
I don't think (with the current GUI) it's a good idea to add lots of different drawing types just for minor variations of an existing drawing type. It would make selecting the drawing type more difficult. A more general approach is needed. An idea with lot of customizability can be found in https://github.com/xournalpp/xournalpp/pull/3025#issuecomment-826806191. But that would be plugin-based.

**Comment by tattsan** [comment]
As for single head arrows,  `side 1 of head -> head -> tail > head-> side 2 of head`  will fill the head.
But you can't fill both heads of double arrows.

**Comment by Photon89** [comment]
Woah, that looks like magic! Personally, I use double arrows rather rarely and wouldn't care about the little inconsistency, but would really profit from the solid arrowheads in the single arrows. 

@rolandlo: Could we have it this way?

**Comment by tattsan** [comment]
I think it's ugly that the specifications are different between single arrow and double arrow. I think it's better to use it for your personal builds.

**Comment by Photon89** [comment]
I disagree. This is clearly an inconsistency, but the solution would offer a very useful feature and it would be still much better than  what we had so far (and nobody complained till I filed this issue). I'd just consider it a temporary solution till the new file format is there!

**Comment by rolandlo** [comment]
It doesn't look great even for simple arrows when the fill opacity is relatively low:
![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/df9c0fb1-3e6d-4863-9c97-abf399a0bfe5)
I would prefer to have the upper looks, which is #5258

**Comment by Photon89** [comment]
Well, let's wait for the new file format then!
