### ISSUE TITLE
App crashed and lost all my work in last two hours

### ISSUE THREAD

**Issue by hbaklan943** [xournalpp/xournalpp#5265]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Downloaded .exe from Website

### Xournal++ Version

1.2.2

### libgtk Version

3.24.39

### Bug Description

First time trying the app for doing my Homework, nothing fancy. Enjoying the app using my stylus(HUION) for over 2 hours a lot of work was done. Then suddenly app dissappears without any warnings, crossed my fingers that the progress had been saved but no luck. Cursed everything and decided to open an issue. 

### Expected Behaviour

Auto save and not crash if possible.

### Steps to Reproduce

1. Install to Windows device
2. Use the app for several hours( mostly drawing and selection tools).

### Additional Context

Damn this app is not production ready. Please warn users about some safety measurments.

**Comment by rolandlo** [comment]
How did you conclude that there is no autosave file? By default Xournal++ autosaves every 3 minutes. The location  (same folder like the saved file or cache folder) depends on whether you have saved the file previously or not. See https://xournalpp.github.io/guide/file-locations/ for more info.

**Comment by rolandlo** [comment]
> see Configuration->Load/Save.

The info there on autosave paths is Linux-specific and partly outdated. The website is up to date.

**Comment by hbaklan943** [comment]
> How did you conclude that there is no autosave file? By default Xournal++ autosaves every 3 minutes. The location (same folder like the saved file or cache folder) depends on whether you have saved the file previously or not. See https://xournalpp.github.io/guide/file-locations/ for more info.

When i reopenned the app after crash, I saw a blank new page, then i thought that i lost it. Now try to find it based on the info you provided. 🙏

**Comment by hbaklan943** [comment]
> How did you conclude that there is no autosave file? By default Xournal++ autosaves every 3 minutes. The location (same folder like the saved file or cache folder) depends on whether you have saved the file previously or not. See https://xournalpp.github.io/guide/file-locations/ for more info.

Thank a lot mate! I found all my work under "C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves".
