### ISSUE TITLE
Xournal++ closed unexpectedly

### ISSUE THREAD

**Issue by kdjoseph** [xournalpp/xournalpp#5276]
[errorlog.20231023-125826.log](https://github.com/xournalpp/xournalpp/files/13126602/errorlog.20231023-125826.log)
### Operating System

Windows (dual boot with Linux Ubuntu 20.04)

### (Linux only) Distribution

Ubuntu 20.04

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

None

### Installation Method

most likely snap (but I don't fully recall)

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

While using the app on Linux Ubuntu 20.04 to do some math homework, I used the "select region" tool to copy a small part of my work (a vector and some symbols), but the app crashed as I was about to go to the other page where I wanted to paste the content. The app autosaved the last version of the file I was working on. I had to convert it to PDF to attach it to this section. Hope this helps.
[.2023-10-22-Note-21-38_HW3_Prob8.autosave_annotated.pdf](https://github.com/xournalpp/xournalpp/files/13074212/default.2023-10-22-Note-21-38_HW3_Prob8.autosave_annotated.pdf)

### Expected Behaviour

I had previously successfully use the "select region" tool to copy and past parts of my work, so I did not expect this to cause the app to crash. 

### Steps to Reproduce

1- write a lot of linear algebra to take up about 8 pages (see file attached to "Bug Description" section)
2- then try to use the "select region" tool to copy a matrix with some variable names. 

### Additional Context

I'm not sure if this is relevant, but I had the app running the day before and did not close it entirely or shutdown my computer before the bug occurred. I just locked my computer the night before and only minimized the app, then opened it this morning to continue working on my homework.

**Comment by Cliffd3s** [comment]
Thanks for the prompt response. I attached the error log file to the report.

**Comment by Cliffd3s** [comment]
Sorry, the log file is not helpful. I have updated to the 1.2.2 version. My homework have been getting longer and longer for this class, so I will be able to try to reproduce the same issue on this new version soon. thanks.
