### ISSUE TITLE
Add a empty page after every page in a pdf

### ISSUE THREAD

**Issue by hanna2826** [xournalpp/xournalpp#5285]
### Is Your Feature Request Related to a Problem?

I use Xournal++ for Uni, but when annotating books, or other pdfs, I often run out of space. 
My Uni does offer a printed version of a lot of the books where the left side is a page from the pdf and the right one is empty for annotations. 
Is it possible to implement this? And also change the background of the empty space for example to lines/ checkered?

### Feature Description

Option to add a clear page after every page in pdfs

**Comment by rolandlo** [comment]
There is no built-in option for that in the GUI, but you could easily write a [plugin](https://xournalpp.github.io/guide/plugins/plugins/) doing that. You basically need to iterate through all the pages,
use
`app.uiAction({["action"] = "ACTION_NEW_PAGE_AFTER"})`  to insert a new page after the current one
and
`app.changeCurrentPageBackground("graph")`

for changing to "graph" page style (or "lined", "ruled", whatever you need).

**Comment by rolandlo** [comment]
Closed in view of #5836.
