### ISSUE TITLE
Device hash check breaks touchpad+trackpad combo

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#5287]
This breaks my workflow at least. I have a thinkpad that has both a touchpad and one of those red trackpoints. Like this:

![sef](https://cdn.notebookgalerie.de/magento_catalog/t/h/thinkpad-t4xx-tochpad-folie-id-15333_4.jpg)

The thing is, the buttons above and below the touchpad belong to the two different devices. The above two buttons are for the trackpoint, the below for the touchpad. I used to be able to press whichever, if I wanted to draw a line in xournal++. Now the above two don't work, for it's a different device. What do?
Many thanks @bhennion

_Originally posted by @MikuChan03 in https://github.com/xournalpp/xournalpp/issues/5170#issuecomment-1778681579_

**Comment by renzev58** [comment]
I am still affected by this issue on Xournal++ 1.2.3 under X11. I have a Lenovo Thinkpad T420. Xinput lists the devices as `SynPS/2 Synaptics TouchPad` and `TPPS/2 IBM TrackPoint `. I don't think adding exceptions for specific device pairings like in #5288 is a sustainable solution. Is it possible to add a settings option to disable this "device hash check" feature and treat all devices equally, like most other programs do?
