### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rschram** [xournalpp/xournalpp#5291]
### Operating System

Windows

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

X.Org

### Installation Method

Official

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Date: Thu Oct 26 15:55:45 2023
Error: signal 6
Xournal++ version 1.2.1
Git commit b48932a2 from xournalpp/HEAD
Gtk version 3.24.38

[bt]: (0) /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3555) [0x55b3ad93f555]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f58408fb520]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f584094fa7c]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f58408fb476]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f58408e17f3]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f58408e171b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f58408f2e96]
[bt]: (7) /snap/xournalpp/86/usr/bin/xournalpp(+0x6042d3) [0x55b3adb602d3]
[bt]: (8) /snap/xournalpp/86/usr/bin/xournalpp(_ZN3xoj4view16StrokeViewHelper16drawWithPressureEP6_cairoRKSt6vectorI5PointSaIS5_EERK9LineStyled+0x206) [0x55b3adb60557]
[bt]: (9) /snap/xournalpp/86/usr/bin/xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x276) [0x55b3adbe0948]
[bt]: (10) /snap/xournalpp/86/usr/bin/xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0x1f5) [0x55b3adadd791]
[bt]: (11) /snap/xournalpp/86/usr/bin/xournalpp(+0x49f703) [0x55b3ad9fb703]
[bt]: (12) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (13) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (14) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (15) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x288cc9) [0x7f5841827cc9]
[bt]: (16) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3962c9) [0x7f58419352c9]
[bt]: (17) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (18) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (19) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x397071) [0x7f5841936071]
[bt]: (20) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (21) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (22) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (23) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2bf7bd) [0x7f584185e7bd]
[bt]: (24) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (25) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (26) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2bbc35) [0x7f584185ac35]
[bt]: (27) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (28) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (29) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (30) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8a28) [0x7f5841677a28]
[bt]: (31) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (32) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (33) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd9e75) [0x7f5841678e75]
[bt]: (34) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (35) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (36) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (37) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8a28) [0x7f5841677a28]
[bt]: (38) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (39) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (40) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd9e75) [0x7f5841678e75]
[bt]: (41) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (42) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (43) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (44) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8a28) [0x7f5841677a28]
[bt]: (45) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (46) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (47) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd9e75) [0x7f5841678e75]
[bt]: (48) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (49) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (50) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (51) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8a28) [0x7f5841677a28]
[bt]: (52) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
[bt]: (53) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
[bt]: (54) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd9e75) [0x7f5841678e75]
[bt]: (55) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (56) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (57) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (58) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (59) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
[bt]: (60) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
[bt]: (61) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
[bt]: (62) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3b024f) [0x7f584194f24f]
[bt]: (63) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x82c) [0x7f58417cb7ec]
[bt]: (64) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x40e19) [0x7f58414c3e19]
[bt]: (65) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x520e1) [0x7f58414d50e1]
[bt]: (66) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x54891) [0x7f58414d7891]
[bt]: (67) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x54ac8) [0x7f58414d7ac8]
[bt]: (68) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x16569) [0x7f5841154569]
[bt]: (69) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2f00a) [0x7f584116d00a]
[bt]: (70) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x39) [0x7f58411763f9]
[bt]: (71) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f58411764c3]
[bt]: (72) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4ad1a) [0x7f58414cdd1a]
[bt]: (73) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x34e6d) [0x7f58414b7e6d]
[bt]: (74) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x6374f) [0x7f584104574f]
[bt]: (75) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5ed13) [0x7f5841040d13]
[bt]: (76) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x625f0) [0x7f58410445f0]
[bt]: (77) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f5841044eb3]
[bt]: (78) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f58412ce025]
[bt]: (79) /snap/xournalpp/86/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x7f0) [0x55b3ad9476e1]
[bt]: (80) /snap/xournalpp/86/usr/bin/xournalpp(main+0x29) [0x55b3ad93f112]
[bt]: (81) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f58408e2d90]
[bt]: (82) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f58408e2e40]
[bt]: (83) /snap/xournalpp/86/usr/bin/xournalpp(_start+0x25) [0x55b3ad93f025]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3cbf) [0x55b3ad93fcbf]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f58408fb520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f584094fa7c]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f58408fb476]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f58408e17f3]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f58408e171b]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f58408f2e96]
??:0
[bt] #8 /snap/xournalpp/86/usr/bin/xournalpp(+0x6042d3) [0x55b3adb602d3]
??:0
[bt] #9 /snap/xournalpp/86/usr/bin/xournalpp(_ZN3xoj4view16StrokeViewHelper16drawWithPressureEP6_cairoRKSt6vectorI5PointSaIS5_EERK9LineStyled+0x206) [0x55b3adb60557]
??:0
[bt] #10 /snap/xournalpp/86/usr/bin/xournalpp(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x276) [0x55b3adbe0948]
??:0
[bt] #11 /snap/xournalpp/86/usr/bin/xournalpp(_ZN11XojPageView9paintPageEP6_cairoP20_cairo_rectangle_int+0x1f5) [0x55b3adadd791]
??:0
[bt] #12 /snap/xournalpp/86/usr/bin/xournalpp(+0x49f703) [0x55b3ad9fb703]
??:0
[bt] #13 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
??:0
[bt] #14 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
??:0
[bt] #15 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
??:0
[bt] #16 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x288cc9) [0x7f5841827cc9]
??:0
[bt] #17 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3962c9) [0x7f58419352c9]
??:0
[bt] #18 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
??:0
[bt] #19 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
??:0
[bt] #20 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x397071) [0x7f5841936071]
??:0
[bt] #21 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
??:0
[bt] #22 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
??:0
[bt] #23 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
??:0
[bt] #24 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2bf7bd) [0x7f584185e7bd]
??:0
[bt] #25 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x135b21) [0x7f58416d4b21]
??:0
[bt] #26 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x13d181) [0x7f58416dc181]
??:0
[bt] #27 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2bbc35) [0x7f584185ac35]
??:0
[bt] #28 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3a63d4) [0x7f58419453d4]
??:0
[bt] #29 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_propagate_draw+0x235) [0x7f58416cd885]
??:0
[bt] #30 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x12e99d) [0x7f58416cd99d]
??:0
[bt] #31 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xd8a28) [0x7f5841677a28]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = /snap/xournalpp/86/usr/share/locale, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /snap/xournalpp/86/usr/share/locale
INFO    : xopp :: Loading plugins from: /snap/xournalpp/86/usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/rschram/snap/xournalpp/86/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.autosave.xopp
WARNING : GLib-GIO :: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp to /home/rschram/snap/xournalpp/common/.cache/xournalpp/autosaves/8953.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/rschram/Current/Notes/Xpp/.2023-10-26-Note-09-48.autosave.xopp
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/rschram/snap/xournalpp/common/.cache/xournalpp/errorlogs/errorlog.20231026-155545.log

### Expected Behaviour

?

### Steps to Reproduce

?

**Comment by rolandlo** [comment]
This should already be fixed in version 1.2.2. So please update.
