### ISSUE TITLE
Xournalpp replaces last stroke width value with -1

### ISSUE THREAD

**Issue by JariNestel** [xournalpp/xournalpp#5321]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

Wayland

### Installation Method

yay -S xournalpp

### Xournal++ Version

1.2.2 (09ae3333)

### libgtk Version

3.24.38

### Bug Description

When Opening and Saving a Xournal File, the last stroke width entry is replaced by -1, opening the file after that results in lots of warnings being generated.

### Expected Behaviour

Opening and saving a file should not change stroke width at all.

### Steps to Reproduce

Load file, save file, all last entry in stroke width will be replaced by -1.
A near minimal example with the ha02.in.xopp and the output I get when saving ha02.out.xopp is provided renamed to .txt.
[ha02.in.xopp.txt](https://github.com/xournalpp/xournalpp/files/13269609/ha02.in.xopp.txt)
[ha02.out.xopp.txt](https://github.com/xournalpp/xournalpp/files/13269610/ha02.out.xopp.txt)

**Comment by tattsan** [comment]
This bug is same as #5238, and already fixed in release-1.2 branch  d763bffa521e88f2dab59b4d2a49f43696e99eea or after.

**Comment by JariNestel** [comment]
Thanks for the quick reply!
I've now read the issue, the fix and tested it with the nightly AppImage build (2023-11-01 1.2.2+dev https://github.com/xournalpp/xournalpp/commit/5d141101d4328c3550ecf9d1b018f23c988dbc23)
For files created with version 1.2.2 (https://github.com/xournalpp/xournalpp/commit/09ae33339438a777e8a22a6972ed5a9c7e8c3b1a) the additional width entry is now getting removed.
For files created before version 1.2.2 (namely version 1.2.1) it behaves as expected.
For new files (and strokes) it behaves as expected.
I therefore consider this issue solved (for future releases).
