### ISSUE TITLE
wacom table stylus button action doesn't take effect

### ISSUE THREAD

**Issue by natask** [xournalpp/xournalpp#5323]
### Operating System

Windows 11

### Installation Method

from website

### Xournal++ Version

1.2.0, 1.2.2-dev

### libgtk Version

3.24.39

### Bug Description

The action assigned to a stylus button doesn't manifest when the button is pressed. For example, if top button on a wacom tablet stylus is assigned to select region, when the button is pressed the animation changes as expected (cursor changes, tool menu changes) but no region is selected. However the eraser button can be assigned and reassigned and it functions as expected. It is also possible to activate the tool assigned to a stylus button by manually selecting the tool from the menu bar and engage it. 

I have validated that the issue persists in the 1.2.2-dev latest version found on the website.  

### Expected Behaviour

Action assigned to stylus button manifests when button is pressed.

### Steps to Reproduce

1. assign an action to a style button in edit->preferences->stylus->stylus buttons->button 2->select region (example action)
2. have selectable material in page
3. press the button and attempt to select the material

**Comment by jerdoe** [comment]
My question might sound a bit silly, but I was initially misled by the behavior (but actually convenient). Do you keep the stylus button pressed while writing, with the stylus tip touching the pad, to select the region?

**Comment by elisabethseguin** [comment]
Hi, I've had the same problem with my Surface stylus, I fixed it by going in Preferences -> Input system -> Merge button events with stylus tip events. I activated that setting and it worked perfectly afterwards.

**Comment by vladQll** [comment]
maybe i can help , i had to deal with some shortcuts to recognize but that happened to me when i had a wacom intuos ctl-4100 small , do you have the same model?

**Comment by natask** [comment]
@elisabethseguin tip solved my problem.

**Comment by natask** [comment]
> My question might sound a bit silly, but I was initially misled by the behavior (but actually convenient). Do you keep the stylus button pressed while writing, with the stylus tip touching the pad, to select the region?

I naturally remove the tip of the stylus from the pad before depressing any of the stylus buttons.
