### ISSUE TITLE
Latex preview readability with dark mode

### ISSUE THREAD

**Issue by WuerfelDev** [xournalpp/xournalpp#5327]
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

brew

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

With dark mode enabled the Latex preview is hard to see.
![Screenshot 2023-11-07 at 11 22 22](https://github.com/xournalpp/xournalpp/assets/12686819/358f98e8-5a04-4864-8000-957c56141a78)

### Expected Behaviour

Expected is to be able to easily read the formula.
I guess the text color should be dependant on the actual document background, maybe the background of the window can be made adjustable

### Steps to Reproduce

1. Enable dark mode
2. open latex window

**Comment by rolandlo** [comment]
This issue was fixed in #5307 and the fix will appear in version 1.2.3.
