### ISSUE TITLE
insert page crash

### ISSUE THREAD

**Issue by ribisi** [xournalpp/xournalpp#5329]
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

website

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

The software crashed
[errorlog.20231109-113727.log](https://github.com/xournalpp/xournalpp/files/13307051/errorlog.20231109-113727.log)

### Expected Behaviour

not to crash

### Steps to Reproduce

1. insert a page between to existing pages

**Comment by rolandlo** [comment]
That issue should already be fixed in the release-1.2 branch. It will be available in upcoming version 1.2.3.
