### ISSUE TITLE
xoj export (compatibility mode) broken in 1.2.2

### ISSUE THREAD

**Issue by KlausBlum** [xournalpp/xournalpp#5331]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Windows installer from official release

### Xournal++ Version

1.2.2

### libgtk Version

3.24.39

### Bug Description

When exporting a `*.xopp` document as a `.xoj` file (compatibility mode) with Xournal++ 1.2.2, the exported file cannot be opened with "original" Xournal 0.4.8, latest version from [xournal.sourceforge.net](xournal.sourceforge.net). 
The same document exported by Xournal++ 1.2.1 or 1.2.0 (portable version) loads fine in Xournal 0.4.8.
  
Here is my test document and the exported files I get with Xournal++ 1.2.0, 1.2.1 and 1.2.2: 
[files.zip](https://github.com/xournalpp/xournalpp/files/13322058/files.zip)
  
contents:
* test.xopp
* Test_kommentiert_120.xoj
* Test_kommentiert_121.xoj
* Test_kommentiert_122.xoj

### Expected Behaviour

Exported `*.xoj` file should still be compatible with "original" Xournal.

### Steps to Reproduce

Export a Xournal++ document as `*.xoj` file: 
1. Load or create any document in Xournal++
2. `File` > `Export as...`
3. In the dialog window, above the `Save` button, there is a dropdown box that reads "PDF files". 
Click on it and click the "Xournal (Compatibility)" entry. 
4. Click the `Save` button. 
Now you have created a `*.xoj` file. 
5. Open this `*.xoj` file with the "original" Xournal executable from [xournal.sourceforge.net](xournal.sourceforge.net). 
6. Depending on the Xournal++ version you have used, the file can be opened successfully... or not.  
Xournal++ 1.2.2: No, error Message: "Error opening file ..."
older versions: Yes

### Additional Context

By the way: Thanks a million for this wonderful software, I use it a lot.

**Comment by rolandlo** [comment]
Thanks for reporting. It looks to me that the issue comes from the added pressure values reported in #5238 and fixed in https://github.com/xournalpp/xournalpp/commit/d763bffa521e88f2dab59b4d2a49f43696e99eea. 
When using the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) the exports should work fine again.

**Comment by KlausBlum** [comment]
Yes, confirmed! 
With the nightly build it works again. 

I didn't know that "nightly" can be taken literally and there's a new executable every day. Lesson learned. ;-)
