### ISSUE TITLE
Xournal crashes with xp-pen tablet

### ISSUE THREAD

**Issue by IbrahimQatato** [xournalpp/xournalpp#5339]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

None

### Installation Method

Snap

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Xournal crashes while using it with an xppen tablet, if I open the file again I can't see the progress unless I recover an autosaved file.
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
WARNING : xopp :: [Crash Handler] Crashed with signal 6

### Expected Behaviour

It shouldn't crash

### Steps to Reproduce

Can't reproduce error, I'm not sure why exactly it happens but it happened several times to me.

**Comment by rolandlo** [comment]
Please upgrade to version 1.2.2 by switching to the candidates or edge channel. The issue is fixed there.
