### ISSUE TITLE
Error in opening a .xopp file

### ISSUE THREAD

**Issue by pidaryeu** [xournalpp/xournalpp#5369]
### Operating System

Linux

### (Linux only) Distribution

Debian 12

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Flatpak

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

An error message (about some missing stroke) appears when trying to open a .xopp file containing some annotations on a pdf file.
The message then started to appear for all .xopp files.
After closing the warning window, the files work as expected.

### Expected Behaviour

The files open regularly.

### Steps to Reproduce

1. Open a .xopp file

### Additional Context

[Uploading errorlog.20231124-150956.log…]()

**Comment by rolandlo** [comment]
Please reupload the errorlog, as it links to the current issue.

**Comment by pidaryeu** [comment]
Unfortunately, I deleted the errorlog. Since then, no error message displayed.
I close the issue, because I think it is useless without the errorlog.
I'm sorry.
Thank you.
