### ISSUE TITLE
No drawing possible with Wacom Intuos Pro L

### ISSUE THREAD

**Issue by maxawake** [xournalpp/xournalpp#5371]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

GNOME 45

### (Linux Only) Display Server

X.Org

### Installation Method

Pacman, Flatpak

### Xournal++ Version

1.2.2-1

### libgtk Version

3.24.38

### Bug Description

In a freshly installed Xournal++ i can use my Wacom Intuos Pro L Pen as a mouse but i can't draw. If i try to draw the mouse gets locked and i can't use it for other apps anymore until i press the super key. The wacom tablet gets recognized by Xournal++, xinput and libinput. I can use my tablet in other Programs without any issues (e.g. in RNote). I used both versions, pacman and flatpak, but both appear to have the same issue. It might not be a direct issue of Xournal++ but could be a unfortunate play together of several things. 

### Expected Behaviour

I was able to draw with the very same configuration before. So drawing and especially being able to annotate PDFs would be awesome.

### Steps to Reproduce

1. Install Xournal++
2. Try to draw with Intous Pro L
3. Fail

### Additional Context

NVidia 4070ti with driver version 545.29.02 
Kernel version 6.6.2-arch1-1 
BenQ 4K Monitor with HiDPI settings (xrandr scaling and GNOME scaling combined, made some issues with zoom for example)

**Comment by maxawake** [comment]
It might be related to https://github.com/linuxwacom/xf86-input-wacom/issues/327 or as they have mentioned in this issue https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3393

**Comment by Febbe** [comment]
RNote is using gtk4, we and the other apps are still stuck with gtk3.

**Comment by rolandlo** [comment]
It looks also related to #5249

**Comment by psycotica0** [comment]
Hello! I'm not a xournal user, but wanted people to know that I've tested mutter 45.2 with other software which was having similar issues on my machine and my issues have now cleared up! Maybe give it a shot!

**Comment by rolandlo** [comment]
I can confirm that the issue is solved with mutter 45.2. On Ubuntu it only arrived today in the repos.
