### ISSUE TITLE
Shortcut `Ctrl+Enter` in TeX Editor doesn't work on nightly

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#5381]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

dwm

### (Linux Only) Display Server

X.Org

### Installation Method

source or AppImage

### Xournal++ Version

nightly 1.2.2+dev (c5ddca93)   vs  release 1.2.2 (09ae3333)

### libgtk Version

3.24.20

### Bug Description

Shortcut `Ctrl+Enter` in the TeX Editor to essentialy press `OK` button doesn't seem to work in the nightly build/AppImage.
It works when running release 1.2.2 Appimage.

### Expected Behaviour

Pressing `Ctrl+Enter` in the TeX Editor should accept the formula (press `OK`).

### Steps to Reproduce

1. Open TeX Editor with `Ctrl+Shift+x`.
2. Write something.
3. Try to accept with `Ctrl+Enter`.
4. Doesn't work on nightly, works on release-1.2.2.

**Comment by tattsan** [comment]
The change was introduced by bd181399c1f5ba6f08a5d6dddd598ca75a82a474 .
