### ISSUE TITLE
Is it me, or is Windows Security wrong?

### ISSUE THREAD

**Issue by lightningHoneypot** [xournalpp/xournalpp#5391]
Why did Windows Security says that it is a trojan horse?

![image](https://github.com/xournalpp/xournalpp/assets/88814097/23c2f719-5f1d-4d6a-9864-29d337741e85)

**Comment by Yohanners** [comment]
I had the same issue while downloading the windows zip from the site, but the name of the threat was different

![image](https://github.com/xournalpp/xournalpp/assets/153060271/652879b0-7267-4271-9a26-bd06b8c03b3c)

i downloaded the last release, now it only showed me this but i didnt run the setup

![image](https://github.com/xournalpp/xournalpp/assets/153060271/c1311f57-0140-468f-998c-d6e39ee36558)

**Comment by Febbe** [comment]
> i downloaded the last release, now it only showed me this but i didnt run the setup
> 
> ![image](https://private-user-images.githubusercontent.com/153060271/288312787-c1311f57-0140-468f-998c-d6e39ee36558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE1NjUsIm5iZiI6MTcwMjM5MTI2NSwicGF0aCI6Ii8xNTMwNjAyNzEvMjg4MzEyNzg3LWMxMzExZjU3LTAxNDAtNDY4Zi05OThjLWQ2ZTM5ZWUzNjU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNDI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWY1ZjVhM2E3NTA2ODVjNjAyYzk1MWZmMjNhNmI3MWFkZTM4MDkwNDZlNDA5ZTRjMjAxNDhkMDU0NTc4YzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmQXFqANUCW5B2CcXhOSLMoQXfbwppsu1ssGM_cYjPk)

Microsoft shows this popup for all applications which are not signed. You can safely install it.
