### ISSUE TITLE
xournal++ suddenly closed upun accidentally dragging TeX window out of the visualized region

### ISSUE THREAD

**Issue by lurix66** [xournalpp/xournalpp#5398]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 18.04

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

X.Org

### Installation Method

Snap

### Xournal++ Version

xournalpp 1.2.1 (b48932a2) 

### libgtk Version

└──libgtk: 3.24.38

### Bug Description

I was editing inside a TeX dialog. It resulted correct but too long end therefore split in two lines.
So naively I tried to enlarge the TeX box but this actually resulted in a magnification of its content, so it was useless (there should be a way to do this though). So I went back (likely with a CTRL+Z) and tried to reposition the window, but my move was too big and the TeX window got too low and out of the lower border of the visualized region of document. At that point I couldn't find my xournal++ session any more, it was completely gone.

### Expected Behaviour

Even whe dragging a TeX box out of the visualized region, it should either block there or, better, move the visualized region.  For sure it should not crash

### Steps to Reproduce

see above

**Comment by rolandlo** [comment]
This should be fixed in version 1.2.2. Please upgrade. For the snap package you must currently switch to the `candidates` or `edge` channel to do that.
