### ISSUE TITLE
MACOS Sonoma 14.1+ BREAKS Xournal++ - No UI Dialogs WORK!!

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#5404]
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

unzip and move to applications folder

### Xournal++ Version

Official Release, as well as various nightly builds up to 12/5/2023

### libgtk Version

up to 3.24.38

### Bug Description

The following problem never occurred in any MacOS version prior to Sonoma 14.1. (So Sonoma 14.0 WORKED FINE)
Problem started instantly after "upgrade" to Sonoma 14.1 - and hasn't been resolved in Sonoma 14.2
Installation is on M2 Pro mini, 32 gb.

Main program window works fine. Clicking on anything that opens sub-window of Xournal, such as Preferences window, Open File Window, even "Opacity Settings", will cause UI to become unresponsive, with a rainbow circle spinning indefinitely. In the "force quit" window, Xournal++ will appear with the red label "no responding"

Please note: Occasionally, everything will work fine - file dialogs are responsive and snappy. But that only occurs 1 in 20 times.

If you click on exit (close application) and the file has modifications, that little window prompting you to save / discard or cancel changes will also hang.... meaning all your changes will be lost when you ultimately have to force quit the app.
So, one must remember to click on Save prior to exiting, so no dialogs will have to open.

The only way to open files when this problem occurs is to select a file from the finder app and open in Xournal++ that way. Thank god the ability to open from finder was recently fixed...

ChatGPT said it could have something to do with Rosetta getting corrupted and suggested I reinstall with this command:
/usr/sbin/softwareupdate --install-rosetta --agree-to-license

That actually seemed to "fix" the problem for the next several launches of Xournal++. But then the problem returned.
Now, if I rerun the Rosetta reinstallation, it produces "hit or miss" results.

I tried compiling Xournal++ for Mac ARM but the compilation always fails in multiple places and the best I can figure out is that some of the underlying libraries used aren't yet compatible with ARM....

THIS IS A SERIOUS PROBLEM for anyone using Xournal++ on Mac who encounters this problem, as it renders the program almost USELESS.

### Expected Behaviour

Shouldn't hang.

### Steps to Reproduce

do anything that might open a dialog window in Xournal++

### Additional Context

I submitted a bug report weeks ago on this - thinking at that time that I was only related to file dialog interactions - but no one looked at it even once... This bug report is more complete

**Comment by rolandlo** [comment]
Unfortunately I can't debug the issue, since on my old MacBook BigSur (11.7) is the latest that runs.
Most likely it's a Gtk issue related to the new MacOS version, so please check the [Gtk issue tracker](https://gitlab.gnome.org/GNOME/gtk/-/issues/?sort=created_date&state=opened&search=mac&first_page_size=20) or open an issue there. Maybe the problem also exists with other Gtk apps. So you could try out Inkscape, MyPaint, Gimp etc. and see whether the same issue appears there.

**Comment by rolandlo** [comment]
Since I have an M2 now, I can debug any issues for MacOS Arm. It seems that the Xournal++ ARM build from https://cirrus-ci.com/task/5138787729145856 works pretty fine though. Please give it a try if you can.

**Comment by rolandlo** [comment]
A MacOS ARM build has been released with version 1.2.4. Closing the issue therefore.
