### ISSUE TITLE
Compile.md contains a typo

### ISSUE THREAD

**Issue by samin36** [xournalpp/xournalpp#5411]
### Operating System

Linux

### (Linux only) Distribution

Linux Mint

### (Linux only) Desktop Environment

Cinnamon

### (Linux Only) Display Server

None

### Installation Method

Not installed yet, trying to build it from source.

### Xournal++ Version

Not installed yet, trying to build it from source.

### libgtk Version

N/A

### Bug Description

I was following the instructions in `Compile.md` to build Xournal++ from source and noticed that under the `Compile` section, there is a typo. `--DCMAKE_INSTALL_PREFIX=install` should be `-DCMAKE_INSTALL_PREFIX=install` without the extra leading hyphen.

### Expected Behaviour

`--DCMAKE_INSTALL_PREFIX=install` should be `-DCMAKE_INSTALL_PREFIX=install` without the extra leading hyphen.

### Steps to Reproduce

See Bug Description

**Comment by rolandlo** [comment]
Thanks for pointing out the typo. It's fixed now
