### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by a-sad-dan** [xournalpp/xournalpp#5427]
### Operating System

Linux

### (Linux only) Distribution

Zorin Os

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

X.Org

### Installation Method

apt

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Xournalpp crashes while saving

### Expected Behaviour

should not crash while saving

### Steps to Reproduce

i use a viek vk640 pen tablet and it has only happened when i was using the pen on a big pdf file and happens when i am saving the document

### Additional Context

Date: Thu Dec 28 15:00:42 2023
Error: signal 6
Xournal++ version 1.2.1
Git commit b48932a2 from xournalpp/HEAD
Gtk version 3.24.38

[bt]: (0) /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3555) [0x5591514f1555]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f00dda2f520]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f00dda839fc]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f00dda2f476]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f00dda157f3]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f00dda1571b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f00dda26e96]
[bt]: (7) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x11d) [0x559151739459]
[bt]: (8) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob3runEv+0x26a) [0x559151739752]
[bt]: (9) /snap/xournalpp/86/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x559151636839]
[bt]: (10) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e1) [0x559151502e61]
[bt]: (11) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x97ce1) [0x7f00de1adce1]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f00dda81ac3]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f00ddb13a40]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3cbf) [0x5591514f1cbf]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f00dda2f520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f00dda839fc]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f00dda2f476]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f00dda157f3]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f00dda1571b]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f00dda26e96]
??:0
[bt] #8 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x11d) [0x559151739459]
??:0
[bt] #9 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob3runEv+0x26a) [0x559151739752]
??:0
[bt] #10 /snap/xournalpp/86/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x559151636839]
??:0
[bt] #11 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e1) [0x559151502e61]
??:0
[bt] #12 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x97ce1) [0x7f00de1adce1]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f00dda81ac3]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f00ddb13a40]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = /snap/xournalpp/86/usr/share/locale, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /snap/xournalpp/86/usr/share/locale
INFO    : xopp :: Loading plugins from: /snap/xournalpp/86/usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/dan/snap/xournalpp/86/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp to /home/dan/snap/xournalpp/common/.cache/xournalpp/autosaves/39972.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/dan/Desktop/DSA- Jay Wengrow/.Jay Wengrow - A Common-Sense Guide to Data Structures and Algorithms_ Level Up Your Core Programming Skills-Pragmatic Bookshelf (2020).autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/dan/snap/xournalpp/common/.cache/xournalpp/errorlogs/errorlog.20231228-150042.log

**Comment by rolandlo** [comment]
This should be fixed in version 1.2.2. Please upgrade. For the snap package you may have to switch to the candidates or edge channel to get the newer version.
