### ISSUE TITLE
Adding chapter sidebar for navigating large pdfs

### ISSUE THREAD

**Issue by r-gheda** [xournalpp/xournalpp#5448]
### Is Your Feature Request Related to a Problem?

I often use xournal for annotating large pdf files such as books and I find it would be extremely useful to have a chapter sidebar to navigate through the pdf similar to what happens on Ubuntu's pdf viewer.

### Feature Description

A chapter sidebar to navigate through the pdf similarly to what happens on Ubuntu's pdf viewer.

***EDIT***
Here's an example image of a chapter sidebar.
![image](https://github.com/xournalpp/xournalpp/assets/75741616/f03747ce-2fe7-427b-b261-c97b576e74de)

**Comment by rolandlo** [comment]
You mean this (in Evince)?
![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/898ef8d7-369a-4b28-91aa-3c291f2029b0)

That also exists in Xournal++'s sidebar:
![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/fc6f47e2-ac4f-4e4c-9cda-1945ccafac6a)

**Comment by r-gheda** [comment]
You're right! 
Mind that when working with books usually subsections are shown as well.

![image](https://github.com/xournalpp/xournalpp/assets/75741616/565be989-d47a-49c8-b2ea-f9b4d8ecbc9b)

**Comment by r-gheda** [comment]
Thanks for pointing that out. Never noticed such feature.
