### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by dh2pp** [xournalpp/xournalpp#5455]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 220.04

### (Linux only) Desktop Environment

Unity

### (Linux Only) Display Server

None

### Installation Method

Snap

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

Freezes and crashes. Dont know why.

### Expected Behaviour

normally working

### Steps to Reproduce

don't know

### Additional Context

Date: Wed Jan 17 15:53:06 2024
Error: signal 6
Xournal++ version 1.2.1
Git commit b48932a2 from xournalpp/HEAD
Gtk version 3.24.38

[bt]: (0) /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3555) [0x557d139ac555]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f9649798520]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f96497ec9fc]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f9649798476]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f964977e7f3]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f964977e71b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f964978fe96]
[bt]: (7) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x11d) [0x557d13bf4459]
[bt]: (8) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob3runEv+0x26a) [0x557d13bf4752]
[bt]: (9) /snap/xournalpp/86/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x557d13af1839]
[bt]: (10) /snap/xournalpp/86/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e1) [0x557d139bde61]
[bt]: (11) /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x97ce1) [0x7f9649f16ce1]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f96497eaac3]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f964987ca40]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/86/usr/bin/xournalpp(+0x3e3cbf) [0x557d139accbf]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f9649798520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f96497ec9fc]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f9649798476]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f964977e7f3]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f964977e71b]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f964978fe96]
??:0
[bt] #8 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x11d) [0x557d13bf4459]
??:0
[bt] #9 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9RenderJob3runEv+0x26a) [0x557d13bf4752]
??:0
[bt] #10 /snap/xournalpp/86/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x557d13af1839]
??:0
[bt] #11 /snap/xournalpp/86/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e1) [0x557d139bde61]
??:0
[bt] #12 /snap/xournalpp/86/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x97ce1) [0x7f9649f16ce1]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f96497eaac3]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f964987ca40]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = /snap/xournalpp/86/usr/share/locale, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /snap/xournalpp/86/usr/share/locale
INFO    : xopp :: Loading plugins from: /snap/xournalpp/86/usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/pb/snap/xournalpp/86/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
WARNING : GLib-GIO :: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to:

**Comment by tmoerschell** [comment]
This is a known issue that was fixed by d8b9ea5. The fix is included in the latest release 1.2.2. You can use that version by switching to the "candidate" or "edge" channel in the snap store.

Have fun with Xournal++ !

**Comment by dh2pp** [comment]
Thanks for the response and for maintaining this very nice piece of software!
