### ISSUE TITLE
How often is the PPA updated?

### ISSUE THREAD

**Issue by Hedronmx** [xournalpp/xournalpp#550]
I would like to know how often is the PPA updated with builds. Thanks!

**Comment by andreasb242** [comment]
There is no time set (not sure if I even can).
The git repo is updated automatically.

https://code.launchpad.net/~andreasbutti/xournalpp/+git/xournalpp
>The next import is scheduled to run in 5 hours.
>Last successful import was 16 minutes ago. 

https://code.launchpad.net/~andreasbutti/+recipe/xournalpp-daily
>23 minutes ago

So it build maybe about 4 times a day, if there are changes.
The timing depends on the server load, but it should be a current build.

The package is not marked as urgent, so you will get the automatically updates probably weekly. If you which, you need to call apt update and then apt distupgrade to force a current update.
