### ISSUE TITLE
Thumbnailer failing on some files (example provided): xoj-preview-extractor: no preview and page found, maybe an invalid file?

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#5534]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 23.10

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

.deb official release

### Xournal++ Version

1.2.3 (c6970f47)

### libgtk Version

3.24.38

### Bug Description

I have an hit-and-miss experience with thumbnails: more or less one third of them are not correctly build, and defaults to the standard thumbnail.

### Expected Behaviour

The very nice .xopp thumbnail is produced.

### Steps to Reproduce

Just uncompress the attached file:
[ApuntesWebinars.zip](https://github.com/xournalpp/xournalpp/files/14470575/ApuntesWebinars.zip)

The thumbnail is the following:

![image](https://github.com/xournalpp/xournalpp/assets/6414907/30a5602b-64b0-4d93-83d0-fc4ca0b2ddaf)

If I manually run `xournalpp-thumbanailer`, I have: 

```bash
[romano:~/software/ … alpp/new-thumb] 5 % xournalpp-thumbnailer ApuntesWebinars.xopp icon.png
xoj-preview-extractor: no preview and page found, maybe an invalid file?
```

This happens with old `.xopp` files as well as new ones, when created opening a `.pdf` file (to several, but not to all; sometimes it works ok, sometimes I have the above error).

**Comment by tmoerschell** [comment]
It appears that the file does contain a preview as it should, which I was able to extract manually: 

![download](https://github.com/xournalpp/xournalpp/assets/144177788/256c9be9-52bb-40b8-af36-1b1e30081978)

However, the encoded preview string is much longer than what is supported by the current code. In the provided example, the preview ends at byte number 11219 (decompressed), but only the 8192 first bytes are actually read from the file. 

Probably this is an issue on the extractor side: the preview is always shrunk to have a maximum of 128px width and height. Or maybe somebody else knows if there is another requirement?

**Comment by Rmano** [comment]
Hm. If I am not mistaken, 128x128 pixels, with a depth of 3 bytes (RGB), is around 50k. If it's [base64 encoded](https://stackoverflow.com/a/4715480/2907484) (didn't check), that means that in the worst case, when there is no compression, it would occupy 64kbytes (give or take). I understand that usually the `png` will be much smaller, but you never know. Especially in cases of scanned documents, with a high noise level, the compression can be very bad.

**Comment by Rmano** [comment]
I can confirm that the following patch

```diff
diff --git a/src/util/XojPreviewExtractor.cpp b/src/util/XojPreviewExtractor.cpp
index 21ddcd148..2f189a24a 100644
--- a/src/util/XojPreviewExtractor.cpp
+++ b/src/util/XojPreviewExtractor.cpp
@@ -21,7 +21,7 @@ const char* TAG_PAGE_NAME = "page";
 const size_t TAG_PAGE_NAME_LEN = strlen(TAG_PAGE_NAME);
 const char* TAG_PREVIEW_END_NAME = "/preview";
 const size_t TAG_PREVIEW_END_NAME_LEN = strlen(TAG_PREVIEW_END_NAME);
-constexpr auto BUF_SIZE = 8192;
+constexpr auto BUF_SIZE = 65536;
 
 XojPreviewExtractor::XojPreviewExtractor() = default;
```

seems to fix the issue. Notice that probably the real worst case (no compression at all) still is not covered because it should be added the header size for the preview image, if any, and probably a couple of bytes for terminators and so on.  And it could happen in some compression schemes that particularly nasty input creates output bigger than the data... 

Would you like a PR (with comments and maybe a more thought-of size) or is this sufficient?

**Comment by rolandlo** [comment]
@Rmano Yes, a PR is welcome.

**Comment by Rmano** [comment]
@rolandlo , done. I hope it's ok...

**Comment by Rmano** [comment]
Wonderful. Thanks, @bhennion , closing now (funny it did not close automatically...)
