### ISSUE TITLE
Border size in generated TeX too big

### ISSUE THREAD

**Issue by Nora-n** [xournalpp/xournalpp#5542]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

i3

### (Linux Only) Display Server

X.Org

### Installation Method

AUR

### Xournal++ Version

xournalpp 1.2.3+dev (8207b89a)

### libgtk Version

3.24.41

### Bug Description

When generating a TeX formula, the xournalapp item has a huge space between
the actual formula and the box it has when selected. It brings issues when
selecting figures because a small formula will have a way bigger bounding box.
See the image attached.

![24-03-05_16:16:47](https://github.com/xournalpp/xournalpp/assets/49752842/40ec8dac-df2b-48e3-9c38-22649cab5373)

### Expected Behaviour

I would like TeX-generated formulas to have a smaller selection box.

### Steps to Reproduce

1. Open xournalapp
2. Click Add/Edit Tex
3. Confirm the default x^2

**Comment by FrnchFrgg** [comment]
You should modify the LaTeX template to remove the default 5pt border. This will solve your issue. I do not know if the default template should remove that border which may have a good reason.

**Comment by Nora-n** [comment]
Changing that does not affect the border of the xournalapp object, only on the
preview. If you take negative borders, then it crops the formula, but
the distance between the cropped formula and the object's border is still
the same.

**Comment by tattsan** [comment]
It became larger with  62ac7b6df1a872ce7c34a988d883e58e50ac0195 @bhennion.

**Comment by tattsan** [comment]
I will post a comparison between the image selected using `xournalpp-1.2.3-x86_64.AppImage`:
![release](https://github.com/xournalpp/xournalpp/assets/6355486/8c936d27-f1d9-4c3c-b241-c9c7e7900e41)

 and the image selected using `xournalpp-1.2.3+dev-nightly.20240303-x86_64.AppImage`:
![master](https://github.com/xournalpp/xournalpp/assets/6355486/f3552657-5ad5-4d83-b9c3-0e16b8323f5d)

I've created the object before the comparison, and selected the same object in the same file.

This difference did not occur in a vanilla environment, so it seems that some setting in preferences is having an effect. I'll look into it further.

**Comment by tattsan** [comment]
The culprit is "screen DPI calibration"!

**Comment by Nora-n** [comment]
Indeed! Thank you I wouldn't have found this link without you.

See the two screenshots attached. One with the lowest value for DPI calibration, and one with the value that matches my ruler. I also did one with the parameter at maximum, and the selection box is clearly oversized.

![24-03-06_10:58:46](https://github.com/xournalpp/xournalpp/assets/49752842/adac521f-6c63-4a98-8d56-7821ae352fd8)
![24-03-06_10:59:35](https://github.com/xournalpp/xournalpp/assets/49752842/4a257e71-79f8-40da-8a57-157f4a92130c)

However, the smallest parameter is still not satisfactory… and this DPI
parameter seems useful to draw on an A4 paper with the right length, so I'd rather keep it at the intended value, but I'd rather have correct bounding boxes if there is a choice to make.

Any idea how to decorrelate this DPI parameter and the selection box?

**Comment by tattsan** [comment]
> Any idea how to decorrelate this DPI parameter and the selection box?

Use the release 1.2.3, not nightly build. That correlation is only in master &mdash; is this an intended behavior @bhennion?

You can also reduce `border=5pt` in the $\mathrm{\LaTeX}$ template file (In my case, `border=1pt`). This margin can be considered an insurance policy in case `standalone.cls` misidentifies the boundingbox, but I think it could be made smaller.
