### ISSUE TITLE
When enabling Geometry Tools, automatically switch to "Hand" tool

### ISSUE THREAD

**Issue by mesonium** [xournalpp/xournalpp#5548]
### Is Your Feature Request Related to a Problem?

When enabling and thus displaying a geometry tool, such as setsquare, the current used tool stays activated.

However, it's pretty clear that the user intends to interact with the geometry tool when they pull it into their document and when not by chance the "Hand" tool has already been selected, directly interacting the geometry tool is not possible.

### Feature Description

Automatically activate the "Hand" tool when enabling a geometry tool, in order to make direct interaction possible.

**Comment by rolandlo** [comment]
This solution wouldn't be ideal for Touchscreen users. The setsquare is primarly intended to be moved using Touch (even though it can also be moved via the hand tool or via keyboard) and then you want to draw immediately without switching back to the pen tool.

**Comment by rolandlo** [comment]
> Maybe there could a short hint displayed for non-touch-screen-users at least:
> 
> > Use the Hand tool to move and press (Shift) + R to rotate it (counter)clockwise
> 
> It took me a minute to figure it out by trial and error. I first had tried to interact with the "Select object" tool but w/o success.

I know it's not easy to figure out just using the tool. At least there is some decent documentation on the website though. https://xournalpp.github.io/guide/tools/geometry/
