### ISSUE TITLE
Add declaration file for the lua api

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#5555]
### Is Your Feature Request Related to a Problem?

Writing with the lua api you always need to have the docs / the header file open which isn't that nice to code with.

### Feature Description

Nowadays most ("general purpose") editors can use a language server. For lua there is [LuaLS](https://github.com/LuaLS/lua-language-server). Using this, the coding experience is much nicer. Still for proper suggestions, the language server needs to get to know the xournalpp lua api. For this purpose one can write some sort of declaration file.

What do you think about adding such file to the repo? The big drawback I see is that we need to keep that file in sync with the implementation of the luaAPI (which doesn't quite work with the website currently tbh)

### Additional Context

I've already created such file for me personally (docs on the functions are pretty brief though) which I could share / add to the repo.

**Comment by rolandlo** [comment]
That sounds like an interesting idea. How does one write a declaration file, are there some docs about it? Also please share an example, so we can get an idea of how it looks like.

**Comment by atticus-sullivan** [comment]
Implemented/Closed via https://github.com/xournalpp/xournalpp/pull/5572
