### ISSUE TITLE
Build for ARM on macOS

### ISSUE THREAD

**Issue by tmoerschell** [xournalpp/xournalpp#5566]
### Is Your Feature Request Related to a Problem?

Xournal++ requires Rosetta to run on ARM macOS devices. I talked to someone who considered this a blocker for him. That may be an issue for more people as well. 

### Feature Description

Add builds for ARM (aarch64) packages, and make them available on the website.

### Alternative Solutions

None (outside of using Rosetta)

### Additional Context

I'm aware this probably involves more than changing the complier flag. There are open issues about the same thing for Windows (#4585, #2145) and Linux (#3536, although that's just about the pipeline: binaries seem to be available and working). 

I have no experience with macOS or AzurePipelines at all, so I can't help much unfortunately.

**Comment by SteveLauC** [comment]
Yeah, I would love to see a native aarch64 package, thanks for bringing this up!

I switched from Linux to macOS, installed Xournal++ from homebrew, opened my books, and it felt so laggy, totally different from the one that I used on Linux.

**Comment by ricolxwz** [comment]
https://github.com/xournalpp/xournalpp/issues/5643#issuecomment-2083480167

**Comment by rolandlo** [comment]
An ARM build for MacOS was released with version 1.2.4

**Comment by SteveLauC** [comment]
Thanks for the work!

**Comment by tmoerschell** [comment]
Awesome! Thank you very much!!
