### ISSUE TITLE
Selected elements change colour when moved

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#558]
Steps to reproduce:
1) With your mouse, chose the tool "pen" (default colour is black, any will do)
2) With your pen, use the "select region" or "select rectangle" tool to move a group or a single element
3) the element(s) have now changed colour to match the "pen" colour set with your mouse
![peek 18-12-2018 09-34](https://user-images.githubusercontent.com/20294254/50141624-46607a80-02a8-11e9-9972-69a125f0e4af.gif)

**Comment by andreasb242** [comment]
There is a color changed event to much... Because if there is a selection, and you select another color, it changes the color.

**Comment by luco5826** [comment]
I don't know why but this doesn't happen to me

![ezgif-4-88fed93383d2](https://user-images.githubusercontent.com/38291180/50219327-29eb3d80-038f-11e9-955f-b250a57f99da.gif)

**Comment by morrolinux** [comment]
@luco5826 Have you chosen the "Pen" tool with your mouse, but selecting and moving with the pen?

**Comment by luco5826** [comment]
Oh sorry, I misread! I have no pen to test it right now!

**Comment by andreasb242** [comment]
I expect the error is caused by InputSequence::changeTool(), which is now called more often. I'll look at it.

**Comment by andreasb242** [comment]
The bug was not that worse than I thought, because it only appears in a very specail case, but anyway, it's fixed.
