### ISSUE TITLE
Virus in stable version - FileRepMalware

### ISSUE THREAD

**Issue by RodrigoHenriqueDev** [xournalpp/xournalpp#5595]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Download

### Xournal++ Version

Stable v1.2.3

### libgtk Version

none

### Bug Description

I downloaded Xournal++ on the oficial website today on April 1st and my Windows Defender detected a virus and prevented me from opening.
I scanned the .exe of Xournal++ with the Avast and it found FileRepMalware virus on its scanning. 

### Expected Behaviour

It's not supposed to have a malware in the software

### Steps to Reproduce

Somebody has to remove this virus

**Comment by Febbe** [comment]
Microsoft and Avast updated their virus database, it should work now.
