### ISSUE TITLE
Exact Fedora 29 build dependencies

### ISSUE THREAD

**Issue by orki** [xournalpp/xournalpp#560]
`sudo dnf install libxml2-devel cppunit-devel gtk3-devel boost-devel cmake-gui texlive-scheme-basic texlive-dvipng poppler-glib-devel`

This was tested with a fresh installation of Fedora 29 workstation.

**Comment by luco5826** [comment]
Hi! 
Thank you, could you create a Pull Request where you modify the readme/LinuxBuild.md file with the right install method?

**Comment by andreasb242** [comment]
@orki nearly forgot: Thank you, for the Information!
