### ISSUE TITLE
xournalpp-1.2.3-windows failed to set gui language to zh

### ISSUE THREAD

**Issue by saxyx** [xournalpp/xournalpp#5606]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

1.2.3

### libgtk Version

3.24.41

### Bug Description

OS: Windows 10 22H2 19045.4170
SystemCodePages：936

By selecting Edit -> Preferences -> Language, when I set the GUI language to Chinese (zh), it remains in English after restarting.

### Expected Behaviour

Set the GUI language to Chinese without any issues.

### Steps to Reproduce

As described in the Bug Description.

**Comment by Eason0210** [comment]
Have the same issue on Windows 10

**Comment by Febbe** [comment]
Seems like, setting the locale works, but it has no effect, probably something wrong with gettext. What's the content of `C:\Program Files\Xournal++\share\locale\zh\LC_MESSAGES`, is there a xournalpp.mo file?

**Comment by Febbe** [comment]
Can you try this? https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

**Comment by Febbe** [comment]
Can you also tell me the full path of the xournalpp.mo file? It may be, that we have an issue with utf8 / <windows chinese encoding> conversion of paths. I may have tracked it down to PathUtil.cpp:180 `auto Util::getGettextFilepath(const char* locale_dir) -> fs::path` which incorrectly mixes utf8 and system path encoding.

**Comment by Febbe** [comment]
Most likely the reason for this is, that there does not exist any translation for this. You could help out, by translating those on crowdin. I can't speak Chinese and we also don't have any one in the core team which does.

**Comment by Photon89** [comment]
Something similar happens with the German locale (Windows, Xournal++ v. 1.2.3 as well). As you can see, some menu entries are in German while some are in English.

![grafik](https://github.com/xournalpp/xournalpp/assets/1191480/8e4c4f80-49fd-48a2-97ab-fac69e26862f)
![grafik](https://github.com/xournalpp/xournalpp/assets/1191480/e15ea206-799d-4300-82c9-dd9a4a723fd0)
![grafik](https://github.com/xournalpp/xournalpp/assets/1191480/036c7acb-ce95-4e3f-9282-64dcc6a932c4)

**Comment by Febbe** [comment]
> Something similar happens with the German locale (Windows, Xournal++ v. 1.2.3 as well). As you can see, some menu entries are in German while some are in English.
> Image

The reason for this is, that there is just no translation for this in the locale file.
But @saxyx new issue is, that both releases show different output on windows 10 and windows 11.

**Comment by Febbe** [comment]
@rolandlo can you update the translations for release 1.2?

**Comment by rolandlo** [comment]
> @rolandlo can you update the translations for release 1.2?

Hmm, not sure if that makes sense. The translations are always made for master as you can see from https://crowdin.com/project/xournalpp/sources/files, so if we merge them into release 1.2, it may not work very well. We have only updated translations for master (and never for minor releases).

**Comment by Febbe** [comment]
Mhh, can we add also translations from the last minor release?
Another solution would be, to merge translations of the latest 2/3 (with xpp2.0 in mind) versions?

**Comment by rolandlo** [comment]
I'm not sure if we understand each other correctly. What I called "minor release" are versions 1.2.1, 1.2.2, 1.2.3 and the like. Version 1.2.3 runs with the translations from 1.2.0 (as do 1.2.1 and 1.2.2) and the current translations on Crowdin are for master. Are you saying we should just use the translations from master (maybe from a previous commit) and apply them to the release-1.2 branch? Normally we just merge translations into master every 2-3 months and for sure before the 1.3.0 release.

**Comment by Febbe** [comment]
x.x.Y are patch releases, major is Y.x.x .
What I mean is, to either 
 - merge the po from master and the minor branch together, so that the translations will work for both. This might increase translation files a bit (~5%).
 - or, add an additional translation branch in crowdin
 - or, just use translations from master.

**Comment by Febbe** [comment]
> I'd vote for either 1. or 2., with a preference for 2. (depending on how easy it is to configure)

Same. But I don't know how to configure that. Also @LittleHuba wrote the bot to do that for the master branch.

**Comment by rolandlo** [comment]
I would also go with 2. To configure that in Crowdin, it looks like one can add the branch via the "New Version branch" dropdown next to the "New folder" button.

![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/89af6c33-d335-4c4c-bfe3-9c35c904a25b)
![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/04458b7e-3857-4a19-81be-d83f51760e97)
![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/03159ff6-5cd0-47ed-90fe-8ccd2e445156)

**Comment by Photon89** [comment]
Is this actually a Windows specific issue? On my Linux machine all translations are fine.

**Comment by Febbe** [comment]
> Is this actually a Windows specific issue? On my Linux machine all translations are fine.

Partially, the windows related part is already fixed, but we have not released it yet.
