### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by majorace** [xournalpp/xournalpp#5611]
### Operating System

Linux

### (Linux only) Distribution

ubuntu

### (Linux only) Desktop Environment

mate

### (Linux Only) Display Server

X.Org

### Installation Method

official release

### Xournal++ Version

1.2.3

### libgtk Version

3.24.20

### Bug Description

Date: Tue Apr  9 08:18:48 2024
Error: signal 11
Xournal++ version 1.2.3
Git commit c6970f47 from xournalpp/HEAD
Gtk version 3.24.20

[bt]: (0) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(+0xde4b0) [0x57511090d4b0]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7cea88c42520]
[bt]: (2) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libcairo.so.2(cairo_get_target+0x4) [0x7cea89549fc4]
[bt]: (3) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZNK3xoj4view18BaseStrokeToolView10createMaskEP6_cairo+0xc0) [0x575110a98a90]
[bt]: (4) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x170) [0x575110a94580]
[bt]: (5) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XojPageView21drawAndDeleteToolViewEPN3xoj4view8ToolViewERK5Range+0x94) [0x575110a00e94]
[bt]: (6) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN13StrokeHandler20onButtonReleaseEventERK17PositionInputDatad+0x1f3) [0x575110a71213]
[bt]: (7) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XojPageView20onButtonReleaseEventERK17PositionInputData+0x9b) [0x575110a035cb]
[bt]: (8) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN15PenInputHandler9actionEndERK10InputEvent+0x104) [0x57511095ba94]
[bt]: (9) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN17MouseInputHandler10handleImplERK10InputEvent+0xdd) [0x57511095a9ad]
[bt]: (10) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN12InputContext6handleEP9_GdkEvent+0x2cc) [0x57511095967c]
[bt]: (11) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN3xoj4util6detail9wrap_implIXadL_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS3_EEbS8_JS5_S7_EEENSt11conditionalIX9is_same_vIbT0_EEiSA_E4typeEDpT2_Pv+0x10) [0x57511095a080]
[bt]: (12) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x3e736f) [0x7cea89de736f]
[bt]: (13) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(+0x14a56) [0x7cea89737a56]
[bt]: (14) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7cea89755df1]
[bt]: (15) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7cea897570f3]
[bt]: (16) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x391949) [0x7cea89d91949]
[bt]: (17) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x24ced8) [0x7cea89c4ced8]
[bt]: (18) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(gtk_main_do_event+0x89b) [0x7cea89c4f18b]
[bt]: (19) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgdk-3.so.0(+0x3cf69) [0x7cea8a261f69]
[bt]: (20) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgdk-3.so.0(+0x700f6) [0x7cea8a2950f6]
[bt]: (21) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7cea8963e17d]
[bt]: (22) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(+0x52400) [0x7cea8963e400]
[bt]: (23) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7cea8963e4a3]
[bt]: (24) /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgio-2.0.so.0(g_application_run+0x205) [0x7cea89895fe5]
[bt]: (25) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x647) [0x575110910a87]
[bt]: (26) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7cea88c29d90]
[bt]: (27) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7cea88c29e40]
[bt]: (28) /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_start+0x2e) [0x57511090c4de]

Try to get a better stacktrace...
[bt] #0 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(+0xdeb37) [0x57511090db37]
emergencySave() at ??:?
[bt] #1 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7cea88c42520]
__restore_rt at libc_sigaction.c:?
[bt] #2 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libcairo.so.2(cairo_get_target+0x4) [0x7cea89549fc4]
cairo_get_target at ??:?
[bt] #3 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZNK3xoj4view18BaseStrokeToolView10createMaskEP6_cairo+0xc0) [0x575110a98a90]
xoj::view::BaseStrokeToolView::createMask(_cairo*) const at ??:?
[bt] #4 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZNK3xoj4view14StrokeToolView4drawEP6_cairo+0x170) [0x575110a94580]
xoj::view::StrokeToolView::draw(_cairo*) const at ??:?
[bt] #5 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XojPageView21drawAndDeleteToolViewEPN3xoj4view8ToolViewERK5Range+0x94) [0x575110a00e94]
XojPageView::drawAndDeleteToolView(xoj::view::ToolView*, Range const&) at ??:?
[bt] #6 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN13StrokeHandler20onButtonReleaseEventERK17PositionInputDatad+0x1f3) [0x575110a71213]
StrokeHandler::onButtonReleaseEvent(PositionInputData const&, double) at ??:?
[bt] #7 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XojPageView20onButtonReleaseEventERK17PositionInputData+0x9b) [0x575110a035cb]
XojPageView::onButtonReleaseEvent(PositionInputData const&) at ??:?
[bt] #8 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN15PenInputHandler9actionEndERK10InputEvent+0x104) [0x57511095ba94]
PenInputHandler::actionEnd(InputEvent const&) at ??:?
[bt] #9 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN17MouseInputHandler10handleImplERK10InputEvent+0xdd) [0x57511095a9ad]
MouseInputHandler::handleImpl(InputEvent const&) at ??:?
[bt] #10 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN12InputContext6handleEP9_GdkEvent+0x2cc) [0x57511095967c]
InputContext::handle(_GdkEvent*) at ??:?
[bt] #11 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN3xoj4util6detail9wrap_implIXadL_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS3_EEbS8_JS5_S7_EEENSt11conditionalIX9is_same_vIbT0_EEiSA_E4typeEDpT2_Pv+0x10) [0x57511095a080]
std::conditional<is_same_v<bool, bool>, int, bool>::type xoj::util::detail::wrap_impl<&InputContext::eventCallback, bool, InputContext*, _GtkWidget*, _GdkEvent*>(_GtkWidget*, _GdkEvent*, void*) at ??:?
[bt] #12 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x3e736f) [0x7cea89de736f]
gtk_window_position_get_type at ??:?
[bt] #13 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(+0x14a56) [0x7cea89737a56]
g_closure_invoke at ??:?
[bt] #14 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7cea89755df1]
g_signal_emit_valist at ??:?
[bt] #15 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7cea897570f3]
g_signal_emit at ??:?
[bt] #16 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x391949) [0x7cea89d91949]
gtk_requisition_copy at ??:?
[bt] #17 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(+0x24ced8) [0x7cea89c4ced8]
gtk_lock_button_set_permission at ??:?
[bt] #18 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgtk-3.so.0(gtk_main_do_event+0x89b) [0x7cea89c4f18b]
gtk_main_do_event at ??:?
[bt] #19 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgdk-3.so.0(+0x3cf69) [0x7cea8a261f69]
gdk_event_free at ??:?
[bt] #20 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgdk-3.so.0(+0x700f6) [0x7cea8a2950f6]
gdk_x11_drag_context_get_type at ??:?
[bt] #21 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7cea8963e17d]
g_main_context_dispatch at ??:?
[bt] #22 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(+0x52400) [0x7cea8963e400]
g_main_context_dispatch at ??:?
[bt] #23 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7cea8963e4a3]
g_main_context_iteration at ??:?
[bt] #24 /tmp/.mount_xourna6jq3X5/usr/bin/../lib/libgio-2.0.so.0(g_application_run+0x205) [0x7cea89895fe5]
g_application_run at ??:?
[bt] #25 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x647) [0x575110910a87]
XournalMain::run(int, char**) at ??:?
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7cea88c29d90]
__libc_start_call_main at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
[bt] #27 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7cea88c29e40]
call_init at ./csu/../csu/libc-start.c:128
[bt] #28 /tmp/.mount_xourna6jq3X5/AppRun.wrapped(_start+0x2e) [0x57511090c4de]
_start at ??:?

Execution log:

DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
MESSAGE : xopp :: TEXTDOMAINDIR = /tmp/.mount_xourna6jq3X5/usr/share/locale:, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /tmp/.mount_xourna6jq3X5/usr/share/locale
INFO    : xopp :: Loading plugins from: /tmp/.mount_xourna6jq3X5/usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/jex/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/jex/.cache/xournalpp/errorlogs/errorlog.20240409-081848.log

### Expected Behaviour

.

### Steps to Reproduce

1

**Comment by Febbe** [comment]
What happened, or what did you do right before the crash. Looks like the handle to the cairo context was invalid. This can only happen, when the drawing process is canceled while still drawing.
