### ISSUE TITLE
tikz grid gets cut off when scaled

### ISSUE THREAD

**Issue by EmperorPenguin18** [xournalpp/xournalpp#5619]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

N/A

### (Linux Only) Display Server

X.Org

### Installation Method

pacman

### Xournal++ Version

1.2.2

### libgtk Version

3.24.41

### Bug Description

When using xscale with the tikz grid feature to make a stretched looking table, if more than 4 columns are used it gets cut off.

### Expected Behaviour

Table looks like it does on the wiki website.

### Steps to Reproduce

Try to enter this LaTeX text:
`\tikz{\draw (0,0) grid[xscale=2.5](5,6)}`

**Comment by rolandlo** [comment]
That was a problem in the past, but doesn't happen with the latest [default_template.tex](https://raw.githubusercontent.com/xournalpp/xournalpp/master/resources/default_template.tex) (when you add the tikz package again).

**Comment by EmperorPenguin18** [comment]
Yep that fixed it thanks
