### ISSUE TITLE
Stylus second button not working

### ISSUE THREAD

**Issue by jugendhacker** [xournalpp/xournalpp#5629]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Distribution Package

### Xournal++ Version

1.2.2

### libgtk Version

3.24.41

### Bug Description

When pressing the second button on my Stylus pen the defined action for the button does not happen anymore. I also tried it with the latest master and it still seems to be a problem.

### Expected Behaviour

When pressing the button Xournal++ should select the tool defined in the settings, just like the eraser button does.

### Steps to Reproduce

1. Define an action for the second button of the Stylus
2. Press this button
3. See that nothing happens

### Additional Context

Input log while drawing a stroke, pressing eraser button und then after that the second button of the pen: [debug_input.log](https://github.com/xournalpp/xournalpp/files/15048607/debug_input.log)

**Comment by j-lakeman** [comment]
Reproduced issue on Debian Sid also GNOME and Wayland.
Same Xournal++ and libgtk version as OP.

**Comment by jugendhacker** [comment]
Interestingly my pen (Lenovo Active Pen 2) works again after fixing it's common problem with the battery not having good contact anymore. Going to close this, as it was seemingly a hardware only problem.

**Comment by ruisuan** [comment]
Same there, my pen table ( XpPen Star G430S ) is recently bought ( purchased 2 months ago ) and the problem is there.
But in addiction the eraser button doesn't work too.

![video](https://streamable.com/0npj3i)
