### ISSUE TITLE
Missing user interface file

### ISSUE THREAD

**Issue by GhostJWZ** [xournalpp/xournalpp#5632]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Github下载安装

### Xournal++ Version

1.2.3

### libgtk Version

I don't know

### Bug Description

![IMG_20240421_160005](https://github.com/xournalpp/xournalpp/assets/91769008/1f1ee343-1ff6-435e-9471-bced7483e28f)
This picture popped up using an old version of software. Unable to run version 1.2.3 of the software

### Expected Behaviour

The software is not running properly

### Steps to Reproduce

The software is not running properly

**Comment by Febbe** [comment]
Can you delete the folder %AppData%\Local\xournalpp and reinstall xournalpp?
