### ISSUE TITLE
Titlebar is still white after setting the dark theme on MacOS

### ISSUE THREAD

**Issue by MatrixRanger98** [xournalpp/xournalpp#5635]
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

1.2.3

### libgtk Version

3.24.38

### Bug Description

![Xnip2024-04-22_01-18-26](https://github.com/xournalpp/xournalpp/assets/48684632/61f02038-1187-422b-b33f-b2d2129182a6)

### Expected Behaviour

Dark titlebar

### Steps to Reproduce

Install the official release on MacOS.
Launch the app.
Set the theme to dark.
Restart the app.

**Comment by rolandlo** [comment]
Dark theme support was recently improved. Please try the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly). Also include the version number for MacOS and your system preference setting for Dark/Light theme in case the issue is not solved.

**Comment by MatrixRanger98** [comment]
The nightly build does look nicer but the issue I mentioned remains. 
MacOS Sonoma 14.4.1; Apple M3 Pro; system set to dark theme

![Xnip2024-04-22_09-18-47](https://github.com/xournalpp/xournalpp/assets/48684632/5305b526-f26c-44f4-b030-8e99f9931ff0)

**Comment by rolandlo** [comment]
I can confirm the issue on MacOS Sonoma (with a Xournal++ ARM build) and will investigate once I find time for it.

**Comment by rolandlo** [comment]
Interestingly when I build Xournal++ locally and run it via `jhbuild run xournalpp` I get a dark titlebar (when the system theme is dark). Then when it is packed into an app bundle (via `build-app.sh`) and run as an app bundle, the titlebar is light.
GIMP has the same problem https://gitlab.gnome.org/GNOME/gimp/-/issues/10078 (but Inkscape apparently not).

**Comment by rolandlo** [comment]
The fix #5651 was merged into the release-1.2 branch. It will be part of the upcoming 1.2.4 release. The bundled version on cirrus-ci was built with the master branch, that doesn't contain the fix yet.
