### ISSUE TITLE
I can't change the type of sheet, the program closes when I try to change it.

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#5663]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release

### Xournal++ Version

v1.2.3+dev

### libgtk Version

3.24.41

### Bug Description

I try to change to grid sheet but the program closes when I do it.

### Expected Behaviour

would like it to work as usual

### Steps to Reproduce

1. open xournal++

2. go to sheet options

3. choose any type of different sheet style

**Comment by rolandlo** [comment]
The fix (#5665) will be available in the next nightly.
