### ISSUE TITLE
Gtk3 version update?

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#567]
Hi!
I was trying to fix some make warnings about deprecated methods, but the Travis CI build failed because it is still building on Ubuntu Xenial which uses gtk 3.18. Would it be a problem for Xournal++ to upgrade at least to Ubuntu 17 in order to get Gtk 3.22? I saw in PageTemplateDialog.cpp that using Gtk 3.22 makes the dialog a lot smaller and simpler reducing a lot the code complexity. 
This is just an example, what do you think?

I also saw this "versions history" and even Debian Stretch (which is usually the least up-to-date distro) uses Gtk 3.22

[https://github.com/FreeRDP/Remmina/wiki/GTK-versions-on-various-distributions](url)

**Comment by andreasb242** [comment]
https://docs.travis-ci.com/user/reference/overview/

At the Moment. No.
>A sudo enabled, full virtual machine per build, that runs Linux, either Ubuntu Xenial 16.04, Ubuntu Trusty 14.04, or Ubuntu Precise 12.04

Update Ubuntu 16.04 with PPAs would be an option, but it would make the Build slower, so at the Moment I would simply say no.

They added Ubuntu 16.04 a short time ago, so I don't expect a change at the Moment:
https://github.com/travis-ci/travis-ci/issues/9460

But to clarify: I brought the GTK3 branch to master not a long time ago, so I'm not against updating. But it's simple not possible at the moment without spending much time to this.

**Comment by andreasb242** [comment]
I close this ticket now, if you have a solution for a Build, or (later) Travis CI supports Ubuntu 18.04, we can update. 
@luco5826 OK?

**Comment by luco5826** [comment]
@andreasb242 Awesome! I didn't know Travis doesn't support Ubuntu 17 or later! I'm gonna search for a workaround in the meantime!

**Comment by andreasb242** [comment]
Ok. You may also register for Notification on the Tickets of travis, so you get notified if they support it. It's a Github ticket...
