### ISSUE TITLE
Linux reads wrong PDF-filepath after editing with Windows

### ISSUE THREAD

**Issue by PapierFliegr** [xournalpp/xournalpp#5673]
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

KDE Plasma 6

### (Linux Only) Display Server

Wayland

### Installation Method

Arch extra repo

### Xournal++ Version

1.2.2

### libgtk Version

3.24.41

### Bug Description

I sync my notes between Linux and Windows using Nextcloud.
Since .xopp uses absolute paths for background pdfs, I changed my document folder on windows to be `C:/home/<user>/Documents/`.

When opening the .xopp file on windows everything works as expected (even when last edited on Linux), whereas on Linux I get the error message, that the background file was last seen at `/home/<user>/Documents/C:/home/<user>/Documents/`

### Expected Behaviour

Opening .xopp with the background file independent of operating system.

### Steps to Reproduce

1. Use any background pdf
2. Save on Windows
3. Sync file with Linux
4. Open on Linux

### Additional Context

I am aware of the "attach file to journal" option, but I wouldn't want an extra copy of the pdf.

**Comment by KlausBlum** [comment]
Here it would be helpful to have relative PDF-paths, see https://github.com/xournalpp/xournalpp/pull/4262.  
Someone already has done the work. AFAIK it's on the roadmap for 1.3.0.
I've cheery-picked the commits from the PR and applied them to a nightly 1.2.3 build: 
https://github.com/KlausBlum/xournalpp/releases/tag/v1.2.3_JKG  
  
I have the same folder structure on a Win10 and a Linux machine and sync them via a USB memory stick. This works pretty well for me. 
On both machines, I can open a xopp file and the background PDF is found.

**Comment by PapierFliegr** [comment]
Thank you for your input.
Then I guess, I'll have to wait until the release of 1.3.0 :)

If I am to impatient, maybe I will try your build.
