### ISSUE TITLE
Crash when using keyboard or mouse after using pen

### ISSUE THREAD

**Issue by nicegamer7** [xournalpp/xournalpp#5713]
### Operating System

Linux

### (Linux only) Distribution

NixOS

### (Linux only) Desktop Environment

Hyprland

### (Linux Only) Display Server

Wayland

### Installation Method

Nixpkgs

### Xournal++ Version

1.2.3

### libgtk Version

3.24.41

### Bug Description

Xournal crashes when clicking any button using the trackpad or using any keyboard shortcut, but only after using a pen for some time. If I don't use the pen, then the trackpad and keyboard shortcuts don't cause any problems, but after I use the pen for some time, if I click a button using the trackpad (sometimes even just moving the mouse), or if I use a keyboard shortcut (such as Ctrl+s), Xournal will crash.

### Expected Behaviour

I should be able to use my trackpad, keyboard, and pen without any issue.

### Steps to Reproduce

1. Launch Xournal
2. Use mouse and/or keyboard
3. Use pen for some time
4. Use mouse or keyboard

### Additional Context

[errorlog.20240528-125218.log](https://github.com/xournalpp/xournalpp/files/15488538/errorlog.20240528-125218.log)

**Comment by Tychology** [comment]
I have the same problem, also on Nixos and Hyprland.

**Comment by yorororo** [comment]
I also have the same problem, on exactly the same environment.
Has someone searched for Xournal++ version where the problem doesn't appear?

**Comment by nicegamer7** [comment]
I haven't and I won't be able to for at least the next week. It would also be good to try this on different versions of Hyprland, or on another compositor like Sway.

**Comment by CrumblyLiquid** [comment]
I'm running an up to date NixOS system with Hyprland as my WM.

Using this [website](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=xournalpp) I found the nixpkgs revisions corresponding to Xournal++ versions and I quickly tried `1.1.0` and `1.0.8`. 

`1.0.8` fails to even start complaining about `version `GLIBC_2.34' not found`

`1.1.0` runs and I can reproduce the crash on that version.

So assuming the issue wasn't patched and then reintroduced again I think it's an Hyprland issue. I was on an old revision of the nixpkgs until recently and I didn't have any issues with Xournal++ so I think it's probably and issue with some newer versions of Hyprland.

**Comment by J-Kreisel** [comment]
I am using arch with hyprland and have the same problem. I have now downgraded hyprland to version 0.40.0-1 and it does not crash. 
I also tried it on a similar setup on my Laptop and it does not crash there for some reason.

Sidenote:
I am using OpenTabletDriver for my tablet and this driver shows weird behaviour on the newer hyprland versions where the defined screen area does not match the real area on my screen, so I guess it is not a random change in hyprland that only impacts xournal++

**Comment by okobenoko** [comment]
> I am using arch with hyprland and have the same problem. I have now downgraded hyprland to version 0.40.0-1 and it does not crash. I also tried it on a similar setup on my Laptop and it does not crash there for some reason.
> 
> Sidenote: I am using OpenTabletDriver for my tablet and this driver shows weird behaviour on the newer hyprland versions where the defined screen area does not match the real area on my screen, so I guess it is not a random change in hyprland that only impacts xournal++

Same problem.

**Comment by okobenoko** [comment]
> I am using arch with hyprland and have the same problem. I have now downgraded hyprland to version 0.40.0-1 and it does not crash. I also tried it on a similar setup on my Laptop and it does not crash there for some reason.
> 
> Sidenote: I am using OpenTabletDriver for my tablet and this driver shows weird behaviour on the newer hyprland versions where the defined screen area does not match the real area on my screen, so I guess it is not a random change in hyprland that only impacts xournal++

I have the same problem.
