### ISSUE TITLE
Palm Rejection settings

### ISSUE THREAD

**Issue by cshah25** [xournalpp/xournalpp#5721]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Official Release

### Xournal++ Version

1.2.2

### libgtk Version

3.24.41

### Bug Description

Tweaking the settings for palm rejection crashed ubuntu. Running surface linux kernel. Furthermore it feels like there is no palm rejection. The screen goes insane when I try to write anything and put my hand on the screen.

### Expected Behaviour

Expected to increase palm rejection.

### Steps to Reproduce

1. Install surface kernel from https://github.com/linux-surface/linux-surface on a surface device.
2. Changing the settings for hand recognition under touchscreen in preferences

**Comment by jbussmann** [comment]
Similar issue on Debian 12/Gnome with surface kernel and Xournal++ v1.2.3. Hand Recognition does not have any noticeable effect as I can place the pen on the screen and create strokes by using my finger to move the page underneath the pen. I can only make the program usable by disabling the touchscreen as an input device. However I didn't experience any crashes whatsoever.

**Comment by niiiksh** [comment]
I have this problem with Ubuntu 24.04.1, hand detection doesn't work. Ubuntu uses Wayland but this option has X11 only and manual one.

**Comment by cshah25** [comment]
I was able to do a workaround this issue by calibrating the IPTSD driver in the linux-surface kernel.

Here is the guide i followed:
https://github.com/linux-surface/iptsd/wiki/Calibrating-iptsd
