### ISSUE TITLE
Windows: PDF Not working

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#574]
On Windows 10 PDFs are not loaded, looks like a path issue.

**Comment by luco5826** [comment]
Do you refer to the "Annotate PDF" action?

**Comment by andreasb242** [comment]
No, generally.
I think I found the issue, Windows uses Backslashes, and the file URI is not valid anymore with backslashes, probably they only need to be replaced with slash.

**Comment by andreasb242** [comment]
g_filename_to_uri does the trick. Replacing backslash with slash does not work.
