### ISSUE TITLE
Xournal++ crashes upon calling `app.getFilePath` in Lua plugin

### ISSUE THREAD

**Issue by PellelNitram** [xournalpp/xournalpp#5743]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.3

### libgtk Version

3.24.33

### Bug Description

I am working on a Lua plugin and want to obtain a file path using `app.getFilePath()`.

Xournal++ crashes when the plugin reaches the line that states `app.getFilePath()`.

### Expected Behaviour

I expect to see a file selection dialogue and I expect to get the selected file back upon returning control to the Lua plugin.

### Steps to Reproduce

**Install the plugin**

Copy the following content to `~/.config/xournalpp/plugins/get_file_path_crash/plugin.ini`:

```ini
[about]
## Author / Copyright notice
author=Martin Lellep

description=Reproduce Xournal++ 1.2.3 crash upon calling app.getFilePath

## If the plugin is packed with Xournal++, use
## <xournalpp> then it gets the same version number
version=0.1

[default]
enabled=true

[plugin]
mainfile=main.lua
```

Copy the following content to `~/.config/xournalpp/plugins/get_file_path_crash/main.lua`:

```lua
function initUi()
  app.registerUi({["menu"] = "get file path crash", ["callback"] = "run"});
end
  
function run()

  app.getFilePath()

  return
end
```

**Call the plugin through Xournal++**

Click on "Plugin" > "get file path crash" in the menubar.

My Xournal++ crashes upon doing so!

### Additional Context

I tested the same procedure on Windows and also there Xournal++ crashes.

**Comment by rolandlo** [comment]
You need to write `app.getFilePath({})`. It was falsely documented previously. That was changed in #5723.
Also note that `app.getFilePath` got deprecated in favor of `app.fileDialogOpen` (which is Gtk4 compatible).

**Comment by PellelNitram** [comment]
Cheers for your quick response!

Based on what you responded, I have discovered both `app.fileDialogOpen` and `app.fileDialogSave`, where the latter is actually what I need.

However, none of the two seem to work for me when using `1.2.3+dev` nightly. `app.fileDialogSave`, which is used in QuickScreenshot plugin, does not seem to block the execution order so that the logic just continues. After then selecting a file, I am show this error: `Error in Plugin: "xournalpp_htr", error: "attempt to call a nil value"`. When trying to use `app.fileDialogOpen`, then Xournal++ crashes again for me.

Am I using the API incorrectly?

**Comment by rolandlo** [comment]
How are you using the API? Show me the code. You can't block execution in Gtk 4. In `app.fileDialogOpen` and `app.fileDialogSave` you must provide the name of a callback function that is executed when the user has chosen a file to open/save.

**Comment by PellelNitram** [comment]
> you must provide the name of a callback function

Oh, that's interesting and probably solves my problem!

This is the code that I execute:

```lua
filepath = app.fileDialogSave("Save", "untitled.pdf")
print(filepath) -- For debugging purposes

local result = app.msgbox("Exports starts now, please wait until finished", {[1] = "Continue", [2] = "Cancel"}) -- code logic after selecting file
```

I then see the message box right on top of the save dialog.

What is the right usage of `app.fileDialogSave`?

**Comment by rolandlo** [comment]
Well yes, looking at the documentation helps. By the way there is a definition file `luapi_application.lua.def` in the plugins folder, which help a great deal when writing plugins.

For example in VS Code you can install the sumneko Lua language server extension and set workspace.library to the folder containing the file. See #5572 and https://luals.github.io/wiki/definition-files/ for background info.

You're right about `save_file` being only allowed to feature one parameter, the string that refers to the selected path.

**Comment by PellelNitram** [comment]
Thanks a lot for your help! I can confirm that everything seems to work. This is the result of my questions: [Xournal++ HTR Plugin (draft)](https://github.com/PellelNitram/xournalpp_htr/blob/master/plugin/main.lua#L36).

I had not seen the `luapi_application.lua.def` file and itself as well as the underlying tooling looks super cool! In particular, it is in sync with the corresponding code version where the page [Building Plugins](https://xournalpp.github.io/guide/plugins/plugins/) is (obviously) not compatible with any given code version as the page was built using one specific code version.

I consider my problem solved & close the issue.
