### ISSUE TITLE
[bug report]  clicking on "image" button does not bring up file dialog menu

### ISSUE THREAD

**Issue by fugata** [xournalpp/xournalpp#5748]
### Operating System

Linux

### (Linux only) Distribution

mint 21.02

### (Linux only) Desktop Environment

xfce

### (Linux Only) Display Server

X.Org

### Installation Method

github

### Xournal++ Version

1.1.1 and 1.2.3

### libgtk Version

3.24.33

### Bug Description

Clicking the "image" button does not bring up the file dialog menu, so I cannot import image files into xournal.  

### Expected Behaviour

Based on the user manual:  Upon clicking the "image" button I should have gotten a file dialog menu.

Note:
I do get a file dialog menu if I click on e.g. the "save" button or "open file" button.

### Steps to Reproduce

1. Click on the "image" button
2. Nothing happens

### Additional Context

(I tried generating input logs, but failed at

 cmake -UDEBUG_INPUT_GDK_PRINT_EVENTS -UDEBUG_INPUT ..

since a number of the modules required seem to be older than what's on my system)

**Comment by rolandlo** [comment]
Clicking on the image button won't bring up a file dialog. You first have to click on the canvas (or drag out a rectangle) to define the place where the image is inserted. Only then you see a file dialog.

**Comment by fugata** [comment]
@rolandlo:  You are correct!   

May I then suggest that this be included in the user manual?   THANKS!

(I don't know if I should close this issue myself or wait until the system admin does)
