### ISSUE TITLE
Silent installation ("/S") does not work with switch "/AllUsers"

### ISSUE THREAD

**Issue by O-Bal** [xournalpp/xournalpp#5768]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

xournalpp-1.2.3-windows.exe /S /AllUsers

### Xournal++ Version

1.2.3

### libgtk Version

3.24.41

### Bug Description

When installing with "xournalpp-1.2.3-windows.exe /S /AllUsers" the installer writes its information into "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Xournal++" instead of "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Xournal++". This works fine, when the installation is not silent. But for installing this automatically, it is crucial to have the silent installion working.

### Expected Behaviour

When installing with "xournalpp-1.2.3-windows.exe /S /AllUsers" the installer should write its information into "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Xournal++".

### Steps to Reproduce

Just install with these options: "xournalpp-1.2.3-windows.exe /S /AllUsers"

**Comment by rolandlo** [comment]
This was fixed in the release branch via #5988.
