### ISSUE TITLE
Make .xopp journals more portable

### ISSUE THREAD

**Issue by sweeneyal** [xournalpp/xournalpp#5796]
### Is Your Feature Request Related to a Problem?

I'm trying to use Xournal++ for notetaking for university, and I found that .xopp files created on my Windows 11 tablet are incompatible with .xopp files on Ubuntu 20.04. 

When I open the file created on Windows on my Linux machine, the formatting is wrong and the name is a random string of text, and saving it creates a completely different file, regardless if Save or Save-As is used.

### Feature Description

Make .xopp files compatible across platforms.

### Alternative Solutions

Alternatively, allow save-as to overwrite the old .xopp file and not create files with random string names, or create a second file type that supports cross platform transfer.

**Comment by rolandlo** [comment]
That shouldn't happen. What versions of Xournal++ do you use on Windows and Ubuntu? Cn you please share a .xopp-file that looks different on the two systems?

**Comment by sweeneyal** [comment]
Sure, I'm trying to put together an example but Github is throwing a fit over any zip files or xopp files I attach. 

I'm using Xournal++ 1.2.3 installed from the website on both. One further thing I didn't mention initially is that the .xopp files are synchronized and shared across Google Drive for the sake of ease of transfer. I'm still testing my setup, but here's an explicit writeup of what I did:

1. Installed Xournal++ 1.2.3 (stable) on my Ubuntu 20.04 and Windows 11 devices.
2. Connected Windows to Google Drive using the Google Drive for Desktop app.
3. Created a .xopp file on Windows with some text in it and saved it into the local copy of Google Drive that gets synchronized.
4. Connected Ubuntu 20.04 to Google Drive using the GNOME Online Accounts feature.
5. Accessed the .xopp file from the Google Drive from Xournal++ on my Ubuntu machine.
6. Noticed that instead of opening the .xopp file, Xournal++ loads the data from the .xopp file and generates a name at the top like "1udA2bR..." where it continues for about 33 characters. If I compress the .xopp file to a zip file, this string looks exactly like what the file looks like inside a zip file.
7. The formatting also is wrong, where text that does not overlap on Windows starts overlapping.
8. Fixed the formatting.
9. Save will then use the 33 character string name instead of the original name.
10. Save-As will also use the 33 character string name if you attempt to overwrite the original file.
11. Current workaround I found is to Save-As a different file, delete the old one, then rename back to the old file name.
12. I just now transferred this file back to Windows and the formatting fixes on Linux work, so this appears to be a Linux-only issue.

**Comment by sweeneyal** [comment]
After testing it further it looks like it has to do with Google Drive borking my files. If I copy the offending file to somewhere else, I can open it without having the zip string issue. My bad. I'll keep looking at this.
