### ISSUE TITLE
xournalpp crashes when swiching to another workspace on hyprland

### ISSUE THREAD

**Issue by leodlpy7** [xournalpp/xournalpp#5817]
### Operating System

Linux

### (Linux only) Distribution

NixOS

### (Linux only) Desktop Environment

Hyprland

### (Linux Only) Display Server

Wayland

### Installation Method

Nix Package

### Xournal++ Version

1.2.3

### libgtk Version

3.24.42

### Bug Description

When I switch from the workspace where I use Xournal++ to another workspace, Xournal++ craches. I experience this behaviour only when I have used the canvas to write something.

Maybe this is a Hyprland bug, but I am not sure. But if it should be relevant, I am using Hyprland build from commit 918d8340afd652b011b937d29d5eea0be08467f5 (Tag: v0.41.2) on NixOS from the unstable channel.

### Expected Behaviour

No crash, I don't want to restart Xournal++ every time I switch the workspace to read something.

### Steps to Reproduce

1. Start Xournal++ on Hyprland
2. Write something to the canvas
3. Switch the workspace to your second screen
4. See Xournal++ crash on your other screen

### Additional Context

[errorlog.20240819-111424.log](https://github.com/user-attachments/files/16658429/errorlog.20240819-111424.log)

**Comment by leodlpy7** [comment]
Update: Xournal++ now crashes just sometimes and I cannot determine why. Maybe I forgot to install an external dependency which is not used at all times?

**Comment by leodlpy7** [comment]
Update: Xournal++ just not crashes totally, only the UI crashes. The process is running on, but the UI is not visible any more.

**Comment by dr0bz** [comment]
@leodlpy7 i had the same behaviour on Hyprland: v0.41.2. Update it. I'm on v0.42.0-58-gf634b9e6 - xournal not crashing anymore.

**Comment by leodlpy7** [comment]
@dr0bz Thx for your response, I now waited for hyprland v0.42.0 to be in nix unstable, and I do not encounter the issue anymore.
I think the issue can be closed as it is related to hyprland and not to xournalpp
