### ISSUE TITLE
Bug with highlighter

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#583]
Hi! I've got a problem, whenever I try to highlight something or generally using the highlighter, the stroke is fine until I end it, then after one/two secs it does something like re-render the stroke but not every point, just some of them, resulting in a less transparent stroke or a messy output

![ezgif-4-2aee7208b1b7](https://user-images.githubusercontent.com/38291180/50378405-fbd95800-0631-11e9-99d3-d2cbb3a28c7d.gif)

**Comment by andreasb242** [comment]
Confirmed, I have a look at it
