### ISSUE TITLE
Add toggle option for ctrl and shift button

### ISSUE THREAD

**Issue by BerubePascal** [xournalpp/xournalpp#5899]
### Is Your Feature Request Related to a Problem?

I use the app on a Surface and I'm always in tablet mode (no acces to keyboard) which makes it impractical to use the Ctrl and/or Shift key for shape generation. The main issue I have is the circle generation that start at a corner of a square to the opposite corner. I'm sure it has it's utility, but guessing the final possition is often hard and the shape as to be repositionned.

### Feature Description

It would be nice to have the possibility to chose how shapes are generated instead of one permanent way with modifiers (Ctrl and/or Shift). I was thinking of something like sketchs in CAD software like SolidWorks or Onshape:

![image](https://github.com/user-attachments/assets/a69286ac-78fa-4f96-85fc-4ce3b235ea9a)

![image](https://github.com/user-attachments/assets/44dc707b-0f2b-48b5-969d-c77bb61c5285)

![image](https://github.com/user-attachments/assets/2b586c1a-e519-44d3-96d0-2daf07d655a0)
[images from onshape]

### Alternative Solutions

What could possibly work too is the possibility to simply tell the app to concider the key pressed with a check box or something. I know some people use the TabletFriend to add keyboard shortcut to the screen, but I'd like a solution that don't requier a third party app.

### Additional Context

I do have a plugin to save custom pencil, but I have no clue on how to tell it to "think" Ctrl and/or Shift are pressed (even if they are not)

```-- Icon path: C:\Program Files\Xournal++\share\xournalpp\ui\iconsLucide-dark\hicolor\scalable\actions

function initUi()
  app.registerUi({["menu"] = "Circle", ["callback"] = "circle", ["toolbarId"] = "CIRCLE", ["iconName"] = "xopp-draw-ellipse"})
  app.registerUi({["menu"] = "Red line", ["callback"] = "red_line", ["toolbarId"] = "RED_LINE", ["iconName"] = "xopp-draw-red-line"})
  app.registerUi({["menu"] = "Green line", ["callback"] = "green_line", ["toolbarId"] = "GREEN_LINE", ["iconName"] = "xopp-draw-green-line"})
  app.registerUi({["menu"] = "Red arrow", ["callback"] = "red_arrow", ["toolbarId"] = "RED_ARROW", ["iconName"] = "xopp-draw-red-arrow"})
  app.registerUi({["menu"] = "Green arrow", ["callback"] = "green_arrow", ["toolbarId"] = "GREEN_ARROW", ["iconName"] = "xopp-draw-green-arrow"})
  app.registerUi({["menu"] = "Green double arrow", ["callback"] = "green_double_arrow", ["toolbarId"] = "GREEN_DOUBLE_ARROW", ["iconName"] = "xopp-draw-green-double-arrow"})
end

function cirlce()
  app.uiAction({["action"] = "ACTION_DRAW_ELLIPSE"})
  SOMEHOW THINK CTRL + SHIFT IS PRESSED
end

function red_line()
  app.uiAction({["action"]="ACTION_RULER"})
  app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
  app.changeToolColor({["color"] = 0xFF0000, ["selection"] = True})
end

function green_line()
  app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
  app.uiAction({["action"]="ACTION_RULER"})
  app.changeToolColor({["color"] = 0x307A26, ["selection"] = false})
end

function red_arrow()
  app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
  app.uiAction({["action"]="ACTION_TOOL_DRAW_ARROW"})
  app.changeToolColor({["color"] = 0xFF0000, ["selection"] = false})
end

function green_arrow()
  app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
  app.uiAction({["action"]="ACTION_TOOL_DRAW_ARROW"})
  app.changeToolColor({["color"] = 0x307A26, ["selection"] = false})
end

function green_double_arrow()
  app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_MEDIUM"})
  app.uiAction({["action"]="ACTION_TOOL_DRAW_DOUBLE_ARROW"})
  app.changeToolColor({["color"] = 0x307A26, ["selection"] = false})
end```

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
