### ISSUE TITLE
Xournal crashes when settings window closes

### ISSUE THREAD

**Issue by PatrickCharlot** [xournalpp/xournalpp#5923]
### Operating System

Linux

### (Linux only) Distribution

kubuntu

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

None

### Installation Method

AppImage

### Xournal++ Version

1.2.3

### libgtk Version

libgtk: 3.24.20

### Bug Description

The application crashes everytime I close the settings window.

### Expected Behaviour

I would expect that Xournal++ does not crash and save settings. 

### Steps to Reproduce

1. Open settings windows 
2. close by "validate" button (and enjoy !)
[errorlog.20241007-063757.log](https://github.com/user-attachments/files/17273164/errorlog.20241007-063757.log)

**Comment by rolandlo** [comment]
It looks like the AppImage was compiled with GtkSourceView and you don't have all files in the AppImage or on your system. See https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/55
Probably installing `libgtksourceview-4-0` and `libgtksourceview-4-common` helps.

**Comment by PatrickCharlot** [comment]
I have installed |libgtksourceview-4-0 and it seems to be OK  (for now !)|

Thanks,
Patrick

Le 07/10/2024 à 07:05, Roland Lötscher a écrit :
