### ISSUE TITLE
Coverity scan fails because of  include for 90%

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#595]
I try to compile xournalpp with cov-build for coverity scan. But it is failing on same extern error in `/usr/include/c++/8/type_traits` for almost all files. This results in 90% failure. Anybody an idea?

```
"/usr/include/c++/8/type_traits", line 1049: error #255: type name is not
          allowed
        : public __bool_constant<__is_assignable(_Tp, _Up)>
                                                 ^

"/usr/include/c++/8/type_traits", line 1049: error #255: type name is not
          allowed
        : public __bool_constant<__is_assignable(_Tp, _Up)>
                                                      ^

"/usr/include/c++/8/type_traits", line 1049: error #20: identifier
          "__is_assignable" is undefined
        : public __bool_constant<__is_assignable(_Tp, _Up)>
                                 ^

"/usr/include/c++/8/utility", line 307: error #1937: pack expansion does not
          make use of any argument packs
        using __type = _Index_tuple<__integer_pack(_Num)...>;
                                                        ^

Emit for file 'PROJECTPATH/FILEPATH/FILE.cpp' complete.
[ERROR] 4 errors detected in the compilation of 
```

**Comment by andreasb242** [comment]
Does not happen on my system. it gots 100%. I try to upload it.

**Comment by andreasb242** [comment]
I got a mail.
>    Your request for analysis of xournalpp/xournalpp  is failed.
 >   Analysis status: No action need
>
>    The problem is on the Coverity server, and we will address it.
 >   Your request will be automatically submitted for analysis.
 >   If you do not see your build being analyzed, please email REMOVED_FOR_SPAM_REASON@coverity.com.

So for now I think we have to wait?!

**Comment by andreasb242** [comment]
Still not working

**Comment by peetCreative** [comment]
Coverity scan seems to be dead or at least down anyway. 
[https://community.synopsys.com/s/article/Coverity-Scan-Update](coverity news)

**Comment by peetCreative** [comment]
I would also for now move away from coverity.
