### ISSUE TITLE
Crash on Annotate PDF

### ISSUE THREAD

**Issue by IkeEisenhauer** [xournalpp/xournalpp#5982]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

1.2.4+dev

### libgtk Version

3.24.41

### Bug Description

App crashes to close upon attempted loading of pdf to annotate from Annotate PDF menu item.

### Expected Behaviour

PDF should open and be ready to annotate. App should not crash to close.

### Steps to Reproduce

1. Start App
2. Select Annotate PDF
3. Select PDF file from File Open dialog box

### Additional Context

Works correctly on same PDF in 1.2.3

**Comment by rolandlo** [comment]
I can't reproduce on Linux (Ubuntu 24.10), putting therefore a Windows label for the time being.

**Comment by IkeEisenhauer** [comment]
Issue seems to have resolved itself in the latest [2024_12_03] dev drop. Closing issue.
