### ISSUE TITLE
Bug that crashes application on entering certain mouse presses on the scrollbar

### ISSUE THREAD

**Issue by AteebXYZ** [xournalpp/xournalpp#5986]
### Operating System

Linux

### (Linux only) Distribution

Fedora 40

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

X.Org

### Installation Method

Official Release (AppImage)

### Xournal++ Version

1.2.4 (2a4ed3fd)

### libgtk Version

3.24.20

### Bug Description

By left clicking the scrollbar on the left and holding left click, it becomes highlighted as blue. Then, when you quickly right and then left click on the pages tab, the application crashes. However, if the two clicks at the end have a time gap, the app wont crash, the screen recording shows this behavior.

### Expected Behaviour

The app should continue functioning, not showing any strange behavior or quitting.

### Steps to Reproduce

1. Left click and then right click the scrollbar on the right so it is highlighted blue
2. Quickly right and left click with minimal interval on the pages tab for the app to crash.

### Additional Context

The error log and a simple screen recording of the bug.

[errorlog.20241026-201741.log](https://github.com/user-attachments/files/17531428/errorlog.20241026-201741.log)

https://github.com/user-attachments/assets/8dc2f33b-e151-4420-a44c-1e77caa444cf

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AteebXYZ** [comment]
> I cannot reproduce. It looks like a bug in GTK though, and it may have been fixed (I have GTK 3.24.43).
> 
> Could you try another installation method (like the Fedora package)? It'll then use Fedora's GTK 3.24.43 which could help.

Yeah i just tried with the dnf package, i couldnt reproduce the problem, looks like it only happens with the appimage or the gtk version, when i installed the fedora package and did xournalpp --version i got gtk 3.24.43 but the appimage only shows the older libgtk
