### ISSUE TITLE
Form based PDF sometimes does not export

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#60]
There is some element in the form that isn't properly handled by PdfExport.cpp (i.e. it's not returning an objStream). I'm guessing it's a form element, though it might be a weird font element or something.

```
** (xournalpp:26941): WARNING **: other poppler type: 6
```

ObjType is an enum so I believe this refers to an objArray that the PDF has and we don't know how to handle yet.

**Comment by andreasb242** [comment]
There are already some fixes, and the bug is really old, and no file to confirm. Therefore I close this bug.
