### ISSUE TITLE
Let tools spawn at the zoomed viewport

### ISSUE THREAD

**Issue by cgloeckner** [xournalpp/xournalpp#6006]
### Is Your Feature Request Related to a Problem?

When zooming in (e.g. such that the page width fills the screen), and scrolling down (to the edge of the page between a first and second page), enabling the triangle or compass tool spawns them at a static position (upper page half). The tool needs to moved by hand afterwards.

### Feature Description

Enabling the tool should consider the zoom and scroll viewport of the user to spawn it there.
Clicking the tool should place it in the middle of the screen.

### Alternative Solutions

Moving the tool by hand is not an option, because it causes some distraction to my younger students when I zoom/scroll for reasons that are not obvious to them.

### Additional Context

It would also help in situations where the user barely scratches the second page and the original spawn position is too low.
But this may interfere with the fact, that a tool can not be moved across pages (I see this as a bug btw.)

**Comment by rolandlo** [comment]
Fixed in the release branch by #6012
