### ISSUE TITLE
Undo/redo doesn't work any more for strokes added via a plugin

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#6015]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 24.10

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.4+dev

### libgtk Version

3.24.43

### Bug Description

When adding strokes via a plugin (`app.addStrokes`) undo doesn't undo the strokes. Git bisection showed that this is a regression from  #5350 (commit 399b10537b596998318f361bf0d610bfc67161fd)
@Febbe Can you see what is wrong?

### Expected Behaviour

Undo/redo works for elements added via a plugin.

### Steps to Reproduce

1. Unzip the contents of [StrokeTest.zip](https://github.com/user-attachments/files/17614175/StrokeTest.zip) into the plugins subfolder of the config folder.
2. Start xournalpp and use "Add a stroke" from the plugin menu. Observe the triangle and square get inserted.
3. Hit undo a couple of times. Observe that the two strokes are not undone (but they are on the stable version 1.2.4).

**Comment by Febbe** [comment]
I can take a close look later after work. But are you sure, that this is the causing issue? Git bisect sometimes has problems, when the source of a bug is not compilable or if it is in a different branch.

**Comment by tattsan** [comment]
I have saved all the binaries I have built so far and it seems to happen just after #5350.

**Comment by rolandlo** [comment]
> I can take a close look later after work. But are you sure, that this is the causing issue? Git bisect sometimes has problems, when the source of a bug is not compilable or if it is in a different branch.

Yes, I'm sure. The first commit of #5350 doesn't have this issue, the second commit does. I have built them both from a fresh build folder.

**Comment by Febbe** [comment]
> > I can take a close look later after work. But are you sure, that this is the causing issue? Git bisect sometimes has problems, when the source of a bug is not compilable or if it is in a different branch.
> 
> Yes, I'm sure. The first commit of #5350 doesn't have this issue, the second commit does. I have built them both from a fresh build folder.

I think I found the culprit, there is a line missing in luapi_application.h:906. The stroke was added to a strokes vector before and isn't anymore.

**Comment by rolandlo** [comment]
> > > I can take a close look later after work. But are you sure, that this is the causing issue? Git bisect sometimes has problems, when the source of a bug is not compilable or if it is in a different branch.
> > 
> > 
> > Yes, I'm sure. The first commit of #5350 doesn't have this issue, the second commit does. I have built them both from a fresh build folder.
> 
> I think I found the culprit, there is a line missing in luapi_application.h:906. The stroke was added to a strokes vector before and isn't anymore.

Good find. Undo works when adding back a line 
```C++        
strokes.push_back(stroke.get());
```
before `addStrokeHelper(L, std::move(stroke));`

However redo crashes the app then:
```term
[bt]: (0) inst/bin/xournalpp(+0xfd283) [0x615b5a9ec283]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x45250) [0x7d05df645250]
[bt]: (2) inst/bin/xournalpp(_ZNK7Element16getElementHeightEv+0x4) [0x615b5aa738d4]
[bt]: (3) inst/bin/xournalpp(_ZN16LegacyRedrawable15rerenderElementEP7Element+0x21) [0x615b5ab77e11]
[bt]: (4) inst/bin/xournalpp(_ZN11PageHandler18fireElementChangedEP7Element+0x4d) [0x615b5aa794dd]
[bt]: (5) inst/bin/xournalpp(_ZN17InsertsUndoAction4redoEP7Control+0xb0) [0x615b5aa8ade0]
[bt]: (6) inst/bin/xournalpp(_ZN15UndoRedoHandler4redoEv+0x97) [0x615b5aa8ced7]
[bt]: (7) inst/bin/xournalpp(_ZN18UndoRedoController4redoEP7Control+0x77) [0x615b5ab63df7]
```

**Comment by rolandlo** [comment]
> > > > I can take a close look later after work. But are you sure, that this is the causing issue? Git bisect sometimes has problems, when the source of a bug is not compilable or if it is in a different branch.
> > > 
> > > 
> > > Yes, I'm sure. The first commit of #5350 doesn't have this issue, the second commit does. I have built them both from a fresh build folder.
> > 
> > 
> > I think I found the culprit, there is a line missing in luapi_application.h:906. The stroke was added to a strokes vector before and isn't anymore.
> 
> Good find. Undo works when adding back a line
> 
> ```c++
> strokes.push_back(stroke.get());
> ```
> 
> before `addStrokeHelper(L, std::move(stroke));`
> 
> However redo crashes the app then:
> 
> ```
> [bt]: (0) inst/bin/xournalpp(+0xfd283) [0x615b5a9ec283]
> [bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x45250) [0x7d05df645250]
> [bt]: (2) inst/bin/xournalpp(_ZNK7Element16getElementHeightEv+0x4) [0x615b5aa738d4]
> [bt]: (3) inst/bin/xournalpp(_ZN16LegacyRedrawable15rerenderElementEP7Element+0x21) [0x615b5ab77e11]
> [bt]: (4) inst/bin/xournalpp(_ZN11PageHandler18fireElementChangedEP7Element+0x4d) [0x615b5aa794dd]
> [bt]: (5) inst/bin/xournalpp(_ZN17InsertsUndoAction4redoEP7Control+0xb0) [0x615b5aa8ade0]
> [bt]: (6) inst/bin/xournalpp(_ZN15UndoRedoHandler4redoEv+0x97) [0x615b5aa8ced7]
> [bt]: (7) inst/bin/xournalpp(_ZN18UndoRedoController4redoEP7Control+0x77) [0x615b5ab63df7]
> ```

The redo crash is a regression from a different commit/PR. Adding the line above to  399b105 works fine.
