### ISSUE TITLE
Please add basic support for "select text" from pdf file. So user can copy the text out.

### ISSUE THREAD

**Issue by flyingosprey** [xournalpp/xournalpp#6029]
### Is Your Feature Request Related to a Problem?

Currently, user cannot select and copy text in pdf file.

### Feature Description

Please add basic support for "select text" from pdf file. So user can copy the text out

### Alternative Solutions

Use other pdf reviewer. But I love this open source one.

**Comment by rolandlo** [comment]
You can already select and copy text from the PDF background. Just use the PDF selection tools. 
![Bildschirmfoto vom 2024-11-06 07-21-48](https://github.com/user-attachments/assets/8de6c4d5-2e57-4889-bf26-128cfed41732)
