### ISSUE TITLE
Reload background with different number of pages

### ISSUE THREAD

**Issue by tobiasBora** [xournalpp/xournalpp#6035]
### Operating System

Linux

### (Linux only) Distribution

Nixos

### (Linux only) Desktop Environment

KDE plasma

### (Linux Only) Display Server

Wayland

### Installation Method

nix

### Xournal++ Version

1.2.3

### libgtk Version

3.24.43

### Bug Description

I'm annotating a pdf that may grow in the future in number of pages. The problem right now is that if I change the pdf later (e.g. add one page), and open it again in xournal, then only the first page (of the new document) will be displayed.

### Expected Behaviour

I would expect a new page to appear, or at least a menu that would allow me to reload the document.

### Steps to Reproduce

1. Create a 1 page document, open/edit/save in xournalpp
2. Close xournalpp, add one page to pdf, open again in xournalpp
3. The new page does not appear.

**Comment by rolandlo** [comment]
Use menu `Journal > Append new PDF pages` after reloading the document.

**Comment by tobiasBora** [comment]
Oh, good point, thanks a lot! Sorry for the noise.
