### ISSUE TITLE
Make uninstall forgets some folders

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#604]
I don't know if this is an issue, but when executing `sudo make uninstall` there is a thing:
if Xournal++ has been installed with `sudo make install`, the uninstaller leaves `/usr/local/share/xournalpp` directory and the empty directories inside it. Not a problem nor a high priority bug, but I think this could be easily fixed

**Comment by andreasb242** [comment]
Yes, it's not a bug, it's a feature ;-)
I don't find it in the documentation now, but it's documented like this, they don't delete on uninstall. I also noticed that. I'm not sure how hard it is to delete the empty folder, there are some entries on stackoverflow.

**Comment by luco5826** [comment]
Fantastic! Good to know it!
