### ISSUE TITLE
need support apple m4 cpu

### ISSUE THREAD

**Issue by Niko-1118** [xournalpp/xournalpp#6042]
### Feature Description

Thank you author,  need a version that supports Apple m4 chip, please

**Comment by rolandlo** [comment]
Does the MacOS ARM version of the 1.2.4 release not run on a M4? If so, what is the problem? Can you provide an errorlog?

**Comment by Niko-1118** [comment]
> ?

When I open the dmg file, it says "Xournal++" is damaged and cannot be opened. You should eject the disk image.

**Comment by rolandlo** [comment]
Did you read the release notes?
![Bildschirmfoto vom 2024-11-10 06-52-07](https://github.com/user-attachments/assets/c66bafc1-79ba-4896-abc9-b764ff93ec12)

**Comment by rolandlo** [comment]
Maybe you need to remove the quarantine status of Xournal++.dmg

**Comment by Niko-1118** [comment]
> Did you read the release notes? ![Bildschirmfoto vom 2024-11-10 06-52-07](https://private-user-images.githubusercontent.com/40485433/384664039-c66bafc1-79ba-4896-abc9-b764ff93ec12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTg1NTksIm5iZiI6MTczMTIxODI1OSwicGF0aCI6Ii80MDQ4NTQzMy8zODQ2NjQwMzktYzY2YmFmYzEtNzliYS00ODk2LWFiYzktYjc2NGZmOTNlYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA1NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzg2YWI0YjlmMzQ2Yzk4N2ZhY2YxZGFjOGI1OWQ1ZDdmODc0ZTZkZjk3NGRhZDAwNzY5MGE3MTgxNTM4YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KTu5xKuYltZa7avnXen1RZHuNzIGl4Kg8IosvT_0SHk)

Sorry, I didn't see this, it works now, thank you very much
