### ISSUE TITLE
CI create-installers does not start

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#6044]
Typing \action create-installers does not do anything for me, although author_association is set to member for my messages.

@rolandlo Have you tried in a PR? It may work for people with owner status?

**Comment by rolandlo** [comment]
> Typing \action create-installers does not do anything for me, although author_association is set to member for my messages.
> 
> @rolandlo Have you tried in a PR? It may work for people with owner status?

In #6038 it works for me.
