### ISSUE TITLE
Tochscreen, Two Finger Zoom, Zoom not linear, Zooming makes me jump to page 2, "Programm not Responding" Message afterwards. 

### ISSUE THREAD

**Issue by Programmer-Domi** [xournalpp/xournalpp#6050]
### Operating System

Linux

### (Linux only) Distribution

Pop OS

### (Linux only) Desktop Environment

GNOME?? Maybe. 

### (Linux Only) Display Server

X.Org

### Installation Method

sudo apt commands over terminal

### Xournal++ Version

1.2.4

### libgtk Version

3.24.43

### Bug Description

I use Xournal++ in combination with a touchscreen (finger inputs) and a touchpen (for writing notes and stuff). 
When I put in a picture (I want to annotate stuff on this picture), I need to zoom closer to the picture. And for this I use  two fingers on my touchscreen. 

I expect that when I zoom in with my fingers, the zoom is linear and I can navigate to the point where I want to make a 
touchpen annotation. 

However, when I start zooming (I want to zoom on page 13 for example), the zooming stops and I get shot to page 1 or 2. 
And on page 1 or 2 I am like zoomed in extremely deep. 

The example with the picture is just that you can understand my use case. The zooming fail also happens when I 
zoom into other annotations and stuff. 

### Expected Behaviour

What I expect:
When I am on page 12 and use my fingers to zoom on this page. I expect that it zooms linear into this page. 
Not throw me on page 2/3 and zoom in at its maximum...and give me a "Xournal++ not responding" message. 

Basically I want to zoom like on "state of the art" software like "Drawboard PDF" or every other PDF/Handwriting Editor. 

### Steps to Reproduce

1. Step --> Make some pages for example 12
2. Step --> Insert a picture on page 12
3. Step --> Try to zoom into this picture (with two fingers on the touchscreen)
4. Step --> Zoom with your fingers and enjoy getting catapulted onto page 2 with extremely deep zoom

### Additional Context

I read about this problem, maybe not exactly this problem, but it also was about zooming on touchscreen. 
I read something about the "GTK" Option and maybe this would fix it. 

There is the enable and disable "GTK" Option under "Tochscreen" in Settings. 

I tried both, but the problem consisted ;(

https://github.com/user-attachments/assets/91555cb6-c061-4d80-8550-06fe1bb237f5

**Comment by Programmer-Domi** [comment]
https://github.com/user-attachments/assets/fa039bf1-4f88-444e-a0ac-7f5e2fbf4fd6

This should be the whole 50 seconds video.

**Comment by Programmer-Domi** [comment]
[Kooha-2024-11-10-22-35-22.webm](https://github.com/user-attachments/assets/1a6c04f3-f731-4124-93ce-e1428b9a185c)

Dont know why the other video is only 1 second long.

**Comment by rolandlo** [comment]
With the GTK option do you mean this one?
![Bildschirmfoto vom 2024-11-10 22-49-14](https://github.com/user-attachments/assets/9e2f3e51-d73f-4e8f-8e7c-cb7a199322df)

**Comment by Programmer-Domi** [comment]
Jeah exactly, I tried in enabled mode and also disabled mode. 

But bug is still there.

**Comment by rolandlo** [comment]
I can't reproduce on Ubuntu 24.10 (with Wayland). Can you try to go into a Wayland session? It seems to me that X11 has degraded quite a bit with respect to touch input.

**Comment by Programmer-Domi** [comment]
I started my Pop OS Wayland today. The zooming problem was fixed, I no longer had the issue. 

When switching back to non-Wayland version Xournal++ had the old zooming problem. 

But on wayland it worked great ;-)
