### ISSUE TITLE
Missing accelerators for Zoom in and Out on master

### ISSUE THREAD

**Issue by aphelei** [xournalpp/xournalpp#6072]
### Is Your Feature Request Related to a Problem?

No

### Feature Description

I'm used to use CTRL + KP_ADD (zoom in) and CTRL + KP_SUBSTRACT (zoom out). Is that possible to add those ? 

these keys are in the keypad

### Alternative Solutions

also add CTRL + = to zoom in

browser (firefox) does it

### Additional Context

I know "CTRL +" and "CTRL -" are already implemented but in my layout, to zoom in I need to press CTRL + shift + "=" in order to zoom in and it's not really intuitive. 

It's a little feature but it would be really handy

Thanks !

**Comment by soufhehe** [comment]
related : #5373 and #2756

**Comment by soufhehe** [comment]
It works. Thank you !

I was using latest git (version below). Is it normal that it doesn't work ? 
![image](https://github.com/user-attachments/assets/ecfd5fb6-d7da-4893-b591-adda64dc73af)
