### ISSUE TITLE
new page is not according to my 'page template', always same as current page though option is not selected

### ISSUE THREAD

**Issue by MiltonBalaOfficial** [xournalpp/xournalpp#6108]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official (nightly)

### Xournal++ Version

xournalpp-1.2.4+dev-nightly.20241127-windows.zip

### libgtk Version

3.24.43

### Bug Description

new pages are as the current page not as the template page though copy current page is not selected

### Expected Behaviour

new pages as page template

### Steps to Reproduce

open any pdf file or any file
set page template different from the current one
add new page

**Comment by MiltonBalaOfficial** [comment]
![image](https://github.com/user-attachments/assets/bad42132-4e2c-4e64-ad5d-8464e202719b)
How should be the new pages if I add a page at this setting?

**Comment by Chrisimx** [comment]
> It was introduced by #4562 (I tested [426aaa1](https://github.com/xournalpp/xournalpp/commit/426aaa1e67287e9f2061f7d6fb1b46d0c8b1b76e) which is not affected). @Chrisimx could you have a look? To be honest, I am not sure how to fix this and how to have the two features coexist peacefully.

@bhennion My mental model on how it should work is the following:

- The settings from the "Configure page template"-dialogue specify what page size and background is used when you create a new document in Xournal++ or when you open Xournal++. This already works, as far as I can tell.

- It should also specify the default settings for new pages when you start up Xournal++. (e.g. if the "copy current page size" is set in the page template settings this should also be the initial setting in the popover and when you click the new page button). This also seems to work.

- Finally, when you change the settings in the "Configure page template"-dialogue these changes should also be reflected in the "new page"-popover. These settings should now be used for new pages until you change it to something else in the popover or in the "Configure page template"-dialogue.
This feature doesn't work reliably. While the changes are actually reflected in the popover (e.g. if you change the background setting in the "Configure page template"-dialogue the background is also set to this in the popover), these settings are not used. This means it's saying for example "A4" in the popover after I set it to this value using the  "Configure page template"-dialogue but when I click on the "new page"-button the page is for instance A5 while it obviously should create an A4-sized page.

I will take a closer look in the following days but I think it is possible to have no unexpected interference between the two features if we implement it with this mental model and fix the bug with the final point.
