### ISSUE TITLE
Latek do not work

### ISSUE THREAD

**Issue by ankiman1** [xournalpp/xournalpp#6109]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release

### Xournal++ Version

1.2.4

### libgtk Version

3.24.43

### Bug Description

Probably is my fault but when i try to write a formula with latek tool even if I write the code and then click "ok" the output is a trasparent image without anything. This is my global template 
[teX_xournal.zip](https://github.com/user-attachments/files/17966858/teX_xournal.zip)
probably i have made a mistake in the file, what i have to write in the global file? 

### Expected Behaviour

.

### Steps to Reproduce

1. click insert new latek formula 
2. type the code in the box that appear
3. waiting few seconds
4. click "OK" 
5. see an object that is transparent and noting is written no formula (nothing)
6. i can select and move the object in the document

**Comment by tattsan** [comment]
When creating a LaTeX template, copy default_template.tex and add the necessary packages. If you do not know what you are doing, please do not delete anything from default_template.tex.

**Comment by ankiman1** [comment]
ok, now I **used the default_template.tex** ( and i have not change anything)  but this appear: 
![image](https://github.com/user-attachments/assets/e19ab6c9-5541-4fa5-ac72-05fe3470760d)

and if a click install appear other 8-10 times the samewindow with other package name to install

**Comment by tattsan** [comment]
Please check whether you can compile your LaTeX source file directly.

* Copy  default_template.tex to test.tex
* Replace `%%XPP_TEXT_COLOR%%` with `0000ff`  (or another RGB value expressed in hexadecimal)
* Replace `%%XPP_TOOL_INPUT%%` with some math formula, such as `x^2`.
* Compile the file with `pdflatex`.

You can also try `legacy_template.tex` which doesn't require `scontents` package.

**Comment by ankiman1** [comment]
if i try to compile the program ( even if I use legacy_template.tex) those windows appear.

**Comment by tattsan** [comment]
The file created by replacing `%%XPP_TOOL_INPUT%%` or other means is not a template file.
Template file should contain `%%XPP_TOOL_INPUT%%`  or so.

**Comment by tattsan** [comment]
Why don't you try it before asking questions?

**Comment by ankiman1** [comment]
i do. i used the template  that i modify and happens the error (this:
![image](https://github.com/user-attachments/assets/4ad1caf7-160c-45a6-85a0-089d6bc45914))
