### ISSUE TITLE
Xournal++ Highlight colors very light/washed-out; despite using same color code as Evince which is brighter

### ISSUE THREAD

**Issue by kiers** [xournalpp/xournalpp#6149]
### Discussed in https://github.com/xournalpp/xournalpp/discussions/6148

<div type='discussions-op-text'>

<sup>Originally posted by **kiers** December  8, 2024</sup>
I like Xournal++ annotations MUCH better than Evince's;
However,  plugging the bright yellow custom color code "#FFFF00", only produces washed out highlight colors.  
Whereas, Evince's "#FFFF00" is vivid bright yellow.  The Xournal++ yellow can barely stand out if you squint.
What's up?</div>

**Comment by kiers** [comment]
Yes the 2 shades above describe it exactly.  Thank you;
SO, i go to ==>tools==>highlighter options==>"fill opacity=100?"
xournal++ is only showing 6 hex digits for its color space,  ARGB has 8, so the opacity sets alpha universally?

**Comment by kiers** [comment]
Another curious thing about the inconsistent opacity in highlights....I dunno if anyone has noticed, Xournal++  appears to automatically choose a "high opacity ~100%" for highlighting with highlighter, but choosing the box option, but then automatically does highlighting at "very low opacity ~10%" for highlighting with "select linear PDF text" option of highlighter.  So that's two different uses of "highlighting" with different options, that default to two different opacities. (Those of us with weak eyes would like 100% opacity as the default, as you may have guessed for my case)

Also, Opening a pdf already highlighted with Evince (v42.3) in Xournal++ to add say a text annotation, and then re-exporting that as a pdf, strips all the original Evince highlights from the xournal doc, leaving ONLY the Xournal++ annotations in place.  I thought both Evince and Xournal highlights worked on the same layer? That this highlight layer were commonly accessible to each other?  Because opening an Evince highlighted doc in xournal does SHOW the evince highlights, but chooses to ignore them when exporting to pdf!

Thanks.

**Comment by ElectricBoot** [comment]
Why this issue was closed? This is the only reason preventing me from switching to xournalpp completely for my PDF annotating needs (currently I have to use okular + xournalpp in combination). The highlight annotations feel way tool light.
