### ISSUE TITLE
New macOS-ARM64.dmg version is "damaged and should be moved to trash" as reported by my M2 when trying to launch.

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#6172]
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

dmg file launched, then dragged Xournal++.app to /Applications

### Xournal++ Version

1.2.5 and 1.2.5+dev

### libgtk Version

can't even launch the program

### Bug Description

MacOS reports Xournal++.app as damaged or corrupted and won't let it run on Mac M2 and Mac M4. Running macOS-X64 version (using Rosetta) works fine...

### Expected Behaviour

It should launch without errors

### Steps to Reproduce

1. download
2. double-click dmg
3. drag Xournal++.app to /Applications
4. launch
5. Kaboom!  Window pops up saying "Xournal++.app" is damaged and can't be opened. You should move it to the Trash."

**Comment by lcalder** [comment]
BTW, thanks so much for finally working on an ARM version of this excellent piece of software!

**Comment by rolandlo** [comment]
As mentioned in the 1.2.5 release notes after dragging Xournal++.app to /Applications you must run
```term
xattr -c /Applications/Xournal++.app
```
to remove quarantine status. On MacOS Intel this is not required somehow.

**Comment by lcalder** [comment]
Thanks so much for the reply. This is really great!

**Comment by lcalder** [comment]
Using the xattr -c command corrects the problem. Thanks so much.
