### ISSUE TITLE
AUR package file conflict with xournal

### ISSUE THREAD

**Issue by piegamesde** [xournalpp/xournalpp#633]
I have xournal installed and tried to install xournalpp:

    error: failed to commit transaction (conflicting files)
    xournalpp-git: /usr/share/icons/hicolor/scalable/mimetypes/application-x-xoj.svg exists in filesystem (owned by xournal)
    xournalpp-git: /usr/share/mime/packages/xournal.xml exists in filesystem (owned by xournal)
    xournalpp-git: /usr/share/mimelnk/application/x-xoj.desktop exists in filesystem (owned by xournal)

**Comment by andreasb242** [comment]
Ok, we have to rename this file.

**Comment by andreasb242** [comment]
https://github.com/andreasb242/xournalpp/tree/naminig-conflicts

Now open .xoj files does not work anymore.
@morrolinux / @luco5826
Any hint?

**Comment by morrolinux** [comment]
@andreasb242 Sorry, what do you mean by that? The file do not open with xournalpp by double-clicking it from desktop / the xoj files does not open from inside xournalpp -> open / what else?

**Comment by andreasb242** [comment]
I changed the names, as this would solve the issue, but now .xoj files are not associated anymore with Xournal++. No Icon, no double click, no Preview.

**Comment by andreasb242** [comment]
If all entries are renamed it's working.
@piegamesde Please recheck. Reopen the Ticket if not working. Thank you.

**Comment by andreasb242** [comment]
I clicked the wrong button - close again...
