### ISSUE TITLE
Rotating Images not working

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#644]
Rotating is displayed for images, but not working.
In my opinion rotating of images is not needed for Xournal++, and simple should be disabled.

**Comment by morrolinux** [comment]
it's a feature I would use if it was present. 
I have a few ideas on how to implement this, I just need some time to try some implementations (soon, but not too soon)

**Comment by andreasb242** [comment]
@morrolinux You can do this any time, for now I disabled rotation if there is something else than stroken selected.
