### ISSUE TITLE
Exported PDF in Windows

### ISSUE THREAD

**Issue by K0ertis** [xournalpp/xournalpp#65]
If I open a exported PDF in Windows it won't open and causes errors.

**Comment by MarPiRK** [comment]
There have been some small improvements in PDF export system since May 2014 (I remember I had some problems with PDFs before and after changes they disappeared).

**Comment by wbrenna** [comment]
If I recall right this was a buildsystem specific problem, not something I could replicate. Hopefully the PDF improvements + the buildsystem improvements made things more standard and this is fixed now. If not I'll reopen and investigate further!
