### ISSUE TITLE
Pen Tips

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#67]
From xournal-dev mailing list. Different pen styles would be nice.

**Comment by andreasb242** [comment]
Like in gimp, you have a normal pen which is round, or some other pattern? Or what do you mean with different pen styles?

**Comment by wbrenna** [comment]
I should have added the details rather than referring to the list. The tips requested were:
 - more pen/highlighter shapes (chisel)
 - slanted tip pens (calligraphy)

**Comment by andreasb242** [comment]
I close this because of age, and nobody was interested in it...
