### ISSUE TITLE
Mac .app Packaging

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#676]
Xournal++ should be packaged as .app for macOS.

folder "mac-build" contains the current progress.
The Icons are currently not packed, but the current issue is gdk-pixbuf libraries, and loader.cache.
Currently not sure how to solve this, for windows there is also a relative loading implemented, not sure if this is active on the homebrew implementation.

See:
https://github.com/GNOME/gdk-pixbuf/blob/master/gdk-pixbuf/queryloaders.c
get_toplevel (void)

My current idea from here:
https://github.com/Homebrew/homebrew-core/issues/5482
>brew reinstall gdk-pixbuf --build-from-source

Rebuild with some debug printfs.

If anybody with a mac will try / help: Please write a comment to this issue.

**Comment by andreasb242** [comment]
GTK Stuff, theming etc. may be usefull:
https://balintreczey.hu/blog/beautiful-wireshark-on-os-x-using-homebrew-and-gtk3quartz/

**Comment by andreasb242** [comment]
Working.

**Comment by luzpaz** [comment]
Was xournalapp ever submitted to homebrew?

**Comment by andreasb242** [comment]
No. Feel free to help!
