### ISSUE TITLE
Different icons for dark-themed DE

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#677]
Hi!
I thought that some modifications to the icon pack could be nice!
I personally use a dark themed DE and some icons like the Arrow Tool, or any other black-iconed tool are really hard to see. So I thought we could add a "brighter" variant in order to solve this. I can work on it, even on the graphic side, but i still have to see how to implement it in the code, maybe adding a Setting entry? Like a CheckBox which enables it at next startup?

**Comment by andreasb242** [comment]
For sure.
@morrolinux also would change the Icons.

And on macOS, it looks horrible, not the Icons, manly the GTK Style.
Can you check, if we may use the GTK Mechanism, and then also have the option to switch the GTK Style. And may detect, if there is a dark style, automatically switch to the dark style?

Gimp does support it, so it is possible.

**Comment by andreasb242** [comment]
For mac theming is a solution. You may simple create a subfolder for new icons, and load them if configured in the settings.

**Comment by luco5826** [comment]
@andreasb242 Yeah! That's exactly what I was thinking about!
