### ISSUE TITLE
ubuntu: touch screen not drawing

### ISSUE THREAD

**Issue by gregdymek** [xournalpp/xournalpp#683]
drawing not working on the touchscreen, it's scrolling instead, normal xournal is working ok however icons are too small on uhd screen

**Comment by gregdymek** [comment]
I'm using hp spectre x360

**Comment by andreasb242** [comment]
But your tablet has also pen input, right? And this does drawing?

Xournal is still on GTK2, Xournal++ is on GTK3, and the GTK3 Scrolled Container automatically takes the Touch event for Scrolling. The Xournal Widget only gets an event where you touch ("click"), but not the dragging. And this is not an option, this is hardcoded in GTK3.

I already noticed this (it's the same behavoir on all devices), and I already tried to make this configurable.
So you need a really good reason, why you would use the touch for drawing, else I probably wont spend time to this.

**Comment by Stiffy2000** [comment]
Many people could be using a tablet + Xournal++ to do notes and the like.
Maybe if there is another touch handler we can use?

**Comment by andreasb242** [comment]
We can remove the scrolled panel and to it ourselv, with this we remove all standard scrolling stuff. We had this before. And then let the user select.

**Comment by morrolinux** [comment]
@andreasb242 I have to say that after the last X11 update my tablet's stylus gets (erroneously) detected as a touchscreen device (by x11, not a xournal++ bug). With the actual status I can configure it under the "Input" section of xournal, but cannot use it to write because of this.
I think indeed that could be useful to let the user pick one "touchscreen" device from the "Input" tab, and handle it manually.
would this be possible?

**Comment by andreasb242** [comment]
@morrolinux We can do this, but this also means to disable all gestures, and it wont fix your issue, because on the Touschreen no pressure is provided.

**Comment by morrolinux** [comment]
Umh I see... wouldn't be too much of a problem for pen pressure as I always disable this (me personally of course) but with no gestures.. yeah.. it would have been useful if it was possible to do it just "per-device"

**Comment by andreasb242** [comment]
If it would be work, it may also solves #404 if enabled.

**Comment by andreasb242** [comment]
By the way, it's working on Windows, at least on the cheap chinese 7" Tablets...

**Comment by andreasb242** [comment]
It's already planed. I'll hope I'll can fix this soon.

**Comment by andreasb242** [comment]
Technical I removed the GTK Scroll handling, therefore removed the full Touch scrolling, Scroll wheel, Scrollbars etc.
I added Scrollbar so scrolling is possible, but it's not finished for sure, so use with care.

You have to manual enable it, and please give feedback.
Currently there are really much issues open, therefor I close this, and try to solve others. (There will be new tickets for the new bugs in short I think...)


![grafik](https://user-images.githubusercontent.com/822958/51493876-f8fb8f80-1db6-11e9-841c-fb245d7c74c2.png)

**Comment by parkerlreed** [comment]
Working great here on a touch only Razer Stealth.

**Comment by sammdu** [comment]
I found that disabling pressure sensitivity fixes the issue. Maybe my touchscreen reports a low pressure by default.

**Comment by Technius** [comment]
Hi everyone, I think I may have figured out a way for touch screen drawing to work without the "Touch Workaround." Can someone try [opening the GTK inspector](https://blog.gtk.org/2017/04/05/the-gtk-inspector/) and copy what I do in the following gif (with a real touchscreen instead of simulated touchscreen) to see if touch works correctly without the "Touch Workaround"? 
![xpp_touch_scrolling](https://user-images.githubusercontent.com/1066652/72675390-e8b4d980-3a37-11ea-9013-266bc30230cb.gif)

**Comment by sammdu** [comment]
@Technius No I don't think so.   
Dell XPS 15 9570 Touchscreen, Ubuntu 18.04 

I openned the GTK Inspector, `Objects`, Inspected the canvas, switched to tree view, selected `GtkScrolledWindow`, changed `kinetic-scrolling` to `FALSE`, and the result is the canvas stopped scrolling, but no ink traces were produced either. I made sure I'm in pencil mode, and _not_ accidentally in eraser.   

If it helps, Firefox does not support touch scrolling with my setup, but Chromium does! If you can investigate their implementation differences that might help with Xournal++ as well.

**Comment by sammdu** [comment]
> @Technius No I don't think so.
> Dell XPS 15 9570 Touchscreen, Ubuntu 18.04
> 
> I openned the GTK Inspector, `Objects`, Inspected the canvas, switched to tree view, selected `GtkScrolledWindow`, changed `kinetic-scrolling` to `FALSE`, and the result is the canvas stopped scrolling, but no ink traces were produced either. I made sure I'm in pencil mode, and _not_ accidentally in eraser.
> 
> If it helps, Firefox does not support touch scrolling with my setup, but Chromium does! If you can investigate their implementation differences that might help with Xournal++ as well.

Or to be honest, I think the workaround mode right now works pretty well, and if you can support scrolling with 2 fingers via touch (so 1 finger == ink, 2 fingers == scroll), then pinch zoom via touch, it would be perfect.

**Comment by parkerlreed** [comment]
Where is this setting on 1.0.17? The Preferences page looks completely different with tabs on the left instead of the top. I don't see any option resembling that GTK touch setting.

**Comment by parkerlreed** [comment]
I found it... Through the magic of GTK hiding scrollbars on timeout it was hiding from me.

![image](https://user-images.githubusercontent.com/841440/77865602-364e7f00-71fd-11ea-823b-0458d95405e3.png)

![image](https://user-images.githubusercontent.com/841440/77865612-41091400-71fd-11ea-898c-54cb923fa4bf.png)

**Comment by enricoar** [comment]
So I understand if you want to be able to draw with a finger, you need to select the GTK  workaround, but then there is no way to scroll neither with a mouse wheel, nor with the hand tool, only with the scrollbar. And also this doesn't seem to work correctly. So indeed it is inconvenient for tablets or for electronic whiteboards.

**Comment by Technius** [comment]
The finger drawing code is coupled to the GTK workaround, but it can actually be refactored to be independent. We have plans to remove the GTK workaround (it's causing more trouble than it's worth) while retaining the ability to touch-draw.

**Comment by enricoar** [comment]
Thanks a lot Technius for the quick answer! And thanks a lot for the awsome Xournalpp
