### ISSUE TITLE
Dots appear randomly

### ISSUE THREAD

**Issue by DuendeInexistente** [xournalpp/xournalpp#684]
I encircled one in red to make it more clear
![image](https://user-images.githubusercontent.com/20157727/50667119-a3417d80-0f96-11e9-8b6f-13864f5155fb.png)

These dots appear constantly, and without printing any error to the terminal, so I don't have any idea of why might this be happening.
My tablet is a Wacom Intuos, and I compiled xournal from source in ubuntu 17.10 64 bits. [This](https://files.catbox.moe/p1tsm9.7z) is the compiled binary, in case its useful.

**Comment by andreasb242** [comment]
The Binary brings nothing, but can you upload this .xopp file?
I can see if the point contains pressure or not, if not the point is created with touch / mouse.
if the point contains pressure, it is created from pen device.
By the way: You can delete everything which is on the page EXCEPT the point, save it as a new file, unzip it (witz gui or) gunzip file.xopp and then you have a plain .xml, only the <page></page> part is from interest.
But you can also share the whole file, but you have to compress it as .zip, else github don't support it.

**Comment by peetCreative** [comment]
I found out, when you change tools finger to pen. It paints the last position of the finger.

**Comment by andreasb242** [comment]
@peetCreative How did you change, with touch / pen / mouse?
Do you have Wayland or X11?

I couldn't reproduce it with the mouse on X11

But I already guess what it is, the new input handling which handle input by device.

**Comment by DuendeInexistente** [comment]
Oh, right, the dot is:
````xml
<background type="solid" color="#ffffffff" style="lined"/>
<layer>
<stroke tool="pen" ts="0" fn="" color="#3333ccff" width="2.26">277.97 785.38 277.97 785.38</stroke>
</layer>
````
And the whole file is [2019-01-03-Note-20-15.xopp.zip](https://github.com/xournalpp/xournalpp/files/2729536/2019-01-03-Note-20-15.xopp.zip) , just in case.
In case it helps I haven't a touch-enabled system, though, just a tablet and mouse.

**Comment by andreasb242** [comment]
Two input devices, I have to try to reproduce, as @peetCreative already wrote: I have to change the tool, and probably use the pen before or so.

@DuendeInexistente Do you use wayland or X11?

**Comment by DuendeInexistente** [comment]
X11

**Comment by DuendeInexistente** [comment]
> Two input devices, I have to try to reproduce, as @peetCreative already wrote: I have to change the tool, and probably use the pen before or so.
> 
> @DuendeInexistente Do you use wayland or X11?

X11

**Comment by andreasb242** [comment]
@DuendeInexistente Please recheck. If it happens again, reopen the ticket.

But I'm really sure it was this code, because:
>width="2.26"

There is no pressure saved, so it's not a normal pen drawing.
And I hope you would know if you would draw some points with your mouse :-)

>277.97 785.38
>277.97 785.38

Start and end is at the exact same position. This is not possible if you draw with the pen. So it was probably the changed code.

**Comment by Rmano** [comment]
Hi (back from holidays!) 

I'll check, but please notice that this is a very, very long-standing problem. It was (and still is) happening with the original `xournal`, too.

**Comment by andreasb242** [comment]
Haha :-) I'm probably right!
I wrote Xournal++ because Xournal is not really extensible, it's really hard to add new features.

But Xournal is working, and I also mentioned this in the About dialog, it's based on Xournal. I looked into the Xournal code, and found this:

```c
  if (ui.cur_path.num_points == 1) { // GnomeCanvas doesn't like num_points=1
    ui.cur_path.coords[2] = ui.cur_path.coords[0]+0.1;
    ui.cur_path.coords[3] = ui.cur_path.coords[1];
    ui.cur_path.num_points = 2;
    ui.cur_item->brush.variable_width = FALSE;
  }
```
This is exactly the same behavior. So I hope I found the correct part. This is a special case, which cannot be easy reproduced.

**Comment by andreasb242** [comment]
This bug is still there, and can easy be reproduce by Zoom gesture.

**Comment by oyren** [comment]
Same problem here.

**Comment by morrolinux** [comment]
Like I was pointing out here: https://github.com/xournalpp/xournalpp/issues/404#issuecomment-452787348
That's weird because according to @andreasb242 this should already be handled per-device?

**Comment by LittleHuba** [comment]
Seems like it is not GDK that is mixing something up but Xournal++ that processes the events twice. Once for zoom and another time to draw, using the currently selected tool.
I'll dig a little bit and try to find where the issue is.

**Comment by andreasb242** [comment]
Thank you for the analysis, I need to check the gesture handling...

**Comment by frohro** [comment]
For me, I still get dots when the "Enable Zoom Gestures" is turned off in the preferences.  Do you?

**Comment by Rmano** [comment]
Just tried again `xournal` this weekend. Random dots appears there too; more often when moving the pen and somehow touching the tablet to pan the canvas. So it's deeper I think --- it must be something very old if it's common to both applications.

**Comment by hensur** [comment]
I'm having the same problem on a Yoga 370. I don't think it's related to zoom at all for me. Also, I don't have this problem with xournal.

I'm not exactly sure how it happens, but I did some test drawings with my hand on the screen. The dots always appear when I lift the pen and let my hand stay on the screen. Never while drawing.
Seems to be related to disabling the touch device when the pen comes into proximity of the screen. Or more likely when it gets enabled again, after the pen is out of proximity.

**Comment by LittleHuba** [comment]
This would point to an easy fix:
Just filter all touch events south-east of the position of the pen.

**Comment by LittleHuba** [comment]
> This would point to an easy fix:
> Just filter all touch events south-east of the position of the pen.

Or south-west for left-handed people. It would be easier to just filter everything when the pen is within proximity

**Comment by andreasb242** [comment]
Proximity Events are not working on GTK3.
By the way, it does not happen on my Tablet while writing, it happens e.g. on Zooming, and I have the touch disable fix already enabled, and it is working, so for this case this would not work.

Technical currently only one input device is used at once, if there are more, the second will be ignored, you can easy test this with the pen and the mouse, they are not mixed anymore.
See InputSequence::checkCanStartInput

So this is not that easy...

**Comment by LittleHuba** [comment]
> I did some triaging of this bug.
> This is a result of the zoom gesture not taking into account that the two touch points my be from different devices.
> 
> You can reproduce it by doing the following steps:
> 
> 1. Put one finger onto the journal and keep it there
> 2. Put your pen onto the journal and keep it there
> 3. Now zooming is possible by moving either the finger or the pen or both
> 4. Put another finger onto the screen
> 5. Now you can draw using the second finger, while the pen does not draw but change zoom
> 
> Neither steps 3 or 5 should be possible.

Obviously that is not working correctly.

**Comment by LittleHuba** [comment]
As a workaround you can use the following script:
https://gist.github.com/LittleHuba/55f2d79dd59332e8ad6e60642e462c78

It's a simple hand-recognition using X11 that disables the touch device when the pen is in  proximity. You obviously need to change the names of the devices stored in the variables `stylusDevice` and `touchDevice`. You can use `xinput list devices` to get the appropriate names.

**Comment by andreasb242** [comment]
@LittleHuba You don't need this script, this is already supported with Xournal++!

![grafik](https://user-images.githubusercontent.com/822958/52178440-d8780000-27ce-11e9-8383-56733ac8e744.png)

**Comment by frohro** [comment]
Gentlemen, thanks for working on this.  
I found the script handy to test this, because it will tell you whenever the swap occurs, and for me the dots appear when the swap occurs.  I tried playing around with the timing, as mine was set at 0.5 seconds in Xournalpp and 0.2 seconds in the script.  I tried 1.5 seconds in both, and it was better, but the dots still annoyingly appear.  
Obviously we need better filters for them.  One thing I notice is that they seem to be always for me just perfect dots, not marks as I make with the pen.  That fact might be useful to filter them out.

Also, when I use the stylus (pen) I never want to mark on my canvas with my finger or using the touch.  I do use the touch to advance the scrolling.  Couldn't we just disable marking with touch, but let it move the page or activate the tools?

Rob

**Comment by andreasb242** [comment]
If touch is disabled for drawing in the settings, touch events are ignored for drawing now.

I HOPE this is fixed, if the bug still appears on the current master, please Reopen the bug!
I could not reproduce it now.

**Comment by frohro** [comment]
Hi andreasb242,
I am delighted to see your note!  I did a git pull and rebuilt xournalpp to test it out.  I expected the place to disable the touch to be under the "Touch" tab.  I think I found it under the "Input Device" tab, but for me I cannot disable touch using it.  See below:
```
`frohro@frohro-260:~/Projects/xournalpp/readme$ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=14	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech TrackPoint              	id=15	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen stylus	id=10	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen eraser	id=17	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Finger touch	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=13	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=16	[slave  keyboard (3)]
    ↳ C-Media Electronics Inc. ThinkPad OneLink Plus Dock Audio	id=11	[slave  keyboard (3)]
frohro@frohro-260:~/Projects/xournalpp/readme$ 
`
```
Note that the screen shot below does not have the touch device (id=9 from above) to disable.
![screenshot from 2019-02-11 10-50-48](https://user-images.githubusercontent.com/994565/52586007-3cac4c80-2deb-11e9-88f2-b2baa250d1eb.png)
Any ideas?
Thanks,
Rob

**Comment by andreasb242** [comment]
![grafik](https://user-images.githubusercontent.com/822958/52586378-ac482900-2e37-11e9-8578-f56eda81e68d.png)

I mean this checkbox needs to be unchecked. Sorry, the text was not clear / wrong.

**Comment by frohro** [comment]
Wow!  I unchecked the box, and the dots are gone!!!  I have to say, I don't think it is obvious to me anyway, that unchecking this box should do what I want, especially given that I can't find the finger touch device in the list.  However, if I select "No Device" and uncheck the box, the dots are gone for me!  We might want to think about how to make this more clear, so users get the best experience. 

Here is what I would expect.

- The option would be found under the "Touch" tab, similar to "Disable touch if pen is near screen."
- I would expect to select the finger touch, and select "Disable drawing for this device," by checking the box.

Thanks so much for fixing this annoying bug!
Rob

**Comment by andreasb242** [comment]
I did a change today, and yes, the settings here needs to be cleaned up and describe what they do.
But I got today a crash report which has something to do with this stuff... really complicated...

I removed the touch device already, because I thought that was the caus of crashes... But probably was not...

**Comment by LittleHuba** [comment]
The fix only solves the issue when the pen touches the screen first. If the finger is touching the screen prior to the pen there are still random dots.

**Comment by andreasb242** [comment]
@LittleHuba You set the wrong checkbox. (contact me if not yet clear)

By the way: I moved the checkbox now to the Touch tab.
@frohro checked it and it was working.
