### ISSUE TITLE
Provide a button for item deletion

### ISSUE THREAD

**Issue by bwurst** [xournalpp/xournalpp#686]
I found Xournal++ these days and I love it. I use it on a convertible notebook with pen input on the touch screen. Great experience so far!

What I really could not find is a convenient way to delete items. There is a select tool and one can move stuff around with the pen but for deletion of selected items, the keyboard is needed (or "Edit -> Delete"). I did not find a simple Toolbar button to delete the selected item, even not as an option in the customize dialog. It would be great if this could be added.

**Comment by andreasb242** [comment]
You have to customize the toolbar yourself, the button is not in the default toolbar. (I think the most user need mostly the eraser)

**Comment by bwurst** [comment]
Thanks a lot, I'll fetch an updated build in a few days!
