### ISSUE TITLE
Dash line

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#704]
Hi. Please add the option to choose dash line, dot line as in the program MrWriter https://unruhschuh.github.io/MrWriter/

**Comment by masac** [comment]
Thanks! When will this feature be used?

**Comment by andreasb242** [comment]
@masac Load / Save and the UI is not done yet.
If the weather stays bad, you can expect it next weekend ;-)

**Comment by masac** [comment]
Thanks!

**Comment by andreasb242** [comment]
Loading of a MrWrite document can import dotted lines
(still not completed, feature by feature, but there is a progress! ;-))

![grafik](https://user-images.githubusercontent.com/822958/50988446-e9ee2500-150c-11e9-8357-c99b7accaeb2.png)

**Comment by andreasb242** [comment]
Ah I forgot: I wrote @unruhschuh , and we decided to keep the file format as compatible as possible.
Xournal++ now allows to import the files from MrWriter, which are nearly identical as .xoj.

Dotted lines will be saved as MrWrite does, so it's compatible.
Therefore I also add the exact same line types. But if there are other line types requested, which makes sense, we will add it, even if MrWrite does not support it. We also added features which are not supported by Xournal, but currently we try to keep the Fileformat as compatible as possible, without limiting new features.

**Comment by andreasb242** [comment]
@masac It's working!
But there are a lot of UI Bugs, and therefore I won't add it now to the toolbar, you have to customize it.
The Toolbar does not show the correct icon, but you can select it. The line is only painted dotted after a few second on the first repaint.

Therefore I'll let this ticket open. But you can test it, with the limitations mentioned above.

**Comment by masac** [comment]
Thanks!
