### ISSUE TITLE
When pressure sensitivity is on, shape recognizer use always maximum width

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#713]
The title says all (see the attached GIF also). 
It would be much better is the shape could be painted with the average line width of the hand-made path.

![recorded](https://user-images.githubusercontent.com/6414907/50739139-40d9be80-11dc-11e9-8eb3-3b8727194223.gif)

**Comment by andreasb242** [comment]
Possible, but not sure if this really make sense. It's not much work, so we can try it.
We have to calculate the average pressure of the original object (which is anyway saved, for undoing) and then multiply it with the width.

**Comment by andreasb242** [comment]
Yes... Its working really good. Thank you @luco5826 !

![bildschirmfoto vom 2019-01-08 19-39-08](https://user-images.githubusercontent.com/822958/50851523-60f4b380-137d-11e9-9c35-bbfeb97b8ad1.png)
