### ISSUE TITLE
Undo lets go of selection

### ISSUE THREAD

**Issue by unruhschuh** [xournalpp/xournalpp#719]
1. Select something
2. move it at least twice
3. hit "undo"

The last move is undone, but the selection is let go. If the content overlaps with some other strokes, it might be impossible to reselect.

I'd suggest to either
a) undo all moves, such that the content is where it was selected
b) undo the last move and keep the content selected

Mac version 1.0.6

**Comment by andreasb242** [comment]
Libreoffice lets the selection as long as the object is not deleted or so, but if there is more undone, the last selection is not restored.

Technical we need to check after each undo / redo step is the element ist still selectable, or not on the document anymore. Stroke will not be deleted, it exists in the undo / redo stack.
