### ISSUE TITLE
Need a preference for setting up snap grid....

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#731]
I need a preference that would allow my snap grid to be the same as the background.  It seems like those points are a little more likely, but it would be nice to be able to have only those points possible.

**Comment by frohro** [comment]
Well, I found the number to change to make snap to grid work the way I want it.  The problem is that when you have snap to grid on it only snaps to the grid if you are very close to it.  I changed the "tolerance" variable on line 36 of src/control/RulerHandler.cpp from 2.5 to gridsize/2, and now it works the way I want, and snaps everywhere to the grid.  If i don't want it to always snap to grid, I turn it off.  :-)  It would be nice to have an adjustable grid size in units of the squares on the graph paper in the preferences though.

Rob

**Comment by morrolinux** [comment]
I'll take note of that, don't close the issue just yet :)

**Comment by frohro** [comment]
The epsilon parameter in ArrowHandler.cpp, line 63 is another one I would like to see in the preferences.  I prefer .25 rather than the 0.1 presently used.   You can hold the shift key if you don't want snap to rotation, or unclick the snap to rotation.

**Comment by morrolinux** [comment]
Closed with #754
