### ISSUE TITLE
Logarithmic ZoomSlider and percentage 

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#733]
I think it would make sense to make the ZoomSlider logarithmic so 1.0 is more in the middle. I have to think how to calculate it correctly.
Nother thing is to introduce an indicator which shows the percentage of the zoom. Just for viewing to the user.

**Comment by andreasb242** [comment]
What about a menu like evince has?

![grafik](https://user-images.githubusercontent.com/822958/51077858-5f442c00-16ac-11e9-9190-0dcab186257c.png)

It's logarithmic, more or less, maybe better readable, and probably also better to select with the pen.
I have to check, the Wacom Pen is not working that good at the corner of the screen, so such a menu would maybe better?

**Comment by peetCreative** [comment]
Yes, that looks good. I will do sth.
 I think  a scale like libre office is also good. with the slider snapping to 100%, fit
