### ISSUE TITLE
Some things don't nicely align with snap to grid.

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#738]
The graph and dotted background line up nicely with snap to grid, but not some other backgrounds, especially the graph with border.

**Comment by andreasb242** [comment]
Both are new features, and it take some time to bring it to 100%.

**Comment by Rmano** [comment]
Yes --- see here: snapping to the graph with border is quite difficult...
![snap](https://user-images.githubusercontent.com/6414907/55870855-c2e5d480-5b89-11e9-8097-8a97d00be957.gif)

**Comment by morrolinux** [comment]
I guess the simples way to sove this would be to make the "graph with border" to actually be aligned to the "graph" style. This happens because the border has an offset which slightly disalign the graph. should be easy to fix thoguh. I'll have to look at it

**Comment by morrolinux** [comment]
take a look at #1067

**Comment by Rmano** [comment]
#1067 fixes it for me.
