### ISSUE TITLE
Draw coordinate system doesn't snap to grid.

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#739]
You can draw a coordinate system with the line tool, or the arrow tool, so maybe this feature is redundant, but if it is there, it would be nice if it worked as well as the other tools.  :-)

Thanks to all the developers!  You have some major improvements over xournal.
Rob

**Comment by frohro** [comment]
The rectangle, the circle, and the coordinate system all lack this feature.  It is not so obvious unless you compile with the modification I made to the snap parameter, so it only snaps.   The arrow, thankfully has snap to angle, but not snap to grid.

**Comment by andreasb242** [comment]
>unless you compile with the modification I made to the snap parameter

If you do fixes you can create a pull request, and we can merge it.
Developers are always welcome. The rules are simple: it needs to make sense, and don't break anything ;-)

The Coordinate System was also a Pull Request from a contributor. I already notice, that this feature is not fully integrated, but I personally merge them, because it also can be the base for improvements.

**Comment by frohro** [comment]
Okay, I have snap to grid working for the square, the starting point of the arrow, (maybe I should do the end too).  I also fixed a bug with the square that it would only go up and to the left or down and to the right of the original point.  Shift to turn off snap to grid doesn't work with the rectangle because the shift was claimed to make a square.  It might be nice to change the key for one or the  other.  

I also need some directions on how you want me to do a pull request.  Right now I have these fixes committed to my local machine under a branch called frohro.

**Comment by frohro** [comment]
I further edited it until now on the arrow, if you have snap to grid selected, but only want one of the ends snapped you can free the other by holding the shift down.  It works with either end.  

I created a repository here: https://github.com/frohro/xournalpp  I'm not quite sure how to do a pull request, except for repos I  have write permission on.  You probably know this much better.  Let me know if I can help you get the code.

**Comment by frohro** [comment]
It is the frohro branch.

**Comment by morrolinux** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by morrolinux** [comment]
You probably need to fix your tab size though. It's not consistent with the actual code

**Comment by andreasb242** [comment]
Change the editor config to save Tabs instead of spaces. But the size (4) is correct.
