### ISSUE TITLE
When you copy an object from one layer to another it sometimes gets enlarged and moved.

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#740]
Steps to reproduce:

1. Create an object on layer 1.  (I used an arrow, or a line.)
2. Create a new layer.
3. Cut the object on layer 1.
4. Go to layer 2 and paste it.
I'm not sure what makes the difference, but sometimes it works as I would like, and is the same size and position.  It may be operator error.  :-)

**Comment by andreasb242** [comment]
It's still not reproducible for me. Therefor I close this issue now.

You are also a developer, therefor I hope you understand. You can reopen the ticket, if you find out how it's reproducible, or may fix it ;-)

Here was also nobody else, which wrote he has the same bug, as it was on other tickets. So it's probably a really special case...

**Comment by frohro** [comment]
Lately it has been working fine for me too, so I don't know either.
Rob
