### ISSUE TITLE
Circles would be nice to be drawn with the starting position as the center.

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#742]
Most CAD tools I'm familiar with draw circles using the point you click as the center.  The way it is, I find it hard to make the circles the way I want.

**Comment by frohro** [comment]
I'm closing this.  I've played with it more, and the way it is actually isn't bad.

**Comment by Photon89** [comment]
Is it possible to reopen this? For mathematical sketches it is frequently much better to use the center as starting point.

**Comment by LittleHuba** [comment]
Proposal: Introduce new tool that draws circles from the center outward

**Comment by JJones780** [comment]
WIP: Initial implementation done - see PR #1063

**Comment by Photon89** [comment]
Works very nicely, thank you!

**Comment by JJones780** [comment]
You're Welcome!
