### ISSUE TITLE
Add rotation to paste 

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#76]
Enhancement proposal:
It would be really handy  to have the possibility to rotate a selection when pasting. I understand that the thing is not easy, especially for text, but it would be great even if only for handwritten things. 
A possible interface is:

![kir1rck](https://f.cloud.github.com/assets/6414907/2284031/ddb8fb24-9fc4-11e3-9f6e-f21dcc7be7c0.png)

(Commented on original xournal, see https://sourceforge.net/p/xournal/feature-requests/44/ )

**Comment by morrolinux** [comment]
currently working on it in `stroke_rotation` branch. Any contribution is appreciated
