### ISSUE TITLE
Text tool doesn't let me type on MacOS/Windows

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#767]
Here's what happens: 
1. I choose text tool
2. Clicking on the page opens up the text box as usual 
3. When typing, the input are not registered within the textbox
 
I also noticed that the VIM navigation style switches "hjkl" are working in this phase. 
So my guess is that the "focus" is not being captured by the textbox but stays on the page

**Comment by morrolinux** [comment]
I've also noticed that "Return" and "Backspace" are being captured within the textbox as they should

**Comment by luco5826** [comment]
Hi @morrolinux ! 
I had problems with Text tool too some times ago, it was related to the GTK_IM_MODULE environment variable set to "xim" instead of something like "ibus", could you try checking your GTK_IM_MODULE value and/or running Xournal++ with 'GTK_IM_MODULE=ibus' parameter? 
Maybe it's somehow related!

**Comment by morrolinux** [comment]
Hi! 
The variable was not set. 
However, setting it doesn't seem to help

**Comment by andreasb242** [comment]
On my MacBook it's working. At least with an older build...

**Comment by Gabirel** [comment]
Same problem encountered in Windows 10. 

How can I solve this then?

**Comment by andreasb242** [comment]
Try to find out if this happen always, or only sometimes.
When it's working on my development Notebook, I cannot find the issue, so I need a hint.

**Comment by LittleHuba** [comment]
Maybe also the Windows version would be interesting as Microsoft is changing features continuously and creates as many bugs as it fixes...

**Comment by andreasb242** [comment]
Yes, but I think it was working on Windows and macOS for me, so I guess there is some pre requirement to get the error.

**Comment by LittleHuba** [comment]
The bug is at least resolved for Windows (#800). Closing this if there is no update within a week on the MacOS side.

**Comment by libphy** [comment]
The Text function doesn't work in Windows10. It doesn't type anything no matter what I do.

**Comment by Rmano** [comment]
Could be the same as issue #1769?

I solved it removing the configuration directory...

**Comment by Rmano** [comment]
@libphy  can you try to disable "new input system"? It fixes the text tool for me --- although I have again spurious dot in that case, I think. Still testing.

**Comment by guycohen** [comment]
When using the new input system, I also can't type using the text tool (on Ubuntu). This is true on older builds and on nightly.

**Comment by Rmano** [comment]
@guycohen for me the problem was the keyoboard+mouse combo. It is fixed in version 1.1.x... (see #1769)

**Comment by wolkenschieber** [comment]
Had the same issue. My keyboard was set to mouse in the input system preferences.

**Comment by ivsanro1** [comment]
Same issue here for xournalpp 1.1.1 installed using snap on Ubuntu 16

**Comment by rolandlo** [comment]
@ivsanro1 Please see #2573
