### ISSUE TITLE
Google summer of code - should we may try to find new developers?

### ISSUE THREAD

**Issue by andreasb242** [xournalpp/xournalpp#770]
The article is in German.
https://www.heise.de/developer/meldung/Summer-of-Code-Google-sucht-noch-Mentoren-4278222.html

The link to the google project is english:
https://summerofcode.withgoogle.com/

I only would start the discussion. I did not read all requirements and I don't know all details.

**Comment by morrolinux** [comment]
Might be a good idea. If we match the terms..

**Comment by ThoFrank** [comment]
Sounds interesting. I'm a student myself and would be interested in joining.

**Comment by andreasb242** [comment]
I filled out the form today. We may can do it :-)

**Comment by andreasb242** [comment]
I checked again, currently everythink OK, we probably get a result on the 26. Feb.

![grafik](https://user-images.githubusercontent.com/822958/52848644-85c40f80-310f-11e9-94df-21b69ae1ce43.png)

**Comment by andreasb242** [comment]
>Thank you for applying to be a Google Summer of Code 2019 mentor organization. Sadly, we were unable to accept Xournal++ this year. We had many more applications than available slots. We hope you will apply again in the future!
