### ISSUE TITLE
Mathtex is GPL-3.0 but xournalpp is GPL-2.0+

### ISSUE THREAD

**Issue by badshah400** [xournalpp/xournalpp#771]
It seems there may be a licensing issue here: most of xournalpp is licensed under GPL-2.0+, but mathtex is licensed as GPL-3.0+. SUSE's legal department [flagged this](https://build.opensuse.org/request/show/663047) as an issue:
```
declined the legal report with the following comment: GPL-3.0+ xournalpp-1.0.5/src/mathtex/mathtex.c
```

**Comment by andreasb242** [comment]
First: we don't link them together, they are fully independent, so the issue is only the packaging.
We should anyway remove it and use svg / pdf.

I may do this tomorrow, I don't know how much work it is, but this is a good reason.

**Comment by andreasb242** [comment]
GPL 3 has the issue with the key sharing, which makes it's nearly impossible e.g. to bring it to google play. So I would not change the license of Xournal++ to GPL3.

**Comment by andreasb242** [comment]
#375 will be solved together. I think the technical discussion should be made in the other ticket.

**Comment by badshah400** [comment]
@andreasb242 Great! Thanks for the quick response and fix. Will you be releasing a tagged version soon, or should we just go ahead and apply the PR as a patch?

**Comment by andreasb242** [comment]
@badshah400 Release is done

**Comment by badshah400** [comment]
@andreasb242 Thanks a lot for the quick fix and release. I have updated the package for openSUSE as well.
