### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#772]
Hi!
I got a problem while using Xournal++, I recently found out that when I open Xournal++ the zoom is centered way above the page and I cannot scroll down as the gif shows, if I mess with the zoom I get to move down, but then I'm not able to Zoom out, neither with panel button not with CTRL + scroll.
Right now I think the first part has something to do with the "Add vertical space" option, which I enabled.

![ezgif-4-cd9a40b50946](https://user-images.githubusercontent.com/38291180/51341678-2c29e000-1a92-11e9-925a-6d8c9e730fe0.gif)

**Comment by luco5826** [comment]
Ok I checked, the first part is related to the "Add vertical space" option, if I disable it I don't have that proble anymore, but the Zoom one persists, I don't even know if they're correlated

**Comment by GregDMeyer** [comment]
I have the same problem that I can't zoom out. Clicking zoom in or zoom out always zooms in. Even trying to pinch to zoom out still zooms in. Sometimes even just pressing save zooms in! and there is no way to zoom back out again.

**Comment by andreasb242** [comment]
You may compare the two files, they are textfiles / human readable!

**Comment by peetCreative** [comment]
@GregDMeyer have you found out sth in the files?

**Comment by GregDMeyer** [comment]
Sorry it took me a bit, I had diff'ed them a few days ago but I guess I had customized a lot of settings because the diff was like the whole file ;)

It turns out the culprit is "Presentation Mode". When I turn it on, zooming is broken; when I turn it off, it works again. (The settings file stores an attribute for presentation mode, so that's why it was persistent between restarts). So the easy fix to get zoom working again is to turn off presentation mode!

**Comment by peetCreative** [comment]
OK, so this issue is related to #671.
Anyhow in Presentationmode Zoom should be disabled.

**Comment by GregDMeyer** [comment]
Sounds good. Should this issue be closed then as a duplicate?

**Comment by andreasb242** [comment]
As this is a really specific issue: Let it open. There are anyway to many issues open again ;-)

**Comment by LittleHuba** [comment]
Zomming is now completely broken. We need to rewrite it to handle the new columnized layouts and handle pages with different sizes in a better way.

**Comment by peetCreative** [comment]
@LittleHuba What do you mean? For me it's not exactly zooming to the right position but roughly it works.

**Comment by peetCreative** [comment]
Btw. what is the expected behavior for Rows/Colums layout for presentation mode?

**Comment by andreasb242** [comment]
Maybe we should switch to 1 row on presentation mode?
I think only one page should be displayed.

**Comment by LittleHuba** [comment]
@peetCreative create a second page with a different width than the first page and try zooming in the presentation mode. 
But you might have fixed the issue with your changes. Have not tested them yet.

**Comment by LittleHuba** [comment]
@peetCreative create a second page with a different width than the first page and try zooming in the presentation mode. 
But you might have fixed the issue with your changes. Have not tested them yet.

**Comment by peetCreative** [comment]
OK, this is due to that Zoom is not supposed to work with Presentationmode. So we might remove presentation mode?

**Comment by LittleHuba** [comment]
In essence presentation mode should zoom-fit the page with the largest width and then disable zoom entirely. That is at least how I understand this visualisation mode.

**Comment by peetCreative** [comment]
mh... I would rather implement it like, zoom-fit width and height, replace scrolling with next/previous page, disable zoom
