### ISSUE TITLE
Better layer interface

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#78]
It would be very nice to have a layers interface to selectively show them in an individual form. The miniature bar can be used for this, with a layer tab. The dropbox in the bottom still choose the layer where writing go.

![xournal_shape_layer](https://f.cloud.github.com/assets/6414907/2284114/d238c670-9fc5-11e3-9b53-6675ef272376.png)

A great plus would be to have two selecting flags, one for visibility and the other one for choosing which layer are involved in selection/cut/copy and paste.

**Comment by andreasb242** [comment]
![xournalpp-layer](https://cloud.githubusercontent.com/assets/822958/7430211/c340fbec-f00f-11e4-8fcf-845329550196.png)

Working on this topic, layers are displayed, but hide / show, reordering etc. is not yet implemented, and it's not updates always.
