### ISSUE TITLE
Unable to record sound

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#784]
I am a Xournal++ user on ElementaryOS 5 (based off Ubuntu 18.04).
After following the instructions by the letter, and having set VLC Web Interface, single instance, and a folder to save the audio, I find myself unable to record anything. 
After pressing the Recording button, a system notification dialogue informs me that "Recording started with 35% gain", but that does not lead to any audio file being produced (neither being played back in the .xopp, nor saved in the designated folder).
I would be grateful if you could help me sort out where the issue is.

**Comment by morrolinux** [comment]
Hi! 
Which path have you set for audio recorded files under settings? 
Do you have `arecord` and `lame` both installed? are they your path? (e.g: what happens if you launch them from shell?)
The recording feature is baed on those commands, which I belive are not installed or working properly.

**Comment by edo0** [comment]
Thank you for the advice!. I was indeed missing the required "lame" package, which I would recommend to add to the readme at this point.

After installing lame I manage to record files (which found in the default saving folder, even though playing at very low volume - my system does not have a "/usr/local/bin/xopp-recording.sh" config file I can tweak). The same are not played with the "Play Object" tool.

Sorry to be abusing of your good will, and help. Hope other people might stumble upon this thread and find it of use

**Comment by morrolinux** [comment]
Definitely have to add `lame` to the readme requirements...
xopp-recording.sh it's not a config file but the recording script itself. 
It's surely somewhere in your PATH since you're using it. Try posting the output of `which xopp-recording.sh` here.
Play object calls VLC for audio playback, do you have this package installed? And have you made the required configuration on it like the readme describes?

**Comment by edo0** [comment]
No, VLC is not launched. 
After having recorded and simultaneously taken notes, when I press on text/images with the Play Object tool I get no visual or audio feedback of sort, no VLC window opens, it's just as if I didn't press anything, the hand-shaped pointer stands on the text without doing anything

**Comment by morrolinux** [comment]
Wait, this feature actually only works for handwritten text, no keyboard typing or images either!

**Comment by edo0** [comment]
That explains it. With handwritten text it does work flawlessly indeed !
Should I open an "enhancement" issue asking for a new feature to be added, for recording to be allowed together with the text inout function?
Grazie ancora for your help!

**Comment by morrolinux** [comment]
Yeah probably that's a good idea if you really need this, although at the actual state-of-the-art it would be not trivial to implement for "keyboard text" as each text field is being stored as a whole object, and having an audio track to be played just at the beginning of the text field isn't too useful (ideally you would need to lick on a specific typed word, right? we would need to redesign the text tool and save format for that, so I'm not sure)

**Comment by edo0** [comment]
Thank you very much for your reply.

In my very specific use case scenario, I make use of Xournal++ to add notes to PDF slides during class in university.

While possibly very useful for other contexts, in my specific case perfect matching between text and recorded audio would not be possible, and in case very inconvenient: I do not type at the same speed as the professor's speech, nor everything of what is said, and in case it would indeed be partly reworked and partly out of sync.

Furthermore, many different text boxes with short to medium length text are added, so that ideally would better correspond to breaks in audio: here a shortcut for start-stop recording, or even better an automatic stop/restart rec with new textbox mechanism [or object to time-tag mechanism, to keep a single recorded file and redirect to exact timing based on object played?] could prove very useful

**Comment by edo0** [comment]
Thank you very much, that would be great!

**Comment by andreasb242** [comment]
If I look e.g. at this sample:
http://portaudio.com/docs/v19-doxydocs/paex__record_8c_source.html

Looks really complicated, only to record / reply audio files.
If there is a library which allows easy recording / replay this would be an option, but the most libraries are really complicated like this, and this is much work...

**Comment by LittleHuba** [comment]
I'll take a look around and search for an appropriate library. O even wouldn't be averse to writing a wrapper so you can use it more easily.

**Comment by andreasb242** [comment]
@LittleHuba if you want to do it, you can use any library you want ;-) (it needs to be working and cross plattform)

**Comment by LittleHuba** [comment]
Just started a new issue #808 to reference it correctly

**Comment by LittleHuba** [comment]
This PR adds the requested linking between audio records and typed text.
