### ISSUE TITLE
Icon for  Show grid/Snap to grid

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#785]
https://drive.google.com/file/d/1Qs3Hdd11TXyFI5ej2MWxXDtnEPGeF63C/view?usp=sharing
I'm a math teacher. Can you add a _show grid_ icon? It would greatly help me to graphically represent geometric figures in space. The _MrWriter_ version would be ideal. Thanks!

**Comment by andreasb242** [comment]
@morrolinux What do you think, especially: Should we link it to the background, or should we do it independently?

**Comment by morrolinux** [comment]
Honestly, I think this feature is not needed as of now:
Grid snapping only makes sense when you use "graph" or "dotted" paper, which are easy to pick and apply for all pages when you edit, and can be defaulted back to "plain white" when finished. 
Or one could simply edit with "graph" paper and export to PDF with white plain background (like I do).

Given that grid size is not (yet) customizable, and even if it was, it would probably make sense for it to just follow the paper "graph" or "dotted" size (spacing), (maybe size/2 as a toggle) I wouldn't bother developing a feature in contrast with that concept

**Comment by andreasb242** [comment]
I'm currently working on the Glade UI integration.
We may should add scripting / plugins, for example here we only need to execute a few actions, like change background and change snap to grid, which all are UI Commands.

This is only an idea, It's not sure that it will be done. But there are more and more such requests, and it don't make sense to implement them all in core. But the user would have such a functionality...

**Comment by andreasb242** [comment]
I wrote a plugin which does this. Plugins will be available in a short time ;-)

**Comment by andreasb242** [comment]
You have to enable the Plugin "ToggleGrid" in the Plugin menu, for this you need to build with Lua, or may to wait until new packages / releases are available. It's only available in the Menu.
No Icon yet, at the moment plugins cannot provide icons, this will be done at a later time.

**Comment by masac** [comment]
Thanks!

**Comment by omennia** [comment]
Hello, 
I think this is a nice feature.
Although there's no icon for it, is it possible to have a shortcut set for this?
For exemple, the color cycle pluging has the Alt+C shortcut mapped to it.
Is there any way to map a shortcut to this plugin?
If so, how can it be done?

Thanks

**Comment by omennia** [comment]
I just realized you just need to add a parameter to a line of code.
It can be found (at least for me) in ~/.local/share/xournalpp/plugins/ToggleGrid

change the line:
`app.registerUi({["menu"] = "Toggle Grid Paper", ["callback"] = "toggleGridPaper"});
`
to:
`app.registerUi({["menu"] = "Toggle Grid Paper", ["callback"] = "toggleGridPaper", ["accelerator"] = "<Alt>k"});
`
And you should now have a mapping of this plugin to the shortcut Alt+k, which you can map to one of your tablet buttons. Simple and useful.

Hope it helps someone

**Comment by Ainson** [comment]
This is really nice, especially with the keyboard shortcut.

But do you think it's possible to have it work on other paper backgrounds?

I ask specifically because I use a bigger grid than the default in graph: https://github.com/xournalpp/xournalpp/issues/2137

The only variable I see for it is 'graph' in app.changeCurrentPageBackground("graph"); but won't connect to individual profiles in pagetemplate.ini AFAICS.
