### ISSUE TITLE
Big Cursor with yellow opaque circle 

### ISSUE THREAD

**Issue by JoergBitzer** [xournalpp/xournalpp#786]
Dear authors,
for screen-cast it would be great to have a "big cursor" with a yellow/red/whatever opaque circle. Since you overwrite the normal cursor-scheme DMZ-highlight is not working in Xournalpp. Joerg

**Comment by andreasb242** [comment]
@luco5826 Something for you?

Additional checkbox in the settings near the big cursor setting?

**Comment by luco5826** [comment]
Yeah! I could work on it! 
But i think that would be useless with something like highlighter, maybe we could make it available just for PenTool?

**Comment by andreasb242** [comment]
May @JoergBitzer can post an image of an example cursor, in another application?

**Comment by JoergBitzer** [comment]
I agree that this is only useful for the pen-tool. 
And an example:
https://askubuntu.com/questions/777896/how-do-i-highlight-my-mouse-pointer-while-screen-recording
The third answer has a nice short animated gif with a green halo. I like yellow or red more, but this is a matter of taste.

**Comment by luco5826** [comment]
No problem! I can work on that!
