### ISSUE TITLE
Text-tool doesn't work on Windows 7

### ISSUE THREAD

**Issue by ngbvol** [xournalpp/xournalpp#800]
No Text can be inserted via keyboard except the CR/LF-key

**Comment by andreasb242** [comment]
@morrolinux had the same on macOS, but it was not reproducible by me...
Probably the same issue...

**Comment by peetCreative** [comment]
I have under Windows 10 the problem as well.
Now I have to figure out how to compile and debug things. aaaahrg.

**Comment by LittleHuba** [comment]
A friend of mine has the same big on his laptop. I'll take a look the next time I see him and triage the issue.

**Comment by morrolinux** [comment]
A friend of mine has the same issue on Win10, I can do tests if needed

**Comment by LittleHuba** [comment]
Duplicate of #767
