### ISSUE TITLE
Quickmenu (right mouse button)

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#804]
https://drive.google.com/file/d/1yg0_Q7CNWRIl7L4Svb5HgdDt8TgJnNID/view?usp=sharing
In version 0.0.5 of the MrWriter program https://github.com/unruhschuh/MrWriter/releases , was added the option Quickmenu (right mouse button). Can this option be implemented in Xournalpp? Thanks!

**Comment by andreasb242** [comment]
The buttons in Xournal++ are configurable, so generally reserve the right button is no option.
The Toolbars are also customizeable, so for this a new config option is needed, and a new "Toolbar".

Possible for sure, but also not a high priority feature. Currently we get more feature requests / bugs than we can implement / fix.

**Comment by masac** [comment]
Thanks!

**Comment by JJones780** [comment]
This is done... see #1161 !
You can now assign `Floating Toolbox` in `Prefs->Mouse->Mouse Buttons`  or `Prefs->Stylus->Stylus Buttons`,
Also note the experimental feature in` Prefs->DrawingArea->Action on Tool Tap` which lets you call up the toolBox without a button (via quick tap - great for stylus - use button for other things). Please try it out.
Once assigned to a Stylus/Mouse button or Tool Tap, you can drag and drop tool items to the Floating Toolbox via the usual `View->Toolbars->Customize`
