### ISSUE TITLE
Points displayed later

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#805]
https://drive.google.com/file/d/1bxbqP93_U4azdqV3Jq5UlSP9ZtVKCV9g/view?usp=sharing
1. I use Linux Mint 19.1 Mate 64 bit. When I choose Journal-Paper background-Apply to all pages then Xournalpp crashes.
2. When I try to write the sign of divisibility, sometimes the points are displayed late.

**Comment by LittleHuba** [comment]
@masac please check if issue 2 is still present. I think it is related to issue #684 as there the dots also appeared late. Maybe the fix for this issue also solved yours. If not we can triage it some more now.

**Comment by masac** [comment]
https://drive.google.com/file/d/1tcnbeFB051O2Q64ymjZY-u27XeDFkz6G/view?usp=sharing
Unfortunately, this bug has not been fixed.

**Comment by LittleHuba** [comment]
That is unfortunate.
Are you by chance touching the screen with your hand while drawing those points?

**Comment by masac** [comment]
No.

**Comment by LittleHuba** [comment]
I think I found the problem. Xournal++ takes some time for input events that do not move the pen inbetween the up and down events. I'll try to find the bug in the code and push a fix.

**Comment by andreasb242** [comment]
@LittleHuba Notify me, if you find it. I had a bug on macOS which I could not really reproduce, but this may also fixes this.

**Comment by LittleHuba** [comment]
@masac Please check that the bug is really fixed. Reopen if it is not the case.

**Comment by masac** [comment]
https://drive.google.com/file/d/1tcnbeFB051O2Q64ymjZY-u27XeDFkz6G/view?usp=sharing
Same problem!

**Comment by LittleHuba** [comment]
Please build manually with the following flags and send me another video. 

```
-DDEBUG_SHOW_PAINT_BOUNDS=ON -DDEBUG_SHOW_REPAINT_BOUNDS=ON
```

**Comment by masac** [comment]
I use deb http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu bionic main
Linux Mint 19.1 Mate 64 bits

**Comment by LittleHuba** [comment]
Then the supplied fix will not have reached your system yet. You'll either have to wait for the next release or build by hand. I'll close the issue for now and wait for you feedback when you have received the fix on your system.

**Comment by masac** [comment]
Solved! Thank you very much!
