### ISSUE TITLE
Clicking outside of a Textbox should create a new one

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#806]
When using the Text tool, clicking outside of the textbox simply deselects the one being edited, instead of straighforwardly creating a new one. Having to click twice to create a new textbox seems to me an undesirable behaviour. 
The same situation presents itself to the user who wants to switch from a currently being edited textbox to a previous one to change/correct the content (deselect and then select old textbox).

Would it be possible to change this behaviour, or make it configurable by the user?

**Comment by andreasb242** [comment]
Yes, this can be changed.
