### ISSUE TITLE
It would be nice if when snap to grid is selected, that moved objects would snap to grid.

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#807]
I'm creating slides for video lectures using xournalpp.  It is much nicer than xournal, which I used before, and getting much better all the time.  I often create a figure and then copy/paste it, and move the pasted object to a new location, for example when making schematic diagrams.  Then I modify the pasted figure.  I use snap to grid to make things line up nicely.  I have to be extremely careful when I move items to try and align them again on the grid or my modifications don't line up properly.

**Comment by andreasb242** [comment]
There was already a ticket to this topic, @morrolinux did a config option or something?

For me it's not clear whats the problem.

**Comment by morrolinux** [comment]
I think we're talking about a different thing @andreasb242 : he's talking about grid snapping for moving objects, not drawing.
I might have an idea on how to do this, but I'm busy with exams right now so I would do it in a couple of weeks or so I think...

**Comment by frohro** [comment]
It appears that the VerticalToolHandler needs fixed too, because when you have snap to grid selected, you want it to snap to grid too.

**Comment by rolandlo** [comment]
This has been fixed in #2011.
