### ISSUE TITLE
Use PortAudio for Recording and Playback of audio

### ISSUE THREAD

**Issue by LittleHuba** [xournalpp/xournalpp#808]
Switch to PortAudio library for audio handling

**Comment by LittleHuba** [comment]
@andreasb242 could you point out a few things for me?

- How can I include the recorded data into the xopp format? Is there a preference on how to do that or can I simple create my own tag?

Is there something else to keep in mind except that it has to wrk (obviously) and it is cross platform?

**Comment by andreasb242** [comment]
The Problem with the .xopp format is that it's an gzipped XML, which is a really bad start to put in an audio file. So I would currently still put it into a separate file, and keep the format as it is.

I would prefer to change the file format, but it's much work, and therefore I never did it. So for now I would stay at it and use an external file.

Instead of use a Library there would be also an option to integrate a tool which is better supported, e.g. a command line audio recorder / playback, add it as dependency.

I personal didn't look in details at audio recording, it's writte by @morrolinux .

VLC has also an API:
https://wiki.videolan.org/LibVLC/

If you have a good idea, or a sample (don't need to be fully working) post it here, before you do the full work, and the there is an issue (e.g. License, whatever).

I may missed some point, I was not prepared, and I didn't really expect that you really would do it ;-)
:+1:

**Comment by LittleHuba** [comment]
What new file format are you thinking of? It might influence my approach as I'd prepare the code for those changes.

What I would like to prevent is having a huge dependency on another tool like VLC. Even if a lot of people have it installed on their system, it is still awful if you only have to install it for using xournalpp.

Additionally PortAudio is not as hard to use as it seems, it's actually one of the easiest audio libraries out there. The whole wrapper will be around 200-300 lines for recording and playback. So I'll most likely stick with it instead of just using another tool ;-)

I'll work it into xournalpp since I don't want to do the same work twice. ;-) Xournalpp is actually well prepared for the changes required, as far as I have seen.

**Comment by morrolinux** [comment]
@LittleHuba that's great news! I had a look at PortAudio among the others few months ago, when I did the audio mapping stuff. I needed something to work with and I needed it quick (during lessons period) , so after a few trials went wrong I decided it was no option.
It's surely a good idea to incorporate this in xournalpp, and if you're familiar with it.. it probably won't take you as long, like you said. I'm looking forward to see your early changes as well

**Comment by LittleHuba** [comment]
Ahh using a zip container makes it easy for me. Then I'll stick with the audio file.

I'll separate my work into multiple PRs. I'll keep you posted on my progress, so you can tell me early on if anything does not match your expectations. ;-)

**Comment by andreasb242** [comment]
@LittleHuba Thank you! :-)

**Comment by LittleHuba** [comment]
Good news!
I got Portaudio running and recording in good quality. The audiofiles are written using libsox, which generates mp3-files.

The hard part was actually separating the generation of the audio samples from writing out the data. To get good audio quality I had to separate the two tasks into own threads, which use the consumer-producer pattern to exchange the data.

Playing the audio files will work in a very similar way and should not be that hard now. But before I implement that part, I'll clean up the code somewhat and provide you with the link to the files, so you can take a look.

**Comment by andreasb242** [comment]
Thank you!

**Comment by andreasb242** [comment]
@morrolinux what do you think? for me it looks good

**Comment by morrolinux** [comment]
Looks good!!

**Comment by sambhavsaggi** [comment]
When building from source, I get an error with CMake:

```
--   No package 'portaudiocpp' found
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  CMakeLists.txt:92 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

When I try installing PortAudio via `sudo apt install portaudio19-dev`, it will remove essential packages: 

```
kali-linux-all kali-linux-forensic kali-linux-full kali-linux-pwtools kali-linux-web libasound2-plugins:i386
  libjack-jackd2-0:i386 ollydbg regripper shellter sqldict veil wine-stable wine-stable-i386:i386 winehq-stable
  winetricks
```

and will render the following packages useless:

```
binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 fuseiso g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64
  gcc-mingw-w64 gcc-mingw-w64-base gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 i965-va-driver:i386 libaom0:i386
  libavcodec58:i386 libavresample4:i386 libavutil56:i386 libcodec2-0.8.1:i386 libcroco3:i386 libcrystalhd3:i386
  libdatrie1:i386 libfribidi0:i386 libgdk-pixbuf2.0-0:i386 libgomp1:i386 libgraphite2-3:i386 libharfbuzz0b:i386
  libieee1284-3:i386 libmono-microsoft-csharp4.0-cil libmp3lame0:i386 libnuma1:i386 libopenjp2-7:i386
  libpango-1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386 librsvg2-2:i386 librsvg2-common:i386
  libsamplerate0:i386 libsane:i386 libshine3:i386 libsnappy1v5:i386 libsoxr0:i386 libspeex1:i386
  libswresample3:i386 libthai0:i386 libtwolame0:i386 libva-drm2:i386 libva-x11-2:i386 libva2:i386
  libvdpau-va-gl1:i386 libvdpau1:i386 libvpx5:i386 libwavpack1:i386 libwebpmux3:i386 libx264-155:i386
  libx265-165:i386 libxcb-xfixes0:i386 libxvidcore4:i386 libzvbi0:i386 mesa-va-drivers:i386 mesa-vdpau-drivers:i386
  mingw-w64 mingw-w64-common mingw-w64-i686-dev mingw-w64-x86-64-dev mono-mcs va-driver-all:i386
  vdpau-driver-all:i386 wine-stable-amd64
```

**Comment by andreasb242** [comment]
@sambhavsaggi may the right package for you would be?
https://packages.debian.org/search?keywords=portaudio
>libportaudio-dev

Please open a new ticket for such issues, else we have two topics here. If it's working with libportaudio-dev, you can give us a feedback here, then we have to make sure this is written in the readme, else other users will have the same issue for sure...

Ubuntu PPA Build is working, Windows Build is nearly working, and macOS Build is not done yet.

**Comment by LittleHuba** [comment]
The problem of @sambhavsaggi is worrying, since it might mean that I need to rework everything to the C API of PortAudio. Only other way to fix that would be to provide the library packaged with Xournal++

Error handling needs to be improved. I'll fix that with the PR for playback. I have some issues with keeping devices selected over restarts of Xournal++ since the enumeration is not constant.

Switching to another audio format is no problem since I made it a point to separate the file access from the playback and recording. I'll take a look around for appropriate libraries.

**Comment by andreasb242** [comment]
>Error handling needs to be improved.

Mostly fixed, I could not reproduce a crash anymore.

The audioformat is only a licensing issue...

**Comment by andreasb242** [comment]
>The problem of @sambhavsaggi is worrying, since it might mean that I need to rework everything to the >C API of PortAudio. Only other way to fix that would be to provide the library packaged with Xournal++

I over read the comment...
Maybe it's simple the wrong library installed. On Windows I had to compile the library with a flag, that also the C++ wrapper are compiled. 

I searched again:
https://packages.debian.org/sid/i386/libportaudiocpp0/filelist
@sambhavsaggi For Debian probably libportaudiocpp needs to be installed!

I can't do everything at once, I'm currently looking at the macOS Build, which also needs changes as always if we do such stuff...

**Comment by LittleHuba** [comment]
Just sent the PR for the playback of the audio. This also includes the options in the settings dialog and fixes some issues with the reliability.

We are still missing the ability to seek within the file. I'll add this when we have decided for a final I/O-library.

What licensing issues do you see with MP3 since I could only find sources that say there is no licensing since 2007 anymore.

**Comment by LittleHuba** [comment]
I'll take a look at the opus libraries and add some producer and consumer classes so we can switch when I finished implementing them. The workflow is mostly the same so writing them shouldn't take that much effort.

**Comment by andreasb242** [comment]
Opus instead of SOX (and instead of MP3)?
So I stop spending time to get it built on macOS, and wait for your changes.

@morrolinux What do you think about opus?
It should be supported by VLC, so I think no problem...?

But I'm really not a specialist, I simple have now the build problems, and I'm currently not sure, may I also have broken the build with portaudio (I thought about it, but as it's not solved yet, I don't know it).

But technical it makes sense, if we can compile in a fixed codec, we don't have the issue with MP3 and all this stuff...

**Comment by LittleHuba** [comment]
Unfortunately I'm unable to use libopus directly since the necessary libaries are not yet spread widely enough (not even Ubuntu has all the packages). Thus I'm using libogg and libvorbis. But those are not as high-level as SOX and therefore implementation will take some time.

**Comment by morrolinux** [comment]
The situation seems very tough... Yeah opus could have been a reasonable candidate but according to @LittleHuba could be not the right moment for it..
