### ISSUE TITLE
Printed PDF is cut off slightly

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#81]
US size letter paper printed from a PDF cuts off the bottom by a few cm when printed directly from Xournalpp. Interestingly, a Print to PDF seems to produce a PDF that looks good but without shrinking/scaling, it cuts off as well.

**Comment by MarPiRK** [comment]
I had this kind of error previously too. Now it seems to be fixed (in my string_new) branch. I don't know why, but exported PDFs are not cut and moved.
Can you check if it's fixed for you too?

**Comment by wbrenna** [comment]
I think automake has a few quirks with zlib in this branch - I get 
```
  CXXLD    xournalpp
  /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libxml2.so: undefined reference to symbol 'gzclose'
  /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
```

Might be that the order of ```-lz``` is incorrect in the Makefile. I'll fiddle with this to see if I can fix it.

**Comment by andreasb242** [comment]
Exactly, the same, I also googled this, but didn't get it fixed yet.

**Comment by andreasb242** [comment]
I found the linker error in src/Makefile.am and fixed it.

**Comment by wbrenna** [comment]
Good catch - I just came across the same fix and it worked for me too.

**Comment by wbrenna** [comment]
To properly close this issue I'll want to test the branch a bit further since it originally only appeared with some PDFs.

**Comment by MarPiRK** [comment]
So, have you tested it by now?

**Comment by wbrenna** [comment]
Yes, this appears to be fine now.
