### ISSUE TITLE
Need to arrange when an object is behind of in front of another....

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#810]
I have found it nice to be able to draw objects on top of one another.  Sometimes I select the rear most object.  It then becomes the top object, and if it is bigger than the ones that were in front of it, it is very difficult to get them back in front.  We need something, like "Send selection to the back" so you can put it behind the other objects again.

**Comment by andreasb242** [comment]
Right, until then you can draw on two layers, you can select now the layer in the background for drawing, which fixes this issue for now...

**Comment by morrolinux** [comment]
@andreasb242 I'm afraid it doesn't:  You can draw on two layers, but the object you select gets brought on top even if it's a layer under the current one

**Comment by andreasb242** [comment]
But only as long as it's selected, when it's release it will be back on the background. The selected elements are always topmost.

**Comment by LittleHuba** [comment]
Just tested if this is really the case and unfortunately it does not seem to be.
When two strokes are on the same layer, selecting the one beneath the other will bring it to the foreground as expected. Unfortunately releasing it does not restore the original ordering of the strokes.

**Comment by Technius** [comment]
At the very least, we should implement the "Send to back/front" buttons first so users can fix the ordering if needed. Then we can look into why selection is messing up the order.
