### ISSUE TITLE
Windows: Build with Windows

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#815]
Hi I just try to fix some bugs only occuring on Windows. 
Does anyone has an idea or best practise to build on Windows?
Maybe we can put this than also here: https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md
Honestly my Internet atm is too slow to download things for Windows. :-(

**Comment by andreasb242** [comment]
You need to download stuff, you need GTK and Poppler etc.

What is missing? This manual schould work, at leas on Win 10...

**Comment by peetCreative** [comment]
OK... I got it now. Didn't expect pacman existing anywhere else then in arch.
