### ISSUE TITLE
File names conflict during PDF export if portion before first dot is identical

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#816]
Steps to reproduce:
1) Open  "Presentation 1.pdf"
2) Export as PDF in the same folder 
3) Naming it as "Presentation 1.***" or "Presentation 1.***.pdf", where *** can be any text with or without spaces (e.g. _"Presentation 1.w notes.pdf"_) will return the error: "Do not overwrite the background PDF! This will cause errors"
It is safe to assume that only the text before the first dot is considered to avoid naming conflicts purposes.
(for reference, the original Xournal did not present similar behaviour). This could be easily extended to text after the first dot and before the ".pdf" extension?

**Comment by edo0** [comment]
Addendum! 
When exporting as PDF, any character after the first dot is ignored "1.2.3.4.5.pdf" will be saved as "1.pdf"
Funnily enough, when saving a project as .xopp file, only the last character after dot and before extension is ignored (1.2.3 is saved as 1.2.xopp, 1.2.3.4.5.6.7 is saved as 1.2.3.4.5.6.xopp)

**Comment by luco5826** [comment]
Yes @andreasb242 !
I suspected this behaviour since the logic deletes any previous extension, but I'll have a look on it!

**Comment by andreasb242** [comment]
This is an easy one, I do it and then do a new release...
