### ISSUE TITLE
Selecting custom toolbar not persistent

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#818]
Upon opening Xournal++, previously selected (custom) toolbar is not selected any more. Instead, the toolbar on which the custom toolbar is based is selected. 

Steps to reproduce: 
1. View>Toolbar>Manage; create copy of (e.g.) Right hand Note Taking. Call it e.g. "TEST"
2. Select "TEST", then View>Toolbars>Customize to customize this, move some things around. 
3. Edit document & save document 
4. Close X++, reopen. Notice that under View>Toolbars "Right hand Note Taking" is selected again, instead of "TEST". 

May be related to #188 ?

ETA: latest master on linux

**Comment by andreasb242** [comment]
Yes, it's working now, so already fixed with #819 (your link to 188 is probably wrong ;-))
