### ISSUE TITLE
Can only create one custom toolbar from existing settings

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#819]
It seems I can only create one custom toolbar from an existing toolbar, and older custom toolbars are lost. 
Perhaps related to  #818 

Steps to reproduce:
1. Create custom toolbar by copying existing: View>Toolbar>Manage, select (e.g. "Portrait"), and click "Copy". Call it e.g. "Portrait2"
2. Create another custom toolbar by copying the same: View>Toolbar>Manage, select same as before and click "Copy". Call it e.g. "Portrait3"
3. Verify that under View>Toolbars both copies are visible. 
4. Close Xournal++, and re-open.
5. Verify under View>Toolbars that only Portrait3 remains, and Portrait2 has disappeared.

ETA: latest master on linux

**Comment by andreasb242** [comment]
Confirmed...  Hopefully an easy fix...
