### ISSUE TITLE
Strokes look different on canvas after release

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#82]
Maybe people can provide me with more details here. Certainly I have noticed Pango text is different - I believe that this is due to the rounding of font size to the DPI scale when the text box is unselected and becomes a xournalpp element. But I haven't seen this with strokes - on 64-bit systems the highlighter is not transparent while being drawn but I don't consider this to be a problem.

**Comment by andreasb242** [comment]
The main reason for this is a performance reason. To make the highlighter look right you need to draw them on a separate image and put them with alpha to the main image.
If you paint multiple times to the screen, then its getting less and less transparent.
So I decided to write it non transparent to the screen.
(Performance was tested on a single core CPU, no complete redrawing was needed, but today it should be possible to redraw always the whole document)

The difference with text while editing is less than in Xournal ;-)

**Comment by andreasb242** [comment]
Moved to GTK3 - and close because of age
