### ISSUE TITLE
Enable textbox double, triple click, to select word, line

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#841]
As per the title, I think it would be useful to introduce in the Text tool a functionality such as double clicking to select a full word, or triple clicking to select the whole line / whole content of the textbox.

**Comment by Technius** [comment]
This can be easily implemented after #1159 is merged.

**Comment by Technius** [comment]
Would it be more familiar for a triple click to select a line or select a paragraph? I'd like to know how people are using the text tool so I can implement triple clicks in the best way possible.

**Comment by edo0** [comment]
I do have to admit, after doing some research on the Internet myself, that triple click to select the whole paragraph (and not limiting to the sole line) seems to be the most useful and wide-spread general-purpose behaviour

**Comment by LittleHuba** [comment]
> I do have to admit, after doing some research on the Internet myself, that triple click to select the whole paragraph (and not limiting to the sole line) seems to be the most useful and wide-spread general-purpose behaviour

This also is one of the easier things to implement as selecting a paragraph means we can select everything between newline characters and do not need to go into any deeper questions like which word is still in this line and where is the linewrap.

**Comment by Technius** [comment]
@LittleHuba Unfortunately, GTK's idea of a "paragraph" is a newline. Currently, there's no text wrapping for text objects, so if we want to write something that looks like a paragraph, we have to insert newlines manually.

If we have a text object that displays
```plain
Example sentence on line 1.      <--- GTK thinks this is a paragraph.
Example sentence on line 2.      <--- GTK thinks this is a different paragraph, but it should be grouped with line 1.

Example sentence on line 3.      <--- This is indeed a different paragraph.
```
triple clicking either the 1st or 2nd should select both lines but not the 3rd line. Triple clicks on the 3rd line should only select line 3.

So what we want to do is look for double newlines. I've already updated the PR to account for this behavior.
