### ISSUE TITLE
Link fails: undefined reference to `std::__1::basic_ostream ...

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#844]
```
PlaceholderString.cpp:(.text+0x7b5): undefined reference to `std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<< <char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
```

Version 1.0.7
FreeBSD 11.2

**Comment by andreasb242** [comment]
I don't have FreeBSD installed, I'll check this on the weekend, if it's not fixed until then.

**Comment by LittleHuba** [comment]
Not an issue of our build scripts but the package you made. See issue #851 for further details on how to build.

**Comment by yurivict** [comment]
For the record, the problem is gone after the latest commits.

**Comment by yurivict** [comment]
This failure is still there. I don't see how does the port build deviate from your instructions.
It preforms a pretty straightforward build.

**Comment by LittleHuba** [comment]
It does not use the toolchain we use for building...

**Comment by LittleHuba** [comment]
Please use this toolchain. It makes your live easier.

**Comment by yurivict** [comment]
I use the same toolchain.

**Comment by yurivict** [comment]
Fix: https://github.com/xournalpp/xournalpp/pull/899
