### ISSUE TITLE
Please don't require portaudiocpp

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#845]
Repology can't find such package for any OS: https://repology.org/metapackages/?search=portaudiocpp

Also, graphics software shouldn't unconditionally require audio to be present.

1.0.7-117-g8f332420

**Comment by LittleHuba** [comment]
Please provide some more information on your system so we can provide the appropriate package in our Readme. 

An overall list of packages for PortAudio can be found here [https://pkgs.org/download/Portaudio](https://pkgs.org/download/Portaudio) 

Xournal++ is primarily a note taking application and no graphics application. Part of its features is recording and paying audio. For this feature it requires PortAudio. I do not think it would be of benefit to hide this feature behind a compiler flag.

**Comment by yurivict** [comment]
This link is dead: https://pkgs.org/download/Portaudio
My system is FreeBSD.
Portaudio only installs these files:
```
$ pkg info -l portaudio 
portaudio-19.6.0,1:
	/usr/local/include/pa_unix_oss.h
	/usr/local/include/portaudio.h
	/usr/local/lib/libportaudio.a
	/usr/local/lib/libportaudio.so
	/usr/local/lib/libportaudio.so.2
	/usr/local/lib/libportaudio.so.2.0.0
	/usr/local/libdata/pkgconfig/portaudio-2.0.pc
	/usr/local/share/doc/portaudio/README.txt
	/usr/local/share/doc/portaudio/index.html
	/usr/local/share/examples/portaudio/CMakeLists.txt
	/usr/local/share/examples/portaudio/pa_devs.c
	/usr/local/share/examples/portaudio/pa_fuzz.c
	/usr/local/share/examples/portaudio/paex_mono_asio_channel_select.c
	/usr/local/share/examples/portaudio/paex_ocean_shore.c
	/usr/local/share/examples/portaudio/paex_pink.c
	/usr/local/share/examples/portaudio/paex_read_write_wire.c
	/usr/local/share/examples/portaudio/paex_record.c
	/usr/local/share/examples/portaudio/paex_record_file.c
	/usr/local/share/examples/portaudio/paex_saw.c
	/usr/local/share/examples/portaudio/paex_sine.c
	/usr/local/share/examples/portaudio/paex_sine_c++.cpp
	/usr/local/share/examples/portaudio/paex_wmme_ac3.c
	/usr/local/share/examples/portaudio/paex_wmme_surround.c
	/usr/local/share/examples/portaudio/paex_write_sine.c
	/usr/local/share/examples/portaudio/paex_write_sine_nonint.c
	/usr/local/share/licenses/portaudio-19.6.0,1/LICENSE
	/usr/local/share/licenses/portaudio-19.6.0,1/MIT
	/usr/local/share/licenses/portaudio-19.6.0,1/catalog.mk
```

**Comment by andreasb242** [comment]
We definitive will find a solution for this.

**Comment by Rmano** [comment]
Although I think that audio recording is a great feature, `xournal++` is greatly useful even without it, so I really think that it should be optionally selectable. Porting to other architectures will be simplified, and a lot of us do not use the recording thing at all...  So my vote would be to let it configurable.

**Comment by andreasb242** [comment]
I currently think we should make it like it was before with the PDF stuff: Allow to use different implementations, like VLC as it was before or portaudio, and if portaudio is not available, it should be possible to compile without...

But I didn't expect that it's so hard to get the library to all platforms...

**Comment by Rmano** [comment]
...is that I still dream with an android port... ;-)

**Comment by andreasb242** [comment]
@Rmano Feel free to start with it :-) I currently do not even try, I know how much work it is. Libreoffice started at the base of the Firefox app, so may this would be a good code base...

**Comment by LittleHuba** [comment]
I've written the maintainer of the portaudio package to please include the C++-API. If he is unwilling we will take another route to solve this issue.

**Comment by LittleHuba** [comment]
portaudiocpp is now included in the FreeBSD package portaudio:
https://svnweb.freebsd.org/ports?view=revision&revision=492362
