### ISSUE TITLE
Making Flatpak package

### ISSUE THREAD

**Issue by Garbulix** [xournalpp/xournalpp#857]
Having cross-distro package would be very nice. Haven't you thought about making Flatpak package? 
I cannot do that at the moment, because I am still not good at this stuff (compiling, making packages...).

**Comment by andreasb242** [comment]
I'm against it, I think we should get to the offical repos, then also the update and all will be handled, or at least ppa. If possible also Windows Marked and Apple Store.

**Comment by Garbulix** [comment]
I don't believe that will work, sorry. 
There is a lot of "big" distros and maintaining packages in every repo will need manpower - I guess there is not enough people for that. 
For example - there is no xournalpp in any of Fedora's repo (official, rpmfusion or even copr). 
I know that xpp from official repo could be better integrated with system (theme for example), but looking after all the distros would be too hard. Also - xpp isn't an app that needs some privileges - it is just a notebook. I would understand if that was some kind of system app, like Timeshift or VS Code (which sometimes need an access to terminal). 
Also, one of the pros of having a Flatpak is that there is one, nicely maintained Flathub. More apps there the better - it just looks good for people-new-in-linux.

Sorry, you can see that I am huge Flatpak fan. I believe that containerization and centralization can be step forward in making Linux systems usable for "normal people".
Eventually - I would deal with no Flatpak (or even Snap) package if there was a package in my Fedora's repository (a little selfish, I know).

**Comment by andreasb242** [comment]
@Garbulix only flatpack fan or also developer?
> I cannot do that at the moment, because I am still not good at this stuff (compiling, making packages...).

I never used flatpack, and I do already the Windows and macOS Build, even if I'm not really using them.
If you whish to do it, no problem - we will help you, but I don't do it, and I don't think that one of the other developers would do it.

**Comment by Garbulix** [comment]
I think that my previous post might sound little impudent - sorry for that. You are doing great job.
> @Garbulix only flatpack fan or also developer?  
Shamefully - currently only a fan. 
I want to dive into Linux programming (I was an IT student once...) in the future.
I hope I will be able to make some Flatpak packages in the future and maintain them and spread "good news".

**Comment by andreasb242** [comment]
For this probably not even programming is required, or at least not much - usually you only need some commands, which may should be automated with a shellscript or so.

Did you build Xournal++ yourself? Then it also should not be that hard to create a package.
http://docs.flatpak.org/en/latest/first-build.html

For me this looks relative simple (yes I know, the details are always the problem):

>"build-commands": [
>                "make install"
>            ],

Try it out ;-)

**Comment by Garbulix** [comment]
No, I haven't built it, I've downloaded RPM from software openSUSE - https://software.opensuse.org/package/xournalpp?search_term=xournalpp  
Maybe the best way to learn Flatpak is to make one :D I will try!

**Comment by andreasb242** [comment]
That was the answer I would like to read ;-)

**Comment by ezickler** [comment]
I have a running flatpak. Thought it is also my first and as i'm also new to xournal++ i'm quit unsure if it is working properly. So consider it a alpha version. If any one is interested i can also make a PR for it. 

```
{
    "app-id": "com.github.xournalpp.xournalpp",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.30",
    "sdk": "org.gnome.Sdk",
    "command": "xournalpp",
    "rename-icon": "xournalpp",
    "rename-desktop-file": "xournalpp.desktop",
    "rename-appdata-file": "xournalpp.xml",
    "finish-args": [
        /* X11 + XShm access */
        "--share=ipc", "--socket=x11",
        /* Wayland access */
        "--socket=wayland",
        /* Needs to save files locally */
        "--filesystem=xdg-documents",
        "--socket=pulseaudio",
        /* Allow dconf */
        "--filesystem=xdg-run/dconf",
        "--filesystem=~/.config/dconf:ro",
        "--talk-name=ca.desrt.dconf",
        "--env=DCONF_USER_CONFIG_DIR=.config/dconf",

        "--system-talk-name=org.freedesktop.portal.Settings"
    ],
    "build-options" : {
    },
    "cleanup": [
    	"/include",
        "/lib/pkgconfig",
        "/man",
        "/share/doc",
        "/share/gtk-doc",
        "/share/man",
        "/share/pkgconfig",
        "*.la",
        "*.a"
    ],
    "modules": [
        {
   	    "name": "poppler",
            "buildsystem": "cmake-ninja",
            "config-opts": [
                "-DCMAKE_INSTALL_LIBDIR=/app/lib",
                "-DCMAKE_INSTALL_INCLUDEDIR=/app/include",
                "-DENABLE_LIBOPENJPEG=none"
            ],
            "cleanup": [
                "/bin"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://poppler.freedesktop.org/poppler-0.69.0.tar.xz",
                    "sha256": "637ff943f805f304ff1da77ba2e7f1cbd675f474941fd8ae1e0fc01a5b45a3f9"
                }
            ]
		},
		{
			"name": "libportaudiocpp",
			"buildsystem": "autotools",
            "config-opts": [ "--enable-cxx" ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://git.assembla.com/portaudio.git",
                    "commit": "396fe4b6699ae929d3a685b3ef8a7e97396139a4"
                }
            ],
			"cleanup": [
				"/include",
				"/lib/*.a",
				"/lib/*.la",
				"/lib/pkgconfig",
				"/man",
				"/share/aclocal",
				"/share/doc",
				"/share/gtk-doc",
				"/share/man",
				"/share/pkgconfig"
			]
		},
        {
            "name": "sox",
            "buildsystem": "autotools",
            "config-opts": [ ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsox%2Ffiles%2Fsox%2F14.4.2%2Fsox-14.4.2.tar.gz%2Fdownload&ts=1549545438",
                    "sha256": "b45f598643ffbd8e363ff24d61166ccec4836fea6d3888881b8df53e3bb55f6c"

                }
            ]
        },
        {
            "name": "xournallpp",
            "buildsystem": "cmake-ninja",
            "config-opts": [ ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/xournalpp/xournalpp",
                    "commit": "4d28632b023c7efd17eb85e520cefbd681e7b8c7",
                    "tag": "1.0.7"
                }
            ]
        }

    ]


}
```

**Comment by andreasb242** [comment]
@ezickler Hey, thank you!

If you have time, create a pull request! Do a short manual to the Linux build, or to a new readme file, and I may create also a flatpak on the next release!

**Comment by LittleHuba** [comment]
sox is no requirement anymore. That would need to be changed to libsndfile for the flatpak to work.

**Comment by ezickler** [comment]
@LittleHuba  Thx. I will look into it. 

As for the dependencies there is one for latex as far as i can see. Latex seams to be a problem with flatpak as it would need bundling but would be pretty huge. I that a big problem or is it fine to have no latex in the flatpak release?

@andreasb242 I will try to come up with a PR worthy version. As far as i understood the flatpak thing there would be two options for flatpak releases. First so but the flatpak manifest in the repo and generate a flatpak every release, or let the CI do it (not sure how this works). 
The other common option is to provide the flatpak manifest to the flathub repo, where it would be distributed. This would result in an new git repo only for the manifest which would need to be updated to get the new release to flathub. 

I would start with the first option for some testsing.

**Comment by andreasb242** [comment]
>The other common option is to provide the flatpak manifest to the flathub repo, where it would be distributed.

Something like this is done for the Ubuntu PPA, we have the debian folder in the main repo - so we may also put the flatpak here.

For Latex you can leave it, it's searched on the path, if it's not there, a message is displayed.

**Comment by ezickler** [comment]
Thanks for merging the manifest. 

Would be great if some one could try this out with the flowing commands for some feedback.

```
flatpak-builder ./flatpak-build org.github.xournalpp.xournalpp.yaml --force-clean --repo=./repo 
flatpak build-bundle ./repo  xournalpp.flatpak com.github.xournalpp.xournalpp
```

**Comment by LittleHuba** [comment]
Can we close this?

**Comment by andreasb242** [comment]
I created also a shellscript in the root, but I did not yet release a build. But I think we close it.
