### ISSUE TITLE
Xournalpp won't open (tries to load then generates crash report)

### ISSUE THREAD

**Issue by C3lliot** [xournalpp/xournalpp#859]
I'm using Antergos Linux 4.20.7-arch1-1-ARCH x86_64 with KDE Plasma 5 desktop environment, and recently (in the last two weeks), Xournalpp won't open. It tries to load, and then stops, with no windows or error messages popping up. I only found out that a crash report was being generated each time by looking at .xsession-errors, where it says 

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  locale::facet::_S_create_c_locale name not valid'
> 
> ** (process:5254): WARNING **: 21:52:03.883: [Crash Handler] Crashed with signal 6
> 
> ** (process:5254): WARNING **: 21:52:03.885: [Crash Handler] Wrote crash log to: /home/[USER]/.config/xournalpp/errorlogs/errorlog.20190210-215203.log

with [USER] being my username. The errorlog generated is attached. I have the most recent version of Xournalpp from the AUR. 

[errorlog.20190210-215203.log](https://github.com/xournalpp/xournalpp/files/2849714/errorlog.20190210-215203.log)

**Comment by LittleHuba** [comment]
Can you tell us which locale you are using on your system?

**Comment by C3lliot** [comment]
If I run `locale` in terminal:


locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_GB.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=C
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by LittleHuba** [comment]
There is something very wrong with your OS. The error means that Xournal++ is unable to find a default locale. Also `locale`should never throw those errors, as there should definitely be a default locale available.

I merged a fix so Xournal++ is able to start even if the locale cannot be found, but missing the default locale can lead to further errors. I don't know how huge that impact is on Xournal++, but it could even render it unusable. No way to test it without crashing my system though...

As this is a bug within your OS setup we can't help in that regard.
