### ISSUE TITLE
Paste form clipboard can land outside of the viewport

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#877]
When you paste with CTFL-V, if you are zoomed in, the pasted material (I checked with images) can land outside of the viewport, which is quite disconcerting (I pasted 21 times the same images before noticing...) 

![recorded](https://user-images.githubusercontent.com/6414907/52734559-dd566400-2fc5-11e9-8a56-07938f6e80b2.gif)

**Comment by Rmano** [comment]
Somehow it is again here. Look at the gif here. 
1) select and ctrl-c (ok) 
2) ctrl-v is exactly superposed (ok if you know it; it should be better if it were pasted at the cursor position...)
3) scroll down, ctrl-v is **still** over the original selection, quite surprising... 


![copyandpaste](https://user-images.githubusercontent.com/6414907/55541747-df839780-56c5-11e9-8a91-d468eaa24fe5.gif)

**Comment by LittleHuba** [comment]
@JJones780 I think you fiddled with that method a few commits ago. Could you check this?

**Comment by lehmanju** [comment]
as this is probably related to my already fixed issue, i will work on this
