### ISSUE TITLE
relative path for pdf files

### ISSUE THREAD

**Issue by enricoar** [xournalpp/xournalpp#880]
It would be nice if relative pdf paths were allowed in xournalpp. This was possible in xournal and it is useful  if one moves a pdf with its .xoj file into a different directory

**Comment by Rmano** [comment]
Yes; I think that in `xournal`, moreover, if the file is not found at the absolute address, it is searched with a relative path (just using the last element of the pathname and searching in the local directory). Very useful.

**Comment by LittleHuba** [comment]
Ultimately Xournal++ will receive a file format that includes attached files within it. That will solve this issue finally. But until that is the case we can use the same approach as Xournal and just try to resolve the file in the local directory if it was not found under the absolute path

**Comment by Rmano** [comment]
> Ultimately Xournal++ will receive a file format that includes attached files within it. That will solve this issue finally. But until that is the case we can use the same approach as Xournal and just try to resolve the file in the local directory if it was not found under the absolute path

Notice that the external file is really useful sometimes. I often do handwritten correction/solution on a PDF with an exercise as background, and if I notice an error in the text, I can just change the background PDF file and reload, and all is well (if the change is not big). Also often I have two PDFs, one in Spanish and the other in English, and juggle things the same way ;-)...

**Comment by LittleHuba** [comment]
We would still allow you to change the pdf background using the GUI. So no worries, that should not break your workflow. It just simplifies moving and sharing .xopp files tremendously.

**Comment by LittleHuba** [comment]
> Yes; I think that in `xournal`, moreover, if the file is not found at the absolute address, it is searched with a relative path (just using the last element of the pathname and searching in the local directory). Very useful.

This algorithm of searching the file in the local directory if it was not found under the global path is already done in Xournal++. I'll close this ticket for that reason.

@enricoar If you think this is not what you require or wanted to express, please describe the way you think it should be and reopen the ticket.

**Comment by LittleHuba** [comment]
@Rmano to support your workflow in the future I just created the ticket #889. Feel free to add your suggestions there if there are any specific ones!

**Comment by enricoar** [comment]
Thanks a lot for the rapid reply. And thanks for your work. I'm a fan of xournal and xournalpp is an awesome extension!
@LittleHuba   I noticed that if the pdf file is not in the absolute address, it will be searched locally. 
However, if the (uncompressed) .xoj or .xopp file has just a filename without path, then it doesn't work (it did in xournal)
example
<background type="pdf" domain="absolute" filename=/path/file.pdf pageno="1ll"/>
WORKS

<background type="pdf" domain="absolute" filename=file.pdf pageno="1ll"/>
GIVES ERROR

It would be nice if also the second version would work, but it's not a big deal if it doesn't. I'am also happy as it is

**Comment by rolandlo** [comment]
Relative path (attach mode) has been fixed in PR #2106
