### ISSUE TITLE
Make color selectable why eraser is on

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#888]
When you choose a color, while the eraser is selected, the color should change accordingly and switch back to the pen. I happen to try this often, but then have to select the pen first in order to change the color

**Comment by andreasb242** [comment]
Yes I agree, the disabled colors are badly visible... I also do this from time to time ;-)

**Comment by cbm755** [comment]
As a long time xournal user, I'll just add that it behaves as @coldspark29 describes and I'll +1 this.

**Comment by coldspark29** [comment]
I see that it has been implemented and it works great. In my opinion the crossed out color indicators are not necessary. There is already an indicator for the eraser being selected and it just makes things messy
