### ISSUE TITLE
eraser cursor size doesn't always update

### ISSUE THREAD

**Issue by cbm755** [xournalpp/xournalpp#895]
Suppose toolbar is at top of window.

1.  Select the small eraser
2.  Zoom in and scroll a bit so the red edge of the paper isn't visible.
3.  Change to the large eraser.
4.  Move down to the paper: the eraser cursor is still small.

If zoomed out, the cursor update seems to trigger when it hits the red border (not carefully confirmed).

This is Fedora 29, Gnome desktop, experimenting with a mouse as no pen on this system.

I can try to figure out how to record a screencast if the above is unclear.

**Comment by luco5826** [comment]
Hi!
I was able to reproduce your issue, I'm trying to figure out the source of the problem since ANY size change doesn't change the cursor after a zoom action, I need to figure it out

**Comment by cbm755** [comment]
Maybe this is related to #875?

**Comment by luco5826** [comment]
I don't think so, because I noticed that when the bug occurs, if you zoom just a little, then the eraser's icon updates but otherwise it get stuck in the previous size.
It seems like the Zoom gesture somehow "blocks" the "eraser size changed" event and the cursor doesn't update

**Comment by cbm755** [comment]
Related in the sense of events generated when the cursor hits the "gutter" of the paper window (specifically the red "current-page" highlight).

I don't see how its related to zoom: maybe my steps to reproduce were not clear.   This can be reproduced without zooming, simply scroll the paper far enough the you can get from the toolbar into the paper without touching the red border.
