### ISSUE TITLE
accidently dragging toolbars moves window

### ISSUE THREAD

**Issue by cbm755** [xournalpp/xournalpp#896]
A fairly common feature in GTK3 is that menubars and toolbars are draggable to move the window (like titlebars traditionally).

But I played briefly with xournalpp (on a Win10 tablet) and several times I accidentally grabbed the window with my pen and moved it when trying to change tools.

At least on Windows without a mouse, it was not at all obvious how to get the window titlebar back onscreen!

Does GTK3 have a setting to disable this?

  * For vertical toolbars it really feels inappropriate to me.
  * At least on Gnome, the bottom toolbar isn't currently draggable.
  * For horizontal toolbars at the top of the screen, maybe its ok, no strong opinion yet.

**Comment by andreasb242** [comment]
I can confirm this on all Plattforms (except with older GTK3, on Ubuntu 16.04 it does not happen).
But with gtk3-demo there is the same behavior, so it's GTK.

I looked into the GTK Code:
The implementation which move the Window (for menu, but for Toolbar it will be probably the same):
>gtk_menu_scroll_to
```
  /* Scroll the menu: */
  if (gtk_widget_get_realized (widget))
    {
      gdk_window_move (priv->bin_window, 0, -offset);
      gdk_window_move_resize (priv->view_window, x, y, view_width, view_height);
    }
```

This can not be turn off. So Xournal++ can not do it. You have to ask for this on GTK or on Your distribution.
