### ISSUE TITLE
Memory leak - rectangle

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#90]
Closing an open document with a selected object leaks 1 rectangle. This isn't serious but can be fixed easily.

**Comment by wbrenna** [comment]
To replicate, save an xoj containing some strokes. Open that file, select them, and close. This remains even after the clearSelectionEndText() that's being called in close() now.

**Comment by andreasb242** [comment]
The problem is the RepaintWidgetHandler which is static in the .cpp file.
This needs to be fixed with threading. #93
