### ISSUE TITLE
Make colors configurable with only stylus input and option to add configured color bins to toolbar

### ISSUE THREAD

**Issue by jclsn** [xournalpp/xournalpp#901]
I think additional configurable color slots, that keep the colour, after you have selected a standard color, would be nice. A colour wheel would also be interesting

**Comment by andreasb242** [comment]
First: You can configure as many colors as you wish if you configure a custom toolbar.
Edit ~/.xournalpp/toolbar.ini
Add something like COLOR(0xababab)
(0xXXXXXX is a standard Color Code)

If you select the custom color (rectangular color button, not the round colors)
![grafik](https://user-images.githubusercontent.com/822958/52915054-b2268a00-32cf-11e9-8c9f-0c8854e9815d.png)
Press The "+" button, then you get a Color selection:

![grafik](https://user-images.githubusercontent.com/822958/52915073-e8fca000-32cf-11e9-8e11-e70da418b8f2.png)

If this is not enough, please explain in detail what you are missing, and reopen the ticket.

**Comment by coldspark29** [comment]
@andreasb242: Sorry, I haven't discovered this. Might also be because I use the application only with a stylus and I can't right-click the color bins. It is also a pity, that you have to go into the color configuration dialog to re-select the color. An option to add them to the main color bar would be nice. Also a "Configure color" button in the color configuration menu, to be able to configure them without a touchpad or mouse.

**Comment by coldspark29** [comment]
@andreasb242: Where can I reopen the ticket?

**Comment by LittleHuba** [comment]
> Also a "Configure color" button in the color configuration menu, to be able to configure them without a touchpad or mouse.

What do you mean with that? You can move the crosshairs with your stylus... There is no need for a touchpad or mouse to choose a custom color.

**Comment by coldspark29** [comment]
@LittleHuba: I find it rather counter-intuitive to right click on a color bin. I did not find the option until it was mentioned here. So I am suggesting a button to configure the colors. Apart form that I have issues with my stylus buttons and right-click doesn't work out of the box.

**Comment by GregDMeyer** [comment]
+1 to allowing to customize the colors in the main toolbar, so that it's not necessary to open up the color dialog in order to change the pen color

**Comment by LittleHuba** [comment]
We should add a section to the settings for this that allows to add a list of colors that are then available as buttons in the toolbar

**Comment by bhennion** [comment]
Customizable palettes are now available (see d669ad). Closing this ticket.
