### ISSUE TITLE
Page background style not saved until next session

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#902]
Page background for a new page is always ruled paper

**Comment by peetCreative** [comment]
It might be a nice feature to save the preferred background in config for new documents.

**Comment by andreasb242** [comment]
![grafik](https://user-images.githubusercontent.com/822958/52915137-b010fb00-32d0-11e9-8795-c9c0d389fb45.png)

![grafik](https://user-images.githubusercontent.com/822958/52915149-c7e87f00-32d0-11e9-974f-6662220e4cad.png)


If this is not working for you, reopen the ticket.

**Comment by coldspark29** [comment]
@andreasb242: Works. Thank you!

**Comment by LittleHuba** [comment]
@andreasb242 we should move this to the settings dialog since people will look for this functionality there.

**Comment by andreasb242** [comment]
Hmm... Not sure, if there is this question again - we can talk about this ;-)
