### ISSUE TITLE
Very small steps when zooming with Ctrl +/-

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#903]
Zooming with touch is fast and smooth, but the steps have to be increased for old fashioned Ctrl +/-

**Comment by peetCreative** [comment]
I would rather make it configurable. Because for exact steering this small steps are quite good.

**Comment by LittleHuba** [comment]
We could also add a graphical interface to change this, like other applications do:
![image](https://user-images.githubusercontent.com/10881589/52969096-72cf6a80-33af-11e9-8b34-37d262aac48f.png)

**Comment by coldspark29** [comment]
@peetCreative: For exact steering one would rather use Ctrl + Scroll Up/Down I beleive. In my opinion Ctrl+ should do this in steps of 10% as in browsers.

**Comment by peetCreative** [comment]
@LittleHuba Isn't there already a slider? How do you mean this?

**Comment by peetCreative** [comment]
@coldspark29 Yes, I can look to implement sth like this. But I think I have to evaluate the behaviour.

**Comment by coldspark29** [comment]
@peetCreative: I also just discovered something else I would like to have considering zooming. Sorry for all my enhancement request  :P #908 #909

**Comment by LittleHuba** [comment]
> @LittleHuba Isn't there already a slider? How do you mean this?

I checked and now there is... I'll observe if it dissapears once more since there definitely was none when I wrote that comment...
