### ISSUE TITLE
Option for direct scrolling behaviour with the touchpad

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#904]
The scrolling runs on after the touch if the hand is lifted from the touchpad abruptly. Some people may prefer a more direct feeling

**Comment by peetCreative** [comment]
Could you please give a more detailed description of the project? I can't reproduce problems, when scrolling with touchpad.

**Comment by LittleHuba** [comment]
He means that currently when one stops actively scrolling on the touchpad, the ScrollView does deaccelerate and stop. That is called smooth scrolling.

What he wants is direct scrolling or normal scrolling which stops the ScrollView when he stops actively scrolling on the touchpad. Thus he wants to make the deacceleration optional.

**Comment by LittleHuba** [comment]
@andreasb242 could this be realized with scripting? Since I don't think this is an enhancement that many people would use as it is rather special and against the common flow of development where all applications switch to smooth scrolling.

**Comment by andreasb242** [comment]
I don't think so.
I would also say, this is not a Xournal++ issue, when, then it's a GTK or driver issue, I don't think we can and we will change this.

But after a short search: Other People also don't like it. And it looks like it's configurable:
https://askubuntu.com/questions/903160/turn-off-smooth-scrolling-in-gtk3

@coldspark29 try this out. I hope this fixes it, else you need to ask GTK.

**Comment by coldspark29** [comment]
@andreasb242: Your mentioned solution doesn't fix it. This is the only application where I have smooth scrolling enabled btw. I have it turned off in my settings and doing so should have disable it for GTK3 as well.

**Comment by LittleHuba** [comment]
@coldspark29 also direct scrolling is possible if you stop the physical scroll move when your fingers are still on the touchpad. So this is something that does not really need a fix from our side.

**Comment by coldspark29** [comment]
@LittleHuba: I don't consider it something broken myself. I am just to this behavior by Okular for example. I like the smooth scrolling on touchscreen input. For the touchpad I would like to be more direct. So an overall GTK3 fix, would probably not satisfy me :)

**Comment by coldspark29** [comment]
Smooth scrolling has been deactivated for touchscreen input as well now, has it?
