### ISSUE TITLE
Add horizontal space is broken

### ISSUE THREAD

**Issue by nicjohnston** [xournalpp/xournalpp#906]
Hi,
I updated from ~v1.0.7 to 1.0.8, and the Add horizontal space option in preferences no longer changes the page view.
The first commit that breaks the functionality is c624c378b6a4e5ed85bf21c8657a18c6a29fc4bd, which appears to be part of the multilayout changes in #872.
Is there a new way to get extra space on the sides of pages or is this a bug?
Thanks,
Nic

**Comment by LittleHuba** [comment]
This is a bug from PR #872.

**Comment by andreasb242** [comment]
```
LayoutMapper::LayoutMapper
	// TODO: Use these again?
	bool verticalSpace = settings->getAddVerticalSpace();
	// TODO: Use these again?
	bool horizontalSpace = settings->getAddHorizontalSpace();
```

I overseen this in the Pull, but it should not be that hard to fix this. I'll do a short fix, I think I know where...

**Comment by andreasb242** [comment]
I added 150px if you select the checkbox. I used additional space because the pen does not work that good at the border.
@nicjohnston Does this work for you, or do you have another case where you need this?

**Comment by nicjohnston** [comment]
@andreasb242 Yes, it is working now.  Thank you very much for the rapid fix.

**Comment by asanakoy** [comment]
version 1.0.18.
When annotatiing PDF nothing changed after I added 600px of the horizontal space and set the checkbox.
Looks like ther bug is still there
