### ISSUE TITLE
Zoom in where the mouse pointer is 

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#908]
Zooming doesn't zoom further into the point where the mouse pointer (or fingers on a touchscreen) are located. In fact when you get very close the zooming shifts the focal point further to the right. In my opinion zooming should always zoom in on the point where your fingers or mouse are located, because that is the region you are interested in.

**Comment by peetCreative** [comment]
This is in my opinion a numerical problem for very big documents, because for zooming we storing the page absolute document location of the pointer, which causes problems when calculating the scroll after zoom.

**Comment by peetCreative** [comment]
I have to correct my self. The problem is rather, that scroll zoom is not a zoom sequence.

**Comment by coldspark29** [comment]
Is this fix already pushed? I don't see a great improvement. Apart from that zooming with finger pinch has a tremor effect.

**Comment by andreasb242** [comment]
You can change the speed in the settings now.
