### ISSUE TITLE
Make moving the page possible while zooming with the touchscreen

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#909]
Not a real problem, but a "nice to have". I would like to be able to shift the picture around while I am zooming and not have to lift my fingers, then shift and zoom in again.

**Comment by andreasb242** [comment]
Probably also a hard one, as this is handled by GTK...

**Comment by LittleHuba** [comment]
I'll check if we can handle this internally by ourselves as it will be impossible to get this in when GTK is handling the gesture. 

I'm currently rewriting major parts of the input handling anyways so I'll try my hand.

**Comment by LittleHuba** [comment]
@coldspark29 Could you please test #1146?

**Comment by coldspark29** [comment]
@LittleHuba How can I test it? I just recompiled Xournal++, but I don't see any changes. Is there a preview version?

**Comment by LittleHuba** [comment]
You will have to recompile using my fork and branch `fix_909`

**Comment by coldspark29** [comment]
Tested and works!
