### ISSUE TITLE
Zoomslider Scale marks are not shown

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#914]
Only for the toolbar layout Toolbar left the scalemarks for 100% is shown for every other not.

**Comment by andreasb242** [comment]
For me the mark is shown always, don't matter if horizontal or vertical.

**Comment by andreasb242** [comment]
@peetCreative Can you please add a screenshot?

**Comment by peetCreative** [comment]
Here you go:
![with_markers](https://user-images.githubusercontent.com/5854864/53297968-0b8e3c00-382f-11e9-8f67-25723b8a5886.png)
![without_markers](https://user-images.githubusercontent.com/5854864/53297974-1a74ee80-382f-11e9-805e-e4b893725ce9.png)
This is in Toolbar Left Mode. When going over the scale the following warning is thrown.
`(xournalpp:4413): Gtk-WARNING **: 12:20:09.359: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)`

**Comment by andreasb242** [comment]
I get the same warning, but the mark is still drawn.

**Comment by andreasb242** [comment]
Maybe a GTK Bug https://gitlab.gnome.org/GNOME/gtk/issues/746

**Comment by andreasb242** [comment]
Definitive a GTK bug, if the scales are removed, all the warnings are gone. I'll check the GTK Implementation.

**Comment by andreasb242** [comment]
gtk3-demo has no vertical Example, only horizontal.
@peetCreative If you whish to get this fixed you probably need to fill a GTK Bug.
We cannot fix it (except we write our own control - but this is probably not a good idea)
