### ISSUE TITLE
crashes on selecting "Edit / Preferences"

### ISSUE THREAD

**Issue by andreas-hirczy** [xournalpp/xournalpp#917]
Version 1.0.6-0 ~ 201902192026 crashes on Debian Stretch when selecting menu entry "Edit / Preferences". The slightly older version 1.0.6-0 ~ 201901281910 works as expected.

The error message is 
> xournalpp: symbol lookup error: xournalpp: undefined symbol: ZN9portaudio6System14DeviceIteratorneERKS1_

The system is Debian Stretch/amd64 with all updates as of 2019-02-21 applied; the binaries have been installed via APP for Ubuntu Xenial:

>ahi@faepop78 ~ $ apt policy xournalpp
xournalpp:
  Installed: 1.0.6-0 ~ 201902192026 ~ ubuntu16.04.1
  Candidate: 1.0.6-0 ~ 201902192026 ~ ubuntu16.04.1
  Version table:
 *** 1.0.6-0 ~ 201902192026 ~ ubuntu16.04.1 500
        500 http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.6-0 ~ 201901281910 ~ ubuntu16.04.1 500
        500 https://itp.tugraz.at/Comp/debian stretch/main amd64 Packages

**Comment by LittleHuba** [comment]
You are using the master branch for releases. It is not ensured that this branch is working after each commit. Please use the stable branch for that.

**Comment by LittleHuba** [comment]
Or even better: use the releases we provide.

**Comment by andreasb242** [comment]
This looks like a "linker" runtime error - this should NEVER happen, even not on the master.
This is probably not a programming error.

@andreas-hirczy Did you update and build again, right?
Can you delete your build folder, and cmake .. and make again? Does is still crash?

**Comment by LittleHuba** [comment]
This is a class from the PortAudio library. So maybe the linking between Xournal++ and PortAudio did not work correctly.

**Comment by Octogonapus** [comment]
I am experiencing this issue on release 1.0.16. I get this output when opening the preferences:
```
(xournalpp:3500): Gtk-WARNING **: 11:50:55.314: Could not load image 'pixmaps/xournalpp.svg': Failed to open file '/usr/bin/../share/xournalpp//ui/pixmaps/xournalpp.svg': No such file or directory
xournalpp: symbol lookup error: xournalpp: undefined symbol: _ZN9portaudio6System14DeviceIteratorneERKS1_
```
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by vjrj** [comment]
Same error here:
```
ldd /usr/bin/xournalpp | grep port
        libportaudiocpp.so.0 => /usr/lib/x86_64-linux-gnu/libportaudiocpp.so.0 (0x00007f692e4aa000)
        libportaudio.so.2 => /usr/lib/x86_64-linux-gnu/libportaudio.so.2 (0x00007f692e27b000)
```

```
ii  libportaudio2:amd64     19.6.0-1         amd64            Portable audio I/O - shared library
ii  libportaudiocpp0:amd64  19.6.0-1         amd64            Portable audio I/O C++ bindings - shared library
```

**Comment by Technius** [comment]
[Debian is generally incompatible with Ubuntu PPAs](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). If you are using Debian, you will either have to compile from source, use a Flatpak, or (if you are on Debian Buster) use a Debian binary provided on [the releases page](https://github.com/xournalpp/xournalpp/releases).

@vjrj What OS and Xournal++ version are you using?

**Comment by vjrj** [comment]
@Technius I'm using `1.0.16~git20191111.0716-c474` from Releases in `18.04.1-Ubuntu`. 

You recommend more using the ppa?

**Comment by Technius** [comment]
> @Technius I'm using `1.0.16~git20191111.0716-c474` from Releases in `18.04.1-Ubuntu`.
> 
> You recommend more using the ppa?

It looks like our official releases are still on Ubuntu 16.04, which we'll actually have to update. If you use/plan on using Xournal++ heavily, I would recommend using the Snap, using the Flatpak, or compiling from source (at least until we release `1.0.17`, after which you can just use the updated release). Otherwise, if you are willing to live with potential bugs/breakages, the PPA version of Xournal++ would be more convenient.

**Comment by vjrj** [comment]
@Technius using the PPA the preferences works as expected. Thanks!

**Comment by joanpau** [comment]
The error still occurs with release 1.0.17 downloaded from releases page and manually installed on debian.
```bash
$ apt show libportaudiocpp0 
Package: libportaudiocpp0
Version: 19.6.0-1
Priority: optional
Section: libs
Source: portaudio19
Maintainer: Debian VoIP Team <pkg-voip-maintainers@lists.alioth.debian.org>
```

**Comment by Technius** [comment]
> The error still occurs with release 1.0.17 downloaded from releases page and manually installed on debian.
> 
> ```shell
> $ apt show libportaudiocpp0 
> Package: libportaudiocpp0
> Version: 19.6.0-1
> Priority: optional
> Section: libs
> Source: portaudio19
> Maintainer: Debian VoIP Team <pkg-voip-maintainers@lists.alioth.debian.org>
> ```

What version of Debian are you using? The package that we have provided is only compatible with Debian Buster. If you are not using Buster, you compile from source or use the Flatpak instead.

**Comment by unhandyandy** [comment]
I'm getting the same error with v. 1.0.18 on Ubuntu 19.10.

**Comment by mikeshulman** [comment]
I also get this error with v1.0.18 installed from the Ubuntu .deb on the releases page, in Ubuntu 18.04 LTS.

**Comment by vjrj** [comment]
See my comment https://github.com/xournalpp/xournalpp/issues/917#issuecomment-578037606

**Comment by LittleHuba** [comment]
Any output in the console?

**Comment by mikeshulman** [comment]
I was worried about trying the PPA because it's advertised as unstable.  The AppImage works fine.  Are there no plans to release a .deb for newer versions of Ubuntu?

**Comment by unhandyandy** [comment]
I switched to the PPA version and the bug went away.
