### ISSUE TITLE
Remove gdk_threads_enter()

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#93]
Since Gtk3.6 gdk_threads_enter() has been deprecated along with gdk_threads_leave(). The focus should be to remove any direct gdk calls (including Cairo calls) from the secondary threads, and clean up the gdk_threads_*.

The recommendation appears to be that we use gdk_threads_add_idle() on all secondary threads. In addition the g_idle_add() and g_timeout_add() are apparently only safe when no code is gdk_threads_enter() dependent - therefore, these should be changed, at least for now, to gdk_threads_add_idle() etc.

**Comment by cass00** [comment]
Could you elaborate a bit more what actually has to be done. An example with the current code might be nice. 
If I grep for gdk_threads_enter() I get around 30 results. Would it be as easy as to replace them with the appropriate call, as described above and in [Gtk3 Threads](https://developer.gnome.org/gdk3/stable/gdk3-Threads.html)?

**Comment by wbrenna** [comment]
Is there a single appropriate replacement call? From what I remember on this, all gdk calls need to be done from the main thread now. The way to do that from secondary threads is, I think, to use ```gdk_threads_add_idle``` which means in each case when we need ```gdk_threads_enter```, we'd probably first need a function that performs the GDK/Cairo calls and then add that function to the idle queue.

In addition, I'm suspicious that not every ```gdk_threads_enter``` instance is needed, and that there may be some areas where such activity is needed but isn't implemented - I remember seeing parts of the code where it looked like this was called on the main thread, where I think it should do nothing but at worst could cause problems. The deadlocks on the gtk3 branch I'm pretty sure is sometimes caused by gdk calls on secondary threads since as I recall it happened during threaded activities like saving files, and was fixed by using the no-threads option.

**Comment by andreasb242** [comment]
>In addition, I'm suspicious that not every gdk_threads_enter instance is needed
Yes, possible
>and that there may be some areas where such activity is needed but isn't implemented
No, I don't think so. As I started writing the Code for Xournal++ I forgot some gdk_threads_enter, which nearly always ended in a complete frozen Desktop, only an X restart helped...

So I don't think there are places which are missing the synchronisation, but there are maybe more synchronisation than needed...

**Comment by wbrenna** [comment]
That's good to know - if a missing enter freezes X, then it must be deadlock due to some other issue.

**Comment by cass00** [comment]
Could you give me an example of how to freeze xournalpp? I removed every single call of `gdk_threads_enter()` and `gdk_threads_leave()`, compiled and done some basic operations (drawing,zooming and saving) in the program, however, xournalpp behaves normally and does not freeze. I checked with `noThreads` true and false. Am I missing some major point here?

**Comment by andreasb242** [comment]
You now have a GTK3 environment, so it's possible that this problem isn't reproducible any more with a current Linux Distribution.

The repaint is called from a scheduler thread, if I missed the this calls my complete desktop was frozen.

I had Gnome 2 with Ubuntu that time...

>Am I missing some major point here?
Yes, my information was from 2010 or 2009 and not tested any more since then ;-)
Sorry.

**Comment by cass00** [comment]
So what is the conclusion here? gdk_threads_enter() and gdk_threads_leave() can be removed and everything is fine? Have a look at commit cass00/xournalpp@038de7a78 if you want to test the "thread-free" version.

**Comment by andreasb242** [comment]
is duplicated by #286

**Comment by andreasb242** [comment]
> gdk_threads_enter has been deprecated since version 3.6 and should not be used in newly-written code.
> 
> All GDK and GTK+ calls should be made from the main thread

Therefore like in Swing or JavaFX all should be done in UI Thread. In C++ this is some work. I'll create a helper construct. But not now.
