### ISSUE TITLE
Key shortcut to enable/disable pressure sensitivity

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#943]
It would be very nice to have the possibility to enable/disable on the fly the pressure sensitivity, either with a widget and/or with a shortcut...

**Comment by coldspark29** [comment]
It would also be interesting to let the pressure sensor handle opacity instead of thickness

**Comment by schuhumi** [comment]
Both issues would be solved with this:

https://github.com/xournalpp/xournalpp/issues/1170

You could configure two similar drawing tools, one with a non-constant pressure curve and one where the curve is constantly 1. That issue also proposes a opacity curve in addition to the pressure curve.

**Comment by LittleHuba** [comment]
As mentioned by schuhumi this will be taken care of in #1170
