### ISSUE TITLE
Linux Appimage

### ISSUE THREAD

**Issue by CsatiZoltan** [xournalpp/xournalpp#944]
Packaging as an [Appimage](https://appimage.org/) under Linux would be useful.

**Comment by JJones780** [comment]
I agree... I'll play with this if I get the chance.  If anyone spots an AppImage example packaging script that looks close to what we'd need please comment here... the examples are found at: 
[https://github.com/AppImage/pkg2appimage/tree/master/recipes](https://github.com/AppImage/pkg2appimage/tree/master/recipes)

The above as well as other suggestions for building appImages (including Travis builds ) are here:
[https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages)

**Comment by TheAssassin** [comment]
The up-to-date source of information would be the [Packaging Guide](https://docs.appimage.org/packaging-guide/overview.html#packaging-from-source). Making an AppImage normally can be really simple, you already use CMake so you can utilize that and only have to run a few commands to bundle the dependencies and generate the AppImage afterwards.

Feel free to pass by in #appimage on Freenode where we can help you in making AppImages, there's a lot of AppImage creators around, and often the team can provide you with example scripts that you just have to adjust a little.

**Comment by TheAssassin** [comment]
I think this has been closed too early and should be reopened until there is an AppImage available for download.

**Comment by LittleHuba** [comment]
@TheAssassin please provide your input on #1448 as you have more experience with AppImages.
