### ISSUE TITLE
Input lag while using the eraser on surface pro

### ISSUE THREAD

**Issue by alexanderi96** [xournalpp/xournalpp#949]
The eraser results very laggy after long session of usage on my surface pro 2017

**Comment by andreasb242** [comment]
Which operating system are you using? Addional: X11, Wayland etc?

**Comment by alexanderi96** [comment]
Right now I'm using Ubuntu 18.10, the latest jakeday's surface kernel (4.19.23) and yes, I'm running under Wayland. Actually I must check if the problem persists with x11

**Comment by alexanderi96** [comment]
I can confirm that the problem persists under x11 as well (even if it is less evident)

**Comment by GregDMeyer** [comment]
I've noticed this as well, but only in HiDPI mode. Setting GDK_SCALE=1 I have no issue.

**Comment by LittleHuba** [comment]
Please provide a video of the problem. Maybe this will help to get to the actual problem. With the current description it can be anywhere in the whole stack.

**Comment by saengowp** [comment]
My stylus is also laggy under Wayland (but not X11). The first continuous stroke is responsive while the next stroke wouldn't be displayed until the pen is lifted. 

I resolved it by

- Use a mouse to move the cursor out of the Xournal++ window then use the stylus only inside the drawing page. This resolve the issue
- **OR** Change the preference to enable the new input system. This also resolve the issue.

**Environment**
- Hunion H420 Drawing Tablet
- Xournalpp 1.0.17
- WM: Sway (Wayland)
- OS: Arch Linux

**Comment by violoncelloCH** [comment]
I'm just checking the latest nightly build (xournalpp-1.1.0.dev-nightly.20210103-x86_64.AppImage) and I'm getting an Input lag also when using the new input system. However I only get the lag for the eraser and not while drawing. I can easily reproduce it in an empty document by drawing some parallel strokes and then trying to erase them. The more individual lines I cross with my eraser stroke, the longer it takes until the strokes actually disappear. (e.g. ~ 2 sec for erasing 25 lines). 
To be specific: this is when I do a fast eraser stroke and the lines all disappear at the same time after the delay. However when erasing with a slow stroke the lines disappear almost immediately and one by one.
I also need to mention that this only happens on Wayland not for X11.
I'm happy to provide further information; just let me know what could help debugging this.

**Comment by caleb-allen** [comment]
I'm on Wayland and I'm experiencing exactly what @violoncelloCH describes

**Comment by LittleHuba** [comment]
> To be specific: this is when I do a fast eraser stroke and the lines all disappear at the same time after the delay. However when erasing with a slow stroke the lines disappear almost immediately and one by one.

This sounds awfully like the number of points per line increases tremendously. This increases the number of intersection tests required to find the sections that must be erased from the lines. @violoncelloCH or @caleb-allen could one of you provide input logs of the same inputs for both Wayland and X11 sessions? Just by seeing the difference in the number of events, we could check if this is actually the case.

Another problem might be how the data is stored. Currently, items are stored in lists, which is not ideal for fast intersection tests. Something I wanted to change with the revamp of the rendering system.

**Comment by caleb-allen** [comment]
@LittleHuba unfortunately I don't have a working X11 installation at the moment

**Comment by violoncelloCH** [comment]
@LittleHuba I'll hopefully find some time this weekend to look into this. Is my assumption correct that I'll need to build Xournal++ from source in order to get those logs?
https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs
is this the procedure I should follow?

**Comment by bhennion** [comment]
PR #3532 has a new and improved eraser. @violoncelloCH @caleb-allen, could you try out the installer available in [this post](https://github.com/xournalpp/xournalpp/pull/3532#issuecomment-955772441) and tell me if the lag you experienced is still there?

**Comment by caleb-allen** [comment]
Hey @bhennion, happy to help!

I installed your branch from source to try it out with my machine. I made some drawings and then began testing the eraser, and I unfortunately saw a significant amount of lag.

I went to record this video (my apologies for the poor crop), and suddenly the performance of the eraser was extremely smooth. This looks great!! Much smoother than I have experienced before. Great work!

https://user-images.githubusercontent.com/3279748/139747661-993ff646-a70b-4521-91e7-996937a0e732.mp4

So, it seems that moving focus away from the Xournalpp window and back (as described by @saengowp) resolves an issue unrelated to your PR (maybe related to stylus input and wayland?). That aside, your new and improved eraser is buttery smooth.

I can't test this with X11 but I'd be interested to see if it resolves the lag @alexanderi96 mentions in https://github.com/xournalpp/xournalpp/issues/949#issuecomment-470886059

**Comment by bhennion** [comment]
@caleb-allen Thanks for testing!

As far as I can tell, most of the posts in this ticket have little to nothing to do with the eraser, right?
Most of them mention an input lag on Wayland, not really related to the eraser.
@caleb-allen Would you mind opening a dedicated ticket for this lag, with a clear title and description, and with a reference to this ticket?
