### ISSUE TITLE
macos10.12.6不兼容

### ISSUE THREAD

**Issue by kingxiaofire** [xournalpp/xournalpp#950]
![2019-03-01 11 21 32](https://user-images.githubusercontent.com/27213623/53614315-80d58480-3c14-11e9-95d1-75b4b717d651.png)

**Comment by kingxiaofire** [comment]
Incompatible with macos10.12.6，how can l fix this ?? with upgrade system ?

**Comment by sambhavsaggi** [comment]
Could you insert an English Translation?

**Comment by andreasb242** [comment]
I have to check, I built it on High Sierra I think.

**Comment by LittleHuba** [comment]
See #1413 for a solution
