### ISSUE TITLE
Crash on Startup, Archlinux

### ISSUE THREAD

**Issue by simonsimon006** [xournalpp/xournalpp#953]
After I installed xournal++ through the mentioned AUR package I could start it but after a reboot I crashes without showing a window. The console output is:

ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Datei oder Verzeichnis nicht gefunden)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Datei oder Verzeichnis nicht gefunden)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Datei oder Verzeichnis nicht gefunden)
attempt to connect to server failed

** (xournalpp:26530): WARNING **: 11:12:19.702: [Crash Handler] Crashed with signal 11

** (xournalpp:26530): WARNING **: 11:12:19.702: [Crash Handler] Wrote crash log to: /home/user/.config/xournalpp/errorlogs/errorlog.20190302-111219.log

** (xournalpp:26530): WARNING **: 11:12:19.763: Versuche ein Notfall-Speichern des aktuell geöffneten Dokuments…

** (xournalpp:26530): WARNING **: 11:12:19.763: Dokument erfolgreich nach "/home/user/.config/xournalpp/emergencysave.xopp" gespeichert.

and the content of the crashfile is:

Date: Fri Mar  1 11:31:28 2019
Error: signal 11
[bt]: (0) xournalpp(+0x18a366) [0x558154f52366]
[bt]: (1) /usr/lib/libc.so.6(+0x37e00) [0x7f1dc1420e00]
[bt]: (2) xournalpp(_ZN16ColorSelectImage8setStateE14ColorIconState+0xb) [0x558154f1a05b]
[bt]: (3) xournalpp(_ZN12AbstractItem19actionEnabledActionE10ActionTypeb+0x93) [0x558154f07f43]
[bt]: (4) xournalpp(_ZN13ActionHandler16fireEnableActionE10ActionTypeb+0xa8) [0x558154e579f8]
[bt]: (5) xournalpp(_ZN7Control11toolChangedEv+0xea) [0x558154e5d7fa]
[bt]: (6) xournalpp(_ZN7Control10selectToolE8ToolType+0x98) [0x558154e5c6a8]
[bt]: (7) xournalpp(_ZN7Control10initWindowEP10MainWindow+0xb9) [0x558154e60be9]
[bt]: (8) xournalpp(_ZN11XournalMain3runEiPPc+0x77d) [0x558154e7b7cd]
[bt]: (9) xournalpp(main+0x34) [0x558154e55354]
[bt]: (10) /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f1dc140d223]
[bt]: (11) xournalpp(_start+0x2e) [0x558154e5578e]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x18a6b0) [0x558154f526b0]
??:0
[bt] #2 /usr/lib/libc.so.6(+0x37e00) [0x7f1dc1420e00]
??:0
[bt] #3 xournalpp(_ZN16ColorSelectImage8setStateE14ColorIconState+0xb) [0x558154f1a05b]
??:0
[bt] #4 xournalpp(_ZN12AbstractItem19actionEnabledActionE10ActionTypeb+0x93) [0x558154f07f43]
??:0
[bt] #5 xournalpp(_ZN13ActionHandler16fireEnableActionE10ActionTypeb+0xa8) [0x558154e579f8]
??:0
[bt] #6 xournalpp(_ZN7Control11toolChangedEv+0xea) [0x558154e5d7fa]
??:0
[bt] #7 xournalpp(_ZN7Control10selectToolE8ToolType+0x98) [0x558154e5c6a8]
??:0
[bt] #8 xournalpp(_ZN7Control10initWindowEP10MainWindow+0xb9) [0x558154e60be9]
??:0
[bt] #9 xournalpp(_ZN11XournalMain3runEiPPc+0x77d) [0x558154e7b7cd]
??:0
[bt] #10 xournalpp(main+0x34) [0x558154e55354]
??:0
[bt] #11 /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f1dc140d223]
??:0
[bt] #12 xournalpp(_start+0x2e) [0x558154e5578e]
??:0

The bug happens on X11 as well as on wayland. Xournal starts fine.

**Comment by LittleHuba** [comment]
Do you have any special toolbar settings like a custom toolbar?

**Comment by simonsimon006** [comment]
I think so, I can't check in the application but I think I changed it to not appear.

**Comment by LittleHuba** [comment]
Thanks for reporting this, then it is actually not that hard to fix. I'll push a fix later in the evening.
