### ISSUE TITLE
Document stuck to left side

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#954]
The document is stuck to the left side. No matter where I zoom or scroll, it always stays there

![image](https://user-images.githubusercontent.com/19779511/53696372-9d192300-3dc6-11e9-8569-caa944bca858.png)

**Comment by LittleHuba** [comment]
Have you enabled the multi column layout by any chance?

**Comment by peetCreative** [comment]
Same to me. How could one deactivate multi column layout?

**Comment by LittleHuba** [comment]
Bug description: On deactivating the Pair Pages mode, the view of the pages is never centered. Even restarting Xournal++ does not help.

**Comment by coldspark29** [comment]
@LittleHuba Set Column is set to 1, if that is what you mean

**Comment by LittleHuba** [comment]
Yeah as described above and marked by the label, this is actually a bug and not a wrong setting of yours.

**Comment by JJones780** [comment]
Sorry I didn't notice this earlier. This is something I missed with the multi-column layout change. I'll fix it asap.
