### ISSUE TITLE
Recording feature presents acoustic artefacts

### ISSUE THREAD

**Issue by edo0** [xournalpp/xournalpp#957]
Everything works well, and I have to say that sensitivity of the mic is very good - allowing me to pick up a lecturer's speech, 3 metres far from me.
However, I couldn't but notice this shrill acoustic aberration (please listen to [this file](https://www.brogiolo.eu/nextcloud/s/HPWCWp89xJ4x6AH)), which can cause significant disturbance when the source of the sound is not high enough, forcing to increasing the volume.
Hopefully there will be a fix for this. Let me know if you need any further detail about my setup, Ubuntu-based distro on an Asus UX310UA-gl100t
Thank you!!

**Comment by LittleHuba** [comment]
Could you test with some other software to make sure the artefacts are not originating from your hardware? Do also turn up the recording gain very high (as you did with Xournal++). Did you turn up the gain on system level or in Xournal++?

Additional info I need:
- The audio chip your device uses
- Whether you have installed PulseAudio
- The device you selected within Xournal++ for recording
- The gain you apply to the recording (see preferences and/or system settings)

**Comment by LittleHuba** [comment]
Preferably use Audacity for the recording test as it uses the same library.

**Comment by edo0** [comment]
I confirm the issue was mostly related to an excessive gain setting for the internal microphone.
Lowering it results in much much better recording, in that those artefacts are lowered to a minimum (not as much as in Audacity on the same hardware, possibly due to additional filters/processing, but quite close indeed!!
Thank you very much for the advice. As for me, this query can be closed now

**Comment by LittleHuba** [comment]
Thanks for the feedback. Currently there is no plan to add filters and such things to the recording feature, but if you have further issues with the sound quality we can review this topic.
