### ISSUE TITLE
Copy and paste layers

### ISSUE THREAD

**Issue by enricoar** [xournalpp/xournalpp#963]
It would be useful to have the option to copy (or cut) and paste layers

**Comment by andreasb242** [comment]
![grafik](https://user-images.githubusercontent.com/822958/54074710-18327b80-4296-11e9-8491-e7d4ee00c46a.png)

Already possible.

**Comment by enricoar** [comment]
Ok thans sorry, I didn' notice it

**Comment by andreasb242** [comment]
No Problem
