### ISSUE TITLE
add vertical space

### ISSUE THREAD

**Issue by bela127** [xournalpp/xournalpp#964]
I have a Bug
in: settings -> Layout -> Select: add vertical space

only the first of multible pages gets the space all other pages stuck to the left 

I think #954 could be related

**Comment by GregDMeyer** [comment]
I believe it is related. I also find that the update that stuck the page to the left seemed to swap the "add vertical space" and "add horizontal space" options, and reduced the extra space for both. I can try to bisect and find the commit that made it happen

**Comment by LittleHuba** [comment]
I'm quite sure what commit caused the bug, as we changed the architecture behind the page layout quite recently. So no need for bisecting but thanks anyway.

@JJones780 as this was your PR would you mind fixing this bug? You know your way best around these changes.

**Comment by JJones780** [comment]
@LittleHuba 
Yes, Sorry, I had left it disconnected ( with some comments in my pull request that I haven't gotten back to completely yet ) as I wasn't sure what the purpose for the horizontal and vertical space preferences were.  Is it meant to allow the user to scroll all of the pages farther over for easier reach on a touchscreen?  Would it be beneficial to let the user specify the amount of offset in preferences or should it remain fixed and just a checkbox to enable?  I'll try to discover these answers for myself but would be happy to hear some history on these settings.

**Comment by LittleHuba** [comment]
This feature solves a problem older Wacom tablets have. They don't use active pens but magnetic resonance to determine the position of the stylus. That technique has the problem to not reliably work at the edges of the screen. 
We solve this by just moving the pages away from the border of the screen. It's not really necessary for users to set their own offset but you can add this if you want.

**Comment by JJones780** [comment]
@LittleHuba 
The pull request is up and should add back the expected functionality.
Thanks for the background info.

**Comment by JJones780** [comment]
This has been fixed with Pull Request #986 .

**Comment by GregDMeyer** [comment]
Thanks so much for the fix!!

One more comment--the amount of extra space seems to be smaller now. I'm not sure this is a big deal, but I was using this feature because it's more comfortable for me to write near the top of my display (so that my palm can rest comfortably on the flat lower part). I can't scroll the bottom of the page up to the top of the view any more. (Maybe allowing user adjustment of the amount of extra space would be a good solution).

Thanks again!
