### ISSUE TITLE
Zoom with mouse wheel unexpected behaviour

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#965]
The zoom behaviour with the mouse wheel + CTRL in Xournal++ is very un-intuitive, and throws me each time. I'm on Ubuntu, and most apps I use have a similar zoom with mousewheel "feel". Xournal is different in two ways:

1. Zoom direction is reversed: elsewhere, ctrl+wheel_down is zoom out, in X++ it's zoom in
2. The steps are very small. In Firefox, each scroll "click" is 10% zoom, in Evince it's 20%, but in X++ it is only 2%.

Ideally, X++ has similar behaviour to the other apps.

**Comment by andreasb242** [comment]
I think also the direction is wrong, but the steps are now configurable.

@peetCreative

**Comment by peetCreative** [comment]
Ok, I see, will make it configurable. And make it your way default.
