### ISSUE TITLE
Make color selectable all the time and switch back to drawing tool

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#968]
So there was good progress in making the colors selectable, when the eraser is selected. I realized just now that the same problem exists for the selection tool and all others that don't need color. So here is my suggestion to fix this: 

Group tools in two types: 1. Tools that apply color 2. Tools that don't apply color
Make colors selectable all the time and in case a color is selected while a non-color tool is selected, the selection goes back to the last tool that applies color. 

Okay this was a lot of select/ed/able/ion in one sentence, but I guess you know what I mean ;)

And can you get rid of the white bars, when the eraser is selected? I think they are really unnecessary

**Comment by andreasb242** [comment]
> the selection tool and all others that don't need color.
Selection tools supports color, as soon as you selected something which has a color, you can change the color.

With the eraser makes sense, because it's really hard coupled with pen, so it makes sense in the standard flow. But for the other tools definitive not.

It's now clear visible, that the color is disabled. So this is no issue anymore.

**Comment by coldspark29** [comment]
it makesvsense for the other tools as well, because it saves the user time. It is really annoying to always have to hit two buttons

**Comment by andreasb242** [comment]
Second opinion: @LittleHuba or @morrolinux , what do you think?

**Comment by LittleHuba** [comment]
I think we should not do that, as it will confuse users whether they can change the color of the current tool/selection or will switch back to another tool. 

Actually I think it would be better if we introduce something like per-tool-toolbars that show the options that are available for the currently selected tool and hide all other options. That would clean up the toolbar quite nicely and solve the current overflow of buttons and settings we have...

**Comment by coldspark29** [comment]
Well, in Xournal that never confused me, but if you are not willing to change it, I have to accept it. I like the idea with the per-tool-toolbars as well. Everything that supports a better workflow will be highly appreciated!

**Comment by LittleHuba** [comment]
You can open a new ticket for per-tool-toolbars. But it will take some time until we can add this as we are bogged down with other tickets and this needs a lot of work. (We have to think about user configurable toolbars and everything as well...)
