### ISSUE TITLE
Changing ruling colour

### ISSUE THREAD

**Issue by jeffreyantony** [xournalpp/xournalpp#971]
In the lined page template, the current line is having a blue colour. I would like to change the line colour to grey using an GUI option. Will this be feasible ? Or is this option already existing ?

Currently I changed the colour by directly editing the source code and compiling. But I think a menu option will be much better.

In the file "LineBackgroundPainter.cpp" inside the function "void LineBackgroundPainter::resetConfig()", I made the below change
this->foregroundColor1 = 0xC0C0C0; //0x40A0FF;

**Comment by LittleHuba** [comment]
There is currently no such functionality. 
It should be feasible but no promises on when we will implement this. We are somewhat swamped with new tickets currently.

**Comment by andreasb242** [comment]
@LittleHuba It's possible.
It's possible to change this with a template file. Or to change the page templates, which are loaded from a Textfile, see ui/pagetemplates.ini

you can add new entries, and you can configure all colors, e.g. the example at the end:
[XournalppRedTest]
name=Red dotted
name[de]=Rot gepunktet
format=dotted
config=f1=FF0000

You can also save such settings in the Page Template Dialog in Journal / Page Template.
Same syntax.
There is no menu option. I'll add this to the readme.

**Comment by andreasb242** [comment]
I'll add a menu entry for this, to help user to find this option. But probably a Text editor, not a fully UI Editor, because this will be really complicated....

**Comment by jeffreyantony** [comment]
I was requesting for a menu option so that people who are using the (pre)compiled versions can change.

I am not sure about editing the file "ui/pagetemplates.ini". Is this file available for all users ? I mean will this file be present if a Windows user had downloaded a exe file for this application ?

If you think adding GUI is not a good idea, then can you make this parameter loadable via template file ? In the Journal > PageTemplate option, there is an option to load a template. I think editing the template file and loading it is a much better option.

**Comment by andreasb242** [comment]
> I am not sure about editing the file "ui/pagetemplates.ini". Is this file available for all users ? I mean will this file be present if a Windows user had downloaded a exe file for this application ?

Yes.

> If you think adding GUI is not a good idea, then can you make this parameter loadable via template file ?

It should be, it uses the same syntax. But this will not add it to the menu.

I'll probably do a new menu entry.

**Comment by LittleHuba** [comment]
See #1344
