### ISSUE TITLE
feature request: hover cursor size

### ISSUE THREAD

**Issue by ea42gh** [xournalpp/xournalpp#974]
I find myself constantly hunting for the hovering cursor location:
it's a tiny dot, allowing precise positioning, but it gets lost easily.

Some way of locating where it is, or some way of changing its shape
might be useful

**Comment by andreasb242** [comment]
Please check "View" Tab in settings. Already there.

**Comment by ea42gh** [comment]
Great!
There does not appear to be such a setting in version 1.09 compiled march 9, 19?

**Comment by andreasb242** [comment]
This setting is a long time there, but we reorganized the settings, so it needs to be somewhere...

**Comment by ea42gh** [comment]
found it under edit/preferences.   Thank you!
