### ISSUE TITLE
Ctrl+G dialog is not usable

### ISSUE THREAD

**Issue by flyasky** [xournalpp/xournalpp#975]
I'm drawing over long pdf. When I try to go to any page by Ctrl+G dialog  it opens  first page in document.

**Comment by andreasb242** [comment]
I can not reproduce this - please try to describe the issue better. As long as we cannot reproduce this, we can not fix it...

**Comment by flyasky** [comment]
1. Open any page in document
2. Gtrl+G and put number of any other page
3. Press Enter
4. You moved on first page (if Ok button used it will moves right)

**Comment by andreasb242** [comment]
Ok, Enter is not working, but OK is. this was the Information I needed.

**Comment by Technius** [comment]
This was fixed by #1678.
