### ISSUE TITLE
Not visible icons

### ISSUE THREAD

**Issue by flyasky** [xournalpp/xournalpp#976]
![xournalpp_01](https://user-images.githubusercontent.com/213282/54086935-387a3d00-435f-11e9-8b22-a59a18d1c1ad.png)

Not all icons on toolbar drawed properly. 

![xournalpp_02](https://user-images.githubusercontent.com/213282/54087058-5b592100-4360-11e9-8af3-f1e1bf497623.png)

**Comment by andreasb242** [comment]
Do you have selected dark theme in the Settings / Tab "View"?

**Comment by flyasky** [comment]
No. When enabled other buttons became white:
![Screenshot from 2019-03-10 18-20-24](https://user-images.githubusercontent.com/213282/54087154-53e64780-4361-11e9-9757-640c7ceaaf1b.png)

**Comment by andreasb242** [comment]
This Icons are the standard GTK Icons, not the Xournal++ one.
The Xournal++ one are correct displayed.

So this is probably an issue from your system configuration. How are the Toolbars in other Applications? White Icons on dark background?

**Comment by LittleHuba** [comment]
Most likely you enabled some buggy theme for your system UI. I had this problem once and the easiest fix is to switch back to the standard theme. If that is not what you want, you have to check how to enable this theme in GTK applications. The developers of the theme normally have some instructions to do so.

**Comment by flyasky** [comment]
I use standard Adwaita theme. But it seems ok on Adwaita-dark...

**Comment by LittleHuba** [comment]
I assume you have bogged up the settings of GTK-applications for your theme. Normally this is specified in the system settings. Where exactly I don't know. From our side we can't do much so I'll close the ticket for now.

**Comment by yujki720-collab** [comment]
1. #6955
