### ISSUE TITLE
Pen not recognized in wayland

### ISSUE THREAD

**Issue by Scafir** [xournalpp/xournalpp#981]
I just installed xournalpp on the latest openSUSE tumbleweed (20190310) using kde on wayland. I am using a Surface-like machine (Lenovo Miix 720). The reported wacom device are Wacom HID 5099 Pen and Wacom HID 5099 Finger.
The pen input, while reported by libinput, is not recognized by xournalpp (= does not respond to it)

This problem could be linked to #980, as they appear on the exact same configuration

**Comment by LittleHuba** [comment]
Please provide the output of the following command (run as root): `libinput-list-devices`.

**Comment by Scafir** [comment]
Output of `sudo libinput list-devices`
<details>
  <summary>Click to expand</summary>

```
Device:           Power Button
Kernel:           /dev/input/event10
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event1
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event9
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Lid Switch
Kernel:           /dev/input/event8
Group:            4
Seat:             seat0, default
Capabilities:     switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           EasyCamera: EasyCamera
Kernel:           /dev/input/event16
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Chicony Lenovo MIIX 720
Kernel:           /dev/input/event2
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Chicony Lenovo MIIX 720 Consumer Control
Kernel:           /dev/input/event4
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Chicony Lenovo MIIX 720 Wireless Radio Control
Kernel:           /dev/input/event5
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Chicony Lenovo MIIX 720 Touchpad
Kernel:           /dev/input/event7
Group:            6
Seat:             seat0, default
Size:             85x56mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

</details>

```
Device:           Wacom HID 5099 Pen
Kernel:           /dev/input/event14
Group:            7
Seat:             seat0, default
Size:             254x169mm
Capabilities:     tablet 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   none
Rotation:         n/a

Device:           Wacom HID 5099 Finger
Kernel:           /dev/input/event15
Group:            7
Seat:             seat0, default
Size:             254x169mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
```

<details>
  <summary>Click to expand</summary>

```
Device:           Ideapad extra buttons
Kernel:           /dev/input/event13
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH Mic
Kernel:           /dev/input/event20
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH Headphone
Kernel:           /dev/input/event21
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=3
Kernel:           /dev/input/event22
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=7
Kernel:           /dev/input/event23
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=8
Kernel:           /dev/input/event24
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=9
Kernel:           /dev/input/event25
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=10
Kernel:           /dev/input/event26
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Intel Virtual Button driver
Kernel:           /dev/input/event11
Group:            10
Seat:             seat0, default
Capabilities:     keyboard switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Raw Set 2 keyboard
Kernel:           /dev/input/event0
Group:            11
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
```
</details>

**Comment by LittleHuba** [comment]
Do the devices work in `gtk-demo`?

**Comment by Scafir** [comment]
The pen is unfortunately not recognized there.
(There is no problem with the touch on either xournalpp or gtk3-demo)

**Comment by LittleHuba** [comment]
Is the pen recognized by the OS (non-gtk apps)?

**Comment by Scafir** [comment]
I guess that the answer is no. I have not found an app that recognized the pen, but I don't know if it is by design, as a mouse is not simulated by the system from the pen input (`libinput debug-events` reports correctly the pen)
On non-wayland kde, everythings works as one could expect and sway/weston also show the same problem

**Comment by LittleHuba** [comment]
If your pen is not even recognized by your OS, Xournal++ can not even see the pen. So we can't really help you there.
File a bug over at the libinput/openSUSE-guys which should be able to help you in that regard. After that is fixed we can reopen the bug if it persists.

**Comment by jaykijay** [comment]
Hi,
i got the same Problem, but the Pen is in fact recognized in e.g.  libinput debug-gui and id draws a line perfectly.
It even creates nice events in libinput like:
`vent14  TABLET_TOOL_PROXIMITY  +3.58s         164.60*/121.70* pressure: 0.00* pen (0, id 0) proximity-in      axes:p  btn:S
 event14  TABLET_TOOL_TIP   +3.59s              164.22*/121.33* pressure: 0.40* down
 event14  TABLET_TOOL_AXIS  +3.61s              164.22/121.33   pressure: 0.44*
 event14  TABLET_TOOL_AXIS  +3.61s              164.22/121.33   pressure: 0.49*
 event14  TABLET_TOOL_AXIS  +3.62s              164.22/121.33   pressure: 0.52*
 event14  TABLET_TOOL_AXIS  +3.63s              164.22/121.33   pressure: 0.55*
 event14  TABLET_TOOL_AXIS  +3.64s              164.22/121.33   pressure: 0.57*
 event14  TABLET_TOOL_AXIS  +3.64s              164.22/121.33   pressure: 0.59*
 event14  TABLET_TOOL_AXIS  +3.65s              164.22/121.33   pressure: 0.60*
 event14  TABLET_TOOL_AXIS  +3.66s              164.22/121.33   pressure: 0.61*
 event14  TABLET_TOOL_AXIS  +3.67s              164.22/121.33   pressure: 0.62*
 event14  TABLET_TOOL_AXIS  +3.67s              164.22/121.33   pressure: 0.63*
 event14  TABLET_TOOL_AXIS  +3.68s              164.22/121.33   pressure: 0.63*
 event14  TABLET_TOOL_AXIS  +3.69s              164.22/121.33   pressure: 0.64*
 event14  TABLET_TOOL_AXIS  +3.70s              164.22/121.33   pressure: 0.64*
 event14  TABLET_TOOL_AXIS  +3.71s              164.22/121.33   pressure: 0.64*
 event14  TABLET_TOOL_AXIS  +3.71s              164.22/121.33   pressure: 0.61*
 event14  TABLET_TOOL_AXIS  +3.72s              164.22/121.33   pressure: 0.59*
 event14  TABLET_TOOL_AXIS  +3.73s              164.22/121.33   pressure: 0.56*
 event14  TABLET_TOOL_AXIS  +3.73s              164.22/121.33   pressure: 0.17*
 event14  TABLET_TOOL_TIP   +3.75s              164.22/121.33   pressure: 0.00* up
 event14  TABLET_TOOL_PROXIMITY  +3.80s         164.22/121.33   pressure: 0.00  pen (0, id 0) proximity-out`

So.. how do i add it to xournalpp under wayland? It works fine under Xorg and it's the only thing thats blocking my switch to Wayland :(

here is lipinput list-devices btw:

`Device:           ELAN0732:00 04F3:262A
Kernel:           /dev/input/event13
Group:            8
Seat:             seat0, default
Size:             289x163mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           ELAN0732:00 04F3:262A
Kernel:           /dev/input/event14
Group:            8
Seat:             seat0, default
Size:             293x165mm
Capabilities:     tablet 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   none
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event15
Group:            10
Seat:             seat0, default
Size:             69x51mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           HP WMI hotkeys
Kernel:           /dev/input/event10
Group:            11
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HP Wireless hotkeys
Kernel:           /dev/input/event5
Group:            12
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HP Tilt Pen Mouse
Kernel:           /dev/input/event16
Group:            13
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           HP Tilt Pen Keyboard
Kernel:           /dev/input/event17
Group:            13
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a`

**Comment by Scafir** [comment]
I had the same thing. The problems comes from the interface between libinput and GTK, which is taken care of by the DE (so the people here cannot do anything :( ). But you can file a bug report directly to them.
What DE are you using? I found that the latest version of gnome works out well (on fedora at least)
