### ISSUE TITLE
Touchscreen device not listed

### ISSUE THREAD

**Issue by debdeepbh** [xournalpp/xournalpp#988]
First of all, great work on xournalpp! It looks amazing.

I am using Lenovo yoga 720 and I am unable to draw with the touchscreen. I noticed that in the drop-down list "Device" for touchscreen under the "Stylus" tab in "Preference", I do not see my touchscreen device listed. To clarify further, the device is listed in `xinput list` as `Wacom HID 50EE Finger touch`. But it is not listed in xournalpp "device" section for some reason, although I can scroll fine with the touchscreen inside xournalpp.

Is there any other way I can draw using the touchscreen?

A follow-up question, how to make the page aligned at the center? (I looked through the settings, but I can't seem to find an option for this. Sorry if it is somewhere obvious.)

**Comment by peetCreative** [comment]
What OS are you running? Have you tried using the GTK Touch/ Scroll workaround"? However you might run into another bug #980.

Towards your follow-up question: It's a bug #954 we are working on at the moment.

**Comment by debdeepbh** [comment]
I am running Xubuntu 18.10. I tried checking the box "GTK Touch/ Scroll workaround" but it just disables scrolling with touchscreen. The pointer still follows my touch (and doesn't draw) and the touch device still does not show up in the Device list.

**Comment by LittleHuba** [comment]
@andreasb242 I think you mentioned once that touchscreens never occur in that picker as they are handled differently?

**Comment by andreasb242** [comment]
Yes, right. The touch device will never be shown in the device list, as this is a device which is special handled with GTK.
Try the touch tab, there you can configure all touch related stuff.

You can also allow to draw with touch (needs some Workarounds, as GTK has hardcoded Scrolling assigned to it)
