### ISSUE TITLE
Filename not preserved when opening file

### ISSUE THREAD

**Issue by sm8ps** [xournalpp/xournalpp#990]
Good day everyone and thank you very much for your efforts with keeping Xournl(++) alive and kicking! I have been a long-time user of Xournal and only very recently switched to Xournal++. My experience so far has been quite overwhelming because it adds so much well appreciated functionality to good ole Xournal.
When I open a file either through the dialogue in Xournal++ or by double-clicking a .xopp-file, the document is opened as "Unsaved Document". This does not seem to be intended.
This happens with Xournal++ 1.0.9 on Ubuntu Linux 18.10. In a terminal, I see:
** (xournalpp:16676): WARNING **: 17:39:42.197: lastSavePath is not set!
** Message: 17:39:49.037: Dateiname: /home/stefan/temp/Test.xopp

**Comment by njtwiseman** [comment]
I am experiencing this as well on Manjaro 18.0.4

**Comment by LittleHuba** [comment]
Can reproduce the behaviour

**Comment by sm8ps** [comment]
I can confirm that this issue is resolved also here. Thanks a lot!
