### ISSUE TITLE
Autosave failure

### ISSUE THREAD

**Issue by sm8ps** [xournalpp/xournalpp#991]
I constantly get autosave errors saying (translation from German):
> Autosave failed with error: couldn't rename "PATH/.FILE.autosave.xopp" to "HOME/.xournalpp/autosave/25089-FILE.autosave.xopp"
where FILE is the filename without extension, PATH the path it has been saved under and HOME my home directory.
This happens with Xournal++ 1.0.9 on Ubuntu Linux 18.10. I successfully tried to manually perform the copy action with Xournal++ running. So it is not an issue of permissions.
I have been trying to reproduce the error in some more isolated scenarios but am not getting consistent results. Maybe there is a connection with #990?

**Comment by LittleHuba** [comment]
We are using the bash command `rename` internally. You may try copying the file with that command and check if that succeeds.

**Comment by sm8ps** [comment]
Sorry for the long delay! I did not use the specific device for a while first but now that I have used it for some days I do not see this error anymore. There have been quite some updates lately for xournalpp so maybe that did influence the behaviour or the errors were simply spurious. So I close this issue and thank the developers for their dedicated efforts. Much appreciated!

**Comment by CobaltSpace** [comment]
So, I am actually experiencing the same problem.  I'm not sure if this would help, but my full path looks like `"/home/username/foo.bar/folder 123/.file name.autosave.xopp"`.  I guess the points of interest include a folder name with a space, a folder name with a period, and the file name having a space.

This happens on Xournal++ 1.0.10 on Arch Linux.

**Comment by Technius** [comment]
Oh, I didn't see this before I submitted #1122. This should be fixed by #1123.

**Comment by Technius** [comment]
Can you guys test if #1123 fixes the issue?

**Comment by Technius** [comment]
I'm closing this because #1123 was merged and should presumably fix the issue. If the issue still persists, please reopen this issue.

**Comment by giampierosalvi** [comment]
Hi,
I am getting this problem with version 1.0.16 installed on Ubuntu 18.04 through snap.

Sometimes the program crashes completely without any error message.

I do not use filenames/paths that include spaces.

Details:
Version: 1.0.16
Git commit: 1429879c
Built on: Jan 24 20202, 21:22:59

**Comment by giampierosalvi** [comment]
Some additional information: it seems that the problem occurs only when the file is stored in the home directory (/home/<user>). This directory contains other "dot" files, that is files starting with ".". However, I do not see how this could be a problem because there are no other files with the same name (that is, the current file name with an appended "."). Hope this helps finding the issue.

**Comment by Technius** [comment]
> I am getting this problem with version 1.0.16 installed on Ubuntu 18.04 through snap.

Does this issue occur with the Flatpak?
