### ISSUE TITLE
Tabs for multiple instances

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#995]
I think it would be a very convenient feature to have multiple instances grouped in tabs. When I use Xournal++ in the lecture I usually have the lecture slides open in one instance and am taking notes in a second instance. Switching beetween both would be more convenient with tabs.

**Comment by LittleHuba** [comment]
Duplicate of #936

**Comment by peetCreative** [comment]
I wouldn't say so, because tabs for different open document is sth different than multiple view of same document next to another.

**Comment by LittleHuba** [comment]
See my comments in the other thread.Am 19.03.2019 17:21 schrieb peetCreative <notifications@github.com>:I wouldn't say so, because tabs for different open document is sth different than multiple view of same document next to another.

**Comment by peetCreative** [comment]
Ok I didn't followed the complete thread in #936. So let's keep issue open.
