### ISSUE TITLE
Performance issues with current playback implementation

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#996]
Hello, I came back to my lectures and noticed something using the object playback function:
on long audio tracks (>30mins) the longer the point on the track, the slower xournalpp will be to retrive and play that specific part, to the point where it becomes unusable.
For instance: if I were to play the 60th minute of my last lecture, xournalpp would hang with 100% cpu for serveral seconds before actually play that part, whereas if I play an object within the first few minutes being recorded, everything happens much more fast. 
Here's a quick video about it:
![Peek 19-03-2019 18-10](https://user-images.githubusercontent.com/20294254/54626957-8d5e3780-4a72-11e9-93ed-bba1af73612e.gif)
As you can see, the more I scroll down, the slower it gets. until I reach the next lecture on a new recording which play smoothly as it's just few minutes long

**Comment by LittleHuba** [comment]
I'll look into that. Would you mind providing such a long audio file? Then I don't have to record one on my own.

**Comment by morrolinux** [comment]
Yeah, sure: https://mega.nz/#!V0RTzSpD!h50q1g-SbmknsVKyDdMZZDwzRsjqwM6vk4UAdGBPDaA

**Comment by LittleHuba** [comment]
This issue relates to (this)[https://github.com/erikd/libsndfile/pull/457] PR of `libsndfile`, which is used to read audio files. Most likely you do not yet have a version of the library installed that includes this fix.
Either wait for this or update your libsndfile version manually and rebuild.
