### ISSUE TITLE
Eraser doesn't work with marker

### ISSUE THREAD

**Issue by jclsn** [xournalpp/xournalpp#997]
When I use the eraser on paint drawn with the marker, it rearranges the colour in a very strange way, instead of erasing it.

**Comment by LittleHuba** [comment]
Please provide a video or screenshot.

**Comment by coldspark29** [comment]
Before erasing:
![image](https://user-images.githubusercontent.com/19779511/54666960-80315f00-4aeb-11e9-916d-f1a30d92708c.png)

While erasing:
![image](https://user-images.githubusercontent.com/19779511/54666969-86274000-4aeb-11e9-9107-dc734c6ecaff.png)

After letting go of the eraser:
![image](https://user-images.githubusercontent.com/19779511/54666976-8a535d80-4aeb-11e9-8134-e858fad77a8f.png)

**Comment by masac** [comment]
https://drive.google.com/file/d/1mp4jXg66ZphWJN0f3P_cQIXqbd7zUBU6/view?usp=sharing

**Comment by eliasrg** [comment]
I am not familiar with the implementation details, but this seems like a difficult issue to fix directly, without completely losing the overlap behaviour of highlighter strokes:
![997-erase-marker-1](https://user-images.githubusercontent.com/7657466/55954560-41607600-5c5f-11e9-9387-261e5fecc674.png)
Whiteout seems to be the best tool for erasing parts of a highlighter stroke, but unfortunately it also whites out the background. Maybe that is worth changing?

**Comment by LittleHuba** [comment]
The bug is twofold:
- The rendering while erasing is broken
- The gap in the stroke created by the eraser is to small it should create a gap with the following rule:
All points of the stroke within a distance of `1/2 (eraserWidth + strokeWidth)` of the eraser path will be removed

**Comment by jvwowd** [comment]
@eliasrg  I have a concern about changing the whiteout as suggested. Maybe there is another way, but currently using whiteout is the only way I know how to remove part of a background PDF when annotating which I sometimes find useful.

For example, when taking notes for a lecture, it is sometimes useful to duplicate a page, and remove part of the background to show more work.

**Comment by eliasrg** [comment]
@jvwowd One way would be to use the pen with a white colour, enabling fill, and making sure to set "fill transparency" to 100% in Tools/Pen Options. It might even be more convenient than using whiteout!

**Comment by jvwowd** [comment]
@eliasrg Thanks for the suggestion. I have tried a similar approach using a white filled rectangle, but one issue with this is #810 causing me to not be able to see objects drawn later. Even if issue 810 is fixed, it would be nice to remove background content without having an additional object in the document.
